### ISSUE TITLE
bug in clipboard widget 

### ISSUE THREAD

**Issue by gsaga** [qtile/qtile#1000]
Line 108-9 in clipboard.py are:
`            # only clear if don't change don't apply in .5 seconds`
`            self.timeout_id = self.timeout_add(0.5, self.clear)`

Shouldn't it be 
`self.timeout_id = self.timeout_add(self.timeout, self.clear)`

Without it the clipboard content shows only for 0.5 seconds, no matter what is the value of timeout. Replacing 0.5 with self.timeout fixes this. Am I missing something here?

**Comment by flacjacket** [comment]
Yes, you are print, that should be fixed
