### ISSUE TITLE
Why screens is a list?

### ISSUE THREAD

**Issue by zhou13** [qtile/qtile#1003]
I am new to qtile and I am confused the fact that the `screens` variable in qtile config is a list.  If I have multiple monitors, how could I specify different bars/widgets to the particular screens? Does the order of the list matter, e.g., for left to right? In i3 I can use something like
````
tray_output DP1
````
or
````
workspace "$WS3" output eDP1
````
to specify the position of the tray and the default workspace(group) for each screen, where DP1 and eDP1 are the video port name.

**Comment by ramnes** [comment]
IIRC, the `screens` order matters and represents screens from left to right, and the bar will be on the first `Screen` you create by default.

That said, you still can add bars to screens directy, at instanciation: http://docs.qtile.org/en/latest/manual/config/screens.html

**Comment by zhou13** [comment]
````
def gen_screen(name):
    return Screen(
        bottom=bar.Bar(
            [
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Systray(),
                widget.TextBox(name),
                widget.Clock(font='Monospace', format='%Y-%m-%d %a %I:%M %p'),
            ],
            30,
        ),
    )


screens = [gen_screen("left"), gen_screen("middle"), gen_screen("right")]
````

Using the above code, the "left" label shows on my middle screen, "right" label shows on my left screen and "middle" label shows on my right screen.  It seems it also deals with the which screen is primary but I cannot find a rule.

Also, I still don't see how I can assign bars to screen using port name in the doc you referred.

**Comment by flacjacket** [comment]
The screens are resolved in the order that X gives them to us, see: https://github.com/qtile/qtile/blob/develop/libqtile/manager.py#L352

With two monitors, you can use the `--primary` flag when calling `xrandr` to set which is the first screen, I'm not sure what is the way to set the second vs the third monitors.

**Comment by flacjacket** [comment]
Closing this, if you still have questions, feel free to ask, either here, on the email list, or IRC

**Comment by zhou13** [comment]
Why this is closed?  The order of `screens` is confusing and there is still no explicit ways to specify the `Screen` to the screen I want in a multi-screen environment.
