### ISSUE TITLE
Reload configuration on SIGHUP

### ISSUE THREAD

**Issue by Matt-Deacalion** [qtile/qtile#1005]
I have a shell script that is executed on a uevent from udev. In this script, I have to restart Qtile. At the moment I'm accomplishing this with the following:

`echo restart | qshell -s /home/matt/.cache/qtile/qtilesocket.\:0.0 &> /dev/null`

This isn't ideal due to the hard coded qtilesocket path. Would it be ok to add the ability to either restart Qtile or reload the configuration file when Qtile receives a SIGHUP, adhering to the Unix convention?

**Comment by flacjacket** [comment]
That should be fine to add that functionality and pretty easy with the asyncio signal handlers [1]. In the interim, if you are using the default socket location, you don't need to call qshell with the socket name, also the `-c` flag can be used to pass in a command.

[1] https://docs.python.org/3/library/asyncio-eventloop.html#unix-signals

**Comment by ramnes** [comment]
Implemented in #2114

**Comment by ramnes** [comment]
Reverted in #2257 because of #2256.

**Comment by tych0** [comment]
I think it would be fine to use SIGUSR1 for this.
