### ISSUE TITLE
Disabling fullscreen bug

### ISSUE THREAD

**Issue by frostidaho** [qtile/qtile#1015]
Using xfce4-terminal I run into a bug where when fullscreen mode is enabled and then disabled the terminal is resized / placed as fast as possible.

The bug only happens if `auto_fullscreen = True` in the qtile config.

I'll post a video because the bug is difficult to describe.

**Comment by frostidaho** [comment]
Here's a video of the bug
https://youtu.be/RruN6QujPJk

**Comment by flacjacket** [comment]
Closed by #1016

**Comment by jwijenbergh** [comment]
This bug is yet again present on latest master. Just hold down the fullscreen key with `auto_fullscreen` and xfce-terminal and you will see it never stops getting out of the fullscreen off/on dance
