### ISSUE TITLE
window focus cycling (different for certain layouts)

### ISSUE THREAD

**Issue by dhannes** [qtile/qtile#1023]
Hi all,
I just stumbled about different behaviour for `cmd_next_window`, `cmd_prev_window` focus cycling of `libqtile.group._Group` for different layouts.

I am using `Key( [ 'mod4' ], 'Tab', lazy.group.next_window() )` in config.py of qtile 0.10.7.
Depending on the current Layout of the group not all windows are cycled or the cycling stops.

For example
- in _Columns_ layout only windows in the current column and floating windows are cycled.
- for _wmii_ the cycling stops at end of windows in layout. No floating windows are focused.
- other layouts enable the group to cycle through all managed windows. (although i did not consider all layouts yet)

If this behaviour is considered a defect, i am willing to fix it, according to comments on #972 i already found. This seem to require changes in `focus_next`, `focus_previous` of certain layouts.

**Comment by flacjacket** [comment]
You are right, this is a bug, the naming of the functions are just not perfect in describing their behavior, which has led to inconsistent implementation, and the testing isn't in place to make sure it is done correctly. Getting the fixes in would be a great help!

**Comment by dhannes** [comment]
I need discussion or suggestion on this topic:
Is `Group.cmd_next_window` and its reverse expected to cycle through _all_ windows in the current group, or just the visible ones?

Currently `Columns` and `Stack` layouts explicitly omit clients that are not on top of stack (not currently visible), thereas the `Max` layout cycles all clients.

Personally i would prefer to cycle all windows,
because i use other layout specific commands (or the mouse) to focus visible windows.

**Comment by flacjacket** [comment]
I'd agree, that it should cycle all the windows.

**Comment by flacjacket** [comment]
It looks like you handled this in #1030, closing this out. Thanks!
