### ISSUE TITLE
qtwebengine 5.8 and <select> 

### ISSUE THREAD

**Issue by Etn40ff** [qtile/qtile#1029]
Hi All,
It appears that qtwebengine 5.8 and qtile do not mix very well. Browser based on
qtwebengine 5.8 (I tested qutebrowser and qupzilla) create a window to manage
`<select>` tags in webpages but this window is not handled properly by qtile. 
This issue was not present with qtwebengine 5.6.

This is the output of xprop on such a window running outside of qtile:

    _NET_WM_USER_TIME(CARDINAL) = 0
    WM_TRANSIENT_FOR(WINDOW): window id # 0x200008
    _NET_WM_ICON_NAME(UTF8_STRING) =
    XdndAware(ATOM) = BITMAP
    WM_NAME(STRING) =
    _NET_WM_NAME(UTF8_STRING) = "QupZilla"
    _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
    _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
    _XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
    WM_CLIENT_LEADER(WINDOW): window id # 0x20000a
    WM_HINTS(WM_HINTS):
                    Client accepts input or input focus: False
                    Initial state is Normal State.
    _NET_WM_PID(CARDINAL) = 5032
    _NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 2097207
    WM_CLASS(STRING) = "qupzilla", "QupZilla"
    WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
    WM_NORMAL_HINTS(WM_SIZE_HINTS):
                    user specified location: 813, 274
                    user specified size: 59 by 70
                    window gravity: Static

To reproduce just visit
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select with a
qtwebengine 5.8 browser and try to open the "Volvo" menu.

**Comment by svnset** [comment]
Hey. I remember having this Issue as well. There is no qtile update or anything, but the issue is gone for me now. Tested with qutebrowser v0.10.1 and qt5-webengine 5.8.0-4
. So it might be a webengine bug?

**Comment by Etn40ff** [comment]
@svnset thanks for the hint! I think I traced the issue back to this patch:
https://github.com/qt/qtwebengine/commit/7e7dd262.patch
I am not on arch so I will have to build qtwebengine by hand in order to test it but I am pretty sure this is the culprit.

**Comment by Etn40ff** [comment]
Ok I can confirm that patching qtwebkit solves the issue.

**Comment by flacjacket** [comment]
Great, thanks for reporting back on this
