### ISSUE TITLE
Wlan widget broken. Percent keyword issue.

### ISSUE THREAD

**Issue by ExileOnAnIsle** [qtile/qtile#1032]
**Description:**
I am using the Built-in Widget "Wlan" in my config-file. The only two arguments passed to the widget are "format = '{percent:2.0%}' " respectively "format = '{percent:0.2}' " and "interface='wlo1' " (Interface name is definitely correct!). The wlan widget always displays "0%" when I am using "format = '{percent:2.0%}' " and "N/A" when I am using "format = '{percent:0.2}' ". I am using the python module pythonwifi.iwlibs which is imported in the wlan widget file "wlan.py". I do not have the module "iwlib" installed.

This issue may be related to the issue "Wlan widget broken. Interface issue.". [https://github.com/qtile/qtile/issues/1031](1031)

**Possible Cause:**
Here I assume the issue "Wlan widget broken. Interface issue." (see link above) has already been fixed.

The function "poll" within the class "Wlan" in the widget file "wlan.py" (folder: libqtile/widget/) contains a division of two integers "percent = ( quality / 70)" (see 'Code Block 1'). Because the integer variable "quality" is always smaller or equal 70, the integer variable "percent" is always 0 or 1. Therefore in case of using "format = '{percent:2.0%}' " the keyword percent is replaced by either 0 or 1. In case of using "format = '{percent:0.2}' ", invoking the command "format" (see 'Code Block 1') causes the error "ValueError: Precision not allowed in integer format specifier" since the keyword "percent" expects a variable of type float, not an integer. Thus the widget outputs "N/A".

**Code Block 1:**

```
def poll(self):
        try:
                essid, quality = get_status(self.interface)
                disconnected = essid is None
                if disconnected:
                        return self.disconnected_message
                return self.format.format(
                        essid=essid,
                        quality=quality,
                        percent=(quality / 70)
                )
        except EnvironmentError:
                logger.error(
                        '%s: Probably your wlan device is switched off or '
                        ' otherwise not present in your system.',
                        self.__class__.__name__)
```

**Proposed Solution:**

Replace "percent = (quality / 70)" in the function "poll" (see 'Code Block 1') by "percent = (quality / 70.0)".

**Comment by flacjacket** [comment]
Thanks for the detailed reports! Feel free to submit your own patches if you want.
