### ISSUE TITLE
obscure unicode characters in tasklist widget

### ISSUE THREAD

**Issue by frostidaho** [qtile/qtile#1035]
![printing these characters in the terminal](https://cloud.githubusercontent.com/assets/8061555/24673705/3ac39ce4-1947-11e7-81ce-0b9a4e42ba12.png)

The tasklist widget was recently changed and the window status symbols are now some uncommon unicode characters. It just shows up as a space with my fonts (dejavu sans iirc). It should probably default to using ascii characters and have it be a customizable option.

old code:
```python
elif w.maximized:		
    state = '[] '		
elif w.minimized:		
    state = '_ '		
elif w.floating:		
    state = 'V '
```

new code:
```python
elif window.minimized:
    state = '\U0001F5D5 '  # minimize character
elif window.maximized:
    state = '\U0001F5d6 '  # maximize character
elif window.floating:
    state = '\U0001F5D7 '  # overlap character
```

**Comment by flacjacket** [comment]
Fixed in #1036
