### ISSUE TITLE
Can't use asyncio event loop in widgets

### ISSUE THREAD

**Issue by infmagic2047** [qtile/qtile#1046]
I am creating a widget that uses asyncio to run some external command (with `asyncio.create_subprocess_exec`). It doesn't work, and raises the `RuntimeError("Cannot add child handler, the child watcher does not have a loop attached")` exception instead.

If my understanding of the code is correct, calling `set_event_loop` after `new_event_loop` should fix this issue, but I'm not sure whether it will cause other problems.

**Comment by frostidaho** [comment]
Do you need stdout or stderr from the program? If not you could just use `qtile.cmd_spawn()`.
You can also get at the underlying eventloop with `qtile._eventloop`, so you can call `qtile._eventloop.subprocess_exec`

**Comment by infmagic2047** [comment]
I need the stdout in this case, so I can't use `cmd_spawn()`.

Using `qtile._eventloop` explicitly won't help here. `subprocess_exec()` uses `asyncio.get_child_watcher()` internally, which uses the event loop set with `set_event_loop()`.

**Comment by ramnes** [comment]
Just got fixed by @tych0 , sorry it took so long!
