### ISSUE TITLE
Can't keybind python code

### ISSUE THREAD

**Issue by SimLeek** [qtile/qtile#1054]
the cmd_function argument used along with the Key object seems to no longer exist, which was used by many of the config examples in the qtile_examples repository. Currently, none of the examples that use python functions work correctly.

This isn't an issue in that repository, because I feel that deprecating those functions removes the main functionality I was looking for when I downloaded qtile. I know it's possible to do everything I need with external scripts or other built in qtile functions, but that defeats the purpose of using python for modifiability. I even tried subclassing the root command class, but that turned out to be way too much work.

**Comment by frostidaho** [comment]
Can you link to the examples you're talking about?

**Comment by SimLeek** [comment]
Of course.

[Here](https://github.com/qtile/qtile-examples/blob/master/emdete/config.py) is the script I based my config off of. The code at line 77 does nothing.

[This one](https://github.com/qtile/qtile-examples/blob/master/ramnes.py) works differently by using the lazy.function decorator, but it didn't work either. 

I'm using qtile on Ubuntu with version 0.10.7.

**Comment by SimLeek** [comment]
I just borrowed [tych0's example](https://github.com/qtile/qtile-examples/blob/master/tych0/config.py) and used it for my code, since it was the most recent:

`def toggle_mute():

    def f(qtile):
        get_state = subprocess.Popen(['amixer', 'sget', 'Master'], stdout=subprocess.PIPE)
        out, err = get_state.communicate()
        if '[off]' in out: #muted
            #  the unused speakers should be saved at 0%
            subprocess.call(['amixer', '-q', 'sset', 'Master', 'unmute'])
            subprocess.call(['amixer', '-q', 'sset', 'Headphones', 'unmute'])
            subprocess.call(['amixer', '-q', 'sset', 'Speaker', 'unmute'])
        else:
            # Here we only need to mute master
            subprocess.call(['amixer', '-q', 'sset', 'Master', 'mute'])
    return f

keys = [
...
Key([], "XF86AudioMute", lazy.function(toggle_mute())),
...
]
`

I tested the code inside f() with `echo -e "<the code>" | python` after adding `exit()` to the end, and that worked. I also changed XF86AudioMute to a key that I knew worked when running another command, and it just stopped that key from doing anything.

**Comment by dhannes** [comment]
Did you have a look in the logfile at `~/.local/share/qtile/qtile.log`?
For me the function is called (qtile 0.10.7, python 3.6.1), and the logfile reveals:
```
File "[...]libqtile/command.py", line 473, in cmd_function
     function(self, *args, **kwargs)
   File "/home/dirk/.config/qtile/config.py", line 38, in mute
      if b'[off]' in out: #muted
TypeError: a bytes-like object is required, not 'str'
```

**Comment by SimLeek** [comment]
Oh, interesting. That error doesn't happen when I enter the code in a terminal in Python 2, but it does happen in Python 3. I was pretty sure my qtile was built in python 2, but I guess I was wrong.

Well, it looks like I didn't have an actual bug. Sorry about that, and thanks for the help.
