### ISSUE TITLE
Bar with transparency redraw issue

### ISSUE THREAD

**Issue by ei-grad** [qtile/qtile#1059]
![2017-04-28-184049_3840x1080_scrot](https://cloud.githubusercontent.com/assets/78607/25536198/9644e4b6-2c42-11e7-8dda-002a620d82f3.png)

How to reproduce:

Add a `background=(0, 0, 0, 0)` option to bar.Bar in qtile config.

**Comment by frostidaho** [comment]
I looked into fixing this months ago, and have an _almost_ decent fix
![screenshot-20170428-141835](https://cloud.githubusercontent.com/assets/8061555/25541771/f68499a4-2c1d-11e7-9a4b-abfb2d42dca2.png)

Take a look at this [window_opacity2](https://github.com/frostidaho/qtile/tree/window_opacity2) branch. It's missing some of the code for getting the systray to work, but I can't find where I put that atm.

The patch does a few things:
* drawer.py - change the cairo drawing operations work with transparent windows
* Allow creating 32bit x-windows

The biggest issue remaining with getting everything to work is getting the systray right. IIRC it involves having to reparent x-windows with different color depths, and doing some hacks to make 24-bit windows appear transparent.

**Comment by elParaguayo** [comment]
#2513 merged. Closing.
