### ISSUE TITLE
Setting clipboard content from within qtile

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1079]
I'm trying to set clipboard content from within qtile using the following code

```        try:
            from Tkinter import Tk
        except ImportError:
            from tkinter import Tk
        r = Tk()
        r.withdraw()
        r.clipboard_clear()
        r.clipboard_append(selected)
        r.update() # now it stays on the clipboard after the window is closed
        r.destroy()
```

but this does not work from within qtile, how can I get this to work ?

**Comment by Terseus** [comment]
Looks like the problem may be in Python 3.4 or Tkinter itself, see [this Python bug](https://bugs.python.org/issue23760) and [this StackOverflow answer](https://stackoverflow.com/a/33703390/648661), looks like preserving the clipboard in Tkinter after destroying the window isn't very reliable, in what other WM have you tested that code and worked?

**Comment by jagguli** [comment]
I haven't tried it in any other wm. I tried the work around and it does not seem to work.
I'm using python2.7.
