### ISSUE TITLE
 Cannot Autostart

### ISSUE THREAD

**Issue by djrmarques** [qtile/qtile#1083]
Hi guys. For some reason I can't make that script run the **autostart.sh** script run at start. The script runs well when I run it individually but I don't think the startup hook script is calling it. I tried using **startup_once** but it dind't work as well.  

  #Startup Scripts 
   @hook.subscribe.startup
   def startup():
      home = os.path.expanduser('~')
      subprocess.call([home + '/.config/qtile/autostart.sh'])

I am running the **qtile-python3-git** that I installed from the AUR. 

Thank you!

**Comment by djrmarques** [comment]
So it started working after I changed the path /home/user/.config/qtile/autostart.sh

**Comment by flacjacket** [comment]
Are you saying it works when you explicitly put in `"/home/user/.config/qtile/autostart.sh"`, but not when you use the code you pasted originally?

**Comment by ep12** [comment]
I have a similar issue, will try the absolute path later on.

**Comment by ramnes** [comment]
Closing in favor of #1169.
