### ISSUE TITLE
Qtile on GNOME not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by farebord** [qtile/qtile#1087]
Hi, I'm trying to run Qtile on GNOME on Ubuntu 17.04 and it doesn't work. I get a black splash after login in and then go back to the display-manager again. I did all the steps required on the guide and qtile config is working just fine.

I did get a warning saying that DESKTOP_AUTOSTART_ID key doesn't exist, but I think it shouldn't be a problem.

Thanks.
Facundo.

**Comment by flacjacket** [comment]
Hi @farebord, do you have any output in `~/.local/share/qtile/qtile.log`? It is hard to tell if qtile is failing and how it is failing otherwise.

**Comment by mlq** [comment]
I had the same issue with Ubuntu 18.10 and the configuration proposed in the documentation. While the `qtile.log` showed no issues, the X log suggested that it cannot find `gnome-settings-daemon`. 

If you look at the default configuration of other GNOME sessions, those services have been renamed:

```
RequiredComponents=qtile;org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Clipboard;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gno    me.SettingsDaemon.Mouse;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.g    nome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;
```

**Comment by nicolas-pantel** [comment]
@ramnes 
I wondered why this issue was closed without the documentation being changed?

I ran in the same issue and spent hours finding this solution.
The documentation part:

`$ cat /usr/share/gnome-session/sessions/qtile.session`
`[GNOME Session]`
`Name=Qtile session`
`RequiredComponents=qtile;gnome-settings-daemon;`

may be changed, or even amended for concerned Ubuntu versions, by:

`$ cat /usr/share/gnome-session/sessions/qtile.session`
`[GNOME Session]`
`Name=Qtile session`
`RequiredComponents=qtile;org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Clipboard;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Mouse;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;`

**Comment by ramnes** [comment]
Hi @nicolas-pantel, thank you for this comment. I've closed the issue because an answer was given to OP, without any further comment. I didn't realize it needed a documentation update or anything else. Please feel free to open another issue or a PR directly!

**Comment by scratchmex** [comment]
I think this may be related. I followed all the instructions to install Qtile in Gnome (I'm in PopOS 19.10) and this error raises. When I login from gnome-session the start failed and digging in the logfiles:
```console
❯ journalctl SYSLOG_IDENTIFIER=gnome-session-binary -n 5
-- Logs begin at Sat 2019-10-26 16:56:36 CDT, end at Fri 2020-04-03 16:18:37 CST. --
Apr 03 16:01:35 pop-os gnome-session-binary[11495]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Clipboard'
Apr 03 16:01:35 pop-os gnome-session-binary[11495]: WARNING: Unable to find required component 'org.gnome.SettingsDaemon.Mouse'
Apr 03 16:01:35 pop-os gnome-session-binary[11495]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Apr 03 16:01:51 pop-os gnome-session-binary[11578]: WARNING: Error creating FIFO: File exists
Apr 03 16:01:52 pop-os gnome-session-binary[11662]: Entering running state
```

I really don't know what to do :/

**Comment by mlq** [comment]
Remove them from your RequiredComponents in the qtile gnome-session configuration.

In my configuration, it looks like:

```
[GNOME Session]
Name=qtile-gnome
RequiredComponents=org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;gnome-flashback;qtile-gnome;
```

**Comment by scratchmex** [comment]
Qtile now runs but as a little window and the super key trigger the gnome exposé. I think it runs but not as a wm, the key bindings don't work, only alt+enter

**Comment by mlq** [comment]
I am using a configuration based on https://github.com/i3-gnome/i3-gnome

**Comment by Ritbit1111** [comment]
I am on Ubuntu 18.04, installed qtile using apt, I have the same issue : When I try to login after a restart, I am thrown back to the same login window again. I have awesome wm installed which works fine. 
I don't see this log file : ~/.local/share/qtile/qtile.log
Neither do I see /usr/share/gnome-session/sessions/qtile.session file
I don't know which log file to see. I am a beginner Linux user. Please help me find the solution.
