### ISSUE TITLE
IOError: [Errno cairo returned CAIRO_STATUS_FILE_NOT_FOUND: file not found]

### ISSUE THREAD

**Issue by Virtuos86** [qtile/qtile#1091]
Fulll log on [Pastebin](https://pastebin.com/JvUBFT31).

I install dev version of Qtile from Github repo using [this official manual](http://docs.qtile.org/en/latest/manual/install/).

**Comment by flacjacket** [comment]
This is odd, what distro are you on?

**Comment by Virtuos86** [comment]
Linux Mint 18.2 "Sonya", 64-bit, with Xfce as DE

**Comment by Virtuos86** [comment]
I was able to start Qtyle by removing the line
`widget.Image(filename=os.path.expanduser('~/.config/qtile/logo.png')),`

**Comment by flacjacket** [comment]
@Virtuos86 I've added a better message to check that the file exists, you can check what happens with the current develop version. I thought this may have been a weird Cairo issue, but it may be as the message says that the file cannot be found.

**Comment by Virtuos86** [comment]
Oh, thanks. My bad. "~/.config/qtile/logo.png is not exist". I forgot to copy this image from my git repo :[. Anyway you made quite good changes.

**Comment by flacjacket** [comment]
Sounds good, I'll close this then
