### ISSUE TITLE
Group spawned through Matching does not use label

### ISSUE THREAD

**Issue by Sweenu** [qtile/qtile#1095]
When creating a group like that: 
`Group('music', layouts=[layout.Max()], label='spotify')`
And having the group spawned when qtile starts, the label is used in the GroupBox widget.

However if I use the matching mechanism, the label isn't used, it's the name of the group that is used.
`Group('music', layouts=[layout.Max()], persist=False, init=False,
          matches=[Match(title=['Spotify'])], label='spotify')`

**Comment by flacjacket** [comment]
This is closed by #1108.
