### ISSUE TITLE
Columns and Wmii layouts are almost equivalent

### ISSUE THREAD

**Issue by heitzmann** [qtile/qtile#1096]
In their current versions, these 2 layouts are almost identical.
From what I can tell, Columns implements all of Wmii features with a few extra options (`autosplit`, `num_columns` and `fair`).

Is there anything in Wmii that is missing in Columns?
If not, it makes sense to leave only one of them, doesn't it?

**Comment by flacjacket** [comment]
If all of the Columns functionality can be written in terms of Wmii, then yes, we can get rid of columns. I can take a look as well, but feel free to open a pull request deleting one if you think this is the case.

**Comment by ramnes** [comment]
MR in progress: #1107 1107
