### ISSUE TITLE
Stacking order not retained when switching using toggle_fullscreen/toggle_maximize

### ISSUE THREAD

**Issue by tombeers** [qtile/qtile#1098]
I'm using the MonadTall layout. When using `libqtile.command.lazy.window.toggle_fullscreen()` or `libqtile.command.lazy.window.toggle_maximize()` and then toggling back again, the original position/stacking order of the windows is changed, and not in a consistent way either, it almost seems random.

The configuration for the layout is:

```
libqtile.layout.MonadTall(
	name="normal",
	align=libqtile.layout.MonadTall._left,
	change_ratio=0.05,
	change_size=10,
	new_at_current=False,
	ratio=0.618,
	single_border_width=None,
	border_normal=colour_border_normal,
	border_focus=colour_border_selected,
	border_width=3,
	margin=8
)
```

Is this known behaviour, and is there a fix?

Thank you, and thank you especially for Qtile.

**Comment by numirias** [comment]
(I'm not a qtile developer.)

What seems to happen when you fullscreen a window is that it gets removed from the layout (in the same way a window that you want to close gets removed). When you toggle back, the window is added to the layout again (in the same way an unrelated window you just spawned will be added). Especially in nested layouts, the new position can therefore be at an entirely different place than where it was originally.

**Comment by Granitosaurus** [comment]
I've been suffering from this as well. @numirias you explanation makes sense but it can't be preferred behaviour, can it? Why would anyone want the possition to reset all the time?

**Comment by ramnes** [comment]
The same bug happens with the Columns layout.

**Comment by numirias** [comment]
FWIW, the [Plasma layout](https://github.com/numirias/qtile-plasma) (disclaimer: I've written it) solves the problem by remembering where removed windows have been, in case they need to be restored. So minimized/floated/fullscreened windows would all go all back into their original spots afterwards.

But I'm not sure if managing that should generally be a layout's obligation or if there's a standard way to deal with it. It might make sense to give layouts the ability to differentiate between a window being put into fullscreen, etc. as opposed to actually being removed.

**Comment by ramnes** [comment]
Thanks for raising the issue. I'm going to close this one in favor of #1114, which is exactly the same.
