### ISSUE TITLE
Test(Travis-CI) is failed because a py library is not support python 3.3 from v1.5.0.

### ISSUE THREAD

**Issue by sux2mfgj** [qtile/qtile#1100]
the py library is required by a pytest-cov. How to resolve this problem?   

- Python 3.3.x has already reached end of life.
https://www.python.org/downloads/release/python-337/

- This is a announcement of the py library.
http://py.readthedocs.io/en/latest/changelog.html#id2

- a failed test 
https://travis-ci.org/himaaaatti/qtile/builds/308500409  
This is a my repository but this branch is same as a head of qtile/qtile develop branch.

**Comment by numirias** [comment]
My PR fails because of that too.

Is Python 3.3 support something that needs to be maintained?

**Comment by sux2mfgj** [comment]
My PR for this problem (#1103 ) is merged !! thanks!
