### ISSUE TITLE
Fix Arch PKGBUILD to include all optional dependencies

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#1106]
Helloes,

I'm on Arch Linux, qtile 0.10.7 and I just installed a new machine.
It seems, that the mpd widget is still crashing qtile, when python-mpd2 is not installed, as shown in the log below.

```
2017-12-11 02:17:15,206 WARNING libqtile log_utils.py:init_log():L118 Starting logging for Qtile
2017-12-11 02:17:15,293 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.launchbar.LaunchBar', No module named 'xdg'
2017-12-11 02:17:15,295 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.mpriswidget.Mpris', No module named 'dbus'
2017-12-11 02:17:15,296 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.mpris2widget.Mpris2', No module named 'dbus'
2017-12-11 02:17:15,297 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.mpdwidget.Mpd', No module named 'mpd'
2017-12-11 02:17:15,298 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.mpd2widget.Mpd2', No module named 'mpd'
2017-12-11 02:17:15,306 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.wlan.Wlan', No module named 'iwlib'
2017-12-11 02:17:15,307 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.khal_calendar.KhalCalendar', No module named 'dateutil'
2017-12-11 02:17:15,308 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.imapwidget.ImapWidget', No module named 'keyring'
2017-12-11 02:17:15,309 WARNING libqtile __init__.py:safe_import():L48 Unmet dependencies for optional Widget: '.keyboardkbdd.KeyboardKbdd', No module named 'dbus'
2017-12-11 02:17:15,321 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing
2017-12-11 02:17:15,322 ERROR libqtile qtile.py:make_qtile():L106 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/confreader.py", line 55, in __init__
    config = __import__(os.path.basename(fname)[:-3])
  File "/home/dave/.config/qtile/config.py", line 305, in <module>
    widget.Mpd(
AttributeError: module 'libqtile.widget' has no attribute 'Mpd'
)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/confreader.py", line 55, in __init__
    config = __import__(os.path.basename(fname)[:-3])
  File "/home/dave/.config/qtile/config.py", line 305, in <module>
    widget.Mpd(
AttributeError: module 'libqtile.widget' has no attribute 'Mpd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/scripts/qtile.py", line 104, in make_qtile
    config = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/usr/lib/python3.6/site-packages/libqtile/confreader.py", line 70, in __init__
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/confreader.py", line 55, in __init__
    config = __import__(os.path.basename(fname)[:-3])
  File "/home/dave/.config/qtile/config.py", line 305, in <module>
    widget.Mpd(
AttributeError: module 'libqtile.widget' has no attribute 'Mpd'
```

Here is a snippet from my config.py, where I use the mpd widget in a top bar:

```
            widget.Mpd(
                host="127.0.0.1",
                port=6600,
                reconnect=True,
                fmt_playing="%a [%A] %t [%v%%]",
            ),

```

As soon as I install python-mpd2 from [community] repo, qtile starts normally and the Mpd widget functions.

**Comment by flacjacket** [comment]
Hi dvzrv, if you look at the log output, it says:
```
Unmet dependencies for optional Widget: '.mpdwidget.Mpd', No module named 'mpd'
```
so it does not have the necessary dependencies to use the widget. Did you have `mpd` installed? If you look in the source for the `mpdwidget`, it does `import mpd`, I assume this is what was failing before. I'm not sure what else we can do to make the error message more informative, but we might be able to do something if you feel this wasn't clear.

**Comment by dvzrv** [comment]
@flacjacket: that might be the case. 
If you think, this is not a bug, then the packaging needs to fix this ([as requested over a year ago](https://aur.archlinux.org/packages/qtile/)) by declaring dependencies on e.g. python-mpd2.
Optional dependencies for the other widget's requirements would be very much appreciated, too.

In AUR I was told, that due to _safe import_, qtile should not crash if a widget dependency is not available. However, this seems to be the case for the Mpd widget, which is why I'm reporting this as a bug.

So either it's time to fix a bug or a PKGBUILD. ;-)

**Comment by flacjacket** [comment]
The safe import will keep it from crashing if you don't have the dependencies installed and don't use the widgets, but they don't exist then if you then try to use them. We can maybe get a better workaround to fail more gracefully in that case.

@Roger has handled the AUR package, he would be the one that knows how to update the dependencies.

**Comment by dvzrv** [comment]
I understand.
When I first tried to use the mpd widget (by modifying the configuration and reloading qtile), I didn't have the dependencies installed (because I didn't know of them). It took my whole system with it, not only X11!
This is something, that should not happen.

Well, in any case case the PKGBUILD has to be changed.
I suggest to (for now) make python-mpd2 a dependency of qtile - as you might otherwise end up with a system that you have to hard reset - until this is fixed somehow.

I have checked out a subset of the widgets and there are some, that have a dependency on python-dbus (mpris, mpris2, keyboardkbdd) but python-dbus is not a dependency of the package qtile (neither is python-gobject), which means that dbus support will not work out of the box (and neither will the aforementioned widgets).
I assume, that dbus support is desired out of the box though, which is why I added the two packages to depends in the below PKGBUILD.
I added the widget dependencies I know of to optdepends.

```
pkgname=qtile
pkgver=0.10.7
pkgrel=2
pkgdesc="A full-featured, pure-Python tiling window manager."
arch=('any')
url="http://www.qtile.org"
license=('MIT')
depends=('pango' 'python-xcffib' 'python-cairocffi' 'python-dbus'
'python-gobject')
makedepends=('python-setuptools' 'python-ipykernel')
optdepends=('python-setproctitle: change the process name to qtile'
            'python-mpd2: Mpd widget'
            'python-gobject: dbus interface'
            'python-dbus: dbus interface, Mpris, Mpris2, KeyboardKbdd widgets'
            'python-iwlib: Wlan widget'
            'python-keyring: Imap widget'
            'khal: calendar widget')
conflicts=('qtile-git')
source=("${pkgname}-${pkgver}.tar.gz::https://github.com/${pkgname}/${pkgname}/archive/v${pkgver}.tar.gz")
sha512sums=('9b8f056ca9b4e5d3136114cafa47ee640f189c3f188815cfe5845c974b745978ebf0f74a691869517144d8fcaac0a29f5b38ee9265b888cc2bb3bfae865934cd')

check() {
  cd "${pkgname}-${pkgver}"
  python setup.py test
}

build() {
  cd "${pkgname}-${pkgver}"
  python setup.py build
}

package() {
  cd "${pkgname}-${pkgver}"
  # install
  python setup.py install --skip-build \
    --optimize=1 \
    --root="${pkgdir}" \
    --prefix=/usr
  # license
  install -Dm 644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
  # config
  install -Dm 644 libqtile/resources/default_config.py \
  "${pkgdir}/usr/share/doc/${pkgname}/default_config.py"
  # desktop file
  install -Dm 644 "resources/${pkgname}.desktop" \
  "${pkgdir}/usr/share/xsessions/${pkgname}.desktop"
  # docs
  install -Dm 644 CHANGELOG "${pkgdir}/usr/share/doc/${pkgname}/CHANGELOG"
  install -Dm 644 README.rst "${pkgdir}/usr/share/doc/${pkgname}/README.rst"
}

```

@Roger please read the [Arch packaging standards](https://wiki.archlinux.org/index.php/Arch_packaging_standards) and respond to change requests in the AUR. It would be great to see qtile be integrated better. I hereby offer to co-maintain the package, if you have no time.

Apart from the PKGBUILD, the mpd widget should be revised, as a crash like this is not so nice.

**Comment by flacjacket** [comment]
Alright, I've updated the name of this issue to address the PKGBUILD file and opened a new issue to track fixing the widgets.

**Comment by Roger** [comment]
Sorry, I didn't see this issue until now.

Yeah, the PKGBUILD should be updated with all the optional dependencies, would be nice if we have documented them somewhere, the only reason that I didn't this before is because I had to track all the of them and hadn't the time to.

In the future, we can ask to the widget authors, to add in the documentation the optional dependencies.

Would be ok if I add the PKGBUILD in the qtile repo?

**Comment by dvzrv** [comment]
@Roger it would be great, if you could then just incorporate the suggested changes right away.

I am advising against providing a PKGBUILD in this repository, as this would mean data held twice (Arch will have it in a repository anyways).

However, a file, that lists the requirements for each provided widget would be very smart.
This could be done in the README of this project, by a) listing the available widgets and b) listing their specific (optional) dependencies.
I would make this a requirement for widget authors, as you otherwise will have to handle with plenty more issues related to similar problems (dependencies missing).
This way it also becomes instantly recognizable for people trying to package qtile for their distribution.

**Comment by eli-schwartz** [comment]
Maintaining distro-specific packaging scripts rather than investing in a well-written README is a pox. :p
Please do not maintain the PKGBUILD here, as that would only encourage fixing things in the wrong place.

**Comment by dvzrv** [comment]
Needs canto-daemon in optdepends for the canto widget.

**Comment by dvzrv** [comment]
needs cmus in optdepends for cmus widget.
needs python-six in optdepends for generic_poll_text widget.
needs python-imaplib2 in optdepends for gmail_checker widget.
needs python-xdg in optdepends for launchabr widget.
needs python-six in optdepends for maildir widget.
needs moc in optdepends for moc widget.
needs python-six in optdepends for mpd2widget widget.
needs python-six in optdepends for sensors widget.
needs lm_sensors in optdepends for sensors widget.
needs python-six in optdepends for stock_ticker widget.
needs alsa-utils in optdepends for volume widget.
needs python-six in optdepends for yahoo_weather widget.

**Comment by dvzrv** [comment]
Seems python-xcffib requires python-six.
Therefore this could maybe also be removed from [setup.py](https://github.com/qtile/qtile/blob/develop/setup.py#L89)?

**Comment by Roger** [comment]
Sorry, I have been with a lot of issues irl, I'll be working on this today

**Comment by Roger** [comment]
dbus is an optional dependency, requiered for a lot of widgets, but still optional

**Comment by Roger** [comment]
Also, I have a semi working fix for the mpd(and other widgets) that don't have the dependencies installed. https://github.com/qtile/qtile/issues/1110

**Comment by Roger** [comment]
@dvzrv is there any reason to remove the "install=" from the PKGBUILD?

**Comment by dvzrv** [comment]
@Roger: it's not really needed.

**Comment by dvzrv** [comment]
@Roger I had to hard reset my computer because of that.
I'm not sure how, but it seems that qtile->X11->i915 triggered a kernel panic.

Depending on whether you use a DM, it might trigger some odd behavior (e.g. LightDM at that time locked up).
Depending on whether you allow your X11 user to switch TTYs, you'll be trapped on a borked X11.
I currently use startx, as I want to be able to run X11 not as root.
There it failed "more gracefully" by killing itself afair.

Whatever it triggers, opening a bug report for that will basically talk about more symptoms.
It seems you are working on a solution for the widgets now, which is great!

Let's keep the focus on the PKGBUILD in this bug then.

**Comment by dequis** [comment]
There are several issues that are obviously out of scope of qtile - if your kernel panics because of X quitting, it's silly to blame optional dependencies. But that aside, one thing that still doesn't make sense to me.

The error is initiated by `qtile.py:make_qtile():L106 Error while reading config file` - this is the usual "the user has made a mistake in the config", and this is normally handled by loading the fallback config. Why did this not happen?

**Comment by Roger** [comment]
@dequis we should try to move this to another issue.

@dvzrv does that PKGBUILD builds in your system? because the check is trying to run the tests in a way that fails.

**Comment by dvzrv** [comment]
@Roger I just added #1130 for the test environment.

I'll close this now, as I've moved qtile to [community].
However, I suggest listing dependencies for widgets (e.g. in the README) to make it easier for people to package and/or use qtile.
