### ISSUE TITLE
Build fails due a timeout (?)

### ISSUE THREAD

**Issue by numirias** [qtile/qtile#1109]
The build currently fails with what [looks like a timeout](https://travis-ci.org/qtile/qtile/jobs/313282015) on one of the jobs.

Since a red build badge might scare away visitors regardless whether the package works fine, it would be great to get that fixed.

If it's really just a timeout, could one of the owners maybe just re-run the job?

**Comment by flacjacket** [comment]
Thanks for pointing that out! Restarted the build to get it green.
