### ISSUE TITLE
Make using unavailable widgets not crash

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#1110]
See #1106 for discussion

**Comment by flacjacket** [comment]
I feel like the way to fix this is to have the `safe_import` replace the offending widget with a text widget class that displays an error.

**Comment by Roger** [comment]
I'm working on this, how should we display the error? this is what I got for now

![image](https://user-images.githubusercontent.com/9746/35385857-8dac8700-01a8-11e8-87dd-c5d30394e55f.png)

**Comment by ramnes** [comment]
From my experience other WM handle that by not loading the module and popping a notification. But that works too.

**Comment by flacjacket** [comment]
Without another notification system, I think that is a great solution. Since this is covered by Roger's PR, I'll close this.
