### ISSUE TITLE
How do I flatten a floating window?

### ISSUE THREAD

**Issue by nochiel** [qtile/qtile#1113]
In (xmonad](http://xmonad.org/tour.html#floating):
> To float a window (or move an already-floating window), click and drag it with the mod-button1 held down. *To flatten the window back down to the tiling layer use mod-t.*

How do I flatten floating windows using the xmonad.py layout (or any other layout algorithm provided with qtile)?

**Comment by ramnes** [comment]
You have to bind and use the `lazy.window.toggle_floating` function.

See an example [here](https://github.com/qtile/qtile-examples/blob/master/ramnes.py#L110).
