### ISSUE TITLE
Unicode character in group name breaks qtile restart

### ISSUE THREAD

**Issue by doenerkebap** [qtile/qtile#1120]
Having a group name with a unicode character produces the following error when trying to restart qtile:

```
2018-01-23 02:44:33,242 libqtile manager.py:handle_KeyPress():L910  KB command error restart: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/libqtile/command.py", line 97, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/libqtile/manager.py", line 1387, in cmd_restart
    argv.append('--with-state=' + buf.getvalue().decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 218: invalid continuation byte

```

**Comment by Sweenu** [comment]
I'm not answering the issue but you can use labels instead and have a unicode-free name:
```python
Group('music', label='Åll the Ünicøde ¢haracters yøu wañt')
```

**Comment by doenerkebap** [comment]
As far as I can see, the label feature was introduced only recently in https://github.com/qtile/qtile/commit/31abc0f2dac95b270351eabb56d9d8071a78a60b . I installed version 10.7 via pip, so it is not available to me, right?
Is there an easy way to upgrade to the latest github version. Can the develop branch recommended to be used by end users, or will i run into further trubles?

**Comment by Sweenu** [comment]
The 10.7 version is almost a year old. In my opinion, you're better off using the develop branch. You'll get the fixes and features and you shouldn't have more problems because each pull request is tested against the whole test suite. 
You can build it from source or, if you're on Arch, install the  qtile-python3-git AUR package.

**Comment by flacjacket** [comment]
This seems like a shortcoming of pickling everything to serialize between restarts. In general, I think we need a more robust way to serialize and deserialize state, there are several issues related to the way that we restart and how we restore the previous state.

Also, I can work on getting a release out this weekend so you can get caught up :)

**Comment by tcld** [comment]
There has been a recent change to the serialization code by @m-col: #1898 fixes this issue.

**Comment by m-col** [comment]
Great, thanks. Looks like these are (almost) duplicates, so makes sense.
