### ISSUE TITLE
Mpd2 widget no output

### ISSUE THREAD

**Issue by mrneilypops** [qtile/qtile#1125]
Distro=Void linux
python-mpd2 installed

I do not get any output from Mpd2 widget.
Mpd widget works OK.

Could I be missing a library in Void linux?

**Comment by ramnes** [comment]
What do the logs say?

**Comment by mrneilypops** [comment]
Good point...I have attached my log file.
[qtile.log](https://github.com/qtile/qtile/files/1686571/qtile.log)

**Comment by ramnes** [comment]
I don't seem to find anything relevant in your logs.

If you have the mpd widget working, then I guess that you have `python-mpd` (not `python-mpd2`) installed? If so, try to uninstall `python-mpd`, that might just be the wrong module being imported.

**Comment by mrneilypops** [comment]
Hmm...according to Void I have python-mpd2 installled;
https://github.com/voidlinux/void-packages/search?utf8=%E2%9C%93&q=python-mpd2&type=

**Comment by mrneilypops** [comment]
In fact I now have python-mpd2,python3-mpd2 and python3.4-mpd2 installed...

**Comment by ramnes** [comment]
But what about `python-mpd` or `python3-mpd`?

**Comment by mrneilypops** [comment]
I do not have the packages python-mpd or python3-mpd installed.
However, if I uninstall python-mpd2, leaving python3-mpd2 and python3.4 installed I get some output from the widget.
![import-error](https://user-images.githubusercontent.com/1450448/35779256-46097db6-09ca-11e8-8f02-60f18180b362.png)

Could this be progress?
What could I be missing now?

**Comment by mrneilypops** [comment]
I just installed Qtile on Debian Sid as a comparison and have exactly the same problem. mpd widget works but mpd2 widget gives above error...

**Comment by Roger** [comment]
@mrneilypops same error, you mean Import Error? that means that you don't have some dependency installed, you can look at the logs. 

About the no output, not even [ ]?  can you share your config?

**Comment by mrneilypops** [comment]
Hi Roger,
You can see from the above scrot the output I get;
`Import Error: Mpd2`
The latest qtile.log and config.py is attached.

**Comment by bmjoan** [comment]
`mpd2widget.Mpd2` works for me

@mrneilypops By your log, `mpd` module from `python-mpd2` cann't be found in python's search path:

> Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named mpd

Check if python version running `qtile` matches with version `python-mpd2` was installed for.
Is your python environment somehow altered during a startup, like (improper) use of pyenv ?

Following oneline, based on used python version and mpd server settings, should return some similar meaningful output:

```
~$ python3 -c 'import mpd;c=mpd.MPDClient();c.connect("localhost", 6600);print(c.status())'
{'volume': '100', 'repeat': '0', 'random': '0', 'single': '0', 'consume': '0', 'playlist': '22', 'playlistlength': '25',
 'mixrampdb': '0.000000', 'state': 'stop', 'song': '24', 'songid': '39'}
```

**Comment by flacjacket** [comment]
This seems to just come down to not having the module installed. I'll close this out.
