### ISSUE TITLE
Kupfer Launcher appears behind current window

### ISSUE THREAD

**Issue by cserb** [qtile/qtile#1128]
I'm trying to setup kupfer launcher, but currently it appears behind the current window when launched. I need to go to a workspace with no windows to be able to see and use it.

Is there a way to say it should appear always in front and if possible also align to the center?

**Comment by Granitosaurus** [comment]
What's your `floating_layout` setting?
I'm using `rofi` launcher which I presume is quite similar, with my `floating_layout` set to:

```
floating_layout = layout.Floating(float_rules=[
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'guake'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass
])
```

**Comment by cserb** [comment]
@Granitosaurus same here. I'm also using rofi and it works fine. 

I tried to open Kupfer as a non floating window, which makes it fullscreen but still shown behind the current window. I assume by now it might be an issue with Kupfer, but I'd like to know how qtile makes the decision on where to display it. Than I might be able to report a bug at the kupfer project

**Comment by cserb** [comment]
@Granitosaurus same here. I'm also using rofi and it works fine. 

I tried to open Kupfer as a non floating window, which makes it fullscreen but still shown behind the current window. I assume by now it might be an issue with Kupfer, but I'd like to know how qtile makes the decision on where to display it. Than I might be able to report a bug at the kupfer project

**Comment by nazar-pc** [comment]
I'm using Cerebro and experience the same issue, also it is only shown in the group where it was initially opened, not on current one.

**Comment by nazar-pc** [comment]
Just as an additional info: Cerebro runs in background and shows its window on hotkey. First time it shows above all windows and everything is fine. But when I open more programs, it starts showing behind those and only on a group it was initially opened, which is not a desired behavior.

**Comment by nazar-pc** [comment]
I've switched to `develop` branch and it seems to work better now.
Also for the issue where Cerebro opens on the same group I wrote this:
```python
@hook.subscribe.client_name_updated
def move_cerebro_to_current_group(window):
	if window.window.get_name() == 'Cerebro':
		window.togroup()
```

**Comment by cserb** [comment]
version 0.11.0 fixes it for me. thanks for the update!
