### ISSUE TITLE
qtile-top crashes on startup

### ISSUE THREAD

**Issue by sminez** [qtile/qtile#1129]
I tried running the `qtile-top` utility and I immediately get the following traceback (running under python 3.5.2:
```python
qtile-top 
Traceback (most recent call last):
  File "/usr/local/bin/qtile-top", line 11, in <module>
    load_entry_point('qtile==0.10.7', 'console_scripts', 'qtile-top')()
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.7-py3.5.egg/libqtile/scripts/qtile_top.py", line 162, in main
    force_start=force_start)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.7-py3.5.egg/libqtile/scripts/qtile_top.py", line 88, in get_stats
    scr.addstr(0, 0, "Qtile - Top {0:s} lines".format(limit))
ValueError: Unknown format code 's' for object of type 'int'
```

The offending line is line 88:
```
scr.addstr(0, 0, "Qtile - Top {0:s} lines".format(limit))
```
which seems to just be inserting the **int** limit variable into the string. I've tried looking at the `format` docs again (I always forget all of the DSL options hidden away in there!) but I'm not sure what `{0:s}` is supposed to be doing...

Replacing it with a bare `{}` seems to do the trick (in terms of getting rid of the ValueError) but I then get the following:
```
$ python3 qtile_top.py
tracemalloc not started on qtile, start by setting PYTHONTRACEMALLOC=1 before starting qtile
or force start tracemalloc now, but you'll lose early traces
```

Which I assume is because I'm just trying to run the script manually rather than using `qtile-top` as installed?

**Comment by flacjacket** [comment]
Thanks for reporting this, but this issue has already been fixed on master, you can get a working version by installing from source. The latest release is very old, but we should have a new one out with this fix soon.

**Comment by sminez** [comment]
Ah fab, that seems to have sorted it now 👍  thanks!
