### ISSUE TITLE
Trying to use SVG icons makes qtile crash in a non clean way

### ISSUE THREAD

**Issue by Sweenu** [qtile/qtile#1132]
I just tried using svg icons for my widgets (which I didn't know wasn't supported) and got some serious problems (black screen after a reboot and no information in the logs). It took me 2 hours to understand the problem was coming from the icons being svg.

Is there any news about svg support for icons ([PR #1066](https://github.com/qtile/qtile/pull/1066))?

Seems like there hasn't been any release for cariocffi for more than a year... Should we resolve to use the git version after all?

**Comment by ramnes** [comment]
Let's keep the discussion in #1066 directly. :+1:
