### ISSUE TITLE
Some windows are ignored by Qtile

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#1136]
Following crash from #144 and restart of Qtile, some windows are shown on any group and are completely ignored by Qtile.
I think this is caused by the fact that certain windows become `window state: Withdrawn`, like described in https://github.com/i3/i3/issues/1617

Is this something that can be fixed? After Qtile restart it doesn't print any complains about such window.

**Comment by nazar-pc** [comment]
Also happens with 0.11.0

**Comment by flacjacket** [comment]
Is it still after a crash? Or is it after a normal restart?

**Comment by nazar-pc** [comment]
It is some kind of crash, I see that gnome-session reports that Qtile was restarted, but there is no exceptio reported in `~/.local/share/qtile.qtile.log` or even its stdout/stderr. What happens is that randomly some windows on from current group become in withdrawn state, visible all the time regardless of current group and no longer managed by Qtile.

Haven't seen this behavior after restart explicitly initiated my myself.

**Comment by nazar-pc** [comment]
OK, it seems to mostly happen with apps like Nextcloud, CopyQ, qBittorrent, ckb-next, which are running, but minimized in tray (most of them if not all are using Qt5). On Qtile restart they appear as painted regions under other apps and have on them whatever apps that were opened at Qtile restart. When I restore each such app and minimize back to tray everything seems to become fine again.

This is a different scenario that effectively leads to the same issue (I had the same issue with Thunderbird and Firefox). The issue always happens exclusively to windows that were started on particular group.

BTW, in 0.11.0 these apps stick back to group on Qtile restart, which is a good progress already, at least I don't need to restart X11.

**Comment by nazar-pc** [comment]
OK, some more details. I took qBittorrent, unminimized it from tray and minimized back, looks fine so far:
```
nazar-pc@nazar-pc ~> xwininfo -name "qBittorrent v4.0.4"

xwininfo: Window id: 0x7e0000d "qBittorrent v4.0.4"

  Absolute upper-left X:  1920
  Absolute upper-left Y:  1080
  Relative upper-left X:  1920
  Relative upper-left Y:  1080
  Width: 1918
  Height: 1078
  Depth: 24
  Visual: 0x27
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x7e0000c (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +1920+1080  -0+1080  -0-0  +1920-0
  -geometry 959x539-0-0
```

Now I restart Qtile with `lazy.restart()` and suddenly:
```
nazar-pc@nazar-pc ~> xwininfo -name "qBittorrent v4.0.4"

xwininfo: Window id: 0x7e0000d "qBittorrent v4.0.4"

  Absolute upper-left X:  1920
  Absolute upper-left Y:  1080
  Relative upper-left X:  1920
  Relative upper-left Y:  1080
  Width: 1918
  Height: 1078
  Depth: 24
  Visual: 0x27
  Visual Class: TrueColor
  Border width: 1
  Class: InputOutput
  Colormap: 0x7e0000c (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1920+1080  -0+1080  -0-0  +1920-0
  -geometry 959x539-0-0
```

But as I said before, it is just an area on screen (where qBittorrent was before minimizing) with picture of the app that was running on top of that region as the restart moment (though, in most cases, app is still clickable, I can see dropdown menu on torrents if I make right click on the area, despite area is painted with terminal). When I unminimize it back from tray it actually draws itself on the same exact area, despite layout has changed since then, afterwards I minimize it back to tray and everything is fine again.

There are some other variations of this bug, but I suspect they are related and this particular one it pretty easy to reproduce relatively reliably.

**Comment by nazar-pc** [comment]
I haven't experienced this for a while and the only change I think might have affected behavior is that I've stopped using `Stack` layout. I'll dig deeper into it once I have time and mood for it again.

**Comment by nazar-pc** [comment]
So this looks like some kind of internal crash that happens in the middle of some process that is interrupted, which results in some windows being lost by Qtile. It doesn't reach `libqtile.manager.Qtile#stop()` (I've checked that).

### How to reproduce with 100% reliability:
1) Install Nemo file manager (not sure it happens with Nautilus, I don't have it, but you may try it too)
2) Open Firefox
3) Open Nemo
4) Close Nemo
5) `nemo` process is still running, kill it

### Expected result
Visually nothing happens

### Actual result
Qtile restarts without any error or exception printed and messes up with some (many) windows in current group, in particular, Firefox will not get focus from Qtile anymore until it is closed and restarted again.

@flacjacket, is this enough info for you or someone else to debug the issue now?

**Comment by nazar-pc** [comment]
So this is more generic issue with closing hidden apps. If I minimize qBittorrent to tray and then close it from tray menu - Qtile also kind of crashes/restarts.

**Comment by nazar-pc** [comment]
So it appears to call `stop()` on event loop for some reason with stack like this:
```
  File "/home/nazar-pc/.local/bin/qtile", line 10, in <module>
    exit_code = load_entry_point('qtile', 'console_scripts', 'qtile')()
  File "/web/github/qtile/libqtile/scripts/qtile.py", line 127, in main
    q.loop()
  File "/web/github/qtile/libqtile/manager.py", line 792, in loop
    self._eventloop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/web/github/qtile/libqtile/manager.py", line 785, in stop
    logger.warning(traceback.format_stack())
```

**Comment by nazar-pc** [comment]
This is a really annoying issue I'm facing every day, but can't fix myself.
Can someone take a look at this, please?

**Comment by numirias** [comment]
I was trying to reproduce the problem but didn't succeed. Do you mind sharing your config? (Is it reproducible with a minimal config?)

**Comment by nazar-pc** [comment]
Here is my config:
<details>

```python
from libqtile.command import lazy
from libqtile.config import EzDrag, EzKey, EzClick, Screen, Group, Match
from libqtile.layout import Floating, Max, Matrix, Tile
from libqtile import hook
from plasma import Plasma
import subprocess
import os

@hook.subscribe.startup_once
def dbus_register ():
	id = os.environ.get('DESKTOP_AUTOSTART_ID')
	if not id:
		return
	subprocess.Popen([
		'dbus-send',
		'--session',
		'--print-reply',
		'--dest=org.gnome.SessionManager',
		'/org/gnome/SessionManager',
		'org.gnome.SessionManager.RegisterClient',
		'string:qtile',
		'string:' + id
	])

@hook.subscribe.client_name_updated
def move_cerebro_to_current_group (window):
	if window.window.get_name() == 'Cerebro':
		window.togroup()

show_current_group_notification = lazy.function(
	lambda qtile:
		qtile.cmd_spawn(
			'notify-send -h string:x-canonical-private-synchronous:qtile -t 50 --icon window-manager "Group #' + qtile.currentGroup.name + ', layout ' + qtile.currentLayout.name + '"'
		)
)

mod = 'mod4'

keymap = {
	'M-<Left>'     : lazy.layout.left(),
	'M-<Down>'     : lazy.layout.down(),
	'M-<Up>'       : lazy.layout.up(),
	'M-<Right>'    : lazy.layout.right(),
	'M-S-<Left>'   : [lazy.layout.move_left(), lazy.layout.shuffle_up()],
	'M-S-<Down>'   : [lazy.layout.move_down(), lazy.layout.shuffle_down()],
	'M-S-<Up>'     : [lazy.layout.move_up(), lazy.layout.shuffle_up()],
	'M-S-<Right>'  : [lazy.layout.move_right(), lazy.layout.shuffle_down()],
	'M-C-<Left>'   : lazy.layout.integrate_left(),
	'M-C-<Down>'   : lazy.layout.integrate_down(),
	'M-C-<Up>'     : lazy.layout.integrate_up(),
	'M-C-<Right>'  : lazy.layout.integrate_right(),
	'A-S-<Tab>'    : lazy.layout.previous(),
	'A-<Tab>'      : lazy.layout.next(),
	'M-h'          : lazy.layout.mode_horizontal(),
	'M-v'          : lazy.layout.mode_vertical(),
	'M-S-h'        : lazy.layout.mode_horizontal_split(),
	'M-S-v'        : lazy.layout.mode_vertical_split(),
	'M-<End>'      : lazy.layout.grow_width(30),
	'M-<Home>'     : lazy.layout.grow_width(-30),
	'M-<Page_Up>'  : lazy.layout.grow_height(30),
	'M-<Page_Down>': lazy.layout.grow_height(-30),
	'M-<Tab>'      : [lazy.next_layout(), show_current_group_notification],
	'C-A-<Up>'     : [lazy.screen.prev_group(), show_current_group_notification],
	'C-A-<Down>'   : [lazy.screen.next_group(), show_current_group_notification],
	'M-r'          : lazy.layout.reset_size(),
	'M-w'          : lazy.window.kill(),
	'C-A-t'        : lazy.spawn('terminator'),
	'C-A-c'        : lazy.spawn('gnome-calculator'),
	'C-A-s'        : lazy.spawn('env XDG_CURRENT_DESKTOP=GNOME gnome-system-monitor'),
	'M-n'          : lazy.spawn('env XDG_CURRENT_DESKTOP=GNOME nemo'),
	'M-S-c'        : lazy.spawn('killall -9 cerebro'),
	'M-c'          : lazy.spawn('cerebro'),
	'M-a'          : lazy.spawn('pavucontrol'),
	'<XF86Tools>'  : lazy.spawn('clementine'),
	'<Print>'      : lazy.spawn('gnome-screenshot'),
	'A-<Print>'    : lazy.spawn('gnome-screenshot --window'),
	'S-<Print>'    : lazy.spawn('gnome-screenshot --area'),
#	'<Caps_Lock>'  : lazy.spawn('xdotool key Alt+F2'),
	'M-l'          : lazy.spawn('i3lock -c 000000'),
	'M-C-r'        : lazy.restart(),
}

mouse = [
	EzDrag('M-1', lazy.window.set_position_floating(), start = lazy.window.get_position()),
	EzDrag('M-3', lazy.window.set_size_floating(), start = lazy.window.get_size()),
	EzClick('M-2', lazy.window.bring_to_front()),
	EzClick('9', lazy.screen.prev_group()),
	EzClick('8', lazy.screen.next_group()),
]

borders = {
	#	'border_focus' : '#dcdcdc',
	#	'border_normal': '#2d2d2d',
	'border_width': 0
}

layouts = [
	Max(name = 'Max'),
	Matrix(columns = 3, name = 'Matrix', **borders),
	Plasma(name = 'Plasma', **borders),
	Tile(
		name = 'Tile',
		expand = False,
		add_after_last = True,
		shift_windows = True,
		ratio = 0.5,
		master_match = Match(wm_class = ['Nightly', 'Thunderbird']),
		**borders
	),
]

floating_layout = Floating(
	no_reposition_match = Match(wm_class = ['Cerebro']),
	**borders
)

groups = [
	Group('1', layout = 'Tile', matches = [Match(wm_class = ['Thunderbird'])]),
	Group('2', layout = 'Tile', matches = [Match(wm_class = ['Nightly', 'qBittorrent'])]),
	Group('3', layout = 'Max', matches = [Match(wm_class = ['jetbrains-idea'])]),
	Group('4', layout = 'Matrix', matches = [Match(wm_class = ['Clementine', 'Pavucontrol', 'Synaptic'])]),
	Group('5', layout = 'Plasma'),
	Group('6', layout = 'Matrix'),
	Group('7', layout = 'Matrix'),
	Group('8', layout = 'Matrix'),
	Group('9', layout = 'Matrix'),
	Group('0', layout = 'Matrix'),
]

for i in groups:
	keymap['M-' + i.name] = [
		lazy.group[i.name].toscreen(),
		show_current_group_notification
	]
	keymap['M-S-' + i.name] = [
		lazy.window.togroup(i.name),
		lazy.group[i.name].toscreen(),
		show_current_group_notification
	]

keys = []
for k, v in keymap.items():
	if type(v) is list:
		keys.append(EzKey(k, *v))
	else:
		keys.append(EzKey(k, v))

screens = [Screen()]

follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
auto_fullscreen = True
focus_on_window_activation = 'smart'

wmname = 'LG3D'
```

</details>
I'm on Ubuntu 18.10 and Nemo is installed from stock repositories.

**Comment by nazar-pc** [comment]
Let me close this one, since what I'm experience right now is not crash, but a bit different behavior with those same apps. Will report separately. This particular issue might have been fixed somewhere during last year.
