### ISSUE TITLE
Not all floating windows should be centered

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#1140]
OK, there is one regression in 0.11.0 comparing to 0.10.7: floating windows are always in the center.
This might be good for some purposes, but not always.

For instance, I have an app launcher Cerebro that appears slightly above the center of the screen and now it jumps from the center to its usual position each time I activate it.

The other example if IntelliJ IDEA (Java) whose dropdown menus, even nested, are now all exactly in the center of the screen, looks bizarre:
![2018-03-01 08-38-43](https://user-images.githubusercontent.com/928965/36830370-0643c7b6-1d2c-11e8-9fb9-a35cab219397.png)

**Comment by flacjacket** [comment]
So, to a degree, this is desired behavior. When we spawn a new floating window, we will put it in the center of the screen, which as you say, is sensible for a standard notion of a new window. The consequence is when things make new windows and want them placed a certain way, it may behave poorly. It's odd that the program doesn't take care of placing them, there is likely some position hint we aren't checking in the way that they expect.

**Comment by nazar-pc** [comment]
@flacjacket, what could be my options for debugging this issue?
How can I identify which hints should be checked by Qtile or sent by Intellij and how can I prevent this behavior for certain windows?

**Comment by Sweenu** [comment]
Here's the reference for position and size hinting: https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.3
There's a "force" parameter to the place() function which is supposed to bypass the hints but it doesn't seem used in the function. I suppose the hints are ignored by default.

**Comment by nazar-pc** [comment]
I've submitted #1149 already, which fixes the issue in Java apps (like on screenshot above) and adds an option that allows me to specify which windows should not be moved, which actually all I've noticed as needed so far. If the second thing can work out of the box - that would be even better.

Here is Cerebro's `xprop` output:
```
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 56573318
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1597, 834
WM_NAME(UTF8_STRING) = "Cerebro"
_NET_WM_NAME(UTF8_STRING) = "Cerebro"
_NET_WM_STATE(ATOM) = 
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "cerebro", "Cerebro"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_SPLASH
_NET_WM_PID(CARDINAL) = 28066
WM_LOCALE_NAME(STRING) = "uk_UA.UTF-8"
WM_CLIENT_MACHINE(STRING) = "nazar-pc"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

Looks like `program specified location: 1597, 834` is what Qtile should read and take into account in this case.

**Comment by nazar-pc** [comment]
And here is the output of the program that only specifies what size it wants to be, but not position (this is the kind of floating window Qtile should center by default):
```
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_SKIP_PAGER
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x680001f
		bitmap id # of mask for icon: 0x6800022
		window id # of group leader: 0x6800001
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
	...
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 109052437
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_USER_TIME(CARDINAL) = 57059949
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x6800214
WM_CLIENT_LEADER(WINDOW): window id # 0x6800001
_NET_WM_PID(CARDINAL) = 27174
WM_LOCALE_NAME(STRING) = "uk_UA.UTF-8"
WM_CLIENT_MACHINE(STRING) = "nazar-pc"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 281 by 484
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "tint2conf", "Tint2conf"
WM_ICON_NAME(STRING) = "Properties"
_NET_WM_ICON_NAME(UTF8_STRING) = "Properties"
WM_NAME(STRING) = "Properties"
_NET_WM_NAME(UTF8_STRING) = "Properties"
```

**Comment by ramnes** [comment]
Did you manage to find a workaround @nazar-pc?

It's crazy how 20% (very scientific estimation) of our issues are linked to Java.

**Comment by nazar-pc** [comment]
With #1149 being merged a while ago I have no issues with Java (JetBrains Intellij IDEA) and `no_reposition_match` introduced in the same PR allows  me to correct behavior for Synapse.

So generally, this is resolved in latest release for my use case. However, it would be nice if Qtile can handle those apps without workarounds specified in config file or built-in, because otherwise there will be more issues like this going forward.

**Comment by ramnes** [comment]
Do you have any lead as to how fix this in a more durable way? Aren't we screwed anyway since we're completely dependent of the client's implementation?

**Comment by nazar-pc** [comment]
No idea to be honest, I'm quite far from X11 or even native development, just wanted to get things working for me and managed to hack Qtile appropriately.

**Comment by pawamoy** [comment]
Can this issue be closed? Right-click menus correctly appear below the mouse with Qtile 0.14.2 (and 0.15.x as well I guess).

**Comment by ramnes** [comment]
I think so. Feel free to comment if this is still a problem!

**Comment by Miziak** [comment]
Problem still exists for ms teams app:
xprop for notification:
`_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 0
WM_NAME(UTF8_STRING) = "Powiadomienie w aplikacji Microsoft Teams"
_NET_WM_NAME(UTF8_STRING) = "Powiadomienie w aplikacji Microsoft Teams"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 1612, 944
                program specified minimum size: 301 by 128
                program specified maximum size: 301 by 128
_NET_WM_ICON(CARDINAL) = 
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "microsoft teams - preview", "Microsoft Teams - Preview"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION
_NET_WM_PID(CARDINAL) = 2956
WM_LOCALE_NAME(STRING) = "pl_PL.UTF-8"
WM_CLIENT_MACHINE(STRING) = "pmizio-e5400"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING`

for make window float in my config sits this:
`@hook.subscribe.client_new
def floating_dialogs(window):
    dialog = window.window.get_wm_type() == 'dialog' or window.window.get_wm_type() == "notification"
    transient = window.window.get_wm_transient_for()
    if dialog or transient:
        window.floating = True
`

Additionaly popup grab focus, any quick solution for this?

**Comment by m-col** [comment]
@Miziak which teams window is this? I use teams so I can check it out, but I don't get any notification popups. How can I trigger one?

**Comment by zordsdavini** [comment]
I can't confirm (not 100% sure). Banner for me comes near mouse position.

**Comment by zordsdavini** [comment]
@m-col enable notifications/banners in your settings

**Comment by Miziak** [comment]
@m-col 
It looks like this:
![image](https://user-images.githubusercontent.com/4346598/81172812-46494380-8f9f-11ea-95ad-3fab0a8a06b0.png)

for me it appear when i personally get message or someone post something in group i belong.

**Comment by ramnes** [comment]
Do we have a way to have more sensible defaults for this? I don't have this problem with Chrome notifications, for example. Meanwhile, you can use the `no_reposition_match` option of the `Floating` layout.

**Comment by ramnes** [comment]
Alright, as @nazar-pc said [previously](https://github.com/qtile/qtile/issues/1140#issuecomment-370074411), the "program specified location" hint is what we are most likely failing to use. Contributions are welcome!

**Comment by tych0** [comment]
Isn't the culprit that you make the notification type floating but don't set where you want it? The default is to put things in the middle of the screen.

**Comment by tych0** [comment]
Oh, I see. Yeah, looks like we should respect WM_SIZE for both location and size. Shouldn't be too huge a patch.

**Comment by ramnes** [comment]
Should be fixed now! Feel free to report back.
