### ISSUE TITLE
Tint2 is covered by other apps

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#1145]
I'm using Tint2 as my panel of choice and configured it to show on top of all windows except fullscreen.
However, this only works for windows that were opened before Tint2, everything opened later covers it.

Tint2 doesn't occupy separate area on the screen, but rather act like an overlay, so I'd really like to see it all the time.

`xprop` output:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: -1175627520, 22095
		program specified minimum size: 564 by 24
		program specified maximum size: 564 by 24
WM_CLASS(STRING) = "tint2", "Tint2"
XdndAware(ATOM) = ATOM
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_NET_WM_PID(CARDINAL) = 16986
_NET_WM_ICON_NAME(UTF8_STRING) = "tint2"
_NET_WM_NAME(UTF8_STRING) = "tint2"
WM_ICON_NAME(STRING) = "tint2"
WM_NAME(STRING) = "tint2"
```

**Comment by nazar-pc** [comment]
Wrote a workaround, would be nice to have something like this in simpler form out of the box:
```python
from libqtile import hook
from xcffib.xproto import StackMode

tint2_instance = None

@hook.subscribe.client_managed
def register_and_bring_to_front_tint2_instance (window):
	global tint2_instance
	if window.name == 'tint2':
		tint2_instance = window
	elif tint2_instance is not None:
		tint2_instance.window.configure(stackmode=StackMode.Above)

@hook.subscribe.client_killed
def unregister_tint2_instance (window):
	global tint2_instance
	if window.name == 'tint2':
		tint2_instance = None
```

**Comment by soulchainer** [comment]
@nazar-pc If the height of your `tint2` is fixed (it doesn't grow), maybe this could also solve it → http://docs.qtile.org/en/latest/manual/config/screens.html?highlight=gap#gap (from the docs). Just reserve space for tint2 and that's all. I guess I don't use tint2 at the moment, but the integrated bar.

**Comment by nazar-pc** [comment]
@soulchainer I don't want to reserve space. I'm using it as overlay, it doesn't occupy any space on its own.

**Comment by ramnes** [comment]
So basically the problem here is that we don't handle `_NET_WM_STATE_ABOVE`, right? This should be pretty simple to add to the codebase.

**Comment by jwijenbergh** [comment]
Can you still reproduce this? For me new windows do not overlap tint2

**Comment by nazar-pc** [comment]
I used mentioned workaround ever since in my config. Was it fixed by some PR so I should try to remove workaround?

**Comment by jwijenbergh** [comment]
I'm not sure if it's fixed, but I can't reproduce it and I have not added any workaround in my config

**Comment by nazar-pc** [comment]
Just commented-out workaround and the issue is definitely present. I just opened a terminal window and it covered tint2 immediately.

**Comment by jwijenbergh** [comment]
> Just commented-out workaround and the issue is definitely present. I just opened a terminal window and it covered tint2 immediately.

Thanks for testing! Was just going over old issues and my quick testing worked. We can leave this open then
