### ISSUE TITLE
qcmd conflicts with renameutils

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#1153]
I suggest a rename of the qcmd script.
It [conflicts with renameutils](https://bugs.archlinux.org/task/57710)' qcmd.

As "same name" issues are quite common, I suggest a naming scheme such as `qtile-cmd` (in line with `qtile-{run,top}`)

**Comment by flacjacket** [comment]
Thanks for reporting this, I just pushed changes to the script naming.
