### ISSUE TITLE
Feature request: single_margin_width for MonadTall

### ISSUE THREAD

**Issue by bedax** [qtile/qtile#1154]
It would be nice, with the MonadTall layout, if you could have no margin when there is a single window.

Thank you for QTile

**Comment by flacjacket** [comment]
You should be able to set that currently if you set `single_border_width=0` in your config. Let us know if you need any more help!

**Comment by bedax** [comment]
@flacjacket thank you for your response. I am using that setting, and it works for the border, but I also want to remove the spacing around the border when there is a single window, so essentially it looks maximised, which I don't think is currently possible?

**Comment by bedax** [comment]
If this doesn't involve C I would happily submit a patch, if you can point me in the right direction.

**Comment by Sweenu** [comment]
If I'm not wrong, this spacing comes from the `margin` argument. Putting it to zero will solve your problem I think.
Now if you want to keep this margin for multiple windows, you'll have to look into libqtile/layout/xmonad.py where you'll probably want to add a `single_margin` parameter (in the same way there's a `single_border_width` parameter) and add some conditionals for the margin size to be different if there's only a single window.

**Comment by bedax** [comment]
thanks for that @Sweenu, I'll give it a go and post back soon
