### ISSUE TITLE
Scratchpad Issues With MonadTall

### ISSUE THREAD

**Issue by TheArchNemesis** [qtile/qtile#1156]
Hey,
Not long ago a new feature was added to Qtile - scratchpad desktops.
I have long awaited this feature in Qtile, and tried to add a scratchpad desktop to my configuration. Unfortunately, i wasn't able to get it to work. 
I have copied the example from [here](http://docs.qtile.org/en/latest/manual/config/groups.html) into my configuration, and it hasn't worked correctly. instead of popping as a floating window on top of my current layout ( MonadTall ) a terminal window appeared as a part of my regular layout, a repeated press of the shortcut set to toggle the visibility of the terminal did absolutely nothing, after closing the appeared terminal window it haven't appeared after pressing the shortcut again.
Is there any way to fix this?

**Comment by dhannes** [comment]
The given example works for me, also for the MonadTall layout.

The ScratchPad /DropDown behaviour is basically as follows:
1)  the command of the DropDown is executed by `cmd_spawn` command of Qtile and the returned process id is remembered.
2) if a new client appears (hook: `client_new`), with that process id (determined by `net_wm_pid`) it is wrapped and stored by the Scratchpad group, set to floating and added to current group.
- if the a process is already spawned by (1), but no client window is determined yet (2),
pressing the shortcut again has no effect.

According to your description
- the client is added as tiled window
- pressing the shortcut again has no effect

it seems there is a problem in determining the process ids and reliably match the client window to the spawned process.

You might check that in a manual way by
1) spawn a process by using the spawn command in [qshell](http://docs.qtile.org/en/latest/manual/commands/qshell.html), for example `spawn("xterm")`.
2) use xprop in the spawned terminal to determine the net_wm_pid property by `xprop _NET_WM_PID`
3) the printed numbers should be equal.

**Comment by flacjacket** [comment]
@dhannes answer seems to have this covered. Feel free to reopen or ask more questions if more help is needed.
