### ISSUE TITLE
WLAN widget not working with with newer cards iwconfg vs. iw

### ISSUE THREAD

**Issue by s-hell** [qtile/qtile#1159]
Since a few days i'm trying to configure qtile and i found a issue with the wlan config.
I'm playing with an  Intel Corporation Centrino Advanced-N 6205 under funtoo with kernel 4.15.9-gentoo and =sys-kernel/linux-firmware-20180213

The wireless card doens't get recognized be iwconfig: no wireless extensions.

Both libraries, iwlib and python-wifi, are base on iwconfig. So in my case my card will never be recognized.

iw is a replacement for iwconfig. So any know a python library which uses iw?

Otherwise i think, i can write a wrapper for the iw command. Maybe expand the existing wlan widget. Any suggestions?

**Comment by s-hell** [comment]
#1162 

I've written a small wrapper for iw. If there is no python-wifi or iwlib. it will search for the iw binary to get all.
I didn't found an libraries for this, so i wrote this wrapper.
I hope i did everything right. This is my first pull request, so be patient ;-)

**Comment by flacjacket** [comment]
Is there still an issue using the network with your wireless card?
