### ISSUE TITLE
Make the Clock widget timezone-aware

### ISSUE THREAD

**Issue by dj-foxxy** [qtile/qtile#1170]
`Clock(format='%Z')` should print the timezone (`BST` for me). However, it's the empty string because the `datetime` created in `Clock._get_time()` does not set the `datetime`'s timezone. Here's the fix I'm using:

```python
class Clock(widget.Clock):
    def _get_time(self):
        now = datetime.datetime.now(datetime.timezone.utc).astimezone()
        return (now + self.DELTA).strftime(self.format)
```

**Comment by sux2mfgj** [comment]
I think the timezone is configured by the tz function.
https://github.com/qtile/qtile/blob/92bfafe2cf98789e531b2381c92eb689742c667c/libqtile/widget/clock.py#L32-L42

I tried to Europe/London timezone by below configuration.
```
widget.Clock(format='%a %d %b %I:%M %p', timezone='Europe/London'), 
```

**Comment by ramnes** [comment]
@dj-foxxy all good with @sux2mfgj answer? I'll go ahead and assume than yes, but feel free to ping me here if needed and I'll re-open the issue.

**Comment by dj-foxxy** [comment]
@ramnes 

@sux2mfgj requires explicitly declaring the timezone, were as I want it to use the system timezone (e.g., `/etc/localtime`)

**Comment by ramnes** [comment]
I just took a look at this and it seems difficult to achieve without adding a dependency like `dateutils` or `tzlocal`.

**Comment by ramnes** [comment]
Thanks @dj-foxxy, I've put your fix directly inside the codebase. :+1:

**Comment by dj-foxxy** [comment]
@ramnes no problem. Thanks for fixing.
