### ISSUE TITLE
DemuRun crashes because self.fontsize is not a string

### ISSUE THREAD

**Issue by dj-foxxy** [qtile/qtile#1171]
I think `self.fontsize` needs passing to `str()` first.
https://github.com/qtile/qtile/blob/a8143bfd9f3fc8f0cabf337255a289844a258de1/libqtile/extension/dmenu.py#L74

**Comment by flacjacket** [comment]
That's a good point, thanks for finding this. I'll push the fix for this, but feel free to cut a pull request for issues like this that you find!
