### ISSUE TITLE
It looks like your cairocffi was not built with xcffib support.

### ISSUE THREAD

**Issue by yatrisam** [qtile/qtile#1177]
I'm using debian(stretch) and following the official documentation qtile(building from source). I've installed all the dependencies and their headers. Here what I have done so far: 
pip3 install xcffib==0.5.1
pip3 install cairocffi==0.8.0
sudo python3 setup.py install
I've tried doing all of these: purge ~/.cache/pip, reinstalling cairocffi, etc. What am I missing?

**Comment by flacjacket** [comment]
You can check the cairocffi install, from a REPL, `import cairocffi` and look at `cairocffi.__file__`, it will be something like `/path/to/site-packages/cairocffi/__init__.py`, look at the file `/path/to/site-packages/cairocffi/_ffi.py`, the first few lines should look like:
```
# auto-generated file
import _cffi_backend
from xcffib._ffi import ffi as _ffi0
ffi = _cffi_backend.FFI('cairocffi._ffi',
```

**Comment by yatrisam** [comment]
import _cffi_backend
from xcffib._ffi import ffi as _ffi0

 ffi = _cffi_backend.FFI('cairocffi._ffi',
       _version = 0x2601,
This is what my _ffi.py looks like. 
What exactly should I look into this file?

**Comment by flacjacket** [comment]
Sam, sorry for not getting back to you. What I'm looking for is the xcffib import, that means that the cairocffi install was done correctly. This likely means that your cairo library does not have xcb support, and that needs to be rebuilt or re-installed.

**Comment by fmipsylone** [comment]
Hello,

Trying to install Qtile from sources on a "RPI 4 buster lite", I got the following error in Qtile build with cairocffi-1.2.0 installed with `pip`:
```
It looks like your cairocffi was not built with xcffib support.  To fix this:
  
    - Ensure a recent xcffib is installed (pip install 'xcffib>=0.5.0')
    - The pip cache is cleared (remove ~/.cache/pip, if it exists)
    - Reinstall cairocffi, either:
  
        pip install --no-deps --ignore-installed cairocffi
  
      or
  
        pip uninstall cairocffi && pip install cairocffi
  
  
  ----------------------------------------
  Failed building wheel for qtile
```
If I uninstall cairocffi installed from `pip` to use the debian package via:
```
pip3 uninstall cairocffi
sudo apt install python3-cairocffi
```
The `0.7.2` cairocffi version is installed on the system and Qtile builds correctly. 
In my tests the `python3-cairocffi` package installation did not add any missing dependencies. So it seems all required debian packages dependencies were satisfied before 'cairocffi' install via 'pip'.

Does something changed with xcffib support ? Or is it mandatory to use `cairocffi` from a distribution package ? Does we need another debian package headers dependencies to build ?

Thanks you guys for your replies

**Comment by BarreiroLeo** [comment]
> Hello,
> 
> Trying to install Qtile from sources on a "RPI 4 buster lite", I got the following error in Qtile build with cairocffi-1.2.0 installed with `pip`:
> 
> ```
> It looks like your cairocffi was not built with xcffib support.  To fix this:
>   
>     - Ensure a recent xcffib is installed (pip install 'xcffib>=0.5.0')
>     - The pip cache is cleared (remove ~/.cache/pip, if it exists)
>     - Reinstall cairocffi, either:
>   
>         pip install --no-deps --ignore-installed cairocffi
>   
>       or
>   
>         pip uninstall cairocffi && pip install cairocffi
>   
>   
>   ----------------------------------------
>   Failed building wheel for qtile
> ```
> 
> If I uninstall cairocffi installed from `pip` to use the debian package via:
> 
> ```
> pip3 uninstall cairocffi
> sudo apt install python3-cairocffi
> ```
> 
> The `0.7.2` cairocffi version is installed on the system and Qtile builds correctly.
> In my tests the `python3-cairocffi` package installation did not add any missing dependencies. So it seems all required debian packages dependencies were satisfied before 'cairocffi' install via 'pip'.
> 
> Does something changed with xcffib support ? Or is it mandatory to use `cairocffi` from a distribution package ? Does we need another debian package headers dependencies to build ?
> 
> Thanks you guys for your replies

Same problem with Raspberry 2B on RPi OS Lite (based on Debian Buster). Using apt's cairocffi package, Qtile can build.
