### ISSUE TITLE
no jump group

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#1179]
How can I set the startup of an app for example: Firefox automatically matches that group?
Group ('a', matches = [Match (wm_class = ['Firefox'])],
Terminal idle firefox "d" group and remain in that group did not change to "a"

Thank you in advance for your help.

**Comment by flacjacket** [comment]
I'm not sure what you're asking. The group you posted looks like what you'd need to have a group that will have Firefox launch to it. I'm not sure what you mean by "Terminal idle firefox "d" group and remain in that group did not change to "a"", can you clarify this?

**Comment by krive001** [comment]
Okay. 9 groups, 1,2,3,4,5,6,7,8,9 ,.
The "1" firefox is what you wrote above.
If I'm in another group, like "2", if you start a command, it will open in Group 1 but will not go there.

**Comment by Sweenu** [comment]
If I understand well, you could use something like that:

def app_or_group(group, app):

def f(qtile):

if qtile.groupMap[group].windows:

qtile.groupMap[group].cmd_toscreen()

else:

qtile.groupMap[group].cmd_toscreen()

qtile.cmd_spawn(app)

return f



You can then have `Key([mod], 'm', lazy.function(app_or_group('firefox', 'firefox'))),

**Comment by krive001** [comment]
not work

**Comment by krive001** [comment]
def app_or_group(group, app):
    def f(qtile):
        if qtile.groupMap[group].windows:
            qtile.groupMap[group].cmd_toscreen()
        else:
            qtile.groupMap[group].cmd_toscreen()
            qtile.cmd_spawn(app)
    return f


this is what I'm doing.

My problem is that if I click on a link in another application then a firefox tab will open but it will not be there.

**Comment by krive001** [comment]
def app_or_group (csoport, app): 
def f (qtile): 
ha qtile.groupMap [csoport] .windows: 
qtile.groupMap [csoport] .cmd_toscreen () 
más: 
qtile.groupMap [csoport] .cmd_toscreen () 
qtile.cmd_spawn app) 
visszatérés f

ez az, amit csinálok.

Az én problémám az, hogy ha egy másik alkalmazásra mutató linkre kattintok, akkor egy tűzjelző lap nyílik meg, de nem lesz ott.

tesztcsapat b "elindul a megkülönböztetés, kattintson a linkre.

**Comment by krive001** [comment]
def app_or_group(group, app):
def f(qtile):
if qtile.groupMap[group].windows:
qtile.groupMap[group].cmd_toscreen()
else:
qtile.groupMap[group].cmd_toscreen()
qtile.cmd_spawn(app)
return f

that's what I'm doing.

My problem is that if I click on a link to another application, a firefox tab opens but does not go there automatically.

test team "b" for example discord click on the link.

**Comment by krive001** [comment]
Not focus group

**Comment by m-col** [comment]
It's been 2 years so I'm going to assume that you figured it out :) 

If not, feel free to re-open and we can try to figure out a solution.
