### ISSUE TITLE
Confirming a url in firefox moves focus to window under the mouse

### ISSUE THREAD

**Issue by steveeJ** [qtile/qtile#1181]
The issue described in the topic has been bugging me for some time.
It can be very confusing when trying to navigate in firefox using the keyboard while the focus has switched to another window, as all the input goes to that window instead.

It happens only when `follow_mouse_focus = True` is set.

#### Steps to reproduce:
1. Launch firefox
1. Focus another window by moving the mouse on it
1. Focus firefox using keyboard shortcuts
1. Press ctrl+l to enter the address bar
1. Enter an address and press enter
1. Observe that the focus has moved to the window under the mouse

qtile version 0.10.7

**Comment by m-col** [comment]
Is this problem still happening?

Following the steps I cannot reproduce it, so I'm thinking that it has been fixed in the 2+ years since it was submitted!

**Comment by steveeJ** [comment]
@m-col I can't reproduce it anymore either, thanks for checking in.
