### ISSUE TITLE
mpd2 widget crashes

### ISSUE THREAD

**Issue by s-hell** [qtile/qtile#1183]
If there is no artist returned from mpd, mp2widget crashs:

> 
> Traceback (most recent call last):
>   File "/usr/lib64/python3.4/site-packages/qtile-0.11.1-py3.4.egg/libqtile/widget/base.py", line 512, in on_done
>     result = future.result()
>   File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
>     raise self._exception
>   File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/lib64/python3.4/site-packages/qtile-0.11.1-py3.4.egg/libqtile/widget/mpd2widget.py", line 125, in poll 
>     return self.update_status()
>   File "/usr/lib64/python3.4/site-packages/qtile-0.11.1-py3.4.egg/libqtile/widget/mpd2widget.py", line 135, in update_status
>     return self.formatter(status, current_song)
>   File "/usr/lib64/python3.4/site-packages/qtile-0.11.1-py3.4.egg/libqtile/widget/mpd2widget.py", line 182, in formatter
>     return fmt.format(play_status=play_status, **status)
> KeyError: 'artist'

**Comment by flacjacket** [comment]
Thanks for reporting this, I just pushed what I think should catch this more gracefully. If this is still an issue, feel free to reopen this!
