### ISSUE TITLE
Windows persisting even after closing and switching to a different desktop

### ISSUE THREAD

**Issue by 0paIescent** [qtile/qtile#1198]
Here is a link to a short video of what exactly is happening. https://imgur.com/a/chRf21G
Whenever I close a window it persists until I quit Qtile and log back in. Restarting or changing desktops doesn't have any effect. Does anyone have a solution for this?

**Comment by s-hell** [comment]
+1

**Comment by baldrianbandit** [comment]
This might be a behaviour of your compositor (e.g. xcompmgr, compton, ...). Disable it and see if anything changes. Which one do you use?

**Comment by ramnes** [comment]
I am not able to reproduce this. Does any of you guys have a 100% predictable way of reproducing this? @0paIescent @s-hell @baldrianbandit @dexic79

**Comment by bertobule** [comment]
First try of Qtile and i got this issue. Just switching to another desktop keep and the previous window is still displayed.
Reproduced on Ubuntu 18.04 fresh install and apt-get install qtile (qtile-0.10.7-2ubuntu2)
@ramnes

**Comment by ramnes** [comment]
@bertobule Hi, thanks for the comment! What video card / driver are you using? Do you have something like xcompmgr or compton running? If so, does it help to disable it?

**Comment by bertobule** [comment]
device: Intel Corporation HD Graphics 630
xorg driver: Loaded and initialized i965
Ubuntu 18.04 seems to be using Wayland just for gdm, but disabling it to go back on Xorg for gdm does not fix this issue.
I was not using compton, but using it fix the issue, no more windows artifacts !

**Comment by bertobule** [comment]
Using the HEAD of develop branch ( ba2b800d69980c7157d15439f7c7e5ec486d0779 ) also fix the issue, even without compton.
