### ISSUE TITLE
Unmaximize is not keeping order for monad layout

### ISSUE THREAD

**Issue by neworld** [qtile/qtile#1202]
This issue is conceptually similar to #1201. Fullscreen toggle should restore exactly the same state. 

### Reproduce

1. set monad layout
2. maximize master window
3. unmaximize it

### Expected

order of windows should be the same

### Actual

the unmaximized window was put to second place

### Visual

Yellow is master window in initial state. After maximize/unmaximize the red one takes position of master

![visual](https://user-images.githubusercontent.com/38703/44484951-cf97d580-a657-11e8-9fba-75d3be52bfaa.gif)

**Comment by ramnes** [comment]
related to #1114 and #1098

**Comment by ramnes** [comment]
I'm going to keep this issue open until it's resolved for this particular layout, but also lock it so that we centralize the discussion in #1482 as it concerns a bunch of other layouts. Thanks!

**Comment by ramnes** [comment]
@jwijenbergh says we can close this: https://github.com/qtile/qtile/issues/1482#issuecomment-1017304294

Feel free to comment and I'll reopen if needed. :)

**Comment by jwijenbergh** [comment]
I'm not sure, is this about maximized or fullscreen? The gif looks like fullscreen but the description is about maximized. Anyways a fix for maximized is in a local branch of mine that is a part of a larger pr
