### ISSUE TITLE
Kill all windows from a specified group

### ISSUE THREAD

**Issue by acuenat** [qtile/qtile#1203]
Hello,
i'm new to qtile so maybe it's something already possible but i'd like to be able to clean a group(meaning kill every window associated to this group) or even clean a group except the current focus.
Possibly adding methods to the Group class so we could do something like this?

c= Client()
c.group['web'].killallwindows()

Currently i don't know how to address a specific window (except the current focus which is c.window) with the client

**Comment by ramnes** [comment]
Hi @acuenat!

Thanks for the interesting feature idea. What is your use-case for it?

Feel free to open a PR if you feel you could tackle it, or simply wait that someone else does it. :wink:

**Comment by osimplex** [comment]
I don't know how to submit something, but I use this code for an "kill all windows":

Function definition
```
@lazy.function
def kill_all_windows(qtile):
	for window in qtile.currentGroup.windows:
		window.kill()
```

Function in use
`Key([mod, "control"], "k", kill_all_windows),	# Kill all windows`

**Comment by ramnes** [comment]
Thank you @osimplex for the nice snippet!

I feel that it's simple enough to add to a config so that we don't need to extend the core of Qtile.

@acuenat Feel free to comment if you disagree, and I'll reopen. :+1:

**Comment by acuenat** [comment]
Hello  @ramnes,

thanks @osimplex for the solution but it's only partialy solving the use case i had in mind. 
My use case i'm using with other wm is that i like to be able to set a key to set "specific layouts on different screens". For instance let's say i want to have 3 terminals on screen 1, 1 firefox on screen 2, an application x on screen 4, everything opened and nicely arranged on a single mod+key.
This is easily scriptable except that i need to clean the 3 screens from the eventual windows opened on them before.
If instead of currentGroup in the solution  above i can access a list of every currently used group by screen, that can do the trick but i don't know if such thing exists.
The other "nice to have" feature i mentioned in my first post is obviously if you have a group loaded with windows, to close all except the one you are using right now but this is probably possible with a condition in osimplex's solution.
Cheers

**Comment by ramnes** [comment]
> If instead of currentGroup in the solution above i can access a list of every currently used group by screen, that can do the trick but i don't know if such thing exists.

On that previous example, you can access to `qtile.screens` which is a list of screens, and on each screen you can do `screen.group.windows`.

See https://github.com/qtile/qtile/blob/develop/libqtile/manager.py to check everything you can do with that `qtile` object.

> The other "nice to have" feature i mentioned in my first post is obviously if you have a group loaded with windows, to close all except the one you are using right now but this is probably possible with a condition in osimplex's solution.

Indeed! This should work:

```python
@lazy.function
def kill_all_windows_except_current(qtile):
	for window in qtile.currentGroup.windows:
		if window != qtile.currentWindow:
			window.kill()
```

**Comment by osimplex** [comment]
Maybe, this for the close.

But, I don't have a multimonitor setup now for test this.

```
@lazy.function
def kill_all_screens_windows(qtile):
	for screen in qtile.screens:
		for window in screen.group.windows:
			window.kill()

@lazy.function
def kill_all_screens_windows_except_current(qtile):
	for screen in qtile.screens:
		for window in screen.group.windows:
			if window != qtile.currentWindow:
				window.kill()
```
