### ISSUE TITLE
Neo2 keyboard layout breaks hotkeys after Qtile restart

### ISSUE THREAD

**Issue by moritzschaefer** [qtile/qtile#1206]
This might be related to: https://github.com/qtile/qtile/issues/268

I use the neo keyboard layout on an antergos with qtile. Hotkeys I configured (for example):

> mod+n => go to first group
> mod+shift+n => move current window to first group

Everything works fine, until I restart qtile (for example due to a screen connect):
```
@hook.subscribe.screen_change
def restart_on_randr(qtile, ev):
    qtile.cmd_restart()
```
After that the hotkeys act in the following weird way:

> mod+n => move current window to first group
> mod+shift+n => no action

Interestingly, when I use the normal german keyboard layout, everything works as expected also AFTER a restart. 

Qtile version: 0.12.0
I have no idea how to start debugging this problem. Any suggestions?

Edit/"Workaround": The bug only arises when Qtile starts with neo-layout activated. When switching to the normal german keyboard before restarting Qtile and only switching back to neo after the restart, no issue can be observed.

**Comment by ramnes** [comment]
This is very strange indeed. Can you share your full configuration?

**Comment by moritzschaefer** [comment]
Sure. Here is it: 

https://github.com/moritzschaefer/dotfiles/tree/master/home/.config/qtile

This is my workaround in config.py btw: 
```

@hook.subscribe.startup
def startup():
    subprocess.call(['setxkbmap', 'de', 'neo'])  # workaround/fix
@hook.subscribe.screen_change
def restart_on_randr(qtile, ev):
    subprocess.call(['setxkbmap', 'de'])  # workaround/fix
qtile.cmd_restart()
```

(if I login with a "normal" layout and switch to neo after startup, everything works fine).

**Comment by moritzschaefer** [comment]
I am now using EXWM, which suffers from a similar, but handleable issue (when changing the keyboard layout, keyboard shortcut are still on their old keys on the keyboard).
However, since my problem seems to be too exotic to be of interest for anyone, I'll close this,

**Comment by tych0** [comment]
I suspect this is due to the call of setxkbmap on restart; don't you need to do `setkxbmap de neo` as you do on startup? Anyway, thanks for closing.

**Comment by julkip** [comment]
I'd really appreciate if this bug was fixed, it is the only thing that is keeping me right now from switching from i3 to qtile. It might be that this error occurs, since no real KeyReleaseEvent from releasing shift is ever sent with this layout. When I press shift I get a KeyPressedEvent for Shift and When I release I get KeyReleasedEvent from Caps_lock.

xev output:
`KeyPress event, serial 34, synthetic NO, window 0x3000001,
    root 0x1e8, subw 0x0, time 11977597, (165,648), root:(855,677),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x3000001,
    root 0x1e8, subw 0x0, time 11977741, (165,648), root:(855,677),
    state 0x1, keycode 50 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False`

**Comment by ramnes** [comment]
Did you try the workaround above based on hooks?

**Comment by julkip** [comment]
Yes, but either I'm doing something wrong, or it simply does not work. My config can be found here https://pastebin.com/mbNMLZT2

**Comment by tych0** [comment]
We ignore all KeyRelease events, so I doubt it's related (although it is odd...).

I still don't understand what the bug is, though. If you don't `setxkbmap de neo` on restart, why would you expect the `de neo` keys to work?

**Comment by SpringerJack** [comment]
I've been running into the same issue with the derivative neo_qwertz layout recently. This workaround seems to actually work wonders, but for completeness sake I'd like to add two things for future readers. 

Defining a restart function will make your life easier. Just replace all  ̀restart() ̀ calls with a call to something like: 
```
def restart_qtile():
    @lazy.function
    def __inner(qtile):
        subprocess.call(['setxkbmap', 'de'])
        qtile.restart()
    return __inner
```
and add the `startup` hook from above.

Secondly it was stated, that starting qtile with a troublesome keymap active seemed to be the problem. For me it seems like globally setting your keymap with `localectl` seems fine, you just need to override the users keymap when actually restarting qtile. Weirdly the initial startup works flawless despite the keymap.

**Comment by SpringerJack** [comment]
I've been running into this issue with a derivative keymap, so this seems like a good place to add some things.

For the workaround use 
```
@hook.subscribe.restart
def secure_kbd():
    subprocess.call(['setxkbmap', 'de'])

@hook.subscribe.startup
def set_keymap():
    subprocess.call(['setxkbmap', 'de', 'neo'])
```
These hooks really do it all for you at this point.

Also regarding this observation:
> The bug only arises when Qtile starts with neo-layout activated

For me setting my global keymap to neo via ̀localect ̀ and initially starting qtile with it seems fine. Overriding the keymap seems to only be necessary for restarting. That comes in handy when using different WMs or switching to another tty.
