### ISSUE TITLE
[SOLVED] Java Applet not shown - just gray background

### ISSUE THREAD

**Issue by dexic79** [qtile/qtile#1211]
Solution to be found here:
https://github.com/qtile/qtile/issues/1189
Although without explanation.
I have made the text a bit more clear with "java applet" and "background" for search.

Hello,

I use a java applet for work, which works fine with other window managers (I use xfce, before that gnome), but unfortunately I have only a grey background with qtile.

When I start it from terminal, I receive no error messages. For java, I use icedtea.

Please feel free to try starting it from:
https://dejan.mercaware.de
Click on the mx007 to start the applet.

Thank you in advance!

Cheers,
Dejan

**Comment by Sweenu** [comment]
Putting `wmname = 'LG3D'` in your config file should solve your problem.

If you don't want to do that, you can also try exporting the following environment variable: `_JAVA_AWT_WM_NONREPARENTING=1`
That should do it too.

**Comment by flacjacket** [comment]
The above should be the fix to this, feel free to reopen if this issue persists.
