### ISSUE TITLE
XDG_AUTOSTART

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#1213]
I think some sort of XDG_AUTOSTART support should be possible, maybe with the option to disable special entries [arch wiki article](https://wiki.archlinux.org/index.php/XDG_Autostart).
It might be more convenient to automatically have NetworkManager loaded via XDG instead of having to add it manually or put it explicitly into some autostart.sh. If I have time, I try to find a small solution.

**Comment by ramnes** [comment]
Hi @ep12!

Thanks for opening this issue. I didn't know about XDG_AUTOSTART but it looks like it does indeed solve a very common problem.

What do you think about using [dex](https://github.com/jceb/dex), just like [i3 people seems to do](https://faq.i3wm.org/question/2155/how-can-i-use-autostart-desktop-files-in-i3.1.html)? The answer on this last link seems completely applicable to Qtile also.

**Comment by CharString** [comment]
Would be cool if we could just

    import dex
    dex._autostart()

but I guess calling it the way I call my autostart.sh works...

**Comment by ep12** [comment]
Yep I saw that dex thingy... Since I'm using qtile on a laptop, a power-dependent setup would be quite fancy. Some kind of condinition-based preset with different backlight, system tray, update frequency settings... Maybe even colors to indicate that the ac adapter is plugged out. That would also be useful in combination with display hotplug stuff. Maybe some update_conditional_settings method, hook and class to organise the presets and have them kind of overlapping? For just autostarting apps dex might just be enough, but I prefer a well-designed python program over ten thousand little bash scripts. I don't have that much time currently, but maybe I will get the chance to dive deep in the source code and find out how all that magic stuff works... I'll leave it as it is for now........

**Comment by m-col** [comment]
> import dex
> dex._autostart()

This is already possible and will do what you want, just hook it:

```py
import dex
hook.subscribe.startup_once(dex._autostart)
```
