### ISSUE TITLE
Prompt widget cannot be focused from some windows

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#123]
Sometimes, windows can get into a state where when you activate the prompt widget it shows up, but keypresses are not sent to it. You can fix this by switching to a window which doesn't have this corrupted state and activating the prompt widget.

I'm not exactly sure how to reproduce it, but if you open the prompt widget and then switch focus for a while, usually you can see this. I realize this isn't a great description, so if someone else tackles it, feel free to pester me for more info.

**Comment by m-col** [comment]
Is this still an isue?

**Comment by ramnes** [comment]
Let's assume not considering how little activity that thread have seen recently. Feel free to reopen if needed! :)
