### ISSUE TITLE
Floating window always shows in the desktop whare they are opened first time

### ISSUE THREAD

**Issue by gspe** [qtile/qtile#1232]
Floating window, albert or kcalc, in this case, always open in the desktop where they was opened first.
For example if I open a float in desktop 1 and then switch to desktop 4 and try to reopen that float it doesn't display but if I switch back to desktop 1 I can see that floating window.

**Comment by MarcinWieczorek** [comment]
I can confirm.

**Comment by MaltheMM** [comment]
I don't know about floats, but when I launch albert for the first time after start up it will always show up on the same workspace afterwards.

**Comment by weeping-angel** [comment]
Yeah! It's annoying.

**Comment by comonadd** [comment]
Any progress on this?

**Comment by m-col** [comment]
I think https://github.com/qtile/qtile/pull/2766 fixes this, or at least improves it. If anyone is able to run that commit for a while and test it out for confirmation of it working (and no unexpected behaviour) that would be much appreciated.

**Comment by m-col** [comment]
It also fixes the same issue that keepassxc has when you kill the window and then later re-open it. Now it opens on the current group.

**Comment by m-col** [comment]
I believe #2766 fixed this but if not feel free to re-open.
