### ISSUE TITLE
layout.flip() at xmonad layouts and margin little error

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1236]
Qtile 0.12

When I use `lazy.layout.flip()` (on both monad layouts, margin > 0), all works as expected, except the position of master window.
The master window go plus some pixels in the direction of screen border. The master window touch screen border.
If I do `lazy.layout.flip()` again, all works as expected.

My config for monad layout:

```
def init_layout_theme():
	return {
		"border_width": 2,
		"margin": 2
	}
```

`layout_theme = init_layout_theme()`

`layout.MonadTall(**layout_theme)`

**Comment by ramnes** [comment]
I can confirm this.

With a 10px marging, before flip:

![Before flip](https://i.imgur.com/KZID2kB.png)

After flip:

![After flip](https://i.imgur.com/rUNW825.png)

**Comment by osimplex** [comment]
Maybe this will solve the issue (I don't know how to do tests, I'm not a developer):

In Xmonad.py there are two blocks like this at `_configure_specific` functions:
```
    # calculate client's x offset
        if self.align == self._up:  # up orientation
            if cidx == 0:
                # main client
                ypos = self.group.screen.dy
            else:
                # secondary client
                ypos = self.group.screen.dy + height_main
        else:  # right or down orientation
            if cidx == 0:
                # main client
                ypos = self.group.screen.dy + height_shared
            else:
                # secondary client
                ypos = self.group.screen.dy
```

Instead of `ypos = self.group.screen.dy + height_shared`, `ypos = self.group.screen.dy + height_shared - self.margin`.

**Comment by osimplex** [comment]
I tested this, and works.
Here is the diff:
```diff
36c36
< from libqtile.layout.base import _SimpleLayoutBase
---
> from .base import _SimpleLayoutBase
318c318
<                 xpos = self.group.screen.dx + width_shared - self.margin
---
>                 xpos = self.group.screen.dx + width_shared
875c875
<                 ypos = self.group.screen.dy + height_shared - self.margin
---
>                 ypos = self.group.screen.dy + height_shared
```
The first change is because I made it for my personal config.

**Comment by ramnes** [comment]
Thank you for raising the issue and for the fix, @osimplex!
