### ISSUE TITLE
Floating Layout border config not respected in Scratchpad

### ISSUE THREAD

**Issue by sjugge** [qtile/qtile#1237]
## Problem observed

When displaying a Scratchpad, a border with the default color `#0000ff` is shown rather then the configured styling for Floating layouts. [Screenshot](https://i.imgur.com/Fa4LfZf.png).

## Expected behaviour

Floating styling is applied to Scratchpad.

## Environment 

* OS: Arch Linux `4.19.2-arch1-1-ARCH`.
* Qtile version: `0.12.0-2`, installed through Pacman ([package info](https://www.archlinux.org/packages/community/any/qtile/)).
* Python versions: `3.7.1`.

## Reproduce

Run `qtile` with _default_ or _custom_ config (see below).

I'm starting `qtile` using `startx`, through `~/.xinitrc`.

### Default config

Based on package default and docs examples:

* [`default_config.py`](https://github.com/qtile/qtile/blob/develop/libqtile/resources/default_config.py) as referenced in the docs.
* scratchpad config added, based on [the docs](http://docs.qtile.org/en/latest/manual/config/groups.html?highlight=scratchpad).

Config used available as [gist](https://gist.github.com/sjugge/3ccd1ee5c243aeab2f4041183c393ba5), additions based on docs have been indicated with a comment: `# Added per docs.`.

2 Scratchpads are defined in this config:

* `F11`: `urxvt` terminal
* `F12`:  `urxvt` terminal running `qshell`

### Custom config

Based on the [`default_config.py`](https://github.com/qtile/qtile/blob/develop/libqtile/resources/default_config.py) as referenced in the docs, the documentation, [qtile-examples](https://github.com/qtile/qtile-examples) and custom config.

Config [available for reference in my dotfile repo](https://gitlab.com/sjugge/dotfiles/blob/db729b6427d88dabc814969c1ce1f49d4c185f0f/.config/qtile/config.py), (link at commit at time of creating this issue).
Note that [`color_config.py`](https://gitlab.com/sjugge/dotfiles/blob/db729b6427d88dabc814969c1ce1f49d4c185f0f/.config/qtile/color_config.py) is imported.

2 Scratchpads are defined in this config:

* `Super`+`t`: `terminator` terminal
* `Super`+`y`: `urxvt` terminal with Python REPL

## Additional info

I've been going through the issue queue on GitHub and the docs to find a solution for this, as I'm new to Qtile I assumed the issue was on my end. But after researching this and going through the code I have the impression that this may be a bug.

Any other relevant system config may be viewed in [my dotfiles repo](https://gitlab.com/sjugge/dotfiles), likely no relevant but linking to ensure transparency over my environment.

**Comment by ramnes** [comment]
I can't reproduce so far, the floating color is used as expected:

![orange](https://i.imgur.com/vmmYVHu.png)

**Comment by ramnes** [comment]
@sjugge I guess it is because you have two `Floating` layouts defined in your configuration. What if you add `**layout_border` to [the second one](https://gitlab.com/sjugge/dotfiles/blob/db729b6427d88dabc814969c1ce1f49d4c185f0f/.config/qtile/config.py#L389-404)?

**Comment by sjugge** [comment]
_facepalm_

@ramnes adding the styling config to the second `Floating` definition indeed resolves my issue. No idea how I managed to overlook that. Apologies for filling a bug report for this and thank you for the quick follow-up,  appreciate it!

**Comment by ramnes** [comment]
No worries, I wish we could solve all issues that fast!
