### ISSUE TITLE
Volume widget with Pulse Audio

### ISSUE THREAD

**Issue by trev-dev** [qtile/qtile#1244]
Hey there,

It looks like the Volume widget uses amixer. I don't have that installed. Instead, I have pulse audio (pactl). Are there any widgets floating around for that already or should I hack this myself?

**Comment by trev-dev** [comment]
Ahh nevermind, I was missing alsa-utils

**Comment by flacjacket** [comment]
There is #743 if that works, but there were some issues that the author never got back to so it isn't merged.
