### ISSUE TITLE
Custom drag callback

### ISSUE THREAD

**Issue by ruapotato** [qtile/qtile#1245]
I want a custom function called on a drag event. All the examples are using:
``Drag([mod],` "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position())``

I setup test with *args and tried: 
``Drag([mod2], "Button1", test())``

This just errors out with: 
``AttributeError: 'NoneType' object has no attribute 'check'``

In the end, I want to create a function that will open a window and start resizing it when a drag on the root windows is detected. Something like: https://www.youtube.com/watch?v=0DKDol1B1bo

**Comment by ramnes** [comment]
The third argument will be called, so you either have to get your `test` function to return a function, or simply to pass `test` without the parentheses. :wink:

**Comment by ruapotato** [comment]
It is getting called now! Thanks. :)
I cannot get the lazy.spawn('cmd') to do anything outside of the mose [] part tho.
Can you call lazy.spawn and set_size_floating() from my function? 
I need to create a window with a given size and placment. 

```
firstClick = []
OpenNew = False
def openNewWindow(*args):
  global OpenNew
  MoveX = args[1]
  MoveY = args[2]
  x = args[3]
  y = args[4]
  threshold = 50
  if MoveX > threshold or MoveY > threshold:
    if not OpenNew:
      #open new menu/terminal 
      lazy.spawn("xterm") #this dose nothing :S
      OpenNew = True
      debug ("OpenNew at " + str(x) + " " + str(y))
    else:
      #resize newly opened
      debug ("Resize " + str(x) + " " + str(y))
  else:
    OpenNew = False
    
    #lazy.window.set_size_floating()
  """Move window to x and y"""
  pass

...
Drag([mod2], "Button1",  lazy.function(openNewWindow))
...
```

**Comment by ramnes** [comment]
You can play with `qtile.currentWindow`, for example. See `libqtile/manager.py` for all the thing you could do with that `Qtile` instance. :wink:
