### ISSUE TITLE
Small windows end up fullscreen

### ISSUE THREAD

**Issue by ruapotato** [qtile/qtile#1247]
I'm useing 
`qtile.cmd_spawn("xterm")`
then
`newWin.place(x,y,width,height,2,None)`

This works fine. But when I click on anything, All the windows I opened become fullscreen. 
`auto_fullscreen` is False
and calling: `newWin.cmd_disable_maximize()` and `newWin.cmd_disable_fullscreen()` did not help

https://youtu.be/bvjCp56IzpM
config: https://bitbucket.org/hackersgame/qtile_lavinder/src/master/

**Comment by ramnes** [comment]
Isn't it because [you're using the Max layout](https://bitbucket.org/hackersgame/qtile_lavinder/src/c4ea6cde734e6ec91ebe664d606aed4d6d1d131e/config.py?at=master&fileviewer=file-view-default#config.py-237)?

What if you use Floating by default?

**Comment by ruapotato** [comment]
That did it! 

Thank you very much!
