### ISSUE TITLE
System statistics widgets not portable

### ISSUE THREAD

**Issue by ekollof** [qtile/qtile#1248]
Hi,
The widgets in qtile assume Linux. That's a bit myopic for us in the BSD camp. Can some of the widgets (Cpu/Net/Network) be rewritten using portable means? Maybe through pyspectator (<https://github.com/it-geeks-club/pyspectator>)?

**Comment by ramnes** [comment]
Hi @ekollof! 

We'd be glad to get PR for a BSD support on widgets. :+1:

**Comment by ramnes** [comment]
By the way, the `graph` module supposedly support BSD already: https://github.com/qtile/qtile/blob/develop/libqtile/widget/graph.py#L204

**Comment by ekollof** [comment]
Yup, the Cpu/Mem graphs work with the FreeBSD linprocfs module loaded, but that just implements Linux /proc on top of FreeBSD, and is admittedly somewhat of a hack. I'm kind of looking into more portable solutions. :)

I'll take a look at making things more portable when I have some spare time.

**Comment by ekollof** [comment]
See <https://github.com/qtile/qtile/pull/1250>

**Comment by elParaguayo** [comment]
Closing this. I believe some changes were made and many widgets are now using `psutil` module which should provide greater compatibility. Any ongoing issues should be raised in a new issue.
