### ISSUE TITLE
How to find X,Y position of mouse

### ISSUE THREAD

**Issue by ruapotato** [qtile/qtile#1249]
I cannot seem to find the x,y position of the mouse in the qtile scripting commands. Can this be done? 

I found:
`qtile.cmd_get_position()`
But I get the error `qtile has no attribute cmd_get_position`

**Comment by flacjacket** [comment]
What are you looking for with the mouse position? When do you want it? The position at a particular time? The only `cmd_get_position` I see is on the window.

**Comment by ruapotato** [comment]
I'm trying to find the mouse position relative to the screen in a callback function (in this case: handleMouseWheelUP)
```
mouse = [
  Click([mod2], "Button4", lazy.function(handleMouseWheelUp))
]
```

**Comment by ruapotato** [comment]
It looks like I have access to stuff in libqtile.manager
Is it possible to extend libqtile.manager to have a getMousePosition? At the moment I only see: 
mouseMap
grabMouse()

**Comment by ramnes** [comment]
Closing since #1305 got merged. Thanks!
