### ISSUE TITLE
Stack layout: lazy.layout.shuffle_up() & shuffle_down()

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1252]
These methods of Stack layout, instead of call the `shuffle` methods of base, call the `rotate` methods, so there isn't a shuffle.

Lines 279+ for `cmd_shuffle_up` and 284+ for `cmd_shuffle_down` at `stack.py`.

I don't know if Xmonad shuffle (lines 651+ and 657+) can be copied to Stack layout.

**Comment by flacjacket** [comment]
Thanks for pointing out these inconsistencies in our layouts! These should be simple fixes, sorry for letting these issues sit so long. Feel free to submit a PR for a fix if you get to it before us!

**Comment by osimplex** [comment]
Ref:
  * https://github.com/qtile/qtile/blob/master/libqtile/layout/stack.py -> `stack.py`
  * https://github.com/qtile/qtile/blob/master/libqtile/layout/base.py -> `base.py`


At `stack.py:278` there is `self.current_stack.rotate_up()`.
At `stack.py:283` there is `self.current_stack.rotate_down()`.

At `base.py` there are methods called `shuffle_up()` and ` shuffle_down()`. I think these methods work as `rotate_up()` and `rotate_down()`, they change the index of clients at `clients`, so maybe only a little replace is needed.

Solution:
* Change the method call
  1. (278) `self.current_stack.rotate_up()` -> `self.current_stack.shuffle_up()`
  1. (283) `self.current_stack.rotate_down()` -> `self.current_stack.shuffle_down()`

Obs.: I couldn't test this.

**Comment by ramnes** [comment]
Fixed, thanks!
