### ISSUE TITLE
Where are the xephyr script and other testing scripts in the Arch installation?

### ISSUE THREAD

**Issue by AndrewECarlson** [qtile/qtile#1253]
I just installed Qtile from the Arch Linux community repository, and I can't find this [xephyr script and test suite](http://docs.qtile.org/en/latest/manual/hacking.html#using-xephyr-and-the-test-suite) for testing my configuration.
Or is that intended primarily for Qtile developers?
In which case, what is the recommended method of checking/debugging your config.py before loading it?

**Comment by osimplex** [comment]
This you can find here: https://github.com/qtile/qtile/blob/develop/scripts/xephyr

I'm just a Qtile user. My config I check with python from terminal ($ python ~/.config/qtile/config.py) for sintax error, and other errors I don't know how to check, but usualy I have an fallback DE, and have an time when I have to do something with my Qtile config, so I can handle with WM config errors.

**Comment by ramnes** [comment]
Hello @AndrewECarlson!

As @osimplex said, `python ~/.config/qtile/config.py` is enough to validate that qtile won't crash when loading your application and, worst case scenario, it will use the default configuration on which you can read the logs located by default in `~/.local/share/qtile/qtile.log`.

Feel free to comment here or open another issue if needed, especially if you feel that something could be improved in the code base or documentation.
