### ISSUE TITLE
Configuration for dynamic screens (screen_change)

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1255]
I use a code to restart Qtile when I plug or unplug another screen in an laptop, for example. This to make Qtile do the screen process.

```python
@hook.subscribe.screen_change
def restart_on_randr(qtile, ev):
	qtile.cmd_restart()
```

Having:

```python
def init_screens():
	return [
		Screen(
			top = init_top_screen_widgets(),
			bottom = init_bottom_screen_widgets()
		),
		Screen(
			top = init_top_screen_widgets(),
			bottom = init_bottom_screen_widgets()
		)
	]
```

There is a Qtile function or another solution to make Qtile do the process of adding and removing screens as I plug and unplug monitors dynamicaly, without `qtile.cmd_restart()`?

**Comment by flacjacket** [comment]
No, currently there is no way to do this. We are currently in the middle of a refactor that should enable behavior like this by decoupling the configuration from the running manager.

**Comment by m-col** [comment]
This is now possible with `lazy.reload_config`. You can use that the same way as you are using restart:
```py
@hook.subscribe.screen_change
def restart_on_randr(_):
	qtile.cmd_reload_config()
```
This does all of the config-related stuff that restart does but it doesn't have the burden of restarting the whole process and is much smoother.
