### ISSUE TITLE
qtile and session management?

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#1256]
I do have a serious problem with `lightdm` [(which freaking hard-codes the -novtswitch X option)](https://github.com/CanonicalLtd/lightdm/blob/712a0254baf2bedf0370affbb3b54bc68c2aafc2/src/x-server-local.c#L507) and I might hunt that one down and use another method to login and I would need to save the current session and later restore it when I want to "lock"/"unlock" the screen. Can qtile manage sessions like xorg-xsm or similar or is it compatible with an existing session management program? I haven't really done a lot of research or experimenting but maybe someone already has a clue...

**Comment by ramnes** [comment]
Qtile is a window manager, not a session nor display manager, so I don't think its role is to handle that. What is it that you want to achieve, more precisely?

With LightDM you can use `dm-tool switch-to-greeter` to switch between users. If you really want to quit LightDM, I can recommend SLiM that works just great, although it is now considered deprecated. I use `i3lock` to lock the screen, whatever the DM or WM is.

**Comment by mchwalisz** [comment]
I'm using sddm (the kde session manager) and the following works ok to lock the screen:
```python
Key([mod], "l", lazy.spawn("/usr/lib/kscreenlocker_greet")),
```

**Comment by flacjacket** [comment]
I'll close this as the question was answered, if you have any other questions, please let us know!
