### ISSUE TITLE
Always on top floating windows

### ISSUE THREAD

**Issue by yousufinternet** [qtile/qtile#1260]
So I want to start by saying that I am sorry if this is not the right place for this post, I tried asking my question on the IRC channel (couldn't find any active sub reddit or forum), but I don't have constant access to internet/electricity (I live in Iraq) so I can't remain connected all the time and I might miss answers. 

My problem is that I want floating windows to remain always on top of tiled windows, the current behavior is that floating windows get covered by newly spawned windows. 
next I want to be able to apply this rule to some windows only (for example if I want to make mpv window playing youtube video always on top), and I want them to be sticky (always appear on the current active group). 

I couldn't figure out how to use the scripting commands on certain windows, groups, screens, root obj ... etc from the documentation. and the qtile-examples repository only contained very simple configurations with nothing to help me with my problem. 

So, to conclude I think the related hooks are: 
- client_new and client_focus, to run cmd_bring_to_front on a specific window whenever a new client is spawned or whenever the focus is changed 
- setgroup or changegroup (I don't know what the difference is exactly), to run cmd_togroup on the specified window to move it to the current group whenever the active group is changed 

But I don't know how to put everything together, how can I get the windows objects and run commands on them.. etc 

Thanks in advance for help, and sorry for my English, it is not my native language

**Comment by flacjacket** [comment]
I can't think of a simple way that we could do this, but this is definitely something that we can look into improving with our current floating layout.

**Comment by yousufinternet** [comment]
Thanks for the reply.. I thought that something could be setup with hooks, but I guess I just have to wait for future versions.

**Comment by yousufinternet** [comment]
I know it has been a long time since this was posted, but I have solved this in somewhat weird way: 

in qtile\config.py:
`@libqtile.hook.subscribe.focus_change
def float_mpv():
    subprocess.Popen(os.path.expanduser('~/.config/qtile/floating_mpv.py'))`

floating_mpv.py:
`def float_mpv():
    c = Client()
    floating_mpvs = [(w['id'], w['name'], w['group']) for w in c.windows()
                     if 'mpv' in w['name'] and w['floating']]
    if len(floating_mpvs) == 0:
        return
    for floating_mpv in floating_mpvs:
        c.window[floating_mpv[0]].bring_to_front()
        c.window[floating_mpv[0]].togroup()

    # This code runs only when the current group is changed, so that
    # correct window is focused instead of mpv window
    prv_grp = floating_mpvs[0][2]
    cur_grp = c.group.info()['name']
    focusHistory = c.groups()[c.group.info()['name']]['focusHistory']
    mpvs_were_last = len(focusHistory) > len(floating_mpvs) and len(floating_mpvs) > 0
    if mpvs_were_last and cur_grp != prv_grp:
        floating_mpvsnames = [w[1] for w in floating_mpvs]
        if all(wname in floating_mpvsnames for wname in
               focusHistory[-len(floating_mpvs):]):
            wid = [w['id'] for w in c.windows()
                   if w['name'] == focusHistory[-len(floating_mpvs)-1]
                   and w['group'] == cur_grp][0]
            c.window[wid].focus()`

**Comment by btwe** [comment]
I use a simple function in my config file:
```
def float_to_front(qtile):
    """
    Bring all floating windows of the group to front
    """
    for window in qtile.currentGroup.windows:
        if window.floating:
            window.cmd_bring_to_front()
```

Currently, I just bind it to a key, but of course this can also be subscribed to a hook.

**Comment by btwe** [comment]
> I can't think of a simple way that we could do this, but this is definitely something that we can look into improving with our current floating layout.

I agree that floating windows should always be on top of tiled windows. Until I made the function above, I had to search many times for hidden windows.
I remember from fvwm2 times, that they provided layers, into which windows could be grouped. Here, two layers would be sufficient, `tiled` below `floating`. I am not sure if that is something out of the X standards.

**Comment by g0josh** [comment]
> I use a simple function in my config file:
> 
> ```
> def float_to_front(qtile):
>     """
>     Bring all floating windows of the group to front
>     """
>     for window in qtile.currentGroup.windows:
>         if window.floating:
>             window.cmd_bring_to_front()
> ```
> 
> Currently, I just bind it to a key, but of course this can also be subscribed to a hook.

Thanks for this.Now that the floating windows are in front, how do you focus on the last one? I tried and ended up adding this to your snippet.
```python
def float_to_front(qtile):
    """
    Bring all floating windows of the group to front
    """
    for window in qtile.currentGroup.windows:
        if window.floating:
            window.cmd_bring_to_front()
            floating_windows.append(window)
    window.cmd_focus()
    qtile.cmd_simulate_keypress()
```
Now my question is, if I have multiple floating windows, how to switch between them?

**Comment by btwe** [comment]
> Now my question is, if I have multiple floating windows, how to switch between them? Or is there a way to get the current focused window ? If so I could get a list of floating windows and switch to the next one, which would be a dirty workaround to solve this problem.

Sorry, I have no solution for this at hand. For me, as soon as floating windows are in play, I' just use the mouse pointer

**Comment by YoloClin** [comment]
> Now my question is, if I have multiple floating windows, how to switch between them? Or is there a way to get the current focused window ? If so I could get a list of floating windows and switch to the next one, which would be a dirty workaround to solve this problem.

Sorry if I'm resurrecting a dead post but I solved this issue by adding the following to my config.py, it could do with some cleanup niceties (it might randomly reorder window stack as windows are added/removed or something) but it works and suits my use-case):

```python
floating_window_index = 0

def float_cycle(qtile, forward: bool):
    global floating_window_index
    floating_windows = []
    for window in qtile.current_group.windows:
        if window.floating:
            floating_windows.append(window)
    if not floating_windows:
        return
    floating_window_index = min(floating_window_index, len(floating_windows) -1)
    if forward:
        floating_window_index += 1
    else:
        floating_window_index += 1
    if floating_window_index >= len(floating_windows):
        floating_window_index = 0
    if floating_window_index < 0:
        floating_window_index = len(floating_windows) - 1
    win = floating_windows[floating_window_index]
    win.cmd_bring_to_front()
    win.cmd_focus()

@lazy.function
def float_cycle_backward(qtile):
    float_cycle(qtile, False)

@lazy.function
def float_cycle_forward(qtile):
    float_cycle(qtile, True)

keys = [
    ...
    Key([mod, alt], "period", float_cycle_forward),
    Key([mod, alt], "comma", float_cycle_backward),
]
```

m-col has another solution in https://github.com/qtile/qtile/issues/1693 which I'm only just reading, which may be of interest too.

**Comment by tusqasi** [comment]
@YoloClin that works really well for my case too!
