### ISSUE TITLE
Having new windows open to the right

### ISSUE THREAD

**Issue by zsebacher** [qtile/qtile#1262]
I just recently started using qtile, and I decided to go with the ratiotile layout as it is able to give me the perfect 2x2 layout ability that I am wanting right out of the box. However it seems that whenever a new window is launched in qtile it opens it to the left and moves the previous active window to the right. This just feels backwards to me and I would like to change it.

I went into the ratiotile.py file and changed where it was adding clients from appendHead to just append. I then recompiled the file and then reran the qtile installer, but I'm noticing the effect hasn't seemed to change. Is there another way to do this or am I doing it wrong?

**Comment by osimplex** [comment]
@zsebacher, append and appendHead are methods to set the position of the window in the list of clients. Look at `libqtile/layout/base.py`, line 454+.

The window placement is done at `libqtile/layout/ratiotile.py`, line 242+ (at 282+ there is the win.place([...]) call). This method is defined at `libqtile/window.py` 449+.

**Comment by flacjacket** [comment]
It looks like @osimplex 's change should fix this for you. If you can find a way to work this behavior into a the existing widget as a configuration parameter, we can try to find a way to integrate this into master. If you have any other questions, feel free to reopen, thanks!
