### ISSUE TITLE
root authentication request do not appears when gparted opens

### ISSUE THREAD

**Issue by ui3o** [qtile/qtile#1264]
Hi,

When I would like to open gparted program, normally a root authentication window comes up, but in qtile I never show this window.

Thank you for your reply.

**Comment by osimplex** [comment]
You need an authentication agent (v. https://wiki.archlinux.org/index.php/Polkit#Authentication_agents).

In Arch Linux ou can write an `autostart.sh` file like, if you have `polkit-gnome` installed:
```bash
#! /bin/bash 

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &	# Graphical authentication agent
```

Then put this at your `config.py` file:
```python
##### STARTUP PROGRAMS #####

@hook.subscribe.startup_once
def start_once():
	home = os.path.expanduser("~")
	subprocess.call([home + "/.config/qtile/autostart.sh"])
```
You need to import os for this python code.

Then, when Qtile start, the authentication agent will start too (and all programs you call at your `autostart.sh` file, like a compositor, a wallpaper setter _et cetera_).

**Comment by flacjacket** [comment]
It looks like @osimplex 's solution should work, feel free to re-open if you are still having issues, thanks!
