### ISSUE TITLE
Using obmenu

### ISSUE THREAD

**Issue by zero77** [qtile/qtile#1269]
I would like to use obmenu in qtile, how can i do this and is there any documentation any one can point me to, as i haven't found any so far.
Thanks

http://obmenu.sourceforge.net/

**Comment by zordsdavini** [comment]
As I understand, obmenu is menu editor. So, you just launch it and use. 
But I think you are asking from the running menu it self. For that we have keybindings as `Key([mod], 'r', lazy.spawn('some_command')),` or even add to mouse click: 
```
# -> Mouse
mouse = (
    Drag([], 'Button3', lazy.spawn('some_command')),
)
```
Check [http://docs.qtile.org/en/latest/manual/config/index.html](Qtile docs)

**Comment by zero77** [comment]
@zordsdavini 
Thanks, i will have a look.

**Comment by flacjacket** [comment]
Please feel free to reopen if you have more questions, I'm closing this for now, thanks!
