### ISSUE TITLE
no #qtile channel on OFTC

### ISSUE THREAD

**Issue by quinn** [qtile/qtile#1272]
This channel doesn't seem to exist (as far as I can see):

![image](https://user-images.githubusercontent.com/3764/51868522-32368100-231c-11e9-8134-1afa54478314.png)

No qtile. New to IRC, could be missing something super obvious....

**Comment by ramnes** [comment]
Where is that list from? I'm not sure why we don't appear in there, but #qtile does exist. If you want to join us, simply type `/join #qtile` in your IRC client once connected to OFTC.

**Comment by quinn** [comment]
@ramnes weird, was getting a Message(404) thing, but now it works. Sorry about that
