### ISSUE TITLE
Laptop battery monitoring on FreeBSD

### ISSUE THREAD

**Issue by andkem** [qtile/qtile#1274]
Hello!

The bundled battery monitoring widget only works on Linux. I had a look at adapting it to work on FreeBSD as well, but it was a pain to try and axe support into it because of the lack of a clear interface against batteries.

I ripped most of the code out and defined a well specified battery interface that clearly states what a battery implementation for a specific system is meant to supply. The code written can be found here: https://github.com/andkem/qtile/commit/a17d9cb9e625cfc95b8d147cd67aa2899eee6e75

I have been considering porting the Linux parts of the widgets into this new interface, but since I don't have a Linux laptop at the moment, it would be a bit of work seeing if I can borrow one or boot my own from a USB stick. Hence, I'm checking here to see if there would even be any interest in me porting the Linux parts to my own code base. If no one wants to use my code, there is really no point in doing work porting things I'm never going to use.

Thank you for any response!

**Comment by flacjacket** [comment]
This seems like a good thing to have, particularly with other fixes to our widget compatability in #1250. I'd say open up a PR for it!

**Comment by ramnes** [comment]
Closing since #1277 got merged in! Thanks @andkem.
