### ISSUE TITLE
How to make sure no windows start as floating?

### ISSUE THREAD

**Issue by wurosh** [qtile/qtile#1275]
Pretty self explanatory. I tried setting `float_rules=[]`, `float_rules=None`, and removing `layout.Floating()` from my `config.py` altogether. I just don't want to have to keep running `lazy.window.toggle_floating()` all the time because I really dislike handling floating windows, even if they are dialog boxes.

**Comment by flacjacket** [comment]
It looks like any attempt to blank out `float_rules` will result in the float rules being set to the default. If you change:
```
--- a/libqtile/layout/floating.py
+++ b/libqtile/layout/floating.py
@@ -91,7 +91,7 @@ class Floating(Layout):
         self.clients = []
         self.focused = None
         self.group = None
-        self.float_rules = float_rules or DEFAULT_FLOAT_RULES
+        self.float_rules = float_rules if float_rules is not None else DEFAULT_FLOAT_RULES
         self.no_reposition_match = no_reposition_match
         self.add_defaults(Floating.defaults)

```
does that fix this behavior?

**Comment by jjzmajic** [comment]
Shoot, sorry for the delay (exam time). I just tried it, no luck.

**Comment by jjzmajic** [comment]
Any updates?

**Comment by jjzmajic** [comment]
Bump in case anyone thought of a solution...

**Comment by ramnes** [comment]
It seems weird to me that @flacjacket diff does not work. Can you confirm that you tried to use the diff with `float_rules=[]` (and not `float_rules=None`)?

**Comment by jjzmajic** [comment]
@ramnes I'm surprised too, but yes, I tried with `[]`

**Comment by jjzmajic** [comment]
Did some more digging, but came out empty-handed. The logic of the patch should indeed fix the issue, but based on the above, it seems that `DEFAULT_FLOAT_RULES` replace `float_rules` some time before that takes effect.

**Comment by jjzmajic** [comment]
Hate to be a nag about this, just wondering if there are any updates? I can't seem to find the place where user vars are overwritten no matter how hard I look.

**Comment by m-col** [comment]
Looks like https://github.com/qtile/qtile/pull/1937 set the default `float_rules` to have no rules, so it can be omitted or set to `None` or `[]` to have no windows starting as floating.
