### ISSUE TITLE
python-cairocffi 1.0.0-1 update breaks qtile [Arch Linux]

### ISSUE THREAD

**Issue by kwestro** [qtile/qtile#1282]
on Arch Linux

If a user upgrades their system from python-cairocffi-0.9.0.1 to 1.0.0-1 Qtile will break and the user will not be able to log in

exec qtile from command line does not work either
The best solution for me at the moment is for me to downgrade python-cairocffi to 0.9.0.1
and at it to my pacman config ignore package list for the time being.

seems like this happens from time to time

https://github.com/qtile/qtile/issues/680

https://github.com/qtile/qtile/issues/994

**Comment by tych0** [comment]
Can you please post the full stack trace?

**Comment by tych0** [comment]
Based on other reports, this sounds like it's probably https://github.com/Kozea/cairocffi/issues/120

**Comment by kwestro** [comment]
from: ~/.local/share/qtile/qtile.log.1

[qtile.log.1.txt](https://github.com/qtile/qtile/files/2849107/qtile.log.1.txt)

**Comment by tych0** [comment]
Hm, I can't read the stack trace from that file somehow. Can you just paste it into a comment?

**Comment by kwestro** [comment]
I can't find the stack trace. probably deleted it.

It's been resolved and I'm able to upgrade to the latest version of cairocffi without it breaking qtile

Looks like it might an arch Linux maintainer issue.

the maintainer repackaged qtile and I upgraded that as well.

https://bugs.archlinux.org/task/61698?project=5

**Comment by dvzrv** [comment]
It seems like qtile requires a rebuild after each upgrade to python-{cairocffi,xcffib}, which I have communicated to the maintainers of those packages.
I hope we can reliably keep an eye on it from now on!

**Comment by flacjacket** [comment]
We rebuild qtile in our tests and we are seeing failures there, see https://travis-ci.org/qtile/qtile/jobs/490956510

**Comment by flacjacket** [comment]
Tests are running now (failures seem to be for another reason...)

**Comment by tych0** [comment]
Just for posterity, you can fix this if you have a broken cffi install by upgrading to something >= 1.0.2 with:

```
pip3 install --upgrade cairocffi
```
