### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by alikolling** [qtile/qtile#1292]
While building from source i'm getting various errors of invalid sintax like this:
  
`File "/usr/local/lib/python3.5/dist-packages/qtile-0.13.0-py3.5.egg/libqtile/widget/net.py", line 57
    lines: List[str] = []
         ^
SyntaxError: invalid syntax`

I don't know what to do. The pip installation doesn't work too. I get this:

`Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 346, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: cairocffi>=0.9[xcb] .dist-info directory not found`

**Comment by flacjacket** [comment]
We have moved the current master to be python 3.6 or greater. What distro
are you running that you have 3.5? How easy is it to move to 3.6? We could
back off our version requirement if this is too new.

**Comment by Ryuno-Ki** [comment]
Ubuntu 16.04 LTS is shipping with Python 3.5 for example. (But a PPA is available for bringing Python 3.6 in addition to the system).

[Debian stable is using Python 3.5 as well](https://packages.debian.org/en/stretch/python3).

**Comment by alikolling** [comment]
Thanks @flacjacket!! Going to try install later. Looks a really nice WM, congrats on the job.

**Comment by Ryuno-Ki** [comment]
Thanks, @flacjacket.
I'd guess, once [Ubuntu 16.04 reaches End of Life](https://wiki.ubuntu.com/Releases) (scheduled for April 2021), this could be reverted.

Debian Stable (Stretch) will reach [end of life somewhen between 2020 and 2022](https://wiki.debian.org/DebianReleases#Production_Releases).

**Comment by flacjacket** [comment]
Just pulled the changes in, if you still have any problems, feel free to reopen!
