### ISSUE TITLE
qtile-cmd -o window <windowid> ... doesn't convert <windowid> to an int

### ISSUE THREAD

**Issue by AntonyBlakey** [qtile/qtile#1298]

**Comment by przymusp** [comment]
I can confirm this, I have some temporary workaround (see code bellow), but this definitely is NOT the solution.

The problem with temporary solution is that not all numbers at command line should be treated as integers.

Possible solutions are:

  * predefined list of elements of path or arguments that should be treated as int
  * getting info on types of arguments from function objects.
 
Any suggestions ? 

```diff
110,115c110
<             if arg.isdigit():
<                 obj = obj[int(arg)]  # check if it is an item
<             else:
<                 obj = obj[arg]  # check if it is an item
< 
---
>             obj = obj[arg]  # check if it is an item
```

**Comment by whatacold** [comment]
@przymusp How about trying the `obj[int(arg)]` version first, then trying `obj[arg]` in addition if the it fails? It's a quite simple way in my opinion.
