### ISSUE TITLE
Scratchpad not working

### ISSUE THREAD

**Issue by mrndrsn** [qtile/qtile#1302]
I got an issue configuring QTile with the scratchpad.
It says me that the scratchpad key is unknown and i don't know how
to handle this.
Maybe you can take a look at my configuration:
https://pastebin.com/vr67nfAk

The QTile log output is:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/johndoe/.config/qtile/config.py", line 126, in <module>
    Key([mod], i.name, lazy.group[i.name].toscreen()),
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 60, in __init__
    raise utils.QtileError("Unknown key: %s" % key)
libqtile.utils.QtileError: Unknown key: scratchpad
```

**Comment by osimplex** [comment]
I think this is not about Scratchpad.

Part of your log first:
```python
File "/home/johndoe/.config/qtile/config.py", line 126, in <module>
    Key([mod], i.name, lazy.group[i.name].toscreen()),
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 60, in __init__
    raise utils.QtileError("Unknown key: %s" % key)
libqtile.utils.QtileError: Unknown key: scratchpad
```

Parts of your config file:
```python
groups = [
        ScratchPad("scratchpad", [
```
```python
for i in groups:
    keys.extend([
        Key([mod], i.name, lazy.group[i.name].toscreen()),
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name)),
    ])
```

Well when you run the last block of code, at the first loop of for, Python try something like this:
```python
keys.append(Key([mod1], "scratchpad", lazy.group["scratchpad"].toscreen())
```
This happens because Python will see your Scratchpad at group list as a Group, so will get the name of Scratchpad group, and send as a keyname, and there is not a key "scratchpad".

You can change your Scratchpad group name to a valid keyname, or can do somenthing to mount your parts of Qtile graph like this:
```python
# Fundamental elements
keys = init_keys()
mouse = init_mouse()
floating_layout = init_floating_layout()
groups = init_groups()
dgroups_app_rules = init_rules()
screens = init_screens()
widget_defaults = init_widget_defaults()
	
# Append some elements
keys += init_group_keybindings(groups)
groups += init_scratchpad()
keys += init_dropdown_keybindings()
```
First init your basic keybindings and your basic groups, then your group related keybindings, then init your scratchpad groups, then init your dropdown related keybindings.

**Comment by whatacold** [comment]
Ah, @osimplex is right, I was just bit by the exact error.

**Comment by ramnes** [comment]
Thank you @osimplex for digging into this! @mrndrsn, do not hesitate to open another issue if you still have this problem, or another.

**Comment by emanuelep57** [comment]
Not working for me right now

**The issue I get :**  
2021-11-14 23:21:25,222 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-11-14 23:21:25,657 ERROR libqtile manager.py:load_config():L116 Error while reading config file (No such key: scratchpad)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 114, in load_config
    self.config.validate()
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 125, in validate
    raise ConfigError("No such key: %s" % k.key)
**libqtile.confreader.ConfigError: No such key: scratchpad**


**My code (I literally just copied from documentation):**

from libqtile.config import Key, Group, ScratchPad, DropDown
from libqtile.lazy import lazy
from .keys import keys, mod
from libqtile.command import lazy

groups = [
    ScratchPad("scratchpad", [
        DropDown("term", "alacritty", opacity=0.8),
       DropDown("qshell", "urxvt -hold -e qshell",
                 x=0.05, y=0.4, width=0.9, height=0.6, opacity=0.9,
                 on_focus_lost_hide=True) ]),
    Group("a"),
]

**Comment by m-col** [comment]
@osimplex's comment above explains why the error is happening. Take a read of that and if you do not understand the solution then please post your **entire** config.

**Comment by emanuelep57** [comment]
> @osimplex's comment above explains why the error is happening. Take a read of that and if you do not understand the solution then please post your **entire** config.

Thanks, I fixed by calling the scratchpad "2" (valid group name) as suggested.

**Comment by m-col** [comment]
I suspect you don't want to bind a key to that - you may instead want to move the for loop creating your key bindings to after you add the scratchpad to the list

**Comment by emanuelep57** [comment]
[**My code**](https://pastebin.com/2FfgEhSS)
Yeah actually this solution doesn't seem very efficient. May you help me out so I can get what do you mean? Thanks a lot.

**Comment by m-col** [comment]
Sure - you can take out the scratchpad and append it to `groups` at the very end:
```py

from libqtile.config import Key, Group, DropDown, ScratchPad
from libqtile.lazy import lazy
from .keys import keys, mod
 
groups = [
          Group('1', label="1"),
          Group('2', label="2"),
          Group('3', label="3"),
          Group('4', label="4"),
          Group('5', label="5"),
          Group('6', label="6"),
          Group('7', label="7"),
          Group('8', label="8"),
          Group('9', label="9")
]
 
for i in groups:
    keys.extend([
 
        Key([mod],i.name,lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),
 
        Key([mod], "Right", lazy.screen.next_group(),
            desc="Switch to next group"),
 
        Key([mod], "Left", lazy.screen.prev_group(),
            desc="Switch to previous group"),
 
        Key([mod, "shift"],i.name,lazy.window.togroup(i.name, switch_group=True),
            desc="Switch to & move focused window to group {}".format(i.name)),
 
        Key([], 'F12', lazy.group["2"].dropdown_toggle('term')),
])

groups.append(
    ScratchPad("2", [
            DropDown("term", "alacritty", opacity=0.8),
             ]),
)
```

**Comment by emanuelep57** [comment]
> Sure - you can take out the scratchpad and append it to `groups` at the very end:
> 
> ```python
> from libqtile.config import Key, Group, DropDown, ScratchPad
> from libqtile.lazy import lazy
> from .keys import keys, mod
>  
> groups = [
>           Group('1', label="1"),
>           Group('2', label="2"),
>           Group('3', label="3"),
>           Group('4', label="4"),
>           Group('5', label="5"),
>           Group('6', label="6"),
>           Group('7', label="7"),
>           Group('8', label="8"),
>           Group('9', label="9")
> ]
>  
> for i in groups:
>     keys.extend([
>  
>         Key([mod],i.name,lazy.group[i.name].toscreen(),
>             desc="Switch to group {}".format(i.name)),
>  
>         Key([mod], "Right", lazy.screen.next_group(),
>             desc="Switch to next group"),
>  
>         Key([mod], "Left", lazy.screen.prev_group(),
>             desc="Switch to previous group"),
>  
>         Key([mod, "shift"],i.name,lazy.window.togroup(i.name, switch_group=True),
>             desc="Switch to & move focused window to group {}".format(i.name)),
>  
>         Key([], 'F12', lazy.group["2"].dropdown_toggle('term')),
> ])
> 
> groups.append(
>     ScratchPad("2", [
>             DropDown("term", "alacritty", opacity=0.8),
>              ]),
> )
> ```



> Sure - you can take out the scratchpad and append it to `groups` at the very end:
> 
> ```python
> from libqtile.config import Key, Group, DropDown, ScratchPad
> from libqtile.lazy import lazy
> from .keys import keys, mod
>  
> groups = [
>           Group('1', label="1"),
>           Group('2', label="2"),
>           Group('3', label="3"),
>           Group('4', label="4"),
>           Group('5', label="5"),
>           Group('6', label="6"),
>           Group('7', label="7"),
>           Group('8', label="8"),
>           Group('9', label="9")
> ]
>  
> for i in groups:
>     keys.extend([
>  
>         Key([mod],i.name,lazy.group[i.name].toscreen(),
>             desc="Switch to group {}".format(i.name)),
>  
>         Key([mod], "Right", lazy.screen.next_group(),
>             desc="Switch to next group"),
>  
>         Key([mod], "Left", lazy.screen.prev_group(),
>             desc="Switch to previous group"),
>  
>         Key([mod, "shift"],i.name,lazy.window.togroup(i.name, switch_group=True),
>             desc="Switch to & move focused window to group {}".format(i.name)),
>  
>         Key([], 'F12', lazy.group["2"].dropdown_toggle('term')),
> ])
> 
> groups.append(
>     ScratchPad("2", [
>             DropDown("term", "alacritty", opacity=0.8),
>              ]),
> )
> ```

Thanks a lot, that's very kind of you! The only issue I see with this solution is when I press "mod +2" it will enable the scratchpad, isn't there a way to use the scratchpad as a normal dropdown terminal e.g. guake in any workspace?

**Comment by emanuelep57** [comment]
> I suspect you don't want to bind a key to that - you may instead want to move the for loop creating your key bindings to after you add the scratchpad to the list



> Sure - you can take out the scratchpad and append it to `groups` at the very end:
> 
> ```python
> from libqtile.config import Key, Group, DropDown, ScratchPad
> from libqtile.lazy import lazy
> from .keys import keys, mod
>  
> groups = [
>           Group('1', label="1"),
>           Group('2', label="2"),
>           Group('3', label="3"),
>           Group('4', label="4"),
>           Group('5', label="5"),
>           Group('6', label="6"),
>           Group('7', label="7"),
>           Group('8', label="8"),
>           Group('9', label="9")
> ]
>  
> for i in groups:
>     keys.extend([
>  
>         Key([mod],i.name,lazy.group[i.name].toscreen(),
>             desc="Switch to group {}".format(i.name)),
>  
>         Key([mod], "Right", lazy.screen.next_group(),
>             desc="Switch to next group"),
>  
>         Key([mod], "Left", lazy.screen.prev_group(),
>             desc="Switch to previous group"),
>  
>         Key([mod, "shift"],i.name,lazy.window.togroup(i.name, switch_group=True),
>             desc="Switch to & move focused window to group {}".format(i.name)),
>  
>         Key([], 'F12', lazy.group["2"].dropdown_toggle('term')),
> ])
> 
> groups.append(
>     ScratchPad("2", [
>             DropDown("term", "alacritty", opacity=0.8),
>              ]),
> )
> ```

Thanks a lot for your kindness and availability! Altough, forgive me for my ignorance in matter, but is there a way to use the scratchpad as a normal dropdown terminal? e.g. guake? What I mean, not binding it to a specific workspace, make it work in any workspace normally

**Comment by emanuelep57** [comment]
> Sure - you can take out the scratchpad and append it to `groups` at the very end:
> 
> ```python
> from libqtile.config import Key, Group, DropDown, ScratchPad
> from libqtile.lazy import lazy
> from .keys import keys, mod
>  
> groups = [
>           Group('1', label="1"),
>           Group('2', label="2"),
>           Group('3', label="3"),
>           Group('4', label="4"),
>           Group('5', label="5"),
>           Group('6', label="6"),
>           Group('7', label="7"),
>           Group('8', label="8"),
>           Group('9', label="9")
> ]
>  
> for i in groups:
>     keys.extend([
>  
>         Key([mod],i.name,lazy.group[i.name].toscreen(),
>             desc="Switch to group {}".format(i.name)),
>  
>         Key([mod], "Right", lazy.screen.next_group(),
>             desc="Switch to next group"),
>  
>         Key([mod], "Left", lazy.screen.prev_group(),
>             desc="Switch to previous group"),
>  
>         Key([mod, "shift"],i.name,lazy.window.togroup(i.name, switch_group=True),
>             desc="Switch to & move focused window to group {}".format(i.name)),
>  
>         Key([], 'F12', lazy.group["2"].dropdown_toggle('term')),
> ])
> 
> groups.append(
>     ScratchPad("2", [
>             DropDown("term", "alacritty", opacity=0.8),
>              ]),
> )
> ```

Thanks a lot man! It fixed and works fine!!

**Comment by m-col** [comment]
Awesome, no problem
