### ISSUE TITLE
widget memory used not correct

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#1303]
Update memory.py 31-32 

 val[key] = int(uv[0]) // 1024
    val['MemUsed'] = val['MemTotal'] + val['Shmem'] - val['MemFree'] - val['Buffers'] - val['Cached'] - val['SReclaimable']

correcz.

**Comment by arcolinuxz** [comment]
![ArcoLinux-2019-05-21-1558419064_screenshot_1600x900](https://user-images.githubusercontent.com/36679406/58072752-f2ccc280-7ba0-11e9-8a84-14bae46a5f74.jpg)

You can see in the image **3 measurements** of the memory.

On top in the bar of Qtile you see a very high memory usage.

Our users ask us why this measurement differs from htop and conky and others.

You can compare with htop and the conky measurement. They are both the same.

Can you take a look as to why qtile reports a different and higher number of memory usage?
Tiling window managers are known to be low in memory usage - that is their selling point.
That is why we find it to be strange.

**Comment by ramnes** [comment]
This shouldn't be a problem anymore with the newest version of the memory widget. Thanks!
