### ISSUE TITLE
GroupBox continues to show old group names

### ISSUE THREAD

**Issue by lem0n4de** [qtile/qtile#1315]
After fixing a ConfigError in config or adding new groups to it and restarting QTile, GroupBox continues to show old tags.

For example, I have 5 tags at start: `1 2 3 4 5`
After I remove "5" and add "6" GroupBox shows it like: `1 2 3 4 6 5`

or after fixing a config error: `1 2 3 4 5 a s d f u i o p`

**Comment by ramnes** [comment]
Yep, I've already seen this. Thanks for the bug report @lem0n4de!

**Comment by zordsdavini** [comment]
Is this bug? I have this issue, too, then I migrated from asdfuiop to numeric. But it is enough to start qtile from the begining and you will have correct groups

**Comment by zordsdavini** [comment]
from other hand @whatacold did fix on this that @tych0 closed

**Comment by ramnes** [comment]
https://github.com/qtile/qtile/pull/1391#issuecomment-623138218
