### ISSUE TITLE
Completely transparent bar background ? 

### ISSUE THREAD

**Issue by g0josh** [qtile/qtile#1320]
Is it possible to have a completely transparent background with only widgets visible? I have been playing with Qtile for a few weeks now (i3 + polybar user previously), and being into python I am happy how flexible it is. Although I was able to set opacity for the whole bar (including widgets), I could not find a way to make just the background completely transparent. The bar draws `#000000` even though I set  it to `ff0000.00`. 
PS: I read about a closed issue(#853 ) about the same matter, the response said it is not possible as of 2016, wondering if there is any update since then!

**Comment by tych0** [comment]
It might be, with some combination of clever setting of the alpha with what's in `libqtile/drawer.py`. See https://cairocffi.readthedocs.io/en/stable/api.html#cairocffi.Context.set_source_rgba ; I think basically if you set the background alpha to 0 and run a compositor, you might (?) get it to work.

**Comment by g0josh** [comment]
Thanks @tych0, I guess that's how it's done currently,

This is from `drawer.py`
```python
def set_source_rgb(self, colour):
        if type(colour) == list:
            if len(colour) == 0:
                # defaults to black
                self.ctx.set_source_rgba(*utils.rgb("#000000"))
            elif len(colour) == 1:
                self.ctx.set_source_rgba(*utils.rgb(colour[0]))
            else:
                linear = cairocffi.LinearGradient(0.0, 0.0, 0.0, self.height)
                step_size = 1.0 / (len(colour) - 1)
                step = 0.0
                for c in colour:
                    rgb_col = utils.rgb(c)
                    if len(rgb_col) < 4:
                        rgb_col[3] = 1
                    linear.add_color_stop_rgba(step, *rgb_col)
                    step += step_size
                self.ctx.set_source(linear)
        else:
            self.ctx.set_source_rgba(*utils.rgb(colour))

def clear(self, colour):
      self.set_source_rgb(colour)
      self.ctx.rectangle(0, 0, self.width, self.height)
      self.ctx.fill()
      self.ctx.stroke()
```
But does not work as expected

**Comment by tych0** [comment]
@g0josh I don't think that's how it's done currently; we don't pass an alpha anywhere as far as I can tell, so it uses the default of 1. You'd have to change the code to pass 0 somehow.

**Comment by g0josh** [comment]
Thanks for taking the time @tych0. I have set my bar background to `#ff0000.0` my bar config. But the background renders black with some symbols and glyphs (probably remains of the previous render). I am running compton as well.
Here is my bar config,

Inside ~/.config/qtile/config.py
```
screens = []
for n in range(NUM_SCREENS):
    screens.append(
        Screen(
            top=bar.Bar(
                widgets=getWidgets(n),
                size=border_font['fontsize'] - 1,
                background="#ff0000.0", opacity=1
            )
        )
    )
```

I can see that `drawer.py` gets the colors from `utils.rgb()`, which does the right thing by separating RGB and alpha channels. But the result is just not there. I have been stumped on this.
Here's a screenshot
[
![Screenshot from 2020-05-09 14-43-00](https://user-images.githubusercontent.com/24892654/81464580-4e56ec80-9206-11ea-85f6-d757f0a0fb29.png)
](url)
Any help is greatly appreciated. Thanks !

**Comment by g0josh** [comment]
Is it connected to this issue -> #1059 ?

**Comment by ramnes** [comment]
I was about to reopen but I'll keep it close in favor of #1722 if you don't mind. :)
