### ISSUE TITLE
Android Studio hiding itself after startup

### ISSUE THREAD

**Issue by Borwe** [qtile/qtile#1327]
Reproduction:

- Just get Android Studio, install, it, open it, finish the setting up stage, then open it again.
- After it shows loading screen, wait like 2 seconds.
- Android Studio window just disapears, but the resources it uses show prove that it runs.
- Restarting qtile shows that now it's in a static state, appearing on all groups/screens like some background image, but operatable.

Version: 0.13.0

Temporary workaround:
```
#for handling android studio hiding itself
@hook.subscribe.client_name_updated
def fixAndroidStudio(w):
    if w.name == "Welcome to Android Studio":
        for i in range(5):
            time.sleep(5)
            w.unhide()
```

I didn't notice any other errors affecting any other window, just the Android Studio instance.
Android Studio version 3.4.1

**Comment by ramnes** [comment]
Hello @Borwe, thanks for opening this issue. Does adding `wmname = "LG3D"` in your config fix this?

**Comment by Borwe** [comment]
It was actually there while the error still was happening.

**Comment by oboingo** [comment]
I can confirm this issue.  Same version of qtile and a new install of Android Studio.  The temp workaround seems to work. I also have the wmname = "LG3D" in my config.

**Comment by ramnes** [comment]
I think this should be fixed in master. Can someone confirm?

**Comment by lkadalski** [comment]
Android Studio 4.0, Qtile 0.15.1 
I don't see such behavior. Everything runs smoothly.

**Comment by ramnes** [comment]
Thanks for the confirmation!
