### ISSUE TITLE
Browser (Chromium) loses authorization after reboot because of no policy kit running

### ISSUE THREAD

**Issue by soulmare** [qtile/qtile#1331]
In Qtile (Ubuntu 18), browser (Chromium) loses authorization at Google after reboot, and at other websites also. It was because of policy kit not running. Probably, it deserves to be mentioned in install notes for Qtile, that one must install and launch policy kit to run some apps properly.
In case of Chromium, it does not give any explicit alerts in UI, so it was not very easy to realize why this happens.
For Ubuntu, I did that:
1. Installed policykit:
    sudo apt install policykit-1-gnome
2. Added to Qtile's autostart.sh line to launch it:
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

**Comment by ramnes** [comment]
How do you start Qtile? I've never had to run polkit myself on Ubuntu, LightDM (I think) takes care of it.

**Comment by soulmare** [comment]
I'm starting it from login screen, selecting Qtile from the menu instead of default Gnome. And in Ubuntu 18 there's no LightDM, it is now Gnome and I think the login manager here is named GDM3. When started Gparted from console, it gave me an error like "No polkit authentication agent found".

**Comment by soulmare** [comment]
Probably, there was no exact need to install policykit-1-gnome package and there was another way to manually start default Ubuntu's polkit, but that was just the first workaround I've googled and it worked for me.

**Comment by osimplex** [comment]
This is not a problem with Qtile, maybe a topic that can be added to documentation.
Here I also have a `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &` in my `autostart.sh`. No problem. (v. https://wiki.archlinux.org/index.php/Polkit#Authentication_agents)

To add in docs:
"Qtile is only a WM (with a bar that you can use), so you will need a authentication agent."
