### ISSUE TITLE
Memory leak on handling windows, maybe

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1342]
I use mpv with mps-youtube to watch youtube videos. So, I'm often opening then closing windows.

So, I can observe with `ps aux | grep qtile` an memory usage increase across the time. I say on window handling because I observe major memory usage increase over time when I, example, watch several videos and the check memory usage, always there is a greater memory usage increase than on days of less intensive window open then close use.

**Comment by tych0** [comment]
The python allocator pools memory and doesn't release it back to the kernel, so I think this is (unfortunately) expected behavior. I've looked around for some ways to get python to flush its memory pools in long running processes, but I haven't found anything interesting :(
