### ISSUE TITLE
NetGraph always report "maximum" network activities

### ISSUE THREAD

**Issue by actbusy** [qtile/qtile#1353]
Hi,

Just want to point out that the `NetGraph` widget always "maxes out" in v0.14.2.
The graph used to rise/fall according to last sampled network activity.

https://github.com/qtile/qtile/blob/833e7f67256a2c54a29cfda3ccd94486f8e00a83/libqtile/widget/graph.py#L325-L330
`net[self.interface].bytes_sent` and `bytes_recv` return cumulative values.

Maybe `NetGraph` should take the difference between readings (as per before using psutil)?

Thanks.

**Comment by ramnes** [comment]
Hello @actbusy, thank you for reporting this!

Yes, I guess this is a regression introduced with the new `psutil` implementation in #1250. Would you like to work on a fix for this?

**Comment by actbusy** [comment]
Hi @ramnes, yes I will be glad to help.

**Comment by ramnes** [comment]
Fixed with #1357. Thank you again!
