### ISSUE TITLE
Generate a list of all lazy commands

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1360]
See #1358 for rationale.

We should have all the available lazy commands listed in the documentation, either on the ["Lazy objects"](http://docs.qtile.org/en/latest/manual/config/lazy.html) or directly along the resource that provide them (for example on the ["Built-in Layouts"](http://docs.qtile.org/en/latest/manual/ref/layouts.html) page).

**Comment by elParaguayo** [comment]
I'm looking at lazy docs and widget commands.
