### ISSUE TITLE
Exception in Battery widget

### ISSUE THREAD

**Issue by heitzmann** [qtile/qtile#1361]
In `LinuxBattery`, the implementation searches for the correct files to get batttery information from and uses the first it finds. However, it reports missing files as exceptions in the log. I believe this is incorrect, since the behavior is expected is the file name differs. The bad line is: https://github.com/qtile/qtile/blob/master/libqtile/widget/battery.py#L235

Also worth changing: the try block should only contain the `open` statement and the `except` should only catch `FileNotFoundError`—everything else should be properly raised.

I can make a PR if you prefer.

**Comment by ramnes** [comment]
Hey @heitzmann, thanks for reporting this! A PR would be very nice indeed.
