### ISSUE TITLE
Migration issues to 0.14.2

### ISSUE THREAD

**Issue by btwe** [qtile/qtile#1363]
Dear all, 

archlinux recently upgraded to 0.14.2
This resulted in an incompatible configuration at some elementary places and qtile did not start. I just want to share my migration steps with others here.

1. My first issue have been the graph widgets (CPUGraph, MemoryGraph, NetGraph), which could not be initialized on startup and thus qtile failed to start. The problem was a missing dependency to `python-psutils`, which I think is an issue with archlinux packaging. But it seems to be new dependency by qtile. Installing this solved this point easily.

2. The main `Qtile` object which is passed to a `func` through `lazy.function(func)` seems to have changed. I faced these at two locations:
- `AttributeError: 'Qtile' object has no attribute 'groupMap'`
- `AttributeError: 'Qtile' object has no attribute 'currentLayout'`
After reading some code, I realized that this can be solved by simply changing these to `qtile.current_group.layout` and qtile.groups_map` respectively.
```
% sed -i 's/groupMap/groups_map/g' config.py
% sed -i 's/currentLayout/current_group.layout/g' config.py
```
Now my config works again; as far as I can see.

Is there a guide/doc what has changed?

LBNL, thank you all a lot for your good work on qtile!

**Comment by ramnes** [comment]
All the important changes are listed in the [CHANGELOG](https://github.com/qtile/qtile/blob/master/CHANGELOG).

It seems that the new dependency on `psutil` for `widget.graph` is missing, though.
