### ISSUE TITLE
A group.next_minimized_window() function

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1368]
There is in qtile the `group.next_window()` and `group.prev_window()` pair, good and working.

How can I cycle through the minimized windows only and not minimized windows only?

**Comment by ramnes** [comment]
Yes, I guess we could add the `group.{prev,next}_{minimized,maximized}_window` functions, or something like `minimized` and `maximized` as parameters to the current functions.

**Comment by arczan1** [comment]
I'm trying to add this functionality.
The problem is that the next_window() function only change focus between windows.
When you set focus to minimilized window it does not show on the screen.
Should the behaviour of the function be changed?

**Comment by osimplex** [comment]
@arczan1 the function is good as it is.
Minimized windows without a tasklist makes no sense for me. I think, maybe cicle until focus the desired window, then `lazy.window.toggle_minimize()` with one binding, or cicling will raise _all_ windows until I find that one that I want.
The problem I faced when trying to make a funcion for this was cicle only through minimized windows: first minimized window, second _etc_. I cannot go beyond the first.

**Comment by arczan1** [comment]
```
    def cmd_next_minimized_window(self):
        """
        Focus the next minimized window in group.

        Method cycles all minimized windows ing group
        """
        if not self.windows:
            return
        if not True in [window.minimized for window in self.windows]:
            return
        nxt = self.current_window
        while True:
            if self.current_window.floating:
                nxt = self.floating_layout.focus_next(nxt) or \
                    self.layout.focus_first() or \
                    self.floating_layout.focus_first(group=self)
            else:
                nxt = self.layout.focus_next(nxt) or \
                    self.floating_layout.focus_first(group=self) or \
                    self.layout.focus_first()
            if nxt.minimized:
                break
        self.focus(nxt, True)
```
I made this function but I don't know if it is good solution.
I can always add toggle_minimize() at the end.
