### ISSUE TITLE
Some functions on qtile that has not standard function_names

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1370]
From shell: `qtile-cmd -o some_object`.

* Group: `setlayout`, `toscreen`.
* Window: `togroup`, `toscreen`.
* Qtile: `addgroup`, `delgroup`, `findwindow`, `loglevel`, `loglevelname`, `qtilecmd`, `spawncmd`, `switchgroup`, `togroup`.

**Comment by ramnes** [comment]
I'm not sure to understand, what is the problem exactly? Is it that they don't have an underscore between words?

**Comment by osimplex** [comment]
Right.
All the functions have an underscore between the words.

In 0.14.2 there is an switch to another case on composite function names, so I needed to alter some lines on personal functions. Fixing my code, I've founded some the `toscreen()`, `togroup()`, and needed to read some help to make sure those not changed.

**Comment by ramnes** [comment]
Fair enough. My point was to remove camelCase, so I didn't touch to anything that wasn't camelCase, but I should have gone further apparently. I'm not sure that we want to break everything again though, maybe we should do deprecation notices this time?
