### ISSUE TITLE
Work with floating windows: move_floating and resize_floating

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1371]
YT link: https://www.youtube.com/watch?v=skT9CZJ7V4Y
Old config file: https://github.com/bavardage/qtile/blob/master/examples/config/bavardage-config.py

I tried the block from the config:
```python
for key, x, y in [("Left", -10, 0), 
                  ("Right", 10, 0), 
                  ("Up", 0, -10),
                  ("Down", 0, 10)]:
    keys.append(Key([modkey, "control"], key, lazy.window.move_floating(x, y)))
    keys.append(Key([modkey, "shift"], key, lazy.window.resize_floating(x, y)))
    keys.append(Key([modkey, "mod1"], key, lazy.window.move_to_screen_edge(key)))
```
but doesn't work.
The `window.move_to_screen_edge` function doesn't exists also.

How can I use this pair of functions for this kind of window manipulation with keyboard?

**Comment by ramnes** [comment]
`move_to_screen_edge` got removed in ee31fc24, 9 years ago, not sure why. @cortesi, remember? :smile: 

The two other bindings should work, though. What happens when you try to activate those?

**Comment by osimplex** [comment]
The two methods need other two parameters:
* `move_floating(dx, dy, curx, cury)`
* `resize_floating(dw, dh, curx, cury)`

On `lazy.window.move_floating(x, y)` is sent only two parameters.

On `libqtile.window` there are the functions on the lines [1327,1333]:
```python
def cmd_move_floating(self, dx, dy, curx, cury):
    """Move window by dx and dy"""
    self.tweak_float(dx=dx, dy=dy)

def cmd_resize_floating(self, dw, dh, curx, cury):
    """Add dw and dh to size of window"""
    self.tweak_float(dw=dw, dh=dh)
```
I don't know why need to pass 4 parameters to the function, because it uses only two.

So, when I tryed (keybinding, qtile-cmd or via qshell), just not worked, two parameters missing.

**Comment by ramnes** [comment]
The reason of those empty arguments is because `cmd_set_position` need them, and that this function and the ones you're trying to use are meant to be called at the same place: https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L1077

I'm about to push a commit that will modify `cmd_set_position` so that we leverage #1305, that made the coordinates of the mouse always available, so that we can remove those useless arguments all around. :+1:

**Comment by ramnes** [comment]
Alright, done. Can you try this @osimplex? If this works then we can see for the rest, i.e. whether we reimplement `move_to_screen_edge` or not.

**Comment by Stock84-dev** [comment]
I tried this and still doesn't work.

**Comment by ramnes** [comment]
@Stock84-dev What did you try and what doesn't work, exactly?

**Comment by Stock84-dev** [comment]
I tried the same thing as he did and cannot move windows or resize them.
```python
for key, x, y in [("Left", -10, 0), 
                  ("Right", 10, 0), 
                  ("Up", 0, -10),
                  ("Down", 0, 10)]:
    keys.append(Key([modkey, "control"], key, lazy.window.move_floating(x, y)))
    keys.append(Key([modkey, "shift"], key, lazy.window.resize_floating(x, y)))
```

**Comment by ramnes** [comment]
That commit I pushed the other day hasn't been released yet; are you running the HEAD of the `master` branch of the git repository? I just tried again and your snippet works for me.

**Comment by Stock84-dev** [comment]
Ah I see, I am running qtile 0.14.2 release version which is behind master by around 50 commits, looks like I need to update it with git.
