### ISSUE TITLE
keybinding alt+shif

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1372]
I have in config such functionality
```
...
# keyboard next layout
@lazy.function
def z_next_keyboard(qtile):
    keyboard_widget.cmd_next_keyboard()

keys = [
    Key([alt], 'Tab', z_next_keyboard),
    ...
]

keyboard_widget = widget.KeyboardLayout(configured_keyboards=['us', 'lt', 'ru phonetic_winkeys'], **Theme.widget)
...
```
How can I create keybinding to `alt+shift`?

**Comment by stanso** [comment]
You may try using EzKey('A-S', func)
Need to import from libqtile.config
I think Key() should be able to do the same somehow but I haven't tried.

**Comment by zordsdavini** [comment]
Changed to EzKey, same:
```
Traceback (most recent call last):
  File "config.py", line 163, in <module>
    Key("A-S", z_next_keyboard),
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 152, in __init__
    modkeys, key = self.parse(keydef)
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 141, in parse
    raise utils.QtileError(msg % spec)
libqtile.utils.QtileError: Invalid key/btn specifier: A-S
```

**Comment by stanso** [comment]
Sorry I think you are right..
Looked at the parse function in /usr/lib/python3.7/site-packages/libqtile/config.py
It does seem like it's not supporting only using 2 modifier keys (both alt and shift are categorized as modifiers) and no other keys..

**Comment by Edzan** [comment]
Key(["mod1"], "Shift_L", z_next_keyboard)

**Comment by osimplex** [comment]
1. The `alt` key is called `mod1`.
1. In `Key([alt], 'Tab', z_next_keyboard)`, the correct alt is `'mod1'`, so: Key(['mod1'], 'Tab', z_next_keyboard)`.
1. For an `alt+shift` binding: `Key(['mod1', 'shift'], 'Tab', z_next_keyboard)`.

**Comment by zordsdavini** [comment]
solved by `Key("A-S-<space>", z_next_keyboard),` for now. 
Accidentally I formatted my computer, so I had to rebuild all super-druper config. Forgot about this issue. This helped to restore what I had :)
