### ISSUE TITLE
Emulate key press on non-focused window

### ISSUE THREAD

**Issue by soulmare** [qtile/qtile#1375]
On my two-monitor setup, I have an editor opened on one monitor, and a web-browser on the second one. Editor is focused. Is it possible to create a keybinding to send F5 (refresh) key to the browser window while it is not in focus?

**Comment by ramnes** [comment]
I think that we don't have anything bundled in for that kind of use case, but you can bind a key to a custom `lazy.function` that focuses the browser, sends F5, and then focuses back to the previous window.

**Comment by soulmare** [comment]
Thank you for the answer. The problem is, I don't know how to send a key.

**Comment by ramnes** [comment]
You can use a library like [pynput](https://github.com/moses-palmer/pynput) for this. :wink:
