### ISSUE TITLE
Switching back and fourth between groups

### ISSUE THREAD

**Issue by Nebucatnetzer** [qtile/qtile#1378]
I i3 you can activate an option which allows you to quickly switch between two groups.
When it is activated you can for example press "Meta+3" to jump from group 1 to group 3. If you press "Meta+3" again you switch back to group 1.
I find this very useful for quickly having a glance at a documentation or something similar.
Is the a way to recreate this behaviour in qtile? So far I haven't seen anything in the documentation or the examples.

**Comment by ramnes** [comment]
One easy way to achieve something similar would be to bind a key to use to the latest group.

Something like this should work:

```python
def latest_group(qtile):
    qtile.current_screen.set_group(qtile.current_screen.previous_group)

keys += [Key(["mod4"], "s", lazy.function(latest_group))]
```

**Comment by Nebucatnetzer** [comment]
That would require to have the order correct of the groups correct or switching keys.
I'm imagining more something like this:

``` python
def switch_to_group(qtile):                                                     
    start_group = qtile.get_current_group_name()                                
    if start_group = key # key is the number that gets pressed with Mod e.g. Mod+4
        return                                                                  
    else                                                                        
        qtile.switch_to_group(key)

groups = [Group(name=i, matches=group_matches[int(i)]) for i in "1234567890"]   
                                                                                
for i in groups:                                                                
    keys.extend([                                                               
        # mod1 + letter of group = switch to group                              
        Key([mod], i.name, switch_to_group(i.name)),                      
    ])                       
```

**Comment by Nebucatnetzer** [comment]
Thinking about this led me to this [function](http://docs.qtile.org/en/latest/manual/ref/commands.html#libqtile.config.Screen.cmd_toggle_group).
From the description it does what I intend to do.
I'll post here if I find the correct way to implement it.

**Comment by osimplex** [comment]
I have a function to handle this:
```python
def init_group_keybindings(groups):
    group_keys  = ["dead_grave"]
    group_keys += [str(i) for i in range(1, 10)]
    group_keys += ["0", "minus"]

    keys = []

    for i, group in enumerate(groups):
        # Switch to another group
        keys.append(Key([self.mod], group_keys[i], lazy.group[group.name].toscreen()))

        # Move current window to another group
        keys.append(Key([self.mod, "shift"], group_keys[i], lazy.window.togroup(group.name)))

        # Move with current window to another group
        keys.append(Key([self.mod, "control"], group_keys[i],
            lazy.window.togroup(group.name),
            lazy.group[group.name].toscreen()))

    return keys
```
You can use  this on `config.py` to add to your `keys` variable all the bindings.
```python
def init_general_keybindings():
    return [Key(["mod4"], "q", lazy.shutdown())]

groups = [Group(i) for i in "asdfiop"]

keys  = init_general_keybindings()
keys += init_group_keybindings(groups)
```

**Comment by Nebucatnetzer** [comment]
I don't think your function does what I'm looking for.
I already have the first two functionalities in my config and the third one move the window and the focus to a group which is not what I'm trying to achieve.

I'm trying to do this:
https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth

**Comment by osimplex** [comment]
Qtile has an function for this, not exacty the same thing:
```python
Key([self.mod], "z", lazy.screen.togglegroup())
```
This will allow you move to last group visited. The only thing is: will cost a keybinding.

**Comment by Nebucatnetzer** [comment]
That function does basically the same as the code ramnes provided. Which requires to move your fingers when using. IMO not really useful :).

I think this function would be the solution since it takes a group name as an argument. 
However I haven't found a way yet to implement it. 
I'm still to unexperienced with qtile :). 
http://docs.qtile.org/en/latest/manual/ref/commands.html#libqtile.config.Screen.cmd_toggle_group

**Comment by Stock84-dev** [comment]
Here is working example :)
```python
groups = [Group(i) for i in "asdfuiop"]

def toscreen(qtile, group_name):
    if group_name  == qtile.current_screen.group.name:
        qtile.current_screen.set_group(qtile.current_screen.previous_group)
    else:
        for i in range(len(qtile.groups)):
            if group_name == qtile.groups[i].name:
                qtile.current_screen.set_group(qtile.groups[i])
                break

for i in groups:
    keys.extend([
        # mod1 + letter of group = switch to group
        #Key([mod], i.name, lazy.group[i.name].toscreen()),
        # switch to group with ability to go to prevous group if pressed again
        Key([mod], i.name, lazy.function(toscreen, i.name)),

        # mod1 + shift + letter of group = switch to & move focused window to group
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name)),
    ])
```

**Comment by ramnes** [comment]
Nice!

You should be able to iterate on groups directly, though:

```python
        ...
        for i, group in enumerate(qtile.groups):
            if group_name == group.name:
                qtile.current_screen.set_group(qtile.groups[i])
                break
```

Also, you can use returns to avoid the `else` and `break` instructions, but this is more a matter of programming style tastes!

**Comment by Nebucatnetzer** [comment]
@Stock84-dev, your example works perfectly, thanks a ton!
I've adapted it a bit to go with the `return` style ramnes suggested:

``` python
def toscreen(qtile, group_name):                                                
    if group_name  == qtile.current_screen.group.name:                                
        qtile.current_screen.set_group(qtile.current_screen.previous_group)     
        return                                                                  
    for i, group in enumerate(qtile.groups):                                    
        if group_name == group.name:                                            
            qtile.current_screen.set_group(qtile.groups[i])                     
            return                                                              
```

I'm closing this comment because @Stock84-dev solved it for me.

**Comment by ramnes** [comment]
Almost what I had in mind! :wink: 

``` python
def toscreen(qtile, group_name):
    if group_name  == qtile.current_screen.group.name:
        return qtile.current_screen.set_group(qtile.current_screen.previous_group)
    for i, group in enumerate(qtile.groups):
        if group_name == group.name:
            return qtile.current_screen.set_group(qtile.groups[i])
```

**Comment by Nebucatnetzer** [comment]
Ah yes that looks a bit nice :)

**Comment by c02y** [comment]
> Qtile has an function for this, not exacty the same thing:
> 
> ```python
> Key([self.mod], "z", lazy.screen.togglegroup())
> ```
> 
> This will allow you move to last group visited. The only thing is: will cost a keybinding.

According to the [official website](https://docs.qtile.org/en/latest/_modules/libqtile/config.html#Screen.toggle_group), this should be working.

But it seems it doesn't work at all, but the two functions `lazy.screen.prev_group()/lazy.screen.next_group()`  in the context work fine.
