### ISSUE TITLE
Rouge window appearance

### ISSUE THREAD

**Issue by noahsmindfuck** [qtile/qtile#1379]
Sometimes I have a rouge window appearing. It is in the center of the screen, square, doesn't react to any layouting and I can't drag it around either.
I can not reproduce it so it is hard to debug. It can vanish without any interaction. restarting qtile doesn't solve it, it stays. 
![2019-07-18-154124_1920x1080_scrot](https://user-images.githubusercontent.com/24893086/61462721-6a398b00-a973-11e9-8504-76c5252bb6b5.png)

It is the one in the center the others are dragged around with the mouse.
Layout is MonadTall
I am using qtile-python-3 package from the Arch User Rep. (https://aur.archlinux.org/packages/qtile-python3-git/)

**Comment by przymusp** [comment]
I can confirm this on 0.14.2. Unfortunately it is very hard to reproduce (in my case it was part of rxvt terminal or part of pdf viewer). Changing layout or restarting does not fix this.

**Comment by m-col** [comment]
This fits with my experience #1861

**Comment by m-col** [comment]
@noahsmindfuck and @przymusp, does https://github.com/qtile/qtile/pull/1896 fix this?

**Comment by przymusp** [comment]
I think the problem was the same as #1861 based on the description.

czw., 3 wrz 2020 o 22:51 m-col <notifications@github.com> napisał(a):
>
> @noahsmindfuck and @przymusp, does #1896 fix this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
Piotr Przymus
website: www.przymus.org
jabber: piotr.przymus@gmail.com
