### ISSUE TITLE
Font stopped working and shows only squares in bar/widgets, other programs (terminal, browser, ...) are fine!?

### ISSUE THREAD

**Issue by mejo13** [qtile/qtile#1384]
Hey, [terminus-font](https://www.archlinux.org/packages/community/any/terminus-font/) stopped working in [qtile](https://www.archlinux.org/packages/community/any/qtile/) after the last reboot. I've tried to reinstall qtile and terminus-font, started qtile with default_config.py and checked the logs (-l DEBUG) but couldn't find anything. As other programs are fine i assume it's a qtile problem but there weren't any updates in the last days so i'm not really sure!?

**Comment by ramnes** [comment]
Did you update Qtile? Are you sure that the problem is linked to the font, i.e. that using another font make it work again?

**Comment by mejo13** [comment]
Yes, i update qtile, but that was a while ago. Anyway i just started zathura and it has the same problem. So it looks like this is not a qtile problem. This issue can be deleted i guess.

**Comment by ramnes** [comment]
We changed a lot of things lately, you might want to take a look at [the CHANGELOG](https://github.com/qtile/qtile/blob/master/CHANGELOG) to see if something could cause this. I'll close meanwhile but feel free to reopen an issue if you see anything wrong on Qtile's side!
