### ISSUE TITLE
libqtile.widget.Image renders transparent backgrounds of PNG images as black

### ISSUE THREAD

**Issue by gcmartinelli** [qtile/qtile#1385]
I'm importing the image with:
`widget.Image(filename=HOMEDIR+"/Pictures/icons/whitepng/wifi.png")`
My bar is initialized with:
`Screen(top=bar.Bar(widgets=init_widgets_list(), size=24))`

The result is the PNG appear but with a black background, instead of the expected transparent background.

I have tried incorporating other colors for the background using the `background` argument inside `widget.Image()` but no colors work (tried both RGB and RGBA values).

My full config file is [here](https://github.com/gcmartinelli/dotfiles/blob/master/.config/qtile/config.py).

I'm not sure it is related with issues #1059 so I'm adding this ticket.

**Comment by akemrir** [comment]
I confirm. Same here.
Other applications while reading png shows transparent background, but on bar background is black.

**Comment by ramnes** [comment]
I can reproduce. I'm attaching the PNG file I used.

![test](https://user-images.githubusercontent.com/835072/79692170-fdd21c00-8263-11ea-89e4-040a98df26b2.png)

**Comment by tych0** [comment]
I think the behavior here is correct -- it shows the default bar background color, which is black in place of the transparency. I suspect if you set your bar up with background="#FF0000" or something, it would show that color.

What's the expected behavior? The above seems right to me...

**Comment by ramnes** [comment]
Fixed, as long as you give the `background` argument to the `Image` object. Thanks for raising this @gcmartinelli!
