### ISSUE TITLE
Feature Request: default console if there is a config error

### ISSUE THREAD

**Issue by gcmartinelli** [qtile/qtile#1386]
It would be nice if, upon a config error, a terminal window would be shown, giving you a chance to fix the code from inside Qtile instead of freezing and forcing a reboot.

**Comment by Stock84-dev** [comment]
There is a workaround:
Ctrl + Alt + F2 shows a terminal that you can log in, then you can edit config file, save it and restart qtile with this command:
`qtile-cmd -o cmd -f restart`
It will throw some errors but ignore it.
To go back to qtile press Ctrl + Alt + F7
If above command doesn't work then kill qtile:
`pkill qtile`
This will open login/display manager where you can start new qtile session.

**Comment by pawamoy** [comment]
Thansk @Stock84-dev, I was previously going in another TTY and running `sudo pkill xinit`, which was a bit overkill compared to your solution :rofl: 

Also killing qtile did not seem to work, maybe because I'm launching it with startx.

**Comment by sux2mfgj** [comment]
Instead of shown any terminal, I made a patch to prepare to close qtile easily in the default configuration, using a mouse(not any keyboard shortcut). 
The patch is discussed at #1389 . 
How do you think the method to resolve this problem?

**Comment by pawamoy** [comment]
It's another way to resolve it, yes! Your patch would be very effective when the user cannot think of or doesn't know they can switch to another TTY to kill and restart QTile. The mouse button is a very handy shortcut :slightly_smiling_face:

**Comment by ramnes** [comment]
Just a quick note without entering the discussion for now but:

> Alternatively, it would be nice to have a QTile command to check the validity of the config file (if it does not raise a SyntaxError or else). I happened to forget a coma in the keys list multiple times...

`python config.py` does pretty much this.

**Comment by gcmartinelli** [comment]
> There is a workaround:
> Ctrl + Alt + F2 shows a terminal that you can log in, then you can edit config file, save it and restart qtile with this command:
> `qtile-cmd -o cmd -f restart`

Yes I have been using this, but it is not as 'user friendly'

**Comment by pawamoy** [comment]
@ramnes

> python config.py does pretty much this.

Yes this is what I do :slightly_smiling_face: But some errors will not be caught. For example if you set `Key([mod], ":", ...)` instead of `Key([mod], "colon", ...)`, it will result in an error and an unusable interface! This could be easily prevented with very few introspection thanks to a check command :stuck_out_tongue:

**Comment by pawamoy** [comment]
Improved config validation snippet:

```python
import os
from libqtile.confreader import Config
from libqtile.core.xcore import XCore

Config.from_file(XCore(), os.path.expanduser("~/.config/qtile/config.py"))
# will raise ConfigError if errors
```

It will catch wrong modifiers / keys in addition to syntax errors.

**Comment by zordsdavini** [comment]
I think this can be closed because config now is validated before reload (6ab9d024eb676eaf99c6cbe738929c7f1935186a)

**Comment by kavorite** [comment]
the validation snippet looks like this now, in case anyone else comes across this and wants to branch off `if __name__ == '__main__'` in their `config.py` (loading semantics and `XCore` import from `/usr/lib/python3.8/site-packages/libqtile/scripts/qtile.py`):

```python
if __name__ == '__main__':
    # validate the correctness of the configuration file
    from libqtile.confreader import Config
    from libqtile.backend.x11.xcore import XCore
    Config.from_file(XCore(), os.path.realpath(__file__))
```
