### ISSUE TITLE
docs: List missing requirements for widgets

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1398]
For example, when trying to use the `Wlan` widget, I was getting the `ImportError` kind of widget. I had to look at the source to see that it tries to import
1. `pythonwifi`
2. `iwlib` if the previous failed

On Python 3, `pythonwifi` generates syntax errors (`iwlibs.py, line 113`), so I went with `iwlib` only, installed with `sudo python3 -m pip install iwlib`.

For the MPD widgets, I had to install `python-mpd` and `python-mpd2` with the same method.

Of course, seeing https://github.com/qtile/qtile/issues/587, I'm not asking you to put `sudo python3 -m pip install` in the docs. I used that because I personally installed QTile in my system Python libraries (didn't know a better way to make it accessible when booting, but maybe installed as `pip --user` would have worked as well). Rather, we could just list the required `apt-get` or `pip` packages.

**Comment by ramnes** [comment]
See #1354 for more discussion around that topic.

**Comment by pawamoy** [comment]
Thank you for the link to the previous issue.

Indeed using setuptools' `extras_require` could be nice.

For example:

```python
extras_require={
    "wlan":  ["iwlib"],
    "mpd": ["python-mpd", "python-mpd2"],
}
```
Then one could run `pip install qtile[wlan,mpd]`, even if Qtile has already been installed with `pip`.

I left out the version specifiers, but I guess we should add them if we start doing this.

I think the easiest to start with is to list the requirements in the docs at least, for each widget. This is where people learn about the built-in widgets :slightly_smiling_face:

**Comment by ramnes** [comment]
That'd be great, we have to start somewhere!
