### ISSUE TITLE
Feature Request: Pass Qtile instance to startup_once hook

### ISSUE THREAD

**Issue by elmdalf** [qtile/qtile#1401]
I only use dynamicly named groups (added/deleted via prompts) in my qtile config.
Persistence between sessions for this groups (and other added stuff) is achieved by a state file written from relevant hooks.
Because i need a Qtile instance to re-add these groups on session start i patched manager.py:
```
diff --git a/libqtile/core/manager.py b/libqtile/core/manager.py
index 47c2e01d..bda78afa 100644
--- a/libqtile/core/manager.py
+++ b/libqtile/core/manager.py
@@ -230,7 +230,7 @@ class Qtile(CommandObject):
         # no_spawn is set when we are restarting; we only want to run the
         # startup hook once.
         if not no_spawn:
-            hook.fire("startup_once")
+            hook.fire("startup_once", self)
         hook.fire("startup")
 
         if state:
```

Maybe this might also be useful for others?

**Comment by ramnes** [comment]
I think that we already have the `main` function and that you could use it here, as it takes the manager instance as an argument.

For example: https://github.com/ramnes/qtile-config/blob/64e658e9c31e961c9e3ade4e14c121ba14247f62/config.py#L298-L301

Did you try it? 

`startup_once` being used by a lot of people, I'm not sure that we want to change its signature and break all the configs, unless we rationalize all hooks parameters at once (see the discussion in https://github.com/qtile/qtile/pull/1341).

**Comment by ramnes** [comment]
I'll go ahead and close this directly, but feel free to comment if needed!
