### ISSUE TITLE
Feature Request: resize horizontal and vertical for BSP layout

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1402]
### Use-case
Coming from Terminator (the terminal emulator written in Python), I immediately liked the BSP layout since it's very similar to the split feature of Terminator.

One thing that felt a bit unfriendly (as in, not like in Terminator) in the BSP layout is the proposed keys configuration for resizing the windows: it's using only `grow` methods. Which means I can only shrink a window by switching focus to its neighbor and make it grow. A solution to this would be to add shrink methods and bind them to keys, but then we would have 8 different shortcuts to resize windows! In Terminator you can simply resize horizontally or vertically using Ctrl+Shift+Arrow.

### Feature request
What I propose it to add the ability to "resize" windows in addition or in place of "grow"ing them.

I would like to add four commands to the BSP layout:
- `cmd_resize_left`
- `cmd_resize_right`
- `cmd_resize_down`
- `cmd_resize_up`

Here's how I implemented it in my config file:

```python
def resize(qtile, direction):
    layout = qtile.current_layout
    child = layout.current
    parent = child.parent

    while parent:
        if child in parent.children:
            layout_all = False

            if (direction == "left" and parent.split_horizontal) or (
                direction == "up" and not parent.split_horizontal
            ):
                parent.split_ratio = max(5, parent.split_ratio - layout.grow_amount)
                layout_all = True
            elif (direction == "right" and parent.split_horizontal) or (
                direction == "down" and not parent.split_horizontal
            ):
                parent.split_ratio = min(95, parent.split_ratio + layout.grow_amount)
                layout_all = True

            if layout_all:
                layout.group.layout_all()
                break

        child = parent
        parent = child.parent


@lazy.function
def resize_left(qtile):
    resize(qtile, "left")


@lazy.function
def resize_right(qtile):
    resize(qtile, "right")


@lazy.function
def resize_up(qtile):
    resize(qtile, "up")


@lazy.function
def resize_down(qtile):
    resize(qtile, "down")


...

keys = [
    Key(["mod4", "mod1"], "Left", resize_left),
    Key(["mod4", "mod1"], "Up", resize_up),
    Key(["mod4", "mod1"], "Down", resize_down),
    Key(["mod4", "mod1"], "Right", resize_right),
]
```

If we add it in the BSP layout, we just have to change `layout` to `self`!

**Comment by pawamoy** [comment]
Maybe I should have described the effect of these "resize" functions: unlike `grow` who is only able to grow the window, `resize` can also shrink it. If you have two windows (left/right), doing `resize_right` on the left window will grow it, while doing `resize_left` will shrink it. This way you don't have to change focus as with `grow` methods.

The code I've pasted here works for any level of window nesting, vertical or horizontal.

**Comment by pawamoy** [comment]
Still interested :slightly_smiling_face: I can send a PR if you'd accept one.

**Comment by ramnes** [comment]
Yeah I think it makes sense but then I think it would also makes sense to remove the `grow` methods and just keep these ones. Now I don't want to make people coming from BSP inconfortable, and I don't know how it works on this WM.

@heitzmann Any opinion?

**Comment by ramnes** [comment]
Somewhat related to #665

**Comment by heitzmann** [comment]
Looks good to me. I can how being able to shrink helps out. I'm not against removing `grow` methods either, but maybe we should add a deprecation warning for a little while, so that users are able to properly adjust their configs?

**Comment by Pakrohk** [comment]
Resize method added to the current qtile? Or will it be added in the future?
