### ISSUE TITLE
Feature request: window.send_to_back

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1403]
Inversely to `window.bring_to_front`, I'd like a command to send a window to the back, be it floating or not.

The use-case is that sometimes a floating window is hidden behind another window. I'd like to be able to send a particular window to the back.

Currently I'm using this workaround from another issue:

```python
@lazy.function
def float_to_front(qtile):
    logging.info("bring floating windows to front")
    for window in qtile.current_group.windows:
        if window.floating:
            window.cmd_bring_to_front()
```

...but it could still happen that one of the floating window is still hidden behind another one right? Being a tiling window manager, I'd like Qtile to allow to use a keyboard shortcut to make the desired window visible by sending the one on top of it to the back (or one layer below) instead of using the mouse to drag the offensive window somewhere else.

My problem arises from the fact that I'm not sure to understand how floating windows work in the current layout/group: when trying to move focus onto the next window, the floating ones never get focused. Could someone explain to me the behavior of moving focus to next window in a group/layout with both tiled and floating window? Because if I could just bring floating windows on top by focusing them I would not need to sned other windows to the back.

Anyway, I think the implementation for `send_to_back` would be something like

```python
    def cmd_send_to_back(self):
        self.window.configure(stackmode=StackMode.Below)
```

...but maybe I'm missing some cases here.

**Comment by ramnes** [comment]
Related to #753
