### ISSUE TITLE
docs: suggestion to add screenshots

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1405]
Related to https://github.com/qtile/qtile/issues/1360, I would like to improve the documentation by adding screenshots of the screen **before** and **after** running a particular layout command.

The rationale is that it is hard to guess what the command will do, especially for non-native english speakers: what will `flip_left` do? what will `shuffle_left` do? what's the difference? what will `toggle_split` do?

I think adding screenshots would really help grasping the available commands and their effect on the layout :slightly_smiling_face: 

Each pair of screenshot would ideally be placed next to the layout command it shows, but we could also consider putting all screenshots in one specific page.

Before I continue working on this, would you agree on such an addition? I'm currently automating the process of taking these screenshots so other contributors can produce or update them easily as well.

**Comment by ramnes** [comment]
Definitely a good idea! The only thing I'm concerned about is how we would integrate these into the documentation so that it doesn't make the page too big, in bytes but also in terms of scrolling.

If we're crazy, we could even write a script that generate videos for each layout and each one of its commands.

**Comment by pawamoy** [comment]
Great! Here is a first draft, written in Bash:


```bash
# qtile-screenshot.sh
# requires xterm and scrot

group_script="${GROUP_SCRIPT:-a}"
group_screenshots="${GROUP_SCREENSHOTS:-s}"
n_windows="${N_WINDOWS:-3}"
layout="${LAYOUT:-bsp}"
command="${COMMAND:-shuffle_right}"

sleep=0.1

# base colors, up to 9 different windows (see screenshot below)
black="#111111"
gray="#444444"
white="#cccccc"
red="#cc4444"
green="#44cc44"
blue="#4444cc"
magenta="#cc44cc"
cyan="#44cccc"
yellow="#cccc44"

# particular color order when spawning windows
colors=(
  "$green"
  "$magenta"
  "$blue"
  "$yellow"
  "$cyan"
  "$white"
  "$gray"
  "$black"
  "$red"
)

# pull "screenshots" group to screen
echo "Pull group $group_screenshots"
#qtile-cmd -o group -f toscreen -a "$group_screenshots"  # does not work!!
# error: Sorry cannot run function 'toscreen' with arguments ['s']
{ echo cd group/$group_screenshots; echo toscreen; } | qshell >/dev/null
# another way:
# qtile-cmd -o screen -f toggle_group -a "$group_screenshots"
sleep $sleep

# switch to the selected layout
echo "Switch to layout $layout"
qtile-cmd -o group -f setlayout -a "$layout" >/dev/null
sleep $sleep

# open three windows
echo "Spawn $n_windows windows"
for i in $( seq 0 $(( n_windows - 1)) ); do
  qtile-cmd -o cmd -f spawn -a "xterm +ls -hold -e printf '\e]11;${colors[i]}\007'"
  sleep $sleep
done

# take the first screenshot
echo "Take screenshot ./screenshots/layout/$layout/$command.1.png"
scrot -t 10 "./screenshots/layout/$layout/$command.1.png"
# --thumbnail 10: generate a thumbnail at 10% size
# we could also use --quality 50 (instead of 75) as we do not need great details
# and should avoid having heavy files
# then maybe delete the original screenshot if we only use the thumbnails

# run the layout command
echo "Run layout command $command"
qtile-cmd -o layout -f "$command" >/dev/null
sleep $sleep

# take the second screenshot
echo "Take screenshot ./screenshots/layout/$layout/$command.2.png"
scrot -t 10 "./screenshots/layout/$layout/$command.2.png"

# kill all windows
echo "Kill windows"
for i in $(seq $n_windows); do
  qtile-cmd -o window -f kill >/dev/null
  sleep $sleep
  # we could also simply "pkill xterm", without a loop
  # but this solution is more portable
done

# switch back to the original group
echo "Move back to original group"
# qtile-cmd -o group -f toscreen -a "$group_script"  # does not work!!
# error: Sorry cannot run function 'toscreen' with arguments ['a']
{ echo cd group/$group_script; echo toscreen; } | qshell >/dev/null
# another way:
# qtile-cmd -o screen -f toggle_group
```

Now you can run it like this:
```bash
LAYOUT=bsp COMMAND=shuffle_down bash qtile-screenshot.sh
```

There is room for improvements (esp. argument handling). With this code, function like `shuffle_left ` will have no visible effect, since the focused window will always be on the left.

Maybe we could accept a list of functions to run before taking the first screenshot.  
Example: `./qtile-screenshot.sh --layout=bsp --functions-before="right flip_left right up" --functions="shuffle_left"`  
With this command, we spawn three windows, 2 in the left column, 1 in the right one, then move focus to the right window, flip it with the other two, move focus again to the top right one, then take a screenshot, run shuffle_left, and take another screenshot.

I think this way we could even use a screen recorder instead of a screenshooter to record gifs or videos, as you proposed :slightly_smiling_face:  

As you can see, it could be easy to generate a big script that runs every function of every layout with this script.

An example of the screenshot it generates:

![screenshot](https://user-images.githubusercontent.com/3999221/63845850-f5eb0200-c98a-11e9-9eca-4d1c651892ab.png)

**Comment by pawamoy** [comment]
Example with BSP's `flip_right`:

Shot 1 (2.2 KiB):
![flip_right 1](https://user-images.githubusercontent.com/3999221/64215754-54960b80-ceb6-11e9-8c7c-49646c899691.png)
Shot 2 (2.2 KiB):
![flip_right 2](https://user-images.githubusercontent.com/3999221/64215757-565fcf00-ceb6-11e9-86ba-0e47f596fe5f.png)
Animation (4.3 KiB):
![flip_right](https://user-images.githubusercontent.com/3999221/64215758-5790fc00-ceb6-11e9-982f-9561fabde0e7.gif)




As you can see it flickers a bit. I'll try to find a way to record it without flickering.

**Comment by pawamoy** [comment]
When I generate them automatically, sometimes the screenshot happens at the wrong moment. I think it's because the `qtile-cmd` commands are asynchronous (and therefore I have to play with `sleep`s to make sure they are finished before I take the screenshot, but it's hackish).

What would be a synchronous equivalent of a `qtile-cmd` command? Is `qshell` synchronous?

**Comment by whatacold** [comment]
I think it's also valuable to add screenshots for layouts themselves, there are some many built-in layouts that I have no idea what they look like at the first glance, unless I try them out one by one.

**Comment by pawamoy** [comment]
Good idea. I'll update my code to handle this as well.

**Comment by whatacold** [comment]
> ...I think it's because the `qtile-cmd` commands are asynchronous (and therefore I have to play with `sleep`s to make sure they are finished before I take the screenshot, but it's hackish).
> ...
> EDIT: I see that `qshell` is async as well. Opening 4 terminals and running `printf "cd window\nkill\nkill\nkill\nkill" | qshell` closes only one or two terminals.

I think they're synchronous because the Client instance will wait for the response at [send()](https://github.com/qtile/qtile/blob/master/libqtile/ipc.py#L215),
but I don't know how to prove it with commands yet :(

**Comment by pawamoy** [comment]
I'm a bit confused as well, because each of the three methods (`qtile-cmd`, `qshell` and direct Python) return a result when calling the command, so it seems to wait for the action to be finished. Yet I'm still experiencing a lag between the commands I run and the screenshots I get.

For example, if you script this without sleeping between each kill:
- move to group "s"
- spawn 3 windows
- kill 3 windows
...then you either end up with 1 or 2 remaining window, or a CommandError because it tried to kill a window once more, while there were non left.

I ended up with the following code in my Python rewrite of the above Bash script:
```python
def kill_group_windows(self):
    while len(self.client.layout.info().get("clients")) > 0:
        try:
            self.client.window.kill()
        except CommandError:
            pass
```

**Comment by pawamoy** [comment]
So now that #1423 is merged, I'm gonna open a fresh new issue to discuss about how/where to add the screenshots.
