### ISSUE TITLE
libqtile.command.Client doesn't exist anymore

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1409]
How has it been replaced? The docs [here](http://docs.qtile.org/en/latest/manual/commands/scripting.html) need an update.

**Comment by pawamoy** [comment]
And [here](http://docs.qtile.org/en/latest/manual/commands/index.html) as well.

**Comment by pawamoy** [comment]
I was able to instantiate a client with this code:

```python
from libqtile.ipc import find_sockfile, Client
from libqtile.command_client import InteractiveCommandClient
from libqtile.command_interface import IPCCommandInterface

sock_file = find_sockfile()
ipc_client = Client(sock_file)
cmd_object = IPCCommandInterface(ipc_client)
cmd_client = InteractiveCommandClient(cmd_object)
cmd_client.status()
```

Or as a one-liner:

```python
c = InteractiveCommandClient(IPCCommandInterface(Client(find_sockfile())))
c.status()
```
```

**Comment by pawamoy** [comment]
Maybe a simple fix would be to allow `None` for the `command` argument of `InteractiveCommandClient`:

```python
from libqtile.ipc import find_sockfile, Client
from libqtile.command_interface import IPCCommandInterface

class InteractiveCommandClient:
    def __init__(self, command: CommandInterface, current_node: GraphType = None) -> None:
        if not command:
            command = IPCCommandInterface(Client(find_sockfile()))
        self._command = command
        ...
```

And update the docs to

```python
from libqtile.command_client import InteractiveCommandClient as Client

c = Client()
c.status()
```

**Comment by ramnes** [comment]
You would need to default to `command=None` in your example but apart from that LGTM. @flacjacket any thoughts on this?

**Comment by pawamoy** [comment]
Ah yes, forgot the default to `None`.

**Comment by tych0** [comment]
I think with the two PRs above we can close this, so I'll go ahead and do that. Please re-open (or send patches :D) if we find other stuff that needs updated.
