### ISSUE TITLE
libqtile.command_object.SelectError: Unable to make selection on current node

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1410]
```bash
$ qtile-cmd -o group 
Traceback (most recent call last):
  File "/home/ramnes/.local/bin/qtile-cmd", line 11, in <module>
    load_entry_point('qtile', 'console_scripts', 'qtile-cmd')()
  File "/home/ramnes/perso/qtile/libqtile/scripts/qtile_cmd.py", line 194, in main
    obj = get_object(cmd_client, args.obj_spec)
  File "/home/ramnes/perso/qtile/libqtile/scripts/qtile_cmd.py", line 116, in get_object
    client = client[arg]
  File "/home/ramnes/perso/qtile/libqtile/command_client.py", line 232, in __getitem__
    raise SelectError("Unable to make selection on current node", name, self._current_node.selectors)
libqtile.command_object.SelectError: Unable to make selection on current node
```

This shouldn't happen, I guess?

**Comment by whatacold** [comment]
Can confirm, even an example (`qtile-cmd -o group 3 -f focus_back`) printed by `qtile-cmd` itself can raise this exception.

**Comment by whatacold** [comment]
It seems that this problem was introduced by commit a3ae3c623859b247813fc1876b188c4d40e84df0 , as identified by the following helper script for `git bisect` with the starting good endpoint being `v0.14.2`, which is based on the `scripts/xephyr`:

    #!/bin/sh
    
    HERE=$(dirname $(readlink -f $0))
    SCREEN_SIZE=${SCREEN_SIZE:-1000x800}
    XDISPLAY=${XDISPLAY:-:1}
    LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    LOG_LEVEL=INFO
    if [[ -z $PYTHON ]]; then
        PYTHON=python
    fi
    
    ./scripts/ffibuild
    
    CLIENT="urxvt"
    XTRACE=""
    
    Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
    #Xephyr -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
    XEPHYR_PID=$!
    sleep 0.5
    source ~/workspace/virtualenv/qtile-devel/bin/activate
    env DISPLAY=${XDISPLAY} $XTRACE ${PYTHON} "${HERE}"/../bin/qtile -l ${LOG_LEVEL} $@ &
    QTILE_PID=$!
    
    export DISPLAY=${XDISPLAY}
    cd ~/workspace/python/qtile
    sleep 0.5
    ./bin/qtile-cmd -o screen -f info
    EXIT_CODE=$?
    
    kill -9 $QTILE_PID
    kill $XEPHYR_PID
    
    exit $EXIT_CODE

**Comment by ramnes** [comment]
fixed
