### ISSUE TITLE
question: processes spawned by Qtile are children of init instead of Qtile?

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1412]
In another project, I generate (in a shell function) the list of the parents of the current shell process.

On my previous system, I was getting something like:

```
/bin/bash
/usr/bin/python /usr/bin/x-terminal-emulator
/usr/bin/openbox --startup
/usr/lib/x86_64-linux-gnu/openbox-autostart OPENBOX lightdm --session-child 13 22
/usr/sbin/lightdm
/sbin/init
```

Now with Qtile I have this:

```
/usr/bin/zsh
/usr/bin/python2 /usr/bin/terminator
/sbin/init
```

It seems the whole chain of processes between init and the process spawned by Qtile has been cut.

Is this desirable behavior? 
It's not really a problem, I'm just loosing information here :slightly_smiling_face: (and Qtile won't appear in my stats/analytics, what a shame :smile: !)

I wonder if this is because Qtile forks itself and replace the fork with `os.execvp`. Maybe using `subprocess` would give the result I was expecting. Or maybe it has nothing to do with Qtile? I'm using ArchLinux by the way.

**Comment by pawamoy** [comment]
I'd like feedback on this one, even if it's just "won't fix" :sweat_smile:

**Comment by pawamoy** [comment]
In fact I'll close this, it's really not important :slightly_smiling_face:

**Comment by tych0** [comment]
Yes, we double fork intentionally. This way if your X session ends, tasks spawned by it do not necessarily end (if they have some way to survive). I think this is definitely a feature, and not a bug :)
