### ISSUE TITLE
Weird behavior with Control-A

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1415]
My tenth issue! Still not finished haha :smile: 

So, I noticed that when I type Control-A, whatever the window, it does weird things like moving windows around (from one screen to another one), or display more windows, all transparent, or flip them around, etc.

I checked my config and I did not define `Key(["control"], "a")` anywhere, so I really don't know what's going on. What would be the best way to debug that? Can I set the log level to DEBUG from my config.py? Or should I subscribe to every event and log what happens from there?

**Comment by ramnes** [comment]
> I checked my config and I did not define `Key(["control"], "a")` anywhere, so I really don't know what's going on. 

I really doubt that it could come from Qtile if you didn't define this binding. Are you running Qtile inside Gnome or something?

> What would be the best way to debug that? Can I set the log level to DEBUG from my config.py? Or should I subscribe to every event and log what happens from there?

You can switch to the debug level directly from the command line with `qtile-cmd -o cmd -f debug`.

**Comment by pawamoy** [comment]
OK thanks.

No Gnome: I'm `exec'ing Qtile from `~/.xinitrc` (with `startx`).

Right now I get this exception:

```
2019-08-30 18:42:08,349 - libqtile - ERROR - Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/core/manager.py", line 724, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 570, in wrapper
    return f(*args)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 611, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 684, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 647, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
```

I also see some Internal Events: client focus and client change.

Also, issue happens only with multiple windows open. If I only have firefox open, Ctrl-A works correctly (select all text in textbox).

**Comment by pawamoy** [comment]
Hmmm, it might be because of Zsh. It seems to only happen when a terminal is open. This is good news :sweat_smile:
