### ISSUE TITLE
docs: how to install Qtile from source in detail?

### ISSUE THREAD

**Issue by whatacold** [qtile/qtile#1417]
Hi,

Installing Qtile via a distro's package manager is a no-brainer.

But, If I want to try the source of master, I'm not sure how to do that exactly. There is a [section](http://docs.qtile.org/en/latest/manual/install/index.html#installing-from-source) on the site about how to install dependent packages, but it doesn't mention how to install Qtile itself actually.

My thought is to:
1. create a system-wide virtualenv
2. copy the source to somewhere, e.g. `/usr/local/bin/`
3. create a new file `/usr/share/xsessions/qtile-venv.desktop`

Am I right? How do you do that?

**Comment by anselal** [comment]
According to the docs I have to install the dependencies via `pip` and qtile via `pip3`.
Is this supposed to work ?

**Comment by ramnes** [comment]
Just use whatever `pip` version you want to use, for both dependencies and the `qtile` package itself. Python 2.7 will be EOL at the end of the month anyway, so `pip2` and `pip3` won't make sense anymore, we'll only have `pip` running in Python 3. I'm updating the docs accordingly.

**Comment by anselal** [comment]
thnx !!

**Comment by tych0** [comment]
Will pip3 ever be renamed to pip though?

**Comment by ramnes** [comment]
Well it seemed obvious to me as `pip3` is just an helper AFAIK, like `pip3.6` and `pip3.7`, but I can always be wrong.

**Comment by tych0** [comment]
What I'm saying is: when python2 is dead, there will never be an executable named `pip` on peoples' systems, so isn't it correct to say `pip3`?

**Comment by ramnes** [comment]
I got you already, Tycho. What I'm saying on my side is that I doubt any distribution will go that route and only keep `pip3`, without a `pip` using Python 3. Actually, I already have a system without Python 2 on Gentoo, and see:

```
$ pip --version
pip 19.1 from /usr/lib64/python3.6/site-packages/pip (python 3.6)
```

**Comment by tych0** [comment]
Oh, interesting. Debian/ubuntu definitely do not use pip3 as an alternative to pip, I just assumed everyone was the same. I would be surprised if they do ever add it, so it's probably worth a note for debian-based distros that you'll have to use pip3.

**Comment by ramnes** [comment]
Yeah, I'm not too surprised. Do you think we should rather write `pip3` everywhere, since this command exists on pretty much every distribution, AFAIK?

**Comment by anselal** [comment]
@ramnes yes !!

**Comment by pawamoy** [comment]
@ramnes Indeed, using `pip3` in the docs makes it obvious that Qtile should be installed under Python 3 only. 

The other solution is to make it *absolutely clear* in the readme and the docs that Qtile is Python 3 only. I'm not sure about the installation statistics of Qtile regardind OSes and their versions, but it's quite common these days for Python packages not to mention Python 2 at all and expect users to use Python 3, or say *"Python >=3.6 required"* only once, in the readme.

Just a note about Debian/Ubuntu: Debian Buster (10), which is was released in July 2019 and is considered the stable version, is using Python 3.7 as default: https://wiki.debian.org/Python.

> At any given time, there is one stable release of Debian, which has the support of the Debian security team. When a new stable version is released, the security team will usually cover the previous version for a year or so, while they also cover the new/current version. Only stable is recommended for production use. 

[Also Debian 8 and 9 are EOL LTS in 2020 and 2022 respectively.](https://wiki.debian.org/DebianReleases#Production_Releases)

I can't believe I wrote all this just for `pip` vs `pip3` :rofl:

**Comment by ramnes** [comment]
Interesting. I would definitely prefer to advertise Python 3 everywhere and not use `pip3` or `python3` in the docs.

**Comment by anselal** [comment]
1. must I run all the `pip3 install` command as root ?
2. when installing qtile via `pip3 install qtile` where will the binary be located ?

**Comment by tych0** [comment]
You shouldn't really ever need to run pip as root; you can find the installed binaries when you run it as a local user at ~/.local/bin/*.

**Comment by whatacold** [comment]
I'm not sure if this helps, but `pip` will point to a version of python 3 within a virtualenv on Fedora 30:

    ➜  ~ pip --version
    pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
    ➜  ~ 
    ➜  ~ source ~/virtualenv/qtile-devel/bin/activate
    (qtile-devel) ➜  ~ pip --version
    pip 19.2.3 from /home/hgw/virtualenv/qtile-devel/lib64/python3.7/site-packages/pip (python 3.7)

**Comment by anselal** [comment]
When I run `pip install .` as a normal user I get an error "Segmentation fault". What does this mean ?

**Comment by whatacold** [comment]
Hmm, that's weird, maybe a bug of pip? Would you like to try to install it with a virtualenv?

There is a similar issue on [Stackoverflow](https://stackoverflow.com/questions/26494324/python-pip-segfault-when-installing-package), which may help, thought it has no direct answer.
