### ISSUE TITLE
Default config uses deprecated lazy

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1420]
Seems to be related to #644.

The default config imports `lazy` from `libqtile.command`, which is deprecated.

It should be imported from `libqtile.lazy` instead. Does it work the same way?

**Comment by ramnes** [comment]
Good catch. IIRC it works exactly the same way.

**Comment by pawamoy** [comment]
I just tried to replace `from libqtile.command import lazy` by `from libqtile.lazy import lazy` and got a `ConfigError` :confused:

**Comment by pawamoy** [comment]
Hmm it might just be because my installed version of QTile lags behind master. 59 new commits since 0.14.2, with a lot of structural changes.
