### ISSUE TITLE
Incorrect reaction to resizing of host display

### ISSUE THREAD

**Issue by gyakushev** [qtile/qtile#1422]
I am running qtile inside a resizable Xephyr window:
```
Xephyr :4 -ac -br -screen 1248x1024 -resizeable
DISPLAY=:4 qtile
```

1. QTile does react to vertical window resizing, but not to horizontal resizing (see screenshot)
2. When increasing vertical size the bottom bar black 'ghosts' are left on screen. They also receive mouse events, not underlying app (see screenshot)
3. Mouse does not work to the right of original window boundary: if I increase window size, mouse only works in the original window rectangle.

Screenshot: https://i.ibb.co/gWqqHRM/Screenshot-from-2019-09-05-16-47-22.png

**Comment by gyakushev** [comment]
Ping? Would be nice to have a fix, the bug is not going away on its own.

**Comment by tych0** [comment]
Patches welcome :)
