### ISSUE TITLE
Typo in docs Hacking

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1424]
The docs state to run `python libqtile/ffi_build.py` to build the `cffi` module. Shouldn't it be `./scripts/ffibuild` instead, like in `libqtile/core/xcursors.py`, line 6:
```python
raise ImportError("No module named libqtile.core._ffi_xcursors, be sure to run `./scripts/ffibuild`")
```

**Comment by ramnes** [comment]
Indeed! Feel free to open a PR directly for that kind of quick fix; don't bother writing an issue/description. :wink:

**Comment by pawamoy** [comment]
Yes I'm planning to! The issues are a way for me to remember :wink:

Also I prefer to ask until I'm more familiar with the code :slightly_smiling_face:
