### ISSUE TITLE
Feature Request: CPU widget

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1439]
We have `Memory` and `MemoryGraph`, `Net` and `NetGraph`, `DF` and `HDDGraph` / `HDDBusyGraph`, but only `CPUGraph` (no `CPU`!). So I'm voting to add a `CPU` widget that simply displays the current CPU load (average on all cores or a specific core) as text.

Note: same thing for a `Swap` widget (unless `Memory` already handles it), though I'm less interested in that.

**Comment by ramnes** [comment]
That would be great, indeed.

**Comment by pawamoy** [comment]
Implemented in #1481 :tada:
