### ISSUE TITLE
MonadTall layout crash/strangeness on moving windows between groups

### ISSUE THREAD

**Issue by daBrado** [qtile/qtile#144]
If I move windows between groups using the MonadTall layout, I sometimes get a crash with an 'list Index out of range' error.  I'm having a hard time finding the minimal case to reproduce the crash, but it seems to only happen when moving to or from groups that have multiple windows...

Sometimes, it doesn't crash, but windows become 'hidden' in the group that they are moved to.  One thing that always causes this strageness for me is if I create two windows group A, go to group B and create a window there, then move that window to group A, when I return to group A I only see two windows, and the third one is somehow hidden (e.g. I can cycle between all three).

The kind of index error I see looks like:

```
*** QTILE REPORT 2012-07-23 22:14:37.711828
Message: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 1077, in _xpoll
    r = h(e)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 1187, in handle_EnterNotify
    self.toScreen(s.index)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 1331, in toScreen
    True
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 445, in focus
    self.layoutAll(warp)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 378, in layoutAll
    self.layout.layout(normal, screen)
  File "/usr/lib/python2.7/site-packages/libqtile/layout/base.py", line 36, in layout
    self.configure(i, screen)
  File "/usr/lib/python2.7/site-packages/libqtile/layout/xmonad.py", line 285, in configure
    height = self.sizes[cidx - 1]
IndexError: list index out of range
```

**Comment by nazar-pc** [comment]
I'm getting something similar relatively frequently, it destroys the whole session so that I have to restart system (Qtile restart doesn't help, windows are still open, but somewhere beyond any group that is present, so that I can't switch to them).
Once I've got it during fullscreen video playback in Firefox and a few times I think on opening/closing windows:
```
2018-02-28 13:18:48,410 libqtile manager.py:handle_KeyPress():L910  KB command error next: Traceback (most recent call last):
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/libqtile/command.py", line 97, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/libqtile/layout/xmonad.py", line 675, in cmd_next
    client = self.focus_next(self.clients[self.focused]) or \
IndexError: list index out of range
```

I'm on 0.10.7 right now

**Comment by flacjacket** [comment]
Hmm, it looks like the MonadTall behavior has changed too much since 0.10.7 to be able to really debug this. If you still see this on the latest version it would be good to get a backtrace of it.

**Comment by nazar-pc** [comment]
Yeah, I've already tried using develop branch and saw your reply. Will report how latest version works later.

**Comment by flacjacket** [comment]
Awesome, thanks, I'd like to get a release out soon (was even thinking tonight) since we are now more than 1 year old. How often would you hit the issue before? Is it something that you would expect to see quickly if this is still an issue? If we need to fix something, it'd be great to do it before a release, but if it's already fixed, even better.

**Comment by nazar-pc** [comment]
Multiple times in an hour, makes Qtile literally unusable. There were also similar issues with other layouts, so I'll try the latest version first and then will see how it goes, might be something common to multiple layouts.

**Comment by nazar-pc** [comment]
Few hours of testing `develop` branch - no crash yet, looks like it is fixed already.
Also this bug report is quite old, I believe you can close it now.

**Comment by flacjacket** [comment]
Great!
