### ISSUE TITLE
Feature Request: custom actions on mouse buttons for all widgets

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1440]
For example, I'd like to open a terminal with `iotop` when I click on the `HDDBusyGraph`, or a terminal with `htop` when I click on `CPUGraph`.

Ideally I would be able to apply these custom actions to **any** widget, overriding existing ones if any.

**Comment by ramnes** [comment]
Interesting. We could probably just add a `widget_click` hook or something in those lines.

**Comment by zordsdavini** [comment]
it should contain not only left click but all 5 :) left, right, middle, scroll down, scroll up. I wanted to add to some widgets custom actions but this idea is much better :+1:

**Comment by pawamoy** [comment]
I would even say the 7 mouse buttons! I have two mice with these two buttons on the left (right-hand mice) which maps to buttons 8 and 9. More buttons available is always interesting.

**Comment by b10011** [comment]
> EDIT: in fact there 9 common buttons on a mouse:

If I remember correctly, only 3 of those will result in a click-event, whereas others are more comparable to keypresses than clicks. And as such, shouldn't there be on_mouseover and on_mouseout so that user could bind any keys to widget's functions during mouseover?
