### ISSUE TITLE
To add config check before restart

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1449]
Maybe ir would be good practice to validate user config before restarting Qtile. We even can implement flag to do Hard code restart what because of broken user config should fall back to default config. But Maybe this iš needless

**Comment by pawamoy** [comment]
So, I wrote a snippet that checks if a configuration file is valid. You can put it in the config file itself, in the `if __name__ == "__main__":` conditional block. Here it is:

```python
if __name__ == "__main__":
    from libqtile.confreader import Config, ConfigError
    from libqtile.core.xcore import XCore

    try:
        Config.from_file(XCore(), __file__)
    except ConfigError as error:
        print(
            "The configuration file '{}' generated the following error:\n".format(
                __file__
            ),
            file=sys.stderr,
        )
        print("{}\n".format(error), file=sys.stderr)

        if str(error).startswith("No such key"):
            # there is an invalid key in the config

            def find_similar_keys(key):
                import regex
                from libqtile.xkeysyms import keysyms

                regexp = regex.compile(
                    r"({}{{e<{}}})".format(key, len(key)), regex.IGNORECASE
                )
                similar_keys = []
                for qtile_key in keysyms.keys():
                    if regexp.match(qtile_key):
                        similar_keys.append(qtile_key)
                if not similar_keys:
                    return "No key similar to '{}' could be found in libqtile.xkeysyms.keysyms :/".format(
                        key
                    )
                if len(similar_keys) == 1:
                    return "Maybe you meant '{}'?".format(similar_keys[0])
                return "Maybe you meant '{}', or '{}'?".format(
                    "', '".join(similar_keys[:-1]), similar_keys[-1]
                )

            print(
                find_similar_keys(str(error).replace("No such key: ", "")),
                file=sys.stderr,
            )
        sys.exit(1)
    else:
        print("OK!")
        sys.exit(0)
```

Now just run `python ~/.config/qtile/config.py` to validate it. It's a bit lengthy, but it will print configuration errors as well as erroneous keys and valid similar candidates if any. This last feature requires `regex` to be installed/importable.

Example output when using `left` instead of `Left`:
```
The configuration file 'config.py' generated the following error:

No such key: left

Maybe you meant 'Left', 'leftradical', 'leftmiddlecurlybrace', 'leftarrow', 'leftt', 'leftanglebracket', 'leftopentriangle', 'leftsinglequotemark', 'leftdoublequotemark', 'leftpointer', 'leftcaret', 'leftshoe', or 'lefttack'?
```

**Comment by zordsdavini** [comment]
Wow. That's the real game. Maybe we should add some snipets to docs? Ir could be in HOWTO format?

**Comment by ramnes** [comment]
I'd be in favor of merging this upstream, granted that we can avoid to depend on `notify-send`.

**Comment by pawamoy** [comment]
When you say merging upstream, you mean in the default config file? Or somehow in the configuration loading mechanism?

To avoid the `notify-send` dependency we could then maybe:
- default to it but be able to change the command with a `command_on_error` variable, something like `command_on_error = "NOTIF_PROG ARGS {message}"
- or take the first installed program in a list (we would need to check what is pre-installed in the most common distributions)
- or a mix of both?
-
Other ideas?

**Comment by ramnes** [comment]
> When you say merging upstream, you mean in the default config file? Or somehow in the configuration loading mechanism?

The later. I was thinking about implementing this directly in the current `cmd_restart`, or add another command that we would use by default.

**Comment by m-col** [comment]
Notifications can be made like this:

```
import gi
gi.require_version('Notify', '0.7')
from gi.repository import Notify
Notify.init('App name')
notifier = Notify.Notification.new('Summary text', 'Body text')
notifier.set_timeout(1000)
notifier.show()
```

libqtile/core/manager.py already imports `gi` [here](https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L217) if dbus is present, which (as I understand it) is a dependency of having notifications in general. This could get around the notify-send dependency.

**Comment by pawamoy** [comment]
@ramnes do you have any advice where I should fit my code? I looked at the `cmd_restart` method, but I'm not sure: should I simply execute all this code at the beginning of the method?

**Comment by tych0** [comment]
I wonder if we can't also add an entry point to the main binary or maybe another script? `qtile-checkconfig` or `qtile check-config` or something.

**Comment by pawamoy** [comment]
Also, is there a way to know which config file was loaded from within the `libqtile.core.manager.Qtile` instance?

**Comment by pawamoy** [comment]
@m-col, your snippet was giving me this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/command.py", line 465, in cmd_function
    function(self, *args, **kwargs)
  File "/home/pawamoy/.config/qtile/config.py", line 135, in validate_and_restart
    notifier.show()
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

It required [this](https://wiki.archlinux.org/index.php/Desktop_notifications#Standalone) to work: installing `notification-daemon` and writing 

```
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon-1.0/notification-daemon
```

to `/usr/share/dbus-1/services/org.freedesktop.Notifications.service`

**Comment by m-col** [comment]
Yep that snippet is a notification client, like notify-send. Your system also needs a notification server to receive the messages and create windows with the information. Looks like you had one installed in your first screenshots though

**Comment by m-col** [comment]
That `notification-daemon` program you needed is playing the same role as what I implemented in #1521 that we discussed.

**Comment by pawamoy** [comment]
OK yes, I understand now, thanks again for your explanations @m-col  :slightly_smiling_face:

**Comment by tych0** [comment]
So this all looks pretty slick to me; @m-col can you send your notification-daemon code so we can rebase this and it'll be totally self-contianed?

**Comment by m-col** [comment]
Yep can do. I'll reply on that issue to discuss things specific to that.

**Comment by ramnes** [comment]
Merged! Thanks everyone.
