### ISSUE TITLE
High cpu usage when playing TrackMania in fullscreen

### ISSUE THREAD

**Issue by Brn9hrd7** [qtile/qtile#1450]
I have noticed that the gaming performance when playing TrackMania United Forever is significantly worse when using qtile compared to other window managers/desktop environments. According to Sysprof qtile uses around 25% of my CPU while playing this game, which is the cause for the bad performance.
![Bildschirmfoto von 2019-09-14 19-56-14](https://user-images.githubusercontent.com/46742447/64912050-3bdcef80-d719-11e9-9820-deb7789af276.png)
![Bildschirmfoto von 2019-09-14 19-56-32](https://user-images.githubusercontent.com/46742447/64912051-3bdcef80-d719-11e9-9407-8c01e746e591.png)

This only happens when the game runs in fullscreen, in windowed mode the CPU usage is below 1%. I have tried a few other games, but this game is the only one that is causing problems so far. The free version of the game(TrackMania Nations Forever) is most likely affected too, so if someone is interested in fixing(or trying to reproduce the issue) you could use that one as well.

**Comment by Brn9hrd7** [comment]
I've figured out the problem, it looks like it's caused by a patch in wine-staging, that isn't present in the regular wine version. I'll close this issue, since it's probably not qtile's fault(I had the same issue in Xmonad, although the performance impact wasn't as big there).

**Comment by ramnes** [comment]
Do you know which blob exactly? Can you link the patch?

**Comment by Brn9hrd7** [comment]
Just finished bisecting this issue, it's caused by [this patch](https://github.com/wine-staging/wine-staging/blob/master/patches/winex11-WM_WINDOWPOSCHANGING/0001-winex11.drv-Send-WM_WINDOWPOSCHANGING-WM_WINDOWPOSCH.patch).
