### ISSUE TITLE
Opened logo request on VectorLogoZone

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1456]
I just opened a request on VectorLogoZone: https://github.com/VectorLogoZone/vectorlogozone/issues/36. I linked the PNG file, but maybe you have an SVG one ready somewhere?

There's not much activity on VLZ, but I still like it and use it for example in credits page like [this one](http://pawamoy.github.io/credits/). Maybe they simply would like more people to contribute the logos. Unfortunately I don't have the skills to do it. Anyway, feel free to close if there's nothing to do from here!

**Comment by tych0** [comment]
I don't know that we do have one, unfortunately :(. I'll close for now, thanks!
