### ISSUE TITLE
resize layouts

### ISSUE THREAD

**Issue by pranaykinng** [qtile/qtile#1464]
How to resize layouts like mod+r in i3?

**Comment by pawamoy** [comment]
What does "resizing" do in i3?

**Comment by pranaykinng** [comment]
We can manually resize the layout of tiling windows in using the arrow keys in i3..

**Comment by pawamoy** [comment]
Got it.

In Qtile you would define your keys in your config file like so:

```
keys = [
    ...
    Key([mod, "r"], "Left", lazy.layout.grow_left()),
    Key([mod, "r"], "Up", lazy.layout.grow_up()),
    Key([mod, "r"], "Down", lazy.layout.grow_down()),
    Key([mod, "r"], "Right", lazy.layout.grow_right()),
    ...
]
```

In some layouts, you have only grow methods, not shrink ones, so you have to change focus to a window's neighbor to shrink it. Other layouts have both grow and shrink methods.

You can also check the code snippets in this issue: #1402. These are functions that allow to grow **and** shrink windows with the same keys. They are written for the BSP layout so you'll maybe have to adapt them if you are using another layout.

**Comment by pranaykinng** [comment]
@pawamoy i did that its working but i ain't enjoying it i think i will stay with i3wm, qtile is fine but still needs a lot of work.
Thanks but u were helpful.

**Comment by pawamoy** [comment]
No problem, you'll come back to Qtile later :wink:

Just joking, go with what you enjoy of course!

**Comment by ramnes** [comment]
What is it exactly that you don't like, @pranaykinng?

**Comment by pranaykinng** [comment]
@ramnes Well i am really new to tiling wm so i am having fun with i3wm as there is lot of content available to easily configure it while in qtile it is taking a lot more time configuring it.

**Comment by inaugur** [comment]
Is it possible to do same thing with mouse?

**Comment by pawamoy** [comment]
@inaugur There's discussion about that in #855. Short answer: not yet.

**Comment by ramnes** [comment]
Closing in favor of #855 (also, the discussion diverged quite a bit).

**Comment by ramnes** [comment]
@pranaykinng I would love more feedback and examples on how simpler it was to configure i3 than Qtile!
