### ISSUE TITLE
Is there a way to change keybindings on the fly?

### ISSUE THREAD

**Issue by kureta** [qtile/qtile#1472]
I have tried to `.clear` and `.extend` the `keys` list in a `layout_change` hook but it doesn't seem to have any effect.

**Comment by osimplex** [comment]
As far as I know, there isn't this for now.

There is a way to add and remove rules and groups. You only can see your KB using `qtile-cmd -o cmd -f display_kb'.

**Comment by osimplex** [comment]
This kind of thing is at `core.manager`: https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L478

**Comment by kureta** [comment]
How can I access that from my config file?

**Comment by kureta** [comment]
OK. I have figured it out. `layout_change` hook gives me acces to `group`, which has `group.qtile` attribute, that is the actual Qtile manager instance.

I have the list of previous keybindings. First I unbind all of them, modify the `keys` list and rebind them as follows:

```
@hook.subscribe.layout_change
def on_layout_change(layout: Layout, group: Group):
    for k in keys:
        group.qtile.unmap_key(k)

    # modify the keys list

    for k in keys:
        group.qtile.map_key(k)

**Comment by pawamoy** [comment]
I believe you could write that instead:

```python
@lazy.function
def modify_keys(qtile):
    for k in keys:
        qtile.unmap_key(k)

    # modify the keys list

    for k in keys:
        qtile.map_key(k)
```
Then call the function directly or bind it to a key.

**Comment by kureta** [comment]
Thanks. I didn't know about the `@lazy.function` decorator. I just wanted to use different keybindings for `bsp` and `monadtall` layouts so the hook is fine for this use case. But that is one handy decorator. I'm sure it'll be useful. Thanks again.
