### ISSUE TITLE
How do I install the pangocairo dependency ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [qtile/qtile#1473]
I am using Void linux and I have figured all dependencies except pangocairo ... is it the same thing as pangocairocffi ?

**Comment by whatacold** [comment]
Have you tried installing `libpangocairo`? e.g. `sudo apt-get install libpangocairo-1.0-0` on Ubuntu as in http://docs.qtile.org/en/latest/manual/install/index.html#pangocairo .(I'm not familiar with Void Linux.)

**Comment by flacjacket** [comment]
`pangocairo` should be installed by pango if it configured to use cairo as a dependency via `--with-cairo`

**Comment by tych0** [comment]
I'll go ahead and close this for now. Feel free to re-open or hit the ML up if you are still having trouble.
