### ISSUE TITLE
Change groups from screen_change hook?

### ISSUE THREAD

**Issue by arsen-ch** [qtile/qtile#1474]
Hello

Is it possible to run such code from a `screen_change` hook?
This works only in xephyr:
```
@hook.subscribe.screen_change
def group_map(qtile, ev):
    group = qtile.groups[2]
    qtile.screens[0].set_group(group)
```

The idea is to run various commands immediately after loading. Maybe there is another way?

**Comment by arsen-ch** [comment]
I solved the problem like this:

> config.py:
```
@hook.subscribe.startup_once
def autostart():
    script = os.path.expanduser('~/.config/qtile/scripts/autostart.sh')
    subprocess.call([script])
```

> autostart.sh
```
~/.config/qtile/scripts/autopost.py &
```

> autopost.py
```
#!/usr/bin/env python

import time
from libqtile.ipc import find_sockfile, Client
from libqtile.command_client import InteractiveCommandClient
from libqtile.command_interface import IPCCommandInterface


time.sleep(3)

cli = Client(find_sockfile())
ipc = IPCCommandInterface(cli)
icc = InteractiveCommandClient(ipc)

client = icc
client.group['7'].toscreen(1)
client.group['1'].toscreen(0)

```
Maybe someone will find it useful.

**Comment by pawamoy** [comment]
I guess it could be greatly simplified if the `startup_once` hook accepted a `qtile` parameter. This feature was actually requested in another issue: https://github.com/qtile/qtile/issues/1401

**Comment by m-col** [comment]
> I guess it could be greatly simplified if the startup_once hook accepted a qtile parameter. 

This functionality exists: if you define a `main` function in your config it will be executed after config loading and is passed the `qtile` instance.

**Comment by ramnes** [comment]
@m-col answer is the way to go. I'll go ahead and close this, but feel free to comment if needed!
