### ISSUE TITLE
Battery widget error: Unable to read status for status_file

### ISSUE THREAD

**Issue by osimplex** [qtile/qtile#1476]
Qtile 0.14.2 - Arch Linux

My battery widget config:
```python
Battery(
	battery = 0,
	format = "{char} {percent:0.1%}",
	update_interval = 5,
	low_percentage = 0.05,
	full_char = "",
	charge_char = "+",
	discharge_char = "-",
	empty_char = "",
	low_foreground = self.color.red
)

```

Qtile log:
```
2019-10-14 23:11:33,865 ERROR libqtile battery.py:_load_file():L235 Failed to get status
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/widget/battery.py", line 222, in _load_file
    path = os.path.join(self.BAT_DIR, self.battery, name)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
```

**Comment by osimplex** [comment]
The solution that I found is put this on 222L:
```python
path = os.path.join(self.BAT_DIR, "BAT" + str(self.battery), name)
```

**Comment by osimplex** [comment]
The solution is put this on 222L:
```python
path = os.path.join(self.BAT_DIR, "BAT" + str(self.battery), name)
```

**Comment by ramnes** [comment]
@osimplex, does the PR I've submitted fix your problem?

**Comment by flacjacket** [comment]
The battery widget is configured with the full name of the battery, so you could specify `"BAT0"` rather than `0`, is there a reason to prefer the int value over the full name?

**Comment by zordsdavini** [comment]
and why you need to specify `battery`. For `BAT0` it should work out of the box. Try not to give that argument. Example of my config:
```
widget.Battery(discharge_char='↓', charge_char='↑', format='{char} {hour:d}:{min:02d}', foreground=YELLOW, low_foreground=RED),
```

**Comment by zordsdavini** [comment]
I checked widget. I don't have BSD but I think this is something from last updates to support BSD (https://github.com/qtile/qtile/commit/dc46f9f044c0db025fb4fe9012053cbff634cd6c), so documentation is bad and `self.battery` as default takes `0` (integer). This property is used for BSD systems as integer (and as string in `class _FreeBSDBattery(_Battery): -> __init__(self, battery='0'):`) but in Linux it takes as string ex. `BAT0` (no defaults for __init__, just **config).

**Comment by osimplex** [comment]
> @osimplex, does the PR I've submitted fix your problem?

Yes, fixes the problem.

> so documentation is bad and self.battery as default takes 0 (integer).

With this PR, the documentation is now consistent across Linux and BSD since who have two batteries (some thinkpad users with slice battery) can just use `0` or `1` on Linux and maybe BSD (don't have BSD here to try this) .
(v. http://docs.qtile.org/en/latest/manual/ref/widgets.html#battery)

**Comment by osimplex** [comment]
> @osimplex, does the PR I've submitted fix your problem?

Yes, fixes the problem.

> so documentation is bad and self.battery as default takes 0 (integer).

With this PR, the documentation is now consistent across Linux and BSD since who have two batteries (some thinkpad users with slice battery) can just use `0` or `1` on Linux and maybe BSD (don't have BSD here to try this) .
(v. http://docs.qtile.org/en/latest/manual/ref/widgets.html#battery)
