### ISSUE TITLE
config Err when qtile is installed differently ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [qtile/qtile#1479]
when I install qtile using: 
+++
git clone git://github.com/qtile/qtile.git
cd qtile
pip3 install .
+++
everything works fine, but when I install it using:
+++
pip3 install qtile
+++
I get a config Err ...why is that ?

**Comment by zordsdavini** [comment]
Try `pip show qtile` to get version. From pip you installed 0.14.2 I giess. By github ypu installed development version

**Comment by zordsdavini** [comment]
It looks like iy is time to bump version 😀

**Comment by ramnes** [comment]
As @zordsdavini said, `pip3 install qtile` will install the latest release, while cloning the repository and executing `pip3 install .` will install the current development version.

If you want to debug your configuration for the version on which it doesn't work, you can execute `python3 config.py` and/or take a look at the `~/.local/share/qtile/qtile.log` file to hunt any error.

Feel free to ping me here or open another issue if needed. :wink:

**Comment by ReductoAdAbsurdum** [comment]
So the config.py for a version is not compatible with another version ? no backwards compatibility ?

**Comment by ramnes** [comment]
We document the most changes in the [CHANGELOG](https://github.com/qtile/qtile/blob/master/CHANGELOG), especially the breaking ones. We try to not change the API as much as possible (i.e. how a normal config file would look) but the internals might change more regularly, so if you're using them you must keep an eye to the changes.

See this part of the CHANGELOG for an example of what kind of things we allow ourselves:

> Many internal things were renamed from camel case to snake case. If your config uses main(), or any lazy.function() invocations that interact directly with the qtile object, you may need to forward port them. Also note that we do *not* consider the qtile object to be a stable api, so you will need to continue forward porting these things for future refactorings (for wayland, etc.). A better approach may be to add an upstream API for what you want to do ;)
