### ISSUE TITLE
what do the gray and blue workspace tag borders mean ? 

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [qtile/qtile#1486]
I look at other people's setup and they don't have gray tags....what do gray tags mean ?

**Comment by pawamoy** [comment]
I guess you found the answer :slightly_smiling_face:? It must be: blue border for the group being displayed on the current screen, gray border on groups displayed on other screens?

**Comment by ReductoAdAbsurdum** [comment]
yeah I figured...many thanks
