### ISSUE TITLE
Unable to run "scrot -s" using lazy.spawn()

### ISSUE THREAD

**Issue by mwip** [qtile/qtile#1488]
I usually use two keybindings for screenshots: 
1. `Print`: Full screen is recorded. 
2. `Shift + Print`: select an area for the screenshot. 

I wanted to use the following key bindings. 
```
Key([], 'Print', lazy.spawn("scrot '%Y-%m-%d_$wx$h.png' -e 'mv $f /tmp/shot.png && xclip -selection clipboard -t image/png -i /tmp/shot.png && notify-send \"screenshot copied to clipboard\"'")),
Key([mod, 'shift'], 'Print', lazy.spawn("scrot -s '%Y-%m-%d_$wx$h.png' -e 'mv $f /tmp/shot.png && xclip -selection clipboard -t image/png -i /tmp/shot.png && notify-send \"screenshot copied to clipboard\"'"))
```

The first one works just fine. The second, however does not. ~~I tested the second command by assigning it to `Print` only and it works.~~

I think this is a bug which does not allow modifiers in combination with the `Print`key.

**Comment by ramnes** [comment]
Why the `mod` in `[mod, 'shift']` if all you want is shift + print?

**Comment by mwip** [comment]
oh, my bad. that's just a leftover from the tests I ran. Anyways, it does not work.

**Comment by whatacold** [comment]
What about replacing `"Print"` with `"3270_PrintScreen"`, as defined in [xkeysyms.py](https://github.com/qtile/qtile/blob/master/libqtile/xkeysyms.py#L535) ?

**Comment by pawamoy** [comment]
Could you also check the output of `xev` when hitting Shift+Print?

```bash
xev & sleep 5; pkill xev  # you have now 5 seconds to hit Shift+Print
```

**Comment by mwip** [comment]
I'd leave the less crowded
```
xev | grep keycode
#    state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
#    state 0x11, keycode 107 (keysym 0xff61, Print), same_screen YES,
```
The keys are registered just fine. In fact, when is use shift-print on the first command, i.e. scrot without the '-s` flag, it works just fine. Apparently when I stated that "I tested the second command by assigning it to Print only and it works.", I must have gotten something confused. In fact it does not work. Sorry for the misleading. 

Some testing lead to the real problem: It's not the keys that are not registered, but `scrot -s` cannot be run from `lazy.spawn()`. It is also *not* possible to run by invoking a script

```
./test_scrot.sh
---------------------------------------------------
#!/bin/bash
scrot -s 
```

**Comment by McCroden** [comment]
I am using imagemagick instead of scrot (I think I had the same problem, but it was a while ago). Putting this here in case it helps others. 

```python
from libqtile.config import EzKey
keys = [EzKey(k[0], *k[1:]) for k in [
    # Screenshot selector with PrtScr button on keyboard
    ("<Print>", lazy.spawn(f"'{scripts_path}/screenshot_imagemagick'")),
    # Open last screenshot
    ("M-S-<Print>", lazy.spawn(f"'{scripts_path}/open_last_screenshot'")),
]]
```

Here are the scripts:
screenshot_imagemagick:
```sh
#!/bin/bash
_now=$(date +"%Y_%m_%d-%H_%M_%S")
_file="${HOME}/Pictures/screenshot/img-${_now}.png"
import $_file
```

open_last_screenshot:
```sh
#!/bin/bash
# Script to open the most recent screenshot
# Screenshot folder
screenshot_path=~/Pictures/screenshot
sxiv -f $screenshot_path/$(ls -t1 $screenshot_path | head -1)
```

**Comment by mwip** [comment]
Wow, @McCroden thanks for this hint! I immediately changed my workflow to imagemagick. 

However, I would leave the issue open, as it seems to be an issue of how qtile approaches `lazy.spawn()` and therefore might also be related to other programs than `scrot`.

**Comment by pawamoy** [comment]
Maybe worth noting: `xfce4-screenshooter -r` works fine with `lazy.spawn()` (`-r` is to select a region, similarly to scrot's `-s` option).

**Comment by binaryronin** [comment]
I currently use `maim` and pipe that into `xclip` in order to quickly screen shot regions for Slack etc.. I can confirm that `lazy.spawn()` does not work for this either. I've also tried using `subprocess` and that doesn't work either. Any workarounds?

Here is my `maim` command: `maim -s | xclip -selection clipboard -t image/png`

**Comment by tych0** [comment]
I think the confusion here is that lazy.spawn() is not a shell. If you want to use it as a shell, either do something like `lazy.spawn(["sh", "-c", "command that expects a shell | other command"])` or make it into a script itself.

I'll close this for now, as I don't believe there's a bug that should be fixed.
