### ISSUE TITLE
qtile no on apt

### ISSUE THREAD

**Issue by Ara0n** [qtile/qtile#1493]
running either debian 10 or testing qtile is not in apt, contrary to what is said in the website (http://docs.qtile.org/en/latest/manual/install/ubuntu.html) :/
```
$ sudo apt install qtile  
[sudo] Mot de passe de thomas : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet qtile
```

**Comment by ramnes** [comment]
@tych0 can you take a look at this?

**Comment by tych0** [comment]
Hmm, I guess it didn't get promoted to stable then? Seems like without a maintainer it might be perpetually in unstable. I'll send a PR to change the docs. FWIW, the version in unstable is quite old, so maybe we shouldn't tell people to install it from there at all.

**Comment by LeLobster** [comment]
Looks like qtile is no longer in the Debian repos at all anymore  
https://packages.debian.org/search?keywords=qtile&searchon=names&suite=all&section=all

Yet the qtile docs still mention it being available in Unstable  
http://docs.qtile.org/en/latest/manual/install/ubuntu.html

I'm assuming it went by unmaintained for too long, and thus has been removed?
