### ISSUE TITLE
Hide the bottom bar in qtile

### ISSUE THREAD

**Issue by georgebush422** [qtile/qtile#1497]
I want no title bars or panels on the screen. In qtile, there are no title bars by default (unlike i3), so that is solved. I want the bottom bar to show up when a specific button is pressed and then go back to hide when the button is released. It was pretty straightforward in i3, but I got confused by the documentation when it came to qtile. Here's my i3 setup for reference.

![screenshot](https://66.media.tumblr.com/edecbac68229e04a988c5b80dba16064/f6fd4774cfda3c5e-5e/s1280x1920/e34fed8fd7046a8e92e66f170fc44686915124ef.png)

To elaborate, I came across [http://docs.qtile.org/en/latest/\_modules/libqtile/bar.html](http://docs.qtile.org/en/latest/_modules/libqtile/bar.html). The Bar class had these functions named `handle_buttonPress()` and `handle_buttonRelease()`, but the definitions don't seem to do what I want them to do. They look like they handle the widgets which the bar contains. Help?

**Comment by zordsdavini** [comment]
You can check my config with:
```
@hook.subscribe.startup
def startup():
    bottom.show(False)
```
with 
```
Key("M-S-x", lazy.hide_show_bar("top")),
Key("M-C-x", lazy.hide_show_bar("bottom")),
```
in https://github.com/zordsdavini/dotfiles/blob/master/.config/qtile/config.py

**Comment by georgebush422** [comment]
@zordsdavini, thanks. I'll try it out.

**Comment by georgebush422** [comment]
@zordsdavini, can you show me the reference to lazy.hide_show_bar()? I can't seem to find it. Also, can you explain the syntax you used to define the Key object? The default configuration does it in a slightly different way.

**Comment by zordsdavini** [comment]
the method is here: http://docs.qtile.org/en/latest/manual/ref/commands.html#libqtile.core.manager.Qtile.cmd_hide_show_bar
and the Key object what I use is EzKey: `from libqtile.config import EzKey as Key` . You can read about it in http://docs.qtile.org/en/latest/manual/config/keys.html#keys .

**Comment by georgebush422** [comment]
Thanks for the info, but let me elaborate what I need exactly.

Think of the super (mod4) key. When I press (not tap, tap = press + release) it, the bar should appear and when I release it, the bar should disappear.

**Comment by zordsdavini** [comment]
I don't think we support press + release events. For floating maybe wm class could work

**Comment by georgebush422** [comment]
Maybe I can add it if it isn't already there.
