### ISSUE TITLE
Qtile 0.14.2 Elementary Hera 5.1

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#1502]
Hello,

I am trying to install Qtile 0.14.2 on Elementary Hera 5.1, but pip3 gives me this error, is there a way i can force pip3 to install it?

Thanks for the help.

this is the log

gibranlp@Elementary:~/qtile$ pip3 install .
Processing /home/gibranlp/qtile
Collecting cffi>=1.1.0 (from qtile==0.14.2)
  Using cached https://files.pythonhosted.org/packages/49/72/0d42f94fe94afa8030350c26e9d787219f3f008ec9bf6b86c66532b29236/cffi-1.13.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting cairocffi[xcb]>=0.9.0 (from qtile==0.14.2)
  Downloading https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 421kB/s 
Collecting xcffib>=0.8.1 (from qtile==0.14.2)
Collecting pycparser (from cffi>=1.1.0->qtile==0.14.2)
Collecting setuptools>=39.2.0 (from cairocffi[xcb]>=0.9.0->qtile==0.14.2)
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 1.6MB/s 
Collecting six (from xcffib>=0.8.1->qtile==0.14.2)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Building wheels for collected packages: cairocffi
  Running setup.py bdist_wheel for cairocffi ... done
  Stored in directory: /home/gibranlp/.cache/pip/wheels/11/5e/47/167d9dfd5fa5850dd0cd3db80afe6db46e620edec3419dce5a
Successfully built cairocffi
Installing collected packages: pycparser, cffi, setuptools, six, xcffib, cairocffi, qtile
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 141, in distutils_scheme
    d.parse_config_files()
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/dist.py", line 494, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/config.py", line 110, in parse_configuration
    options.parse()
  File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/config.py", line 380, in parse
    self.section_prefix, section_name))
distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]

**Comment by whatacold** [comment]
Have you upgraded `setuptools`? You'd better upgrade `pip` too.

    pip install -U pip setuptools

**Comment by gibranlp** [comment]
should i use pip or pip3?

**Comment by whatacold** [comment]
Well, I'm not quite sure, but I think `pip3` should work. And there is a related "pip vs pip3" discussion on issue #1417 , in case you're interested.

**Comment by pawamoy** [comment]
- Installed Qtile with `pip3`? Use `pip3`.
- Installed Qtile with `pip` with system Python version >= 3? Use `pip` again.

**Comment by lxbarbosa** [comment]
I think you have run in this issue https://github.com/qtile/qtile/issues/994#issuecomment-497984551

**Comment by gibranlp** [comment]
I have updated setuptools and pip to no avail, im working on some stuff will let you guys know if it works.

**Comment by tych0** [comment]
I'm gonna go ahead and close this; it looks like updating setuptools is the path forward. Let us know if that still doesn't work.

FWIW, I'm on:

```
~ python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'41.1.0'
```
