### ISSUE TITLE
mouse pointer size 

### ISSUE THREAD

**Issue by Selion05** [qtile/qtile#1503]
With most of my applications the pointer is to big but on the wallpaper or thunar file manager its normal. the pointer itself is also different.

Is there a way to control that? 

some system info
OS: Manjaro Linux x86_64 
Kernel: 5.3.15-1-MANJARO 
Resolution: 3840x2160 
DE: qtile 
WM: LG3D

**Comment by Brn9hrd7** [comment]
The cursor theme and size can be changed using the .Xresources file in your home directory(create it if it doesn't exist).
E.g.:
```
Xcursor.theme: Adwaita
Xcursor.size: 36
```
You can find the exact names of your installed cursors by running `find /usr/share/icons ~/.local/share/icons ~/.icons -type d -name "cursors"`.

**Comment by Selion05** [comment]
thanks, I can not test it on the machine where it happens right now but I'm pretty sure it will work :)
