### ISSUE TITLE
Fix and unify mpd and mpd2 widgets

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1509]
I have used the Mpd2 widget for a while and it will sometimes stop responding to mpd state changes and keypresses. I think this is due to how it keeps track of its client connection, and should be a simple fix.

Looking at this widget and the original Mpd widget, I think they could be unified into a single Mpd widget using code from both (e.g. Mpd has some functionality that never made it to Mpd2).

I'd be happy to make and submit these changes.

**Comment by m-col** [comment]
I've merged them together on [my branch](https://github.com/m-col/qtile/tree/unify_mpd_mpd2_widgets). It contains only one mpd widget, `Mpd`, which has the updates that `Mpd2` had, some tricks from `Mpd` that never made it to `Mpd2` (e.g. text foreground color acting as progress meter), and some fixes for some circumstances that would make `Mpd2` die. It works with either python-mpd2 or python-musicpd. The original python-mpd is deprecated.

I will use it for a few days for testing before submitting a PR - if there is interest in the update.

**Comment by m-col** [comment]
I think we can close this in favour of #1306.

**Comment by tych0** [comment]
Ok; should I just merge that one and close your other one #1514 as well?

**Comment by m-col** [comment]
Yep!
