### ISSUE TITLE
EzKey does not allow description

### ISSUE THREAD

**Issue by lulivi** [qtile/qtile#1510]
I think the [EzKey constructor](https://github.com/qtile/qtile/blob/master/libqtile/config.py#L155) does not allow a description (no `kwds` variable) although [Key constructor](https://github.com/qtile/qtile/blob/master/libqtile/config.py#L53) does. 

Edit: Why do you set the description within a dictionary instead of having a constructor argument for it?

Edit 2: Forgot my versions and stuff:

|    Item   |     Version    |
|:---------:|:--------------:|
|   Qtile (from official repositories)   |     0.14.2     |
| ArchLinux | 5.4.6-arch3-1 |

**Comment by ramnes** [comment]
Indeed, it looks like the keyworded arguments were forgotten.

As for your second question, the documentation seems incorrect: you don't have to pass a dictionary, just a `desc` keyworded argument. The dictionary is just a way to pack all keyworded arguments in the function, as seen with the `**` notation.

**Comment by lulivi** [comment]
Thank you for your responses! Would you like for me to create a pull-request with the keyworded argument added to EzKey class constructor?

**Comment by ramnes** [comment]
Of course, please do!
