### ISSUE TITLE
Screenshots: how and where to add them?

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1512]
Now that #1423 has been merged, we should discuss how and where the screenshots should be added.

Where:

- in the official documentation?
- in the wiki?

How:

- manual updates of the docs/wiki?
- tox env + CI job?

#### Wiki

If we go with the wiki, I guess we'll update the markdown files manually, and upload the pictures/gifs on GitHub to avoid versioning them in the wiki repo. However that would be a lot of work to keep the wiki up to date, since layouts commands descriptions would have to be duplicated over the wiki, and updated every time they change. Maybe we could consider writing a script to output a markdown document with description and inlines GIFS, but that seems a bit complicated...

#### Official docs

If we go with the official documentation (which I favor), we should decide if we track the GIFs in the repository, directly or with LFS (~500K worth, probably growing with time), or if we host the GIFs on a third-party service (GitHub? something else?). What would be great is that the URL/path used in docstrings does not have to be updated when the GIF changes.

```python
def cmd_flip_left(self):
    """
    Swap the position of the focused window's node with its left neighbor.

    .. image:: screenshots/layout/bsp/flip_left.gif
        :alt: Swap node position to the left

    Or

    .. image:: https://THIRD-PARTY.com/QTILE_NAMESPACE/screenshots/layout/bsp/flip_left.gif
        :alt: Swap node position to the left
    """
```

We must also make sure the GIFs are up-to-date when a layout command changes.

#### Vocabulary

As you can see in the docstring example above, it might not be clear what a "window" or "node" is. I think we should discuss about the terms we use and how. Each term should be well explained in the docs.

- window = ?
- layout = ?
- client = ?
- node = ?

**Comment by ramnes** [comment]
I'd go for the official documentation. We can add a task in Travis that runs the script and upload the images somewhere, with a filename that never changes (the layout's name, for example), so that the documentation doesn't have to be updated. As to where upload the images, I'd say to add them directly (no LFS for now) in the [the static/img directory of qtile.org](https://github.com/qtile/qtile.org/tree/master/qtile/static/img). Then we'd add some Travis magic here to auto-deploy the website, which IIRC is not the case yet.

**Comment by pawamoy** [comment]
Alright, so:

- [ ] 1. activate qtile.org repository on Travis, add a job to auto-deploy on push
- [ ] 2. on qtile's Travis, add a job that
  - clones qtile.org
  - generates the screenshots into qtile.org/qtile/static/img/screenshots/layouts directory
  - pushes the files using Travis secret credentials (a GitHub token would be the best I think)
- [ ] 3. update layouts docstrings to include the screenshots URLs

For `#1`, I can try and send a PR to qtile.org with a Travis configuration if you tell me how the site is deployed, otherwise I'll need someone with access+knowledge to do it. In any case, someone with access to the qtile org on GitHub must activate it on Travis.

For `#2`, I will need someone with access to generate a token with push access to qtile.org and add it as a secret in Travis. I'll also need to know what name and email I should use in git config (`Travis CI <qtile@qtile.org>`?), to push from the Travis job.

**Comment by pawamoy** [comment]
Maybe a GitHub deploy key would be better than a token.

Some resources:
- https://stackoverflow.com/questions/49839883/pushing-on-a-git-repository-with-travis-ci
- http://markbucciarelli.com/posts/2019-01-26_how-to-push-to-github-from-travis-ci.html
- https://www.vinaygopinath.me/blog/tech/commit-to-master-branch-on-github-using-travis-ci/

**Comment by pawamoy** [comment]
Following our discussion in the IRC channel:

I searched the internet for programs allowing to take screenshots directly in SVG, unfortunately I found none.

So I searched for tools allowing to convert from PNG to SVG, and found `potrace` and this repo: https://github.com/migvel/color_trace

- it seems `potrace` does not handle colors
- `color_trace_multi.py`'s results are not really satisfying, and more importantly results are different across two runs (generate screenshot, convert to a.svg, generate same screenshot, convert to b.svg, a and b are different). I'm not sure whether the difference happens when taking the screenshot or when converting the file to SVG.

**Comment by zordsdavini** [comment]
IDK discussion in IRC, but do we really nead SVG? Maybe it would be better to have them faster in docs?

**Comment by pawamoy** [comment]
Using SVG was an idea of @ramnes to have idempotent files across different runs. Currently we have PNGs and GIFs, which differ each time we regenerate them. The use-case was that, with idempotent files, we could have tracked them in the website repository without generating tons of diff for each CI run.

**Comment by ramnes** [comment]
More formats we could investigate: https://ezgif.com/help/alternative-animated-image-formats

**Comment by pawamoy** [comment]
Still relevant :slightly_smiling_face:  Discussion happened on IRC a bit.
