### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by MerrinX** [qtile/qtile#1513]
hey, i am looking for how to add wallpaper. This might not be a bug, but could not find andy doc on how. If you could please show me an example i would much appreciate it.

**Comment by ronniedroid** [comment]
You can use nitrogen, then put ' nitrogen --restore & ' to your autostart.sh script

**Comment by fardke** [comment]
Or you can use feh. Add in your autostart.sh :
`feh --bg-scale ~/path/to/your/wallpaper&`

**Comment by ramnes** [comment]
On top of the solutions above, there is the [wallpaper widget](http://docs.qtile.org/en/latest/manual/ref/widgets.html#wallpaper), which uses feh behind the scenes. You can also try out the pull request #1495, which implements another way of setting a wallpaper per screen, directly through X.

So you have several solutions here, I'll close this issue. Feel free to comment if you want it reopen for some reason!

**Comment by pawamoy** [comment]
Hmmm maybe this deserves a section in the wiki 🙂 
I'll create a new page.
