### ISSUE TITLE
Qtile doesn't respect WM_SIZE_HINTS

### ISSUE THREAD

**Issue by Brn9hrd7** [qtile/qtile#1518]
Qtile by default sets all windows with the WM_STATE "dialog" to floating automatically. But there are also some programs that use WM_STATE "normal" and only set a minimum and maximum window size hint. I think windows with a maximum window size hint should be set to floating as well, otherwise they can look pretty weird because they're not meant to be sized differently. An example for this would be the startup dialog and the info dialog of Steam.

**Comment by pmkap** [comment]
I have a hook for this in my `config.py`:

```@hook.subscribe.client_new
def floating_size_hints(window):
    hints = window.window.get_wm_normal_hints()
    if hints['max_width']:
        window.floating = True
```

Maybe this should be in the docs or in the default config.

**Comment by ramnes** [comment]
Nice! PR welcome!

**Comment by pmkap** [comment]
Alternatively, I can try to make the changes in `floating.py` and `window.py` if this is preferable.

**Comment by ramnes** [comment]
As you feel. Did you ever see anything wrong with it? I'm kinda worried it could have indésirable side effects, i.e. put in floating applications that do not handle their hints correctly but aren't meant to float. I'm adding it to my configuration right now to experiment with it.

**Comment by ramnes** [comment]
So far so good, it makes a lot of things I previously manually handled in my configuration floating by default.

**Comment by pmkap** [comment]
I cannot tell about side effects yet because I also just started using it. I will observe, though. Please note I just made another small change in in my comment above. I made a mistake before.

**Comment by ramnes** [comment]
I modified it a tiny bit to make it (I think) even simpler:

```python
@hook.subscribe.client_new
def set_floating(window):
    if window.window.get_wm_normal_hints().get("max_width"):
        window.floating = True
```

**Comment by pmkap** [comment]
Ok, but this could possibly lead to an AttributeError because `get_wm_normal_hints` either returns a dict or None. I didn't check on which occasions it returns None but it's in the code.

**Comment by ramnes** [comment]
Ah, right! Ignore my previous comment.

**Comment by pmkap** [comment]
Is there a reason why the `class Floating` has different parameters `float_rules` and `auto_float_types`? This is somehow confusing. Even more if we add additional floating properties like the maximum size.
My idea is to have one new parameter for all information about which windows to float. Maybe like this:
```python
float_props = {
    'wmtype': ['toolbar', 'splash'],
    'role': ['About'],
    'wmclass': ['file_progress, classB'],
    'wmname': [name1, name2],
    'wmhint': ['max_width'],
}

# default + custom rules
floating_layout = layout.Floating(border_focus='#0000ff', float_props=float_props)

# only custom rules
floating_layout = layout.Floating(border_focus='#0000ff', float_props=float_props, override_default_float_props=True)
```
Plus some documentation which properties can be used.

**Comment by ramnes** [comment]
> Is there a reason why the `class Floating` has different parameters `float_rules` and `auto_float_types`? This is somehow confusing. Even more if we add additional floating properties like the maximum size.

I guess `float_rules` just came after `auto_float_types`.

What do you think of deprecating `auto_float_types` and extending `float_rules` to support `wmtype` and `wmhint` rather than adding a third way?

Relevant xkcd:

![standards.png](https://imgs.xkcd.com/comics/standards.png)

**Comment by pmkap** [comment]
This could work. However, `float_rules` is a list of dicts, e.g. `[{'wmclass': 'confirm'}, {'wmclass': 'dialog'}, {'wmclass': 'download'}]`
So by itself it's not really extensible.
One would have to do a case differentiation if it's a list (old API) or a dictionary (new API)

**Comment by ramnes** [comment]
Why would you prefer a list of dict rather than a dict of list? It's just the same but the other way around, isn't it?

**Comment by pmkap** [comment]
Currently is is a list of dicts which is kind of awkward because one needs to repeat the keys over and over. I would prefer a dict like in my example above. It's the most clean and also extensible.

**Comment by ramnes** [comment]
But does it prevent you from doing anything that you would be able to do with a dict of lists? We'd rather not break configs if we can avoid doing so.

**Comment by pmkap** [comment]
Ah now I see what you mean. Right, you can do the same with a list of dicts, it's just not very pretty and not intuitive to write. But I see your point.

**Comment by Brn9hrd7** [comment]
I've put the snippet from https://github.com/qtile/qtile/issues/1518#issuecomment-618171311 in my config, and now firefox gets set to floating automatically. According to xprop, the maximum size set by firefox is 32766 by 32766, which is way bigger than my display. So I think it should only be set to floating if the maximum size hint isn't bigger than the actual screen size of the user.

**Comment by ramnes** [comment]
> I'm kinda worried it could have undesirable side effects, i.e. put in floating applications that do not handle their hints correctly but aren't meant to float.

Worries confirmed :)

> I'm kinda worried it could have undesirable side effects, i.e. put in floating applications that do not handle their hints correctly but aren't meant to float.

Sounds like a reasonable counter-hack hack.

**Comment by pmkap** [comment]
Ok, for now I just use this.
```python
@hook.subscribe.client_new
def floating_size_hints(window):
    hints = window.window.get_wm_normal_hints()
    if hints and 0 < hints['max_width'] < 1000:
        window.floating = True
```
I consider this when I try to integrate this feature in the `floating.py` layout.

**Comment by pmkap** [comment]
I think the floating defaults of i3 are very sensible, so I grepped myself through i3 to find the corresponding code.
https://github.com/i3/i3/blob/next/src/manage.c#L449
I suggest we use the same defaults, but easily to extend or replace via `config.py`.

**Comment by ramnes** [comment]
Indeed, let's do the same thing, it looks fine!

**Comment by m-col** [comment]
Did #1710 fix this?

**Comment by Brn9hrd7** [comment]
Just tried it out, and it indeed fixed the issue. Thanks.
