### ISSUE TITLE
math domain error in net widget

### ISSUE THREAD

**Issue by stehessel** [qtile/qtile#1519]
The recent changes to the net widget (commit a8aeacd7102cbd9a1e8b42a7db158e37d893b1ea) introduce a log function into the the conversion function
```
power = int(log(num_bytes) / log(factor))
```
This leads to a math domain error exception if no bytes are transmitted, i.e. when `num_bytes = 0`. I suggest to add a check to treat this case separately.

I also wonder if it is worth it to include `b` and `B` as units, because this causes the widget to shift even with a monospace font (all other units are two characters, i.e. `kb`)

**Comment by flacjacket** [comment]
Thanks for noting this, pushed a fix for this, let us know if you are still having any problems!
