### ISSUE TITLE
[REQUEST] StatusNotifierItem/AppIndicator/Ayatana support

### ISSUE THREAD

**Issue by judemille** [qtile/qtile#1523]
The XEmbed system tray protocol is quite outdated and buggy. Whether we like it or not, StatusNotifierItem is what most DEs and applications are adopting to replace it. An implementation in Haskell can be found at [taffybar/gtk-sni-tray](https://github.com/taffybar/gtk-sni-tray). I can read Haskell and have some free time, so I am willing to work on implementation. To avoid adding extreme amounts of extra effort, the menus can be rendered with libdbusmenu-gtk3.

E: another implementation can be found at https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by juliandemille** [comment]
To encourage the use of SNI in other Python programs, it may be a good idea to separate the core components of this implementation into a different library.

**Comment by ramnes** [comment]
Hey @juliandemille, that's interesting, thank you for raising this! A dedicated library would be great indeed. Feel free to work on this and open a PR if you're willing to!

**Comment by m-col** [comment]
@elParaguayo and I have been discussing this lately and have slowly put some code together (mostly him) that make an SNI widget. Didn't realise there was already an issue here about it! As the XEmbed systray is inherently X-specific, running Qtile with Wayland currently lacks a system tray so this would become its replacement.

One thing we were worried about - in terms of it potentially growing too large and complex to include within libqtile - was the menus, so @elParaguayo we should definitely take a look at libdbusmenu-gtk3 for that.

@judemille did you make any progress with this yourself?

**Comment by elParaguayo** [comment]
To add to this, I've got code working that creates a watcher and draws icons for registered items. I need to port that into a widget next.

**Comment by judemille** [comment]
Ah shit, it's been forever since I actually used qtile lol, so no, no 
progress.

**Comment by elParaguayo** [comment]
Little sneak preview...

![20210624_213254](https://user-images.githubusercontent.com/946265/123328879-0abb6100-d534-11eb-941a-e5ac3fab8543.png)

**Comment by elParaguayo** [comment]
https://user-images.githubusercontent.com/946265/123484549-70751f00-d600-11eb-9afa-43008c0ae758.mp4

**Comment by m-col** [comment]
Please do!
