### ISSUE TITLE
MPRIS2 widget infinitely adds "Paused: " to song name when paused

### ISSUE THREAD

**Issue by judemille** [qtile/qtile#1525]
![Peek 2020-01-22 21-51](https://user-images.githubusercontent.com/8127111/72952987-9ccca200-3d61-11ea-8174-f465a55d69c7.gif)
As shown in the image, "Paused: " gets added to the front of the song title four times, staying there a few seconds, before the song disappears entirely.

**Comment by whatacold** [comment]
Can you reproduce the problem? Maybe I could help fix it, although I haven't used this widget yet.

**Comment by tych0** [comment]
@juliandemille any chance you can test the PR above?

**Comment by juliandemille** [comment]
Sorry, I don't use qtile anymore.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ramnes** [comment]
Fixed in 2caeb6d8540813dc60a9d8e36ca62ac77eadcae8. Thanks @judemille for raising the issue!
