### ISSUE TITLE
Run qtile in conda environment

### ISSUE THREAD

**Issue by shadowrylander** [qtile/qtile#1531]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I was wondering if, just as it's possible to run `qtile` in a `venv`, if it's also possible to run it in a `conda` environment? If so, would the same steps apply to install it? <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the assistance!

**Comment by ramnes** [comment]
Definitely possible in a virtual environment. Not sure about Conda as I do not use it but I don't see any reason it would not work.

**Comment by shadowrylander** [comment]
I thought it might; however, there are `venv` specific files and directories in the `glue` file that I don't know the `conda` equivalents of. I could do a quick search for them, but I'm not entirely sure what to search for.

**Comment by ramnes** [comment]
What is the `glue` file?

**Comment by shadowrylander** [comment]
Step three at the bottom: http://docs.qtile.org/en/latest/manual/install/index.html

It says to create a `glue shell`, but the file it's referencing is specific to `venv`, i.e. `activate`. I'm not sure there's an equivalent in `conda`.

**Comment by pawamoy** [comment]
Then instead of using the `activate` file, use the `conda activate` command?

**Comment by shadowrylander** [comment]
@pawamoy Would it work from the `gdm` login menu?

**Comment by pawamoy** [comment]
I have no idea, but I would say yes, if you manage to untie the wrapper script from a particular user (i.e. not relying on a user's PATH or any other environment variable)?

```bash
#!/bin/bash
eval "$(/path/to/conda shell.bash hook)"
/path/to/conda activate qtile-venv  # qtile-venv must have been created the same way
qtile "$@"
```

Could you try that and report back? 🙂

**Comment by shadowrylander** [comment]
I would, but I've switched to using the arch package; when I switch to another distro base, I'll get back to this! Thank you kindly for the help, though!

**Comment by ramnes** [comment]
I'll go ahead and close this. Feel free to add a message or open a new issue if needed!

**Comment by shadowrylander** [comment]
@ramnes Right! Thanks for the help!

**Comment by wdroz** [comment]
Hello, I tried the approach suggested by @pawamoy and this is working fine.

my qtile file in PATH
```bash
#!/bin/bash
/path/to/conda run -n qtile-env qtile $@
```

The wrapper from @pawamoy should work better if you don't want your users to alter `/path/to/conda`. This is just `conda run` current limitation as explained [here](https://github.com/conda/conda/issues/10690)

For QoL improvement, I suggest to deactivate **qtile-env** at the end of your `.bashrc`
```bash
if [ "$CONDA_DEFAULT_ENV" == "qtile-env" ]; then
    conda deactivate
fi
```
