### ISSUE TITLE
widget.CPU() does not exist 

### ISSUE THREAD

**Issue by terrencetec** [qtile/qtile#1534]
Hello, I am using Ubuntu 18.04 and have recently installed Qtile via `sudo apt install qtile`. I tried using widget.CPU() in the config file but it just ended up using the default config. This probably means that the config returned an error. After a few tests, I decided to look into the python library folder and discovered that cpu.py doesn't exist in /libqtile/widget/ and is not imported via \_\_init__.py. I don't know if it is only an issue for me or not. I know this is not good practice but I ended up copying the cpu widget code somewhere from the web and added a line in \_\_init__.py to enable it. 

P.S. I apologize if I made any mistakes filing an issue. I am new to github and Qtile. Great work BTW.

**Comment by pawamoy** [comment]
I think the CPU widget has not been released yet.

**Comment by whatacold** [comment]
> I think the CPU widget has not been released yet.

I agree, as the CPU widget is quite new, it was merged on Dec 23, 2019, in PR #1481 .

**Comment by terrencetec** [comment]
Oh, I didn't know. Thanks!

**Comment by ramnes** [comment]
As @pawamoy and @whatacold said (thanks to both of you), it's not released yet. Either wait for next release or install Qtile from sources!

**Comment by nonetrix** [comment]
This is still an issue, it has been 2 years any update? Sorry for bothering

**Comment by elParaguayo** [comment]
You must have a different issue as the widget is available in 0.21.

Start a new issue and post your error messages and config file.
