### ISSUE TITLE
Default Config error

### ISSUE THREAD

**Issue by Ayush1325** [qtile/qtile#1536]
I am using qtile with Arch linux. The problem is that qtile is not reading my default config. So every time I make an error in my actual config, there is no way to fix it without restarting. I know for a fact that my default config is located at
` /usr/share/doc/qtile/default_config.py` 
I think qtile is supposed to fall back to default config in case of an error but it just doesn't seem to happen in my case. So is there a solution? or at least a way to specify the location of a fallback config? I am using the [qtile](https://www.archlinux.org/packages/community/any/qtile/) package in arch repos.

**Comment by pawamoy** [comment]
Some related issues: https://github.com/qtile/qtile/issues/1445, https://github.com/qtile/qtile/issues/1411, https://github.com/qtile/qtile/issues/1386

**Comment by tych0** [comment]
Should be fixed now by #1547, so I'll close this.
