### ISSUE TITLE
Built-in Widget format argument not working

### ISSUE THREAD

**Issue by SammyTheBEAST** [qtile/qtile#1538]

**Comment by whatacold** [comment]
Do you mean the `fmt` argument?

It may help others if you could describe the problem in detail, and more importantly, how you solved it :)

**Comment by SammyTheBEAST** [comment]
> Do you mean the `fmt` argument?
> 
> It may help others if you could describe the problem in detail, and more importantly, how you solved it :)

Right after I posted I realized I put "format" instead of "fmt"...
