### ISSUE TITLE
why not add the python deps to install script

### ISSUE THREAD

**Issue by dulm** [qtile/qtile#1539]
cairocffi, pangocairo, python-gobject and python-dbus are all python packages.
but now we need to install the deps first, then install qtile.

but pip install could install deps automaticly. why not add them to install script ?

so i could  `sudo apt-get install libpangocairo-1.0-0`,  then only type `pipx install qtile`.

now i can't use pipx to install qtile.

**Comment by tych0** [comment]
I've not used pipx before. Can you send a patch?

**Comment by dulm** [comment]
it's just like pip, but create venv.

**Comment by tych0** [comment]
If it's just like pip, won't the same requirements.txt file works? That has all of the requirements. (Note that pangocairo is not needed, and gobject and dbus are optional.)
