### ISSUE TITLE
Copy from qt5 app fails with "QXcbClipboard::setMimeData: Cannot set X11 selection owner"

### ISSUE THREAD

**Issue by TauPan** [qtile/qtile#1542]
I'm using keepassxc as a password manager, and on a new (work) laptop I installed a more recent qtile than on an old one without taking much note of it (just checked out qtile from github and setup the virtualenv).

Suddenly I could not copy passwords in keepassxc any more and noticed that it prints the error message if I start it from a terminal.

QXcbClipboard::setMimeData: Cannot set X11 selection owner

Googling for the error message gives several ancient qt bugs.

(I found an issue that was found to be caused by a window manager, but I can't find it any more at the moment. I think I saved it in a note on the new work laptop.)

Then I reverted to the commit I was using on the old laptop, after having eliminated all other causes I could think of, and the behaviour was fixed.

I have now bisected this on a completely different laptop (the newer and older work laptops I first tried this with are running openSUSE 15.1, the private laptop runs Ubuntu 18.04) and the first bad commit is 28d5c30005b5342db9ea400e638daad15d110bfe, the fix for #755.

If I go back to the commit before it, I can copy passwords in keepassxc.

I can also replicate the problem in qt5ct (go to a number field in the second tab and try to copy it with ctrl-c, same error printed in the shell, nothing is copied).

I suspect it's reproducible with other qt(5?) apps. I generally don't take note which toolkit an application is using, so I'm not aware of any other qt apps I might use.

The behaviour in #755 is annoying too. I see that this was a very hard one to figure out and fix. I wasn't aware that it was specific to emacs and I never have an empty desktop that often. Copy + paste from keepassxc however is more important to me. (So I'm obviously  using 0617235c3e5748de83b2d8d630f766e3cd5682a4 until this issue is closed.)

**Comment by whatacold** [comment]
Sorry that it introduces another issue :(,  I also noticed that Zeal has this issue the other day, and the exact error message,  I wasn't aware that it was introduced by that commit though.

So some investigation should be conducted to see what goes wrong, unfortunately.

**Comment by bernatnan** [comment]
I use other qt5 applications and all they fails the copy action. But if I downgrade the qtile to the revision that TauPan coment, they work fine.

If you need any tests, I will be pleased to help.

**Comment by whatacold** [comment]
@bernatnan Thanks, but it seems this can be reproduced steadily, at least with Zeal on my side.

**Comment by whatacold** [comment]
Don't know why the qt app (I tried Zeal and konsole) can't work when being used with `xtrace`.

Here are something that I found:
1. Qt seems to set and check the selection owner: https://code.woboq.org/qt5/qtbase/src/plugins/platforms/xcb/qxcbclipboard.cpp.html#370
2. Docs about selections: https://tronche.com/gui/x/icccm/sec-2.html

**Comment by whatacold** [comment]
Ah, I see!

I was wondering what if the TIMESTAMP set to `WM_TAKE_FOCUS` is too big? As it says in the spec that
>  The client should set the specified selection to the atom that represents the selection, set the specified owner to some window that the client created, and set the specified time to some time *between the current last-change time of the selection concerned and the current server time.*

It could fail if qt5 apps set a wrong TIMESTAMP, somehow.

But I failed to find the exact value range for TIMESTAMP in the spec, so I tried it with `x11trace emacs -Q`, and found that emacs sets a way smaller value than `time.time()` in the Python code (`54846926` vs. `1582992026` in decimal):

    002:<:100e: 16: Request(22): SetSelectionOwner owner=0x05200147 selection=0x1("PRIMARY") time=0x0344e5e6
    002:<:100f:  4: Request(43): GetInputFocus 

Then I did a quick verification to just hard-code the timestamp to `54846920`, and Zeal this time, as expected, text can be copied and pasted to another app perfectly.

I will continue to find out how to fix it properly, Cheer!

**Comment by karolyi** [comment]
@ProgrammingLife, not sure what you meant by this.

On my Manjaro, it's exactly keepassxc that doesn't survive a laptop suspend with the following message:

```
qt.qpa.clipboard: QXcbClipboard::setMimeData: Cannot set X11 selection owner
sh: Job 1, 'keepassxc' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by AGI-chandler** [comment]
So should this be reopened as a regression? ...because I also get the error from _KeePassXC_, which makes it impossible to authenticate to anything.  Not sure how to see which version of _qtile_ is being used, but it's gotta be pretty recent: The OS is Debian stable (12 bookworm) and _libqt5gui5_, for example, is 5.15.8+dfsg-11+deb12u2.
