### ISSUE TITLE
Question: How to go back in the window layout history like emacs winner-mode

### ISSUE THREAD

**Issue by QiangF** [qtile/qtile#1544]
In emacs, winner-undo and winner-redo can brings back the recent window configurations, can we do it with qtile?

**Comment by tych0** [comment]
On Tue, Mar 03, 2020 at 02:57:08AM -0800, QiangF wrote:
> In emacs, winner-undo and winner-redo can brings back the recent window configurations, can we do it with qtile?

There's group.prev_window() and layout.previous() which will bring
back the most recent window configurations, but there's not a history
list.
