### ISSUE TITLE
No such key: +

### ISSUE THREAD

**Issue by liborw** [qtile/qtile#1553]
I have czech keyboard layout and I would like to be able to switch groups using [mod]  + one of `+ěščřžýáí` as that is what I have instead of `1233456789`, however when I try to use them in config I got `No such key: +` error.

**Comment by tych0** [comment]
Can you start xev and paste all the keysyms you get? I think we just need to add them to keysyms.py.

**Comment by zordsdavini** [comment]
I think better idea was to use keycode instead keysymbol. This issue can be merged into https://github.com/qtile/qtile/issues/933

**Comment by tych0** [comment]
Yep, agreed. I'll go ahead and close this for now.
