### ISSUE TITLE
Troubles importing `lazy`

### ISSUE THREAD

**Issue by Sawrz** [qtile/qtile#1555]
Hi,
I get a strange error while installing qtile-0.14.2-3 with pacman:
The lazy.py file misses in the site-package libqtile. Therefore I can't import it. [Here](https://i.imgur.com/hDLXzdM.png) you'll find a screenshot from PyCharm.

Thank you in advance,
Sandro

-----

**Maintainers edit: The solution is to import `lazy` from `libqtile.command` if you're using Qtile 0.14.2 or older, or from `libqtile.lazy` if you're using a more recent version (e.g. 0.15.0 or HEAD). Sorry for the mess.**

**Comment by tych0** [comment]
In the future, it's better to post the code in text format, instead of screenshot format. In any case, it looks like you need to import lazy via:
```
from libqtile.command import lazy
```
not
```
from libqtile.lazy import lazy
```

**Comment by Sawrz** [comment]
I agree if the purpose of the screenshot is to illustrate the code. But the main point is to show the files within the library, where lazy.py is missing - it's not missing in the master branch of libqtile.
There was no indicator the code is buggy since it's a copy of the default_config.py in the master branch of this repository, which is linked in the docs for the latest version.

Does it seem lazy.py is deprecated now? If that's true, default_config.py or the link in the official docs should be updated accordingly.

Here you'll find the references I mention:
- [Docs](http://docs.qtile.org/en/latest/manual/config/index.html#default-configuration)
- [config.py](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py)

Otherwise, it leads to confusion. In case my references are wrong, please inform me about that so that it may prevent future issues with such simple solutions. =)

However, thanks for the info! I replace the import and start messing with qtile! =D

**Comment by pawamoy** [comment]
I'm the one to blame haha: https://github.com/qtile/qtile/commit/8789c67730001c04e138dfad67cfe357bbe5541c#diff-ce9efb2308a35839024a670719bcaada

I think the documentation should link to the version of the file in the repo matching the docs version: https://github.com/qtile/qtile/blob/0d6819181632df8ba13d8468530ad9c628142dcc/libqtile/resources/default_config.py.

**Comment by ramnes** [comment]
The problem here is the opposite one. @Sawrz seems to use the newer version of the config file with an older version of Qtile...

**Comment by ramnes** [comment]
Reopening as it's like the 10th issue on the subject and I'd like that we find a way to not have that kind of issue anymore, or at least shed some light on this.

**Comment by Sawrz** [comment]
> The problem here is the opposite one. @Sawrz seems to use the newer version of the config file with an older version of Qtile...

Can you elaborate on this? I use version 0.14.2 (`qtile --version`) of qtile and copied the config version from the docs corresponding to 0.14.2 (or latest). Maybe I'm missing something here =)

@tych0 solution did the trick. So my question would be, what's the newer config then? In the docs, the config imports as follows:
`from libqtile.lazy import lazy`

So I think @pawamoy has a point here. The doc version should link to the config file he mentioned. At least for my case.

I'm quite new to qtile, and after a bit of testing several WM I decided to mess more seriously with qtile. So I don't exclude user stupidity on my side =)

**Comment by ramnes** [comment]
Yeah sorry, by "older version of Qtile", I meant the latest released version rather than HEAD. :sweat_smile: 

> So I think @pawamoy has a point here. The doc version should link to the config file he mentioned. At least for my case.

But... it's already the case, isn't it? I see `from libqtile.command import lazy` on qtile.org homepage.

**Comment by Sawrz** [comment]
Ah ok. I was just wondering if you keep master as the only version and don't do any releases anymore. So wanted to be sure to get the recommended version =)



> But... it's already the case, isn't it? I see `from libqtile.command import lazy` on qtile.org homepage.

Well, yes and no. You're entirely right on the homepage. But on docs.qtile.org, [here](http://docs.qtile.org/en/latest/manual/config/index.html), you link to the newer import rather than stick to the old one. So the link goes to [this](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py) config.

That's what confused me in the first place. Since I didn't look much on the homepage banner and preferred to go straight to the documentation. So I think a quick fix in the doc link should fix the whole issue =)

**Comment by ramnes** [comment]
I think we should make a new release that will ship with #1489 (which automatically copies the default `config.py` if it doesn't exist yet), and then simply remove these links.

**Comment by Sawrz** [comment]
It sounds like a solution to me! How about the qtile folks with older versions? Does it simply break for them?
The error messages while in the tile manager are quite generic, so how do they know the import statement broke their old configuration?

Again, just out of curiosity =)

**Comment by Sawrz** [comment]
You are entirely right! I had my problem in mind, which is the other way around and doesn't have to do with deprecation. So I never asked =)

 When does the new version appear then? Do you have a schedule in mind?

**Comment by ramnes** [comment]
Paging @flacjacket @tych0

**Comment by tych0** [comment]
Before we can do a release, we need to go through and list all of the changes (like this one) that broke things in the config. We should try and do that in the actual changesets if possible in the future.

**Comment by tych0** [comment]
Now wait a minute. It should just print a deprecated warning, but still work, right?

**Comment by Sawrz** [comment]
> Well if they're running an old version of Qtile, it means that they should already have a working configuration running, I guess. slightly_smiling_face
> 
> And if they upgrade, nothing will break, as `libqtile.command.lazy` still exists, and emits a deprecation warning. Plus, we'll document everything in the changelog.

That was @ramnes reply about breaking things.



> Before we can do a release, we need to go through and list all of the changes (like this one) that broke things in the config. We should try and do that in the actual changesets if possible in the future.

[python-semantic-release](https://github.com/relekang/python-semantic-release), combined with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) and travis can help automate changelogs, releases and version bumps. So, you don't have to keep track about everything manually.

**Comment by tych0** [comment]
We already have the changelog file, and we can't even keep that up to date :)

**Comment by Sawrz** [comment]
Ok, just to be sure we talk about the same thing:
Did you mean to write a changelog for the future relase,, right? Something like breaking changes, new features, etc. which shows up on the release page. Did I get your point right here?

**Comment by tych0** [comment]
Yeah, new features, breaking changes with suggestions on how to fix people's configs, deprecation, etc.

**Comment by Sawrz** [comment]
Well, python-semantic-release can help you there as long as you stick to conventional commits. You added a feature and a breaking change before pushing like:
feat: Cool new feature
BREAK: import of lazy changed

Semantic release checks for such comments bump up the version (you can configure that part), creates a release with that changelog, like [here](https://i.imgur.com/gp6rOAd.png). You can still edit the changelog to your liking, but it keeps more or less track of the changes in the new version.

The workflow is a bit different, but I find it incredibly useful and time-saving. =)

**Comment by tych0** [comment]
Yeah, I guess my point is just that we have an existing workflow that has been established for many years, and often people don't stick to that. I'm not sure changing it will help us.

**Comment by Sawrz** [comment]
Yeah, you probably right. However, maybe it's something worth to know that something like this exists =)

**Comment by nicoeinsidler** [comment]
I just had the same issue when installing qtile (latest there is 14.2) via `dnf` on Fedora 32. Grabbing the default config of the docs for version 15.X or 14.2 does not work.

However upgrading qtile via `pip` does work. Using the default config again, now I cannot import `guess_terminal()`. Trying to locate it in the `libqtile` directory with

```bash
grep -rnw . -e 'guess_terminal'
```

does not find the missing function.

**Comment by ramnes** [comment]
It's because guess_terminal hasn't been released yet. Simply do not put a default config manually: since 0.15.0, qtile will create one by itself based  on the currently installed version.

**Comment by nicoeinsidler** [comment]
Ah okay, deleting `~/.config/qtile/config.py` and restarting qtile twice so that it can add a config file, solved my problems. The version of qtile that installs with `dnf` should be updated still. :)
