### ISSUE TITLE
Venv install effects on shell environment

### ISSUE THREAD

**Issue by chillax9000** [qtile/qtile#1556]
Hey

I've been using qtile for a few days, I quite like it! It is running in a Python3.7 venv on Debian 10, and has been installed following the 'Fedora example' given in the doc (http://docs.qtile.org/en/latest/manual/install/index.html#installing-from-source), with no real issue.

However when opening a terminal (with `lazy.spawn(...)`), the shell environment looks partly modified by the Qtile venv:
`$PATH = <qtitle_repo_path>/venv/bin : [...]`
`$VIRTUAL_ENV = <qtile_repo_path>/venv`
I'm guessing that the Python process running Qtile passes by default the shell environment for children, thought I'm not sure why then `$PS1` is not the venv one.

I ended up adding a optional kwarg `env` to `core.manager.Qtile.cmd_spawn` used with `os.execvpe`, to allow the use of a 'cleaned' env.

It seems to be working so far, but I'm wondering if I haven't missed anything, like a more natural way to deal with this, or if my install is faulty. Also I didn't try any packaging-like solution, like using zipapp.

**Comment by tych0** [comment]
I don't think there really is a nice way of dealing with this; is this causing you issues, with running venvs in child shells I guess? I suppose we should clean some of the things (maybe VIRTUAL_ENV), but it does seem reasonable to want to pass through most of the environment.

**Comment by chillax9000** [comment]
No problem when running venvs so far.
Actually I came across the matter only once, when compiling vim with python3 support. The changes in the env were messing with the configuration for as where to find `Python.h`, even with many flags explicitely set.
But then, passing a cleaned env (by that I mean removing `<qtitle_repo_path>/venv/bin` from `PATH` and unsetting `VIRTUAL_ENV`) was enough for the build to succeed painlessly.

**Comment by tych0** [comment]
Yeah, I can see where having VIRTUAL_ENV set at least would cause a problem. I'll go ahead and send a patch to unset that.
