### ISSUE TITLE
mpd2 widget errors

### ISSUE THREAD

**Issue by ghost** [qtile/qtile#1558]
When the 'elapsed' status is present, the widget returns an error if the music is stopped.
`2020-03-20 03:51:23,135 libqtile mpd2widget.py:formatter():L176  mpd client did not return status: elapsed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/widget/mpd2widget.py", line 173, in formatter
    formatted = fmt.format(play_status=play_status, **status)
KeyError: 'elapsed'`

also, if there is no tagged artist or title it returns an error.
I tried to fix this issue by editting the widget with an if statement that would show an alternative 'status_format' that had those values set to a string that just said 'unknown' if it was going to return an error but I'm really not familiar enough with python.

**Comment by MagusLucius** [comment]
Try the current version of mpd2widget.py.

[mpd2widget](https://github.com/qtile/qtile/blob/master/libqtile/widget/mpd2widget.py)

**Comment by m-col** [comment]
Is this still an issue? There is at least one other bug with the Mpd2 widget that I might try to tackle when I have some time.
