### ISSUE TITLE
Group - matches is not list no exception

### ISSUE THREAD

**Issue by Sawrz** [qtile/qtile#1562]
Hi,
If I pass a single Match object to the matches parameter of a group object, qtile simply crashes and redirects to the login manager. 

That behavior leads to confusion since the user doesn't get proper feedback. So I would suggest two options:

1. Add Exception:
```
if matches is not None or type(matches) is not list:
      raise Exception("I don't know if you have custom Exception class")
```
2. Catch and Convert:
```
if matches is None:
      self.matches = []
    elif type(matches) is Match:
      self.matches = [matches]
    else:
      self.matches = matches
```

Although the latter option is not as slick as `self.matches = matches or []`, it improves usability and prevents user error and frustration. So I prefer option 2.

However, I think qtile needs at least option 1. 

Best,
Sandro

**Comment by tych0** [comment]
If we raise an exception, the behavior will be the same: a crash going back to the login manager.

I wonder if we can export type information so that users can run pytype on their configs and get this kind of feedback? That seems maybe the best.

**Comment by Sawrz** [comment]
> If we raise an exception, the behavior will be the same: a crash going back to the login manager.

Ok, I thought it would fallback to default configuration then. That would still be better than just going back to the login manager. 


> I wonder if we can export type information so that users can run pytype on their configs and get this kind of feedback? That seems maybe the best.
I never heard of pytype, but if I understood the README right, it just checks for the right type based on type annotations. It would be an option for feedback. 
As far I understand, which is guessing, qtile works by importing the config.py and use these variables. Therefore, one needs to run pytype on that run script, right?

What would be the reasons to cast simply to a list? Having such conditional statements doesn't look nice but would do the job as well =)

**Comment by tych0** [comment]
It doesn't look nice, and it only fixes one instance of a failure. What if someone passes a bar.Bar() in? What if someone passes in an object()? We can't account for every case, so type checking seems much better.

Yes, you'd have to run pytype on your config, but that doesn't seem like a huge burden.

**Comment by Sawrz** [comment]
> It doesn't look nice, and it only fixes one instance of a failure. What if someone passes a bar.Bar() in? What if someone passes in an object()? We can't account for every case, so type checking seems much better.

True! My suggestion aimed more on usability since most configs I saw use only one Match.



> Yes, you'd have to run pytype on your config, but that doesn't seem like a huge burden.

No, as long as it would be only the config and not some run script, nobody ever touches! That was the question. But if it's only that way it would be great! That would decrease the amount of qtile kills I have to do because of type errors.
