### ISSUE TITLE
widget.Spacer fails with background

### ISSUE THREAD

**Issue by Sawrz** [qtile/qtile#1564]
Hi,
According to [the docs](http://docs.qtile.org/en/latest/manual/ref/widgets.html#spacer), the spacer object accepts the background key. Either as an argument or in the defaults. However, the bar stays black (#000000) using the `widget_defaults` dictionary. When I use `background` as an argument, qtile crashes.

Is the doc ahead again, like in issue [#1555](https://github.com/qtile/qtile/issues/1555)?

**Comment by tych0** [comment]
Yeah, looks like that code came from 417ce07, which was after our last release.
