### ISSUE TITLE
Window following active group

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#1565]
Is there a way to make a window follow the active group?

Let's say i open a window and "shortcut" makes that type of window from now on follows the current group, and if you change group the window just fits into the current layout and integrates as a new window in the group.

Don't know if this is possible?

**Comment by tych0** [comment]
It should be possible using the focus_change() hook. You'll have to
find your window ID and move it to the right group. You'll probably
also need to capture the qtile object via a `main` function so that
you can munge things when the focus changes.

**Comment by gibranlp** [comment]
Awesome will look into this, thanks man
