### ISSUE TITLE
widget.CPU doesen't work

### ISSUE THREAD

**Issue by Godnyx** [qtile/qtile#1567]
I don't know if I'm doing something wrong but "widget.CPU" dosen't work for me. "widget.CPUGraph" works tho. My config is based on ArcoLinux Qtile [config](https://github.com/arcolinux/arcolinux-qtile/blob/master/etc/skel/.config/qtile/config.py) so you can give a quick look in the imports in case it misses something. If not, I will upload mine!

**Comment by tych0** [comment]
On Fri, Mar 27, 2020 at 03:32:59AM -0700, Godnyx wrote:
> I don't know if I'm doing something wrong but "widget.CPU" dosen't work for me. "widget.CPUGraph" works tho. My config is based on ArcoLinux Qtile [config](https://github.com/arcolinux/arcolinux-qtile/blob/master/etc/skel/.config/qtile/config.py) so you can give a quick look in the imports in case it misses something. If not, I will upload mine!

What does "doesn't work" mean? Is there an error message in the logs?
Does it not update? Does it not show up?

**Comment by Godnyx** [comment]
It generates "config error". I think I'm setting up the widget but still my config breaks. Tho running "python -m py_compile ~/.config/qtile/config.py" it doesn't says that a made any mistake in my config. But still my config breaks.

**Comment by Godnyx** [comment]
It generates "config error". I think I'm setting up the widget but still my config breaks. Tho running "python -m py_compile ~/.config/qtile/config.py" it doesn't says that a made any mistake in my config. But still my config breaks. [here](https://gist.github.com/Godnyx/f943b93af25b5de9ffd59159dae56752) is my config.

**Comment by tych0** [comment]
Can you pleas post the full stack trace?

**Comment by Godnyx** [comment]
Sorry for the late answer! I completely forgot this! What is this and where is it located?

**Comment by tych0** [comment]
Look in ~/.xsession-errors

**Comment by Godnyx** [comment]
I don't know if you want this but this is what's inside of .xssession-errors:

```
(nitrogen:423592): Gtk-WARNING **: 20:56:30.217: Unable to locate theme engine in module_path: "adwaita",
 
(nitrogen:423592): Gtk-WARNING **: 20:56:30.221: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.221: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.223: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.223: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.223: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.268: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.270: Unable to locate theme engine in module_path: "murrine",

(nitrogen:423592): Gtk-WARNING **: 20:56:30.270: Unable to locate theme engine in module_path: "murrine",
 
(nitrogen:423592): Gtk-WARNING **: 20:56:30.271: Unable to locate theme engine in module_path: "murrine",
 
(nitrogen:423592): Gtk-WARNING **: 20:56:30.271: Unable to locate theme engine in module_path: "murrine",
 
(nitrogen:423592): Gtk-WARNING **: 20:56:30.271: Unable to locate theme engine in module_path: "murrine",
```

**Comment by am01k01h3** [comment]
I am also facing this issue. For me other widgets work memory, memorygraph, network, networkgraph etc. But qtile complains it doesn't recognize/find widget.CPU. I'll try to post error logs soon.

**Comment by am01k01h3** [comment]
[qtile.log](https://github.com/qtile/qtile/files/4453698/qtile.log)

File "/home/amol/.config/qtile/config.py", line 468, in init_widgets_list widget.CPU(
AttributeError: module 'libqtile.widget' has no attribute 'CPU'
[config.py.txt](https://github.com/qtile/qtile/files/4453707/config.py.txt)


Exact same issue with CPUGraph also. Rest of the widgets work fine.

**Comment by tych0** [comment]
I think you guys must be using 0.14.2, and these widgets were released after that.

**Comment by am01k01h3** [comment]
Thats it :) I literally just now figured it out too, as I saw the documentation on docs.qtile.org specific to the version I have :+1: 

Is there any guidance on how to build from latest source? I have git clones the repo to my local.

**Comment by tych0** [comment]
On Thu, Apr 09, 2020 at 07:00:38AM -0700, Amol Kolhe wrote:
> Thats it :) I literally just now figured it out too, as I saw the documentation on docs.qtile.org specific to the version I have :+1: 
> 
> Is there any guidance on how to build from latest source? I have git clones the repo to my local. 

http://docs.qtile.org/en/latest/manual/install/index.html#installing-from-source

**Comment by am01k01h3** [comment]
Thank you!!

**Comment by Godnyx** [comment]
ok! Makes sense! But what's the latest Qtile binary version? Arch repos saying "14.2-3". And if Arch have this version probably there are no latest build binaries...
