### ISSUE TITLE
simple_key_binder doesn't work properly (?)

### ISSUE THREAD

**Issue by parsrch** [qtile/qtile#1568]
the example config in docs for it doesn't do anything should I do something extra to use it?

**Comment by tych0** [comment]
On Sat, Mar 28, 2020 at 05:57:00AM -0700, parsrch wrote:
> the example config in docs for it doesn't do anything should I do something extra to use it?

I'm not aware of any bugs with it right now. A more complete
description of the failure would be useful though.

**Comment by parsrch** [comment]
> On Sat, Mar 28, 2020 at 05:57:00AM -0700, parsrch wrote: the example config in docs for it doesn't do anything should I do something extra to use it?
> I'm not aware of any bugs with it right now. A more complete description of the failure would be useful though.

i dont think that its a bug.I think it's just lack of description in docs.
BTW what should I do to make it work?

**Comment by parsrch** [comment]
whoops,It was just me being stupid.sorry
