### ISSUE TITLE
widget.Pacman needs a non existing file:'checkupdates'

### ISSUE THREAD

**Issue by parsrch** [qtile/qtile#1574]
```
2020-03-30 07:09:12,582 ERROR libqtile base.py:worker():L478 problem polling to update widget pacman
Traceback (most recent call last):
  File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 474, in worker
    text = self.poll()
  File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/pacman.py", line 49, in poll
    pacman = self.call_process(['checkupdates'])
  File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 266, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'checkupdates'
```

**Comment by tych0** [comment]
On Sun, Mar 29, 2020 at 07:42:13PM -0700, parsrch wrote:
> `2020-03-30 07:09:12,582 ERROR libqtile base.py:worker():L478 problem polling to update widget pacman
> Traceback (most recent call last):
>   File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 474, in worker
>     text = self.poll()
>   File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/pacman.py", line 49, in poll
>     pacman = self.call_process(['checkupdates'])
>   File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 266, in call_process
>     output = subprocess.check_output(command, **kwargs)
>   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.8/subprocess.py", line 489, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'checkupdates'`

This doesn't seem like a bug; if you're not on Arch, you won't have
this, so there's no reason to use Arch's package management widget.

**Comment by parsrch** [comment]
> On Sun, Mar 29, 2020 at 07:42:13PM -0700, parsrch wrote: `2020-03-30 07:09:12,582 ERROR libqtile base.py:worker():L478 problem polling to update widget pacman Traceback (most recent call last): File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 474, in worker text = self.poll() File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/pacman.py", line 49, in poll pacman = self.call_process(['checkupdates']) File "/home/parsrch/.local/lib/python3.8/site-packages/libqtile/widget/base.py", line 266, in call_process output = subprocess.check_output(command, **kwargs) File "/usr/lib/python3.8/subprocess.py", line 411, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "/usr/lib/python3.8/subprocess.py", line 489, in run with Popen(*popenargs, **kwargs) as process: File "/usr/lib/python3.8/subprocess.py", line 854, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'checkupdates'`
> This doesn't seem like a bug; if you're not on Arch, you won't have this, so there's no reason to use Arch's package management widget.

1-I Use Arch BTW
2-its because the script for Checkupdates is missing even on github

**Comment by m-col** [comment]
It uses `/usr/bin/checkupdates` which is provided by the `pacman-contrib` package. Do you have that installed?

**Comment by ramnes** [comment]
IIRC widget.Pacman is deprecated in favor of widget.CheckUpdates.

**Comment by tcld** [comment]
Should the deprecation be made more clear? I just played around with the widget, but the documentation doesn't mention it at all. I only noticed it when looking at the code.

**Comment by negativeExponent** [comment]
ditto, i used widget.Pacman as well on latest build and desktop can hang-up when its used.

**Comment by ramnes** [comment]
I guess we should just remove it, there is a deprecation warning in the code for quite some time now.
