### ISSUE TITLE
Widgets common to multiple bars are duplicated

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1579]
[I see there is a new (to me) issue template. Does this issue count as a 'general question' even though it relates to a potential improvement rather than "how do I do X?"]

# Issue description

I often use 2 monitors which each have their own `Bar`, but most of their widgets are the same. Common widgets that execute code non-interactively (such as checking how many emails one has) will run twice as often as needed. Additionally, common widgets that poll to update their text often go out of sync and display different text, when they should always be identical.

# Configuration

I think the neatest way for this to be controlled at the config level would be simply to pass the same instance of a widget to your bars. Internally somewhere in the base widget could redraw any updates to their list of bars rather than their single bar.

I'd be happy to work on this if you think it would be worth doing!

**Comment by tych0** [comment]
Seems fine to me, the question is really just how to go about doing it. Right now, all the widgets add their state to "self", but it seems like instead they should all be stateless, and take some kind of state object? Then you can indicate via the state object that two widgets should share the same state.

Worth noting though that some widgets you really do want two copies of. For example, GroupBox(). So we need a way to accomplish both.

**Comment by tych0** [comment]
I suppose another option would be to introduce a new widget type, which just renders a copy of whatever the other widget's text is. That seems simpler to do?

**Comment by m-col** [comment]
The new widget type was definitely the easier idea! Submitted at #1596.
