### ISSUE TITLE
Creation of Iso with lightdm and Qtile - qtile crashes after login into lightdm

### ISSUE THREAD

**Issue by arcolinuxz** [qtile/qtile#1581]
# Issue description

I would like to understand the message qtile shows when I start qtile from terminal.

# Qtile version

Arch Linux : 0.14.2-3
Installed on ArcoLinux

# Stack traces

Please attach any stack traces found in:

* `~/.xsession-errors`
* `~/.local/share/qtile/qtile.log`
None

# Configuration

Selecting qtile from lightdm, qtile tries to start and we end back in lightdm
Investigating possible ways what could cause the crash.
Lightdm works with 14 other desktops. Not with qtile.

Does this image ring a bell?
I took a look at these files. Seems it looks for distribution? Do not understand these lines enough to make an educated guess where to look for a solution.

Can you assist?

![qtile](https://user-images.githubusercontent.com/36679406/78277162-555a5300-7514-11ea-81ad-4624d7de3a85.png)

**Comment by zordsdavini** [comment]
what is you default locale? run `locale` to see it

**Comment by tych0** [comment]
See #1578, but yeah, seems like maybe there's some locale stuff
missing possibly?

**Comment by arcolinuxz** [comment]
![locale](https://user-images.githubusercontent.com/36679406/78282640-e59c9600-751c-11ea-9b33-aea1f3d3e780.png)

**Comment by arcolinuxz** [comment]
I have read this one too.

https://github.com/qtile/qtile/issues/274
In that issue it says an empty LC_ALL is not the problem so I stopped looking in that direction.

**Comment by arcolinuxz** [comment]
In  #1578 I have added code and tested that out

**Comment by zordsdavini** [comment]
does it help? What output you have for `cat /etc/locale.conf`? Have you tried to regenerate locales by `locale-gen`?

**Comment by arcolinuxz** [comment]
the issues is solved in the meantime - if #1578 is merged the issue will be fixed and this can be closed

**Comment by tych0** [comment]
On Thu, Apr 02, 2020 at 12:49:52PM -0700, arcolinuxz wrote:
> the issues is solved in the meantime - if #1578 is merged the issue will be fixed and this can be closed

That's really just a workaround; it's probably worth running
locale-gen or investigating why setting the locale explicitly doesn't
work for you.

**Comment by arcolinuxz** [comment]
We solved the issue.
