### ISSUE TITLE
Some browser windows stop rendering and become unresponsive

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1588]
# Issue description

After a while application windows stop drawing or responding.
I can switch to them, but they are just a frame, the application is not rendering on screen
Only solution is to kill them

Observed this issue with the following applications:

1. Chromium
2. Webmacs (consistently after while of usage)
3. Slack (ocassionaly after swithing around or some window events)
4. Discord (most reliably when switching groups)

# Qtile version

0.14.2

Please include the exact commit hash of the version of Qtile that failed.

# Stack traces

I could'nt find any stacktraces or any indication of errors in the logs

* `~/.xsession-errors`
* `~/.local/share/qtile/qtile.log`

# Configuration

https://gitlab.com/asyncmind/qtile_config.git

**Comment by jagguli** [comment]
I'm at a loss with trying to debug this :(

**Comment by tych0** [comment]
On Mon, Apr 06, 2020 at 03:32:31PM -0700, Steven wrote:
> 
> # Issue description
> 
> After a while browser windows stop drawing or responding.

..which browser? :)

> Only solution is to kill them
> 
> # Qtile version
> 
> 0.14.2
> 
> Please include the exact commit hash of the version of Qtile that failed.

0.14.2 is quite old, can you reproduce on current git master?

**Comment by jagguli** [comment]
so far webmacs and chromium

the latest master causes other issues for me
I'm on Archlinux
I'll try it again

**Comment by jagguli** [comment]
Tried this with latest version, still getting this
Is there any way to debug this ? its very annoying

**Comment by deniss-s** [comment]
I can confirm that on Manjaro and Gentoo with Firefox. With time browser becomes very slow and unresponsive. I'm on version 0.15.1.

**Comment by ramnes** [comment]
Related to #1446 maybe? Can you reproduce with the default config?

**Comment by deniss-s** [comment]
Yes, it's the same issue!
Removed `widget.KeyboardLayout` from my config and Firefox instantly became snappy as it should. Thanks for help!

Will try if https://github.com/qtile/qtile/pull/1682 is going to work for me.

**Comment by ramnes** [comment]
@jagguli Is it the same problem for you also?

**Comment by jagguli** [comment]
I don't use this widget, this issue is really annoying

can reproduce consistently with discord app

**Comment by jagguli** [comment]
I dont get high cpu usage, The windows just dont redraw, its there but does not redraw

**Comment by jagguli** [comment]
I have just updated to tip, seems better now.

Discord is not hanging all the time, certainly seems smoother

**Comment by jagguli** [comment]
Nope still happening, discord window has become invisble and unresponsive

**Comment by zordsdavini** [comment]
@jagguli maybe you use sddm as display manager?

**Comment by deniss-s** [comment]
@zordsdavini I use sddm as display manager, what's wrong with it?

I was suspicious that it might cause some problems, but I have no evidence. Though, wanna try to migrate to LightDM anyway.

**Comment by zordsdavini** [comment]
@deniss-s I didn't believed but give a try

**Comment by jagguli** [comment]
No I don't use a DM im running it under systemd-user

**Comment by ramnes** [comment]
@jagguli Do you happen to run a compositor? If so, do you still have problems when the compositor does not run?
