### ISSUE TITLE
restarting qtile kills all current windows

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1589]
# Issue description

If I restart qtile using cmd.restart all current windows are killed
 
# Qtile version

0.14.2 master build (cea3b653)
# Stack traces

None

# Configuration
I'm using the DmenuRun extension to start the applications 

git@gitlab.com:asyncmind/qtile_config.git

**Comment by jagguli** [comment]
I'm running qtile on systemd user service

**Comment by zordsdavini** [comment]
As I understand you start Qtile without any login manager and restarting it restarts X. I've solved that by creating `qtile-session` executable and running through this layer:
```
#!/bin/sh

while true; do
    qtile >/dev/null 2>&1
done
```

**Comment by m-col** [comment]
Could be this bug? #1566

**Comment by zordsdavini** [comment]
Then I had display manager (sddm) I have been getting same errors about restart in command but Qtile restarted and apps there running, so it should not be related.

**Comment by zordsdavini** [comment]
p.s. I tried to add some documentation for systemd case in https://github.com/qtile/qtile/pull/1590 but we have issue with doc building and I'm waiting for fix

**Comment by jagguli** [comment]
> As I understand you start Qtile without any login manager and restarting it restarts X. I've solved that by creating `qtile-session` executable and running through this layer:
> 
> ```
> #!/bin/sh
> 
> while true; do
>     qtile >/dev/null 2>&1
> done
> ```

This worked thanks!

**Comment by ramnes** [comment]
@jagguli You should rather update Qtile, we've fixed this, no need for this loop. Check the discussion in #1615.
