### ISSUE TITLE
Path issue from moving qtile to bin/

### ISSUE THREAD

**Issue by dmpayton** [qtile/qtile#159]
I've come to realize that my attempt at a repo cleanup -- 8d33f931dd912aded31fd3a50fab581e95c3e98c -- has derped things up a bit. With those files moved into bin/, the repos libqtile is no longer on the path. This means that, e.g., scripts/Xephyr will use the systems libqtile, thus rendering it useless for development.

The reason this went unnoticed by me is because I had symlinked my qtile checkout to my dist-packages, causing everything to appear to function normally. I only discovered that things were broken when I removed the symlink, installed qtile with setup.py, and then tried to test some other changes with scripts/Xephyr.

I thought that adding ../ to PYTHONPATH might fix the issue, but easy-install.pth (which lists qtile) is added to sys.path before PYTHONPATH is, so the system libqtile is still used.

I liked the idea of moving these out of the root of the repository into a bin/ directory, but unless there is a way to add ../ to sys.path, this commit will need to be reverted.

**Comment by irl** [comment]
Just a note that this confused the hell out of me until I worked out it was a symlink.

**Comment by flacjacket** [comment]
@irl I just switched from the symlink to explicit path modifications in 01e6743e7c9e423b35de4abf2bf16e010b2814b9. As a side note, the scripts in that directory shouldn't be installed (except for `iqshell`), they should all be installed via entrypoints.
