### ISSUE TITLE
lock layout on each screen

### ISSUE THREAD

**Issue by MerrinX** [qtile/qtile#1591]
Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

# Issue description
I am trying to get one screen to have access to ws 1,3 and 7
while screen 2 has access to 2,4,5 and 6
Here is my config:
https://github.com/MerrinX/Dotfiles/blob/master/qtile/config_desktop.py

# Qtile version
0.14.2

**Comment by m-col** [comment]
Here is an extract from my config which accomplishes this with groups 1, 2, 3 on one screen and 4, 5 on another. It should be easily adapted to your numbers.
https://gist.github.com/m-col/627579cecc769776ec4b904b408dde87#file-config_extract-py

**Comment by tych0** [comment]
@m-col would you mind sending that to qtile-examples with a little writeup?

**Comment by m-col** [comment]
I'd be happy to. However, might it not make sense to include this functionality within Qtile itself? A list of group names, or the groups themselves perhaps, could be passed to `Screen`s so that any group-changing functions called elsewhere (keybinds, widgets) adhere to the locked list of groups.

**Comment by tych0** [comment]
On Wed, Apr 08, 2020 at 08:50:26AM -0700, m-col wrote:
> I'd be happy to. However, might it not make sense to include this functionality within Qtile itself? A list of group names, or the groups themselves perhaps, could be passed to `Screen`s so that any group-changing functions called elsewhere (keybinds, widgets) adhere to the locked list of groups.

People ask for it all the time, so if you can find a way to push it
upstream, that would be great.
