### ISSUE TITLE
3 Monitors

### ISSUE THREAD

**Issue by MerrinX** [qtile/qtile#1592]
Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

# Issue description
I had a thread, but it got closed before I managed to solve it. I got 3 monitors, one connceted to DVI, the two others, connected to HDMI. DVI is set as Primary on xrandr. The funny thing is when i reboot, none of the bars are correct, but when i do a reload of qtile, it becomes correct. My buttons for each screen, is correct from the getgo, but not the layout of the bars, need to do a reload after reboot.

here is my config:
https://github.com/MerrinX/Dotfiles/blob/master/qtile/config_desktop.py

screen one is supposed to be the one connected to DVI, then screen two on  HDMI 1, and third is on HDMI2.
Nb! the third screen is tilted on the side. so its 1080x1920, but i do not see how that could have had anything to say?

here is my xrandr on the autostart script:
https://github.com/MerrinX/Dotfiles/blob/master/qtile/scripts/autostart.sh

# Qtile version
0.14.2

**Comment by MerrinX** [comment]
Xrandr output

`Screen 0: minimum 8 x 8, current 4920 x 1920, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+3000+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    50.00    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
HDMI-1 connected 1080x1920+0+0 right (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+ 144.00   119.88   100.00    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 connected primary 1920x1080+1080+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  59.94    50.00    60.00    50.04  
   1680x1050     59.95  
   1440x900      59.89  
   1440x576      50.00  
   1440x480      59.94  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  `

**Comment by MerrinX** [comment]
Is there a command i can put inn my startup script, so that it automatically restart qtile at login? then this would be solved.

**Comment by MerrinX** [comment]
I hate to be asking / Pumping my own thread, but please help. When i startup, it act as the 3 monitors are all one, and when i then open a terminal, it fills all 3 monitors. but when i reload qtile, it is fine. By why this bug?

**Comment by m-col** [comment]
I think the xrandr command you are executing in your startup script needs to be executed before qtile sets up screens, for example in your `~/.xinitrc` file or somewhere else where X will run it before starting Qtile. Maybe try that?

**Comment by MerrinX** [comment]
i just add it to xinitrc, like it is now?
Thank you very much for helping

**Comment by m-col** [comment]
Yep, I'd remove that xrandr line from the autostart.sh and paste it exactly as
it is to your xinitrc.

**Comment by MerrinX** [comment]
My problem is i startx with lightdm, not using xinitrc, so it never get initialized. Is it any other place i can run xrandr from so it runs before qtile set screens?

**Comment by m-col** [comment]
I'm afraid I can't help you with that. The lightdm man page might give
information about any startup scripts that it might run. An alternate workaround
might be to put a line to restart qtile either in your autostart script or in
the hooked function in your qtile config.

**Comment by MerrinX** [comment]
How will that command be, to restart qtile in my autostart script?

Again thank you for your time, much appreciated

**Comment by m-col** [comment]
Adding "qtile-cmd -o cmd -f restart" after xrandr in your autostart.sh will do
it. No worries at all!

**Comment by MerrinX** [comment]
I managed to get it working, by using the conf file for lightdm, however now it failes when i do run a restart of qtile. It returns to login screen. here is my log file:
https://github.com/MerrinX/Dotfiles/blob/master/qtile.log

**Comment by m-col** [comment]
Could it be this bug #1566 ?

**Comment by MerrinX** [comment]
That looks like me yeah, if you are still around, i got a strange error msg..

```
groups = [
    Group('im', init=False, persist=False,
          matches=[Match(wm_class=['im'])])
```

got an unexpected keyword argument 'vm_class'

according to the documentation this is correct?

**Comment by MerrinX** [comment]
Figured it out, thank you for your help!
