### ISSUE TITLE
Netgraph widget issue

### ISSUE THREAD

**Issue by am01k01h3** [qtile/qtile#1600]
On my setup, the netgraph always shows very busy, even though I don't have much network activity going on. On startup it starts at zero but immidiately jumps up to maximum and stays there.

I'm attaching a screenshot to show comparison between how the graph looks from conky versus qtile. Am I doing something wrong, or could it be a bug?

![Screenshot from 2020-04-10 19-32-03](https://user-images.githubusercontent.com/62161236/79029530-bf04dd80-7b62-11ea-91c3-7a9a712a77f8.png)
![netgraph](https://user-images.githubusercontent.com/62161236/79029593-04c1a600-7b63-11ea-9c04-7a652a2330be.png)

[config.py.txt](https://github.com/qtile/qtile/files/4463723/config.py.txt)

**Comment by am01k01h3** [comment]
Here's one more, that shows the net usage numbers next to the graph.
![Screenshot from 2020-04-10 19-59-53](https://user-images.githubusercontent.com/62161236/79030204-ed37ec80-7b65-11ea-946f-6009889b61f5.png)

**Comment by zordsdavini** [comment]
tried your config (on left side mine, on right yours) 
![20200411_0803](https://user-images.githubusercontent.com/4191548/79035869-0f178a80-7bcb-11ea-976f-c10f1f56fd3a.png)
try not `auto`

**Comment by pawamoy** [comment]
I think we discussed this already: isn't it fixed in master? Just waiting for a new release? https://github.com/qtile/qtile/pull/1357

**Comment by tych0** [comment]
Yep, I think so. I'll try and do a release today.

**Comment by am01k01h3** [comment]
You guys are amazing. Thank you for the great work!!
