### ISSUE TITLE
man page generation is broken

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#1607]
Seems like sphinx broke internally, as we haven't changed these for a long time:

```
~/packages/qtile/docs master make man
sphinx-build -E -W -b man -d _build/doctrees   . _build/man
Running Sphinx v3.0.1
Unmet dependencies for optional Widget: '.widget.pulse_volume.PulseVolume', No module named 'libqtile.widget._pulse_audio'
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 36 added, 0 changed, 0 removed
reading sources... [100%] manual/ref/widgets                                                              
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... failed

Warning, treated as error:
"man_pages" config value references unknown document man/qtile
make: *** [Makefile:118: man] Error 2
```

But, I wonder if we can change these to be auto-generated somehow, so that we can get documentation of the new arguments people have added.

**Comment by tych0** [comment]
https://pypi.org/project/argparse-manpage/

**Comment by zordsdavini** [comment]
build breaks because of https://github.com/qtile/qtile/commit/e7aeaf71ba0ee442417fbe4de8d5883650dd8e36 :)
docs/conf.py:L116 `exclude_patterns = ['_build', 'man']`

**Comment by tych0** [comment]
Yeah, I thought I had removed that and come up with some other error :(

**Comment by ramnes** [comment]
Seems to work now! Just opened the docs with man for the first time, that's nice.
