### ISSUE TITLE
Reloading qtile shutdowns qtile

### ISSUE THREAD

**Issue by arcolinuxz** [qtile/qtile#1615]
Just a behavior change we observed after update to 0.15.0-1 on Arch Linux

super + shift + r launches this command

`Key([mod, "shift"], "r", lazy.restart()),`

I can not recall that in previous version we were thrown out of qtile and back into lightdm.

I was just wondering if this is the normal behavior starting from this version onwards.

**Comment by Kacperum** [comment]
Also experienced this exact behavior on the ly display manager. Reloading on lightdm made everything apart from the mouse and the wallpaper disappear, and rendered the X-session unresponsive.

**Comment by marcoobaid** [comment]
qtile-cmd -o cmd -f restart is behaving exactly like qtile-cmd -o cmd -f shutdown
It throws the user to the login screen. Previously, qtile-cmd -o cmd -f restart will reload the Qtile config.

**Comment by seanbreckenridge** [comment]
Ah. Also on Arch; I was switching over from from another WM a few hours ago and experienced the same issue with `lightdm` (kicking me back to the login screen), thought it was some issue with `lightdm`.

Am now using `sddm`; invoking `refresh` stops `qtile` process but doesn't start it again; it doesn't kick me out to the login screen either, I end up just being stuck with no way to reboot `qtile` (unless I happened to be at a terminal already)

**Comment by aegis965** [comment]
Can confirm. I'm also on Arch. I have a restart hook that subscribes to `screen_change`. I use `startx`, so everytime my screen goes to power saving mode I'm thrown back to tty.

**Comment by shauser** [comment]
Same issue here. `qtile-cmd -o cmd -f restart` produces the following output:
```
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 84, in unpack
    assert len(data) >= HDRLEN
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/.local/bin/qtile-cmd", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/scripts/qtile_cmd.py", line 205, in main
    ret = run_function(obj, args.function, args.args)
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/scripts/qtile_cmd.py", line 143, in run_function
    ret = func(*args)
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/command_client.py", line 179, in __call__
    return self._command.execute(self._current_node, args, kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/command_interface.py", line 221, in execute
    status, result = self._client.send((
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 215, in send
    self.loop.run_until_complete(asyncio.wait_for(client_proto.reply, timeout=10))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 161, in eof_received
    data, _ = _IPC.unpack(self.recv)
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 89, in unpack
    raise IPCError(
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```

And on the server side:

```
2020-04-14 13:13:45,443 ERROR libqtile manager.py:<lambda>():L201 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 872, in _read_ready__on_eof
    keep_open = self._protocol.eof_received()
  File "/home/xxx/.local/lib/python3.8/site-packages/libqtile/ipc.py", line 282, in eof_received
    self.transport.write(result)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 893, in write
    raise RuntimeError('Cannot call write() after write_eof()')
RuntimeError: Cannot call write() after write_eof()
```

**Comment by zordsdavini** [comment]
That's why I use in .xinitrs
```
while true; do
    qtile
done
```
http://docs.qtile.org/en/latest/manual/config/without-dm.html

**Comment by pawamoy** [comment]
Off-topic but, @zordsdavini doesn't `startx` run a loop already? Here's what they do in ArchLabs:

```
init runs zsh (or other default shell)
zsh runs .zprofile
in .zprofile, exec startx
startx runs .xinitrc
in .xinitrc, exec qtile
```

Or is it because things are `exec`'d, and therefore if they fail, there's no process under `init` anymore and `init` starts the whole chain again? Last time I changed code in my main qtile instance, it broke, and was re-spawning indefinitely. I had to open another TTY, and comment the contents in `.zprofile` character by character between each qtile respawn to stop the endless loop. It was hell :laughing:

**Comment by tych0** [comment]
Oof, this is my fault. I reverted the buggy commit, let me know if it would be useful to have another release.

**Comment by ramnes** [comment]
@tych0 This is affecting people a lot, I'd be in favor of releasing a 0.15.1.

**Comment by tych0** [comment]
Ok, I'll do a 0.15.1 with just this commit.

**Comment by zordsdavini** [comment]
@pawamoy yes, it's pain in a** to interupt this infinity restarts but I didn't have choice to reload Qtile without loosing session

**Comment by tych0** [comment]
https://github.com/qtile/qtile/tree/v0.15.1

**Comment by ramnes** [comment]
Thanks @tych0! I'll keep the issue pinned for a few days in case people updated to 0.15.0 but did not see 0.15.1 yet. I also added an edit to OP to that end.

**Comment by dvzrv** [comment]
I've just updated the package on Arch.

**Comment by arcolinuxz** [comment]
Confirming that on ArcoLinux there is no issue anymore.

**Comment by kaistian** [comment]
Any ETA on when 15.1 is available in PyPI?

**Comment by tych0** [comment]
Oh, derp. I just didn't upload it, let me do that now.

**Comment by tych0** [comment]
Should be up, thanks for the ping!

**Comment by kaistian** [comment]
Thanks, only thing missing is an update of http://www.qtile.org/

**Comment by tych0** [comment]
Yep, got that too. Thank you :)
