### ISSUE TITLE
KeyboardLayout widget re-applies layout every two seconds

### ISSUE THREAD

**Issue by shauser** [qtile/qtile#1616]
# Issue description

When the KeyboardLayout widget is loaded, the command `setxkbmap -verbose 10` is executed every two seconds.This command causes a `MappingNotify` message to be broadcast, which can cause issues in other programs.

A good example for this is the kitty terminal emulator, which tries to releoad the keyboard layout and currently has an issue which doesn't remember the modifier key states when doing so.

To reproduce this problem:
* Start qtile with the keyboard layout widget present
* Start kitty
* Open nano and load a large file
* Press and hold Ctrl and press k (cut line) repeatadly

As soon as the `setxkbdmap` call is run, the ctrl key stops working untill released and re-pressed.

While I'm not exactly sure this is solely a qtile bug, I have a feeling that other applications have similar issues and fixing the issue in Kitty is just going to patch one instance of this. Instead of calling `setxkbdmap` itself, which re-applies the current configuration, we should rather call `setxkbdmap -print` or `-query` which will only report the current settings. This is also preferable from a performance standpoint.

# Qtile version

qtile 0.15.0 as published on pypi.org

**Comment by ramnes** [comment]
Related to #1446

**Comment by zordsdavini** [comment]
That part of -query and -print I've already noted. I want to rewrite widget but don't find time for it. But will
