### ISSUE TITLE
Be consistent on imports style

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1618]
[PEP8 favors absolute imports](https://www.python.org/dev/peps/pep-0008/#imports), let's use them everywhere in place of the relative ones we have.

The discussion started here: https://github.com/qtile/qtile/pull/1611#discussion_r408289718

**Comment by tych0** [comment]
+1, sounds good to me. And if there's a linter we can use to reject relative imports after we fix this, even better.

**Comment by pawamoy** [comment]
I'm taking care of this right now, before #1625.

**Comment by pawamoy** [comment]
I couldn't find a tool to check for presence/absence of relative imports, but we could write a Python script:

```python
import ast

with open("file.py") as fd:
    code = ast.parse(fd.read())

for node in code.body:
    if isinstance(node, ast.ImportFrom) and node.level > 0:
        print("detected relative import!")
```

We would need something a bit more complex of course, to recurse on nodes' bodies, etc.

**Comment by ramnes** [comment]
Isort doesn't seem to do that, bummer. Just found this library, maybe it's would be worth a try?

https://github.com/adamchainz/flake8-tidy-imports

**Comment by ramnes** [comment]
Oh, pylint seems to check and enforce absolute imports also.

**Comment by pawamoy** [comment]
The flake8 plugin seems like the way to go :slightly_smiling_face:

**Comment by ramnes** [comment]
Thanks @pawamoy!
