### ISSUE TITLE
Dropdown lost focus kill process

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#1621]
I have a DropDown the mutt email client and I would like to run and kill it when I trigger the dropdown. Is this possible to do or to hack in?

**Comment by m-col** [comment]
The `group_window_add` hook is fired upon both dropdown show and dropdown hide. You could hook a function to it that could check the scratchpad group for your mutt window, and if it is there, kill it. Then when you send the dropdown back to the scratchpad, it is killed. Is that what you mean?
