### ISSUE TITLE
widget.WindowTabs default selected task indicator produces invalid pango markup

### ISSUE THREAD

**Issue by airwoodix** [qtile/qtile#1622]
# Issue description

The default _selected task indicator_ (``("<", ">")``) for ``widget.WindowTabs`` produces invalid pango markup and thus the call to ``pango_parse_markup`` fails.

It leads to invalid tag names for single word window names (e.g. ``<terminal>``) or invalid syntax for multiword names (e.g. ``<qtile - Mozilla Firefox>``).

Possible fixes:

- change default to e.g. ``('[', ']')`` or different foreground color
- default to no markup
- at least add a note in the documentation, but defaults should be working

If this is wanted, I'm happy to prepare a PR based on the outcome of the discussion here.

# Qtile version

Qtile version ``0.15.1``. Also [latest revision of libqtile/widget/windowtabs.py](https://github.com/qtile/qtile/blob/d47347ad0f37b4a5735faa8b7061f484e8cf81d9/libqtile/widget/windowtabs.py) (d47347a)

# Configuration

Use default ``widget.WindowTabs()``

**Comment by tych0** [comment]
Thanks for the report! I'd say maybe just use `("<b>", "</b>")`?

**Comment by airwoodix** [comment]
Sounds good, thanks for the quick feedback.
