### ISSUE TITLE
Auto-format the code

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1623]
In the same quality approach of #1618, would you consider using a tool like [black](https://github.com/psf/black) to auto-format the code?

To try, I've ran it on the code base with the options `-l 120 -t py35 -S` (max line length 120 based on flake8 config, target style for py35, no string normalization).

```console
% git diff --stat
 libqtile/backend/x11/xcbq.py               |  262 ++++++---------
 libqtile/backend/x11/xcore.py              |   43 +--
 libqtile/backend/x11/xcursors.py           |   10 +-
 libqtile/backend/x11/xcursors_ffi_build.py |    6 +-
 libqtile/bar.py                            |   35 +-
 libqtile/command_client.py                 |   18 +-
 libqtile/command_interface.py              |    4 +-
 libqtile/command_object.py                 |    4 +-
 libqtile/config.py                         |  149 ++++-----
 libqtile/confreader.py                     |    1 +
 libqtile/core/manager.py                   |  157 ++++-----
 libqtile/core/session_manager.py           |    4 +-
 libqtile/dgroups.py                        |   33 +-
 libqtile/drawer.py                         |   66 ++--
 libqtile/extension/base.py                 |    1 +
 libqtile/extension/dmenu.py                |   10 +-
 libqtile/extension/window_list.py          |    3 +-
 libqtile/group.py                          |   83 ++---
 libqtile/hook.py                           |    6 +-
 libqtile/images.py                         |    4 +
 libqtile/interactive/iqshell_kernel.py     |    1 +
 libqtile/ipc.py                            |   15 +-
 libqtile/layout/base.py                    |   31 +-
 libqtile/layout/bsp.py                     |   37 +-
 libqtile/layout/columns.py                 |   73 ++--
 libqtile/layout/floating.py                |   23 +-
 libqtile/layout/matrix.py                  |   24 +-
 libqtile/layout/max.py                     |    9 +-
 libqtile/layout/ratiotile.py               |   58 +---
 libqtile/layout/slice.py                   |    8 +-
 libqtile/layout/stack.py                   |   38 +--
 libqtile/layout/tile.py                    |   41 ++-
 libqtile/layout/tree.py                    |   64 +---
 libqtile/layout/verticaltile.py            |    6 +-
 libqtile/layout/xmonad.py                  |  138 ++------
 libqtile/layout/zoomy.py                   |   43 +--
 libqtile/log_utils.py                      |   27 +-
 libqtile/notify.py                         |   10 +-
 libqtile/pango_ffi_build.py                |    6 +-
 libqtile/pangocffi.py                      |    3 +
 libqtile/resources/default_config.py       |   77 ++---
 libqtile/scratchpad.py                     |   37 +-
 libqtile/scripts/qshell.py                 |   27 +-
 libqtile/scripts/qtile.py                  |   56 ++--
 libqtile/scripts/qtile_cmd.py              |   45 +--
 libqtile/scripts/qtile_run.py              |   44 +--
 libqtile/scripts/qtile_top.py              |   47 ++-
 libqtile/sh.py                             |   16 +-
 libqtile/state.py                          |    1 +
 libqtile/utils.py                          |    9 +-
 libqtile/widget/__init__.py                |   14 +-
 libqtile/widget/backlight.py               |   28 +-
 libqtile/widget/base.py                    |   72 ++--
 libqtile/widget/battery.py                 |   76 ++---
 libqtile/widget/bitcoin_ticker.py          |    3 +-
 libqtile/widget/canto.py                   |   15 +-
 libqtile/widget/check_updates.py           |   27 +-
 libqtile/widget/clipboard.py               |   26 +-
 libqtile/widget/clock.py                   |   23 +-
 libqtile/widget/cmus.py                    |   14 +-
 libqtile/widget/countdown.py               |   15 +-
 libqtile/widget/cpu.py                     |    6 +-
 libqtile/widget/crashme.py                 |    8 +-
 libqtile/widget/currentlayout.py           |   26 +-
 libqtile/widget/currentscreen.py           |    2 +-
 libqtile/widget/debuginfo.py               |    7 +-
 libqtile/widget/df.py                      |   23 +-
 libqtile/widget/generic_poll_text.py       |    5 +
 libqtile/widget/gmail_checker.py           |   10 +-
 libqtile/widget/graph.py                   |   41 +--
 libqtile/widget/groupbox.py                |  129 +++----
 libqtile/widget/image.py                   |    4 +-
 libqtile/widget/imapwidget.py              |    1 +
 libqtile/widget/import_error.py            |    1 +
 libqtile/widget/keyboardkbdd.py            |   28 +-
 libqtile/widget/keyboardlayout.py          |   13 +-
 libqtile/widget/khal_calendar.py           |   22 +-
 libqtile/widget/launchbar.py               |   33 +-
 libqtile/widget/maildir.py                 |   34 +-
 libqtile/widget/moc.py                     |   11 +-
 libqtile/widget/mpd2widget.py              |   57 ++--
 libqtile/widget/mpris2widget.py            |   58 ++--
 libqtile/widget/mpriswidget.py             |   34 +-
 libqtile/widget/net.py                     |   31 +-
 libqtile/widget/notify.py                  |   25 +-
 libqtile/widget/pacman.py                  |    1 +
 libqtile/widget/pomodoro.py                |   13 +-
 libqtile/widget/prompt.py                  |  104 +++---
 libqtile/widget/pulse_volume.py            |   63 +---
 libqtile/widget/pulseaudio_ffi.py          |    6 +-
 libqtile/widget/sensors.py                 |   38 +--
 libqtile/widget/sep.py                     |   14 +-
 libqtile/widget/she.py                     |    3 +-
 libqtile/widget/spacer.py                  |    8 +-
 libqtile/widget/stock_ticker.py            |    6 +-
 libqtile/widget/systray.py                 |   48 +--
 libqtile/widget/tasklist.py                |  145 ++------
 libqtile/widget/textbox.py                 |    1 +
 libqtile/widget/volume.py                  |   40 +--
 libqtile/widget/wallpaper.py               |   23 +-
 libqtile/widget/windowname.py              |    3 +-
 libqtile/widget/windowtabs.py              |    1 +
 libqtile/widget/wlan.py                    |   24 +-
 libqtile/widget/yahoo_weather.py           |   26 +-
 libqtile/window.py                         |  301 +++++++----------
 libqtile/xkeysyms.py                       | 3454 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------------------------------------------------
 106 files changed, 3123 insertions(+), 4034 deletions(-)
```

-911 lines.

Of course it doesn't mean the code is more readable. In some places, it's not. But it's still readable, just not as "visual" as before. In most other places, I find it more readable.

It should also be optimized to reduce the size of diffs in PRs.

What's your opinion on this?

**Comment by tych0** [comment]
I am generally in favor of code formatters, so that seems reasonable. I'd like to look through the diff just to make sure it's not too insane, though.

If we do this, we should also make CI fail so that we don't have to do this every once in a while.

**Comment by pawamoy** [comment]
> If we do this, we should also make CI fail so that we don't have to do this every once in a while.

Black has a `--check` option to do this.

> I'd like to look through the diff just to make sure it's not too insane, though.

I can open a PR if you want, not to be merged, just for you to take a look :slightly_smiling_face: 

Otherwise you can easily try locally: `pip install black && black -l 120 -S libqtile`.

**Comment by tych0** [comment]
On Thu, Apr 16, 2020 at 08:27:56AM -0700, Timothée Mazzucotelli wrote:
> > If we do this, we should also make CI fail so that we don't have to do this every once in a while.
> 
> Black has a `--check` option to do this.
> 
> > I'd like to look through the diff just to make sure it's not too insane, though.
> 
> I can open a PR if you want, not to be merged, just for you to take a look :slightly_smiling_face: 
> 
> Otherwise you can easily try locally: `pip install black && black -l 120 -S libqtile`.

Naturally, I think this would need some manually fixing up,

```
-            0, self.wid,  # src_window, dst_window
-            0, 0,         # src_x, src_y
-            0, 0,         # src_width, src_height
-            x, y          # dest_x, dest_y
+            0,
+            self.wid,  # src_window, dst_window
+            0,
+            0,  # src_x, src_y
+            0,
+            0,  # src_width, src_height
+            x,
+            y,  # dest_x, dest_y
```

I'd also like to limit line length to something < 120, it does a lot
of formatting expanding line lengths when we set it to 120, which is
not great in my mind. I tried with 80 and it some similarly ugly things, but 90
seems reasonable.

It does stupid stuff like:

```
-    "USPosition": 1,     # User-specified x, y
-    "USSize": 2,         # User-specified width, height
-    "PPosition": 4,      # Program-specified position
-    "PSize": 8,          # Program-specified size
-    "PMinSize": 16,      # Program-specified minimum size
-    "PMaxSize": 32,      # Program-specified maximum size
-    "PResizeInc": 64,    # Program-specified resize increments
-    "PAspect": 128,      # Program-specified min and max aspect ratios
-    "PBaseSize": 256,    # Program-specified base size
+    "USPosition": 1,  # User-specified x, y
+    "USSize": 2,  # User-specified width, height
+    "PPosition": 4,  # Program-specified position
+    "PSize": 8,  # Program-specified size
+    "PMinSize": 16,  # Program-specified minimum size
+    "PMaxSize": 32,  # Program-specified maximum size
+    "PResizeInc": 64,  # Program-specified resize increments
+    "PAspect": 128,  # Program-specified min and max aspect ratios
+    "PBaseSize": 256,  # Program-specified base size
```

and

```
-                    results.append((
-                        x + xoffset,  # i * width + xoffset,
-                        y + yoffset,  # j * height + yoffset,
-                        width,
-                        height
-                    ))
+                    results.append(
+                        (
+                            x + xoffset,  # i * width + xoffset,
+                            y + yoffset,  # j * height + yoffset,
+                            width,
+                            height,
+                        )
+                    )
```

But overall it seems like it would be better to be consistent even if it's bad.
Too bad you can't disable stuff :)

**Comment by pawamoy** [comment]
Apparently there's a `fmt: on/off` feature:

https://github.com/psf/black/issues/1162

**Comment by ramnes** [comment]
As hard I want a code formatter to stop useless debates and to stop caring, and as appealing a defacto standard is, I really do not lean towards black. I've been working with this tool for a year or so, and I do not like it for so many reasons that it would be pointless to list them here.

My favorite setup so far is just flake8 with a bunch of extensions properly configured in the repository and in the CI, for lack of a better one.

**Comment by ramnes** [comment]
Now if I'm the only one that do not like black, feel free to put it in place, that's better than nothing. Even if I find it pretty depressing, I won't put my energy in fighting this but rather accept to live with it.

**Comment by tych0** [comment]
Is there another option? I'd like to be able to disable some of the stuff.

**Comment by pawamoy** [comment]
There's yapf, which is highly configurable

**Comment by ramnes** [comment]
There's autopep8 also, which IIRC is not idempotent but does the job if you want to stick to flake8. I've played a bit with yapf but not enough to have a strong opinion. From what I recall I couldn't have it format to my tastes, but it wasn't near as bad as black one configured.

**Comment by ramnes** [comment]
Another tool that could be useful if we want to keep more freedom but still enforce the bare minimum is EditorConfig.

Also, as mentioned in another issue, should we talk about the line length? I'm the reactionary 80 characters kind of guy, because it enforces clear and concise code, and above all because it allows me to split my screen into numerous columns without ugly line breaks.

**Comment by flacjacket** [comment]
I'm open to some more heavy handed formatting as long as there are good linters and fixers in place for it. I haven't used yapf before, but have used black, and have found it to be pretty nice, especially that its fixer is really consistent and really fast. In general I find the oddities it can introduce are worth the consistency, but if you have a lot of nested lists and tuples it can get nasty fast. Definitely open to something like this.

**Comment by mikelward** [comment]
I'm going to provide updated info using `black`.

I don't love everything it does, but I like not having to think about it.

The inconsistent string quoting is one of the first things I noticed about Qtile, so I'd lean towards not passing `-S`.

I'd like to see what it does with no flags...

**Comment by ramnes** [comment]
> As hard I want a code formatter to stop useless debates and to stop caring, and as appealing a defacto standard is, I really do not lean towards black. I've been working with this tool for a year or so, and I do not like it for so many reasons that it would be pointless to list them here.

FWIW I'm getting more and more used to black so I must revise my words and say I wouldn't mind anymore if we used it here as well. To anyone that really cares about this, a PR that fixes style and adds CI may be a good start. :)

**Comment by m-col** [comment]
I would LOVE to use black on Qtile, and if nobody else wants to take it up then I'll happily do it. I mean, I do have other things I need to do so I'd rather someone volunteer, but just saying, I am very eager to use black so I'd do it anyway if not.
