### ISSUE TITLE
Add default config Key descriptions?

### ISSUE THREAD

**Issue by arczan1** [qtile/qtile#1628]
I watched [youtube video](https://youtu.be/hGwoRyykifw?t=572)(Distrotube) where author talks about feature in Qtile that lot of users don't know about. It is optional "description" parameter in Key class.

I think it is good idea to add it to defaut_config.py for example.
` 
   Key([mod], "k", lazy.layout.down(), desc="Go down in stuck"),
`

Description for key bindings helps hacking Qtile in my opinion.

If this idea is good I can take this issue :)

**Comment by ramnes** [comment]
Hey @arczan1, good idea! Let's have the discussion in #1024.
