### ISSUE TITLE
lazy.when

### ISSUE THREAD

**Issue by cubimon** [qtile/qtile#1629]
# Issue description

I found this quite oldy [`config.py`](https://gist.github.com/cjbarnes18/4151805) that uses a `when` operation to limit the keybinding to a layout but it throws an exception. I also couldn't find it in the docs, so is it supposed to exist? Is there another similar intended way to limit key bindings to a layout.

```python
from libqtile.lazy import lazy
```
...
```python
    Key([mod], 'Left',
        lazy.layout.left().when('xmonadtall'))
```

# Qtile version

v0.15.0

# Stack traces

```
libqtile xcore.py:_xpoll():L277  Got an exception in poll loop
Traceback (most recent call last):
  File "/share/git/qtile/libqtile/backend/x11/xcore.py", line 246, in _xpoll
    ret = target(event)
  File "/share/git/qtile/libqtile/backend/x11/xcore.py", line 494, in handle_KeyPress
    self.qtile.process_key_event(keysym, event.state & self._valid_mask)
  File "/share/git/qtile/libqtile/core/manager.py", line 342, in process_key_event
    if cmd.check(self):
AttributeError: 'NoneType' object has no attribute 'check'
```

Thanks for any help

**Comment by ramnes** [comment]
Yep, it's still supposed to work as it's still in the code: https://github.com/qtile/qtile/blob/09b7d517312886b7af47c8c1e13bca88f845ccff/libqtile/lazy.py#L72-L74

That being said I don't see any unit test for this which is probably why it doesn't work anymore.
