### ISSUE TITLE
Dual Monitors going wonky after waking up from sleep

### ISSUE THREAD

**Issue by mtwb47** [qtile/qtile#1632]
Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

# Issue description

I'm using qtile on arcolinux right now. I have a dual monitor setup. When the monitors go to sleep, everything is fine. Both monitors display their respective workspaces (groups). When the monitors are woken up from sleep, only one group is displayed stretching across both monitors. I have to do a qtile recompile to get it to go back to the way it should be. I haven't a clue as to how to fix this. I'm guessing that something in xrandr isn't saving the screen layout? IDK. Any help would be appreciated because this is annoying af. This doesn't happen in i3, DWM, or XFCE which I have installed on the same OS.
Linux Kernel 5.6.4-arch1-1

# Qtile version

Please include the exact commit hash of the version of Qtile that failed.
0.15.1 (I'm not sure if this was what you're asking for)

# Stack traces

Please attach any stack traces found in:

* `~/.xsession-errors`
Top of the file (not sure what the first line means, but might be my issue?) 

```
warning: output HDMI2 not found; ignoring
(pamac-tray:78890): GLib-GIO-CRITICAL **: 01:03:49.935: GApplication subclass 'PamacGtkTrayIcon' failed to chain up on ::startup (from start of override function)

(pamac-tray:78890): GLib-GIO-CRITICAL **: 01:03:49.935: GApplication subclass 'PamacGtkTrayIcon' failed to chain up on ::shutdown (from end of override function)
conky: desktop window (6b5) is root window
conky: window type - override
conky: drawing to created window (0x1000002)
conky: drawing to double buffer
conky: forked to background, pid is 78928
```

* `~/.local/share/qtile/qtile.log`

(just the first of the file. The most recent errors are from the update not being kind to the arcomemory script, that was rectified recently) https://pastebin.com/AambPd2m

# Configuration

Please include a link or attach your configuration to the issue.

https://pastebin.com/MxMrY39G

**Comment by tych0** [comment]
On Thu, Apr 16, 2020 at 10:36:23PM -0700, mtwb47 wrote:
> Please do not ask general questions here! There are [community
> contact](https://github.com/qtile/qtile#community) options for that.
> 
> # Issue description
> 
> I'm using qtile on arcolinux right now. I have a dual monitor setup. When the monitors go to sleep, everything is fine. Both monitors display their respective workspaces (groups). When the monitors are woken up from sleep, only one group is displayed stretching across both monitors. I have to do a qtile recompile to get it to go back to the way it should be. I haven't a clue as to how to fix this. I'm guessing that something in xrandr isn't saving the screen layout? IDK. Any help would be appreciated because this is annoying af. This doesn't happen in i3, DWM, or XFCE which I have installed on the same OS.
> Linux Kernel 5.6.4-arch1-1

Yes, I've seen this behavior myself, so I can confirm. Restarting will
fix it, but it would be great not to have to restart.

**Comment by zordsdavini** [comment]
I don't know is it much related, but yesterday I got stuck after suspend. I couldn't restart, so had to kill Qtile :-1: I was in hurry, so didn't check logs

**Comment by tych0** [comment]
I think #1848 should fix this, if anyone can test and confirm. It fixes similar behavior for me.
