### ISSUE TITLE
Qtile update broke my config

### ISSUE THREAD

**Issue by Godnyx** [qtile/qtile#1640]
Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

# Issue description

I just updated qtile to version 0.15.1 and after the restart my config completely broke!

# Qtile version

0.15.1

# Stack traces

Please attach any stack traces found in:

qtile.log file is [here](https://gist.github.com/Godnyx/294303aee9267beac389a7e01a37abd7)

# Configuration

The config is [here](https://gist.github.com/Godnyx/bbf4829268d329e6a32ca1cadf5d1d52)!

**Comment by zordsdavini** [comment]
7th line in config: Client is moved to command_client https://github.com/qtile/qtile/issues/1633

**Comment by Godnyx** [comment]
Thanks a lot! What about the other things? I've started from the default config Qtile gives and tried to match my previous one. But I'm getting some errors? Do we have a complete changelog?

**Comment by tych0** [comment]
Looks like you're probably hitting: https://github.com/qtile/qtile/blob/master/CHANGELOG#L20

**Comment by Godnyx** [comment]
Thanks a lot! I'm gonna check it. Also Arcolinux qtile and Derek Taylor's config will help A LOT!!!
