### ISSUE TITLE
Focus issue with Jetbrains IDEs

### ISSUE THREAD

**Issue by Granitosaurus** [qtile/qtile#1641]
# Issue description

Recent Qtile has issues with window focus with java based Jetbrainds IDEs such as Pycharm. whenever the IDE window focus is lost regained focus is broken: seems like key capture is being corrupted, e.g. no text input.   
This can be fixed by forcing focus via some pop up window (i.e. ctrl+e) however leaving focus will bring back the issue and you need to force focus again. 

I'm not sure whether this is qtile or pycharm's issue as I don't have alternative setup to try to replicate this. Is anyone else suffering from this issue?

# Versions

Qtile - 0.15.1
Pycharm - 2020.1

# Configuration
```
wmname = "LG3D"
```

**Comment by pawamoy** [comment]
Related: #1548

**Comment by Pilifer** [comment]
The escape trick doesn't work for me. Middle button works, but I had to disable pasting with that button.

**Comment by pawamoy** [comment]
Take a look at #1548, I've posted some links to workarounds.

**Comment by Granitosaurus** [comment]
Closing in favor of https://github.com/qtile/qtile/issues/1548 - seems to have the same cause.
