### ISSUE TITLE
Systray not updating icons, just showing on top

### ISSUE THREAD

**Issue by gfz23** [qtile/qtile#1653]
Instead of updating an icon in the systray when it updates it just plunks it on top of the old icon. It seems to do this with everything, here's an example. 
![ibus](https://user-images.githubusercontent.com/64043870/79801180-dbe7a080-831a-11ea-88cb-4779ad8bfd81.png)

**Comment by m-col** [comment]
Weird - its working fine for me. What qtile version is this on? What is your config?
