### ISSUE TITLE
qtile.update_gaps isn't cleanly reconfiguring bars

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1654]
# Issue description

If I create a window that says its window type is `_NET_WM_WINDOW_TYPE_DOCK`, qtile.update_gaps is called. My qtile bar then reacts strangely: clicks still work, a CPU graph continues to update, but the groupbox doesn't update when I change groups. The compton shadows around the bar get darker, so I suspect that what is happening is a new bar is being created (in the _configure calls), or at least the bar is creating a new window for itself, but the original isn't being cleaned away.

I'd like to take a look and fix the behaviour, but first I wanted to clarify what the full aims of qtile.update_gaps are. This is what I could interpret from the code:

1. if a dock is spawned with the window type above or it has strut hints and wants reserved edge space, qtile turns its window into a `Static` window
2. `Static` replaces qtile's struts with its own (maybe qtile should be summing them? What if there are two windows with struts?)
3. With the new struts, qtile should update current_screen.{top,bottom,left,right} to make space. This bit seems to be the broken bit. 

I think the solution might involve slightly changing how the bars are configured so that they don't need to create a whole new window upon reconfiguring, and just need to increase their outside margin.

# Qtile version

5bd8e57

**Comment by m-col** [comment]
Looking into this, I can't see what benefit there is to Qtile handling struts at all. If a user wants to make space for a third party bar/dock then they are able to easily by adding a Gap, or if there is a Bar on that edge, then by setting the margin. With Bars having margins now, do we need [window.Static.update_strut](https://github.com/qtile/qtile/blob/master/libqtile/window.py#L736), [qtile.reset_gaps](https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L494) and [qtile.update_gaps](https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L498)?

**Comment by tych0** [comment]
On Mon, Apr 27, 2020 at 01:40:43PM -0700, m-col wrote:
> Looking into this, I can't see what benefit there is to Qtile handling struts at all. If a user wants to make space for a third party bar/dock then they are able to easily by adding a Gap, or if there is a Bar on that edge, then by setting the margin.

Right, but they have to do that manually. IIUC the struts spec is so
that they don't. i.e. the bar can tell the WM itself "hey, WM_STRUTS
extension me off 30px at the top", so the user needn't intervene.

**Comment by m-col** [comment]
This is being addressed by #1820

**Comment by m-col** [comment]
Fixed by #1654 :)
