### ISSUE TITLE
Feature: Simplify the creation of keybindings with custom conditions (i. e. per program keybindings)

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#1661]
Qtile makes it relatively hard to have key combinations trigger different action depending on the active window (or the qtile state in general).
It would be nice to make simple filters like so:
```py
import re
from libqtile.lazy import lazy
from libqtile.config_utils import program_filter
from libqtile.... import Key

PROG_FF = program_filter(title=re.compile('.* - Mozilla Firefox))

keys = [
    ...
    Key([mod], 'x',
        lazy.layout.shuffle().when(filter_func=PROG_FF),
        ...
    ),
    ...
]
```
# Details
+ `when` should take a `Callable[[libqtile.manager.Qtile], bool]` as an argument (`filter_func`)
+ `program_filter` is a helper function that generates such a filter func
+ this approach should be modular: instead of adding a `program_title_re` argument to when, it is more pythonic to pass a custom callable. Why? Because then the user has the choice, we don't limit users just to check the window titles. We avoid that the user has to implement similar features using `lazy.function` that do basically the same thing...

# Possible problems
+ What if an action should only be triggered when all the other actions weren't triggered? (-> python is missing a switch-case/match statement / functionality, really) That is a bit annoying... Maybe a magic argument `default_action=True`???
+ What about the description argument to `Key` et al? Should it be `desc: Union[str, List[str]]`?

Opinions? More examples and ideas for features that this should have? More state variables that might be checked in `filter_func`s regularly (-> more helper functions)?

**Comment by airwoodix** [comment]
What about leaving ``when`` as a simple layout filter and calling this functionality ``dispatch``?

One could then recycle keybindings depending on context, something like:

```python
Key([mod], 'x', lazy.dispatch({
     program_filter("firefox"): cmd1,
     custom_filter: cmd2,
     # ...
    })
```
with the keys being ``Callable[['Qtile'], bool]`` as you proposed.

Discussion:

  - didn't think too much about the implementation details. Not sure how non-trivial this is but looks feasible as a wrapper around ``function``;

  - iteration order might be crucial. For Py3.5 users, passing an ``OrderedDict`` is a bit verbose but would work. IIRC, since Py3.6 (effectively) and Py3.7 (guaranteed), the insertion order is preserved for dicts;

  - it is trivial to define a default action;

  - there might be a good amount of syntactic sugar to add to make it nice to use.  In particular, an extensive list of built-in predicates would be nice (``program_matches``, ``group_matches``, ``current_layout_matches``, etc.)

  - chained calls might be used instead of a dict, e.g. (_à la_ ``functools.singledispatch``):

```python
 Key([mod], 'x', lazy.dispatch\
    .register(cmd1, program_filter("firefox"), cmd1)\
    .register(cmd2, current_group_matches("[a-d]"), current_layout_matches("max"))
```

  This has the advantage that the iteration order is explicit and easy to guarantee without adding boilerplate in user code. Also, multiple filters can be AND-ed (like for ``cmd2``).

  - getting the same effect as ``when`` requires boilerplate, thus making ``when`` still valid:

```python
 Key([mod], 'x', lazy.dispatch\
     .register(cmd, current_layout_matches("columns,monadtall"), cmd)\
    .register(noop, true_filter)
```

What's you take on that? I think it is more versatile than extending ``when`` and the implementation will be cleaner, since separated from the ``when``/``check`` mechanism.

**Comment by ep12** [comment]
I like that! The second variant seems perfect, although I personally don't like the ugly trailing backslash.
Yeah, my personal config also has this feature implemented using `lazy.function`, but I think it should be built-in to qtile...

**Comment by ep12** [comment]
But I have to think about how to handle edge cases (`when` and `dispatch` mixed). Maybe that's not a problem at all, but I wanted to write it down so you can remind me if I forget thinking about it :smile:...

**Comment by airwoodix** [comment]
> although I personally don't like the ugly trailing backslash.

Good point, it's not necessary here since the calls are in brackets. :)

> But I have to think about how to handle edge cases (``when`` and ``dispatch`` mixed). 

  - One could think about applying ``when`` to ``cmd``in ``register`` as a shortcut to ``current_layout_matches`` filters. But that's just a shortcut, I probably wouldn't use this.

  - applying ``when`` to the dispatcher might also be interesting to restrict command dispatching to a specific layout. This is less verbose than adding a layout matching filter to all the registered commands. But this also opens Pandora's box for extra arguments for ``when``: what about filtering per group for example? I guess one needs to draw a line where the "common" use cases stop.

I have the impression that both cases should integrate seamlessly if ``dispatch`` is a regular lazy call. Or don't they? Do you see other cases?

The keybinding description issue remains and supporting this in the keybinding cheat sheet generator from #1631 won't be trivial. For the moment, I'd add a keyword-only argument ``desc`` to ``register`` and store that in the dispatcher. Any thoughts on that @zordsdavini ? Is the key description used somewhere else?

**Comment by zordsdavini** [comment]
I can't answer do we have description used somewhere else. I think it was only for user self to put some info, like DT did. In keybinding image generator this description if exists is used as label. 
There was no  much thoughts about how button should look if we will have many commands on button. For now I just take 1st command and use its scope.
But maybe I didn't understand the problem that you @airwoodix is describing :-/

**Comment by airwoodix** [comment]
So one could stick to a keyword-only argument to ``register`` and not bother too much about what is done with it.

@ramnes @tych0 any opinions on the proposed feature?
@ep12 would you like to work on a PR for this?

**Comment by ramnes** [comment]
I think this is a pretty advanced and niche usage that could be handled by the user writing a simple lazy.function in his config.

That being said, I see some similarities with [the float_rules of the Floating layout](https://github.com/qtile/qtile/blob/master/libqtile/layout/floating.py#L67-L79) and would probably +1 for something that is consistent with these.

**Comment by ep12** [comment]
Uuu. I don't think this is very niche at all. I have a wacom tablet and since GIMP, Krita, blender, xournal and xournal++ all have different things and shortcuts I want to associate with the buttons on that keyboard, I need to filter the actions by program...
The same is true for macro keyboards e. g. for video editing or whatever you like. Or for layout management in vim, emacs, gui editors and tmux, maybe even unified tab management in browsers and text editors. They all have different ways to achieve a split, a macro keyboard would help not to remember all that stuff...
Another example would be the XF86AudioPlay button. Maybe I just want to pause music or a video in one player like cmus that is currently focussed while I already started up a movie in VLC which starts with some logos.
There are definitely a ton of use cases, although some of them are less likely to affect the _average_ user (who always uses Microsoft Office, you know). With #1576 we could find out what the _average qtile user_ uses. Maybe tells us that some of the following are niche widgets:
+ `BitcoinTicker`
+ `CapsNumLockIndicator`: No matter if it is on screen or not, you would probably notice that you pressed caps lock only when you start typing.
+ `CheckUpdates`: I guess that the _average qtile user_ updates the system in a terminal. There will be people out there who use this widget, but maybe that's a minority.
+ `Countdown` (which I will probably try out): I could think of using this for time management, but what was this intended to do?
+ `Pacman`: Only a minority of the users use pacman.
+ `QuickExit`: If you are mentally able to configure your WM's keyboard shortcuts, why should you ever want to use this?
+ `StockTicker`
Of course this is a bit cynical, but at the moment we don't have real stats about what qtile users use. In general: _Is it niche? __It depends.___

----------
I'd suggest:
+ Telemetry for usage stats of existing features (#1576).
+ Online polls for new features (e. g. _This could be a new feature. This is how you would use it in your config. A: Do you think that this is useful? B: Would you use it yourself?_)
+ Combining the telemetry and the poll data, we could then measure, how significant the poll results are (number of poll participants much less than the number of qtile users?)
+ Create `qtile_extras` for niche widgets and features. Because then users wouldn't have to implement everything themselves. Even if keyboard action filtering by program is niche, the WM (or the WM extras) should provide the interface to do that.

Question: What about limiting the poll to the users (with their telemetry identity)? Probably a bad idea, because the opt-out folks wouldn't have a voice. But without a check, any user or even a bot could participate in that poll. I hope that this scenario is purely theoretical because qtile users are probably more intelligent than that...

**Comment by ep12** [comment]
@airwoodix 
> @ep12 would you like to work on a PR for this?

Maybe, but at the moment there are quite a lot of open questions. Like this idea:
> That being said, I see some similarities with the float_rules of the Floating layout and would probably +1 for something that is consistent with these.

Also, I've spent a lot of time with #1657 since that inhibited my workflow significantly and also caused a bit of anger each day I logged in in the morning. Not really a good start for the day. We should definitely answer those questions before thinking about who should implement that.

**Comment by pawamoy** [comment]
`QuickExit` is useful for new users who don't remember shortcuts yet, or when your configuration has a problem: the widget is here, you can click it, it's easy. Even if I have the shortcuts and macro possible configured, I'd still appreciate being able to click to logout/shutdown/reboot :slightly_smiling_face: 

Not sure this widget allow all this though! And, maybe nobody is using it yet. It's quite recent I think.

**Comment by ep12** [comment]
9 months: 8eedc5cba5ab38. Yeah, of course `QuickExit` can be helpful. I'd really know what the criteria are for a feature to be called _niche_. If the criterion is that it must be used by the vast majority of users (like `GroupBox`, `Clock`), then there are widgets that are probably niche and that still are in `libqtile`. I would really like to get those criteria clarified by all the official Qtile members @ramnes @tych0 @zordsdavini @flacjacket @dmpayton @dequis...

**Comment by zordsdavini** [comment]
@ep12 I could try to answer but I'm new member (with using Qtile for past 7 year), so other guys can disagree.
The start of Qtile was with some few guys in front by Aldo. To get understanding https://www.youtube.com/watch?v=r_8om4dsEmw
So, everybody who created something was welcomen :)
Now we have growing comunity and we don't have any organisation structure here. Yet...
We have @tych0 @flacjacket @ramnes as main architectures.
There are speaks about splitting widgets or other stuff to separate packages and as you mensioned qtile-extra is possible. Bus as you said - we need poll or telemetry to get what is used and what is not (`QuickExit` is used in default config and solved at that time problem then you can't do anything then default_config keybindings there broken, now we have config check before reload (thanks to @pawamoy), even nice notification :) )
So, we need to decide what is _niche_ feature. IMO it is feature what will be used in comunity and can't be easelly get by reusing other widgets (for simple reuse we need more documentation).
Who should decide is it _niche_? I think "architectures".
But cool stuff should not be just forgoten. If it was not accepted, it could go into git (in worse case) or better to future qtile-extra package for telemetry.
Or even better to have 3 levels: qtile (as base), qtile-extra (cool stuff), qtile-testing (bleading edge of stuff what can go into base or extra)

**Comment by zordsdavini** [comment]
p.s. I didn't follow all discussion but I was waiting for this feature (I know we have something with `when` but never tested) and I wanted to try. I see perspective for it

**Comment by zordsdavini** [comment]
p.p.s. what is _niche_? In google translate I got it as "right place to use", something positive

**Comment by ep12** [comment]
> p.p.s. what is niche? In google translate I got it as "right place to use", something positive

Google defines it as follows

>adjective: niche
    denoting or relating to products, services, or interests that appeal to a small, specialized section of the population.
    "other companies in this space had to adapt to being niche players"

But that's a qualitative definition, not a quantitative one. But setting a quantitative limit (e. g. 5 %) is arbitrary. Why not 6 %? So the qtile extras would not really require a limit that anyone would discuss. It could be large, it could be maintained mostly by the community and not the main Qtile developers......

**Comment by ep12** [comment]
Another use case is this:
`mpv` takes screenshots when `s`, `shift+s` or `ctrl+s` is pressed. When I switch between my notes and a video in `mpv`, it occasionally happens that I press `ctrl+s` to save my notes, but `mpv` is focussed at the moment. `mpv` then pollutes my home folder with screenshots which I manually have to remove. I would really like to bind a `NOP` to those shortcuts when `mpv` is focussed. But that renders the keys totally useless, because qtile now thinks that the keystroke has been handled. So the key `s` does not work in any program. It would be necessary to foward the keystroke to the focussed window if that is *not* `mpv`.

**Comment by gmjain** [comment]
Native support for per application keybindings would be pretty cool and I definitely see a use case for it. It could also be one more power-user feature that distinguishes qtile from other WMs. :-)

Meanwhile, I'm using this to achieve exactly that. It works pretty well!
https://github.com/mooz/xkeysnail

**Comment by ep12** [comment]
> Native support for per application keybindings would be pretty cool and I definitely see a use case for it. It could also be one more power-user feature that distinguishes qtile from other WMs. :-)
> 
> Meanwhile, I'm using this to achieve exactly that. It works pretty well!
> https://github.com/mooz/xkeysnail

Uh that looks nice indeed! Although I don't like the idea of having two systems for keybindings. That quickly goes out of control and becomes a mess I suppose...
