### ISSUE TITLE
Scratchpads windows are lost when restarting

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1663]
# Issue description

Qtile appears not to keep track of scratchpad windows when restarting so calling the scratchpad windows after restarting creates duplicate instances of these programs. I don't think they are closed, as programs that want only one instance complain that they are already open.

If it is difficult to restart Qtile and keep information about running scratchpads and how they map onto the config (that may have changed), Qtile could potentially add some X property to the window and remove it again after restart. Scratchpads that are no longer in the config could be plunked on the first desktop for the user to deal with.

I'm happy to work on a solution after confirmation :) 

# Qtile version

9ed2449

# Configuration

E.g.:
```
groups.extend([
    ScratchPad("scratchpad", [
        DropDown("tmux", "xterm -e tmux", height=0.4, on_focus_lost_hide=False, opacity=1)
    ]),
])
```

**Comment by m-col** [comment]
I searched to find this issue already, because it surprises me that it hasn't already been posted. Sorry if I missed it!

**Comment by tych0** [comment]
On Wed, Apr 22, 2020 at 07:41:15AM -0700, m-col wrote:
> I searched to find this issue already, because it surprises me that it hasn't already been posted. Sorry if I missed it!

Yeah, scratchpad should probably set some atom and look for that atom
on restart.

**Comment by m-col** [comment]
Alright cool - I'll look into this then.

**Comment by zordsdavini** [comment]
@m-col can you do something like common state storage, because there are a lot of objects what could use that, ex. pomodori widget current state, I have bar show/hide state. Maybe layout window positions could be saved, too

**Comment by tych0** [comment]
We still have QtileState right? Sorry, I forgot about it :-)

**Comment by m-col** [comment]
Yeah that sounds useful

**Comment by m-col** [comment]
#1717 closes this
