### ISSUE TITLE
Ubuntu 20.04: Unable to locate package qtile

### ISSUE THREAD

**Issue by PeterSR** [qtile/qtile#1671]
Following the [latest docs](http://docs.qtile.org/en/latest/manual/install/ubuntu.html) to install on Ubuntu 20.04:

```shell
$ sudo apt install qtile   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qtile
```

Prior I ran 

```shell
$ sudo apt update   
Hit:1 http://dk.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://dk.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://dk.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

Has the package been removed from the default package lists of Ubuntu 20.04? Should the docs be updated? 

Installing from source should be no problem, I just wanted to make sure I am not doing anything incorrectly.

**Comment by tych0** [comment]
On Fri, Apr 24, 2020 at 07:40:25AM -0700, Peter Severin Rasmussen wrote:
> Following the [latest docs](http://docs.qtile.org/en/latest/manual/install/ubuntu.html) to install on Ubuntu 20.04:
> 
> ```shell
> $ sudo apt install qtile   
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package qtile
> ```
> 
> Prior I ran 
> 
> ```shell
> $ sudo apt update   
> Hit:1 http://dk.archive.ubuntu.com/ubuntu focal InRelease
> Hit:2 http://dk.archive.ubuntu.com/ubuntu focal-updates InRelease
> Hit:3 http://dk.archive.ubuntu.com/ubuntu focal-backports InRelease
> Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> ```
> 
> Has the package been removed from the default package lists of Ubuntu 20.04? Should the docs be updated? 
> 
> Installing from source should be no problem, I just wanted to make sure I am not doing anything incorrectly.

Yes, looks like it was dropped from Focal. The packages were quite
old, so that's probably reasonable on their part.

Do you want to send a patch for the docs? Otherwise I can.

**Comment by PeterSR** [comment]
I would love to give it a shot. 

I came from Arch Linux to Ubuntu 20.04, exploring alternatives to i3. In Ubuntu, it seems that snaps are the new hot thing. Is that something Qtile should explore?

**Comment by tych0** [comment]
On Fri, Apr 24, 2020 at 07:54:57AM -0700, Peter Severin Rasmussen wrote:
> I would love to give it a shot. 
> 
> I came from Arch Linux to Ubuntu 20.04, exploring alternatives to i3. In Ubuntu, it seems that snaps are the new hot thing. Is that something Qtile should explore?

Sure, if there's someone willing to do the work :)

**Comment by PeterSR** [comment]
Of course :) 
I have no experience with that and is still in the exploration phase of a new tiled window manager, but if I decide to go with Qtile, I will not rule it out, as it could be a good learning experience.

I will create a pull request for the docs shortly.

**Comment by tych0** [comment]
On Fri, Apr 24, 2020 at 08:07:58AM -0700, Peter Severin Rasmussen wrote:
> Of course :) 
> I have no experience with that and is still in the exploration phase of a new tiled window manager, but if I decide to go with Qtile, I will not rule it out, as it could be a good learning experience.
> 
> I will create a pull request for the docs shortly.

Cool, thanks!
