### ISSUE TITLE
qtile version

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1681]
As we ask users to say version during posting new issue, it would be better to have git version included. Especially in latest version.
It could be in format: 
```
$ qtile --version
0.15.0 (3449.01b0bc06)
```

**Comment by tych0** [comment]
It's not clear to me how to get setuptools to do this, but yes, that would be great.

**Comment by airwoodix** [comment]
What about [setuptools_scm](https://pypi.org/project/setuptools-scm/)? You get something like ``0.15.1.dev59+gde942288`` for the test code airwoodix@de94228 (so 59 commits past the last tag `0.15.1`, versioned with git, SHA ``de942288``). The output is in principle customizable but there's sort of a standard.

**Comment by zordsdavini** [comment]
I think @airwoodix given `setuptools_scm` is the way to go.
