### ISSUE TITLE
IntelliJ IDEs (Android Studio etc.) fail to get focus for keyboard

### ISSUE THREAD

**Issue by tuomas2** [qtile/qtile#1683]
# Issue description

1. Start Android Studio and open some text file 
2. Click text with left mouse button to get focus
3a. Try to type
Actual: no text appears. Text cursor is not visible.
Expected: text appears

Seems to be issue related to left mouse clicking, as I get focus like this:
2. Click with right mouse button -> context menu appears
3. Click with left mouse button from text 
  -> text cursor appears 
      text appears when typing

# Qtile version

0.15.1

**Comment by ramnes** [comment]
Hello @tuomas2! Yes, this is a very discussed issue at the moment. See #1548. Closing in favor of this other one.
