### ISSUE TITLE
review default layout

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1707]
This is part of Plans for default config improvements #1582
_Just wanted to separate for clear discussion._
I'd suggest switch to Max and Columns. Columns has same functionality as Stack but more possibilities.
But only difference is that stack layout with filled 1 stack, other will leave empty. The problem is for idea to start default config with open terminal. If we will have columns/max layout then all screen will be filled. With stack/max you can get filled half of window. Solution could be start new terminal as floated.

**Comment by ramnes** [comment]
#1741 got merged :)
