### ISSUE TITLE
Current desktop not properly set when switching to a group on another screen

### ISSUE THREAD

**Issue by dbistriceanu** [qtile/qtile#1712]
If i just move the mouse between monitors, the group on the screen from the new monitor does get focus but something's not being set properly and `rofi -modi windowcd -show windowcd` still shows the windows from the previously active group.

However, if I manually click on the currently active group displayed in the GroupBox widget then everything works as expected afterwards and the windows from that group are shown by the same rofi command that I have bound to _alt-`_.

So it seems to me that this is an issue with how qtile handles changing the current desktop when switching focus to a group on another screen and not something wrong with rofi itself.

I'm still on version 0.14.2 because the latest one still doesn't play nice with jetbrains products I use for work everyday.

**Comment by tych0** [comment]
Does the above PR fix it?

**Comment by dbistriceanu** [comment]
Seems to have done the trick. Thanks!
