### ISSUE TITLE
Example Please : mouse_callbacks{}

### ISSUE THREAD

**Issue by 20jam** [qtile/qtile#1713]
https://github.com/qtile/qtile/blob/1d7b4c5a35310c6fdaa5239f7edf48588769be53/libqtile/widget/base.py#L95-L98

Say I want to spawn a terminal window with a command or dmenu

Thanks

**Comment by tcld** [comment]
Is this just about adding a few lines to the doc string?

I have the following in my config, would that do?

```
def open_calendar(qtile):  # spawn calendar widget
    qtile.cmd_spawn('gsimplecal next_month')

def close_calendar(qtile):  # kill calendar widget
    qtile.cmd_spawn('killall -q gsimplecal')

# add widget with callbacks somewhere

widget.Clock(format='%Y-%m-%d %a %H:%M', mouse_callbacks={'Button1': open_calendar, 'Button2': close_calendar})
```

**Comment by m-col** [comment]
I'll update the docstring to show an example. @tcld is it OK if I use your spawn example?

**Comment by tcld** [comment]
Sure, feel free, then I won't have to add it myself. :)

**Comment by m-col** [comment]
We can close this (#1728)

**Comment by 20jam** [comment]
Thanks for the help, It is very appreciated. Sometime is difficult for us non python developer to look for answer in source code, examples are very useful.

**Comment by m-col** [comment]
No worries at all :)
