### ISSUE TITLE
Tasklist icon placement 

### ISSUE THREAD

**Issue by am01k01h3** [qtile/qtile#1714]
I can't seem to get the icons & text placed in the center vertically in the tasklist.

If the text is placed vertically center (by setting padding = 8), then the icon is chopped off like in the picture. 
![Screenshot from 2020-05-08 22-42-28_2](https://user-images.githubusercontent.com/62161236/81462010-a85f9f80-917d-11ea-86ca-cb2b6845884c.png)

if I adjust padding to 0, so that the icon is centerd, the text goes all the way up.

![Screenshot from 2020-05-08 22-49-50](https://user-images.githubusercontent.com/62161236/81462152-68e58300-917e-11ea-8d35-fe96a8c5741d.png)

Is this a bug?

qtile version 0.15.0
[config.py.txt](https://github.com/qtile/qtile/files/4602520/config.py.txt)

**Comment by am01k01h3** [comment]
Some observations:
I'm really just trying to make text and icon vertically centered in the bar and it seems like this is the default behavior for other widgets. But for tasklist, icon and text are vertically aligned to top edge.

With padding=0, the rectangle box around text becomes small/tight and vertically aligned to top.
Icon placement works correctly with padding=0.

With padding=8, the text becomes centered correctly. But it adds padding to the icons on all directions, and pushed it down (especially if I set the icons to a large size over 24 pixels).

Groupbox or Graph widgets seem to not have this issue, text or graphs are always vertically aligned to center, unless overridden with margin_y.

**Comment by M05QU170** [comment]
did you try to change icon size in widget.tasklist section? And try to play with font size if this will not workout

**Comment by am01k01h3** [comment]
> did you try to change icon size in widget.tasklist section? And try to play with font size if this will not workout

Yes, my qtile config is posted above.
My current workaround is to use font size 10 which is same as all other widgets, icon size 20, padding 8 and everything is sort of centered correctly. The issue I've raised is that if we use icon size larger than 24 it starts to show the behaviour I mentioend above.

**Comment by DeeeeLAN** [comment]
This is still a valid issue, the tasklist top-aligns the icon and text which is not very flexible. I think either center-align both, or have separate padding values for the icon and the text would work fine.

**Comment by ezntek** [comment]
the issue still exists.

this is what it looks like with the following:
```py
# snip
margin_x=12,
margin_y=8,
padding=3,
icon_size=16,
```

![Screenshot_2023-07-08_20-09-50](https://github.com/qtile/qtile/assets/79492706/c3190df1-c4e5-46d3-b08d-977c29864276)


and this is what it looks like with the following (my preferred size):
```py
# snip
margin_x=12,
margin_y=8,
padding=3,
icon_size=26,
```
![Screenshot_2023-07-08_20-12-02](https://github.com/qtile/qtile/assets/79492706/5a6cb1f9-7bc6-4f55-8ec0-2fc95973c64c)

it appears so that qtile is trying to center the icon from the top of the icon, not the icon size divided by two on the y axis.
