### ISSUE TITLE
Make hooks arguments more sensible

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#1719]
A lot of the hooks fire and don't have any context for what actually changed when they fire. We have various commits (ac2346a26b39ccff69af13b80def7e94857f9e8f for #1341 or example) that add relevant context, we should do that everywhere.

**Comment by m-col** [comment]
Many of the hooks currently pass context-specific arguments, some of which couldn't otherwise be determined (e.g. `selection_change`, `screen_change`). I guess this means that all hooks would receive one argument (`qtile`) and some would have a second, context-specific argument. Is this the desired way to approach this? I don't think there would be a way to send all hooked funcs the same number of arguments, which would be super neat.

**Comment by tych0** [comment]
Yeah, I think "do whatever makes sense" should be the guiding principle. It seems reasonable to *always* pass the qtile object just because people may want to do arbitrary stuff, but any additional arguments based on context could/should also be passed. I don't think there's a reason to try and unify the arguments passed, as they may differ based on context.

**Comment by m-col** [comment]
[Looks like](https://github.com/qtile/qtile/blob/master/libqtile/hook.py#L45) the qtile object is available at `hook.qtile` as an importable. I can't find any reference to `hook.qtile` in libqtile... is it old, vestigial code? We could either use that copy, fire hooked functions with `i(qtile, *args, **kwargs)` and remove the qtile argument from any hooks that currently pass the qtile object, or alternatively we could remove that global (unless it's used somewhere else) and pass `qtile` manually to all `hook.fire` calls. I like the idea of the qtile being 'implied' and passed as part of the hook mechanism automatically, but like many I've had a dislike for "global" drilled into me. What do you think?

**Comment by tych0** [comment]
Oh, interesting. Maybe we should just rely on that vs. arguments? People could also keep track of it via `main()` if they wanted. (Maybe the above is a reason to get rid of `main()`?)

**Comment by m-col** [comment]
Depending on how/if #1751 progresses `main` might not be required and `qtile` might be accessible from somewhere that isn't `libqtile.hook.qtile`. `libqtile.hook` seems like an odd place to import qtile from. Although perhaps that is a different conversation... not having to pass `qtile` around when firing hooks would be nice so I'll make change and we can then reassess.

**Comment by tych0** [comment]
On Mon, Jun 22, 2020 at 09:16:58AM -0700, m-col wrote:
> Depending on how/if #1751 progresses `main` might not be required and `qtile` might be accessible from somewhere that isn't `libqtile.hook.qtile`. `libqtile.hook` seems like an odd place to import qtile from. Although perhaps that is a different conversation... not having to pass `qtile` around when firing hooks would be nice so I'll make change and we can then reassess.

Yeah, maybe we can move it to somewhere like libqtile.core.qtile or
something?

**Comment by m-col** [comment]
This was meant to be closed when we merged #1791
