### ISSUE TITLE
Bar Background Opacity

### ISSUE THREAD

**Issue by am01k01h3** [qtile/qtile#1722]
Using version 0.15.1,
Bar Opacity applies to the whole bar including the objects which are on the bar. If you set opacity to 0, the whole bar would become completely invisible. 

The more common/expected behavior for opacity is to apply it only to the background and not to the objects.  So, if Opacity was set to 0, it would result in a fully transparent bar, but the objects are still visible.

**Comment by ramnes** [comment]
Yes. IIRC we already have some discussion on this issue somewhere but I could not find right now.

**Comment by am01k01h3** [comment]
After I posted this, I did find some old threads, let me link them here.

Completely transparent bar background ? #1320
https://github.com/qtile/qtile/issues/1320

Bar with transparency redraw issue #1059
https://github.com/qtile/qtile/issues/1059

Incorrect behaviour of alpha channel in Bar background #900
https://github.com/qtile/qtile/issues/900

**Comment by jackiboi307** [comment]
this still happens for me 2021. just installed arch and qtile so im not on an outdated package

**Comment by Zeus07298101** [comment]
> this still happens for me 2021. just installed arch and qtile so im not on an outdated package

Yeah, I'm also still experiencing it too, I can only go down to about opacity = 0.8 otherwise widgets start getting hard to read.

**Comment by ramnes** [comment]
Have a look at #2513

**Comment by elParaguayo** [comment]
#2513 merged. Closing.
