### ISSUE TITLE
Missing content on docs.qtile.org

### ISSUE THREAD

**Issue by tcld** [qtile/qtile#1731]
The documentation for extensions and widgets seems to be missing from http://docs.qtile.org/en/latest/manual/ref/extensions.html since today.

# Qtile version

I am fairly sure that the documentation was still working yesterday, at the very least the day before.

Can andybody confirm this?

**Comment by tych0** [comment]
On my phone right now, but it looks like builds should be working:

https://readthedocs.org/projects/qtile/builds/
