### ISSUE TITLE
Hiding the qtile bottom bar (libqtile.bar)

### ISSUE THREAD

**Issue by dopimoon** [qtile/qtile#1734]
Is it possible to hide the bottom bar of qtile. I was reading documentation and tried searching but didn't find any answer.

`qtile verison = 0.15.1`
`distro manjaro`

**Comment by ramnes** [comment]
Of course! Just remove the `bottom=bar.Bar(...)` from your configuration (located in `~/.config/qtile/`), in the screen definition.

**Comment by dopimoon** [comment]
I have removed that line of code from start even removed bar and widgets from import but didn't worked.

**Comment by ramnes** [comment]
Oh, it's because you don't have the `screens` variable defined, so the default one (which includes a bottom bar) is being used.

**Comment by zordsdavini** [comment]
Example (with ExKeys):
```
<...>
keys = [
    <...>
    EzKey("M-C-x", lazy.hide_show_bar("bottom"), desc='toggle bottom bar'),
    <...>
]

bottom = bar.Bar(
    [ <list of widgets> ], 24
)

screens = [
    Screen(top=top, bottom=bottom),
]

@hook.subscribe.startup
def startup():
    bottom.show(False)
```
