### ISSUE TITLE
[Feature request] Combining windows into tabbed window?

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#1739]
I came across this cool xmonad feature where you can push windows together into a subLayout, in this case a tabbed layout:
[https://youtu.be/70IxjLEmomg?t=319](https://youtu.be/70IxjLEmomg?t=319)

This would be an incredibly useful feature for qtile. Definitely for smaller screens such as on laptops where space is scarce. As an example I often work with multiple browsers, one for normal use and the others for development and testing. This would come in very handy as I could simply stack them in one tabbed window. 

Is there some way to do this in qtile? And if not what would be a good place to start to develop?

**Comment by cubimon** [comment]
I am still very new to qtile, but isn't this behavior similar to the max or zoomy layout? The max layout doesn't show any tab info, while the zoomy layout shows all windows in a small vertical bar

**Comment by tamis-laan** [comment]
Not really you can use for example a zoomy layout but then all windows will be using the zoomy layout. If you watch the video you can see that he is merging two windows inside a column layout into one container with a tabbed layout.

**Comment by cubimon** [comment]
I am used to this in i3wm and couldn't figure out how to get the same behavior in qtile so far. Basically the space is divided into a tree and each node is either a layout or window, like this:

```
vertical layout -  terminal 1
                -  max layout  - terminal 3
                               - terminal 4
                -  terminal 2
```

while left is the top of the tree and most right are windows/leaves.
Anyway I found on github a project called qtile-plasma which provides this mostly, but I guess no tabs. Also it hasn't been updated for almost a year. 

By not providing this dynamic behavior a user probably has to predefine the location of each window by creating e.g. a layout, so you can simply open your workspace/application and it is located where it should be and the user doesn't have to mess with the layout. Idk I am also a bit confused on how to use qtile properly.

**Comment by tamis-laan** [comment]
Well qtile is a list based tiling window manager and not a tree based tiling window manager like i3. Instead of manually defining a tree of splits qtile uses predefined layouts. This makes things easier in the sense you don't need to manually layout everything and you can easily switch between layouts. However it comes at a cost in terms of flexibility. Creating a tabbed container is something you could easily do in i3 I imagine. 

It would be nice to have a single tabbed container container you could throw windows into but turning qtile in a tree based window manager is probably not what most people have in mind.

**Comment by tych0** [comment]
The slice layout shows examples of fallback layouts.

I also don't think it would be too hard to build an abstraction for doing this; just have the layouts operate on Windowish objects, which are a proxy for either a real X11 window or a different layout. Then the layouts need to respect where they've been .place()d, instead of just using the whole screen. The real challenge would be migrating all the layouts to this framework.

**Comment by ramnes** [comment]
Did you see the `toggle_split` function of layouts `Stack`, `Columns` and `Bsp`? It seems really close to what you're looking for.

**Comment by tamis-laan** [comment]
Indeed this toggle_split functionality seams close! But it's not exactly what I'm looking for as I'm stuck to that particular layout. 

As an example I'm using MonadWide to have a browser open in the master area and a terminal in the lower area. Let's say I'm developing something for chrome and firefox. This means that one of the browsers wil be in the master area and the browser is in the a smaller window down below. In order to check my work in both browsers I wil need to switch the small windowed browser with the master windowed browser. 

It would be much nicer if I could do a merge operation where both browsers are combined into one tabbed window in the master area. A split operation would then put both browsers back into separate windows. 

It would be like the toggle_split functionality but more generic.

**Comment by tamis-laan** [comment]
> The slice layout shows examples of fallback layouts.

Not sure I tried using the Slice layout but it seams broken #1470.

**Comment by thales-maciel** [comment]
I've been trying to achieve this too, It's my most wanted feature by far. Maybe using tabbed (by suckless) would help for now, but I didn't got any lucky with It also.

**Comment by tamis-laan** [comment]
Hey, yeah I already tried this using tabbed but qtile is not a window manager that uses parenting thus it's not really possible. I was working on an implementation inside qtile itself together with @m-col. We created a buggy hack that implements this feature but some of the core functionality has to be changed in order to make it work proper. 

If you want to give it a shot with us come over on IRC ( irc://irc.oftc.net:6667/qtile )  and we can give you the code so far. Maybe the 3 of us can build something proper.

**Comment by jwijenbergh** [comment]
> Hey, yeah I already tried this using tabbed but qtile is not a window manager that uses parenting thus it's not really possible. I was working on an implementation inside qtile itself together with @m-col. We created a buggy hack that implements this feature but some of the core functionality has to be changed in order to make it work proper.
> 
> If you want to give it a shot with us come over on IRC ( irc://irc.oftc.net:6667/qtile ) and we can give you the code so far. Maybe the 3 of us can build something proper.

Do you still have the code for this?

**Comment by tamis-laan** [comment]
@jwijenbergh  I'm afraid I wiped my system and the experiments. Maybe @m-col still has the code on his machine.

**Comment by m-col** [comment]
Thought it'd be in my gists but apparently not, so not sure I do have it sorry.

**Comment by jwijenbergh** [comment]
Ah okay I will see if I can implement something like this, it would be a lot of changes though I assume. Maybe we could just try to fix the Slice layout
