### ISSUE TITLE
Can't set background in image widget

### ISSUE THREAD

**Issue by Ayush1325** [qtile/qtile#1742]
So I am trying to set the background of a widget in png image but it just doesn't seem to work. Here is the code I am using:
```python
widget.Image(filename="~/.config/qtile/icons/updates.png",
                                 background=colors["highlight"], margin=4),
```
It works fine on text and other widgets. Just doesn't seem to work with images. Any idea what might be the problem here?

**Comment by ramnes** [comment]
What version of Qtile?

Did you see #1385?

**Comment by Ayush1325** [comment]
I didn't quite understand:

> Fixed, as long as you give the background argument to the Image object. As @tych0 explained, it will fallback to the bar color.

If the background argument is not the way to specify a custom background color for a transparent image, then what is?

**Comment by Ayush1325** [comment]
> What version of Qtile?
> 
> Did you see #1385?

My version of qtile is : 0.15.1

**Comment by ramnes** [comment]
The background argument *is* the way to specify the background color, it's just that it didn't work before the commit mentioned in that issue. :)

IIRC this commit came after 0.15.1 though. Can you try the current master branch?

**Comment by Ayush1325** [comment]
Sure, will checkout if it works on master.

**Comment by Ayush1325** [comment]
> The background argument _is_ the way to specify the background color, it's just that it didn't work before the commit mentioned in that issue. :)
> 
> IIRC this commit came after 0.15.1 though. Can you try the current master branch?

Yup, works on master, just tried it with xephyr.

**Comment by ramnes** [comment]
Great!
