### ISSUE TITLE
/usr/lib/Xorg uses a lot CPU

### ISSUE THREAD

**Issue by M05QU170** [qtile/qtile#1744]
# Issue description
![ArchLabs-02-1920x1080](https://user-images.githubusercontent.com/41060362/82707985-1f646000-9c75-11ea-8835-22ff435040af.png)
For some reason /usr/lib/Xorg uses a lot CPU its jumping from 10% to 20%. I noticed that it's only in qtile session. I tried to disable all widgets which might use CPU still the same. I wonder anyone else noticed this ?

# Qtile version
0.15.1

# Stack traces

# Configuration

[config.py.txt](https://github.com/qtile/qtile/files/4670318/config.py.txt)

**Comment by tych0** [comment]
Seems like #1682

**Comment by ramnes** [comment]
Can you try the master branch @M05QU170?

**Comment by M05QU170** [comment]
> Can you try the master branch @M05QU170?

Sorry for noobish question, but what do you mean by that?

**Comment by ramnes** [comment]
I'm asking you to try the unreleased version of Qtile (i.e. the current state of the "master" branch of the our git repository). The steps to install Qtile from sources, assuming that you already have the dependencies installed, are explained here: http://docs.qtile.org/en/latest/manual/install/#qtile

**Comment by M05QU170** [comment]
I can confirm that caused by widget.keyboardlayout. When i removed it everything back to normal. I will try with master branch version.

**Comment by ramnes** [comment]
Great! I'll go ahead and close this issue, assuming that it has been fixed already. Feel free to comment if it needs to be reopened. :)
