### ISSUE TITLE
Thoughts on configuration and remote scriptability

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1751]
Difficulties to play with the different Qtile objects such as in #1748 make me think that we could greatly improve the user experience by having a global `qtile` object and play with it, à la `current_app` in Flask. Something like:

```python
from libqtile import qtile

qtile.keys = [...]
```

This would make the configuration file radically different and a lot of things would have to be changed in the codebase, but I think it would increase the hackability of Qtile by an order of magnitude. And we could drop that `main()` hack.

If we push this one step further, we could make this `qtile` object remotely available and this would make the remote scriptability much simpler, because you could then import that global object in any Python shell and play with it, and you wouldn't have to use the command clients anymore, which I feel are an unnecessary abstraction over the manager from the user perspective, and yet another thing to understand and master.

I guess we will come back to a chicken and eggs problem on the implementation, but before we get into that I'd love to hear everyone's thoughts on the observation and idea.

**Comment by zordsdavini** [comment]
I'd like to see no differencies between internal and external scripting. Maybe `qshell` will become needless, because in `ipython` I could just import `qtile` and play around.
I support this for simplicity.

**Comment by zordsdavini** [comment]
And it is still time to do that before 1.0 Qtile release ;)

**Comment by Craksy** [comment]
This would be great. i'll admit, i'm a bit of a noob. I'm sort of getting the hang of how the qtile instance is being exposed by now, but it is all quite confusing if you're just starting out.
when i was first exploring and playing around, directly importing qtile was one of the first things i tried.
for what it's worth i think this and #1791 would make things much more intuitive and approachable, especially for beginners.

**Comment by ramnes** [comment]
[rlpython](https://github.com/fscherf/rlpython) looks like a good pretender for a future qtile-shell that looks a bit more like a normal shell
