### ISSUE TITLE
@hook.subscribe.layout_change never invoked?

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#1753]
I'm trying to detect when I'm in the Max layout so I can hide the qtile bar. I'm trying to do this in the following way:
```python
@hook.subscribe.layout_change
def layout_change(layout,group):
    if(layout.name == 'max'):
        layout.screen.bar.size = 0
        layout.screen.bar.window.hide()
    else:
        layout.screen.bar.size = 100
        layout.screen.bar.window.show()
```
Everything runs fine, no failures no crashed but the bar stays the same. So I'm guessing the hook is never invoked? I

t's difficult to so say as I find debugging qtile extremely hard there is for example as far as I know, no way to trace thing with a print statement.  Or to invoke qtile in a way I can see trace information without restarting the whole window manager.

**Comment by ramnes** [comment]
Print statements will not end up in your logs but will still end up somewhere, depending on how you installed Qtile. That being said, the simpler route is to use Qtile's own logger inside your configuration, and optionally change the log level. For example: https://github.com/ramnes/qtile-config/blob/master/config.py#L287-L291 You can also set the log level from the command line directly with `qtile-cmd -o cmd -f debug`.

**Comment by tych0** [comment]
On Wed, May 27, 2020 at 05:31:58AM -0700, Tamis wrote:
> I'm trying to detect when I'm in the Max layout so I can hide the qtile bar. I'm trying to do this in the following way:
> ```python
> @hook.subscribe.layout_change
> def layout_change(layout,group):
>     if(layout.name == 'max'):
>         layout.screen.bar.size = 0
>         layout.screen.bar.window.hide()
>     else:
>         layout.screen.bar.size = 100
>         layout.screen.bar.window.show()
> ```
> Everything runs fine, no failures no crashed but the bar stays the same. So I'm guessing the hook is never invoked? I
> 
> t's difficult to so say as I find debugging qtile extremely hard there is for example as far as I know, no way to trace thing with a print statement.  Or to invoke qtile in a way I can see trace information without restarting the whole window manager. 

Any prints should be seen in ~/.xsession-errors, and both that file
and ~/.local/share/qtile/qtile.log, as noted in the issue template :)

The hook should be invoked, you can try confirming with the debuginfo
widget.

**Comment by tamis-laan** [comment]
FOR OTHERS AND FUTURE REFERENCE 

The `~/.local/share/qtile/qtile.log` file contains errors and printouts from `logger.debug()`. 

I set qtile to debug mode on after startup:
```python
# Post-startup script hook
@hook.subscribe.startup_complete
def post_startup():
    os.system('qtile-cmd -o cmd -f debug')
```

I created a debug scratchpad:
```python
scratchpad = ScratchPad("scratchpad", [
    DropDown("debug", "termite -e 'tail -f .local/share/qtile/qtile.log'", #Change termite to your terminal
                x=0.05, y=0.05, width=0.9, height=0.9, on_focus_lost_hide=False),
)]
```
Triggered with key:
```python
    Key([mod1], 'd', lazy.group['scratchpad'].dropdown_toggle('debug')),
```

**Comment by tamis-laan** [comment]
Oke so this debugging works, the problem is:
AttributeError: MonadWide has no attribute: screen
i.e.
`layout.screen` does not exists, although the command API http://docs.qtile.org/en/latest/manual/commands/index.html 
tells me layout should hold a reference to screen? 

I have tried to play with the command API by following the examples in the docs but I think they are out of date? 

running: 
```python 
from libqtile.command_client import InteractiveCommandClient
c = InteractiveCommandClient()
```
produces:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-24f674ade6cc> in <module>
      1 from libqtile.command_client import InteractiveCommandClient
----> 2 c = InteractiveCommandClient()

TypeError: __init__() missing 1 required positional argument: 'command'
```

**Comment by tych0** [comment]
Yeah, I think that doc is just wrong. Layouts can sort of do whatever they want, we haven't taken the time to normalize the code in any significant way, unfortunately.

**Comment by tamis-laan** [comment]
This is still a problem...

**Comment by ramnes** [comment]
Hey @tamis-laan, I'm going to close this issue, because `@hook.subscribe.layout_change` works as expected (I just tried again to make sure). For the screen reference in the MonadWide layout, what you're looking for is `layout.screen_rect`. It was named screen before but that was confusing because that term was used for different types of variables. See PR #1838.
