### ISSUE TITLE
Focus follows mouse when disabled and Emacs doesn't focus

### ISSUE THREAD

**Issue by brandonwillard** [qtile/qtile#1754]
# Issue description.

I just pulled the current master branch (i.e. 7b43c9f) and now the focus follows my mouse even though `follow_mouse_focus = False` in my config, and I cannot give Emacs focus using `lazy.layout.[up|down]` in `MonadTall`.

If I revert the changes introduced in 7af310b1, everything seems to work again.

# Qtile version

7b43c9f

# Configuration

[`qtile-config.py`](https://gist.github.com/brandonwillard/b6406d69fc7fbb80e6d5afe2c456ddcc)

**Comment by tych0** [comment]
On Wed, May 27, 2020 at 07:02:00PM -0700, Brandon T. Willard wrote:
> # Issue description.
> 
> I just pulled the current master branch (i.e. 7b43c9f) and now the focus follows my mouse even though `follow_mouse_focus = False` in my config, and I cannot give Emacs focus using `lazy.layout.[up|down]` in `MonadTall`.
> 
> If I revert the changes introduced in 7af310b1, everything seems to work again.
> 
> # Qtile version
> 
> 7b43c9f
> 
> # Configuration
> 
> [`qtile-config.py`](https://gist.github.com/brandonwillard/b6406d69fc7fbb80e6d5afe2c456ddcc)

Yeah, focusing in master is not quite correct. I am working on a patch
to fix it.

**Comment by tych0** [comment]
See #1760, can you test with that?

**Comment by brandonwillard** [comment]
Just tried: looks like it does fix both issues.

This is probably unrelated, but I just noticed that if I click a Chrome link on an unfocused window on another screen (and in another group), the active screen will switch to the group with Chrome in it.

**Comment by tych0** [comment]
On Sun, May 31, 2020 at 01:22:44PM -0700, Brandon T. Willard wrote:
> Just tried: looks like it does fix both issues.
> 
> This is probably unrelated, but I just noticed that if I click a Chrome link on an unfocused window on another screen (and in another group), the active screen will switch to the group with Chrome in it.

Try focus_on_window_activation = "never".

**Comment by brandonwillard** [comment]
Ah, makes sense; thanks!

**Comment by tych0** [comment]
Gonna close this since the fix was merged, thanks for the report!
