### ISSUE TITLE
Chromium icon not getting in systemtray

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1757]
# Issue description

The chromium icon is not getting trayed 
![image](https://user-images.githubusercontent.com/74574/83228139-1b7e9380-a1c9-11ea-91cd-3034220b239e.png)

# Qtile version

# Stack traces

# Configuration

**Comment by nushankodikara** [comment]
The issue is present with all the chromium-based browsers, regardless of the configuration.

**Comment by jagguli** [comment]
Not happening anymore closing thx.
