### ISSUE TITLE
Can't swap screens properly - focus stills on the same monitor

### ISSUE THREAD

**Issue by soulmare** [qtile/qtile#1759]
# Issue description
Can't swap screens properly. I defined a function which swaps screens on my two-monitor setup: the group of the screen-0 goes to the screen-1, and the group shown on the screen-1 beforehand, goes to the screen-0. That's ok, but focus doesn't go to another screen. For example, if focus is on the screen-0, I make swapping, and I want screen-1 to be focused after it - to continue to work with the same app. But screen-0 stills focused. I tried qtile.cmd_to_screen(1) - but it doesn't work there. The function is:

```
def swap_screens():
    def __inner(qtile):
        index = qtile.screens.index(qtile.currentScreen)
        if index < len(qtile.screens) - 1:
            index_target_screen = index + 1
        else:
            index_target_screen = 0
        qtile.screens[index].setGroup(qtile.screens[index_target_screen].group)
        qtile.cmd_to_screen(index_target_screen)
        #qtile.cmd_to_screen(1)
    return __inner
...
Key([mod], "Up", lazy.function(swap_screens())),
```

# Qtile version
0.10.7

**Comment by tych0** [comment]
0.10.7 is quite old, can you try on a more recent version?

**Comment by ramnes** [comment]
Here's what I use with the latest Qtile: https://github.com/ramnes/qtile-config/blob/47b592f736938d47f8e13d836874fc65f911f4e4/config.py#L83-L89

```python
def switch_screens():
    @lazy.function
    def __inner(qtile):
        i = qtile.screens.index(qtile.current_screen)
        group = qtile.screens[i - 1].group
        qtile.current_screen.set_group(group)
    return __inner
```

And yes, updating from 0.10.7 will most likely break your config. Have a look at the CHANGELOG before. :)

**Comment by fdev31** [comment]
It didn't look obvious at first, but I faced the same issue and created a duplicate:
https://github.com/qtile/qtile/issues/1778

I think I'm providing a bit more details on it and why, also I found a way to work around it.
We should be able to control the mouse position from qtile IMO and address such issue by "following" the window with the mouse cursor.

**Comment by fdev31** [comment]
> Here's what I use with the latest Qtile

Is the full group moving working all the time ? I think with such code I faced the same issue: the group is moved, but the focus might not be on the right screen after operations (depending on the mouse position).

**Comment by fdev31** [comment]
I really believe there is a bug here...
