### ISSUE TITLE
alacritty and kitty terminals focus is messed up

### ISSUE THREAD

**Issue by Miziak** [qtile/qtile#1762]
# Issue description
Both terminals focus is so much buggy for alacritty focus working only by mouse follow till I switch screens after this focus stop working and stay on another monitor, in kitty is similar but cannot focus another instation even by mouse. gnome-terminal work fine ;)

Reverting to https://github.com/qtile/qtile/commit/ae354a27eafda53316973f35db0363eaec686c38 fix problem

alacritty xprop:
```
WM_HINTS(WM_HINTS):
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
_NET_WM_ICON(CARDINAL) =
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 800 by 600
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLIENT_MACHINE(STRING) = "user-e5400"
_NET_WM_PID(CARDINAL) = 148565
WM_CLASS(STRING) = "Alacritty", "Alacritty"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "xprop /home/user"
WM_NAME(STRING) = "xprop /home/user"
```

kitty xprop:
```
_NET_WM_ICON(CARDINAL) = 
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON_NAME(UTF8_STRING) = "xprop /home/user"
_NET_WM_NAME(UTF8_STRING) = "xprop /home/user"
WM_LOCALE_NAME(STRING) = "pl_PL.UTF-8"
WM_CLIENT_MACHINE(STRING) = "user-e5400"
WM_ICON_NAME(STRING) = "xprop /home/user"
WM_NAME(STRING) = "xprop /home/user"
XdndAware(ATOM) = BITMAP
WM_CLASS(STRING) = "kitty", "kitty"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		window gravity: Static
WM_HINTS(WM_HINTS):
		Initial state is Normal State.
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 154832
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by tych0** [comment]
Can you bisect and see which commit causes it?

**Comment by tych0** [comment]
I mentioned this in another thread, but d58cb2dd67fbef9e6053ca658d3bf485df284a8e is suspicious.

**Comment by Jamim** [comment]
Hello @tych0,
I'll try to bisect.

Just for transparency, some related messages from other threads:
https://github.com/qtile/qtile/issues/1548#issuecomment-637674737
https://github.com/qtile/qtile/pull/1760#issuecomment-637682344

**Comment by Jamim** [comment]
> Hello @tych0,
> I'll try to bisect.

Done. You were right, d58cb2d is the first bad commit.

**Comment by tych0** [comment]
On Wed, Jun 03, 2020 at 02:28:03PM -0700, Aliaksei Urbanski wrote:
> > Hello @tych0,
> > I'll try to bisect.
> 
> Done. You were right, d58cb2d is the first bad commit.

Thanks, can you post an xtrace of xprop on one of terminals?

**Comment by Jamim** [comment]
Here you go.
[xprop-alacritty.log](https://github.com/qtile/qtile/files/4726332/xprop-alacritty.log)

**Comment by tych0** [comment]
On Wed, Jun 03, 2020 at 02:40:20PM -0700, Aliaksei Urbanski wrote:
> Here you go.
> [xprop-alacritty.log](https://github.com/qtile/qtile/files/4726332/xprop-alacritty.log)

Awesome, thank you.

So it looks like alacritty is not setting the input hint, so we should
not be unsetting it. Should be a reasonably simple fix... :)

**Comment by tych0** [comment]
Can someone test the above PR and reply there? I think this should be fixed.

**Comment by Jamim** [comment]
> Can someone test the above PR and reply there? I think this should be fixed.

I'm glad to confirm that with #1763 (on 52366ff) the qtile focuses well on the alacritty, kitty, and keepassxc :rocket:

**Comment by tych0** [comment]
Excellent, thanks :)

**Comment by Miziak** [comment]
Confirm! it's working on mentioned branch ;)
