### ISSUE TITLE
How to move to the group which has matched ?

### ISSUE THREAD

**Issue by dhaval15** [qtile/qtile#1765]
How can I move to specific group for which a new client has matched ?

**Comment by fdev31** [comment]
Keep track of new clients with a hook...
then add a key to go to the group of this client ?

**Comment by dhaval15** [comment]
I want to go to matched client automatically not manually, can you tell me how can I achieve this.

**Comment by fdev31** [comment]
By removing your current group matching and replacing it by something similar can work (I didn't test it):
```python
automoved_apps = {
        'skype'              : groups_by_id.chat.name,
        'Blender'            : groups_by_id.gfx.name,
        'Popcorn-Time'       : groups_by_id.media.name,
        'TermLog'            : groups_by_id.logs.name,
        'zim'                : groups_by_id.rec.name,
        'Evolution'          : groups_by_id.mail.name,
        }

@hook.subscribe.client_new
def hook_move_to_group(client):
    for wm_class in client.window.get_wm_class():
        group = automoved_apps.get(wm_class, None)
        if group:
            client.togroup(group)
            qtile.current_screen.set_group(group)
            break
```
You may want to replace `automoved_apps` content of course, and using your group's names.

**Comment by dhaval15** [comment]
Thanks , this works.

**Comment by fdev31** [comment]
@ramnes @dhaval15 do you think marking new clients which are moved as urgent would do the trick ? (then you can chose to follow the window or not).
I personally like the current behavior but this could be a configuration flag... (to mark as urgent the new clients which are moved to a group which has no screen)
