### ISSUE TITLE
Does Qtile supports window swallowing? If not I'm making a request!!!!

### ISSUE THREAD

**Issue by Godnyx** [qtile/qtile#1771]
So I watched a video from Luke Smith and he shows how his DWM has a great feature called "window swallowing". It actually "swallows" your terminal window when opening apps so it's not in the screen and when you close your app is there again!

If you didn't understand what I'm talking about? Check [this](https://www.youtube.com/watch?v=92uo5OBOKfY) video. He demonstrates the "problem" at 0:30 and shows how it's config works at 2:30. 

If that's not able to be done in Qtile that I want to make a request to add it. You don't have to do it of course but it would be nice.

**Comment by ramnes** [comment]
We don't have this but that would be really nice indeed! Pull request welcome. :)

**Comment by m-col** [comment]
Wouldn't this be achieved with a stacking layout?

**Comment by michalszymura** [comment]
> Something like this?
> 
> ```python
> import psutil
> 
> @hook.subscribe.client_new
> def _swallow(window):
>     pid = window.window.get_net_wm_pid()
>     ppid = psutil.Process(pid).ppid()
>     cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
>     for i in range(5):
>         if not ppid:
>             return
>         if ppid in cpids:
>             parent = window.qtile.windows_map.get(cpids[ppid])
>             parent.minimized = True
>             window.parent = parent
>             return
>         ppid = psutil.Process(ppid).ppid()
> 
> @hook.subscribe.client_killed
> def _unswallow(window):
>     if hasattr(window, 'parent'):
>         window.parent.minimized = False
> ```

Thanks a lot. It works with mpv, vlc, ristretto. But i have trouble to make it work with sxiv. Any ideas?

**Comment by Godnyx** [comment]
> > Something like this?
> > ```python
> > import psutil
> > 
> > @hook.subscribe.client_new
> > def _swallow(window):
> >     pid = window.window.get_net_wm_pid()
> >     ppid = psutil.Process(pid).ppid()
> >     cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
> >     for i in range(5):
> >         if not ppid:
> >             return
> >         if ppid in cpids:
> >             parent = window.qtile.windows_map.get(cpids[ppid])
> >             parent.minimized = True
> >             window.parent = parent
> >             return
> >         ppid = psutil.Process(ppid).ppid()
> > 
> > @hook.subscribe.client_killed
> > def _unswallow(window):
> >     if hasattr(window, 'parent'):
> >         window.parent.minimized = False
> > ```
> 
> I don't know... How should I use the code? If the window goes away and when you close the app it's there again (like how it happens in Luke's video) then it works!

I just had my lazy ass trying it out and it works like a CHAMP!!!! You are great man! Thanks for your work!!!

**Comment by Godnyx** [comment]
> > Something like this?
> > ```python
> > import psutil
> > 
> > @hook.subscribe.client_new
> > def _swallow(window):
> >     pid = window.window.get_net_wm_pid()
> >     ppid = psutil.Process(pid).ppid()
> >     cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
> >     for i in range(5):
> >         if not ppid:
> >             return
> >         if ppid in cpids:
> >             parent = window.qtile.windows_map.get(cpids[ppid])
> >             parent.minimized = True
> >             window.parent = parent
> >             return
> >         ppid = psutil.Process(ppid).ppid()
> > 
> > @hook.subscribe.client_killed
> > def _unswallow(window):
> >     if hasattr(window, 'parent'):
> >         window.parent.minimized = False
> > ```
> 
> Thanks a lot. It works with mpv, vlc, ristretto. But i have trouble to make it work with sxiv. Any ideas?

Mine works! Check my [config](https://gist.github.com/Godnyx/bbf4829268d329e6a32ca1cadf5d1d52). Remember to change you apps of use and to examine the keybindings so you don't stack.

**Comment by m-col** [comment]
Glad it's working for you :)

**Comment by MithicSpirit** [comment]
Is there a way to make this only affect my terminal? I was thinking about doing something with the `WM_CLASS` or `WM_NAME` but I'm not sure how I would check that.

**Comment by ramnes** [comment]
@MithicSpirit just add this before `parent.minimized = True`, replacing `roxterm` by the class of your own terminal:

```python
if parent.window.get_wm_class()[0] != "roxterm":
    return
```

**Comment by ramnes** [comment]
Standalone binary alternative: https://github.com/salman-abedin/devour

**Comment by m-col** [comment]
> Standalone binary alternative: https://github.com/salman-abedin/devour

very cool!

**Comment by Malex** [comment]
> Something like this?
> 
> ```python
> import psutil
> 
> @hook.subscribe.client_new
> def _swallow(window):
>     pid = window.get_net_wm_pid()
>     ppid = psutil.Process(pid).ppid()
>     cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
>     for i in range(5):
>         if not ppid:
>             return
>         if ppid in cpids:
>             parent = window.qtile.windows_map.get(cpids[ppid])
>             parent.minimized = True
>             window.parent = parent
>             return
>         ppid = psutil.Process(ppid).ppid()
> 
> @hook.subscribe.client_killed
> def _unswallow(window):
>     if hasattr(window, 'parent'):
>         window.parent.minimized = False
> ```

May I ask you why range(5) ?
I've been usin this a little logging the "i" found and I always get 1

**Comment by MithicSpirit** [comment]
`range(5)` means that it'll check up to the 5th parent. Most of the time it'll stop at 1 (2nd parent) since it usually goes terminal -> shell -> application, but if there is an intermediary (e.g. terminal file manager, launcher, etc.) then you can get more parents until the terminal.

**Comment by Malex** [comment]
> `range(5)` means that it'll check up to the 5th parent. Most of the time it'll stop at 1 (2nd parent) since it usually goes terminal -> shell -> application, but if there is an intermediary (e.g. terminal file manager, launcher, etc.) then you can get more parents until the terminal.

ok so basically it's just a "sensate guess" on how many intermediary will be there at most, I see

**Comment by Srinath-Anand** [comment]
Even after adding the snippet to my config.py (and restarting Qtile), window swallowing doesn't occur ☹️
How can I make it work?

**Comment by Malex** [comment]
> Even after adding the snippet to my config.py (and restarting Qtile), window swallowing doesn't occur ☹️ How can I make it work?

I'm using the code just fine (https://github.com/Malex/qtile-swallower/blob/develop/src/qtile_swallow/_swallow.py#L24)
Do you get anything in the log when using this config? ($HOME/.local/share/qtile/qtile.log)
Maybe you get some error when processing the configuration (for instance, very important: psutil is installed?

**Comment by Srinath-Anand** [comment]
I got it to work
I'd applied the decorator to only 2 hooks, thinking it'd suffice
Thanks @Malex 👍
