### ISSUE TITLE
idea: qtile-config {check,migrate}

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#1773]
For a long time we've had issues with configs:

1. people have syntax/logic errors and have to restart a bunch
2. we want to make changes to the internals and people are using them
3. people use the wrong kind of values for config variables, but it works "well enough", except doesn't get the desired behavior
4. etc.

In particular, we've long struggled with number 2, and have no real conclusions about what to support for a 1.0 API. For example, we (rightly so) got rid of a bunch of camel case in our codebase, but it broke everyone's configs who was messing with the internals. I've argued that everything that isn't a `cmd_` is not a public API and we reserve the right to change, but it's still annoying for people to have to update their configs.

Further, r.e. numbers 1 & 3, we've often told people "just run your config via python3 config.py" or (when we get type annotations working) "run pytype on your config". But there are additional checks we could/should have people do (see e.g. #1772) that neither of those will accomplish.

So, what if we introduce a new command `qtile-config`. Initially I'm imagining two subcommands, `check` and `migrate`. `check` would run a type checker, our checks from #1772, and anything else we want (deprecation warnings, etc.). `migrate` would do a best-effort migration of code. In general re-writing code is undecidable, but most of our changes are things like "add another argument to this function" or "rename fooBar to foo_bar", which we could do with reasonable accuracy, and if your config doesn't get auto-migrated, well, too bad.

Then, after 1.0, we allow any API changes where someone can write a migrate blurb that would be reasonably successful at migrating most configs. This means that 1. users don't have do this themselves and 2. we can keep refactoring our code for e.g. wayland.

Once we had this code, we could do other things too, like run `migrate` on qtile start so users' configs are automatically upgraded.

There is an issue of dependencies, but we can make the type checking deps for `qtile-config check` optional, so people don't have to install them if they don't want, and just print a big warning if they're not available.

I'm happy to work on an implementation of this, but I'd just like to see if anyone else has any good ideas before starting :)

**Comment by ramnes** [comment]
I really like the idea! 

We said a few times that we have too many entrypoints, so maybe we should merge all these into qtile beforehand? Something like

```
qtile
qtile help
qtile shell
qtile check
qtile migrate
qtile top
...
```

Also, we could have an automigrate flag in config so that users can optin for us to migrate their config automatically when we detect that qtile version has changed (with the version written in a cache dir or something).

I'll try to think a bit more about this and report back if I have anything else. :)

**Comment by zordsdavini** [comment]
How that should work in distro packaged? Ex., I do `qtile-git` update in Arch and what should happen?

**Comment by ramnes** [comment]
> How that should work in distro packaged? Ex., I do `qtile-git` update in Arch and what should happen?

Well, the user runs the migrate command, or better, you have your package manager doing it for you, or qtile itself does it for you:

> Also, we could have an automigrate flag in config so that users can optin for us to migrate their config automatically when we detect that qtile version has changed (with the version written in a cache dir or something).

At startup we check the version written in the cache, compare it against current version, and migrate if there's a difference.

**Comment by tych0** [comment]
On Mon, Jun 08, 2020 at 10:41:07PM -0700, Guillaume Gelin wrote:
> I really like the idea! 
> 
> We said a few times that we have too many entrypoints, so maybe we should merge all these into qtile beforehand? Something like
> 
> ```
> qtile
> qtile help
> qtile shell
> qtile check
> qtile migrate
> qtile top
> ...
> ```

That sounds fine, although I think `qtile` should do nothing (and
probably exit(1)), so that people are aware of the new API.

> Also, we could have an automigrate flag in config so that users can optin for us to migrate their config automatically when we detect that qtile version has changed (with the version written in a cache dir or something).

I don't even think we need a version change detection; we can just
require that the transformations in migrate be idempotent.
