### ISSUE TITLE
Feature: More Simple Configuration

### ISSUE THREAD

**Issue by pylang** [qtile/qtile#1779]
# Issue description

Python is great.  It's relatively easy to read, but not all people know Python.  I've learned that some newcomers to qtile have had trouble grasping how the `config.py` works.  While I can follow `config.py` as a Python programmer, I can commiserate with beginners who are used to reading yaml files.

# Suggestion

Many WMs have plaintext configs, which I think is easier among new users transitioning from other WMs.  Perhaps consider extracting the user metadata contents to json, yaml (preferred) or other plaintext config?  Thanks.

Btw, I'm grateful you've created a python option in the WM space.  Many thanks.
  

# Qtile version

All

# Stack traces

N/A

# Configuration

N/A

**Comment by cr1ogen** [comment]
Great Suggestion!!

**Comment by fdev31** [comment]
Would it be good enough if it is a limited subset of what you can do now?
I was thinking in something, could even be Python but very simplified - a bit like TOML.
In addition to this kind of "simplified subset" one could still add custom definitions for instance.
I was thinking in generating the final config.py from some boilerplate, could almost be a template...

Just an example of what I had in mind:
```python
files="nautilus"
web="firefox"
term="kitty"

follow_mouse_focus = True
bring_front_click = False
auto_fullscreen = True
focus_on_window_activation = "smart"

groups = [
    dict(label="web"),
    dict(label="term"),
    ]

layouts = ["max", "bsp", "columns"]

floating = dict(
    classes=['confirm', dialog', download'],
    names=['pinentry', 'branchdialog']
)

screens = [
    dict(placement="top", widgets=["groupbox", "prompt", "tasklist", "systray"]),
    dict(placement=None)
    ]


scratchpads = [
    dict(name="scratch1.term", command="xterm", width=0.9)
    dict(name="scratch2.volume", command="pavucontrol", width=0.5, height=0.9)
]

mod="mod4"

keys = [
    [[mod], "r", "custom.raiseFloatingWindows"],
    [[mod, "mod1"], "Right", "layout.z"],
#...
]
```

**Comment by pylang** [comment]
Many thanks on the mock up.  

My first instinct is that *someone shouldn't have to know a program's language to configure it.*  So config files in markup languages like YAML, TOML, ini, etc. would be my first reaction.

However, I have seen config files written in Python that aren't too bad.  The [ipython config][0] file comes to mind.  They can generate a config file with commented out defaults.  If the user uncomments, the defaults can be overriden.  Maybe a sample config file might look as follows:

```python

# Uncomment options below to change default settings.

# General settings.  These options control ...
#q.term = "kitty"
#q.follow_mouse_focus = True
#q.bring_front_click = False
#q.auto_fullscreen = True
q.focus_on_window_activation = "super smart"

# Assign labels, e.g. "web", "term", ...
#q.groups.label = [
#    "web",
#   "term",
#]

# List the desired layouts.  Example ["max", "bsp"] ...
#q.layouts = [
#    "max", 
#    "bsp", 
#    "columns",
#    "something else",
#]

# The default floating properties are below.  You can override them as shown.
#q.floating.classes = ["confirm", "dialog", "download"]
#q.floating.names = ["pinentry", "branchdialog"]

# Set your screens and properties
#q.screens.screen_1.placement = "top" 
#q.screens.screen_1.widgets = ["groupbox", "prompt", "tasklist", "systray"]
#q.screens.screen_2.placement = None

```

If python config files were kept, I would try to lower the users burden beyond strings, ints, floats and bools and lists.  I would avoid "intermediate" data-structures such as dicts or nested containers.   I've managed to partially demonstrate that in the example above with dotted access.  Yet, I do know the value of key-value pairing.  In such cases, i'd use the bracket-style over `dict()` keyword.  Though I think YAML and TOML handle key-values pretty nicely.










  [0]: https://ipython.readthedocs.io/en/stable/config/intro.html#example-configuration-file

**Comment by ramnes** [comment]
Hello @pylang, thanks for your input. We've been discussing this with @tych0, and we decided that we don't want to pursue that proposal, I'm sorry.

We believe that the whole point and advantage of Qtile is that it's written and configured in Python. In that sense, it's out of scope for our project and community to offer such an alternative style of configuration, as we don't want to spend time supporting users that doesn't have an interest in Python in the first place. 

That being said, we do have interest in making the current configuration style simpler if we can, and we regularly add such improvements (e.g. the EzKey helper, or the new libqtile.qtile import), so feel free to submit ideas that go in that direction!

**Comment by pylang** [comment]
@ramnes To be clear, which proposal are you dismissing?  I loosely understand not wanting to deviate from Python to plain text, but the main proposal here is to lower the barrier of entry. 

> We believe that the whole point and advantage of Qtile is that it's written and configured in Python. ... submit ideas that go in that direction!

The discussion has since progressed to suggestions on simplified configurations written *in Python* (see @fdev31's [great mock-up](https://github.com/qtile/qtile/issues/1779#issuecomment-653190537) and 2/3 of my [last post](https://github.com/qtile/qtile/issues/1779#issuecomment-653230773))

Perhaps those were not seen.  

----
Anyhow, thanks to @cr1ogen  and @fdev31 on the feedback.  Cheers.

**Comment by ramnes** [comment]
Sorry that wasn't clear, let me throw a few examples:

Things we don't want:
* Another language than Python for the config
* Everything as dicts and strings

Things we would most likely accept a PR for:
* Simplified constructors (e.g. setting sane defaults for arguments that are not strictly necessary)
* More comments in the default config

**Comment by pylang** [comment]
I stumbled on this post on [trailets](https://labs.quansight.org/blog/2020/08/what-are-traitlets/), which have been used to generate clean `config.py` files.  See the section entitled "A Traitlets usage example".

 *Note:  the link above expands on a previous topic of [IPython's config method](https://github.com/qtile/qtile/issues/1779#issuecomment-653230773).*


Takeaways:

- Use traitlets to convert class attributes into properties. (simple constructors)
- Documentation is directly extracted from a traitlet's docstring and added to the config file as comments (more comments in the default config)
- The generated config file implements Python as commented options (pure Python)
- These options can be changed interactively

The latter features appear to address the mentioned [sample requisites](https://github.com/qtile/qtile/issues/1779#issuecomment-669142241), i.e.:  

> - Simplified constructors (e.g. setting sane defaults for arguments that are not strictly necessary)
> - More comments in the default config

Hopefully the mentioned features will spur ideas helpful in goals of this project.

Cheers.

**Comment by ramnes** [comment]
Yeah, I like such patterns, and it's actually one of the things I proposed in #1751. It would also make Qtile internals much simpler and easier to test I think.
