### ISSUE TITLE
Feature: Xmonad type submap

### ISSUE THREAD

**Issue by prathampowar2001** [qtile/qtile#1783]
# Issue description
Xmonad has a cool feature called submap.Which allows me to press a keychord eg mod+d and the key I press after that decides what action is performed just like modes in vim.

#Suggestion
I suggest qtile should have a feature like
# Qtile version
Any

# Stack traces
None

# Configuration
Any

**Comment by tych0** [comment]
https://github.com/qtile/qtile/pull/1777

**Comment by ramnes** [comment]
Closing in favor of #1208 and #1777
