### ISSUE TITLE
Leaving group with fullscreen window and then returning to it is broken

### ISSUE THREAD

**Issue by rxcomm** [qtile/qtile#1784]
# Description

When I create a fullscreen window in a group, and then change to another group
and back to the original group, the fullscreen window is no longer rendered. Functionality
for the window is still there, however. E.g. when running a zoom ;) conversation in
fullscreen mode, the audio part of the conversation continues whereas window containing
the video does not render. Clearly the window (and it's functionality) is still someplace,
just not rendered.

Other applications also exhibit this behavior when used in fullscreen mode. Another example
is chromium (enter fullscreen mode with F11).

# Commit hash

This behavior manifests itself with current git, master branch. I bisected the issue,
and the last good commit that does not exhibit this behavior is: 52d787944ebb669d5e90d7d372648e539034c271.

# Stack traces
No stack traces were thrown.

**Comment by michalszymura** [comment]
It works this way for me when i use floating in the group. Also Steam window does not reappear(its not fullscreen)
