### ISSUE TITLE
Shutdown triggers a "Got an exception in poll loop" error

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [qtile/qtile#1786]
# Issue description
When I click "shutdown" and "max" which are on the tray, and then quit to X (mod4+ctrl+q)
this is what I get: https://ibb.co/vHTnqMg .. As you can see there are two errors at the bottom..
"Got an exception in poll loop"

# Qtile version

qtile-0.15.1

# Stack traces

https://ibb.co/vHTnqMg

# Configuration

https://pastebin.com/wqbdSH9K

**Comment by tych0** [comment]
So.... What's the actual problem? Looks like the shutdown worked to me.

In the future, please paste things from the logs vs. sending screenshots.

**Comment by ReductoAdAbsurdum** [comment]
I should ignore them ? I thought they mean something is wrong....

**Comment by ramnes** [comment]
I think you're both right; the shutdown worked, but it shouldn't log an error.

**Comment by tych0** [comment]
I don't think either of those stack traces are related to the shutdown, both of them are fixed by one of the patches in https://github.com/qtile/qtile/pull/1723

**Comment by ramnes** [comment]
Eh, I read the logs too fast and thought the error were related to the X connection. Sorry and thanks, @tych0!

@ReductoAdAbsurdum This is fixed but not released yet.
