### ISSUE TITLE
Dialog windows have no frames in Gimp

### ISSUE THREAD

**Issue by serzhshakur** [qtile/qtile#1794]
# Issue description
Dialog window frames (borders) are not visible for some programs like Gimp and Intellij Idea. See screenshots below

- Gimp: *File > New*

![gimp_0 15-git](https://user-images.githubusercontent.com/15928203/86031085-128a1780-ba3e-11ea-8876-74531ac5b934.png)

- IntelliJ Idea: *File > New > Project ..*

![intelliJ_Idea_new-project__0 15-git](https://user-images.githubusercontent.com/15928203/86031610-bb387700-ba3e-11ea-9824-be352e449dfc.png)

# Qtile version

latest Qtile git version `0.15.1.dev158+gfb45432b`

# Configuration

can be observed with default qtile configuration.

**Comment by tych0** [comment]
Can you show an xprop for one of these dialogs?

**Comment by serzhshakur** [comment]
Here you go!
```
WM_WINDOW_ROLE(STRING) = "gimp-image-new"
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16784057
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_USER_TIME(CARDINAL) = 288975
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1001ab8
WM_CLIENT_LEADER(WINDOW): window id # 0x1000001
_NET_WM_PID(CARDINAL) = 842
WM_LOCALE_NAME(STRING) = "en_GB.utf8"
WM_CLIENT_MACHINE(STRING) = "serzh-pc"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		program specified location: 0, 0
		program specified minimum size: 409 by 256
		program specified maximum size: 409 by 256
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gimp", "Gimp"
WM_ICON_NAME(STRING) = "Create a New Image"
_NET_WM_ICON_NAME(UTF8_STRING) = "Create a New Image"
WM_NAME(STRING) = "Create a New Image"
_NET_WM_NAME(UTF8_STRING) = "Create a New Image"
```

![gimp__xprop](https://user-images.githubusercontent.com/15928203/86032732-7a416200-ba40-11ea-94c2-77f47e34f652.png)

**Comment by tych0** [comment]
https://github.com/qtile/qtile/pull/1795

Can you confirm that the above fixes it?

**Comment by serzhshakur** [comment]
I'm afraid it doesn't work.
Tried with xephyr 

```
❯ git log --oneline| head -n 1
f4e7d067 floating: set the border color on user-placed windows
APP=alacritty SCREEN_SIZE=1920x1070  ./scripts/xephyr -c ~/.config/qtile/config.py
```

![gimp__xprop-fix](https://user-images.githubusercontent.com/15928203/86036878-34d46300-ba47-11ea-9b48-f167db7c1be0.png)

**Comment by tych0** [comment]
Huh, ok. :(

**Comment by ramnes** [comment]
Yes this is new and due to one of the commits on the batch of changes we made related to focus. I noticed it a few weeks ago but did not take the time to bisect. We also have borders on fullscreen windows when we shouldn't, and I'm pretty sure it's related.

**Comment by tych0** [comment]
Can someone try again with the PR now? I used gimp to test it, and it works for me.

**Comment by serzhshakur** [comment]
Tested with `adaf51ac floating: set the border color on user-placed windows`. 
I see no changes, even with Gimp

![2020-07-09_06-41-gimp](https://user-images.githubusercontent.com/15928203/86994657-a632b500-c1af-11ea-868d-d37cf66a6c78.png)

@tych0 how did you test at your side? I used the following command to launch Xephyr:

```
APP=alacritty SCREEN_SIZE=1920x1070  ./scripts/xephyr -c ~/.config/qtile/config.py 
```
And then `Ctrl+Shift` to lock mouse pointer inside Xephyr window.

**Comment by tych0** [comment]
I just installed it and launched a new X session, like a real barbarian :)

**Comment by serzhshakur** [comment]
Just installed qtile from your branch using setup.py and I see no changes. Gimp (and Intellij IDEA) dialogs still have no frames

```
❯ qtile --version
0.2.dev3350+gadaf51ac
```

**Comment by tych0** [comment]
Huh, can you add some logs to verify what the border pixel/width are? Weird that it works for me and not you :(

**Comment by serzhshakur** [comment]
Which logs are you talking about? Can you help me to get them?

**Comment by serzhshakur** [comment]
Why was this closed? The bug has not been fixed, at least for me. Did anybody else except @tych0 and me try to test the fix?

**Comment by ramnes** [comment]
Yep, I did test it and it's fixed on my side, for Gimp and all other floating windows. It's weird that it does not work for you when it works for Tycho and myself. Can you update to the latest master, reload Qtile and try again? If it still does not work, can you confirm that `qtile --version` says `0.15.1.dev166+g0f6be02d`?

**Comment by zordsdavini** [comment]
@serzhshakur  tested on last master version - there are borders in gimp and Jetbrain's product. Maybe libs are bad not qtile itself (before it was)?

**Comment by serzhshakur** [comment]
Hm.. that's strange. Ok, will try to reinstall everything from scratch and try to verify this with genuine config. Thanks!

**Comment by serzhshakur** [comment]
I finally figured out what was causing the problem. Now I see borders. But is there a way to put a shadow on those floating windows?

**Comment by ramnes** [comment]
> I finally figured out what was causing the problem. Now I see borders.

What was the problem? In case anyone has the same problem and read this later.

> But is there a way to put a shadow on those floating windows?

This is up to your compositing manager.

**Comment by serzhshakur** [comment]
a trivial one, as always. Had `border_width=2` in `layout.Floating`
Ok, will play around with picom. Thanks!
