### ISSUE TITLE
gen-keybinding-img gives error  __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by shubham-cpp** [qtile/qtile#1804]
# Issue description

I was trying out the feature to generate images out of the config file as mention [here](http://docs.qtile.org/en/latest/manual/commands/keybindings.html#generate-your-own-images)
# Qtile version

0.15.1
# Stack traces

# Configuration

The gen-keybinding-img file from your scripts folder
the Error is 
```
Traceback (most recent call last):
  File "./scripts/gen-keybinding-img", line 420, in <module>      
    kb_map = get_kb_map(config_path)
  File "./scripts/gen-keybinding-img", line 361, in get_kb_map
    c = Config(config_path)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by tych0** [comment]
@zordsdavini

**Comment by zordsdavini** [comment]
Me here :)
@shubham-cpp can you provide what arguments were in your call?

**Comment by shubham-cpp** [comment]
This is was first time  `./scripts/gen-keybinding-img -c config.py -o icons/`
This is second time `./scripts/gen-keybinding-img -c ~/.config/qtile/config.py -o ~/Pictures/temp/`

**Comment by zordsdavini** [comment]
does these files and directories exist?

**Comment by shubham-cpp** [comment]
yes of course

**Comment by shubham-cpp** [comment]
@zordsdavini have you got the script working. I actually want this to work so that when I press `super + h` it will show me the keybindings in good way

**Comment by zordsdavini** [comment]
I tried with/without arguments and got images. I have a little bit newer version then 0.15.1 but it worked before as I remember. 
<...>
Checkouted 0.15.1 version (tag) - there is no script to generate images, so now it is interesting what version you are using @shubham-cpp :)
But to get to keybinding all these images, you will need to put them in one or some kind of `Key(mod, 'h', lazy.spawn(['sciv', '~/Pictures/temp/*.png`])`

**Comment by tych0** [comment]
@zordsdavini try master, I think it's been refactored there.

**Comment by shubham-cpp** [comment]
Thank you both for your replies, I guess right now the problem wont be solved. Maybe we'll look into it in future

**Comment by zordsdavini** [comment]
@tych0 I cloned master branch and run the script - all works for me :-/

@shubham-cpp can you give your config. Maybe this is related to that. I'll try to run on it

**Comment by shubham-cpp** [comment]
[to_upload.txt](https://github.com/qtile/qtile/files/4896354/to_upload.txt)

You're talking about qtile config right @zordsdavini ?

**Comment by aru-hackZ** [comment]
I know maybe this is off-topic, but I'm not able to find the gen-keybinding-img script on my arch linux qtile installation (via pacman). Thanks.

**Comment by zordsdavini** [comment]
It is in git repository not in lib itself that comes with pacman.

2020-09-06, sk 17:26, hackZ Aru62 <notifications@github.com> rašė:

**Comment by aru-hackZ** [comment]
@zordsdavini ok thank you! So to use it, i just need to copy the script to a file, and execute it.

**Comment by zordsdavini** [comment]
@aru-hackZ it uses libqtile directory, so to use it, you should clone all git repo and use it from this codebase

**Comment by aru-hackZ** [comment]
> @aru-hackZ it uses libqtile directory, so to use it, you should clone all git repo and use it from this codebase
> 

Ok Thank u!
