### ISSUE TITLE
MonadTall and Slice don't work together

### ISSUE THREAD

**Issue by mikelward** [qtile/qtile#1811]
# Issue description

If I create a Slice layout with MonadTall as the delegate/fallback layout, the MonadTall layout uses the entire screen width, instead of just the width remaining after Slice.

It seems to be something to do with `self.group.screen` being the whole screen instead of just the screen passed to `clone`?

# Qtile version

3c46be326e7c1f14d24e836b40dcefac443d9478

# Stack traces

# Configuration

Like https://github.com/mikelward/conf/blob/main/config/qtile/config.py, with

```
layouts = [
    ...
    layout.Slice(width=400, name='sidebrowser', role='browser', fallback=layout.MonadTall()),
    ...
]
```

**Comment by tych0** [comment]
Yeah, it looks like you're right that the math needs to be fixed in MonadTall to respect the screen it actually sees.
