### ISSUE TITLE
How to launch bash commands at every start-up

### ISSUE THREAD

**Issue by lapingenieur** [qtile/qtile#1817]
# Issue description

I want to run `nitrogen --restore` and `mapmyself` (custom bash command located in `/usr/bin/mapmyself`, works perfectly with bash) everytimes qtile starts. I tried this first : (adding these lines somewhere in `config.py`)

        lazy.spawn("nitrogen --restore")
        lazy.spawn("mapmyself")

Then I tried out :

        from libqtile import layout, bar, widget, hook
        
        @hook.subscribe.startup_once
        def autostart():
            lazy.spawn("nitrogen --restore")
            lazy.spawn("mapmyself")
 
And finally :

        import subprocess
        from libqtile import layout, bar, widget, hook
        
        @hook.subscribe.startup_once
        def autostart():
            home = os.path.expanduser('~/.config/qtile/autostart.sh')
            subprocess.call([home])

None of these methods worked. Note that this actually works fine if I assign it to a keybinding :

    Key([mod, "control"], "w",
        lazy.spawn("mapmyself"),
        lazy.spawn("nitrogen --restore")),

# Qtile version

`0.10.7-2ubuntu2` (version from ubuntu 19.10's APT repo)

# Stack traces

# Configuration

[config.txt](https://github.com/qtile/qtile/files/4926461/config.txt)

**Comment by lKk2** [comment]
You should follow the steps to build from source since your version is too old and ubuntu removed qtile from their oficial package list, a new one like 0.15.1 will work for sure

**Comment by ramnes** [comment]
Yeah, 0.10.7 is very old, please upgrade to a newer version and report back. :)
