### ISSUE TITLE
Dynamic group creation and deletion

### ISSUE THREAD

**Issue by c-torre** [qtile/qtile#1818]
### Issue description

Hi, I have been trying to reproduce this groups behavior with the documentation and other online resources, but so far unsuccessful. My goal is for group creation and deletion to follow this heuristic:

**There are always `g = n + 1` groups available, where `n` is the number of non-empty groups and `+1` refers to a single empty group at the end of the list."**

Therefore, according to this rule:

* Removing all windows from the group deletes it.
* Adding a window to the last empty group updates `n` and therefore `g`, so a new empty group is added at the end.
* Booting into QTile means `g = 0 + 1`, so only one empty group is available until a window is spawned.

This description also matches how GNOME handles workspaces.

As a result, keys can be mapped to:

* Go to next group
* Go to previous group

Is this a feature that is possible or could be added?

Thank you

### Qtile version

0.15.1-1

**Comment by m-col** [comment]
I think you might be able to script this in your config. The Qtile object (`libqtile.qtile` on master) has `qtile.add_group` and `qtile.delete_group` methods, which you could use inside the appropriate hooks to add/delete groups when required.

**Comment by hbonnavaud** [comment]
> I think you might be able to script this in your config. The Qtile object (`libqtile.qtile` on master) has `qtile.add_group` and `qtile.delete_group` methods, which you could use inside the appropriate hooks to add/delete groups when required.

Hi, I did this in my config, however I can't manage to shift the remaining groups:
Let say I have 9 groups with names "1", "2", "3", ..., "8", "9".
I use a shortcut to remove group "3" (or remove it by any other way doesn't matter).
Then, I want to rename groups "4" to "9" as "3" to "8".
group.name = int(group.name) - 1 doesn't work, the groups are still named 1, 2, 4, 5, 6 ...

Do you have an Idea how I can do this renaming stuff?
