### ISSUE TITLE
How to automatically send a window to a specific workspace?

### ISSUE THREAD

**Issue by apoorv569** [qtile/qtile#1821]
I have my workspace section like this
```
##### WORKSPACES #####

group_names = [("1", {'layout': 'monadtall'}),
               ("2", {'layout': 'max'}),
               ("3", {'layout': 'monadtall'}),
               ("4", {'layout': 'monadtall'}),
               ("5", {'layout': 'monadtall'}),
               ("6", {'layout': 'max'}),
               ("7", {'layout': 'monadtall'}),
               ("8", {'layout': 'monadtall'}),
               ("9", {'layout': 'max'})]
groups = [Group(name, **kwargs) for name, kwargs in group_names]

for i, (name, kwargs) in enumerate(group_names, 1):
     keys.append(Key([mod], str(i), lazy.group[name].toscreen()))        # Switch to another group
     keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(name))) # Send current window to another group
```
How can I send a window to automatically spawn to a particular workspace, for example, when I open steam I want it to open on workspace 9, and I want firefox to open on workspace 2, and so on.

**Comment by Craksy** [comment]
you can use the `client_new` hook for that:
```python
@hook.subscribe.client_new
def client_new(client):
    if client.name == 'Firefox':
        client.togroup('Web')
```
this is also described in the [documentation](http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.client_new)

**Comment by apoorv569** [comment]
> you can use the `client_new` hook for that:
> 
> ```python
> @hook.subscribe.client_new
> def client_new(client):
>     if client.name == 'Firefox':
>         client.togroup('Web')
> ```
> 
> this is also described in the [documentation](http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.client_new)

I have to write this block for every client I want to send?

**Comment by Craksy** [comment]
I'm not sure what you mean.
you only have to subscribe to the hook once, ie. you can put all your definitions in that one function.
Obviously it's not gonna guess by itself which clients belong where, so you'll have to write a definition for each.
I think the `Match()` class is supposed to give you a bit finer control with these things, but tbh i'm not really using it myself.

But i do encourage you to read the documentation, and check out some of the configurations in the [examples repo](https://github.com/qtile/qtile-examples).
You don't have to read it back to back, but familiarize yourself with it enough, so that you know where to look for these kind of things. This is pretty basic stuff.

**Comment by apoorv569** [comment]
> I'm not sure what you mean.
> you only have to subscribe to the hook once, ie. you can put all your definitions in that one function.
> Obviously it's not gonna guess by itself which clients belong where, so you'll have to write a definition for each.
> I think the `Match()` class is supposed to give you a bit finer control with these things, but tbh i'm not really using it myself.
> 
> But i do encourage you to read the documentation, and check out some of the configurations in the [examples repo](https://github.com/qtile/qtile-examples).
> You don't have to read it back to back, but familiarize yourself with it enough, so that you know where to look for these kind of things. This is pretty basic stuff.

I meant do I have to write this block for every client for example
```
@hook.subscribe.client_new
def client_new(client):
    if client.name == 'Firefox':
        client.togroup('Web')
```
```
@hook.subscribe.client_new
def client_new(client):
    if client.name == 'Steam':
        client.togroup('Web')
```
```
@hook.subscribe.client_new
def client_new(client):
    if client.name == 'vlc':
        client.togroup('Web')
```
and so on.

In the documentation is [this](https://github.com/qtile/qtile-examples/blob/master/mort65/config.py) what you talking about?

**Comment by Craksy** [comment]
I'm just going to say "sorry" in advance, because i'm going to come off as a massive jerk here but..
You might not even be aware, but by not putting any sort of effort into this, you are taking other peoples time for granted. Do not assume that people have nothing better to do than to solve your problems.
I love to help. I really do. But when you don't even try yourself, it's not helping. It's just doing your stuff.

If you scroll down the page of the *very same link you just posted* you will find your answer. It's actually a very elaborate piece of documentation for *the exact* thing that you're requesting.

I'm not saying that you can't ask simple questions. plenty of guys here are happy to help. Just make sure that you're not actually sitting on the answer, because if someone has to tell you to lift your own ass to find it, they are probably going to feel really shitty about trying to help you in the first place.

That being said please note that i don't have any sort of authority here what so ever.
Take what i said with a grain of salt or  feel free to disregard it entirely.
I'm not trying to enforce any rules. This is just my personal oppinion (and a piece of advice)

Finally, to answer your questions:
No you do not need the 
```python
@hook.subscribe.client_new
def client_new(client):
```
part for every client. you can put all of them in the same function (or loop through a collection as done in the example config you linked)

And yes. Something like that was exactly what i was talking about.
Those example configs are great. Most of Qtiles features are showcased here, at least for the most common use cases, and even in a sort of "real life" context - all of these lmplementation has been writting by someone else, so solve an actual problem.

Aside from that remember to explore and experiment.
Try to put some code in your config, hit the switch, and see what happens.

**Comment by apoorv569** [comment]
> I'm just going to say "sorry" in advance, because i'm going to come off as a massive jerk here but..
> You might not even be aware, but by not putting any sort of effort into this, you are taking other peoples time for granted. Do not assume that people have nothing better to do than to solve your problems.
> I love to help. I really do. But when you don't even try yourself, it's not helping. It's just doing your stuff.
> 
> If you scroll down the page of the _very same link you just posted_ you will find your answer. It's actually a very elaborate piece of documentation for _the exact_ thing that you're requesting.
> 
> I'm not saying that you can't ask simple questions. plenty of guys here are happy to help. Just make sure that you're not actually sitting on the answer, because if someone has to tell you to lift your own ass to find it, they are probably going to feel really shitty about trying to help you in the first place.
> 
> That being said please note that i don't have any sort of authority here what so ever.
> Take what i said with a grain of salt or feel free to disregard it entirely.
> I'm not trying to enforce any rules. This is just my personal oppinion (and a piece of advice)
> 
> Finally, to answer your questions:
> No you do not need the
> 
> ```python
> @hook.subscribe.client_new
> def client_new(client):
> ```
> 
> part for every client. you can put all of them in the same function (or loop through a collection as done in the example config you linked)
> 
> And yes. Something like that was exactly what i was talking about.
> Those example configs are great. Most of Qtiles features are showcased here, at least for the most common use cases, and even in a sort of "real life" context - all of these lmplementation has been writting by someone else, so solve an actual problem.
> 
> Aside from that remember to explore and experiment.
> Try to put some code in your config, hit the switch, and see what happens.

Sorry for being a pain in the ass, but I'm not against putting effort for what I want achieve, you just assumed that about me yourself. If you really feel something is not worth your time please ignore it don't do it, I did not @ you, I posted a question in public site. Anyways, I asked the question because I wanted to know where/what to look for, to shortlist some stuff. And sometimes there are multiple ways to achieve something, in other WM I have used such as XMonad, DWM, doing this is pretty straight forward for example in XMonad
```
                -- Xprop                        -- Shift/Float               -- Workspace
      [ className =? "obs"             --> doShift              ( myWorkspaces !! 6 )
      , className =? "firefox"         --> doShift              ( myWorkspaces !! 1 )
      , className =? "vlc"              --> doShift              ( myWorkspaces !! 4 )
```
and in DWM
```
 /* class        instance        title       tags mask     iscentered   isfloating    monitor */
  { "Gimp",      NULL,        NULL,          0,                   0,               1,              -1 },
  { "firefox",     NULL,        NULL,       1 << 1,              0,               0,              -1 },
  { "Steam",    NULL,        NULL,       1 << 8,              0,               0,              -1 },
```
so I sent you the link back here to make sure this is what you are trying to recommend, or maybe there is some another way.

**Comment by easilok** [comment]
To do what XMonad and DMW do, you could use the match attribute. I came from XMonad to try qtile and found how to use recently so I only have one example to show, but it's working:

```python
group_names =  [("1", {'layout': 'monadtall', 'init': True}),
            ("2", {'layout': 'monadtall'}),
            ("3", {'layout': 'monadtall'}),
            ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
            ("5", {'layout': 'monadtall'}),
            ("6", {'layout': 'monadtall', 'matches':[Match(wm_class=["Pcmanfm"])]}),
            ("7", {'layout': 'monadtall'}),
            ("8", {'layout': 'max'}),
            ("9", {'layout': 'monadtall'}),
            ("0", {'layout': 'monadtall'})]
```

**Comment by apoorv569** [comment]
> To do what XMonad and DMW do, you could use the match attribute. I came from XMonad to try qtile and found how to use recently so I only have two examples to show, but it's working:
> 
> ```python
> group_names =  [("1", {'layout': 'monadtall', 'init': True}),
>             ("2", {'layout': 'monadtall'}),
>             ("3", {'layout': 'monadtall'}),
>             ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
>             ("5", {'layout': 'monadtall'}),
>             ("6", {'layout': 'monadtall', 'matches':[Match(wm_class=["Pcmanfm"])]}),
>             ("7", {'layout': 'monadtall'}),
>             ("8", {'layout': 'max'}),
>             ("9", {'layout': 'monadtall'}),
>             ("0", {'layout': 'monadtall'})]
> ```

This looks interesting, and clean. What is the `init` here means 
```
group_names =  [("1", {'layout': 'monadtall', 'init': True}),
```

And you are missing a `"` here after `4` 
```
("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
```

**Comment by easilok** [comment]
> > To do what XMonad and DMW do, you could use the match attribute. I came from XMonad to try qtile and found how to use recently so I only have two examples to show, but it's working:
> > ```python
> > group_names =  [("1", {'layout': 'monadtall', 'init': True}),
> >             ("2", {'layout': 'monadtall'}),
> >             ("3", {'layout': 'monadtall'}),
> >             ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
> >             ("5", {'layout': 'monadtall'}),
> >             ("6", {'layout': 'monadtall', 'matches':[Match(wm_class=["Pcmanfm"])]}),
> >             ("7", {'layout': 'monadtall'}),
> >             ("8", {'layout': 'max'}),
> >             ("9", {'layout': 'monadtall'}),
> >             ("0", {'layout': 'monadtall'})]
> > ```
> 
> This looks interesting, and clean. What is the `init` here means
> 
> ```
> group_names =  [("1", {'layout': 'monadtall', 'init': True}),
> ```
> 
> And what if I want to add more `match` can I just do this
> 
> ```
> ("4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> ```
> 
> And you are missing a `"` here after `4`
> 
> ```
> ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
> ```

I'm starting with qtile, just jumped in the weekend to my working setup (was making little configurations before when I had time). The init: True was to try to fix an issue where on startup, the initial layout of that group was not the one defined. But I'm not sure if that fixed the issue, but I changed the layouts order, and the one defined for first group is actually the first now.

For the missing '"', it was some copy+paste issue :-P

**Comment by apoorv569** [comment]
> > > To do what XMonad and DMW do, you could use the match attribute. I came from XMonad to try qtile and found how to use recently so I only have two examples to show, but it's working:
> > > ```python
> > > group_names =  [("1", {'layout': 'monadtall', 'init': True}),
> > >             ("2", {'layout': 'monadtall'}),
> > >             ("3", {'layout': 'monadtall'}),
> > >             ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
> > >             ("5", {'layout': 'monadtall'}),
> > >             ("6", {'layout': 'monadtall', 'matches':[Match(wm_class=["Pcmanfm"])]}),
> > >             ("7", {'layout': 'monadtall'}),
> > >             ("8", {'layout': 'max'}),
> > >             ("9", {'layout': 'monadtall'}),
> > >             ("0", {'layout': 'monadtall'})]
> > > ```
> > 
> > 
> > This looks interesting, and clean. What is the `init` here means
> > ```
> > group_names =  [("1", {'layout': 'monadtall', 'init': True}),
> > ```
> > 
> > 
> > And what if I want to add more `match` can I just do this
> > ```
> > ("4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > ```
> > 
> > 
> > And you are missing a `"` here after `4`
> > ```
> > ("4, {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"])]}),
> > ```
> 
> I'm starting with qtile, just jumped in the weekend to my working setup (was making little configurations before when I had time). The init: True was to try to fix an issue where on startup, the initial layout of that group was not the one defined. But I'm not sure if that fixed the issue, but I changed the layouts order, and the one defined for first group is actually the first now.
> 
> For the missing '"', it was some copy+paste issue :-P

Nice. What about this - 

> And what if I want to add more match can I just do this
> 
> ```
> (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> ```
>

**Comment by easilok** [comment]
>  And what if I want to add more match can I just do this
>  ```
>  (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),

Sorry, didn't see that.

I'm not sure yet, but I think you need to make it:
```
(`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
```
Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.

**Comment by easilok** [comment]
> > And what if I want to add more match can I just do this
> > ```
> > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > ```
> 
> Sorry, didn't see that.
> 
> I'm not sure yet, but I think you need to make it:
> 
> ```
> (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
> ```
> 
> Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.

Actually, I tested it in a test machine here, and the way you asked worked. So, I withdraw my previous answer that was wrong, and I answer at this: 

> And what if I want to add more match can I just do this
>```
> (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),

with yes

**Comment by apoorv569** [comment]
> > > And what if I want to add more match can I just do this
> > > ```
> > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > ```
> > 
> > 
> > Sorry, didn't see that.
> > I'm not sure yet, but I think you need to make it:
> > ```
> > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
> > ```
> > 
> > 
> > Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.
> 
> Actually, I tested it in a test machine here, and the way you asked worked. So, I withdraw my previous answer that was wrong, and I answer at this:
> 
> > And what if I want to add more match can I just do this
> > ```
> > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > ```
> 
> with yes

Ah! Nice, appreciate it, this way is a lot cleaner. Thanks!

**Comment by apoorv569** [comment]
> > > And what if I want to add more match can I just do this
> > > ```
> > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > ```
> > 
> > 
> > Sorry, didn't see that.
> > I'm not sure yet, but I think you need to make it:
> > ```
> > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
> > ```
> > 
> > 
> > Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.
> 
> Actually, I tested it in a test machine here, and the way you asked worked. So, I withdraw my previous answer that was wrong, and I answer at this:
> 
> > And what if I want to add more match can I just do this
> > ```
> > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > ```
> 
> with yes

I'm getting a `Config Err!` after adding this
```
 ##### WORKSPACES #####

group_names = [("1", {'layout': 'monadtall'}),
               ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
               ("3", {'layout': 'monadtall'}),
               ("4", {'layout': 'monadtall'}),
               ("5", {'layout': 'monadtall'}),
               ("6", {'layout': 'max'}),
               ("7", {'layout': 'monadtall'}),
               ("8", {'layout': 'monadtall'}),
               ("9", {'layout': 'max'})]
```
I tried running `python .config/qtile/config.py`
```
❯ python .config/qtile/config.py
Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
Traceback (most recent call last):
  File ".config/qtile/config.py", line 69, in <module>
    ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
NameError: name 'Match' is not defined
```

Ignore the unmet dependencies.

**Comment by easilok** [comment]
> > > > And what if I want to add more match can I just do this
> > > > ```
> > > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > > ```
> > > 
> > > 
> > > Sorry, didn't see that.
> > > I'm not sure yet, but I think you need to make it:
> > > ```
> > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
> > > ```
> > > 
> > > 
> > > Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.
> > 
> > 
> > Actually, I tested it in a test machine here, and the way you asked worked. So, I withdraw my previous answer that was wrong, and I answer at this:
> > > And what if I want to add more match can I just do this
> > > ```
> > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > ```
> > 
> > 
> > with yes
> 
> I'm getting a `Config Err!` after adding this
> 
> ```
>  ##### WORKSPACES #####
> 
> group_names = [("1", {'layout': 'monadtall'}),
>                ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
>                ("3", {'layout': 'monadtall'}),
>                ("4", {'layout': 'monadtall'}),
>                ("5", {'layout': 'monadtall'}),
>                ("6", {'layout': 'max'}),
>                ("7", {'layout': 'monadtall'}),
>                ("8", {'layout': 'monadtall'}),
>                ("9", {'layout': 'max'})]
> ```
> 
> I tried running `python .config/qtile/config.py`
> 
> ```
> ❯ python .config/qtile/config.py
> Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
> Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
> Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
> Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
> Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
> Traceback (most recent call last):
>   File ".config/qtile/config.py", line 69, in <module>
>     ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
> NameError: name 'Match' is not defined
> ```
> 
> Ignore the unmet dependencies.

You need to import *Match* in
```
from libqtile.config import Match

**Comment by apoorv569** [comment]
> > > > > And what if I want to add more match can I just do this
> > > > > ```
> > > > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > > > ```
> > > > 
> > > > 
> > > > Sorry, didn't see that.
> > > > I'm not sure yet, but I think you need to make it:
> > > > ```
> > > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser"]), Match(wm_class=["Firefox"]), Match(wm_class=["GIMP"]), Match(wm_class=["VLC"])]}),
> > > > ```
> > > > 
> > > > 
> > > > Because I read that the 'matches' varible expects an array of Match results. I'm learning python at the same time, but maybe with a map function you can do that more friendly. But as I said, I'm not sure.
> > > 
> > > 
> > > Actually, I tested it in a test machine here, and the way you asked worked. So, I withdraw my previous answer that was wrong, and I answer at this:
> > > > And what if I want to add more match can I just do this
> > > > ```
> > > > (`"4", {'layout': 'max', 'matches':[Match(wm_class=["Brave-browser", "Firefox", "GIMP", "VLC"])]}),
> > > > ```
> > > 
> > > 
> > > with yes
> > 
> > 
> > I'm getting a `Config Err!` after adding this
> > ```
> >  ##### WORKSPACES #####
> > 
> > group_names = [("1", {'layout': 'monadtall'}),
> >                ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
> >                ("3", {'layout': 'monadtall'}),
> >                ("4", {'layout': 'monadtall'}),
> >                ("5", {'layout': 'monadtall'}),
> >                ("6", {'layout': 'max'}),
> >                ("7", {'layout': 'monadtall'}),
> >                ("8", {'layout': 'monadtall'}),
> >                ("9", {'layout': 'max'})]
> > ```
> > 
> > 
> > I tried running `python .config/qtile/config.py`
> > ```
> > ❯ python .config/qtile/config.py
> > Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
> > Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
> > Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
> > Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
> > Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
> > Traceback (most recent call last):
> >   File ".config/qtile/config.py", line 69, in <module>
> >     ("2", {'layout': 'max', 'matches':[Match(wm_class=["firefox"])]}),
> > NameError: name 'Match' is not defined
> > ```
> > 
> > 
> > Ignore the unmet dependencies.
> 
> You need to import _Match_ in
> 
> ```
> from libqtile.config import Match
> ```

Nice, its working now thanks!
