### ISSUE TITLE
Error when adding brightness and battery widget.

### ISSUE THREAD

**Issue by apoorv569** [qtile/qtile#1822]
I am trying to add a brightness and battery widget to my `Qtile` bar, after adding this for brightness
```
               widget.TextBox(
                        text="",
                        foreground=colors[2],
                        background=colors[10],
                        padding = 0,
                        fontsize=16
                        ),
               widget.Memory(
                        foreground = colors[2],
                        background = colors[10],
                        padding = 5,
                        format = '{MemUsed}M',
                        update_interval = 1.0,
                        ),                
               widget.Backlight(
                       foreground = colors[2],
                       background = colors[12],
                       brightness_file = "intel_backlight"
                       ),
```
and this for battery
```
               widget.TextBox(
                       text=" 奔 ",
                        foreground=colors[2],
                        background=colors[12],
                        padding = 0,
                        fontsize=14
                        ),
               widget.Volume(
                        foreground = colors[2],
                        background = colors[12],
                        padding = 5,
                        channel = 'Master',
                        device = 'default'
                        ),            
               widget.Battery(
                        format = '{char} {percent:2.0%}'
                        battery = 1,
                        foreground = colors[2],
                        background = colors[13],
                        charge_char = "^",
                        discharge_char = "V",
                        empty_char = "x",
                        full_char = "=",
                        unknown_char = "?",
                        low_percentage = 15,
                        low_foreground = colors[2],
                        notify_below = 15,
                        update_interval = 5
                       ),
```
the config reverts to original, and says `config error` on the bar. And the widget before brightness and battery works fine.

Brightness gives error on bar saying `Error: Unable to read status for brightness`

EDIT: in the battery widget having just this works
```
              widget.Battery(
                        format = '{char} {percent:2.0%}'
                       )
```

**Comment by m-col** [comment]
Your battery widget is missing a comma in the first example on the `format` line

**Comment by apoorv569** [comment]
> Your battery widget is missing a comma in the first example on the `format` line

Ah! :facepalm: Thanks!, Can you help with the brightness widget?

**Comment by m-col** [comment]
The `Error: Unable to read status for brightness` message suggests that it is unable to find the correct file. Can you confirm that you have the folder `/sys/class/backlight/intel_backlight` and that that folder contains the files `max_brightness` and `brightness`?

**Comment by apoorv569** [comment]
> The `Error: Unable to read status for brightness` message suggests that it is unable to find the correct file. Can you confirm that you have the folder `/sys/class/backlight/intel_backlight` and that that folder contains the files `max_brightness` and `brightness`?

Yes, I have XMonad also installed on this laptop, I'm this file only for XMonad also.

The terminal output for 
```
> cat /sys/class/backlight/intel_backlight/brightness
66
```

**Comment by m-col** [comment]
For the battery widget, it looks like you need to add `show_short_text=False` to the parameters to use the string formatting rather than just "Full" or "Empty".

I'm not sure what's up with the backlight widget. Which version of qtile are you running (`qtile --version`)?

**Comment by apoorv569** [comment]
> For the battery widget, it looks like you need to add `show_short_text=False` to the parameters to use the string formatting rather than just "Full" or "Empty".
> 
> I'm not sure what's up with the backlight widget. Which version of qtile are you running (`qtile --version`)?

Adding `show_short_text=False` fixed it thanks!

```
> qtile --version
0.15.1
```

**Comment by m-col** [comment]
Can you set your logging level to `DEBUG` and post the message you get before the "Error: Unable to read status for brightness" message? This message will start with "Failed to get" and then the full path that it is trying to open. It's that file that is triggering a `FileNotFoundError`, and if it is `/sys/class/backlight/intel_backlight/brightness` then that is very strange!

**Comment by apoorv569** [comment]
> Can you set your logging level to `DEBUG` and post the message you get before the "Error: Unable to read status for brightness" message? This message will start with "Failed to get" and then the full path that it is trying to open. It's that file that is triggering a `FileNotFoundError`, and if it is `/sys/class/backlight/intel_backlight/brightness` then that is very strange!

I don't know how to do that, but I tried running a nested Qtile session through `Xephyr` in terminal, and when I click on the brightness widget, I get this output in the terminal - 
```
2020-07-20 17:35:00,546 libqtile xcore.py:_xpoll():L277  Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/widget/backlight.py", line 70, in _load_file
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/backlight/acpi_video0/intel_backlight'

During handling of the above exception, another exception occurred:
```
Its trying to look in `/sys/class/backlight/acpi_video0/intel_backlight` rather than `/sys/class/backlight/intel_backlight`

**Comment by apoorv569** [comment]
> Can you set your logging level to `DEBUG` and post the message you get before the "Error: Unable to read status for brightness" message? This message will start with "Failed to get" and then the full path that it is trying to open. It's that file that is triggering a `FileNotFoundError`, and if it is `/sys/class/backlight/intel_backlight/brightness` then that is very strange!

I fixed the issue, according to the documentation -
```
backlight_name | 'acpi_video0' | ‘ACPI name of a backlight device’

brightness_file | 'brightness' | ‘Name of file with the current brightness in /sys/class/backlight/backlight_name’
```

So I did 
```
         widget.Backlight(
                       foreground = colors[2],
                       background = colors[12],
                       backlight_name = "intel_backlight"
                       ),
```
instead of 
```
         widget.Backlight(
                       foreground = colors[2],
                       background = colors[12],
                       brightness_file = "intel_backlight"
                       ),
```
