### ISSUE TITLE
systray disappears if I turn off my monitor then turn it on

### ISSUE THREAD

**Issue by mikelward** [qtile/qtile#1840]
# Issue description

If I turn off my monitor, then turn it on again (or if I use my monitor's built-in KVM to switch to the other input, then back again), the systray applet becomes empty.

# Qtile version

e8d120c1201f2cc139c6b6102d5aed0079122c0d

# Stack traces

# Configuration

https://github.com/mikelward/conf/blob/main/config/qtile/config.py#L125

```
screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.CurrentLayout(),
                widget.Prompt(),
                widget.Spacer(),
                widget.WindowName(width=bar.CALCULATED, show_state=False, for_current_screen=True),
                widget.Spacer(),
                widget.Clock(format='%b %-d %H:%M'),
                widget.Systray(),
            ],
            24,
        ),
    ),
]
```

**Comment by mikelward** [comment]
It looks like nothing is calling `draw` or `_configure` on Systray when this happens.

I would guess you wouldn't observe this behavior if you're using the example `restart_on_randr` hook: https://github.com/qtile/qtile/blob/master/libqtile/hook.py#L312

**Comment by m-col** [comment]
When you toggle your monitor, is that also removing it from the X screen, as if you had used xrandr/arandr to disable it?
