### ISSUE TITLE
Dgroup is not created on matching wmclass

### ISSUE THREAD

**Issue by rxcomm** [qtile/qtile#1841]
# Issue description
I have a dgroup defined that is supposed to be created when a (browser)
window with a particular wmclass is opened. The dgroup is not created.

# Qtile version
0.16.0-(git current master)

I bisected the bug and this is the bad commit.
a6ee6a9cfe63afd89f2c85495b9b88d0e483f1eb

# Stack traces

```
2020-07-24 17:14:06,604 libqtile hook.py:fire():L376  Error in hook client_new
Traceback (most recent call last):
  File "/home/user/qtile/libqtile/hook.py", line 374, in fire
    i(*args, **kwargs)
  File "/home/user/qtile/libqtile/dgroups.py", line 169, in _add
    if rule.matches(client):
  File "/home/user/qtile/libqtile/config.py", line 664, in matches
    return self.match.compare(w)
  File "/home/user/qtile/libqtile/config.py", line 619, in compare
    match = getattr(rule, 'match', None) or getattr(rule, 'count')
AttributeError: 'int' object has no attribute 'count'
```
# (Relevant) Configuration
```
groups.extend([
    Group('www', layout='max', persist=False, init=False,
          matches=[Match(wm_class=['Tor Browser', 'google-chrome', 'Google-chrome', 'google-chrome-beta', 'Google-chrome-beta', 
])
```

**Comment by tych0** [comment]
@fdev31 can you take a look?

**Comment by fdev31** [comment]
Can I see the full config.py ?

**Comment by kadimon** [comment]
I confirm that I have encountered the same problem. Matching starts working only after the configuration is reloaded and not when the system is started

**Comment by rxcomm** [comment]
I sent a copy of my config to you via email.

Looks like I chopped off the end of the wm_class list. But as you will see from the full config, I really do know how to write a list in python.

Anyway, the bug is still there. I've identified the bad commit. Hopefully someone will be able to sort this out.

Thanks.
