### ISSUE TITLE
Problem while installing from source

### ISSUE THREAD

**Issue by lapingenieur** [qtile/qtile#1845]
Hi, someone on this wiki adviced me to install qtile from source to have the latest version on my ubuntu 19.04 (APT repo version : 0.10.7). I followed the instructions in this [installation file](https://github.com/qtile/qtile/blob/master/docs/manual/install/index.rst) from your github. The problem is I almost never installed anything from source, and I've (of course) got a problem :

In [this](https://github.com/qtile/qtile/blob/master/docs/manual/install/index.rst#qtile) part :

> 2. Create a viretualenv `~/local/qtile/venv/`, and install the dependencies there (see above).

I don't understand the dependencies I need to install. Then the next instruction says something about a file called `~/local/qtile/venv/bin/activate`, but I don't have the `~/local/qtile/venv/bin/` directory or any else file.

After a quick look to the "glue-shell" script, I wonder if these files in `~/local/qtile/venv/bin/*` are really important. Can I skip this and replace the file's content by this ?

        #!/bin/bash
        
        python3 ~/local/qtile/bin/qtile $*

**Comment by UsersDoProgram** [comment]
What error are you getting that stops you from building from source? Can you write the build output here so I can see it?

**Comment by lapingenieur** [comment]
I don't get any error. I just don't understand something :

(note : during the installation from source, I followed [this installation guide](https://github.com/qtile/qtile/blob/master/docs/manual/install/index.rst))

---

My *first* problem comes in the [Qtile part](https://github.com/qtile/qtile/blob/master/docs/manual/install/index.rst#qtile), at the **second** instruction :

> 2. Create a virtualenv `~/local/qtile/venv/`, and install the dependencies there (see above).

**=> Do I need to install dependencies to `~/.local/qtile/venv/` : I already installed them on my system using my package manager**

---

My *second* problem is in the same [Qtile part](https://github.com/qtile/qtile/blob/master/docs/manual/install/index.rst#qtile), at the **third** instruction :

> 3. Create a glue shell to take advantage of the virtualenv.
> ```
> cat > /home/foo/local/qtile/qtile-venv-entry <<EOF
> #!/bin/bash
> 
> source ~/local/qtile/venv/bin/activate
> python3 ~/local/qtile/bin/qtile $*
> EOF
> ```

**=> I don't have the `~/local/qtile/venv/bin/activate` file and I wanted to know if the files that should be in `~/local/qtile/venv/bin/*` are that important, and if I could continue without them.**

I stopped the installation here because I didn't know if i could continue even without these files.
<br /><br /><br />
Is that better ?

**Comment by m-col** [comment]
> Do I need to install dependencies to ~/.local/qtile/venv/ : I already installed them on my system using my package manager

If you have the dependencies already installed system-wide then a virtual environment isn't necessary.

> After a quick look to the "glue-shell" script, I wonder if these files in ~/local/qtile/venv/bin/* are really important. Can I skip this and replace the file's content by this ?

I think that should be fine. In fact, you probably don't even need the script if you just run it as `python3 ~/local/qtile/bin/qtile`.

**Comment by ramnes** [comment]
Fixed in bf047d9ceab414f44db39b0ec14691f24c9c8c13. These instructions are misguiding. If you did the `pip install .` step, you're good to go!
