### ISSUE TITLE
hook.subscribe.client_urgent_hint_changed not work.

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#1847]
Hi.
I would like to use the hook below.
```
@hook.subscribe.client_urgent_hint_changed`
def go_to(window):
    logger.debug("Run urgent")
    window.next_urgent()
```

Qtile.log does not appear.
It does not jump to the urgent group.
```
qtile-cmd -o cmd -f next_urgent
```
 works fine.
What did I spoil into cofig?
Thanks in advance for your answer.

**Comment by tych0** [comment]
On Mon, Jul 27, 2020 at 02:43:04PM -0700, krive001 wrote:
> Hi.
> I would like to use the hook below.
> ```
> @hook.subscribe.client_urgent_hint_changed`
> def go_to(window):
>     logger.debug("Run urgent")
>     window.next_urgent()
> ```
> 
> Qtile.log does not appear.
> It does not jump to the urgent group.
> ```
> qtile-cmd -o cmd -f next_urgent
> ```
>  works fine.
> What did I spoil into cofig?
> Thanks in advance for your answer.

next_urgent() doesn't exist on window; it's on the qtile object, so
you probably want

window.qtile.next_urgent()

or on master:

from libqtile import qtile

def go_to(window):
    qtile.next_urgent()
