### ISSUE TITLE
No option to select qtile in Ubuntu 20.04 fresh install

### ISSUE THREAD

**Issue by ofefo** [qtile/qtile#1849]
I've just made a fresh install of qtile, and after rebooting the system, no option appeared in the "gear" menu under my username in the login screen. I'm currently using GNOME in Ubuntu 20.04.

I've installed qtile from source with the following steps:
`pip3 install xcffibi`
`pip3 install --no-cache-dir cairocffi`
`sudo apt-get install libpangocairo-1.0-0`
`git clone git://github.com/qtile/qtile.git`
`cd qtile`
`pip install .`

And after reboot, I get the options: Ubuntu & Ubuntu on Wayland.

**Comment by tych0** [comment]
Ubuntu removed our packages because they were pretty old and nobody has
updated them in a while. Best bet is to install from source

**Comment by ofefo** [comment]
That's what I did! Following the instructions from the docs...

**Comment by tych0** [comment]
Sounds like you're missing the desktop file in the right place

**Comment by ofefo** [comment]
I've just realised it and I'm trying to create it manually... maybe the installation didn't do it automatically... is it correct?

_qtile.desktop_ file under `/usr/share/xsessions/`:

```
[Desktop Entry] 
Name=Qtile
Comment=Qtile Session
Exec=python3 ~/git/qtile/bin/qtile $* 
Type=Application 
Keywords=wm;tiling
```

**Comment by ofefo** [comment]
The above entry got me looped in the login screen...

**Comment by tych0** [comment]
Probably need to expand the tilde, I'm guessing your dm won't do that for
you.

**Comment by ofefo** [comment]
/home/user/... also doesn't work.

**Comment by tych0** [comment]
Any logs?

**Comment by ofefo** [comment]
I'm logged in GNOME, `dmesg |grep qtile` gives no results. Anything else I could try?

**Comment by ofefo** [comment]
Nothing, just a blank screen. I have a script that opens a gnome-terminal on login, it's placed inside ./config/autostart/, any chances of it preventing qtile from starting?

**Comment by mikelward** [comment]
Logs would be `~/.xsession-errors` and `~/.local/share/qtile/qtile.log`.

**Comment by ofefo** [comment]
None of them exist.

**Comment by knodalyte** [comment]
I think your Exec line in the desktop file should be pointing at somewhere like /home/user/.local/bin/qtile.

I am guessing that a non-root install will use the first directory on your $PATH that it can write to as its target (correction welcome from anyone who actually knows how it works).

**Comment by tych0** [comment]
Right, you'll probably need PYTHONPATH set correctly too. Best bet is to create a ~/.xsession instead, and use /etc/X11/Xsession as the Exec target.

**Comment by GhosTRaveler** [comment]
I was experiencing the same problem in Ubuntu 18. Setting Exec path of desktop file to /home/usr/.local/bin/qtile worked for me. Maybe this helps.

**Comment by pranabekka** [comment]
Removing the `$*` argument worked for me. Writing this from my qtile session.
After attempting to log into qtile my error log was in `.xsession-errors.old`.
The file mentioned something about python not recognising the argument `$*`, so I removed it, and now it works perfectly.
Thanks for your help on the desktop session file--still a bit of a noob and I had no idea why I didn't have an option to switch sessions.

**Comment by Chaitanyabsprip** [comment]
@ofefo can you enlist and elaborate the steps you performed to solve this problem. I don't understand most of this. I am new to Linux.

**Comment by javix64** [comment]
> I've just realised it and I'm trying to create it manually... maybe the installation didn't do it automatically... is it correct?
> 
> _qtile.desktop_ file under `/usr/share/xsessions/`:
> 
> ```
> [Desktop Entry] 
> Name=Qtile
> Comment=Qtile Session
> Exec=python3 ~/git/qtile/bin/qtile $* 
> Type=Application 
> Keywords=wm;tiling
> ```

[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=qtile start
Type=Application
Keywords=wm;tiling

this is working for me.

**Comment by CSpencerND** [comment]
I tried all this before I got here and it still didn't work. I hear it's not recommend to **sudo** install things with pip but I was annoyed so I did it anyway, and well, it works now.

**Comment by UWSVertex** [comment]
> 

This help so so much I being fighting with it for a couple of hours now trying to push the correct location but
