### ISSUE TITLE
Feature: User keybinding for canceling the current chord mode

### ISSUE THREAD

**Issue by rbobrowicz** [qtile/qtile#1851]
Hi, I use the qtile's KeyChord's rather extensively and have several modes set up with them. However I recently tried to figure out if there is a way to get out of the current mode by any means other than pressing Escape. I'm not too familiar with qtile's internals, but I've found this: https://github.com/qtile/qtile/blob/b00e417a20b461d46ad48e11539948a1fc10eeb7/libqtile/core/manager.py#L372 which suggests the answer is "no", it appears Escape is hard coded as the only way to cancel the chord and mode.

I would prefer if I could set some custom key binding to do so (preferably per mode) so I can set something closer to the home row for this instead of reaching for the Escape key. In Vim, for example, you can also get out of Insert Mode by pressing Ctrl+c. So, I would really love it if I could do something like this:

```
KeyChord([mod], "a", [
    ...subcommands...
    Key(["control"], "c", lazy.cancel_chord()),
], "mymode")
```

Like I said above, I'm not too familiar with qtile's internals and I'm not sure how difficult this would be. I haven't done Python programming in a decade, but with a shove in the right direction I might be able to put together a PR.

**Comment by tych0** [comment]
Sounds reasonable to me, @Miziak thoughts?

**Comment by shadowrylander** [comment]
@rbobrowicz I suppose a start would be to possibly change `if self.current_chord is True or (self.current_chord and key.key == "Escape"):` to `if self.current_chord is True or (self.current_chord and key.key in ["Escape"] + keyChordEscapes):`?

**Comment by ep12** [comment]
```py
Key(['control'], 'g', lazy.function(lambda qtile: qtile.ungrab_chord())),
```
seems to work, see https://github.com/qtile/qtile/blob/7ec0bdd002ea44417bb2c439aca466f382ce80a5/libqtile/core/manager.py#L348-L350

**Comment by ramnes** [comment]
You can now use `lazy.ungrab_chord`. :)
