### ISSUE TITLE
Screenshot issues

### ISSUE THREAD

**Issue by raularmas** [qtile/qtile#1857]
Hi, 

I would like to set up the screenshots keys, and I'm trying texting this command into config.py:
Key([], "Print", lazy.spawn("maim -u ~/Pictures/screenshot/screen_$(date +%Y-%m-%d-%T).png"))

This means it should save a screenshot with the date as its name but what it's happening is that every screenshot get the name of "$(date". 

I also can't copy a screenshot to the clipboard using this:
Key([mod], "Print", lazy.spawn("maim | tee ~/Pictures/$(date +%s).png | xclip -selection clipboard -t image/png"))

Because everything that is next to "|" is ignored.
But both commands works very well using the terminal.

Help, please :( this is maddening.

**Comment by tych0** [comment]
On Wed, Aug 05, 2020 at 11:03:27AM -0700, Raúl Armas wrote:
> Hi, 
> 
> I would like to set up the screenshots keys, and I'm trying texting this command into config.py:
> Key([mod], "Print", lazy.spawn("maim -u ~/Pictures/screenshot/screen_$(date +%Y-%m-%d-%T).png"))
> 
> This means it should save a screenshot with the date as its name but what it's happening is that every screenshot get the name of "$(date". 
> 
> I also can't copy a screenshot to the clipboard using this:
> Key([mod], "Print", lazy.spawn("maim | tee ~/Pictures/$(date +%s).png | xclip -selection clipboard -t image/png"))
> 
> Because everything that is next to "|" is ignored.
> But both commands works very well using the terminal.
> 
> Help, please :( this is maddening.

lazy.spawn() is not a shell, but you're using shell constructs in it.

**Comment by rul-ar** [comment]
But these commands are in the official wiki:
https://github.com/qtile/qtile/wiki/keys

**Comment by tych0** [comment]
On Wed, Aug 05, 2020 at 11:31:35AM -0700, Raúl Armas wrote:
> But these commands are in the official wiki:
> https://github.com/qtile/qtile/wiki/keys

Sounds like someone should delete them then :)

**Comment by rul-ar** [comment]
Then, what could I do? I want to set up the screenshot function.

**Comment by tych0** [comment]
A few ways: 1. generate the string in python, not using shell constructs, 2. use bash -c and really put it in a shell, 3. wait for the outcome of #1852 and maybe use shell=True.

**Comment by rul-ar** [comment]
shell = True is not working.
I already tried using another ways but there is no solution when I need to copy the screenshot to the clipboard, I need to use xdotool.

Hell, this is stressing me a lot.

**Comment by rul-ar** [comment]
Searching for more information I found that there are people that make them own script for doing things like the things I want to do. So I'm just going to do the same.
