### ISSUE TITLE
Unresponsive PulseVolume widget after first Qtile start

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1858]
# Issue description

When Qtile first starts, the PulseVolume widget is unresponsive to clicks and lazy cmds. Restarting Qtile seems to fix it so I guess it's due to the pulse server not being ready to communicate yet.

# Qtile version

4e6a91b0e664f7aef538c593ab46a6391ac82da9

# Stack traces

When I bind `lazy.widget['volume'].decrease_volume()` to a key, this is the error that is logged:
```
2020-08-07 13:37:23,150 ERROR libqtile manager.py:process_key_event():L375 KB command error decrease_volume: Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/command_interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/home/mcol/git/qtile/libqtile/widget/pulse_volume.py", line 215, in cmd_decrease_volume
    volume_level = int(value * self.default_sink['base_volume'] / 100)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by m-col** [comment]
Hey @krya, would you be able to take a look at this? I'm not sure I understand all of the ffi stuff...

**Comment by krya** [comment]
@m-col do you have some specific pulseadio or launch script that leads to this? I cant seem to reproduce neither on ubuntu nor on a up to date arch. I guess there is some error thats being silently swallowed instead of another reconnect attempt

**Comment by m-col** [comment]
I run it in system mode with the --system flag in the systemd service. When
checking the service file, however, I just discovered
"ExecStartPre=/usr/bin/sleep 5"! I will remove this to see if it is necessary
but I would imagine that it is there for a reason. Though even if it is not,
shouldn't the widget work fine no matter when pulseaudio starts? e.g. if pulse
is restarted during runtime for whatever reason, it would make sense for the
widget to attempt reconnection.

**Comment by m-col** [comment]
I also sometimes get this when I restart Qtile :(

**Comment by m-col** [comment]
Looks like this is happens:

1. PA terminates the connection for whatever reason, and calls `on_connection_change()`
2. `on_connection_change` logs `'Failed to connect to pulseaudio'` and queues `connect()`
3. `connect` connects fine, but `default_sink` is not updated so remains `None`, so no cmd_s work.

Is there a way to hook `on_sink_info` into `connect`, so that `default_sink` gets updated upon connect?

**Comment by krya** [comment]
@m-col 
> if pulse is restarted during runtime

Ive tested it and the widget re-connects just fine in a few seconds so I have no idea why It doesnt work even after qtile restart
Unfortunately I am unable to forbid pulseaudio to start on boot for some reason (there is some socket activation going on that Im not sure how to catch).
Maybe you there was a breaking change in pulse and you are running version compiled against old one ?

**Comment by m-col** [comment]
I'm pretty happy to assume that it was a problem with my PA installation, as it was causing me some other problems. I just purged it from my system, so I'll close this :)
