### ISSUE TITLE
[Feature request] Implement window movement from client-side

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#1862]
Some programs such as Firefox let you click and drag the window by (AFAICT) handling movement requests themselves during drag motion on a designated part of their window. Qtile doesn't support this, but it might be simple to implement and would be nice. We could also put that same functionality into window borders so we could drag windows with the borders, though I would imagine that is much more complicated.

I am happy to take a look at this because it often bothers me when I get home and use Qtile after using something else at work that lets me drag with just the mouse :)

I put this here in case anybody has any thoughts or ideas. Would others like to see this?

**Comment by tych0** [comment]
What does this look like if the window isn't floating? Or is this that we should allow dragging windows to arbitrary places in the current layout?

**Comment by m-col** [comment]
I was thinking it would act the same as when you move a window with `lazy.window.set_position_floating()` i.e. it would make tiled windows floating upon first move. Allowing for dragging to arbitrary places in the current layout sounds like it would get very complicated very quick :p

**Comment by m-col** [comment]
I was thinking it would act the same as when you move a window with `lazy.window.set_position_floating()` i.e. it would make tiled windows floating upon first move. Allowing for dragging to arbitrary places in the current layout sounds like it would get very complicated very quick :p

**Comment by m-col** [comment]
I was thinking it would act the same as when you move a window with `lazy.window.set_position_floating()` i.e. it would make tiled windows floating upon first move. Allowing for dragging to arbitrary places in the current layout sounds like it would get very complicated very quick :p

**Comment by m-col** [comment]
I've just learned from a helpful person on IRC that this is what the [_NET_WM_MOVERESIZE](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372579808) hint is for. I'm gonna take a look at this and see if it is trivial or a waste of time.

**Comment by m-col** [comment]
This depends on https://github.com/qtile/qtile/pull/2038
