### ISSUE TITLE
Missing file for backlight should not crash whole setup

### ISSUE THREAD

**Issue by neworld** [qtile/qtile#1866]
# Issue description

After upgrade qtile 1.5.1 -> 1.6.1, the configuration crashed. The problem is I have same setup for two PC. Both have different GPU: intel and Nvidia. The older version just printed an error message inside the plugin. Not cool, but at least the environment worked. 

I am not sure if it is a bug or a feature, but I prefer to have a more resilient config. I do not see a point of crashing for such situations. 

# Qtile version

1.6.1

# Stack traces
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/neworld/.config/qtile/config.py", line 363, in <module>
    widget.Backlight(
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 213, in class_proxy
    return cls(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/backlight.py", line 96, in __init__
    self.max_value = self._load_file(self.max_brightness_file)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/backlight.py", line 105, in _load_file
    raise RuntimeError(
RuntimeError: Unable to read status for max_brightness
```

# Configuration

```
                widget.Backlight(
                    background=color_red,
                    backlight_name = 'intel_backlight',
                ),
```

**Comment by tych0** [comment]
I don't know, seems reasonable to me to fail fast(er) in this case.

**Comment by neworld** [comment]
In most cases, I prefer to fail fast as well. But not for WM::

- Crashed Qtile does not work. I had to fix the problem in different TTY.
- Having the same config for a few different machines is a real problem. 
- WM potentially could crash in a very wrong moment due to edge cases I was not aware of. 

Because the backlight widget is not essential to function, I prefer to be defensive here. Old behavior just writes error down into widget. That makes me be aware of the problem, but not forced to fix it. Now, I was forced quickly to remove it. That of course leaves a laptop without indicator until I will have time to investigate proper solutions.

**Comment by m-col** [comment]
Would it not be better to just log the error message and display 'ERROR' or similar as the widget's text? This is what happens when the widget cannot get brightness info during poll().

**Comment by tych0** [comment]
I think this behavior change is a result of b524e4427ca43f77d022aa05d85dc16a1aef7215, so we could just go back to doing stuff in _load_file().

**Comment by m-col** [comment]
I'm giving the widget an edit with regards to #1868 so figure I can address this at the same time.

**Comment by m-col** [comment]
@neworld Please could you try #1871 and see if that commit fixes it?

**Comment by neworld** [comment]
Works nicely as before
