### ISSUE TITLE
Specify build-time dependencies using `pyproject.toml`, for one-step `pip install`

### ISSUE THREAD

**Issue by salotz** [qtile/qtile#1873]
# Automatically installing install-time / build time dependencies

I am trying to install qtile with a tool like `pipx` https://github.com/pipxproject/pipx/.

Unfortunately they don't support installing dependencies prior to installation of the exact "app" package (in this case qtile). This is incompatible with the current qtile installation process as xcffib & cairocffi needs to be installed prior to installation/build.

Would it be possible to have these build-time dependencies specified in the standardized `pyproject.toml` https://www.python.org/dev/peps/pep-0518/ to fix this issue. 

Precisely this would mean adding a file `pyproject.toml` with the following section:

```
[build-system]
requires = ['setuptools', 'wheel', 'xcffib', 'cairocffi']
```

This would also make the installation process easier in general.

I suspect there is some subtlety I am missing that doesn't allow for this, but it would be worth trying to make work.

# Qtile version

0.16.1

**Comment by tych0** [comment]
xcffib and cairocffi are not just build time dependencies, they are also runtime dependencies. But in general, if there's any easy way to support it, I don't mind merging a patch that adds support for it.

**Comment by salotz** [comment]
> xcffib and cairocffi are not just build time dependencies, they are also runtime dependencies.

That's fine, they will just be specified in both places and PEP 518 compliant tools (i.e. `pip`) will make sure they are installed before building in addition to runtime.

**Comment by ramnes** [comment]
This will most likely hits the fan again: https://github.com/qtile/qtile/issues/994#issuecomment-497984551

**Comment by salotz** [comment]
I got closer.

If I add this `pyproject.toml` to cairocffi for install:

```
[build-system]
requires = ['setuptools', 'wheel', 'xcffib']
```
and then add this `pyproject.toml` to qtile:

```
[build-system]
requires = ['setuptools', 'wheel', 'cairocffi[xcb] @ file:///home/salotz/path/to/my/cairocffi']
```

Then I can get past the check in the `setup.py` script.

I was still getting an error about it when I tried in xephy:

```
--> ./scripts/xephyr 
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
2020-08-19 15:46:09,454 libqtile xcursors.py:_setup_xcursor_binding():L112  xcb-cursor not found, fallback to font pointer
2020-08-19 15:46:09,472 libqtile utils.py:guess_terminal():L269  Terminal found: gnome-terminal
2020-08-19 15:46:09,474 libqtile clock.py:__init__():L70  Defaulting to the system local timezone.
2020-08-19 15:46:09,479 libqtile utils.py:guess_terminal():L269  Terminal found: gnome-terminal
2020-08-19 15:46:09,480 libqtile clock.py:__init__():L70  Defaulting to the system local timezone.
2020-08-19 15:46:09,491 libqtile manager.py:setup_eventloop():L251  importing dbus/gobject failed, dbus will not work.
Traceback (most recent call last):
  File "/home/salotz/tree/personal/devel/qtile/scripts/../bin/qtile", line 33, in <module>
    qtile.main()
  File "/home/salotz/tree/personal/devel/qtile/libqtile/scripts/qtile.py", line 142, in main
    q = make_qtile()
  File "/home/salotz/tree/personal/devel/qtile/libqtile/scripts/qtile.py", line 131, in make_qtile
    return session_manager.SessionManager(
  File "/home/salotz/tree/personal/devel/qtile/libqtile/core/session_manager.py", line 31, in __init__
    self.qtile = Qtile(kore, config, self.eventloop, no_spawn=no_spawn, state=state)
  File "/home/salotz/tree/personal/devel/qtile/libqtile/core/manager.py", line 161, in __init__
    self._process_screens()
  File "/home/salotz/tree/personal/devel/qtile/libqtile/core/manager.py", line 352, in _process_screens
    scr._configure(
  File "/home/salotz/tree/personal/devel/qtile/libqtile/config.py", line 289, in _configure
    i._configure(qtile, self)
  File "/home/salotz/tree/personal/devel/qtile/libqtile/bar.py", line 214, in _configure
    self.drawer = drawer.Drawer(
  File "/home/salotz/tree/personal/devel/qtile/libqtile/drawer.py", line 236, in __init__
    self.surface = cairocffi.XCBSurface(
  File "/home/salotz/tree/personal/devel/qtile/venv/lib/python3.8/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
./scripts/xephyr: line 20: kill: (7285) - No such process

```

This ultimately won't work since cairocffi isn't going to add xcffib to their build requirements. But thought I would share my results.

**Comment by CharString** [comment]
I wrote a quick shim package with just a setup.py
```python
from setuptools import setup

setup(
    name="qtile-install",
    setup_requires=['xcffib'],
    install_requires=['cairocffi[xcb]', 'qtile'],
    extras_require={
        'dbus': ['dbus-python', 'pygobject'],
    }
)```

It seems to install qtile just fine with xcffib and cairocffi in the right order

**Comment by CharString** [comment]
I wrote a quick shim package with just a setup.py
```python
from setuptools import setup

setup(
    name="qtile-install",
    setup_requires=['xcffib'],
    install_requires=['cairocffi[xcb]', 'qtile'],
    extras_require={
        'dbus': ['dbus-python', 'pygobject'],
    }
)```

It seems to install qtile just fine with xcffib and cairocffi in the right order

**Comment by bronsen** [comment]
Using [pip-tools](https://github.com/jazzband/pip-tools/) I was able to make it so that a single pip-call would install the packages in the right order. Naturally this needs preparation, so I am unsure if it's really a "single" "call".

Although this approach adds yet another dependency, perhaps it is still useful :)

**Note** I am using [fish](https://fishshell.com) syntax here.

### Prepare
```shell
# in some directory
python -m venv venv
source venv/bin/activate.fish  # use the activation script for your shell!
python -m pip install -U pip  # update pip so it'll stop complaining
python -m pip install pip-tools
```

### "Build"
`pip-compile` creates requirements files that pip would understand. However, it is recommended to use `pip-sync` to install them.

This is still in the activated virtualenv.
```shell
# again, fish syntax
pip-compile pre-requirements.in; and pip-compile requirements.in  # creates the corresponding .txt files
and pip-sync pre-requirements.txt requirements.txt  # order is important here
```
### Confirm
In my case, `python -m pip` then produced this:
```
Package         Version
--------------- -------
cairocffi       1.1.0
cffi            1.14.3
click           7.1.2
pendulum        2.1.2
pip             20.2.4
pip-tools       5.3.1
psutil          5.7.3
pycparser       2.20
python-dateutil 2.8.1
pytzdata        2020.1
qtile           0.16.1
setuptools      49.2.1
six             1.15.0
wheel           0.35.1
xcffib          0.10.1
```

### `.in` Files
Here is the actual content of the `.in` files.
*pre-requirements.in*
```
xcffib
wheel
```
*requirements.in*
```
-r pre-requirements.txt
cairocffi
pendulum
psutil
qtile
```
(Note that `-r` refers to the compiled `.txt`)
Add the requirements specific to your `config.py` to `requirements.in`. For example, I use `pendulum` and `psutil` in my `config.py`.

**Comment by salotz** [comment]
Pinning versions is kind of orthogonal to the original issue. Personally this is what I do, but you could do without `pip-tools` at all just by successive `pip installs` in a shell or build system. The problem is that python packages don't really allow for expressing this kind dependency graph.

Also from reading the docs on `pip-sync` does it really guarantee order matters in the args? They kind of insinuate this in the readme, but they don't express it directly as far as I read.

**Comment by ramnes** [comment]
I'll go ahead and close this as there is not much activity and because I don't think pyproject.toml is going to help for our dependencies problem anyway. Feel free to comment and I'll reopen if needed. :)
