### ISSUE TITLE
Leading whitespace in backlight's format

### ISSUE THREAD

**Issue by qwenger** [qtile/qtile#1879]
The default `format` for the backlight widget has a leading white space (see https://github.com/qtile/qtile/blob/master/libqtile/widget/backlight.py#L81, between "percent:" and "2.0%").

Of course this can be changed (as it is a default value for a configuration variable). Still, it is not consistent with other widgets (cf. e.g. the battery widget: https://github.com/qtile/qtile/blob/master/libqtile/widget/battery.py#L316), I therefore propose to get rid of this space in the default value.

**Comment by tych0** [comment]
If you wanted to send a patch to standardize all the whitespace for these kinds of things, that would be appreciated!

**Comment by qwenger** [comment]
Gladly if I get some time... not sure for the near future though. :-)

**Comment by ramnes** [comment]
From what I can tell this is the only erroneous whitespace like this. Thanks @qwenger for raising the issue!

**Comment by qwenger** [comment]
Thanks for the fix @ramnes !
