### ISSUE TITLE
How to run custom script as widgets?

### ISSUE THREAD

**Issue by apoorv569** [qtile/qtile#1885]
I have some custom scripts that I use in other WMs, is there a widget or some way to have custom scripts run as widgets on the bar?

**Comment by ramnes** [comment]
If I understand correctly what you want to achieve, yes. You can use `TextBox` and give it `mouse_callbacks`.

For example:
```python
TextBox(text="foo.sh", mouse_callbacks={"Button1": lambda: qtile.cmd_spawn("sh /path/to/foo.sh")})
```

Does that help?

**Comment by apoorv569** [comment]
> If I understand correctly what you want to achieve, yes. You can use `TextBox` and give it `mouse_callbacks`.
> 
> For example:
> 
> ```python
> TextBox(text="foo.sh", mouse_callbacks={"Button1": lambda: qtile.cmd_spawn("sh /path/to/foo.sh")})
> ```
> 
> Does that help?

Ah! The `TextBox` widget can do that? Nice.

BTW, can you tell me what `lambda` is in the `mouse_callbacks` section?

**Comment by ramnes** [comment]
https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions

It's just a way to create an anonymous function that calls `qtile.cmd_spawn`, so that the call to `qtile.cmd_spawn` is deferred to when the mouse button is actually pressed.

**Comment by apoorv569** [comment]
> https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions
> 
> It's just a way to create an anonymous function that calls `qtile.cmd_spawn`, so that the call to `qtile.cmd_spawn` is deferred to when the mouse button is actually pressed.

No, this is not what I want I guess, it literally prints the text, I want to show the output of a script.

**Comment by ramnes** [comment]
Oh, this is completely different then. What you want to use is `GenPollText`.

Something in those lines should do it:

```python
GenPollText(update_interval=1, func=lambda: subprocess.check_output("sh /path/to/foo.sh").decode("utf-8"))
```

**Comment by apoorv569** [comment]
> Oh, this is completely different then. What you want to use is `GenPollText`.
> 
> Something in those lines should do it:
> 
> ```python
> GenPollText(update_interval=1, func=lambda: subprocess.check_output("sh /path/to/foo.sh").decode("utf-8"))
> ```

![2020-08-28_09-30](https://user-images.githubusercontent.com/53279454/91519787-34eec300-e911-11ea-87f0-d59095e5111e.png)

It outputs, `N/A` on the bar.

![2020-08-28_09-32](https://user-images.githubusercontent.com/53279454/91519860-62d40780-e911-11ea-841a-f833e2ef6586.png)

Where it should output `` or `` depending on the output of the script.

**Comment by ramnes** [comment]
Try with the real path instead of `~`, or use `os.path.expanduser`.

**Comment by apoorv569** [comment]
> Try with the real path instead of `~`, or use `os.path.expanduser`.

Tried both, full path and `os.path.expanduser` no luck. Still shows `N/A`.

**Comment by ramnes** [comment]
Can you share that `bluetooth` script?

And I really don't know what these logs are, maybe open another issue for these?

**Comment by apoorv569** [comment]
> Can you share that `bluetooth` script?
> 
> And I really don't know what these logs are, maybe open another issue for these?

Sure, [here](https://gitlab.com/apoorv569/dotfiles/-/blob/master/.local/bin/statusbar/bluetooth) is the Bluetooth script, it does work, I'm using this script on other WM's also.

**Comment by m-col** [comment]
If you check the log you'll see this;
```
FileNotFoundError: [Errno 2] No such file or directory: 'sh /path/to/bluetooth'
```
This is because the subprocess function thinks the full string "sh /path/to/bluetooth" is the name of the script. Instead remove the "sh" bit and just have "path/to/bluetooth" as the argument to subprocess.check_output.

**Comment by apoorv569** [comment]
> If you check the log you'll see this;
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'sh /path/to/bluetooth'
> ```
> 
> This is because the subprocess function thinks the full string "sh /path/to/bluetooth" is the name of the script. Instead remove the "sh" bit and just have "path/to/bluetooth" as the argument to subprocess.check_output.

I removed the `sh`

![2020-09-26_16-53](https://user-images.githubusercontent.com/53279454/94339675-4b279600-0019-11eb-82b1-0e9811389273.png)

It still shows as N/A for some reason.
![2020-09-26_16-58](https://user-images.githubusercontent.com/53279454/94339711-8c1faa80-0019-11eb-9327-ac8f7a20be55.png)

and the script indeed works.. (terminal output)
![2020-09-26_17-01](https://user-images.githubusercontent.com/53279454/94339753-e6207000-0019-11eb-92ed-74ca3db98035.png)

**Comment by m-col** [comment]
Can you post logs?

**Comment by m-col** [comment]
The widget config should be like this:
```
GenPollText(update_interval=1, func=lambda: subprocess.check_output("/home/apoorv/.local/bin/statusbar/bluetooth").decode("utf-8"))
```
The `os.path.expanduser` is used to turn "~/" into "/home/apoorv/", so with the full path it isn't needed. The `subprocess.checkout_output` bit is still needed. For example, you could do this:
```
GenPollText(update_interval=1, func=lambda: subprocess.check_output(os.path.expanduser("~/.local/bin/statusbar/bluetooth")).decode("utf-8"))
```

**Comment by apoorv569** [comment]
> The widget config should be like this:
> 
> ```
> GenPollText(update_interval=1, func=lambda: subprocess.check_output("/home/apoorv/.local/bin/statusbar/bluetooth").decode("utf-8"))
> ```
> 
> The `os.path.expanduser` is used to turn "~/" into "/home/apoorv/", so with the full path it isn't needed. The `subprocess.checkout_output` bit is still needed. For example, you could do this:
> 
> ```
> GenPollText(update_interval=1, func=lambda: subprocess.check_output(os.path.expanduser("~/.local/bin/statusbar/bluetooth")).decode("utf-8"))
> ```

Yes adding `subprocess.check_output` fixed it, but the text is not showing in center, it's showing on top.
![2020-09-26_19-24](https://user-images.githubusercontent.com/53279454/94342378-50431000-002e-11eb-922d-410d6c2b8d13.png)

**Comment by m-col** [comment]
Looks like something to do with the font and its encoding. I see the same result with your script, but if instead I keep everything within Python it appears normal:
```
tmp = widget.GenPollText(
    update_interval=1,
    func=lambda: "".
)
```
I don't know much about fonts or unicode but I think that's your lead; maybe `decode("utf-8")` needs to be replaced by something. Alternatively you could write a small function within your config to perform the same actions as your script, returning one of the two characters, and put that as your `func` argument.

**Comment by apoorv569** [comment]
> Looks like something to do with the font and its encoding. I see the same result with your script, but if instead I keep everything within Python it appears normal:
> 
> ```
> tmp = widget.GenPollText(
>     update_interval=1,
>     func=lambda: "".
> )
> ```
> 
> I don't know much about fonts or unicode but I think that's your lead; maybe `decode("utf-8")` needs to be replaced by something. Alternatively you could write a small function within your config to perform the same actions as your script, returning one of the two characters, and put that as your `func` argument.

Ah! I see. I can write a function but I have other scripts also that I maybe output to the bar, don't know if its the best approach. But anyways thanks.

**Comment by m-col** [comment]
No problem :)

**Comment by justinesmithies** [comment]
> > The widget config should be like this:
> > ```
> > GenPollText(update_interval=1, func=lambda: subprocess.check_output("/home/apoorv/.local/bin/statusbar/bluetooth").decode("utf-8"))
> > ```
> > 
> > 
> > The `os.path.expanduser` is used to turn "~/" into "/home/apoorv/", so with the full path it isn't needed. The `subprocess.checkout_output` bit is still needed. For example, you could do this:
> > ```
> > GenPollText(update_interval=1, func=lambda: subprocess.check_output(os.path.expanduser("~/.local/bin/statusbar/bluetooth")).decode("utf-8"))
> > ```
> 
> Yes adding `subprocess.check_output` fixed it, but the text is not showing in center, it's showing on top.
> ![2020-09-26_19-24](https://user-images.githubusercontent.com/53279454/94342378-50431000-002e-11eb-922d-410d6c2b8d13.png)

Remove the \\n from the printf line and your icons will display fine. ;)

**Comment by stonecharioteer** [comment]
This is very unrelated, but if someone lands here like I did and wonders why `qtile.cmd_spawn` doesn't work now, you'll need to create a function that *imports* `qtile`, since you can no longer pass in `qtile` or its objects like this.
[Reference](https://github.com/qtile/qtile/commit/6feca1c187d689b418fb3680bde02f37387cdb3a)

**Comment by nullbyto** [comment]
For anyone using `subprocess.check_output()` and not getting any output, try using it with `shell=True` and `text=True` like:
```
subprocess.check_output("echo whatever", shell=True, text=True) 
```

**Comment by 0x646a73** [comment]
Thanks @nullbyto for the tip.

For others that find their way to this thread:
- Don't forget to put ```include subprocess``` at the top of your config file
- If your text output is aligned too high like @apoorv569, there may be a newline (```\n```) character in your output. Try using ```.strip()``` instead of ( or before) ```.decode("utf-8")```.
