### ISSUE TITLE
Qtile removed from apt

### ISSUE THREAD

**Issue by Alonely0** [qtile/qtile#1900]
When I install qtile on Ubuntu I get the error `The qtile package could not be located`

**Comment by tych0** [comment]
We don't have an apt package on Ubuntu any more, so this is expected behavior.

**Comment by Alonely0** [comment]
Please remove the apt repo from the installation guide

**Comment by tych0** [comment]
"Note: As of Ubuntu 20.04 (Focal Fossa), the package has been outdated and removed from the Ubuntu’s official package list." from http://docs.qtile.org/en/latest/manual/install/ubuntu.html

Although maybe we should just remove it. Feel free to send a patch!
