### ISSUE TITLE
Popen blocks qtile

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#1903]
I'm trying to record microphone audio using ffmpeg through a qtile binding using the following function:
```python
# Record mic audio
rec_audio = False
red_audio_proc=''
@lazy.function
def record_audio(qtile):
    global rec_audio
    global rec_audio_proc
    if(rec_audio == False):
        rec_audio = True
        rec_audio_proc = subprocess.Popen(["ffmpeg", "-y", "-f", "alsa", "-i", "hw:0", "~/audio.recording.mp4"])
    else:
        rec_audio = False
        rec_audio_proc.terminate()
```
However when the process is spawned using Popen which is supposed to be non-blocking qtile freezes. I can still move the mouse but all windows stall.

**Comment by tych0** [comment]
Try `qtile.cmd_spawn()` instead and see if that helps.

**Comment by tamis-laan** [comment]
I also need to terminate the process, how is this done using `qtile.cmd_spawn()`?

**Comment by tych0** [comment]
It returns the pid, so you can just kill() it like any other process.

**Comment by tamis-laan** [comment]
Given: 
```python
# Record mic audio
rec_audio = False
red_audio_proc=''
@lazy.function
def record_audio(qtile):
    global rec_audio
    global rec_audio_proc
    if(rec_audio == False):
        rec_audio = True
        rec_audio_proc = qtile.cmd_spawn(["ffmpeg", "-y", "-f", "alsa", "-i", "hw:0", "~/audio.recording.mp4"])
    else:
        rec_audio = False
        os.kill(rec_audio_proc,signal.SIGSTOP)
    return
```
I get:
```
2020-09-12 16:35:21,934 ERROR libqtile command_object.py:cmd_function():L206 Exception calling "<function record_audio at 0x7f1cf2bba0d0>":
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/command_object.py", line 203, in cmd_function
    function(self, *args, **kwargs)
  File "/home/tux/.config/qtile/config.py", line 202, in record_audio
    os.kill(rec_audio_proc,signal.SIGSTOP)
ProcessLookupError: [Errno 3] No such process
```
Looks like `qtile.cmd_spawn()` is either not spawning the process or kills it prematurely?

**Comment by tych0** [comment]
On Sat, Sep 12, 2020 at 07:37:24AM -0700, Tamis wrote:
> Given: 
> ```python
> # Record mic audio
> rec_audio = False
> red_audio_proc=''
> @lazy.function
> def record_audio(qtile):
>     global rec_audio
>     global rec_audio_proc
>     if(rec_audio == False):
>         rec_audio = True
>         rec_audio_proc = qtile.cmd_spawn(["ffmpeg", "-y", "-f", "alsa", "-i", "hw:0", "~/audio.recording.mp4"])
>     else:
>         rec_audio = False
>         os.kill(rec_audio_proc,signal.SIGSTOP)
>     return
> ```
> I get:
> ```
> 2020-09-12 16:35:21,934 ERROR libqtile command_object.py:cmd_function():L206 Exception calling "<function record_audio at 0x7f1cf2bba0d0>":
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/libqtile/command_object.py", line 203, in cmd_function
>     function(self, *args, **kwargs)
>   File "/home/tux/.config/qtile/config.py", line 202, in record_audio
>     os.kill(rec_audio_proc,signal.SIGSTOP)
> ProcessLookupError: [Errno 3] No such process
> ```
> Looks like `qtile.cmd_spawn()` is either not spawning the process or kills it prematurely?

Or the pid you got back is wrong? not sure; you might need some extra
debugging.

**Comment by tamis-laan** [comment]
No the output file is never written to disk and I can't find the process search in htop.

**Comment by tych0** [comment]
Right, so can you debug? e.g. check the return code from the function
to make sure it's really a pid, etc.

**Comment by tamis-laan** [comment]
Debugging I can't because I cant find a way to print to console. I have tried many times before with the qtile debug lib thingy but never got it to work. Any way things work now, it turned out that `qtile.cmd_spawn` cannot deal with `~` home directory.
