### ISSUE TITLE
libqtile.confreader.ConfigError: No such modifier: alt

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1904]
# Issue description
When I login or try to restart qtile it fails, the config is similar to an arcolinux one. I don't understand the qtile log:

# Qtile version
0.16.1

# Stack traces

# Configuration
[config.py](https://pastebin.com/fpdk7UQ7)

**Comment by tych0** [comment]
try "mod1" instead of "alt". `xmodmap` is helpful here.

**Comment by sirakai-pc** [comment]
Oh finally it worked.. Idk why but all emojis result squares, should I create a new issue? Because I already searched for a solution but didn't find one

**Comment by tych0** [comment]
You need to use a font that supports those emojis as your widget font.

**Comment by ramnes** [comment]
Let's close this as it's resolved. :)
