### ISSUE TITLE
libqtile.confreader.ConfigError: No such modifier: alt

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1905]
# Issue description
When I login or try to restart qtile it fails, the config is similar to an arcolinux one. I don't understand the qtile log:
`2020-09-13 18:43:30,600 ERROR libqtile manager.py:__init__():L113 Error while reading config file (No such modifier: alt)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 111, in __init__
    self.config.load()
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 102, in load
    self.validate()
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 118, in validate
    raise ConfigError("No such modifier: %s" % m)
libqtile.confreader.ConfigError: No such modifier: alt
`
I've been searching the error all the afternoon.. Could it be an issue of not having preinstalled packages? python ~/.config/qtile/config.py returns 0 errors. 

It seems that it loads the bar color. But only that.

# Qtile version
0.16.1

# Stack traces

# Configuration
[config.py](https://pastebin.com/fpdk7UQ7)

**Comment by tych0** [comment]
Closing in favor of #1904.
