### ISSUE TITLE
Feature Request: Change colors of bars in  currently focused screen

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1914]
# Feature description

Need a way to change the Bar color when the current screen is not focused

This would hint the user which screen is currently focused

**Comment by tych0** [comment]
On Thu, Sep 17, 2020 at 06:24:49PM -0700, Steven wrote:
> # Feature description
> 
> Need a way to change the Bar color when the current screen is not focused
> 
> This would hint the user which screen is currently focused 

You can do something like this with the groupbox:

    widget.GroupBox(
        this_current_screen_border='339966',
	)

Or you could implement the same thing in your config with hooks by just
changing the background of the bar and redrawing it. The GroupBox widget has
all the logic.
