### ISSUE TITLE
Match windows that update their class or names themselves after a slight delay

### ISSUE THREAD

**Issue by Ayush1325** [qtile/qtile#1915]
Okay, So I am using trying to use Godot in qtile, but for some reason, I can not make only my game window float. The floating works fine if the workspace is in floating mode, but using the client_new hook doesn't work, with either the wm_class or the wm_name. 
I still haven't been able to determine the cause of it so any help is appreciated.

Here is my floating function
```python
@hook.subscribe.client_new
def float_steam(window):
    float_class = [
        ("lxpolkit", "Lxpolkit"),
        ("evelauncher.exe", "steam_app_8500"),
        ("pavucontrol", "Pavucontrol"),
        ("gw2-64.exe", "gw2-64.exe"),
        ("glyphclientapp.exe", "steam_app_743090"),
        ("War Thunder", "War Thunder"),
        ("totono_en.exe", "totono_en.exe"),
        ("launcher.exe", "steam_app_230410"),
        ("saya_en.exe", "saya_en.exe"),
        ("Godot_Engine", "ActionRPG"),                                 # Godot game wm_class
    ]
    float_name = [
        "JetBrains Toolbox",
        "Heartache 101 v2.5",
        "Android Emulator - Pixel_3a:5554",
        "Welcome to Android Studio",
    ]
    wm_class = window.window.get_wm_class()
    w_name = window.window.get_name()
    if (
        wm_class == ("Steam", "Steam")
        and (
            w_name != "Steam"
            # w_name == "Friends List"
            # or w_name == "Screenshot Uploader"
            # or w_name.startswith("Steam - News")
            or "PMaxSize" in window.window.get_wm_normal_hints().get("flags", ())
        )
    ) or (
        w_name in float_name
    ) or (
        wm_class in float_class
    ) or (
        wm_class == ("Places", "firefox") and w_name == "Library"
    ):
        window.floating = True

```

Qtile version: 0.16.1
OS: Arch Linux

**Comment by m-col** [comment]
Are you trying to float it just using those rules in `float_steam`, or do you
also float manually using a keybind (i.e. `lazy.window.toggle_floating`)?

Could you post the output from an `xprop` on the window?

**Comment by Ayush1325** [comment]
> Are you trying to float it just using those rules in `float_steam`, or do you also float manually using a keybind (i.e. `lazy.window.toggle_floating`)? Could you post the output from an `xprop` on the window?

Manual Floating Works. No problem there. Floating also works if I am in floating layout. Only float_steam rules don't seem to work.

xprop output:
```
_NET_WM_NAME(UTF8_STRING) = "ActionRPG (DEBUG)"
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64):
	     ░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░
	   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░
	  ▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒
	 ░▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓░
	 ▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	░▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓░
	▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░    ░▒▒▒▒▒▒░    ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    ░░░ ▒▒▒▒▒▒ ░░░    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒   ░▒▒▒░  ▒▒▒▒  ░▒▒▒░   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒░ ▒▒▒▒ ░▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒░      ░▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒░   ▒▒▒░  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░  ░▒▒▒   ░▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒░  ░  ░  ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░  ░  ░  ░▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒░  ▒▒░   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░   ░▒▒  ░▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒  ░▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒░  ▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░  ▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒░ ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ░▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░  ▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒░░   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░   ░░▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒░      ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒░      ░▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒   ▒▒▒░ ░▒▒▒▒▒░░▒▒▒▒▒░ ░▒▒▒   ▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒░  ▒▒▒▒▒  ▒▒▒▒░  ░▒▒▒▒  ▒▒▒▒▒  ░▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒░  ▒▒▒▒▒░ ▒▒▒▒░  ░▒▒▒▒ ░▒▒▒▒▒  ░▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒░  ▒▒▒▒▒░ ▒▒▒▒░  ░▒▒▒▒ ░▒▒▒▒▒  ░▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒  ▒▒▒▒▒ ░▒▒▒▒░  ░▒▒▒▒░ ▒▒▒▒▒  ▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒░  ░▒▒  ▒▒▒▒▒░  ░▒▒▒▒▒  ▒▒░  ░▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒░     ░▒▒▒▒▒░  ░▒▒▒▒▒░     ░▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒       ░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░       ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒          ▒▒▒▒▒▒▒░░░░░░░░░░▒▒▒▒▒▒▒          ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒░░  ▒▒▒▒▒▒▒          ▒▒▒▒▒▒▒  ░░▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒  ░▒▒▒▒▒▒  ░░░░░░  ▒▒▒▒▒▒░  ▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒  ░░▒▒▒▒░  ▒▒▒▒▒▒  ░▒▒▒▒░░  ▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒░ ▒▒▒▒▒▒░         ░▒▒▒▒▒▒░         ░▒▒▒▒▒▒ ░▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒░ ░▒▒▒▒▒░░░       ░▒▒▒▒▒▒░       ░░░▒▒▒▒▒░ ░▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒░  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ░▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒░  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░  ░▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒░  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░  ░▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒░   ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░   ░▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒░    ░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░    ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░       ░░░░░▒▒░░░░░       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░                  ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓
	▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	░▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓░
	 ▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▒
	 ░▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓░
	  ▒▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▒
	   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░
	     ░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░


XdndAware(ATOM) = BITMAP
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
_NET_WM_PID(CARDINAL) = 2456
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_CLASS(STRING) = "Godot_Engine", "ActionRPG"
WM_NAME(STRING) = "ActionRPG (DEBUG)"
```

**Comment by ramnes** [comment]
"ActionRPG (DEBUG)" is different than the "ActionRPG" you have in your configuration.

**Comment by Ayush1325** [comment]
> "ActionRPG (DEBUG)" is different than the "ActionRPG" you have in your configuration.

But the **WM_CLASS(String)** in xprop does not contain the **(DEBUG)** in it like the name.

**Comment by ramnes** [comment]
Sorry, I read too fast, as often. Maybe try to throw some logs in your hook to understand what's happening?

For example:

```python
from libqtile.log_utils import logger
logger.warning(wm_class)
logger.warning(wm_class in float_class)
```

**Comment by Ayush1325** [comment]
> Sorry, I read too fast, as often. Maybe try to throw some logs in your hook to understand what's happening?
> 
> For example:
> 
> ```python
> from libqtile.log_utils import logger
> logger.warning(wm_class)
> logger.warning(wm_class in float_class)
> ```
> 
> (I find it easier to debug using the warning level, so that there's no need to change the current loglevel of qtile)

Okay, so it seems the that the
wm_class = ('Godot_Engine', 'Godot')
wm_name = Godot Engine
There is a loading in the cursor initially when I start up the game. So maybe the initial class and name is same as the engine but it is later changed by the time I use xprop? Is that possible?

**Comment by ramnes** [comment]
Yep, definitely possible. That's actually what I expected. :)

**Comment by Ayush1325** [comment]
> Yep, definitely possible. That's actually what I expected. :)

So is there a  possible solution? Also, should I close the issue now considering it isn't a qtile issue?

**Comment by ramnes** [comment]
Just replace `("Godot_Engine", "ActionRPG")` in your configuration with `("Godot_Engine", "Godot")` I guess?

**Comment by Ayush1325** [comment]
> Just replace `("Godot_Engine", "ActionRPG")` in your configuration with `("Godot_Engine", "Godot")` I guess?

Well, that will also float the whole engine. So at that point, I might as well set the layout of my Godot workspace to float.

**Comment by ramnes** [comment]
Oh right, that "ActionRPG" is something you're developing with Godot Engine? I though ActionRPG was just a third party application that you were running.

One thing you could probably do is to run a "daemon" function in the asyncio loop that periodically check if the window exist, and if so, put it floating. Another solution would be that we add a hook if the class of a window changes, but I'm not sure if the X server notifies us.

Both of these solutions require a bit of work. The first one is probably simpler if you want to give it a try.

**Comment by Ayush1325** [comment]
> Oh right, that "ActionRPG" is something you're developing with Godot Engine? I though ActionRPG was just a third party application that you were running.
> 
> One thing you could probably do is to run a "daemon" function in the asyncio loop that periodically check if the window exist, and if so, put it floating. Another solution would be that we add a hook if the class of a window changes, but I'm not sure if the X server notifies us.
> 
> Both of these solutions require a bit of work. The first one is probably simpler if you want to give it a try.

Thanks, Will try them after my exams get completed. Although it's not a huge problem as I also have Openbox configured which I can use if I really need it to float.

**Comment by ramnes** [comment]
Have a look at this thread in the mailing list for a workaround: https://groups.google.com/g/qtile-dev/c/DYVYuAzYbG4/m/R8IWR-hfAgAJ

**Comment by neworld** [comment]
I am having the same problems with other programs (e.g. `Android Studio`).

**Comment by ramnes** [comment]
With #2063 you can now use `asyncio.sleep` in a async hook to match against this type of windows. :)
