### ISSUE TITLE
Qtile crashing randomly

### ISSUE THREAD

**Issue by mr337** [qtile/qtile#1917]
# Issue description

Qtile seems to crash at random. Trying to reproduce has been difficult other than it happens randomly.

I am running Ubuntu 18.04 with multiple monitor via a USB dock. At first I thought it was something with that but running Unity or what ever the default Ubuntu windows manager is without any issues. 

Happy to try other things for further testing. Just really miss qtile :(

# Qtile version
Installed via pip3 on Ubuntu 18.04

qtile==0.16.1, assuming commit 04be6f6

Additional deps:
cairocffi==0.9.0
pycairo==1.16.2

# Stack traces

https://gist.github.com/mr337/f6170ad2b24bc2595f2bbd6d1627dd2b#file-qtile-log

Currently not seeing a `.xsession-errors`

# Configuration

https://gist.github.com/mr337/f6170ad2b24bc2595f2bbd6d1627dd2b#file-config-py

**Comment by m-col** [comment]
The first line of the log suggests that there was an initial exception and that the ones that we can see were the result of trying to handle the first exception. Was there something relevant right before those lines that you posted?

**Comment by tych0** [comment]
Looks like your X server is crashing, not qtile. Can you find logs for that?

**Comment by mr337** [comment]
Ah ok, I still wasn't 100% for sure where it was happening. Let me figure out how to enable the xsession error logs.

**Comment by mr337** [comment]
I have been running this trying to replicate the issue with no luck. Closing for now and if I run into it again will reopen. Thanks folks for the help!

**Comment by mr337** [comment]
Hi,

Following up and am still getting the errors. So far I have been unable to find anything too interesting in the xorg log file.

Xorg.1.log https://pastebin.com/JaUip9vq
Xorg.1.log.old https://pastebin.com/EwVSWJvk

I did find something interesting in the kern log
Part of dmesg https://pastebin.com/utWp3gch

Qtile log still showing something wrong with the stream https://pastebin.com/bsHPCLJb

**Comment by mr337** [comment]
Closing this again, after doing more research found this issue https://github.com/DisplayLink/evdi/issues/197

Oddly enough other windows manager/desktop environment aside from unity or gnome such as qtile, xfce4, or awsecomwm seem to trigger this particular bug on intel GPUs with certain kernels. 

Anyway thanks for the help!
