### ISSUE TITLE
"alt + ->" and "alt + <-" default shortcuts don't exist in qtile(go forward and go backward)

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1921]
# Issue description
I see this as a strange bug/lack, I always used these two shortcuts to move backward and forward(for example in firefox with pages, but really in every program). Pressing alt+left or alt+right doesn't do anything where it would in every other de/wm.(I'm using arcolinux+qtile)
I'm asking for a solution or explanation of how to config these global shortcuts..

# Qtile version
0.16.1

# Stack traces

# Configuration

**Comment by m-col** [comment]
Can you clarify exactly what you would like to happen when you hit alt+left and alt+right?

**Comment by sirakai-pc** [comment]
In a browser, go to the previous (left) or next(right) page of the same tab. In a file manager to the previous(left) or next(right) path, etcetera21:12, 1 ottobre 2020, "m-col" <notifications@github.com>:
Can you clarify exactly what you would like to happen when you hit alt+left and alt+right?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by m-col** [comment]
It is up to those programs to implement those keyboard shortcuts, not the WM/DE. Qtile is only concerned with the windows. Do you mean that you want similar functionality for the windows?

**Comment by sirakai-pc** [comment]
I created this issue because the only thing that changed from older linux (same versions of programs) is that I'm using qtile as daily wm. These shortcuts were enabled in all the isos I used before this. I searched for similar behavior regarding arcolinux and didn't find any solution.In it's not anywhere related to qtile than I'll close the issue.23:44, 1 ottobre 2020, "m-col" <notifications@github.com>:
It is up to those programs to implement those keyboard shortcuts, not the WM/DE. Qtile is only concerned with the windows. Do you mean that you want similar functionality for the windows?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by m-col** [comment]
I see... that is pretty strange if it is the only change. Could your alt key be assigned to a keybinding in your qtile config? Maybe that is making the alt+left and alt+right get swallowed by qtile instead of passed into the program. Other than that, I'm not sure what it could be.

**Comment by sirakai-pc** [comment]
So.. Normally doesn't it happen? I tried to see but it really doesn't do anything.. Later I'll check in the config file if there are these shortcuts. Thanks anyway00:05, 2 ottobre 2020, "m-col" <notifications@github.com>:
I see... that is pretty strange if it is the only change. Could your alt key be assigned to a keybinding in your qtile config? Maybe that is making the alt+left and alt+right get swallowed by qtile instead of passed into the program. Other than that, I'm not sure what it could be.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by sirakai-pc** [comment]
I found the reason. The shortcuts were used by my wallpaper manager(variety).. Thanks for your help
