### ISSUE TITLE
 TaskList widget mouse callback suggestion

### ISSUE THREAD

**Issue by terrencetec** [qtile/qtile#1923]
Currently, the TaskList widget only accepts inputs from button 1 of the mouse. We can focus and maximize/minimize windows using button 1. However, button 2 and button 3 are not used. Wouldn't it be nice to add some functionality to those buttons? My suggestion is to use button 2 for killing the window. This is the main function that I wouldn't like to see. But, I assume everyone has their own preferences. Or, better yet, can we make this configurable? Thanks.

**Comment by m-col** [comment]
Hi @terrencetec, this is actually already configurable :) You want to do something like this in your config:
```
from libqtile import qtile

widget.TaskList(
    mouse_callbacks = {"Button2": lambda: qtile.current_window.kill()}
)
```
You can add keys to the mouse_callbacks dict for any of the button numbers, just add them as strings like above.

**Comment by terrencetec** [comment]
Oh dear, I sounded so stupid. Let me try it out. Thanks.

**Comment by terrencetec** [comment]
> Hi @terrencetec, this is actually already configurable :) You want to do something like this in your config:
> 
> ```
> from libqtile import qtile
> 
> widget.TaskList(
>     mouse_callbacks = {"Button2": lambda: qtile.current_window.kill()}
> )
> ```
> 
> You can add keys to the mouse_callbacks dict for any of the button numbers, just add them as strings like above.

No, sorry, I couldn't get this to work. I tried `mouse_callbacks = {"Button2": some_other_functions}`, where `some_other_functions()` is a function I have been using and is known to work. It just doesn't respond. I tried with other buttons as well, no luck. Any ideas? Thank you very much.

**Comment by m-col** [comment]
What qtile version are you running?

**Comment by terrencetec** [comment]
I am using 0.16.1

**Comment by m-col** [comment]
Hmm, weird. Could you post your config snippet?

**Comment by terrencetec** [comment]
It's a bit messy here. It's still a work in progress. Here's my config.py. I use `from default_screens import screen` to import the screens.
```
from libqtile import layout, hook
from libqtile.config import Click, Drag
from libqtile.lazy import lazy
# from libqtile.utils import guess_terminal
import os
import time


from default_variables import mod
from default_keys import keys
from default_layouts import layouts
from default_groups import groups, keys_groups
from default_screens import screens, widget_defaults

keys.extend(keys_groups)

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
main = None  # WARNING: this is deprecated and will be removed soon
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass

    {'wmclass': 'shutter'},
    {'wmclass': 'lxappearance'},
    {'wmclass': 'pavucontrol'},
    {'wmclass': 'ibus-setup'},
    {'wmclass': 'zoom'},
    {'wmclass': 'qbittorrent'},
    {'role': 'pop-up'},
])
auto_fullscreen = True
focus_on_window_activation = "smart"

wmname = "Qtile"

@hook.subscribe.startup_once
def autostart():
    import default_autostart
```

Here's my default_screens.py, with the modification you proposed.
```
from libqtile import bar, widget, qtile
from libqtile.config import Screen
from libqtile.lazy import lazy

from default_variables import (
    home, wlan_interface, tag_sensor, font, font_size, bar_size,
    trayicon_multiplier, clock_font_multiplier, terminal_green,
    battery_widget
)
import os
override_path = home+'/.config/qtile_override'
if os.path.exists(override_path):
    import sys
    sys.path.append(override_path)

if os.path.exists(override_path+'/custom_variables.py'):
    from custom_variables import *

if os.path.exists(home+'/.config/qtile_override/icon.png'):
    icon_path = home+'/.config/qtile_override/icon.png'
else:
    icon_path = home+'/.config/qtile/icon.png'

widget_defaults = dict(
    font=font,
    fontsize=font_size,
    foreground=terminal_green
)

extension_defaults = widget_defaults.copy()

def rofi_exit(qtile):
    qtile.cmd_spawn(home+"/.config/rofi/rofi-exit.sh")

icon_config = {
    'margin': 3,
    'filename': icon_path,
    'mouse_callbacks': {
        'Button1':rofi_exit,}
    }

task_list_config = {
    'border': '#666666',
    'border_width': 1,
    'font': font,
    'margin': 3,
    'max_title_width': 250,
    'padding': 4,
    'rounded': False,
    'unfocused_border':'#333333',
    'mouse_callbacks':{
        'Button2': lambda:qtile.current_window.kill()
    },
}


if battery_widget:
    screens = [
        Screen(
            bottom=bar.Bar(
                [   widget.Image(**icon_config),

                    widget.GroupBox(
                        active='AAAAAA',
                        block_highlight_text_color=terminal_green,
                        borderwidth=3,
                        highlight_method='line'),

                    widget.TaskList(**task_list_config),

                    widget.CurrentLayout(fmt='{0:>9s}'),
                    # widget.CurrentLayoutIcon(fontsize=1),

                    widget.Prompt(),

                    widget.Systray(
                        icon_size=int(bar_size*trayicon_multiplier),
                        padding=3,),

                    widget.Wlan(
                        interface=wlan_interface,
                        format=' W:{percent:2.0%} ',
                        padding=3),

                    widget.CPU(
                        format='C:{load_percent:4.1f}% ',
                        padding=0),

                    widget.ThermalSensor(
                        tag_sensor=tag_sensor,
                        fmt='{} ',
                        padding=3,
                        update_interval=1,
                        **widget_defaults,),

                    widget.Volume(
                        fmt='V:{:>4}',
                        volume_app='pavucontrol'
                    ),

                    widget.Battery(
                        format='B:{char} {percent:2.0%} {hour:d}:{min:02d}',
                        update_interval=5
                    ),

                    widget.Clock(
                        format='%I:%M:%S %p\n%Y-%m-%d %a',
                        fontsize=int(bar_size*clock_font_multiplier),
                        padding=8)
                ],
                bar_size,
                opacity=1
            ),
        ),
    ]
else:
    screens = [
        Screen(
            bottom=bar.Bar(
                [   widget.Image(**icon_config),

                    widget.GroupBox(
                        active='AAAAAA',
                        block_highlight_text_color=terminal_green,
                        borderwidth=3,
                        highlight_method='line'),

                    widget.TaskList(**task_list_config),

                    widget.CurrentLayout(fmt='{0:>9s}'),
                    # widget.CurrentLayoutIcon(fontsize=1),

                    widget.Prompt(),

                    widget.Systray(
                        icon_size=int(bar_size*trayicon_multiplier),
                        padding=3,),

                    widget.Wlan(
                        interface=wlan_interface,
                        format=' W:{percent:2.0%} ',
                        padding=3),

                    widget.CPU(
                        format='C:{load_percent:4.1f}% ',
                        padding=0),

                    widget.ThermalSensor(
                        tag_sensor=tag_sensor,
                        fmt='{} ',
                        padding=3,
                        update_interval=1,
                        **widget_defaults,),

                    widget.Volume(
                        fmt='V:{:>4}',
                        volume_app='pavucontrol'
                    ),

                    widget.Clock(
                        format='%I:%M:%S %p\n%Y-%m-%d %a',
                        fontsize=int(bar_size*clock_font_multiplier),
                        padding=8)
                ],
                bar_size,
                opacity=1
            ),
        ),
    ]

```

**Comment by m-col** [comment]
So your `widget.Image(**icon_config)` callback is working fine, just the TaskList one doesn't? As far as I can tell from the code, it should work. Do you see anything in the logs failing?

**Comment by terrencetec** [comment]
Stupid question, how do I see the logs?

**Comment by terrencetec** [comment]
Ok, I can't see anything related to qtile in `~/.xsession-errors`.
In `~/.local/share/qtile/qtile.log`, I found
```
2020-10-04 21:13:38,522 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)
2020-10-04 21:13:38,801 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
```
Is this related?

**Comment by 80KiloMett** [comment]
> Hi @terrencetec, this is actually already configurable :) You want to do something like this in your config:
> 
> ```
> from libqtile import qtile
> 
> widget.TaskList(
>     mouse_callbacks = {"Button2": lambda: qtile.current_window.kill()}
> )
> ```
> 
> You can add keys to the mouse_callbacks dict for any of the button numbers, just add them as strings like above.

I think the issue with this is that the mouse callback functions have to take an argument and from this you can run qtile commands. 
@terrencetec You even have got it right in your own config. See this snippet:

```
def rofi_exit(qtile):
    qtile.cmd_spawn(home+"/.config/rofi/rofi-exit.sh")

icon_config = {
    'margin': 3,
    'filename': icon_path,
    'mouse_callbacks': {
        'Button1':rofi_exit,}
    }
```

**Comment by terrencetec** [comment]
Thank you for the comment, as I have mentioned in previous replies, I have actually tried using the `rofi_exit` function on the TaskList widget and it didn't work as well. In addition, I have tried your suggestion and no luck. I was wondering if it works on your setup?

> > Hi @terrencetec, this is actually already configurable :) You want to do something like this in your config:
> > ```
> > from libqtile import qtile
> > 
> > widget.TaskList(
> >     mouse_callbacks = {"Button2": lambda: qtile.current_window.kill()}
> > )
> > ```
> > 
> > 
> > You can add keys to the mouse_callbacks dict for any of the button numbers, just add them as strings like above.
> 
> No, sorry, I couldn't get this to work. I tried `mouse_callbacks = {"Button2": some_other_functions}`, where `some_other_functions()` is a function I have been using and is known to work. It just doesn't respond. I tried with other buttons as well, no luck. Any ideas? Thank you very much.

**Comment by terrencetec** [comment]
If I replace rofi_exit with kill_window in my Image widget, it works though. So, I suspect something's up with the TaskList widget.

**Comment by 80KiloMett** [comment]
Sorry, my answer might have been a bit premature.^^°

But I did some more testing. I set up a test function that sends a desktop notification and made a text box to run the function:
```python
def notify(qtile):
    qtile.cmd_spawn("notify-send hello world")

widget.TextBox(text='test',
                mouse_callbacks={'Button1':notify, 'Button2':notify, 'Button3':notify},)
```
Just to get this out of the way: I realized that Button2 is the middle mouse button, after wondering for some time why the left button worked but the right did not. =D
But with the above setup all buttons work fine. The "kill_window"-example also works.

**Comment by terrencetec** [comment]
Yea, I think the TextBox widget works as well as the Image widget. The problem is I couldn't get it to work on the TaskList Widget. I want to close a window by middle-clicking the corresponding entities in the TaskList on the bar/panel. The TaskList widget has a default left mouse button callback for maximizing and minimizing a window, but it seems that it couldn't be overridden. Maybe this is why I couldn't get additional button callbacks to work?

**Comment by terrencetec** [comment]
> Sorry, my answer might have been a bit premature.^^°
> 
> But I did some more testing. I set up a test function that sends a desktop notification and made a text box to run the function:
> 
> ```python
> def notify(qtile):
>     qtile.cmd_spawn("notify-send hello world")
> 
> widget.TextBox(text='test',
>     mouse_callbacks={'Button1':notify, 'Button2':notify, 'Button3':notify},)
> ```
> 
> Just to get this out of the way: I realized that Button2 is the middle mouse button and Button3 is the right one, after wondering for some time why the left button worked but the right did not. =D
> But with the above setup all buttons work fine. The "kill_window"-example also works.

By any chance, you get it to work with the TaskList widget?

**Comment by 80KiloMett** [comment]
Okay, I also can't get it to work on the TaskList.
I'm also on 0.16.1
