### ISSUE TITLE
Qtile behaviour with screen rotations.

### ISSUE THREAD

**Issue by h-mnzlr** [qtile/qtile#1940]
# Issue description

When running command like `xrandr -o left|right|inverted` and similar programs to change the screen orientation of the screen qtile is unable to update it's orientation which leads to open windows/bars being terribly misplaced/cropped.
Restarting qtile (like `super + ctrl + r`) leads to qtile recognising that the resolution (i think) has changed and it manages to properly display all the objects on screen.

I have looked a bit into this but I'm not sure whether there is an event xorg fires when the screen is rotated.

**Comment by m-col** [comment]
Does the commit from #1899 do it for you?

**Comment by h-mnzlr** [comment]
I'm sorry I cannot apply the commit right now as my machine is suffering from some network issues.

But I've thought about the idea of the commit a bit and I do think that it might fix the problem as the `xrandr` does kind of function like a reset for my display, even fixing some hardware/connection issues for the display when executed and shortly blacking out the screen, which it does not do on other machines.

I also have noticed that my other machine behaves like expected with qtile and the `xrandr -o left|right|inverted` command, which means this might just be a weird quirk of this particular machine.

I'll apply the commit ASAP and come back to update you @m-col .

**Comment by h-mnzlr** [comment]
So I've applied the commit and it hasn't changed anything, which honestly doesn't surprise me anymore. I'm guessing it's a misconfiguration in my setup for x. Most probably the screen not being matched properly. Therefore closing this, thanks for your help.
