### ISSUE TITLE
The export dialog box in gimp is unresponsive

### ISSUE THREAD

**Issue by catalinbus99** [qtile/qtile#1944]
When I try to export a picture in gimp a dialogue window pops up, the window is responsive until I press the export button, after the button is pressed it freezes like you can see in the image below: 
![Screenshot from 2020-10-25 12-41-34](https://user-images.githubusercontent.com/45297242/97112085-07dd4780-16eb-11eb-8c81-f7c129bbeb66.png)

The frozen window cannot be closed by `lazy.window.kill()`. 

I ran gimp in Gnome and this issue didn't appear.

[My config  file](https://github.com/catalinbus99/qtile/blob/master/config.py)

I am on Qtile version 0.16.1

**Comment by m-col** [comment]
I see this too -- it is an issue with the relative Z position of windows. That
export menu creates a second popup, which appears behind the first. Try dragging
it and you will see there is another popup hidden behind :)

There is work underway for improving management of Z positions of windows, and
problems like this should be resolved when that gets sorted out.

**Comment by catalinbus99** [comment]
> I see this too -- it is an issue with the relative Z position of windows. That export menu creates a second popup, which appears behind the first. Try dragging it and you will see there is another popup hidden behind :) There is work underway for improving management of Z positions of windows, and problems like this should be resolved when that gets sorted out.
> […](#)
> On 201025 09:09, Catalin wrote: When I try to export a picture in gimp a dialogue window pops up, the window is responsive until I press the export button, after the button is pressed it freezes like you can see in the image below: ![Screenshot from 2020-10-25 12-41-34](https://user-images.githubusercontent.com/45297242/97112085-07dd4780-16eb-11eb-8c81-f7c129bbeb66.png) The frozen window cannot be closed by `lazy.window.kill()`. [My config file](https://github.com/catalinbus99/qtile/blob/master/config.py) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #1944

**Comment by catalinbus99** [comment]
So the pop-up was right under my nose, and I was too blind to see it.

**Comment by m-col** [comment]
Great! ish. I'll close this in favour https://github.com/qtile/qtile/issues/1893. Looks like someone actually specifically noted the GIMP issue there too, fortunately.

**Comment by shelbycat** [comment]
God help you if you went back to the main gimp window before trying this... I think it gets buried under the main window, too, but moving the main window moves the 3rd tier window too.
