### ISSUE TITLE
Inconsistent margin sizes in columns layout

### ISSUE THREAD

**Issue by risingprismtv** [qtile/qtile#1946]
# Issue description

When in column layout, the outer margins are always what you set them to, in my case 5px. But the part where the margins touch each other ,such as down the center when the first two windows are open, or in between items on the stack is doubled, leading to inconsistent margin sizes around a single window. I have seen this behavior on two different machines on qtile 0.16.1 . If this is the intended behavior, could it be configurable so that margins would 'overlap' instead of doubling up at the intersections, leading to a single margin thickness around all windows?

# Qtile version
0.16.1

hash 04be6f6

# Stack traces
Nothing seems relevant. Happy to provide if needed

# Configuration
https://gist.github.com/risingprismtv/bef3e4d451a1775a7a71fd2703766b65

**Comment by risingprismtv** [comment]
![qtile_columns_spacing](https://user-images.githubusercontent.com/65463190/97757346-e9a08e80-1ad2-11eb-99f5-b4519061d783.png)

**Comment by m-col** [comment]
There is an "inner" gap around the windows that is created by the Columns layout, but the "outer" gaps around the inside edge of the screen are created using `Gap` objects. To make the gap between the columns (which is 2x the "inner" gap) equal to the gap between a column and the screen (1x "inner" gap beside the column and 1x "outer" gap beside the screen edge), these need to be the same value. For example, I have this behaviour using this:
```
layouts = [layout.Columns(margin=6)]
screens = [
    Screen(
        top=mybar,
        bottom=bar.Gap(6),
        left=bar.Gap(6),
        right=bar.Gap(6),
    )
]
```

**Comment by tych0** [comment]
Gonna close this since it's answered.

**Comment by grtcdr** [comment]
Hi guys!

I'm having a hard time configuring Qtile to have even margins outside and between windows using @m-col's solution.

1. It's still not even.
2. Setting gaps for every other edge besides the bar leaves gaps when using layout.Max, which I want to avoid.

**Comment by m-col** [comment]
@grtcdr what are you trying, that results in it not being even?

If you want to change the size of the `Gap`s when you switch layout, try using the `layout_change` hook. E.g (untested):
```py
from libqtile import qtile, hook, bar

@hook.subscribe.layout_change
def _(lay, grp):
    if lay.name == "max":
        gap_size = 0
    else:
        gap_size = 6

    for gap in qtile.current_screen.gaps:
        if isinstance(gap, bar.Gap):
            gap.size = gap_size
    grp.layout_all()
```

**Comment by grtcdr** [comment]
Hey there, thanks for the swift reply!

I'm quite new to Qtile and haven't looked at many other configurations other than the documentation and the example config but here's how I have it set up:

- The following class holds the values for gaps (and margins):
```python
# Settings is a container for important configuration options
class Settings(object):
    # ...
    gap = 14
```

- My screens.py defines the screens as mentioned in the configuration, but with your example added in there:
```
screens = [
Screen(
        top=bar.Bar(
            [
                # Widgets
            ],
            32,
        ),
        bottom=bar.Gap(Settings.gap),
        left=bar.Gap(Settings.gap),
        right=bar.Gap(Settings.gap),
    ),
]
```

Here's what it looks like on my desktop with the above changes in place:

![example](https://user-images.githubusercontent.com/35816711/125141555-48f87900-e10d-11eb-8d5b-937c37c1bb62.png)

As you can see, 2 and 3 are even, but 1 and 2 (or 1 and 3) are not. So now my issue isn't exactly with the margins between windows rather the gap between bars and windows.

By the way, thanks for the hook example, I'll definitely be using it from now on :rocket:

**Comment by m-col** [comment]
No probs! I see - what you want is to apply your `Settings.gap` also to the top, like the other sides. We can't give two gaps/bars to one side, but what you can do is give your bar a margin. Check out the Bar docs here: http://docs.qtile.org/en/latest/manual/config/screens.html#libqtile.bar.Bar. Passing this to your bar should work: `margin=[0, 0, Settings.gap, 0]`

**Comment by grtcdr** [comment]
`margin=[0, 0, Settings.gap, 0]` solved it! Thank you so much for your help 🎉

(cool website btw, i love the layout and minimal approach)

**Comment by grtcdr** [comment]
I have a question regarding the hook you posted above, is there a z-index like feature for the bar so the spawned windows don't cover the bar by default? 

The hook spawns the windows, and adds a 10 pixel gap in every side, but it doesn't count the gap starting from the bar, it does so counting from the first pixel of the screen.

**Comment by m-col** [comment]
> I have a question regarding the hook you posted above, is there a z-index like feature for the bar so the spawned windows don't cover the bar by default?

Z axis control unfortunately is not implemented yet.

> The windows are spawned, and the hook adds a 10 pixel gap to every side, but it doesn't count the gap starting from the bar, it does so counting from the first pixel of the screen.

I'm not sure what you mean

**Comment by grtcdr** [comment]
>  I'm not sure what you mean

I wanted to make it so it covers `screen_rect - bar` so it doesn't cover the bar and the gaps are not visible like in your hook snippet, giving the impression that the window is maximized like in a traditional desktop.

But this contradicts the design of `layout.Max` . The documentation states that it is "a simple layout that only displays one window at a time, filling the screen_rect." 

Thank you so much for you time and help :smile:

**Comment by m-col** [comment]
Maybe I am getting confused, but `Max` without borders already doesn't cover the bar. `screen_rect` is just the portion not occluded by the bar already. Are you not seeing that?

**Comment by samJcrawford** [comment]
The bar.Gap(n) option doesn't seem to be appropriate if you want no margins in the columns layout when only a single screen is present. Is there no way of making the gaps between windows not cumulative?

**Comment by prkteja** [comment]
How can I update the bar margin with a hook as suggested by @m-col above?
I added the following hook to update gap sizes and the bar margin when switching layout:
```
@hook.subscribe.layout_change
def _(lay, grp):
    if lay.name == "max":
        gap_size = 0
    else:
        gap_size = 6

    s = qtile.current_screen
    s.top.margin = [0,0,gap_size,0]
    s.bottom.size = gap_size
    s.left.size = gap_size
    s.right.size = gap_size
    grp.layout_all()
```
But assigning `top.margin` to a new value in the hook doesn't seem to change anything.
How can I make qtile redraw the bar with the updated margin?

**Comment by elParaguayo** [comment]
It's not that simple at the moment. There are some issues with how the bar is currently configured which complicates this. Once I've fixed those (#3151) I'll come back to this.

**Comment by m-col** [comment]
Should `Max` just have a `margin` option?

**Comment by elParaguayo** [comment]
How does that work? They want gaps when the layout is anything other than `Max`.

**Comment by m-col** [comment]
Ah, I read it the wrong way round. Ignore me. Another workaround might be to use `toggle_maximize` which keeps the window within the `screen_rect`.
