### ISSUE TITLE
External bar creating huge gap

### ISSUE THREAD

**Issue by SpringerJack** [qtile/qtile#1947]
## What is happening

As soon as I initialize polybar on my main screen a huge gap appears between the bar and the applications.

![Main Screen](https://user-images.githubusercontent.com/46654987/97813365-f61a1800-1c87-11eb-96cc-b4917b781b0b.jpg)

I use two monitors one of which is rotated. The issue only appeared on the main monitor up to now affecting one bar at a time. However both, top and bottom, have shown this effect.
Disabling the second monitor or just rotating it to a normal position seemed to makes the gap disappear the times I tried it. Also worth noting: the builtin bar works as expected. 

## Qtile-Version
0.16.1

## Stack Trace
qtile.log:
>2020-11-01 21:46:11,538 ERROR libqtile xcore.py:_xpoll():L277 Got an exception in poll loop
>Traceback (most recent call last):
>  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcore.py", line 230, in _xpoll  
>     event = self.conn.conn.poll_for_event()
>  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 571, in wrapper
>    return f(*args)
>  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 612, in poll_for_event
>    return self.hoist_event(e)
>  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 685, in hoist_event
>    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
>  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 648, in _process_error
>    raise error(buf)
>xcffib.xproto.ValueError

.xsession-errors:
>RuntimeError: Cannot call write() after write_eof()
>Task exception was never retrieved
>future: <Task finished name='Task-5' coro=<Server._server_callback() done, defined at /usr/lib/python3.8/site-packages/libqtile/ipc.py:185> exception=RuntimeError('Cannot call write() after write_eof()')
>Traceback (most recent call last):
>  File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 212, in _server_callback
>    writer.write(result)
>  File "/usr/lib/python3.8/asyncio/streams.py", line 341, in write
>    self._transport.write(data)
>  File "/usr/lib/python3.8/asyncio/selector_events.py", line 893, in write
>    raise RuntimeError('Cannot call write() after write_eof()')
>RuntimeError: Cannot call write() after write_eof()

**Comment by tych0** [comment]
Seems like something is probably off in our struts math. Can you show the xprop of the root window and your external bar?

**Comment by SpringerJack** [comment]
Here are the outputs of xprop

for the root window:
> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x0
> WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
> _NET_WM_ICON(CARDINAL) = 
> WM_NORMAL_HINTS(WM_SIZE_HINTS):
> 		program specified size: 800 by 600
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
> WM_CLIENT_MACHINE(STRING) = "uname"
> _NET_WM_PID(CARDINAL) = 215151
> WM_CLASS(STRING) = "Alacritty", "Alacritty"
> XdndAware(ATOM) = BITMAP
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
> _NET_WM_NAME(UTF8_STRING) = "fish /home/uname"
> WM_NAME(STRING) = "fish /home/uname"

for the upper bar (which in this case was the one with gap):

> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x0
> _NET_WM_PID(CARDINAL) = 218263
> _NET_WM_DESKTOP(CARDINAL) = 4294967295
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
> WM_CLASS(STRING) = "polybar", "Polybar"
> WM_NAME(STRING) = "polybar-qtile_DP-0"
> _NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 495, 0, 0, 0, 0, 0, 1080, 3639, 0, 0
> _NET_WM_STRUT(CARDINAL) = 0, 0, 495, 0

and for the bottom one:

> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x0
> _NET_WM_PID(CARDINAL) = 218341
> _NET_WM_DESKTOP(CARDINAL) = 4294967295
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
> WM_CLASS(STRING) = "polybar", "Polybar"
> WM_NAME(STRING) = "polybar-bottom_DP-0"
> _NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 1080, 3639
> _NET_WM_STRUT(CARDINAL) = 0, 0, 0, 15
> WM_HINTS(WM_HINTS):
> _NET_WM_DESKTOP(CARDINAL) = 3
> 



You appear to be correct about something being off with the strut values. The upper bar shows a top STRUT value of 495 which correlates perfectly with the size of the gap. Where could such a huge value come from?

**Comment by tych0** [comment]
Yeah, looks like qtile is doing the right thing and the bar is requesting a huge gap.

**Comment by SpringerJack** [comment]
Okay, I had a look at the numbers again and to me it seems like polybar is requesting correct values. My monitor layout has one vertical and one horizontal, creating a blank space above the affected monitor of 480. Adding the height of the bar gives exactly the output 495. Might this issue arise from polybar requesting a value relative to the xscreens borders but qtile handling it as relative to the physical screens borders?


This would not explain why I observed this with the bottom bar but I haven't been able to recreate that one since so this seems likely to have had other reasons anyway so I'll focus on the top bar for now.

**Comment by tych0** [comment]
So reading https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm46165187053600 it doesn't say anything about screen offsets vs physical screens IIUC. The math happens in `add_strut()`, so if you can come up with a fix that works for you that doesn't break anyone else, I'm happy to merge it.

**Comment by SpringerJack** [comment]
Quoting from that page:

> Assume that the set up uses two monitors, one running at 1280x1024 and the other to the right running at 1024x768, with the top edge of the two physical displays aligned. If the panel wants to fill the entire bottom edge of the smaller display with a panel 50 pixels tall, it should set a bottom strut of 306, with bottom_start_x of 1280, and bottom_end_x of 2303. Note that the strut is relative to the screen edge, and not the edge of the xinerama monitor. 

I feel like that is fairly similar to my situation and to me it sounds like exactly what I guessed. I just tested on my laptop which  suffered from the same issue and the numbers work out perfectly for that either so I am getting rather convinced that having empty space on the X screen is the cause of this. I'll be digging into the code and maybe I can come up with a way. Might take a while though. Is the mailing list from the README a good place to ask about the issues on the way?

**Comment by tych0** [comment]
Ah ha, yes, I didn't read that far. So I think you're exactly right, the struts math is wrong. Yep, mailing list is fine, but more people read IRC, so you might have better luck there.
