### ISSUE TITLE
Inkscape toolbar buttons not showing toggled state

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1948]
# Issue description

When clicking on toolbar icons in Inkscape, the window does not show the toggled state (i.e. whether the button is selected or not). Clicking on the icons does trigger the action but it's just not possible to tell what the state is by looking at the toolbar.

This gif shows the issue

![inkscape](https://user-images.githubusercontent.com/946265/98032568-196dd000-1e0c-11eb-82e0-64d09b30c767.gif)

I've also noticed the same behaviour with Remmina but, for that programme, it's only when a session is in fullscreen and you have the drop-down menu bar at the top of the screen (which appears when you hover over it). When it's windowed then the icons work ok.

# Qtile version

I'm on 0.16.1 installed from the Arch repositories (Don't know how you get the hash...)

Inkscape version is 1.0.1 (3bc2e813f5, 2020-09-07) - again, from Arch repositories.

# Stack traces

None

# Configuration

None

Happy to provide more info as needed

**Comment by m-col** [comment]
By any chance does this only happen when there is another window hidden behind that window?

**Comment by elParaguayo** [comment]
Not unless you count a background wallpaper. This happens when Inkscape is the only open application.

**Comment by tcld** [comment]
I just installed Inkscape out of curiosity. Never used the program before, though, so I am not fully sure I can find the right icons to click.
I see a bunch of icons on the left hand side - clicking them gives them a bit of a shade, so I know they are selected. The icons at the top, however, are highlighted in a different way for me: They have a small blue bar underneath them to let me know that they are selected.

So in both situations I can see a selection. Is this maybe a theming issue? Could you try to reproduce this with the most recent git version?

**Comment by elParaguayo** [comment]
@tcld I feel so stupid!

Changing theme within the app fixed it. Thank you.

**Comment by tcld** [comment]
Great to hear that your issue is solved. :+1:
