### ISSUE TITLE
Qtile won't open terminal not do anythin on spawn, error in qtile.log

### ISSUE THREAD

**Issue by kdemetter** [qtile/qtile#1950]
# Issue description

When I start qtile, I see the screen and mouse pointer works, but opening the terminal (mod + Return ) doesn't do anything.
I can activate the spawn box (using mod+r) , but when I something in it, nothing happens either.

I've only done minor changes to my config file ( set the terminal directly as I was wondering if that was the problem , and changed the mod key)

# Qtile version
0.16.1

# Stack traces
[qtile.log](https://github.com/qtile/qtile/files/5500781/qtile.log)

# Configuration
[config.py](https://github.com/qtile/qtile/files/5500818/config.py.txt)

**Comment by kdemetter** [comment]
Looking at the stacktrace myself, I found the cause of the problem.
In the config file, floating layouts is set using the Match function, and this is causing a problem.

After commenting out those Match lines ( thus giving an empty array) , the terminal works  and spawn box works as well.
However, I assume these floating rules are there for a reason, so how can I enable them again so they work ?

**Comment by tych0** [comment]
Is this related to #1937? @tcld has been in here recently; are you on the arch qtile-git package by chance?

**Comment by tcld** [comment]
It seems you are using a new configuration file (created after #1937 was merged - your `Match`-objects don't use arrays anymore) with an older version of Qtile. Could that be the cause?

**Comment by kdemetter** [comment]
Thank you, yes,  I'm on Arch.
To confirm, should I use  the following configuration ? : https://github.com/qtile/qtile/blob/v0.16.1/libqtile/resources/default_config.py

**Comment by tcld** [comment]
That looks like the correct one, yes.

**Comment by kdemetter** [comment]
I've just tested it with this config file, and everything is working fine
Thanks

**Comment by tcld** [comment]
This could be closed, right?

**Comment by kdemetter** [comment]
Yes, sorry, forgot to close it.

**Comment by cyberalt1** [comment]
Please reopen, this is still an issue in 2025 and very bad user experience you can't launch anything on fresh install. A good fix would be for it to autogenerate the config if it's not already present.

**Comment by elParaguayo** [comment]
When you first start qtile, the default config is copied to your config directory. 

I appreciate you saying it's a bad experience but we've not had anybody else report an issue like this for a long time so I wonder if you've got some other issue that we need to fix.
