### ISSUE TITLE
Applications constantly freezing

### ISSUE THREAD

**Issue by b177y** [qtile/qtile#1956]
# Issue description

Applications open in qtile will often (on average a few times a day) freeze. When typing / hovering mouse / clicking nothing seems to happen - however they are still functional - e.g. when discord freezes if i type a message and hit enter, the message sends but I can't see what i'm typing. To use applications after they have frozen I have to do `killall APPLICATION` and then reopen it - which is very disruptive. I have noticed the problem with alacritty, spotify, discord and microsoft teams (most of the programs I use) but I don't think it has ever happened with firefox.

# Qtile version

```
> qtile --version
0.16.1
```
Not sure about the commit hash but it is installed using pacman

# Stack traces

qtile.log:
https://termbin.com/wwik

nothing in ~/.xsession-errors

# Configuration

https://termbin.com/mved

**Comment by tcld** [comment]
I use all the software you mentioned, and I have been running 0.15, later 0.16.1 and now the current master branch. I have never observed a freeze like you described.

More information might be necessary: Do the freezes happen with other window managers/desktop environments? How long have you been having these issues? Are there any particular details about your system that you would think differ from the norm?

The log you attached doesn't seem to contain anything of interest - at least there are no error-messages or anything similar in there.

**Comment by b177y** [comment]
I haven't had this problem with i3 or gnome. I've been having the issues since I started using qtile, so a few months now. I can't think of anything specifically different about my system - I'm using manjaro (5.6.19-3-rt12-MANJARO) and have upgraded the kernel at least a couple times since using qtile so I don't think it's a kernel specific bug. I have hybrid graphics (nvidia and intel) managed with optimus, but 99% of the time I'm using intel only mode so that shouldn't cause problems.

**Comment by tcld** [comment]
So if it seems to be just the UI that freezes, can you still move the "frozen" windows around afterwards? Resize them? What happens if you restart Qtile in that situation? Is there anything of interest in your system logs (e.g. `journalctl -p 3 -xb`)? Are you using picom or something similar to give you transparency?

It all sounds like it could very well be an issue with the graphics driver(s). Qtile should only move and resize the windows, not be responsible for actually drawing them.

Sorry for all the questions. :)

**Comment by b177y** [comment]
Yes it seems that I can move the application to different workspaces and move them using the mod key and dragging, however they remain frozen. Sometimes when they are frozen they just show the application at the point that it froze - this is what usually happens but sometimes it shows another application that's running, but where the app should be, or the desktop background but in the application frame.

Couldn't find anything interesting in the journal, there were some bugs but none that look relevant or match the timings of when applications freeze. I used picom with i3 and I believe it is still installed but nothing in my qtile config / elsewhere is starting it. 

I understand what you mean about qtile not drawing the windows - it most likely is something else it's just strange how it only happens with qtile - I'll keep looking into it.

Thanks

**Comment by tcld** [comment]
Thanks for all the information. It does sound like the problem is caused somewhere underneath Qtile; sadly that's mostly a blackbox for me, too. Maybe @tych0 has an idea where to look next?

**Comment by b177y** [comment]
I was planning a fresh install of arch on my laptop anyway so hopefully that'll fix it. Still can't think of what might be causing it though

**Comment by tcld** [comment]
Let's hope that fixes it.

**Comment by b177y** [comment]
Update: I've reinstalled linux (this time arch instead of manjaro) and I have most of the same software installed but I have not come across the issue again after about a week of use. Not sure what it was that caused it but everything is good now 👍

**Comment by b177y** [comment]
This is happening again as of a few weeks ago. Not sure what changed that has brought it back.

This error keeps appearing in ~/.local/share/qtile/qtile.log but I don't think its related:
```
ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1038, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 407, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.9/site-packages/libqtile/configurable.py", line 51, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2021-09-06 11:25:05,933 WARNING libqtile.widget.pulse_volume pulse_volume.py:on_connection_change():L97 Connection to pulseaudio has been terminated
2021-09-06 11:25:05,984 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

It is mainly happening with alacritty and firefox (they usually freeze at the same time). To fix it i have to open a new terminal and run `killall firefox && killall alacritty`

**Comment by m-col** [comment]
Do you have a way to reproduce the error? It might be difficult to track this down, but if you've noticed that it has happened in the past few weeks then that might be a clue. Are you running a git version or a release? Did anything change in your qtile setup, general X/laptop setup, qtile config, a few weeks ago?

I don't think that error is related, but it also shouldn't happen, as it suggests your bar is receiving keyboard input before it has grabbed the keyboard, which should be impossible with a vanilla qtile installation.

**Comment by elParaguayo** [comment]
I saw this for the first time yesterday with alacritty. Haven't tried to replicate yet as working on something else.

**Comment by b177y** [comment]
> Do you have a way to reproduce the error? It might be difficult to track this down, but if you've noticed that it has happened in the past few weeks then that might be a clue. 

It seems to have happened since I installed gnome-desktop. I have since removed it and attempted to get rid of all dependencies in case something weird is going on there but it seems unlikely.

>Are you running a git version or a release? Did anything change in your qtile setup, general X/laptop setup, qtile config, a few weeks ago?

Running version `0.18.1.dev0+g8e7ecc0a.d20210719` from the AUR.

> I don't think that error is related, but it also shouldn't happen, as it suggests your bar is receiving keyboard input before it has grabbed the keyboard, which should be impossible with a vanilla qtile installation.

Hmm weird, I'll try use a more simple qtile config for a while and if it stops happening then I know its my config and I can investigate further.

**Comment by elParaguayo** [comment]
> I saw this for the first time yesterday with alacritty. Haven't tried to replicate yet as working on something else.

Ignore this. In my case, alacritty was "freezing" because I accidently hit ctrl+s to save something in a different app while the focus was actually in alacritty. Didn't know that ctrl+s freezes the terminal! ctrl+q unfreezes it for me.

**Comment by amvasilyev** [comment]
I came across the issue of application freezes after installation of qtile in Debian Testing. This behavior can be seen on two systems. One was upgraded, the other one is the fresh installation.

When an application tried to show the notification (Firefox, Thunderbird, Telegram and so on), it became frozen for a while (up to 30 seconds). Then the notification would appear and the application becomes fully functional.

Today I was able to fix the issue by configuring the org.freedesktop.Notifications DBus service. I used the general `notification-daemon` and configuration provided by Arch project: https://wiki.archlinux.org/title/Desktop_notifications See standalone section for details.

It seems that Debian does not provide such a service by default and relies that desktop environments will provide required DBus service.

**Comment by elParaguayo** [comment]
Qtile can provide the notification service if you add the `Notify` widget to your bar.

However, if the apps are slow because if they can't find a service then that sounds like a bug (or an interesting design choice) with those apps.

**Comment by 0xUnicorn** [comment]
I'm having the same issue on a Kali linux box running as a Virtualbox VM. 
All applications are none interactive using the mouse, I'm still able to interact with keyboard. So writing in vim, <F5> in firefox etc.
I've no idea how to reproduce it, but I have experienced it a lot on this Kali VM.

**Comment by gibranlp** [comment]
i have issues like this but in the Electron apps

**Comment by aagowl** [comment]
I've been having the same issue primarily with Discord. Like the people above both in this issue thread and the #3032 thread, this problem only happens to me while using qtile and not KDE. I have tried using the `Notify` widget with no effect. It happens with both the default config and my personal config that I've been working on. For me this problem has only occurred with Discord- but I think that is because that is the only application that I use that provides notifications

I'm very new to qtile and fairly new to the rest of this type of stuff so this could easily be a simple mistake on my part.
