### ISSUE TITLE
Failed restoring state after upgrade

### ISSUE THREAD

**Issue by mikelward** [qtile/qtile#1960]
# Issue description

I just updated to git head, and restarted Qtile. It lost my bar, workspaces, and shortcuts.

Posting this from my broken setup before I start investigating because I have another long-running operation going and I can't even get a terminal open.

# Qtile version

464bf7f

# Stack traces

```
2020-11-13 20:41:49,070 DEBUG libqtile hook.py:fire():L380 Internal event: startup((), {})
2020-11-13 20:41:49,070 ERROR libqtile manager.py:__init__():L198 failed restoring state
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/libqtile/core/manager.py", line 194, in __init__
    with open(state, 'rb') as f:
OSError: [Errno 36] File name too long: 'ccopy_reg\n_reconstructor\np0\n(clibqtile.state\nQtileState\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nVgroups\np6\n(lp7\n(V1\np8\nV2equal\np9\ng8\ntp10\na(V2\np11\nV3wide\np12\ng11\ntp13\na(V3\np14\ng12\ng14\ntp15\na(V4\np16\ng12\ng16\ntp17\na(V5\np18\ng12\ng18\ntp19\na(V6\np20\ng12\ng20\ntp21\na(V7\np22\ng12\ng22\ntp23\na(V8\np24\ng12\ng24\ntp25\na(V9\np26\ng12\ng26\ntp27\na(V0\np28\ng12\ng28\ntp29\nasVscreens\np30\n(dp31\nI0\ng11\nssVcurrent_screen\np32\nI0\nsVscratchpads\np33\n(dp34\nsVorphans\np35\n(lp36\nsb.'
```

# Configuration

https://github.com/mikelward/conf/tree/main/config/qtile

**Comment by mikelward** [comment]
I think it was broken by f7c212db2abce06f78c23f3aaa4e2fa03affcdb1?

Looks like state used to be the pickled data but is now being treated as a filename?

**Comment by m-col** [comment]
There were problems with text encoding (e.g. group names) when storing state in that way, which we managed to fix by instead avoiding encoding altogether by passing a temp file for state restoration rather than the data directly. Sorry to hear this has bitten you. Perhaps you could revert the change until your running processes finish, then upgrade later when you can?

**Comment by mikelward** [comment]
It's no big deal.

It does make me wonder if we should try to keep interfaces stable, and add new parameters when we want new types or semantics. And whether we should document every parameter. And maybe add type hints.

I guess in retrospect this should at least have been marked a breaking change.

But yeah, it only broke me once. Not the end of the world. :)

**Comment by m-col** [comment]
>I guess in retrospect this should at least have been marked a breaking change.

Yep, when I made the change it's likely that i didn't add an appropriate
changelog entry, sorry about that!

**Comment by ramnes** [comment]
@m-col Better late than never! Can you add the changelog entry?
