### ISSUE TITLE
Popup window doesn't react to events

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1961]
# Issue description

I referenced this in a different issue (https://github.com/qtile/qtile/issues/1954) but, as that issue was closed, I'm adding this to a new one so it's not lost. @m-col is aware of this issue.

I'll start off by saying I could have misunderstood how the Popup object is meant to work but I felt like it may be what I was looking for (ability to have window temporarily display some additional information from my widgets).

However, I just can't get them to work. The code I'm using is as follows:

```
from libqtile.popup import Popup

class MyPop(Popup):
    def _handle_Expose(self, e):
        logger.warning("Exposed")

    def _handle_KeyPress(self, event):
        logger.warning("Key: {}".format(event))

    def _handle_ButtonPress(self, event):
        logger.warning("Button: {}".format(event))
```
I create the popup with the following function which is bound to a key:
```
def poptest(qtile):
    p = MyPop(qtile, opacity=0.7) #, border="#ff0000", border_width=2)
    p.place()
    p.unhide()
```
I subclassed Popup so I could write my own handle functions but none of them seem to get called (as there's nothing in the log file).

The window loads ok (small, semi-opaque window in top left corner as per default values) but clicking on it does not cause anything to be written to the log.

I've also tried with the bare Popup class which looks like it should hide the window when it's clicked (https://github.com/qtile/qtile/blob/master/libqtile/popup.py#L91)

# Qtile version

Issue is on 0.16.1 but also on current master (I'm synced to 464bf7f191e800bcb8a075d465841cde81bc15f8)

I'm very happy to debug this by bisecting as appropriate but I haven't found one commit where this actually works so I wonder if I'm just doing something wrong!

# Stack traces

None

# Configuration

Relevant code is above.

**Comment by m-col** [comment]
It looks like the code that lets the Popup windows receive events has never changed, so bisecting won't find a time when it worked. I am 100% certain that it did work at least at the point it was added to libqtile. I did find something very interesting while probing around: the window ID reported by the event data is _not_ the window ID that is saved in `qtile.windows_map`, and so the event handler is "doing the right thing", but their is no corresponding window known by qtile to handle it. I wonder if this is due to a change made in X at some point. I will keep looking for a solution.

**Comment by elParaguayo** [comment]
Very interesting. Thanks for the update. 

I would stress, this isn't urgent for me - for the widgets I'm currently working on, I can just add a timer to hide the popup so I don't need it to react to an event.

I also have no clue how X works so this is issue is probably way beyond me. However, I am a bit confused by your answer i.e. what's special about the popup window's ID compared to any other windows that qtile makes? Isn't the bar a window?

**Comment by m-col** [comment]
>what's special about the popup window's ID compared to any other windows that qtile makes? Isn't the bar a window?

Yes, it's basically the same, all the more reason I'm confused and a bit
worried! Hopefully it is just one tiny thing somewhere in the way Popup
instances are created that means that the ID that is given to the `qtile` object
is not the one that ought to be.

**Comment by m-col** [comment]
Does https://github.com/qtile/qtile/pull/1964 fix it?

**Comment by elParaguayo** [comment]
Yes - the popup window does now react to events.

Only question: looking at the windows_map, is this window being added twice as a result i.e. once with the wrong id (as before) and once with the correct id (based on your updates)?

**Comment by m-col** [comment]
Turns out it was never being added!

I had the Popup class in a staging repository as a plug-in for a while before
commiting it to libqtile, so I think it must have got lost in the migration.

**Comment by elParaguayo** [comment]
Ah. That makes sense.

I was trying to set the name of the window so I could identify it more easily in the windows_map but failed in my attempt.

Given your PR fixes this, I'll close the issue. 

Thanks for your help.
