### ISSUE TITLE
Json Text Pane not rendering in Charles Proxy (Java Swing Program). The same program works fine in KDE Plasma

### ISSUE THREAD

**Issue by kamiox** [qtile/qtile#1970]
# Issue description

I have a weird issue when running [Charles Proxy](https://www.charlesproxy.com) under Qtile.

Steps to reproduce:

1. Use Charles proxy to inspect a request with the JSON response. 

2. Under Response pane there are different tabs like Headers, Text, Hex, **JavaScript**, JSON, **JSON Text**, Raw.
Tapping on **JavaScript** or **JSON Text** tab does not switch to this tab (the previous tab is still highligted) and results in the stack trace attached below. Running the same scenerio on KDE Plasma works without any issues. 

# Qtile version

The latest version from the master branch (5eee9b375da285313a6aefad2dda6f39a25502fb)

Here is a stack trace from Charles
This stack trace does not show up when running the program under KDE Plasma.

# Stack traces
2020/11/19 22:07:20	Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
2020/11/19 22:07:20		at com.xk72.charles.gui.lib.AntiAliasingJEditorPane.XdKP(Unknown Source)
2020/11/19 22:07:20		at com.xk72.charles.gui.lib.AntiAliasingJEditorPane.paintComponent(Unknown Source)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
2020/11/19 22:07:20		at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
2020/11/19 22:07:20		at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
2020/11/19 22:07:20		at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
2020/11/19 22:07:20		at java.base/java.security.AccessController.doPrivileged(Native Method)
2020/11/19 22:07:20		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
2020/11/19 22:07:20		at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
2020/11/19 22:07:20		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
2020/11/19 22:07:20		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
2020/11/19 22:07:20		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
2020/11/19 22:07:20		at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
2020/11/19 22:07:20		at java.base/java.security.AccessController.doPrivileged(Native Method)
2020/11/19 22:07:20		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2020/11/19 22:07:20		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2020/11/19 22:07:20		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

# Configuration

[Default configuration from the repo.](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py)

# Screenshots

https://imgur.com/a/dxz2pZ1

**Comment by tych0** [comment]
On Thu, Nov 19, 2020 at 01:47:59PM -0800, Kamil Bartoszek wrote:
> 2020/11/19 22:07:20	Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> 2020/11/19 22:07:20		at com.xk72.charles.gui.lib.AntiAliasingJEditorPane.XdKP(Unknown Source)
> 2020/11/19 22:07:20		at com.xk72.charles.gui.lib.AntiAliasingJEditorPane.paintComponent(Unknown Source)

Hrm, would be interesting to know what's happening (or what it has
just queried) at this line. If you xtrace it some of the requests?
Maybe that'll give us a clue as to what it doesn't like.

**Comment by kamiox** [comment]
@tych0 Here is a xtrace log from the Charles app. It is quite verbose but I hope you will find it helpful.

[charles2.tar.gz](https://github.com/qtile/qtile/files/5570365/charles2.tar.gz)

**Comment by tych0** [comment]
Can you say when exactly this bug happens relative to the logs here? like which request ids seem to trigger it?

**Comment by kamiox** [comment]
@tych0 I have recorded a [video](https://easyupload.io/7qcp5s) where you can see a live preview of xtrace logs and interactions with the Charles app.

Check the events when I tap on JavaScript or JSON Text tabs.

**Comment by kamiox** [comment]
Here is xtrace log file [charles_log.zip](https://github.com/qtile/qtile/files/5570598/charles_log.zip)
