### ISSUE TITLE
The "Hide" button of Chrome's screen sharing sticky window doesn't work

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1974]
This window won't go away:

![image](https://user-images.githubusercontent.com/835072/99949439-5548e500-2d7b-11eb-89c5-7b84bb179990.png)

xprop:

```
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4109694196
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_USER_TIME(CARDINAL) = 495685613
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1041, 1384
		program specified minimum size: 478 by 56
		program specified maximum size: 478 by 56
WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
_NET_WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128): ...
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20979044, 20979045
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 26321
WM_CLIENT_MACHINE(STRING) = "saiga"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

**Comment by tych0** [comment]
On Mon, Nov 23, 2020 at 02:04:14AM -0800, Guillaume Gelin wrote:
> This window won't go away:
> 
> ![image](https://user-images.githubusercontent.com/835072/99949439-5548e500-2d7b-11eb-89c5-7b84bb179990.png)
> 
> xprop:
> 
> ```
> _NET_WM_DESKTOP(CARDINAL) = 1
> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x0
> _NET_WM_WINDOW_OPACITY(CARDINAL) = 4109694196
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
> _NET_WM_USER_TIME(CARDINAL) = 495685613
> WM_NORMAL_HINTS(WM_SIZE_HINTS):
> 		program specified location: 1041, 1384
> 		program specified minimum size: 478 by 56
> 		program specified maximum size: 478 by 56
> WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
> _NET_WM_NAME(UTF8_STRING) = "meet.google.com is sharing your screen."
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
> XdndAware(ATOM) = BITMAP
> _NET_WM_ICON(CARDINAL) = 	Icon (128 x 128): ...
> _NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
> _NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20979044, 20979045
> _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
> _NET_WM_PID(CARDINAL) = 26321
> WM_CLIENT_MACHINE(STRING) = "saiga"
> WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
> ```

If you run a compositor, does that fix it? I'm wondering about
_NET_WM_SYNC_REQUEST.

**Comment by ramnes** [comment]
I'm already running picom. :)

**Comment by tych0** [comment]
Huh, the rest of that looks ok (i.e. like it should really be displaying the window). Maybe it's because it is using WM_SYNC and BYPASS_COMPOSITOR? We don't implement WM_SYNC at all, so I usually tell people to just run a compositor for that...

**Comment by ramnes** [comment]
FWIW it seems that it doesn't hide on i3 neither.

**Comment by ramnes** [comment]
Are you using Qtile? From your comment I understand that you use i3, not Qtile.

**Comment by masterAllen** [comment]
Oh, I'm not using qtile. My mistake, thank you for your reply : )
However, can you give me some advices, i am stuck with this problem.

**Comment by ramnes** [comment]
Well you probably want to open an issue here: https://github.com/i3/i3

**Comment by masterAllen** [comment]
Yep, you're right. Thanks: )
