### ISSUE TITLE
Question: Using pydbus instead of dbus

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1980]
# Issue description

I've got a number of custom widgets which I would happily submit pull requests for. However, these widgets use pydbus to query and receive signals from dbus.

I've done this because I find pydbus vastly easier to use than the dbus module currently being used by qtile.

However, I don't want to submit any of these if using pydbus is not acceptable.

**Comment by tych0** [comment]
On Fri, Nov 27, 2020 at 01:52:48AM -0800, elParaguayo wrote:
> # Issue description
> 
> I've got a number of custom widgets which I would happily submit pull requests for. However, these widgets use pydbus to query and receive signals from dbus.
> 
> I've done this because I find pydbus vastly easier to use than the dbus module currently being used by qtile.
> 
> However, I don't want to submit any of these if using pydbus is not acceptable.

I'd rather not have two dbus libraries in the code base -- any
interest in porting the existing code to pydbus? :) I agree it looks
much nicer (and the freedesktop.org people seem to think so too).

Tycho

**Comment by elParaguayo** [comment]
Sure. Let me take a look at moving it over. May take some time as I don't know how deeply ingrained dbus is to qtile but I'm very happy to give it a go.

**Comment by elParaguayo** [comment]
Hmm. Only concern here is that it doesn't look like pydbus code has been touched in 4 years so not clear if it's being maintained or not.

**Comment by DorianGray** [comment]
Have you looked at dbus-next? Seems to be more sane, maintained, and also no dependencies. Would simplify package maintenance as well as provide an easier approach to running qtile with pypy on some distributions.

**Comment by elParaguayo** [comment]
Interesting. Never heard of it before but having a library that uses asyncio seemed to be the goal. The lack of asyncio support was one of the main criticisms of pydbus.

Presumably, if we can use asyncio here then we can drop the mainloop that's currently used. Is that correct? 

@tych0  worth a look? I'm happy to have a go at this.

**Comment by tych0** [comment]
Yep, that sounds reasonable to me. Thanks for looking into it!

**Comment by elParaguayo** [comment]
dbus_next isn't in the official arch repositories so that's not ideal if we want this to eventually make the main release.

**Comment by kaistian** [comment]
I don't think that is an issue. Any distribution would add it just to have Qtile in the repositories.

**Comment by elParaguayo** [comment]
Fair enough.

Still trying to get my head round asyncio's event loop in this code. Can't understand why it say the loop isn't running...

**Comment by elParaguayo** [comment]
I'm going to close this thread and start a new one so I can set out what I think needs changing and any issues that come up during the process.
