### ISSUE TITLE
Not even sure where to start!! The docs are extremely insufficient!!!!

### ISSUE THREAD

**Issue by pianocomposer321** [qtile/qtile#1981]
I'm SO confused! The docs list what extensions, hooks, layouts, and widgets there are. But that's it. They don't tell you how to use custom functions for keybindings (I have since learned that you do this with `lazy.function`, but I still have no idea how to use it because there is absolutely no documentation), how to use layout-specific keybindings, or even, for that matter, how to use keybindings at all - all there is is a few examples. There _needs_ to be more docs, otherwise, new users like me have no idea what they are doing!

**Comment by tcld** [comment]
I only started out using Qtile myself about half a year ago, and I agree that there are some blind spots in the documentation. But between the docs and some [example configurations](https://github.com/qtile/qtile-examples), I got my setup done decently quickly.

Please don't forget that this is an open source project and there is always work left to be done. If you feel anything lacking, may it be features or guidance, it would be very much appreciated if you could communicate your issues in a constructive manner or, even better, find a way to help.
For example, if you created a list of topics you would want to see covered, plus information about where exactly you would expect to see them covered, there would be a good chance that, over time, your issues would be resolved.

**Comment by pianocomposer321** [comment]
@tcld I would be glad to do that. But it's not really that simple.

For example, now that I know that the `lazy.function` function exists, I would say that it should probably go in with the list of Lazy objects (http://docs.qtile.org/en/latest/manual/config/lazy.html). I also know that these functions take an argument, normally named `qtile`, but I don't know what type of object it is or what its properties are. So I have no idea where that documentation should go, because I don't even know what it would be documenting yet ;-). There are tons more things like this, I'm sure. Of course, I have no way of knowing, because the docs is where I would normally find out.

The examples are where I learned that the `lazy.function` function exists, but it didn't help me know what the `qtile` parameter is or what its methods are, which makes sense, because that's what the docs are for. Except the docs didn't tell me either, even after hours of searching.

So far I love the qtile project. I am a big fan of python (it's the only programming language that I would consider myself "fluent" in), and qtile in general seems very functional. I would love to adopt it as my WM, but that really won't work so well if I can't get my config running due to a lack of documentation. I'm sorry if I sounded "deconstructive", I'm just really frustrated after hours of wasted time googling for pages that don't exist.

So in the meantime, if you could explain to me how the `lazy.function` function works and what the qtile parameter is, or at the very least point me to the source file so I can look at it myself, I would appreciate it.

**Comment by ramnes** [comment]
Thank you @tcld.

@pianocomposer321, I do agree that the documentation is far from perfect, so let me start by genuinely thanking you for the reminder. Now please understand that people's time is a limited resource and that Qtile contributors will work on the aspects they care about, not on what you believe is important.

If you want a better documentation, your options are either to improve it yourself by submitting pull requests, write constructive recommandations and create interest, or pay people to spend that time for you (I do take sponsorships myself). But such an issue is a dead end.

**Comment by ramnes** [comment]
@pianocomposer321 I'm just seeing the message you posted while I was writing mine. Qtile folks are quite active on the mailing list and IRC, feel free to ask your questions there!

**Comment by pianocomposer321** [comment]
@ramnes Why is the issue closed? If, as you said, this issue is a good reminder, then why close it? The issue is not solved.

**Comment by ramnes** [comment]
Because it can't be resolved, it's too vague and possibly endless. Please open issues that state one problem and its possible improvements at a time.
