### ISSUE TITLE
Moving from dbus to dbus_next

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1982]
This isn't an "issue" as such but is just somewhere for me to set out progress and ask questions related to moving from dbus to dbus_next.

Tasks to do:
- [X] Strip dbus/glib mainloop out of core/master.py
- [X] Notify widgets when asyncio's eventloop has started
- [X] Update mpris2 widget (I'm aware there's a pull request for an updated version of this widget. If that gets merged I'll need to redo this one)
- [x] Update keyboardkbdd widget - Tricky. I can't test this one and I don't really understand what it does!
- [x] Look at base widgets and see if anything should be updated
- [x] Update notify.py
_List last updated: 4 January 2021_

Removed tasks:
- Update mpris widget. Widget will be deleted (see #2066)

Happy to add to the list if anyone has any comments.

**Comment by elParaguayo** [comment]
OK - first question.

I'm looking at widget/base.py. 

The ThreadedPollText class uses threading for the poll
``` python
    def tick(self):
        def worker():
            try:
                text = self.poll()
                if self.qtile is not None:
                    self.qtile.call_soon_threadsafe(self.update, text)
            except:  # noqa: E722
                logger.exception("problem polling to update widget %s", self.name)
        # TODO: There are nice asyncio constructs for this sort of thing, I
        # think...
        threading.Thread(target=worker).start()
```

But the ThreadPoolText uses asyncio
``` python
    def timer_setup(self):
        def on_done(future):
            try:
                result = future.result()
            except Exception:
                result = None
                logger.exception('poll() raised exceptions, not rescheduling')

            if result is not None:
                try:
                    self.update(result)

                    if self.update_interval is not None:
                        self.timeout_add(self.update_interval, self.timer_setup)
                    else:
                        self.timer_setup()

                except Exception:
                    logger.exception('Failed to reschedule.')
            else:
                logger.warning('poll() returned None, not rescheduling')

        future = self.qtile.run_in_executor(self.poll)
        future.add_done_callback(on_done)
```
It's not immediately clear to me what the differences are which means we have two classes here. One of the docstrings talks about pushing vs pulling.

I'd assume we'd look to move the threading with an ayncio coroutine but would appreciate any thoughts.

**Comment by tych0** [comment]
On Sun, Nov 29, 2020 at 06:37:40AM -0800, elParaguayo wrote:
> OK - first question.
> 
> I'm looking at widget/base.py. 
> 
> The ThreadedPollText class uses threading for the poll
> ``` python
>     def tick(self):
>         def worker():
>             try:
>                 text = self.poll()
>                 if self.qtile is not None:
>                     self.qtile.call_soon_threadsafe(self.update, text)
>             except:  # noqa: E722
>                 logger.exception("problem polling to update widget %s", self.name)
>         # TODO: There are nice asyncio constructs for this sort of thing, I
>         # think...
>         threading.Thread(target=worker).start()
> ```
> 
> But the ThreadPoolText uses asyncio
> ``` python
>     def timer_setup(self):
>         def on_done(future):
>             try:
>                 result = future.result()
>             except Exception:
>                 result = None
>                 logger.exception('poll() raised exceptions, not rescheduling')
> 
>             if result is not None:
>                 try:
>                     self.update(result)
> 
>                     if self.update_interval is not None:
>                         self.timeout_add(self.update_interval, self.timer_setup)
>                     else:
>                         self.timer_setup()
> 
>                 except Exception:
>                     logger.exception('Failed to reschedule.')
>             else:
>                 logger.warning('poll() returned None, not rescheduling')
> 
>         future = self.qtile.run_in_executor(self.poll)
>         future.add_done_callback(on_done)
> ```
> It's not immediately clear to me what the differences are which means we have two classes here. One of the docstrings talks about pushing vs pulling.
> 
> I'd assume we'd look to move the threading with an ayncio coroutine but would appreciate any thoughts.

Yeah, I agree. You can probably just drop ThreadedPollText entirely in
favor of the asyncio one if you want.

**Comment by elParaguayo** [comment]
OK. So, I've made some changes but have tried to keep this as simple as I could.

I've made some changes to manager.py and session_manager.py in https://github.com/elParaguayo/qtile/commit/c0c45f4e261b63ec491d51071d18b3d02b7cdd71:
- Removed dbus/glib references
- The eventloop is started after widgets have run `_configure`. This means that `asyncio.create_task` etc can't run yet (they'll give RuntimeError if there's no running loop). We can either handle exception and retry or create new `_configure_async` method to be called once the eventloop is in place. This is my current approach but happy to discuss alternatives.

Next up, I've changed `ThreadedPollText` widgets to `ThreadPoolText` widgets as there seems to be no need for both - https://github.com/elParaguayo/qtile/commit/7b47282aece8c04acb909bad3237956104a72845
- CPU widget - not sure this needs to be ThreadPoolText - it updates every second so, presumably, is quick. Also removed redundant "tick" method.

Lastly, I've changed MPRIS2 widget to use dbus_next instead of dbus https://github.com/elParaguayo/qtile/commit/11fccf3a4fb952247c4a3e301596937ab2e06b7b
- seems to work ok

I can create a pull request for the above unless there are some fundamental disagreements with the approach which we should fix first.

Oh, and I'm not sure what deal is with copyrights. Haven't updated most of these - only where some more substantial changes.

**Comment by tych0** [comment]
> Oh, and I'm not sure what deal is with copyrights. Haven't updated most of these - only where some more substantial changes.

If you change a file, feel free to add your copyright to the top of it. I think it should mostly just be additive, unless you're absolutely sure you deleted all the person's code from a file, then you can remove their name.

**Comment by elParaguayo** [comment]
Notifications updated to use asyncio and dbus_next in this commit: https://github.com/elParaguayo/qtile/commit/323574087a648a6187f31393ec5078beebae6e9a

**Comment by elParaguayo** [comment]
Should I be using "# type:  ignore" on dbus_next to suppress mypy errors for now?

**Comment by tych0** [comment]
It looks like dbus_next has a py.typed file exported, so it seems like we should be able to type check it.

**Comment by elParaguayo** [comment]
Still having build errors with mypy. Having added `dbus-next` to the requirements I'm still getting errors like:
`Skipping analyzing 'dbus_next.service': found module but no type hints or library stubs` 
and `error: Name 's' is not defined`

Am I doing something wrong (never used mypy before so could be user error) or do I need to flag to dbus-next developer?

**Comment by tych0** [comment]
Does wherever the dbus_next module lives on your filesystem have a py.typed file?

**Comment by elParaguayo** [comment]
No, it doesn't. I guess that means the py.typed file isn't included in the pip package. I can post an issue for that.

However, adding the file doesn't completely solve the problem. It does remove the `...found module but no type hints or library stubs` message, but I still get the `...is not defined` messages. Probably worth posting about that too.

**Comment by elParaguayo** [comment]
I've submitted a PR on dbus_next to get `py.typed` to be included in the pip package but I don't think that's going to solve the issue here.

The problem is that dbus_next uses type hinting to define the in and out signatures for dbus. That's pretty clever and makes the code nice and neat (the original dbus module used decorators for this). However, the problem is that mypy can't deal with these string values when type checking.

Here's a nice comparison.

Old:
``` python
        @service.method(BUS_NAME, in_signature='susssasa{sv}i', out_signature='u')
        def Notify(self, app_name, replaces_id, app_icon, summary,  # noqa: N802
                   body, actions, hints, timeout):
```
New:
``` python
        @method()
        def Notify(self,  # noqa: N802, F722
                   app_name: 's', replaces_id: 'u',  # noqa: F821
                   app_icon: 's', summary: 's',  # noqa: F821
                   body: 's', actions: 'as',  # noqa: F821
                   hints: 'a{sv}', timeout: 'i') -> 'u':  # noqa: F821
```

I can't see an obvious fix to make mypy work on this so we may end up having to have mypy skip these bits.

I'll keep looking for a bit though.

**Comment by m-col** [comment]
>     * The eventloop is started after widgets have run `_configure`. This means that `asyncio.create_task` etc can't run yet (they'll give RuntimeError if there's no running loop). We can either handle exception and retry or create new `_configure_async`

Is it feasible to get around this by configuring the screens+widgets in the event loop?

**Comment by elParaguayo** [comment]
@m-col yes - I'll take a look at this again. I wasn't 100% happy with the way I did it - felt a bit hacky.

**Comment by elParaguayo** [comment]
Having looked at this again, I think the basic premise to this is actually ok subject to one minor point. 

There is currently no configuration that is done after the loop is started so delaying the calling of configuration code should, I think, probably be avoided to keep the code neater.

The way the configuration works is by scheduling a callback that's only run once the loop starts. The loop does not need to be running in order to schedule the callback. 

This is currently how the `timer_setup` method is called by `_configure` so using the same approach to call a specific method (`_configure_async`) provides a guaranteed entry point for widgets that need to run code that can only work if the loop is running. The alternative would be for widgets to implement their own `call_soon` (or equivalent) from `_configure`. This doesn't feel like it should be the default position but widgets are still free to do this if they wish.

I would therefore suggest keeping as is but I would be open to changing the method name (e.g. `_eventloop_started`) but happy to hear views.

**Comment by m-col** [comment]
OK, sounds good. I was thinking that keeping all that stuff in one _configure
method might be neater but I'll take your word for it as you're the one who has
made the changes so you're better able to picture it :)

As for the 'how' -- if there are other things in the code/peoples configs that
would benefit from being run only when the event loop has started, then maybe
there might be value in having an `eventloop_started` hook or something. The
relevant widgets could use that mechanism too. Of course this would only be good
if there is more than just the widgets that needs this.

**Comment by m-col** [comment]
This has been done and can be closed, right?

**Comment by elParaguayo** [comment]
Yup.
