### ISSUE TITLE
lazy.function() not working

### ISSUE THREAD

**Issue by pianocomposer321** [qtile/qtile#1984]
If I add the following to my config.py...

```python3
keys = [
    # snip
    Key([mod], "0", lazy.to_screen(0)),
    # snip
]
```

...and restart qtile, mod+0 switches focus to screen 0 as expected. If, however, I do this...

```python3
def to_screen(qtile):
    lazy.to_screen(0)

keys = [
    # snip
    Key([mod], "0", lazy.function(to_screen)),
    # snip
]
```

...pressing mod+0 does nothing.

`qtile --version`: `0.16.1`
I am running on xubuntu, and I installed qtile with pip3, but I have also tried on MX Linux (which is debian based), and the same thing happens. This is with the default config.py, other than the changes from above.

**Comment by tych0** [comment]
On Sun, Nov 29, 2020 at 11:27:02AM -0800, pianocomposer321 wrote:
> def to_screen(qtile):
>     lazy.to_screen(0)

you want qtile.cmd_to_screen(0) here instead; the lazy architecture is
for stuff that gets bound in Keys, lazy.function(f) runs f against the
live qtile object.

**Comment by pianocomposer321** [comment]
@tych0 it doesn't make a difference, the binding still does nothing. I could have put anything in that function, lazy.to_screen was just an example. The point is that lazy.function isn't doing anything for me.

**Comment by tych0** [comment]
Have you tried logging from it to see if the logs show up?

**Comment by pianocomposer321** [comment]
@tych0 how would I do that?

**Comment by tych0** [comment]
print() is the simplest way, that'll show up in ~/.xsession-errors;
you could also use the qtile logging infrastructure if you want.

**Comment by pianocomposer321** [comment]
@tych0 NVM, I had a typo in `to_screen` when I tried your example lol (I had cmod_to_screen instead of cmd_to_screen). When I fixed it it worked! So all of the qtile object functions start with cmd? In the examples (qtile/qtile-examples) they don't, and I was testing it without the cmd prefix. That's probably why it wasn't working. That should probably be fixed, especially because it doesn't give an error, the keybinding just doesn't work.

Also, why exactly does lazy.to_screen not work? It is just a regular function, isn't it?

Anyway, thanks for your help!

**Comment by tych0** [comment]
On Sun, Nov 29, 2020 at 11:54:38AM -0800, pianocomposer321 wrote:
> @tych0 NVM, I had a typo in `to_screen` when I tried your example lol (I had cmod_to_screen instead of cmd_to_screen). When I fixed it it worked! So all of the qtile object functions start with cmd? In the examples (qtile/qtile-examples) they don't, and I was testing it without the cmd prefix. That's probably why it wasn't working. That should probably be fixed, especially because it doesn't give an error, the keybinding just doesn't work.

No, the lazy.* namespace is just a list of things that are prefixed
with cmd_* on the Qtile object. See:
http://docs.qtile.org/en/latest/manual/ref/commands.html and
http://docs.qtile.org/en/latest/manual/commands/index.html

> Also, why exactly does lazy.to_screen not work? It is just a regular function, isn't it?

Exactly because it is not a regular function :)

**Comment by pianocomposer321** [comment]
DUH!!! I feel stupid now. lazy.* _returns_ the function that is called, it's not the one that is called. And I call myself a pythonista!

Thanks again for all your help!

BTW, I think there is an issue opened on the qtile-examples repo, but I'll restate it here - the examples really should be updated. I've already opened an issue about the docs not being as good as they could be, and the only other source of information is the examples. So when they are out of date, it's really hard to understand what's wrong with your config, especially when it doesn't exit with an error.

Thanks anyway, you have been a big help!

**Comment by tych0** [comment]
Patches welcome!
