### ISSUE TITLE
Hooks don't seem to work

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1986]
# Issue description
I'm trying to make a new floating window(spawned by another one) to focus always itself over previous floating windows.
Everytime a floating window calls another floating window and they're related(sort of subprocessing) the initial floating window remains focused and the last one spawns under the previous one. Sometimes it's difficult to get focus on the last spawned.
An example? Here's the video:
[Bug on Vimeo](https://vimeo.com/485561690)
What am I doing wrong? In the config I tried to make the last client windows to focus without it working.

# Qtile version
0.16.1

# Stack traces

# Configuration
[Myconfig](https://pastebin.com/ZmTBSmya)

**Comment by sirakai-pc** [comment]
??

**Comment by tcld** [comment]
Do you have a chance to try out the current master branch instead of version 0.16.1?

Please check out issue #1893 to see whether that describes the problem you are having.

**Comment by tcld** [comment]
Also, I don't think this is realted to hooks. The "floating" hook in your config shouldn't be necessary, the layout does that stuff automatically. Do things get worse when you remove the hook?

**Comment by sirakai-pc** [comment]
I installed the latest qtile from github. Now the problem seems gone. I also tried to remove those lines of code but then no default floating window could launch floating..
Anyway, now the problem is fixed. thanks.

**Comment by tcld** [comment]
The configuration for the automatically floating windows has changed a bit, see the default configuration for examples (there are more hints in the `CHANGELOG` about recent changes).

I might have been wrong before; I think the only line of code you don't actually need is the one for switching focus. But as long as things work for you everything is fine.
