### ISSUE TITLE
Moving specific windows to specific group (not working)

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1988]
I'm trying to get two programs to launch everytime on the group "0"
I tried different approaches from different configs and the official documentation, I didn't ever get it to work.
Here's the latest code I tried:
```python
def assign_app_group(client):
    wm_class=client.window.get_wm_class()
    if(wm_class == "telegram-desktop" or wm_class == "spotify-wrapper"):
        client.togroup("0")
        client.group.cmd_toscreen()
```
From 
**@hook.subscribe.client_new**.
It just doesn't spawn these two windows on my "0" group.
# Issue description

# Qtile version
0.16.1

# Stack traces

# Configuration
[Myconfig](https://pastebin.com/ZmTBSmya)

**Comment by tych0** [comment]
On Mon, Nov 30, 2020 at 10:46:44AM -0800, sirakai-pc wrote:
> I'm trying to get two programs to launch everytime on the group "0"
> I tried different approaches from different configs and the official documentation, I didn't ever get it to work.
> Here's the latest code I tried:
> `def assign_app_group(client):
>     wm_class=client.window.get_wm_class()
>     if(wm_class == "telegram-desktop" or wm_class == "spotify-wrapper"):
>         client.togroup("0")
>         client.group.cmd_toscreen()`

Try,

    Group('music', spawn="spotify", layout='max',
          matches=[Match(wm_class='Spotify')]),

This is what I use in my config for spotify.

**Comment by sirakai-pc** [comment]
Where do I put it?

**Comment by sirakai-pc** [comment]
I tried to put it there, 'Match' was undefined.
`@hook.subscribe.client_new
def set_floating(window):
    if (window.window.get_wm_transient_for()
            or window.window.get_wm_type() in floating_types):
        window.floating = True
        window.cmd_focus()

def assign_app_group(client):
    wm_class=client.window.get_wm_class()
    if(wm_class == "telegram-desktop" or wm_class == "spotify-wrapper"):
        client.togroup("0")
        client.group.cmd_toscreen()

def specific_instance_rules(window): # type: Window
    if window.match(wmclass='XTerm'):
        window.cmd_set_size_floating(w=302,h=800)
    Group('0', spawn="spotify-wrappers", layout='max',
        matches=[window.match(wm_class='spotify-wrapper')]),
`
It doesn't work..

**Comment by sirakai-pc** [comment]
?

**Comment by tcld** [comment]
This kind of stuff goes into the configuration of your group, as can be seen by the example @tych0 gave. There was a similar issue discussed on the [mailing list recently](https://groups.google.com/u/1/g/qtile-dev/c/-kgQEON9Eao). There are no hooks or custom functions needed.

**Comment by sirakai-pc** [comment]
I don't know why still it's not working..
`group_names = ["1", "2", "3", "4", "5", "6", "0",]
group_layouts = ["monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "treetab", "max",]
for i in range(len(group_names)):
    groups.append(
        Group(
            name=group_names[i],
            layout=group_layouts[i].lower(),
            label=group_labels[i],
        ))
Group('0', spawn="spotify-wrapper", matches=[Match(wm_class='spotify'),]),
`
I also tried the full version:
`    Group('0', spawn="spotify-wrapper", layout='max',
          matches=[Match(wm_class='spotify')]),
`

**Comment by tcld** [comment]
Your code is horribly formatted. It seems like you are setting up an extraneous group with the additional match, but that group is never added to anything. If you want to customize the groups to this degree, I would refrain from using the iterative way of generating your groups - just set up a list and things will be much easier to maintain.

**Comment by sirakai-pc** [comment]
> Your code is horribly formatted. It seems like you are setting up an extraneous group with the additional match, but that group is never added to anything. If you want to customize the groups to this degree, I would refrain from using the iterative way of generating your groups - just set up a list and things will be much easier to maintain.

I'm using the default config from arcolinux-qtile, with some additional changes.
I'll create a list then

**Comment by tcld** [comment]
I think I started out with that, too. But as I said, once you want to actually configure your groups just iterating over a bunch of numbers becomes cumbersome.
I added a few examples in the post above. The configuration works with the master-branch, but won't with 0.16.1 due to some recent changes with the `Match`-class.

**Comment by sirakai-pc** [comment]
It worked perfectly, thanks.
There only appears to be a strange bug with spotify.. It doesn't open in the correct group.
`    Group('0', position=8, label='', layout='max', matches=[Match(wm_class='spotify'), Match(wm_class='TelegramDesktop')])
`
I checked with xprop the correct wm_class.
I don't think it's related to qtile, so if you can't help the issue can be closed.

**Comment by sirakai-pc** [comment]
Oh I would have also another request, how can I focus on the layout where the window launched? It happens only with few windows and I'm not using so many different layouts therefore I don't know the reason

**Comment by tcld** [comment]
About Spotify: Are you sure you don't have any other `Match`es set up for it? Also, some windows seem to change their class while booting up and thus end up in the wrong group (#1915).

About the auto-switch: I have seen a number of solutions for this, so I'm not sure this is the best one, but try this (since you are already subscribed to the hook, you can just add the body of the function):

```python
@hook.subscribe.client_new
def modify_window(client):
    for group in groups:  # follow on auto-move
        match = next((m for m in group.matches if m.compare(client)), None)
        if match:
            targetgroup = client.qtile.groups_map[group.name]  # there can be multiple instances of a group
            targetgroup.cmd_toscreen(toggle=False)
            break
```

**Comment by sirakai-pc** [comment]
No with this code it doesn't work.
Also I experienced that with some program if I open multiple istances(windows) only the first goes to the right group.(only brave-browser does this for now) 
That's not a big issue anyway.

**Comment by ramnes** [comment]
Your code was badly formatted because you used one back-tick (`) on each side of your code instead of three (```).

The issue with Spotify is that it doesn't have a class when it's spawned, only a few ms later. Have a look [here](https://groups.google.com/g/qtile-dev/c/DYVYuAzYbG4/m/R8IWR-hfAgAJ). Closing in favor of #1915.

Please keep one subject per issue on GitHub for readability matters. IRC and the mailing list are better places for a free discussion. :)
