### ISSUE TITLE
Custom bar on a specific layout(and group)

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1992]
Is there a way to add and remove widgets from the bar only in a group? I would like to add "widget.TaskList()" only to the treetab layout.

# Issue description

# Qtile version

# Stack traces

# Configuration

**Comment by m-col** [comment]
Interesting question!

Firstly, a "group" is a virtual desktop, and can use different layouts, so
you'll have to hook into either the `setgroup` or `layout_change` hooks
depending on which one you want.

I'm not sure exactly what would get the behaviour that you want, but the first
thing I would try if I was trying to get it would be to add/remove the widget
the appropriate `bar.widgets` list upon firing of one of the hooks above, then
call `bar.draw`. Maybe that'd trick the bar into thinking the widget isn't
there.

**Comment by elParaguayo** [comment]
@m-col That should work as that's the trick you suggested for my WidgetBox widget and it worked brilliantly.

Alternatively, you build something more fundamental into the code so the user can add a parameter for the widget e.g. 
``` python
widget.TaskList(visible_on=["treetab"])
```

I don't think it would be too hard to code but not sure if there'd be sufficient interest in this to make it worthwhile (no offence @sirakai-pc !)

**Comment by m-col** [comment]
I agree that it wouldn't be too hard to implement, which is why it would be easy
to have it set up in a user's config without needing to add more code to
libqtile :) If down the line more people express an interest in this then
perhaps it'd be worth having it.

**Comment by sirakai-pc** [comment]
Guys the real problem that I'm facing with qtile is the documentation of real examples. As a semi-beginner on qtile I just don't understand how I'm supposed to undestand what kind bar.widgets list I should modify.
(I really like qtile unless for these things)
I tried so without any result(I didn't expect it to work bcs I didn't find any example or documentation to do so):
```
@hook.subscribe.layout_change
def tabbed_layout(layout, group):
    #if(layout=="treetab")
    #if(group=="7")
    if (qtile.CurrentLayout == "treetab"):
        global widgets_list
        widgets_list[4]=widget.TaskList()
        init_screens
        #bar.draw()
```
widget_list is the list used by this function:
```
def init_screens():
    return [Screen(top=bar.Bar(widgets=init_widgets_list(), size=26)),]
```
to initially draw the bar on screen0 (?), idk.

My [config .py](https://pastebin.com/Nc8aCycP)

**Comment by m-col** [comment]
> Guys the real problem that I'm facing with qtile is the documentation of real examples

The problem with this kind of problem is that this is a new idea, and there are so many new ideas and possiblities that it is impossible for us to have an example way to do everything. You are the very first person AFAICT to want this behaviour. That's fine, but please remember that us giving advice on how to do something like this also involves us figuring it out (which, remember, also takes our own time), not us just copying it from elsewhere. Be the change you want to see, and submit the working example to our examples repository once it's done.

FWIW I think you are in the right direction. You need to store the `bar` somewhere, and modify that, as that is the object that handles the bar that you're trying to modify.

```python
mybar = bar.Bar(widgets=init_widgets_list(), size=26)
tasks = widget.TaskList()

def init_screens():
    return [Screen(top=mybar),]
```
Then in the hook you can modify it:
```python
@hook.subscribe.layout_change
def tabbed_layout(layout, group):
    if (qtile.current_layout.name == "treetab"):
        mybar.widgets.insert(4, tasks)
        mybar.draw()
```
This is untested, but should get you in the general direction I think.

**Comment by Barbarossa93** [comment]
FWIW, I think this would be a very nice feature to have. I find having the TaskList widget a logical choice when using the floating layout compared to WindowName for the other tiling layouts.

@m-col , if I wanted to replace a widget, could I do:
```
mybar = bar.Bar(widgets=init_widgets_list(), size=26)
tasks = widget.TaskList()
windowname = widget.WindowName()

@hook.subscribe.layout_change
def tabbed_layout(layout, group):
    if (qtile.current_layout.name == "treetab"):
        mybar.widgets.remove(4, windowname)
        mybar.widgets.insert(4, tasks)
        mybar.draw()
```
I'm not sure what the 4 is referring to, does it indicate to remove/insert the fourth (third if we're talking 0 index?) widget?

**Comment by slowsage** [comment]
Fwiw, this works for me:
```
class AutoWidgetBox(widget.WidgetBox):
    def _configure(self, qtile, bar):
        widget.WidgetBox._configure(self, qtile, bar)
        if len(self.layouts_open) + len(self.layouts_close) > 0:
            self.setup_hooks()

    def __init__(self, widgets: list = None, layouts_open: list = [], layouts_close: list = [], **config):
        widget.WidgetBox.__init__(self, widgets, **config)
        self.layouts_open = layouts_open
        self.layouts_close = layouts_close

    def setup_hooks(self):
        def hook_response(layout, _):
            if (layout.name in self.layouts_open and not self.box_is_open) or (layout.name in self.layouts_close and self.box_is_open):
                self.cmd_toggle()
        hook.subscribe.layout_change(hook_response)
```
