### ISSUE TITLE
qshell command not found

### ISSUE THREAD

**Issue by erichamers** [qtile/qtile#1997]
Hello everyone,

I installed qtile from the AUR repo, `yay -S qtile-git` and I can't run any of the commands. Specifically I'm trying to run `qshell` but I'm getting `command not found: qshell` error. I'm using zsh but I've tried with bash and doesn't work there aswell. Can anyone help me figure out what's happening? 

Thanks!

Edit: Oh! And qtile does run btw.

**Comment by tych0** [comment]
On Mon, Dec 07, 2020 at 07:39:33AM -0800, Eric Hamers wrote:
> Hello everyone,
> 
> I installed qtile from the AUR repo, `yay -S qtile-git` and I can't run any of the commands. Specifically I'm trying to run `qshell` but I'm getting `command not found: qshell` error. I'm using zsh but I've tried with bash and doesn't work there aswell. Can anyone help me figure out what's happening? 

You're installed from git, which has the unreleased patches for the
command migration:

https://github.com/qtile/qtile/blob/master/CHANGELOG#L22

Tycho

**Comment by erichamers** [comment]
Yeap. Got it working.
