### ISSUE TITLE
Adding Urgency Hint To Window

### ISSUE THREAD

**Issue by erichamers** [qtile/qtile#1999]
Hey guys.

I'm having trouble getting the urgency hint to work with Slack on qtile. I can see notifications from dunstrc but there is no visual hint on the GroupBox widget (color is not beeing applied). From what I read around it seems that this is a problem with applications not setting the correct urgency hints, but saw that there was some workarounds currently working with i3 and wmctrl. Is there something similar I can to in qtile? Can I use wmctrl to add urgency hints in qtile? 

This is my GroupBox config in config.py
```python
widget.GroupBox(
    urgent_alert_method='block',
    highlight_method='block',
    rounded=False,
    disable_drag=True,
    this_screen_border=colors['background'],
    this_current_screen_border=colors['purple'],
    other_screen_border=colors['dark_gray'],
    other_current_screen_border=colors['dark_gray'],
    urgent_border=colors['red'],
    inactive=colors['current-line'],
    fontsize=font_size,
    padding_y=5,
    padding_x=8,
),
```

Thanks,
Eric

**Comment by m-col** [comment]
How do they trigger the wmctrl calls in the workaround you found for i3? A
similar thing should work in qtile -- wmctrl doesn't care about WM.

**Comment by erichamers** [comment]
@m-col They added the following script
```bash
#!/bin/sh
wmctrl -r $1 -b add,demand_attention
```
and this block to `dunstrc`
```bash
[slack]
    appname = Slack
    summary = "*"
    script = "path/to/script/notification.sh"
```

**Comment by m-col** [comment]
If you set that up the same way in qtile, does the groupbox not show the urgency
hint?

**Comment by erichamers** [comment]
I was able to get it to work by modifying the command to something like this:
```bash
wmctrl -r "slack" -b add,demands_attention
```
I'll just leave it here in case anyone runs into the same issue.
