### ISSUE TITLE
to log out linux

### ISSUE THREAD

**Issue by lucas-FP** [qtile/qtile#2000]
# Issue description

# Qtile version

# Stack traces

# Configuration

**Comment by m-col** [comment]
Did you, err, forget to add the text?

**Comment by tramhao** [comment]
I met the same problem because the recent changes. I'm using git version
qtile cmd-obj -o cmd -f shutdown

**Comment by ramnes** [comment]
Wut? Please re-open an issue if needed, but with a description this time.
