### ISSUE TITLE
NotificationManager does not capture Notifications from Chrome/Chromium

### ISSUE THREAD

**Issue by tchar** [qtile/qtile#2001]
Hello I started hacking into qtile recently and I came across the following issue.

# Issue description

Notifications will not work in Chrome/Chromium.

When I use `notify-send` notifications work normally.
I also tested it with [Mailspring](https://getmailspring.com/), it works.

Chromium notifications will appear inside a chrome popup and will not be sent to the [NotificationManager](https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L97)

## What I tried
At first I though it was my configuration's problem because I am using a `NotificationClient` implementation of my own because it does not exist in `qtile`. However this is not the issue. I also tried it with the default configuration and the issue is still there:

I run the following to check what is received by the bus
```
dbus-monitor path=/org/freedesktop/Notifications
```
And this actually confirms it. Other notifications show up properly, but Chrome related ones don't.

It looks like Chrome is not sending any notification to the bus.

## How I (partially?) fixed it (at least works for me)
By running
```
dbus-monitor path=/org/freedesktop/Notifications
```
and by killing chrome and starting it from scratch I get the following outputs from the command above

With qtile:
```
method call time=1607498444.683416 sender=:1.39 -> destination=org.freedesktop.Notifications serial=4 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
```
With gnome:
```
method call time=1607498013.203004 sender=:1.149 -> destination=org.freedesktop.Notifications serial=4 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
method call time=1607498013.203382 sender=:1.66 -> destination=:1.43 serial=31 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
method call time=1607498013.205821 sender=:1.149 -> destination=org.freedesktop.Notifications serial=5 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1607498013.205878 sender=:1.66 -> destination=:1.43 serial=35 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
```

It looks like that Chrome is quering the capabilities of the [NotificationService](https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L44).

As of now the only capabilities are `body` ([link](https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L51)).

So I changed the `capabilities` to 
```
self._capabilities = {'body', 'actions', 'body-hyperlinks', 'body-markup'}
```
and I am now able to get notifications properly form chrome.

As far as the capabilities that Chrome uses, according to [this](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/browser/notifications/notification_platform_bridge_linux.cc) these are:
```
const char kCapabilityActionIcons[] = "action-icons";
const char kCapabilityActions[] = "actions";
const char kCapabilityBody[] = "body";
const char kCapabilityBodyHyperlinks[] = "body-hyperlinks";
const char kCapabilityBodyImages[] = "body-images";
const char kCapabilityBodyMarkup[] = "body-markup";
const char kCapabilityIconMulti[] = "icon-multi";
const char kCapabilityIconStatic[] = "icon-static";
const char kCapabilityPersistence[] = "persistence";
const char kCapabilitySound[] = "sound";
const char kCapabilityXKdeOriginName[] = "x-kde-origin-name";
```

I haven't extensively tested it to be honest and I am not sure whether or not this will impact qtile but maybe you consider adding them or maybe you have a reason you haven't added them.

If there is no reason. I could create a pull request so that they can be added.

# Qtile version

Arch-Linux: 0.16.1(From packages)
Ubuntu: 0.16.1 (Compiled from source)

# Stack traces

There is no stack trace error

# Configuration
Configuration independent
You can use the default configuration with a widget.Notify to test it.

**Comment by tych0** [comment]
Is there any reason not to patch this upstream? Seems like a reasonable patch to me.

On Wed, Dec 9, 2020, at 2:39 AM, Tilemachos Charalampous wrote:
> 

> Hello I started hacking into qtile recently and I came across the following issue.

> Issue description

> Notifications will not work in Chrome/Chromium.


> When I use `notify-send` notifications work normally.
> I also tested it with Mailspring <https://getmailspring.com/>, it works.

> Chromium notifications will appear inside a chrome popup and will not be sent to the Notificationmanager <https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L97>

> What I tried

> At first I though it was my configuration's problem because I am using a `NotificationClient` implementation of my own because it does not exist in `qtile`, however this is not the issue because I tried it with the default configuration and the issue is still there:

> I run the following to check what is received by the bus

> `dbus-monitor path=/org/freedesktop/Notifications
`
> And this actually confirms it. Other notifications show up properly, but Chrome related ones don't.

> It looks like Chrome is not sending any notification to the bus.

> How I (partially?) fixed it (at least works for me)

> By running

> `dbus-monitor path=/org/freedesktop/Notifications
`
> and by killing chrome and starting it from scratch I get the following outputs from the command above

> With qtile:

> `method call time=1607498444.683416 sender=:1.39 -> destination=org.freedesktop.Notifications serial=4 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
`
> With gnome:

> `method call time=1607498013.203004 sender=:1.149 -> destination=org.freedesktop.Notifications serial=4 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
method call time=1607498013.203382 sender=:1.66 -> destination=:1.43 serial=31 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
method call time=1607498013.205821 sender=:1.149 -> destination=org.freedesktop.Notifications serial=5 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1607498013.205878 sender=:1.66 -> destination=:1.43 serial=35 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
`
> It looks like that Chrome is quering the capabilities of the NotificationService <https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L44>.

> As of now the only capabilities are `body` (link <https://github.com/qtile/qtile/blob/de7d13413a83fa619c3218f8ac0fb677add8bc1a/libqtile/notify.py#L51>).

> So I changed the `capabilities` to

> `self._capabilities = {'body'}` to `{'body', 'actions', 'body-hyperlinks', 'body-markup'}
`
> and I am now able to get notifications properly form chrome.

> As far as the capabilities that Chrome uses, according to this <https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/browser/notifications/notification_platform_bridge_linux.cc> these are:

> `const char kCapabilityActionIcons[] = "action-icons";
const char kCapabilityActions[] = "actions";
const char kCapabilityBody[] = "body";
const char kCapabilityBodyHyperlinks[] = "body-hyperlinks";
const char kCapabilityBodyImages[] = "body-images";
const char kCapabilityBodyMarkup[] = "body-markup";
const char kCapabilityIconMulti[] = "icon-multi";
const char kCapabilityIconStatic[] = "icon-static";
const char kCapabilityPersistence[] = "persistence";
const char kCapabilitySound[] = "sound";
const char kCapabilityXKdeOriginName[] = "x-kde-origin-name";
`

**Comment by m-col** [comment]
It would be against the notification spec for the notification service to advertise capabilities that it does not have. The issue with adding them is that it removes some functionality (e.g. executing an action upon click) that the program sending the notification (and its users) expect. The behaviour seem by chrome is expected. If you can force chrome to use the notification service by falsifying the capabilities like you have, then great, but I don't think we should do so within qtile.

**Comment by tych0** [comment]
Great, thanks for clarifying. I suppose we could add these features, but I agree we probably shouldn't just add the capabilities without adding those features.

**Comment by m-col** [comment]
FWIW hooking into `NotificationManager` to make your own service with its own capabilities is relatively easy:
```
from libqtile.notify import notifier
capabilities = {"body", "actions"}

def handle_notification(notification):
    # do something

notifier.register(handle_notification, capabilities)
```

The only place this is done within libqtile is for the `Notify` widget, which does not add any new capabilities. But adding some new capabilities to the widget would be cool, and I suspect that adding "actions" would be easy, perhaps also "body-markup".

**Comment by elParaguayo** [comment]
@m-col any pointers on how you'd do this?

I've been updating the NotificationManager as part of the dbus_next work so I could look to incorporate changes here.

However, for `actions` I understand the manager should send the ActionInvoked signal. That part should be easy but how do we know which action was invoked? I believe notifications can send more than one.

For `body-markup` is that the same as the markup used by the text layouts? If so, that seems like an easy win.

**Comment by tchar** [comment]
Hi sorry for not responding. My laptop died and I am basically doing everything from a 1.7 Gb Ram garbage so I am a bit  restricted.

@m-col  I would like to make some comments on the `NotificationManager` so I get the idea.

1. Two widgets registering for different capabilities will create a superset of capabilities and then receive all the notifications regardless of their ability to handle them. This is because the `NotificationManager` just calls all the callbacks. Is this a problem? Unless you are sure that only one notification  handler will be active each time.

2. I was digging in the code and I missed the extra argument for registering.

This is what I ended up doing. I actually extended the widget's capabilities so it has more functionality. Keeps the old functionality too but can also display other things like total notifications, number of urgent/normal/low notifications separately with different colors. I am using the format argument so you can choose whatever you need of the available options.

I also wrote the python code to call `Rofi` as a notification gui manager (custom dmenu option) so that you can dismiss notifications from there instead of clicking at the widget.

Because I did not want to break the original `NotificationManager` I wrote a `NotificationClient` that registerns on the `NotificationManager` and acts like a proxy between any widget/program that uses Notifications. First notification logic is not handled by the widget except what is viewed (but not what is dismissed) so that any gui/widget can be consistent when something is added/dismissed or gets `timeout`.

I am currently working on performing actions (i.e open link that was received from the Browser).

I am not sure if you are interested in something like that for Qtile but I woudl like to know in which features you are interested in.

3. I also thought that maybe it is a good idea to add the ability to permanently delete notifications from the `NotificationManager` some notifications (like the one from mailspring) actually occupy a lot of memory because they carry image information inside the hints (the icon). So maybe it is a good idea to add an interface to the notification manager to do that. Yeah you can actually set the list of notifications manually but without locking and thread safe operations I prefer to let them live there until the `NotificationManager` is restarted.

@elParaguayo I guess you mean that the user should select if they want to invoke an action or not right? You can refer to the action based on the notification_id and the id/index of the specific action. Problem is that some actions are sent through the hints for some applications for some reason and this is where I am stuck at.

**Comment by m-col** [comment]
> However, for actions I understand the manager should send the ActionInvoked signal. That part should be easy but how do we know which action was invoked? I believe notifications can send more than one.

I wasn't aware of this, but it's great to know. Do you have a link to ActionInvoked? Searching isn't finding anything. The notification service would have to deal with reading which option was clicked i.e. the notify widget would have have to take the coordinate of a click (if any) and turn it into the chosen action, then return that information.

> Two widgets registering for different capabilities will create a superset of capabilities and then receive all the notifications regardless of their ability to handle them. This is because the NotificationManager just calls all the callbacks. Is this a problem? Unless you are sure that only one notification handler will be active each time.

I would expect people to only ever use one notification service, but in any case, I don't think this would cause a problem because as long as a given capability is covered by one service, then it's all good.

The changes that you mention all sound like good additions. My only gripe is the rofi stuff, because IMO that gets into the territory of opinionated "this is how you must build your setup" kinda stuff. I suppose it depends on how it is implemented, but it could get unwieldy because you'd have to somehow account for all argument options etc (if I'm picturing what you've made correctly!).

>  wrote a NotificationClient that registerns on the NotificationManager and acts like a proxy between any widget/program that uses Notifications

I think that was the intent of the NotificationManager (`NotificationService` is then the more 'low-level' bit). What behaviour did you need that you'd need to extend NotificationManager to get? We could extend that if it made sense.

I think the actions handling in particular would be great. Any other useful additions to the manager and/or widget that others would use would definitely be worth considering too. Clearing all past notifications also sounds like a useful thing to be able to do. I made myself a notification service using `libqtile.popup` [here](https://mcol.xyz/code/qtools/file/qtools/notification/notification.py.html), you might be able to lift some of the logic from there to save some time.

**Comment by elParaguayo** [comment]
There's a bit about ActionInvoked here: https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html

**Comment by tchar** [comment]
> There's a bit about ActionInvoked here: https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html

@elParaguayo Thanks I will have a look at it

> 
> I would expect people to only ever use one notification service, but in any case, I don't think this would cause a problem because as long as a given capability is covered by one service, then it's all good.
> 
> The changes that you mention all sound like good additions. My only gripe is the rofi stuff, because IMO that gets into the territory of opinionated "this is how you must build your setup" kinda stuff. I suppose it depends on how it is implemented, but it could get unwieldy because you'd have to somehow account for all argument options etc (if I'm picturing what you've made correctly!).
> 
> I think that was the intent of the NotificationManager (`NotificationService` is then the more 'low-level' bit). What behaviour did you need that you'd need to extend NotificationManager to get? We could extend that if it made sense.
> 

Ok First of all I am not sure if this should be another issue since what I am about to write is not directly related to the original issue. I will refer to the original issue though.

I agree about the rofi. The rofi is just an example. In the end it is just a callable class that subscribes to the `NotificationManager`. Now I am not saying to include rofi in `Qtile` because it is tottally unrelated and we should not force users use "our" tools. For that reason I am keeping it outside of this conversation and just let it be on my repo.

So here are the two main topics.

### Notification Deletion/Dismiss

My main point is to make the `NotificationManager` to be able to notify all subscribers for notification deletion. This has 2 main benefits.
1. Lets the Notification system to make all subscribers communicate any Notification dismiss. (In my case it is the `Notify` widget and `Rofi` but this is just an example, it can be anything).
2. Lets the user actually delete Notifications from the memory. This lets the whole Notification system to free up memory
  - As an example the notifications that come through `Mailspring` are quite large because they carry the icon itself in bytes in the `hints`. I don't see any reason for these staying into memory until  the restart/shutdown of `Qtile` if the user wants to dismiss them.

So I wrote a NotificationProxy in my [repo](https://github.com/tchar/qtile-extras/blob/bc9c0f5df17cfd377e4487cf36aec13f71e92e00/libqtile_extras/notify/notify.py#L39
) but it has some drawbacks like where to put locking for notification access etc.

For that reason I cloned `Qtile` and updated the `NotificationManager` and the `Notify` widget to be able to handle Notification dismiss/delete.

[Here](https://github.com/tchar/qtile/blob/master/libqtile/notify.py) is the updated `libqtile/notify.py` and [here](https://github.com/tchar/qtile/blob/master/libqtile/widget/notify.py) is the `Notify` widget (`libqtile/widget/notify.py`) that handles deletion signaled from other subscribers (`Rofi` in my case).

Now I am not sure if you are interested in something like that. If yes I can make a Pull Request (run all tests properly etc) and we can discuss implementation specifics (like if locking should be used, what kind etc) there. 

Please let me know if you are interested in a Pull Request with Notification Deletion.

### Notify widget capabilities.

Now my main problem that I had with the capabilities is that although the current implementation cannot handle some Notifications due to markup/actions etc, it can however handle Notification count with small modification (using the format option. [example](https://github.com/tchar/qtile-extras/blob/master/libqtile_extras/widget/notify.py)). And since it can count Notifications it could register for more capabilities to actually capture them. This is basically why I opened the issue in the first place.

I already have implemented that but I am gonna keep it out of the discussion for now since I think the Notification deletion is more important.

> I think the actions handling in particular would be great. Any other useful additions to the manager and/or widget that others would use would definitely be worth considering too. Clearing all past notifications also sounds like a useful thing to be able to do. I made myself a notification service using `libqtile.popup` [here](https://mcol.xyz/code/qtools/file/qtools/notification/notification.py.html), you might be able to lift some of the logic from there to save some time.

That's pretty cool I'll give it a try for sure.

Cheers.
