### ISSUE TITLE
Test fails and missing file from documentation

### ISSUE THREAD

**Issue by erichamers** [qtile/qtile#2003]
I just forked qtile's repo and tried to run the tests on the tests folder and test_scratchpad.py is failing the tests.

Also, in the documentation part about hacking qtile (http://docs.qtile.org/en/latest/manual/hacking.html), the **Development and Testing** section tells me to run `tests/test_module.py`, but there is no such file in the repo.

**Comment by erichamers** [comment]
Just realized the error is because I had no ImageMagick installed. But it doesn't say so in the documentation, so maybe something that should be added as a dependencie to be installed?

**Comment by tych0** [comment]
Funny that the detection code assumes it exists :-)

Yep, looks like a bug.

**Comment by erichamers** [comment]
@tych0 the missing file or test_scratchpad.py failing the tests?

**Comment by tych0** [comment]
That it fails the tests. Looks like the intent is to skip.

**Comment by tych0** [comment]
See above, I believe that patch should fix it.

**Comment by erichamers** [comment]
I found that tests were failing because I was missing xterm. Installed xterm and it worked. I'm on arch.

**Comment by tych0** [comment]
Sure, that may be a different problem. Convert is only used for a small set of tests, but xterm is used everywhere :)

**Comment by erichamers** [comment]
Yeap, got it, but maybe that's one thing that should be added as a dependecy on the documentation?
