### ISSUE TITLE
Bug with mouse_callbacks on latest master branch of qtile

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#2005]
# Issue description
[Video Demonstration](https://vimeo.com/489876470)

As shown in the video, whenever I launch qtile or restart it all my mouse_callbacks keys launch like they were put in the autostart hook. They don't work as mouse events on the widgets. I had every single mouse callback assigned to a function but then I just put the instruction directly assigned to the key like this:
```
widget.Battery(
		charge_char='+',
		discharge_char='-',
		format='{char}{percent:2.0%}',
		#low_foreground='990033',#?????
		#low_percentage=0.20,#?????
		notify_below=15,
		mouse_callbacks={'Button1': qtile.cmd_spawn('bash '+home+ '/.bin/show_battery.sh'), 'Button2': qtile.cmd_spawn('xfce4-power-manager-settings')}
        ),
```
I tried so because the other way wasn't working.
I installed the master branch of qtile as suggested to solve another issue I were facing. 
Maybe I installed it wrong.. I didn't find any bug like this until now.

# Qtile version
```
please move to `qtile start` as your qtile invocation, instead of just `qtile`; this default will be removed Soon(TM)
usage: qtile [-h] [--version] {start,shell,top,run-cmd,cmd-obj,help} ...
qtile: error: unrecognized arguments: --version
```

# Stack traces

# Configuration
[config](https://pastebin.com/3KFMhHTV)

**Comment by leschalu** [comment]
I had similar problem with my custom calendar. Here how I solved it:

1. import run
```python
from subprocess import run
```

2. define fucntion
```python
def calnotify():
    run("calnotify.sh", shell=True)
```
3.callback the function
```python
widget.Clock(format="%a %d.%m, %H : %M", background=bgcoldark, mouse_callbacks={"Button1": calnotify}),
```
So far so good.
![2020-12-11-211558_1920x1080_scrot](https://user-images.githubusercontent.com/45047877/101939595-43c66080-3bf6-11eb-963d-6be6f544ca1c.png)

**Comment by tramhao** [comment]
`    widget.CPU(**base(bg='color2'),format = '{freq_current}GHz {load_percent}%', mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(terminal+" -e bpytop")}),
 `

**Comment by m-col** [comment]
Yep, as the above comments are suggesting, the way you are defining the callbacks is problematic. Your line:
```
mouse_callbacks={'Button1': qtile.cmd_spawn('bash '+home+ '/.bin/show_battery.sh'), ... }
```
actually executates the function call `qtile.cmd_spawn('bash '+home+ '/.bin/show_battery.sh')` and the return value of that call is what is put inside the mouse_callbacks dictionary. Your options are to define it as a separate function as @leschalu says, define it as an inline function using `lambda` as @tramhao demonstrates, or look at using `functools.partial` which is very simlar to using `lambda` (the main difference being that lambdas don't evaluate their signature until they are called which in some edge cases can cause unpredictable results).
