### ISSUE TITLE
Qtile loads config but does not work

### ISSUE THREAD

**Issue by SammyTheBEAST** [qtile/qtile#2007]
# Issue description

Qtile starts and loads config but there is no bar and none of my key binds work. My autostart programs launch but I cannot see any of the GUI's other than nitrogen's background and Dunst. I don't think it's a problem with my config as replacing my config with the default one just shows a black screen. XFCE loads fine, I've tried reinstalling qtile with the current commit (4a8ebc8b6c8af22c4c9b5ec70fbcbd1489be2c9a) and it still does not work.

Screenshot of it running in Xephyr, Xeyphyr spawns a terminal (alacritty) which works fine, but I cannot move it and there are no borders:
[![https://imgur.com/yAk53h5.png](https://imgur.com/yAk53h5.png)](https://imgur.com/yAk53h5.pngr)

# Qtile version

qtile 0.16.1-1 (4a8ebc8b6c8af22c4c9b5ec70fbcbd1489be2c9a)

# Stack traces

[qtile.log](https://pastebin.com/BSnjaX4r)
[.xsession-errors](https://pastebin.com/RcrteZBi)

# Configuration

[config.py](https://pastebin.com/PEWwjy0C)
[dotfiles on GitHub](https://github.com/SammyTheBEAST/dotfiles)

**Comment by tramhao** [comment]
It seems all right to me. As long as you don't meet a config error, you can reload qtile to apply the config changes. xepher is not actual x server. Thanks.

**Comment by m-col** [comment]
Just to check: so on that commit, when you run qtile, even with the default config, within a normal X server session, you get these problems? That's.... concerning. If so, the first check might be to run an all-else-equal X session with a different WM, using the same `.xinitrc` and just to rule out that something else is causing the problem.

**Comment by SammyTheBEAST** [comment]
> It seems all right to me. As long as you don't meet a config error, you can reload qtile to apply the config changes. xepher is not actual x server. Thanks.

The problem exists outside of xephyr, running it normally gives the same screen without alacritty. I just used xephyr to get a screenshot. I also cannot reload qtile as none of my keybinds work.


> Just to check: so on that commit, when you run qtile, even with the default config, within a normal X server session, you get these problems? That's.... concerning. If so, the first check might be to run an all-else-equal X session with a different WM, using the same `.xinitrc` and just to rule out that something else is causing the problem.

I can use XFCE just fine without changing anything. If I load qtile with the default config under a normal X session it works normally (running it in xephyr does not work), I can then replace the normal config with my own and restart qtile (super+ctrl+q), then it works normally. If I keep my config and reboot, it breaks again.

The only thing that loads only once during startup is [the script that autostarts my programs](https://github.com/SammyTheBEAST/dotfiles/blob/master/.config/qtile/scripts/autostart.sh) (line 302 in my config.py), that must be the problem. If I comment that out, qtile works normally in both xephyr and a normal X session. I can then run autostart.sh in a terminal and everything works fine. Does anyone know why running autostart.sh during startup would break everything?

**Comment by SammyTheBEAST** [comment]
I found the issue, in my autostart.sh script it was starting the greenclip daemon but not as a background task, causing all of the programs before it to load but stalling the main qtile loop. I've changed the script to start the greenclip daemon in the background and reformmated the autostart function in my config.py to start programs in another thread, that way if an autostart program failed it at least doesn't cause qtile to crash.

**Comment by m-col** [comment]
I'm glad you found the issue. How did you discover that that was the problem? I'm thinking that any stdout from a program run by qtile could be logged, which would make things like this easily detectable, but there might be problems with doing so that I'm overlooking.

**Comment by SammyTheBEAST** [comment]
> 
> 
> I'm glad you found the issue. How did you discover that that was the problem? I'm thinking that any stdout from a program run by qtile could be logged, which would make things like this easily detectable, but there might be problems with doing so that I'm overlooking.

If you look at my startup script I'm using echo to log what programs are starting to stdout which does work. This just so happened to be the last program loaded, so it all looked normal. You could make an echo after all the programs are running to make sure the script exited properly, that would make it clear that a program was running in the foreground.
