### ISSUE TITLE
mouse_callback functions do not receive qtile as argument

### ISSUE THREAD

**Issue by lucas-FP** [qtile/qtile#2008]
# Issue description

It is described in the commentary section in the `BaseWidget` class that the mouse callback functions expect a `qtile` object as argument:

```
        def open_calendar(qtile):
            qtile.cmd_spawn('gsimplecal next_month')

        clock = widget.Clock(mouse_callbacks={'Button1': open_calendar})
```

But in the implementation, this object is not being passed to the callbacks. (line 227). I tried to change it by smply passing the qtile object, as it was before the [changes made by mcol 4 months ago](https://github.com/qtile/qtile/commit/55f92b22b346ccd8a4c3e1867080bc82dbcaf33b#diff-932dbeefdf2b3d64837a8571334e72328fd8580e50c453de2c5652ade6e2d3b6), but then the default callbacks for the other widgets stopped working because they were receiving an extra argument. 

Either the class description should be changed to the new behavior, or the `qtile` object should be passed to the callbacks. If the correct behavior is to not pass the `qtile` object, how do I access it from the config?

Also, this might be related to #1923 

# Qtile version
0.16.1 (up to date with master branch)

**Comment by tcld** [comment]
The comment was probably overlooked when the behaviour was changed. If access to the `qtile`-object is needed, one can do something like `from libqtile import qtile`.

**Comment by m-col** [comment]
Yep, the comment was overlooked, and needs to be updated accordingly, and as
@tcld shows the qtile object is now importable directly. Thanks for letting us
know :)

**Comment by lucas-FP** [comment]
Thank you for the fast answer @tcld and @m-col!
