### ISSUE TITLE
Make LazyCall objects callable

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2018]
... so that an issue like #2005 can be resolved with something like this:

```python
mouse_callbacks={'Button1': lazy.spawn('...')}
```

Am I missing an obvious reason why we don't want them callable, or can't have them?

**Comment by tych0** [comment]
IMO, mostly because of,

> There should be one-- and preferably only one --obvious way to do it.

This problem arises from people not understanding when things are executed. Papering over their misunderstandings will only lead to more misunderstandings down the line.

Perhaps we could use a document explaining the difference between lazy.* and hooks, mouse_callbacks, etc.

Or an even more radical idea: we should deprecate lazy.* all together, since it's kind of a weird DSL. Instead, we could just have everything bind to regular python functions/closures which might make a lot more sense.

**Comment by ramnes** [comment]
> This problem arises from people not understanding when things are executed. Papering over their misunderstandings will only lead to more misunderstandings down the line.

Yeah, it's an understanding problem before anything. But don't you think that it would be nice to reuse lazy.* here, so that you could use all the cmd functions as lazy functions without having to rewrite the laziness by yourself every time?

> Or an even more radical idea: we should deprecate lazy.* all together, since it's kind of a weird DSL. Instead, we could just have everything bind to regular python functions/closures which might make a lot more sense.

Are you reading my mind? I would love this!

**Comment by tych0** [comment]
> But don't you think that it would be nice to reuse lazy.* here, so that you could use all the cmd functions as lazy functions without having to rewrite the laziness by yourself every time?

I'm not sure what you're re-using. The implementation of the nonlazy way is now:

```
from libqtile import qtile

mouse_callbacks={'Button1': qtile.cmd_spawn('...')}
```

which doesn't seem so bad to me.

> Are you reading my mind? I would love this!

It might be an interesting exercise for the first `qtile migrate` migration. Once I'm done with `qtile check` I intend to implement some migrations to see how it would work, but if you got to it before me I wouldn't be offended :)

**Comment by ramnes** [comment]
> I'm not sure what you're re-using. The implementation of the nonlazy way is now:
> 
> ```
> from libqtile import qtile
> 
> mouse_callbacks={'Button1': qtile.cmd_spawn('...')}
> ```
> 
> which doesn't seem so bad to me.

My whole point is that you can't do that, actually! You've got to encapsulate in a lambda at best, or you'd actually call the command when the config is read.

**Comment by tych0** [comment]
Yes, naturally I missed the lambda :-)

But overall it doesn't seem too bad to me. Having confusing semantics seems much worse.

On Sun, Dec 20, 2020, at 1:50 PM, Guillaume Gelin wrote:
> 

>> I'm not sure what you're re-using. The implementation of the nonlazy way is now:

>> `from libqtile import qtile

mouse_callbacks={'Button1': qtile.cmd_spawn('...')}
`

**Comment by m-col** [comment]
What would you do about things like `lazy.window.kill()`? Turn that into `lambda: qtile.current_window.kill()`?

**Comment by tych0** [comment]
> Also, we shouldn't expect users to use cmd_* functions directly as this is the internal API

No, it's not. It's not because we grep for cmd_ and expose that via lazy, which is what people use in their configs. So cmd_ prefixed things are exactly the external API.

**Comment by tych0** [comment]
> What would you do about things like lazy.window.kill()? Turn that into lambda: qtile.current_window.kill()?

I don't really have a strong desire to get rid of lazy. But if I actually thought that this was a problem, that's the way I'd pursue fixing it :)

**Comment by m-col** [comment]
Fair enough. I guess one thing that seems intuitive that doesn't work is just
binding a function like you mention above. Like, why use lazy.function(func) at
all?

Might be one doable change :)

**Comment by ramnes** [comment]
> > Also, we shouldn't expect users to use cmd_* functions directly as this is the internal API
> 
> No, it's not. It's not because we grep for cmd_ and expose that via lazy, which is what people use in their configs. So cmd_ prefixed things are exactly the external API.

What's the limit of what you consider to be the external API then? Is something like qtile.current_window part of the external API for you? I'm getting confused as to what we expect end users to know or not. The qtile.cmd_ notation isn't documented anywhere AFAIK, so they can't know they have to use this other than by looking at the code.

Whether we deprecate the lazy notation or not, we should probably define clearly with documentation, guidelines and/or conventions what is public or private.

**Comment by tych0** [comment]
Yes, agreed that we don't have a clear discussion of what's public API. Right now lazy.* clearly is, which translates to things prefixed with cmd_*; we have been a lot more lax about changing signatures/names of things internally when things aren't prefixed with cmd_*.

There's a bit of discussion around this in #1773; it's something I'd certainly want to clearly define before we did a 1.0. Really I'd like to implement `qtile migrate` and see how well it works in practice before doing anything concrete.

**Comment by tych0** [comment]
And FWIW, I don't consider `qtile.cmd_*` the public API, but the `lazy.*` bits. Since the `cmd_` prefix is how we resolve this right now, that dictates the public API.

But if we did some new kind of resolution (e.g. a decorator on special functions that just had regular names), I would be fine with renaming `cmd_*` to something else, as long as the `lazy.*` resolution keeps working.
