### ISSUE TITLE
cannot install recent versions of qtile on centos 7

### ISSUE THREAD

**Issue by jdratlif** [qtile/qtile#2020]
# Issue description

Installation fails when using pip on centos 7.

I run this command:
`pip3 install --user qtile`

I get this:

```
$ pip3 install --user qtile --upgrade
Collecting qtile
  Using cached https://files.pythonhosted.org/packages/e7/9c/b596f401760395769a8d270a31dbd200287dfad6bfa49e524ac436b548e8/qtile-0.16.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-82oiizpr/qtile/setup.py", line 96, in <module>
        include_package_data=True,
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 107, in parse_configuration
        options.parse()
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 395, in parse
        self.section_prefix, section_name))
    distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-82oiizpr/qtile/
```

# Qtile version

0.16.1

# Other information

If I checkout from git, and get the 0,13,0 version, I can install with pip3 install --user .
0.16.1, 0.16.0, 0.15.1, 0.15.0, 0.14.2, and 0.14.0 all failed the same way.

**Comment by tych0** [comment]
For this specifically, you can probably just remove those, as they're man pages that likely nobody reads.

However, I suspect you'll run into other issues with outdated versions of libraries and such, if your setuptools is this old.

**Comment by jdratlif** [comment]
Thanks. I updated pip, but didn't realize I needed to also update setuptools.

Yes, on CentOS 7, you will need to

python3 -m pip install --user --upgrade pip setuptools
after yum install python3-pip.

Or maybe skip system python3-pip and use get-pip.py instead.

**Comment by ramnes** [comment]
I seem to understand that upgrading setuptools solved your problem, so I'll go ahead and close this. Feel free to comment if you still have any issue!
