### ISSUE TITLE
Memory Widget : RAM percentage only outputs "N/A"

### ISSUE THREAD

**Issue by guillemollix** [qtile/qtile#2030]
# Issue description
I am a user of the Memory widget in the bar. I find really useful for me to have the current percentage of memory used. Unfortunately, when using the MemPercent field in format, it only displays N/A in the bar. 
I think I know why this error shows up. The widget tries to use the `percent` field of the `psutil.virtual_memory()` output. Unfortunately this field does not exist (it exists for swap though, this might be a reason why this is present). 

I don't have enough time to fix this today but I will work on this issue this week and propose a fix. 

# Qtile version
I use qtile 0.16.1-2 from pacman (I guess it corresponds to 04be6f6a50baf8d28ad388eea2fa4b7e13817d52 but i'm really not sure).
However, even with latest update (d6f8a6b2bdb0a184d691e059db03ba0918063997), nothing changed. 

# Config
OS: Arco Linux
Qtile: v0.16.1-2
Python: v3.9.1-1
psutil: v5.7.3-3

**Comment by tych0** [comment]
MemPercent is only in git master, it has not been released (and is not in 0.16.1).
