### ISSUE TITLE
qtile top breaks when the terminal is too small

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2032]
I just launched `qtile top` several times but it only worked once, and broke on the next runs:

```
$ qtile top --force-start
$ qtile top
Traceback (most recent call last):
  File "libqtile/scripts/main.py", line 46, in main
    options.func(options)
  File "qtile/libqtile/scripts/top.py", line 158, in top
    force_start=force_start)
  File "/usr/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "libqtile/scripts/top.py", line 95, in get_stats
    scr.addstr(cnt + 1, 0, '{:<3} {:<40} {:<30}'.format(index, filename, mem))
_curses.error: addwstr() returned ERR
```

Also I'm not sure what's happening, but I can't replicate this in another X session, whether I use PYTHONTRACEMALLOC or --force-start.

**Comment by tych0** [comment]
Seems like maybe it depends on the size of your terminal:

https://stackoverflow.com/questions/54409924/curses-error-addwstr-returned-err-on-changing-nlines-to-1-on-newwin-method

maybe `curses.wrapper` doesn't restore everything entirely correctly?

**Comment by ramnes** [comment]
Uh, yeah, I should have used Google. :)

It indeed breaks when the terminal is too small.
