### ISSUE TITLE
Reload the configuration without restarting

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2053]
In the same vein as #1899, we should expose a command to reload the configuration without restarting. That would minimize the impact of #1874 and other problems related to restarts (like messed up windows), as mentioned by @tych0 in [this comment](https://github.com/qtile/qtile/issues/1874#issuecomment-676477897).

On the implementation level, we must be careful to reset anything we may have loaded from previous configurations before reloading it. I'm thinking about hooks in particular.

End game would be to watch the configuration file. :)

Edit: WIP in #2369

**Comment by ramnes** [comment]
Actually, I'm taking back what I just said about removing anything we loaded already. If we do this, then it's probably just the same as restarting. Maybe just some sort of eval of diffs? Not sure how to do this, thoughts welcome!

**Comment by m-col** [comment]
If this was implemented then what does restarting do? Seems that restarting
(after #1899 is merged) serves exclusively for config reloading.

**Comment by ramnes** [comment]
Restarting would then be kept for when Qtile is in a weird or bad state, I guess? Or to force a reload without checking the config? Or just to upgrade Qtile.

**Comment by m-col** [comment]
I really like this idea, and I'm happy to work on it if nobody else has started or has desire to do so.

Also, reload via SIGHUP would be cool: https://github.com/qtile/qtile/issues/1005

**Comment by ramnes** [comment]
#2369
