### ISSUE TITLE
Fix coveralls

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2054]
https://coveralls.io/github/qtile/qtile

Last update was on November 18th, so I guess something's broken.

**Comment by ramnes** [comment]
We probably want to use this: https://github.com/coverallsapp/github-action

And I want to setup notifications on pull requests when coverage decreases.

**Comment by ramnes** [comment]
Or maybe we should make the tests fail with something like `pytest --cov-fail-under=$(curl -s https://coveralls.io/github/qtile/qtile.json | jq -r '.covered_percent')`

**Comment by m-col** [comment]
I'm not very familiar with coveralls. Am I interpreting correctly that the github action will basically do the coverage test via coveralls for PRs, whereas the pytest will simply do the test itself? And then once a commit has been added to master, coveralls updates?

**Comment by ramnes** [comment]
It will actually just send the coverage results written by pytest-cov during the tests to coveralls servers but yes, you have the overall idea.

**Comment by m-col** [comment]
If we use `pytest --cov-fail-under=$(curl -s https://coveralls.io/github/qtile/qtile.json | jq -r '.covered_percent')` does that basically mean that it will never decrease? That sounds pretty nice.

**Comment by ramnes** [comment]
Yeah, but that can be cumbersome sometime. Ideally you want to do this only when you have 100% coverage to ensure you keep it that way, but alas I don't see us coming close to 100% without something like this.

Also we should rather have this as another test in the CI than hidden in a pytest option, if we can. The result would be the same, a big red thing on PRs that make the coverage decrease, but it would be more explicit as it would have its own line and description.

**Comment by elParaguayo** [comment]
I'm new to this. Is "coverage" essentially having tests that cover every part of the codebase?

If so, how important/realistic is it to have 100% coverage?

I'm happy to spend a bit of time writing some tests but this would probably be centred around the widgets but it would be good to understand how meaningful an impact that exercise would have.

**Comment by ramnes** [comment]
Yeah but here it's about the connection with the service we use to monitor our code coverage (i.e. Coveralls) that seems broken. :)

You can see which parts of the code are untested at the end of a pytest run if you want to work on improving the coverage.

**Comment by elParaguayo** [comment]
Thanks will add to my list!
