### ISSUE TITLE
Docs: Built-in Widgets and Extensions pages show no content

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#2056]
http://docs.qtile.org/en/latest/manual/ref/widgets.html shows a heading but no detail of the widgets (it does work if you select a previous version e.g. v0.16.1).

Not overly familiar with sphinx so not sure how to fix but I don't think the source for that page has been touched since June so I'm assuming problem is elsewhere.

**Comment by tcld** [comment]
I would assume it's related to #2048, but I don't know much about the documentation generation either. @ramnes?

**Comment by ramnes** [comment]
Yeah, we had a similar problem with the previous PR related to widgets laziness, so it's almost sure it's related to that later one. Looking into it.

**Comment by ramnes** [comment]
Thanks for raising the issue!
