### ISSUE TITLE
KeyChord documentation

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2059]
KeyChord really needs a few lines in the docs! Please help if you're using it.

Relevant issues and PR:
* #1190 
* #1208 
* #1777

**Comment by elParaguayo** [comment]
@ramnes I can probably draft something for this.

**Comment by tcld** [comment]
I'm looking forward to some documentation. Tried my hands on the chords, but the handling was quite awkward, so I likely missed something. (I noticed we have a widget related to chords - maybe I should have used it?)
