### ISSUE TITLE
Should mpris widget be deleted?

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#2066]
My understanding is that mpris2 replaced mpris a while ago and I'm not aware of any players that are still exporting an mpris dbus interface as opposed to mpris2.

If that's the case then it would seem sensible to delete the old widget and just keep the mpris2 one.

Looking at the [mpris page on the freedesktop site](https://www.freedesktop.org/wiki/Specifications/mpris-spec/) it even says that v1 is flawed and "should not be used".

**Comment by ramnes** [comment]
Yeah, I don't think there's a point in keeping stuff that has been deprecated upstream. Just opened #2067 to remove the widget. @tych0, thoughts? IIRC you were using that widget.

**Comment by tych0** [comment]
I'm not any more, so bombs away :-)
