### ISSUE TITLE
Gnome or Qtile but not both

### ISSUE THREAD

**Issue by tx-jeeper** [qtile/qtile#2085]
# Issue description
Using Ubuntu and following the docs and configs to run in GNOME, I get GNOME to start, with a Qtile bar but no Qtile WM. 

# Qtile version
Ubuntu 20.04
Qtile - Latest stable version installed with PyPI

# Stack traces

# Configuration
Configs were copied from: http://docs.qtile.org/en/latest/manual/config/gnome.html 
Slight modification to the qtile.session config to remove some of the required components causing crash at login:

Name=Qtile session
RequiredComponents=org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;qtile;

**Comment by ramnes** [comment]
What do you mean by "no Qtile WM"? If the bar is there, then it's most likely running.

**Comment by tx-jeeper** [comment]
The bar is there, but like an application, not as a window manager. You can interact and move the bar. Closing the bar, also closes the session, logging me out.
![Screenshot from 2021-01-09 05-29-09](https://user-images.githubusercontent.com/34829224/104285539-6b207f80-5479-11eb-8617-d54844ddca6a.png)

**Comment by Thesald** [comment]
Seems like you did not just copy and paste extra code from the [wiki page](http://docs.qtile.org/en/latest/manual/config/gnome.html) but also made some customization. If you can give your config file, I will try to recreate the issue. I didn't use Gnome much but I will assume that everything on your system is as default and try to run qtile alongside Gnome with your config file. Please give more information about your system and settings.

**Comment by tx-jeeper** [comment]
@Thesald - I am running a generic install of Ubuntu. 
I copied the extra code from the wiki link/docs that you also linked to.  Which resulted in no desktop at all, and dumped me right back to the login screen after 20-30 seconds.
I kept all the other files as copied, but changed the /usr/share/xsessions file.  After changing the .desktop file in the xsessions folder, I was able to get something to launch from GDM, which was my previous screenshot.
[qtile-gnome-desktop.txt](https://github.com/qtile/qtile/files/5822664/qtile-gnome-desktop.txt)

**Comment by 2br-2b** [comment]
From my understanding, you can only run one window manager: Qtile or Gnome. Trying to run both at the same time gives this options. When logging in, you need to follow the steps from the second answer [here](https://askubuntu.com/questions/162516/switching-window-manager-desktop-environments) to choose a different desktop environment.
