### ISSUE TITLE
AttributeError: 'Static' object has no attribute '_group' when launching KDE's plasmoid popups

### ISSUE THREAD

**Issue by imswebra** [qtile/qtile#2092]
# Issue description
I'm trying to run qtile inside of KDE Plasma as a kwin replacement. I've made minimal changes to the default config aside from adding to the float rules based on KDE's [own documentation](https://userbase.kde.org/Tutorials/Using_Other_Window_Managers_with_Plasma#Configure_i3) regarding configuring i3. Most everything is working, though when I launch a plasmoid (KDE widget) popup by clicking on the plasmoid in my KDE panel, the popups do not appear, and the stack trace below is written to the qtile log. Note I'm using the term "popup" casually, perhaps there is better terminology. Examples of these plasmoids are the bluetooth, wifi or clock ones.

I've also verified that this error occurs when running the default config.

Here is the result of `xprop` (minus a number of KDE-specific properties) on one of these popups from within a regular KDE session:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_TRANSIENT_FOR(WINDOW): window id # 0x2000027
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
WM_CLIENT_LEADER(WINDOW): window id # 0x2000015
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x2000015
WM_CLIENT_MACHINE(STRING) = "imswebra-xps9575"
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 3395, 664
		user specified size: 444 by 390
		program specified minimum size: 12 by 12
		program specified maximum size: 1920 by 1054
		window gravity: Static
```

# Qtile version
0.16.1-2 from the Manjaro community repo

# Stack traces
```
2021-01-10 22:45:18,524 ERROR libqtile xcore.py:_xpoll():L277 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcore.py", line 245, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcore.py", line 589, in handle_MapRequest
    self.qtile.map_window(window)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 543, in map_window
    c = self.manage(window)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 580, in manage
    c = window.Window(w, self)
  File "/usr/lib/python3.9/site-packages/libqtile/window.py", line 791, in __init__
    group = win._group
AttributeError: 'Static' object has no attribute '_group'
```

# Configuration
Error occurs with default config

**Comment by DorianGray** [comment]
Unfortunately I don't know enough to fix this the right way (yet!) but would you mind trying to have the window as a normal Window instead of Static? The issue is that in qtile Static windows can't have groups.

**Comment by imswebra** [comment]
Fairly new to the standalone-WM world, could you point me in the right direction to try that out? Am I just trying to change that window gravity with something like `xprop` or is there an opposite command of `window.Window.cmd_static()` that I could use via a new client hook? Not sure if the former would be possible given that said popups close on focus loss and therefore I can't type in a terminal at the same time they are open.

**Comment by DorianGray** [comment]
Better question - what commands are you running in sequence to cause the above error?

**Comment by imswebra** [comment]
Wish I had a better answer for you.
![Peek 2021-01-11 13-16](https://user-images.githubusercontent.com/29715203/104233509-3e378280-540f-11eb-8d58-dc5983c0b0a8.gif)
Recorded under a normal KDE session.

I did find this [reddit thread](https://www.reddit.com/r/kde/comments/7ms2ew/executing_widgets_manually/) about executing the widgets manually. While this is older, I can still use `plasmawindowed org.kde.plasma.bluetooth` style commands, but of course they launch windowed and therefore I don't see the error. The `plasmoidviewer` command seems to have been removed.

**Comment by m-col** [comment]
So this is with the default config... It looks as though the window is becoming a `Static` window prematurely. Normally (with default config) this should only happen with `dock` windows, and not before the line that is erroring. Nothing in the `xprop` output suggests it should be a made static, and I'm not even sure _where_ the static-related code is executed. Please could you post an xprop of the bar itself? I wonder if child windows of `docks` are themselves automatically `Static` somehow.

**Comment by imswebra** [comment]
Here's the xprop again of the Bluetooth widget, without any filtering this time in case there is something relevant here that simply don't know:
```
_NET_WM_DESKTOP(CARDINAL) = 4294967295
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_KDE_NET_WM_SHADOW(CARDINAL) = 33554763, 33554800, 33554775, 33565037, 33565037, 33565037, 33554759, 33554761, 0, 0, 1, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_KDE_NET_WM_ACTIVITIES(STRING) = "00000000-0000-0000-0000-000000000000"
_NET_WM_USER_TIME(CARDINAL) = 158438578
WM_TRANSIENT_FOR(WINDOW): window id # 0x2000019
_KDE_SLIDE(_KDE_SLIDE) = 0xffffffff, 0x3
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 1, 0, 360, 1, 0, 1, 362, 461
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _KDE_NET_WM_STATE_SKIP_SWITCHER
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "org.kde.plasmashell"
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2000015
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x2000015
WM_CLIENT_MACHINE(STRING) = "imswebra-xps9575"
_NET_WM_PID(CARDINAL) = 3614
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33554498
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 2171, 592
		user specified size: 362 by 462
		program specified minimum size: 12 by 12
		program specified maximum size: 2560 by 1054
		window gravity: Static
```

And here's the xprop of that bottom panel (bar):
```
_KDE_NET_WM_SHADOW(CARDINAL) = 33554463, 33557936, 33557936, 33557936, 33557936, 33557936, 33557936, 33557936, 6, 1, 1, 1
_KDE_NET_WM_ACTIVITIES(STRING) = "00000000-0000-0000-0000-000000000000"
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = 
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP
_NET_WM_USER_TIME(CARDINAL) = 158437107
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 26
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 2559
_KDE_SLIDE(_KDE_SLIDE) = 0xffffffff, 0x3
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_KDE_NET_WM_BLUR_BEHIND_REGION(CARDINAL) = 0, 0, 2560, 26
_KDE_NET_WM_DESKTOP_FILE(UTF8_STRING) = "org.kde.plasmashell"
XdndAware(ATOM) = BITMAP
_KDE_NET_WM_USER_CREATION_TIME(CARDINAL) = 243820
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Plasma"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2000015
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		window id # of group leader: 0x2000015
WM_CLIENT_MACHINE(STRING) = "imswebra-xps9575"
_NET_WM_PID(CARDINAL) = 3614
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33554458
WM_CLASS(STRING) = "plasmashell", "plasmashell"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 1054
		user specified size: 2560 by 26
		program specified minimum size: 2560 by 26
		program specified maximum size: 2560 by 26
		window gravity: Static
```

Again, these are from a traditional KDE session (KDE + Kwin), though I did verify that the xprop output of the panel under a KDE+qtile session is approximately the same (save for PIDs and the like). Note that the original xprop and the screen recording were done on a 1080p 16:9 screen, but these are on a 21:9 ultrawide (hence the 2560px width of the panel).

**Comment by imswebra** [comment]
Sorry for not bumping this earlier. This problem continues to exist with v0.17.0, again with the default config.
