### ISSUE TITLE
Matching programs to specified groups does not work.

### ISSUE THREAD

**Issue by Cindafella** [qtile/qtile#2096]
# Issue description

I can't seem to get programs opening in the specified groups, i've tried multiple snippets from others configs.

# Qtile version

 [04be6f6](https://github.com/qtile/qtile/releases/tag/v0.16.1)

# Configuration

https://pastebin.com/b8VQqL5N

**Comment by Masacaai** [comment]
OS: Arch Linux
Version: 0.16.1 (from the Arch repositories)

I got it to work by doing this:

```
groups = [
        Group("1", label='GEN', matches=[Match(wm_class=["firefox"])]),
        Group("2", label='DEV', matches=[Match(wm_class=["zathura"])]),
        Group("3", label='CHT', matches=[Match(wm_class=["discord"])]),
        Group("4", label='SYS', matches=[Match(wm_class=["ranger"])]),
        Group("5", label='MUS', matches=[Match(wm_class=["spotify"])]),
]

for i in groups:
    keys.extend([

                Key([mod], i.name,
                lazy.group[i.name].toscreen(),
                desc="Switch to group {}".format(i.name)),

                Key([mod, "shift"], i.name,
                lazy.window.togroup(i.name, switch_group=True),
                desc="Switch to & move focused window to group {}".format(i.name)),

                ])
```

I know it's long and inefficient, but at least it works. I tried implementing the code you provided in my config, and I got no results, just like you. Maybe there's a problem in the code?

**Comment by Cindafella** [comment]
Your code works, thanks.

**Comment by desprit** [comment]
The reason your code didn't work was because of the syntax:
```
Match(wm_class="firefox")]
```
should be:
```
Match(wm_class=["firefox"])]
```
