### ISSUE TITLE
`qtile --log-level=INFO` no longer works

### ISSUE THREAD

**Issue by mikelward** [qtile/qtile#2099]
My `.xsession` runs qtile using `qtile --log-level=INFO`.

This no longer works.

```
qtile: error: unrecognized arguments: --log-level=INFO
```

I'm guessing due to 908b910d00087ece13bb576f672c94bcf9e6fc43?

No big deal, but the changelog says

```
          Running `qtile` without arguments will continue to work for the
          forseeable future, but will be eventually deprecated.
```

**Comment by ramnes** [comment]
Eh, yeah, our backward compatibility with `qtile` without argument is just a hack so that we don't break most people stuff. I don't think we want to add more to it to support `qtile start` arguments as well. :)

**Comment by tych0** [comment]
I wonder if we shouldn't support --log-level as a global option for
all commands though. Any chance this works:

https://paste.ubuntu.com/p/KTykfFyjbJ/
