### ISSUE TITLE
Order Groups on Startup

### ISSUE THREAD

**Issue by Sawrz** [qtile/qtile#2101]
Hi,
I have a triple monitor setup, and my middle monitor (Screen1) is my primary screen. Obviously, Qtile assigns the first group to it. However, I want to have something like:
Screen0 = Group0
Screen1 = Group1
Screen2 = Group2

I thought it might be a good idea to use a hook and the `toggle_group` method from the `Screen` class. Something like:

``` Python
@hook.subscribe.startup
def assign_groups_to_screens():
    for i in range(len(screens)):
        screens[i].toggle_group(groups[i])
```

But I get the following error message:

```
2021-01-13 19:08:33,659 ERROR libqtile hook.py:fire():L367 Error in hook startup
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 365, in fire
    i(*args, **kwargs)
  File "/home/sandro/.config/qtile/config.py", line 460, in assign_groups_to_screens
    screens[i].toggle_group(groups[i])
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 378, in toggle_group
    self.set_group(group)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 335, in set_group
    if new_group.screen == self:
AttributeError: 'Group' object has no attribute 'screen'
```

Do I miss something here? I mean, it should work since I use an object's method with another defined object as a parameter, but it won't.

**Comment by m-col** [comment]
Try using the `startup_complete` hook instead. This fires a little later (right at the end of startup) by which point the groups have been given their initial screens.

**Comment by Sawrz** [comment]
The startup_complete hook didn't change much, but I use it anyway since it seems cleaner. I came up with the following solution:

``` Python
from libqtile import qtile

@hook.subscribe.startup_complete
def assign_groups_to_screens():
    screen_arrangement = [2, 0, 1]

    for index, screen_number in enumerate(screen_arrangement):
        qtile.groups_map[groups[index].name].cmd_toscreen(screen_number)
```
