### ISSUE TITLE
QtileState is broken between versions because of moving state.py

### ISSUE THREAD

**Issue by DorianGray** [qtile/qtile#2104]
I believe this might be able to be fixed without a documentation change by encoding the QtileState class definition within the pickle. This would allow QtileState to change and still be successfully restored from a previous version. This might be as simple as using dill instead of pickle.

**Comment by DorianGray** [comment]
...this will not fix old versions, just prevent future changes from breaking again...

I am going to investigate doing some sort of hack to make it work for old versions too

**Comment by tych0** [comment]
I also think it's fine to just not support restarting across versions of qtile. It's really a tool for people testing configs, I never intended to have it be cross version.

**Comment by tych0** [comment]
We could add something to the docstring for cmd_restart() about that though, maybe.

**Comment by DorianGray** [comment]
Yeah, this is definitely just a nice to have and super low priority... just wanted to document these thoughts
