### ISSUE TITLE
VirtualBox dropdown menu shows up behind the parent window

### ISSUE THREAD

**Issue by FroztOfficial** [qtile/qtile#2116]
# Issue description
So when I launch the "Settings" on a VM on VirtualBox, and then click on a dropdown menu, then the menu appear in the back instead of in the front. 

On the picture, you can see that when I click on the version button "Ubuntu (64-bit)", then the dropdown menu appears in the back.

# Qtile Version
Qtile version: 0.16.1

![qtile bug](https://user-images.githubusercontent.com/51519573/104957590-b9300880-59ce-11eb-898c-1daa3aa9d3a8.png)

**Comment by ramnes** [comment]
Can you try the current HEAD of our git repository? I think it has been fixed already.

**Comment by FroztOfficial** [comment]
I just tried the latest version from this git repository and now it seems to work perfectly.
But why have this version(0.16.2) not been pushed to a new release yet? (I am kinda new to GitHub)

Installed version: 0.16.2.dev190+ga7d27ef6

**Comment by ramnes** [comment]
Because it takes time to release a new version. :)
