### ISSUE TITLE
No such key: <libqtile.lazy.LazyCall object at 0x7f216c0dd730>

### ISSUE THREAD

**Issue by MJBN** [qtile/qtile#2118]
i get config error when i launch qtile or When I use "qtile - c ~/.config/qtile/config.py" on terminnal I get
the following stack trace

Qtile version: 0.16.1

Stack traces: [qtile-log.txt](https://github.com/qtile/qtile/files/5832684/qtile-log.txt)

Configuration: [config.txt](https://github.com/qtile/qtile/files/5832665/config.txt)

**Comment by elParaguayo** [comment]
It's this line:
```Key("f5", lazy.restart(), desc="Restart qtile"),```
If there's no mod, then you need to put an empty list first e.g
```Key([], "f5", lazy.restart(), desc="Restart qtile"),```

**Comment by MJBN** [comment]
@elParaguayo thanks
