### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#2126]
I know there is an IRC chat, but it could be nice to also have discussions enable on this repo to lower the barrier of entry for things that don't deserve an issue. What do you think?

**Comment by elParaguayo** [comment]
There's the qtile-dev group on google (https://groups.google.com/g/qtile-dev). Some good discussions there about helping with things that aren't necessarily full blown issues.

**Comment by ramnes** [comment]
Let's try!
