### ISSUE TITLE
Broken Xephyr script (qtile unrecognised arguments)

### ISSUE THREAD

**Issue by SirWrexes** [qtile/qtile#2130]
# Issue description

When trying to launch `qtile` in a `xephyr` container using the provided script, I get this error :
![image](https://user-images.githubusercontent.com/5567164/105354341-b6acf900-5bf0-11eb-9bae-2574423b9883.png)
Changing the log level doesn't solve the issue.
However, replacing `"${HERE}"/../bin/qtile` in the script with `$(which qtile)` to invoke the one installed via `pacman`, this happens :
![image](https://user-images.githubusercontent.com/5567164/105355177-fde7b980-5bf1-11eb-960a-e78b01b65ca6.png)
Removing `start` from the line where `qtile` is called fixes this, and the container launches, effectively spawning a new X server with `qtile` as the window manager.

Note : I see the default terminal called is `xterm`, which I did not install (I only have `kitty`).
I made a simple bash script inspired by your utils.guess_terminal() to fix this issue and will propose a pull request to implement it in the `xephyr` script soon.

# Qtile version
Repo : dc95d81a39b64be9d452c88df1e2849cb78fc85b
Arch package : 0.16.1-2

**Comment by elParaguayo** [comment]
Sorry if I'm not completely understanding your issue here.

However, regarding using `start` or not: this is a change that was added after 0.16.1 (the one in the Arch repos). For 0.16.1 you launch via `qtile` but, if you're using git version, you need `qtile start`.

**Comment by elParaguayo** [comment]
Ah, sorry, I think I'm with you now.

Looking at the error, it looks like `qtile` expects `start` after the log level argument but the script file places it before (https://github.com/qtile/qtile/blob/master/scripts/xephyr#L16).

If that's right, can you try just moving start to before the `&` in the xephyr script and see if it works.

**Comment by Barbarossa93** [comment]
Changing it to this:
```
  env DISPLAY=${XDISPLAY} QTILE_XEPHYR=1 ${PYTHON} "${HERE}"/../bin/qtile -l ${LOG_LEVEL} start $@ &
```
worked for me

**Comment by elParaguayo** [comment]
OK - I can submit a pull request for this later if no one else does.

**Comment by Barbarossa93** [comment]
No worries, I got it @elParaguayo  :)

**Comment by elParaguayo** [comment]
Thanks - can you test passing other arguments that would be expanded via the `$@` part? My suspicion is the `start` argument is the only positional one and needs to come last so could break if `$@` is expanded into some other arguments.

**Comment by Barbarossa93** [comment]
Placing `start` in front of the `$@` doesn't work when passing `-c ~/.config/qtile/exp_config.py` to the script, which makes sense. Placing `start` before the `$@` works with passing the same arguments. Also tried `-n` with the other arguments as well, which was working. Essentially, any arguments from `qtile start --help` will work. These were:
```usage: qtile start [-h] [-c CONFIGFILE] [-s SOCKET] [-n] [--with-state STATE] [-b {x11}]

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIGFILE, --config CONFIGFILE
                        Use the specified configuration file
  -s SOCKET, --socket SOCKET
                        Path of the Qtile IPC socket.
  -n, --no-spawn        Avoid spawning apps. (Used for restart)
  --with-state STATE    Pickled QtileState object (typically used only internally)
  -b {x11}, --backend {x11}
                        Use specified backend. Currently only x11 is implemented.
```
The `-l` flag works with `qtile` according to `qtile --help`:
```
usage: qtile [-h] [--version] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] {start,shell,top,run-cmd,cmd-obj,help} ...

A full-featured, pure-Python tiling window manager.

positional arguments:
  {start,shell,top,run-cmd,cmd-obj,help}
    start               Start the window manager
    shell               shell-like interface to qtile
    top                 resource usage information
    run-cmd             A wrapper around the command graph
    cmd-obj             qtile.command functionality exposed to the shell.
    help                Print help information and exit

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -l {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set qtile log level
```

I guess adding the `-l` flag to `qtile start` would be nice, but is frankly unnecessary

**Comment by elParaguayo** [comment]
Ah, I see, it's passing args to the `start` subparser. Agreed - makes sense to have `start` before `$@`. Thanks for the explanation.

**Comment by m-col** [comment]
Looks like #2143 resolves this. Could you confirm?

**Comment by ramnes** [comment]
Yep it should be fixed. :)
