### ISSUE TITLE
Brave Auto-fill

### ISSUE THREAD

**Issue by milkias17** [qtile/qtile#2147]
Auto-fill in brave browser doesn't work when using qtile. This is for sure is a qtile problem as it works flawlessly in other window managers. What happens is as I click on my account on the small dialog box that pops up, what normally happens is my password and username gets filled, but inside qtile as I click on my account, the dialog box  just disappears and it doesn't fill in anything. Other browsers have no such problem though

I am using qtile git version 0.16.2.dev169+g548a7e04, brave version 88.1.19.86.  Here is my qtile config:
[qtile-config.zip](https://github.com/qtile/qtile/files/5860443/qtile-config.zip)

**Comment by Barbarossa93** [comment]
I think it's probably related to this: https://github.com/qtile/qtile/issues/1792

**Comment by milkias17** [comment]
This now works perfectly fine.

**Comment by g0rdonL** [comment]
I still cant get it to work. I can only navigate autofill with my arrow keys. If I click on the option with my mouse it just hides the autofill options and automatically selects the option selected (ie the first one if u didnt navigate with arrow keys).
@milkias17 how did u get it to work?

**Comment by nevim42** [comment]
I had similar problem with Brave. Autofill looked like mouse click was propagate through autofill popup window. I was using Tile layout in Qtile and just by switching to another layout (Bsp in my case) this problem disappear. It looks like there is some bug in Tile layout.
@g0rdonL Are you using Tile layout? Maybe try another layout and it will be OK ;)

**Comment by g0rdonL** [comment]
@nevim42 I am using monadtall

**Comment by JuanM04** [comment]
@nevim42 I can confirm this issue: when I use monadtall, the autofill (and other popups) don't work, but when I change the layout to max, they work perfectly

**Comment by JuanM04** [comment]
It's the same issue described here: #1809

**Comment by elParaguayo** [comment]
The issue in #1809 impacts me on max layout too.
