### ISSUE TITLE
gnome-screensaver-command not working in Ubuntu

### ISSUE THREAD

**Issue by sainad2222** [qtile/qtile#2148]
# Issue description
I installed qtile today in my Ubuntu 20.04. I used to do `super+l` to lock my screen in my gnome, now I remapped `gnome-screensaver-command -l` to `super+shift+x` in qtile
[my_config](https://github.com/sainad2222/dotfiles/blob/master/.config/qtile/config.py#L70)
When I tried `gnome-screensaver-command -l` in terminal nothing happening also there are no logs in qtile.logs
but when I running the same command in gnome it's working.

I also added **installing inside Gnome** part in my config (dbus stuff)
Am I missing something?
#### Qtile version
My qtile version: 0.16.2.dev202+gcc0eedb7

**Comment by ramnes** [comment]
Is `gnome-screensaver-command` a shell alias? If so, that's normal, Qtile can't read your aliases.

**Comment by sainad2222** [comment]
No it's not. `gnome-screensaver-command` is also suggested in [docs](http://docs.qtile.org/en/latest/manual/config/gnome.html)

**Comment by tych0** [comment]
Try either: 1. passing shell=True to spawn() or 2. splitting it up into a list of arguments, e.g. `["gnome-screensaver-command", "-l"]`

**Comment by sainad2222** [comment]
@tych0  tried both, not working. I think I am doing something wrong. Does `gnome-screensaver-command` requires gnome to run in background or something like that?

**Comment by tych0** [comment]
> Does gnome-screensaver-command requires gnome to run in background or something like that?

Presumably, but I'm not a gnome user so I don't really know.

**Comment by ramnes** [comment]
Have a look here: https://askubuntu.com/questions/7776/how-do-i-lock-the-desktop-screen-via-command-line :)

**Comment by ramnes** [comment]
Closing as it's most likely due to the daemon not being running. Please comment if you have any reason to think it's related to Qtile and I'll reopen.
