### ISSUE TITLE
Missing widget requirements in documentation

### ISSUE THREAD

**Issue by OlaRune** [qtile/qtile#2150]
# Issue description
The CPU and CPUGraph widgets do not work without psutil, but this isn't mentioned in the documentation for Built-in Widgets.

[http://docs.qtile.org/en/latest/manual/ref/widgets.html#cpu](http://docs.qtile.org/en/latest/manual/ref/widgets.html#cpu)
[http://docs.qtile.org/en/latest/manual/ref/widgets.html#cpugraph](http://docs.qtile.org/en/latest/manual/ref/widgets.html#cpugraph)

# Qtile version
Release 0.16.1

# Stack traces
N/A

# Configuration
Irrelevant

**Comment by elParaguayo** [comment]
Thanks for flagging. I'll submit a PR for this later.
