### ISSUE TITLE
Minor errors in documentation for MonadTall and MonadWide

### ISSUE THREAD

**Issue by OlaRune** [qtile/qtile#2152]
# Issue description
The MonadTall and MonadWide documentation has some minor errors:
- For MonadTall the default name is documented as 'xmonadtall' when it actually is called just 'monadtall' (at least in my version of Qtile)
- For MonadWide the default name is also documented as 'xmonadtall' when it actually is called 'monadwide' (at least in my version of Qtile)

[http://docs.qtile.org/en/latest/manual/ref/layouts.html#monadtall](http://docs.qtile.org/en/latest/manual/ref/layouts.html#monadtall)
[http://docs.qtile.org/en/latest/manual/ref/layouts.html#monadwide](http://docs.qtile.org/en/latest/manual/ref/layouts.html#monadwide)

# Qtile version
0.16.1

# Stack traces
N/A

# Configuration
Not relevant

**Comment by ramnes** [comment]
Fixed with #2365. Thanks!
