### ISSUE TITLE
[FEATURE REQUEST] The option to use Window Class instead of name in WindowName widget

### ISSUE THREAD

**Issue by Masacaai** [qtile/qtile#2154]
# Background

When opening windows with large names , the WindowName widget becomes congested with text, making it look rather ugly. 

# Suggestion

Allow the user to choose between using Window Name and Window Class. This would function much like an Application Name widget we see in KDE Plasma, thus allowing the WindowName widget to only display the class of the window in focus, not it's actual name.

I don't know if implementing this would be as easy as just adding an attribute to use w.class instead of w.name, but I'll try to look into this when I can.

**Comment by mbenford** [comment]
I'm not fond of long window names as well, and I "fixed" it by extending the `WindowName` widget in order to truncate long titles:

```python
from libqtile import widget
from libqtile.widget import base

class WindowName(widget.WindowName):
    orientations = base.ORIENTATION_HORIZONTAL
    defaults = [
        ('max_chars', 0, 'max chars before truncating with ellipis'),
    ]

    def __init__(self, width=bar.STRETCH, **config):
        widget.WindowName.__init__(self, width=width, **config)
        self.add_defaults(WindowName.defaults)

    def truncate(self, text):
        if self.max_chars == 0:
            return text

        return (text[:self.max_chars - 3].rstrip() + "...") if len(text) > self.max_chars else text

    @widget.WindowName.text.setter
    def text(self, value):
        super(WindowName, type(self)).text.fset(self, self.truncate(value))
```

Result: 
![image](https://user-images.githubusercontent.com/446867/106395938-b7f5d700-63e3-11eb-87c3-3dac9344a53b.png)

But if you really want to replace the window name with the window class name, all you have to do is override the `update` method of `WindowName` to your liking.

**Comment by Masacaai** [comment]
How do I implement your code? Do I just copy/paste it into my config file? That doesn't seem to work for me? Do I need to do anything else?

**Comment by Masacaai** [comment]
Where can I find the available attributes for current_window?
I tried extending the update function to use w.class instead of w.name, but it didn't work. 
I assumed 'class' would be an attribute just like 'name' but it doesn't seem to accept that.
I tried searching through the source code, but I wasn't able to find it.
Sorry, bit of a newbie at this :)

**Comment by mbenford** [comment]
Take a look at the [window.py](https://github.com/qtile/qtile/blob/master/libqtile/window.py) file and search for `wm_class`. You will find `self.window.get_wm_class()` in the `cmd_inspect` method. You can use that function in your `update` method:

```python
class WindowName(widget.WindowName):
    (...)
    def update(self, *args):
        if self.for_current_screen:
            w = self.qtile.current_screen.group.current_window
        else:
            w = self.bar.screen.group.current_window
        state = ''
        if self.show_state and w is not None:
            if w.maximized:
                state = '[] '
            elif w.minimized:
                state = '_ '
            elif w.floating:
                state = 'V '

        class_name = w.window.get_wm_class()[0] if w and w.window else ""
        unescaped = "%s%s" % (state, class_name if class_name != "" else self.empty_group_string)
        self.text = pangocffi.markup_escape_text(unescaped)
        self.bar.draw()
```

**Comment by Masacaai** [comment]
Thank you so much! I was so keen on finding an attribute related to class that I didn't think of using the function instead!
