### ISSUE TITLE
Missing requirement in documentation for Volume widget

### ISSUE THREAD

**Issue by OlaRune** [qtile/qtile#2157]
# Issue description
The Volume widget by default needs access to amixer, which is part of the package alsa-utils, unless the `get_volume_command` is manually set to something else by the user.

This is not mentioned in the documentation [http://docs.qtile.org/en/latest/manual/ref/widgets.html#volume](http://docs.qtile.org/en/latest/manual/ref/widgets.html#volume)

# Qtile version
0.16.1

# Stack traces
N/A

# Configuration
Irrelevant

**Comment by ramnes** [comment]
Thank you for raising the issue. :)
