### ISSUE TITLE
[Question] Wayland please??

### ISSUE THREAD

**Issue by sujay1844** [qtile/qtile#2166]
You guys said you're working on wayland in Jun 2019.
So how's the progress?? Any ETA?? Or is it not your primary concern right now??
I mean I'm not roasting you because none of the major WMs haven't implemented Wayland yet.
Why is it like this?? Why hasn't any major WM took the leap?? Is it because Xorg is good enough??
No offense to anyone working on wayland support.

I may be totally impractical for asking an ETA. excuse me

**Comment by ramnes** [comment]
We definitely want it but that requires quite some time and effort. PR welcome. :)
