### ISSUE TITLE
Can't switch to group n° 7

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#2169]
# Issue description
When trying to move to the group 7(starting from 1) it just doesn't switch to it. As shown in the video also the Groupbox widget seems to not 'compute' the group switch despite its load at qtile's startup, it also becomes buggy(shows as focused multiple groups etc..)  just after trying to switch to the group.
[Video demonstration](https://vimeo.com/506712251)

# Qtile version
0.16.2.dev210+gd68819e6

# Stack traces

# Configuration
[My config file](https://pastebin.com/dtsrJFtP)

**Comment by m-col** [comment]
I don't see any obvious reasons why that might be happening. Do you see anything in the log?

**Comment by sirakai-pc** [comment]
Oh, sorry I totally forgot to check the log. I gave an int value <1 to a parameter of treetab. Now the problem has disappeared! Thanks

**Comment by m-col** [comment]
Awesome, np, glad you got it sorted.
