### ISSUE TITLE
Feature Request: Save Session State

### ISSUE THREAD

**Issue by Chaitanyabsprip** [qtile/qtile#2190]
There should be an option to save session state such that when enabled you can quit qtile and when you come back all the windows are open in the same place as when qtile was quit. Also, if possible, the contents of the windows be the same. I dont think this has been implemented in any of the WM or DE.

**Comment by ksladowski** [comment]
I don't believe the WM/DE handles this. Its a restriction of X as far as I know. Wayland might support it?
