### ISSUE TITLE
Improper behaviour of Tile layout with add_on_top=False

### ISSUE THREAD

**Issue by Tokariew** [qtile/qtile#2198]
# Issue description

With focus on master window, newly created layout will push current master to slave stack, and on slave stack newly created window will push window with focus below it.

Focus on A, new window D, push A to slave
```
|   | B    |   | A
| A | --   | D | B
|   | C    |   | C
```
second example, focus on B, new window D, created on top of it
```
|   | B    |   | D
| A | --   | A | B
|   | C    |   | C
```
# Qtile version

0.16.1

# Configuration

layout.Tile(add_on_top=False),

# fix?
0 should be 1 in the line below in file https://github.com/qtile/qtile/blob/master/libqtile/layout/tile.py
```
def add(self, client, offset_to_current=0):
```

With fix
```
|   | B    |   | D
| A | --   | A | B
|   | C    |   | C
```
```
|   | B    |   | B
| A | --   | A | D
|   | C    |   | C
```

**Comment by tych0** [comment]
This is a great writeup; any chance you can send this as a patch? Including a test would be appreciated as well.

**Comment by Tokariew** [comment]
I will try in the weekend to send a patch with test.
Test should be added here https://github.com/qtile/qtile/blob/master/test/layouts/test_tile.py ?

**Comment by tych0** [comment]
Yep, that would be great!
