### ISSUE TITLE
qtile is sluggish, windows dont open, and if they do, they are frozen

### ISSUE THREAD

**Issue by ksladowski** [qtile/qtile#2203]
# Issue description

I changed very little from the default config, just set up some keybinds and chords and put a bar on my second monitor. Qtile was behaving and then suddenly I log into X, everything looks good, I can move around workspaces and everything just fine. I can open rofi, which for some reason is the only application I've tried that isn't affected. I spawn windows and they sometimes take 10-15 seconds to appear, if they show up at all, and when they do, they're small in the upper corner, disappear when I change layouts, and aside from being able to type in my terminal, I can't interact with them.

# Qtile version

qtile 0.16.1-2 from the Arch repo

# Stack traces

[qtile.log](https://github.com/qtile/qtile/files/5963163/qtile.log)

# Configuration

[config.py.txt](https://github.com/qtile/qtile/files/5963175/config.py.txt)

**Comment by ramnes** [comment]
```
TypeError: match() got an unexpected keyword argument 'wmname'
```

Try replacing wmname with `wname` in your config?

**Comment by ksladowski** [comment]
Yep, that was it. I looked at that log so many times and every single time I overlooked that line. I got confused because wmclass is another valid argument so I assumed it would be wmname as well. Thanks
