### ISSUE TITLE
 The configuration broke after updating

### ISSUE THREAD

**Issue by jonhson1981** [qtile/qtile#2219]
After updating all my configuration was broken, the message ERROR CONFIG and CONFIG DEFAULT was noted on the bar, I went back to the previous version and it was fixed

**Comment by tych0** [comment]
This is expected. While we're working on a strategy for API stabilization, we do not currently have one. See: https://github.com/qtile/qtile/blob/master/CHANGELOG#L4 for specific details about changes.
