### ISSUE TITLE
Copy entire config folder for qtile check

### ISSUE THREAD

**Issue by MithicSpirit** [qtile/qtile#2223]
# Issue description
My config is split across two files, `config.py` (main config) and `custom.py` (custom widgets), but `qtile check` only copies the `config.py` file to the `/tmp/tmp…/` folder; therefore, the `mypy` check fails because it cannot find the `custom` module. I can work around this by quickly copying the `custom.py` file to the folder, but this gets annoying.

This could be fixed by automatically copying the entire `~/.config/qtile` folder to the temporary folder, instead of just the `config.py`. It might also be necessary to remove the `__pycache__` folder if it is present.

# Qtile version
The latest version on the Archlinux repos, `v0.17.0-1` (not sure about exact commit hash, sadly).

# Configuration
https://github.com/MithicSpirit/dotfiles/tree/master/.config/qtile

**Comment by tych0** [comment]
+1, I had not thought about this at all, but it's a very good point. Thanks for the report!
