### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by ekhall** [qtile/qtile#2225]
# Issue description

Upgraded qtile via arch aur from most recent to 0.17. It's not loading, but dumping an 8.4meg log file. I note this in the upgrade relnotes:

```
    !!! warning !!!
        - When (re)starting, Qtile passes its state to the new process in a
          file now, where previously it passed state directly as a string. This
          fixes a bug where some character encodings (i.e. in group names) were
          getting messed up in the conversion to/from said string. This change
          will cause issues if you update Qtile then restart it, causing the
          running old version to pass state in the previous format to the new
          process which recognises the new.
```

For those of us now having this problem this message does not make it clear how to fix this.

Any ideas how to fix this?

**Comment by tych0** [comment]
Once qtile has died, that's not longer an issue (it is only about sharing state across lazy.restart() calls).

If you still can't start, it's likely something else that's causing your problem, although without the last bits of your log file it's hard to tell.
