### ISSUE TITLE
No filename provided Image widget causes QTile to crash.

### ISSUE THREAD

**Issue by spaceraiders0** [qtile/qtile#2226]
# The issue
When no filename argument, OR an invalid filename is provided for the Image widget, Qtile seems to crash, and needs to be killed to restart. You are obviously not supposed to provide a non-existant image, but I have doubts that it crashing is intended behavior. 

What I am describing here as a "crash" is no keyboard input being accepted, and windows from *all* other workspaces being displayed on the workspace you are currently on. If this is not actually a crash, I apologize, but regardless, Qtile becomes unusable until the process is killed and I am kicked back to my Display Manager.

# Steps to reproduce
In your bar, create a new ``Image`` widget somewhere inside. Either provide a path to an image that does not exist, or do not provide one period.

# Qtile version
This is the commit hash of the version I am running.
6c4d0557124989d46ffb2bb24f4468db687fcdb2

# Stack traces
No stack traces from xsession-errors, or the Qtile log are produced, however I have traced the error (through using the logger provided in the module's file) to the ``_configure`` method of the Image widget, and it seems to be coming the line: ``base._Widget._configure(self, qtile, bar)``

# Configuration
https://pastebin.com/qxBq6yPn

If there is any information I got wrong here, or some other bit of information I can provide that will help this issue get solved, I will try my best.

**Comment by tych0** [comment]
Looks like we probably moved inital drawing earlier to base.Widget's _configure somehow. I really don't think we should be drawing there at all, at least on the first _configure, since we don't know what to draw yet.

I think the bug is that we now call _reset_surface() in Drawer's __init__, and we probably shouldn't. @DorianGray thoughts?

**Comment by DorianGray** [comment]
reset surface doesn't draw, it just reinitializes the in memory recording surface used to stage drawing operations. If something is drawing early it' outside of the drawer changes.

**Comment by elParaguayo** [comment]
Looking at the source for the image widget, in both of those scenarios (no filename or non-existent file) the widget will raise a `ValueError` in `_configure`. Those errors aren't caught by `bar._configure` which I'm guessing causes qtile to crash.

Do we just need better error handling? I'll take a look.

**Comment by DorianGray** [comment]
Ah, that changed as a part of removing the session manager. _configure gets called in a slightly different place that would cause qtile to shut down if certain errors occurred.
