### ISSUE TITLE
Systray, icon to big when starting app from .xinitrc

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#2228]
I'm running `pasystray`, from `.xinitrc`:
```bash 
# Sound system
pkill pasystray
pasystray &
```
This results in the icon being to large in the systray:
![screenshot](https://user-images.githubusercontent.com/3178666/108509925-2a105c00-72be-11eb-8f8f-00ea7d310770.png)
If I kill `pasystray` and start it again the icon has the correct size:
![screenshot](https://user-images.githubusercontent.com/3178666/108510036-4f04cf00-72be-11eb-8a96-a5710f844bee.png)

**Comment by m-col** [comment]
Works fine for me. Got anything in your xinitrc or qtile config that could be playing with DPI or something?

**Comment by tamis-laan** [comment]
Yes I have a HDPI screen, I do the following in my .xinirc:
``` bash
# Set high DPI
echo "Xft.dpi: 192" | xrdb -merge
```
But this is before:
``` bash
# Sound system
pkill pasystray
pasystray &
```
So that shouldn't be the problem.
