### ISSUE TITLE
RFC/enhancement: Key sequence mode feature: mode stack to keep outer mode active

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#2241]
# Issue description
I want to create a mode for `xournalpp` because I want to control it with one hand. With the other hand I am drawing with a graphics tablet.  
KeyChords are all fine, but one thing is just not possible with them: to return to an outer level:
+ I want to configure qtile in such a way that `mod+x` enters the `xournalpp` mode. In this mode I'd like to have
    ```
    t p: pen
    t e: eraser
    t h: highlighter
    ....
    ```
+ I could easily configure it to stay in the `tools` or `recogniser` level, but not in the main `xournalpp` level
+ A work-around is not possible:
    https://github.com/qtile/qtile/blob/7ec0bdd002ea44417bb2c439aca466f382ce80a5/libqtile/core/manager.py#L385-L391
    the hook is called too early to implement a work-around because `self.ungrab_keys()` cannot be inhibited.
+ I think this should really be a feature instead of a user hack:  
+ Suggestion based on my attempt to create a work-around:
   + Qtile keeps a mode stack (list) with all the modes that have been activated.
   + In `grab_chord()`: `chord` is pushed onto the stack
   + In `ungrab_chord()`: the last value is popped off the stack, the new last value `stack[-1]` is used to find a higher-level chord that is then restored using `grab_chord()`
        ```py
	 def ungrab_chord(self) -> None:
		    self.current_chord = False
		    hook.fire("leave_chord")
		    self.ungrab_keys()
		    while self.chord_stack:
		        chord = self.chord_stack.pop()
		        if chord.mode != "":
		            self.grab_chord(chord)
		            break
		    else:
		        for key in self.config.keys:
		            self.grab_key(key)
        ```
        Note that this is just a guess, I haven't tested this.

I hope this short text was enough to explain the idea and I look forward to reading your comments.

# Qtile version
newest: 7ec0bdd002ea44417bb2c439aca466f382ce80a5

# Configuration
```py
...
keys = [
	...
	KeyChord([mod], 'x', [
		KeyChord([], 't', [
			Key([], 'p', send_key('Control+Shift+P')),  # pen
			Key([], 'e', send_key('Control+Shift+E')),  # eraser
			Key([], 'h', send_key('Control+Shift+H')),  # highlighter
			...
		]),  # xournalpp: tools
		KeyChord([], 'r', [
			Key([], 's', send_key('Control+1')),  # shape recogniser
			Key([], 'r', send_key('Control+2')),  # rectangle
			Key([], 'a', send_key('Control+3')),  # arrow
			...
		]),  # xournalpp: recogniser tools
		...
	], mode='xournalpp'),
	...
]
...
```

**Comment by ep12** [comment]
I started playing around with this, see #2264.
It turns out, pushing `chord` onto a stack is bad when restarting qtile. Of course, it is faster to have the actual `chord` object available rather than searching `self.keys` recursively.
To avoid errors, the `chord_stack` attribute will be `del`eted before the `QtileState` is created and saved.
This is a hack, but there are reasons to do it this way: After restarting Qtile you nearly expect it to be in the root mode, getting to the old mode is probably quick. And what if the `keys` have changed and we are restarting Qtile to load the new config. So non-persistent is reasonable, I think...

**Comment by m-col** [comment]
I haven't set up any Chords for myself but this really shows how powerful they can be. This sounds awesome, gonna read through the PR now.
