### ISSUE TITLE
logging: possibly unwanted behaviour: 'smart' is reported as invalid for `focus_on_window_activation`

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#2242]
I stumbled across an entry in my log: `Invalid value for focus_on_window_activation: smart`.
This piece of code is responsible for that:
https://github.com/qtile/qtile/blob/3bee7be1713e3970e2c5f03a840b355048f6c1e4/libqtile/window.py#L1163-L1177
If `focus_behavior == "smart" and self.group.screen and self.group.screen != self.qtile.current_screen` then the final `else` case is the only one matching and hence `smart` is logged although it is a valid option.

Suggestion: Change
```py
elif focus_behavior == "smart" and self.group.screen and self.group.screen == self.qtile.current_screen: 
     logger.info("Focusing window") 
     self.qtile.current_screen.set_group(self.group) 
     self.group.focus(self)
```
to
```py
elif focus_behavior == "smart" and self.group.screen:
     if self.group.screen == self.qtile.current_screen: 
         logger.info("Focusing window") 
         self.qtile.current_screen.set_group(self.group) 
         self.group.focus(self) 
    else:
        logger.info("Ignoring focus request")
```
or change
```py
elif focus_behavior == "never":
```
to
```py
elif focus_behavior == "never" or (focus_behavior == "smart" and self.group.screen and self.group.screen != self.qtile.current_screen):
```
The first option is longer, but more readable...

Version: newest,
config: `focus_on_window_activation = 'smart'`

**Comment by tcld** [comment]
I have seen this message show up in my logs for quite some time, too. Never bothered to look where it came from so far. So thank you very much for this issue. :)

**Comment by ep12** [comment]
Maybe the corresponding test should be extended to check all cases?
