### ISSUE TITLE
AttributeError: KeyChord breaks cmd_display_kb

### ISSUE THREAD

**Issue by ep12** [qtile/qtile#2247]
# Issue description
qtile shell excerpt:
```
 > display_kb()
Command exception: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 1001, in cmd_display_kb
    if not k.commands:
AttributeError: 'KeyChord' object has no attribute 'commands'
```
# Configuration
At least one `KeyChord` in `keys`. My config: https://www.github.com/ep12/qtileconf

**Comment by elParaguayo** [comment]
Yes, that makes sense as a KeyChord doesn't have that attribute. That line could be changed to:
``` python
if not getattr(k, "commands", None):
```
So it checks if the attribute exists and returns None if not.

Separate question is if/how should KeyChords be handled in this function? You've got nested KeyChords too in your config which would be harder still for this function.

**Comment by ep12** [comment]
The `display_kb` function already contains a local class, why not define a function that handles the `Key` and `KeyChord` elements using recursion? `KeyChord` would be translated into a "enter ... mode" row and then the function would be called on all the child elements... Maybe another column `mode` should be prepended such that keybindings are sorted by mode first, then as before?

**Comment by ep12** [comment]
> Separate question is if/how should KeyChords be handled in this function? You've got nested KeyChords **too** in your config which would be harder still for this function.

@elParaguayo If you want to nest `KeyChord`s too, are you interested in #2241 and #2264. I know that there is #2121 but it implements different things...
It seems only very few people care about `KeyChord`s, and even fewer about nested ones... I would be glad to get some feedback and maybe you could test the branch?

**Comment by elParaguayo** [comment]
I don't use chords much at all and don't currently have any nested ones. My interest in this is primarily as a coding problem that can be fixed.
