### ISSUE TITLE
KeyboardLayout widget uses obscure dependency

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#2265]
xkb-switch is not necessarily mainstream, although it was used in the fix for #2027 in #2042. It would be nice to fix the bug using setxkbmap instead (or perhaps just revert #2042 if enough people don't like this change).

/cc @tcld @k4leg

**Comment by tcld** [comment]
Thank you for opening the issue.

One question: Assuming somebody is using the keyboard layout-widget and he updates qtile without installing the new dependency - should this be handled gracefully or would it be ok for the widget (or even qtile) to throw?

**Comment by m-col** [comment]
Someone who is feeling adventurous could get some pretty sweet l33t points by using xcffib for a (relatively) dependency-free version 👀 (setxkbmap source is [here](https://gitlab.freedesktop.org/xorg/app/setxkbmap/-/blob/master/setxkbmap.c) and not huge)

**Comment by zordsdavini** [comment]
> One question: Assuming somebody is using the keyboard layout-widget and he updates qtile without installing the new dependency - should this be handled gracefully or would it be ok for the widget (or even qtile) to throw?

thanks to restart checker I got notification about missing dependency. But as configuration is incompatible with older one I still doesn't have keyboard layout. And from description I don't understand how it should be configured. For me it could be better just to have separate implementation for keyboard layout as it use different backend

**Comment by tych0** [comment]
> Someone who is feeling adventurous could get some pretty sweet l33t points by using xcffib for a (relatively) dependency-free version eyes (setxkbmap source is here and not huge)

Unfortunately I'm not so sure it'll be easy, the xcffib docs have xkb as a TODO: https://github.com/tych0/xcffib/#todo

I don't remember exactly what the pain points were, though.

> For me it could be better just to have separate implementation for keyboard layout as it use different backend

I'd rather just have one, so if there's a preference for the old style, we should revert this commit.
