### ISSUE TITLE
Starting qtile files after `backend` not found

### ISSUE THREAD

**Issue by tcld** [qtile/qtile#2267]
# Issue description

Currently trying to upgrade to the most recent master, but I can't get past https://github.com/qtile/qtile/commit/cf923103e830c50a03d4aefc104cffa3ddd49173

Restarting with this commit works, but after doing a full restart of my machine I always end up with the below error.

# Stack traces

`~/.xsession-errors` shows this:
```log
Traceback (most recent call last):
  File "/home/tcl/Software/qtile/libqtile/scripts/main.py", line 62, in main
    options.func(options)
AttributeError: 'Namespace' object has no attribute 'func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcl/Software/qtile/bin/qtile", line 36, in <module>
    main()
  File "/home/tcl/Software/qtile/libqtile/scripts/main.py", line 66, in main
    start.start(options)
  File "/home/tcl/Software/qtile/libqtile/scripts/start.py", line 87, in start
    q = make_qtile(options)
  File "/home/tcl/Software/qtile/libqtile/scripts/start.py", line 50, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
AttributeError: 'Namespace' object has no attribute 'backend'
```

The folder `backend` does exist. Could this be an issue with my `__pycache__` or is it maybe something more serious?

@ramnes : FYI

**Comment by ramnes** [comment]
Are you updating commit pet commit or do you have this error with the current master? And what command are you running?

**Comment by tcld** [comment]
The current master crashed, so I went back until I found the first commit that I couldn't run. There might be more issues, but so far you could say I am updating one commit after another.

To launch qtile I just execute `bin/qtile`.

**Comment by tcld** [comment]
I switched to `bin/qtile start`, which seems to have fixed this particular issue. Thought I had done that a long time ago, actually.

Since the way of starting qtile without `start` has been completely removed, I'll assume that this issue is fixed.
