### ISSUE TITLE
Intellij Idea communitiy edition, text input does not work

### ISSUE THREAD

**Issue by blin** [qtile/qtile#227]
I am unable to edit any text field, either main text or option fields. Drop down menus, project file browser and other elements work as expected.

If i click on a line it actually gets selected, and it seems like cursor gets installed in the click location (as evident from variable highlighting), but cursor symbol is not displayed and i am unable to input or delete any text.

I am using qtile 0.5 and intellij idea 11.1 on openjdk7 on arch linux. wmname is set to LG3D.
Everything works fine on awesome wm, so it is not openjdk vs sun jdk issue.

**Comment by geektrainee** [comment]
Hello everybody, 
Am not so good in programs though up-coming, this is the solution i explored in intellij and helped me out  of the same problem. Try it if it may help you. JUST DISABLE YOUR "idea Vim" plugin. i think it some times dont work well when automatically configuring it's settings with IDEA editting settings.
All the best.

**Comment by codeninja88** [comment]
thank you geektrainee. This plugin was one that intellij recommended at the setup section so i installed it and had this problem. Now i've disabled it and it works fine. cheers

**Comment by geektrainee** [comment]
U r welcomed, pleasure

**Comment by ghtali** [comment]
Just **turn off** the **Vim Emulator** from **Tools** in the **intelliJ**

[http://stackoverflow.com/questions/37964499/im-using-editor-intellij-idea-2016-i-cant-write-or-edit-any-code-because-code/43244047#43244047](url)

**Comment by zordsdavini** [comment]
I have phpStorm (same flower from Jetbrains). I use vim plugin and don't have any issues. Maybe this was same issue as Libreoffice had?
