### ISSUE TITLE
Confusing output from `qtile check`

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2274]
# Issue description

When I run `qtile check` I see this:
```
$ ./bin/qtile check                    
checking qtile config file /home/mcol/.config/qtile/config.py
error: failed mypy build.
config.pyi:3: error: Cannot find implementation or library stub for module named 'libqtile.config'
config.pyi:3: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
config.pyi:4: error: Cannot find implementation or library stub for module named 'libqtile.layout.base'
```

I'm not super sure what this means, so from a user's perspective this must be even more confusing. We should probably try to detect the possible outcomes and give a bit more information.

# Qtile version

505e5741ee7faa1cdcc62725dbe3e8aced13d8a5

**Comment by tych0** [comment]
Do you have a py.typed file in your libqtile dir?

**Comment by m-col** [comment]
I do not. Should I?

**Comment by tych0** [comment]
My understanding is yes, after
48df71a6a6758ed61b45d835f07383dd08be097b.

How did you install?

**Comment by m-col** [comment]
Oh sorry, i misread 'libqtile dir' as the root dir. I do have it.

**Comment by tych0** [comment]
Sorry, I mean the installed dir, not the dir in the git repo. I
*think* py.typed should be recursive for a package, but you might try
adding it to every sub-module dir and see if that helps.

**Comment by m-col** [comment]
Ah I see. I run it directly from my git repo (in .xinitrc):
```
exec python $HOME/git/qtile/bin/qtile start
```
and it only appears within the `libqtile` top directory there. Installing it with setup.py into ~/.local and I see the same: just one `py.typed` file in the top folder. Should this exist in all folders? What does it do?

Running `qtile check` using the newly installed executable at `~/.local/bin/qtile`. Does seem to yield better results:
```
checking qtile config file /home/mcol/.config/qtile/config.py
error: config failed to import: 'NoneType' object has no attribute 'cmd_spawn'
Stub: at line 1
MypyFile:1(
  /tmp/tmp3yzddu3o/config.pyi)
Runtime:
MISSING
```
Though the whole `qtile` being `None` thing has false positive-ed.

**Comment by tych0** [comment]
> Should this exist in all folders?

I don't believe so.

> What does it do?

It tells mypy "this package has type information".

> Though the whole qtile being None thing has false positive-ed.

Seems like maybe it needs a type annotation. I played around with: https://github.com/tych0/qtile/commit/7ecb514e28512d44c07805ac3fe9f9c2bebb9013 but it wasn't immediately obvious to me why exporting that type info fails :(

**Comment by Fabien-Bernard** [comment]
FWIW, I edit my libqtile/__init __.py like this : 
```
from libqtile.core.manager import Qtile

qtile: Qtile = None

def init(q: Qtile):
    global qtile
    qtile = q
```

to get rid of my own false positive "qtile check" error.
I didn't test extensively nor launch the qtile test suite, it was just a quick try after reading [tych0@7ecb514](https://github.com/tych0/qtile/commit/7ecb514e28512d44c07805ac3fe9f9c2bebb9013).

**Comment by tych0** [comment]
I don't think that's correct: qtile can have a None type (viz. the initial assignment), so it won't type check. Maybe it works for a local hack, but it's not something we can carry upstream, unfortunately.

**Comment by m-col** [comment]
There is a lot about this [here](https://mypy.readthedocs.io/en/latest/kinds_of_types.html#strict-optional) in the mypy docs but I still can't figure it out! Truly a head-scratcher.

**Comment by tych0** [comment]
Yeah, it feels like mypy is discarding our type annotation because of the direct assignment :(

**Comment by SCOTT-HAMILTON** [comment]
I can reproduce this issue with qtile's NixOS derivation if you're interested.

**Comment by m-col** [comment]
We probs just need to stick `assert qtile is not None` after the import when type checking, like we do a bunch of places in the codebase.
