### ISSUE TITLE
WidgetBox does not fully re-expand on click

### ISSUE THREAD

**Issue by knodalyte** [qtile/qtile#2285]
# Issue description

On first click, WidgetBox expands properly, but clicking a second time does not hide all widgets.

Specifically, in my configuration (below), the Wallpaper is shown/hidden properly, but the Systray does not hide again.

# Qtile version

qtile-0.17.1.dev82+geb8722ec

# Stack traces

no errors in qtile.log

# Configuration

```
            widget.WidgetBox(widgets=[
                widget.Wallpaper(directory='~/Downloads/wallpaper/', wallpaper_command=None, random_selection=True, label='\u0394'),
                widget.Systray(padding=1, icon_size=22),
                ], close_button_location='right',
            ),
```

**Comment by elParaguayo** [comment]
Thanks knodalyte. This widget was mine so let me take a look. 

I didn't test with systray as I don't use it. My understanding is that that widget is a little bit different to the others so it may be the case that it would need some additional logic to handle it.

**Comment by elParaguayo** [comment]
Just tested this. Pretty sure this is specific to systray.

Widgetbox is correctly adding and removing the widgets when it's opened and closed. However, systray seems to generate a widget and a window and I suspect it's the latter that causes the issue here. I'll do some digging to see if there's a way to hide the systray but my optimistic quick fix failed!

**Comment by Fabien-Bernard** [comment]
Inspired from the systray.draw method, the icons of the systray could be hidden by a new method of Systray class like this :
```
    def hide_icons(self):
        for pos, icon in enumerate(self.icons.values()):
            icon.hide()
```
            
Then a call of this new method at the beginning of the draw method of WidgetBox class if :
		- the systray widget is present in the widgetbox,
		- and the widgetbox is not open
may be another optimistic quick fix :)

**Comment by elParaguayo** [comment]
Yes, I hadn't appreciated that the icons were also windows so they'll need to be hidden separately too.

**Comment by elParaguayo** [comment]
OK. Think I've got it working.

Systray's draw method unhides the icons if they're hidden but as the draw method isn't called for widgets that are in the box then that doesn't matter so all we need to do is hide the icons when closing the box.

It feels very hacky to do this but Systray does seem to be a special case of widget.

I'll do a bit more testing and then submit a PR.

**Comment by elParaguayo** [comment]
PR submitted. Would be great if either of you could test this,
