### ISSUE TITLE
Installing from source.

### ISSUE THREAD

**Issue by QuietLab** [qtile/qtile#2287]
I have tried several times to install qtile from source on fresh install of FreeBSD.

I did following steps from docs.qtile.org:
- pip install xcffib
- pip install cairocffi
- pip install dbus-next
- pip install qtile
Installation of these modules were without any error.
My .xinitrc consists: exec ~/.local/bin/qtile 
As soon as I call startx I get black blank screen. None of the keybindings are working. I use default qtile config as well.

**Comment by ramnes** [comment]
Let me give you the issue template again, since you decided to remove it:

```
# Stack traces

<!--
Please attach any stack traces found in:

* `~/.xsession-errors`
* `~/.local/share/qtile/qtile.log`
-->
```
:)

**Comment by m-col** [comment]
Looks like you need to change `exec ~/.local/bin/qtile` to `exec ~/.local/bin/qtile start`
