### ISSUE TITLE
Scratchpad not working properly in conjunction with terminator

### ISSUE THREAD

**Issue by tcld** [qtile/qtile#2289]
# Issue description

I have configured a few drop down terminals in my configuration, and recently those don't show up as drop downs anymore, but instead they just open as normal windows in the current group.
There is nothing in the log about this, and I haven't bisected the issue yet.

# Qtile version

Most recent master.

# Configuration
```python
ScratchPad('scratchpad', position=99, dropdowns=[
    DropDown('term', f'{terminal} -T "scratchpad-term"', x=0.025, height=0.4, width=0.95),
    DropDown('vim', f'{terminal} -T "scratchpad-vim" -e nvim', height=0.5, width=0.8),
]),
```

**Comment by elParaguayo** [comment]
Have you changed anything else? My ScratchPad is still working in latest master.

If not, bisecting may be a good way to go here.

**Comment by tcld** [comment]
Thanks for checking! :)

Things did stay dodgy for the entire day yesterday. At some point one of the scratchpads stopped working altogether, while the other started working properly.
I have not changed anything about the code or my machine (nor did I install any updates since then), but this morning the scratchpads both are working fine.

I did _restart_ Qtile before the issue yesterday, although I don't remember why I did it. Might have just been that the weather widget was initialized before my network connection again.

I'll keep an eye on this and, if it doesn't show up again, I'll close the issue in a few days.

**Comment by tcld** [comment]
I have encountered this again. There might be an issue with group matching - my dropdown terminal spawns like a normal window after I manually opened a proper terminal (i.e. there are two windows with the same `wm_title` etc.). After I closed both terminals, the drop down terminal stopped working altogether. So it looks like something is trying to bunch windows of the same class etc. into the same group?

So far, this seems to reproduce the issue:
1. Use my scratchpads (or yours, but then you probably have to launch your programs instead).
2. Open a terminal or a terminal and then neovim (as per my two scratchpads).
3. Open the scratchpads. They should open in a normal window instead of as a scratchpad.
4. Close the "scratchpad" and your manually opened window.
5. Open the scratchpad again. Nothing should happen.

Could anybody give this another go?

**Comment by elParaguayo** [comment]
I have two scratchpads: an `alacritty` terminal and `spt`. I followed the steps above and had no problems.

What terminal are you using? I've no reason to suspect that's causing your issue but I'm happy to try to replicate your setup.

**Comment by tcld** [comment]
I'm using `terminator` at the moment.

I experimented with neovim a little and restarted my Qtile a few times in the process. Right now my scratchpads work.

Have you tried, instead of just hiding the scratchpad after it showed up, to close it?

**Comment by elParaguayo** [comment]
Had tried closing (rather than hiding) but no issues there.

However... switching to `terminator` gave me all the issues you're seeing (scratchpads opening as normal windows, not opening at all). So it looks like that's the cause of the issue.

Try a different terminal and see if your behaviour changes.

**Comment by tcld** [comment]
Thank you for testing that out, I would have never expected such a weird issue. After installing alacritty I can use the scratchpad throughout all the steps I listed above.

I guess I have to take a look at the scratchpad-code again to find out whether this might be an issue with Qtile or terminator. A while ago I switched from alacritty to terminator specifically because of other issues I had, and I was glad to have found another program written in Python. I'll have to reconsider, it seems.

**Comment by elParaguayo** [comment]
Ok. This is getting beyond my level of expertise. 

Might need the skills of @tych0 and/or @ramnes to take over her!

**Comment by m-col** [comment]
I also see what you are seeing exclusively with terminator and nothing else.



> One is that whenever _any_ `terminator`-window is killed, my scratchpad calls its `_check_unsubscribe()`-method - which, if there is any scratchpad alive, succeeds

Do you mean it succeeds in unsubscribing? If so then there aren't any dropdowns, and any windows that you see must not be dropdowns (from Qtile's POV).

All in all it sounds like an issue with detecting the right window. This can sometimes happen with terminals if/when they are running in some kind of server-client mode because process and window IDs might not match. I work around this with `urxvtd` but using `urxvt` (standalone) for my dropdowns, where my regular terminal is `urxvtc` (client). _However_ it looks like terminator can do this with `terminator -u` but unfortunately this didn't fix it for me.



> My assumption right now is that this is all related to `terminator` being _a little_ slower than alacritty when it comes to launching/closing. Maybe there is a hidden race condition somewhere.

I don't think this is it, because you could stick firefox or something else slow in a dropdown and it'd work fine.

**Comment by tcld** [comment]
> Do you mean it succeeds in unsubscribing? If so then there aren't any dropdowns, and any windows that you see must not be dropdowns (from Qtile's POV).

Yes.

Thanks for the other input. If I find the time, I will debug this a little further. Maybe something good will come out of it. (the z-stuff has a higher priority, though)
