### ISSUE TITLE
Extreme Tux Racer flickers in qtile

### ISSUE THREAD

**Issue by RiedleroD** [qtile/qtile#2292]
# Issue description

Upon opening etr, the screen begins to flicker, while the music is playing in the background. etr works fine on sway and i3.
This issue seems to be related to  i3/i3#2499

# Qtile version

0.17.0

# Stack traces

* `~/.local/share/qtile/qtile.log`: https://pastebin.com/4ajQ0sd3
# Configuration

* `~/.config/qtile/config.py`: https://pastebin.com/ZUYZTJTD

**Comment by m-col** [comment]
Does it do this?

https://user-images.githubusercontent.com/44536113/111065222-8a0ab480-84b0-11eb-86ae-ee3116c246a8.mp4

**Comment by m-col** [comment]
Hmm, github doesn't like the video. Try using mpv or something if you can if it also tells you it is corrupt.

**Comment by RiedleroD** [comment]
No, it flickers fullscreen and black, right from the beginning.

**Comment by RiedleroD** [comment]
tested again with qtile 0.17.0-1 and extreme tux racer 0.8.0-1; the issue seems to be resolved.
