### ISSUE TITLE
Right way to call a function

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#2293]
Hi, Im not sure if this in an error.

I have a function 

def wsearx(qtile):
    qtile.groups_map["4"].cmd_toscreen(toggle=False)
    run('script.sh')

This function is called by a Key Shortcut and a widget on the bar

Key([mod],"f",lazy.function(wsearx)),
&
widget.TextBox(
                    font='Font Awesome 5 Free',
                    fontsize=15,
                    foreground=colors[7],
                    text="",
                    mouse_callbacks={'Button1': wsearx},
                    fontshadow=colors[3]
                    ), 

The issue is that when the function is wsearx(qtile), i can call it from the key shortcut but not from the widget, and when the function is wsearx(), i can call it from the widget but not from the key shortcut.

i think i am calling the function wrong from the widget but it used to work both ways before update 0.17

**Comment by tych0** [comment]
Yes, mouse_callbacks no longer give the qtile object as an argument: https://github.com/qtile/qtile/blob/master/CHANGELOG#L68
