### ISSUE TITLE
KhalCalendar doesn't read appointments

### ISSUE THREAD

**Issue by greweln** [qtile/qtile#2296]
# Issue description
The widget displays "No appointments scheduled" , ignoring any records in khal.
![screenshot](https://user-images.githubusercontent.com/78338967/111071002-8ecc6a00-84aa-11eb-9d6d-a90a666ddbd5.png)
 

I check the qtile.log and noticed nothing related to this.
# Qtile version

# Stack traces

# Configuration

**Comment by Fabien-Bernard** [comment]
To gather informations about appointments, KhalCalendar widget uses the khal command **agenda** with the option **days**.

Snippet of khal changelog v0.9.0 - Backwards Incompatibilities section :
```
- renamed agenda to list
- removed days configuration option in favor of timedelta
```
If the version of khal used is higher, it won't work without modification of the widget.

**Comment by greweln** [comment]
thnak you @Fabien-Bernard 
I modified the widget as you suggested. All good now
![screenshot](https://user-images.githubusercontent.com/78338967/111097945-e7d2e700-8518-11eb-97ff-0dccf6a50b07.png)

**Comment by greweln** [comment]
issue fixed.
