### ISSUE TITLE
Do qtile have move specific window to specific workspace?

### ISSUE THREAD

**Issue by pypeetpy** [qtile/qtile#2299]
# Issue description
1. does Qtile have move specific window to specific workspace?
2. does Qtile have specific workspace display on specific screen?

# Qtile version
0.17.0

# Stack traces

# Configuration

**Comment by m-col** [comment]
Sorry, I'm not sure what you mean exactly. Do you mean is it possible to bind a specific action to a key combo?

**Comment by pypeetpy** [comment]
sorry, I'm using I3 and in I3 when i start Telegram so i can tell i3 put Telegram window to workspace 10 in monitor on the right hand side with out press any key, did qtile have this kind of config?

**Comment by ep12** [comment]
@pypeetpy take a look [at the docs](http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.client_new) and see if that helps you configure qtile to your liking.

**Comment by diego-rapoport** [comment]
1. It does. I believe the default is Super+Shift+[your workspace]
2. Don't know if it has like an automatic way to do this, but you can always change the workspace on a specific screen by calling another workspace with that screen in focus. Than you can manually set all the screens.

**Comment by greweln** [comment]
take a look at this :

```
groups = [                                                                 
    Group("a", label = ""),                                                                         
    Group("s", label = ""),                                                     
    Group("d", label = ""),                              
    Group("f", label = ""),                                                      
    Group("j", label = ""),                                                                                      
    Group("k", label = ""),                                                                      
    Group("l", label = ""),                                                                      
]                                                        
                                                                                                                       
for i in groups:                                                                                  
    keys.extend([                                                                                 
        Key([alt], i.name, lazy.group[i.name].toscreen(),                      
            desc="Switch to group {}".format(i.name)),                          
                                                                              
        Key([alt, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True),     
            desc="Switch to & move focused window to group {}".format(i.name)),      
    ])  
```
