### ISSUE TITLE
widget.LaunchBar padding background color

### ISSUE THREAD

**Issue by lgaboury** [qtile/qtile#2301]
# Issue description

When the widget.LaunchBar is used with a padding greater than 0 (zero), the rightmost padding does not respect the bar background color. 

# Qtile version

0.17.0

# Configuration

```
screens = [
    Screen(
        top=bar.Bar(
            [
                widget.CurrentLayoutIcon(),
                widget.GroupBox(),
                widget.Prompt(),
		        widget.LaunchBar(
		            [      
		                ("google-chrome", "google-chrome-stable", "Launch Google Chrome"),
                        ("firefox", "firefox", "Launch Google Firefox"),
		            ],
                    padding=15
                ),
		        widget.Spacer(),
                widget.Clock(format='%a %d %b %Y %I:%M %p'),
		        widget.Spacer(),
                widget.Systray(),
                widget.QuickExit(),
            ],
	        29, background="#008880", opacity=.5
        ),
    ),
]
```
![2021-03-16-190402_436x32_scrot](https://user-images.githubusercontent.com/50297059/111395278-76b34100-868a-11eb-9b26-447083e6ab4d.png)

**Comment by lgaboury** [comment]
My appologies as I can't seem to be able to insert my code so it is properly formatted.

**Comment by elParaguayo** [comment]
Looking at the source code, it does appear that, while the background colour is set, the widget never actually draws to that final bit of padding.

Can you do a pull request for this or do you need someone else to?
