### ISSUE TITLE
Feature Request groups for every screen or workspaces missing

### ISSUE THREAD

**Issue by karstengo** [qtile/qtile#2312]
Hey,

as I come form awesome there it is possible to have on each screen same names of workspaces ( groups.. ) but dedicated to each screen and it depends on which screen is focused when switching groups / workspace it only switches groups on that screen.
Behaviour in qtile:
You can bring up same group on other screen by just selecting it, which is kinda cool. But you cannot use same identifiers like 1,2,3 on different screens.

So it would be nice to have groups 1,2,3 detached to screen 1 and 1,2,3 on screen 2. Both can have applications which do not know from each other.
It is semi possible via 

```
                widget.GroupBox(visible_groups=['1', '2', '3'], size=30),
```

But this would mean you can only use 1,2,3 on screen x and not on screen y with different applications

Maybe the feature request would be better called. Workspaces would be a nice to have?

best regards

**Comment by ramnes** [comment]
Your issue is just about the group names? If so, a group can have a label, I guess you could use that.
