### ISSUE TITLE
FreeBSD + qtile: cannot find default config.py

### ISSUE THREAD

**Issue by r2com** [qtile/qtile#2326]
I know I am supposed to copy "/usr/share/doc/qtile/default_config.py" to the "/home/yourusername/.config/qtile/config.py" before first run.

but the problem is, after installing qtile to freebsd as stated on manual page: pkg install qtile
I do not see default_config.py in above mentioned folder to copy from. why is that?

btw, I did add exec qtile in my .xinitrc and with startx i can indeed start qtile but it starts with error, and log file says that config.py was not loaded. which makes sense because i did not copy it since i didnt know where to grab it from

any ideas?

**Comment by ramnes** [comment]
What version of Qtile? You're not supposed to copy anything anymore for a few versions now.

**Comment by r2com** [comment]
0.14.2

**Comment by r2com** [comment]
hm.. it seems that FreeBSd freshports offered only 0.14.2, do you then suggest build from source?

**Comment by ramnes** [comment]
This version is really old so yeah, I'd recommend installing from source. :)
