### ISSUE TITLE
Provide information on release manager(s) and chain of trust

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#2327]
# Issue description

As a packager of qtile for Arch Linux I am happy to see, that you create verifiable releases for qtile by e.g. using signed tags.
Generally, Arch Linux (and other downstreams) try to make use of existing means of source verification to fend off [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack).
Unfortunately it is not enough for individuals to sign their tags, as this only ensures, that the specific individual used a specific PGP key to sign a tag.
Between v0.12.0 and including v0.14.2 @flacjacket provided signed tags using `4EDAC65FECB64426`, while @tych0 signed the most recent release v0.17.0 using `18D18F1BC464DCA3`.

To provide the means for downstreams to follow up on a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) it is necessary to document who is in charge (can be multiple persons) of the release process of a project and which PGP key IDs are expected to be used for signed tags and/or signed release artifacts. This can happen in a document such as the README of the project. The trust towards the person first adding this information is trusted on first use ([TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use)).

Changes to this document, that e.g. introduce a new key ID should then *always* happen with a signed commit of the person that is already trusted. Cross-signing the respective individual's keys is of course also an (additional) option to provide a chain of trust.

Generally I would be happy to use verifiable source tarballs (e.g. sdist tarballs) or clone from a verifiable tag to build this project.

If you have any questions in regards to best practices, please let me know.

# Qtile version

Any

# Stack traces

n/a

# Configuration

n/a

**Comment by tych0** [comment]
Ha, someone just e-mailed me about exactly this :). My key should be signed by @flacjacket here: https://tycho.pizza/tych0.asc so we have that chain at least.

Is it more valuable to have it in the project readme, on qtile.org, or on docs.qtile.org (hosted by a third party readthedocs)?

**Comment by dvzrv** [comment]
I think the best would be in the README of this repository as it directly relates to the project and commits are done towards the same repository.

Thanks for looking into this! :)

**Comment by tych0** [comment]
Ok; I will add a MAINTAINERS with @flacjacket @ramnes @m-col and myself for now, listing their GPG key fingerprints. Gonna do a bit of off-line dancing to try and get them all cross signed, I'll close this issue when it's addressed.

**Comment by dvzrv** [comment]
In the case of the document stating the valid/known PGP key fingerprints it would probably suffice if @flacjacket or you created and signed the commit for that document, as other than the two of you, noone has used signed tags so far, and thanks to the aforementioned cross-sig between the two of you the chain could probably start with either of you! :)

**Comment by tych0** [comment]
Will do. I've got the key ready, just waiting on @ramnes to confirm his fingerprint :)
