### ISSUE TITLE
When a program goes in the system tray the whole bar becomes transparent

### ISSUE THREAD

**Issue by SebastianDorobantu** [qtile/qtile#2334]
# When a program goes in the system tray the whole bar becomes transparent

Every time i open a program/app that has a sys tray icon the whole bar goes transparent with a weird white gradient on the left
making reading everything very dificult

# Latest version of qtile
I think this is the commit hash hope this is right idk how it works 
15569a97f72d3a5f4e688124987110dc3e65e8e0

I am running a nvidia gpu with jonaburgs fork of picom 

![DeepinScreenshot_select-area_20210329143147](https://user-images.githubusercontent.com/62898162/112831130-2bdaf580-909c-11eb-9b94-28ee120ac813.png)

**Comment by m-col** [comment]
Does it happen when you don't have picom running?

**Comment by SebastianDorobantu** [comment]
No it doesn't

**Comment by m-col** [comment]
I also assume this isn't anything to do with the specific picom fork you're using? I have to ask these questions where the answer might be obvious to you because 1. I don't know what else you're running on your system, 2. I have no other leads as to what can be causing it and 3. you seem to be the only one with this issue.

**Comment by SebastianDorobantu** [comment]
You were right to assume that , no worries , i have just checked and it seems to happen indiferent of what fork of picom I am using.

**Comment by m-col** [comment]
Please could you post your config for the Bar and widgets? @elParaguayo I wonder if https://github.com/qtile/qtile/pull/2513 will fix this

**Comment by elParaguayo** [comment]
It may do but I can't recreate the issue. Having a config would certainly help.

**Comment by ramnes** [comment]
I'll go ahead and close this one since we can't replicate. Please reopen an issue with more context if you're still hitting this with 0.23.0.
