### ISSUE TITLE
multiple systray widgets are racy

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#2336]
The Distrotube Guy reports via https://www.youtube.com/watch?v=9NO2DJARbU0 that multiple systrays are racy.

The spec says: https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.1.html#locating

that we should use `_NET_SYSETM_TRAY_Sn` for the nth system tray widget, but I think our code calculating this is wrong:

https://github.com/qtile/qtile/blob/master/libqtile/widget/systray.py#L129

This code always uses qtile's current screen, instead of the screen that the bar is on. It should at least use the right value for `n`.

Perhaps instead, we could make multiple Systray() objects be an error, and just have people specify one and let it mirror everywhere.

**Comment by elParaguayo** [comment]
I suspect we can't add a `Mirror` as the icons are windows rather than being rendered by the widget's `Drawer`.

We can certainly still make multiple `Systray`s be an error.

**Comment by m-col** [comment]
Even if we could mirror them (which might be possible if we can get the pixmap data... but I doubt it'd be simple), there would also be the question of how they respond to clicks. I assume clients will just respond to icon clicks how they see fit, and so some may open menus at the pointer location (which would be ideal for mirroring the systray) but others may open them from the icon's position perhaps.

Also - mirroring would have to respond to changes in the icon's contents just like `Mirror` except this time it's draws to the window's pixmap. I'm not sure if that can be listened to as an X event.

**Comment by elParaguayo** [comment]
You could probably make any `Systray.draw()` call, also call the Mirror's `draw` method too but I think the mouse clicks are the bigger issue here as you can't replicate it in the Mirror.

As I understand it, the Systray icons are windows and so respond to mouse clicks in accordance with however that application desires, e.g. toggling state, showing a menu (generated by the application). I don't see how we could get a Mirror's mouse click event to do the same.

So, two things we can do:
- make multiple `Systray` raise an error - probably remove the second one too
- prevent mirroring of `Systray` if someone tries to pass the same object to multiple bars

**Comment by m-col** [comment]
Yeah that would be good. We can set a boolean `global` in `systray.py` during `Systray._configure()`, and if it's already set, raise the config error.

A bit hacky perhaps but we override `create_mirror` so that it returns itself or another `Systray` we force the config error.
