### ISSUE TITLE
No perfect alignment of windows

### ISSUE THREAD

**Issue by lkjell** [qtile/qtile#2352]
In MonadTall and Columns layout (only these are tested) when there are too many windows opened the background will become visible.

# Issue description
Open many windows.
![qtile leaking](https://user-images.githubusercontent.com/6495040/113423132-3b28ae80-93ce-11eb-8074-238ebceeafc4.png)
![qtile leak1](https://user-images.githubusercontent.com/6495040/113423151-3f54cc00-93ce-11eb-9325-75d89b2de0b8.png)

# Qtile version
0.17.0 released

# Stack traces

# Configuration
Just use the default config but comment out layout.

**Comment by m-col** [comment]
Don't open so many windows?

jk. yeah it would be nice if these layouts resolved this.
