### ISSUE TITLE
Make fullscreen windows non-draggable or restore previous state before dragging

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#2387]
It doesn't make sense to drag a window that's taking the whole screen size.

Thank you @drishal for the idea.

**Comment by m-col** [comment]
Yeah, sounds good. I really like the fact I can drag a fullscreen window but it definitely makes sense to restore its dimensions before moving it (and make it floating if it wasn't), so I vote for the latter.

**Comment by ramnes** [comment]
Why do you like that? I'm rather leaning towards disabling drag completely.

**Comment by m-col** [comment]
Guess I'm lazy and like to skip the un-fullscreen step if i want to float it and
then drag it.
