### ISSUE TITLE
Formatting issue in docs

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#2390]
# Issue description

As reported in qtile-dev group, there's a formatting bug in the docs where the parameter name and type are joined into a single word.

See example here: https://docs.qtile.org/en/latest/manual/config/groups.html#group

I'm not familiar with sphinx so I'm not immediately sure how to fix this.

# Qtile version

Latest

EDIT:
On the docs site, in v0.16.1 there was a colon between the parameter and its type. However, testing locally I have that colon showing even with the latest version.

**Comment by ramnes** [comment]
Still present in a lot of other places

**Comment by elParaguayo** [comment]
@ramnes - can you point me to these other issues (I couldn't immediately see any) and I'll fix them

**Comment by ramnes** [comment]
Uh I can't remember what I was referring to, sorry, but it's at least there: https://docs.qtile.org/en/latest/manual/config/groups.html#scratchpad

**Comment by kaistian** [comment]
You get potential candidates you run a `grep -r " : "` to also get the class name you can run this `git grep -n -p " : "`
