### ISSUE TITLE
Can't login to Qtile

### ISSUE THREAD

**Issue by dragonDScript** [qtile/qtile#2401]
I'm trying to log in to Qtile, however, gnome is started instead.

This is my `/usr/share/xsessions/qtile.desktop` file:
```
[Desktop Entry] 
Name=Qtile
Comment=Qtile Session
Exec=~/qtile/bin/qtile $*
Type=Application 
Keywords=wm;tiling

```

**Comment by m-col** [comment]
Try changing "Exec=~/qtile/bin/qtile $*" to "Exec=~/qtile/bin/qtile start $*"

**Comment by dragonDScript** [comment]
> Try changing "Exec=~/qtile/bin/qtile $*" to "Exec=~/qtile/bin/qtile start $*"
> […](#)
> On 210418 07:15, dragonDScript wrote: I'm trying to log in to Qtile, however, gnome is started instead. This is my `/usr/share/xsessions/qtile.desktop` file: ``` [Desktop Entry] Name=Qtile Comment=Qtile Session Exec=~/qtile/bin/qtile $* Type=Application Keywords=wm;tiling ``` -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #2401

:+1:

**Comment by dragonDScript** [comment]
I can't log in yet.

**Comment by m-col** [comment]
Sorry, I thought the thumbs up was you saying that it worked.

**Comment by dragonDScript** [comment]
> Sorry, I thought the thumbs up was you saying that it worked.

No problem, sorry for the confusion.

**Comment by cr1ogen** [comment]
My /usr/share/xsessions/qtile.desktop file working

[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=qtile start
Type=Application
Keywords=wm;tiling

I use Lightdm

**Comment by tych0** [comment]
...did you select the qtile session from lightdm?

**Comment by dragonDScript** [comment]
Alright, I logged in to qtile from the terminal. The error said:
No module named 'something starting with c i can't remember. it had some ffs in the middle.'

**Comment by tych0** [comment]
You're probably missing cffi, which is a dependency of qtile. It sounds like you need to read: http://docs.qtile.org/en/latest/manual/install/#installing-from-source

**Comment by dragonDScript** [comment]
From my console:
Requirement already satisfied: xcffib in /usr/lib/python3/dist-packages
(0.8.1)
