### ISSUE TITLE
Using `subscribe.client_new` doesn't send new clients to designated workspaces

### ISSUE THREAD

**Issue by cysea** [qtile/qtile#2403]
# Issue description

Using the subscribe.client_new doesn't send clients to other workspaces, and I am clueless as to why.
If I have a workspace named "WWW", then opening "chromium" while focused on the "DEV" workspace, should automatically send "chromium" to the "WWW" workspace according to the documentation and it's syntax. Instead "chromium" just opens on the "DEV" workspace. Same for all the other clients defined at the bottom of my config file.

I have tried both solutions (hook, and Match(wm_class...)), recommended from [another request](https://github.com/qtile/qtile/issues/1821), although a similar issue, and neither seem to be working.

# Qtile version

0.17.1.dev141+g90a07097

# Stack traces

https://pastebin.com/DP56hE6P

# Configuration

https://pastebin.com/cXk3Q9Cg
Line `199`: Workspace names.
Line `593`: subscribe.client_new hook

**Comment by m-col** [comment]
Client new hook:
```py
@hook.subscribe.client_new
def client_new(client):
    if client.name == 'chromium':
        client.togroup("WWW")
```

First of all can you confirm that the `if` statement is matching correctly by adding a logging line to it?

**Comment by cysea** [comment]
You are correct.

`client.name` is actually the window title.

`2021-04-20 10:18:49,111 WARNING libqtile config.py:client_new():L597 Window('Inbox - foo@bar.baz - Mozilla Thunderbird')`

`2021-04-20 10:18:56,772 WARNING libqtile config.py:client_new():L597 Window('New Tab - Chromium')`

Is there an easier way to get this fixed or am I supposed to do custom regex?

Also, should this be considered a bug? `client.name` should be != `client.title`

**Comment by cysea** [comment]
Okay this is what my `config.py` looks like now.

```python
@hook.subscribe.client_new
def client_new(client):
    logger.warning(client)
    if client_check('chromium', client):
        client.togroup("WWW")
    elif client.name == 'Discord' or client.name == 'Discord Updater':
        client.togroup("DISC")
    elif client.name == 'Signal':
        client.togroup("CHAT")
    elif client.name == 'spotify':
        client.togroup("MUS")
    elif client.name == 'VLC media player':
        client.togroup("VID")
    elif client.name == 'Mozilla Thunderbird':
        client.togroup("MAIL")

def client_check(new_window, client):
    check = bool(re.search(new_window, client.name, re.IGNORECASE))
    return check
```

Everything seems to be working except spotify, I'll open another issue because that seems like a separate problem.

I used the following to find proper window names.

```python
from libqtile.log_utils import logger
...
@hook.subscribe.client_new
def client_new(client):
    logger.warning(client)
    ...
```

**Comment by m-col** [comment]
Great, glad you got it working.

It might be worth looking into the `matches` argument to `Group`, which can be
used to match new clients to move them to the given group.

On 210420 02:06, cysea wrote:
>Okay this is what my `config.py` looks like now.
>
>```python
***@***.***_new
>def client_new(client):
>    logger.warning(client)
>    if client_check('chromium', client):
>        client.togroup("WWW")
>    elif client.name == 'Discord' or client.name == 'Discord Updater':
>        client.togroup("DISC")
>    elif client.name == 'Signal':
>        client.togroup("CHAT")
>    elif client.name == 'spotify':
>        client.togroup("MUS")
>    elif client.name == 'VLC media player':
>        client.togroup("VID")
>    elif client.name == 'Mozilla Thunderbird':
>        client.togroup("MAIL")
>
>def client_check(new_window, client):
>    check = bool(re.search(new_window, client.name, re.IGNORECASE))
>    return check
>```
>
>Everything seems to be working except spotify, I'll open another issue because that seems like a separate problem.
>
>I used the following to find proper window names.
>
>```python
>from libqtile.log_utils import logger
>...
***@***.***_new
