### ISSUE TITLE
Spotify client opens as "None" ; Can't send "None" client to designated workspace

### ISSUE THREAD

**Issue by cysea** [qtile/qtile#2405]
# Issue description

As seen in `qtile.log`, a client_check is commenced when starting a new client, since the newly opened window is None (spotify), the function fails. Opening chromium works and sends the window to the proper workspace. I can't even get the spotify window name because the logger says it's none. Looking this up brought me to [another issue](https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/td-p/1247042) on spotify's help page, but I don't really see a solution there.

I could call the `client_check` function for the `elif` part of my code, but I still have a Null comparison, so it wouldn't do any good.

# Qtile version

0.17.1.dev141+g90a07097

# Stack traces

```
2021-04-20 11:08:58,050 WARNING libqtile config.py:client_new():L597 Window(None)
2021-04-20 11:08:58,050 ERROR libqtile hook.py:fire():L380 Error in hook client_new
Traceback (most recent call last):
  File "/home/agent/.local/lib/python3.8/site-packages/libqtile/hook.py", line 378, in fire
    i(*args, **kwargs)
  File "/home/agent/.config/qtile/config.py", line 598, in client_new
    if client_check('chromium', client):
  File "/home/agent/.config/qtile/config.py", line 612, in client_check
    check = bool(re.search(new_window, client.name, re.IGNORECASE))
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

# Configuration

```python
@hook.subscribe.client_new
def client_new(client):
    logger.warning(client)
    if client_check('chromium', client):
        client.togroup("WWW")
    elif client.name == 'spotify':
        client.togroup("MUS")

def client_check(new_window, client):
    check = bool(re.search(new_window, client.name, re.IGNORECASE))
    return check
```

**Comment by m-col** [comment]
It looks like `client.name` is None, not `client`. Is that right? Trying matching using a `Match` (to Group(matches=...)) and match using a `wm_class`. Maybe spotify is setting its class correctly.

**Comment by cysea** [comment]
The `client.name` part is irellevant, because spotify might not even be the name of the client.

Since the spotify client triggered the hook, it is the client, and that's why the script fails on the first `if`, since `client_check` can't parse `client`, also `logger.warning(client)` prints it out as none.

**Comment by ramnes** [comment]
This problem has been discussed a few times already. The issue with Spotify is that it doesn't have its attributes set when it's spawned, only a few ms later. Since #2063, one solution is to sleep asynchronously in the hook function. Something in those lines should do:

```python
import asyncio

@hook.subscribe.client_new
async def move_spotify(client):
    await asyncio.sleep(0.01)
    if client.name == 'spotify':
        ...
```

**Comment by wolfisberg** [comment]
I think the `client_name_updated` hook would be more fitting to solve this issue, as it does not require any `await sleep` hacks. This may have unintended consequences though. E.g if the window changes its name at some point later on and you manually changed its group, it will be reset to the group specified in the hook (and refocused in the solution below).

Anyway, this is how I solved it

```
@hook.subscribe.client_name_updated
def move_spotify_workaround(window):
    try:
        if window.name.lower() == 'spotify':
            music_group = [g for g in qtile.groups if hasattr(g, "label")
                           and "music" in g.label.lower()][0]
            window.togroup(music_group.name)
            music_group.cmd_toscreen(qtile.current_screen.index)
    except Exception as e:
        logger.warning("Failed to move spotify window to group.", e)
```

**Comment by pharaok** [comment]
I also wasn't a big fan of the async hack and while I haven't had the window be moved back to its group after it was manually moved, I came up with this anyway.

```python3
from collections import defaultdict

class WindowMatcher:
    def __init__(self, name, group):
        self.name = name
        self.group = group
        self.rename_count = defaultdict(int)

        hook.subscribe.client_name_updated(self.client_name_updated)
        hook.subscribe.client_killed(self.client_killed)

    def client_name_updated(self, client):
        if self.rename_count[client.wid] > 1:
            return

        self.rename_count[client.wid] += 1

        if client.name == self.name:
            client.cmd_togroup(self.group)

    def client_killed(self, client):
        self.rename_count.pop(client.wid)


WindowMatcher("Spotify", "Music")
```

it should only move the window if its original name or its first rename matches.
