### ISSUE TITLE
Building from source fails for FreeBSD for 0.17.0

### ISSUE THREAD

**Issue by r2com** [qtile/qtile#2420]
# Issue description:

When I try to modify Makefile to source from 0.17.0 in FreeBSD 12.2 and install all dependencies, and then do "make install". I see the following error:

LookupError: setuptools-scm was unable to detect version for '/usr/ports/x11-wm/qtile/work/qtile-0.17.0'.

# Qtile version
0.17.0

**Comment by tych0** [comment]
Try using a git clone, I think we need to rearrange our use of setuptools-scm to allow for tarball based installs.

**Comment by r2com** [comment]
what do you mean by trying to use a git clone? Just cloning the git repository and build inside using make install?

just to remind that I am using it on FreeBSD, and basically the way I do it is just change version to 0.17.0 in Makefile inside the ports settings folder and compiling from source.

**Comment by tych0** [comment]
> just to remind that I am using it on FreeBSD, and basically the way I do it is just change version to 0.17.0 in Makefile inside the ports settings folder and compiling from source.

I'm not familiar with the freebsd ports makefile. I mean checking out the tagged git version you want and then installing it as you would any other python program.

I wouldn't hand edit versions anywhere, that is a recipe for confusion.

**Comment by r2com** [comment]
so will setuptools-scm related issue be considered and fixed?

**Comment by tych0** [comment]
They definitely will if someone sends a patch :-)
