### ISSUE TITLE
Features I'm missing from Sway

### ISSUE THREAD

**Issue by hernan3009** [qtile/qtile#2421]
Hi,

I am trying to implement some functions in my config.py file to add some functionality that I miss from Sway and I really wish to have in Qtile. The are:

1) Swap between tiled windows using mouse: Hold MOD+Left clic and drag win_1 to win_2, after releasing win_1 and win_2 must permute their places.
2) Resize tiled windows using mouse: MOD+Right clic in any part of a tiled window lets change its size (and adjust the size of the remaining windows in the group) [1 and 2 can be viewed in action in [this](https://swaywm.org/) video]
3) Stick a window to some region of the monitor:  The window remains always visible in the same way no mater if other windows are modified or if I move to another group (this is nice to play videos will doing other activities...).

I have been many hours reading the Docs and playing with the config file but I am stuck. I am trying to follow the example from [here](https://github.com/qtile/qtile-examples/blob/master/bglasber.py).

I made a keybinding to a new function:
`    Key([mod], "i", lazy.function(new_function), desc="Prueba"),`
The function is:
```
def new_function(qtile):
    if qtile.currentWindow is not None:
        i = qtile.groups.index(qtile.currentGroup)
        qtile.currentWindow.togroup(qtile.groups[i + 1].name)
    return
```
I get (in the .log file)
`AttributeError: 'Qtile' object has no attribute 'currentWindow'`

I managed to send some data to `new_function` through optional parameters like `Group` but I cannot get info and processing it in a reasonable way (as the function in the example). Is this behaviour normal or is some bug?

Qtile version:    0.17.1

**Comment by tych0** [comment]
A while ago we changed a bunch of camelCase stuff to snake_case, this is one of them. You should be able to use current_window.

**Comment by hernan3009** [comment]
Thank you! I continued trying and found a partial solution: `currentWindow` seems to be `current_window` (maybe outdated example file?). The same applies when changing "Window" to "Group".

Are there any known solutions to the three mentioned functions? (I am not a developer and it seems to me that it will be very hard for me to implement them)

**Comment by ramnes** [comment]
1 is already implemented but non-functional at the moment. See PR #1334 for relevant history, discussion, and a fix proposal.

I don't think you will be able to implement 2 globally with our current layouts architecture. That being said, if you're coming from Sway and want something that feels similar, you might be interested in the BSP layout. Modifying this layout specifically to add the feature you mentioned in 2 shouldn't be too hard.

For 3, you just have to bind [`lazy.window.static()`](http://docs.qtile.org/en/latest/manual/ref/commands.html#libqtile.backend.x11.window.Window.cmd_static).
