### ISSUE TITLE
Error using qtile cmd-obj with an argument meant to be an int

### ISSUE THREAD

**Issue by amjack100** [qtile/qtile#2433]
Hello,

I'm trying to write a simple script to switch focus between screens and found that using
```
qtile cmd-obj -o cmd -f to_screen -a 0
```
in the terminal  causes a TypeError where the arg "0" can be any integer.

I'm guessing that this can be fixed with a simple "int()" somewhere, right? I'd make the pr myself but I'm new to github and need more experience with issues first.

---
```
$ qtile --version
0.17.1.dev166+g2f36ad91
```
---

```
$ qtile cmd-obj -o cmd -f to_screen -a 0

error: Sorry cannot run function 'to_screen' with arguments ['0']: Traceback (most recent call last):
  File "/home/andy/.local/lib/python3.8/site-packages/libqtile/command/interface.py", line 313, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/home/andy/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 1293, in cmd_to_screen
    return self.focus_screen(n)
  File "/home/andy/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 851, in focus_screen
    if n >= len(self.screens):
TypeError: '>=' not supported between instances of 'str' and 'int'

```

Thanks!

**Comment by m-col** [comment]
Hey @amjack100 and welcome to github. I think you're right, all that would be needed is an `int()` stuck somewhere, most likely in `Qtile.cmd_to_screen`. However I actually came across this same issue with another command the other day, so it might be better to have a mechanism to check arguments for integers and cast them if needed, rather than doing it within each command manually. This is what I have implemented in #2435.

**Comment by jrwrigh** [comment]
Error is also present in `qtile shell`. Figured I'd mention it since I was about to write up a separate issue for the same problem (but searching didn't turn it up).

**Comment by ramnes** [comment]
We could probably use the type hints to deserialize the inputs... :)

**Comment by FerrielMelarpis** [comment]
Is there a workaround to make the `cmd-obj` API work?
Any function that expects int fails as it parses the args I passed as string.
For e.g. `qtile cmd-obj -o window -f resize_floating -a 5 5`
```
Sorry cannot run function 'resize_floating' with arguments ['5', '5']
```

**Comment by elParaguayo** [comment]
You can use a python script:
```python
from libqtile.command.client import InteractiveCommandClient

c = InteractiveCommandClient()
c.window.resize_floating(5, 5)
```
It's pretty ugly, I know. However, it does work.
