### ISSUE TITLE
IPC connection error due to appended `.0` to DISPLAY

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2436]
# Issue description

Running `qtile cmd-obj ... ` from the command line seems to fail with

```
IPCError: Could not open /home/mcol/.cache/qtile/qtilesocket.:0.0
```

# Qtile version

I think this was introduced by https://github.com/qtile/qtile/commit/03e911bd0dcd49cfea6e4e1ee9c6e6ddff273e57

The original version (before this commit) of `find_sockfile` appended `.0` to DISPLAY if it wasn't there already, and it seems that that is causing the problem for me now. Why was this originally there, and is it still needed?

# Configuration

e.g. `qtile cmd-obj -o cmd -f windows`

**Comment by leschalu** [comment]
It used in past. Now xrandr combines multiple screens into a single one.
