### ISSUE TITLE
Bad icon scaling in Systray widget

### ISSUE THREAD

**Issue by juanscr** [qtile/qtile#2438]
# Issue description
1. I added the system tray widget to my qtile bar with an icon size of 20.
2. I currently use the icon set Papirus Dark.
3. I launched the `nm-applet` through the autostart script and I obtained a really small icon for the `nm-applet` as you can see in the following image: 

![image](https://user-images.githubusercontent.com/31258166/116829694-d0a09500-ab6a-11eb-805e-8f0e6a8cb91c.png)

The previous small icon also happened if I launched `nm-applet` through the terminal. 

One way I found to correct it was to setting the **icon size for the system tray to 16**. With this icon size, I obtained the following good results:

![image](https://user-images.githubusercontent.com/31258166/116829734-2412e300-ab6b-11eb-9687-e7121be99d21.png)

# Qtile version
`qtile 0.17.0`

# Configuration

My configuration can be found in the following [dotfiles](https://github.com/juanscr/dotfiles/tree/master/.config/qtile)

**Comment by elParaguayo** [comment]
I'm pretty sure this happens if the icon defines a `min_width` and `min_height` hint and these are smaller than your set `icon_size`. Looking at the code, there's nothing to increase the `icon_size` in that scenario.

I'll submit a PR with a potential fix. Would be good if you could test.

**Comment by juanscr** [comment]
I'll test it today and let you know how it goes.
