### ISSUE TITLE
No full screen on commands when used with lazy.spawn 

### ISSUE THREAD

**Issue by parasbhanot** [qtile/qtile#2443]
hi everyone , 

i am facing issue with command line tools . whenever i run any command [htop , calcurse] form terminal (kitty , alacritty, terminator)  it takes the full screen of terminal . 

![normal](https://user-images.githubusercontent.com/22582725/117099849-e2af4d00-ad8f-11eb-9569-01d5e23b18ed.png)

But when run same command from qtile confi.py using :

`Key([mod], "w", lazy.spawn("kitty -e calcures")) `

it only take small part of terminal . i have tried several terminal emulators but issue remains the same . 

![abnormal](https://user-images.githubusercontent.com/22582725/117099858-e80c9780-ad8f-11eb-939c-34603ace61ed.png)

Am i doing something wrong ? 
is this the normal behaviour of qitle ? 

# Qtile version --> 0.17.0

**Comment by ramnes** [comment]
Hi @parasbhanot,

This is being discussed already, mainly here: https://github.com/qtile/qtile/discussions/2164

Closing in favor of this other discussion.
