### ISSUE TITLE
Feature request: Move all windows to one workspace

### ISSUE THREAD

**Issue by luis-07** [qtile/qtile#2444]
# Issue description

I would like to have a workspace in which all windows move when I open it and when I switch to another the windows go back again

**Comment by ura43** [comment]
You can definitely do that already.
On a high level, you would use the hook that tracks group changes. Then, when a group is changed, you check wether its the special group you want.
Then you can basically grab the windows and put them there, tho that part is a little more involved. Check the documentation on scripting for that
