### ISSUE TITLE
Crash when using touchscreen and stylus

### ISSUE THREAD

**Issue by h-mnzlr** [qtile/qtile#2456]
# Issue description

I am using qtile on a Surface Laptop running archlinux as my main/only wm. For some time now I have experienced that using the stylus and touchscreen crashes qtile immidiatly (e. g. unable to switch groups, click on windows and their buttons or issue commands via keys while applications like videos keep rolling). I used to think this was just a quirk in my setup but lately I installed a demo version of i3 just to try this out, where I didn't find any crashing.

I notice that qtile allows two pointers to act on the coursor simultanously (when I use the touchpad and touchscreen at the same time, which by the way does not crash qtile). I believe this to be the problem, as the touchscreen's and stylus' pointer are weirdly intertwined due to them only having one native device file, split up into three different ones by the wacom driver I use (as opposed to the touchpad and touchscreen). This, I believe, creates a nonsensical input for the cursor to point to (I sometimes see similar logs from applications like xournal++). I have tried a few workarounds but haven't found a satisfying solution yet.

Sadly I have never found any output in qtile's logs suggesting a crash even happened or any indication of where to look for a fix. 
I would be very happy to provide more information and logs if someone has an idea how to find them :)

# Qtile version
0.17.0 (latest from arch repo)

**Comment by h-mnzlr** [comment]
Following the Issue feed, I thought #2461 was interesting regarding to this issue. And indeed my problem is solved: Qtile is not crash anymore when using both touchscreen and stylus. Thank you @m-col, even if I'm unsure whether it was intentional :)

**Comment by m-col** [comment]
It was not intentional but this is great :)
