### ISSUE TITLE
Doens't refresh when workspace changed

### ISSUE THREAD

**Issue by codic12** [qtile/qtile#2469]
When I change my workspace to an empty workspace (not a used one, issue doesn't occur then) all the windows from the workspace I am on appear in the new empty one, except I can't interact with them. If I open a window on the new workspace, the problem goes away. Also when i close the last window in a workspace, it just freezes (screen not refreshed). this seems to be a recent regression. I'm using Qtile 0.17.0 on arch and void linux.

**Comment by codic12** [comment]
Never mind, only seems to happen when a background is not set with eg feh.

**Comment by m-col** [comment]
Interesting resolution. Are you using a compositor?

**Comment by codic12** [comment]
Indeed, I'm using picom. The problem _might_ be caused by my display manager, sddm.

**Comment by m-col** [comment]
If you don't specifically want a wallpaper but this is annoying then you can just set a background color with `hsetroot -solid #ff0000`

**Comment by codic12** [comment]
I did want one, I just hadn't set it up yet and noticed that. Thank you for the helpful tip!
