### ISSUE TITLE
Bitcoin Ticker keeps showing locale currency sign

### ISSUE THREAD

**Issue by hamensman** [qtile/qtile#2470]
My locale is GB, so if I don't specify a currency, it will show BTC in £. But when I specify, say,"USD", it shows the USD **numbers** but still shows the "£" sign in front of it.

So let's say BTC is "$44,000" in USD and "£31,000" in GBP. If I don't specify, it will say "£31,000". But if I write "USD", it says "**£**44,000" (the USD value, but the GBP sign).

**Comment by elParaguayo** [comment]
Looking at the code, I don't think the symbol is connected to your chosen currency. As you say, it's just determined by your locale.

Would need some extra code to change the symbol too. Are you happy to have a go at submitting a pull request for this?

**Comment by m-col** [comment]
Yeah might be good to just add a text formatting option so users can stick in
whatever they want. It seems however that the symbol is found with
`locale.localeconv()['currency_symbol']`. For me this is `''` so... not helpful.

**Comment by elParaguayo** [comment]
You could move the symbol to being configurable but have it default to the locale version (which should hopefully mean it doesn't break for people currently using it). It can then be overwritten as necessary.

**Comment by m-col** [comment]
Yeah, sounds good. If the default format matches what it currently results in
i.e. `"{symbol}{value}"` or something, then `symbol` could be what it gets from
the locale, and nothing changes for most people. If people are not getting what
they want they can change it manually to `"£{value}"` for example.

**Comment by elParaguayo** [comment]
The widget hardcodes the display as `BTC: {symbol}{amount}`. We could pull that out into a configurable item as well (in case people want to change the prefix). Only issue with that is you've got two places where the symbol can be changed.

**Comment by m-col** [comment]
I think it's good that the general text format is configurable; this is what we
have for many other widgets. But I don't think we need `symbol` to be directly
configurable, because it'd be redundant like you said, as it can be set in the
format string. So rather than adding a `symbol` option (as the `{symbol}` in the
format string will always be from the locale), the string formatting option is
sufficient for setting non-locale symbols (but also for e.g. changing the
prefix).

**Comment by elParaguayo** [comment]
OK - it looks like that widget wasn't included in my batch of tests so I'm happy to make the changes and add a test while I'm at it.

**Comment by Graeme22** [comment]
Just saw this. Let me fit it in #2493.

**Comment by elParaguayo** [comment]
Thanks for picking this up. I'd done changes to the widget but had a manic week last week and hadn't got round to doing the test.

When your PR gets merged, I'll write a test for it.
