### ISSUE TITLE
Qtile on arch linux startup_once hook And other bug

### ISSUE THREAD

**Issue by heriyasuma** [qtile/qtile#2471]
i Have fress install arch linux with qtile nitrogen and picom, qtile work properly but i cant draw wallpaper with this code at config.py
```
from libqtile import hook
import os
import subprocess
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~/.config/qtile/autostart.sh') # path to my script, under my user directory
    subprocess.call([home])

```
and my this is autostart.sh 
`#!/bin/sh
picom &
nitrogen --restore &`
i already set my nitrogen to draw wallpaper but when i restart the komputer the qtile doesnt draw a wallpaper.
so i using screens to draw wallpaper with this code 
`wallpaper=wallpaper location`
and it work because it build in whith qtile
but i still want to draw wallpaper with autostart because i want to use systray and other . pls help me

oh by the way i found allot of bug when i type qtile -l ERROR or qtile -l DEBUG qtile-l INFO and more pls fix this. because i love using qtile because it base on python. my goal is to use all python application in this linux experimental build.
need solution for this problem fast

**Comment by jrwrigh** [comment]
Changing my `autostart.sh` to what you have is working fine on my machine, but I'm also not doing fully machine shutdown, so everything was already running correctly anyways. 

I normally have `nitrogen --restore; sleep 1; picom -b &` in my script, so possibly give that a shot.

**Comment by m-col** [comment]
Make sure that when you run `autostart.sh` manually that you aren't getting any errors, just to be certain that the error is in the script rather than how it's being called from Qtile. Also, if it helps at all, you can put those lines into `~/.xinitrc` and they'll be executed along with qtile itself and that'll work fine without any fiddling with subprocess in your config.
