### ISSUE TITLE
PulseVolume widget - missing module

### ISSUE THREAD

**Issue by JonBoyleCoding** [qtile/qtile#2472]
# Issue description

I've just installed qtile via git on Ubuntu 20.04.2 LTS and I'm getting an warning for the PulseVolume widget stating `No module named 'libqtile.widget._pulse_audio'`. This doesn't crash, it just shows `Import Error: PulseVolume` in the area it's supposed to display the widget.

This is working fine on my Arch install at home, so I figure it's something either related to Ubuntu or my config.

# Qtile version

b3875d9 as best as I can tell, literally just installed via `pip install git+https://github.com/qtile/qtile.git --upgrade`

# Stack traces

```
2021-05-18 13:11:19,198 WARNING libqtile utils.py:import_class():L159 Unmet dependencies for 'libqtile.widget.pulse_volume.PulseVolume': No module named 'libqtile.widget._pulse_audio'
```
# Configuration

```
from libqtile import widget

widget.PulseVolume()
```
The whole config file is huge, but this is essentially all I do. The widget is put into a list that then gets put into a bar.

**Comment by tych0** [comment]
Do you/did you have the pulse development headers installed when you built qtile? It's a cffi plugin, so it won't be built if you don't have those.

**Comment by JonBoyleCoding** [comment]
Indeed I did not - just redid and it's working now. Thanks!

**Comment by ajoino** [comment]
> Do you/did you have the pulse development headers installed when you built qtile? It's a cffi plugin, so it won't be built if you don't have those.

I think that all headers necessary to compile the built-in widgets should be included in the 'install from source' instructions. This bit me earlier and I it's annoying thing that can be prevented. Is it ok if I open an issue and PR for this?

**Comment by elParaguayo** [comment]
You're welcome to create a PR to update the docs.
