### ISSUE TITLE
feature request: cursor_warp only on keyboard commands

### ISSUE THREAD

**Issue by jrwrigh** [qtile/qtile#2474]
# Issue description

Make all actions of `cursor_warp` only occur when triggered from keyboard commands. ie. not from mouse actions.

The idea being that if you change focus using your mouse, you probably don't want your mouse to teleport across the screen. However, when you're changing focus using keyboard commands, it is probably desirable to have the cursor warp locations. i3 worked in a very similar way.

Note this behavior somewhat already works when using the mouse to change focus on windows in the same group:
![qtile_focus_change_20210519](https://user-images.githubusercontent.com/20801821/118827546-b5779a00-b879-11eb-98c5-d651d034be55.gif)

Excuse my ignorance on how exactly hardware inputs are handled on linux, but I think a way to do this would be to check/create a "log" of all keyboard and mouse inputs into the machine. When changing window focus, qtile could check the log to see whether the keyboard was just used, or the mouse and then choose whether to warp the cursor.

Some specific examples:
- Changing Group using the mouse by clicking the bar
    - The cursor movement is quite jarring as you just clicked something and then your mouse has suddenly disappeared
- Issues with Chromium refocusing too aggressively
    - See #990 
    - I believe this would be fixed by the proposed feature (though I'm not entirely sure)
- Closing a floating window on top of a different window
    - The change in focus after closing the floating window (with mouse) causes the mouse to warp. Again, fairly jarring experience

# Qtile version
0.17.0 (git hash not given, maybe should add to `qtile --version` output)

# Configuration
`cursor_warp = True`

**Comment by m-col** [comment]
I just submitted #2498 which deals with the GroupBox widget issue, which I think everbody would agree is bad.

I'm afraid I don't use Chromium so someone else might be better to comment on that one.

As for the third example, warping the cursor when focussing a window following closure of the focussed window... I'd agree this seems like unexpected behaviour but not certain everyone would agree. What do people think?

**Comment by jrwrigh** [comment]
Thanks for creating the PR fix. I've actually switched over to having `cursor_warp = False` and then having all context-switching keyboard shortcuts perform a cursor warp manually.

```python
def warp_cursor_here_win(win):
    if win is not none:
        win.window.warp_pointer(win.width // 2, win.height // 2)

def warp_cursor_here():
    '''warp the cursor to the currently focused window'''
    @lazy.function
    def _warp_cursor_here(qtile):
        win = qtile.current_window
        warp_cursor_here_win(win)
    return _warp_cursor_here

[...]

    EzKey('M-h', lazy.layout.left(), warp_cursor_here()),
```

It's not perfect by any means, since I can't figure out how to make the cursor warp to a newly opened application (via dmenu for example, it simply cursor-warps to the previous window) and there are a few functions in qtile that seem to automatically warp the cursor in some unexpected ways (see bottom of #2495).

**Comment by m-col** [comment]
No worries. I agree it certainly is strange behaviour to warp the pointer when
it's being used. I did wonder whether strictly using warping via keybindings
(i.e. whitelisting keybindings and defaulting to False otherwise) but it seems
much easier to specifically prevent warping upon the few actions where it
appears jarring, such as those you mention. If you think of other examples where
it happened that'd make sense to prevent then please let me know.
