### ISSUE TITLE
Odd behavior with group.cmd_toscreen and qtile.cmd_to_screen()

### ISSUE THREAD

**Issue by jrwrigh** [qtile/qtile#2477]
# Issue description

Using `qtile.cmd_to_screen(n)` or `qtile.focus_screen(n)` in a lazy function can sometimes revert focus back to the "original" screen after exiting the lazy function.

Example:

```python
def move_next_screen():
    @lazy.function
    def __inner(qtile):
        if len(qtile.screens) != 2: return
        i = qtile.screens.index(qtile.current_screen)
        j = 0 if i == 1 else 1

        if qtile.current_group:
            logger.warning(f'Move group "{qtile.current_group.name}" from screen {i}->{j}')
            qtile.current_group.cmd_toscreen(j)
            logger.warning(f'Sleeping...')
            time.sleep(2)
            logger.warning(f'After Sleep')

            # qtile.cmd_to_screen(j)
            qtile.focus_screen(j)
            time.sleep(2)

    return __inner
```
This will move the current group from screen `i` to screen `j`, then attempt to focus on the new screen (ie. keep the original group focused).

With the above code, I expect the following to happen (starting at `if qtile.current_group:`):
1. `current_group` is moved to screen `j` (`qtile.current_group.cmd_toscreen(j)`)
    - Screen `i` is still focused
2. Wait 2 seconds  (`time.sleep(2)`)
3. Focus on screen `j` (`qtile.focus_screen()`)
4. Wait another 2 seconds before exiting the function  (`time.sleep(2)`)
5. Screen `j` remains focused after function exit

**However, actual behavior has qtile changing the focus back to screen `i` on step 5**

I do have a solution to this (which is to focus on screen `j` first, and then move the group to screen `j`), but the screen focus changing after/upon exiting the lazy function seems like a bug to me.

# Qtile version

0.17.0

**Comment by jrwrigh** [comment]
The issue appears to be very similar to that mentioned in #1759 and #1778

**Comment by jrwrigh** [comment]
Note the mentioned solution does not work anymore. So

```python
def move_next_screen():
    @lazy.function
    def _move_next_screen(qtile):
        if len(qtile.screens) != 2: return
        i = qtile.screens.index(qtile.current_screen)
        j = 0 if i == 1 else 1

        if qtile.current_group:
            group = qtile.current_group
            logger.warning(f'Move group "{group.name}" from screen {i}->{j}')
            group.cmd_toscreen(j)
            logger.warning(f'Sleeping...')
            time.sleep(2)
            logger.warning(f'After Sleep')

            # qtile.cmd_to_screen(j)
            qtile.focus_screen(j)
            time.sleep(2)

    return _move_next_screen
```
***and***
```python
def move_next_screen():
    @lazy.function
    def _move_next_screen(qtile):
        if len(qtile.screens) != 2: return
        i = qtile.screens.index(qtile.current_screen)
        j = 0 if i == 1 else 1

        if qtile.current_group:
            group = qtile.current_group
            logger.warning(f'Move group "{group.name}" from screen {i}->{j}')
            qtile.cmd_to_screen(j)
            time.sleep(3)
            group.cmd_toscreen()
            time.sleep(3)

    return _move_next_screen
```

**Comment by jrwrigh** [comment]
I believe the previous issue is due to me turning off `cursor_warp` in my `config.py`. I've moved over to a more manual version of cursor warping to have better control over it's behavior, but that subsequently broke the above behavior.

So to fix the above, simply warp the cursor to the desired window. For some reason, that makes the focus switch back correctly. So:

```python
def warp_cursor_here_win(win):
    if win is not None:
        win.window.warp_pointer(win.width // 2, win.height // 2)

def move_next_screen1():
    @lazy.function
    def _move_next_screen1(qtile):
        if len(qtile.screens) != 2: return
        i = qtile.screens.index(qtile.current_screen)
        j = 0 if i == 1 else 1

        if qtile.current_group:
            group = qtile.current_group
            logger.warning(f'Move group "{group.name}" from screen {i}->{j}')
            group.cmd_toscreen(j)
            warp_cursor_here_win(group.current_window)
            logger.warning(f'Sleeping...')
            time.sleep(2)
            logger.warning(f'After Sleep')

            # qtile.cmd_to_screen(j)
            qtile.focus_screen(j)
            time.sleep(2)

    return _move_next_screen1

def move_next_screen2():
    @lazy.function
    def _move_next_screen2(qtile):
        if len(qtile.screens) != 2: return
        i = qtile.screens.index(qtile.current_screen)
        j = 0 if i == 1 else 1

        if qtile.current_group:
            group = qtile.current_group
            logger.warning(f'Move group "{group.name}" from screen {i}->{j}')
            qtile.focus_screen(j)
            time.sleep(2)
            group.cmd_toscreen()
            warp_cursor_here_win(group.current_window)
            time.sleep(2)

    return _move_next_screen2
```

I still get a flash after the `move_next_screen1()` function finishes, but the focus remains on the correct window at least. `move_to_screen2()` does not feature the screen flash.

**Comment by m-col** [comment]
Hi, sorry the bot is a bit trigger happy. What is the state of your issue atm? Looks like this issue flew under the radar a bit - sorry for that!

**Comment by jrwrigh** [comment]
Honestly, not sure. I figured out a workaround (explained in a previous comment), so I'm not sure if the issue still happens. 

I also remember the issue being intermittent, so  I'm not sure if I can reproduce it quickly/easily to verify that the behavior is still occurring.

**Comment by m-col** [comment]
OK, no problem. Please do re-open if you decide the workaround isn't adequate and the issue persists.
