### ISSUE TITLE
It looks like your cairocffi was not built with xcffib support

### ISSUE THREAD

**Issue by fmipsylone** [qtile/qtile#2478]
Hello,

Trying to install Qtile from sources on a "RPI 4 buster lite", I got the following error in Qtile build with cairocffi-1.2.0 installed with `pip`:
```
It looks like your cairocffi was not built with xcffib support.  To fix this:
  
    - Ensure a recent xcffib is installed (pip install 'xcffib>=0.5.0')
    - The pip cache is cleared (remove ~/.cache/pip, if it exists)
    - Reinstall cairocffi, either:
  
        pip install --no-deps --ignore-installed cairocffi
  
      or
  
        pip uninstall cairocffi && pip install cairocffi
  
  
  ----------------------------------------
  Failed building wheel for qtile
```
If I uninstall cairocffi installed from `pip` to use the debian package via:
```
pip3 uninstall cairocffi
sudo apt install python3-cairocffi
```
The `0.7.2` cairocffi version is installed on the system and Qtile builds correctly. 
In my tests the `python3-cairocffi` package installation did not add any missing dependencies. So all required debian packages dependencies are satisfied before 'cairocffi' install via 'pip'.

Does something changed with xcffib support ? Or is it mandatory to use `cairocffi` from a distribution package ? Does we need another debian package headers dependencies to build ?

Thanks you guys for your replies

**Comment by Fabien-Bernard** [comment]
Hello,
I remember reading similar error. Maybe this will help https://github.com/qtile/qtile/issues/2268#issuecomment-808918334

**Comment by fmipsylone** [comment]
Thanks you @Fabien-Bernard for your tip, this workaround works fine!
```
$ pip3 uninstall cairocffi
```
OR 
```
$ sudo apt remove python3-cairocffi
```
Then
```
$ pip3 install --no-cache-dir cairocffi
$ cd /home/pi/.local/lib/python3.7/site-packages
$ python3 cairocffi/ffi_build.py
$ cd qtile/
$ pip3 install .
```

**Comment by fmipsylone** [comment]
I close the issue because its source is not due to qtile but to the build of cairocffi.
