### ISSUE TITLE
Qtile freezes/crashes when only having firefox-beta and kitty (console) open

### ISSUE THREAD

**Issue by AndOrangutan** [qtile/qtile#2486]
# Issue description
Programs and qtile all freeze, and upon hitting ctr+mod+r everything graphically glitches out. Has happened multiple times,  and most times I only have firefox-beta-bin and a couple kitty terminals open. It doesn't happen instantly, instead anywhere from 20min to a couple hours after rebooting. Doesn't seem to have anything to do with number of pages in firefox (or load) or number of terminals. If I find a way to reproduce it on command, I will update this. Also the crash happened around 15:40 Still new to linux, but I did my best to problem solve this on my own first. 

# Qtile version
0.17.0-1

Commit: d6f3c14f9038b639bd3249fa7c0d4adb4e0c0a5d
installed on arch linux.

# Stack traces
xsession-errors is empty.

Cleared qtile.log not too long before the crash, but it should have its info.
[qtile.log.txt](https://github.com/qtile/qtile/files/6535461/qtile.log.txt)

[base.py.txt](https://github.com/qtile/qtile/files/6535493/base.py.txt)
[drawer.py.txt](https://github.com/qtile/qtile/files/6535501/drawer.py.txt)
[pangocffi.py.txt](https://github.com/qtile/qtile/files/6535506/pangocffi.py.txt)

# Configuration
[config.py.txt](https://github.com/qtile/qtile/files/6535465/config.py.txt)

**Comment by m-col** [comment]
My repo is telling me that that commit hash doesn't exist. Have you made custom changes to libqtile? Also, is that why you've posted base.py, drawer.py and pangocffi.py? The log suggests something is up with one of those files. If that is the case, please could you post a `git diff` showing just the changes? It is difficult to know which parts have changed with the whole file.

**Comment by 1-minute-to-midnight** [comment]
I also have the same problem with qtile on arch linux. Usually the crash occurs when youtube is the open website.

**Comment by AndOrangutan** [comment]
> 
> 
> My repo is telling me that that commit hash doesn't exist. Have you made custom changes to libqtile? Also, is that why you've posted base.py, drawer.py and pangocffi.py? The log suggests something is up with one of those files. If that is the case, please could you post a `git diff` showing just the changes? It is difficult to know which parts have changed with the whole file.

Oops, my bad. Still kind of new to GitHub and must have copied the wrong hash. I installed it off of the Arch repository, https://archlinux.org/packages/community/x86_64/qtile/, but I think that repo just is a list of dependencies and uses the lataest release. If that is the case,  I think that  this would be the hash:
6c4d0557124989d46ffb2bb24f4468db687fcdb2



> 
> 
> I also have the same problem with qtile on arch linux. Usually the freeze occurs when youtube is the open website.

I  think that might have been the case for me too now that you mention it as I have Firefox open all day, and no crashes. I was thinking that it was on qtile, since it was crashing too, but maybe it is some sort of graphics issue. 

The Firefox version I am currently on is 89.0b15-1, though I think it did update yesterday, so I would have to look up what came before.

Again, sorry for the mistake @m-col

**Comment by AndOrangutan** [comment]
May have figured something out. I somehow didn't have some graphics drivers for my intel integrated graphics. Don't have any quantitative evidence yet, but I haven't crashed yet. @1-minute-to-midnight are you sure that you have all your drivers installed? If you are using intel integrated graphics I would specifically read up on the Mesa package and the Intel-media-driver package.

**Comment by 1-minute-to-midnight** [comment]
Yes I have all the graphics drivers installed. And everything was fine until this week. No idea what changed. I haven't installed anything new or removed anything.

**Comment by AndOrangutan** [comment]
Never mind, false positive lol. Just got a similar crash same sort of deal

**Comment by 1-minute-to-midnight** [comment]
Practically unusable now with youtube. Currently using i3.

**Comment by AndOrangutan** [comment]
Mine isn't quite unusable, but there has been multiple times when I will be working on something just for it to crash without letting me save. I'll probably swap in a week if we can't figure out how to resolve it.

**Comment by m-col** [comment]
Could you try using git master and see if that fixes the issue? There have been a few bug fixes since that release so maybe it's actually resolved.

> Currently using i3 instead of qtile for the time being

This also supports it not being a driver issue if i3 works fine. @1-minute-to-midnight do you see the same or different log output?

@AndOrangutan have you made custom changes to the main codebase or just to your config? I'm not sure what can cause the `xcffib.XcffibException: Invalid connection.` but I think that is the primary issue. The `TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType` error can only happen if that object has been finalised, which only happens when Qtile begins to shut down. I think that is probably a side-effect of whatever the first issue is.

Sounds like you are in Arch... what's the output of `pacman -Qi xorg-server`?

**Comment by AndOrangutan** [comment]
No custom changes @m-col, just the config. Hopped over to the git master. 

Here is the `pacman -Qi xorg-server` output:

> Name            : xorg-server
> Version         : 1.20.11-1
> Description     : Xorg X server
> Architecture    : x86_64
> URL             : https://xorg.freedesktop.org
> Licenses        : custom
> Groups          : xorg
> Provides        : X-ABI-VIDEODRV_VERSION=24.0  X-ABI-XINPUT_VERSION=24.1  X-ABI-EXTENSION_VERSION=10.0
>                   x-server
> Depends On      : libepoxy  libxfont2  pixman  xorg-server-common  libunwind  dbus  libgl
>                   xf86-input-libinput  nettle  libpciaccess  libdrm  libxshmfence
> Optional Deps   : None
> Required By     : None
> Optional For    : None
> Conflicts With  : nvidia-utils<=331.20  glamor-egl  xf86-video-modesetting
> Replaces        : glamor-egl  xf86-video-modesetting
> Installed Size  : 3.65 MiB
> Packager        : Laurent Carlier <lordheavym@gmail.com>
> Build Date      : Tue 13 Apr 2021 08:12:10 AM PDT
> Install Date    : Fri 21 May 2021 04:24:44 PM PDT
> Install Reason  : Explicitly installed
> Install Script  : Yes
> Validated By    : Signature

**Comment by m-col** [comment]
Do you also see the crash on master?

**Comment by AndOrangutan** [comment]
@m-col, yup. While I haven't been able to use my laptop much over the past couple days, I did have one or two crashes still.

**Comment by m-col** [comment]
If you used Qtile on the previous release, did you ever come across this issue there? I wonder if it was introduced at some point.

**Comment by m-col** [comment]
So for some reason, `PangoLayout.finalize()` is being called when it shouldn't be, I think. It would be helpful to find out what is calling this. To do so, please could you stick these lines inside that method? Then when it happens, a traceback will be saved to this file and will hopefully give us some insight into what's going on.

```diff
diff --git a/libqtile/pangocffi.py b/libqtile/pangocffi.py
index 6bf904c7..06eefbbe 100644
--- a/libqtile/pangocffi.py
+++ b/libqtile/pangocffi.py
@@ -95,6 +95,9 @@ class PangoLayout:
         self._desc = None
         self._pointer = None
         self._cairo_t = None
+        import traceback
+        with open("/home/yourhome/pangofinalize.txt", "w") as f:
+            traceback.print_stack(file=f)
 
     def finalized(self):
         return self._pointer is None
```

**Comment by AndOrangutan** [comment]
I am pretty sure it was the same error before I swapped over to the git branch, though I was pretty new and was never on the previous release. 

Added those lines in, here is what I got after I crashed a second later. If I needed to restart the computer first, let me know, and I can send the next crash. Thanks again for working through this with me @m-col :)
```
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:798
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:798>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 799, in f
    self.core.flush()
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 409, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in _resize
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in <listcomp>
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 145, in length
    return int(self.calculate_length())
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 414, in calculate_length
    self.layout.width,
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    width = ffi.new("int[1]")
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
[ 06/07/2021 12:25:55.277 x_new_id FATAL ERROR ] We seems to have run of XIDs. 
```

**Comment by AndOrangutan** [comment]
Got another one, and the output was slightly different making me think the changes hadn't taken effect before the last crash, so hear you go:
```
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:790
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:790>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 791, in f
    func(*args)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 409, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in _resize
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in <listcomp>
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 145, in length
    return int(self.calculate_length())
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 414, in calculate_length
    self.layout.width,
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:790
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:790>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 791, in f
    func(*args)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 409, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in _resize
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 282, in <listcomp>
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 145, in length
    return int(self.calculate_length())
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 414, in calculate_length
    self.layout.width,
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
[ 06/07/2021 13:18:25.402 handle_queued_x_events FATAL ERROR ] X11 server connection broke (error 1)
```

**Comment by AndOrangutan** [comment]
Here is what got output into that "pangofinalize.txt":
```
 File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.17.1.dev315+g67f97604', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/main.py", line 55, in main
    options.func(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 232, in async_loop
    self.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 258, in finalize
    widget.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 211, in finalize
    self.layout.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 56, in finalize
    self.layout.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 100, in finalize
    traceback.print_stack(file=f)
```

**Comment by m-col** [comment]
So this looks interesting, but I realised this could also be output like this
when Qtile shuts down.  It's very strange because those `finalize` calls are
only done when Qtile is stopping, either to restart or to shutdown. Perhaps
something is trying to redraw the bar after one of these processes has begun,
but with the event loop stopped there isn't anything to actual handle that.

Was this output saved to file during the session but before shutdown/restart?
Because either of those would put this content in there.

**Comment by AndOrangutan** [comment]
No, I restart first, let me get you one before I restart next time. My bad. Didn't think of that, my bad.

**Comment by AndOrangutan** [comment]
Got the same output in the pangofinalize.txt, though I didn't delete or clear the file before if I was supposed to. Around this time I was reloading relatively often because I was customizing my bar.

**Comment by AndOrangutan** [comment]
I probably didn't think of this earlier because I didn't mess with anything but the config file, but I went ahead and fully uninstalled then reinstalled, and I HAVEN'T CRASHED SINCE :D. It could just be taking a while to crash, like it does sometimes. But unless I respond to this thread, it fixed it. Sorry to waste your time @m-col, I should have done that earlier.

**Comment by ramnes** [comment]
Let's go ahead and close it. :)

Please comment and we'll reopen if needed.
