### ISSUE TITLE
mouse_callbacks not working

### ISSUE THREAD

**Issue by Graeme22** [qtile/qtile#2487]
# Issue description
I cannot, for the life of me, get mouse_callbacks to work with any of my widgets. The goal is to run a bash script when the widget is clicked. However, it seems like qtile is simply not recording my clicks at all.

```python
widget.KeyboardLayout(fmt='  Keyboard: {}', background=colors[1], mouse_callbacks={'Button2': lambda: qtile.cmd_spawn('bash /home/graeme/.local/bin/togglekeyboard.sh')}),
```

I've also tried `lazy.spawn`, `subprocess.run`, `subprocess.call`, and using a non-lambda function. Nothing seems to work.

# Qtile version
0.17.0

# Stack traces
Nothing relevant was printed to the log.

# Configuration
https://github.com/Graeme22/dotfiles

**Comment by elParaguayo** [comment]
Have you tried having the callback write to the logfile e.g.
``` python
from libqtile.log_utils import logger
mouse_callbacks={'Button2': lambda: logger.info("Mouse callback - button 2 clicked")}
```
We need to see if callbacks are firing at all first.

**Comment by Graeme22** [comment]
> Have you tried having the callback write to the logfile e.g.
> 
> ```python
> from libqtile.log_utils import logger
> ...
> mouse_callbacks={'Button2': lambda: logger.info("Mouse callback - button 2 clicked")}
> ```
> 
> We need to see if callbacks are firing at all first.

Yup, nothing is logged, so they're not firing at all.

**Comment by elParaguayo** [comment]
Weird. Have you tried running`xev` in a terminal and see if it captures any
mouse events?

**Comment by Graeme22** [comment]
> > > Have you tried having the callback write to the logfile e.g.
> > > ```python
> > > from libqtile.log_utils import logger
> > > ...
> > > mouse_callbacks={'Button2': lambda: logger.info("Mouse callback - button 2 clicked")}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > We need to see if callbacks are firing at all first.
> > 
> > 
> > Yup, nothing is logged, so they're not firing at all.
> 
> Can you try with `logger.error` instead? Info logs are not included in the current default log level.

Good catch. Nope, still nothing in the logs.

**Comment by Graeme22** [comment]
Anyone able to reproduce? I wonder if this doesn't have to do with the config at all.

**Comment by elParaguayo** [comment]
No, can't recreate.

Just checked out `v0.17.0`, added the `Battery` widget and added a mouse callback to log a warning message. When I click on the widget, the message is printed in the log.

**Comment by Graeme22** [comment]
> No, can't recreate.
> 
> Just checked out `v0.17.0`, added the `Battery` widget and added a mouse callback to log a warning message. When I click on the widget, the message is printed in the log.
> 
> EDIT: Sorry, no idea why I tested the `Battery` widget, when you're not having issues with that one... Let me try `KeyboardLayout`.
> 
> EDIT 2: Callback works fine on `KeyboardLayout` too.

Hm. Let me start from a fresh config and see what happens.

**Comment by Graeme22** [comment]
Update: It is working just fine for me with the default config. So somehow, part of my config causes the callbacks to stop working. Let me see if I can narrow down what part.

**Comment by Graeme22** [comment]
This is really bizarre. I've traced it down, and it appears that the Wlan and KeyboardLayout widgets don't coexist. If I comment out my Wlan widget, everything works fine. But if I have both Wlan and KeyboardLayout in the bar, the callbacks stop working.

**Comment by Graeme22** [comment]
On the default config, it looks like Wlan and KeyboardLayout can coexist, so that's not it.

**Comment by Graeme22** [comment]
It seems like it has to do with the *number* of widgets. My base config has 23. Is there a hard limit on the number of `base.InPollLoop` widgets?

**Comment by Graeme22** [comment]
Here's a bit of an info dump.

### Minimal code to reproduce
Default config, but replace the widgets with:
```python
widget.CurrentLayoutIcon(),
widget.Spacer(length=5),
widget.TextBox(text='◣', fontsize=32, width=27, padding=-5),
widget.GroupBox(),
widget.TextBox(text='◣', fontsize=32, width=27, padding=-5),
widget.WindowName(),
widget.Spacer(),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.KeyboardLayout(fmt='  Keyboard: {}', configured_keyboards=['us', 'es', 'gr']),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.Battery(charge_char='+', discharge_char='-', full_char='', show_short_text=False, format='  Power: {char}{percent:2.0%}'),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.Volume(fmt='  Volume: {}'),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.CPU(format='  CPU: {freq_current}GHz {load_percent}%'),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.Memory(fmt='  RAM: {}'),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.Wlan(interface='wlp1s0', disconnected_message='  Disconnected', format='  Network: {essid}'),
widget.TextBox(text='◥', fontsize=32, width=27),
widget.Clock(format='  %A, %B %d %H:%M '),
```
This doesn't work on my system; however, if I comment out Wlan, for example, it works. I can also comment out Volume and it works.

### System info
- OS: Arch Linux x86_64
- Kernel: 5.12.6-arch1-1
- Resolution: 1920x1080
- WM: LG3D
- CPU: Intel Celeron J4115 (4) @ 2.500GHz
- GPU: Intel UHD Graphics 605
- Memory: 952MiB / 7770MiB

**Comment by elParaguayo** [comment]
Odd. I wouldn't have expected the number of widgets to have this impact.

What if you comment out one of the spacers i.e. is it the total number of
widgets that's causing the problem or is it the type?

**Comment by ramnes** [comment]
Could it be just a wrong offset calculation or alike, due to the bar being too crowded for the number of pixels it has?

**Comment by Fabien-Bernard** [comment]
In the list of widgets, I don't understand what is the use of the spacers() widget just after the windowname (they have both a stretched width). It's not that important that I understand, but I'd like to know what is the behavior if you remove it.

I start to believe it's a wrong offset calculation due to the number of stretched widgets.
The bar._resize method is still not obvious for me, but my main suspect for sure.
I think the second stretched widget as a wrong offset, which seems to "cover" more width than expected. Depending of the number of widgets after that second stretched widget, the keyboardlayout widget might or not be covered.

**Comment by Graeme22** [comment]
> In the list of widgets, I don't understand what is the use of the spacers() widget just after the windowname (they have both a stretched width). It's not that important that I understand, but I'd like to know what is the behavior if you remove it.

Yup, looks like it had to do with the `WindowName` and `Spacer` widgets combined. Somehow that messed up the offset once enough widgets were present.
Side note, I had no idea `WindowName` was a stretching widget, but looks like it's in the docs so that's on me.

> I start to believe it's a wrong offset calculation due to the number of stretched widgets.
> The bar._resize method is still not obvious for me, but my main suspect for sure.
> I think the second stretched widget as a wrong offset, which seems to "cover" more width than expected. Depending of the number of widgets after that second stretched widget, the keyboardlayout widget might or not be covered.

What I'm seeing matches up with this theory. The click events aren't working on the widgets next to the spacer, but they're working fine on the ones further away.

**Comment by Graeme22** [comment]
If y'all wanna just say "don't use spacer and windowname together" this issue can be closed, unless there's some wrong offset somewhere that needs to be addressed.

**Comment by ramnes** [comment]
Definitely sounds like something needs to be fixed anyway. :)

**Comment by Fabien-Bernard** [comment]
I used the logger for almost all the variables of this function to finally find a described pr :D
So, most of the current behavior comes from #1774.

If I understand right, the logic does not take into account the possibility of a block with a length superior to the interval.

In a case like this : Block1, Stretch1, Block2, Stretch2, Blooooooooooooooooooock3
the calculated length of Stretch2 is **negative** (~interval minus Block3), which makes the calculation of the following offsets wrong.
The consequence is that some widgets share the same space, therefore the inoperative mouse_callbacks.

One solution could be to fallback to the previous logic when a block is bigger than the interval.
All stretched widgets get equal width by sharing the space left by the non-stretched widgets.
We'll lose the centered effect, which in that case seems impossible to obtain anyway.

Last point that comes to my mind, I haven't read this part of the code yet, but it seems that at some point we tried (and succeeded?) to draw a widget with a negative length. To log something when that happens could be a fair addition too.

**Comment by elParaguayo** [comment]
Nice detective work!

With regard to losing the centred effect, this is something that does get asked quite a lot in the qtile-dev group so would be good to preserve it or find a new way of doing it if possible.

**Comment by Graeme22** [comment]
> Last point that comes to my mind, I haven't read this part of the code yet, but it seems that at some point we tried (and succeeded?) to draw a widget with a negative length. To log something when that happens could be a fair addition too.

Logging could make sense here, in my case that would've tipped me off that my config had two adjacent spacers which I didn't know nor want. However, I'd assume some people might want that behavior. Intuitively it seems like two adjacent widgets with width stretch should equally divide that space between them.
