### ISSUE TITLE
widget.CheckUpdates on Fedora: show the correct number of updates

### ISSUE THREAD

**Issue by Alteus** [qtile/qtile#2488]
widget.CheckUpdates on Fedora shows -2 updates when no updates found.

Excerpt from my config.py:
```
widget.CheckUpdates(
                     distro='Fedora',
                     display_format='  {updates} updates',
                     colour_have_updates=colors[3],
                     no_update_string='  no update',
                     update_interval=1800,
                     colour_no_updates=colors[5],
                     background=colors[8],
                     ),
```
# Qtile version
0.17.1dev
# distro
Fedora 34

**Comment by elParaguayo** [comment]
The widget should work by running `dnf list updates`, counting the number of lines and subtracting 3. So, if you're getting `-2` then there's only a single line output at the moment.

Run the command in a terminal and see what the output is.

**Comment by Alteus** [comment]
Correct. Only one line about last metadata check date.

**Comment by elParaguayo** [comment]
So the problem is not the widget.

**Comment by Alteus** [comment]
Last metadata expiration check date is a standard message, doesn't mean errors.
I think Fedora maintaners won't change the behaviour of dnf package manager for a Qtile widget.

**Comment by elParaguayo** [comment]
Ah. Fair enough. Said I didn't use Fedora!

Does that mean there are no updates?

If so, maybe we just change the widget so that, if there are fewer than the
minimum number, it treats it as no updates.

**Comment by elParaguayo** [comment]
Alternatively, can the metadata message be silenced? Could change the command that the widget runs.

**Comment by Alteus** [comment]
_"-q, --quiet
    In combination with a non-interactive command, shows just the relevant content. Suppresses messages notifying about the current state or actions of DNF."_

So, `dnf list updates -q` is what we are looking for.

**Comment by elParaguayo** [comment]
Excellent. Does it produce the same number of lines when there are updates (i.e. is it still correct to subtract 3?)

If it does work, can to submit the pull request with the fix?

**Comment by Alteus** [comment]
Needs some testing, I have a fully upgraded system atm. I have to wait for a few upgrades to land in the repos.
I think I'll be able to submit a PR with the fix.
