### ISSUE TITLE
[Wayland] Unable to use alacritty

### ISSUE THREAD

**Issue by Fabien-Bernard** [qtile/qtile#2502]
# Issue description
Using the wayland backend, I am not able anymore to launch alacritty terminal.
I launch it via lazy.spawn.

# Qtile version

the first bad : 7640c2e

# Stack traces

Nothing in qtile log.
2 console messages after exiting qtile : 
```
[EGL] command: eglMakeCurrent, erro: EGL_BAD_DISPLAY (0x3008), message: "Invalid display 0x557bcce34b30"
[render/egl.c:428] eglMakeCurrent failed
```
I don't have these messages when I removed the bar from the config, so I think it's not related.

# Configuration

The default config, minus a few widgets (Systray, WindowName and QuickExit).

**Comment by Fabien-Bernard** [comment]
If I remove this line : 
https://github.com/qtile/qtile/blob/7640c2eed46fd40b6408d4238e441c79df11c226/libqtile/backend/wayland/window.py#L89
that was added in this commit, the terminal opens again. It's far from perfect, the window looks more like a dropdown.
The exception raised : `RuntimeError("cannot use string() on <cdata 'char *' NULL>")`

**Comment by m-col** [comment]
> 2 console messages after exiting qtile

Yeah i also see a couple messages that look a bit like this, I'm not very knowledgable about EGL and rendering in general so I have my fingers crossed that someone else who understands this can help out :) or, failing that, I could ask the wlroots guys. For the time being I'm pretending these errors don't appear lol.

> The default config, minus a few widgets (Systray, WindowName and QuickExit).

Side question: does WindowName work? I don't think I've touched it, and I don't use it. I guess window names are a bit messy atm, right? Probably just <no name> all the time, possibly?

I'm also seeing the alacritty error, just investigating now. Seems it is doing something different with its name or class or something that I've gotta account for, and it's messing up some logic in `Match`, I think.

**Comment by m-col** [comment]
Oh, do you have https://github.com/qtile/qtile/commit/b3ccf9d1186d6a08b571b6f5895929a649aea91b, and if you didn't before, does it fix the issue?

**Comment by m-col** [comment]
It seems to work perfectly for me, changing groups via a keybinding makes the terminals unmap and map, and toggling between Max and Columns with a whole load of alacritties open seems to work as expected. What layouts are you using? I haven't made any changes, just on master.

**Comment by m-col** [comment]
My alacritty version is `alacritty 0.8.0 (a1b13e68)`, though I would imagine the issue is on our side and not theirs.

**Comment by Fabien-Bernard** [comment]
Same version of alacritty.
I used monadtall and max. Same problem for both. The terminal even cover my top bar.

So... It seems it comes from me, I will continue to investigate tomorrow, it may be late for my brain.
Once the issue is fixed, i will reactivate the windowname widget for your side question, good night.

**Comment by m-col** [comment]
Perhaps https://github.com/qtile/qtile/pull/2504 fixes it

**Comment by Fabien-Bernard** [comment]
It looks very promising Yes ! After a quick try, no sign of the weird previous behaviors, I will play with it a little bit and come back.
Thank you :)

**Comment by Fabien-Bernard** [comment]
I confirm that it is ok. This issue can be closed anytime for my part.

For the WindowName widget, each time I open a new terminal the widget first displays `<no name>`. If I change the focus or the group and come back, then the widget displays correctly "Alacritty". If I open firefox, the widget displays `<no name>` even after change. 
Weird thing about firefox, the window doesn't appear till I do something else. Or I am not patient enough, this one could be long to open. I might open a new issue in the next days about that.

**Comment by m-col** [comment]
OK, thanks for the info. Sounds the widget itself is fine but the `Window.name` bit needs a bit of work to make sure it gives the right thing as soon as it can do. Thanks!
