### ISSUE TITLE
lazy.spawn() broke icons in apps

### ISSUE THREAD

**Issue by DannyDies** [qtile/qtile#2520]
Hello!
When I make shortcut for vifm and run it doesn't show icons. 
![2021-06-09-164522_1366x768_scrot](https://user-images.githubusercontent.com/70198933/121367287-dc8a2e80-c942-11eb-8da6-79e2964b39a0.png)
But if I run it from terminal it works as it should.
![2021-06-09-164550_1366x768_scrot](https://user-images.githubusercontent.com/70198933/121367588-18bd8f00-c943-11eb-8166-0c5fe13b6544.png)
The same for rofi with unicode icons.
![2021-06-09-165919_1366x768_scrot](https://user-images.githubusercontent.com/70198933/121368930-1ad41d80-c944-11eb-9d21-183b1aa650af.png)
![2021-06-09-170047_1366x768_scrot](https://user-images.githubusercontent.com/70198933/121369150-4820cb80-c944-11eb-8652-226832b5be8d.png)

Term: alacrity, shell: zsh. 
I use this command for spawn
`    Key([mod], "e", lazy.spawn("alacritty -e vifm")),
`

**Comment by m-col** [comment]
Your shell is setting up some things in its environment that are letting these programs work correctly, but this isn't being done in the process that starts Qtile. You'll have to identify what those things are are set them in Qtile's environment too. Alternatively, you could pass `shell=True` to `lazy.spawn` which might work - not sure, untested.

**Comment by DannyDies** [comment]
@m-col I've tried before shell=True, also manually set the font for rofi in `lazy.spawn`, parse file to config and a lot of other stuff I can't even remember:D I've been struggling with this for the second day. I didn't find anything in Google and unfortunately I'm not a hacker enough to find out on my own. I just don't know how to run a program from qtile like from my work environment I would be grateful for any clue.

**Comment by DannyDies** [comment]
Solve it! Sorry for you time. If someone will encounter same issue.
I've created .sh script
`#!/bin/zsh
alacritty -e vifm
`
and passed that command
`zsh -i ~/vifm.sh`

And it work as it should. For rofi the same.

**Comment by m-col** [comment]
Ah you know why `shell=True` doesn't work? It runs it with `sh`, rather than checking what the user's default shell is. Might be worth doing that... not sure what is the appropriate thing there.

For your solution, you could probably do `alacritty -e "zsh -c vifm"`

**Comment by DannyDies** [comment]
@m-col sorry, didn't mension you. but I've tried both solutions before and it didn't work. Only this approach with script worked
