### ISSUE TITLE
[Request] Drawing a border on bar

### ISSUE THREAD

**Issue by lag00n** [qtile/qtile#2524]
# Issue description

I would like to know if there would be the possibility of adding an option that allows drawing an outer border on the bar. Unfortunately, I can't implement this myself because I'm kinda new to python, but I think that should be easy to do.

My idea was to create a border around the bar, which by default has the same color that the bar background and a default width. In that way, the user can change this on config.

Is there any way to do this?

Thanks in advance, 
\- lag00n

# Qtile version
v0.17.0  (latest one from git)

**Comment by elParaguayo** [comment]
Hi @lag00n,

It's been asked before (see #2115) and it's a little bit complicated.

I've been looking at adding widget decorations (which includes the ability to draw borders) - see #2473.

Adding a decoration to the bar won't currently work but it is on the list of things that I want to do.

So, to answer your question, no you can't do it yet but I hope to take a look at it soon.

**Comment by elParaguayo** [comment]
Closing in favour of #2115.

**Comment by lag00n** [comment]
I apologize for the inconvenience, I had not seen this request... Btw, these widget decorations are looking kinda great! I'm looking forward using them :D

Sorry for the lack of attention.
