### ISSUE TITLE
Mouse8 & Mouse9 (side buttons on mouse) are passed to firefox despite having a keybind assigned

### ISSUE THREAD

**Issue by IgnisFlamme** [qtile/qtile#2538]
# Issue description
Whenever I press Mouse8 or Mouse9, it is passed to firefox when it shouldn't. It should be intercepted and not passed on to applications. I have Mouse8 & Mouse9 bound to switching groups.

# Qtile version
0.17.0

# Configuration

Relevant code

```python
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front()),
    # Switch groups
    Click([], "Button9", lazy.screen.next_group()),    
    Click([], "Button8", lazy.screen.prev_group()),
]
```

**Comment by m-col** [comment]
Do you get any log output at startup about this?

**Comment by m-col** [comment]
Also run `xev` and see what kind of button code is created when you click these buttons.

**Comment by IgnisFlamme** [comment]
Well, its a bit late. I went back to KDE plasma. 

I used xev to check and yes. They do correspond to Button8 and Button9.

`ButtonPress event, serial 37, synthetic NO, window 0x3000001,
    root 0x19e, subw 0x0, time 76802340, (173,174), root:(1116,174),
    state 0x10, button 9, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x3000001,
    root 0x19e, subw 0x0, time 76802468, (173,174), root:(1116,174),
    state 0x10, button 9, same_screen YES

ButtonPress event, serial 37, synthetic NO, window 0x3000001,
    root 0x19e, subw 0x0, time 76802988, (173,174), root:(1116,174),
    state 0x10, button 8, same_screen YES

ButtonRelease event, serial 37, synthetic NO, window 0x3000001,
    root 0x19e, subw 0x0, time 76803100, (173,174), root:(1116,174),
    state 0x10, button 8, same_screen YES`

**Comment by nazar-pc** [comment]
I my experience all software methods have this bug one way or another, the better approach is to program the mouse itself on hardware level. Logitech mice support storing such settings in the device without any software required, I just remapped those buttons to keyboard combo and it works on any machine 100% of the time.
