### ISSUE TITLE
White glitch "thing' when characters overflow a bar

### ISSUE THREAD

**Issue by matheusfillipe** [qtile/qtile#2547]
# Issue description
![image](https://user-images.githubusercontent.com/24435787/121793002-7bc45580-cbd1-11eb-8405-abf0603104f7.png)

You can see on my bar there is some sort of weird white hover that happens when a TextWidget has a font that is too big or using pango and setting a bigger font, anything that makes characters overflow the bar seem to be causing that glitch.

It would be more ideal just to let it overflow cutting it out. This was working before like on here:
![image](https://user-images.githubusercontent.com/24435787/121793110-4b30eb80-cbd2-11eb-81fe-5e84a4f559d4.png)

I tried the older commit though where that was working but the glitch still happens so it could be something that updated on my system? I am not sure what it could be.

# Qtile version
0.17.1.dev340+g30ce930a

Not sure if this has anything to do with it:
```python
2021-06-12 22:50:47,280 ERROR libqtile base.py:on_done():L559 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 551, in on_done
    self.update(result)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 462, in update
    old_width = self.layout.width
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-06-12 22:50:47,280 ERROR libqtile base.py:on_done():L559 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 551, in on_done
    self.update(result)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 462, in update
    old_width = self.layout.width
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
```

**Comment by elParaguayo** [comment]
Matheus, thanks for submitting this. 

I'm not convinced those reports are related.

I'm working on a few things at the moment but I will take a look at this and see if I can recreate.

**Comment by ramnes** [comment]
Please share a minimal configuration to reproduce this, that would help. :)

**Comment by matheusfillipe** [comment]
@ramnes 
Well that wasn't easy! I tried reproducing on Xephyr but it doesn't happen there. It could be something else on my environment maybe. But it happens with simply having a character that is too big to fit in the bar and with a color gradient. This does not happen without a color gradient. Look on like 100 of this file, the interesting stuff starts there.
[config.py.txt](https://github.com/qtile/qtile/files/6679808/config.py.txt)

If you are still not able to reproduce here is a "weird" thing I have on my setup. I have dpi set to 110:

```
$ cat ~/.Xresources 
Xft.dpi: 110
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb

```
No idea if that could be related.

**Comment by matheusfillipe** [comment]
Well I realized it only happens with the foreground of characters when they overflow the bar. So most likely the gradient isn't being computed right when the character is bigger than the bar itself while the expected behavior would be having the color limits clamp to the bar height making it look seamless with other widgets/backgrounds.

**Comment by elParaguayo** [comment]
I'm not seeing the glitches with your test config. Those separators look the same to me.

**Comment by matheusfillipe** [comment]
This is how it is to me on that config:
![image](https://user-images.githubusercontent.com/24435787/123333324-fcf7e280-d517-11eb-935a-ad5b31ecf84f.png)

**Comment by elParaguayo** [comment]
The size difference of the separators is interesting. They're very different in mine compared to yours.

**Comment by matheusfillipe** [comment]
Yeah that is weird. This is what i used:
```python
        bottom=bar.Bar(
            [
                widget.GroupBox(background=colors[0]),
                widget.Prompt(background=colors[0]),
                widget.WindowName(background=colors[0]),
                # this smaller one is ok
                widget.TextBox(
                    text=separator,
                    background=colors[0],
                    foreground=colors[5],
                    padding=0,
                    fontsize=30,
                ),
                # This one glitches. It is whiter than the other:
                widget.TextBox(
                    text=separator,
                    background=colors[0],
                    foreground=colors[5],
                    padding=0,
                    fontsize=50,
                ),
                # This one makes it clear to see but it never glitches since it
                # is just background and no foreground
                widget.TextBox(
                    text="     ",
                    background=colors[5],
                    padding=0,
                    fontsize=40,
                ),
                widget.Spacer(
                    background=colors[0],
                ),
            ],

```

So the first is 30 and the second 50. I am really suspecting this is related to hiDPI now.

**Comment by matheusfillipe** [comment]
I tried with an empty ~/.Xresources and the size is still the same and the glitch is still there. Interestingly it works from within xephyr but not from X11.
