### ISSUE TITLE
Proper way to shutdown qtile and linux 

### ISSUE THREAD

**Issue by parasbhanot** [qtile/qtile#2551]
Hello everyone , 

i want to shutdown linux machine directly without shutting down qtile first. The way i am doing right now is by having shortcut using 
  
`Key([mod], "BackSpace", lazy.shutdown(), desc="Shutdown Qtile"),`  

in my config.py file . 

This only shuts down the window manager (qtile) and then i am presented with my login manager [lightdm] . 

Can i use following to do the complete linux shutdown using dmenu/direct shutdown command ?  ​

  ​` Key([mod], "e", lazy.spawn("shutdown now")),`

is  it  safe  to  shutdown   qtile  and  lightdm  from  terminal  ?

if not  what   is the  proper  way  to  shutdown  the  linux  directly  from  qtile  directly ?

My goal is having the shortcut key in qtile to do the complete linux shutdown .

**Comment by m-col** [comment]
Yeah that should work fine, I do the same with `systemctl poweroff`, it works fine

**Comment by elParaguayo** [comment]
Closing this as it seems to be answered but do reopen if you're still having issues.
