### ISSUE TITLE
The window name widget is showing state also

### ISSUE THREAD

**Issue by debarkamondal** [qtile/qtile#2569]
I am new to Qtile. I put a WindowName widget with format='{name}' still it shows the state

**Comment by elParaguayo** [comment]
Hi debarkamondal, welcome to Qtile.

I can't replicate that error. Using `format='{name}'` just displays the window name for me.

What version of qtile are you using? How did you install it?

Can you share your config file?

**Comment by debarkamondal** [comment]
I installed it via official arch repo 
qtile 0.17.0-1 is the version number.

**Comment by elParaguayo** [comment]
Thanks. I've tested it on that version and don't get the same result. Can you post your config file?

**Comment by debarkamondal** [comment]
[https://github.com/debarkamondal/.dotfiles/blob/main/.config/qtile/config.py](url)

**Comment by elParaguayo** [comment]
The widget behaves as it should for me on 0.17.0-1. Can't see any reason why it's not working for you.

I assume you've reloaded qtile since changing the config? The config file is read once when starting qtile. The state is shown in the default format so the only reason you'd still see this is if the default hasn't been overriden.

**Comment by debarkamondal** [comment]
Yes restarted even the whole system

**Comment by elParaguayo** [comment]
Tested your config on my system with 0.17.0 and don't get the state displayed. Just the window title as expected.

Is there any chance that qtile is loading a different config? Can't understand why it's not working for you.

**Comment by debarkamondal** [comment]
I myself am quite frustrated...

**Comment by elParaguayo** [comment]
Can you just check that your widget is loading properly by changing it to something like: `format='WINDOW NAME: {name}'` just to check that this is even being picked up properly?

**Comment by debarkamondal** [comment]
Sorry for the delay but it is working fine and showing any string i add explicitly perfectly fine.

**Comment by elParaguayo** [comment]
Great. Does that mean it's not showing the state now too? If so, I'll close this.

**Comment by debarkamondal** [comment]
It's showing whatever I hardcode extra... 
I mean it is still showing both the title and state along with the hard coded string

**Comment by elParaguayo** [comment]
Is it doing this for every window? I just don't see how the `state` can be displayed if it's not part of the window name.

**Comment by debarkamondal** [comment]
On mt browser it is showing the tab name, on terminal it is showing the directory i am in or the file i am editing

**Comment by elParaguayo** [comment]
That's the correct behaviour. Those are part of the window name (which is not the same as the application name).

The "state" is a symbol showing if the window is maximised, minimised etc

If you're just seeing the former then the widget is working as it is meant to.

**Comment by ramnes** [comment]
This discussion doesn't make sense. What is the output you're seeing and what is the output you would expect to see?

**Comment by debarkamondal** [comment]
Ok suppose i am in alacritty and run a command. Instead of showing "Alacritty" it is showing the command that is running like "sudo pacman -Syu"

**Comment by elParaguayo** [comment]
As above, none of that is the "state". There's really nothing here to suggest that the widget is not working exactly as it's meant to.

**Comment by debarkamondal** [comment]
Ohk i thought that it was supposed to show name only

**Comment by elParaguayo** [comment]
It will show whatever is included in the window name. Try running `xprop` and click on a window and you should see the same text in the `WM_NAME` field being shown in the widget.
