### ISSUE TITLE
QTile Autostart doesn't work

### ISSUE THREAD

**Issue by Mushwoom** [qtile/qtile#2570]
# Issue description
Hi. I've been playing around with qtile and i'm looking to make it my default. The only problem is is that autostart won't work. Here's the auto start hook in my config.py file:

> @hook.subscribe.startup
def autostart():
      home = os.path.expanduser('~/.config/qtile/autostart.sh')
      subprocess.call([home])

And here's what i have in my autostart

> #!/bin/sh
lxsession &
picom &
nitrogen --restore &
nvidia-settings &

I cannot understand where i went wrong, any help is appreciated

# Qtile version
qtile-0.17.0-1

# Configuration
In case anyone needs my whole config here it is [https://pastebin.com/BMiqrZUd](url)

**Comment by tych0** [comment]
Does autostart.sh have +x?

**Comment by Mushwoom** [comment]
> Does autostart.sh have +x?
> […](#)
> On Tue, Jun 22, 2021 at 11:26:46AM -0700, Mushwoom wrote: # Issue description Hi. I've been playing around with qtile and i'm looking to make it my default. The only problem is is that autostart won't work. Here's the auto start hook in my config.py file: > @hook.subscribe.startup def autostart(): home = os.path.expanduser('~/.config/qtile/autostart.sh') subprocess.call([home]) And here's what i have in my autostart > #!/bin/sh lxsession & picom & nitrogen --restore & nvidia-settings & I cannot understand where i went wrong, any help is appreciated # Qtile version qtile-0.17.0-1 # Configuration In case anyone needs my whole config here it is [[https://pastebin.com/BMiqrZUd](url)](https://pastebin.com/BMiqrZUd%5D(url)) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #2570

nope, i'm an idiot, it works now


thank you!

**Comment by ramnes** [comment]
We should probably write it somewhere though, I've seen a lot of people confused on this.
