### ISSUE TITLE
Wayland: incorrect mouse pointer

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#2585]
I've noticed that, when using the Wayland backend, I get the incorrect mouse pointer. It shows the "select text" pointer even when mousing over the bar.

Flagging this now but I'll see if I can I identify some steps to recreate this reliably.

# Qtile version

Seen on 50a4adf but was present before too.

**Comment by m-col** [comment]
Nice catch. From a quick test I noticed if I'm in `Max` and move the pointer from Firefox to my Bar it stays as an ugly icon set by Firefox. In my `Columns` there is a gap between Firefox and the Bar and the pointer is changed back to my nice pointer when it goes over the desktop. So it looks like the pointer is being restored to normal when it is not over a window, but it should do this either when it is not over a window _or_ it moves over a Bar. Is that consistent with what you're seeing?

**Comment by elParaguayo** [comment]
Ah, interesting.

Yes. If I'm in `Max` and open, say, an Alacritty terminal, I get the select text pointer. Moving to the bar doesn't change that pointer. However, if I do switch to another layout e.g. `MonadTall` then the pointer changes when it leaves the window.
