### ISSUE TITLE
Scratchpad alternates opening with and without focus

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#2588]
I'm seeing some slightly odd behaviour in my scratchpad (running Alacritty) where the alt key is not being respected. For exampled `alt`+`.` in a terminal would give me the last argument from the previous command and `alt` + number gives a different screen in `irssi`.

This occurs when the scratchpad window is visible but doesn't have focus.

If I toggle the scratchpad, it alternates having focus and not having focus. There needs to be another window open on the active group for this to happen.

This bug is present on latest master: d5425eeb

**Comment by elParaguayo** [comment]
Did some bisecting and it seems to be 41cadb19 that's the start of the issue. Before this, the scratchpad toggles ok and takes focus each time. After it, it alternates getting focus and not having it. 

However, with this one, the scratchpad appears when first toggled but isn't hidden when toggled again.

A bit more digging neede.

**Comment by m-col** [comment]
> If I toggle the scratchpad, it alternates having focus and not having focus. There needs to be another window open on the active group for this to happen.

Is this a separate issue from the alt key issue you describe? I can't reproduce on either x11 or wayland, scratchpad seems to work fine, even with alacritty. Possibly due to your configuration? The bisected commit is interesting, one line change in scratchpad.py and the commit pertains to pointer warping - suggesting it would be config related. However I changed around my `warp_pointer` and `follow_mouse_focus` options and still couldn't reproduce.

I also can't reproduce the alt issue.

**Comment by elParaguayo** [comment]
The alt issue seems to be because certain keypresses are being sent to the terminal (e.g. the `.`) but not the alt.

Interesting that you can't reproduce. Did you have another window open in the group?

**Comment by m-col** [comment]
I tried with other windows, changing the focus around - all seems fine. Do you
have a reliable step-by-step i could use?

**Comment by elParaguayo** [comment]
It was as simple as:
1) Open an Alacritty session (mod + enter)
2) Open scratchpad via toggle key (it has focus - cursor is solid white block)
3) Close scratchpad via toggle key
4) Reopen scratchpad via toggle (Alacritty has hollow white square cursor and `alt` + `.` doesn't work - just types a `.`)

**Comment by elParaguayo** [comment]
Tested with default config and this added at the bottom:
``` python
groups.append(ScratchPad("scratchpad", position=99, dropdowns=[
                DropDown("term", "alacritty",
                         on_focus_lost_hide=True),
                      ]),
          )

keys.extend([Key([], 'F12', lazy.group['scratchpad'].dropdown_toggle("term")),])
```
Get the same behaviour.

**Comment by elParaguayo** [comment]
Here's a video of the issue. Look at the cursor character each time the dropdown window opens:


https://user-images.githubusercontent.com/946265/124389896-27e4f200-dce1-11eb-92cc-634d2e761b7c.mp4


Does seem to be x11 only for me.

**Comment by elParaguayo** [comment]
I think this is Alacritty related. Closing this as I should be able to solve with a hook.
