### ISSUE TITLE
client_focus and focus_change hooks seem to mean the same thing

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2597]
# Issue description

There are two hooks with similar names: `client_focus` and `focus_change`. I can't tell what their distinction is conceptually.

We should either clarify the distinction (if there is one) or merge them.

# Qtile version

Master 55cc226

**Comment by yobleck** [comment]
It looks like client_focus takes a window object as an argument so a config could include
```
@hook.subscribe.client_focus
def my_func(window):
    print(window.window.get_name())
```
while focus_change doesn't take any specific argument and searching through the [code](https://github.com/qtile/qtile/search?q=focus_change) it mostly seems like it's used internally to trigger widget updates

**Comment by m-col** [comment]
Nice, the distinction is subtle but don't think we need to merge them. `client_focus` happens when, as per the name, a client is focussed, and hooked functions receive the window. `focus_change` is more broad and also fires when focus is changed in the absence of windows, for example by changing which group is on screen. I'll post a fix to clarify this in case anyone else gets confused, like me :)
