### ISSUE TITLE
Simplifying base widget call_process method

### ISSUE THREAD

**Issue by yobleck** [qtile/qtile#2607]
# Issue description
The current version of the base widget's call_process method:
https://github.com/qtile/qtile/blob/225cca581a1ec83a89f0e9bf5ed8d5dcca723750/libqtile/widget/base.py#L291-L299
could be simplified as:
```
  def call_process(self, command, **kwargs):
      """
          This method uses `subprocess.check_output` to run the given command
          and return the string from stdout, which is decoded when using
          Python 3.
      """
      return subprocess.check_output(command, **kwargs, encoding="utf-8")
```
The encoding option for subprocess was added in python 3.6: https://docs.python.org/3/library/subprocess.html#frequently-used-arguments

and appears to be nearly identical to the decode built in:
https://docs.python.org/3/library/stdtypes.html#bytes.decode

Is it worth making this change to eliminate the temporary variable and the extra method call?

## Qtile version
0.17 and current dev version (225cca581a1ec83a89f0e9bf5ed8d5dcca723750)

**Comment by m-col** [comment]
Sure! Could you send a patch? :smiley:

**Comment by ramnes** [comment]
Please save your time and don't open issues for minor code changes but PRs directly. :)
