### ISSUE TITLE
Volume widget showing mute only and not doing anything on input

### ISSUE THREAD

**Issue by debarkamondal** [qtile/qtile#2614]
I am using pipewire when i use pavucontrol i can access all the devices but the volume widget is stuck on mute and is not showing any value or doing any function like volume on scoll

**Comment by m-col** [comment]
Please post a config, version, and relevant log output as per the issue template

**Comment by debarkamondal** [comment]
Config: [Qtile config](https://github.com/debarkamondal/.dotfiles/blob/main/.config/qtile/config.py)
Version: 0.17.0-1
Log: Sorry to say but where to do I get a log file

**Comment by m-col** [comment]
The log is at ~/.local/share/qtile/qtile.log, check to see if anything 
is logged during startup and when you hit the keybinding / mouse button 
when you expect the actions to happen.

Probably worth updating too - 0.18.0 was released recently and might 
have fixed it.

**Comment by debarkamondal** [comment]
I think maybe the problem is somewhere else because alsamixer is no longer showing my sound card but it appears and works normally in pavucontrol

**Comment by Fabien-Bernard** [comment]
If you use pulseaudio, it seems interesting to emphasize the existence of the PulseVolume widget (as mentioned at the end of this thread : https://groups.google.com/g/qtile-dev/c/1ykdOEpsziw ).

**Comment by debarkamondal** [comment]
Sorry for the problem caused. But it is now working fine now that i have both pulseaudio and pipewire installed
