### ISSUE TITLE
Mouse clicks get Lost

### ISSUE THREAD

**Issue by mrossinek** [qtile/qtile#2622]
# Issue description

I am experiencing a very odd issue: randomly, mouse clicks appear to get lost..
After a random while, a mouse click will not get registered. This can result (e.g.) in a link in the browser not being clicked properly. I have to press `Esc` multiple times or restart qtile to get the mouse to register clicks again.

I can see this issue on two different machines:

1. Running Arch Linux:
    ```
    % uname -r
    5.12.14-arch1-1
    % pacman -Q xorg-server
    xorg-server 1.20.11-1
    ```

2. Running Fedora 33 (also using the X11 backend) [I don't currently have the detailed data here but it also uses the 5.12.* kernel]

# Qtile version

Compiled from master @ 839771fb0f0a281ac7c766bf2ab81a72241a7b43

# Stack traces

Unfortunately, I am unable to get any log messages from Qtile..
However, I found a more or less reliable way to test this issue is to run `xev` and continuously click. At some point, no more `ButtonPress` or `ButtonRelease` events will get registered.

I have bisected between v0.17.0 and latest master and found the first bad commit to be b2b1ed83e66ee093b8df9104df829b4e27528e42. Reverting it does indeed seem to fix things for me.

# Configuration

https://gitlab.com/mrossinek/dotfiles/-/blob/master/qtile/.config/qtile/config.py

**Comment by elParaguayo** [comment]
There's nothing in that commit about mouse clicks so I really don't see how that could cause the issue you're seeing it (and I'm not just saying that because it's my commit!).

Let me see if I can recreate the issue you're seeing.

**Comment by elParaguayo** [comment]
How many times do you have to click? I've been doing it for about the last 5 minutes and I'm not seeing any clicks that aren't being registered.

**Comment by mrossinek** [comment]
Usually the issue appears after less than a minute. But it being random it is really hard to say.
I agree that the commit is unrelated from mouse clicks (hence I am also confused) but I found it suspiciously reproducible during bisecting.. :/
I still need to check whether reverting this commit works in the long term. I will update this issue in a few days after daily driving but I wanted to open the issue in case anyone else sees something similar

**Comment by elParaguayo** [comment]
OK - let us know how you get on as I can't reproduce this issue.

**Comment by mrossinek** [comment]
Alright so I have been testing this on a daily basis and I have to say it really does feel like reverting the previously mentioned commit is a reliable way of avoiding the issue. Maybe I am experiencing some sort of a race condition on some update anywhere? But this is just a wild guess on what may be going on here..

Anyways, before writing this I wanted to test the latest `master` again real quick but that appears to be even more broken right now. Is that a known issue? Otherwise I can open another issue. A quick bisect leads to three potential bad commits:
- 95bc38c1f6d7763e7a2a53e859c6bedb28203b9f
- ceb070c4cb6e9d62ac8f6de745df9f4006181e2b
- 1fa18b23aa8a9529fda215b99cceab3c1685a329
One of these failed the CI. Two of them I had to skip during bisecting because they wouldn't even start up properly..

I can go into more details what the problem appears to be there if necessary but if you already know about potential issues I'll wait for a fix. FWIW, right now I am using master @ dff41d7 + revert of b2b1ed8 and that causes no issues :+1:

**Comment by mrossinek** [comment]
I have switched to latest master and will test-drive this for a while. I'll update you later next week :+1:

**Comment by mrossinek** [comment]
I have been daily driving the `master` branch for the past week and was still experiencing very weird behavior. Mouse clicks not being registered until pressing either `Esc` or `Ctrl+c` (and sometimes the `Super` key also fixed it), the screen not updating its contents at all or a general lack of responsiveness.

I was running qtile with `qtile start -l DEBUG` for two days but nothing useful was present in the logs. Merely tons of window name messages and output from my widgets.

I also noticed that qtile this trend becomes worse after being logged in (and therefore have qtile running) for >4 hours. A restart of qtile would then take considerably longer and the CPU consumption of qtile would sometimes spike. It also tends to accumulate significant virtual memory resources at times.

The most laggy experience I have is when trying to expand my widget box after a few hours. So maybe it is something to with [my config](https://gitlab.com/mrossinek/dotfiles/-/blob/master/qtile/.config/qtile/config.py)?

Anyways, I again reverted the commit `b2b1ed8` and that makes qtile at least usable for me. Although I still don't know why this would have such a huge effect...

**Comment by jwijenbergh** [comment]
Do you have the ability to test it with the wayland backend? Maybe it's a bug in the x11 backend or x11 itself? It is weird that reverting those commits helps for you though. Can you also try it with a default config so we can narrow things down?

**Comment by m-col** [comment]
> The most laggy experience I have is when trying to expand my widget box after a few hours. So maybe it is something to with my config?

I notice you have some transparency-related stuff and use picom. Considering b2b1ed8 pertains to transparency handling, perhaps there is a really bad memory leak or inefficient computation happening that's slowing everything down and resulting in all these weird side-effects. Maybe try removing alpha from any colours in your config and not using picom for a day and seeing if that makes a difference?

**Comment by elParaguayo** [comment]
That commit was really more focused on getting mirrors to work so there's no real transparency handling in it. I don't immediately see why it would cause the issues but can't argue with empirical evidence if reverting it fixes the problem!

Let me add a mirror to my config and see if my memory usage increases over time.

**Comment by elParaguayo** [comment]
I wonder if the memory leakage is a result of the `RecordingSurface` getting updates for all the widgets that are in the widgetbox but the surface is not being cleared.

Just a guess, will take a look.

**Comment by elParaguayo** [comment]
Yes - think this could be the issue. Clearing the surface only happens in `self.drawer.draw` but this is replaced by a no-op. However, the widget still goes through all the drawing steps.

A fix should therefore be to replace the no-op with a function that resets the `RecordingSurface`.

I can do a PR for this and would be good if @mrossinek can test it after that.

**Comment by elParaguayo** [comment]
@mrossinek - have a look at #2789

**Comment by mrossinek** [comment]
Awesome thanks a lot for looking further into this! I just pulled #2789 on one of my machines and an initial test seems to work well :+1: I will daily drive this for a few days and also pull it to my other machine tomorrow and daily-drive it there too.

I will update you later this week how things are going :+1:

**Comment by elParaguayo** [comment]
Great. Thank you.

**Comment by mrossinek** [comment]
Alright time to report:
- While #2789 does indeed resolve the memory leak as in I don't see an increased memory usage over time, my `WidgetBox` is very snappy and performance also does not degrade, it does *NOT* resolve the mouse clicks getting lost.
- I also disabled picom and removed the alpha channel from my `Bar.background` setting but this also does not fix this issue.

My logs started to contain the following error which, however, afaict is not noticable:
```
2021-09-16 08:41:11,996 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/libqtile/core/manager.py", line 234, in async_loop
    self.finalize()
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/libqtile/core/manager.py", line 272, in finalize
    self.core.finalize()
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 173, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/home/max/Installations/qtile/.direnv/python-3.9.6/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-16 08:41:12,000 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

**Comment by mrossinek** [comment]
> Do you have the ability to test it with the wayland backend? Maybe it's a bug in the x11 backend or x11 itself? It is weird that reverting those commits helps for you though. Can you also try it with a default config so we can narrow things down?

I cannot test the wayland backend but I can test things with the default config on Sunday.

**Comment by elParaguayo** [comment]
> Alright time to report:
> 
> * While [Fix memory leak with widgetbox #2789](https://github.com/qtile/qtile/pull/2789) does indeed resolve the memory leak as in I don't see an increased memory usage over time, my `WidgetBox` is very snappy and performance also does not degrade, it does _NOT_ resolve the mouse clicks getting lost.

Thanks for reporting. That widgetbox fix was only designed to fix the memory leak so I'm pleased to hear that it works.

**Comment by mrossinek** [comment]
I have made a **very** weird observation..
I started to try the default config and noticed that the issue does NOT persist in that case. This means, that it has to do with my config. Although I was not able to reproduce the issue with a minimal config (yet), I found that the `ThermalSensor` widget is what is causing _most_ of the problems. Removing it from my config, fixes the issue entirely.
I.e. commenting out [this](https://gitlab.com/mrossinek/dotfiles/-/blob/master/qtile/.config/qtile/config.py#L194) line.

However, I also found #2640 and have now been daily driving a local branch based on `v0.18.1` + #2789 + #2640 and with my config unchanged the issue is _mostly_ gone. I still loose a mouse click but only very rarily (two clicks in the past 36hours). That is something I can absolutely live with. I am still wondering what may be causing it though... :thinking:

**Comment by mrossinek** [comment]
I have no longer encountered any more mouse clicks being lost and I am still daily-driving a local installation with the two PRs mentioned in my previous comment merged. I saw that one of them just got merged so I just pinged the other one after which we should be able to close this :tada:

**Comment by elParaguayo** [comment]
#2640 has been merged now so, if you're happy, you can close this.

**Comment by mrossinek** [comment]
Awesome I just saw it too! :partying_face: 
I will update my installation to the main branch tonight or tomorrow, double check everything works as expected, and close this issue afterwards :+1:

**Comment by mrossinek** [comment]
Yep, seems good now! Thanks a lot to everyone here on helping to figure things out :slightly_smiling_face:
