### ISSUE TITLE
How can I remove my bar?

### ISSUE THREAD

**Issue by AnantGupta384** [qtile/qtile#2624]
# Issue description
Hey team, I was earlier using BSPWM. I am a pro (type of) in Python. I really like configuring in python. Just want to know that how can I remove my default bar, which is in the down. I don't use bar typically. So can I remove it. Thanks in advance.

# Qtile version
0.17.0

# Stack traces
NA

# Configuration
Not needed I guess

**Comment by ramnes** [comment]
Just remove it from your `Screen` definition, or set the `screens` configuration variable with an empty `Screen` if it's not set yet.
