### ISSUE TITLE
KeyChords get misinterpreted as keypresses

### ISSUE THREAD

**Issue by vhsdream** [qtile/qtile#2626]
# Issue description

I think since [this commit](https://github.com/qtile/qtile/commit/620d12d2d9189e2f76c21a697cd0e1ac60a1dc64), I have had strange behaviour when trying to use keychords. If I am trying to use a keychord that consists of three keypresses, the second keypress gets inputted into the window in focus. This is especially problematic if I am trying to grab a password from pass when I invoke 'passmenu' because the second keypress is put into the password field in a form, or invisibly through a terminal. I should note that the keychord still works, however. EDITED TO ADD: _some_ keychords work. Others do not at all.

# Qtile version

0.18.1.dev46+g8b78793f

# Stack traces

There is nothing in the logs that shows this happening. To repro you could run `tail -f .local/share/qtile/qtile.log`, make sure the terminal window is focused, and then do a keychord that you use in your config. If you have the issue then a letter or key or whatever should become visible in the tail. Relevant portion of config included below.

# Configuration

[link to my keys.py (gitlab)](https://gitlab.com/cnose/dotfiles/-/blob/master/.config/qtile/keys.py)

**Comment by elParaguayo** [comment]
There's a PR (#2625) to revert that commit but thanks for the report. Once that's merged it would be good if you can confirm that this issue is fixed.

@m-col FYI

**Comment by vhsdream** [comment]
Thanks! I can confirm that the revert (or a later commit) fixed the issue.
