### ISSUE TITLE
0.18.0: test/layouts/test_common.py::test_remove sometimes don't return

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#2628]
# Issue description
When running the test suite for 0.18.0 for the Arch Linux package, I ran into the issue of `test/layouts/test_common.py::test_remove` occasionally stalling forever.

It seems the tests are still doing something (but they never return).

# Qtile version

0.18.0

# Stack traces

n/a

# Configuration

n/a

**Comment by dvzrv** [comment]
This issue looks kind of familiar to what has been discussed here: https://github.com/qtile/qtile/issues/1130#issuecomment-673048205

**Comment by elParaguayo** [comment]
I got reliable builds on Arch with #2653 so I'll close this.
