### ISSUE TITLE
0.18.0: unable to run imapwidget related tests

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#2629]
# Issue description

When running the tests for 0.18.0 I came across a set of tests that always fail for me and I can't seem to get them to work.
I have reviewed https://github.com/qtile/qtile/blob/4f398189420b5020a4403a3556d4e4a98db38982/.github/workflows/ci.yml, https://github.com/qtile/qtile/blob/4f398189420b5020a4403a3556d4e4a98db38982/tox.ini and https://github.com/qtile/qtile/blob/4f398189420b5020a4403a3556d4e4a98db38982/setup.cfg to figure out the probable dependencies.
A lot has changed since 0.17.0 and the CI integration doesn't clearly distinguish between what is required for qtile to run/to be tested and what is required to build the additional dependencies (this is *very* time consuming).

```
FAILED test/widgets/test_imapwidget.py::test_imapwidget - ConnectionRefusedEr...
FAILED test/widgets/test_imapwidget.py::test_imapwidget_keyring_error - Conne...
FAILED test/widgets/test_imapwidget.py::test_imapwidget_password_none - Conne...
FAILED test/widgets/test_widget_init_configure.py::test_widget_init_config[ImapWidget-kwargs28]
===== 4 failed, 582 passed, 7 skipped, 27 deselected in 124.12s (0:02:04) ======
```

I have tried to use libgnome-keyring, kwallet + python-dbus, python-keyrings-alt in combination with python-keyring (which seems to be a dependency of the widget), all to no avail.
As I neither use e.g. gnome-keyring or kwallet nor could find information about how the expected setup in CI is handling this (e.g. running a dbus session?), I have no way of figuring out how to prepare the environment unfortunately.

# Qtile version

0.18.0

# Stack traces

Full build logs:
- [qtile-0.18.0-build.log](https://github.com/qtile/qtile/files/6835127/qtile-0.18.0-build.log) (python-keyrings-alt, python-fs, python-cryptodome)
- [qtile-0.18.0-build-kwallet.log](https://github.com/qtile/qtile/files/6835141/qtile-0.18.0-build-kwallet.log) (python-dbus, kwallet)
- [qtile-0.18.0-build-libgnome-keyring.log](https://github.com/qtile/qtile/files/6835147/qtile-0.18.0-build-libgnome-keyring.log) (libgnome-keyring)

In the latter two cases python-keyring seems unable to even find the backends (although they should be there).

# Configuration

n/a

**Comment by elParaguayo** [comment]
As per our IRC chat, I think this is failing because the monkeypatching isn't effective. Removing `python-keyring` from `checkdepends` makes the test pass.

Arch package is skipping this test but we should make sure this is fixed for future releases.
