### ISSUE TITLE
Script access to key mapping 

### ISSUE THREAD

**Issue by nekojess** [qtile/qtile#264]
From what I can see, you can't nicely add/remove/disable key maps after configuration is loaded. I figure it would be lovely to be able change them dynamically, and via scripting. 

I haven't had a whole lot of time looking at the code, so I'm not entirely sure how easy this would be. I figure it would be easiest to put all/most the key handling code in a new KeyManager class, and that class can have an interface for scripting. Maybe they can show up under a keys/ group, e.g. "keys/mod1-a". 

Just a thought.

**Comment by zordsdavini** [comment]
suggest to close in favor to https://github.com/qtile/qtile/issues/1661

**Comment by ep12** [comment]
Wouldn't close this issue, they are fundamentally different...

**Comment by zordsdavini** [comment]
But if we will have configuration to do some magics then access and change on the fly (what should be configured, too) should not be needed, I think.

**Comment by ep12** [comment]
I am not sure about this. Maybe @nekojess wants to do some really fancy stuff that you can't even do with `lazy.function` in a relatively trivial way (by that I mean that it is simpler to modify qtile than to write a server-like interface adding a second key handling layer effectively). So let's keep both issues open and you can discuss this issue and maybe close it if you want to, but making key bindings scriptable is really something new...!

**Comment by m-col** [comment]
This would require very changes to work, I think. All it takes for a keybinding to be registered is to define it and pass it to `Qtile.grab_key`:
```py
from libqtile import qtile
key: Key  # This is your defined Key object

qtile.grab_key(key)  # This will register it

qtile.ungrab_key(key) # This will unregister it
```
Prefixing those methods with `cmd_` would expose them to client interfaces. Does the Python client interface allow for passing things like `Key`s to the server?
