### ISSUE TITLE
Cairo-dock not showing in desktop with 0.18.0-2

### ISSUE THREAD

**Issue by GoVi-48** [qtile/qtile#2642]
# Issue description
Description in title

# Qtile version
0.18.1.dev0+g8e7ecc0a.d20210719

# Stack traces
[xsession-errors.log](https://github.com/qtile/qtile/files/6860109/xsession-errors.log)
[qtile.log](https://github.com/qtile/qtile/files/6860103/qtile.log)

# Configuration
[config.py.log](https://github.com/qtile/qtile/files/6860119/config.py.log)
[xinitrc.log](https://github.com/qtile/qtile/files/6860115/xinitrc.log)

**Comment by m-col** [comment]
I can reproduce. Seems to be these errors:
```
2021-07-22 06:34:09,680 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 258, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)
xcffib.xproto.ValueError
2021-07-22 06:34:09,681 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 258, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)
xcffib.xproto.ValueError
```

Anyone know what causes this? @elParaguayo did these errors crop up during the transparency work?

**Comment by elParaguayo** [comment]
Have bisected. Seems to be this commit: 689d142689

**Comment by m-col** [comment]
@GoVi-48 would you be able to test it with this patch? I think it might fix it.
```diff
diff --git a/libqtile/backend/x11/window.py b/libqtile/backend/x11/window.py
index 1a4c1b95..48be04e3 100644
--- a/libqtile/backend/x11/window.py
+++ b/libqtile/backend/x11/window.py
@@ -1387,6 +1387,7 @@ class Window(_Window, base.Window):
             self.group.remove(self)
         s = Static(self.window, self.qtile, screen, x, y, width, height)
         self.qtile.windows_map[self.window.wid] = s
+        self.unhide()
         hook.fire("client_managed", s)
 
     def tweak_float(self, x=None, y=None, dx=0, dy=0,

```

**Comment by GoVi-48** [comment]
@m-col
Didn't work for me

**Comment by nazar-pc** [comment]
I think I'm having similar issue with tint2 and polybar, they just don't render anything on them.

**Comment by elParaguayo** [comment]
Are you able to confirm that it's the same commit that's responsible?

**Comment by nazar-pc** [comment]
I can try to revert that commit if it is self-contained

**Comment by elParaguayo** [comment]
Confirmed it's the same commit for `tint2`. Not checked `polybar` but it's looking likely.

**Comment by ritik-ghanshani** [comment]
Hey, I just switched from Xmonad to Polybar and I have the same issue. Any updates on this?

**Comment by m-col** [comment]
I think 3187b0c23a6dbe9b93ec2fd1473e59b84a74888e fixed this. Anyone able to confirm?

**Comment by elParaguayo** [comment]
Sorry to be bearer of bad news but I don't think this fixes it.

Tried running `tint2` and got this:
![20210824_075008](https://user-images.githubusercontent.com/946265/130570250-8e7a85c2-e211-4529-b4c5-e3051986e7b1.png)

`xprop`:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 788938160, 22057
		program specified minimum size: 1920 by 30
		program specified maximum size: 1920 by 30
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 1919
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 30
WM_CLASS(STRING) = "tint2", "Tint2"
XdndAware(ATOM) = ATOM
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_NET_WM_PID(CARDINAL) = 23091
_NET_WM_ICON_NAME(UTF8_STRING) = "tint2"
_NET_WM_NAME(UTF8_STRING) = "tint2"
WM_ICON_NAME(STRING) = "tint2"
WM_NAME(STRING) = "tint2"
```

**Comment by m-col** [comment]
OK, looks like my solution doesn't quite work for all programs. I'll find a better one. But we're getting somewhere, if it's showing at all!

**Comment by elParaguayo** [comment]
Sorry, yes, I should have said that this was an improvement as I could now see something!

**Comment by m-col** [comment]
Alright this one is better: https://github.com/qtile/qtile/pull/2713

**Comment by elParaguayo** [comment]
It's certainly _better_ but not quite there...

When I open it, the bar is drawn on the top of the screen but a gap is created at the bottom where it expects the bar to be (opening tint2 in v0.17.0 draws the bar at the bottom).

![20210824_113958](https://user-images.githubusercontent.com/946265/130602903-a3a0a643-1b3a-491e-bd68-ea168c2fc6c5.png)

**Comment by m-col** [comment]
OK! How about now? :D

**Comment by elParaguayo** [comment]
Boom!

![20210824_114843](https://user-images.githubusercontent.com/946265/130604015-d9cc7d6d-4ef3-42c6-9dfa-ffd9cea89fdb.png)

**Comment by nazar-pc** [comment]
Interestingly yes, it does work properly on `master`, so the issue is fixed. Any chance to get a patch release to `0.18.x` series soon?

**Comment by m-col** [comment]
Awesome! Good idea, I think we have a bunch of bug fixes that could do with going out.
