### ISSUE TITLE
Padding not working for specific widgets

### ISSUE THREAD

**Issue by cysea** [qtile/qtile#2643]
# Issue description

Adding `padding` or `max_chars` to widgets like CPU or Net doesn't format properly and still keeps moving the entire statusbar.

![Peek 2021-07-22 13-09](https://user-images.githubusercontent.com/59068073/126630125-716fe55c-2fc5-4118-be1d-92df38be36e4.gif)

^^^ See how the left border of theNet widget is bouncing around? ^^^

# Qtile version

```
$ qtile --version
0.17.0
```

# Configuration

```
...SNIP...

widget.Net(
            interface = "enp0s31f6",
            format = '{down} ↓↑ {up}',
            use_bits = True,
            padding = 4,
            foreground = colors_b[0]
            ),

vline_sep(),

widget.TextBox(
            text = " ",
            padding = 2,
            fontsize = 24,
            foreground = colors_b[1],
            ),
widget.TextBox(
            text = "CPU: ",
            foreground = colors_b[1],
            ),
widget.CPU(
            format = '({load_percent}%)',
            foreground = colors_b[1],
            ),
widget.ThermalSensor(
            threshold = 90,
            padding = 8,
            foreground = colors_b[1],
            ),

...SNIP...
```

**Comment by elParaguayo** [comment]
That's not what `padding` does. It is a gap between the edge of your widget and the widget's contents. That remains constant.

What is changing is the length of the text that you're trying to display. If you don't want the widget to change size then you should use a monospace font and then set the string length in the format string, e.g.
``` python
format = '{down:8s} ↓↑ {up:8s}'  # Set minimum length of up and down strings to 8 characters
```

**Comment by cysea** [comment]
This seems to be what I was looking for. Thank you!
