### ISSUE TITLE
Allow defining named KeyChords for Chord widget without setting it up as a mode

### ISSUE THREAD

**Issue by Infinidoge** [qtile/qtile#2647]
# Issue description (Feature request)

When creating a KeyChord, specifically with use of the Chord widget, I've noticed that the only way to display something with the Chord widget is to set the KeyChord up as a mode. It would be ideal to be able to name a KeyChord for display in that widget, without having the "Keep mode until Escape is pressed" functionality. 

(In my case, I would find this useful for distinguishing if I have accidentally entered a key chord, or to signify a more 'dangerous' key chord such as power management)

**Comment by Infinidoge** [comment]
I looked through the documentation to see if this was possible to implement through a subclass of KeyChord or the Chord widget, and it seems like it *might* be possible, but I'm not sure how modes are implemented currently, and am not sure how to make a version of KeyChord with it removed.

**Comment by elParaguayo** [comment]
Have a look at #2723

**Comment by ValentinLeTallec** [comment]
Looks good, thanks :smile:

**Comment by Infinidoge** [comment]
This comment is to remove the stale label, attached PR was also marked as non-stale.

**Comment by Infinidoge** [comment]
:tada:
