### ISSUE TITLE
Prompt widget doesn't support capslock

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#265]
Shift works, capslock is ignored.

**Comment by aniruddhkanojia** [comment]
Cannot reproduce this bug.

**Comment by flacjacket** [comment]
This may be fixed by #943, if it is confirmed we can close it

**Comment by dequis** [comment]
Yep, works! Thanks!

**Comment by flacjacket** [comment]
```
Jan 31, 2013
```
Nice to clear this one out

**Comment by jiiiijiij** [comment]
9 years later and I run to this problem :((
