### ISSUE TITLE
No Display Set Error

### ISSUE THREAD

**Issue by christopherbui** [qtile/qtile#2652]
I have tried various window managers, gdm, sddm, lightdm in addition to xinit. Qtile will not start. In tty prompt when I tried launching it through xinit, it gives the error "No Display Set". It seems that various window managers cannot set the Display variable for Qtile?

I have tried this on arch and ubuntu. Both distros failed to launch Qtile.

I would appreciate any help regarding this issue. Does anyone have the same problems?

**Comment by christopherbui** [comment]
It appears that after a fresh install of arch linux, pacman -S qtile will install version 0.18, but it does not install all the dependencies as compared when installing 0.17 via pacman -U https://archive.archlinux.org/packages/qtile/qtile-0.17.0-1-x86_64.pkg.tar.zst

**Comment by elParaguayo** [comment]
What dependencies are missing? I'm not talking about differences between 0.17 and 0.18 as there were some changes. I'd like to know what you think is missing to get qtile to start (if you've managed to start it).

**Comment by elParaguayo** [comment]
Also, have a look at https://github.com/qtile/qtile/pull/2653

I'm working on updating the PKGBUILD for Arch (NB I'm not the packager for this) and have added some more dependencies and removed some.

**Comment by elParaguayo** [comment]
@christopherbui are you still having issues or can we close this?

**Comment by christopherbui** [comment]
There seems to be a major difference in dependencies when installing 0.17 vs 0.18. 0.17 offers more packages that 0.18 might need, but are not provided in the package build for some reason. I'll show you what is shown when installing 0.17 vs 0.18

**Comment by christopherbui** [comment]
│ File: qtile17.txt
───────┼────────────────────────────────────────────────────────────────────
   1   │ sudo pacman -U https://archive.archlinux.org/packages/q/qtile/qtile
       │ -0.17.0-1-x86_64.pkg.tar.zst
   2   │ 
   3   │ [sudo] password for alphard: 
   4   │ 
   5   │ loading packages...
   6   │ resolving dependencies...
   7   │ looking for conflicting packages...
   8   │ 
   9   │ Packages (13) python-appdirs-1.4.4-3  python-cairocffi-1.2.0-3
  10   │               python-cffi-1.14.6-1  python-more-itertools-8.8.0-1
  11   │               python-ordered-set-4.0.2-3  python-packaging-20.9-1
  12   │               python-ply-3.11-7  python-pycparser-2.20-3
  13   │               python-pyparsing-2.4.7-3  python-setuptools-1:57.4.0-
       │ 1
  14   │               python-six-1.16.0-1  python-xcffib-0.11.1-1  qtile-0.
       │ 17.0-1
  15   │ 
  16   │ Total Installed Size:  13.01 MiB

**Comment by christopherbui** [comment]
**0.18**
```
sudo pacman -S qtile

resolving dependencies...
looking for conflicting packages...

Packages (7) python-cairocffi-1.2.0-3  python-cffi-1.14.6-1
             python-ply-3.11-7  python-pycparser-2.20-3
             python-six-1.16.0-1  python-xcffib-0.11.1-1  qtile-0.18.0-2

Total Download Size:   0.56 MiB
Total Installed Size:  9.08 MiB
```

**Comment by m-col** [comment]
Looks like it's just some extra dependencies introduced by the way it was being packaged:
```
$ pacman -Qi python-setuptools
...
Depends On      : python-appdirs  python-more-itertools  python-ordered-set  python-packaging  python-pyparsing
...
```

How were you running it with xinit?

**Comment by christopherbui** [comment]
> Looks like it's just some extra dependencies introduced by the way it was being packaged:
> 
> ```
> $ pacman -Qi python-setuptools
> ...
> Depends On      : python-appdirs  python-more-itertools  python-ordered-set  python-packaging  python-pyparsing
> ...
> ```
> 
> How were you running it with xinit?

Through my display manager SDDM. I've tried installing qtile on a separate machine, clean arch install and all. The problem still persists.

**Comment by cybernarius** [comment]
Had the same issue today and what fixed it for me:
1. Install **mypy** and run **qtile check**
2. Fix issues in config file
All done, hope it helps

**Comment by christopherbui** [comment]
> Had the same issue today and what fixed it for me:
> 
>     1. Install **mypy** and run **qtile check**
> 
>     2. Fix issues in config file
> 
> 
> All done, hope it helps

Thanks! I've been running 0.17 for the time being, but when I upgrade to 0.18, I'll keep this in mind if/when the issue persists.
