### ISSUE TITLE
List xvfb and tox as dev dependencies?

### ISSUE THREAD

**Issue by yobleck** [qtile/qtile#2655]
I've been having trouble getting tests up and running locally. Most of it is just my lack of knowledge, 
but I was able to make a number of error messages go away by installing tox and xvfb.
Should they be listed as dependencies?

**Comment by elParaguayo** [comment]
You don't need tox but xvfb is required.

Have a look at: 
 - http://docs.qtile.org/en/latest/manual/install/index.html#core-dependencies
 - http://docs.qtile.org/en/latest/manual/hacking.html

I've also been trying to work out the minimum requirements for running tests in Arch. See https://github.com/qtile/qtile/pull/2653

**Comment by m-col** [comment]
On Mon, Jul 26 2021 at 23:25:11 -0700, elParaguayo 
***@***.***> wrote:
> xvfb

Does xvfb need to be added to that core deps table or is it typically 
pulled in by the X server?

**Comment by elParaguayo** [comment]
It's a requirement for tests, not for running qtile so shouldn't be in your core deps list but should be in the tests list.

**Comment by m-col** [comment]
Oops sorry, I did mean test deps. Looks like it isn't there, so I guess it should be added then?
