### ISSUE TITLE
Restart hook forgets state of global variables

### ISSUE THREAD

**Issue by FF-AntiK** [qtile/qtile#2660]
# Issue description

I have my own two compositing scripts. One to start compositing and one to stop.
Within the Qtile hooks I maintain a global state which tells if compositing is currently running or not.
Whenever a full-screen window is shown on the screen, I stop compositing.
Whenever I leave full-screen, I start compositing again.

Of course, when I `lazy.restart()`, the global compositing state initializes to False.
I guess this is because the `config.py` is completely rerun.

To prevent running my start compositing script more than once before stopping it,
I run the stop script inside the Qtile restart hook.

The problem is, that inside the restart hook, my global compositing state is already forgotten.
It's hard to explain, see my config below.

# Qtile version

`0.18.1.dev67+gcdf8c382`

# Stack traces

```
2021-07-28 09:00:37,625 WARNING libqtile config.py:startcomp():L262 startcomp
2021-07-28 09:00:49,126 WARNING libqtile config.py:on_restart():L298 compositing state: False
```

# Configuration

```python
compositing = False


def startcomp():
    global compositing
    if not compositing:
        logger.warning("startcomp")
        subprocess.call(["/home/antik/.local/bin/startcomp"])
        compositing = True


def stopcomp():
    global compositing
    if compositing:
        logger.warning("stopcomp")
        subprocess.call(["/home/antik/.local/bin/stopcomp"])
        compositing = False


@hook.subscribe.client_focus
def on_client_focus(window):
    if window.fullscreen:
        stopcomp()
    else:
        startcomp()


@hook.subscribe.focus_change
def on_focus_change():
    if qtile.current_window:
        if qtile.current_window.fullscreen:
            stopcomp()
        else:
            startcomp()
    else:
        startcomp()


@hook.subscribe.restart
def on_restart():
    global compositing
    # Compositing state is always False, even if startcomp() was called.
    logger.warning("compositing state: {}".format(compositing))
    # Force stopcomp() by manually setting global compositing state.
    compositing = True
    stopcomp()
```

**Comment by elParaguayo** [comment]
Don't know if this will change anything but there's a PR #2360 which changes how restarting works. Given it still reloads the config, you may still have the same issue but it might be worth a look.

**Comment by FF-AntiK** [comment]
Thanks for the hint @elParaguayo.
I'm not that used to python, but I have the impression that the restart hook is called after Qtile has been restarted.
This would make it inappropriate for any cleanup code.

But the docs state: "Called before qtile is restarted"
http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.restart

I've also tried the shutdown hook, but it's not called on `lazy.restart()`

**Comment by FF-AntiK** [comment]
Maybe in the end it would be wiser to daemonize my compositing script and implement some IPC.
This way I wouldn't rely on the runtime characteristics of Qtile.

**Comment by elParaguayo** [comment]
If the global variable is being reset, you could just write a value to a file instead and read it whenever you need to. That would survive restarts.

**Comment by FF-AntiK** [comment]
Thanks @elParaguayo.
I guess I close this then, because it seems to make more sense to fix this on my side.

**Comment by elParaguayo** [comment]
Thanks for closing (and I agree it's something you can fix on your side). I appreciate you said you're not that strong at python but I would expect there to be plenty of examples on StackOverflow of checking whether processes are running which should help you.

Good luck.

**Comment by FF-AntiK** [comment]
I solved it with systemd user services.
Systemd now tracks for me if compositing is running or not.
Inside the Qtile hooks I only start / stop the service.
