### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/muhammad/.config/qtile/autostart.sh'

### ISSUE THREAD

**Issue by ussak12** [qtile/qtile#2664]
# Issue description

my autostart doesnt work
`PermissionError: [Errno 13] Permission denied: '/home/muhammad/.config/qtile/autostart.sh'`

# Qtile version

0.18.1.dev0+g8e7ecc0a.d20210719

# Stack traces

qtile.log:
`PermissionError: [Errno 13] Permission denied: '/home/muhammad/.config/qtile/autostart.sh'`

# Configuration
config file:
```
import os
import subprocess

@hook.subscribe.startup
def autostart():
    home = os.path.expanduser('~')
    subprocess.Popen([home + '/.config/qtile/autostart.sh'])
```

autostart file: 

```
#!/usr/bin/env bash

#setxkbmap dk
nitrogen --restore &
picom -b -c & 
```

**Comment by tych0** [comment]
chmod +x it.

**Comment by ussak12** [comment]
ok it is fixed.
