### ISSUE TITLE
Toggle fullscreen option doesn't do anything

### ISSUE THREAD

**Issue by HiroiOwO** [qtile/qtile#2672]
# Issue description

When I try to use the lazy.window.toggle_fullscreen() option nothing happens when it should put my focused window in and out of fullscreen mode over the other open windows, I really need this feature to make my workflow work better since it's easier to work with a lot of windows open at the same time like this

# Qtile version

0.17.0 

# Configuration
https://pastebin.com/m3nEaWqf

**Comment by m-col** [comment]
You need to put the toggle_fullscreen `Key` inside your `keys` list.

**Comment by HiroiOwO** [comment]
I didn't notice, thank you for pointing it out, btw fullscreen is fine, but is there a way to just make one window take the whole screen while still seeing the bar?

> You need to put the toggle_fullscreen `Key` inside your `keys` list.
> […](#)
> On Sun, Aug 1 2021 at 07:04:03 -0700, HiroiOwO ***@***.***> wrote: Issue description When I try to use the lazy.window.toggle_fullscreen() option nothing happens when it should put my focused window in and out of fullscreen mode over the other open windows, I really need this feature to make my workflow work better since it's easier to work with a lot of windows open at the same time like this Qtile version 0.17.0 Configuration https://pastebin.com/m3nEaWqf — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by m-col** [comment]
I think for that you use the methods that control 'maximize' state such 
as `toggle_maximize`

**Comment by HiroiOwO** [comment]
ok, thank!
