### ISSUE TITLE
utils.has_transparency has print statement left in from testing

### ISSUE THREAD

**Issue by yobleck** [qtile/qtile#2673]
# Issue description
utils.has_transparency is printing bar colors to stdout.
https://github.com/qtile/qtile/blob/a3dcd5db984f3ab08ef3f89eff86e014dd367ee1/libqtile/utils.py#L127
I would submit a pr myself but my fork is currently a little snafu.

# Qtile version
0.18

# Configuration
in my config I have
```
bar.BAR(
    #other stuff
    background=["#000000","#000000","#000000","#003300"],)
```
This is showing up in stdout as: `['#000000', '#000000', '#000000', '#003300']`

**Comment by elParaguayo** [comment]
That's my fault. I'll fix.

**Comment by yobleck** [comment]
No worries. print("got this far") gang unite! :)
