### ISSUE TITLE
battery 'Low_Background' argument [ Suggestion ]

### ISSUE THREAD

**Issue by LamprosPitsillos** [qtile/qtile#2683]
### Discussed in https://github.com/qtile/qtile/discussions/2668

<div type='discussions-op-text'>

<sup>Originally posted by **LamprosPitsillos** July 31, 2021</sup>
The battery low_background should be present, unlike low_foreground which is a difference in color of a few pixels , low_background is much better in letting you know that the battery is getting low.
I would love to see this simple feature implemented please.
Thanks!</div>

**Comment by LamprosPitsillos** [comment]
I have some python experience, and i would love to contribute. I always wanted to help an open source project.
Maybe I will read on how to contribute, and have some fun trying. I don't have anytime tho, so anyone else please feel free to beat me to it!
Any tips ,since I never contributed to a project?

**Comment by elParaguayo** [comment]
Sure. Have a look at these pages:
https://docs.qtile.org/en/latest/manual/contributing.html
https://docs.qtile.org/en/latest/manual/hacking.html
https://docs.qtile.org/en/latest/manual/howto/widget.html

Also, there's a pull request that's not been merged yet which has some good tips too:
#2333

**Comment by LamprosPitsillos** [comment]
Amazing , no I can look at your code to learn and see what I did wrong! 
It's a win win situation, i get a cool feature i wanted AND get to learn how it was made!
Thank you very much!
