### ISSUE TITLE
lag/stuttering on wayland and X11, qtile wayland not using the whole screen.

### ISSUE THREAD

**Issue by Sydiepus** [qtile/qtile#2689]
# Issue description

Qtile on X11 window lagging when resizing/moving. 
[video for reference.](https://streamable.com/5og5ff)

Qtile on wayland not using the whole screen when started by display manager ly.
to reproduce add `qtile start -b wayland' to .xinitrc and launch with ly.
or create a custom .desktop in /usr/share/xsessions with the following :
```[Desktop Entry]
Name=Qtile-Wayland
Comment=Qtile Wayland Session
Exec=qtile start -b wayland
Type=Application
Keywords=wm;tiling
```
and launch it with ly.
[image for reference.](https://imgur.com/sboSudG)
when started from shell with `qtile start -b wayland` it goes fullscreen but with a lot of lag like on X11 including the terminal.

the stuttering/lag problem could be from my config as i don't see the problem when using the default config even on wayland.

# Qtile version

`0.18.1.dev79+gbd5561a9`

# Stack traces
`.xsession-errors` is empty.
[qtile.log](https://github.com/qtile/qtile/files/6944504/qtile.log)

# Configuration

```python
import os 
import subprocess
from typing import List
from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
from libqtile import hook


mod = "mod4"
terminal = "alacritty"

#startup script
@hook.subscribe.startup_once
def start_once():
    script = os.path.expanduser("/home/sydie/.config/qtile/autostart.sh")
    subprocess.call([script])


keys = [

    Key([mod], 'f', lazy.window.toggle_fullscreen()),
    Key([mod], "x", lazy.spawn("rofi -show drun")),


    Key([mod], "Return", lazy.spawn(terminal), desc="Launch terminal"),

    #Screeshot keybinds
    Key([mod], "e", lazy.spawn(["sh", "-c", "maim --geometry 876x657+316+137 | xclip -selection clipboard -t image/png"]), desc="Screenshot Math"),
    Key([mod], "s", lazy.spawn(["sh", "-c", "maim --geometry 532x708+486+81 | xclip -selection clipboard -t image/png"]), desc="Screenshot Math"),
    Key([mod], "a", lazy.spawn(["sh", "-c", "maim -s | xclip -selection clipboard -t image/png"])),
    Key([mod], "d", lazy.spawn(["sh", "-c", "maim | xclip -selection clipboard -t image/png"])),

           # Toggle between different layouts as defined below
    Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([mod, "shift"], "Tab", lazy.layout.previous()),
    Key([mod], "w", lazy.window.kill(), desc="Kill focused window"),
    Key([mod], "l", lazy.layout.down(), desc="Move focus down in current stack pane"),
    Key([mod], "Up", lazy.layout.up(), desc="Move focus up in current stack pane"),
    Key([mod, "control"], "r", lazy.restart(), desc="Restart Qtile"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
    Key([mod], "r", lazy.spawncmd(),
        desc="Spawn a command using a prompt widget"),
]

groups = [Group(i) for i in "123456789"]

for i in groups:
    keys.extend([
        # mod1 + letter of group = switch to group
        Key([mod], i.name, lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),

        # mod1 + shift + letter of group = switch to & move focused window to group
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True),
            desc="Switch to & move focused window to group {}".format(i.name)),
        # Or, use below if you prefer not to switch to that group.
        # # mod1 + shift + letter of group = move focused window to group
        # Key([mod, "shift"], i.name, lazy.window.togroup(i.name),
        #     desc="move focused window to group {}".format(i.name)),
    ])

theme_layout = {
        "border_width": 3,
        "margin": 9,
        "border_focus": "b1d182",
        "border_normal": "688f4e",
        "grow_amount": 2,
}

layouts =[ 
    layout.Tile(**theme_layout),
    layout.Floating(**theme_layout),
]

widget_defaults = dict(
    #font='UbuntuMono Nerd Font Mono',
    font='JetBrainsMono Nerd Font Mono',
    #font='FiraMono Nerd Font Mono',
    #font='FiraCode Nerd Font Mono',
    fontsize=12,
)
colors = ["#688f4e",
          "#b1d182",
          "#f4f1e9",
          "#2b463c",]
extension_defaults = widget_defaults.copy()
screens = [
    Screen(
        wallpaper = '/home/sydie/Downloads/birds-on-a-wire.jpg',
        wallpaper_mode = 'fill',
        top=bar.Bar(
            [
                widget.CurrentLayout(),
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Chord(
                    chords_colors={
                        'launch': ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.Sep(),
                widget.CheckUpdates(),
                widget.Sep(),
                widget.ThermalSensor(),
                widget.Sep(),
                widget.CapsNumLockIndicator(),
                widget.Sep(),
                widget.Net(),
                widget.Sep(),
                widget.Battery(update_interval=0.1),
                widget.Sep(),
                widget.Wlan(interface='wlp3s0'),
              #  widget.Systray(),
                widget.Sep(linewidth=0),
                widget.Clock(format='%Y-%m-%d %a %I:%M %p',background=colors[1], foreground=colors[2]),
                widget.QuickExit(),
            ],
            24,
         background=colors[0],
         ),
    ),
]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []
follow_mouse_focus = True
bring_front_click = True
cursor_warp = False
floating_layout = layout.Floating(**theme_layout)
auto_fullscreen = True
focus_on_window_activation = "smart"
wmname = "LG3D"
```

**Comment by m-col** [comment]
> to reproduce add `qtile start -b wayland' to .xinitrc and launch with ly.

You're starting the Wayland compositor incorrectly - this starts an X session and runs Wayland Qtile inside that, which is likely why it appears to not take the full screen. It's a window nested within an X session. It looks like ly does support wayland compositors but I couldn't find docs, however a quick search in their github found that they use /usr/share/wayland-sessions which I think is for storing .desktop files. Moving your .desktop file into that folder might work - and you may also have to uncomment some lines in your ly config.

> the stuttering/lag problem could be from my config as i don't see the problem when using the default config even on wayland.

If that is the case then it is definitely something in your config. Unfortunately I can't see something obviously wrong with your config. If it persists (after ensuring you are running Qtile correctly) I suggest slowly converting the default config into your own config piece by piece and testing along the way to try to find what change causes the problem.

**Comment by Sydiepus** [comment]
thanks for your reply i moved the .desktop file into /usr/share/wayland-sessions and it's working, kinda, qtile is using the whole screen but i can't resize/move.
launching firefox returns: `Error: no DISPLAY environment variable specified`
i tried setting it to :0 but that it didn't work i got this error instead:
`Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0`
the lag/stuttering is no longer here after using the default config with my tweaks.

**Comment by m-col** [comment]
>  i can't resize/move.

do any keybinds work? if not then the `mod` key will be wrong. Wayland 
doesn't use X's keyboard configuration so if you use one that differs 
from your keyboard then that might need fixing.

 > launching firefox

check out the GTK3 section of 
https://github.com/swaywm/sway/wiki/Running-programs-natively-under-wayland

**Comment by Sydiepus** [comment]
> do any keybinds work?
yes i can launch the termimal and close it and move around through groups.
could the mouse buttons that are not working.
