### ISSUE TITLE
Prompt widget doesn't import environment variables

### ISSUE THREAD

**Issue by superpupervlad** [qtile/qtile#2692]
# Issue description

Prompt widget doesn't has **all** environment variables.
It has some env. vars like `PATH` and `SHELL` (to list all vars run `printenv > ~/var_list`) but there is no access to vars defined in `/etc/environment`, `~/.bashrc`, `.zshenv`, etc. And some programs read configs from these vars, so the only way to launch them correctly is from terminal.

# Qtile version
0.18.1.dev0+g8e7ecc0a.d20210719

# Suggestion
Maybe add parameter to widget that will be responsible for env. variables.

**Comment by tych0** [comment]
This is not really a bug; you're not setting these environment variables when you launch qtile, so qtile doesn't know about them. Qtile is not in fact a login shell, so it doesn't know to source e.g. zshrc.

If you'd like environment variables available in qtile, the best way to accomplish that would be to write a custom xsession that sets whatever you want: http://docs.qtile.org/en/latest/manual/config/index.html#starting-qtile

**Comment by superpupervlad** [comment]
Adding `export TEST=1` to .xsession works. Thank you.
