### ISSUE TITLE
Spectacle window becomes invisible after taking screenshot

### ISSUE THREAD

**Issue by jrwrigh** [qtile/qtile#2693]
# Issue description

When running spectacle (the screen shot utility), it appears normally on initial running. When I try to take a new screenshot, the window becomes invisible. You can see that if I drag the image from the window, it appears, but the window itself does not:

https://user-images.githubusercontent.com/20801821/129081309-f219a703-47e7-4290-810d-8908a61e385b.mp4

I'm running picom as a window compositor. After I killed picom, I can't even select the area to take a screenshot with. After turning it back on, I get the same behavior as before.

# Qtile version

0.18.1.dev0+g8e7ecc0a.d20210719

# Stack traces

None are given during the demonstration

# Configuration

https://github.com/jrwrigh/dotfiles2.0/tree/7281008913a89535c94cc0c736d685f8bb482e8e/.config/qtile

**Comment by m-col** [comment]
How do you call spectable? Nothing is appearing for me when I run it. Also - is this in X11 or Wayland?

**Comment by m-col** [comment]
Lol, obviously X11 as you mentioned picom - ignore that

**Comment by m-col** [comment]
I'm afraid I can't reproduce. Maybe try with the default config? Works with or without picom, but I did find one or two temperamental things with spectacle, such as the window not appearing at all the first few times I called it. No idea what's up with that but it comes up every time now.

https://user-images.githubusercontent.com/44536113/129085163-bc01b84c-4365-4d76-990a-e456d1e4ec53.mp4

**Comment by m-col** [comment]
> some stuff I have running in the background includes: kdeinit5, kglobalaccel5, kactivitymanagerd, klauncher etc.

terrifying! :D

**Comment by jrwrigh** [comment]
I restarted the machine and tried the default config, but it doesn't change the behavior. Though without picom and using dmenu to launch the program (so that I can invoke `spectacle` while not killing it), it does _kind of_ work; spectacle completely disappears after I try to take a new screen shot, but if I run `spectacle` again, it suddenly realizes that I had asked to take a screenshot:

https://user-images.githubusercontent.com/20801821/129103375-4c19c595-126f-476a-a5c9-5c329d72e9f8.mp4

I mainly want spectacle as it can take a screenshot of the same specified screen area repeatedly, so if there are any suggestions for a screenshot utility that can do that, let me know.

**Comment by ramnes** [comment]
I don't use surfable but I seem to remember from a very similar discussion that it's the expected behavior, spectacle going in the tray when you start taking screenshots or something like that. Summoning @drishal; IIRC you had the same problem, right?

**Comment by drishal** [comment]
> drishal

yep I had the same issue 
I think the option was 
```python
  focus_on_window_activation = "focus"
```

**Comment by drishal** [comment]
this was the right one (ignore my previous message 
this was the one 
```python
  auto_minimize = False
```

**Comment by jrwrigh** [comment]
> Sorry, this is the right one (ignore my previous message if you received a notification)
> 
> ```python
>   auto_minimize = False
> ```

Unfortunately this did not change the behavior, but I did discover a new symptom: toggling picom toggles window visibility:

https://user-images.githubusercontent.com/20801821/129204929-40bf3f91-6635-4b15-9431-b01cafc7e047.mp4

@yobleck The WindowName widget does show that Spectacle is `V Spectacle` on first launch, `_ Spectacle` when it turns invisible, then back to `V Spectacle` when I move the invisible window:

https://user-images.githubusercontent.com/20801821/129205344-02b25243-8786-407c-a34f-94357a5bb0ef.mp4

I should note that I haven't installed qtile on top of KDE; I installed it on top of the i3 version of Manjaro. However, I've used Spectacle in this distribution with `picom` before without much issue, but running i3 instead (though it admittedly has been while). I'll check and see if I get the same behavior on the i3 side of things (assuming I still have it installed, which I believe I was too lazy to remove).

**Comment by jrwrigh** [comment]
Found the issue! I had an opacity rule that all windows with `_NET_WM_STATE_HIDDEN` should be made invisible. This was a solution to an issue on i3 where the opacity of stacked windows (similar to treetab) wouldn't be removed (see [reddit post](https://www.reddit.com/r/unixporn/comments/330zxl/webmi3_no_more_overlaying_shadows_and_windows_in/)).

Removing that setting fixed the issue:
https://user-images.githubusercontent.com/20801821/129214532-60b5411d-71d8-437d-88ab-85943a474bb3.mp4
