### ISSUE TITLE
Focus on alacritty (different group)

### ISSUE THREAD

**Issue by BigfootN** [qtile/qtile#2711]
# Issue description

In my `config.py` I set `focus_on_window_activation = "focus"`.

I launch every one of my applications through `rofi`.

The problem is the following:
- `Any application`: Focuses on the `window` in the `group` in which it spawns. No problem.
- `Alacritty`: It is well spawned in the desired `group`, *but* it is not focused. The focus is not changed.

The `qtile.log` file doesn't log anything.

# Qtile version

Installed from `archlinux` ([qtile-git](https://aur.archlinux.org/packages/qtile-git/]))

# Stack traces

I don't have any `.xsession-errors`

# Configuration

I didn't put my entire configuration (I'm still learning to use `qtile` so my config is for the moment quite a mess, and I'm not really comfortable with python), but you can find my groups and keybindings settings [here](https://gist.github.com/BigfootN/546250718177f7fa527c04e14f96f62e) if it's of any help.

**Comment by m-col** [comment]
Just so I understand correctly, `focus_on_window_activation` is working fine for windows that spawn on the current group, but doesn't change groups if the newly spawned window is spawned on a different group?

If that is correct, a solution would be to use a `client_new` hook to check the group of newly spawned windows, and if they are not the current group, to change to their group and then focus them.

**Comment by elParaguayo** [comment]
Any relation to #2588?

**Comment by BigfootN** [comment]
> Just so I understand correctly, focus_on_window_activation is working fine for windows that spawn on the current group, but doesn't > change groups if the newly spawned window is spawned on a different group?

No, it works very well for any window except `Alacritty`

> Any relation to #2588?

I'm not quite sure. And `alacritty` never gains unless manually moving to the group.

**Comment by elParaguayo** [comment]
I think this is somehow related to Alacritty. I've been looking at #2588 and I can only recreate the issue with multiple Alacritty windows open. Using a different terminal, such as kitty, worked fine.
