### ISSUE TITLE
Last used group is presented on screen when another group is called and the same worspace is already on screen.

### ISSUE THREAD

**Issue by MiguelRodrii** [qtile/qtile#2728]
# Issue description
With the default configuration generated by Qtile on the first launch, I'm experiencing a non desired behavior that for me results confusing, basically: when I'm in the group "1" and push the shortcut to switch to the same group by error Qtile takes me to the last used group and at that point if I were to hit "Mod + 2" for example, Qtile brings the first group and I have to "reset" the shortcuts by pressing "Mod + 1" again; behavior that is really confusing some times.
I've been looking for related information but could not find any in the documentation.
Apologies in advance if I'm missing a related issue or something similar. 

# Qtile version
0.18.1.dev0+g8e7ecc0a.d20210719

# Stack traces

# Configuration
default config.

**Comment by elParaguayo** [comment]
I'm not entirely clear what the issue is and it's therefore hard for me to recreate.

The toggling between last group behaviour is there by design. If you don't want it then you can add `toggle=False` as follows (this is from the default config):

``` python
groups = [Group(i) for i in "123456789"]

for i in groups:
    keys.extend([
        # mod1 + letter of group = switch to group
        Key([mod], i.name, lazy.group[i.name].toscreen(toggle=False),
```

**Comment by MiguelRodrii** [comment]
Thank you for your quick reply, It solved my issue.
