### ISSUE TITLE
Feature Request: MonadTall layout with configurable Nmaster

### ISSUE THREAD

**Issue by addy419** [qtile/qtile#2740]
Currently, Tile layout has configurable master pane but does not have focus/shift by direction and MonadTall has everything I need except increasing windows in master pane. Can this be configured?

**Comment by elParaguayo** [comment]
What do you mean by "increasing windows in master pane"? You can grow the window size in MonadTall with `lazy.layout.grow()`.

If that's not what you're after, can you explain a bit more clearly for me.

**Comment by addy419** [comment]
@elParaguayo by Nmaster, I mean the master length (no. of windows in the left column) Similar to the Tile layout http://docs.qtile.org/en/latest/manual/ref/layouts.html#tile but for MonadTall.

**Comment by helmecke** [comment]
@addy419 I'm in the progress of creating a personal MonadTall and MonadWide layout, which allows to increase master length.
It's still a little rough and removes features(indiviual window sizes) the original qtile xmonad layouts had.
I've also added a maximize layout modifier and the ability to change split orientation of windows in master pane.

You can find it [here](https://github.com/helmecke/qtile-config/blob/master/qtile/.config/qtile/xmonad.py).
