### ISSUE TITLE
Qtile config keybindings do not run user defined functions

### ISSUE THREAD

**Issue by addy419** [qtile/qtile#2743]
# Issue description
Qtile cannot run functions in keybindings.
```python
def grow_main():
    lazy.layout.grow_main()

grow_main_lambda = lambda : lazy.layout.grow_main()

keys = [
    Key([mod, "control"], "l", grow_main_lambda()),
]
```

grow_main_lambda runs on keypress but grow_main does nothing. I also tried grow_main_lambda = grow_main but even that does nothing. Only lambda functions run, functions defined with def do nothing.

# Qtile version
version: 0.16.0 from nix 21.05 stable packages

Edit: This is the log I get
```
2021-09-02 17:33:14,889 ERROR libqtile xcore.py:_xpoll():L278 Got an exception in poll loop
Traceback (most recent call last):
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 246, in _xpoll
    ret = target(event)
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 535, in handle_KeyPress
    self.qtile.process_key_event(keysym, event.state & self._valid_mask)
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py", line 363, in process_key_event
    if cmd.check(self):
AttributeError: 'NoneType' object has no attribute 'check'
```

**Comment by m-col** [comment]
Hey @addy419! Your `grow_main` doesn't `return` anything explicitly so Python implicitly does `return None`. This means that a keybinding using that function is equivalent to `Key([mod, "control"], "l", None)`, which is why nothing happens and you see that logged error. The lambda on the other hand returns the evaluated result of the right hand side, which should work. This should do what you want:
```
keys = [
    Key([mod, "control"], "l", lazy.layout.grow_main()),
]
```

**Comment by elParaguayo** [comment]
@m-col beats me again...

They can all work but you're just missing _how_ they work.

Key bindings expect some form of `lazy` object. For example `lazy.layout.grow_main()` is a method call which returns a `LazyCall` object which is what is executed by Qtile when you press your keys. The method does not, itself, trigger the layout method that you're expecting. So, executing a lazy call in a defined function won't work.

If you want to run a defined function, you'd do this:
``` python
from libqtile import qtile
def my_func(*args):
    qtile.current_layout.cmd_grow_main()

keys = [
    Key([mod, "control"], "l", lazy.function(my_func)),
]
```

**Comment by elParaguayo** [comment]
Looks like you're running an old version of qtile. We're on 0.18 now but you're running 0.16.

Try this: remove qtile from the imports and add it as the argument to your function e.g.
``` python
def my_func(qtile):
    qtile.current_layout.cmd_grow_main()
```

**Comment by addy419** [comment]
@elParaguayo Thank you so much, that worked perfectly.

Also, I am actually using NixOS and 0.18.0 is still unstable in the nix repos. There are some issues with dependencies, so I'm finding it difficult to get that working,
