### ISSUE TITLE
Mouse click is not working on browser's auto suggestions

### ISSUE THREAD

**Issue by deepanshu188** [qtile/qtile#2744]
A mouse click is not working in most of the browser suggestions. If i click on the address bar and hit any suggestions it is working fine but when I fill a forum, log in or search for anything in sites then I have to do it with the keyboard's navigation key.

**Bug:**
[https://giphy.com/gifs/C1xq9ILSfXuzsPdRmF](https://giphy.com/gifs/C1xq9ILSfXuzsPdRmF)

**Qtile version :**  _0.18.1.dev0+g8e7ecc0a.d20210719_

**Configuration:** [https://www.dropbox.com/s/6hdq7mugrsthqud/config.py?dl=0](https://www.dropbox.com/s/6hdq7mugrsthqud/config.py?dl=0)

**Comment by m-col** [comment]
What browser?

Can you post the debug log output from the event?

**Comment by deepanshu188** [comment]
> What browser?
> 
> Can you post the debug log output from the event?

I don't think it's a browser issue cause I've DWM install along with the Qtile and it's working there

**Comment by m-col** [comment]
You're right, but only by knowing which browser is experiencing 
symptoms under Qtile can we track what we are handling correctly.

**Comment by deepanshu188** [comment]
> You're right, but only by knowing which browser is experiencing symptoms under Qtile can we track what we are handling correctly.
> […](#)
> On Fri, Sep 3 2021 at 03:22:05 AM -0700, Zexu Knub ***@***.***> wrote: > What browser? > > Can you post the debug log output from the event? > I don't think it's a browser issue cause I've DWM install along with the Qtile and it's working there — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I logged the mouse click even but it's way too long

**Comment by m-col** [comment]
Yeah, the debug output is very verbose.  No worries - I can reproduce locally. We've had a similar issue before, see #2404. A workaround is to use `--disable-features=SendMouseLeaveEvents` as a flag to the program. This seems to work for me for `chromium` and it might work for others. This is sad to see this appear again. Will have to investigate.

**Comment by m-col** [comment]
It seems to work fine for me when the window is tiled and is the only window in the tiled layout. If I tile another window or make the window float, then it  fails again. Do you see the same?

**Comment by deepanshu188** [comment]
> Yeah, the debug output is very verbose. No worries - I can reproduce locally. We've had a similar issue before, see #2404. A workaround is to use `--disable-features=SendMouseLeaveEvents` as a flag to the program. This seems to work for me for `chromium` and it might work for others. This is sad to see this appear again. Will have to investigate.

Ohh okay i'm glad to know that i'm not the only one who's having this issue. Btw i love your Qtile rice it's really cool.

**Comment by deepanshu188** [comment]
> It seems to work fine for me when the window is tiled and is the only window in the tiled layout. If I tile another window or make the window float, then it fails again. Do you see the same?

In my case it's only working when i'm switching window to fullscreen mode.
