### ISSUE TITLE
Caught Exception

### ISSUE THREAD

**Issue by jayjamesdr** [qtile/qtile#2745]
2021-09-03 14:11:55,838 ERROR libqtile net.py:poll():L128 Net: Caught Exception:
'enp6s0'
2021-09-03 14:11:55,846 WARNING libqtile base.py:on_done():L565 poll() returned None, not rescheduling

arch linux

**Comment by elParaguayo** [comment]
Is that the correct interface name? 

The widget should log the exception so I'm not sure why it's actually giving the interface name.

**Comment by jayjamesdr** [comment]
i don't understand

**Comment by elParaguayo** [comment]
I'm assuming that "enp6s0" is the wifi device name that you set in the widget. I'm asking you if that is the correct name.

I also noted that the error in your log should print the details of the exception after the message. However, it's just printing the string "enp6s0".

**Comment by jayjamesdr** [comment]
I don't have a wireless device how ı fix bro please help me

**Comment by elParaguayo** [comment]
Sorry, I didn't mean wifi. "enp6s0" will be your ethernet device.

Can you post the line in your config file where you add this widget to your bar?

**Comment by jayjamesdr** [comment]
okay ı delete this wget thanks ı fix later

**Comment by elParaguayo** [comment]
OK. Start a new issue if you need help later on.
