### ISSUE TITLE
Popup floating window appearing wrongly

### ISSUE THREAD

**Issue by deepanshu188** [qtile/qtile#2751]
# Issue description

Popup windows are hiding from the main screen.

[https://imgur.com/jWlq4Sh](https://imgur.com/jWlq4Sh)

# Qtile version

0.18.1.dev0+g8e7ecc0a.d20210719

# Configuration

[https://www.dropbox.com/s/6hdq7mugrsthqud/config.py?dl=0](https://www.dropbox.com/s/6hdq7mugrsthqud/config.py?dl=0)

**Comment by m-col** [comment]
Please could you be more specific about the issue? Which popup windows? What action are you taking that isn't giving you the outcome you expect? I don't see `popup` or `Popup` in your config anywhere.

**Comment by deepanshu188** [comment]
> Please could you be more specific about the issue? Which popup windows? What action are you taking that isn't giving you the outcome you expect? I don't see `popup` or `Popup` in your config anywhere.

**Comment by deepanshu188** [comment]
> Please could you be more specific about the issue? Which popup windows? What action are you taking that isn't giving you the outcome you expect? I don't see `popup` or `Popup` in your config anywhere.

Look I've attached the screenshot of downloading a wallpaper & the file manager window is overflowing from the edge

**Comment by m-col** [comment]
I see. Could you post an xprop of that window?

**Comment by deepanshu188** [comment]
> I see. Could you post an xprop of that window?

`_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2000001
_GTK_THEME_VARIANT(UTF8_STRING) = 
WM_TRANSIENT_FOR(WINDOW): window id # 0x80001a
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1124, 822
WM_WINDOW_ROLE(STRING) = "GtkFileChooserDialog"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33557068, 33557069
_NET_WM_USER_TIME(CARDINAL) = 4585816
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2000a4b
WM_CLIENT_LEADER(WINDOW): window id # 0x2000001
_NET_WM_PID(CARDINAL) = 46420
WM_LOCALE_NAME(STRING) = "en_IN.utf8"
WM_CLIENT_MACHINE(STRING) = "x505"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 567 by 406
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "vivaldi-stable", "Vivaldi-stable"
WM_ICON_NAME(STRING) = "Save File"
_NET_WM_ICON_NAME(UTF8_STRING) = "Save File"
WM_NAME(STRING) = "Save File"
_NET_WM_NAME(UTF8_STRING) = "Save File"`

**Comment by m-col** [comment]
I've made an issue that is somewhat related, in that it involves the set positions of newly floated windows and makes sure windows should not be off screen when created: https://github.com/qtile/qtile/issues/2754. I will try to fix both of these issues together by revising that code.

**Comment by deepanshu188** [comment]
> I've made an issue that is somewhat related, in that it involves the set positions of newly floated windows and makes sure windows should not be off screen when created: #2754. I will try to fix both of these issues together by revising that code.

Okay thanks ;)
