### ISSUE TITLE
CPU widget fixed size 

### ISSUE THREAD

**Issue by parasbhanot** [qtile/qtile#2769]
Hello everyone , 

i am using the CPU widget to display the CPU usage in qtile bar  but the problem is that size of the widget keeps on changing as CPU usage increases or decrease due to which it pushes or pulls other surrounding widgets which is quite annoying .   

is there any way to fix the size of CPU widget so that it does not disturb other surrounding widgets ?

CPU widget configuration : 

```
 widget.CPU(

            format='CPU {load_percent}%',
            foreground=colors[2],
            background=colors[5],
            padding=5
        ),
```

**Comment by elParaguayo** [comment]
Have a look at #2379.  Some tips in there.

**Comment by elParaguayo** [comment]
@parasbhanot Is this fixed now for you?

**Comment by parasbhanot** [comment]
i have tried the following formatting syntax but it is not working at all 

 `{load_percent:>6.2f}
 `{load_percent:>2.2f}

`

Size of the cpu percentage text is still fluctuating . 

i do not want to add spacer so i am running out of ideas .

**Comment by elParaguayo** [comment]
Are you using a monospaced font?

**Comment by parasbhanot** [comment]
After trying few more fonts i have got  satisfactory results : 

snippet : 


```
 widget.CPU(

     font="Ubuntu Mono Bold",
     fontsize = 16,
     format='P~{load_percent:5.2f}%',
            foreground=colors[2],
            background=colors[5],
            padding=7
        ),
```

**Comment by elParaguayo** [comment]
Great. Thanks for confirming.
