### ISSUE TITLE
PATH added in ~/.bashrc don't work with lazy.spawn, because I can't run kitty and picom which I have added in my bashrc.

### ISSUE THREAD

**Issue by prateekamana** [qtile/qtile#2788]
I think anything PATH you add in ~/.bashrc doesn't work with spawn, because I can't run kitty and picom which I have added in my bashrc.

_Originally posted by @prateekamana in https://github.com/qtile/qtile/issues/1931#issuecomment-917629734_

**Comment by m-col** [comment]
bashrc doesn't affect Qtile. You need PATH to be set in Qtile's environment. Try exporting PATH somewhere before you start Qtile, such as in .xinitrc or however else you start X.

**Comment by prateekamana** [comment]
`#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession
PATH=~/picom/build/src:$PATH
PATH=~/picom/bin:$PATH
PATH=~/Programming/SF/sfdx/bin:$PATH
PATH=~/.local/kitty.app/bin:$PATH`

I copied .xinitrc to home and added the paths, and restarted qtile and my X, it still doesn't work... sorry I'm not that well versed with all of this.

**Comment by m-col** [comment]
How are you starting X?

**Comment by prateekamana** [comment]
I don't know what that question really means, I am on linux mint, I log in and I guess it starts from some autostart script or something? How can I figure out how I am starting it?

**Comment by m-col** [comment]
I guess you'll be using a graphical login manager such as lightdm? Could you try adding your PATH lines to ~/.xsession?

**Comment by prateekamana** [comment]
I didn't have .xsession in ~/ so I created one and added my paths to it, then ran 
`sudo systemctl restart display-manager`
but still no luck.

**Comment by m-col** [comment]
What is `display-manager`? Does restarting it restart your whole X session?

You may have better luck speaking to the linux mint people, as they will have a better understanding of how your system is set up and where to set the environment for your display manager.

**Comment by prateekamana** [comment]
Yeah I guess, I tried even adding PATH's to etc/X11/Xsession, no luck, I will take this to linuxmint forums I guess. Thanks for your help.

**Comment by prateekamana** [comment]
[https://forums.linuxmint.com/viewtopic.php?f=90&t=356971&p=2065793#p2065793](url)
Someone recommended to put the executables to /usr/local/bin/ and that did the trick, I made a symlink `sudo ln -s /path/to/myapp /usr/local/bin`

The original answer for anyone who comes upon this issue 

> You're best off placing (or linking into) executables in e.g. ~/bin for user-private ones or /usr/local/bin for machine-private ones. Latter directory is part of PATH always and former is added to PATH automatically if it exists on login.
Said adding on login is a matter of ~/.profile being read, and this then also says that you can add any custom user-private bin directories to that file if you insist, or in /etc/profile for again machine-private ones. Note that /etc/profile and ~/.profile are only automatically read on login: if you change it you want to log out and back in to have the so-adjusted environment active also for the GUI.

**Comment by cnekmp** [comment]
Please someone add this to official documentation. I couldn't solve this issue until I've learned that Qtile won't check .bashrc PATH variable.
