### ISSUE TITLE
v0.18.1 update completely breaks Bsp layout

### ISSUE THREAD

**Issue by Graeme22** [qtile/qtile#2799]
# Issue description

After installing the latest update via pacman, qtile appears to break.
Downgrading removed the issue. I reproduced it again by upgrading to 0.18.1 and restarting. Upon restarting, qtile crashed (see log below). I then rebooted and logged in as normal. I ran into this upon opening a terminal window:

![2021-09-17-14:39:43_1920x1080_scrot](https://user-images.githubusercontent.com/4185684/133846704-aa1f96dc-710c-47da-a323-4b716c55dee4.png)

Although I was on desktop "a", the window did not render. I then switched to desktop "s" and back to "a" and saw this:

![2021-09-17-14:39:50_1920x1080_scrot](https://user-images.githubusercontent.com/4185684/133846772-573762a9-e67c-45bf-9f12-0efdb7cbe544.png)

For context, this is what everything looked like BEFORE the update, using my config with the Bsp layout:

![2021-09-17-14:38:49_1920x1080_scrot](https://user-images.githubusercontent.com/4185684/133846886-065032f1-fe9a-457e-b98f-6e7635acfef3.png)

# OS/hardware info

![2021-09-17-14:41:27_1920x1080_scrot](https://user-images.githubusercontent.com/4185684/133846627-423fc918-f992-40a4-a278-0298f1c24888.png)

# Qtile version

0.18.1-1 from community repo

# Stack traces

Relevant sections of log:
[qtile.log.txt](https://github.com/qtile/qtile/files/7188166/qtile.log.txt)

# Configuration

Here's my config:
[config.py.txt](https://github.com/qtile/qtile/files/7188130/config.py.txt)

Things I have yet to try:
- Find minimal reproducible config
- Use layout other than Bsp

**Comment by AdolfGatonegro** [comment]
I also had this issue with the 0.18.1-1 update, except I do not use the bsp layout. The only layouts I have configured in my config.py are MonadTall, Max, RatioTile, and Stack. Downgrading to 0.18.0-2 got rid of the issue.

### Issue description
After installing the 0.18.1-1 update and restarting, qtile crashed and sent me back to the display manager login screen. I was able to log back in, and qtile appeared to be working correctly: the keyboard shortcuts were responding, the systray and widgets in the top panel loaded and displayed the correct information, etc. However, no windows were displayed at all when launching an application, though the GroupBox widget updated correctly to show which groups had windows open in them.

### qtile log
[qtile.log.txt](https://github.com/qtile/qtile/files/7188482/qtile.log.txt)

### OS info
![image](https://user-images.githubusercontent.com/6495042/133854523-ae31e8c6-b1d9-47f1-a030-3c4fcd5abd2c.png)

**Comment by elParaguayo** [comment]
I think you've both got the same issue. Your `floating_layout` rules are defined as a dict in your configs but this was deprecated a while ago and now needs to be replaced with `Match` objects.

Have a look at this section of `default_config.py`:
https://github.com/qtile/qtile/blob/0b238eacc964669aac7e48761339543687277245/libqtile/resources/default_config.py#L164-L173

**Comment by AdolfGatonegro** [comment]
> I think you've both got the same issue. Your `floating_layout` rules are defined as a dict in your configs but this was deprecated a while ago and now needs to be replaced with `Match` objects.

Well, that was a silly thing to miss on my end, I suppose. 😅 I can confirm that the 0.18.1-1 update works as expected now, after updating my `floating_layout` rules to use `Match`. I guess I should be keeping a closer eye on change logs in the future so I don't miss this sort of thing.

I do appreciate the response @elParaguayo. Have an excellent day!

**Comment by Graeme22** [comment]
Good catch. I guess this isn't the type of thing that would be covered in migrate... Anyways perhaps it should be in the release notes? I guess the real bummer is that you have to define `floating_layout` in the first place, I've completely disabled it in my config.

**Comment by kaistian** [comment]
> Anyways perhaps it should be in the release notes?

It's in the changelog
https://github.com/qtile/qtile/blob/0b238eacc964669aac7e48761339543687277245/CHANGELOG#L69-L70

> I guess the real bummer is that you have to define `floating_layout` in the first place, I've completely disabled it in my config.

The problem is the floating rules you have in your config, you don't need to define any floating layout.
```
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass
])
```

**Comment by Graeme22** [comment]
Ah good to know. I was looking for the changelog but couldn't find it.

Also I had set `floating_layout = None` which doesn't work, I guess just omitting it entirely does though.

**Comment by TaiDee475** [comment]
Just to provide, feedback, fixing the floating layout section worked. Thanks guys and apologies for missing that change.
