### ISSUE TITLE
memory wget wrong

### ISSUE THREAD

**Issue by jayjamesdr** [qtile/qtile#2813]
kernal : 5.14.6-zen1-1-zen
qtile : 0.18.1
Python 3.9.7
![image](https://user-images.githubusercontent.com/80429360/134474063-7154b050-81ce-4e69-803d-3ecd7f75ce68.png)
[qtile.log](https://github.com/qtile/qtile/files/7216026/qtile.log)

**Comment by elParaguayo** [comment]
Is your issue just that the widget shows something different to htop?

If so, I don't think this is a Qtile issue as we just use python's `psutil` module to get the memory values so there's nothing here to fix.
