### ISSUE TITLE
PulseVolume widget doesn't work

### ISSUE THREAD

**Issue by flexagoon** [qtile/qtile#2816]
# Issue description
PulseVolume widget does not work, it says "Import Error: PulseVolume" in the status bar instead.

# Qtile version
0.18.0

# Stack traces
`2021-09-24 22:42:00,958 WARNING libqtile utils.py:import_class():L200 Unmet dependencies for 'libqtile.widget.pulse_volume.PulseVolume': No module named 'libqtile.widget._pulse_audio'`

**Comment by elParaguayo** [comment]
How did you install Qtile? That module should have been built by `ffibuild`.

**Comment by flexagoon** [comment]
> How did you install Qtile? That module should have been built by `ffibuild`.

I use NixOS, I just enabled the NixOS qtile module. I'm gonna check the module and tell you how it builds qtile

**Comment by flexagoon** [comment]
@elParaguayo looks like the NixOS derivation just fetches the code from github and builds it with setuptools

**Comment by elParaguayo** [comment]
Sorry, I know nothing about NixOS and how it packages software.

I would have expected`ffibuild` to be run as part of that. However, if the pulse audio headers aren't installed then it won't build that module. Are they installed on your system?

**Comment by elParaguayo** [comment]
Closing this as it looks like we know what the issue is but it's not for us to resolve.
