### ISSUE TITLE
Almost all new windows open minimized like in hidden state (since update 0.18.1)

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#2817]
# Issue description

After update from qtile 0.18.0-2 to 0.18.1-2 (in Manjaro) every new window is like minimized. When I downgrade to the previous version, then it works as expected (just like the entire 7 or 8 months before).

To show the window, I have to click it on the top bar at the window name (widget.TaskList) twice, to bring it back. Firefox seems to open in a floating like state, but some other windows like Alacritty or most others open in this minimized like hidden state.

Oh and, restarting Qtile just crashes to my login screen... When I downgrade to previous version and right away restart Qtile with shortcut, it will just restart normal and everything works again.

# Qtile version

0.18.1
But it is a Manjaro community build: 0.18.1-2

So not sure if the exact commit hash makes sense here.

# Stack traces

Part of recent lines from file "~/.local/share/qtile/qtile.log":

https://pastebin.com/4A1srz2t

# Configuration

My ".config/qtile/config.py":

https://pastebin.com/DymdWXtA

**Comment by elParaguayo** [comment]
Same issue as #2799, #2804 and #2807.
