### ISSUE TITLE
async hooks are not documented

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2818]
# Issue description

Hooked functions can be coroutines and we should document what this means, how it works and how to use it on this page: http://docs.qtile.org/en/latest/manual/config/hooks.html?highlight=hooks

# Qtile version

0.18.1

**Comment by Anubha13kumari** [comment]
hi @m-col  .first timer this side .i want to contribute on this issue please  .

**Comment by m-col** [comment]
Hi @Anubha13kumari, that's great!

The link I posted above shows the rendered version of this file: https://github.com/qtile/qtile/blob/master/docs/manual/config/hooks.rst. A nice solution would be to add a new section at the bottom of the `Examples` section titled e.g. "Using asynchronous hooks" with a small description saying that hooks don't need to be regular functions, but can also be coroutines or coroutine functions defined using the `async` syntax (https://docs.python.org/3/library/asyncio-task.html#coroutine). An example use would also be good. In case it is useful, the functionality was added in https://github.com/qtile/qtile/commit/045bd299df416205bc1cd419c04c6f6801e06414. That commit mentions that async hooks can be useful if you want to sleep during a hook, so you can use `await asyncio.sleep(time)` instead of `time.sleep(time)` which would halt all of qtile until it finishes - perhaps that would make a good example.
