### ISSUE TITLE
Can't set the TextBox's text parameter to "<"

### ISSUE THREAD

**Issue by lominoss-git** [qtile/qtile#2821]
So basically, I want to display a **<** in my Qtile bar. But the TextBox's text is to **_Widget crashed: TextBox (click to hide)_**. And this is the error I find in my **~/.local/share/qtile/qtile.log**:
`2021-09-25 19:04:55,198 ERROR libqtile bar.py:_configure_widget():L274 TextBox widget crashed during _configure with error: Exception("parse_markup() failed for b' < ')`

**Comment by elParaguayo** [comment]
Thanks. We've had a couple of similar errors so I need to take a look at how best to handle this.

In the short term, you can fix this by escaping the text: `&lt;` should give you the symbol you're after.

**Comment by lominoss-git** [comment]
Thank you so much! It worked flawlessly.
