### ISSUE TITLE
Qtile doesn't start

### ISSUE THREAD

**Issue by Nimendra11** [qtile/qtile#2822]
I install qtile using the sudo pacman -S qtile command, But I can't start qtile using the qtile start command.

![image](https://user-images.githubusercontent.com/73674803/134792324-a85da8ff-7766-4fd5-ab5c-74d35910e2b4.png)

**Comment by elParaguayo** [comment]
Looks like you're trying to start qtile from within Xfce. That's not going to work.

Is there a qtile session option in your display manager when you boot your machine?
