### ISSUE TITLE
more error

### ISSUE THREAD

**Issue by jayjamesdr** [qtile/qtile#2823]
please help more error and ı try to play game qtile crush ı'm not python programmer ı have no idea
https://github.com/jayjamesdr/MyArchBoot/tree/main/desktop_manager/qtile this is my confi
[qtile.log](https://github.com/qtile/qtile/files/7230665/qtile.log)
g

**Comment by elParaguayo** [comment]
Please, please use the template that is provided when you post an issue.

You must describe the issue you're having. Posting a lot on its own is often not enough.

How is this different from your previous issue?

**Comment by jayjamesdr** [comment]
ERROR libqtile group.py:layout_all():L157 Exception in layout monadtall
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 681, in request_check
    self._process_error(err)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)

and more how ı explain ı don't know 
this is qtile developer place right ?

**Comment by elParaguayo** [comment]
Yes, this is the developer place but that error is useless on its own. You need to explain what you're seeing when this error happens. I don't mean what's in the log, I mean what happens. Do windows not open? do keypresses stop working? What were you doing when the error happened?

Without that, there is nothing I can with that log message. This is why we ask people to post issues using the template which you keep ignoring.

**Comment by jayjamesdr** [comment]
it seems ok but seeing these errors pisses me off 
it probably makes more sense to learn python and make my own tiling manager

**Comment by elParaguayo** [comment]
Ok, but you do understand that I can't help get rid of those errors if you don't tell me what you're doing when those errors arise? 

Your first post just had a log with 1500 lines and no context. From a quick look at the log it seems identical to your previous post #2814. That's why I asked for more information.

I'm not being rude, I'm not being unhelpful, I'm just trying to get enough information to identify the issue and I'm sorry that you're annoyed by this.
