### ISSUE TITLE
TaskList doesn't display Electron application icons

### ISSUE THREAD

**Issue by RobinBoers** [qtile/qtile#2824]
# Issue description

The TaskList widget doesn't display icons for Electron applications. Tested with VSCode, Discord, Slack, Spotify and the Electron example app.

This occurs in both the latest version of Electron and Electron 12.

# Qtile version

Qtile version 0.18.1
Arch Linux

# Stack traces

No stack traces found

# Configuration

<https://gist.github.com/RobinBoers/e87486891e8568d107c071e8264120ec>

**Comment by elParaguayo** [comment]
Thanks for the report. Just so I understand, did this ever work (i.e. have the icons stopped appearing) or is this more of a general issue? Either is fine, I'd just like to understand a bit more!

**Comment by elParaguayo** [comment]
Do any of those windows provide an icon if you run `xprop` on them? If not, they won't show icons in `TaskList`.

**Comment by RobinBoers** [comment]
No, there is no icon in `xprop`. It hasn't worked before I think.

**Comment by elParaguayo** [comment]
OK. So it sounds like there's nothing broken in Qtile and it's more a case of those programs not providing an icon.

We can reopen if anyone can show that they should have icons.
