### ISSUE TITLE
Config breaking update

### ISSUE THREAD

**Issue by UberVeng** [qtile/qtile#2826]
# Issue description
After the latest update I can't start qtile ("no display set" error). Once I define display with ```export DISPLAY=:0.0``` it starts, but most of binds don't work, and GroupBox widget don't change workspaces.

# Qtile version
0.18.1

# Stack traces
[qtile.log.txt](https://github.com/qtile/qtile/files/7231277/qtile.log.txt)
[xsession-errors.txt](https://github.com/qtile/qtile/files/7231278/xsession-errors.txt)

# Configuration
[config.py.txt](https://github.com/qtile/qtile/files/7231283/config.py.txt)

**Comment by elParaguayo** [comment]
Don't know if this is it, but try changing this line:
```groups = [Group(name, layout='column') for name in group_names]``` to `columns`

**Comment by UberVeng** [comment]
> Don't know if this is it, but try changing this line:
> `groups = [Group(name, layout='column') for name in group_names]` to `columns`

Ok, never mind, after lazy.restart() and reboot I wasn't able to reproduce this issue. Now, the question is, how cant I set display variable permanently, so I don't have to set it manually every time I boot the system?

**Comment by elParaguayo** [comment]
How are you starting Qtile?

**Comment by UberVeng** [comment]
I assume that I start it from .xprofile with `qtile start`
[xprofile.txt](https://github.com/qtile/qtile/files/7231438/xprofile.txt)

**Comment by elParaguayo** [comment]
Hmm. I've not come across `.xprofile` before but it doesn't seem to be something that would be called on its own. Are you using a display manager or `startx`?

**Comment by UberVeng** [comment]
I'm using LightDM.
I removed `qtile start` line from .xprofile (turns out that `export DISPLAY=:0.0` don't need to be there either) and after reboot it started without setting display variable. So starts somewhere else, I don't know where, I grep'ed my whole home directory and couldn't find any config file that contains `qtile start` other than .xprofile . But it works now. Thank you @elParaguayo

**Comment by elParaguayo** [comment]
It's probably using `qtile.desktop` in `/usr/share/xsessions`.

Glad to hear it's working ok.
