### ISSUE TITLE
can't open any program if is not in floating mode

### ISSUE THREAD

**Issue by sercus** [qtile/qtile#2828]
# Issue description

So a few days ago I updated my laptop with arch and qtile on it, and since then I wasn't able to run qtile correcctly, the programs will only open if I'm in floating mode and they are or too small or they will open too high in the screen. I though that it might be a problem with my config but then I updated my PC and the same thing is happening. I let my "qtile.log" and my  ".xsession-errors" here.

qtile.log

2021-09-27 15:01:55,076 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll l>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _x>
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1675, in>
    self.update_hints()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 639, in >
    if self.group.floating_layout.match(self):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in mat>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <ge>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in>
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'

.xsesion-errors

(nm-applet:461): Gtk-WARNING **: 14:44:16.404: Failed to parse /home/ser/.config/gtk-3.0/settings.ini: Key file does not start with a group

(nitrogen:463): Gtk-WARNING **: 14:44:17.306: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:463): Gtk-WARNING **: 14:44:17.334: Unable to locate theme engine in module_path: "murrine",

(nitrogen:463): Gtk-WARNING **: 14:44:17.346: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:463): Gtk-WARNING **: 14:44:17.523: Unable to locate theme engine in module_path: "adwaita",

(nitrogen:463): Gtk-WARNING **: 14:44:17.528: Unable to locate theme engine in module_path: "murrine",

(nitrogen:463): Gtk-WARNING **: 14:44:17.529: Unable to locate theme engine in module_path: "adwaita",

(udiskie:462): Gtk-WARNING **: 14:44:20.922: Failed to parse /home/ser/.config/gtk-3.0/settings.ini: Key file does not start with a group

I also let here my qtile config.

qtile.conf

import os
import re
import socket
import subprocess
from libqtile import qtile
from libqtile.config import Click, Drag, Group, KeyChord, Key, Match, Screen
from libqtile.command import lazy
from libqtile import layout, bar, widget, hook
from libqtile.lazy import lazy
from typing import List  # noqa: F401

mod = "mod4"                                     # Sets mod key to SUPER/WINDOWS
myTerm = "alacritty"                             # My terminal of choice

keys = [

    # open terminal
    Key([mod], "Return", lazy.spawn(myTerm), desc="Launch terminal"),

    # keymaps for rofi menu
    Key([mod], "m", lazy.spawn("rofi -show run")),
    Key([mod, 'shift'], "m", lazy.spawn("rofi -show")),

    # volume
    Key([], "XF86AudioLowerVolume", lazy.spawn("pamixer --decrease 5")),
    Key([], "XF86AudioRaiseVolume", lazy.spawn("pamixer --increase 5")),
    Key([], "XF86AudioMute", lazy.spawn("pamixer --toggle-mute")),

    # Brillo / screen bright
    Key([], "XF86MonBrightnessUp", lazy.spawn("brightnessctl set +10%")),
    Key([], "XF86MonBrightnessDown", lazy.spawn("brightnessctl set 10%-")),

    # start firefox
    Key([mod], "f", lazy.spawn("firefox")),

    # start visual studio code
    Key([mod], "c", lazy.spawn("code")),

    # Switch between windows in current stack pane
    Key([mod], "k", lazy.layout.down(),
        desc="Move focus down in stack pane"),
    Key([mod], "j", lazy.layout.up(),
        desc="Move focus up in stack pane"),

    # Move windows up or down in current stack
    Key([mod, "control"], "k", lazy.layout.shuffle_down(),
        desc="Move window down in current stack "),
    Key([mod, "control"], "j", lazy.layout.shuffle_up(),
        desc="Move window up in current stack "),

    # Switch window focus to other pane(s) of stack
    Key([mod], "space", lazy.layout.next(),
        desc="Switch window focus to other pane(s) of stack"),

    # Swap panes of split stack
    Key([mod, "shift"], "space", lazy.layout.rotate(),
        desc="Swap panes of split stack"),

    # Toggle between split and unsplit sides of stack.
    # Split = all windows displayed
    # Unsplit = 1 window displayed, like Max layout, but still with
    # multiple stack panes
    Key([mod, "shift"], "Return", lazy.layout.toggle_split(),
        desc="Toggle between split and unsplit sides of stack"),

    # Toggle between different layouts as defined below
    Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([mod], "w", lazy.window.kill(), desc="Kill focused window"),

    Key([mod, "control"], "r", lazy.restart(), desc="Restart qtile"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown qtile"),
    Key([mod], "r", lazy.spawncmd(),
        desc="Spawn a command using a prompt widget"),
]

groups = []

###FOR AZERTY KEYBOARD
group_names = ["ampersand", "eacute", "quotedbl", "apostrophe", "parenleft",]

group_labels = ['', '', '', '', '',]

# Get the icons at https://www.nerdfonts.com/cheat-sheet (you need a Nerd Font)
# Icons: 
# nf-fa-firefox, 
# nf-fae-python, ''
# nf-dev-terminal, 
# nf-fa-code, ''
# nf-oct-git_merge, ''
# nf-linux-docker,''
# nf-mdi-image, ''
# nf-mdi-layers'' ''       
#icon spotify''

group_layouts = ["monadtall", "monadtall", "monadtall", "monadtall", "monadtall",]

for i in range(len(group_names)):
    groups.append(
       Group(
       name=group_names[i],
       layout=group_layouts[i].lower(),
       label=group_labels[i],
   ))

for i in groups:
    keys.extend([

### CHANGE WORKSPACES
    Key([mod], i.name, lazy.group[i.name].toscreen()),
    Key([mod], "Tab", lazy.screen.next_group()),
    Key(["mod1"], "Tab", lazy.screen.next_group()),
    Key(["mod1", "shift"], "Tab", lazy.screen.prev_group()),

### MOVE WINDOW TO SELECTED WORKSPACE 1-10
    Key([mod, "shift"], i.name, lazy.window.togroup(i.name)),
    ])
#
#
#
#
#
#
#def init_group_names():
#    return [("WWW", {'layout': 'monadtall'}),
#            ("DEV", {'layout': 'monadtall'}),
#            ("SYS", {'layout': 'monadtall'}),
#            ("CODE", {'layout': 'monadtall'}),
#            ("MUS", {'layout': 'floating'})]
#
#def init_groups():
#    return [Group(name, **kwargs) for name, kwargs in group_names]
#
#if __name__ in ["config", "__main__"]:
#    group_names = init_group_names()
#    groups = init_groups()
#
#for i, (name, kwargs) in enumerate(group_names, 1):
#    keys.append(Key([mod], str(i), lazy.group[name].toscreen()))          # switch to another group
#    keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(name)))   # send current window to another group

layout_theme = {"border_width": 2,
                "margin": 8,
                "border_focus": "e1acff",
                "border_normal": "1D2330"
                }

layouts = [
    layout.Max(**layout_theme),
    layout.Stack(num_stacks=2),
    layout.MonadTall(**layout_theme),
    layout.Floating(**layout_theme),
    # layout.MonadWide(**layout_theme),
    # layout.RatioTile(**layout_theme),
    # layout.Tile(**layout_theme),
    # layout.TreeTab(**layout_theme),
    # layout.VerticalTile(**layout_theme),
    # layout.Zoomy(**layout_theme),
]

# setting the colors for further edit
colors = [["#282c34", "#282c34"], # panel background
          ["#3d3f4b", "#434758"], # background for current screen tab
          ["#ffffff", "#ffffff"], # font color for group names
          ["#ff5555", "#ff5555"], # border line color for current tab
          ["#74438f", "#74438f"], # border line color for 'other tabs' and color for 'odd widgets'
          ["#4f76c7", "#4f76c7"], # color for the 'even widgets'
          ["#e1acff", "#e1acff"], # window name
          ["#ecbbfb", "#ecbbfb"]] # background for inactive screens

prompt = "{0}@{1}: ".format(os.environ["USER"], socket.gethostname())

##### DEFAULT WIDGET SETTINGS #####
widget_defaults = dict(
    font="Ubuntu Mono",
    fontsize = 12,
    padding = 2,
    background=colors[1]
)
extension_defaults = widget_defaults.copy()

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.TextBox(
                       text = "",
                       background = colors[0],
                       foreground = colors[2],
                       padding = 20,
                       fontsize = 37,
                       mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(myTerm)}
                       ),
                widget.Sep(
                       linewidth = 0,
                       padding = 6,
                       foreground = colors[2],
                       background = colors[0]
                       ),
                widget.GroupBox(
                       font = "Ubuntu Bold",
                       fontsize = 35,
                       margin_y = 3,
                       margin_x = 10,
                       padding_y = 5,
                       padding_x = 3,
                       borderwidth = 3,
                       active = colors[2],
                       inactive = colors[7],
                       rounded = False,
                       highlight_color = colors[1],
                       highlight_method = "line",
                       this_current_screen_border = colors[6],
                       this_screen_border = colors [4],
                       other_current_screen_border = colors[6],
                       other_screen_border = colors[4],
                       foreground = colors[2],
                       background = colors[0]
                       ),
                widget.Prompt(
                       prompt = prompt,
                       font = "Ubuntu Mono",
                       padding = 10,
                       foreground = colors[3],
                       background = colors[1]
                       ),        
                widget.Sep(
                       linewidth = 0,
                       padding = 40,
                       foreground = colors[2],
                       background = colors[0]
                       ),
                widget.WindowName(
                       font='UbuntuMono Nerd Font',
                       fontsize = 19,
                       foreground = colors[6],
                       background = colors[0],
                       padding = 0
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[0],
                       foreground = colors[5],
                       padding = -14,
                       fontsize = 85
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[5],
                       foreground = colors[4],
                       padding = -14,
                       fontsize = 85
                       ),
                widget.Sep(
                       linewidth = 0,
                       padding = 6,
                       foreground = colors[0],
                       background = colors[4]
                       ),
                widget.CPU(
                       padding_x = 4,
                       foreground = colors[2],
                       background = colors[4],
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                        ),
                widget.TextBox(
                       text = '',
                       background = colors[4],
                       foreground = colors[5],
                       padding = -14,
                       fontsize =80
                       ),
                widget.TextBox(
                       text = " ⟳",
                       padding = 2,
                       foreground = colors[2],
                       background = colors[5],
                       fontsize = 14
                       ),
                widget.CheckUpdates(
                       update_interval = 1800,
                       distro = "Arch_checkupdates",
                       display_format = "{updates} Updates",
                       foreground = colors[2],
                       mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(myTerm + ' -e sudo pacman -Syu')},
                       background = colors[5],
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[5],
                       foreground = colors[4],
                       padding = -14,
                       fontsize = 80
                       ),
                widget.TextBox(
                       text = " 🖬",
                       foreground = colors[2],
                       background = colors[4],
                       padding = 0,
                       fontsize = 14
                       ),
                widget.Memory(
                       foreground = colors[2],
                       background = colors[4],
                       mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(myTerm + ' -e htop')},
                       padding = 5,
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[4],
                       foreground = colors[5],
                       padding = -14,
                       fontsize = 80
                       ),
                widget.TextBox(
                      text = " Vol:",
                       foreground = colors[2],
                       background = colors[5],
                       padding = 0,
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[5],
                       foreground = colors[4],
                       padding = -14,
                       fontsize = 80
                       ),
                widget.CurrentLayoutIcon(
                       custom_icon_paths = [os.path.expanduser("~/.config/qtile/icons")],
                       foreground = colors[0],
                       background = colors[4],
                       padding = 0,
                       scale = 0.7
                       ),
                widget.CurrentLayout(
                       foreground = colors[2],
                       background = colors[4],
                       padding = 5,
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[4],
                       foreground = colors[5],
                       padding = -14,
                       fontsize = 80
                       ),
                widget.Clock(
                       foreground = colors[2],
                       background = colors[5],
                       format = "%A, %B %d - %H:%M ",
                       font='UbuntuMono Nerd Font',
                       fontsize = 16,
                       ),
                widget.TextBox(
                       text = '',
                       background = colors[5],
                       foreground = colors[0],
                       padding = -14,
                       fontsize = 85
                       ),
                widget.Systray(
                       background = colors[0],
                       foreground = colors[4],
                       padding = 10,
                       fontsize = 50,                     
                       ),
                widget.Sep(
                       linewidth = 5,
                       padding = 6,
                       foreground = colors[0],
                       background = colors[0]
                       ),
                widget.Sep(
                       linewidth = 10,
                       padding = 6,
                       foreground = colors[0],
                       background = colors[0]
                       ),

            ],
            24,
        ),
    ),
]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
main = None  # WARNING: this is deprecated and will be removed soon
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass
])
auto_fullscreen = True
focus_on_window_activation = "smart"

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"

**Comment by elParaguayo** [comment]
Ok, we really need to update the issue template for this as it's posted so often. 

See: #2799, #2804, #2807 amongst others.
