### ISSUE TITLE
in Group configuration, spawn opens windows on wrong group (first group)

### ISSUE THREAD

**Issue by knodalyte** [qtile/qtile#2830]
I am trying to use the spawn parameter of the Group to start apps on the correct group, but I am finding that some apps always seem to start on the first group rather than as configured. The relevant piece of my config.py follows:

```
groups = [
        Group(name='1', matches=None, spawn='kitty', layout="max", label='1:terms'),
        Group(name='2', matches=None, spawn=[home + '/.local/bin/start-ranger'], layout="max", label='2:files'),
        Group(name='3', matches=None, spawn='firefox', layout="max", label='3:web'),
        Group(name='4', matches=None, spawn='QOwnNotes', layout="max", label='4:pkm'),
        Group(name='5', matches=[Match(title="apt-listchanges: Reading changelogs")], spawn=[home + '/.local/bin/start-synaptic'], layout="max",  label='5:sys'),
        Group(name='6', matches=None, spawn=[], layout="max", label='6:misc'),
        Group(name='7', matches=None, spawn=[home + '/.local/bin/start-glrnvim'], layout="max", label='7:vim'),
        Group(name='8', matches=None, spawn=[], layout="max", label='8:find'),
        Group(name='9', matches=None, spawn=[], layout="max", label='9:help'),
    ]
```
Based on the config above, at startup synaptic and glrnvim always start on the first group instead of where they are configured.

I am baffled. I had been doing this with an external script that used the qtile cmd-object to set the group and then ran the appropriate command, but it sure looks like the Group class should handle this consistently. 

qtile 18.1

**Comment by elParaguayo** [comment]
The way `spawn` works with groups is to run the command and attach the pid for that process to a rule for the group. My guess would be that synaptic and dlrnvim have different pids and so aren't matched by the rule.

**Comment by knodalyte** [comment]
In each case where I tried using a script to launch a program, it was because each program requires some commandline tweaking or because the command invokes some other commandline magic (e.g. synaptic-pkexec runs 'pkexec synaptic'. So in each of these scenarios, there is some kind of indirection that apparently results in a secondary pid be created but never associated with the group in qtile.

My linux-fu is shaky here, is there some way I can work around this and still use the Group spawn parameter, or do I need to revert to using my external script with qtile cmd-object?

**Comment by elParaguayo** [comment]
The simplest option may be to add some rules to the group so that they match the spawned processes, like you have in group 5. There's nothing to stop you using both `spawn` and `matches`.

**Comment by knodalyte** [comment]
Yes, that way works but any future instances in any group are automatically matched and moved from whatever group I am in at the time. If, for example, I want to use a new instance of glrnvim to edit a file, I don't necessarily want glrnvim to be automatically moved to the group where it is matched.

I think I will mostly revert to the way I was doing things before, setting the appropriate group and starting apps there using a script run by a startup hook. If qtile ever changes the way the spawn works (which looks difficult), I may reconsider.

Thanks for your help.

**Comment by knodalyte** [comment]
Workarounds exist
