### ISSUE TITLE
deadd-notification toggling not triggered with a key

### ISSUE THREAD

**Issue by OmarAshkar** [qtile/qtile#2832]
I have deadd-notification-center installed and tried to bound the following shell command to a key

```
kill -s USR1 $(pidof deadd-notification-center)
```

This works ok in shell but when binding with a key it doesn't work. 

I tried both:

```
Key([mod], "q", lazy.spawn("kill -s USR1 $(pidof deadd-notification-center)"))
```
and
```
Key([mod], "q", lazy.spawn("sh ~/.config/qtile/deadd_toggle.sh"))
```
where this script contains the bash command

# Qtile version
0.18.1.dev123+g76b3962d

This is the only warning I got on restarting qtile with no warnings on pressing the key.
```
WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)

```

**Comment by elParaguayo** [comment]
I suspect the shell expansion isn't working. Try
```
Key([mod], "q", lazy.spawn("kill -s USR1 $(pidof deadd-notification-center)", shell=True))
```

**Comment by OmarAshkar** [comment]
Wasn't aware of that feature. Thank alot!
