### ISSUE TITLE
Function to switch to next workspace/group.

### ISSUE THREAD

**Issue by lominoss-git** [qtile/qtile#2833]
So basically I want to switch to the next workspace/group when I left click on my AGroupBox widget, but I can't find the function to switch to next  workspace.
Here is the code:
```python
widget.AGroupBox(
    borderwidth = 2,
    margin_x = 12,
    mouse_callbacks = {
        "Button1": lambda: the_answer_to_my_question()
    }
)
```

**Comment by elParaguayo** [comment]
You could try:
``` python
from libqtile import qtile

widget.AGroupBox(
    borderwidth = 2,
    margin_x = 12,
    mouse_callbacks = {
        "Button1": lambda: qtile.current_screen.cmd_next_group()
    }
)
```

**Comment by m-col** [comment]
`lambda: qtile.current_screen.cmd_next_group()` -> `qtile.current_screen.cmd_next_group` :wink:

**Comment by elParaguayo** [comment]
Ha. I thought it looked wrong when I typed that. Clearly need more sleep...

**Comment by lominoss-git** [comment]
Thank you guys so much.
