### ISSUE TITLE
Qtile crashed when launching an app 

### ISSUE THREAD

**Issue by gabrielba15** [qtile/qtile#2837]
# Issue description

When I try to open an app, i.e. "Firefox", the app is stopped and I can't using it, so it happens with all applications that I try to launch. 

I have tried restarting qtile but what it does is log out.

Sorry for not including all the requirements but it does not allow me to access any app. 

Help me please 🥺. 

![IMG_20210930_003727](https://user-images.githubusercontent.com/59029788/135388367-f13a5018-4d79-4500-acc7-e61088145167.jpg)

# Qtile version

# Stack traces

# Configuration

**Comment by m-col** [comment]
Do you mean "the app is stopped and I can't using it"? Please could you describe the issue?

**Comment by gabrielba15** [comment]
I am going to describe the problem with an example using Firefox as app: when I try to open Firefox it is hung and it does not let me do anything, I try to restart qille with (cmd + ctrl + r) but close the session

**Comment by jwijenbergh** [comment]
> 
> 
> I am going to describe the problem with an example using Firefox as app: when I try to open Firefox it is hung and it does not let me do anything, I try to restart qille with (cmd + ctrl + r) but close the session. That happens to me with all the applications that I try to open (telegram, alacrity, xterm, etc).
> 
> Is there some way of formatting qtile or something similar?

Can you post the contents of the following files
* `~/.xsession-errors`
* `~/.local/share/qtile/qtile.log`

How are you starting qtile? What is your config? When did this start happening?

**Comment by gabrielba15** [comment]
Hey, thanks for trying helping me.

Here .xsession-errors:
![2021-10-04-102654_1354x181_scrot](https://user-images.githubusercontent.com/59029788/135869670-863687ac-090f-49af-ab24-641e33569c4f.png)

Here qtile log: 
![2021-10-04-102755_1018x580_scrot](https://user-images.githubusercontent.com/59029788/135869720-e96af4b3-c02c-4e52-8814-502bf8dbec60.png)

Here my config file: 
https://github.com/gabrielba15/configs/tree/master/linux/arch/.config/qtile

I was trying to solve the problem and I realized that the problem is in the floating layouts.
![2021-10-04-103807_720x356_scrot](https://user-images.githubusercontent.com/59029788/135871237-1e0b9bfc-47cb-4fab-bee8-2a2082e79adb.png)

As you can see in the image right now I have commented. 
And here is the floating layouts config file:

![2021-10-04-104121_590x487_scrot](https://user-images.githubusercontent.com/59029788/135871786-b143fc41-e9c3-4492-afec-57ae375b0ad7.png)

Do you see something strange? 
What do you recommend me? 

And thanks again, I appreciate that.

**Comment by jwijenbergh** [comment]
> Hey, thanks for trying helping me.
> 
> Here .xsession-errors: ![2021-10-04-102654_1354x181_scrot](https://user-images.githubusercontent.com/59029788/135869670-863687ac-090f-49af-ab24-641e33569c4f.png)
> 
> Here qtile log: ![2021-10-04-102755_1018x580_scrot](https://user-images.githubusercontent.com/59029788/135869720-e96af4b3-c02c-4e52-8814-502bf8dbec60.png)
> 
> Here my config file: https://github.com/gabrielba15/configs/tree/master/linux/arch/.config/qtile
> 
> I was trying to solve the problem and I realized that the problem is in the floating layouts. ![2021-10-04-103807_720x356_scrot](https://user-images.githubusercontent.com/59029788/135871237-1e0b9bfc-47cb-4fab-bee8-2a2082e79adb.png)
> 
> As you can see in the image right now I have commented. And here is the floating layouts config file:
> 
> ![2021-10-04-104121_590x487_scrot](https://user-images.githubusercontent.com/59029788/135871786-b143fc41-e9c3-4492-afec-57ae375b0ad7.png)
> 
> Do you see something strange? What do you recommend me?
> 
> And thanks again, I appreciate that.

Thanks a lot for providing me with more info!

So does commenting the `floating_layout` help? This seems like a duplicate of #2799, #2804, #2807, #2828. You need to replace your `floating_layout` definition to the one from the default config. For more information see https://github.com/qtile/qtile/issues/2799#issuecomment-922122219
