### ISSUE TITLE
Different outer and inner gaps.

### ISSUE THREAD

**Issue by lominoss-git** [qtile/qtile#2838]
### Discussed in https://github.com/qtile/qtile/discussions/2798

<div type='discussions-op-text'>

<sup>Originally posted by **lominoss-git** September 16, 2021</sup>
I'm just asking if there is any way to have different inner and outer gap sizes. Like indicated in this screenshot:
![VirtualBox_Pop!_OS 64-bit - Daily Driver_16_09_2021_12_10_52](https://user-images.githubusercontent.com/79030093/133608060-9b2a5420-0112-4b7c-9ded-ec81bd466d61.png)
</div>

**Comment by elParaguayo** [comment]
Why open an issue when it's being discussed in that thread already?

**Comment by lominoss-git** [comment]
I am so sorry but I am new to issues in Github. I am so sorry if I caused any kind of problem.
