### ISSUE TITLE
Unable to spawn extension.WindowList

### ISSUE THREAD

**Issue by karthink** [qtile/qtile#2840]
# Issue description
When I try to launch the WindowList extension it fails and I get an error.

# Qtile version
0.18.1

# Stack traces

and the stacktrace:

```
2021-09-30 18:33:24,691 ERROR libqtile manager.py:process_key_event():L361 KB command error run_extension: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 313, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 1525, in cmd_run_extension
    extension.run()
  File "/usr/lib/python3.9/site-packages/libqtile/extension/window_list.py", line 58, in run
    out = super().run(items=self.item_to_win.keys())
  File "/usr/lib/python3.9/site-packages/libqtile/extension/dmenu.py", line 96, in run
    proc = super().run()
  File "/usr/lib/python3.9/site-packages/libqtile/extension/base.py", line 99, in run
    return Popen(self.configured_command, stdout=PIPE, stdin=PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
```

# Configuration
The config is:

```python
from libqtile import extension
from libqtile.lazy import lazy

keys.append(
        Key([mod], "semicolon",
            lazy.run_extension(extension.WindowList(
                dmenu_prompt = 'Switch to:',
                dmenu_command = '/usr/bin/dmenu',
    ))))
```

My dmenu supports the height / -h option.

**Comment by elParaguayo** [comment]
This works fine for me with `dmenu` and `rofi` (using `rofi -dmenu').

Does this happen all the time? Any unusual characters in your window names?

**Comment by karthink** [comment]
Happens every time, even with just one window open. My window names are all ascii characters.

**Comment by karthink** [comment]
I have the following:

```python
extension_defaults = dict(
    font='Monospace bold',
    fontsize=16.5,
    background=colors[2],
    padding=3
)
```

**Comment by elParaguayo** [comment]
What's the value of `colors[2]`?

Can you try removing that parameter. 

I could be way off but there was a recent comment about extensions not working when the colour was formatted a certain way.

**Comment by elParaguayo** [comment]
Given your error message, I suspect this isn't the issue but worth trying quickly!

**Comment by elParaguayo** [comment]
We really need to see what's in the extension's `configured_command`. I'll take a look tonight to see how we can inject some logging code into the extension for you to test.

**Comment by elParaguayo** [comment]
Ok. That's helpful. Let me see if I can give you some code to test later today.

**Comment by mitchdost** [comment]
Hi,
same error here.
In my case your LogWindowList code logs:
`WARNING libqtile config.py:run():L60 WindowList error: ['dmenu', '-l', '80', '-p', 'Switch to:', '-fn', 'Ubuntu-18', '-nb', ['#555555', '#555555'], '-nf', ['#DBDBDB', '#DBDBDB'], '-l', '1']`

**Comment by elParaguayo** [comment]
Your foreround and background colours are invalid. They should be a single string not a list.

**Comment by mitchdost** [comment]
`        lazy.run_extension(WindowList(
            dmenu_prompt = 'Switch to:',
            dmenu_command = 'dmenu',
            background= '#555555',
            foreground='#DBDBDB')
        ),
`
had the same idea when looking at the log output.

But the problem is inherited from the colors List in config.py because this list implicitely referenced inside Dmenu class by self.background and self.foreground.

`colors = [["#555555", "#555555"],  # panel background
          ["#434758", "#434758"],  # background for current screen tab
          ["#DBDBDB", "#DBDBDB"],  # font color for group names
          ["#ff5555", "#ff5555"],  # background color for layout widget
          ["#8BB158", "#8BB158"],  # dark green gradiant for other screen tabs
          ["#7197E7", "#7197E7"]]  # background color for pacman widget
`

**Comment by elParaguayo** [comment]
> Thank you!
> 
> this is now working
> 
> ```
>         lazy.run_extension(WindowList(
>             dmenu_prompt = 'Switch to:',
>             dmenu_command = 'dmenu',
>             background= '#555555',
>             foreground='#DBDBDB')
>         ),
> ```
> 
> had the same idea when looking at the log output.
> 
> But the problem is inherited from the colors List in config.py because this list implicitely referenced inside Dmenu class by self.background and self.foreground.
> 
> ```
> colors = [["#555555", "#555555"],  # panel background
>           ["#434758", "#434758"],  # background for current screen tab
>           ["#DBDBDB", "#DBDBDB"],  # font color for group names
>           ["#ff5555", "#ff5555"],  # background color for layout widget
>           ["#8BB158", "#8BB158"],  # dark green gradiant for other screen tabs
>           ["#7197E7", "#7197E7"]]  # background color for pacman widget
> ```

Not sure that's right, presumably you set `foreground=colors[0]` in your config. If so, you've passed a list. You should have passed `colors[0][0]`.

**Comment by karthink** [comment]
> Cool. Yes, that's the problem.
> 
> This isn't the same as bar colours which can be a gradient. This is a value which gets passed to dmenu so qtile isn't responsible for drawing it.

It's fixed for me as well. This was the problem, `colors[2]` that you referred to earlier wasn't a color string but a 2 element array. Sorry for the trouble.

This doesn't explain why it failed to work even after I commented the extension_defaults block, though.
