### ISSUE TITLE
Wrong number of positional arguments in lazy.function()

### ISSUE THREAD

**Issue by karthink** [qtile/qtile#2848]
Following the documentation for user-defined functions, 

> lazy.function(func, *args, **kwargs):
> Calls func(qtile, *args, **kwargs). NB. the qtile object is automatically passed as the first argument.

I defined the following:

```python
def window_to_previous_screen(qtile, switch_group=False):
    i = qtile.screens.index(qtile.current_screen)
    if i != 0:
        group = qtile.screens[i - 1].group.name
        qtile.current_window.togroup(group, switch_group)

def window_to_next_screen(qtile, switch_group=False):
    i = qtile.screens.index(qtile.current_screen)
    if i + 1 != len(qtile.screens):
        group = qtile.screens[i + 1].group.name
        qtile.current_window.togroup(group, switch_group)

keys.extend([
    Key([mod,"shift"],"comma",lazy.function(window_to_next_screen, switch_group=False)),
    Key([mod,"shift"],"period",lazy.function(window_to_previous_screen, switch_group=False)),
    Key([mod,"control"],"comma",lazy.function(window_to_next_screen, switch_group=True)),
    Key([mod,"control"],"period",lazy.function(window_to_previous_screen, switch_group=True)),
])
```

When I try to run one of these commands, I get the following error:

```
2021-10-04 22:30:19,848 ERROR libqtile base.py:cmd_function():L211 Exception calling "<function window_to_next_screen at 0x7f6894a5e940>":
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/command/base.py", line 208, in cmd_function
    function(self, *args, **kwargs)
  File "/home/karthik/.config/qtile/config.py", line 852, in window_to_next_screen
    qtile.current_window.togroup(group, switch_group)
TypeError: togroup() takes from 1 to 2 positional arguments but 3 were given

```

The documentation for `togroup` says:

```
cmd_togroup(groupName=None, *, switch_group=False)

If groupName is not specified, we assume the current group.
If switch_group is True, also switch to that group.
```

I don't get Python, so I must be doing something wrong?

**Comment by elParaguayo** [comment]
Try changing your line to
``` python
qtile.current_window.togroup(group, switch_group=switch_group)
```
The asterisk is used to force users to use named arguments.

**Comment by karthink** [comment]
Thank you, that fixed it.

So would the function definition be the same if it looked like

```python
def self.togroup(groupName=None, *args, switch_groups=False)
```

Also, is there some way to simplify my code above using a decorator? This throws an error:

```python
@lazy.function
def window_to_previous_screen(qtile, switch_group=False):
    i = qtile.screens.index(qtile.current_screen)
    if i != 0:
        group = qtile.screens[i - 1].group.name
        qtile.current_window.togroup(group, switch_group)

@lazy.function
def window_to_next_screen(qtile, switch_group=False):
    i = qtile.screens.index(qtile.current_screen)
    if i + 1 != len(qtile.screens):
        group = qtile.screens[i + 1].group.name
        qtile.current_window.togroup(group, switch_group)

keys.extend([
    Key([mod,"shift"],"comma",window_to_next_screen(switch_group=False)),
    Key([mod,"shift"],"period",window_to_previous_screen(switch_group=False)),
    Key([mod,"control"],"comma",window_to_next_screen(switch_group=True)),
    Key([mod,"control"],"period",window_to_previous_screen(switch_group=True)),
])
```

**Comment by elParaguayo** [comment]
> Thank you, that fixed it.
> 
> So would the function definition be the same if it looked like
> 
> ```python
> def self.togroup(groupName=None, *args, switch_groups=False)
> ```

No. `*args` means the function will accept any number of positional arguments and store them in `args`. `*` means there is nowhere to store the positional args. If `togroup` used `*args` then your `switch_group` _positional_ argument would have been consumed by `*args` and the `switch_group` keyword argument would not be set.

> 
> Also, is there some way to simplify my code above using a decorator? This throws an error:
> 
> ```python
> @lazy.function
> def window_to_previous_screen(qtile, switch_group=False):
>     i = qtile.screens.index(qtile.current_screen)
>     if i != 0:
>         group = qtile.screens[i - 1].group.name
>         qtile.current_window.togroup(group, switch_group)
> 
> @lazy.function
> def window_to_next_screen(qtile, switch_group=False):
>     i = qtile.screens.index(qtile.current_screen)
>     if i + 1 != len(qtile.screens):
>         group = qtile.screens[i + 1].group.name
>         qtile.current_window.togroup(group, switch_group)
> 
> keys.extend([
>     Key([mod,"shift"],"comma",window_to_next_screen(switch_group=False)),
>     Key([mod,"shift"],"period",window_to_previous_screen(switch_group=False)),
>     Key([mod,"control"],"comma",window_to_next_screen(switch_group=True)),
>     Key([mod,"control"],"period",window_to_previous_screen(switch_group=True)),
> ])
> ```
Can you post the error you're getting please.

**Comment by karthink** [comment]
Sure, it's:

> 2021-10-04 23:10:42,105 ERROR libqtile manager.py:cmd_restart():L1043 Preventing restart because of a configuration error: 'LazyCall' object is not callable

**Comment by elParaguayo** [comment]
Thanks. Just edited my earlier post. That's the error I expected.

**Comment by karthink** [comment]
I'll stick to the verbose version then.

There's another issue with the switch_groups=True argument though. Instead of moving this window to the next/previous screen and switching to that group, it's moving a window from that group to this screen. Not sure why this is happening.

With switch_groups=False, this works as expected: Move the current window from this group to the next/previous screen, stay on this screen/group.

**Comment by elParaguayo** [comment]
It's not really "verbose". The point is that you need to provide the function arguments as arguments to `lazy.function` rather than the function itself. 

I'll need to look at the rest later.

**Comment by elParaguayo** [comment]
As an aside, I've got an idea for a nice fix which would let you do your less "verbose" way in your config. I'll see if I can pull together a version later today.

**Comment by karthink** [comment]
Please ignore the error I reported above. It was working correctly but not as I intended. I wanted to move the focus to the next/prev screen, instead it was moving the group on the next/prev screen to this one.

The version that does what I want is

```python

def window_to_previous_screen(qtile, switch_group=False, switch_screen=False):
    i = qtile.screens.index(qtile.current_screen)
    if i != 0:
        group = qtile.screens[i - 1].group.name
        qtile.current_window.togroup(group, switch_group=switch_group)
        if switch_screen == True:
            qtile.cmd_to_screen(i - 1)

def window_to_next_screen(qtile, switch_group=False, switch_screen=False):
    i = qtile.screens.index(qtile.current_screen)
    if i + 1 != len(qtile.screens):
        group = qtile.screens[i + 1].group.name
        qtile.current_window.togroup(group, switch_group=switch_group)
        if switch_screen == True:
            qtile.cmd_to_screen(i + 1)

keys.extend([
    Key([mod,"shift"],  "comma",  lazy.function(window_to_next_screen)),    
    Key([mod,"shift"],  "period", lazy.function(window_to_previous_screen)),
    Key([mod,"control"],"comma",  lazy.function(window_to_next_screen, switch_screen=True)),
    Key([mod,"control"],"period", lazy.function(window_to_previous_screen, switch_screen=True)),
])
```

Where switch_group is unused and switch_screen is used in its stead.

> As an aside, I've got an idea for a nice fix which would let you do your less "verbose" way in your config. I'll see if I can pull together a version later today.

That would be great, thanks for looking into it!

**Comment by m-col** [comment]
> Also, is there some way to simplify my code above using a decorator?

I can't think of how to neaten it with a decorator while specifying an argument like that, because you'd have to pass the decorator the kwarg and then it's basically hard-coded again. What you can do is use a closure:

```py
def something(option=True):
    def _inner(qtile):
        do_some_things
        do_some_things_with option
    return lazy.function(_inner)

Key(..., something(option=True))
Key(..., something(option=False))
```

**Comment by elParaguayo** [comment]
Or... you could create a `__call__` method in `LazyCall` which sets the `_args` and `_kwargs` properties before returning itself.

It works (I tested quickly this morning).

**Comment by m-col** [comment]
Not sure I am picturing what you mean exactly so interested in your findings.

**Comment by elParaguayo** [comment]
`lazy.function` returns a `LazyCall` object. So, when you do this:
``` python
@lazy.function
def my_function(qtile, arg, kwarg=None):
     pass

Key(...,  my_function(kwarg=True))
```
you're actually calling a `LazyCall` object with `kwarg=True` as an argument.

If you create a `__call__` method in the `LazyCall` class, you can capture these arguments and add them to the arguments that were set when the object was created (e.g. when the function was decorated).

Something like this:
``` python
class LazyCall:

    def __call__(self, *args, **kwargs):
        self._args = (*self.args, *args)
        self._kwargs = self._kwargs.update(kwargs)
        return self
``` 

Still playing with it but hope that gives you an idea of what I'm doing.

**Comment by m-col** [comment]
Huh! Pretty smert!
