### ISSUE TITLE
Qtile not working after latest update

### ISSUE THREAD

**Issue by rdabra3** [qtile/qtile#2855]
I am using Manjaro 21.1.2 . Everything was working very good, until the last update for qtlie came out recently. I can login into Qtile, but I am unable to launch any applications, be it using rofi or be it using shortcuts. I can't even open Alacritty terminal. The only application that I was able to launch was Pamac GUI using rofi. Please help me.

**Comment by elParaguayo** [comment]
Almost certainly going to be the issue: https://github.com/qtile/qtile/issues/2799#issuecomment-922122219

**Comment by elParaguayo** [comment]
Floating layout appears twice in your config: once in layouts and once to define the rules. It's the second one that needs to be fixed. 

If that's not the problem then post a log as you've given us nothing to go on here and I can only guess at the moment.

**Comment by rdabra3** [comment]
It turns out that it was the issue indeed. I tried replacing the entries with Match, but it didn't work. So, I completely deleted the Floating Layout definition and it is now working as good as it was working earlier. Thank you so much for replying quickly and for helping me.
