### ISSUE TITLE
Bar transparency broken with latest days commits

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#2879]
# Issue description

Just updated qtile today and the latest commit seems to have broken my bars transparency. Everything else is working as expected with picom, it's just my bar that has become solid black  since updating today. It was fine before the update.

It was fine with the 8th commit but the 10th has no bar transparency. Nothing new in my log file either ???

# Qtile version

4d9210224e4eca23c0e461f5ec64392e4bf60e83

# Stack traces

# Configuration

**Comment by justinesmithies** [comment]
Not sure as I'm running Qtile on arch and I'm using the qtile-git aur pkgbuild ?

**Comment by m-col** [comment]
As far as I can tell, it shouldn't have worked _before_ that commit.

**Comment by m-col** [comment]
Oh, i totally misunderstood how it worked! I missed the recursion. It should be `Tuple[float, float, float, float]`.
