### ISSUE TITLE
StockTicker widget shows USD value but locale currency symbol

### ISSUE THREAD

**Issue by hamensman** [qtile/qtile#2898]
Same as this https://github.com/qtile/qtile/issues/2470 (`CryptoTicker`) but for `StockTicker` widget.

It shows USD value but with locale currency symbol.

I tried `market = "USD"` just to make sure, but that doesn't do anything. And there's no other option to change the currency anyway.

**Comment by elParaguayo** [comment]
You shouldn't set a symbol in `defaults`. `CryptoTicker` has defaults that look like this:
https://github.com/qtile/qtile/blob/f73371457720be20e2c23184d221837d05afd641/libqtile/widget/crypto_ticker.py#L58-L67

You'll see `symbol` has a default of `_DEFAULT_SYMBOL` which is defined here
https://github.com/qtile/qtile/blob/f73371457720be20e2c23184d221837d05afd641/libqtile/widget/crypto_ticker.py#L33

That should set it to the user's local symbol but they're free to override this when creating the widget in their `Bar`.

**Comment by hamensman** [comment]
> You shouldn't set a specific symbol in `defaults` (lots of users won't want the "$" symbol by default).

Fair enough. I've now made those changes.

Before attempting to change the actual currency value, I've also tried adding the format `parameter` like in `CryptoTicker`. But I can't get that to work - if I specify any kind of `format` in my config, the widget says "No network".

[custom_stock_ticker.txt](https://github.com/qtile/qtile/files/7359949/custom_stock_ticker.txt)

**Comment by elParaguayo** [comment]
You should only get "no network" if it can't retrieve data from the server.

**Comment by elParaguayo** [comment]
Exactly.

**Comment by elParaguayo** [comment]
OK. So add some debugging.

Make sure you've got `logger` imported (`from libqtile.log_utils import logger`) and do:
``` python
def parse(self, body):
    logger.warning(f"Stock ticker body: {body}")
    last = None
    ....
```

**Comment by elParaguayo** [comment]
That spew of text is the logger output with a valid reponse.

You can add `currency` to `self.query` too. You shouldn't touch the `url.format` line.

**Comment by hamensman** [comment]
> That spew of text is the logger output with a valid reponse. You can remove the logger line.

Thanks for clarifying that.

> You can add `currency` to `self.query` too.

Done. Although there are no errors in the logs, the conversion is not taking place.
[custom_stock_ticker.txt](https://github.com/qtile/qtile/files/7360489/custom_stock_ticker.txt)

**Comment by hamensman** [comment]
Converting currency. E.g. EUR.

**Comment by elParaguayo** [comment]
Have a search on alphavantage.co - does it even do prices in different currencies?

**Comment by hamensman** [comment]
> Edit: looking at the docstring, try using market - this would need to be in self.query too.

Changing `currency` to `market` made no difference.

> However, looking at the alphavantage API, this may only be available for cryptocurencies.

I tried this line (written in the documentation) (yes, I put the actual api key in) on both the the **original** as well as the modified `StockTicker` to see whether the new code was interfering, but both say "Can't parse":

`widget.StockTicker(apikey=..., function="DIGITAL_CURRENCY_INTRADAY", symbol="BTC", market="USD")`

Not sure if you can reproduce this too: [qtile.log](https://github.com/qtile/qtile/files/7360559/qtile.log)

**Comment by elParaguayo** [comment]
I'm not sure that alphavantage.co lets you select display currencies for stocks. I don't think it's an issue with the widget, I think it's a limitation of the data.

**Comment by hamensman** [comment]
This is what I get (when trying to show `BTC`) with adding the logger line in both the original and the modified (obviously the modified one will show as `custom_ticker.py`.

```python
2021-10-17 20:21:24,033 WARNING libqtile stock_ticker.py:parse():L68 Stock ticker body: {'Error Message': 'Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for DIGITAL_CURRENCY_INTRADAY.'}
2021-10-17 20:21:24,034 ERROR libqtile generic_poll_text.py:poll():L90 got exception polling widget
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/generic_poll_text.py", line 88, in poll
    text = self.parse(body)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/stock_ticker.py", line 70, in parse
    for k, v in body['Meta Data'].items():
KeyError: 'Meta Data'

```

**Comment by elParaguayo** [comment]
I don't see `DIGITAL_CURRENCY_INTRADAY` in the API at all.

You need to look at the API docs and check that `self.query` contains all the required fields.

**Comment by hamensman** [comment]
https://www.alphavantage.co/documentation/
I found that you have to specify a separate `function` for stocks vs crypto. **Do not mix them.**

### Use `TIME_SERIES_INTRADAY` for stock.
While this accepts `market = "USD"` in your config, it will throw a parse error if you write, say, `market = 'EUR"`. In other words, in your config, if you want to show stock, **just don't write anything for `market` in your config**. Leaving USD in `defaults` will do.

I've tried the other digital currency APIs to accept different markets (daily, weekly, monthly), but kept getting invalid API call parse errors. For now, users will have to stick with USD currency for stocks.

### Use `CRYPTO_INTRADAY` for crypto.
You can specify whatever `market` (currency) you want here.

Although what this means is you have two widgets which both can display crypto. One of two things should happen then. Either we say to users to just use `StockTicker` for stock and use `CryptoTicker` for crypto. Or we get rid of `Cryptoticker` and just have `StockTicker` do both.

If the latter were to be taken, what that would mean for the end user is if, say, they want both `AMZN` ( a stock) and `BTC` (a crypto) on their bar, they will need to declare separate instances in their config (because of the different `function`s).

**Comment by elParaguayo** [comment]
I've now realised why the widget adds everything in `config` to the query: that way users can add any other parameters that alphavantage's API allows without them being part of `defaults`.

So, really, all we need to do is add `sign` and `symbol` to `defaults` and add `symbol` to `self.query`.

I appreciate you've put a lot of effort into this (and hopefully it's been a good learning experience for you) but I think the changes we need are much simpler.

Do you want me to create a Pull Request for this?
