### ISSUE TITLE
Qtile Wayland don't start

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#2933]
# Issue description
qtile start -b wayland not initialize 

# Qtile version
0.18.2.dev54+g1da2e6a0
in Debian

# Stack traces

Traceback (most recent call last):
File "/usr/local/bin/qtile", line 33, in
sys.exit(load_entry_point('qtile==0.18.2.dev54+g1da2e6a0', 'console_scripts', 'qtile')())
File "/usr/local/lib/python3.9/dist-packages/qtile-0.18.2.dev54+g1da2e6a0-py3.9-linux-x86_64.egg/libqtile/scripts/main.py", line 61, in main
options.func(options)
File "/usr/local/lib/python3.9/dist-packages/qtile-0.18.2.dev54+g1da2e6a0-py3.9-linux-x86_64.egg/libqtile/scripts/start.py", line 87, in start
q = make_qtile(options)
File "/usr/local/lib/python3.9/dist-packages/qtile-0.18.2.dev54+g1da2e6a0-py3.9-linux-x86_64.egg/libqtile/scripts/start.py", line 50, in make_qtile
kore = libqtile.backend.get_core(options.backend)
File "/usr/local/lib/python3.9/dist-packages/qtile-0.18.2.dev54+g1da2e6a0-py3.9-linux-x86_64.egg/libqtile/backend/init.py", line 15, in get_core
return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
File "/usr/lib/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/usr/local/lib/python3.9/dist-packages/qtile-0.18.2.dev54+g1da2e6a0-py3.9-linux-x86_64.egg/libqtile/backend/wayland/core.py", line 28, in
import wlroots.helper as wlroots_helper
ModuleNotFoundError: No module named 'wlroots'

i have wlroots installed in /usr/lib/wlroots

**Comment by cr1ogen** [comment]
cr1ogen@Debian-Sid [21:14:01] [~] 
-> % pip list
Package    Version
---------- -------
cffi       1.15.0
pip        21.3.1
pycparser  2.21
pywayland  0.4.7
pywlroots  0.14.10
setuptools 40.8.0
xkbcommon  0.4

**Comment by flacjacket** [comment]
Interesting... it looks like there is something that is messed up with pip installing the pywlroots wheel. Let me look into this.

**Comment by flacjacket** [comment]
Oh, wait! The wlroots package isn't packaged into a wheel, it is uploaded as source and should be built locally as a wheel.

**Comment by flacjacket** [comment]
So, I'm not totally sure what is going on, but I can reproduce this locally if I create a new virtualenv and just do a `pip install pywlroots` there. If I first install all of the dependencies (pywayland, cffi, xkbcommon) and then install pywlroots, everything works just fine. I can keep poking at this to see if there is something that we aren't doing correctly to setup the dependencies, but I _think_ everything should work.

**Comment by flacjacket** [comment]
So it looks like this is what is showing up in the pip install log:
```
  Running setup.py (path:/tmp/pip-install-9tjjy02w/pywlroots_554b3b63490344b1881fe7d0140c9046/setup.py) egg_info for package pywlroots
  Created temporary directory: /tmp/pip-pip-egg-info-1m1fuuph
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  /usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'
    warnings.warn(msg)
```
That is why we aren't able to get the cffi module installed. Why this isn't correctly being handled via the `install_requires`, I'm not totally sure.

**Comment by flacjacket** [comment]
Ugh! So it looks like this might work if we add all of the cffi dependencies to `setup_requires`. Unfortunately, this then also means these packages are required for `sdist`, which should be able to just build the source and doesn't need to have the dependencies, which would greatly complicate the release creating in github actions (not impossible to do, but would take a bit of work to get fixed up). There is some discussion that `build_system` is the replacement for `setup_requires`, but it looks like that gives the same error.

For now, if you re-install pywlroots, but first install `cffi`, `pywayland`, and `xkbcommon`, then it should work. Note that you might need to remove `~/.cache/pip` so you re-download and rebuild the packages. We can move this issue over to the pywlroots repo.

**Comment by flacjacket** [comment]
Let us know if this continues to be a problem. I've moved the underlying problem over to flacjacket/pywlroots#65.

**Comment by cr1ogen** [comment]
> Let us know if this continues to be a problem. I've moved the underlying problem over to [flacjacket/pywlroots#65](https://github.com/flacjacket/pywlroots/issues/65).

Hi! Install pywlroots again following your instructions and it worked, I was able to start Qtile Wayland. Thank you so much!

**Comment by flacjacket** [comment]
Great! I was able to get a fix pushed into pywlroots and a new version cut, so this shouldn't be a problem moving forward!
