### ISSUE TITLE
System tray icons overlap when changing status

### ISSUE THREAD

**Issue by hamensman** [qtile/qtile#2935]
Let's take the wifi (`nm-applet` ) and bluetooth (`blueman-applet`) system tray icons.

When I am connected to wifi and bluetooth is on, they look like this:
![Screenshot_2021-10-23_00-54-29](https://user-images.githubusercontent.com/76445071/138534476-1809b11e-930a-4034-ac9f-7e5029bbf876.png)
If I disconnect wifi and disable bluetooth, they **should** look like this:
![Screenshot_2021-10-23_00-54-58](https://user-images.githubusercontent.com/76445071/138534502-6908b925-bedc-4862-8562-2543bf0dbe94.png)
But what actually happens is they end up overlapping on top of each other, looking like this:
![Screenshot_2021-10-23_00-55-21](https://user-images.githubusercontent.com/76445071/138534522-cb6c390c-ae35-4408-9e42-b63c245205c2.png)

Right now, I would have to do a qtile restart if I wanted the icons to look as they should.

Using latest Qtile on Arch.

**Comment by elParaguayo** [comment]
I've lost track of this one.

Can anyone confirm if the overlapping is still an issue as I can't recreate it.

**Comment by ervinpopescu** [comment]
Yes, it still is.

**Comment by CSpencerND** [comment]
Happens to me with volumeicon as well. I have my Systray inside a WidgetBox. Interestingly, collapsing and opening the WidgetBox corrects it without having to reload qtile.

**Comment by CSpencerND** [comment]
Check this out. I just woke my laptop from sleep and the Systray inside the WidgetBox is overlapping the other widgets.
![2021-11-07_06-09](https://user-images.githubusercontent.com/61397897/140642635-8aa01478-cdfe-4cd2-b5eb-6f6350358e59.png)

**Comment by elParaguayo** [comment]
Is volumeicon a systray app?

Can you post your config and a screenshot of the issue.

**Comment by CSpencerND** [comment]
I have some errors in the logs.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 332, in cmd_reconfigure_screens
    self._process_screens()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 313, in _process_screens
    scr._configure(self, i, x, y, w, h, grp)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 289, in _configure
    self.set_group(group)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 348, in set_group
    g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
```

**Comment by CSpencerND** [comment]
> Is volumeicon a systray app?
Yes.

> Can you post your config and a screenshot of the issue.
I got you in a moment.

**Comment by CSpencerND** [comment]
@elParaguayo 
[my config](https://github.com/CSpencerND/dotfiles/blob/main/.config/qtile/config.py)

**Comment by CSpencerND** [comment]
Full volume
![image](https://user-images.githubusercontent.com/61397897/140643491-fc4751ee-59ee-4b44-9334-7c38c69fad66.png)

Muted
![image](https://user-images.githubusercontent.com/61397897/140643506-3f857cef-9b48-4090-83aa-2b10c82bd714.png)

After unmuting
![image](https://user-images.githubusercontent.com/61397897/140643546-2ead3c35-f2cd-46b4-b350-a09d13a98983.png)

However, it doesn't always happen, and if I kill picom it doesn't happen at all.

**Comment by elParaguayo** [comment]
Does it happen if you use a fully opaque bar? (Try with picom still running).

**Comment by CSpencerND** [comment]
> Does it happen if you use a fully opaque bar? (Try with picom still running).

Wow. It happened like that.

**Comment by elParaguayo** [comment]
Are you saying it still doesn't work with an opaque bar?

**Comment by elParaguayo** [comment]
I can't recreate overlapping items or Systray dispaying from inside WidgetBox after resume.

> However, it doesn't always happen, and if I kill picom it doesn't happen at all.

Doesn't happen for me so I guess we need to try and narrow down what else is going on that triggers this.

**Comment by CSpencerND** [comment]
> Are you saying it still doesn't work with an opaque bar?

I get overlapping even when the bar is opaque if picom is running. I haven't seen the overlapping occur without picom running. Sometimes I can't get it to happen if I try to make it happen, which would make it difficult to pinpoint what's going on if I can't cause it at will.

**Comment by CSpencerND** [comment]
Ok, picom is **_not_** running and the Systray is displaying from inside the WidgetBox.

**Comment by elParaguayo** [comment]
Yes, that will be a separate issue.

**Comment by elParaguayo** [comment]
Can you run:
```qtile cmd-obj -o bar top -f eval -a "self.drawer._depth"```
and tell me what you get.

**Comment by elParaguayo** [comment]
While you're at it, can you also run
```
qtile cmd-obj -o bar top -f eval -a "self.drawer._visual.visual.id"
qtile cmd-obj -o widget systray -f eval -a "self.drawer._visual.visual.id"
```

**Comment by CSpencerND** [comment]
> qtile cmd-obj -o bar top -f eval -a "self.drawer._depth"

(True, '24')

**Comment by CSpencerND** [comment]
> While you're at it, can you also run
> 
> ```
> qtile cmd-obj -o bar top -f eval -a "self.drawer._visual.visual.id"
> qtile cmd-obj -o widget systray -f eval -a "self.drawer._visual.visual.id"
> ```

```
(False, "AttributeError: 'VISUALTYPE' object has no attribute 'visual'")
(False, "AttributeError: 'VISUALTYPE' object has no attribute 'visual'")
```

**Comment by elParaguayo** [comment]
oops. `visual_id`

**Comment by CSpencerND** [comment]
> oops. `visual_id` not `visual.id`

```
(True, '32')
(True, '32')
```

**Comment by elParaguayo** [comment]
Hmm. That looks ok.

Can you check the drawer depth changes to 32 when you have transparency enabled for the bar background in your config.

**Comment by CSpencerND** [comment]
> Can you check the drawer depth changes to 32 when you have transparency enabled for the bar background in your config.

Still 24

**Comment by elParaguayo** [comment]
Interesting. That should change to 32. That could be the issue here.

**Comment by elParaguayo** [comment]
Let's try:
```qtile cmd-obj -o cmd -f eval -a "self.core.conn.default_screen._get_depth_and_visual(32)"```

**Comment by CSpencerND** [comment]
> Let's try: `qtile cmd-obj -o cmd -f eval -a "self.core.conn.default_screen._get_depth_and_visual(32)"`

`(True, '(32, <xcffib.xproto.VISUALTYPE object at 0x7f9af345a8e0>)')`

**Comment by elParaguayo** [comment]
OK. So your screen supports 32 bit depth (I'd have been _very_ surprised if it didn't), so why aren't we getting 32 bit for the bar? Did you restart qtile after changing the bar colour?

**Comment by CSpencerND** [comment]
I restarted with the lazy command keybinding. Should I completely log out?

**Comment by elParaguayo** [comment]
Shouldn't be necessary but, if you could, yes please. Want to be sure we didn't miss something obvious.

**Comment by CSpencerND** [comment]
Nah. Restarting doesn't change anything.

**Comment by elParaguayo** [comment]
OK. So why on earth is your bar 24 bit if you've got transparency enabled in the background colour.

When are you starting picom?

**Comment by CSpencerND** [comment]
With a script on startup with 
```@hook.subscribe.startup_once
def start_once():
    subprocess.call([home + '/.config/qtile/scripts/autostart.sh'])
```

**Comment by elParaguayo** [comment]
Hang on...

32 bit is the default depth for windows, this is only changed to 24 if the bar thinks you don't need transparency.

Looking at your theme `bg` values, none of them have an alpha value so this will force the bar to be 32 bit.

Can you add an alpha value and see what happens.

**Comment by CSpencerND** [comment]
Depth is now 32 after adding alpha.

**Comment by elParaguayo** [comment]
OK... but do you still get the rendering issues with the icons?

**Comment by CSpencerND** [comment]
The overlapping doesn't happen anymore, but now the color in the Systray blends with the wallpaper. It doesn't really bother me but I don't know if that's intended.

**Comment by elParaguayo** [comment]
OK. So...
- Good that you're not getting the issue
- Not sure _why_ you were getting the issue. Systray should work in 24 bit but looks like picom is interfering for you. Was picom set up to do something to your bar?
- If you don't want a transparent bar, just set the alpha to a tiny value. e.g. if you're doing it in hex, just use `01` as the alpha value. There just needs to be some alpha for it to set to 32 bit depth.

**Comment by CSpencerND** [comment]
I haven't explicitly set picom to do anything to the bar, and looking at the config I don't see anything that would suggest picom is doing anything to the bar directly (I'll try the default picom config just to be sure).

**Comment by CSpencerND** [comment]
I tired picom with default config, and even with **no** config and the overlapping occurs. So, the only way to stop it is by adding an alpha value.

**Comment by elParaguayo** [comment]
Ok. Well, at least we've found a fix. May need to add something to the docs about this.

If I recall correctly, setting the bar as 32 bit by default caused some issues if you weren't running a compositor but maybe I should check that again.

**Comment by krive001** [comment]
If the bar background is not alpha, then the background color of the widgets cannot be alpha.
bar.py
```
if self.qtile.core.name == "x11":
                depth = 32 if has_transparency(self.background) else self.qtile.core.conn.default_screen.root_depth
```

No alpha depth = 24

**Comment by elParaguayo** [comment]
I know. I wrote those lines and added the transparency to the bar :wink:

The question is: why is picom messing with the bar when no alpha is set? That's what seems to be causing the issue (although I think some people reported issues even when picom was stopped).

The systray advertises the visual that icons should use and takes this from the colour depth of the bar. So, if the bar is 24 bit, the icon windows should be 24 bit too.

**Comment by krive001** [comment]
And the svg icon? How will it be 24 bits? Or which icon is transparent?

**Comment by elParaguayo** [comment]
The systray widget does not draw icons. They are windows that are embedded into the tray window.

That's why it's so hard to fix this as there's only so much we can do but we are then relying on the apps themselves to do the right thing.

This is different from the StatusNotifier widget which does draw the icons itself. That one does work with transparency.

**Comment by krive001** [comment]
I hope you can see. Glad I was able to help
[video.zip](https://github.com/qtile/qtile/files/7495449/video.zip)
.

**Comment by elParaguayo** [comment]
You should be able to insert video into your comment without zipping it. I'm not downloading a zip when I'm at work.

If you've got a fix, please submit a PR.

**Comment by elParaguayo** [comment]
Can you drop your video file straight into the comment? I'd be very interested to see what you've managed to do.

Your PR doesn't work for me but, given I can't replicate the issue above anyway, it may well be something that works for other people. If that's the case, we could add a config option to force the colour depth of the bar.

**Comment by krive001** [comment]
The widget_map is not visible in the systray or <no name>
0.18* for `xprop` shows this
```
QTILE_INTERNAL(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
```
0.17
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
QTILE_INTERNAL(CARDINAL) = 1
```

It's like creating a window first and then a mask.
But I may misinterpret it.

**Comment by elParaguayo** [comment]
Not sure what you're looking for but, if you run `xprop` and click on the the tray, you'll get the bar window.

To get the tray, you can do this:
```
qtile cmd-obj -o cmd -f eval -a "self.windows_map"
```

That will give you something like this:
```
(True,
 '{4194592: Internal(wid=4194592), 4194596: <libqtile.widget.systray.Systray '
 "object at 0x7fcf5dece280>, 6291458: Window(name='Alacritty', wid=6291458), "
 "20971522: Window(name='Alacritty', wid=20971522)}")
```

You can then run `xprop -id 4194596` and get
```
_NET_SYSTEM_TRAY_VISUAL(VISUALID): visual id # 0x21
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
```
As you can see, the tray advertises the visual id that should be used by apps to display their icons.

**Comment by elParaguayo** [comment]
OK. What am I meant to be looking at in those screenshots?

**Comment by krive001** [comment]
OK. I tried to help find the error.
I have time to fight now, I hope to solve the problem as soon as possible.

**Comment by elParaguayo** [comment]
Can I suggest you start a discussion on this so we don't fill up the issue with questions about the widget.

**Comment by nullbyto** [comment]
I'm having the same issue with `blueman-applet`. And the only way to get rid of that is to stop `picom`.
Did anyone solve it ?

One thing I noticed, I didn't face this issue on my `Fedora` install. After installing `Arch` with `qtile` with the same config, it started happening, which is really odd.

**Comment by michaelmyc** [comment]
@elParaguayo This issue shouldn't be closed. It clearly hasn't been fixed yet. 

For me, there is overlap in the icons when the bar background is set to a solid color (as shown in the original screenshots). Apparently, some reported that this issue does not happen on Fedora. I wonder if some newer versions of qtile or picom or other relevant packages broke this. It would be great if we could get the package versions on a system without these issues so I could test this theory. 

If I set the bar to have any transparency, the systray icons will have a fully transparent background rather than the transparency set in the bar. This is already documented in the documentation. 

Some reported that it's an issue with picom, but this is actually not the case. I'm experiencing this issue with two different systray icons: NetworkManager, and ibus. NetworkManager seems to be fixed when I kill picom, but ibus still exhibits the weird overlaying. I also tried xcompmgr, and I see the same overlaying behavior. 

I ran the following commands as suggested to check depth when using a transparent and a non-transparent background:
```
qtile cmd-obj -o bar top -f eval -a "self.drawer._visual.visual_id"
qtile cmd-obj -o widget systray -f eval -a "self.drawer._visual.visual_id"
```
I'm getting weird results. For non-transparent bar, I'm getting:
```
(True, '33')
(True, '33')
```
For transparent bar, I'm getting:
```
(True, '35')
(True, '35')
```

I'm running qtile 0.22.1 on Arch (EndeavourOS).

**Comment by michaelmyc** [comment]
Also, since I can recreate this issue, I'm happy to assist with testing.

**Comment by elParaguayo** [comment]
Those two numbers are not the depth, they're the ID of the visual being used to display the icons. The bar and the widget should have the same ID which they do so that's good.

Do you have another window manager installed? As System Tray is an X specification, it would be good to know if the same issue arises on that WM too or whether this is because of qtile's implementation.

**Comment by michaelmyc** [comment]
I don't have another window manager, but I installed polybar and polybar's systray doesn't suffer from this issue.

**Comment by michaelmyc** [comment]
I tested polybar with transparency as well. It also doesn't suffer from the semi-transparency issue qtile bar is suffering from. I also tested trayer with and without transparency. No issues for me. I'm digging into polybar source code to see if I can find anything relevant.

**Comment by elParaguayo** [comment]
I suspect they're doing some form of pseudo-transparency where they take the surface underneath the bar and copy that image to the tray.

**Comment by michaelmyc** [comment]
OK, so after a little digging, it seems like polybar is using pseudo-transparency, meaning it draws the at the bottom, and then adds a fully. I believe they are basically creating an illusion that there's semi-transparency, and just using the true transparency. This is likely the technique they're using to achieve transparency: https://en.wikipedia.org/wiki/Pseudo-transparency

Seems like they're drawing the main surface on the main context, and then drawing the background color over the main surface, and then refreshing the windows (tray icons) on top. I haven't used cairo before so I might have gotten some concepts wrong here. 

Here's the source code of how they're redrawing the background: 
![image](https://user-images.githubusercontent.com/15188392/208060153-171f554d-872f-48ea-824d-a64511395466.png)
![image](https://user-images.githubusercontent.com/15188392/208058997-717909d0-852e-46bd-ac83-0413fe0b354f.png)

This PR to disable redrawing the tray when transparency is not present further hints on this process: https://github.com/polybar/polybar/pull/2604

**Comment by michaelmyc** [comment]
> I suspect they're doing some form of pseudo-transparency where they take the surface underneath the bar and copy that image to the tray.

You're absolutely on point.

**Comment by michaelmyc** [comment]
Going to poke around the source code to see if I can hack together something. Need to set up dev environment so I can have a local build running tho.

**Comment by elParaguayo** [comment]
It's complicated, as I recall we need to use the `Composite` function from the XRender extension. 

I might give this another look as it's definitely a suboptimal outcome at the moment but it's probably going to be hard!

**Comment by elParaguayo** [comment]
Also, I think this would need to implemented at the bar level rather than the widget level.

**Comment by elParaguayo** [comment]
I had a working implementation of this a while ago (https://github.com/qtile/qtile/pull/4126). It didn't get merged as we had some other priorities. I can pick this up again after the next release (that's current priority) as it will need to be updated to reflect some other changes to our code.

**Comment by elParaguayo** [comment]
I feel like we should still implement pseudotransparency but I haven't looked at the code in quite a while!
