### ISSUE TITLE
Minimized windows hides from tasklist

### ISSUE THREAD

**Issue by tonich-sh** [qtile/qtile#2953]
# Issue description
Click on task's name in tasklist hides window and removes it's name from tasklist.

introduced with commit:
https://github.com/qtile/qtile/commit/1f3888db8dbe7db03eebeabda096bdcf0e37f209

# Qtile version
master at 2113c9602d545c6340243078b282eb730db6376b

**Comment by yobleck** [comment]
I think I've seen this before. A simple solution might be to create a copy of the layout's window list so that any changes tasklist makes to it's list doesn't affect the layout.
Sort of like:
"""
return self.bar.screen.group.layouts[current_layout].clients_window().copy()
"""
Assuming clients_window is a list (cant check right now)

**Comment by kapilpokhrel** [comment]
As layout removes the minimized window from list, i think we can make a separate list in layouts that contains visible as well as minimized window and using that for tasklist to solve this.

Like :
```diff
# _SimpleLayoutBase example...

def __init__(self):
         self._current_idx = 0
         self.clients = []
+        self.all_clients = []
     




  def add(self, client, offset_to_current=0, client_position=None):
         """
         Insert the given client into collection at position of the current.

         Use parameter 'offset_to_current' to specify where the client shall be
         inserted. Defaults to zero, which means at position of current client.
         Positive values are after the client.

         Use parameter 'client_position' to insert the given client at 4 specific
         positions: top, bottom, after_current, before_current.
         """
         if client_position is not None:
             if client_position == "after_current":
                 return self.add(client, offset_to_current=1)
             elif client_position == "before_current":
                 return self.add(client, offset_to_current=0)
             elif client_position == "top":
                 self.append_head(client)
             else:  # ie client_position == "bottom"
                 self.append(client)
         else:
             pos = max(0, self._current_idx + offset_to_current)
             if pos < len(self.clients):
-                self.clients.insert(pos, client)
+                if client in self.all_clients:
+                    self.append(client)
+                else:
+                    self.clients.insert(pos, client)
+                    self.all_clients.insert(pos, client)
             else:
-                self.clients.append(client)
+                self.append(client)
         self.current_client = client





     def append_head(self, client):
         """
         Append the given client in front of list.
         """
-        self.clients.insert(0, client)
+        if client in self.all_clients:
+            self.append(client)
+        else:
+            self.clients.insert(0, client)
+            self.all_clients.insert(0, client)

     def append(self, client):
         """
         Append the given client to the end of the collection.
         """
-        self.clients.append(client)
+        if client in self.all_clients:
+            self.clients = self.all_clients.copy()
+            for client in self.clients:
+                if client.minimized:
+                    self.clients.remove(client)
+        else:
+            self.clients.append(client)
+            self.all_clients.append(client)

     def remove(self, client):
         """
         Remove the given client from collection.
         """
         if client not in self.clients:
             return
         idx = self.clients.index(client)
         del self.clients[idx]
+        if not client.minimized:
+            del self.all_clients[idx]
         if len(self) == 0:
             self._current_idx = 0
         elif idx <= self._current_idx:
             self._current_idx = max(0, self._current_idx - 1)
```
It seems to work for max, and other layout inherited from _SimpleLayoutBase for now.
What do you think about this?

**Comment by m-col** [comment]
The general idea makes sense. The information about minimised windows is available from the layout's current group. It might be cleaner to get it from there, as there may be places from which that minimised window list would need updating that we haven't thought about. So the tasklist could get the layout-ordered windows from the layout, followed by the group's windows that aren't already accounted for. (I think? I haven't tested anything)

**Comment by kapilpokhrel** [comment]
> The general idea makes sense. The information about minimised windows is available from the layout's current group. It might be cleaner to get it from there, as there may be places from which that minimised window list would need updating that we haven't thought about. So the tasklist could get the layout-ordered windows from the layout, followed by the group's windows that aren't already accounted for. (I think? I haven't tested anything)

can you please explain in detail?

**Comment by m-col** [comment]
>  It might be cleaner to get it from there, as there may be places from which that minimised window list would need updating that we haven't thought about.

Currently layouts are only ever aware of windows that are not minimised. I think making them track minimised windows as well can become confusing as the line between what the layout does (handle positioning of tiled windows on a group) and what the group does (handle a set of windows) becomes less clear. The `Group` provides information that we can use for the tasklist.

So I think it may be as simple as using this like before (in `TaskList.windows()`):
```py
tiled = self.bar.screen.group.layouts[current_layout].get_windows()
```
But then also get the non-tiled windows from the group and combine those lists:
```py
others = [win for win in self.bar.screen.group.windows if win.floating]
return tiled + others
```
Note that `window.floating` is defined as:
```py
    @property
    def floating(self):
        return self._float_state != FloatStates.NOT_FLOATING
```
which actually means "not tiled" and so includes minimised windows as well as visible but floating windows - which I think is actually what we want.

**Comment by kapilpokhrel** [comment]
But this way we would lose the position of the minimized window. For example:
lets say, we created three window, then
```
list in client = [window 1 | window 2 | window 3]
list in group = [window 1 | window 2 | window 3]
```
and when we minimize window window 2
```
list in client = [window 1 | window 3]
list in group = [window 1 | window 2 | window 3]
```
So, the output of tasklist will be: ```[window 1 | window 3 | _window 2]```
but ```[window 1 | _window 2 | window 3]``` is expected.
Anyways this is better than nothing.

**Comment by m-col** [comment]
Why would `[window 1 | window 2 | window 3]` be expected?

**Comment by kapilpokhrel** [comment]
> Why would `[window 1 | window 2 | window 3]` be expected?

Sorry man, till now i was focusing on getting that result LOL. Position of minimized window won't make any difference in navigation, sorry again

**Comment by m-col** [comment]
OK - I'm not sure I follow why that is desirable, as you'll have minimised windows interspersed in the order of windows that reflect the tiled layout, and I thought matching the tiled layout was desirable. What's the final, ideal order of windows in the tasklist including minimised, floating and tiled windows?

**Comment by kapilpokhrel** [comment]
> > It might be cleaner to get it from there, as there may be places from which that minimised window list would need updating that we haven't thought about.
> 
> Currently layouts are only ever aware of windows that are not minimised. I think making them track minimised windows as well can become confusing as the line between what the layout does (handle positioning of tiled windows on a group) and what the group does (handle a set of windows) becomes less clear. The `Group` provides information that we can use for the tasklist.
> 
> So I think it may be as simple as using this like before (in `TaskList.windows()`):
> 
> ```python
> tiled = self.bar.screen.group.layouts[current_layout].get_windows()
> ```
> 
> But then also get the non-tiled windows from the group and combine those lists:
> 
> ```python
> others = [win for win in self.bar.screen.group.windows if win.floating]
> return tiled + others
> ```
> 
> Note that `window.floating` is defined as:
> 
> ```python
>     @property
>     def floating(self):
>         return self._float_state != FloatStates.NOT_FLOATING
> ```
> 
> which actually means "not tiled" and so includes minimised windows as well as visible but floating windows - which I think is actually what we want.

This is good.

**Comment by kapilpokhrel** [comment]
@m-col, are you working on adding this?

**Comment by m-col** [comment]
I'm not - I thought you were :)

**Comment by kapilpokhrel** [comment]
> I'm not - I thought you were :)

Sorry but i am not getting enough time from school nowadays :(

**Comment by m-col** [comment]
No worries at all!
