### ISSUE TITLE
Lazy spawncmd alias support

### ISSUE THREAD

**Issue by Neykuratick** [qtile/qtile#2966]
Hello, i had recently started using Qtile and i've stubled upon an issue that is really bothering me a lot.

Is there any chance i could make lazy.spawncmd run commands in my zshell so it would support all my precious aliases i spent hours to set up?

**Comment by m-col** [comment]
Your .zshrc is only read by zsh's interactive shell, not in command lines or scripts, so they won't have access to your aliases. What you can do instead is add files to your path that replicate aliases, i.e. make a small script (even if it's just one line) to execute a more complex command line, and give a it short name that is more convenient to type into a dialog like the prompt widget.

**Comment by Neykuratick** [comment]
is it possible to make aliases directly in the spawncmd call? Like, pass it as an argument or something

**Comment by m-col** [comment]
Not yet, but I liked the idea and I think others would use it (myself included) so I just implemented it: https://github.com/qtile/qtile/pull/2967

**Comment by elParaguayo** [comment]
My understanding is that it _is_ possible to call aliases from python but it's a bit messy.

You'd need to change these lines:
https://github.com/qtile/qtile/blob/66ce6c282613c4299432a5577e41747b3e7fecbd/libqtile/core/manager.py#L1094-L1095

You have to use:
a) your shell
b) you have to use it in "interactive" mode

So `args` would be something like this:
``` python
args = ["/usr/bin/zsh", "-i", "-c", cmd]
```

I haven't tested it but I think I've seen this before (not on Qtile though).

You wouldn't get tab completion for your aliases though.

**Comment by m-col** [comment]
From what I can tell, running scripts in interactive mode is not recommended as there are side-effects. For example, progams will think they are interactively being run and can change their behaviour, such as asking for a yes/no prompt, which would just make it hang when it isn't actually interactive.
