### ISSUE TITLE
error reload_config: No such command 

### ISSUE THREAD

**Issue by GrosLalo** [qtile/qtile#2971]
### Issue description:

I am using qtile version 0.18.1 on Ubuntu 20.04.3 with X11 as my backend. I have installed qtile by following documentation here http://docs.qtile.org/en/latest/manual/install/index.html#installing-from-source. I am testing the default configuration via Xephyr. So, 

in one terminal i launch Xephyr as such:

`$ Xephyr -br -ac -noreset -screen 1440x900 :1`

And in another terminal i run qtile as so:

`$ DISPLAY=:1 qtile start -c ~/.config/qtile/config.py -l DEBUG`

The window manager gets displayed fine in the virtual display and there are no visible errors in the above terminal. However, when i try to reload the configuration by pressing the key combo (in my case `<super>+CTRL+r`), nothing happens in the display and in the qtile terminal i get this error:

`2021-11-01 07:46:50,597 libqtile manager.py:process_key_event():L361  KB command error reload_config: No such command`

Please find attached the qtile.log which does not tell me much. Any kind of guidance would be most appreciated.

[qtile.log](https://github.com/qtile/qtile/files/7450973/qtile.log)

### 

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Is it possible that when you call `qtile` it is using a version installed onto your path rather than the one in the source folder? Perhaps if you do `./bin/qtile` inside the source folder it might work?

**Comment by stonecharioteer** [comment]
I get this error too. I'm running it locally, not inside a nested X server. (Thanks for Xephyr btw, @GrosLalo, that could be useful)

**Comment by sujaybokil** [comment]
Hii, I am getting this error too, let me know if I can be of any help or if I should also paste my log or sth.

**Comment by stonecharioteer** [comment]
I haven't solved this yet. @sujaybokil

**Comment by sujaybokil** [comment]
Yeah that's cool, I was just asking that since multiple people are having the problem, if pasting my logs or config here could help you resolve the issue.

**Comment by elParaguayo** [comment]
You may need to run qtile in a virtual environment to make sure it picks up the git version of the code rather than the globally installed version.
http://docs.qtile.org/en/latest/manual/hacking.html#setting-up-the-environment

**Comment by stonecharioteer** [comment]
Ah no I figured out what I was doing wrong. I was looking at the latest documents, while I had installed from pypi, so I needed to use `lazy.restart` instead, since `reload_config` is a newer feature. @elParaguayo your comment helped me realize what I was doing wrong. Thanks.

**Comment by m-col** [comment]
`reload_config` is now available in 0.19.0. Can you confirm you have that working for you (if you've updated)?

**Comment by elParaguayo** [comment]
Closing this as I believe the source of the issue was identified. `reload_config` is available in the latest release.
