### ISSUE TITLE
checkupdates widget not refreshing update count after update

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#2977]
Is it possible to reload any widget using cmd-obj? Don't wait for the update time to expire?

**Comment by m-col** [comment]
Something like:
```py
lazy.widget['mpd2'].function(lambda w: w.tick())
```
maybe?

**Comment by krive001** [comment]
No cmd-obj.

**Comment by krive001** [comment]
```
qtile cmd-obj
Specify an object on which to execute command
-o cmd
-o bar
-o group
-o layout
-o screen
-o widget
-o window
-o core
```

**Comment by m-col** [comment]
Ah apologies, wrong interface, but it can be translated to the command-line interface:
```
qtile cmd-obj -o widget mpd2 -f eval -a "self.tick()"
```
However this actually doesn't work, `Mpd2` in this example doesn't have `self.tick`, and it looks like the way the timer is set up in at least this widget (mpd2) it can't be directly updated.

Perhaps someone else has a better idea. What exactly is it you are trying to do? Maybe there is an alternative solution.

**Comment by krive001** [comment]
The checkupdates widget mouse click starts terminal update and when it runs I want the widget to relod.

**Comment by elParaguayo** [comment]
`checkupdates` should update when it's finished. Is it not?

**Comment by krive001** [comment]
Yes

**Comment by elParaguayo** [comment]
OK. Just so I understand you're saying:
- The widget shows a number of updates pending
- You click to install the updates
- Once the installation has finished, the number does not change

Is that correct? If so, I'll rename this thread as that would be a bug in the widget that should be fixed.

**Comment by krive001** [comment]
Yes.  Because of this, I don't always want to issue the qtile cmd-obj -o cmd -f reload_config command.
Only for that widget

**Comment by krive001** [comment]
```
def open_update():
    qtile.cmd_spawn(term + ' -e updatepackage')


def open_update_notify():
    qtile.cmd_spawn("notify-qtile-update")


check_update = widget.CheckUpdates(
    distro="Arch_paru",
    no_update_string="0",
    display_format="{updates:>2}",
    mouse_callbacks={
        'Button1': open_update,
        'Button3': open_update_notify
    },
    update_interval=600,
)
```
Eu pedig az updatepackage

```
cat $(which updatepackage)
#!/bin/sh

printf "Beginning upgrade.\\n"

paru -Syyu

printf "\\nUpgrade complete.\\nPress <Enter> to exit window.\\n\\n"
read -r
```

qtile --version
0.18.2.dev77+g20c1d031

**Comment by elParaguayo** [comment]
Ah.

The widget doesn't update from `mouse_callbacks`. Your update command should go in `custom_command` (you need to delete the `Button1` mapping too). It will then update when you're finished.

**Comment by krive001** [comment]
I look forward to an update. Maybe that's how it will work.
```
check_update = widget.CheckUpdates(
    distro="Arch_paru",
    execute=term + ' -e updatepackage',
    no_update_string="0",
    display_format="{updates:>2}",
    mouse_callbacks={
        # 'Button1': open_update,
        'Button3': open_update_notify
    },
    update_interval=600,
)
```

**Comment by elParaguayo** [comment]
Sorry, yes, `custom_command` is the command for checking updates. `execute` is for installing updates.

**Comment by krive001** [comment]
That's how it works. Thank you sir.
However, the display_format is incorrect.
Consider updating the checkupdates widget like this:

```
 def _check_updates(self):
        # type: () -> str
        try:
            updates = self.call_process(self.cmd, shell=True)

        except CalledProcessError:
            updates = ""
        num_updates = self.custom_command_modify(len(updates.splitlines()))

        if num_updates < 0:
            num_updates = 0
            return self.display_format.format(**{"updates": num_updates})
        if num_updates == 0:
            self.layout.colour = self.colour_no_updates
            return self.display_format.format(**{"updates": self.no_update_string})
        num_updates = str(num_updates)

        if self.restart_indicator and os.path.exists('/var/run/reboot-required'):
            num_updates += self.restart_indicator

        self.layout.colour = self.colour_have_updates
        return self.display_format.format(**{"updates": num_updates})
```

best regards

**Comment by elParaguayo** [comment]
Can you explain what you mean by "the display_format" is incorrect. I can't do much with that information and the function shouldn't really need a rewrite (although I can't tell what changes you've made here).

**Comment by elParaguayo** [comment]
That's the default for the widget. What do you want it to display?

**Comment by krive001** [comment]
Yes, but the text does not appear.

**Comment by elParaguayo** [comment]
Help me out. What text does not appear?

The widget works by running the command to check the number of updates, counts the number of lines in the output, adjusts this number to remove non-update lines and then displays that number.

**Comment by krive001** [comment]
I have since rewritten this:
```
display_format="update: {updates:>2}"
```
and update: text does not appear.

**Comment by elParaguayo** [comment]
Are you talking about when the value is "0"? If so, you set this via `no_update_string`. That value is not meant to be formatted via `display_format` as some people will leave `no_update_string` blank so the widget is hidden when there are no updates.

**Comment by krive001** [comment]
The function stops here and does not return display_fornat.
```
if num_updates == 0:
            self.layout.colour = self.colour_no_updates
            return self.no_update_string
```

That would be right:
```
if num_updates == 0:
            self.layout.colour = self.colour_no_updates
             num_updates = self.no_update_string
```

**Comment by elParaguayo** [comment]
No, your change is not correct.

The `_check_updates" function returns the string to be displayed by the widget.

If the number is zero, it returns `self.no_update_string` which, as mentioned above, is not meant to be formatted by `display_format` and so is not the value to be set in `num_updates`.

Where the number is greater than zero then num_updates uses this value and will format `display_format` accordingly.

If you want it to say "Updates: 0" when there are no updates then set `no_update_string` to `"Updates: 0"`.

**Comment by elParaguayo** [comment]
Assuming you're ok with the above, are we able to close this?

**Comment by krive001** [comment]
Yes. It's a bit of a weird approach, but I understand your thoughts.
I instantiated a class, config.py, and changed the function.
Yes, we can consider it solved.
Thanks

**Comment by elParaguayo** [comment]
I'm not sure it's a weird approach. If someone wants to hide the widget completely, or say "No updates" when `num_updates` is 0, they can't do it with `display_format` because that would use the same format for any number of updates including 0.

Separating `no_update_string` gives you greater flexibility on how the widget is displayed.

However, you are absolutely welcome to subclass the widget as you see fit so I'm pleased that that's working for you.
