### ISSUE TITLE
Problem at starting qtile

### ISSUE THREAD

**Issue by sercus** [qtile/qtile#2979]
Hello, I've been installing arch on a pc and everything was fine, but then I restarted it and now if I try to log in it does log in for a second but then it brings me back to the log in. I already had this problem and it worked by changing the qtile config to the default. But I tried the same this time and nothing changed, and in the xsession-errors this is what I get:

Could not get bg groups from config file.
Can't find file browser: 'xdg-open'. You may want to change the value for the '-f' option.
[ 11/04/21 23:13:50.326 x_new_id FATAL ERROR ] We seems to have run of XIDs. This is either a bug in the X server, or a resource leakage in the compositor. Please open an issue about this problem. The compositor will die.

I'm not quite sure what my problem is but when I get a "FATAL ERROR" and "please open an issue about this problem", well, then I'm scared. I hope somebody can help me out here or place this issue in the right place, thanks in advance.

**Comment by m-col** [comment]
Hey, sounds pretty bad! Are you launching X manually with `startx` or are you starting it with a log-in [display manager](https://en.wikipedia.org/wiki/X_display_manager)?

Please could you post any relevant lines from your logs in ~/.local/share/qtile?

**Comment by sercus** [comment]
Indeed it sounds bad, I've installed arch in other pc's but this is my first "fatal error". The log in and start happens with lightdm and from the logs... oh my, why did I look in the log?? I could send it to you but the file is made of 640 lines of errors. I think that it's going to be better if I just reinstall arch. :')

**Comment by m-col** [comment]
It's good to find the root cause though just in case it happens again!

Maybe just paste the last 50 lines or so? The error will likely appear there as it is what caused the crash and so would be the last thing logged

**Comment by sercus** [comment]
Sure, I leave here the last 50 lines of the "qtile.log" file:

  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-11-04 11:52:41,914 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-11-04 11:52:41,916 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 234, in async_loop
    self.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 272, in finalize
    self.core.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 172, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-11-04 11:52:41,916 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate


I emptied this file and tried to log in again to see if I would get so many errors or a lot less, but after try to log in nothing came into this file. I tried the same with the "xsession-errors" and I this time I just gt the first 2 lines as before, nothing about a fatal error:

Could not get bg groups from config file.
Can't find file browser: 'xdg-open'. You may want to change the value for the '-f' option.

**Comment by sercus** [comment]
I also found the lightdm.log so I'll put it here too, i'm not an expert here, so I'm not really sure about what the problem is but it seems like the proble is with X server o maybe if I reinstall the X11 and xorg files and intall it again it may work, not really sure about it but anyways, I'll leave here the lightdm log:

[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=343
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.00s] DEBUG: Monitoring logind for seats
[+0.00s] DEBUG: New seat added from logind: seat0
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.00s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.00s] DEBUG: Seat seat0: Starting
[+0.00s] DEBUG: Seat seat0: Creating greeter session
[+0.00s] DEBUG: Seat seat0: Creating display server of type x
[+0.00s] DEBUG: Could not run plymouth --ping: Failed to execute child process “plymouth” (No such file or directory)
[+0.00s] DEBUG: Using VT 7
[+0.00s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.00s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.00s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0
[+0.00s] DEBUG: XServer 0: Launching X Server
[+0.00s] DEBUG: Launching process 349: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.00s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.00s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.00s] WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
[+0.00s] DEBUG: Loading user config from /etc/lightdm/users.conf
[+0.01s] DEBUG: User ser added
[+1.09s] DEBUG: Got signal 10 from process 349
[+1.09s] DEBUG: XServer 0: Got signal from X server :0
[+1.09s] DEBUG: XServer 0: Connecting to XServer :0
[+1.17s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+1.17s] DEBUG: Session pid=365: Started with service 'lightdm-greeter', username 'lightdm'
[+1.18s] DEBUG: Session pid=365: Authentication complete with return value 0: Success
[+1.18s] DEBUG: Seat seat0: Session authenticated, running command
[+1.18s] DEBUG: Session pid=365: Running command /usr/bin/lightdm-gtk-greeter
[+1.18s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+1.18s] DEBUG: Session pid=365: Logging to /var/log/lightdm/seat0-greeter.log
[+1.30s] DEBUG: Activating VT 7
[+1.30s] DEBUG: Activating login1 session c1
[+1.30s] DEBUG: Seat seat0 changes active session to c1
[+1.30s] DEBUG: Session c1 is already active
[+1.44s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
[+1.54s] DEBUG: Greeter start authentication for ser
[+1.54s] DEBUG: Session pid=402: Started with service 'lightdm', username 'ser'
[+1.54s] DEBUG: Session pid=402: Got 1 message(s) from PAM
[+1.54s] DEBUG: Prompt greeter with 1 message(s)
[+5.56s] DEBUG: Continue authentication
[+5.56s] DEBUG: Session pid=402: Authentication complete with return value 0: Success
[+5.56s] DEBUG: Authenticate result for user ser: Success
[+5.56s] DEBUG: User ser authorized
[+5.57s] DEBUG: Greeter requests session qtile
[+5.58s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
[+5.58s] DEBUG: Terminating login1 session c1
[+5.58s] DEBUG: Session pid=365: Sending SIGTERM
[+5.59s] DEBUG: Greeter closed communication channel
[+5.59s] DEBUG: Session pid=365: Exited with return value 0
[+5.59s] DEBUG: Seat seat0: Session stopped
[+5.59s] DEBUG: Seat seat0: Greeter stopped, running session
[+5.59s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+5.59s] DEBUG: Session pid=402: Running command /etc/lightdm/Xsession qtile start
[+5.59s] DEBUG: Creating shared data directory /var/lib/lightdm-data/ser
[+5.59s] DEBUG: Session pid=402: Logging to .xsession-errors
[+5.68s] DEBUG: Activating VT 7
[+5.68s] DEBUG: Activating login1 session 2
[+5.68s] DEBUG: Seat seat0 changes active session to 
[+5.69s] DEBUG: Seat seat0 changes active session to 2
[+5.69s] DEBUG: Session 2 is already active
[+47.81s] DEBUG: Session pid=402: Exited with return value 1
[+47.81s] DEBUG: Seat seat0: Session stopped
[+47.81s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+47.81s] DEBUG: Sending signal 15 to process 349
[+47.83s] DEBUG: Seat seat0 changes active session to 
[+48.25s] DEBUG: Process 349 exited with return value 0
[+48.25s] DEBUG: XServer 0: X server stopped
[+48.25s] DEBUG: Releasing VT 7
[+48.25s] DEBUG: XServer 0: Removing X server authority /run/lightdm/root/:0
[+48.25s] DEBUG: Seat seat0: Display server stopped
[+48.25s] DEBUG: Seat seat0: Active display server stopped, starting greeter
[+48.25s] DEBUG: Seat seat0: Creating greeter session
[+48.25s] DEBUG: Seat seat0: Creating display server of type x
[+48.25s] DEBUG: Using VT 7
[+48.25s] DEBUG: Seat seat0: Starting local X display on VT 7
[+48.25s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+48.25s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0
[+48.25s] DEBUG: XServer 0: Launching X Server
[+48.25s] DEBUG: Launching process 501: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+48.25s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+49.07s] DEBUG: Got signal 10 from process 501
[+49.07s] DEBUG: XServer 0: Got signal from X server :0
[+49.07s] DEBUG: XServer 0: Connecting to XServer :0
[+49.17s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+49.17s] DEBUG: Session pid=506: Started with service 'lightdm-greeter', username 'lightdm'
[+49.18s] DEBUG: Session pid=506: Authentication complete with return value 0: Success
[+49.18s] DEBUG: Seat seat0: Session authenticated, running command
[+49.18s] DEBUG: Session pid=506: Running command /usr/bin/lightdm-gtk-greeter
[+49.18s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+49.18s] DEBUG: Session pid=506: Logging to /var/log/lightdm/seat0-greeter.log
[+49.29s] DEBUG: Activating VT 7
[+49.29s] DEBUG: Activating login1 session c2
[+49.29s] DEBUG: Seat seat0 changes active session to c2
[+49.29s] DEBUG: Session c2 is already active
[+49.35s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
[+49.39s] DEBUG: Greeter start authentication for ser
[+49.39s] DEBUG: Session pid=543: Started with service 'lightdm', username 'ser'
[+49.40s] DEBUG: Session pid=543: Got 1 message(s) from PAM
[+49.40s] DEBUG: Prompt greeter with 1 message(s)
[+53.34s] DEBUG: Continue authentication
[+53.35s] DEBUG: Session pid=543: Authentication complete with return value 0: Success
[+53.35s] DEBUG: Authenticate result for user ser: Success
[+53.35s] DEBUG: User ser authorized
[+53.35s] DEBUG: Greeter requests session qtile
[+53.35s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
[+53.35s] DEBUG: Terminating login1 session c2
[+53.36s] DEBUG: Session pid=506: Sending SIGTERM
[+53.36s] DEBUG: Greeter closed communication channel
[+53.36s] DEBUG: Session pid=506: Exited with return value 0
[+53.36s] DEBUG: Seat seat0: Session stopped
[+53.36s] DEBUG: Seat seat0: Greeter stopped, running session
[+53.36s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session1
[+53.36s] DEBUG: Session pid=543: Running command /etc/lightdm/Xsession qtile start
[+53.36s] DEBUG: Creating shared data directory /var/lib/lightdm-data/ser
[+53.36s] DEBUG: Session pid=543: Logging to .xsession-errors
[+53.37s] DEBUG: Activating VT 7
[+53.37s] DEBUG: Activating login1 session 5
[+53.37s] DEBUG: Seat seat0 changes active session to 
[+53.37s] DEBUG: Seat seat0 changes active session to 5
[+53.37s] DEBUG: Session

**Comment by sercus** [comment]
> @sercus Are you managed to fix it?

Yes and no I'd say. Tried to find a solution there but nothing worked so I reinstalled arch from the beginning, it worked fine after it.
