### ISSUE TITLE
Unable to move active window to another screen

### ISSUE THREAD

**Issue by Neykuratick** [qtile/qtile#2993]
deleted

**Comment by elParaguayo** [comment]
What error messages are you getting?

`togroup` takes the group name as an argument, not the group object. 

Also, `togroup` is the method when calling `lazy.window.togroup`. However, when not using `lazy` you need to do `qtile.current_window.cmd_togroup(group_name)`.

NB you can't call `lazy` functions from within another function. They can only be bound to keys, mouse buttons and (recently) widget mouse callbacks.

**Comment by elParaguayo** [comment]
Also, FYI - I'm working on improving the documentation about this as there are definitely some gaps which are not helpful here.

**Comment by Neykuratick** [comment]
yes, i have already realized my fail. I'm so sorry for this thread, this was just my stupid mistake

**Comment by Neykuratick** [comment]
This is my function to move window to another physical screen in qtile in case if anyone in the future will be as inattentive as i am

```
def move_current_window_to_screen(qtile, screen):
    screen_id = [2, 0, 1]
    group = qtile.screens[screen_id[screen]].group
    qtile.current_window.togroup(group.name)
```
