### ISSUE TITLE
cannot import name 'BatterySate' from 'libqtile.widget.battery'  and Hooks not working

### ISSUE THREAD

**Issue by emanuelep57** [qtile/qtile#2995]
### The bug:

Hello everyone, I am on Endeavours OS, on Thinkbook 15. I installed qtile from the official repos with pacman -S qtile.  I was checking out the qtile examples, I copied the code of the class MyBattery from [m-col](https://github.com/m-col/qtile-config/blob/7647bc881eaf1a717377819e6f0ee331600f1a36/config.py).

I receive this error :  **from libqtile.widget.battery import Battery, BatterySate
ImportError: cannot import name 'BatterySate' from 'libqtile.widget.battery' (/usr/lib/python3.9/site-packages/libqtile/widget/battery.py**) . _I made sure the class BatteryState existed in the given path._

Also hooks apparently don't work for me except startup_once one, maybe I am doing something wrong (probably) but I tried also copying the code of the hook from examples and still doesn't work.

**Here is some code I tried:**

@hook.subscribe.startup
def startup():
    execute_once('bspmode')
    execute_once('firefox')

@hook.subscribe.startup
def _():
    # Set up initial GroupBox visible groups
    if len(qtile.screens) > 1:
        groupboxes[0].visible_groups = ['1', '2', '3']
    else:
        groupboxes[0].visible_groups = ['1', '2', '3', 'q', 'w', 'e']

@hook.subscribe.startup
def _():
    lazy.spawn("firefox")

**None** of these actually works. I also tried disabling the other hook, but nothing.

### 

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
First error is a typo. You've written `BatterySate` not `BatteryState`.

As for the hooks, we'll need more info other than they're "not working". We'd need to see your whole config and the error messages you're getting but note, you can't put a `lazy` command inside a function. You could do `qtile.cmd_spawn("firefox")`.

**Comment by emanuelep57** [comment]
Well this kind of solved all the issues I was having, thank you! By the
way, how do I know if something can't be used in hooks?

**Comment by elParaguayo** [comment]
The documentation is not clear about how to use `lazy` so it's understandable that you tried it. 

Fixing the documentation is on my to do list.

If your issues are fixed, please close the thread.
