### ISSUE TITLE
[wayland] wrong screen definition with default config

### ISSUE THREAD

**Issue by pescepalla** [qtile/qtile#3000]
### The bug:

I logged into qtile (wayland) with a clean config.py. 

The systray widget crashes and qtile fails to manage the rightmost fourth of the screen (no wallpaper and no bar).

For the record, my screen is a 1366 x 768 and this only happens for me in wayland: X11 qtile does not have this issue.

Apologies for the photo but `grimshot` would only grab the part managed by qtile and not the whole screen:

![IMG_20211109_195450](https://user-images.githubusercontent.com/46329185/140988402-c409f94a-d277-4d40-9a3b-3c5287a254b6.jpg)

Some applications, e.g. firefox, make use of the space, but others, e.g. alacritty, don't.

qtile version is 0.18.1

[qtile.log](https://github.com/qtile/qtile/files/7507359/qtile.log)

### 

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Don't worry about Systray. It's not compatible with Wayland (as it's an X11 specification). We're working on a neat way to remove it from the default configuration. 

The screen size is odd, however. Probably needs our resident Wayland expert @m-col to look at that one!

**Comment by pescepalla** [comment]
It was my fault after all. I had left an `xrandr` line in my profile. Deleting that solved the issue!
