### ISSUE TITLE
widget.KeyboardLayout - cannot call next_keyboard()

### ISSUE THREAD

**Issue by marcello42** [qtile/qtile#3005]
With following conig in top.Bar

                widget.KeyboardLayout(
                    configured_keyboards=['us', 'us intl', 'us colemak_dh_iso'],
                    display_map={'us colemak_dh_iso': 'COLEMAK'},
                    fmt=' {}',
                    ),

it is possible to switch the keyboard layouts via clicking the widget in the Bar, but as soon as I add:

Key([mod], “space”, lazy.widget[“keyboardlayout”].next_keyboard(), desc=”Next keyboard layout.”),

into keys

the config is not loadable via lazy.restart()

**Comment by m-col** [comment]
Do you get any log output when trying to restart?

**Comment by marcello42** [comment]
@m-col .. nope.. but to be fair I do not see where I could see the stdout/stderr whilst reloading the config file

**Comment by elParaguayo** [comment]
You need to look in your log. Have a look in `~/.local/share/qtile/qtile.log`.

**Comment by marcello42** [comment]
2021-11-11 12:49:20,350 ERROR libqtile manager.py:cmd_restart():L1043 Preventing restart because of a configuration error: invalid character '“' (U+201C) (config.py, line 92)

**Comment by marcello42** [comment]
ok I found the problem.. thanks guys..

The problem was, that whilst copying from the docu there was another quote char:

“ instead of "

**Comment by elParaguayo** [comment]
Great.

Where did you copy it from? If you post the link, we can fix it.

**Comment by marcello42** [comment]
@elParaguayo sure it was in the latest:

https://docs.qtile.org/en/latest/manual/ref/widgets.html#keyboardlayout

**Comment by elParaguayo** [comment]
The docs are generated from the source code so it's the same bug.

Thanks for reporting. Will get this fixed.

**Comment by marcello42** [comment]
after giving it a second look the examples for the keyboardlayouts itself have the same issue with the single quotes.. I did not encounter that since I typed them by hand instead of copying but at a closer look they also look different. Perhpas this could also be a problem for other people who try to copy from there.

**Comment by marcello42** [comment]
if I can support furthere here please let me know

**Comment by ashroyxi** [comment]
i fixed the quote, still not working. no error on logs either.
