### ISSUE TITLE
[question] Getting app ID under Wayland

### ISSUE THREAD

**Issue by pescepalla** [qtile/qtile#3021]
Is there a way to obtain app IDs under Wayland similar to X11's `xprop` or Sway's `swaymsg -t get_tree` 

Or is there an alternative way I can Match applications to their own Group?

**Comment by pescepalla** [comment]
test

**Comment by m-col** [comment]
There is no convenient API for this yet but the app ID is what is returned by `Window.get_wm_class()`, which means you can do:
```
qtile cmd-obj -o window -f eval -a "self.get_wm_class()"
```
and this will show the app ID of the current window. You could prefix it with `sleep 3 &&` and focus the window you want to get that window's app ID.

I'm currently working on implementing the wlr_foreign_toplevel_management_v1 protocol in Qtile, which would let Qtile make this kind of information available in a generic way. This could then be fetched with a tool that uses this protocol, such as [wlrctl](https://git.sr.ht/~brocellous/wlrctl).

**Comment by pescepalla** [comment]
Thanks a lot!

**Comment by m-col** [comment]
I finished up implementing the wlr_foreign_toplevel_management_v1 protocol so this will likely be available in the next release: #3026
