### ISSUE TITLE
They rolled a huge bug from this commit

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#3025]
They rolled a huge bug from this commit
commit number: ~57f0963fbd63f1c32b383412bc9bbc093b38dc22~
diff:
[bugstart.txt](https://github.com/qtile/qtile/files/7534240/bugstart.txt)

**Comment by m-col** [comment]
Sorry it's not clear what the bug is - could you add a bit more detail? Thanks.

**Comment by krive001** [comment]
~/.local/share/qtile/qtile.log

Reload two.
```
for x in qtile.widgets_map:
    logger.warning(f"map: {x}")
```
output ``cat ~/.local/share/qtile/qtile.log
Good: `WARNING libqtile config.py:<module>():L538 map: systray`
Error: ` WARNING libqtile config.py:<module>():L538 map: <no name>`

**Comment by elParaguayo** [comment]
That's not a huge bug. That's a log message that you've inserted.

What's the actual problem that you're having?

Yes, Systray widget currently shows as `<no name>` but I'm not sure why that matters.

**Comment by krive001** [comment]
Yes, but how do you draw a window, a non-existent widget?
