### ISSUE TITLE
firefox becomes unresponsive every time i get a mail

### ISSUE THREAD

**Issue by Lunatik00** [qtile/qtile#3032]
I use the firefox addon "Checker Plus for Gmail" and every single time i get a mail firefox stops responding for a few seconds (10 to 30) or until i restart firefox (if it takes too much i have to restart the application), this is not a problem while using awesome or kde, it only happens on qtile, so there is no other possible cause. I use lazy.spawn("rofi -show drun") to open firefox currently, but it also happens in the default configuration

>qtile --version
>0.18.1

**Comment by m-col** [comment]
Sounds like you need a notification server running, such as `dunst`.

**Comment by Lunatik00** [comment]
> Sounds like you need a notification server running, such as `dunst`.

as i said, it only happens in qtile, and i think awesome have even less things done out of the box, the reason i can think is the single thread nature of python when it is not specified otherwise and that in some part that creates the problem, but LUA also is single threaded and i don't have any problem in awesome even when opening many things using a python file.

**Comment by m-col** [comment]
Could you post your config?

**Comment by m-col** [comment]
> as i said, it happens whit the default config

**Comment by m-col** [comment]
> as i said, it happens whit the default config

Oops sorry yep.

**Comment by m-col** [comment]
Do you get any log output when it happens?

**Comment by m-col** [comment]
Possible duplicate? https://github.com/qtile/qtile/issues/1956

**Comment by Lunatik00** [comment]
> Do you get any log output when it happens?

no, i don't know when i am going to get a mail and i usually am  doing something totally unrelated, so i need to get back to what i was doing immediately, hence the restart firefox solution, it is not the better choice, but is the fastest

**Comment by m-col** [comment]
The logs will persist in the log file at `~/.local/share/qtile/qtile.log`, take a look in there and see if there is anything happening that looks suspicious

**Comment by Lunatik00** [comment]
> Possible duplicate? #1956

not exactly, in that case the app still responds but it is not displayed, in this case it is just not responding at all, i know it because i was in a meeting once when it freeze, i didn't heard the audio and they didn't heard me

**Comment by Lunatik00** [comment]
>  `~/.local/share/qtile/qtile.log`

by hour and because i saw the same error a few times i think it is this one 

2021-11-14 15:00:57,

> 717 ERROR libqtile base.py:_wrapper():L307 got exception from widget timer
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 305, in _wrapper
>     method(*method_args)
>   File "/usr/lib/python3.9/site-packages/libqtile/widget/quick_exit.py", line 61, in update
>     self.text = self.countdown_format.format(self.countdown)
>   File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 361, in text
>     self.layout.text = self.formatted_text
>   File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 72, in text
>     self.layout.set_attributes(attrlist)
>   File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 115, in set_attributes
>     pango.pango_layout_set_attributes(self._pointer, attrs)
> TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
> 2021-11-14 15:00:57,721 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate

**Comment by Lunatik00** [comment]
but i should add that after a time or after i close firefox the notification is shown normally

**Comment by m-col** [comment]
Do you mean one of firefox's own notification windows?

Could you try using a notification service like dunst or the `Notify` widget to see what difference that makes to behaviour?

**Comment by Lunatik00** [comment]
> Do you mean one of firefox's own notification windows?
> 
> Could you try using a notification service like dunst or the `Notify` widget to see what difference that makes to behaviour?

I have no idea what backend program is running to show the notification, what i know is that this behavior doesn't happen in awesome or KDE, so the only point that is different when it freezes is qtile itself, if it helps, can you tell me how to determine what is the program?, i think i will eventually just use a standalone program to manage my mail, this has been just more convenient until now, but i prefer if i can help to solve this for others before doing that change

**Comment by m-col** [comment]
> if it helps, can you tell me how to determine what is the program?

I'm not sure, but sometimes don't use a notification service and when I do not, firefox detects this and creates its own notification windows, which it has complete control over.

> what i know is that this behavior doesn't happen in awesome or KDE

While I realise awesome doesn't have a notification service so there *shouldn't* be any difference here, there is a difference (the bug), so checking to see if the behaviour changes when we add a notification service can help track it down.

**Comment by Lunatik00** [comment]
> ification service and when I do not, firefox detects this and creates its own notification windows, which it has complete control over.
> 
> > what i know is that this behavior doesn't happen in awesome or KDE
> 
> While I realise awesome doesn't have a notification service so there _shouldn't_ be any difference here, there is a difference (the bug), so checking to see if the behaviour changes when we add a notification service can help track it down.

ok, weirdly enough the last mails i have receive have not triggered this issue, and now that i think about it the one i quoted can't be, because it is a different day, it might be the hell of an erratic behavior and i might have tuned out the rest of the notifications because they are not important and have not interfered with what i am doing, and right now i am paying attention. Since i know i got the error a little while before this happening it has to be this one

> 
> 2021-11-15 19:27:22,184 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns
> 2021-11-15 19:27:22,185 ERROR libqtile group.py:layout():L122 No such layout: columns

Or the error is not shown in the log because it is some loop and a bug, but not an error.
By the way, that error is shown multiple times in the log, it was not me trolling or anything like that.

**Comment by m-col** [comment]
I think those errors appear when you use the group's `setlayout` command i.e. with `lazy.group.setlayou("columns")`. Are you using that? I'm not sure it is related though.

**Comment by Lunatik00** [comment]
> I think those errors appear when you use the group's `setlayout` command i.e. with `lazy.group.setlayou("columns")`. Are you using that? I'm not sure it is related though.

I am not using that, the only lazy.group in my config is the one from the default config to switch groups

```
Key([mod], i.name, lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),
```

And the only layouts i have active right now are float and max

**Comment by Lunatik00** [comment]
Well, i have not used qtile in a while, today i had the space to check a few things and i have not encountered the problem, it might be completely random, the important part is that i doubt is something in the code itself.

**Comment by m-col** [comment]
OK, no worries. If you're happy that the issue has faded into obscurity, feel free to close the issue.
