### ISSUE TITLE
Feature request: allow windows from the same group to be present on multiple screens (i.e.allow groups to span screens)

### ISSUE THREAD

**Issue by raj-magesh** [qtile/qtile#3034]
This requires groups not to be bound to a particular screen.

This would open up a workflow where switching groups would update windows on all monitors, allowing rapid context-switching. As an example, I want group A to contain windows A1, A2, A3, and A4, with A1 and A2 on monitor M1 and A3 and A4 to be on monitor M2. When I switch to group B, I want B1 and B2 on monitor M1 and B3 and B4 on monitor M2.

This could be added as an optional parameter when creating the group so that users can choose whether the group should be bound to one screen at a time or not.

While I could combine multiple physical monitors into a single screen using xorg, that would mess up tiling boundaries and would depend too strongly on the physical layout of the monitors.

**Comment by elParaguayo** [comment]
What you could do is write a function that means when you open group X on one screen, group Y is automatically opened on the other screen.

You can use hooks to ensure the function is called whenever groups change. 

Having groups span screens would be harder!

**Comment by raj-magesh** [comment]
I did consider that but it would double the number of groups and mess up some semantics. I guess I could use an extra modifier when moving windows to the corresponding group on the other screen.

I can definitely imagine that it'd be hard to implement this (seems like a very low-level change), so feel free to close the issue if you aren't planning on adding this.

**Comment by elParaguayo** [comment]
There are no immediate plans to implement this (at least, _I'm_ not looking to). 

I'll move this to a discussion for now in case anyone else wants to add their thoughts (which are always welcome).
