### ISSUE TITLE
The qtile bar doesnt have a wm_class

### ISSUE THREAD

**Issue by biscuitrescue** [qtile/qtile#3041]
i was trying to exclude it out of picom but the bar doesnt have a wm_class.
![image](https://user-images.githubusercontent.com/67876678/142752758-bdb758c0-59d7-4396-bfc7-18cfee95c76d.png)

**Comment by elParaguayo** [comment]
This has been asked before. Have a look at #2526.

**Comment by biscuitrescue** [comment]
thank you so much that worked
