### ISSUE TITLE
Shell makes command input difficult

### ISSUE THREAD

**Issue by alethiophile** [qtile/qtile#3058]
The shell input parser in sh.py uses a naive regex to identify command invocations, which results in severely truncating the useful inputs one can pass to commands. For instance, the `eval` command is meant to be passed strings of arbitrary Python code, but almost all useful Python will fail to match the regex `[\w\s,]*`. Thus, `eval` in the shell is mostly useless.

https://github.com/qtile/qtile/blob/da93518b2ab924e803552decdb364d64de46088d/libqtile/sh.py#L318

I would propose using a real parser here, ideally allowing any Python data to be passed as command arguments.

**Comment by elParaguayo** [comment]
What do you mean by "any Python data"?

Remember, `sh.py` is using IPC to communicate with the Qtile session which limits what can be sent from the client to the server. Trying to send complex objects will likely result in an error.

I would also disagree that `eval` in the shell is mostly useless. It's very helpful for debugging!

**Comment by m-col** [comment]
The shell is limited to the set of exposed commands and it's not really suitable for more complex logic. If you want a more rich Pythonic interface you can check out the Python interface: http://docs.qtile.org/en/latest/manual/commands/scripting.html

Note that this also doesn't support arbitrary transfer of Python objects. I'm also not sure it should - it's quite a niche use-case but adds a lot of complexity. If this kind of functionality is needed, you can implement the arbitrary Python logic inside your config and then use trigger out from elsewhere e.g. a keybinding.

If this doesn't quite cover the use cases that you have in mind, could you give an example of what it is you'd be wanting to implement?

**Comment by elParaguayo** [comment]
Closing this as I believe it's answered but feel free to re-open if you disagree.
