### ISSUE TITLE
Widgets are causing bar to glitch when text updates

### ISSUE THREAD

**Issue by matheusfillipe** [qtile/qtile#3062]
It's been a while I didn't pull qtile and I noticed this constant flicking caused but widget updates on my bars. I tried to record it but the flickering doesn't get recorded, it might be too fast. 

I don't have enough time to bisect this now and I believe someone might know what has changed. This flickering is very distracting and bad for my eyes. It seems that it only happens when there is a text resize, doesn't happen when just the text changes without the need of resizing. It looks like a glitch.

Happens on:
da93518b2ab924e803552decdb364d64de46088d

Didn't back happen on:
d8c00aae90d551fa2c326b2bd07d331d66ded04e

Tested under X11, wayland not tested.

**Comment by elParaguayo** [comment]
Can you post your config so we can see what widgets you're using. Can you also try default config and see if there's still an issue.

It's not something that I've noticed but I'm happy to look into it and see if I can recreate.

**Comment by matheusfillipe** [comment]
I tried recreating with a minimal config on Xephyr with widgets with gradient colors for foreground and background that change with (specifically Net, CPU and Memory), but I couldn't reproduce. My whole config where this is happening is huge ~mess~ https://gitlab.com/matheusfillipeag/dotfiles/-/blob/master/.config/qtile/config.py. 

But I took a little time to bisect it and found out that this problem happens since: 6f41e52e "Add borders to Bar" commit.

If it matters I using nvidia proprietary drivers, my widget foreground and backgrounds are all gradients and using the default "sans" font.

The glitch only happens when the text has to resize. If I change to consolas font just for the problematic widgets like this, the glitch is gone:

```python
        widget.Net(
            font="consolas",
            fontsize=18,
            interface="wlp3s0",
            update_interval=1,
            margin=5,
            format="<b>↓{down:<3}  ↑{up:<3}</b>",
        ),
        widget.CPU(
            font="consolas",
            fontsize=18,
            format="<big>🖥</big><b>{load_percent:5.2f}</b>%",
        ),
        widget.Memory(
            font="consolas",
            fontsize=18,
            prefix_text="🖬",
            measure_mem="G",
            format="<b>{MemUsed:2.0f}</b>/{MemTotal:2.0f}{mm}",
        ),
```

If I change the font to something like "sans" then the glitch is back.

Maybe you are able to reproduce just with that? Sorry for not providing an actual proper minimal config to reproduce this, but was surely on that commit, which doesn't seem small.

**Comment by elParaguayo** [comment]
I did wonder if it was (my) bar border commit.

I'll see if I can take a look at some point.

**Comment by elParaguayo** [comment]
I just quickly tried those widgets with commenting out the font name. I don't get any glitching of the bar when the widgets change width.

**Comment by elParaguayo** [comment]
That config file is quite something!

I'll really need a minimal config that recreates this to go any further here. I'm not going to be able to use your config file.

**Comment by matheusfillipe** [comment]
I'm sorry, don't even look on that config :P 

I am pretty sure it is related to or at least happens mostly when there are those width changes. Maybe it has something to do with color gradients, I have those as well. Maybe try with something like this:

```python
        widget.Net(
            font="sans",
            fontsize=14,
            interface="wlp3s0",
            foreground=["#dddddd", "#ffffff"],
            background=["#8c008c", "#613553"],
            update_interval=1,
            margin=5,
            format="<b>↓{down}  ↑{up}</b>",
        ),
        widget.CPU(
            font="sans",
            fontsize=14,
            foreground=["#dddddd", "#ffffff"],
            background=["#258fe1", "#3f56c7"],
            format="<big>🖥</big><b>{load_percent}</b>%",
        ),
        widget.Memory(
            font="sans",
            fontsize=14,
            foreground=["#dddddd", "#ffffff"],
            background=["#8c008c", "#613553"],
            prefix_text="🖬",
            measure_mem="G",
            format="<b>{MemUsed}</b>/{MemTotal}{mm}",
        ),
```

If it still doesn't happen for you, maybe it is my graphics drivers or something related to my Xorg config? 

Also if you have any insight of what part of that commit I should change or comment out to make a test you can tell me.

**Comment by elParaguayo** [comment]
No joy. Still no glitching.

**Comment by elParaguayo** [comment]
You had a glitch issue in #2547 too, didn't you?

So maybe this is driver related.

**Comment by elParaguayo** [comment]
Unfortunately, it's hard to point to a part of that commit when I have no idea what the issue is!

**Comment by matheusfillipe** [comment]
> You had a glitch issue in #2547 too, didn't you?
> 
> So maybe this is driver related.


Yes indeed! I always have those weird issues. That one I tested without loading the nvidia module and it would still happen though.

**Comment by elParaguayo** [comment]
Sounds like your config is identifying some edge cases that we don't see in testing!

**Comment by matheusfillipe** [comment]
I was able to record it 
https://user-images.githubusercontent.com/24435787/144155337-5493e2bf-71b4-4a91-ad7b-7d993385099c.mp4

**Comment by elParaguayo** [comment]
It's a long shot but can you try changing this line:
https://github.com/qtile/qtile/blob/6f41e52e1f2a7692df99ad2127c997e97e80bae7/libqtile/bar.py#L494
to
``` python
if sum(self.border_width):
```

I wonder if that extra code in `Bar._actual_draw` is causing the glitch. 

It shouldn't run if there's no border but I've got the test wrong (`border_width` will always be True even if there's no border). However, if this does solve the glitching, it does mean you won't be able to draw borders without glitching. So, I almost hope this _isn't_ the solution!

**Comment by carmamo** [comment]
> It's a long shot but can you try changing this line:
> 
> https://github.com/qtile/qtile/blob/6f41e52e1f2a7692df99ad2127c997e97e80bae7/libqtile/bar.py#L494
> to
> ```python
> if any(self.border_width):
>```

Hello! I had the same Issue. Making this change solved it. Thank you, it was very distracting :+1:

**Comment by matheusfillipe** [comment]
I can confirm changing the check from `if self.border_width: ` to `if any(self.border_width):` indeed stops the glitching.


> I think a better approach may be to draw the borders once and only draw them again if the bar is reconfigured, otherwise there's no need to keep drawing them.

That sounds reasonable to me.

**Comment by m-col** [comment]
I suspect the borders will still need to be drawn upon `Bar.draw`, as 
that method is hooked up on the `Internal` window to be called upon 
expose events via `self.window.process_window_expose`.

**Comment by matheusfillipe** [comment]
> If you do want borders for your bar, you could try commenting out this line:
> 
> https://github.com/qtile/qtile/blob/da93518b2ab924e803552decdb364d64de46088d/libqtile/bar.py#L530

I tried that and the glitch still happens with borders.

**Comment by elParaguayo** [comment]
Thanks for all the feedback. Let me test a few ideas and see if we can push a fix.

**Comment by elParaguayo** [comment]
> I suspect the borders will still need to be drawn upon `Bar.draw`, as that method is hooked up on the `Internal` window to be called upon expose events via `self.window.process_window_expose`.

Seems to work ok but might be worth some testing.
