### ISSUE TITLE
[feat-req] qtile wiki

### ISSUE THREAD

**Issue by philiparvidsson** [qtile/qtile#3087]
As Qtile is a *hackable* WM, we all do our own hacks and whatnot; we customize and hack away. For that reason, It'd make sense to have a Qtile wiki or similar where users can share snippets to accomplish certain things. E.g., I put some code together to hide the bars, but show it whenever the prompt widget was used and then auto hide the bars again. I'm guessing many users have such hacks and snippets of their own.

The goal would be to engage the Qtile community, to build a database of snippets and also (potentially) provide a source of improvements that could be pulled directly into Qtile over time.

**Comment by elParaguayo** [comment]
You mean like this: https://github.com/qtile/qtile/wiki

**Comment by philiparvidsson** [comment]
I didn't find that. I'm obviously a fool, thanks. ;-)

**Comment by elParaguayo** [comment]
No problem!

Personally, I've never used the wiki. If there are some really good code examples that we think should be shared then I'd like to get them into the main docs but I won't discourage anyone from using the wiki.

**Comment by m-col** [comment]
Also consider adding code to the examples repo: https://github.com/qtile/qtile-examples

We discussed a while ago about adding "plugins" i.e. example snippets like you described to this repo, in addition to the example oonfigs (which are essentially just sets of such snippets). The advantages of that repo over the wiki are mostly 1. version control and 2. mass download of many things so its more greppable, for instance.

E.g. I submitted some snippets to create more of a "plugin" type setup in that repo: https://github.com/qtile/qtile-examples/pull/59. @elParaguayo perhaps if you had a spare moment you could take a look at that PR?
