### ISSUE TITLE
Can't run CommandSet extension

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#3092]
This is split from https://github.com/qtile/qtile/issues/2730

Qtile version: 0.18.2.dev130+g3fe5e0d1
Commit where problem starts: https://github.com/qtile/qtile/commit/4c0988c2e155ff33b0179d22db653454635be814
Xephyr log `cannot grab keyboard`

### Test case
```
    EzKey("M-C-q", lazy.run_extension(extension.CommandSet(
        commands={
            'a': 'xterm'
            },
        foreground='#FF0000', selected_background='#FF0000')),
        desc='test'),
```

**Comment by elParaguayo** [comment]
Thanks for splitting this out. We probably need @m-col to take a look too as the issue arose in that keybinding/swallowing commit.

**Comment by m-col** [comment]
Looks like we are grabbing the key for the keybinding, and then only releasing the grab once the keybinding is complete. @jwijenbergh, we overlooked the case where the the key bound action triggers a key grab. I imagine that X is capable of handling this kind of logic: grab the key, detect a grab request, lend the grab to the requesting window, get it back, and then finally ungrab. As this breaks existing setups, we should lean towards reverting that commit in the meantime. @jwijenbergh perhaps you could take a look and see how feasible a fix is?

**Comment by jwijenbergh** [comment]
> Looks like we are grabbing the key for the keybinding, and then only releasing the grab once the keybinding is complete. @jwijenbergh, we overlooked the case where the the key bound action triggers a key grab. I imagine that X is capable of handling this kind of logic: grab the key, detect a grab request, lend the grab to the requesting window, get it back, and then finally ungrab. As this breaks existing setups, we should lean towards reverting that commit in the meantime. @jwijenbergh perhaps you could take a look and see how feasible a fix is?

yes that makes sense, I will take a look at a fix somewhere in the next few days. My apologies :sweat_smile:. I didn't even know `CommandSet` was a thing haha.

**Comment by m-col** [comment]
Maybe we can grab sync or async here: https://github.com/qtile/qtile/commit/4c0988c2e155ff33b0179d22db653454635be814#diff-71a17283e4aa06f2d83c5904b5e7f1689c7e4f6437178ead9d3e3c79a65f7280L517 according to the value of the `config.Mouse`'s `swallow` value? Then things might otherwise work as expected, and we can simply not support using `swallow=False` when the command to be executed is dependent upon keyboard grabbing. Would that work?

**Comment by jwijenbergh** [comment]
> Maybe we can grab sync or async here: [4c0988c#diff-71a17283e4aa06f2d83c5904b5e7f1689c7e4f6437178ead9d3e3c79a65f7280L517](https://github.com/qtile/qtile/commit/4c0988c2e155ff33b0179d22db653454635be814#diff-71a17283e4aa06f2d83c5904b5e7f1689c7e4f6437178ead9d3e3c79a65f7280L517) according to the value of the `config.Mouse`'s `swallow` value? Then things might otherwise work as expected, and we can simply not support using `swallow=False` when the command to be executed is dependent upon keyboard grabbing. Would that work?

I thought about something like that, I think that should work but is maybe not the cleanest solution. Furthermore, how do we determine if the command is dependent on keyboard grabbing. It also happens with this user defined function:

```python
def run_dmenu(qtile):
    os.system("dmenu_run")
    time.sleep(2)

Key([mod], "m", lazy.function(run_dmenu))
```

**Comment by m-col** [comment]
This would be up to the user. In that example, the key is always expected to be swallowed so we know from config-load time that we can use an async grab, avoiding the issue. If the user passes `swallow=False` then it will fail. I think that the edge case of supporting `swallow=False` with a key-grabbing command is probably something we just don't need to support.

**Comment by jwijenbergh** [comment]
> This would be up to the user. In that example, the key is always expected to be swallowed so we know from config-load time that we can use an async grab, avoiding the issue. If the user passes `swallow=False` then it will fail. I think that the edge case of supporting `swallow=False` with a key-grabbing command is probably something we just don't need to support.

Yeah sorry I meant to put an additional `swallow=True` there. We could indeed document that `swallow=True` has edge cases that need to be considered by the user, such as long running functions with a command in there that grabs the keyboard. I think this solution might work nicely, good thinking! Have not tried to implement it though, maybe x11 does not like it :D.

**Comment by m-col** [comment]
Awesome, I think it should work from X's point of view, it's just a matter of us doing it correctly :)

**Comment by elParaguayo** [comment]
If it's not easy, should we revert 4c0988c for now? We could then push a release and then add this as a later bugfix.

My guess is very few people will be using the `CommandSet` extension!

**Comment by m-col** [comment]
Yeah I think that's a good idea

**Comment by jwijenbergh** [comment]
I've made a patch already based on the idea by @m-col, that should do it

**Comment by matheusfillipe** [comment]
I know it is a bit of a hacky reason but I can also confirm that 4c0988c  is also causing  other related problem that is preventing me from calling `subprocess.check_output(...` from within my `config.py`.

For example, I like to call rofi using `subprocess.check_output` and check the output to switch layouts but since that commit rofi displays but i can't input on it.

```python

def add_layout_and_switch(qtile):
    global group_layouts
    lb = "\n"
    cmd = f"echo '{lb.join([l.name for l in layouts])}' | {rofi_cmd} -dmenu -p layout -i"
    logger.error(f":::::::::{cmd}")
    choice = (
        subprocess.check_output(
            cmd,
            shell=True,
        )
        .decode("utf8")
        .strip()
    )
    layout = None
    for layout_index, layout in enumerate(layouts):
        if layout.name == choice:
            break
        layout = None
    if layout is None:
        send_notification("Qtile", "Invalid layout!", urgent=True, timeout=4000)
        return
    group_name = qtile.current_group.info()["name"]
    this_group = group_layouts[group_name]
    if layout_index not in this_group:
        group_layouts[group_name].append(layout_index)
    qtile.cmd_to_layout_index(layout_index)

# (....)
keys = [
        # (...)
        Key([], "l", lazy.function(add_layout_and_switch), desc="Change Layout"),
]
```
`subprocess.Popen` still works by the way.

**Comment by jwijenbergh** [comment]
> I know it is a bit of a hacky reason but I can also confirm that [4c0988c](https://github.com/qtile/qtile/commit/4c0988c2e155ff33b0179d22db653454635be814) is also causing other related problem that is preventing me from calling `subprocess.check_output(...` from within my `config.py`.
> 
> For example, I like to call rofi using `subprocess.check_output` and check the output to switch layouts but since that commit rofi displays but i can't input on it.
> 
> ```python
> def add_layout_and_switch(qtile):
>     global group_layouts
>     lb = "\n"
>     cmd = f"echo '{lb.join([l.name for l in layouts])}' | {rofi_cmd} -dmenu -p layout -i"
>     logger.error(f":::::::::{cmd}")
>     choice = (
>         subprocess.check_output(
>             cmd,
>             shell=True,
>         )
>         .decode("utf8")
>         .strip()
>     )
>     layout = None
>     for layout_index, layout in enumerate(layouts):
>         if layout.name == choice:
>             break
>         layout = None
>     if layout is None:
>         send_notification("Qtile", "Invalid layout!", urgent=True, timeout=4000)
>         return
>     group_name = qtile.current_group.info()["name"]
>     this_group = group_layouts[group_name]
>     if layout_index not in this_group:
>         group_layouts[group_name].append(layout_index)
>     qtile.cmd_to_layout_index(layout_index)
> 
> # (....)
> keys = [
>         # (...)
>         Key([], "l", lazy.function(add_layout_and_switch), desc="Change Layout"),
> ]
> ```
> 
> `subprocess.Popen` still works by the way.

Thanks for reporting. This is indeed the exact same issue, ```subprocess.popen``` works because you're not waiting for a result. ```subprocess.check_output``` waits for rofi to return. Rofi grabs the keyboard but we're already grabbing the keyboard in qtile. I think we should revert the commit for now.

**Comment by elParaguayo** [comment]
OK - let me do that now.
