### ISSUE TITLE
DmenuRun doesn't take colors from extension_defaults

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#3093]
This is split from https://github.com/qtile/qtile/issues/2730

Qtile version: 0.18.2.dev130+g3fe5e0d1
The problem starts in commit: https://github.com/qtile/qtile/commit/d7016e1dc27680437d89efb322d5e7db03e6b8fe

## test case
```
    EzKey("M-r", lazy.run_extension(extension.DmenuRun()), desc='dmenu run'),
    ...
extension_defaults = dict(
    background='#000000',
    foreground='#00ff00',
    selected_background='#00ff00',
    selected_foreground='#000000'
)
```

No errors

**Comment by elParaguayo** [comment]
Ok. This one is an easy fix. Will submit a PR for it shortly.

**Comment by zordsdavini** [comment]
I confirm - that fixed this issue
