### ISSUE TITLE
guess_terminal() should respect the user environmental variable `TERMINAL` [suggestion]

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3104]
The function `guess_terminal()` from "[qtile/utils.py](https://github.com/qtile/qtile/blob/master/libqtile/utils.py)" should respect the environmental variable `TERMINAL`, because that is what the variable is for. If the user explicitly set the variable, then there is no reason to guess the terminal. I have in example two terminals set on my system and was using `alacritty` for a while. Now I switched back to `konsole` and because `alacritty` is found first, it will always default to it. Even if I set every variable on my system to use `konsole` (set default on Manjaro system settings and set environmental variable `TERMINAL=/usr/bin/konsole`.

This can easily be solved by reading the variable. If a user does not setup this variable, then the function can continue guessing. Currently I do this on my "config.py", but this is something that should be done at default, either in default configuration file or directly in the source code.

```python
try:
    terminal = os.environ['TERMINAL']
except KeyError:
    terminal = guess_terminal()
```

**Comment by jwijenbergh** [comment]
Isn't it the TERM variable that is always set instead of TERMINAL? https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html

Furhermore this variable is not always the name of the terminal, often it has a suffix such as xterm-256color. Also some users have the TERM variable set to xterm even if they're using a different terminal. Neat idea but it would need some additional code that is not fool proof.

**Comment by thingsiplay** [comment]
The TERM variable is to define what type of terminal it is, as far as I know. And TERMINAL can be a direct path to the executable, but it seems as TERMINAL is far less known and not near a standard as TERM is. But to be honest, I probably made this variable up or thought it is a standard variable because a random application supported it? It's a bit embarrassing, sorry.

Well, in that case the suggestion isn't any longer one. At least I wasn't suggesting to use TERM, because this is clearly not easy to work with (and the reason why I use TERMINAL instead). But in this case, it would make TERMINAL less problematic to support, in case you want to. I use this variable across different scripts (and Qtile), in case I switch the terminal; which indeed happened.

**Comment by jwijenbergh** [comment]
> But to be honest, I probably made this variable up or thought it is a standard variable because a random application supported it? It's a bit embarrassing, sorry.

No need to be sorry at all, your idea is still makes sense.

There are probably some DEs/distros that set them by default, I wouldn't be surprised. If some users have this variable configured we can take advantage of it. We can just check if it's non empty. The question is how often this is the case, because if barely anyone has it configured, it wouldn't make much sense to add it.

**Comment by thingsiplay** [comment]
I totally agree. Part of the reason why I even bothered to create an issue is, because I thought this variable is often used. I agree, introducing a non standard variable that people could rely on in the future should be thought out very well. After all, it is not a problem to me to add it in the configuration. Maybe it is enough to add this into the default [config.py](https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py) (simple check as seen above) and make an entry about it in the doc. To be honest, this works just fine (in my case).

I just had todo anything there, because as said before `guess_terminal()` picked up the wrong default terminal, even if it was set as default in Manjaro/KDE (maybe this is another result of my weird setup, not sure whats left and right anymore, I use the KDE applications still but run Qtile). Whatever it is, I had to change that line to use my terminal; either hardcode it or use the variable. That is how I came to the idea to post here, because maybe someone else was in this situation and thought it might be a bug.

**Comment by m-col** [comment]
`guess_terminal` is primarily a utility to ensure that the default config will run with full functionality i.e. when a new user wants to start Qtile for the first time and play around with it, we won't know what terminal is available. I would imagine that most users remove it from their configs completely to instead hard-code a terminal, or like you use an environmental variable.

**Comment by thingsiplay** [comment]
I see. The function works as intended, as a fallback option before any customization. Well if that is the whole intention, then I can see why nothing needs to be changed.
