### ISSUE TITLE
Getting IPC client to work with existing asyncio loop (for Jupyter etc)

### ISSUE THREAD

**Issue by akloster** [qtile/qtile#3111]
I thought it would be nice to work with QTile scripting from a Jupyter kernel or even inside an asyncio script/webservice. And my first impression was this should be really easy, because the IPC client is already using asyncio. But this is actually a big problem, because you can't use "asyncio.run" from an existing loop.

I tried multiple ways to disentangle the CommandClient architecture from running the loop, but failed so far. The only solution I found is to invoke the client from a ThreadPoolExecutor.

**Comment by elParaguayo** [comment]
I'm not entirely clear what you're trying to do. Are you trying to start some sort of service from within Qtile?

**Comment by akloster** [comment]
``First I assumed that when I am running the first example in the docs for scripting QTile inside a Jupyter Notebook it should work.


```python
from libqtile.command.client import InteractiveCommandClient
c = InteractiveCommandClient()
print(c.status())
```

However, it does not, with the following error:
```python
~/anaconda3/envs/py39/lib/python3.9/asyncio/runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop
```

Which is true enough. The IPC client works by starting a new asyncio loop each time it sends a message. It can't be any other way if it has to use asyncio and is supposed to be called in a synchronous way by scripts that don't know how to handle coroutines or event loops and so on.

In Jupyter Notebook and Jupyter Lab, Python code is run by a separate process called the IPython kernel, which in turn is an asyncio application communicating with the ZeroMQ protocol. That's why a loop is already running and that exception gets thrown.

Same thing in any asyncio application. If I wanted to write a little FastAPI/starlette webservice to control QTile from the browser, or just to react to some asynchronous events, I can't just call the IPC client from the main thread because it wants to start and stop the event loop.

Simple script to illustrate the issue, same exception:
```python
from libqtile.command.client import InteractiveCommandClient
import asyncio

async def main():
    await asyncio.sleep(0.5)
    c = InteractiveCommandClient()
    print(c.status())

asyncio.run(main())
```

One workaround is the following, inside Jupyter Lab/Notebook:
```python
import concurrent.futures
import asyncio
def do_sth():
    from libqtile.command.client import InteractiveCommandClient
    c = InteractiveCommandClient()
    print(c.status())

with concurrent.futures.ThreadPoolExecutor() as pool:
    asyncio.get_event_loop().run_in_executor(pool, do_sth)
```

My purpose in raising this issue is starting a discussion. I'm not very far into my QTile journey. I thought it might be nice to have it work with Jupyter and with asyncio. If it works well with asyncio, it would open a whole lot of possibilities. From reading the code so far, I couldn't see an obvious way to make it work both asynchronously and synchronously though...

**Comment by elParaguayo** [comment]
Thanks for taking the time to explain.

As far as I know, there used to be a custom kernel for use with Jupyter notebooks but I don't think it's been updated for a while and I've never really looked at the code.

I can take a look at some point to see if it is something that can be added again.

**Comment by akloster** [comment]
I just looked at it and it throws the same kind of error/issue. I think sometime in the past few years IPykernel switched from Tornado to asyncio and that would have done it.

Also the custom kernel seems to be just for QTile commands, not for Python in general.

I think the problem is with the architecture of the IPC client, and it would need to be refactored somewhat. Also it might be a good idea to have it as a separate module because then it can be installed easier into a Python environment without the X11 dependencies.

**Comment by elParaguayo** [comment]
Could we just create an async version of the client? As far as I see, the issue is not that the client uses asyncio but, rather, it's the call to `asyncio.run` that's the problem. If you're in Jupyter, you could just await the result straightaway.

**Comment by m-col** [comment]
Does the client need to be async at all? I'm not super familiar with how it works, but functionally it seems to behave synchronously, does it not?

> Also it might be a good idea to have it as a separate module because then it can be installed easier into a Python environment without the X11 dependencies.

For just the client side code, you shouldn't need any X dependencies installed. Looks like you do need `cairocffi` though, and some pango system libs.

**Comment by elParaguayo** [comment]
The client uses asyncio to communicate over the socket connection:
``` python
asyncio.open_unix_connection(path=self.socket_path)
```
Why would you need `cairocffi` for a client?

**Comment by m-col** [comment]
> Why would you need cairocffi for a client?

Exactly, you shouldn't, I was thinking that the import graph when using a client might pull in cairocffi from backend.base via core.manager or something, but actually maybe not. If that also isn't needed then that's ideal.

> The client uses asyncio to communicate over the socket connection:

Could we not synchronously wait for a reply before continuing?

**Comment by elParaguayo** [comment]
I would have thought/hoped that a client doesn't need to know about the graph, it just sends a request to the server and the server either executes it if valid or rejects it. However, I guess if you do that then all your calls are from the root node...

I've not looked too closely at this part of the codebase so would need to take some time to think if there's an easy way to have an independent client without changing too much of the existing ipc code.

**Comment by m-col** [comment]
Sorry, I just meant when importing files it might get pulled in. E.g. `from libqtile.core.manager import Qtile` depends on `cairocffi` being present, when arguably it shouldn't.

**Comment by elParaguayo** [comment]
No, no. I totally understand your point. My point was that, arguably, a client could be unaware of the command graph and so doesn't pull in any dependencies. Instead, it just sends a command over the socket and the server interprets that between selectors and command calls.

**Comment by m-col** [comment]
Right, yeah absolutely

**Comment by akloster** [comment]
I tried to replace the asyncio part with plain socket calls, but wasn't able to a response yet. Maybe I'm missing the part about how to send the end marker or something. But this would work in all scenarios, because it would just block the asyncio thread if there is any and otherwise also just block for the function to return. Since the assumption is that QTile responds in a timely manner, this blocking really wouldn't be an issue.

Another crazier solution would be to replace the entire custom IPC protocol with dbus...

**Comment by elParaguayo** [comment]
I'd been toying with the idea of adding a dbus interface as that may help with some of the issues we've got with variable types for exposed methods.

**Comment by akloster** [comment]
Here is one quick way to make the client run with and without asyncio, without changes to the calling code:

https://github.com/akloster/qtile/commit/3a2867e0e5bd0e656a26e86143e903a62d2a3cce

Of course there could be more logic to detect a running asyncio loop and setting up a ThreadPool for more efficiency, but it basically works.

**Comment by slacksystem** [comment]
> Here is one quick way to make the client run with and without asyncio, without changes to the calling code:
> 
> [akloster@3a2867e](https://github.com/akloster/qtile/commit/3a2867e0e5bd0e656a26e86143e903a62d2a3cce)
> 
> Of course there could be more logic to detect a running asyncio loop and setting up a ThreadPool for more efficiency, but it basically works.

Sorry o reopen this but I've been trying to follow the updates and I'm a little confused. Was this resolved? I'm getting this error when trying to use the InteractiveCommandClient in jupyter-console. Is that a separate issue? I wasn't clear about how to apply the effect of the commit here.

**Comment by slacksystem** [comment]
> Here is one quick way to make the client run with and without asyncio, without changes to the calling code:
> 
> [akloster@3a2867e](https://github.com/akloster/qtile/commit/3a2867e0e5bd0e656a26e86143e903a62d2a3cce)
> 
> Of course there could be more logic to detect a running asyncio loop and setting up a ThreadPool for more efficiency, but it basically works.

Sorry to reopen this but I've been trying to follow the updates and I'm a little confused. Was this resolved? I'm getting this error when trying to use the InteractiveCommandClient in jupyter-console. Is that a separate issue? I wasn't clear about how to apply the effect of the commit here.
