### ISSUE TITLE
Volume control in sys tray

### ISSUE THREAD

**Issue by Amogh-Mittal** [qtile/qtile#3112]
I just wanna be able to change volume through a slider instead of scroll wheel, Is there a way of doing so in the qtile bar?

**Comment by alethiophile** [comment]
You should be able to do this by running whatever your desktop environment's volume control program is. If you're running MATE, for instance, that's "mate-volume-control-status-icon". After spawning that, it should appear in the system tray alongside whatever other icons are there.

If you're not running a desktop environment that provides it, you can install a third-party one like [volctl](https://github.com/buzz/volctl).

**Comment by Amogh-Mittal** [comment]
Ok I'll take a look at that, I am using gnome as well with qtile

**Comment by Amogh-Mittal** [comment]
Excatly what I wanted volctl, works great!! thanks
