### ISSUE TITLE
Grow commands work on one layout only.

### ISSUE THREAD

**Issue by xircon** [qtile/qtile#3123]
I am struggling to get "grow" commands working on MonadTall layout,  works on the column layout.

https://user-images.githubusercontent.com/1316691/147102182-bf05b161-ee07-4f17-8542-0444728774ca.mp4

```
    Key([mod, "control"], "h", lazy.layout.grow_left(),  desc="Grow window to the left"),
    Key([mod, "control"], "l", lazy.layout.grow_right(), desc="Grow window to the right"),
    Key([mod, "control"], "j", lazy.layout.grow_down(),  desc="Grow window down"),
    Key([mod, "control"], "k", lazy.layout.grow_up(),    desc="Grow window up"),
```
Am using the Endeavour OS community setup,  but manually installed on existing install.

**Comment by elParaguayo** [comment]
The monad layouts just use `lazy.layout.grow()`.

**Comment by xircon** [comment]
Thank you :+1:  That makes sense.
