### ISSUE TITLE
Screen bright flash with brightnessctl key binding

### ISSUE THREAD

**Issue by ACenTe25** [qtile/qtile#3129]
When I use my key binding of `XF86MonBrightnessDown` to `lazy.spawn("brightnessctl set 10%-")` the screen flashes very brightly and turns white for a fraction of a second, before applying the desired setting. This happens every time I use the key to lower brightness.

This bright flash doesn't happen with the `XF86MonBrightnessUp` to `lazy.spawn("brightnessctl set +10%")` and it doesn't happen if I run `brightnessctl set 10%-` directly in the terminal. This leads me to think that it has something to do with how `lazy.spawn()` works, and not a bug of `brightnessctl`, but I could be wrong.

**Comment by elParaguayo** [comment]
Can't recreate this. Binding a key to `lazy.spawn("brightnessctl set 10%-")` works without issue for me.

**Comment by m-col** [comment]
Same. Do you know if this keybinding works as expected in other WMs such as i3?

**Comment by ACenTe25** [comment]
Sorry it took so long. I've tested with i3 and the issue happens too if I use the keybinding but not if I run the exact same command from the terminal (so the same behavior as Qtile).

I've also tried using different terminals and they behave properly. Any ideas? Should I try with the keybinding in a DE like XFCE?
