### ISSUE TITLE
Incorporate qtile-mutable-scratch

### ISSUE THREAD

**Issue by jrwrigh** [qtile/qtile#3130]
Hey, I created a more i3-like scratch system for qtile (dubbed mutable scratch since, unlike ScratchPad, windows can be added to and removed on the fly). I've put it in this GH repo: https://github.com/jrwrigh/qtile-mutable-scratch

The README there has much more information on how it works and a demo video.

Would there be any interest in incorporating this into Qtile proper? There are a couple implementation details we'd probably want to change (making the window tracking attribute not be dynamically added, creating a completely separate scratch group instead of just using the unnamed one, etc), but I figured I'd throw the idea out there before putting too much effort into it.

**Comment by m-col** [comment]
Neat! I can definitely see the value in this. In general I am pro modularity and a plugin-oriented approach to extending Qtile functionality. Because the functionality this provides is possible without modifying the core code, I think it would be best keeping it in the form you have put it in, where users who want to use it can import and plug it in that way. To get it more visibility I'd suggest adding it to the [examples](https://github.com/qtile/qtile-examples) repository, either as code or just a link in the 'Other Links' table in the readme (which would let you keep full control).

**Comment by jrwrigh** [comment]
Cool! 

> In general I am pro modularity and a plugin-oriented approach to extending Qtile functionality.

I had that thought too, but evidently left it out of the post.

> To get it more visibility I'd suggest adding it to the examples repository, either as code or just a link in the 'Other Links' table in the readme (which would let you keep full control).

I think it'd be interesting to have a dedicated "plugins/extensions" repo for customizations that are stand alone rather than example configs. Beyond my plugin, I know https://github.com/numirias/qtile-plasma is another stand-alone extension. And I'm sure there are others.

**Comment by jrwrigh** [comment]
Maybe the separate extensions repo could have an "example" extension, covering uploading it to PyPI and such.

**Comment by m-col** [comment]
This has been discussed a number of times and it always comes back to "this is kinda the intent of the examples repo, so let's try to improve that". It can certainly do with some Spring cleaning. Many of the config examples are straight up broken, and I think the best course of action would be to prune those that are completely broken, or perhaps move those into a subfolder. And/Or perhaps we can stick example configs into a folder, and plugins into another. We could also redo the readme to bring plugins forward a bit if that would be better. There is (understandable) reluctance to make another repo but I think there is support for a radical refactor of the examples repo.

**Comment by jrwrigh** [comment]
I think a "radical refactor" is a good idea, but also turning it into more of a "how to do ___" setup. Ie. Reduce the noise-to-signal ratio for it since there's a lot of repeated things in those config files. Often the "useful" or "interesting" part is fairly short, or can be summarized into a minimum working example. That way new users could incorporate into their own configs easier while also being able to find them more quickly. The configs table has the description column but when I started to use Qtile and tried to use the repo, it was difficult to map the description to what was in the config.

And separate plugins and config folders makes sense to me.

> We could also redo the readme to bring plugins forward a bit if that would be better.

I think having a TOC at the top would suffice honestly.

**Comment by m-col** [comment]
Well put, I agree 100%. Just added a TOC. Feel free to submit your plugin! Any other feedback/improvements to the examples repo are very welcome.

**Comment by elParaguayo** [comment]
Should we have a link to qtile-examples in the main qtile readme? In our docs?

**Comment by m-col** [comment]
Both!

**Comment by elParaguayo** [comment]
I don't think there's more to discuss here so I'll close this.

A submission of this code (or a link to it) would be welcome in qtile-examples.

**Comment by jrwrigh** [comment]
Agreed. Created a PR for getting mutable scratch on the qtile-examples repo: https://github.com/qtile/qtile-examples/pull/65
