### ISSUE TITLE
Unable to swtich groups with programmer dvorak layout

### ISSUE THREAD

**Issue by joacohoyos** [qtile/qtile#3134]
Hi, I'm trying out qtile and I like it a lot but I'm having issues switching groups.

Basically I use programmer dvorak layout so instead of the number row i have ([, {, } ,( ,=, * ,) , + ,] ,] ,! ,)] and the numbers are in the shift layer.

Currently I'm using I3 and when I want to switch worspaces I just have to do Alt-{num-row} and it will match the keybinding as if I was pressing the number instead of the symbol.

Has anybody had this issue? If so how did you manage to solve it?

I tried both binding the groups with numbers and with the symbols and non of them seem to work

**Comment by elParaguayo** [comment]
This seems identical to #3146

If you use `xev` what do you get when you press those symbols (without shift)? I would have thought that the keybinding should be to the symbol and you can use the number as the group label/name.
