### ISSUE TITLE
Failed to build qtile

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3141]
pip install . give me this error
`  ERROR: Failed building wheel for qtile
Failed to build qtile
ERROR: Could not build wheels for qtile which use PEP 517 and cannot be installed directly`

Build log complete

sudo pip install . 
Processing /home/cr1ogen/Git/qtile
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cffi>=1.1.0 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev6+g12efb431) (1.15.0)
Requirement already satisfied: cairocffi[xcb]>=0.9.0 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev6+g12efb431) (1.2.0)
Requirement already satisfied: xcffib>=0.10.1 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev6+g12efb431) (0.11.1)
Building wheels for collected packages: qtile
  Building wheel for qtile (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpyuz_ro_i_in_process.py build_wheel /tmp/tmp1bh8zgep
       cwd: /tmp/pip-req-build-7t5glltf
  Complete output (219 lines):
  running bdist_wheel
  running build
  running build_py
  file libqtile/_ffi_pango.py (for module libqtile._ffi_pango) not found
  file libqtile/backend/x11/_ffi_xcursors.py (for module libqtile.backend.x11._ffi_xcursors) not found
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/__init__.py -> build/lib.linux-x86_64-3.9/libqtile
  creating build/lib.linux-x86_64-3.9/libqtile/backend
  creating build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/bar.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/command_interface.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/drawer.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/log_utils.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/confreader.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/hook.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/configurable.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/scratchpad.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/command_client.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/utils.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/command_graph.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/popup.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/pango_ffi_build.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/pangocffi.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/sh.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/config.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/dgroups.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/lazy.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/group.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/ipc.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/command_object.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/images.py -> build/lib.linux-x86_64-3.9/libqtile
  copying libqtile/notify.py -> build/lib.linux-x86_64-3.9/libqtile
  creating build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/extension/window_list.py -> build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/extension/dmenu.py -> build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/extension/base.py -> build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/extension/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/extension/command_set.py -> build/lib.linux-x86_64-3.9/libqtile/extension
  copying libqtile/backend/base.py -> build/lib.linux-x86_64-3.9/libqtile/backend
  copying libqtile/backend/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/backend
  creating build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/generic_poll_text.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/spacer.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/caps_num_lock_indicator.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/she.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/wlan.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/config_error.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/window_count.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/battery.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/widgetbox.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/graph.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/idlerpg.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/chord.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/mpris2widget.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/keyboardlayout.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/sep.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/tasklist.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/moc.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/systray.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/textbox.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/sensors.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/prompt.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/base.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/countdown.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/check_updates.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/nvidia_sensors.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/pomodoro.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/windowname.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/wallpaper.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/windowtabs.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/import_error.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/currentscreen.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/backlight.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/pulseaudio_ffi.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/thermal_zone.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/imapwidget.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/gmail_checker.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/groupbox.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/net.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/canto.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/clipboard.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/keyboardkbdd.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/maildir.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/bluetooth.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/launchbar.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/volume.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/crypto_ticker.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/statusnotifier.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/clock.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/image.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/open_weather.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/df.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/stock_ticker.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/mpd2widget.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/quick_exit.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/khal_calendar.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/crashme.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/wttr.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/currentlayout.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/memory.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/cmus.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/pulse_volume.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/cpu.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  copying libqtile/widget/notify.py -> build/lib.linux-x86_64-3.9/libqtile/widget
  creating build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/migrate.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/check.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/cmd_obj.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/top.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/run_cmd.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/main.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/shell.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  copying libqtile/scripts/start.py -> build/lib.linux-x86_64-3.9/libqtile/scripts
  creating build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/verticaltile.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/columns.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/bsp.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/base.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/xmonad.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/stack.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/zoomy.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/matrix.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/tile.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/slice.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/tree.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/ratiotile.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/floating.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  copying libqtile/layout/max.py -> build/lib.linux-x86_64-3.9/libqtile/layout
  creating build/lib.linux-x86_64-3.9/libqtile/command
  copying libqtile/command/interface.py -> build/lib.linux-x86_64-3.9/libqtile/command
  copying libqtile/command/graph.py -> build/lib.linux-x86_64-3.9/libqtile/command
  copying libqtile/command/base.py -> build/lib.linux-x86_64-3.9/libqtile/command
  copying libqtile/command/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/command
  copying libqtile/command/client.py -> build/lib.linux-x86_64-3.9/libqtile/command
  creating build/lib.linux-x86_64-3.9/libqtile/core
  copying libqtile/core/lifecycle.py -> build/lib.linux-x86_64-3.9/libqtile/core
  copying libqtile/core/state.py -> build/lib.linux-x86_64-3.9/libqtile/core
  copying libqtile/core/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/core
  copying libqtile/core/manager.py -> build/lib.linux-x86_64-3.9/libqtile/core
  copying libqtile/core/loop.py -> build/lib.linux-x86_64-3.9/libqtile/core
  creating build/lib.linux-x86_64-3.9/libqtile/interactive
  copying libqtile/interactive/iqshell_kernel.py -> build/lib.linux-x86_64-3.9/libqtile/interactive
  copying libqtile/interactive/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/interactive
  copying libqtile/interactive/iqshell_install.py -> build/lib.linux-x86_64-3.9/libqtile/interactive
  creating build/lib.linux-x86_64-3.9/libqtile/resources
  copying libqtile/resources/default_config.py -> build/lib.linux-x86_64-3.9/libqtile/resources
  copying libqtile/resources/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/resources
  copying libqtile/backend/x11/core.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/xcursors.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/drawer.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/xcursors_ffi_build.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/xcbq.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/window.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  copying libqtile/backend/x11/xkeysyms.py -> build/lib.linux-x86_64-3.9/libqtile/backend/x11
  creating build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/core.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/keyboard.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/drawer.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/output.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/__init__.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/window.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  copying libqtile/backend/wayland/wlrq.py -> build/lib.linux-x86_64-3.9/libqtile/backend/wayland
  running egg_info
  creating qtile.egg-info
  writing manifest file 'qtile.egg-info/SOURCES.txt'
  warning: no previously-included files found matching 'libqtile/_ffi*.py'
  warning: no previously-included files found matching 'libqtile/backend/x11/_ffi*.py'
  no previously-included directories found matching 'rpm'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'qtile.egg-info/SOURCES.txt'
  copying libqtile/py.typed -> build/lib.linux-x86_64-3.9/libqtile
  creating build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-caution-charging.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-caution.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-empty.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-full-charged.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-full-charging.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-full.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-good-charging.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-good.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-low-charging.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-low.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  copying libqtile/resources/battery-icons/battery-missing.png -> build/lib.linux-x86_64-3.9/libqtile/resources/battery-icons
  creating build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-bsp.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-columns.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-floating.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-matrix.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-max.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-monadtall.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-monadwide.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-ratiotile.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-slice.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-stack.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-tile.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-treetab.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-unknown.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-verticaltile.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-wmii.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  copying libqtile/resources/layout-icons/layout-zoomy.png -> build/lib.linux-x86_64-3.9/libqtile/resources/layout-icons
  file libqtile/_ffi_pango.py (for module libqtile._ffi_pango) not found
  file libqtile/backend/x11/_ffi_xcursors.py (for module libqtile.backend.x11._ffi_xcursors) not found
  running build_ext
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/build
  creating build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.9 -c build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.o
  build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.c:50:14: fatal error: pyconfig.h: No existe el fichero o el directorio
     50 | #    include <pyconfig.h>
        |              ^~~~~~~~~~~~
  compilation terminated.
  error: command /usr/bin/x86_64-linux-gnu-gcc failed with exit code 1
  ERROR: Failed building wheel for qtile
Failed to build qtile
ERROR: Could not build wheels for qtile which use PEP 517 and cannot be installed directly

**Comment by cr1ogen** [comment]
then install PEP517 with pip and now give me this error 

Building wheels for collected packages: qtile
  Building wheel for qtile (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpf1utm09t
       cwd: /home/cr1ogen/Git/qtile
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  file libqtile/_ffi_pango.py (for module libqtile._ffi_pango) not found
  file libqtile/backend/x11/_ffi_xcursors.py (for module libqtile.backend.x11._ffi_xcursors) not found
  running egg_info
  warning: no previously-included files found matching 'libqtile/_ffi*.py'
  warning: no previously-included files found matching 'libqtile/backend/x11/_ffi*.py'
  no previously-included directories found matching 'rpm'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'qtile.egg-info/SOURCES.txt'
  file libqtile/_ffi_pango.py (for module libqtile._ffi_pango) not found
  file libqtile/backend/x11/_ffi_xcursors.py (for module libqtile.backend.x11._ffi_xcursors) not found
  running build_ext
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.9 -c build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.o
  build/temp.linux-x86_64-3.9/libqtile.widget._pulse_audio.c:50:14: fatal error: pyconfig.h: No existe el fichero o el directorio
     50 | #    include <pyconfig.h>
        |              ^~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ERROR: Failed building wheel for qtile
Failed to build qtile
ERROR: Could not build wheels for qtile, which is required to install pyproject.toml-based projects

**Comment by cr1ogen** [comment]
i have wheel installed
> % pip show wheel 
Name: wheel
Version: 0.37.1
Summary: A built-package format for Python
Home-page: https://github.com/pypa/wheel
Author: Daniel Holth
Author-email: dholth@fastmail.fm
License: MIT
Location: /home/cr1ogen/.local/lib/python3.9/site-packages
Requires: 
Required-by

**Comment by elParaguayo** [comment]
Might need @m-col 's input here as the `pyproject.toml` file was recently added for us to support `black`. We'd need to look into how/why that's impacting installation.

As for your last error, it looks like you're using Wayland. Systray widget is not compatible with Wayland and will crash on startup (we need to tidy up that error message - I thought I had a PR for that but maybe I'm wrong!)

**Comment by m-col** [comment]
`pip install qtile` will install `0.19.0` which tags commit ce94e6cfd382580660bf6e12092234bdbe367f7c, before `pyproject.toml` was added.

I am hoping that we are not required to move completely to `pyproject.toml`, though I'd like to, but, in my own time! This link suggests the problem may be in pip's side, possibly a version or cache thing: https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly. Could check to see if any of those hints help?

**Comment by elParaguayo** [comment]
Yes, but you can use `pip install .` to install the git version after you've cloned it (makes it easier to uninstall than `python setup.py install`).

**Comment by cr1ogen** [comment]
If I use Wayland.  The problem I have with the config.py file is that the file I was using gave me a configuration error out of nowhere, being that it has few changes to the file that is automatically generated.  When I get home I will go up the exit of qtile check.  It is the second time it happens to me when updating qtile

**Comment by cr1ogen** [comment]
I hope my English is understood as I use the translator xD.

**Comment by m-col** [comment]
This one?

> 2021-12-26 23:03:16,897 ERROR libqtile bar.py:_configure_widget():L308 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")

I think the config should work fine despite this. Or does Qtile crash completely?

**Comment by cr1ogen** [comment]
> 

qtile does not crash but starts with the config.py file by default

**Comment by cr1ogen** [comment]
> This one?
> 
> > 2021-12-26 23:03:16,897 ERROR libqtile bar.py:_configure_widget():L308 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")
> 
> I think the config should work fine despite this. Or does Qtile crash completely?

Yes these error. Qtile does not crash but starts with the config.py file by default

**Comment by cr1ogen** [comment]
-> % qtile check
checking qtile config file /home/cr1ogen/.config/qtile/config.py
error: config failed to import: 
Stub: at line 1
MypyFile:1(
  /tmp/tmp191i689v/config.pyi)
Runtime:
MISSING

**Comment by cr1ogen** [comment]
https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly. This hints not work for me

**Comment by cr1ogen** [comment]
> > This one?
> > > 2021-12-26 23:03:16,897 ERROR libqtile bar.py:_configure_widget():L308 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")
> > 
> > 
> > I think the config should work fine despite this. Or does Qtile crash completely?
> 
> Yes these error. Qtile does not crash but starts with the config.py file by default

The error in the config.py file was my error and it has been solved, I apologize. Only the compilation error remains

**Comment by cr1ogen** [comment]
> 2021-12-26 23:03:16,897 ERROR libqtile bar.py:_configure_widget():L308 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")

this error persists but does not affect the operation of qtile

**Comment by cr1ogen** [comment]
I can install qtile from source. I update qtile and work

> -> % sudo pip3 install . 
Processing /home/cr1ogen/Git/qtile
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.1.0 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev9+g4640369c) (1.15.0)
Requirement already satisfied: xcffib>=0.10.1 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev9+g4640369c) (0.11.1)
Requirement already satisfied: cairocffi[xcb]>=0.9.0 in /usr/lib/python3/dist-packages (from qtile==0.19.1.dev9+g4640369c) (1.2.0)
Building wheels for collected packages: qtile
  Building wheel for qtile (pyproject.toml) ... done
  Created wheel for qtile: filename=qtile-0.19.1.dev9+g4640369c-cp39-cp39-linux_x86_64.whl size=493743 sha256=30ca67695aeb69a55be7f435906aba6e586237707888920912b74307510fcb0c
  Stored in directory: /tmp/pip-ephem-wheel-cache-nl1rpm95/wheels/aa/fd/fe/235157abbc1a7ae095e431b45961744bd388d4cfdb4115c240
Successfully built qtile
Installing collected packages: qtile
  Attempting uninstall: qtile
    Found existing installation: qtile 0.19.0
    Uninstalling qtile-0.19.0:
      Successfully uninstalled qtile-0.19.0
Successfully installed qtile-0.19.1.dev9+g4640369c

I do not know if these packages that I update in Debian, have something to do with the installation of qtile

> gir1.2-gtk-3.0 
gir1.2-soup-2.4 
gtk-update-icon-cache 
klibc-utils
libbluetooth3 
libfakeroot 
libgegl-0.4-0 
libgegl-common 
libgtk-3-common
libklibc 
libsoup-gnome2.4-1 
libsoup2.4-1 libsoup2.4-common 
linux-base
python3-gi 
python3-gi-cairo 
xdg-desktop-portal-gtk
