### ISSUE TITLE
screen problem

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#3150]
### Discussed in https://github.com/qtile/qtile/discussions/3149

<div type='discussions-op-text'>

<sup>Originally posted by **ArchKubi** December 29, 2021</sup>
I don't know when but ı open my computer and see this problem ı reset qtile but every time computer open and this problem comes
is this bug ? or my config file problem ?
https://github.com/ArchKubi/MyQtile/blob/main/low_resolution/qtile/config.py

![2021-12-29-064603_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147626810-90e9432f-d645-4594-9bd1-978fed954519.png)
![2021-12-29-064605_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147626813-e5789c17-3643-43b7-b075-170d0b8a967a.png)

</div>

Posting as issue. My guess is that it's the same issue as #3148.

**Comment by ArchKubi** [comment]
![2021-12-29-200437_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147686593-f9c04b6f-995b-4be4-bc50-96f82b187311.png)
1 day later I didn't do anything refresh doesn't work

**Comment by elParaguayo** [comment]
Can you take a look at all the questions I posted in your original discussion and answer each of them please.

**Comment by elParaguayo** [comment]
Can you run  `qtile cmd-obj -o cmd -f reconfigure_screens` and, if that doesn't work, try `qtile cmd-obj -o cmd -f reload_config`

**Comment by ArchKubi** [comment]
ı found problem xrandr --output VGA-1 --set TearFree on this command problem
refresh working now
![2021-12-29-204006_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147689222-5481babd-f5c6-4f33-8655-567835559cf4.png)
but this is not change 
![2021-12-29-204000_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147689270-4db9dd38-86a9-478b-9407-4904e73bffb7.png)

**Comment by elParaguayo** [comment]
Sorry. I'm really not sure I understand what you're saying.

If you remove the `TearFree` command line, is it working?

**Comment by ArchKubi** [comment]
yes, but not completely fixed, I fix it with lazy.refresh, the screen stays like this every time the computer is turned on
![2021-12-29-204000_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/147691275-438952bb-2cab-4176-a60e-7a62e60ab594.png)

**Comment by elParaguayo** [comment]
Ah, ok. I think that is the same issue at #3148. Basically, you're running `xrandr` _after_ qtile has started but qtile is trying to run `reconfigure_screens` too early (before xrandr has finished setting up your screen).

The PR in #3151 is trying to fix this.

Would be great if you're able to test it.

**Comment by ArchKubi** [comment]
sorry my english not good ı don't understand how ı test
