### ISSUE TITLE
CheckUpdates widget swallows crashes and shows as no updates

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#3158]
As per title, it's not clear if the check update command is working as any error in the command results in the widget treating it as no updates. 

This makes debugging impossible.

**Comment by m-col** [comment]
In the corresponding PR (https://github.com/qtile/qtile/pull/3160) we decided that this would be a no-fix. Shall we close this?

**Comment by elParaguayo** [comment]
How about, rather than fixing, we make the docs clearer?

**Comment by m-col** [comment]
Good idea
