### ISSUE TITLE
[PATCH] QTile source releases won't build due to missing version information

### ISSUE THREAD

**Issue by akdev1l** [qtile/qtile#3164]
Hi,

I was trying to revive the QTile package for fedora as I am keen on maintaining it. I noticed currently the package won't build due to missing version information in the source archives. 

You can use the following Containerfile to reproduce the issue:

```
FROM fedora:35

RUN dnf install -y python3-devel python3-setuptools python3-cffi python3-xcffib python3-cairocffi cairo python3-six python3-pycparser &&
    curl -LOJ 'https://github.com/qtile/qtile/archive/refs/tags/v0.19.0.tar.gz' &&
    tar xvf qtile-0.19.0.tar.gz &&
    cd qtile-0.19.0 && 
    python3 setup.py build
```

(you can also copy paste the commands on a clean Fedora 35 install and it will reproduce the issue, containerfile given for ease of portability)

This is the error message I get:

```
Failed to find pulseaudio headers. PulseVolume widget will be unavailable
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
Traceback (most recent call last):
  File "/qtile-0.19.0/setup.py", line 91, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 807, in finalize_options
    ep(self)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/qtile-0.19.0/.eggs/setuptools_scm-6.3.2-py3.10.egg/setuptools_scm/integration.py", line 65, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/qtile-0.19.0/.eggs/setuptools_scm-6.3.2-py3.10.egg/setuptools_scm/__init__.py", line 177, in _get_version
    parsed_version = _do_parse(config)
  File "/qtile-0.19.0/.eggs/setuptools_scm-6.3.2-py3.10.egg/setuptools_scm/__init__.py", line 135, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/qtile-0.19.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

This patch fixes the issue for me:

```
diff --git a/.git_archival.txt b/.git_archival.txt
new file mode 100644
index 00000000..95cb3eea
--- /dev/null
+++ b/.git_archival.txt
@@ -0,0 +1 @@
+ref-names: $Format:%D$
diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 00000000..a94cb2f8
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+.git_archival.txt export-subst
diff --git a/setup.cfg b/setup.cfg
index 2be324ed..c7ff5479 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -42,6 +42,7 @@ setup_requires =
   cairocffi[xcb] >= 0.9.0
   setuptools >= 40.5.0
   setuptools_scm >= 3.2.0
+  setuptools_scm_git_archive >= 1.1.0
 install_requires =
   cffi >= 1.1.0
   cairocffi[xcb] >= 0.9.0
```

it needs to be adopted by upstream because otherwise the `setuptools_scm_git_archive` tool requires that it be run on tagged commits - so patching this only for Fedora is not trivial and also you probably want your source release to build :).

Let me know if you want a proper PR to adopt this.

**Comment by elParaguayo** [comment]
Can you download the package from PyPi rather than Github?

**Comment by akdev1l** [comment]
@elParaguayo mm can't do sir - Fedora packaging guidelines dictate that the source must be built from a source release if possible.

We also validate checksum as part of the build so there's a strong preference for a static archive vs a git repo. 

I can check the possibility of building directly from git, if I pin down to a commit it should be okay. I'll have to do some research on that (the build is only broken for the git archives).

To be clear the proposed patch adds two 1-line files (which I don't think they would ever change) and a single dependency

You can read a bit more about it here: https://pypi.org/project/setuptools-scm-git-archive/

**Comment by elParaguayo** [comment]
I'll take a look at that. However, if we make that change, it won't have any impact on the v0.19.0 tag so you'd presumably need to wait until the next release (I suspect there'll be a v0.19.1 bugfix release at some point...)

**Comment by akdev1l** [comment]
@elParaguayo I am okay with that - I can fork temporarily to add the files to the current release and switch to upstream on the next  v0.19.x whenever that may be up to your release schedule :)

**Comment by m-col** [comment]
We should think about how/if we need to make more changes to the packaging (for all packagers, not just fedora), because "setup_requires has been deprecated in favor of pyproject.toml" (from https://pypi.org/project/setuptools-scm/).

That statement also means that the instructions from https://pypi.org/project/setuptools-scm-git-archive/ might be outdated(?). 

If we went ahead with the proposed change using the deprecated setup in the meantime, how would it affect other packagers? With `setup_requires` how including `"setuptools_scm_git_archive"`, presumably all packagers will need to use that system over their current approach.

**Comment by akdev1l** [comment]
I did ran into that deprecation notice - I wasn't sure if the current system was a conscious choice or not so I didn't investigate too much in updating it. I would be willing to put in some work to modernize that. (I'm likely forking anyway for the current release - so I can dirty-patch on my package and work on this issue on the side) 

As for impact on current packagers - if they are using the git repo I do not think they would be impact as `setuptools_scm` will still work.

If they are actually using the source archive from the releases page then I wonder how they workaround the lack of versioning info when building the project - really that seems the only issue setuptools doesn't know what version it is.

**Comment by m-col** [comment]
Unfortunately I can't say for certain what approach other packagers are using.

> I would be willing to put in some work to modernize that.

Any contributions and/or advice would be greatly appreciated. Ultimately the packaging-related files/code is there for the packagers and not the devs!
