### ISSUE TITLE
With multi monitors, clicking empty screen group does not fully focus screen?

### ISSUE THREAD

**Issue by asegarra** [qtile/qtile#3166]
Basically I ran into this with dmenu (additional case below) which I have a keybinding for..
To replicate, you need at least 2 monitors. 
On first monitor open a window, the second monitor should be an empty workspace, click the second monitor workspace to active it, open dmenu. I expected dmenu to open in the second monitor but it opens in the first monitor. If the second monitor has a window open then moving your mouse over will activate the workspace and dmenu will appear in the appropriate workspace.

This is also notable for example, I have a bar in both screens with the CurrentLayout widget on each, if you repeat the scenario above but instead of dmenu go to the second screen and click the CurrentLayout widget which by default cycles through the available layouts, in this case clicking the widget on the second screen actually cycles the layouts on the first monitor.

**Comment by elParaguayo** [comment]
Thanks. This is probably a similar issue to #3165 (i.e. there's an underlying issue that causes both issues).

**Comment by elParaguayo** [comment]
I've posted a fix for when you click on the bar. However, please note, that won't address your issue about when you click on an empty screen. When I click on an empty screen, the focus does change to that screen so I suspect the issue with dmenu is something else.

**Comment by asegarra** [comment]
Thanks for the fix! As for dmenu, I suppose something different happens if you switch screens using lazy.next_screen()? Because if I use that then dmenu works as expected, but not when clicking.

**Comment by elParaguayo** [comment]
That's interesting. What version of qtile are you on?

**Comment by asegarra** [comment]
0.19
