### ISSUE TITLE
If TreeTab layout is active when removed from the config and reloading causes qtile to enter into invalid state.

### ISSUE THREAD

**Issue by asegarra** [qtile/qtile#3171]
I rant into this whilst experimenting with my config. if TreeTab layout is active while being removed from the config and reloading, it causes the TreeTab panel to stay on permanently, requiring a qtile restart.

**Comment by elParaguayo** [comment]
Thanks for reporting.

Have confirmed this is the case. Will work on a fix.

**Comment by elParaguayo** [comment]
Ok. I know what the problem is. Fixing it is a little bit harder!
