### ISSUE TITLE
Switching to the current group doesn't do anything anymore

### ISSUE THREAD

**Issue by niklasmohrin** [qtile/qtile#3172]
Hey!

I have set up multiple groups and keybindings for switching to them (full config linked at the end of the report):

```python
for i, label in enumerate(group_labels, 1):
    keys.append(Key([mod], str(i), lazy.group[label].toscreen()))
    keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(label)))
```

These work, I can switch workspaces when pressing the correct keys. Until recently, I could also switch back to the group I came from when pressing the same keys again (for example `Mod+3` to go to group 3, `Mod+3` to go back to the group I was in before). However, the switching-back part stopped working (let's say, one or two weeks ago).

Interestingly, switching back works as expected if I click on the group in the `GroupBox` widget in the built-in bar instead of using the keyboard.

The logfile contains:

```plain
2022-01-02 23:57:00,677 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2022-01-02 23:57:00,915 ERROR libqtile core.py:_xpoll():L336 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 304, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 699, in handle_DestroyNotify
    if self.qtile.current_window is None:
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 552, in current_window
    return self.current_screen.group.current_window
AttributeError: 'Qtile' object has no attribute 'current_screen'
```

Notably, no more `AttributeError`s appear if I try to switch, I am not sure when exactly the one here is raised.

```shell
$ qtile -v
0.19.0
$ python --version
Python 3.10.1
```

I am switching between 1 to 3 monitors which all have their own `Bar`, switching works in neither setup.
I installed qtile with the Arch package `qtile`, [here is my full config](https://github.com/niklasmohrin/dotconfig/blob/3cc95fbe831c3b312f2eeec7774bb5dcafdc1d2e/.config/qtile/config.py).

Any ideas what I am doing wrong? Thank you!

---

I have been using qtile as my daily driver for over a year and am really enjoying it! Thank you for your work :)

**Comment by EHF32** [comment]
I had the same problem, fixed with this:
```python
keys.append(Key([mod], str(i), lazy.group[label].toscreen(toggle=True)))
```
See [changelog](https://github.com/qtile/qtile/blob/70c17e1088df391d7f89040e2e24ef43759a4ab5/CHANGELOG#L25-L26)

**Comment by elParaguayo** [comment]
@niklasmohrin the above fix should work for you as this was something we changed.

I'm interested in the error message from your log though. That's not related to this issue but I am curious as to what caused it. Are you able to trigger it again/reliably?

**Comment by niklasmohrin** [comment]
@EHF32 Thanks, I missed that update, this works!

I am surprised that toggling still works when clicking on the `GroupBox` widget, it is a bit confusing that the default behaviors are not the same for `toscreen` and `GroupBox`.

**Comment by niklasmohrin** [comment]
@elParaguayo I tried to for 10 minutes, I can't really reproduce the error anymore today :thinking: I will post again if I spot it again. I suppose I should still close the issue?
