### ISSUE TITLE
Bar border fails to redraw on some applications

### ISSUE THREAD

**Issue by jwijenbergh** [qtile/qtile#3173]
I was trying out the [kate](https://kate-editor.org) editor and I noticed that the bar border fails to redraw after the application has been toggled fullscreen or just exited when fullscreen. Not sure how it's possible that it only happens on some applications, but so far only kate does this for me. Maybe several other KDE related apps do this? I mostly used terminal applications so I don't know.

This bug was introduced by #3067 so it happens at current master
![borderglitch](https://user-images.githubusercontent.com/46386452/147922590-5b56dcce-2661-4cd9-8ba7-6b417dab8993.gif)

The border will never redraw unless I restart qtile.

Happens with the default config that have bar border settings enabled.

**Comment by elParaguayo** [comment]
Interesting. Thanks for reporting. 

I can take a look at this.

**Comment by jwijenbergh** [comment]
> Interesting. Thanks for reporting.
> 
> I can take a look at this.

Let me know if you need any help! I might also be available to do some experiments with this later

**Comment by elParaguayo** [comment]
I'm struggling to recreate this. I've installed kate, made it fullscreen and quit the application and I can still see the border on the bar.

**Comment by elParaguayo** [comment]
> I'm struggling to recreate this. I've installed kate, made it fullscreen and quit the application and I can still see the border on the bar.

Scratch that!

I can replicate this. I hadn't realised that I was using the `Bar` from `qtile-extras`! With that bar, I don't get the issue that you reported but, if I switch it to `libqtile.bar.Bar`, I do!

Now to work out what's different!

**Comment by elParaguayo** [comment]
OK. The issue is that the bar doesn't draw borders every time `self.bar.draw()` is called. There's a flag `_borders_drawn` which, once set, prevents multiple draws as this reduces unnecessary processing time as the borders don't move (while the widgets do).

Removing this check fixes the problem but that's unsatisfactory (for the above reasons) so I'l like to understand why `kate` needs this but other windows don't. I have some ideas which I'll check.

**Comment by elParaguayo** [comment]
Are you sure it's only `kate` that does it for you? I've seen this on `rofi` in fullscreen mode and `alacritty` too.

I've got a fix which I can submit shortly.

**Comment by jwijenbergh** [comment]
> OK. The issue is that the bar doesn't draw borders every time `self.bar.draw()` is called. There's a flag `_borders_drawn` which, once set, prevents multiple draws as this reduces unnecessary processing time as the borders don't move (while the widgets do).
> 
> Removing this check fixes the problem but that's unsatisfactory (for the above reasons) so I'l like to understand why `kate` needs this but other windows don't. I have some ideas which I'll check.

Indeed, going to a commit before #3067 was merged indeed fixes it.
> Are you sure it's only kate that does it for you? I've seen this on rofi in fullscreen mode and alacritty too.

Hmmm with alacritty it does not happen for me. Also not for rofi with `rofi -theme-str '#window { fullscreen: true; }' -show run`.  Note that I also just found out this happens with my [lockscreen](https://github.com/betterlockscreen/betterlockscreen) as well. So if by default the betterlockscreen is just black, when I unlock the bar border is also black. Oh and also kdevelop, but that pretty much uses the same UI libraries as kate.

**Comment by elParaguayo** [comment]
Can you check if this fixes it for you.

**Comment by jwijenbergh** [comment]
Thanks for looking into this so quickly!
