### ISSUE TITLE
[Feature Request] Window.togroup with toggle

### ISSUE THREAD

**Issue by qwenger** [qtile/qtile#3175]
The `toscreen` method of `Group` has a `toggle` flag that allows toggling to the previous group if the target group is already shown on screen.

It would be nice to have this flag available on the `togroup` method of `Window` as well (and behaving correctly with the `switch_group` flag).

Use case: I use `mod4 + number` to navigate in groups, with toggling activated. I use `shift + mod4 + number` to move the active window in groups, with group switching activated. I would like window movement to behave consistently with group navigation w.r.t. toggling.

**Comment by elParaguayo** [comment]
I'm a bit confused as to what you're asking.

Let's say you're on group 2 and group 1 was your previous group.

If you press `shift + mod4 + 2`, what do you want to happen? Do you want the window to go to group 1? Do you want the window to stay on group 2 but you change to group 1 (like the `toggle` option)?

**Comment by qwenger** [comment]
Assuming that I'm on group 2 with previous group 1 and I call the method `Window.togroup` with group 2, here is what I expect to happen:

| | `toggle=False` | `toggle=True` |
| --- | --- | --- |
| `switch_group=False` | nothing | window moves to group 1, group 2 remains shown |
| `switch_group=True` | nothing | window moves to group 1, screen shows group 1 |

The case `toggle=False` corresponds to the current behavior, which is that nothing happens if the target group is the current one.

**Comment by m-col** [comment]
I don't know why this took me so long to understand :laughing: 

So it's: when trying to moving the current window to the current group (the group it's already on), instead send it to the screen's previous group? If so, something like this might work (untested):
```py
from libqtile import qtile

def togroup_toggle(window, group):
    if window.group and window.group.name == group:  # Already on group
        if qtile.current_screen.previous_group:
            window.cmd_togroup(qtile.current_screen.previous_group.name)
    else:
        window.cmd_togroup(group)
```
You would then bind this to a key with `lazy.window.function(togroup_toggle, "2")`, where the `"2"` here is the group name, the second argument to the function. Is that the logic you're after? You may need to insert the `switch_group` value you want.

**Comment by qwenger** [comment]
Yes that's the behavior that I would like.

**Comment by qwenger** [comment]
Tentative PR created.

(Note: all tests fail locally for me, "Window never appeared", and I don't really have much time to debug that.)

**Comment by m-col** [comment]
Would the snippet above be sufficient for your use case? As it stands it is a niche feature for a single user so I would prefer if you could simply bind the function above to a key in your config. If more people come here and express interest in having this, then we can consider adding it into the core code.

**Comment by qwenger** [comment]
So:

- The following snippet is sufficient for my use case. Yours with `qtile.current_screen` did not work for me.

```python
def togroup_toggle(window, group_name):
    if window.group and window.group.name == group_name:
        if window.group.screen.previous_group:
            window.cmd_togroup(window.group.screen.previous_group.name, switch_group=True)
    else:
        window.cmd_togroup(group_name, switch_group=True)
```

- I agree that it is a niche feature to some extent, but so is the `toggle` option on `Group.toscreen`, at least that's what you implied when switching it off by default (https://github.com/qtile/qtile/pull/2954) (thereby breaking the existing behavior, but that's another topic). And this option for `Window.togroup` would go hand-in-hand with that of `Group.toscreen`, this is why I would like to see both built in. Still I understand if you decide not to integrate it, and I can live with the `togroup_toggle` function.
