### ISSUE TITLE
Unable to create ScratchPad, name mixed-in with keys

### ISSUE THREAD

**Issue by ALydh** [qtile/qtile#3177]
Somehow the name of the scratchpad gets added to `self.config.keys` in the `Qtile` object.

Attached a minimal reproducable config file based on the default, and the error logs.

[config-default-with-scratchpad.txt](https://github.com/qtile/qtile/files/7808062/config-default-with-scratchpad.txt)
[qtile-scratchpad-error.txt](https://github.com/qtile/qtile/files/7808074/qtile-scratchpad-error.txt)

**Comment by elParaguayo** [comment]
You want to add the Scratchpad to your `groups` _after_ that loop for key bindings and then define the necessary key bindings for the drop-downs.
