### ISSUE TITLE
[Wayland] Bar position in start is wrong

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3181]
When i start qtile my bar look like this. Qtile Version 0.19.1.dev13+g7a911d65

![1_grim](https://user-images.githubusercontent.com/9537788/148465738-425be478-3a21-438d-8eb4-83086b1e4b64.png)

If I restart Qtile using mod shift R the bar is seen in the correct position

![2_grim](https://user-images.githubusercontent.com/9537788/148465770-87bf63d8-f5dc-4039-b5c0-87b979a10015.png)

I have an only monitor 4K and i use the following command in my autostart config to make the bars and windows look bigger
`wlr-randr --output DP-2 --scale 2 &`

If I comment on that line the bar looks good, but everything is smaller due to my 4k monitor

![20220106_20h27m07s_grim](https://user-images.githubusercontent.com/9537788/148466916-781a4456-1c0c-4d56-973c-9c2a4c9dee72.png)

**Comment by m-col** [comment]
How are you calling the autostart script?

**Comment by cr1ogen** [comment]
> How are you calling the autostart script?

autostart.sh in .config/qtile path

**Comment by cr1ogen** [comment]
My autostart line in config.py file

> import os
import subprocess
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~')
    subprocess.call([home + '/.config/qtile/autostart.sh'])

**Comment by m-col** [comment]
Do you have `reconfigure_screens = True` in your config? If not, could you try setting that?

**Comment by cr1ogen** [comment]
> Do you have `reconfigure_screens = True` in your config? If not, could you try setting that?

i don't have it. but I would not know where to put it

**Comment by cr1ogen** [comment]
I don't understand anything about programming but it may be that the bar looks like this at startup, because it loads the command `wlr-randr --output DP-2 --scale 2 &` before the bar, that's why when reloading qtile with `Mod + Shift + R` is the bar displayed correctly?

**Comment by elParaguayo** [comment]
@cr1ogen Can you try the fix in #3151 

Despite the title of that PR, I've actually found a bug that will cause issues for both X11 and Wayland backends so it may fix your issue too.

**Comment by cr1ogen** [comment]
> @cr1ogen Can you try the fix in #3151
> 
> Despite the title of that PR, I've actually found a bug that will cause issues for both X11 and Wayland backends so it may fix your issue too.

I clone your Qtile repository, installed it and the problem persists, but maybe I'm doing something wrong.
because I don't know how to test your PR # 3151

**Comment by elParaguayo** [comment]
You've installed the `master` branch of my repo rather than the branch with the fix in. If you've cloned my repo, do `git checkout issue-3148` first, then install it.

**Comment by cr1ogen** [comment]
> You've installed the `master` branch of my repo rather than the branch with the fix in. If you've cloned my repo, do `git checkout issue-3148` first, then install it.

Doing what you told me `git checkout issue-3148`  fix the bar error

**Comment by elParaguayo** [comment]
Great. Thanks for confirming.

**Comment by cr1ogen** [comment]
Thanks to you

**Comment by m-col** [comment]
The PR was merged, so if the issue is fixed shall we close this?

**Comment by cr1ogen** [comment]
It fixed!! I close the issue. Thanks
