### ISSUE TITLE
Support for Window Buttons

### ISSUE THREAD

**Issue by tim-kilian** [qtile/qtile#3182]
![image](https://user-images.githubusercontent.com/5788010/148539901-0cf0d5ad-28de-4f3d-9b52-8837b2c19a78.png)

I know I know, it's a tiling window manager, BUT those 3 Buttons are part of window management. I use the keyboard most of the time, but sometimes it's much easier to click with the mouse, then to press a certain keyboard shortcut. Imo a WindowManager should handle those buttons well, because their purpose is window managing. The gnome applications do have them, but the qt applications do not. This feels a bit inconsistent, which is something I don't like. Also the functionality is a bit odd. The minimize button works well together with the TaskList widget. Also the close button works. But pressing the maximize window button do change the window somehow, but do not maximize it at all. I would expect a Fullscreen trigger. Also I would like to have them also on my non-gtk applications.

**Comment by elParaguayo** [comment]
As far as I understand it (i.e. I could be wrong), it's not that qtile is hiding those buttons, it's that they don't actually exist. Gtk windows use Client Side Decorations which is why those appear.

If you want those buttons on all windows, you'd need to modify the code to create and display those buttons. They would then be bound to `lazy.window.kill()` etc.

**Comment by m-col** [comment]
> As far as I understand it (i.e. I could be wrong), it's not that qtile is hiding those buttons, it's that they don't actually exist. Gtk windows use Client Side Decorations which is why those appear.

This is right - gnome applications are the ones being inconsistent here, as they provide their own client-side decorations, including those buttons. Other windows use server-side decorations, leaving it up to the window manager to provide those, allowing for a consistent appearance.

I see what you're saying, and indeed it would be nice to be able to enable such window decorations, but like you said Qtile is a TWM and generally those opt for simplicity, and implementing window decorations in X11 is a non-trivial task. Therefore there are no plans to implement them. That said, the desire for them has been discussed before (though unfortunately I can't find the other GH issue), and IIRC we concluded it saying we'd help review + merge a submission if somebody were to contribute it. I do worry about customisation and how far to go with that - Qtile is particularly unopinionated and customisable about appearance and so I would expect if we did implement title bars with buttons that many people would be requesting ways to customise them :smile: 

As an alternative solution that you could implement now is adding widgets to the bar to use instead. For example (untested):
```py
from libqtile import widget
from libqtile.lazy import lazy

kill = widget.TextBox("X", mouse_callbacks={"Button1": lazy.window.kill()})
minimize = widget.TextBox("-", mouse_callbacks={"Button1": lazy.window.toggle_minimize()})
maximize = widget.TextBox("=", mouse_callbacks={"Button1": lazy.window.toggle_maximize()})
```
Of course these could be `widget.Image` or any other widget to make them look how you want, or you could add more for `toggle_fullscreen`, `toggle_floating` or whatever you want.

**Comment by tim-kilian** [comment]
Hej. Thanks for your great answers! 

> it's not that qtile is hiding those buttons, it's that they don't actually exist. Gtk windows use Client Side Decorations which is why those appear.

I know about the fact, that gtk windows are inconsistent, but because of this I am biased towards gtk apps. I pick the gtk version if it exist, just to have these buttons in my tiling wm. I mean even if it's tiling, it is also a window manager. Tiling is the fact that I do not have to care about placement, not that I miss functionality. I still have and use a mouse, and I like it.

> unless you tell me all other tiling window managers have that functionality!

Why every tiling window manager have to be the same. I feel that qtile should support every feature possible and customize it to the moon. I dont see why the buttons are bad and why it should not be supported.


> implementing window decorations in X11 is a non-trivial task

I know,

> If you want those buttons on all windows, you'd need to modify the code to create and display those buttons.

but I try.

**Comment by elParaguayo** [comment]
> Why every tiling window manager have to be the same. 

It doesn't have to be the same but if we were the only window manager that wasn't doing this then I'd be more inclined to implement this as, otherwise, qtile would be an outlier compared to others.

> I feel that qtile should support every feature possible and customize it to the moon. I dont see why the buttons are bad and why it should not be supported.

One of the great things is that qtile is highly hackable/customisable and it can support a load of changes. However, the fact that it can be customised does not mean that every change will be included in the main codebase. Users are free to modify as they see fit.

The buttons aren't _bad_, it's just that some users prefer using key bindings and getting some extra screen space.

For the reasons above, I don't think either m-col or I will be working on implementing this. If someone else does, we'll take a look at it.

**Comment by m-col** [comment]
> However, the fact that it can be customised does not mean that every change will be included in the main codebase. Users are free to modify as they see fit.

Indeed - and the more customisable it is, the more code there is to maintain and the more bugs are introduced, and we're only a small team with limited time to contribute (more help is always welcome!).

>  My current TaskList widget looks like this. If there where a button for killing, it would satisfy my need for now I think.

That sounds totally reasonable as an addition. PR welcome if you would be interested :smile:

**Comment by Python-37** [comment]
https://github.com/qtile/qtile/issues/1699
