### ISSUE TITLE
Treetab does not show floating window in the sidebar

### ISSUE THREAD

**Issue by ShuxinLin** [qtile/qtile#3183]
![1_005](https://user-images.githubusercontent.com/8956612/148671589-7b434797-230d-4c26-bb4b-f33e5f29e2c0.png)
As shown in the screenshot, I have two windows open in the workspace, one terminal and one browser. The browser is floating. I can only see the terminal tab in the sidebar. I am using default `layout.TreeTab()` with some basic color settings. Is there any ways to show the tabs of floating windows as well?

**Comment by elParaguayo** [comment]
That's because floating windows are not part of the _layout_ but they are still part of the same _group_.

I think you'd need an option for the layout to also show windows that belong to the group.

**Comment by ShuxinLin** [comment]
Thank you. The windows in the same groups are not the set of windows in one layout. This seems unintuitive to me.

> I think you'd need an option for the layout to also show windows that belong to the group.

How can I do that? Any examples are welcome.

**Comment by elParaguayo** [comment]
I appreciate it may not seem intuitive but the point is that the layout is responsible for laying out the windows according to the layout's rules. When you float a window you're saying you don't want the layout to manage the position of the window so, at that point, the window is no longer managed by layout.

**Comment by ShuxinLin** [comment]
My observation is I can eventually move focus to any floating windows in other layouts (even Max) but not in TreeTab. I guess it is how it is implemented. My current workaround is to add TaskList to the panel so I can bring floating windows to front easily. 

Thanks for the amazing wm! You can close the issue

**Comment by elParaguayo** [comment]
If floating layouts are included in other layouts then we should try to be consistent here too.

I won't close just yet and will try to take a look to see if there's a quick fix later.

**Comment by ShuxinLin** [comment]
> My observation is I can eventually move focus to any floating windows in other layouts (even Max) but not in TreeTab. I guess it is how it is implemented. My current workaround is to add TaskList to the panel so I can bring floating windows to front easily.
> 
I guess I was wrong. It is not possible to switch focus to floating windows in any layouts. Sorry for the misleading information :)
