### ISSUE TITLE
`GroupBox` widget ignores `fmt`

### ISSUE THREAD

**Issue by MithicSpirit** [qtile/qtile#3185]
Setting the `fmt` kwarg in `GroupBox` to anything does not affect the widget in any way. Since it's not really a normal widget in terms of what it displays this somewhat makes sense, though I think it'd be better if `fmt` was applied to each of the groups that is displayed.

**Comment by elParaguayo** [comment]
Interesting question.

`fmt` is only shown as a configuration option for `GroupBox` because it inherits from `base._TextBox`. However, from what I can tell, the widget is not using any of the functionality from `base._TextBox`, hence why this is ignored.

There are two options here:

1. Stop inheriting from `_TextBox`. This would remove the `fmt` option from the docs which should reduce confusion.
2. Format the box label in accordance with `fmt`.

Given that the widget displays the group's label (not its name), I'm inclined to go with option 1 as it should be possible to format the groups' labels when they're being created without the need for additional formatting.

**Comment by m-col** [comment]
Or perhaps just don't use `_TextBox.__init__`?:

```diff
diff --git a/libqtile/widget/groupbox.py b/libqtile/widget/groupbox.py
index 2a754d4d..85559d48 100644
--- a/libqtile/widget/groupbox.py
+++ b/libqtile/widget/groupbox.py
@@ -45,7 +45,9 @@ class _GroupBase(base._TextBox, base.PaddingMixin, 
base.MarginMixin):
     ] # type: List[Tuple[str, Any, str]]

     def __init__(self, **config):
- base._TextBox.__init__(self, width=bar.CALCULATED, **config)
+ _Widget.__init__(self, width=bar.CALCULATED, **config)
+ self.layout = None
+ self._text = ""
         self.add_defaults(_GroupBase.defaults)
         self.add_defaults(base.PaddingMixin.defaults)
         self.add_defaults(base.MarginMixin.defaults)
```

**Comment by elParaguayo** [comment]
That's the point. It uses `base._TextBox.__init__` but `base._Widget._configure` so why not inherit from `base._Widget` instead?

**Comment by elParaguayo** [comment]
The `fmt` attribute doesn't determine whether pango markdown is allowed or not. That's a separate option that's set when creating a text layout. You can still enable pango markdown with option 1.

**Comment by MithicSpirit** [comment]
Well yeah you can enable markdown but you can't use it if you have no way to set the format string. Unless there's another way to use the markdown I'm not aware of? But on other widgets I generally just do something like `fmt="<b>{}</b>"`.

**Comment by elParaguayo** [comment]
Markdown just applies on the text string so you can add formatting directly to it without using `fmt`. e.g. you could do
``` python
groups = [Group(i, label=f"<b>{i}</b>") for i in "123456789"]
```

**Comment by MithicSpirit** [comment]
Huh that doesn't work for me. Instead it just explicitly shows the `<b>` and `</b>` tags. 

In general pango markdown only works for me when I include it in `fmt`. For example in `WindowName` if I set `format="<b>{state}{name}</b>"` then it will display the tags verbatim, but if I use `fmt=<b>{}</b>` instead it works fine. I assume this is on purpose and any markdown characters get escaped so that if a markdown sequence is somehow included in a window title it doesn't cause formatting.

**Comment by elParaguayo** [comment]
Groupbox does not have markdown enabled (you can't toggle it as an option - it's currently hard coded) so using tags won't work at the moment.

My point was that has nothing to do with using `fmt`.

**Comment by MithicSpirit** [comment]
Ah ok makes sense.

**Comment by elParaguayo** [comment]
Sorry. Also edited my post as you were replying. See my additions.

**Comment by m-col** [comment]
> That's the point. It uses base._TextBox.__init__ but base._Widget._configure so why not inherit from base._Widget instead?

But doesn't it also use methods that are inherited from _TextBox?

**Comment by elParaguayo** [comment]
Don't think so. Text is set directly in the `drawbox` method and doesn't use the `text` setter from `_TextBox`. No formatting is applied.
