### ISSUE TITLE
Wrong screen order

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#3186]
This is to continue the discussion with @PucklaMotzer09 from #3151 as that should just be a discussion for that PR and I'm not sure we've resolved.

@PucklaMotzer09 can you please exit and restart qtile and post the following:

- the output of `xrandr --listmonitors`
- those log lines from the function I gave you

I'd also like to see your config file.

Qtile should be ordering the screens based on the order in that `xrandr` command i.e. the first screen will be mapped to the first screen in your config. If that's not happening, then we need to do some more digging to find out why!

**Comment by PucklaMotzer09** [comment]
1. I deleted my log file and logged out and in.
2. `xrandr --listmonitors`
```
Monitors: 2
 0: +HDMI-A-0 1920/477x1080/268+1440+0  HDMI-A-0
 1: +DVI-D-1 1440/410x900/257+0+0  DVI-D-1
```
3. `.local/share/qtile/qtile.log`
```
2022-01-11 17:18:31,341 WARNING libqtile config.py:scr_change():L41 Screen change event qtile.cmd_screens()=[{'index': 0, 'group': '1', 'x': 0, 'y': 0, 'width': 1920, 'height': 1080, 'gaps': {'top': (0, 0, 192
0, 30), 'bottom': None, 'left': None, 'right': None}}, {'index': 1, 'group': '2', 'x': 1920, 'y': 0, 'width': 1440, 'height': 900, 'gaps': {'top': (1920, 0, 1440, 30), 'bottom': None, 'left': None, 'right': No
ne}}]
2022-01-11 17:18:31,343 WARNING libqtile config.py:scr_change():L41 Screen change event qtile.cmd_screens()=[{'index': 0, 'group': '1', 'x': 0, 'y': 0, 'width': 1920, 'height': 1080, 'gaps': {'top': (0, 0, 192
0, 30), 'bottom': None, 'left': None, 'right': None}}, {'index': 1, 'group': '2', 'x': 1920, 'y': 0, 'width': 1440, 'height': 900, 'gaps': {'top': (1920, 0, 1440, 30), 'bottom': None, 'left': None, 'right': No
ne}}]
```
Well, the order of the screens is correct, but the position is wrong. The HDMI one should be at an x position of 1440. Which is the case right after booting/logging in. If I restart qtile everything is were it should be and also the log lines report the same.

4. My config is a modified version of the default Garuda Linux Qtile config
[config.txt](https://github.com/qtile/qtile/files/7848182/config.txt)

**Comment by elParaguayo** [comment]
Thank you. Looks like we need to understand why the positioning isn't being changed even though the order is correct.

Leave it with me.

**Comment by elParaguayo** [comment]
Is there any chance you've got two versions of qtile installed?

I've just tried replicating your screen set up (with monitor 0 being to the right of monitor 1) and it works fine with that PR but is completely broken on v0.19.0.

**Comment by PucklaMotzer09** [comment]
Well yes, I do still have installed the 0.19.0 release of qtile through pacman. That's why I thought that it may be that I am not running your version. Your version is installed in `/usr/lib/python3.10/site-packages/qtile-0.16.2.dev907+gf8b08dde-py3.10-linux-x86_64.egg/libqtile` and `/usr/bin/qtile` is also refering to it via `__requires__ = 'qtile==0.16.2.dev907+gf8b08dde'`. But I always suspected that I might still be running the normal 0.19.0 version.

**Comment by elParaguayo** [comment]
If the `libqtile` library is under that `.egg` folder then I don't think it will be loaded when you run qtile. Instead, it would load libraries from `/usr/lib/python3.10/site-packages/libqtile`.

Also, if this is in `/usr/lib` then you must have done `sudo pip install`. This isn't a great idea as it can muck up pacman's database as you're adding files that pacman doesn't know about.

**Comment by PucklaMotzer09** [comment]
I didn't do `sudo pip install` directly. `qtile` has been installed by the OS and updated through pamac. Maybe pip is used there. To "install" your version I executed `sudo python3 settup.py install` in the repository after checking out your fork.

Well, how do I set it up savely (without screwing up qtile or my system)?

**Comment by elParaguayo** [comment]
Your use of `sudo python3 setup.py install` is what will have put this into the `/usr/lib` folder. `pamac` will install packages using root so they will also go into `/usr/lib`.

Let's just check which version is installed in `/usr/lib/python3.10/site-packages/libqtile`. Can you open `/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py`. Can you paste the `__init__` method from `class RandR` which should be line 406.

**Comment by PucklaMotzer09** [comment]
This is my `__init__` function:

```python
def __init__(self, conn):
         self.ext = conn.conn(xcffib.randr.key)
         self.ext.SelectInput(
             conn.default_screen.root.wid,
             xcffib.randr.NotifyMask.ScreenChange
         )
```

**Comment by elParaguayo** [comment]
Ha. Ok. So you're almost certainly **not** running my changes. Thank goodness for that. I was going mad trying to work this out!!

What I would suggest you do is clone the main qtile/qtile repo and have a look at this page: http://docs.qtile.org/en/stable/manual/hacking.html which tells you how you can run a different qtile setup.

But you should really avoid installing a second version of qtile with `sudo`.

**Comment by PucklaMotzer09** [comment]
I just skipped doing it savely. I just sudo copied your version of libqtile into `/usr/lib/python3.10/site-packages` and well, it works! :grin: 
They bars are in the correct location.

**Comment by m-col** [comment]
Just in case, because I don't see it mentioned already - note that a monitor can be marked as the 'primary' monitor and this will always be used for the first `Screen` by Qtile.

**Comment by elParaguayo** [comment]
The fix has been merged. So closing this.
