### ISSUE TITLE
Restarting Qtile while browsers running sometimes results in audio control to break.

### ISSUE THREAD

**Issue by agoodfellow123** [qtile/qtile#3188]
Hello there, while I was configuring my Qtile I realized my sound widget was showing "M" for mute. I tried to unmute it but it did not work after a while I opened a video and realized that sound plays perfectly fine despite the widget showing "M", the only broken thing is the widget and volume control hotkeys. After another while, I closed one of my browsers and realized that my widget started to work again. However, that's a fifty-fifty solution because sometimes closing all the windows and even restarting after closing them doesn't solve this issue. Also running pulsemixer in the terminal when this bug occurs gives the "Failed to connect to pulseaudio" error.

**Comment by elParaguayo** [comment]
Thanks. Are you using the `PulseVolume` widget?

**Comment by agoodfellow123** [comment]
No, I'm using the `volume` widget.

**Comment by elParaguayo** [comment]
Are there any error messages in your logs.

**Comment by agoodfellow123** [comment]
Yeah there are numerous errors but I don't know which one is related to this: http://ix.io/3LV6

**Comment by elParaguayo** [comment]
That link just gives me the path to your log, rather than the contents of the log.

**Comment by agoodfellow123** [comment]
I am sorry about that here is the right one: http://ix.io/3LV9

**Comment by elParaguayo** [comment]
Are you the same person who posted about the clock on reddit?

**Comment by agoodfellow123** [comment]
No.

**Comment by elParaguayo** [comment]
OK. Well you've got the same function and variable names from their code in your error...

Anyway, can you share your config line for the volume widget. The error suggests there's a bad mouse callback configured there.

**Comment by agoodfellow123** [comment]
Ok, you caught me I'm the Reddit guy, so much for privacy :/
Here is the volume widget: `widget.Volume(step=5, mouse_callbacks={'Button3': lambda: qtile.cmd_spawn(terminal + ' -e pulsemixer')}),`
I should add though, that error did happened before adding mouse_callbacks too.

**Comment by elParaguayo** [comment]
I've tidied up the thread a bit.

The callback errors say that spawn couldn't find `exec` so I'm not sure what you've got set as `terminal` in your config. 

Anyway, if the errors happened before then I wonder if it's to do with the rapid polling that's done by this widget. What happens if you change `update_interval`?

It's also possible that it's not qtile that's broken here and that your browser is locking the audio device when it restarts so the widget can no longer poll the volume command to get current levels.

**Comment by agoodfellow123** [comment]
I use Alacritty as terminal.
Sure I can remove `update-interval` and give it a go.
Before Qtile I was using Bspwm with Polybar with the same browsers, no such error occurred.

**Comment by elParaguayo** [comment]
Don't remove `update_interval` try setting it to something like `1` or `2`.

**Comment by agoodfellow123** [comment]
Sadly it did it again. But this time it took a while.

**Comment by m-col** [comment]
`Volume` uses alsa controls but it looks like you're using pulseaudio. Try the `PulseVolume` widget, which uses a different interface to interact with the audio server. Perhaps it will work a bit better!

**Comment by agoodfellow123** [comment]
Ah, I didn't know that, thanks, I'll test it and see if it also does the same thing. There is one odd problem though, volume always shows 1% lower than what is on pulsemixer.

**Comment by m-col** [comment]
That could be a rounding error. If you change the `int()` to a `round()` is it improved?: https://github.com/qtile/qtile/blob/master/libqtile/widget/pulse_volume.py#L239

**Comment by agoodfellow123** [comment]
Yes round instead of int solved that problem, thank you! I'm trying to replicate the other issue.

**Comment by agoodfellow123** [comment]
Hey so, I haven't been able to recreate the bug in qtile because it requires me to:
1. Edit the config.
2. Restart.
3. Repeat the first two steps for half an hour.
But one interesting thing happen, I was editing my bspwmrc and almost the same thing happened there (I'm saying almost because when that happens qtile doesn't let me change the volume via hotkeys but bspwm did).
So I think it's safe to say it's a pulseaudio problem rather than qtile, albeit it's triggered by restarting the wm too much.

Thank you for your support.
