### ISSUE TITLE
Sreen tearing

### ISSUE THREAD

**Issue by ayman20-py** [qtile/qtile#3189]
Whenever there is a video or im scrolling there are some vertical tearings that occur on the screens and its annoying and I couldnt find anything about it.

Is there something I can do?

**Comment by elParaguayo** [comment]
Screen tearing shouldn't be a qtile issue (unless you're saying you don't see the same tearing in other window managers). 

It's likely to be something with your video driver and/or compositor.

**Comment by m-col** [comment]
If you aren't already using a compositor then I suggest checking out `picom`, it should be in your distro's repos

**Comment by ayman20-py** [comment]
Thx a lot man. One more question, is there any config to do or just download it is enough? Cause I downloaded it, reload the WM and it worked but just to be sure tho?

**Comment by m-col** [comment]
It can be configured further, check out `man picom` for more info.

**Comment by marcinkosztolowicz** [comment]
In my case I used compton compositor

config file: /etc/xdg/compton.conf

```
backend = "glx";
vsync = true;
```

**Comment by marcinkosztolowicz** [comment]
I have to fix a bit my answer. After  OS change I had some problems with screen resolution change. The screen was shifted. Compton was the issue here, and I had to change compton config a bit
```
backend = "glx";
vsync = true;
paint-on-overlay = true;
```
