### ISSUE TITLE
Random teleportation of floating apps when moving it from one screen to another screen

### ISSUE THREAD

**Issue by Javigo07** [qtile/qtile#3192]
Hi. I'm not sure if this is the same as  #2754 but the thing is: I have two screens, whenever I try to move a floating app (terminal, file manager or anything) I'm unable because it moves randomly between screens, as shown in the video. I'm using Qtile 0.19.1 on Gentoo. While using Qtile 0.17.0 (the latest on Gentoo repos, don't know why) it worked fine.  I built it from source ofc.

(On the video screen one is the left side, the second one is the right side).  

https://user-images.githubusercontent.com/37010420/149448784-d5e965c3-6e61-471c-b207-72e34ec83968.mp4

**Comment by elParaguayo** [comment]
Hmm. I can't replicate this on v0.19. Dragging floating windows between screen works fine for me. Can you share your config?

**Comment by Javigo07** [comment]
[Here is it](https://github.com/Javigo07/.config/tree/main/qtile). I tried default config and it works fine. Am I doing something wrong on my config?

https://user-images.githubusercontent.com/37010420/149559571-64513936-e3f7-4794-b603-e55c6b9fb152.mp4

**Comment by m-col** [comment]
I looked through your config and nothing jumps out as obviously bad. I suggest going through it disabling chunks of it at a time to try to identify the problematic piece of code. The first thing to try is the values of the simple variables defined in https://github.com/Javigo07/.config/blob/main/qtile/config.py. Perhaps there is a bug when one of those is changed.

**Comment by Javigo07** [comment]
I found it. When I set cursor_warp to True is when the bug occurs, when I set it to False it doesn't happen.

**Comment by elParaguayo** [comment]
Hmm. I did wonder if this was related to the other cursor warp issue we'd seen.

**Comment by m-col** [comment]
Sounds exactly like it. Might it be fixed on master then?

**Comment by elParaguayo** [comment]
Maybe. However, the Chrome bug is still unfixed.

@Javigo07 - are you able to test the latest Master branch. We've merged a commit today that changes some of the cursor warp code.

**Comment by Javigo07** [comment]
I've just tried qtile 0.19.1.dev36+gab04c7c5 and it didn't worked. The bug persists.

**Comment by elParaguayo** [comment]
Thanks for confirming - I thought that may be the case.

There's clearly still an issue with warping when moving windows. We need to disable the warp whenever we're dragging.

**Comment by Javigo07** [comment]
Is there anything else I can help you with?

**Comment by elParaguayo** [comment]
Not yet. Once we've found a fix, would be great if you can test it.
