### ISSUE TITLE
[Wayland] Random ghost windows on second screen

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3199]
Since using Qtile with Wayland on dual screens I have noticed a bug that sometimes occurs only when a window is open on the right side of screen 0 . Sometimes it manifests as a flickering ghost image then others as in this picture is just like an empty terminal. It's quite random but does happen often and of course nothing in the log files either.
![IMG_20220110_221732](https://user-images.githubusercontent.com/1571498/149627318-1ce09d36-aa55-4260-a012-92cab32fd1ec.jpg)

**Comment by m-col** [comment]
Which terminal is that on the right side of the big monitor?

What desktop geometries are they using? Any scaling?

One thing that might be interesting is doing `qtile cmd-obj -o window -f info` from that terminal when the ghost window appears to get its dimensions from the point of view of Qtile.

**Comment by justinesmithies** [comment]
The terminal is Kitty but this can happen with other windows too it's very random though and I can't seem to trigger the bug on demand. Both screens are running 1920x1080 with no scaling. When it does happen again I'll be sure to run `qtile cmd-obj -o window -f info` though.

**Comment by m-col** [comment]
Could you also post the output of `qtile cmd-obj -o cmd -f screens` when it happens - just in case something's got qtile confused about the screen configuration

**Comment by justinesmithies** [comment]
I got it to happen again briefly but it disappears when typing sometimes or if you move the cursor. I had Qutebrowser opened on screen 0 group 1 and then set screen 1 on the right to an empty group 4. I opened one kitty terminal on screen 0 group 2 then another and that's when the ghost half window appeared on screen 1. I managed to run both commands as requested before it vanished again.
[Output of commands run](https://paste.sr.ht/~justinesmithies/a70760cbf960af8444c0d2dad312e10c0a1df873)

**Comment by m-col** [comment]
OK, thanks for the info. I think I have figured it out. We mark an output as damaged and in need of a new frame upon certain events. I think what's happening here is a state change in one of your terminals (e.g. from floating to tiled) when it overlaps both monitors, but only one (the one where the window ends up on) is getting updated. If I float a window across both monitors with no other windows visible, then make it tile, then the monitor that no longer has the window visible on it retains the old pixels. If you play around with that behaviour, is that consistent with what you're seeing?

**Comment by justinesmithies** [comment]
Managed to get some output from the log with debug if it helps when it happens ??

[https://paste.sr.ht/~justinesmithies/d6364fc94e0545b27f3dc2bca40d55c46b8f769c](https://paste.sr.ht/~justinesmithies/d6364fc94e0545b27f3dc2bca40d55c46b8f769c)

**Comment by justinesmithies** [comment]
Sorry just tried what you said and that is exactly what I'm seeing. Glad it's not just me losing it. ;)

**Comment by m-col** [comment]
Great - I'm pretty sure what's going on then. I think a few different operations can trigger it but it's the same effect. I'll take a look at figuring out a fix.

**Comment by m-col** [comment]
https://github.com/qtile/qtile/pull/3202 will fix this under some circumstances, but not all. Sometimes the geometry of a window according to Qtile gets de-synchronised with what the window thinks, and if we tell a window to change size (for example moving a full-width window from a right hand monitor to the left hand monitor, and take up half the screen in the tiled layout) then sometimes it can delay its own resize long enough (i.e. at least one frame) for us to have refreshed all outputs using Qtile's geometries, but what gets rendered is the window's understood geometry. This can cause a window's right side to spill out of the tiled layout and onto the next screen. In this situation, the screen refresh has already happened, and so the ghost window is seen.

To fully fix this we need proper synchronicity between Qtile's state and client state. This will improve rendering greatly in other ways. It's being worked on in https://github.com/qtile/qtile/pull/2911. Also see issue https://github.com/qtile/qtile/issues/2544

**Comment by justinesmithies** [comment]
This certainly fixes my issues. Thanks ;)

**Comment by m-col** [comment]
Going to close this now as the fix has been merged. The remaining fix for the ghost windows is WIP, and any further discussion on that can be kept to #2544. Thanks for the report!
