### ISSUE TITLE
Paste buffer in cage apps not shared with qtile apps

### ISSUE THREAD

**Issue by mhwombat** [qtile/qtile#3211]
The docs say

> Qtile does not support XWayland directly and there are no plans to implement XWayland support. Instead, the recommended way to run any programs that do not support Wayland themselves is to run them inside the cage Wayland compositor, which will contain the program inside a window that does support XWayland. 

It seems that the apps running in `cage`s have separate paste buffers, so I cannot copy and paste among them, or between them and the wayland apps. Is there a workaround for that?

**Comment by m-col** [comment]
Unfortunately not. I am open to XWayland support if it were to be contributed. Eventually I will look into adding support but it is low on my to-do list I'm afraid.

**Comment by m-col** [comment]
For the paste-buffer issue itself, I think a tool would be needed for synchronising buffers between wayland displays, which I guess would be possible, but it's outside of the scope for an individual compositor.

But to update on your use case: I went ahead and implemented XWayland support, see https://github.com/qtile/qtile/pull/3209. It will be in the next release. No need for the cage workaround.

**Comment by mhwombat** [comment]
Thank you so much!

**Comment by m-col** [comment]
XWayland is now supported in the latest release 0.20.0. Currently there is an annoying bug for override-redirect windows which means they don't get keyboard focus right away, but that'll get patched ASAP. Regular windows will work fine. I'll close this. Thanks for the issue!
