### ISSUE TITLE
Systray icons disappear on lazy restart

### ISSUE THREAD

**Issue by smsteward** [qtile/qtile#3215]
I checked the open issues against the "systray" string and didn't see an open issue related to this, so decided to open one myself.

I've noticed that anytime I do a lazy restart for whatever reason (changing config file, refreshing weather widget, etc) that my systray icons disappear. The only way to recover them is to fully quit Qtile and log back in. I usually have 2-3 items in my systray at any time (my VPN indicator, redshift indicator, and my music player indicator are the most common ones), and they are all lost on a Qtile lazy restart. Quitting and reloading the app whose icon was in the systray does not help under most circumstances (only one or twice did it work successfully).

My config and autostart.sh files are attached as .txt files since the uploader won't accept .py or .sh files

[autostart.txt](https://github.com/qtile/qtile/files/7884851/autostart.txt)
[config.txt](https://github.com/qtile/qtile/files/7884852/config.txt)
.

**Comment by elParaguayo** [comment]
Ha. It's #3210 and a fix is in #3214.

**Comment by smsteward** [comment]
Oh perfect. Thanks so much! I did see that issue but didn't connect it to this one. I'll go ahead and close this then since a fix is in the works.

**Comment by elParaguayo** [comment]
No problem. Thanks for reporting a problem.
