### ISSUE TITLE
[ Wayland ] Notifications under Dunst freeze on screen if multiple are activated in quick succession

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3216]
This works fine under X but under Wayland if I trigger the same notification in quick succession then the last notification stays on screen for ever and no more are displayed. If I examine dbus I can see that dunst is still running in the background and possibly thinking that it is still displaying new notifications. The only way to get them working again is to pkill dunst. If you trigger a notification and wait for it to clear off screen then it runs no problem. The issue occurs if you trigger them one after the other like i do when sending a notification about volume changes or brightness or even skipping tracks on spotify.

**Comment by m-col** [comment]
Thanks for reporting!

I can reproduce it easily with this: `notify-send one two; sleep 1; notify-send two three`. Works fine in sway.

**Comment by m-col** [comment]
I think https://github.com/qtile/qtile/pull/3209 fixes it (second commit).
