### ISSUE TITLE
Notify widget should un-register from dbus when finalized

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#3223]
Without doing so, reloading the config when a `Notify` widget was previously used but now is not, the dbus interface remains in a registered state. This prevents other processes from registering on that interface.

**Comment by elParaguayo** [comment]
This one needs a little work. If I call `org.freedesktop.DBus.ReleaseName` I get a `RELEASED` reply but the service is still running...

**Comment by m-col** [comment]
Thanks for the very quick bug fix!
