### ISSUE TITLE
Position of floating windows, XGetGeometry

### ISSUE THREAD

**Issue by Tokariew** [qtile/qtile#3227]
Not sure if it's a bug on Qtile part…
I play simple game TomeNET in floating windows on Qtile, but I needed to patch game, because compared to i3, Qtile returns different values when asked about `XGetGeometry`, by the game. Relevant part of game code start [here](https://github.com/TomenetGame/tomenet/blob/100ba368b7b076f018deaa06663280099b63232f/src/client/main-x11.c#L2923). At least i think…

The i3 with default config, for all windows return `x_return` as 2 and `y_return` as 0, when Qtile return position from top left corner of display to left upper corner of window border.
I dirty patched game for myself, but maybe it should be fixed here instead?
https://github.com/TomenetGame/tomenet/issues/18 Issue on game part…

So, as I understand
i3 return position of windows, from it's own border, when Qtile return position within X Display, when asked by `XGetGeometry`

**Comment by m-col** [comment]
Could you post the diff you used to patch the game?

**Comment by Tokariew** [comment]
```
diff --git a/src/client/main-x11.c b/src/client/main-x11.c
index 93116f125..49416f6d3 100644
--- a/src/client/main-x11.c
+++ b/src/client/main-x11.c
@@ -2936,8 +2936,8 @@ void x11win_getinfo(int term_idx, int *x, int *y, int *c, int *r, char *fnt_name
 //	printf("XTranslateCoordinates: x = %d, y = %d\n", *x, *y);
 
 	/* correct window position to account for X11 border/title bar sizes */
-	*x -= x_rel;
-	*y -= y_rel;
+	*x = x_rel;
+	*y = y_rel;
 }
 
 void resize_main_window_x11(int cols, int rows) {
```
I just take position returned by `XTranslateCoordinates`. But that only work for Qtile, on i3 or openbox the windows are moving, with each consequence run of game client. On qtile, there are staying in place.

**Comment by Tokariew** [comment]
`x_rel` and 'y_rel' are `x_return/y_return` from `XGetGeometry`
and `XTranslateCoordinates` is used to return position from root window/display in game…

**Comment by Tokariew** [comment]
sorry, in between qtile and game updates it was fixed…

**Comment by m-col** [comment]
Do you know where the problem was?

**Comment by Tokariew** [comment]
The issue is present in qtile 0.18.1, but not in 0.19, so somewhere in between releases it was fixed here.
sorry for writing issue before updating Qtile. On weekend i can check which commit fixed it

**Comment by m-col** [comment]
No worries. I suspect it might have been bd386eaa976b1700dee5a1371d9f51a59d4a653e, https://github.com/qtile/qtile/issues/3011
