### ISSUE TITLE
Widget backgrounds with transparency broke

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#3234]
Hey there. I just updated from v0.17.0-134-g3e899ddb (3e899ddb) to v0.19.0 and found that my bar looks very different.

I did a bisect. The relevant commit is 262ad832b3125e813085c3cece7e7baccf5295de from #2513 

Before (good)

![image](https://user-images.githubusercontent.com/94108/150643235-3955474e-eaad-4231-a3b6-72014ebf15e0.png)

After (bad)

![image](https://user-images.githubusercontent.com/94108/150643244-06d97edb-fffa-4364-8296-571f0671beff.png)

Relevant section of the config:

```
    widget.GroupBox(
        padding_x=8,
        padding_y=1,
        margin=0,
        borderwidth=0,
        inactive="606060",
        this_current_screen_border='44B1FF.45',
        urgent_alert_method='block',
        urgent_border=["FF0000", "660000"],
    ),
    widget.TaskList(
        padding_y=1,
        padding_x=10,
        margin=0,
        borderwidth=0,
        border='44B1FF.45',
        highlight_method='block',
        rounded=False,
    ),
```

I use `border='44B1FF.45'`  (which becomes a background through `highlight_method='block'`) to have a 45% opacity background. With this commit the opacity went away.

This also affected another widget where i use `foreground="FFFFFF.6"`

**Comment by elParaguayo** [comment]
What's you bar's background colour?

**Comment by elParaguayo** [comment]
I suspect you've got a fully opaque bar which means the bar is setting a 24bit colour depth but you want 32bit for the transparency in the widgets. If that's the case, try setting your bar's opacity to 0.99 (anything less than 1 should force the bar to use 32bit depth) but I think this will muck up `Systray` if you're using it.

**Comment by dequis** [comment]
Uh, it's this gradient:

```
>>> c = lambda *x: [str(y)*6 for y in x]
>>> background = c(0,0,0,0,0,0,1,2,4)
>>> background
['000000', '000000', '000000', '000000', '000000', '000000', '111111', '222222', '444444']
```

I added

```
background[0] += '.99'
```

Systray looks fine.

**Comment by elParaguayo** [comment]
Did adding the .99 fix the transparency?

**Comment by dequis** [comment]
Yep. It's a hack though.

**Comment by elParaguayo** [comment]
It is but at least I know what is causing the issue! So now we need to think how best to fix it...

The 24bit colour depth for the bar is because the `Systray` looks ugly with a semi transparent background as we can't (easily) have a semi transparent background for the icons.

I think the best we can do is add a config option in the bar to force 32bit depth even if the bar's background is opaque.

We could check widget `background`s but that doesn't pick up the highlight colours that widgets may also have.

Thoughts? any preference?

**Comment by dequis** [comment]
>I think the best we can do is add a config option in the bar to force 32bit depth even if the bar's background is opaque.

Maybe!

>We could check widget backgrounds but that doesn't pick up the highlight colours that widgets may also have.

Yeah I guess this could fail in the same way the current heuristic fails.

And I just realized, my systray looking "fine" just meant it has a solid black background, possibly from my lack of wallpaper, which blends nicely with how subtle the gradient is.

If I start picom (which i normally don't use) my wallpaper becomes solid gray

![image](https://user-images.githubusercontent.com/94108/150645387-dd4e9131-dfc6-497e-bf23-dfc9c75f445e.png)

If I go back to solid bar backgrounds I get this, note also the "x" on the left side becoming white.

![image](https://user-images.githubusercontent.com/94108/150645775-42aef0f2-cea2-43dd-a7ae-fd6ce747c10c.png)

(interestingly it's offset by one pixel, might have been that way since forever though)

If I go back to the commit I was in before (3e899ddb), I get both that gradient background *and* the opacity of other widgets works fine (note the x on the left side being gray instead of white)

![image](https://user-images.githubusercontent.com/94108/150645519-9330e887-f31e-4ef9-9407-b942d78579a3.png)

So it sounds like the previous state should be achievable?

As far as I can tell the previous version was using this to create the bar window, depth was not configurable:

```
self.conn.core.CreateWindow(
    self.default_screen.root_depth,
```

`xwininfo -root` says depth 24.

So something about the previous version was capable of having a window with depth 24 and opacity in individual widgets

**Comment by elParaguayo** [comment]
Thanks for this.

I don't think you were getting proper transparency without picom running as X11 doesn't handle transparency without a compositor so I think you got something that looked like transparency given your solid background behind the widget.

**Comment by elParaguayo** [comment]
As for the grey background on Systray, yeah, that's the issue I was referring to.

**Comment by elParaguayo** [comment]
If you weren't using true transparency before (which I suspect is the case), you could just change the colours you were using to being lighter versions (i.e. the equivalent colour of your highlight colour on top of your solid background).

**Comment by elParaguayo** [comment]
Here's a 32bit bar with transparency on the widget background ("ff00ff.10").
With picom:
![20220122_164702](https://user-images.githubusercontent.com/946265/150647906-334f81cf-4dad-4be8-a29d-7dc89642e0ac.png)
Without picom:
![20220122_164641](https://user-images.githubusercontent.com/946265/150647912-94b05985-b309-44b8-93bd-278162e156b1.png)

Notice the difference. With picom, this is looking through to my wallpaper. Without picom, the colour has just been dimmed but it is not transparent.

**Comment by elParaguayo** [comment]
Lastly, I don't think the one pixel shift is anything to do with the changes and I doubt there's much we can do about it.

**Comment by elParaguayo** [comment]
@dequis I'm closing this as I don't think there's actually an issue in qtile here but reopen if you think otherwise.

**Comment by elParaguayo** [comment]
@dequis if you're interested, there's a PR adding pseudotransparency to the bar/widgets which helps with some of the rendering issues: #4126
