### ISSUE TITLE
Qtile bar window class (for compton selection)

### ISSUE THREAD

**Issue by kovasap** [qtile/qtile#3236]
I use compton to selectively dim certain windows (among other things).  Compton uses X window properties to select which windows to apply effects to, like this: https://github.com/kovasap/dotfiles/blob/d260b4fd47fd10156520e7c4c67d392c5e1e3344/bin/run-compton.bash#L6.  I'd like to add the qtile bar to the linked exclusion list for my compton shader effect.  However, when I try to use `xprop` to get the window class of the qtile bar, I get this paltry (compared to other windows) output:

```
_NET_WM_WINDOW_OPACITY(CARDINAL) = 3435973836
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
QTILE_INTERNAL(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
```

Does anyone know if there is a way to give the QTile bar a window class, or otherwise select it in my compton config?

**Comment by kovasap** [comment]
`xwininfo` likewise shows no name or class:

```
> xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x140009d (has no name)
```

**Comment by elParaguayo** [comment]
Have a look at #2526.

Works for picom - no idea about compton.

**Comment by kovasap** [comment]
Thanks for the link!  I ended up using https://github.com/qtile/qtile/issues/2526#issuecomment-860244247 to set the WM_NAME like this: https://github.com/kovasap/dotfiles/blob/63735c2cc4029da9a35d58e7414f05637998f97c/.config/qtile/config.py#L478, then I set the compton rule referencing that name: https://github.com/kovasap/dotfiles/blob/63735c2cc4029da9a35d58e7414f05637998f97c/bin/run-compton.bash#L6
