### ISSUE TITLE
CPU current frequency is reported incorrectly

### ISSUE THREAD

**Issue by smsteward** [qtile/qtile#3240]
I've noticed for a while that the CPU frequency widget was always displaying "0.0GHz". After examining the source code for the widget and checking the output of `psutil.cpu_freq()` in my own Python console, I noticed that `psutil` reports the current frequency differently than it reports min and max. The formulas for frequency min and max in `libqtile.widget.cpu` are correct, but for current frequency, it shouldn't be divided by 1000.

I was able to fix this issue by changing line 52 of "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py" from `variables["freq_current"] = round(freq.current / 1000, 1)` to `variables["freq_current"] = round(freq.current, 2)`

I've attached a screenshot to demonstrate what I saw in my Python console. Not sure if anyone else was seeing this issue, or if maybe my system was a fluke. I'd be happy to submit a pull request if this is affecting others, since my change above did fix it for me
![2022-01-23-194605_737x261_scrot](https://user-images.githubusercontent.com/94140636/150706002-3b424f02-2363-481c-b222-509f5f4e0bcd.png)
.

**Comment by elParaguayo** [comment]
It's a known issue. There is actually a bug in `psutil`. Once that's updated this will work again (and your widget will start reporting the wrong values until you undo your change).

I'm not planning on updating the widget for this
