### ISSUE TITLE
Active floating window color is not configurable

### ISSUE THREAD

**Issue by the-argus** [qtile/qtile#3241]
The #0000FF color of selected floating window borders cannot be changed. This is not an issue with the floating layout, but rather with all floating windows present in any layout.

I also observed that, when using the floating layout, the blue border is not initially present until you attempt to float or resize or move a window.

To reproduce, use the builtin layout.Tile layout, configure the border_active and border_normal to be colors distinguishable from blue, bind a key to lazy.window.toggle_floating, and press it while a tiled window is focused. The border will become blue.

**Comment by elParaguayo** [comment]
Once a window is floating, it's not managed by the group's layout configuration.

You have to add the border colour definition to the  floating layout section:
https://github.com/qtile/qtile/blob/6783b67196cc2bcdc38880b411b6344fb1d9139a/libqtile/resources/default_config.py#L166

**Comment by elParaguayo** [comment]
Not quite like that.

First off, don't add `floating` to your `layouts` unless you want an option when all windows will float.

What you need to do is add the `border_focus` etc. to the `Floating` definition that I've linked in the default config. The should be a line starting `floating_layout = `. This is the layout that you need to edit.

**Comment by the-argus** [comment]
Thanks for the quick replies. I was confused because I didn't understand that `floating_layout` was a special qtile config variable. Got it now.

**Comment by elParaguayo** [comment]
> Thanks for the quick replies. I was confused because I didn't understand that `floating_layout` was a special qtile config variable. Got it now.

Maybe we should add a comment in the default config to make this clearer.

Leave it with me.
