### ISSUE TITLE
[ xwayland ] Cursor display and input sketchy running Ardour

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3250]
If I run Ardour from the arch repo using Qtile with wayland obvs the new session window opens with the cursor as a cross but it will not let me select any options. I can tab through to select them on the keyboard. When i get to the main window the cursor is still a cross and menus are operational but if I then exit I get dumped out of Qtile to the tty login.
I'm using qtile-git and the latest wayland python-pywlroots , python-pywalyand from the normal repos.

**Comment by m-col** [comment]
> cursor as a cross

If you run `xsetroot -cursor_name left_ptr` at startup then it will default to a left pointer.

> if I then exit I get dumped out of Qtile to the tty login

This is fixed by https://github.com/qtile/qtile/pull/3252

> it will not let me select any options

Not quite figured this one out yet...

**Comment by m-col** [comment]
> it will not let me select any options

I suspect this is the same issue as https://github.com/qtile/qtile/issues/3280. Does that sound right?

**Comment by justinesmithies** [comment]
Yes that does indeed sound similar.

**Comment by cr1ogen** [comment]
> > it will not let me select any options
> 
> I suspect this is the same issue as #3280. Does that sound right?

Yes it's similar

**Comment by m-col** [comment]
Is this fixed by #3508?

**Comment by m-col** [comment]
This should fix more of the pointer issues: https://github.com/qtile/qtile/pull/3535

**Comment by justinesmithies** [comment]
Other issues mentioned above seem resolved. When Ardour is open i can select options in any pop up window now problem at all. The only one that refuses to work until it is moved is when you first start Ardour. The splash is displayed and then the initial window pop up opens which you cannot select anything in until you drag it away from the splash window as pictured below.
![2022-05-28_16-05-1653752893](https://user-images.githubusercontent.com/1571498/170832882-bd76f63a-7b64-4ed6-975b-3662d4cb8dc2.jpg)
![2022-05-28_16-05-1653752926](https://user-images.githubusercontent.com/1571498/170832883-611c9823-1df4-455b-a701-c2673dc71a3e.jpg)

**Comment by m-col** [comment]
OK I think I've fixed the weird input issue. Please could you test out https://github.com/qtile/qtile/pull/3608?

**Comment by justinesmithies** [comment]
Just tested #3608 and I still have to move the top window off of the splash before i can click on the buttons. I did however notice that if i held down the mod key to allow it to be moved and only move it a mm or so the input buttons allow highlighting as long as the mod button is still held.

**Comment by m-col** [comment]
I've updated it with a little change. Please could you test again?

**Comment by justinesmithies** [comment]
I've tested this and now confirm this issue to be resolved and so can be merged and also closed. Thank you ;)
