### ISSUE TITLE
[ xwayland ] Spotify client doesn't run 

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3251]
If i try and run the Spotify client from the Arch aur it hangs at the terminal. But once in about 10 attempts it runs up but apears to be running under native Wayland even though it wouldn't do that before xwayland was added to Qtile. The reason I think this is if I type xlsclients in the terminal I get no output but I do for other X apps that are running like Ardour.
Also it too dumps me out of Qtile on trying to exit.

**Comment by elParaguayo** [comment]
Similar bug report on reddit:
```
I was trying several applications that use Xwayland such as Steam, Spotify, Ultimaker Cura and when I close them the system crashes and takes me out of Qtile. I don't know whether to put it as an issue on Github because it doesn't give me any errors in qtile.log. In the Cage app they work without problems
```

**Comment by m-col** [comment]
https://github.com/qtile/qtile/pull/3252 should fix this
