### ISSUE TITLE
Run from a Python Virtual Environment?

### ISSUE THREAD

**Issue by 0n0w1c** [qtile/qtile#3258]
Is it proper to run qtile from a python virtual environment? Or should it run with the main system python and site-packages?
I use a rolling distro and concerned about python upgrades and so forth.

**Comment by elParaguayo** [comment]
I'll just tell you how I do it: I am also on rolling release (Arch) and use python packages from the main repos and AUR. Not had any issues with upgrades (I am aware of a small bug in `psutil` which gives a dodgy reading in the `CPU` widget).

I have used a virtual environment for testing/development purposes.

What concerns do you have?

**Comment by 0n0w1c** [comment]
I searched a bit and did not find any information about running qtile in a virtual environment. Every hit I found used pip installs. And with the wlroots version moving to v15 and I assume to v16, the thought of how to hold the wlroots version came to mind. It seems a virtual environment would be the most stable for a rolling release, but I did not find any reference for doing it. The thought then crossed my mind, that a virtual environment might nor work properly, so check what possible or even advised.

**Comment by elParaguayo** [comment]
Where packages are released that would break qtile (such as wlroots v0.15) we'll typically look to push a new release that's compatible with that package - that's why we just pushed v0.20.0 recently.

**Comment by 0n0w1c** [comment]
I use Manjaro, so I have the various python-* packages available too. Would a virtual environment be advisable or should I go with the python-* packages and just run qtile the system python? Maybe I worry too much about unimportant matters.

**Comment by elParaguayo** [comment]
The `python-*` packages have been working fine for me.

**Comment by 0n0w1c** [comment]
Thank you very much, greatly appreciated.
