### ISSUE TITLE
XWayland: Qtile crashes when closing an X window

### ISSUE THREAD

**Issue by arjan-s** [qtile/qtile#3259]
Versions installed from Arch official repos:
```
qtile 0.20.0-1
wlroots 0.15.0-4
python-pywlroots 0.15.3-1
```

When I open X applications, they work perfectly (much better than with cage!). Examples are `Visual Studio Code` and `Element`. But when I close an X application, Qtile crashes hard. Nothing is written to the log, it just exits to the login manager.

**Comment by cr1ogen** [comment]
Same here

**Comment by m-col** [comment]
The third commit of https://github.com/qtile/qtile/pull/3252 should fix this. Would anybody be happy to test this out? Some clients are behaving differently so it would be great to check it's a catch-all fix.

**Comment by cr1ogen** [comment]
> The third commit of #3252 should fix this. Would anybody be happy to test this out? Some clients are behaving differently so it would be great to check it's a catch-all fix.

How can I test it?

**Comment by m-col** [comment]
If you're running the git version, you can pull the branch from the PR and try running it. Otherwise no worries

**Comment by cr1ogen** [comment]
Yes I'm running the Git version but I don't know how to pull the branch

**Comment by cr1ogen** [comment]
Well I did the pull request using github CLI with the command `gh pr checkout 3252`, so I installed qtile and the system no longer crashes when I close the program, but now the mouse doesn't work, I have to use the keyboard. Tested on Steam, Ultimaker Cura, and Spotify

**Comment by cr1ogen** [comment]
Something strange that also happens is that if I open an X application on desktop 2, the mouse takes the firefox event that I have open on desktop 
![20220127_00h09m33s_grim](https://user-images.githubusercontent.com/9537788/151285304-7664842c-63b2-4451-a980-e90a7ae7aa66.png)
![20220127_00h11m46s_grim](https://user-images.githubusercontent.com/9537788/151285427-7e19d6b3-2d21-4370-a649-ea3be8d727d5.png)

**Comment by cr1ogen** [comment]
Game using xwayland on desktop 2

![20220127_01h43m11s_grim](https://user-images.githubusercontent.com/9537788/151293500-4bb91d89-9f5d-46d2-90a7-f457cb0b0a9b.png)

Firefox on desktop 1

![20220127_01h43m25s_grim](https://user-images.githubusercontent.com/9537788/151293531-c09cbe61-2574-44b4-94fe-9927db36088f.png)

**Comment by cr1ogen** [comment]
Something weird happened. It turns out that firefox started to work through xwayland and searching the internet I looked for a solution so that firefox works through wayland. And doing this, the programs that use xwayland began to work the mouse. What I regret is not doing these tests without firefox running

**Comment by arjan-s** [comment]
@m-col I can confirm that running branch https://github.com/qtile/qtile/pull/3252 solves the crashing issue for me! Thank you!

**Comment by m-col** [comment]
#3252 has been merged so I think this specific issue is fixed, and i will close this. If I've made a mistake there feel free to open. I think most of the other issues mentioned here have been given their own issues, but if I've missed one then please open a new issue. Thanks everyone for the help!

**Comment by cr1ogen** [comment]
> 

The error that I mentioned is the same as in this issue, so it would not be necessary to duplicate it. Sorry that sometimes I don't post an issue because it is difficult to explain it technically since I use the translator because I speak Spanish, and I worry that it won't make me understand. Thanks a lot

**Comment by arjan-s** [comment]
Actually, I've been experiencing crashes when closing VirtualBox these past few days, even with the patch that fixed #3361. So if I manage to get a trace of that, I'll ask to reopen this issue.
