### ISSUE TITLE
Widget and Layout classes not recognized by pyright LSP

### ISSUE THREAD

**Issue by gustavobrangel** [qtile/qtile#3264]
I was going to submit it to pyright, but I read that it may actually be related to qtile, something to do with type stubs.
It is just a warning, qtile still works fine.

![a](https://user-images.githubusercontent.com/20937937/151437278-cf412050-da72-4c79-bf08-e9a5dd54db71.jpg)

**Comment by jamestrew** [comment]
The imports are actually lazy loaded leveraging PEP 562 so pyright has issues picking up on them. I think this is more of a pyright issue than qtile.
My solution was to circumvent the lazy loading imports and just import them directly like this:
```python
from libqtile import bar, qtile
from libqtile.widget.base import InLoopPollText, _TextBox
from libqtile.widget.cpu import CPU
from libqtile.widget.memory import Memory
from libqtile.widget.open_weather import (OpenWeather,
                                          OpenWeatherResponseError,
                                          _OpenWeatherResponseParser)
from libqtile.widget.pulse_volume import PulseVolume
from libqtile.widget.sep import Sep
```
A little tedious but it works if you find the diagnostics to be annoying and/or want to be able to jump to definition.

**Comment by vinicius507** [comment]
With `mypy` and `pyls` the lsp does not give errors(just tried it), but it also does not provides type annotations.

I would like to know if it is a future goal of the project to provide static typings with mypy and/or pyright for configuration purposes(optional, of course).

**Comment by elParaguayo** [comment]
@vinicius507 I'm going to close this issue as the original question was answered. However, you are very welcome to start a discussion about typing. 

FWIW I'm not entirely clear what you'd like us to do. We do use typing but it sounds like some linters aren't smart enought to pick it up.

**Comment by vinicius507** [comment]
> FWIW I'm not entirely clear what you'd like us to do. We do use typing but it sounds like some linters aren't smart enought to pick it up.

Ii's exactly what I thought. Although I don't know if it's a case where we should write stubs differently or improve those linters.

**Comment by elParaguayo** [comment]
I don't think we'll be writing stubs for files that are already typed.

**Comment by vinicius507** [comment]
> I don't think we'll be writing stubs for files that are already typed. 

Great. Thanks for all the help!
