### ISSUE TITLE
lutris/wine broke qtile

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#3266]
![2022-01-28-122551_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151525708-e0fd5016-3309-4bf3-bac3-97bc8ddce310.png)
![2022-01-28-123306_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151525719-781ee5ea-f38c-4617-8f31-0c37d57e194f.png)
![2022-01-28-123329_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151525722-a6d5f089-e818-484e-90ed-e0d76a7ce39a.png)

this is lutris wine ı open game not problem but 1 minute later screen going to crazy

**Comment by m-col** [comment]
Do you have `picom` or another compositor running? If you do not, does running one fix it?

**Comment by ArchKubi** [comment]
only picom

**Comment by m-col** [comment]
Does disabling picom fix it?

It looks to me more like a driver issue, not a Qtile issue. If you run these programs under another window manager, does the issue persist?

**Comment by ArchKubi** [comment]
ı use openbox for testing 
there is no problem same picom and lutris
