### ISSUE TITLE
Can't instance some widgets 

### ISSUE THREAD

**Issue by Unknown-User2** [qtile/qtile#3267]
I'm trying to instance the widgets `widgets.CPU()` `widgets.PulseVolume()` and `widgets.Clock()` that are assigned to variables but they crash qtile

**Comment by elParaguayo** [comment]
It's `widget`, not `widgets`.

If you still get errors, can you post messages from your logs and your config file.

**Comment by Unknown-User2** [comment]
i figured it out it was that i had ',' after the assignment of some variables
