### ISSUE TITLE
MonadTall cmd_reset should respect the configured ratio

### ISSUE THREAD

**Issue by piotr-machura** [qtile/qtile#3270]
If I set the MonadTall master/other ratio in my config to something other than 0.5, say 0.6:
```python
layouts = [
    layout.MonadTall(ratio=0.6),
]
```
all is good, the master window takes up 0.6 of my screen. But if I mess around with widening/thinning the master and decide to reset it with `cmd_reset` (or a keybinding to `lazy.layout.reset`) it goes back to being 0.5 of my screen, not 0.6 like I have configured.

I believe this is happening because of this line in `layout.MonadTall.cmd_reset`:
```python
def cmd_reset(self, redraw=True):
    "Reset Layout."
    self.ratio = self._med_ratio # <- this is hard-coded to 0.5
    # ...
```
This can be easily fixed by setting the `self._med_ratio` to what the user has provided (in `__init__`). This is how I have fixed it in my personal configuration with some inheritance:
```python
class FixedMonadTall(layout.MonadTall):
    def __init__(self, **config):
        super().__init__(**config)
        self._med_ratio = self.ratio
```
The only other place I see `_med_ratio` used is `layout.MonadTall._maximize_main` and I believe the same behavior would be expected there - if the master is wider than I have configured the default to be (not "wider than 0.5") minimize it, and maximize otherwise.

The same issue happens with MonadWide, but the above change will fix that too because of inheritance.

Thank you for making this amazing WM, it's a joy to use.

**Comment by m-col** [comment]
That makes sense, and the change would be reasonable! Would you be 
happy to submit a PR with those changes? I do wonder when changing 
things like these if some people are using `cmd_reset` specifically to 
make the ratio 50/50. We would then be breaking their setups. Perhaps 
we should also add a `ratio=None` option to `cmd_reset`, which would 
then default to `self.ratio` as per your suggestion, but would then 
allow for that to overriden (i.e. to 0.5 for those who like the current 
functionality). What do you think?

**Comment by piotr-machura** [comment]
Sure thing, I'll submit a PR including your suggestion shortly.

**Comment by elParaguayo** [comment]
>  I do wonder when changing things like these if some people are using `cmd_reset` specifically to make the ratio 50/50. We would then be breaking their setups. 

The docs say:
```To reset all client windows to their default sizes, including the primary window, use the ``cmd_reset`` method.```

I would say the default size is the one that's there on start-up, i.e. configured by the user.

Your suggestion of passing a ratio is ok, but why not just have a command called `set_ratio` where you can pass any number and leave `cmd_reset` with no parameters?

Just my thoughts...

**Comment by m-col** [comment]
Yep, sounds good!

**Comment by piotr-machura** [comment]
> Your suggestion of passing a ratio is ok, but why not just have a command called `set_ratio` where you can pass any number and leave `cmd_reset` with no parameters?

I have added the keyword arg in my PR as a way to quickly get the old behavior back in case someone out there relies on it for their workflow, but a separate `set_ratio` could be nice to have as well.
