### ISSUE TITLE
[ Xwayland ] Spotify doesn't respect Qtiles layouts ?

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3273]
Using the latest git version of Qtile if I run Spotify from the aur it opens in a small floating window as pictured. If I press mod+f to fullscreen it then do the same again it starts to respect the monadtall layout and fills a window correctly.
![2022-01-29_21-01-1643492899](https://user-images.githubusercontent.com/1571498/151678680-8139e5ee-ec52-48e8-b67a-5bd19db899e6.jpg)
![2022-01-29_21-01-1643492916](https://user-images.githubusercontent.com/1571498/151678682-901db8e0-a093-4b95-8bde-5c442b9f8154.jpg)

**Comment by justinesmithies** [comment]
I'm not actually sure if it's an Xwayland issue or just a Wayland issue as I know Spotify runs native in Wayland but for some reason still requires Xwayland support to run ?

**Comment by cr1ogen** [comment]
I've tried other applications that use xwayland and they don't respect qtile layouts either, for example emacs 
![20220129_19h54m13s_grim](https://user-images.githubusercontent.com/9537788/151680201-e1ff2773-726b-4fd7-98af-cd5d31f436cf.png)

**Comment by m-col** [comment]
Hmm, very weird. Any chance they could be triggering float rules or something? Previously `wm_type` wasn't used by matches when the wayland backend was running but now that is available on xwayland windows. Otherwise my other idea is that the logic that determines whether or not they want to become static windows is wrong. Do these windows behave like regular floating windows (draggable, tilable), or are they completely static?

**Comment by justinesmithies** [comment]
I'll look into wether they are triggering float rules in the morning. But I can confirm they are floating , draggable and you can time them too. I can time Spotify by doing the following mod+f which obvs full screens the app then mod+f again and it's tilled correctly.

**Comment by cr1ogen** [comment]
In my case it doesn't have any float rules. And the window can be dragged and enlarged with the mouse perfectly

**Comment by m-col** [comment]
OK thanks guys, I can reproduce and think I've understood what's going 
on. Will post a fix soon.

**Comment by cr1ogen** [comment]
It's happening again that spotify doesn't respect qtile layouts. Could someone confirm please? Thanks
