### ISSUE TITLE
how ı install old qtile

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#3303]
ı use arch linux this new version problem how ı install old qtile

**Comment by m-col** [comment]
How did you install? If you installed from pip then you can do `pip install qtile==0.19.1` for example.

As the new version has problems for you, are you referring to https://github.com/qtile/qtile/issues/3296 and https://github.com/qtile/qtile/issues/3265? We would love to fix these for you but they are quite vague and difficult (not your fault). If you would be willing to help us to fix them, then that would be amazing. Knowing that the older version works, it should be possible to bisect the changes between the old and new version to identify what change caused the problem. What do you think?

**Comment by ArchKubi** [comment]
I would like to help but I don't have time 
there no error log why qtile freezes
ı install qtile-plasma for arch linux aur qtile not freezes now
sorry my english not good

**Comment by elParaguayo** [comment]
Interesting. qtile-plasma is just a layout, that shouldn't have any impact on qtile freezing or not.

**Comment by ArchKubi** [comment]
yay -Ss qtile-plasma
aur/qtile-plasma-git v1.5.5.r1.g4b57f31-2 (+0 0.00) 
    A flexible, tree-based layout for Qtile
aur/qtile-plasma 1.5.0-1 (+0 0.00) (Orphaned) (Out-of-date: 2020-03-02) (Installed)
    A flexible, tree-based layout for Qtile

not problem for now but 
2022-02-05 12:09:18,709 ERROR libqtile bar.py:_configure_widget():L324 Systray widget crashed during _configure with error: ConfigError('Only one Systray can be used.')

**Comment by elParaguayo** [comment]
Yes, but qtile-plasma does not modify any qtile files. It's a separate layout.

**Comment by ArchKubi** [comment]
ı don't know ıdelete qtile instal qtile-plasma it's strange

**Comment by elParaguayo** [comment]
Closing this as I don't think there's more to add here and the original question has been answered.
