### ISSUE TITLE
Cannot start Qtile after install, "no DISPLAY set"

### ISSUE THREAD

**Issue by ghost** [qtile/qtile#3311]
Hi,
I've installed on Debian Bullseye as set out on the website. But Qtile is not present in SDDM. If i try to log in from tty i get the error:
libqtile.utils.QtileError: No DISPLAY set
I tried in a VM with Bullseye without display manager or DE, but same thing.
What a I missing?
Thanks in advance

**Comment by m-col** [comment]
For Qtile to appear in your display manager it needs a .desktop file, which debian I guess must not be packaging. You can copy it from here: https://github.com/qtile/qtile/blob/master/resources/qtile.desktop. If you put that file in `~/.local/share/applications` I think it should then appear in SDDM. I'm not 100% certain though. To run it without a display manager you need to stick qtile at the end of your `~/.xinitrc` script and start X from your TTY with `startx`.

**Comment by ura43** [comment]
I'm 99% certain the main issue here was that they forgot startx. 
Debian doesn't package qtile at all, so it makes sense that you'd have to manually add a .desktop file

**Comment by m-col** [comment]
Yeah... that they are a ghost now - I'll close this.
