### ISSUE TITLE
pacman -Syu and qtile no longer working

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#3316]
Qtile logs:
![screen](https://user-images.githubusercontent.com/3178666/153025895-04cabf0b-930d-478d-9267-eda7798e5719.jpeg)

Can't even print the version:
![screen](https://user-images.githubusercontent.com/3178666/153026583-74e77896-1df7-4bc4-a2b9-2c7ff2f37d7a.jpeg)

**Comment by tamis-laan** [comment]
Hm... it's the `qtile-dev` package which pulls the latest version of qtile that produces this error. I have reverted to the standard package `qtile` in arch.

**Comment by m-col** [comment]
Do you mean `qtile-git` from the AUR? I couldn't find a `qtile-dev` package. In that second image the contents of `/usr/bin/qtile` is loading qtile version `0.17.1` which is 3 major versions ago.

**Comment by elParaguayo** [comment]
Also seems to be using python 3.9 but Arch is on 3.10...

When did you last update?

**Comment by tamis-laan** [comment]
> Do you mean `qtile-git` from the AUR? I couldn't find a `qtile-dev` package. In that second image the contents of `/usr/bin/qtile` is loading qtile version `0.17.1` which is 3 major versions ago.

Yes qtile-git sorry 

Before it was a few versions ahead :P

**Comment by elParaguayo** [comment]
`qtile-git` is up to date. It will always install the latest version from github but if your other packages aren't up to date then qtile may not work.

**Comment by elParaguayo** [comment]
I'm assuming this is closed now but please reopen if you're still having issues.
