### ISSUE TITLE
Cannot bind Click([], "Button9") in Wayland

### ISSUE THREAD

**Issue by 5ila5** [qtile/qtile#3317]
I'm running Arch  5.16.5-zen1-1-zen
qtile pacman package version 0.20.0-1,
wlroots 0.15.1-2,
python-pywlroots 0.15.7-2

when adding `Click([], "Button9", qtile.cmd_simulate_keypress(["control","shift"], "Tab")),` to my mouse list, Qtile crashes immediately after starting when using Wayland

Using X  no error. 
Using Wayland:

> 2022-02-08 17:57:46,369 ERROR libqtile start.py:start():L94 Qtile crashed
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
>     q.loop()
>   File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 190, in loop
>     asyncio.run(self.async_loop())
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 215, in async_loop
>     self.load_config(initial=True)
>   File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 139, in load_config
>     self.grab_button(button)
>   File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 460, in grab_button
>     button.modmask = self.core.grab_button(button)
>   File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 781, in grab_button
>     keysym = wlrq.buttons[mouse.button_code]
> IndexError: list index out of range

I think libqtile/backend/wayland/core.py l. 828
should be `keysym = wlrq.buttons[mouse.button_code -1]`
instead of now being `keysym = wlrq.buttons[mouse.button_code]`

but I did not dig that deep into the Qtile source code so I'm not quite sure

**Comment by m-col** [comment]
Your config line isn't quite right. When accessing the method directly (i.e calling `cmd_X()`), you're calling the method when the config is read and its result is being passed as to `Click`. I think you want this:
```py
Click([], "Button9", lazy.simulate_keypress(["control","shift"], "Tab")),
```

That said, I dont think that's the source of the problem here. I'll take a look - thanks for the bug report.

**Comment by m-col** [comment]
Neat bug. The odd part is that your suggested change (which is absolutely correct) doesn't change the apparent behaviour (except for when you use `Button9`). Indeed `Core.grabbed_buttons` is not used anywhere at all! It seems currently all buttons are grabbed and processed as if they were all grabbed. I need to do a bit a rewrite of the button grabbing in that core.

**Comment by 5ila5** [comment]
Seems to be resolved after the last update. 
can this be closed now?

**Comment by elParaguayo** [comment]
If it's working, yes!
