### ISSUE TITLE
Moving a fullscreened window to a different group makes it disappear from all groups

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#3323]
When I use `lazy.window.togroup(group_name)` to send a window to another group and the window is fullscreened, it does not appear on the target group.

Some logs:
```
2022-02-10 22:33:15,589 ERROR libqtile manager.py:process_key_event():L391 KB command error togroup: Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/command/interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/home/mcol/git/qtile/libqtile/backend/base.py", line 422, in cmd_togroup
    self.togroup(group_name, switch_group=switch_group)
  File "/home/mcol/git/qtile/libqtile/backend/wayland/window.py", line 370, in togroup
    self.group.remove(self)
  File "/home/mcol/git/qtile/libqtile/group.py", line 295, in remove
    self.tiled_windows.remove(win)
KeyError: Window(name='imv - [1/1] [1920x1080] [100%] /home/mcol/20220210_22h32m45s_grim.png [shrink to fit] ', wid=13)
```

This suggests that, as the window is removed from the current group but then the action errors out, the fullscreened window just remains in an unmapped state.

I think this is a relatively new bug. Pinging @jwijenbergh - I suspect it's to do with your recent fullscreen changes.

**Comment by jwijenbergh** [comment]
I cannot reproduce this (x11 through xephyr). I also tested this when I made the pr. Does this happen for all of your windows?

**Comment by jwijenbergh** [comment]
I tested it like this:

- Start xephyr
- Fullscreen terminal
- Move terminal to workspace 2

**Comment by m-col** [comment]
Ooh, it only happens with windows that were never tiled, i.e. have matches in `float_rules`. Perhaps it's enough to check they are in that `self.tiled_windows` list before removing them.

**Comment by jwijenbergh** [comment]
Ooh gotcha lemme test

**Comment by jwijenbergh** [comment]
> Ooh, it only happens with windows that were never tiled, i.e. have matches in `float_rules`. Perhaps it's enough to check they are in that `self.tiled_windows` list before removing them.

Can confirm. We need to indeed add `if win in self.tiled_windows` when removing it. I think I removed this check when simplifying the pr because I thought it wasn't need any more

**Comment by jwijenbergh** [comment]
Maybe this is also related to the bug by @mithicspirit
