### ISSUE TITLE
Auto-switching group when a new window is launched.

### ISSUE THREAD

**Issue by yuandi42** [qtile/qtile#3325]
Hi!
I've set some programs to launch in specific groups and now I want to work further. i.e., if a new window is created in an inactive group, qtile will automatically switch to that group. 
I've looked through issue https://github.com/qtile/qtile/issues/1958, in which same demand was required. However, his solution doesn't actually help my problem for two reasons:
1. I use [sxhkd](https://github.com/baskerville/sxhkd) for non-WM-related hotkeys like launch my web browser;
2. Sometimes we don't use hotkey to launch a program. For example, my active group is group "Home" with my file manager in it, then I open a `.pdf` , and my pdf viewer launch in group "Note" just as I've set. In this case, no hotkey is used and for certain manually switching to group "Note" is stupid. 

So instead of using hotkey, I tried to use `hook.subscribe.client_new`. But it seems not to work and I'm quite confused now.
Below is my config about the auto-switching func:
```python
@hook.subscribe.client_new
def auto_switch(window):
    if window.group.name != qtile.current_group.name:
        window.group.name.cmd_toscreen()
```
And here is my complete `config.py`: https://pastebin.com/aU7in33p .

**Comment by elParaguayo** [comment]
Two things:

First, you probably want the `client_managed` hook as this is fired *after* the window has been assigned to a group.

Secondly, `cmd_toscreen` is a method of `window.group` and not `window.group.name`.

**Comment by yuandi42** [comment]
> 

I've corrected and it works. Thanks a lot! :-)

**Comment by mwip** [comment]
Thanks for documenting this here, this helped me so much. As I have a multiscreen Qtile config, I had to make one adjustment, though. I thought this might be helpful to someone else, so I want to share my approach:

```python
@hook.subscribe.client_managed
def auto_show_screen(window):
    # check whether group is visible on any screen right now
    # qtile.groups_map['<somegroup>'].screen is None in case it is currently not shown on any screen
    visible_groups = [group_name for group_name, group in qtile.groups_map.items() if group.screen]

    if window.group.name not in visible_groups:
        window.group.cmd_toscreen()
```
