### ISSUE TITLE
simulate_keypress() not working

### ISSUE THREAD

**Issue by 5ila5** [qtile/qtile#3326]
I might did something horribly wrong but when I add the following line to my keys list it does not work like expected.
In Wayland when pressing mod + x simply nothing happens. In X the input filed I'm in uses focus for a fraction of a second, that's all.

```python
Key([mod], "x", lazy.simulate_keypress([],"a"), desc=""),
```

The Qtile shell output (Wayland and X):
```bash
qtile shell
 > help simulate_keypress
simulate_keypress(modifiers, key) -> 'None'
Simulates a keypress on the focused window.

Parameters
==========
modifiers :
    A list of modifier specification strings. Modifiers can be one of
    "shift", "lock", "control" and "mod1" - "mod5".
key :
    Key specification.

Examples
========
    simulate_keypress(["control", "mod2"], "k")
 > simulate_keypress(["control", "mod2"], "k")
Invalid command: simulate_keypress(["control", "mod2"], "k"
```
 

I'm running Arch 5.16.8-zen1-1-zen
qtile pacman package version 0.20.0-1,

**Comment by m-col** [comment]
The docstring there is actually incorrect and misleading. The keys simulated with it are only used for internal processing, such as executing keybindings. The event is _not_ passed to the focussed window. Sorry for that. To simulate a keypress in the current window, you can use external tools such as `xdotool` for X or `wlrctl` for Wayland.

**Comment by 5ila5** [comment]
Thank you for your help
