### ISSUE TITLE
No qtile session option in gdm after pip install qtile

### ISSUE THREAD

**Issue by praneetk96** [qtile/qtile#3329]
I'm on fedora 35, after installing with pip, it gives me warning qtile is installed in ~/.local/bin

**Comment by dr-carlos** [comment]
This is because using pip installs qtile locally. You will need to run `pip install` as root so that the qtile session is available to gdm.

**Comment by praneetk96** [comment]
> This is because using pip installs qtile locally. You will need to run `pip install` as root so that the qtile session is available to gdm.

Okay so uninstalled it and installed again with "sudo pip install qtile" and rebooted, now again I'm not seeing qtile in the session chooser of gdm

**Comment by elParaguayo** [comment]
Installing via pip won't create the xsessions file you need. Have a look here: http://docs.qtile.org/en/stable/manual/config/index.html#starting-qtile

**Comment by praneetk96** [comment]
Thank you so much, it's working now!
