### ISSUE TITLE
lazy.reload_config() method leaks CPU

### ISSUE THREAD

**Issue by morne** [qtile/qtile#3330]
Every call to `lazy.reload_config()` increases the average CPU usage by Qtile. It is quite a small increase, but it builds up rather quickly if you reload the config often, when testing new settings for example.

By doing a few calls to `lazy.reload_config()` in succession, you can easily push up average CPU usage from around 1% to 8-10%...the CPU usage stays at that level, even if left for 20 minutes or more....quitting Qtile, and starting it with the same config, results in expected CPU usage of around 1%, even if left for 24 hours or more.

This is on Qtile version 0.20.0 running on ArchLinux (kernel 5.16.8) with xorg-server 21.1.3 and Python 3.10.2

**Comment by elParaguayo** [comment]
@morne can you share your config? If there is a leak my money would be on a widget.

**Comment by morne** [comment]
> @morne can you share your config? If there is a leak my money would be on a widget.

Sure - I think you are right, it's probably one of the widgets if @Prutserdt can't reproduce it. I'll try and disable all the widgets, and then re-enable them one-by-one, and try and reproduce the behavior each time, to see if I can track down the errant widget.

I've also attached my config as requested (It's just a few modifications from the default config, added 
widgets mostly). 

[config.py.zip](https://github.com/qtile/qtile/files/8055851/config.py.zip)

**Comment by morne** [comment]
Ok - so I've done the test, and I can confirm that both the `widget.ThermalSensor` and `widget.CPUGraph` cause the CPU usage to go up, permanently, when invoking `lazy.reload_config()` multiple times.

I think the effect is exacerbated on my setup, because I have four instances of ThermalSensor and four instances of CPUGraph active. When I then reload my config multiple times with `lazy.reload_config()` (around 20-30 times to test), then the CPU usage goes up, and stays there, never returning to baseline.

**Comment by elParaguayo** [comment]
Thanks. Will investigate.

**Comment by elParaguayo** [comment]
OK. I've actually got a pretty good idea of what's causing this. The clue was in you saying you've got multiple instances.

Basically, when we reload the config we finalize currently running widgets. We do this by iterating over a dictionary of widgets where the key is the widget name. The name defaults to the widget class name. This means that, if you use multiple instances of a widget class, there's only going to be one instance of that widget in the map. The rest will therefore not be finalized and their timers will carry on running.

#3010 should therefore solve this issue. I'll take another look at that PR and see if we can get it in a good form for you to test.

If not, I can knock out a quicker fix for this particular issue.

**Comment by morne** [comment]
Great !

> If not, I can knock out a quicker fix for this particular issue.

No need, it's not that urgent, I'll wait for #3010

**Comment by elParaguayo** [comment]
@morne #3010 has been merged so great if you could test this.

**Comment by morne** [comment]
@elParaguayo - I just did a test and I can confirm that it fixes the problem.

Great work and many thanks !
