### ISSUE TITLE
Getting error when trying to use MonadThreeCol

### ISSUE THREAD

**Issue by cjwyett** [qtile/qtile#3336]
Hi. 

When i add `layout.MonadThreeCol()` to my layouts list i get

`2022-02-13 12:15:36,328 ERROR libqtile manager.py:cmd_reload_config():L258 Configuration error: module 'libqtile.layout' has no attribute 'MonadThreeCol'` in my log, (and spawn into default config).

**Comment by elParaguayo** [comment]
If you're not using the latest git version then you'll need to wait until the next release.

**Comment by elParaguayo** [comment]
Assume this is resolved so closing for now.
