### ISSUE TITLE
After updates systray crashes on start

### ISSUE THREAD

**Issue by Sonic803** [qtile/qtile#3341]
After instaling version 0.20.0-1 on startup the systray crashes.

`2022-02-14 19:21:45,452 ERROR libqtile bar.py:_configure_widget():L324 Systray widget crashed during _configure with error: ConfigError('Only one
Systray can be used.')
`
qtile.log

I have to restart qtile to make it work.

(this  problem doesn' thappen with version 0.19

**Comment by elParaguayo** [comment]
Thanks for posting. Please do search through issues (including closed ones) before submitting a new one.

This has been reported a few times and is fixed in the latest git version.

I'll close this for now.

**Comment by jrwrigh** [comment]
For those who find this, it's discussed in #3260 and fixed in #3261.

**Comment by elParaguayo** [comment]
There was actually another related issue which is fixed in #3345.
