### ISSUE TITLE
Use current python version for qtile check

### ISSUE THREAD

**Issue by MithicSpirit** [qtile/qtile#3342]
When running `qtile check`, the version of python used is hardcoded to 3.10 (on current master), as can be seen here:
https://github.com/qtile/qtile/blob/c1f5073935a61f2bb9a36e198791590410ec07a1/libqtile/scripts/check.py#L101

Since qtile will be run with the system python, which does not necessarily correspond to 3.10, it would make more sense to use that to decide the version. This can either be done by removing the `--python-version` argument to `mypy` (since by default it "assumes your code will be run using the same […] Python version as you are using to run mypy itself"), or by utilizing `sys.version_info` to generate the version string that is passed to `mypy`.

If you would like, I can create a pull request for this.

**Comment by m-col** [comment]
Yeah that sounds like a good idea.

> If you would like, I can create a pull request for this.

That would great, thank you.

I wonder what caveats there might be to this. I assume `--python-version` flag was added for a reason. It might be worth checking the commit messages for that file to see if there is any information about this.

As `qtile check` is something that should work on all python versions supported by qtile (currently 3.7-3.10) we should probably its tests in the CI for all versions too.

**Comment by MithicSpirit** [comment]
Seems like the version check was originally added in d540445e2fe29bfec2f0e05d5caae39ff8bad598 because "we want to use Literal, which is in 3.8. If people have a mypy that is too old, they can upgrade; this is an optional check anyways." Because of this, I believe that the best option is to remove `--python-version` but use `sys.version_info` to detect whether they are at least at 3.8, skipping the `mypy` check otherwise.
