### ISSUE TITLE
Drag events sent to wrong window based on keyboard focus

### ISSUE THREAD

**Issue by alethiophile** [qtile/qtile#3346]
When I have a floating window above tiled windows but have keyboard focus on the tiled window, a mod-drag event over the floating window (meant to move it) instead goes to the tiled window behind. This forces the tiled window into floating mode and makes it cover up the original floating window, causing general irritation. Mod-drag over a floating window only works as desired when the floating window has keyboard focus.

A mouse event over a given window should never go to any other window, regardless of keyboard focus.

**Comment by elParaguayo** [comment]
Thanks for posting.

I've noticed this too but haven't had a chance to look into it yet.

**Comment by SweepingBishops** [comment]
Not stale!
