### ISSUE TITLE
Building from source does not install Qtile

### ISSUE THREAD

**Issue by erlonbie** [qtile/qtile#3350]
Hi, I'm sorry if this issue looks repetitive, but I took a look at a bunch of issues and posts related before posting this issue.

I installed all dependencies (I assume) and followed the [documentation guide](https://docs.qtile.org/en/v0.20.0/manual/install/index.html) to install it localy, so this is what prompted after running the `pip install .` command:

![image](https://user-images.githubusercontent.com/50176483/154608423-bf24dddb-2d75-4229-b3fa-aa79d88b591a.png)

It looks nothing wrong happened, but when I type the command `whereis qtile`, it does not show the binary location or it shouldn't since it is Python?

![image](https://user-images.githubusercontent.com/50176483/154608783-4dcd2a60-2bfb-43bc-b72b-6c6ee0274514.png)

I can tell that there is no command recognized as qtile through zsh, showing the red color. It should've be green (this probably answers my previous doubt)

![image](https://user-images.githubusercontent.com/50176483/154611006-60e2fd23-efdf-4891-83d7-b128c3d0d75b.png)

I also created this desktop entry, but I'm not able to start Qtile (obviously):

![image](https://user-images.githubusercontent.com/50176483/154609864-c16ae0d6-417e-434a-8aaa-ada4998a2fe4.png)

Just for some context: I had Qtile installed normally through pacman, but I wanted to have it installed locally so I could tweak somethings myself, like changing the order of terminal names list in the ` utils.py` that  `guess_terminal()` tries to find.

**Comment by elParaguayo** [comment]
If `qtile` isn't there, can you run `pip show -f qtile` and paste the output.

**Comment by erlonbie** [comment]
I didn't think that would happen.

This `.asdf` is like a version manager for various language/tools, so when I'm in a project, I can specify the apropried language/tool version, for example Python, to run the correct version inside that folder. Maybe you already know this

I'll try to uninstall it, maybe it will solve my problem

**Comment by elParaguayo** [comment]
Yes, I understand. However, if you want to run Qtile from a login manager, I'm not sure you want that inside a virtual environment.

I would be inclined to uninstall it from the virtual environment, deactivate the environment and then run `pip install .` again. That should install it to `~/.local/bin` (with the python libraries in `~/.local/lib/python3.10/site-packages`).

**Comment by erlonbie** [comment]
I uninstalled `asdf`, now after `pip install .`, qtile is now on `~/.local/bin` as well the libraries in `~/.local/lib/python3.10/site-packages`.

But, I stil can't start qtile from login screen. I tried both situations:

![image](https://user-images.githubusercontent.com/50176483/154696050-f6fd04dd-d104-47be-85b0-056505d10abf.png)
![image](https://user-images.githubusercontent.com/50176483/154696096-56c7f9e5-8d65-4994-b448-2aa2338bec18.png)
1

**Comment by erlonbie** [comment]
When I say "I can't start qtile", I mean: the Qtile option/entry shows at the display manager (lightdm), but after typing my password, I get a black screen than the it returns to the login screen.

**Comment by elParaguayo** [comment]
The Exec line would need to be `/home/erlonbie/.local/bin/qtile start`

**Comment by erlonbie** [comment]
Thank you so much @elParaguayo !

**Comment by elParaguayo** [comment]
Great. I take it that it's working now. If so, feel free to close this and have fun tweaking your installation of qtile.
