### ISSUE TITLE
Make `pywlroots` package optional for X11 users (`qtile-git` AUR)

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3352]
Currently I can't install Qtile from the AUR, because my (up to date) Manjaro stable install does not have the newest pywlroots version that is required. From my understanding, wlroots and pywlroots is only needed for Wayland, right? As a X11 user, I would not need it anyway and it just prevents me from installing (newest) Qtile. 

Is it possible to mark the pywlroots as optional package? Unless off course I misunderstand this somehow. I do the request here, because the `qtile-git` AUR package is maintained by one of the developers here.

**Comment by thingsiplay** [comment]
I can see why you won't want to maintain a separate package, because this just adds to more work. I just thought it would be a simple case of making the package optional, but I see there is not an easy solution. The only problem without the git-package is, that qtile releases (even minor) take a while, plus Manjaro (even if it is a rolling release) take a while to include it too. And because I am affected by a few bugs, so have to live with it. That's why I decided to try out the git-package.

No need to sorry. Unfortunately I don't have any other idea for now, but will come back if anything pops up in my mind.

**Comment by elParaguayo** [comment]
This is one of the risks of being bleeding edge is that you sometimes need to wait for packages to be updated.

However, for what it's worth, my view is that splitting it out into `x11` and `wayland` packages would be neat and will avoid issues like this. The only downside I could see is that you can't have both packages installed at the same time so users wouldn't have the option to try both backends without having to install/uninstall different packages.

**Comment by m-col** [comment]
> The only downside I could see is that you can't have both packages installed at the same time so users wouldn't have the option to try both backends without having to install/uninstall different packages.

The difference really would be the set of dependencies installed automatically (and the build-time dep of pywlroots enabling libinput config support in the wayland backend). Someone with `qtile-x11` installed could install pywlroots manually and the wayland backend should work.

We could have `qtile-git` with no backend-specific deps, and `qtile-x11-git` and `qtile-wayland-git` with backend deps. Alternatively just keep `qtile-git` as X11 and `qtile-wayland-git` for wayland, which would avoid disrupting people who have `qtile-git` installed already.

Ideally we could use a package group or meta-package like [i3 does](https://archlinux.org/groups/x86_64/i3/) but I don't think this is possible with AUR packages.

> Can't the build script handle this? Like making the pywlroots package optional and when building, it will build the wayland support if pywlroots is installed. 

Not always - but I'm not 100% certain. Many people build AUR packages in clean chroot environments and so they would need the pywlroots dependency explicitly included in the `makedepends`. It is possible to just remove that from the PKGBUILD when you install though - so you could do that, if your helper makes that easy.

**Comment by ura43** [comment]
> > The only downside I could see is that you can't have both packages installed at the same time so users wouldn't have the option to try both backends without having to install/uninstall different packages.
> 
> The difference really would be the set of dependencies installed automatically (and the build-time dep of pywlroots enabling libinput config support in the wayland backend). Someone with `qtile-x11` installed could install pywlroots manually and the wayland backend should work.
> 
> We could have `qtile-git` with no backend-specific deps, and `qtile-x11-git` and `qtile-wayland-git` with backend deps. Alternatively just keep `qtile-git` as X11 and `qtile-wayland-git` for wayland, which would avoid disrupting people who have `qtile-git` installed already.
> 
> Ideally we could use a package group or meta-package like [i3 does](https://archlinux.org/groups/x86_64/i3/) but I don't think this is possible with AUR packages.
> 
> > Can't the build script handle this? Like making the pywlroots package optional and when building, it will build the wayland support if pywlroots is installed.
> 
> Not always - but I'm not 100% certain. Many people build AUR packages in clean chroot environments and so they would need the pywlroots dependency explicitly included in the `makedepends`. It is possible to just remove that from the PKGBUILD when you install though - so you could do that, if your helper makes that easy.

Keeping `qtile-git` for X11 and `qtile-wayland-git` for wayland seems like the best solution.
Should also make it easier to get packages accepted into distro repos, as wayland introduces some rarely packaged dependencies

**Comment by elParaguayo** [comment]
Not sure if that's what you meant but I'm pretty sure that git versions won't make it into official repos. `qtile-git` and `qtile-wayland-git` will just be AUR packages.

**Comment by ura43** [comment]
Oh right. I assumed this would trickle down to the non-git versions

**Comment by m-col** [comment]
To be honest it might do, if they agree that it's the best approach. Much like with i3, the official arch repos could migrate everyone with `qtile` to a `qtile-x11` meta package, and add a `qtile-wayland` meta package, with a no-deps `qtile` package. AFAICT that would be a neat way of doing it but I'm not very familiar with the caveats of such an approach, or how it might disrupt users who already have `qtile` installed. It would be nice though.

**Comment by m-col** [comment]
I added a `qtile-wayland-git` AUR package for all the wayland deps without the x11 deps. Once I get confirmation that it's working as expected I'll remove the wayland deps from `qtile-git` and direct Wayland users to the wayland package.

**Comment by elParaguayo** [comment]
Might be worth updating docs for this too.

**Comment by thingsiplay** [comment]
I have nothing substantial to add, but want to say that I was reading along and I'm happy with the solution you doing.

**Comment by thingsiplay** [comment]
How is it going? Is anyone using the wayland-git version reporting anything? When I search the AUR with `pamac search qtile`, no `qtile-wayland-git` is listed.

**Comment by thingsiplay** [comment]
BTW, what is the current state? When I search the AUR with the command `pamac search qtile`, then it won't show up Wayland related packages for Qtile. Is it going well so far?

**Comment by elParaguayo** [comment]
https://aur.archlinux.org/packages/qtile-wayland-git

**Comment by thingsiplay** [comment]
I know, checked it already on the website. So this problem has nothing to do with the package then? I'll ask on the official Manjaro forum why it does not show up in the CLI search then.

**Comment by thingsiplay** [comment]
Turns out there was a bug in pamac, which prevented me from finding qtile-wayland-git. It is fixed now: https://gitlab.manjaro.org/applications/pamac/-/issues/1247#note_26101 This wasn't an issue with qtile, but as this specific package couldn't be found I think it is related and therefore worth mentioning it here.

**Comment by thingsiplay** [comment]
I am sorry to bring this up again, but the `qtile-git` package still requires `python-pywlroots`; so this issue is not solved at the moment. Which I don't need and can't update again, because Manjaro has an older version of it. 2 months has passed an if no problems occurred in that time, maybe it is time to remove the dependency from the AUR package?

**Comment by m-col** [comment]
> maybe it is time to remove the dependency from the AUR package?

ok!

**Comment by m-col** [comment]
Done - please let me know if you still have issues

**Comment by thingsiplay** [comment]
Thank you very much! I just updated with the command `yay -S -a --rebuild qtile-git` and it did. The installed version is `0.21.0.r19.g5c28cbb2-1`, is this correct?

**Comment by m-col** [comment]
Yep
