### ISSUE TITLE
Battery low notifications go away with `dunst`

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3353]
yesterday, thanks to @m-col, I manage to have beautiful popup notifications for my battery from within `qtile`'s bar and even sound and brightness bars as I change them with the keyboard:
![notifications dunst](https://user-images.githubusercontent.com/44101798/154742799-065fd65d-1499-45aa-ac37-a5b05bc23943.png)
However it is still not behaving quite as I expected.

I expected the notifications for a low battery to be of *urgent*/*critical* priority and it is red indeed.
I configured my [dunst](https://github.com/a2n-s/dotfiles/blob/main/.config/dunst/dunstrc#L292) so that *low* and *normal* notifications go away quite quicly, but *critical*/red ones never go away!

This is what I observe when I run either
```
notify-send "ERROR" "this is an error" -u critical
notify-send "NORMAL" "this is a normal message" -u normal
notify-send "LOW" "this is nothing important" -u low
```
or
```
dunstify "ERROR" "this is an error" -u critical
dunstify "NORMAL" "this is a normal message" -u normal
dunstify "LOW" "this is nothing important" -u low
```

But this is **not the case with the *critical* battery low notifications** from `qtile`.

I do not really understand the code of the `libqtile.widget.Battery` class, could anyone help fix that?

**Comment by elParaguayo** [comment]
The widget does send messages marked as "urgent". However, I suspect your issue is that the notification is also sent with a set timeout (10 seconds) which dunst is, presumably, honouring.

**Comment by a2n-s** [comment]
> The widget does send messages marked as "urgent". However, I suspect your issue is that the notification is also sent with a set timeout (10 seconds) which dunst is, presumably, honouring.

oooh

it looks exactly the same as a *critical* issue thrown from `dunstify` or `notify-send` indeed!
A timeout is a good suspect :thinking:

But **is there a way to remove the timeout without modifying the source code?**

**Comment by elParaguayo** [comment]
> But **is there a way to remove the timeout without modifying the source code?**

Sadly, no.

However... you might be able to get dunst to ignore it:
https://github.com/dunst-project/dunst/blob/ba4d9d5b9e9d6b761ddd08076031d643c0904666/dunstrc#L234-L238

**Comment by a2n-s** [comment]
It appears not to be working :thinking:
I did restart `dunst` after killing it and did make sure it was loaded with the new config file, i.e. `dunst -conf ~/.config/dunst/dunstrc`,
when running `dunstify "ERROR" "msg" -u critical`, it never goes away, but with `dunstify "ERROR" "msg" -u critical -t 1000`, it goes away after 1 sec!

So if the only solution is to fiddle with the source, **could a timeout argument for the `libqtile.widget.Battery` class be implemented?** Either by one of you guys or through a pull request?

It is not that big of an issue, but I think it would make *more sense for such important notifications to stick on the screen a bit longer!* :yum:

**Comment by elParaguayo** [comment]
We could certainly add a timeout request to the notification. I can do a PR for that.

**Comment by elParaguayo** [comment]
#3354 - great if you could test it.

**Comment by a2n-s** [comment]
> We could certainly add a timeout request to the notification. I can do a PR for that.

Oh my... did you already fix this issue? You guys are amazing :star_struck:

> #3354 - great if you could test it.

so you mean cloning you fork, checking out your 'issue-3353` branch and compiling this, right? Just to be sure I want to do the right thing :wink:

**Comment by elParaguayo** [comment]
Yes - that's one way to test. It might be worth just waiting to see if the tests complete first just to make sure I haven't broken anything!

**Comment by a2n-s** [comment]
ok i'll wait a bit then!

**Comment by a2n-s** [comment]
Thanks a lot guys for the quick response and fix, that is impressive :star-struck:

Is there a way to know when the commit will be available in, let's say, the Arch repositories? :yum:

**Comment by elParaguayo** [comment]
We need to push another release and then the Arch packagers will pick it up.

**Comment by a2n-s** [comment]
noice!
this will be the first thing I test on next release :ok_hand:
