### ISSUE TITLE
Groups cannot be listed using JSON IPC

### ISSUE THREAD

**Issue by Jaakkonen** [qtile/qtile#3360]
Using the JSON serialization format in the IPC and trying to list groups yields exception 
```
Object of type set is not JSON serializable
NoneType: None
```
in the qtile logs and causes a `IPCError: Unable to decode json data` in the client end.

Reproduce with:
```python
from libqtile.command.client import (
    InteractiveCommandClient,
    Client,
    find_sockfile,
    IPCCommandInterface,
)
c = InteractiveCommandClient(
    command=IPCCommandInterface(
        Client(find_sockfile(), is_json=True)
    )
)
c.groups()
```

**Comment by elParaguayo** [comment]
Thanks for flagging. Can confirm I get the same issue. Will investigate.

**Comment by Jaakkonen** [comment]
The main problem is at https://github.com/qtile/qtile/blob/f2d8eb4d079f6d8f6975d56ba37c547556c3b0d7/libqtile/ipc.py#L132
where the Python default JSON encoder is being used which doesn't support `set` type.

The possible fixes are using some JSON library that supports serializing `set`s (`ujson` can probably do that if I recall correctly) or by adding `default` argument to the `json.dumps` that converts the `set` to a `list` that is serializable by the encoder.

**Comment by elParaguayo** [comment]
Thanks. I think we'd go the route of converting the set to a list, rather than introducing a new dependency.

**Comment by elParaguayo** [comment]
Ha. Beat me to it. I was just about to submit a PR too.
