### ISSUE TITLE
[Xwayland] With the latest Git update, once again Spotify does not honor qtile layouts. Could someone confirm please? Thanks

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3365]
With the latest Git update, once again Spotify does not honor qtile layouts. (close issue #3273) Could someone confirm please? Thanks

_Originally posted by @cr1ogen in https://github.com/qtile/qtile/issues/3273#issuecomment-1046430113_

**Comment by elParaguayo** [comment]
I think this was confirmed on IRC yesterday but I've not verified this myself.

**Comment by cr1ogen** [comment]
![Uploading 2022-02-21_12-02-1645458228.png…]()

**Comment by justinesmithies** [comment]
I too can confirm that Spotify opens in floating mode and you could tile it back to normal using shift + mod + f but that doesn't seem to work as of the last days updates. It did work yesterday but now only tiles it to the right hand side and not the full window for monadtall ???
![2022-02-21_19-02-1645471002](https://user-images.githubusercontent.com/1571498/155015327-d1f85ec9-30f0-42ff-b78a-49aaab52386c.jpg)

**Comment by elParaguayo** [comment]
Just done a `git bisect`. It's this commit: https://github.com/qtile/qtile/commit/d0a27321b27577e0a57634c7fe63574a0c28e538
