### ISSUE TITLE
qtile-git aur build problem

### ISSUE THREAD

**Issue by robabo** [qtile/qtile#3366]
Hello, when I try to build qtile-git 0.20.0.r33 from the AUR it is failing some tests and gives me this:

--------------------------------------------------------------------------------------------------------- Captured stderr teardown ---------------------------------------------------------------------------------------------------------
qtile is not alive
========================================================================================================= short test summary info ==========================================================================================================
FAILED test/widgets/test_mpd2widget.py::test_mpd2_widget_display_and_actions[1-x11] - AssertionError: assert '■ MPD IDLE[-----]' == '⏸ Rick Astley/Never gonna give you up [-----]'
FAILED test/widgets/test_mpd2widget.py::test_mpd2_widget_display_and_actions[1-wayland] - AssertionError: assert '■ MPD IDLE[-----]' == '⏸ Rick Astley/Never gonna give you up [-----]'
FAILED test/widgets/test_mpd2widget.py::test_mpd2_widget_extra_info[1-x11] - AssertionError: assert '■ MPD IDLE[-----]' == '⏸ Rick Astley/Never gonna give you up [rz1cU]'
FAILED test/widgets/test_mpd2widget.py::test_mpd2_widget_extra_info[1-wayland] - AssertionError: assert '■ MPD IDLE[-----]' == '⏸ Rick Astley/Never gonna give you up [rz1cU]'
FAILED test/widgets/test_widget_init_configure.py::test_widget_init_config[1-x11-ImapWidget-kwargs28] - TypeError: Expected str, not None
FAILED test/widgets/test_widget_init_configure.py::test_widget_init_config[1-wayland-ImapWidget-kwargs28] - TypeError: Expected str, not None

I'm not sure where Rick Astley is coming from?

**Comment by elParaguayo** [comment]
Ha. That's from some of the music related widget tests. Nothing suspicious about Rick there!

That said, the tests shouldn't fail (and they don't when we run the test suite on github).

**Comment by elParaguayo** [comment]
Do you have mpd (and the python mpd library) installed on your system already?

**Comment by robabo** [comment]
I have both mpd and python-mpd2 installed.  I forgot to include part of the error message: 

--------------------------------------------------------------------------------------------------------- Captured stderr teardown ---------------------------------------------------------------------------------------------------------
qtile is not alive
__________________________________________________________________________________________ test_widget_init_config[1-wayland-ImapWidget-kwargs28] __________________________________________________________________________________________

manager_nospawn = <test.helpers.TestManager object at 0x7f7ed9813160>, minimal_conf_noscreen = <class 'test.widgets.conftest.minimal_conf_noscreen.<locals>.MinimalConf'>, widget_class = <class 'libqtile.widget.imapwidget.ImapWidget'>
kwargs = {'dummy_parameter': 1}

    @pytest.mark.parametrize("widget_class,kwargs", parameters)
    def test_widget_init_config(manager_nospawn, minimal_conf_noscreen, widget_class, kwargs):
        if widget_class in exclusive_backend:
            if exclusive_backend[widget_class] != manager_nospawn.backend.name:
                pytest.skip("Unsupported backend")

>       widget = widget_class(**kwargs)

test/widgets/test_widget_init_configure.py:96:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
libqtile/widget/imapwidget.py:78: in __init__
    password = keyring.get_password("imapwidget", self.user)
/usr/lib/python3.10/site-packages/keyring/core.py:55: in get_password
    return get_keyring().get_password(service_name, username)
/usr/lib/python3.10/site-packages/keyring/backends/chainer.py:51: in get_password
    password = keyring.get_password(service, username)
/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py:81: in get_password
    for item in items:
/usr/lib/python3.10/site-packages/secretstorage/collection.py:91: in search_items
    result, = self._collection.call('SearchItems', 'a{ss}', attributes)
/usr/lib/python3.10/site-packages/secretstorage/util.py:60: in call
    return self.send_and_get_reply(msg)
/usr/lib/python3.10/site-packages/secretstorage/util.py:46: in send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
/usr/lib/python3.10/site-packages/jeepney/io/blocking.py:184: in send_and_get_reply
    self.send_message(message, serial=serial)
/usr/lib/python3.10/site-packages/jeepney/io/blocking.py:144: in send
    data, fds = self._serialise(message, serial)
/usr/lib/python3.10/site-packages/jeepney/io/blocking.py:83: in _serialise
    data = message.serialise(serial=serial, fds=fds)
/usr/lib/python3.10/site-packages/jeepney/low_level.py:473: in serialise
    body_buf = body_type.serialise(self.body, 0, endian, fds=fds)
/usr/lib/python3.10/site-packages/jeepney/low_level.py:208: in serialise
    res_pieces.append(field.serialise(item, pos, endianness, fds=fds))
/usr/lib/python3.10/site-packages/jeepney/low_level.py:280: in serialise
    chunks.append(self.elt_type.serialise(
/usr/lib/python3.10/site-packages/jeepney/low_level.py:208: in serialise
    res_pieces.append(field.serialise(item, pos, endianness, fds=fds))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = StringType(FixedType(4, 'I')), data = None, pos = 21, endianness = <Endianness.little: 1>, fds = None

    def serialise(self, data, pos, endianness, fds=None):
        if not isinstance(data, str):
>           raise TypeError("Expected str, not {!r}".format(data))
E           TypeError: Expected str, not None

/usr/lib/python3.10/site-packages/jeepney/low_level.py:161: TypeError
--------------------------------------------------------------------------

**Comment by robabo** [comment]
I got this built from source without a problem. I don't know why it doesn't build from the AUR for me.
