### ISSUE TITLE
Order of Groups in External Bar not Constant in Multi Monitor Setup

### ISSUE THREAD

**Issue by scaramangado** [qtile/qtile#3375]
### Summary

My setup consists of 9 groups which can be active on either of my two screens. On launch my primary screen shows the first group, the secondary screen the second group. In my Polybar the order of groups is now "_**1, 3**_, 4, 5, 6, 7, 8, 9, _**2**_". When cycling through the groups using `lazy.screen.next_group()` the display-order of the groups sometimes changes.

### Caveats

Now I can't be 100% sure this is a qtile issue and not one of Polybar, however I did downgrade to qtile 0.19 and the issue was not present.

Using `xprop` I can see, that the order in `_NET_DESKTOP_NAMES` seems to be correct.

### Steps to Reproduce

**Two screens are needed.**

I uploaded a more or less minimal configuration which lets me reproduce the issue with the latest qtile and Polybar: [Gist](https://gist.github.com/scaramangado/6e6e940866655b603d6785e5c6437beb).

1. Copy the files from the Gist above to the qtile config directory. Make sure to have at least the defined terminal installed or change the config to an installed one.
2. Launch qtile 0.20.0.
3. If Polybar doesn't launch, run `~/.config/qtile/polybar.sh` (I can't be bothered to figure out why the startup hook isn't working in this example). `meta + Enter` launches a terminal.
4. Take note of the order of groups in the bar and watch it while cycling through them using `meta + Right`.

**Comment by m-col** [comment]
It sounds like it is sorting the groups as per the order in `_NET_DESKTOP_NAMES` _but_ split per output (i.e. `[[1, 3, 4, 5, 6, 7, 8, 9], [2]]`). It suspect it is getting the output that each group is on using the `_NET_DESKTOP_VIEWPORT` hint, which was added in the latest qtile release, likely explaining why downgrading changes the result for you.

I'm not sure I see an issue here. I believe (but won't say I'm certain!) that we are setting the relevant hints correctly, and it looks like the module is doing what it intends on doing. Maybe you want to use `pin-workspaces = true`, or request a feature where you can have groups ordered by `_NET_DESKTOP_NAMES` even if `_NET_DESKTOP_VIEWPORT` is set. Of course, if you discuss with the polybar guys and find we are doing something wrong, or I have misinterpreted what the module is doing, we can sort that out.

**Comment by scaramangado** [comment]
It seems that it's indeed polybar causnig this behaviour. I don't expect it to be changed there, since it'd likely interfere with other features, but if anyone comes across this problem in the future I explained how to patch polybar in the linked issue.
