### ISSUE TITLE
`widget.Prompt` is displayed on the main monitor. only

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3379]
Hi everyone!

It is not that big of an issue as I mainly use `dmenu` tu run commands, but I could not find any related issue :thinking: 
I have the `widget.Prompt` widget in my `qtile` bar.

### What happens
When opened, **it does not display on every monitor, but only on the main one**.

### What is expected
**that the prompt is mirrored on both monitors**, so that there is no need to turn your head around when you focus on the secondary one. This does not happen with the `widget.Chord` widget, which displays fine on all the monitors at once.

Hope there is something to do, did not find any extra argument in the doc nor in the source code.

Cheers :wave: :yum:

**Comment by elParaguayo** [comment]
So... If you use the same instance of a widget in different bars then Qtile will create mirrors which display the same content in each bar. I've no idea if this would work for `widget.Prompt` or not but it's worth a go.

To use it, create an instance in your config file:
``` python
prompt = widget.Prompt()
```

and then add `prompt` in the relevant `Bar`s.

FYI the `Chord` widget is different as that display is updated whenever a hook is fired so you don't need a mirror as all instances will respond to the same hook.

**Comment by m-col** [comment]
> I've no idea if this would work for widget.Prompt or not but it's worth a go.

Can confirm that it does. It's pretty cool because you can't tell which bar actually has keyboard input. It acts as though they all do.

**Comment by elParaguayo** [comment]
Nice. Never used the prompt widget...

**Comment by a2n-s** [comment]
really guys, your reaction time is simply amazing, can not tell enough how great your work is :star_struck: 

I think I get what you propose @elParaguayo, I'll try that right now ! :ok_hand:

**Comment by a2n-s** [comment]
It is a tiny bit convoluted with the way I wrote my config, but it works perfectly now!

The `widget.Prompt` widget is convenient mainly with its embedded history, very useful.

My solution is [here](https://github.com/a2n-s/dotfiles/commit/aca1789eb1fc74f6d99e08e4623c937bcf9b9ab1) if anyone is interested.

Thanks again guys, I close the issue.

**Comment by elParaguayo** [comment]
Glad you've got it working.

At a very high level, all you need to do is this:

``` python

# Create prompt widget first
prompt = widget.Prompt(),

# Then add it to your screens/bars
screens = [
    Screen(
        bottom=bar.Bar(
            [
                # other widgets,
                prompt,
                # other widgets,
            ],
            24,
        ),
    ),
    Screen(
        bottom=bar.Bar(
            [
                # other widgets,
                prompt,
                # other widgets,
            ],
            24,
        ),
    ),
]
The key point is that you're not creating a new widget in each bar, you're using the same one.

This is a trick that can be used for all widgets (with the exception of `SysTray`).

**Comment by a2n-s** [comment]
Yep this is exactly what I have in the commit above, just a bit more automatic I guess :yum: 
I'll remember that for later :+1:
