### ISSUE TITLE
borders are being eaten by `picom`'s rounded corners.

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3380]
Hey it's me again, yes I am hacking a lot on `qtile` recently :yum: 

I like `picom`'s rounded corners and `qtile`'s borders, but I am having trouble making them work properly together.
I am not sure if it is related to `qtile` but could not find related issues on `qtile/qtile` nor `yshui/picom`...

**What I get**
a border that is round on the outside but squary on the inside
![picom-border](https://user-images.githubusercontent.com/44101798/155525113-2271d834-56d2-49aa-8bab-1455d087ad97.png)

**What I expected**
something round on both side, more like this
![rounded-corners-picom](https://user-images.githubusercontent.com/44101798/155525978-fac6f846-f1dd-4bbe-84a0-a2ee4066a8c3.png)

**What I tried**
as it is working with my friend's config, I tried to use `picom` and `picom-tryone-git`(AUR) both in normal and `--experimental-backends` modes, and made sure our config files were similar, but nothing worked :confused:

Does it have something to do with `qtile` or am I missing some details ? :yum:

**Comment by m-col** [comment]
As I understand it, picom creates rounded windows by simply carving into the window's rectangle. If the window has (regular, square) borders then you'll get the effect in your first image. The effect in the second image requires more: not only is the outside carved into, but the border colour itself is rendered within the regular window contents. I don't think picom does this. For this you would need Qtile to render the rounded corners for you. Once upon a time there was a PR for this but it didn't end up getting merged (partially because I prioritise the multiple borders feature): https://github.com/qtile/qtile/pull/1517. I think the feature would still be welcome though.

**Comment by a2n-s** [comment]
yep I get it! So no such feature for now :+1: 

I mean, it is completely useless to do that and the issue is almost not noticeable for small enough radii :ok_hand: 

just wanted to understand what was going on, no idea how it is even possible then on the second image, which was, if i am not mistaken, taken under `qtile` :thinking:

Thanks for your quick answer, I close the issue :yum:

**Comment by a2n-s** [comment]
okey it is very strange indeed because it kinda work in the end :sweat_smile:

**`picom` WITHOUT `--experimetal-backends`**
![picom-glitch](https://user-images.githubusercontent.com/44101798/155584858-959c7a51-acc1-4d5b-b138-098b37b8ac74.png)
see the darker triangle near the X? it blinks when the window is not focused.

**`picom` WITH `--experimetal-backends`**![picom-glitch2](https://user-images.githubusercontent.com/44101798/155584863-4b0e86d5-18af-4502-90de-d8f8eb913a72.png)
there is no more darker blinking triangle, but a ghost corner on the outside, not super pretty but no blinking corner at least.

in any case, it works!!
I am a bit stuned and do not know where it comes from...

**Comment by a2n-s** [comment]
okey it is very strange indeed because it kinda work in the end :sweat_smile:

**`picom` WITHOUT `--experimetal-backends`**
![picom-glitch](https://user-images.githubusercontent.com/44101798/155584858-959c7a51-acc1-4d5b-b138-098b37b8ac74.png)
see the darker triangle near the X? it blinks when the window is not focused.

**`picom` WITH `--experimetal-backends`**
![picom-glitch2](https://user-images.githubusercontent.com/44101798/155584863-4b0e86d5-18af-4502-90de-d8f8eb913a72.png)
there is no more darker blinking triangle, but a ghost corner on the outside, not super pretty but no blinking corner at least.

in any case, it works!!
I am a bit stuned and do not know where it comes from...

**Comment by m-col** [comment]
Huh, neat. picom is doing some clever stuff then.

**Comment by a2n-s** [comment]
> @a2n-s how you made that the border go on the triangle corner? I tried doing something similar but I just get the corner on the border

put a high `corner-radius`, e.g. `16`, maybe `killall picom` and then restart it with `picom --experimetal-backends -b`

i just reporduced that on my machine and it does the triangle thing :wink:

be careful with too wide window borders, it breaks the rounded effect on the inside, which is the topic of this issue indeed!

**Comment by zackfall** [comment]
@amtoine I don't know if you already notice about this, but if you execute `picom --backend glx -b` it does the effect you wanted at the start without the ghost corner
![corners](https://i.imgur.com/QuMyBaq.png)
