### ISSUE TITLE
Window elements dependant on window position on the screen

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3382]
![2022-02-26_01-44](https://user-images.githubusercontent.com/84532402/155818157-15ce01d4-341c-4aaf-a705-666bbece5dab.png)

![2022-02-26_01-47](https://user-images.githubusercontent.com/84532402/155818135-a40ecef0-2f43-470b-9b02-0497c333febc.png)

This is Spotify running in Anbox for... personal reasons, shall we say? 

***Window management*** to be taken with a grain of salt :) I do know that this might be an Anbox issue, just wanted a second opinion.

**Comment by m-col** [comment]
Please could you clarify what issue it is that you're seeing? I'm not really sure what I'm looking for

**Comment by ervinpopescu** [comment]
The buttons are smooshed together... I'm posting more photos now. If the window doesn't get past the half of the screen, this doesn't happen... It's quite a niche case, I'll admit it.

Expected behaviour:

![2022-02-27_03-25](https://user-images.githubusercontent.com/84532402/155864443-5a99cdd3-8f2e-4550-a524-d27f8d672603.png)

![2022-02-27_03-29](https://user-images.githubusercontent.com/84532402/155864543-13e25a48-4a08-4d2a-9aca-d1af79aad459.png)

Actual behaviour:

![2022-02-27_03-25_1](https://user-images.githubusercontent.com/84532402/155864444-8a9be82e-877f-46c5-af45-91d072137a55.png)

It can get as bad as this:

![2022-02-27_03-26](https://user-images.githubusercontent.com/84532402/155864482-d0be5aeb-4db9-4ceb-887e-fde4b21fb056.png)
