### ISSUE TITLE
Systray crashes on desktop login, but displays correctly after qtile restart

### ISSUE THREAD

**Issue by AshishShenoy** [qtile/qtile#3390]
I use qtile with two screens, and the only difference in the bars of both screens is that only one of them contains a systray. On logging in, the systray crashes with the log message:

```
2022-02-27 01:09:23,245 ERROR libqtile bar.py:_configure_widget():L324 Systray widget crashed during _configure with error: ConfigError('Only one Systray can be used.')
```

However, when i restart qtile, the systray displays corectly, with the following log if it means anything:

```
2022-02-27 01:10:08,685 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
```

[Here](https://github.com/AshishShenoy/dotfiles/blob/master/qtile/.config/qtile/config.py#L283) is the relevant line in my config.py, which I use to remove the systray from the bar in one of the screens.

**Comment by elParaguayo** [comment]
I'm guessing you're on v0.20 rather than git latest.

This has been retired many times. It's fixed and will be in the next release. 

If you're on git latest and are still seeing this, please reopen the issue.
