### ISSUE TITLE
Systray Opacity

### ISSUE THREAD

**Issue by christopherbui** [qtile/qtile#3401]
### The issue:

Specs:
- Arch Linux
- Kernel 5.16.11

I have picom eanbled, with 90% opacity set for the bar background. However, regardless of the background opacity set, the systray background will always have 0% opacity.

The only way to have systray background match that of the bar is if opacity is 100%. 

I have tried setting opacity background of systray within the config file, but that does not work.

I have read the docs and have found no proper solution. Is this a bug or is there a proper way to handle systray background opacity? My goal is to have it match the bar's opacity at all times.

Thank you
![systray_opacity](https://user-images.githubusercontent.com/18688562/156469766-554940a4-d8a9-4696-b2e2-ff956a5479c0.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
The Systray icons are separate windows and so the bar opacity value does not impact them.

I will take a look to see if it's possible to pass this value on to the icons.

**Comment by elParaguayo** [comment]
Actually, I can't recreate this. 

I've just tested by setting bar opacity to 0.5 in my config and the systray icons respect that opacity.

Can you share your config?

**Comment by christopherbui** [comment]
That's interesting that it's not reproducible. I am running on a fresh Arch install with _picom-ibhagwan_ from the AUR installed.

[qtile_config](https://github.com/christopherbui/configs/tree/main/laptop/qtile/config.py)
[picom_config](https://github.com/christopherbui/configs/blob/main/laptop/picom/picom.conf)

**Comment by elParaguayo** [comment]
Instead of using a picom rule for the opacity, try setting the opacity for the bar in your config.

**Comment by christopherbui** [comment]
I have commented out all opacity rules in the picom config and set opacity through the qtile config, yet the problem persists. I am thinking about trying a different fork of picom, but I have my doubts that is the cause
![systray2](https://user-images.githubusercontent.com/18688562/156663074-0a42521f-a961-41c8-9e38-076c97945bcd.png)
.

**Comment by elParaguayo** [comment]
That behaviour is expected. Systray doesn't work when you a semi transparent alpha value to e background colour. That's referenced in the docs. 

Try removing the alpha value and then set the opacity value in the bar's parameters. Looking at your GitHub link, that's still set to 1.

**Comment by elParaguayo** [comment]
@christopherbui have you managed to test the above?
