### ISSUE TITLE
Zoom crash when screen-sharing

### ISSUE THREAD

**Issue by RomainMichau** [qtile/qtile#3405]
### The issue:

Since some time I'm having issue with the Zoom client. Every time I'm trying to share my screen my zoom client crash returning an error signal 15. Issue is happening since the upgrade to zoom 5.9.1-1

When looking at zoom logs (~/.zoom/logs/zoom_stdout_stderr.log) I'm seeing this 2 lines (I dont know if it is really related)
```
qrc:/qml/PageContacts.qml:129:13: QML TabView: Binding loop detected for property "count"
qrc:/qml/PageContacts.qml:164: TypeError: Cannot read property 'item' of null
```
Setup:
- Arch Linux
- Xorg 21.1.3-6
- Qtile 0.20.0
 - [AUR](https://aur.archlinux.org/packages/zoom) Zoom package 5.9.6-1

Same issue is happening with 2 different laptops having the same setup and I'm suspecting that the issue is coming from qtile since when using another WM (i3wm) I do not have this issue.
I do not see any logs on qtile side that seems to be related to this issue

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I'm not saying it's _not_ a qtile issue but it is interesting that other people are reporting zoom crashing: https://aur.archlinux.org/packages/zoom

**Comment by DannMartinnez** [comment]
Hi Guys, Im having the same problem.

Setup:

    Arch Linux
    Xorg 21.1.3-6
    Qtile 0.21.0-1
    Zoom package 5.10.0-1

When I try to share screen using xfce it works fine.

**Comment by m-col** [comment]
That's great to hear. If you're happy that this is resolved, feel free to close the issue.
