### ISSUE TITLE
 [ Wayland ] Certain apps right click menus flicker on & off

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3408]
### The issue:

Qtile version: 0.20.1.dev73+g84328b65
OS: Archlinux using qtile-git

Certain apps like Qutebrowser and Libre-Office act strangely when using the right click menus. The menu context menu on Qutebrowser for instance flickers on and off rapidly sometimes making it impossible to see the options. This happens on Libre-Office. There are probably more that this happens on and I'll update as I come across them but I'm sure it's Qtile related.

Edit: Gimp-git suffers the same on right click and left click menus.

**Confirmed that this issue is not present in 0.20.0 Stable only in git**

I have ruled out my config as tried with just the default too.
I have included a video took from my mobile trying to capture what happens.

https://user-images.githubusercontent.com/1571498/156928918-f19ff578-bb22-406b-9ddc-3cd3229fc510.mp4

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Did a bisect and it seems to be this commit: 733f06ae2d277528991b4d27cb6b6829b766afa2

**Comment by m-col** [comment]
If you comment out this assertion, does it fix it? https://github.com/qtile/qtile/blob/master/libqtile/backend/wayland/window.py#L1701

**Comment by justinesmithies** [comment]
Yes @m-col this fixes all those issues for with Qutebrowser, Gimp, Libreoffice and so on.

**Comment by m-col** [comment]
Here is the fix for this: https://github.com/qtile/qtile/pull/3508

**Comment by m-col** [comment]
Fixed by #3508
