### ISSUE TITLE
battery widget displays the unknown char when battery is full

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3411]
### The issue:

When the battery is full, the unknown char, i.e. "?" as I let the default, is displayed instead of the full battery char, which is a full battery emoji in my config.
The source code of that part of `qtile` is quite intricate so I'm not sure how `widget.Battery` gets the battery status, however, to help you:
`acpi` gives me `Discharging` when not charging, `Charging` when charging and `Not charging` when charging with a full battery. Maybe the `Not charging` status is unknown to `qtile`!

`qtile --version`: 0.20.0

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Assuming you're on a laptop, can you do `cat /sys/class/power_supply/BAT0/status`.

**Comment by a2n-s** [comment]
yes I am and I can do that :+1: 
```
~ ❯ cat /sys/class/power_supply/BAT0/status
Discharging
~ ❯ cat /sys/class/power_supply/BAT0/status
Charging
```
when not charging and charging respectively.

however my battery is not full yet, let me charge it and I'll post the result of `cat /sys/class/power_supply/BAT0/status` as soon as it is fully charged :yum:

**Comment by elParaguayo** [comment]
Thanks.

FYI the relevant part of the code is these lines:
https://github.com/qtile/qtile/blob/68fb7da703fd6466c53f76eae5983eca35d54503/libqtile/widget/battery.py#L272-L279

So, if when your battery is full, it says anything other than "Full" then you get the "unknown" state.

**Comment by a2n-s** [comment]
and when the battery is full and still charging, I have
```
~ ❯ cat /sys/class/power_supply/BAT0/status
Not charging
```

**Comment by elParaguayo** [comment]
Well, if that's the only unknown state for your battery, then just change that parameter in your config.

Alternatively, you'd need to subclass `_LinuxBattery` and amend that method. Then you'd subclass `Battery` and make sure the `_load_battery` method loads your updated battery.

**Comment by a2n-s** [comment]
I can definitely rewrite my own `_LinuxBattery` class, I've already done such a thing with the "*notification on low battery*" issue I opened.

> Well, if that's the only unknown state for your battery, then just change that parameter in your config.
What do you mean? I do not see any option in my config that could help :thinking: 

> I'm also curious why your battery doesn't report being full...
I am curious too :laughing:

**Comment by elParaguayo** [comment]
There's an `unknown_char` parameter. If you only see that when your battery is full then just change that setting.

This is what you referred to in your original post.

**Comment by a2n-s** [comment]
oh I just understood :laughing:
my bad really sorry wasting your time on that one...

I patched my own Battery class again to solve this issue and it should work just fine :thumbsup:

I investigate a bit with my arch-based friends and close the issue shortly!
Thanks again for your great answers :ok_hand:

**Comment by elParaguayo** [comment]
No problem. Happy to help.

**Comment by a2n-s** [comment]
After some investigation, I have gathered the following results, each one with an Arch-based distro:

```
uname -sr (i.e. the kernel) | cat /sys/class/.../status (when battery full)
----------------------------+-----------------------------------------------
Linux 5.16.13-arch1-1       | Not charging
Linux 5.16.12-arch1-1       | Not charging
Linux 5.16.12-arch1-1       | Not charging
Linux 5.16.12-arch1-1       | Full (a VM)
Linux 5.16.12-arch1-1       | Full (a VM)
Linux 5.16.11 arch1-1       | Full
Linux 5.16.11-arch1-1       | Full
Linux 5.15.25-1-MANJARO     | Full
```

**Do you think opening a *pull request* would be useful?**

At least, I am not the only one with that problem, even on very recent kernels, what do you think about adding the `Not charging` case in the if statement of the `_LinuxBattery` class or maybe creating a new `_ArchBattery` class?
**I can even write that myself and open a *pull request* if it is ok for you, you tell me** :wink:

**Comment by elParaguayo** [comment]
I'd still like to understand _why_ batteries don't report as `Full` i.e. is this a design choice or a bug?

In terms of fixing, I think the best way would be to be able to set the terms to be matched when checking the status, rather than these being hardcoded.

**Comment by a2n-s** [comment]
and a last example that has `Charging` on `Linux 5.15.25-1-MANJARO`

what about using the content of `/sys/class/power_supply/BAT0/capactity`, check the battery level to determine if the battery is full instead of the `status`?

**Comment by elParaguayo** [comment]
@a2n-s could you try the patch in #3469?

**Comment by a2n-s** [comment]
Yes i can, the commit is now in my code and being tested :ok_hand: 

if you do not have any message from me in here in the next few days, consider this issue definitely closed.
if any bug arises, you'll be notified :wink:

**Comment by elParaguayo** [comment]
Can you do another test for me?

When your battery stops charging, can you check the value of `/sys/class/power_supply/BAT0/capactity`. I'm wondering if `Full` is not returned if capacity is less than a certain value (i.e. maybe it's an older battery). Just an idea.

Ideally, we'd prefer not to add a configuration option to the widget and just handle this automatically.

**Comment by a2n-s** [comment]
> When your battery stops charging, can you check the value of `/sys/class/power_supply/BAT0/capactity`. I'm wondering if `Full` is not returned if capacity is less than a certain value (i.e. maybe it's an older battery). Just an idea.
 will do that on next charging cycle :ok_hand: 

> Ideally, we'd prefer not to add a configuration option to the widget and just handle this automatically.
yeah that seems very sensible to do!

**Comment by a2n-s** [comment]
okey so:

- your patch is working just fine :ok_hand:
- when battery is full, I have `100` inside `/sys/class/power_supply/BAT0/capactity`
- my battery is indeed a bit old (see snippet below)
```
~ ❯ acpi -i
Battery 0: Not charging, 100%
Battery 0: design capacity 4229 mAh, last full capacity 1852 mAh = 43%
```
