### ISSUE TITLE
How do I create key bindings that are layout agnostic

### ISSUE THREAD

**Issue by mastern2k3** [qtile/qtile#3413]
Relates to post by @s-aleck in https://github.com/qtile/qtile/discussions/3255

How do I create a command key bind that would be recognized regardless of the currently active keyboard layout?

**Comment by elParaguayo** [comment]
Copying my post from that discussion thread:

This has been discussed a bit before (have a look at https://github.com/qtile/qtile/issues/933) but nothing's been implemented yet.

**Comment by refaelsh** [comment]
+1
