### ISSUE TITLE
Unable to match LibreOffice wm_class for spawning into group

### ISSUE THREAD

**Issue by JoaoDDuarte** [qtile/qtile#3414]
### The issue:

I am trying to get LibreOffice (including Impress, Calc etc...) to appear in a certain group when spawned. I have managed to do this for lots of other programs. Below is the relevant section in my config

```python
Group(
        "6",
        label="DOC",
        matches=[
            Match(
                wm_class=[
                    "libreoffice-writer",
                    "libreoffice-calc",
                    "libreoffice-impress",
                    "libreoffice",
                    "atril",
                ]
            ),
        ],
    ),
```

I checked with `xprop` and I am in fact targeting the correct `wm_class`, but I cannot seem to get it to work. I disabled the splash screen but still no success.

Does anyone have any experience with this kind of problem?

I am running qtile 0.20.0.

Thanks!

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
`matches` is a list of `Match` objects, so you need a new `Match` for each `wm_class`, rather than a list of classes. Try:
``` python
Group(
    "6",
    label="DOC",
    matches=[
        Match(wm_class="libreoffice-writer"),
        Match(wm_class="libreoffice-calc"),
        Match(wm_class="libreoffice-impress"),
        Match(wm_class="libreoffice"),
        Match(wm_class="atril"),
    ]
),
```

**Comment by JoaoDDuarte** [comment]
Ah ok, my bad for misunderstanding the docs - thanks!

**Comment by JoaoDDuarte** [comment]
Reopening just to ask whether it is expected behaviour for this to work:

```
    Group(
        "7",
        label="MEDIA",
        matches=[
            Match(
                wm_class=[
                    "spotify",
                    "rythmbox",
                    "geeqie",
                    "mpv",
                    "shutter",
                ]
            ),
            Match(
                title=[
                    "GNU Image Manipulation Program",
                ]
            ),
        ],
    ),
```

**Comment by elParaguayo** [comment]
Does it work for all windows listed in `wm_class`? I think (but haven't checked) that, for `wm_class`, the code works by checking whether the client's `wm_class` is in the list of classes in the `Match` object.

So, yes, I think it _should_ actually work.

For LibreOffice, maybe there's an issue with the splash screen that comes up first.

**Comment by JoaoDDuarte** [comment]
All of them work except LibreOffice, I'm trying to figure out why as I did disable the splash screen...very weird...

Is there a way to debug qtile such that I can a verbose output on this matching process?

**Comment by elParaguayo** [comment]
I wonder if the issue is similar to the one discussed here: https://github.com/qtile/qtile/issues/2405 (particularly the last comment)

**Comment by elParaguayo** [comment]
I wrote a quick function which was hooked to `client_new` and prints the client's `wm_class`.

When the window opened, the class was an empty list, this was then replaced by `["soffice", "Soffice"]`.

**Comment by JoaoDDuarte** [comment]
Thank you, I appreciate it! Is there any way I can maybe write a quick sentence about this on the qtile wiki in case anyone is interested in targeting LibreOffice's wm_class or is it not worth it as people can just search the issues?

**Comment by elParaguayo** [comment]
Wiki should be editable so go ahead!

**Comment by em2943** [comment]
i'm having the same trouble but with my browser, librewolf.
