### ISSUE TITLE
StatusNotifier don't load anything

### ISSUE THREAD

**Issue by zackfall** [qtile/qtile#3418]
### The issue:

Distribution: ArchLinux
Qtile: 0.20.0

I'm having a problem with the StatusNotifier, and is that always that I open some app that have systemtray icon like zoom, dbus_next throws me this in the qtile log:
```
2022-03-11 18:05:29,769 ERROR libqtile loop.py:_handle_exception():L61 invalid object path: org.kde.StatusNotifierItem-23900-2
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/statusnotifier.py", line 478, in item_added
    success = future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/statusnotifier.py", line 95, in start
    introspection = await self.bus.introspect(self.service, self.path)
  File "/home/isaac/.local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 214, in introspect
    super().introspect(bus_name, path, reply_handler)
  File "/home/isaac/.local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 204, in introspect
    Message(destination=bus_name,
  File "/home/isaac/.local/lib/python3.10/site-packages/dbus_next/message.py", line 92, in __init__
    assert_object_path_valid(self.path)
  File "/home/isaac/.local/lib/python3.10/site-packages/dbus_next/validators.py", line 153, in assert_object_path_valid
    raise InvalidObjectPathError(path)
dbus_next.errors.InvalidObjectPathError: invalid object path: org.kde.StatusNotifierItem-23900-2
```
This happened to me in X11 and Wayland

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. I can replicate this.

Looking at the d-bus interface, I can see the app should be showing an icon so I need to see why it's crashing the widget.

**Comment by elParaguayo** [comment]
#3421 should fix this for you. Great if you could test and confirm.

**Comment by zackfall** [comment]
Yeah, it fixed with zoom, I tried with another app like KeePass but it doesn't seems to work, I don't know if there is another app that doesn't work with the StatusNotifier

**Comment by elParaguayo** [comment]
Ok. More work needed. Thanks for testing.

**Comment by elParaguayo** [comment]
Are you sure KeePass actually has a StatusNotifier icon? I'm not sure they've implemented the interface. I can't see anything on dbus when loading the app.

Just because an app has a System tray icon, it doesn't mean it will have a StatusNotifier icon.

**Comment by zackfall** [comment]
Ooh, that make sense, so maybe It doesn't have one, I got confused because I used it in sway and it shows an icon.

I tried more apps and it seems to work correctly thanks

**Comment by elParaguayo** [comment]
Well, that's interesting because system tray is an X thing so I'm surprised it's working in Sway.

**Comment by zackfall** [comment]
Mm I mean I'm not using the sway bar that comes default, I'm using waybar I don't know how they implement the system tray

**Comment by elParaguayo** [comment]
I only get an icon with KeePass with SysTray. 

keepassxc does have a StatusNotifier icon.

**Comment by zackfall** [comment]
Ooh okay okay nice, by the way I was trying to use the Systray In the x client but it always crash, maybe I have to create a new issue for this?

**Comment by elParaguayo** [comment]
If you're on v0.20 and you get an error about only having one `Systray` then you don't need to create an issue. It should be fixed in the current git version.

**Comment by zackfall** [comment]
Ooh cool, I will close this issue thanks for the hard work 😊
