### ISSUE TITLE
[Wayland] KeyboardLayout widget not working

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3425]
### The issue:

qtile version 0.20.1.dev78+gb7167931

The keyboard layout, from US to ES, does not change when choosing the language layout. In X11 it works

KeyboardLaout config part

                widget.KeyboardLayout(
                    configured_keyboards=['us','es'],
                ),

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by justinesmithies** [comment]
**I too have this exact issue using latest git version under wayland**

I have two keyboards, one on the laptop which is GB layout and my custom built handwired one which is US layout. If I boot into qtile wayland changing the keyboard layout does nothing on either keyboard.                                                                                                                                                          But if I power cycle my external keyboard then that keyboard starts to function with the keyboard layout widget allowing me to switch between us and gb. But the laptops keyboard sticks at the default setup in the wayland input rules of gb. It's like something isn't getting refreshed ?? Have you seen this issue @m-col  ??

**Comment by m-col** [comment]
Please could you guys test https://github.com/qtile/qtile/pull/3607 and see if it fixes the issue without causing other unexpected effects?

**Comment by justinesmithies** [comment]
Can't check this as the last update virtual pointer has broken my Qtile. It
won't run now.

**Comment by m-col** [comment]
Do you have the latest version of pywlroots?

**Comment by justinesmithies** [comment]
All tested and works perfectly

**Comment by cr1ogen** [comment]
Works now! Thanks
