### ISSUE TITLE
show a popup with group name when switching groups

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3426]
### The issue:

I would like to achieve the same kind of effect that the one on [this short clip](https://youtube.com/clip/UgkxZu4sf2OXuNw-BL0w0Vh56DxokqyaxXe7), i.e. **when switching groups, the name of the group appears somewhere on the screen**.

I have two smaller issues indeed:

1.   I'm trying to use the builtin hooks to do that, e.g. `@hook.subscribe.changegroup` but there is no doc on the [hooks doc page](http://docs.qtile.org/en/stable/manual/ref/hooks.html). I just found the [commands API doc](http://docs.qtile.org/en/stable/manual/commands/index.html) where I might be able to find what i need, i.e. extract the name of the current group, but it was not trivial... **Maybe adding a direct link to the commands API would be helpful!** And then, i do not know if using `libqtile.command.client.InteractiveCommandClient().group.info()` is the prefered way to extract the name of the current group :thinking: 
2. **any idea how to do such a small and ephemeral popup?** Could not find it inside the `xmonad` config of the clip... And using things like `dunst` would not be as pretty as that :thinking: 

Cheers :wave: :yum: 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by a2n-s** [comment]
and regarding the first point,
with
```
from libqtile.command.client import InteractiveCommandClient
@hook.subscribe.changegroup
def changegroup():
    c = InteractiveCommandClient()
    group = c.group.info()
```
i get
```
2022-03-14 17:44:22,812 ERROR libqtile hook.py:fire():L392 Error in hook changegroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 390, in fire
    i(*args, **kwargs)
  File "/home/ants/.config/qtile/config.py", line 120, in changegroup
    group = c.group.info()
  File "/usr/lib/python3.10/site-packages/libqtile/command/client.py", line 227, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 251, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 225, in execute
    status, result = self._client.send((call.parent.selectors, call.name, args, kwargs))
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 161, in send
    return asyncio.run(self.async_send(msg))
  File "/usr/lib/python3.10/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
```
when switching group on
```
$ qtile --version
0.20.0
```

**Comment by elParaguayo** [comment]
You don't need a command client. Your function is being run from within the main qtile process (as it's part of your config) so you can just access the `qtile` object and its attributes.

Something like this:
``` python
from libqtile import qtile

@hook.subscribe.changegroup
def changegroup():
    group_name = qtile.current_group.name
```

As for the second question, shameless plug but you can do some nice popups with my [popup toolkit](https://qtile-extras.readthedocs.io/en/latest/manual/how_to/popup.html). You can set a timer to make the popup disappear.

**Comment by a2n-s** [comment]
with
```
from libqtile import qtile
@hook.subscribe.changegroup
def changegroup():
    group_name = qtile.current_group.name
```
I get 
```
2022-03-14 18:35:24,851 ERROR libqtile hook.py:fire():L392 Error in hook changegroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 390, in fire
    i(*args, **kwargs)
  File "/home/ants/.config/qtile/config.py", line 119, in changegroup
    group_name = qtile.current_group.name
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 549, in current_group
    return self.current_screen.group
AttributeError: 'Qtile' object has no attribute 'current_screen'
```
and `@hook.subscribe.setgroup` does not do anything when changing group

**Comment by elParaguayo** [comment]
The error happens because the hook gets fired during setup too. You can add a check (`if hasattr(qtile, "current_screen"):`)

The package is called `qtile-extras`. The shameless plug was because I was promoting my own work rather than a pure qtile solution.

**Comment by a2n-s** [comment]
> The error happens because the hook gets fired during setup too. You can add a check (`if hasattr(qtile, "current_screen"):`)

ok I got it fireing with 
```
from libqtile import qtile

def popup(qtile):
    controls = [
        PopupText(
            font="mononoki Nerd Font",
            fontsize=150,
            text="TEST",
            row=0,
            col=0,
        ),
    ]

    layout = PopupGridLayout(
        qtile,
        width=500,
        height=200,
        controls=controls,
        background="00000060",
        initial_focus=None,
    )

    layout.show(centered=True)

@hook.subscribe.setgroup
def setgroup():
    popup(qtile)
```
but even though the hook fires when changing groups, I still get 
```
2022-03-14 19:23:17,085 ERROR libqtile core.py:_xpoll():L331 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 299, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1116, in handle_Expose
    self.process_window_expose()
  File "/usr/lib/python3.10/site-packages/libqtile/popup.py", line 149, in draw
    self.drawer.draw()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/base.py", line 726, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 155, in _draw
    self._paint()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 128, in _paint
    if self.needs_update:
  File "/usr/lib/python3.10/site-packages/libqtile/backend/base.py", line 642, in needs_update
    ink_changed = any(not math.isclose(0.0, i) for i in self.surface.ink_extents())
AttributeError: 'NoneType' object has no attribute 'ink_extents'
```
so the popup is not popping up.
I also mapped it onto some bindings and the popup works then
might have to do with the `qtile` argument :thinking: 

i think i need to get some meal before continuing :laughing: 
thank you so much for your time, hope it's not wasted, looks like a very interesting package!

> The package is called `qtile-extras`. The shameless plug was because I was promoting my own work rather than a pure qtile solution.

oooh i thought you were mentioning another package!
would be cool to use such a feature on more WM though :thinking:

**Comment by elParaguayo** [comment]
Hmm. That is odd. I get the same behaviour/errors.

I don't immediately see why the popup wouldn't show from a hooked function.

Will investigate.

**Comment by a2n-s** [comment]
always unexpected things, right? :open_mouth: 

maybe this is getting a bit out of the scope of the original issue :thinking: 
we should open a discussion on your [qtile-extras](https://github.com/elParaguayo/qtile-extras)?

**Comment by elParaguayo** [comment]
Closing this as the issue seems to be qtile-extras.

**Comment by elParaguayo** [comment]
For now, just add `keyboard_navigation=False` to the `PopupGridLayout` config. That should fix it.

**Comment by a2n-s** [comment]
> For now, just add `keyboard_navigation=False` to the `PopupGridLayout` config. That should fix it.

oh wow that works exactly as expected :ok_hand: 

just a last thing thing before the "real" issue with `qtile-extras`, you did mention a timer to make popups disappear :thinking: 
is this built-in to `qtile` or some other thing? could not see any option for the `Popup` classes :sweat_smile:

**Comment by elParaguayo** [comment]
``` python

def popup(qtile):
    controls = [
        PopupText(
            font="mononoki Nerd Font",
            fontsize=150,
            text="TEST",
            row=0,
            col=0,
        ),
    ]

    layout = PopupGridLayout(
        qtile,
        width=500,
        height=200,
        controls=controls,
        background="00000060",
        initial_focus=None,
    keyboard_navigation=False,
    )

    layout.show(centered=True)
    qtile.call_later(1, layout.kill)  # kill popup after 1 second
```

**Comment by a2n-s** [comment]
> ```python
>     qtile.call_later(1, layout.kill)  # kill popup after 1 second
> ```

this is just perfect! works like a charm and like I wanted it to work.
and learned a new feature of `qtile` :star_struck:
