### ISSUE TITLE
Dropdown doesn't work with Tauon Music Box

### ISSUE THREAD

**Issue by cadr10** [qtile/qtile#3430]
### The issue:

I tried to run a dropdown for tauon music box, but it doesn't work. It spawns the player, but can't hide/unhide it. I tried with Nautilus with wm_class and wm_instant_class and it works just fine. Last scratchpad issues were about not having the wm_class option.

I have the same behaviour matching wm_class in awesomewm and it does work.

```
dropdown_conf = {
    'opacity': 1,
    'warp_pointer': False,
    'height': 0.45,
}

groups = []

groups.append(
    ScratchPad('sp', [
            DropDown(
                'tauon',
                'tauon',     
                match=Match(wm_instance_class="Tauon Music Box"),                
        **dropdown_conf
            ),]))
```

My binding:

`    Key([mod], "c", lazy.group['sp'].dropdown_toggle('tauon')),`

WM_CLASS doesn't work either.

Tauon's xprop output:

```
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64):
	(not shown)

_NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 2, 2
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_NAME(UTF8_STRING) = "Tauon Music Box"
WM_NAME(UTF-8) = "Tauon Music Box"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 15012
WM_LOCALE_NAME(STRING) = "pt_BR.UTF-8"
WM_CLASS(STRING) = "Tauon Music Box", "Tauon Music Box"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x95a42af4
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 2402, 289
		program specified minimum size: 560 by 330
WM_CLIENT_MACHINE(STRING) = "vx15"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
```
qtile version: 0.20.0 (X11)

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
When I debug this, it seems that Tauon has a weird startup process

- A window is started
- It is immediately killed
- A new window is started with the same info

Maybe some kind of daemon that gets started?

To verify:

```python
@hook.subscribe.client_new
def hook_new(c):
    print(f"New client with info {c.info()}")

@hook.subscribe.client_killed
def hook_kill(c):
    print(f"Killed client with info {c.info()}")
```

gives

```python
New client with info {'name': 'Tauon Music Box', 'x': 321, 'y': 36, 'width': 382, 'height': 696, 'group': None, 'id': 16777226, 'wm_class': ['Tauon Music Box', 'Tauon Music Box'], 'floating': False, 'float_info': {'x': None, 'y': None, 'width': 382, 'height': 696}, 'maximized': False, 'minimized': False, 'fullscreen': False}
Killed client with info {'name': 'Tauon Music Box', 'x': 622, 'y': 52, 'width': 382, 'height': 696, 'group': '\ue795 ', 'id': 16777226, 'wm_class': ['Tauon Music Box', 'Tauon Music Box'], 'floating': False, 'float_info': {'x': 622, 'y': 52, 'width': 382, 'height': 696}, 'maximized': False, 'minimized': False, 'fullscreen': False}
New client with info {'name': 'Tauon Music Box', 'x': 321, 'y': 36, 'width': 382, 'height': 696, 'group': None, 'id': 16777232, 'wm_class': ['Tauon Music Box', 'Tauon Music Box'], 'floating': False, 'float_info': {'x': None, 'y': None, 'width': 382, 'height': 696}, 'maximized': False, 'minimized': False, 'fullscreen': False}
```

This could be a bug in qtile with killing it and then restarting it or something? But it just looks like the tauon startup process is like this.

Which means that the code simply allocates a scratchpad, immediately deletes it and then adds the second tauon windows as a normal tiled window. The match for wm_name or wm_class is not of a big use here as the info between the windows is identical. You can use something like this as a workaround:

```python

# Put somewhere in your file
scratchpad_tauon_window_count = 0
def check_tauon_scratchpad(client):
    global scratchpad_tauon_window_count
    if Match(wm_class="Tauon Music Box").compare(client):
        scratchpad_tauon_window_count += 1
        if scratchpad_tauon_window_count == 2:
            scratchpad_tauon_window_count = 0
            return True
    return False

# in scratchpad definitions
DropDown('tauon', 'tauon', match=Match(func=check_tauon_scratchpad)),
```
It's a hacky workaround, but I don't know how we could fix this elegantly in Qtile.

**Comment by jwijenbergh** [comment]
Have you tried this workaround @cadr10?

**Comment by LetsGoPepele** [comment]
As a current workaround, I managed to combine title (i.e WM_NAME) and wm_class (i.e WM_CLASS) to only have the main window in the dropdown. But that's not applicable to all programs.
I still have the 1. issue too, but that's not a big deal because I don't mind having that floating since it's a temporary window.
