### ISSUE TITLE
Links clicked in Electron apps don't open in Firefox

### ISSUE THREAD

**Issue by mariuszkurek** [qtile/qtile#3438]
### The issue:

0.20.0, nothing in logs, unrelated to Qtile config.
On the exact same environment (Arch), but with XFCE, links open a new tab in Firefox as expected. In Qtile, it looks like it tries to launch Firefox, but (unless it isn't launched), Firefox throws the "Firefox is already running" error.
The problem occurs in Discord and MS Teams, doesn't occur in Telegram and LibreOffice, which makes me believe it's related to Electron.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
As I understand it, XFCE (like other more full-featured DEs) provides a service that is used to open things (files, URLs, whatever) in a default program. Qtile OTOH doesn't, so you'd need a replacement for this. I think by default it's `xdg-open` but I'm not sure. You might find some useful information on this page: https://wiki.archlinux.org/title/Default_applications

**Comment by mariuszkurek** [comment]
I have `xdg-utils` already installed. Discord triggers `sh xdg-open https://www.google.com/` and fails. However, launching the same command from Sakura works.

**Comment by m-col** [comment]
> Discord triggers sh xdg-open https://www.google.com/ and fails

How did you confirm this? Does it send out any errors?

**Comment by mariuszkurek** [comment]
Fails, as I said in first message, with "Firefox is already running" error. I don't get any Qtile logs and I'm honestly not sure where else to look for any.

**Comment by jwijenbergh** [comment]
Is this Wayland or X11? See https://www.guyrutenberg.com/2020/03/21/xdg-open-fails-when-using-firefox-under-wayland/

**Comment by mariuszkurek** [comment]
X11, so this tip didn't work.

**Comment by mariuszkurek** [comment]
Stopped happening at some point, closing.
