### ISSUE TITLE
Need to implement better text scrolling

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#3445]
### The issue:

This is to remind me that I need to:
* Allow mpris2 widget to keep scrolling
* Implement pixel scrolling

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

Need to revist #2039 and #1927. 

I think pixel scrolling could be a mixin so, in theory, anything can be scrolled. We can think whether it's added to the base `_TextBox` class or whether there's a separate `ScrollingTextBox` class.

**Comment by baudouinth** [comment]
Hello @elParaguayo , I just wanted to thank you for taking the time to implement this. I myself didn't find the time/motivation to finish the work I started on this subject, and I wasn't really used to collaborating on github at this time.

Now that I'm thinking about giving a go at Qtile again, I am so happy to see my idea implemented !

**Comment by elParaguayo** [comment]
It was a vast improvement on the previous method of scrolling so, having seen your idea, I was keen to make sure we included this!
