### ISSUE TITLE
Systray icons properly updating only if alpha is present

### ISSUE THREAD

**Issue by Sonic803** [qtile/qtile#3454]
### The issue:

The issue is the same as #2935 .
The problem is that if i want the color of the background of the icons to not be black i cant use the alpha in the bar background but if i use it the icons will update properly but their background will be transparent.
qtile 0.21.0
picom 9.1-2

### Required:

- [ ] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
This isn't something that can be easily fixed. The issue is flagged in the docs (http://docs.qtile.org/en/stable/manual/ref/widgets.html#systray).

If you want more control over the background, try the `StatusNotifier` widget but, unfortunately, not all apps that provide a tray icon use the StatusNotifier specification.

**Comment by elParaguayo** [comment]
You could take a look at #4126 which adds pseudotransparency to bars and widgets which should help with the rendering of Systaray.

**Comment by Sonic803** [comment]
Wow thanks a lot, now they update properly and can also the alpha works

**Comment by Sonic803** [comment]
The only issue I have is that the alpha is not set for the whole bar right after starting qtile from gdm, i have to manually reload the config to get the full bar with the correct alpha

**Comment by elParaguayo** [comment]
Interesting. I'll see if I can recreate (although I don't use a display manager).

There's a function for screens to force a reload of the transparency so, if nothing else, you could have a function that's hooked to startup that calls this function.

**Comment by Sonic803** [comment]
The problem was that I was setting the wallpaper with an external script that qtile called on startup, by setting it in the Screen constructor works now works perfectly

**Comment by elParaguayo** [comment]
Yes. That's the scenario that I've been thinking about. I can add some better documentation around that.
