### ISSUE TITLE
GroupBox and AGroupBox do not support bold fonts

### ISSUE THREAD

**Issue by mcnuggetsx20** [qtile/qtile#3473]
### The issue:

Whenever the font passed into GroupBox or AGroupBox is bold, it changes to the default font (I think it's the Sans font) in the bold version, instead of the desired one

Here is an image of a GroupBox using Roboto Mono:
![image](https://user-images.githubusercontent.com/71185521/161786068-e59675ab-4d35-4ef3-9446-cf4c7a3d8f64.png)

And here is an image with Roboto Mono Bold passed into the GroupBox:
![image](https://user-images.githubusercontent.com/71185521/161786358-54a45218-b0f2-46ea-aa51-917ffdfecba0.png)

I am also attaching both versions in code:
```py
widget.GroupBox(
    font='Roboto Mono Bold',
    fontsize=15,
    active=gray,
    inactive=gray,
    background=black,
    this_current_screen_border=black,
    this_screen_border=green,
    highlight_method='block',
    block_highlight_text_color=dviolet,

),
```

```py
widget.GroupBox(
    font='Roboto Mono',
    fontsize=15,
    active=gray,
    inactive=gray,
    background=black,
    this_current_screen_border=black,
    this_screen_border=green,
    highlight_method='block',
    block_highlight_text_color=dviolet,

),
```
qtile 0.21.0-1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by SweepingBishops** [comment]
Yeah I checked and get the same issue. This also only happens in GroupBox and AGroupBox. This shows up in bold, oblique and bold oblique fonts.
![2022-04-06_19-52](https://user-images.githubusercontent.com/89494022/161998624-ec6851f5-1949-442c-b0cf-0a725d2c3d7e.png)
The above image shows a GroupBox and two textboxes for reference.

**Comment by elParaguayo** [comment]
Actually, looking at the code for the widget, there is something weird going on there. Let me take a look tonight but, I agree, that line may not be necessary.

**Comment by elParaguayo** [comment]
It's `base._TextBox` that creates the text layouts.

My guess is that the code for setting the font family after the layout has been created is causing the issue but can do some testing later.

**Comment by SweepingBishops** [comment]
Commenting out the next line, the fontsize one, also changes nothing as far as I can tell; you can still change the size. But commenting out the fontcolour line messes up the colouring. All the group lables default to white, no matter what you set.

**Comment by elParaguayo** [comment]
The white colour is hardcoded earlier in the widget's code. Not sure why. Will fix that too.

**Comment by elParaguayo** [comment]
These lines:
``` python
        self.layout.font_family = self.font
        self.layout.font_size = self.fontsize
```
are required because it's possible to change font and size via IPC.

So, I need to fix the underlying issue rather than removing those lines.

**Comment by elParaguayo** [comment]
Is `Roboto Mono Bold` available in other apps e.g. LibreOffice? And I mean, can you select it directly from a drop-down list, rather than selecting `Roboto Mono` and then clicking the bold button?

The font changing code works fine so I'm wondering if you need to use markup to make the font bold here.

**Comment by SweepingBishops** [comment]
![2022-04-07_05-27](https://user-images.githubusercontent.com/89494022/162093906-aa43cb8d-d793-46a2-ae7d-86122ecff9a6.png)
![2022-04-07_05-26](https://user-images.githubusercontent.com/89494022/162093909-b95312c7-da38-42c0-ac05-0b25c1fcf5ff.png)
These are the roboto fonts installed by default in arch linux.
![2022-04-07_05-30](https://user-images.githubusercontent.com/89494022/162093945-112b7de0-3e62-4571-91ff-51498d66e7ca.png)

**Comment by elParaguayo** [comment]
To me, that suggests that you don't have a font called `Roboto Sans Bold`. There are fonts called `Roboto`, `Roboto Medium` etc.

Try running `fc-match "Roboto Sans"` and `fc-match "Roboto Sans Bold"` and see if they give you different fonts.

My guess is, if you want `Roboto Bold` you'd set the font as `Roboto` and use markup via the `fmt` parameter (which now works on latest git) to set the font to be bold.

**Comment by SweepingBishops** [comment]
> To me, that suggests that you don't have a font called `Roboto Sans Bold`. There are fonts called `Roboto`, `Roboto Medium` etc.
> 
> Try running `fc-match "Roboto Sans"` and `fc-match "Roboto Sans Bold"` and see if they give you different fonts.
> 
> My guess is, if you want `Roboto Bold` you'd set the font as `Roboto` and use markup via the `fmt` parameter (which now works on latest git) to set the font to be bold.

I think you are right.
