### ISSUE TITLE
Layout Spiral has inverted next_window and prev_window logic

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3481]
### The issue:

Your Qtile version (qtile --version): `0.21.1.dev9+g634a470a`

* When I use key or mouse binding to change to next or prev window on layout Spiral, it seems to be the only one with inverted logic. `lazy.group.prev_window()` does not go to prev window.
* Also I am not sure if rearranging the windows by minimizing and unminimizing a window that brings it to front does interfere with the window list too. I wish the next_window and prev_window would always follow what the current window order on screen is and not when it was created. Maybe this is another topic.

This behavior is not documented and there seem to be no option to change it, so I believe it is a bug. If not, then this is a request to change the behavior or give me option to invert that logic right in the layout settings, so I don't need to make exceptions everywhere else with `.when(layout='spiral')`. Which does not work with mouse_callbacks anyway I think. I switch between different layouts and this one sticks out with this logic to me, as it is not consistent to all other layouts I tried for longer period of time (5 or so).

Just tried this right now. Created a new terminal window to get qtile version and using next_window() will go back in history to this Firefox window. So clearly it is inverted. Here first my layout settings:

    layout.Spiral(
        border_focus = layout_default['border_focus'],
        border_normal = layout_default['border_normal'],
        border_width = layout_default['border_width'],
        margin = layout_default['margin'],
        clockwise = False,
        # 'after_current', 'before_current', 'top', 'bottom'
        new_client_position = 'top',
        # main_pane_ratio = None,
        main_pane_ratio = 0.47,
        main_pane = 'left',
        # ratio = 0.6180469715698392,
        ratio = 0.42,
        ratio_increment = 0.08,
    ),

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by SweepingBishops** [comment]
I think the definition used here is ```next_window()``` moves focus into the spiral and ```prev_window()``` moves focus outward.

**Comment by thingsiplay** [comment]
So this is seen from someone going from outside to inside. I can see this, but the windows are not created from outside to inside, but from inside to outside. It is growing and the new windows are on its outer side. Therefore I expect the logic to work inverted. 

If this is the intended way, then an option to change it would be helpful.

**Comment by SweepingBishops** [comment]
I see what you mean.
The solution I thought of is this:
```
next_window = lazy.group.prev_window
prev_window = lazy.group.next_window
```
And then
```
Key([mod],'whateverKey', next_window())
Key([mod],'whateverKey2', prev_window())
```

Or you can just forgo all that and just reverse the bindings you use. If you use 'Right' for next and 'Left' for prev, use 'Right' for prev and 'Left' for next.

**Comment by thingsiplay** [comment]
In the keys section I already use mod+j and k with `lazy.layout.up()` and down in general for all layouts and that is how I expect it to work.
But when I use mouse_callbacks on the widget.TaskList I want Button4 and Button5 to `lazy.group.prev_window()`. It works for all windows nice, even for layout.matrix. But then the logic is inverted for only layout.spiral and I can do a .when(layout='spiral'), but can't do whennot to use it with all other layouts.

Example does not work. :
```
mouse_callbacks = {
    'Button4':
    # lazy.group.prev_window(),
    lazy.group.prev_window().when(layout!='spiral'),
    lazy.layout.down().when(layout='spiral'),
    # lazy.layout.down(),
    'Button5':
    # lazy.group.next_window(),
    lazy.group.next_window().when(layout!='spiral'),
    lazy.layout.up().when(layout='spiral'),
    # lazy.layout.up(),
},
```
All of this headache could be solved with a simple option to invert the logic just for layout.spiral.

**Comment by thingsiplay** [comment]
No, new client on bottom changes the way it works completely and does not solve my issue.

**Comment by SweepingBishops** [comment]
I'll try to fix it. Emphasis on _try_. I'm not that experienced.

**Comment by elParaguayo** [comment]
Could be these lines having the wrong logic:
https://github.com/qtile/qtile/blob/634a470a12e787a1a00fe7747059fc6a9de0201c/libqtile/layout/spiral.py#L340-L344

**Comment by thingsiplay** [comment]
I tried to swap the up/down and previous/next in the file "/usr/lib/python3.10/site-packages/libqtile/layout/spiral.py" directly (off course with sudo and making backups). And reload Qtile (even logging out). Either i was confused or it did not work. Was this approach to test this quickly correct? This was tested on my live environment (if done correctly).

**Comment by elParaguayo** [comment]
It was a wild guess at why this layout is giving you weird behaviour.

Let me do some testing.

**Comment by elParaguayo** [comment]
OK. I think I can see the problem. The layout adds windows to the client list. The default behaviour is to add the new window to the top of the list so the client list would be `[window3, window2, window1]`. Doing `prev_window` just takes the previous index but, as the windows are in reverse order here, you will end up picking the windows in order.

If you select `new_client_position="bottom"` then the client list will be `[window1, window2, window3]` and the `prev_window` command should work as expected.

So, we just need to add some logic to handle this.

**Comment by thingsiplay** [comment]
Would it work to reverse the list when adding a window if reverse=True?

**Comment by elParaguayo** [comment]
It depends what you want `prev_window` to do. If you mean it to open the previous window referring to the order you opened the window then, yes, but **only** when `new_client_position` is `top`.

How would propose handling the situation when a client could be added in the middle (e.g. `before_current` or `after_current`)?

**Comment by thingsiplay** [comment]
I am sorry, I deleted my comment just the moment you was replying, as I realized it can't work. For the record, I asked if reverse the list when adding a window would work. Maybe there is more work needed than just a switch.

**Comment by thingsiplay** [comment]
Basically I am happy with the lazy.layout.up() and .down() for layout.Spiral. The functional workaround without changing the source code would be just to write `lazy.layout.up().when(layout='spiral'),` and a default behavior for all other layouts I am using in the mouse_callbacks. It would certainly work and is probably quicker and easier than changing internal code, especially if it is this rooted.

**Comment by SweepingBishops** [comment]
@thingsiplay , you could try writing a function for it.
Something like `{'Button5': lazy.function(my_function_for_button5)}`
```
def my_function_for_button5(qtile):
     if qtile.current_group.layout.name == 'spiral':
        qtile.current_group.cmd_prev_window()
     else:
        qtile.current_group.cmd_next_window()
```

> It depends what you want `prev_window` to do. If you mean it to open the previous window referring to the order you opened the window then, yes, but **only** when `new_client_position` is `top`.
> 
> How would propose handling the situation when a client could be added in the middle (e.g. `before_current` or `after_current`)?

This is not unique to `spiral`. For example in `columns` next is considered to be down the column and columns are ordered left to right, regardless of the whether the new window is above or below.

**Comment by thingsiplay** [comment]
Good idea! I was so focused on solving this problem itself, that I forgot to write a function as I usually do. This simple solution just works. Hopefully this issue did not take too much of your time. Next time I discuss it before doing issues. Thank you.
