### ISSUE TITLE
Scratchpads in fullscreen windows

### ISSUE THREAD

**Issue by milkias17** [qtile/qtile#3482]
### The issue:

I don't know which version specifically started this but since some version, I can't see/toggle scratchpad windows when inside a fullscreen window. Is this intended behavior or a bug? And if it is intended behavior, while I strongly believe that this shouldn't be intended behavior, could you please point me as to what I could do in my config to remedy this issue of mine. 

Qtile version: 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
You're right. It's not intended behaviour!

I'm working on improving layering of windows and this is on the list to fix.

**Comment by milkias17** [comment]
Thank you very much. I would like to say one thing however. I absolutely love the qtile project and I think that what you guys are doing is amazing. And I really cant say this or that as its the dev team thats pouring all this hours into the project. However as a user I feel that the project is too unstable to be usable. It pretty much feels like every release something is bound to break. And when I say break, I don't mean some sort of api change that would cause config breakage. I mean breakage in core functionality. 
I think at this point, the feature set that qtile provides is absolutely huge and more than enough. Therefore I think being a bit restrictive on new features and working on maintaining the codebase would benefit the end user more.

Again this is just my suggestion and opinion. I have had so much frustration about this issue in the project and I just thought I should share this.

**Comment by m-col** [comment]
> I think at this point, the feature set that qtile provides is absolutely huge and more than enough. Therefore I think being a bit restrictive on new features and working on maintaining the codebase would benefit the end user more.

100% agree, and your complaint is completely understandable. In general we don't really want new features, except maybe improvements to the widgets or layouts as they are fully isolated. Any more significant features we generally direct to the qtile-examples repo as a plugin.

There have been many core bugs in the past couple years introduced as a result of refactorings or other big changes to the core code, this issue being one of them. Unfortunately those changes were necessary to fix other bugs, so occasionally we rethink how we handle some functionality (like the fullscreening, in this case) and some bug falls through the cracks. The silver lining is that every time we do so (and indeed pretty much every time we fix a bug) we add even more tests to ensure it won't break again. So generally we reduce the number of bugs, occasionally we swap a bug for a different bug (like here), but with each change qtile's code becomes less likely to get future bugs (that's the hope, anyway). So apologies, it's a valid complaint, and all I can say is bear with us.

**Comment by SweepingBishops** [comment]
> Thank you very much. I would like to say one thing however. I absolutely love the qtile project and I think that what you guys are doing is amazing. And I really cant say this or that as its the dev team thats pouring all this hours into the project. However as a user I feel that the project is too unstable to be usable. It pretty much feels like every release something is bound to break. And when I say break, I don't mean some sort of api change that would cause config breakage. I mean breakage in core functionality. I think at this point, the feature set that qtile provides is absolutely huge and more than enough. Therefore I think being a bit restrictive on new features and working on maintaining the codebase would benefit the end user more.
> 
> Again this is just my suggestion and opinion. I have had so much frustration about this issue in the project and I just thought I should share this.

I too agree. But I also think that the part of qtile that holds it back is it's docs. We have very extensive docs on some topics, and very unclear ones on others. 
For example #3488 #3484

**Comment by elParaguayo** [comment]
If there are gaps in the docs, we're very happy to review pull requests... :wink:

**Comment by elParaguayo** [comment]
Going back to the original issue, it looks like this commit (c8437b1bb) broke the behaviour. It's not clear why that would have caused any issue.

However, I would add that stacking was never really properly handled (and still isn't). There's a PR in the works that should hopefully fix the issue being seen here and give users more control over stacking of individual windows.

**Comment by fdev31** [comment]
I have some similar issue, scratchpads will open below any fullscreen window.
Calling `cmd_bring_to_front()` later may fix the order even though the show() method seems to execute similar code.

**Comment by fdev31** [comment]
Was there some parallel activity regarding this bug ?

**Comment by elParaguayo** [comment]
I'm back working on the layering PR as we really need to get that sorted.
