### ISSUE TITLE
fmt key better documentation?

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3488]
### The issue:

I can't find anything in the documentation on how to format the float output of the OpenWeather widget. I tried searching for `fmt` everywhere but it's just `("fmt", "{}", "How to format the text")` .

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
It's nothing to do with `fmt`. That's an overall wrapper for the final string. Typically, you'd leave it alone but you can add markup.

You actually want to edit `format` instead. Let's say your format string is `format='{location_city}: {temp}` you could try changing this to `format='{location_city}: {temp:.0f}` to remove the decimal point.

**Comment by ervinpopescu** [comment]
Thanks a lot. I'd appreciate some more documentation on fmt tho :)

**Comment by SweepingBishops** [comment]
> Thanks a lot. I'd appreciate some more documentation on fmt tho :)

I agree, but what would be a better description for it? Also, adding an example to it would probably make it way clearer.

**Comment by ervinpopescu** [comment]
> > Thanks a lot. I'd appreciate some more documentation on fmt tho :)
> 
> I agree, but what would be a better description for it? Also, adding an example to it would probably make it way clearer.

If I knew what fmt does, I would submit a PR, not write an issue :)

**Comment by elParaguayo** [comment]
OK, I'll explain:

Widgets that display text typically inherit `base._TextBox` directly, or indirectly.

`base_TextBox` has a property called `formatted_text` which takes the text and basically does `self.fmt.format(text)`.

The output of this property is what is displayed in the widget.

So, if you're using, say, the `OpenWeather` widget and have it set up to show the temperature, leaving `fmt` as `{}` will make no difference to the output. However, if you set `fmt` to `The temperature is: {}` your widget will fill the curly brackets with the temperature.

`fmt` is therefore a way to add additional text, prefixes, markup etc to text based widget. It's particularly useful on those widgets where you can't edit the text. Take `CurrentScreen` for instance. That widget, by default, just shows the number of the screen. If you set `fmt` to `Current screen: {}` you now get that additional text in front of the screen number.

This allows you to add extra text to the widget without needing to use a separate `TextBox` widget to add more text.

**Comment by SweepingBishops** [comment]
How is this different from the `format` property used by widgets like battery.

**Comment by elParaguayo** [comment]
Not every text widget has a `format` parameter (eg my example of `CurrentScreen`) in which case this is the only way to add extra text.

`fmt` is part of `base._TextBox` so *every* text widget inherits this. But, yes, if a widget *also* provides `format` then there's no real need to use `fmt` which is the point I made near the beginning of this thread.

**Comment by SweepingBishops** [comment]
So then why do we even have `format`?

**Comment by elParaguayo** [comment]
Because it's *final* step for formatting text. It is separate to the *contents* of the widget which each widget defines separately.

**Comment by SweepingBishops** [comment]
Oh, yeah I understand. Thanks again!

**Comment by ervinpopescu** [comment]
Thank you, @elParaguayo!

**Comment by m-col** [comment]
While it looks like the confusion here has been resolved, it was a result of the poor documentation (the original issue), so perhaps that should still be addressed? Particularly the disinction between `fmt` and `format` for those widgets that have both.

**Comment by ervinpopescu** [comment]
Shall i reopen this?

**Comment by m-col** [comment]
It's OK, I have. I'm wondering how best to document this. Perhaps as @SweepingBishops says just an example, a note somewhere on the widget page explicitly mentioning both, using for instance the examples @elParaguayo gave. What do you think?

**Comment by elParaguayo** [comment]
This line could be clearer:
https://github.com/qtile/qtile/blob/634a470a12e787a1a00fe7747059fc6a9de0201c/libqtile/widget/base.py#L389

And then we need something in the docs - maybe we add something about configuring widgets in the [Configuration](http://docs.qtile.org/en/stable/manual/config/index.html) page e.g. after `Screens` where we mention the `Bar`.

**Comment by elParaguayo** [comment]
Maybe I should pick this one up...
