### ISSUE TITLE
custom_icon_path not working for widget.CurrentLayoutIcon

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3489]
### The issue:

For some reason the custom icon path for widget.CurrentLayoutIcon does not work for me. For testing I have copied the original icons from libqtile/resources/layout-icons to my .config/qtile folder and changed a color for one of the icons. 

- Your Qtile version (qtile --version): `0.21.1.dev9+g634a470a`
- Relevant logs from ~/.local/share/qtile/qtile.log: --- (nothing relevant is reported)
- If relevant, the problematic part of your config:

            widget.CurrentLayoutIcon(
                custom_icon_path = ['/home/tuncay/.config/qtile/layout-icons'],
                scale = 0.55,
                mouse_callbacks = {
                    'Button1':
                    lazy.next_layout(),
                    'Button2':
                    lazy.to_layout_index(0),
                    'Button3':
                    lazy.prev_layout(),
                },
            ),

Whatever I do, reload, restart or even logout/login as a user; it won't use the icons. I have tried to save the .png in RGB and also tried in Indexed color mode. Am I missing here something or is this a bug? 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Let me test later and see if I can recreate the issue.

**Comment by SweepingBishops** [comment]
Placing icons in ~/.icons or in ~/.local/share/icons works as expected.

**Comment by SweepingBishops** [comment]
Can you doublecheck if the filenames are correct? `layout-{layout_name}.png`

**Comment by thingsiplay** [comment]
Yes correct filenames, I copied the original files from libqtile. I also tested placing the icons in those standard icons folders; without luck.
WAIT!
placing the icons directly without subfolders in "~/.icons" work. So it works, just the custom path does not work for me. Here another test: `custom_icon_path = ['/home/tuncay/.icons/layout-icons'],` And the listing of files:

```
$ find $(readlink -e .) 
/home/tuncay/.icons/layout-icons
/home/tuncay/.icons/layout-icons/layout-matrix.png
/home/tuncay/.icons/layout-icons/layout-ratiotile.png
/home/tuncay/.icons/layout-icons/layout-wmii.png
/home/tuncay/.icons/layout-icons/layout-treetab.png
/home/tuncay/.icons/layout-icons/layout-stack.png
/home/tuncay/.icons/layout-icons/layout-zoomy.png
/home/tuncay/.icons/layout-icons/layout-spiral.png
/home/tuncay/.icons/layout-icons/layout-monadtall.png
/home/tuncay/.icons/layout-icons/layout-monadthreecol.png
/home/tuncay/.icons/layout-icons/layout-monadwide.png
/home/tuncay/.icons/layout-icons/layout-max.png
/home/tuncay/.icons/layout-icons/layout-tile.png
/home/tuncay/.icons/layout-icons/layout-columns.png
/home/tuncay/.icons/layout-icons/layout-floating.png
/home/tuncay/.icons/layout-icons/layout-verticaltile.png
/home/tuncay/.icons/layout-icons/layout-unknown.png
/home/tuncay/.icons/layout-icons/layout-slice.png
/home/tuncay/.icons/layout-icons/layout-bsp.png
/home/tuncay/.icons/layout-icons/layout-recolor.xcf
```

**Comment by SweepingBishops** [comment]
Ah. Symlinks won't work.

**Comment by thingsiplay** [comment]
I don't use a symlink for this. I just did a readlink to make the path fullpath for the listing here.

**Comment by elParaguayo** [comment]
Putting something in `~/.icons` works as that's a default folder that gets checked.

The custom folders should be checked and I can see the code is there to do so.

Am just seeing if I can recreate now.

**Comment by thingsiplay** [comment]
To test easily put https://imgur.com/a/xihstBF into "~/.icons". It will show the icon. Now create a subfolder there and move the file into it, in example "~/.icons/qtile". And use custom path `custom_icon_path = ['/home/tuncay/.icons/qtile'],`. Off course with your home directory.

**Comment by elParaguayo** [comment]
Yup. Can recreate. It's not adding the custom path for some reason.

**Comment by elParaguayo** [comment]
Scratch that. It's an error in your config. It's `custom_icon_paths` not `custom_icon_path`!

**Comment by thingsiplay** [comment]
Omg! I am so sorry, you are right. Can't believe it. So with the "s" added it works. Sorry for taking your time. I'll close shortly if no one says anything.

**Comment by SweepingBishops** [comment]
> Scratch that. It's an error in your config. It's `custom_icon_paths` not `custom_icon_path`!

😅

**Comment by elParaguayo** [comment]
> Omg! I am so sorry, you are right. Can't believe it. So with the "s" added it works. Sorry for taking your time. I'll close shortly if no one says anything.

Don't worry about it!
