### ISSUE TITLE
Errno 2 : hook Qtile not work, because not detect "autostart.sh"

### ISSUE THREAD

**Issue by Angelitoo09** [qtile/qtile#3492]
### The issue:

Hi, I working for make my Qtile configuration and my hook not work, The code in config.py is this :

```
import os
import subprocess

from libqtile import hook
from libqtile.log_utils import logger

@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~')
    subprocess.call([home + '/.config/qtile/autostart.sh'])
    logger.warning("In autostart function")
```
And in the autostart.sh is :

```
#!/bin/shs

setxkbmap es &
volumeicon &
ccbatt &
```
For finish I make `chmod +x .config/qtile/autostart.sh` and don't work, in the log there are this :

`
FileNotFoundError: [Errno 2] No existe el fichero o el directorio: '/home/angel/.config/qtile/autostart.sh'
`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
`.config/qtile/autostart.sh` (as per your chmod command) is not the same as `~/.config/qtile/autostart.sh`.

Can you show the output of `ls -l ~/.config/qtile`.

**Comment by Angelitoo09** [comment]
@elParaguayo The output is :

```
total 20
-rwxr-xr-x 1 angel users   48 abr 10 10:41 autostart.sh
-rw-r--r-- 1 angel users 8712 abr 10 10:41 config.py
drwxr-xr-x 2 angel users 4096 abr 10 10:42 __pycache__
```

**Comment by SweepingBishops** [comment]
This 
>#!/bin/shs

should be
>#!/bin/sh

I don't know why it is giving the `FileNotFoundError` when it is not.

**Comment by Angelitoo09** [comment]
Ok I looked my Qtile version, the version of my qtile is 0.21.0, I'm looking in the Internet and I make 'chmod +777 .config/qtile' but not work. I need reinstall Qtile?

**Comment by elParaguayo** [comment]
No. Did you try the fix in SweepingBishops' comment?

> This
> 
> > #!/bin/shs
> 
> should be
> 
> > #!/bin/sh
> 
> I don't know why it is giving the `FileNotFoundError` when it is not.

**Comment by Angelitoo09** [comment]
Ok, I change `#!/bin/shs` to `#!/bin/sh` and now works, thanks @elParaguayo for help me in this problem :-)
