### ISSUE TITLE
Workspaces not alternating between the last and the current workspace when the mod+[workspace key] is pressed twice

### ISSUE THREAD

**Issue by prateekamana** [qtile/qtile#3496]
### The issue:

Qtile version : 0.21.0
I am on Debian 11, in my old laptop, if I go from workspace 1 to workspace 2, and then again try to go to workspace 2 by pressing mod + [workspace 2 key], then I am thrown to workspace 1 as that was the previous workspace that I was at (it alternates).
This isn't happening with my current install of Qtile, is there anyway I can turn that back on?
(I am using the same Qtile config as the previous install of my Qtile)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by SweepingBishops** [comment]
>is there anyway I can turn that back on?

`lazy.screen.toggle_group()`
>I am on Debian 11, in my old laptop, if I go from workspace 1 to workspace 2, and then again try to go to workspace 2 by pressing mod + [workspace 2 key], then I am thrown to workspace 1 as that was the previous workspace that I was at (it alternates).

I don't think that's supposed to happen. Can you show that part of your config?

**Comment by elParaguayo** [comment]
Change:
``` python
lazy.group[i.name].toscreen(),
```
to
``` python
lazy.group[i.name].toscreen(toggle=True),
```

**Comment by prateekamana** [comment]
@elParaguayo that worked
@SweepingBishops 
I didn't have `lazy.screen.toggle_group()` anywhere in my config, neither did I have toggle=true in the .toscreen() function, somehow it was working without it previously, I wonder if it defaulted to true previously?
Thanks ❤️
