### ISSUE TITLE
DropDown does not always float to top by default.

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3505]
### The issue:

When watching some videos in fullscreen or when any window is fullscreen, `DropDown`s appear in the background and I have to make them float manually to the top with
```
@lazy.function
def float_to_front(qtile):
    """
        Make all floating windows to float lazily
        to the front on a key stroke.
    """
    for group in qtile.groups:
        for window in group.windows:
            if window.floating:
                window.cmd_bring_to_front()
```
I think having any `DropDown` float on top of everything would make more sense, as they always disappear when focus is lost.
Is this a bug or is there a way to have all and only `DropDown`s float on top of everything ?.

**version**:
```
> qtile --version
0.21.0
```
**log**: nothing to see in `~/.local/share/qtile/qtile.log`
**my scratchpad config**: https://github.com/a2n-s/dotfiles/blob/main/.config/qtile/groups.py#L46

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Looks like a duplicate of #3482.

**Comment by a2n-s** [comment]
Oh really sorry...
Don't understand the github search engine for issues :sweat: 

So, the idea is to wait for the PR that adresses https://github.com/qtile/qtile/commit/c8437b1bb26d036ac7682a3e9aaac38398b4ebdc ?

**Comment by elParaguayo** [comment]
Yes.

**Comment by a2n-s** [comment]
Gotcha !
Thanks :yum:
