### ISSUE TITLE
Qtile displaying as a DE, rather than a WM

### ISSUE THREAD

**Issue by Charged5770** [qtile/qtile#3520]
### The issue:

Hi I think I have found a bug with the name of how the name of my DE/WM shows. When I run neofetch or screenfetch, It shows my DE being Qtile and my WM being LG3D. I'm just wondering if it's supposed to be like that...

Screenshots:
![image](https://user-images.githubusercontent.com/85625727/164993063-79869bd4-a77b-4cc6-9c8c-ba2e1b906213.png)
![image](https://user-images.githubusercontent.com/85625727/164993086-144ac363-0bfb-4e5f-9755-e15eb974c18e.png)

Notice how Qtile is a DE, not a WM.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
If you check out the last section of the default config, there is a bit of an explanation as to why this is happening and how you can change it. I'll paste it here so you can see:
```py
# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"
```
If you change `wmname` to `"qtile"` you'll see what you expect in those fetches.

As for the DE/WM thing, you'll have to refer to the docs of the specific fetch tool. I'm not sure how they are determining what is what for those.

**Comment by Charged5770** [comment]
@m-col thanks, I changed `wmname` to to `"qtile"` and it looks normal.

**Comment by elParaguayo** [comment]
Sounds like this is resolved so closing.
