### ISSUE TITLE
Qtile Git root install error

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3531]
### The issue:

I want to install qtile git with pip install and it gives me the following error

 

> Processing /home/cr1ogen/Git/qtile
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Failed to find pywlroots. Wayland backend libinput configuration will be unavailable.
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164
, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 102, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /home/cr1ogen/Git/qtile.
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Above tells me that it can't find pywlroots, but if I type `pip list` it shows
`pywlroots 0.15.13`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by SweepingBishops** [comment]
What are the commands you ran to install qtile?

**Comment by cr1ogen** [comment]
> What are the commands you ran to install qtile?

`pip install .`

**Comment by SweepingBishops** [comment]
Recheck if you have all the dependencies installed.
Try doing it without sudo privileges.
(You're using Wayland right? Also, what distro are you using?)

**Comment by cr1ogen** [comment]
Thank you!  I am using Debian running qtile on wayland.  The dependencies are installed, actually qtile is working on my pc, what it won't let me do is update it to the latest dev version

**Comment by SweepingBishops** [comment]
> Thank you!  I am using Debian running qtile on wayland.  The dependencies are installed, actually qtile is working on my pc, what it won't let me do is update it to the latest dev version

Did you try pip without sudo?

**Comment by cr1ogen** [comment]
I tried to install qtile without sudo, but since the old version is installed with sudo, it won't let me uninstall it.  I also don't dare to uninstall it with sudo because I'm afraid that I won't be able to install qtile again

**Comment by elParaguayo** [comment]
Is that folder a clone from github?

What happens if you run `git tag`, `git status` and `git describe`? (Shamelessly copying ideas from another similar issue...)

**Comment by cr1ogen** [comment]
git tag:
v0.1
v0.10.0
v0.10.1
v0.10.2
v0.10.3
v0.10.4
v0.10.5
v0.10.6
v0.10.7
v0.11.0
v0.11.1
v0.12.0
v0.13.0
v0.14.0
v0.14.1
v0.14.2
v0.15.0
v0.15.1
v0.16.0
v0.16.1
v0.17.0
v0.18.0
v0.18.1
v0.19.0
v0.20.0
v0.21.0
v0.5
v0.6
v0.7.0
v0.8.0
v0.9.0
v0.9.1

**Comment by cr1ogen** [comment]
git status
En la rama master
Tu rama está actualizada con 'origin/master'.

nada para hacer commit, el árbol de trabajo está limpio

**Comment by elParaguayo** [comment]
OK. Was it cloned when you ran `pip install .` or did you just clone it before running those commands?

**Comment by cr1ogen** [comment]
> OK. Was it cloned when you ran `pip install .` or did you just clone it before running those commands?
> 

I clone the repo and then make pip install . 
And for to update qtile I make a git pull and then pip install .

**Comment by elParaguayo** [comment]
Hmm. That's odd.

As far as I understand it, the installer tries to get info from the git repo. The commands show that that info is available so I'm not sure what's going on.

I'll try to recreate this later.

**Comment by cr1ogen** [comment]
> Hmm. That's odd.
> 
> As far as I understand it, the installer tries to get info from the git repo. The commands show that that info is available so I'm not sure what's going on.
> 
> I'll try to recreate this later.

Thank you!!

**Comment by elParaguayo** [comment]
Can't recreate this. Builds fine for me:
```
╰─❯ pip install .
Processing /home/elp/github/qtile-dev/qtile
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting xcffib>=0.10.1
  Using cached xcffib-0.11.1-py3-none-any.whl
Collecting cairocffi[xcb]>=0.9.0
  Using cached cairocffi-1.3.0-py3-none-any.whl
Collecting cffi>=1.1.0
  Using cached cffi-1.15.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: qtile
  Building wheel for qtile (pyproject.toml) ... done
  Created wheel for qtile: filename=qtile-0.21.1.dev16+g29b0f0d4-cp310-cp310-linux_x86_64.whl size=538922 sha256=73b303c34aebad62b8675a86ef627750bc0b6ff881fcb8690f8f200af823b9f4
  Stored in directory: /tmp/pip-ephem-wheel-cache-4499kvge/wheels/7e/61/20/a49319baf2eced5f9ff1acb41d95f9bdb1133f904678bb5ea8
Successfully built qtile
Installing collected packages: six, pycparser, cffi, xcffib, cairocffi, qtile
Successfully installed cairocffi-1.3.0 cffi-1.15.0 pycparser-2.21 qtile-0.21.1.dev16+g29b0f0d4 six-1.16.0 xcffib-0.11.1
```

**Comment by cr1ogen** [comment]
> Can't recreate this. Builds fine for me:
> 
> ```
> ╰─❯ pip install .
> Processing /home/elp/github/qtile-dev/qtile
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting xcffib>=0.10.1
>   Using cached xcffib-0.11.1-py3-none-any.whl
> Collecting cairocffi[xcb]>=0.9.0
>   Using cached cairocffi-1.3.0-py3-none-any.whl
> Collecting cffi>=1.1.0
>   Using cached cffi-1.15.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
> Collecting pycparser
>   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
> Collecting six
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Building wheels for collected packages: qtile
>   Building wheel for qtile (pyproject.toml) ... done
>   Created wheel for qtile: filename=qtile-0.21.1.dev16+g29b0f0d4-cp310-cp310-linux_x86_64.whl size=538922 sha256=73b303c34aebad62b8675a86ef627750bc0b6ff881fcb8690f8f200af823b9f4
>   Stored in directory: /tmp/pip-ephem-wheel-cache-4499kvge/wheels/7e/61/20/a49319baf2eced5f9ff1acb41d95f9bdb1133f904678bb5ea8
> Successfully built qtile
> Installing collected packages: six, pycparser, cffi, xcffib, cairocffi, qtile
> Successfully installed cairocffi-1.3.0 cffi-1.15.0 pycparser-2.21 qtile-0.21.1.dev16+g29b0f0d4 six-1.16.0 xcffib-0.11.1
> ```

Ok. is weird qtile stable 0.21.0 i can installed it (via sudo pip install qtile)

**Comment by euglevi** [comment]
I got the same error. Weird that it works with the stable version and if one wants to install without "sudo". But with `sudo pip install .`, appararently, it cannot find the pywlroots module.

**Comment by elParaguayo** [comment]
Was `pywlroots` also installed with sudo?

**Comment by euglevi** [comment]
Yes, it was in my case.

**Comment by cr1ogen** [comment]
qtile without root install fine

**Comment by cr1ogen** [comment]
> I got the same error. Weird that it works with the stable version and if one wants to install without "sudo". But with `sudo pip install .`, appararently, it cannot find the pywlroots module.

Without root it can be installed, although the error that it cannot find pywlroots appears the same

**Comment by m-col** [comment]
FWIW `pip install .` only installs dependencies for the X backend, not the Wayland backend. Wayland deps need to be installed separately. IIRC pip supports sets of dependencies that be installed alternatively by a syntax like `pip install qtile[wayland]`, that might be worth looking into.

> Without root it can be installed, although the error that it cannot find pywlroots appears the same

idk the details of `pip list` but if you just start a python repl, can you import pywlroots there? It might be useful to then see where it is installed, which can be found like:
```
>>> import wlroots
>>> help(wlroots)
```

**Comment by cr1ogen** [comment]
Help on package wlroots:

NAME
    wlroots - # Copyright (c) Sean Vig 2018

PACKAGE CONTENTS
    _build
    _ffi
    allocator
    backend
    ffi_build
    helper
    renderer
    util (package)
    version
    wlr_types (package)
    xwayland

SUBMODULES
    lib

CLASSES
    builtins.object
        Ptr
            PtrHasData
    
    class Ptr(builtins.object)
     |  Add equality checks for objects holding the same cdata
     |  
     |  Objects that reference the same cdata objects will be treated as equal.
     |  Note that these objects will still have a different hash such that they
     |  should not collide in a set or dictionary.
     |  
     |  Methods defined here:
     |  
     |  __eq__(self, other) -> 'bool'
     |      Return true if the other object holds the same cdata
     |  
     |  __hash__(self) -> 'int'
     |      Use the hash from `object`, which is unique per object
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
     |  
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |  
     |  __annotations__ = {'_ptr': 'ffi.CData'}
    
    class PtrHasData(Ptr)
Add methods to get and set the void *data member on the wrapped struct. The value
     |  stored can be of any Python type.
     |  
     |  Method resolution order:
     |      PtrHasData
     |      Ptr
     |      builtins.object
     |  
     |  Data descriptors defined here:
     |  
     |  data
     |      Return any data that has been stored on the object
     |  
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |  
     |  __annotations__ = {}
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from Ptr:
     |  
     |  __eq__(self, other) -> 'bool'
     |      Return true if the other object holds the same cdata
     |  
     |  __hash__(self) -> 'int'
     |      Use the hash from `object`, which is unique per object
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from Ptr:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
FUNCTIONS
    str_or_none(member: 'ffi.CData') -> 'str | None'
        Helper function to check struct members for ffi.NULL, returning None, or a char
        array, returning a string.

DATA
    Any = typing.Any
        Special type indicating an unconstrained type.
        
        - Any is compatible with every type.
        - Any assumed to have all methods.
        - All values assumed to be instances of Any.
        
        Note that all the above statements are true from the point of view of
        static type checkers. At runtime, Any should not be used with instance
        or class checks.
    
    __wlroots_version__ = '0.15.1'
    annotations = _Feature((3, 7, 0, 'beta', 1), (3, 11, 0, 'alpha', 0), 1...
    ffi = <_cffi_backend.FFI object>

VERSION
    0.15.13

FILE
    /usr/local/lib/python3.10/dist-packages/wlroots/__init__.py

**Comment by m-col** [comment]
So it's installed into `/usr/local/lib/python3.10`. I guess this is where `sudo pip install` puts things. But if you can import it as a user, then what's different about importing it manually vs importing it during qtile's startup?

**Comment by cr1ogen** [comment]
If i try install with `sudo ./setup.py install` (How do I install qtile-extras from El Paraguayo, which I install with sudo)

Failed to find pulseaudio headers. PulseVolume widget will be unavailable
Built with support for XWayland helpers.
Traceback (most recent call last):
  File "/home/cr1ogen/Git/qtile/./setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
    ep(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/cr1ogen/Git/qtile.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

**Comment by m-col** [comment]
This might be useful for that error: https://github.com/pypa/setuptools_scm/issues/697

**Comment by cr1ogen** [comment]
> This might be useful for that error: https://github.com/pypa/setuptools_scm/issues/697

Thank you, but i try these but don't work. I have the .git folder when clone the repo

**Comment by cr1ogen** [comment]
Hello! What I tried for what it's worth was to clone the qtile repository with sudo `sudo git clone` and then I was able to install qtile with `sudo install .`

**Comment by m-col** [comment]
If that works and is what you want, then that's great. Does it all run as you expected, or are there still issues with the wayland dependencies?

**Comment by elParaguayo** [comment]
Using `sudo` to clone does not feel right.

**Comment by cr1ogen** [comment]
> If that works and is what you want, then that's great. Does it all run as you expected, or are there still issues with the wayland dependencies?

In this way I don't have the problem of dependencies, if I install qtile as common user neither. I don't know what is causing this error since I can safely use qtile in wayland

**Comment by cr1ogen** [comment]
> Using `sudo` to clone does not feel right.

Yes, I know. Try to install it like this, to have one more alternative to discover the installation problem. Install qtile as normal user
I also like to live on the edge!
