### ISSUE TITLE
Libinput configuration with qtile

### ISSUE THREAD

**Issue by JoaoDDuarte** [qtile/qtile#3534]
### The issue:

Hi,
I am trying to configure my touchpad in the following way:

```python
from libqtile.log_utils import logger

try:
    from libqtile.backend.wayland import InputConfig

    wl_input_rules = {"type:pointer": InputConfig(tap=True), "type:touchpad": InputConfig(tap=True)}
    logger.warning("worked!")
except ImportError as e:
    logger.exception(e)
    wl_input_rules = None
```
However, when I look at the qtile log, I get the following:

```
2022-04-29 23:24:56,761 WARNING libqtile wayland.py:<module>():L7 worked!
2022-04-29 23:24:57,783 ERROR libqtile hook.py:fire():L391 Error in hook startup_complete
Traceback (most recent call last):
  File "/home/joao/.local/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/home/joao/.local/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 668, in _configure_pending_inputs
    inputs.configure_device(device, self.qtile.config.wl_input_rules)
  File "/home/joao/.local/lib/python3.10/site-packages/libqtile/backend/wayland/inputs.py", line 335,in configure_device
    if handle and libinput.libinput_device_config_tap_get_finger_count(handle) > 0:
AttributeError: 'NoneType' object has no attribute 'libinput_device_config_tap_get_finger_count'
```

I am not quite sure why this is happening, considering that the wl_input_rules are in fact being correctly set.

A sample of my libinput list-devices:
```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event15
Group:            8
Seat:             seat0, default
Size:             100x68mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Accel profiles:   flat *adaptive
Rotation:         n/a
```

I am using the latest dev version of qtile straight from github.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Have you run the `./scripts/ffibuild` script? I think that'll fix it. There should be a log message to inform the user of this but currently there isn't one.

**Comment by JoaoDDuarte** [comment]
I have and then reinstalled qtile but the issue persists - I will redo it again and post an update

**Comment by JoaoDDuarte** [comment]
Apologies, I misread the log output, it solved the issue but I still do not have the tap to click - is this still to be implemented?

**Comment by m-col** [comment]
The error you posted will be cleaned up by https://github.com/qtile/qtile/issues/3534, instead resulting in a more informative logged message rather than raising an exception.

Odd that you'd get it again. You haven't accidentally installed two copies of qtile alongside each other, one which works and one which doesn't?

**Comment by JoaoDDuarte** [comment]
I don't have two copies, the error still persists, but I'll wait for the more informative logs to see if I can narrow down the issue myself!

**Comment by m-col** [comment]
Oops I linked this issue itself, not the PR. The is https://github.com/qtile/qtile/pull/3539. It's merged now - could you try it out and confirm the error is no more?

**Comment by Sydiepus** [comment]
I can confirm the error is no more and the user is informed.
```
2022-05-22 11:54:00,591 ERROR libqtile inputs.py:_configure_pointer():L251 Qtile was not built with libinput configuration support. For support, pywlroots must be installed at build time.
```

**Comment by m-col** [comment]
Thanks.
