### ISSUE TITLE
Systray widget crashed

### ISSUE THREAD

**Issue by kovasap** [qtile/qtile#3550]
### The issue:

I see the following error when running qtile with multiple monitors:

```
2022-05-03 12:40:58,353 ERROR libqtile bar.py:_configure_widget():L350 Systray widget crashed during _configure with error: ConfigError('Only one Systray can be used.')
```

This is a new issue that started for me a couple months ago after updating.

Here is a relevant section of my config:

```python
num_monitors = get_num_monitors()

bars = [bar.Bar(get_widgets(), **bar_config)]
screens = [Screen(top=bars[0])]

if num_monitors > 1:
  for m in range(num_monitors - 1):
    bars.append(bar.Bar(get_widgets(), **bar_config))
    screens.append(Screen(top=bars[-1]))
```

My entire config is at https://github.com/kovasap/dotfiles/blob/master/.config/qtile/config.py.

I see this issue has been raised recently in https://github.com/qtile/qtile/issues/3341 and https://github.com/qtile/qtile/issues/3260.  It looks like both of these issues were fixed with PRs, but on the latest git qtile version I still have this problem.  Any ideas what might be going wrong?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Have you got more than one `Systray` widget?

**Comment by kovasap** [comment]
Yeah I think that is my problem.  So does that mean I need to choose which monitor has my systray?  What's the canonical way to do this in qtile?

**Comment by elParaguayo** [comment]
There's no real set way to do it as people configure multiple monitors in different ways so just go with whatever's easiest for you.

**Comment by kovasap** [comment]
Sounds good, updated my config (for future readers see my dotfiles repo link).
