### ISSUE TITLE
feh does not do anything inside a key binding.

### ISSUE THREAD

**Issue by a2n-s** [qtile/qtile#3553]
### The issue:

Here is a very subtle one I think :yum: 

**What I wanted to do**:
I have some wallpapers installed inside `/usr/share/backgrounds` as arch packages, e.g. my personnal wallpapers ([here](https://github.com/a2n-s/wallpapers/blob/main/PKGBUILD) is the PKGBUILD for this) inside `a2n-s-wallpapers`, some arco and arch related wallpapers inside `archlinux`, etc, etc... 
In a terminal or in the `autostart` script for `qtile`, I run `feh --randomize /usr/share/backgrounds/* --bg-fill`.
I wanted to do the same thing inside a key binding.

**What happened**:
Nothing happened :thinking: 
I get no log at all and the wallpapers do not change.

**What I expected**:
I expected the wallpapers of my monitors to change to random wallpapers from any of the subdirectories inside `/usr/share/backgrounds`, as it works perfectly this way from both the terminal and when restarting `qtile` and thus running the `autostart.sh` hook.

I think this is stange and has something to do with the "*" used in the command, e.g. running `feh --bg-fill --randomize /usr/share/backgrounds/a2n-s-wallpapers/0001_city-grey-paint.jpg` (a wallpaper that exists on my machine) works from a key binding.

**the version of Qtile running**:
```
> qtile --version
0.21.0
```

**the logs**:
absolutely nothing mentioning `feh` and nothing at the same moment the key binding is launched.
I think the command is ran though, because changing `feh` to `fe` results in
```
2022-05-07 19:11:05,117 ERROR libqtile manager.py:cmd_spawn():L1143 couldn't find `fe`
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
I suspect it's the shell that's calling it. If you pass `shell=True` to your `lazy.spawn` call (which I'm assuming you're using - if not, please post how you're doing it), does that fix it?

If it doesn't then a bit more work might be needed to expand it, such as running the * through `glob.glob` to get a list of paths and passing that in to the feh call.

**Comment by a2n-s** [comment]
Perfect, it looks like it's working just fine :star_struck: 

I added the `shell=True` argument to all my `lazy.spawn` calls, as I use a wrapper function to `lazy.spawn` commands and avoid mistakes and breaking the config too often.
It looks like it does not break the previous `lazy.spawn` calls :ok_hand:

**Comment by m-col** [comment]
Awesome
