### ISSUE TITLE
gen-keybinding-img

### ISSUE THREAD

**Issue by RAprogramm** [qtile/qtile#3567]
### The issue:

`qtile -v`
0.21.0
`python scripts/gen-keybinding-img -c /home/user/.config/qtile/config.py -o /home/user/Pictures/`
Traceback (most recent call last):
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 429, in <module>
    f.render(output_file)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 192, in render
    self.draw_button(context, i.key, i.x, i.y, i.width, i.height)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 243, in draw_button
    self.show_multiline(context, x + COMMAND_X, y + COMMAND_Y, k)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 268, in show_multiline
    words = key.command.split(' ')
AttributeError: 'tuple' object has no attribute 'split'
`qtile check`
checking qtile config file /home/user/.config/qtile/config.py
libqtile/core/loop.py:68: error: Unused "type: ignore" comment
Found 1 error in 1 file (checked 1 source file)
config file type checking failed: Command '['mypy', '/tmp/tmpnkag4lua/config.py']' returned non-zero exit status 1.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by RAprogramm** [comment]
`import os
import subprocess

from libqtile import bar, hook, layout, widget
from libqtile.config import EzClick, EzDrag, EzKey, Group, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal


@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser("~/.config/qtile/autostart.sh")
    subprocess.run([home])


@hook.subscribe.client_new
def floating_dialogs(window):
    dialog = window.window.get_wm_type() == "dialog"
    transient = window.window.get_wm_transient_for()
    if dialog or transient:
        window.floating = True


terminal = guess_terminal()
home = os.path.expanduser("~")

keys = [
    EzKey(k[0], *k[1:], desc=k[2:])
    for k in [
        ("M-C-r", lazy.reload_config()),
        ("M-t", lazy.spawn(terminal), "Open Terminal"),
        ("M-c", lazy.window.kill()),
        ("M-h", lazy.layout.left()),
        ("M-l", lazy.layout.right()),
        ("M-j", lazy.layout.down()),
        ("M-k", lazy.layout.up()),
        ("M-S-h", lazy.layout.shuffle_left()),
        ("M-S-l", lazy.layout.shuffle_right()),
        ("M-S-j", lazy.layout.shuffle_down()),
        ("M-S-k", lazy.layout.shuffle_up()),
        ("M-C-h", lazy.layout.grow_left()),
        ("M-C-l", lazy.layout.grow_right()),
        ("M-C-j", lazy.layout.grow_down()),
        ("M-C-k", lazy.layout.grow_up()),
        ("M-S-f", lazy.window.toggle_fullscreen()),
        ("M-<space>", lazy.widget["keyboardlayout"].next_keyboard()),
        ("M-<Tab>", lazy.spawn("sh /home/ra/.config/rofi/window_switcher/launcher.sh")),
        ("M-f", lazy.spawn("rofi -show filebrowser")),
        ("M-a", lazy.spawn("sh /home/user/.config/rofi/app_launcher/launcher.sh")),
        ("M-<Print>", lazy.spawn("sh /home/user/.config/rofi/screenshot/screenshot.sh")),
        ("A-p", lazy.spawn("sh /home/user/.config/rofi/powermenu/powermenu.sh")),
        ("A-m", lazy.spawn("sh /home/user/.config/rofi/mpd_player/mpd.sh")),
    ]
]
# if lazy.reload_config():
#     with open(os.path.expanduser("~/.config/qtile/keybindings.txt"), "w") as file:
#         for key in keys:
#             description = key.desc
#             file.writelines(f"{key} --- description: {description}\n")
#     file.close()

groups = [
    Group(label="Main", name="m"),
    Group(label="Development", name="d"),
    Group(label="Web", name="w", matches=[Match(wm_class=["qutebrowser"])]),
    Group(label="Games", name="g", matches=[Match(wm_class=["Steam"])]),
]

for i in groups:
    keys.extend(
        [
            EzKey(k[0], *k[1:])
            for k in [
                (
                    "M-" + i.name,
                    lazy.group[i.name].toscreen(),
                ),
                (
                    "M-S-" + i.name,
                    lazy.window.togroup(i.name, switch_group=True),
                ),
            ]
        ]
    )
layout_theme = {
    "border_width": 1,
    "margin": 10,
    "border_focus": "074d07",
    "border_normal": "#032541",
    "margin_on_single": 14,
}
layouts = [
    layout.Columns(ratio=0.50, **layout_theme),
]

widget_defaults = dict(
    font="Anurati",
    fontsize=13,
    padding=3,
    fontshadow="074d07",
)
extension_defaults = widget_defaults.copy()
screens = [
    Screen(
        wallpaper="~/Downloads/arch_linux-wallpaper-2560x1440.jpg",
        wallpaper_mode="stretch",
        top=bar.Bar(
            [
                widget.Sep(linewidth=3, foreground="000000",
                           background="000000"),
                widget.GroupBox(
                    hide_unused=True,
                    block_highlight_text_color="000000",
                    highlight_method="block",
                    this_current_screen_border=["ffffff", "074d07"],
                    background="000000",
                ),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    foreground="000000",
                    background="212121ff",
                    fontsize=28,
                ),
                widget.Spacer(),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="000000",
                    foreground="212121ff",
                    fontsize=28,
                ),
                widget.WindowName(
                    background="000000", font="Anurati Bold", foreground="c678dd"
                ),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="212121ff",
                    foreground="000000",
                    fontsize=28,
                ),
                widget.Sep(linewidth=3, foreground="212121ff",
                           background="212121ff"),
                widget.Image(
                    padding=5,
                    margin=0,
                    filename="~/.config/qtile/bar_icons/multimediaaudioplayer_93971.png",
                    mouse_callbacks={
                        "Button1": lazy.spawn(
                            "sh /home/user/.config/rofi/mpd_player/mpd.sh"
                        )
                    },
                ),
                widget.Spacer(),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="000000",
                    foreground="212121ff",
                    fontsize=28,
                ),
                widget.Systray(icon_size=20, background="000000"),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="000000",
                    foreground="000000",
                    fontsize=28,
                ),
                widget.Image(
                    background="000000",
                    filename="~/.config/qtile/bar_icons/volume_2_14691.png",
                    margin=2,
                ),
                widget.PulseVolume(
                    background="000000",
                    fontshadow=None,
                    font="Anurati Bold",
                    fontsize=14,
                ),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="000000",
                    foreground="000000",
                    fontsize=28,
                ),
                widget.Sep(linewidth=3, foreground="000000",
                           background="000000"),
                widget.Image(
                    background="000000",
                    margin=0,
                    filename="~/.config/qtile/bar_icons/Keyboard-icon.png",
                ),
                widget.KeyboardLayout(
                    configured_keyboards=["us", "ru"],
                    background="000000",
                    fontshadow=None,
                    font="Anurati Bold",
                    fontsize=14,
                ),
                widget.TextBox(
                    padding=0,
                    margin=0,
                    text="",
                    background="000000",
                    foreground="000000",
                    fontsize=28,
                ),
                widget.Image(
                    padding=0,
                    margin=2,
                    filename="~/.config/qtile/bar_icons/power-2-icon.png",
                    background="000000",
                    mouse_callbacks={
                        "Button1": lazy.spawn(
                            "sh /home/user/.config/rofi/powermenu/powermenu.sh"
                        )
                    },
                ),
                widget.Sep(linewidth=3, foreground="000000",
                           background="000000"),
            ],
            25,
            margin=10,
            opacity=1,
            border_color="074d07",
            border_width=1,
            background="212121ff",
        ),
    ),
]
mouse = [
    EzDrag(
        "M-1", lazy.window.set_position_floating(), start=lazy.window.get_position()
    ),
    EzDrag("M-3", lazy.window.set_size_floating(),
           start=lazy.window.get_size()),
    EzClick("M-4", lazy.window.bring_to_front()),
    EzClick("M-2", lazy.window.toggle_floating()),
]

dgroups_key_binder = None
# dgroups_app_rules = []
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(
    **layout_theme,
    float_rules=[
        *layout.Floating.default_float_rules,
        Match(wm_class="Dunst"),
        Match(wm_class="confirm"),
        Match(wm_class="dialog"),
        Match(wm_class="download"),
        Match(wm_class="error"),
        Match(wm_class="file_progress"),
        Match(wm_class="notification"),
        Match(wm_class="splash"),
        Match(wm_class="toolbar"),
        Match(wm_class="confirmreset"),  # gitk
        Match(wm_class="makebranch"),  # gitk
        Match(wm_class="maketag"),  # gitk
        Match(title="branchdialog"),  # gitk
        Match(title="pinentry"),  # GPG key password entry
        Match(wm_class="ssh-askpass"),  # ssh-askpass
        Match(wm_class="wine"),
        Match(title="vortex"),
    ],
)
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True
auto_minimize = True
wl_input_rules = None
wmname = "user"
`

**Comment by m-col** [comment]
If I run the script on the default config, it works for me. Can you confirm that it works for you if you pass it the default config? 

If it does run, then something in your config is triggering the error. Could you test out parts of your config to isolate the problem? Then we will know what the bug in the script is.

**Comment by RAprogramm** [comment]
> If I run the script on the default config, it works for me. Can you confirm that it works for you if you pass it the default config? 
> 
> If it does run, then something in your config is triggering the error. Could you test out parts of your config to isolate the problem? Then we will know what the bug in the script is.

Yes, sure. On default config script is working. If I only run script without -c and -o command. It creates 3 .png images in qtile-git directory. That is why I show here my qtile config

**Comment by RAprogramm** [comment]
I think it is all because script working only with Key(but I have used EzKey). 
But! Command 'qtile check' tell about 'type:ignore'

**Comment by elParaguayo** [comment]
You can ignore the `type: ignore` message. That is unrelated to the other issue.

**Comment by RAprogramm** [comment]
I solve my problem. It was in keys iteration. Thank you for spend your time for me. <3
