### ISSUE TITLE
Qtile ignores keystrokes on an alternative keyboard layout

### ISSUE THREAD

**Issue by Fom123** [qtile/qtile#3568]
### The issue:

When I am holding down the volume key (`fn + f3`), the key is pressed only once. (on non-default layout)
Although, when I am using default(english) layout  the key press is repeated few times.
I use `setxkbmap` to switch layouts: 
```bash
setxkbmap -layout us,ru,ua -option grp:alt_shift_toggle
```

**Qtile version**: 0.21.0
**Server**: X11
**Qtile logs in debug mode** (when I am holding down the volume up key):
```vim
Ignoring unknown keysym: 269025043, mask: 128
```
Seems legit, because the key is binded to 0 mask `(269025043, 0): <Key ([], XF86AudioRaiseVolume)>`
But why does the key mask is different between the default layout and the non-default layout?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
You can configure key repeated with `xset`. It can be configured on a per-key basis, so maybe that underlies the difference observed between the two layouts.

**Comment by Fom123** [comment]
@m-col `xset` does not help here because it used to set a delay before the key is pressed again. But the problem here, that qtile doesn't recognize the key press, because of mask mismatch. (maybe I should rename the issue)

I will attach the video, so it's easier to understand. (see the volume widget)

Default layout: 

https://user-images.githubusercontent.com/54082016/169531593-8245ba93-ce1a-4d86-a47c-b11b37878fe5.mp4

Non-default layout:



https://user-images.githubusercontent.com/54082016/169532408-4a35d6e2-7a48-4cc9-ad99-fb9c202a813e.mp4

**Comment by m-col** [comment]
Do you see any differences in `xev`?

**Comment by Fom123** [comment]
As far as I understand, the only difference is the `state`

Xev (default layout):
```vim
KeyPress event, serial 35, synthetic NO, window 0x4600001,
    root 0x728, subw 0x0, time 3320554, (-153,968), root:(817,1003),
    state 0x10, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x4600001,
    root 0x728, subw 0x0, time 3321215, (-153,968), root:(817,1003),
    state 0x10, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x4600001,
    root 0x728, subw 0x0, time 3322419, (-153,968), root:(817,1003),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x4600001,
    root 0x728, subw 0x0, time 3322459, (-153,968), root:(817,1003),
    state 0x10, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

Xev (non-default layout):
```vim
KeyPress event, serial 35, synthetic NO, window 0x5c00001,
    root 0x728, subw 0x0, time 3392204, (-99,527), root:(871,562),
    state 0x2010, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x5c00001,
    root 0x728, subw 0x0, time 3392244, (-99,527), root:(871,562),
    state 0x2010, keycode 122 (keysym 0x1008ff11, XF86AudioLowerVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x5c00001,
    root 0x728, subw 0x0, time 3393155, (-99,527), root:(871,562),
    state 0x2010, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x5c00001,
    root 0x728, subw 0x0, time 3393196, (-99,527), root:(871,562),
    state 0x2010, keycode 123 (keysym 0x1008ff13, XF86AudioRaiseVolume), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by m-col** [comment]
I think I may have a solution, though I don't fully understand why the issue is arising (and why it hasn't arisen before).

Please could you run Qtile from source, applying this diff?:
```diff
diff --git a/libqtile/backend/x11/core.py b/libqtile/backend/x11/core.py
index 9800d26c..efd1311e 100644
--- a/libqtile/backend/x11/core.py
+++ b/libqtile/backend/x11/core.py
@@ -155,7 +155,7 @@ class Core(base.Core):
 
         numlock_code = self.conn.keysym_to_keycode(xcbq.keysyms["Num_Lock"])[0]
         self._numlock_mask = xcbq.ModMasks.get(self.conn.get_modifier(numlock_code), 0)
-        self._valid_mask = ~(self._numlock_mask | xcbq.ModMasks["lock"] | xcbq.AllButtonsMask)
+        self._valid_mask = ~(self._numlock_mask | xcbq.ModMasks["lock"] | xcbq.AllButtonsMask | 0x80)
 
     @property
     def name(self):
```
Or alternatively just insert the change into your installation, it's only small.

Then please could you post any behaviour that changes, whether its fixed or other bugs are introduced?

**Comment by Fom123** [comment]
Wow, thank you! It works perfectly for me. At first glance, it didn't introduce any other bugs, so the issue can be closed.

**Comment by m-col** [comment]
Awesome, thanks for confirming. I'll leave this open while I submit a PR to fix it properly.

Does it also change the key repeat problem?

Also please could you rename the issue? It'll help in the future if others come searching for a similar issue they are having. Thanks.

**Comment by m-col** [comment]
Here's the PR: https://github.com/qtile/qtile/pull/3591

The code there is slightly different to that above, so please could you test again? Thanks

**Comment by Fom123** [comment]
> Does it also change the key repeat problem?

Well, it wasn't key repeat problem at all, because in `xev` everything worked fine. I'm not sure why I named the issue that way...

> Also please could you rename the issue?

 Would a better name be like "Qtile ignores keystrokes in an alternative layout"?

> Here's the PR: #3591
>
> The code there is slightly different to that above, so please could you test again?

Yeah, it works. Thank you again!

**Comment by m-col** [comment]
> Would a better name be like "Qtile ignores keystrokes in an alternative layout"?

Yep that would be great, thanks

**Comment by m-col** [comment]
Hi @Fom123, by any change have you been running Qtile with the patch applied for the past week or so? If so, has everything been working fine?

**Comment by Fom123** [comment]
Yeap, everything has been working fine for me for the last week. So I think #3591 can be merged

**Comment by m-col** [comment]
Excellent, thanks for confirming!
