### ISSUE TITLE
Kivy app windows not obeying the `float_rules` in `floating_layout`

### ISSUE THREAD

**Issue by hastiin-manuelito** [qtile/qtile#3577]
### The issue:

qtile --version = 0.21.0

No relevant logs for this problem.

from `config.py`
`    Match(title='My'),   # Kivy app`

The title is rendered in the kivy files from `main.py`, for example. I checked the output of `xprop`.

I know that the floating rules work for most other programs, further, I don't know if this is a problem with the kivy app itself.

Whenever I launch a kivy app with `python main.py`, for example, the window it tiled instead. However, the float-on-click does make it float. Lastly, whenever I refresh qtile it does "auto float" the app window provided that it is present, of course.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
> Whenever I launch a kivy app with python main.py, for example, the window it tiled instead. However, the float-on-click does make it float. Lastly, whenever I refresh qtile it does "auto float" the app window provided that it is present, of course.

This sounds like the window is being mapped (and tested against the float rules), and _then_ it is setting the window title. I'm not familiar with Kivy but it might be possible to set the title first, then open the window. Failing that, you could try to identify the title that it has when it does open but before it changes title.

**Comment by m-col** [comment]
Maybe something like this might work: https://kivy.org/doc/stable/api-kivy.core.window.html?highlight=window%20title#kivy.core.window.WindowBase.set_title (in case you didnt find it already). Or can you only set that after the window is created?

**Comment by hastiin-manuelito** [comment]
I definitely tried that one. I tried it in the main class from which the main app runs. I tried it within the widgets that stem from the main App. Lastly, I tried it outside the scope of the main classes just before the command that runs the program. I do have one other thing in mind. 

I don't know if it is worth a mention but kivy imports the C header files for Xlib using cython capabilities and uses that to build the windows for the application. Does this cause a disconnect with Qtile for some reason?

**Comment by m-col** [comment]
> I don't know if it is worth a mention but kivy imports the C header files for Xlib using cython capabilities and uses that to build the windows for the application. Does this cause a disconnect with Qtile for some reason?

Nope that's fine - but they would need to set the window title (using Xlib) before mapping the window to make this work
