### ISSUE TITLE
Qtile Wayland Session Fails to Start

### ISSUE THREAD

**Issue by christopherbui** [qtile/qtile#3581]
### The issue:

I've installed all the proper dependencies, including the optional dependencies.

Once starting qtile wayland session both through TTY and display manager GDM, a black screen is displayed indefinitely.

OS: Arch
Kernel: 5.17.9
Graphics: Intel/Nvidia

I've set graphics driver to hybrid, intel, and purely nvidia. All options result in the same bug.

I was wondering if anyone has had a similar experience?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by justinesmithies** [comment]
What output do you get if you run `qtile check` ?

**Comment by christopherbui** [comment]
>
May 23 10:52:38 Everest /usr/lib/gdm-wayland-session[2433]: 2022-05-23 10:52:38,878 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
May 23 10:52:38 Everest /usr/lib/gdm-wayland-session[2433]: 2022-05-23 10:52:38,879 ERROR libqtile bar.py:_configure_widget():L340 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")

I saw someone encounter this same crash report in a different issue and I believed systray crashing bug was fixed? I will link it here once I find it.

**Comment by christopherbui** [comment]
> What output do you get if you run `qtile check` ?

checking qtile config file /home/alphard/.config/qtile/config.py
/tmp/tmp4l5kx8mp/config.py:206: error: Argument 1 to "Floating" has incompatible type "**Dict[str, object]"; expected "Optional[List[Match]]"
Found 1 error in 1 file (checked 1 source file)
config file type checking failed: Command '['mypy', '/tmp/tmp4l5kx8mp/config.py']' returned non-zero exit status 1.

My config is able to run on X11. I'll check the bug promptly after seeing this.

**Comment by justinesmithies** [comment]
What if you just run `qtile start -b wayland` from the terminal ?

**Comment by christopherbui** [comment]
Running `qtile start -b wayland` from TTY still results in a black screen.
Checking `~/.local/share/qtile/qtile.log` there is only:
> 2022-05-23 11:18:31,836 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-05-23 11:19:12,060 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate

This is the result of me holding the power button to reboot as I cannot enter a TTY in the black screen state.

**Comment by christopherbui** [comment]
> Just a quick note:
> 
> The Systray message is expected behaviour. The widget is just incompatible with Wayland. It will never work on Wayland.
> 
> So, if you're only using Wayland, you should remove the widget from your config.

I understand. The issue persists with me removing the systray widget :/

**Comment by elParaguayo** [comment]
Yes. My point about expected behaviour is that is unrelated to your issue.

**Comment by m-col** [comment]
What qtile version is this with?

Please could you check that `sway` runs successfully?

@elParaguayo do users still see that systray log message? I thought 539cbf2edca3da9976af4d291fb1aa4fd2b112f9 would avoid the message by not `_configure`ing it.

**Comment by elParaguayo** [comment]
I think that PR was after the last release, wasn't it?

**Comment by m-col** [comment]
Ah yes you're right, it's not out yet.

**Comment by christopherbui** [comment]
I am on qtile 0.21.0

Sway launches and runs successfully

**Comment by m-col** [comment]
Can you run qtile directly from a TTY without GDM and see if that makes any difference?

**Comment by christopherbui** [comment]
> Can you run qtile directly from a TTY without GDM and see if that makes any difference?

Yep, I've attempted `qtile start -b wayland` from TTY and that also fails.

**Comment by m-col** [comment]
Sorry I see you actually already mentioned that. Hmm. I'm not really sure how to debug this.

Please could you try this from a TTY and report the output? `WAYLAND_DEBUG=1 qtile start -b wayland`

**Comment by christopherbui** [comment]
> Sorry I see you actually already mentioned that. Hmm. I'm not really sure how to debug this.
> 
> Please could you try this from a TTY and report the output? `WAYLAND_DEBUG=1 qtile start -b wayland`

Upon doing so, `~/.local/share/qtile/qtile.log` and `journalctl` did not report any errors. Nevertheless, the black screen state still occurs once starting qtile wayland session.

**Comment by m-col** [comment]
Yep - @christopherbui please could you redirect stderr to a file to catch those logs?

**Comment by christopherbui** [comment]
```00:00:00.388 [ERROR] [EGL] command: eglQueryDevicesEXT, error: EGL_BAD_ALLOC (0x3003), message: "EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
"
00:00:00.389 [ERROR] [EGL] command: eglQueryDevicesEXT, error: EGL_BAD_ALLOC (0x3003), message: "EGL_BAD_ALLOC error: In eglQueryDevicesEXT: Failed to allocate device list.
"
00:00:00.435 [ERROR] [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 5] Input/output error
Call stack:
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.21.0', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 48, in run
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 635, in on_done
    logger.exception("Failed to reschedule.")
Message: 'Failed to reschedule.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
OSError: [Errno 5] Input/output error
Call stack:
  File "/usr/lib/python3.10/site-packages/libqtile/core/lifecycle.py", line 37, in _atexit
    logger.warning("Qtile will now terminate")
Message: 'Qtile will now terminate'
Arguments: ()
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 5] Input/output error
[2096062.403]  -> wl_display@1.get_registry(new id wl_registry@2)
[2096062.418]  -> wl_display@1.sync(new id wl_callback@3)
```
The above is the stderr when running `WAYLAND_DEBUG=1 qtile start -b wayland`

**Comment by Shinyzenith** [comment]
@christopherbui I think two things are happening from looking at the logs.
It failed to find an ego device and you already have an xserver running hence the xwayland failed to bind error.

**Comment by m-col** [comment]
Perhaps this is related to https://github.com/swaywm/sway/issues/6398. The fix appeared to be updating libglvnd. Please could you check out that issue and see if their resolution fixes this?

**Comment by m-col** [comment]
Failing that, this issue might also be of interest with another possible solution: https://github.com/swaywm/sway/issues/6246 - running with `WLR_DRM_NO_MODIFIERS=1`.

**Comment by CharString** [comment]
I had the same symptom: dark screen and unresponsive computer. qtile did work when I removed my config.py and let it generate the default config. Turned out widget.PulseVolume() was causing it. I don't know why. widget.Volume() works better but takes a long while to start because of an amixer timeout.

**Comment by CharString** [comment]
Never mind the PulseVolume widget was causing the hang because I didn't have the cffi binding built. I was missing the libpulse header files. at install time.

**Comment by nonetrix** [comment]
Same issue on just NVIDIA. I do not have a dual graphics card machine

**Comment by nonetrix** [comment]
I am on NVIDIA no dual graphics card when I try to start Wayland I end up just getting and segmentation fault with no useful error

**Comment by m-col** [comment]
@nonetrix I suggest checking out those two sway links I posted above and seeing if any of the workarounds they mention fix your situation. https://github.com/qtile/qtile/issues/3864 also has a bit of wlroots/nvidia info. Unfortunately I don't think there is much we can do on our end, but the sway and wlroots issue trackers are pretty helpful for this and related issues.
