### ISSUE TITLE
Qtile crash after suspend

### ISSUE THREAD

**Issue by HaxSam** [qtile/qtile#3584]
### The issue:

I wanted to go into suspend mode with `loginctl suspend` but after I get out qtile crashed.
Iam on Artix 5.17.8-artix1-1 and the qtile version is 0.21.0.
I also tried the default config but it also crash

I use .xinitrc to start qtile:
```bash
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi 

wal -R -o $HOME/.walupdate &
nitrogen --restore &
picom --config $HOME/.config/picom.conf &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &
exec qtile start
```

[qtile.log](https://github.com/qtile/qtile/files/8780360/qtile.log)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Does this happen consistently?

**Comment by HaxSam** [comment]
Every time I go in suspended and exit it crashes
I reinstalled qtile I installed the git version but nothing changed

**Comment by m-col** [comment]
This looks related to this issue: https://github.com/qtile/qtile/issues/1040

It might be worth reading through that and seeing what causes or fixes might help

**Comment by RudraveerMandal** [comment]
This might not be related but if you are using artix your init system is not systemd how are you even using loginctl

**Comment by locriacyber** [comment]
Same issue here with Artix + dinit. 
[qtile.log](https://github.com/qtile/qtile/files/9741147/qtile.log)
