### ISSUE TITLE
0.0GHZ cpu and 27.8 wrong temp

### ISSUE THREAD

**Issue by ghost** [qtile/qtile#3585]
### The issue:

this is problem
![2022-05-26-191544_206x52_scrot](https://user-images.githubusercontent.com/80429360/170529727-649b5257-5a57-4a72-a5cd-10e4ed423e95.png)
this is screenshot debug i guess
![2022-05-26-191620_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/170529731-72c01fc2-a4d2-4ac0-9341-29982d7f2f08.png)

ı forget this volume always show mute but ı don't know why ?
![2022-05-26-192551_92x44_scrot](https://user-images.githubusercontent.com/80429360/170531450-60d4e439-9c70-49c7-8776-f5d84c7b5e27.png)

this is my config file
[config.txt](https://github.com/qtile/qtile/files/8780452/config.txt)
qtile.log
[qtile.log](https://github.com/qtile/qtile/files/8780463/qtile.log)
qtile --version
0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
CPU is known issue (bug in `psutil` but we're looking at a way to fix in the widget).

Why do you think temperature is wrong?

**Comment by ArchKubi** [comment]
> CPU is known issue (bug in `psutil` but we're looking at a way to fix in the widget).
> 
> Why do you think temperature is wrong?

![2022-05-27-000408_346x174_scrot](https://user-images.githubusercontent.com/80429360/170579948-11d65655-ba4a-400b-bb5c-7232109f94aa.png)

**Comment by elParaguayo** [comment]
I'm not sure what you want me to look at. Your temp widget says 27.8 degrees and I can see that in your `sensors` output. So the widget isn't wrong.

**Comment by elParaguayo** [comment]
If you want a different temperature, find the right thermal zone and configure your widget accordingly:
http://docs.qtile.org/en/stable/manual/ref/widgets.html?highlight=thermalzone#thermalzone

**Comment by ArchKubi** [comment]
ı search but ı dont know how ı find thermal zone

**Comment by elParaguayo** [comment]
Run `cat sys/class/thermal/thermal_zone0/temp`, increasing the zone number by 1, until you find the zone that matches the temperature you want. Then set `zone` to that path.

**Comment by ArchKubi** [comment]
ı do wrong ?
widget.ThermalSensor(foreground = colors[2],background = colors[4], zone="/sys/class/thermal/thermal_zone0/temp", threshold = 90,fmt = 'Temp: {}',padding = 5),

ı try 
/sys/class/thermal/thermal_zone0
/sys/class/thermal/thermal_zone1
/sys/class/thermal/thermal_zone2
![2022-05-27-004044_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/170584676-8846065b-f768-4a6c-81d1-28a3a1855fab.png)

**Comment by Meresmata** [comment]
I also had the problem with 0.0 GHz. What I did is to remove it via the format parameter. The problem I have with it is: that depend on whether the load is 8.7% or 18.7% the length of the text changes. I tried to use fstring syntax.

**Comment by m-col** [comment]
Your sensors suggests two separate entities, ACPI and ISA. From a quick search of 'coretemp isa'  I found this: https://unix.stackexchange.com/questions/418919/how-to-obtain-cat-cpu-core-temp-from-isa-adapter. First line of first answer is "The ACPI temperatures are under /sys/class/thermal, yes, but the lm_sensors hardware monitoring sensors are under /sys/class/hwmon/." Maybe there is a lead for you?
