### ISSUE TITLE
[wayland] StatusNotifier no longer works after logging out and logging back in, notifications included.

### ISSUE THREAD

**Issue by Sydiepus** [qtile/qtile#3588]
### The issue:

Qtile version : 0.21.1.dev47+gbfa55e75
relevant logs :
 ```
2022-05-27 11:29:27,189 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-05-27 11:29:32,247 ERROR libqtile loop.py:_handle_exception():L63 could not open dbus info file: /home/noen/.dbus/session-bus/a6ca2ab917c743f994d4e74a91e65afa-0
NoneType: None
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report.

You say "no longer works". Did it work before?

Also, what do you mean about "logging out and logging back in"?

You could try doing a `git bisect` to see if there's a commit that broke this but that message is an error with the `dbus_next` library not being able to connect to the bus, rather that qtile specific code, which makes me wonder if there's an issue with the session bus being created when you log in.

**Comment by Sydiepus** [comment]
Sorry for the lack of information.


What i mean by "logging out and logging back in" is that : I terminate the session go to the display manager (ly) in my case and log back in to qtile. 


What i mean by "no longer works" is that : icons no longer appear and i don't receive any notifications.


I am not entirely sure if it was working before.


I'll try an older version of the display manager to check if it's the one causing trouble.

**Comment by elParaguayo** [comment]
Thanks. I think(/hope) that it's very unlikely to be a qtile issue. It sounds like your dbus session isn't closing/opening correctly. When you log out and exit qtile, the processes that are creating connections to the bus should be terminated. Logging back in should create new connections but you're getting an error saying that we can no longer connect to the bus.

When you log back in, can you try running `d-feet` and see if it's able to access the session bus?

I will caveat all of this by saying I am far from being a dbus expert.

**Comment by Sydiepus** [comment]
I tried SDDM and well it worked.

Seems like an issue with ly. 

Sorry for the inconvenience.

**Comment by elParaguayo** [comment]
No problem at all. Glad to hear it's working ok now.
