### ISSUE TITLE
XWayland: Firefox context menus always open in their very first position

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#3594]
### The issue:

Version: 32a89c5ec067d9e96b086cb2501aaaf16949f486

This is specific to XWayland, so firefox needs to be run using that.

This likely applies to all override-redirect windows.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Shinyzenith** [comment]
Hi @m-col would you mind sharing a screenshot? I'd like to try my hands at fixing some wayland bugs and I don't quite understand "open in their very first position"

**Comment by Sydiepus** [comment]
Not sure if a screenshot would help but i'll try to explain "open in their very first position".

Imagine firefox as a 2D canvas (i think it's called) with x axis as abscissa and y axis as coordinate like this : 
![image](https://user-images.githubusercontent.com/49863809/171504517-21e7be0e-9392-41ec-bc96-441ce4e83a3d.png)
photo / info from [here](https://www.cuemath.com/geometry/x-and-y-graph/).

If the cursor is at (50,80) and right click is clicked then the context menu / right click menu will open at (50,80)
Now if the cursor moved to (70,100) and  right click is clicked then the context menu will open at (50,80) since the first right click was at (50, 80)

This also applies to tab names, the menu that appears when you hover on a tab.

I tried to record it but obs is crashing, and none of (kooha, peek) worked.
If you can recommend anything else i would be happy to record it.

**Comment by Shinyzenith** [comment]
> I tried to record it but obs is crashing, and none of (kooha, peek) worked. If you can recommend anything else i would be happy to record it.

That's fine, your explanation is crystal clear 😁. I'll try my hand at fixing this.

**Comment by m-col** [comment]
Yes exactly as  described, thank you @Sydiepus.

@Shinyzenith, thank you for trying to tackle this. For a bit of background on how the backend currently handles X11 override-redirect windows like these context menus, this is what happens when they are created (for the first time):

- `Core._on_xwayland_new_surface` is called with the new XWayland surface, and a new `XWindow` is added to `Core.pending_windows`, where it will wait until mapped for the first time.
- When it is mapped, `XWindow._on_map` is called
- The window is in `self.core.pending_windows` so we create a new WID for the window and we start properly managing it.
- In the case of these windows, `self.surface.override_redirect` is `True`, so we convert the window to a `XStatic` via `self.cmd_static`, and manage it through that interface instead.

The thing is, we don't listen for any signals for the window when it wants to change position, but adding a new listener in `XStatic.__init__` with corresponding method might be sufficient. Note that we only want to do this with override-redirect windows - it is possible that an XWayland client is manually made static (and therefore converted to `XStatic`) by the user, and in that case we want to ignore the window's requests for geometry changes.

I hope that helps - and please do let me know if I can help more, I am happy to look further into this.

**Comment by Shinyzenith** [comment]
> I hope that helps - and please do let me know if I can help more, I am happy to look further into this.

Thank you for the clear explanation. I'm still new to Wayland development so I would like to request you to bear with my stupid questions if I ask any 😀.

First of which: Is there any way I can detect if a window was manually made XStatic by the user? Also I cannot find any mention of XStatic in wlroots headers, so where can I read up about possible events it emits?

**Comment by m-col** [comment]
> Thank you for the clear explanation. I'm still new to Wayland development so I would like to request you to bear with my stupid questions if I ask any grinning.

Of course! Note that some concepts will be general to wayland or wlroots, and others will be specific to Qtile. In this case, [Static](https://github.com/qtile/qtile/blob/master/libqtile/backend/base.py#L590) windows are a Qtile concept which exists in both backends. A bit of background: there are 3 classes of windows in Qtile, `Window` (regular tiled/floating windows that exist on 1 group), `Static` that exists on all groups and cannot be moved, and `Internal` which is used for the bar. Each backend has to define implementations for all 3 classes. In the wayland backend, clients can create windows via a number of protocols with different interfaces, so each protocol has implementations for both `Window` and `Static`. E.g. for XWayland we have `XWindow` and `XStatic`. For this reason, you won't find mention of `XStatic` in wlroots.

> where can I read up about possible events it emits?

`XWindow` and `XStatic` do wrap a wlroots object: the `xwayland.Surface` in:
```py
class XWindow(Window[xwayland.Surface]):
    ...

class XStatic(Static[xwayland.Surface]):
    ...
```
This can be found here: https://github.com/flacjacket/pywlroots/blob/main/wlroots/xwayland.py#L148 and I suspect you'll need to use the `set_geometry_event` event.

> Is there any way I can detect if a window was manually made XStatic by the user?

By default, 'regular' windows use `XWindow` and only override-redirect windows use `XStatic`, and the decision is made here: https://github.com/qtile/qtile/blob/master/libqtile/backend/wayland/window.py#L900. You can use that same attribute to determine whether a user has made a window static, because in that case it will be an `XStatic` that is not an override-redirect window, so you could test that in `XStatic.__init__` and create a listener accordingly.

**Comment by Shinyzenith** [comment]
Once again, thank you for the detailed explanation. Now it makes sense why xstatic exists, I'll get to try and fix this first thing tomorrow 😃.

**Comment by Shinyzenith** [comment]
Hi, I'm almost done with this patch.
The only part that remains is getting the geometry data from the surface and then updating the `self.*` values accordingly.

I have registered a listener as such:
```py
    def _on_set_geometry(self, _listener: Listener, _data: Any) -> None:
        logger.debug("Signal: xstatic set_geometry")
```

How can I get the geometry data from the listener? I apologize if this is a very basic question.

**Comment by Shinyzenith** [comment]
The patch is ready. Just trying to figure out how to detect user set XStatic now.
