### ISSUE TITLE
Qtile not moving focus to second screen when the mouse moves to it.

### ISSUE THREAD

**Issue by compromyse** [qtile/qtile#3605]
### The issue:

When my mouse moves to my second display and there are no windows open on it, the focus stays on the window of my first display. Anyone know why this happens?

`qtile 0.21.0`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
The focus won't change just from moving the mouse pointer onto the other screen. What happens if you click on the other screen? does the focus change then?

**Comment by SweepingBishops** [comment]
Hasn't this been reported multiple times before?
#2657 #3381 #2098 #3166 
It seems like a fairly sought after feature. 
> The focus won't change just from moving the mouse pointer onto the other screen.

Is a way to make it happen?
Maybe I can finish the approach in #3381 and open a PR?

**Comment by compromyse** [comment]
> The focus won't change just from moving the mouse pointer onto the other screen. What happens if you click on the other screen? does the focus change then?

Yeah it does

**Comment by m-col** [comment]
> Is a way to make it happen?
> Maybe I can finish the approach in https://github.com/qtile/qtile/issues/3381 and open a PR?

Do you mean what I describe here - https://github.com/qtile/qtile/issues/3381#issuecomment-1050109162 - i.e. tracking cursor for the root window and all regular windows?

An alternative approach might be to use X11 pointer barriers, e.g. https://mcol.xyz/code/xoop/file/xoop.c.html#l63. This could potentially reduce load, as Qtile will only receive events when the mouse moves over the barrier, and make the implementation a bit more simple as we wouldn't need to involve any windows.

Regardless - a PR is very much welcome!

**Comment by m-col** [comment]
Let's keep further discussion on this in #3381, and I'll close this in favour of that issue.

**Comment by elParaguayo** [comment]
> > Is a way to make it happen?
> > Maybe I can finish the approach in #3381 and open a PR?
> 
> Do you mean what I describe here - [#3381 (comment)](https://github.com/qtile/qtile/issues/3381#issuecomment-1050109162) - i.e. tracking cursor for the root window and all regular windows?
> 
> An alternative approach might be to use X11 pointer barriers, e.g. https://mcol.xyz/code/xoop/file/xoop.c.html#l63. This could potentially reduce load, as Qtile will only receive events when the mouse moves over the barrier, and make the implementation a bit more simple as we wouldn't need to involve any windows.
> 
> Regardless - a PR is very much welcome!

Sorry - I know this thread is closed...

We can access the pointer barrier methods through the `xcffib` library so, presumably, we can implement something like this in the backend.

**Comment by m-col** [comment]
> We can access the pointer barrier methods through the xcffib library so, presumably, we can implement something like this in the backend.

Yep, totally!
