### ISSUE TITLE
Highligting text in firefox causes firefox to crash Qtile only

### ISSUE THREAD

**Issue by nymann** [qtile/qtile#3606]
### The issue:

- Linux arch linux 5.18.1-arch1-1
- Qtile --version 0.21.0 (installed via `pacman -S qtile`

The firefox version doesn't matter, and it's affecting thunderbird, firefox and firefox-developer-edition.

I have confirmed that it's qtile since I cannot replicate the bug on the same system with dwm.

I have tried on two systems, with the second one being a fresh install.

The crash causes no qtile logs.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. Sounds very odd!

Is this Wayland or X11?

**Comment by nymann** [comment]
Xorg

xorg-server 21.1.3-7

**Comment by elParaguayo** [comment]
Can't replicate this. Running firefox and highlighting text isn't causing any issues for me.

Does this happen with the default config?

**Comment by nymann** [comment]
> Can't replicate this. Running firefox and highlighting text isn't causing any issues for me.
> 
> Does this happen with the default config?

Yep

**Comment by nymann** [comment]
I successfully debugged the issue @elParaguayo :

As part of my `.zprofile` i do:
```sh
# Get cam to work in Microsoft Teams
export XLIB_SKIP_ARGB_VISUALS=1
```

When I  comment that out, the crash no longer appears, mind you that it's only crashing in Qtile and not DWM.

**Comment by Malex** [comment]
> 1. XLIB_SKIP_ARGB_VISUALS

That variable is related to an extension (Composite) which is usually not on by default (at least according to X11 documentation).
Try `xdpyinfo | grep -i composite` to check if you have it.
The variable seems to be some kind of quirk they added to let some apps work, but reading the doc it doesnt seem something you should use in your profile (if you needed it for teams, the better way would have been to override the variable just for the teams invocation, not for the whole environment): https://www.x.org/archive/X11R6.8.0/doc/RELNOTES5.html 
>  If an application fails only when the Composite is enabled, try setting this environment variable before starting the application.
