### ISSUE TITLE
qtile.org does not have proper SSL Certificate

### ISSUE THREAD

**Issue by mgutz** [qtile/qtile#3625]
### The issue:

I posted a screenshot on `/r/unixporn` with link to the Qtile site, and used [Qtile](https://qtile.org). Browsing that on Firefox, gives you the usual

"Warning: Potential Security Risk Ahead"

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks - this is a known issue (https://github.com/qtile/qtile.org/issues/1#issuecomment-1108141671) - there's some broader work going on with the website too.

**Comment by mgutz** [comment]
😳 I swear I searched for SSL. apologies

**Comment by elParaguayo** [comment]
No problem. It's on the qtile.org issues page, not the qtile one. Easy to miss.
