### ISSUE TITLE
XDG_OPEN and groups

### ISSUE THREAD

**Issue by ThatOneOcto** [qtile/qtile#3626]
### The issue:

qtile ver: 0.21.0

When I open a link in an app it opens in firefox, but it didn't switch to the group firefox was in, and I expected it to switch to the group. I don't think this is a bug, rather a missing feature.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
This seems like something that the `focus_on_window_activation` config variable could/should support. The current behaviour (under x11) of that variable is that it applies when applications emit a `_NET_ACTIVATE_WINDOW` message. I don't know how general it is but I do wonder if firefox already does that, so it may work for that case. It might be worth testing in case you haven't already.

**Comment by ThatOneOcto** [comment]
`focus_on_window_activation` could possibly be one way to do it but `smart` nor `urgent` work to switch the group

*docs for `focus_on_window_activation` [here](https://docs.qtile.org/en/latest/manual/config/index.html?highlight=focus_on_window_activation#configuration-variables)*

**Comment by m-col** [comment]
> focus_on_window_activation could possibly be one way to do it but smart nor urgent work to switch the group

**Comment by m-col** [comment]
> focus_on_window_activation could possibly be one way to do it but smart nor urgent work to switch the group

It works for me if focus_on_window_activation is set to `"focus"`
