### ISSUE TITLE
lazy.layout [switch/move/grow] [left/right] don't work on certain layouts

### ISSUE THREAD

**Issue by gatlace** [qtile/qtile#3627]
### The issue:

Meta+H and L don't work at all, nor do any of its relatives. J and K do, but H and L don't
I haven't changed those bindings from default.

Using a minimally edited config(removing the textboxes and copy-pasting a second screen to make life easier), These layouts don't work: 

Stack
RatioTile
Spiral
The other ones that were in the default config I tried and they seem to work(zoomy doesn't work at all but that's besides the point), I'll try some that aren't in the config soon.

Version: 0.21.0
Distro: Arch

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report (I assume you're the same person that's posted on Reddit too).

As for your issue, the default config binds `lazy.layout.left/right()` to those keys. Not all layouts implement those methods which is why you're seeing this behaviour.

You can bind multiple commands to the same key e.g. you could do:
``` python
Key([mod], "h", lazy.layout.left(), lazy.layout.previous.when(layout="spiral"), desc="Move focus to left"),
```

**Comment by gatlace** [comment]
Doing `lazy.layout.next()` seems to work, trying `previous()` or `<direction>.when()` seems to break the config. It's weird, it used to work out of the box a while ago.  Any idea what happened?

Thank you!

**Comment by elParaguayo** [comment]
Firstly, I made a mistake in my code, it should be:
``` python
lazy.layout.previous().when(layout="spiral")
```
But that doesn't seem to be working for me either. Need to do some checking.

**Comment by elParaguayo** [comment]
Closing this but feel free to reopen if you have more issues with this.
