### ISSUE TITLE
Fullscreen window not accessible when it loses focus.

### ISSUE THREAD

**Issue by LordXerus** [qtile/qtile#3629]
### The issue:

I wanted to do X, but Y happened, and I expected Z. I think this is a bug.

Can't refocus on a fullscreen window that lost focus. The fullscreen window doesn't accept keyboard input so I can't unfullscreen it.

`qtile --version`: `0.21.0`
Logs attached at bottom. None of the open bugs seem to match my issue.

**After some more testing it seems that buggy state(Y) happens whenever fullscreen window loses focus through:**
- `lazy.layout.next()`. Buggy state does not happen when there is no window to switch to.
- Moving the mouse onto another window with focus on hover
- Switching to a different group WITH A WINDOW
- **Switching to a blank group does NOT cause buggy state**

**When hidden, fullscreen windows cannot:**
- Accept keyboard input, even when the Prompt widget shows the fullscreen window's name
- Be switched to by Qtile via `lazy.layout.next()`
    - Switching away is possible, but `layout.next()` will skip the fullscreen window
    - `rofi -show window` can force Qtile to focus on fullscreen windows.
- Can sometimes get control of the window again with `lazy.restart()` (See `Behavior when qtile is restarted`).
- Application responds to `lazy.window.kill()`
- Application can be moved to another group.

### Affected Applications:
- Osu-lazer (the bug report is based on behavior with this in fullscreen)
- Minecraft
- **Interestingly, Firefox (`f11`) is NOT affected. Firefox with fullscreen YouTube isn't either.**

### On group with fullscreen window

**Layout is :`MonadTall`**
**Focus on Hover is *On***
- **If Osu(fullscreen) is the only window**
    - Osu and Qtile seems to have a fight, but Osu remains in fullscreen. Control is regained
- **If Osu(fullscreen) is 1/2 windows**
    - Osu will be forced into a window if focused.
        - Osu still thinks it's in fullscreen.
        - Osu ***can*** accept keyboard input.
        - **Focusing on another window will immediately hide Osu behind everything.**
        - If the layout is bad you may end up with a 1/3 case
    - If not focused, it will be hidden immediately.
- **If Osu(fullscreen) is 1/3 windows**
    - I cannot get Osu to be focused. Osu is hidden(bugged) immediately after restart.

### On a different group not containing fullscreen window
- Switching to the fullscreen group the first time after restart yields proper behavior
- Any future switches yields buggy behavior.

##### Scenario 1
1. Delete qtile config from another group
2. `lazy.restart()` (mod-control-r)
3. `$ qtile shell` -> `> debug()`
4. Switch to group 6 (Osu-Lazer)
5. **Expected behavior happens. Fullscreen is visible**
6. Switch to Group 2
7. Switch to Group 6
8. **Buggy behavior happens. Fullscreen is invisible**
9. `lazy.restart()` 
 

[qtile (copy 2).log](https://github.com/qtile/qtile/files/8894322/qtile.copy.2.log)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by LordXerus** [comment]
did I write an essay?

**Comment by elParaguayo** [comment]
> did I write an essay?

No. You wrote a very thorough bug report which is great.

I have just had no time to look at this yet and may not have some time for a while longer.

**Comment by jwijenbergh** [comment]
OSU seems to request a minimize, because the following gets called: https://github.com/qtile/qtile/blob/ecfc7c921fbf860b2892d955bb813c242669700e/libqtile/backend/x11/window.py#L1725

You can get it to not automatically minimize by adding:

```python
auto_minimize = False
```

to your Qtile config. Is this what you want or is there some other bug at play here?  If so I can look at it more extensively

**Comment by LordXerus** [comment]
I see yeah I think auto_minimize is the issue I am experiencing.
I didn't know minimizing was a thing in Qtile.
Is there any way to bring minimized windows back? Query what windows are minimized? Is there a widget for minimized windows?

**Comment by jwijenbergh** [comment]
You can use the TaskList widget http://docs.qtile.org/en/stable/manual/ref/widgets.html?highlight=tasklist#tasklist

You can also script it:

See e.g. this snippet by @m-col 
https://github.com/m-col/qtile-config/blob/1907ed323ebcb03f43d4925633e0b69560487042/tags.py#L52
