### ISSUE TITLE
GroupBox don't know how to arrange groups when they have the same label

### ISSUE THREAD

**Issue by pineedaa** [qtile/qtile#3630]
### The issue:

When I start Qtile groups don't arrange in their order. This is my config for groups:
icon=''
groups = {
        Group(name="1", position=1, label=icon),
        Group(name="2", position=2, label=icon),
        Group(name="3", position=3, label=icon),
        Group(name="4", position=4, label=icon),
        Group(name="5", position=5, label=icon),
        Group(name="6", position=6, label=icon),
        Group(name="7", position=7, label=icon)
        }

The problem gets solved once I open any window

Qtile version: 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Try using a list `[...]` rather than a set '{...}`.

**Comment by pineedaa** [comment]
Ok. Now it's working well. Thanks!
