### ISSUE TITLE
gnome-keyring-daemon not starting or not publishing SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by chaapp87** [qtile/qtile#3635]
### The issue:

Hi there,

I did a fresh Ubuntu 22.04 LTS installation and set up qtile.
While configuring my keepass2 application which provides SSH keys to the ssh-agent, I reconized that this would not work.
If I use GNOME, it works fine. As soon as I fire up qtile I get an error message telling me that the ssh-agent is not running.

I did some research and found out, that while starting qtile there is no SSH_AUTH_SOCK variable available.
I think this should be published by gnome-keyring-daemon.

I tried adding `gnome-keyring-daemon --start` to my autostart.sh, but this did not help.

Has somebody an idea how I could try to fix it?

On my other machone I use Ubuntu 20.04 LTS. There the SSH_AUTH_SOCK goes to /tmp/...

In Ubuntu 22.04 it should be in /run/user/1000/keyring/ssh but using qtile it is not created.

many thanks in advance!

Qtile-version: 0.21.0
The qtile log does not show anything that has sth. to do with this issue I think. Just some keystroke errors....

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by chaapp87** [comment]
I could fix it myself by disabling gnome-keyring and adding following to ~/.profile:

`export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
ssh-add -l 2>/dev/null >/dev/null
if [ $? -ge 2 ]; then
  ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
fi
`

**Comment by m-col** [comment]
Is that solution satisfactory? should we close this?

**Comment by elParaguayo** [comment]
Well, it's not a qtile issue per se so there's nothing we need to fix. If this works, I'm in favour of closing.
