### ISSUE TITLE
No icon for some apps in Tasklist widget

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3637]
### The issue:

```console
$ qtile --version
    0.21.1.dev67+g2b2cd60b
```

As far as I've checked, this only happens with apps that don't "publish" an X property for icon (_NET_WM_ICON, WM_ICON_NAME). Can the WM_CLASS property be used for this, possibly?

`I know what I have to do, but I don't know if I have the strength to do it.`

![image](https://user-images.githubusercontent.com/84532402/174458652-bcb2245d-3aa6-4fd8-a11f-499cb269ddb2.png)
`That little smudge of color is supposed to be the icon :)`

![image](https://user-images.githubusercontent.com/84532402/174458680-3785b5b2-9f4a-49a4-92c5-a124f05cc03e.png)
`Normal behaviour`

```console
$ xprop
XdndProxy(WINDOW): window id # 0x4600004
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify"
_NET_WM_NAME(UTF8_STRING) = "Spotify"
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
_NET_WM_PID(CARDINAL) = 34927
WM_CLIENT_MACHINE(STRING) = "arch"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

```python
widget.TaskList(
    parse_text=no_text,
    highlight_method="block",
    icon_size=48,
    border=colors[0],
    rounded=True,
    padding=0,
    padding_y=-3,
    margin_x=2,
    margin_y=45,
    txt_floating="🗗 ",
    txt_maximized="🗖 ",
    txt_minimized="🗕 "
),
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What we should be doing is looking up icons installed in the user's system (using a library like `xdg`). This would also allow us to have icons on Wayland.

I can take a look at adding this.
