### ISSUE TITLE
Backend-Specific configuration doesn't work

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#3641]
### The issue:

I want to do a backend-specific configuration as described in the documentation here
https://docs.qtile.org/en/latest/manual/wayland.html#backend-specific-configuration=

```python
from libqtile import qtile

if qtile.core.name == "x11":
    term = "urxvt"
elif qtile.core.name == "wayland":
    term = "foot"
```

The problem is, that the `qtile` variable is `None`.

```python
In [1]: from libqtile import qtile

In [2]: print(qtile)
None

In [3]: 
```

Am I doing something wrong, or is the documentation incorrect/incomplete?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Where are you putting that code?

That will only work in the same python environment (ie it needs to be part of your config). Running in an external script won't work. 

If you need to access the backend name, you will need to do it a different way.

**Comment by elParaguayo** [comment]
To add to my earlier answer...

Currently, any backend checking in the config needs to happen within a function (which can be decorated with `@hook.subscribe.startup` for example). If not, those lines will be executed when the config file is first read and `qtile` will still be `None` at that point.

If there's anything else, let us know but would be good to close this if possible.

**Comment by m-col** [comment]
>  Currently, any backend checking in the config needs to happen within a function (which can be decorated with @hook.subscribe.startup for example). If not, those lines will be executed when the config file is first read and qtile will still be None at that point.

This only applies to the default config loaded for default values before the user's config is loaded. It should work find at the top level of a user config.

**Comment by elParaguayo** [comment]
Ah! That makes sense, I was trying to do it in the default config for the Systray widget.

**Comment by FrostyX** [comment]
> Currently, any backend checking in the config needs to happen within a function (which can be decorated with @hook.subscribe.startup for example). If not, those lines will be executed when the config file is first read and qtile will still be None at that point.

Thank you very much for the explanation. I believe this was the cause of my problem. I can't check right now because I did Wayland experiments on my other laptop which is currently unavailable. I will try later.

It would be nice to have this explained in the docs as well but anyway, let me close the issue.
