### ISSUE TITLE
DropDown geometry is off

### ISSUE THREAD

**Issue by 3nprob** [qtile/qtile#3643]
### The issue:

qtile version `0.21.0`

```
groups.append(ScratchPad('scratchpad', [
    DropDown('term', 'urxvt',
        opacity=0.8,
        y=0.65,
        x=0,
        width=1.0,
        height=0.35
    )
]))

keys = [
    Key(['mod4'], 'space', lazy.group['scratchpad'].dropdown_toggle('term'), desc="scratchpad"),
]
```

The intention is to make it a "DropUp" pinned to the bottom by making `height + y = 1.0`.

Instead, there is a ~50px gap between the bottom of the window and the bottom of the screen.

NixOS, X11 on a `2560x1440` display.

`y=0.68` brings it just a pixels above the bottom.

Similarly, the right border is flowing off the side of the screen.
### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by 3nprob** [comment]
One way this could be solved for: Add a new parameter `relative` (default `True`).

If set to `False`, dimensions and position values will be interpreted as pixels rather than screen fractions, allowing precise placement.

**Comment by elParaguayo** [comment]
That would be problematic if you were trying to open a drop down on different screens with different resolutions.

Going back to your original questions - this feels like it's something to do with a bar. If I remember correctly, the relative values are based on the screen's drawable area (i.e. excluding the bar). 

Could you try disabling the bar in your config (but make sure you have a way to quit qtile) and try again and see if that makes a difference?

**Comment by elParaguayo** [comment]
If it's the bar then we may just need to change some of the logic about the positioning but it _should_ be fixable.

**Comment by elParaguayo** [comment]
I had a quick look at this and the logic looks ok to me.

I tried using `height=0.65, y=0.35` and the window is positioned correctly (other than the window border is off screen). Checking the dropdown's height and y parameters I can see that they do equal the screen's height.

So, as I can't currently replicate this, can you post a screenshot and your config so I can investigate further.

**Comment by 3nprob** [comment]
I may have had some weird state at the point this was filed - after rebooting I have not reproduced this again.
