### ISSUE TITLE
Qtile bar going entire black at random moments

### ISSUE THREAD

**Issue by Sprinter05** [qtile/qtile#3650]
### The issue:

Qtile version: 0.21.0

Sometimes at random moments the Qtile bar goes entirely black and it will only fix itself when restarting qtile and with some applications (for the moment i have only seen it with Discord 0.0.18 (latest version at the moment of posting)) restarting qtile or the system will not fix the issue.

OS: Kubuntu 21.10
Kernel: 5.13.0
Running on VMWare WorkStation 16 using '3D Graphics Acceleration'

https://github.com/Sprinter05/my-dots/tree/main/qtile (config.py and qtile.log)
Most recent logs are at the bottom of the logs file.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Lots of errors in that log!

The last messages show an issue with your `window_name` function which is causing one of the widgets to crash during draw which might be the issue here.

Try adding this:

``` python
def window_name(text):

    if text is None:
        return ""

    for string in [" - Mozilla Firefox"]:
        text = text.replace(string, "")
    return text
```

**Comment by Sprinter05** [comment]
The issue was not fixed with that. attach here the logs after applying the fix.
[qtile.log](https://github.com/qtile/qtile/files/8948291/qtile.log)

**Comment by Sprinter05** [comment]
It only happens when opening Discord or sometimes with some apps.

**Comment by elParaguayo** [comment]
Can you try disabling the `WindowName` and `SysTray` widgets as they're the ones that potentially react to opening Discord and other new apps.

**Comment by Sprinter05** [comment]
Well I have no idea how I didnt think of this before but yes, it was SysTray.

**Comment by elParaguayo** [comment]
That's weird. `SysTray` shouldn't cause that behaviour!

Would be great if you could identify which app causes the issue so I can see if I can recreate on my machine.

**Comment by Sprinter05** [comment]
I mentioned it before but I was using Discord 0.0.18 (latest version at the moment of posting)

**Comment by elParaguayo** [comment]
OK - you also mentioned other apps so wanted to check if you'd narrowed it down. Will see if I can recreate this.

**Comment by elParaguayo** [comment]
I don't have any issues with discord in the Systray. I wonder if this is linked to you running qtile in python 2.7 (as per our discord conversation).

**Comment by Sprinter05** [comment]
qtile is installed in Python 3.9.7 so it shouldnt affect in that regard I have no idea why this happens.

**Comment by elParaguayo** [comment]
Can you record a video of it happening?

**Comment by RudraveerMandal** [comment]
Is this happening on X11 or Wayland? In my case a few widgets crash on wayland and sometimes Systray also crashes. Also you mentioned it happening when you open discord which does interact with wayland-native stuff when it is opened on wayland.
