### ISSUE TITLE
[ Feature ] Allow users to toggle cursor on and off under both X and Wayland

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3651]
### The issue:

I think a missing feature of qtile that would be very useful to most users would be an option to be able to toggle the cursor on and off under both X and wayland. Something similar to unclutter but allowing the user to toggle it via scripts or keybindings.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
I've implemented this here: https://github.com/qtile/qtile/pull/3661 Please could you test it out? Any feedback is appreciated

**Comment by m-col** [comment]
If it's used with swayidle, the cursor is shown again when keys are typed on the keyboard, because that triggers 'wake' events via the idle protocol. I guess that isn't quite how we'd want this to work, huh?

**Comment by justinesmithies** [comment]
All tested and works fine for me. As for the swayidle key wake issue i'm sure a work around can be found at some point.
From little acorns ;)
