### ISSUE TITLE
Bar flickering in vertical mode

### ISSUE THREAD

**Issue by karthink** [qtile/qtile#3652]
### The issue:

Qtile version: 0.21.0

My qtile bar flickers in vertical mode. This might be related to #3062, but the bar behaves normally in horizontal mode for me. Also the fixes in that issue have already been applied to my relatively recent build of Qtile.

https://user-images.githubusercontent.com/8607532/174957846-5fe9465c-e184-4287-a113-264c7bba453e.mp4

There are actually two behaviors here:

1. The bottom segment(s) of the bar (the clock and battery widgets in my case) simply vanish. This is persistent. They reappear for a couple of seconds when I switch desktops but then disappear again. This happens no matter what the bottom widget is.

2. The entire bar flickers whenever something visual happens in an application (such as opening a new tab in a browser, or when changing desktops).

I've tried the following things without success:

1. Ensure that all widgets in the bar support a vertical bar orientation (no groupbox etc)
1. Remove all the multibyte fontawesome icons from the bar, as well as the image widget, leaving only text.
4. Try different monospaced fonts
2. Disable each widget in turn (assuming some misbehaving widget is responsible for this)
5. Initialize the bar with no margin, no border_width
3. Reverse the order of the bar widgets

Here is a simplified version of my bar config that displays the flickering behavior:

```elisp
colors = [["#172030", "#172030"], # panel background
          ["#273a43", "#273a43"], # background for current screen tab
          ["#e8e9eb", "#e8e9eb"], # font color for group names
          ["#db6e8f", "#db6e8f"], # border line color for current tab
          ["#1f2a3f", "#1f2a3f"], # border line color for 'other tabs' and color for 'odd widgets'
          ["#0e131d", "#0e131d"], # for the 'even widgets'
          ["#b16e75", "#1f2a3f"], # window name
          # ["#0e131d", "#c6797e"], #
          ["#34262D", "#c6797e"], #
          ["#7d7f7b", "#7d7f7b"]] # background for inactive screens

terminal = "st"

def sep(cf,cb):
    __box = widget.Sep(
        linewidth = 0,
        padding = 4,
        foreground = colors[cf],
        background = colors[cb],
    )
    return __box

widget_defaults = dict(
    font='Monospace Extrabold',
    fontsize=22,
    background=colors[2][0],
    padding=12,
)

extension_defaults = widget_defaults.copy()
tasklist_focused_markup = "<span weight=\"bold\">{}</span>"

def init_widgets_list():
    widgets_list = [
        widget.Sep(
            linewidth = 0,
            padding = 6,
            foreground = colors[2],
            background = colors[0]
        ),
        widget.Sep(
            linewidth = 0,
            padding = 6,
            foreground = colors[2],
            background = colors[0]
        ),
        widget.Prompt(
            prompt = prompt,
            padding = 10,
            foreground = colors[3],
            background = colors[1]
        ),
        widget.Sep(
            linewidth = 0,
            padding = 40,
            foreground = colors[2],
            background = colors[0]
        ),
        widget.WindowTabs(
            fontsize = 20,
            foreground = colors[6][0],
            background = colors[0],
            border = colors[6][::-1], # was colors[1]
            highlight_method = 'block',
            markup_focused = tasklist_focused_markup,
            max_title_width = 150,
            margin = 1,
            padding = 5,
        ),
        widget.Systray(
            background = colors[0],
            padding = 5
        ),
        sep(0,4),
        widget.Bluetooth(
            foreground = colors[2],
            background = colors[5],
            fmt = '{}',
            padding = 5, max_chars = 9,
            hci = '/dev_88_D0_39_F9_15_0A',
            mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn('dmenu-bluetooth')}
        ),
        sep(5,4),
        widget.Backlight(
            foreground = colors[2],
            background = colors[4],
            padding = 2,
            step = 4,
            update_interval = 1.0,
            backlight_name = "amdgpu_bl0"
        ),
        sep(4,5),
        widget.CPU(
            foreground = colors[2],
            background = colors[5],
            padding = 2,
            format = "{load_percent:2.0f}%",
            update_interval = 2.0,
            mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(terminal + ' -t dropdown_cpu -e btm')},
        ),
        sep(5,4),
        widget.Battery(
            foreground = colors[2],
            background = colors[4],
            padding = 3,
            low_percentage=0.20,
            low_foreground=colors[3],
            update_delay=15,
            format='{percent:.0%}', # '{watt:.1f}W'
        ),
        widget.Clock(
            foreground = colors[2],
            background = colors[5],
            format =  "%a %d/%m %R", #"%A, %B %d - %H:%M ",
            mouse_callbacks = {'Button1': lambda: send_notification('calendar',' "$(cal -3)"')},
        ),
            ]
    return list(widgets_list)

def init_screens():
    return [Screen(left=bar.Bar(widgets=init_widgets_list(), opacity=1.0, size=40, margin=[0,5,0,0])),
            Screen(left=bar.Bar(widgets=init_widgets_list(), opacity=1.0, size=40, margin=[0,5,0,0]))]
```

There's nothing in my qtile log except some restart messages:

```
2022-06-22 11:59:07,922 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-06-22 11:59:34,592 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-06-22 12:09:48,848 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
```

(I don't know what hook to subscribe to with what function to get relevant messages in the log for this bug.)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the detailed post. I'll try to take a look later and see if I can recreate.

**Comment by elParaguayo** [comment]
Interesting - those are widgets with variable lengths which would cause the whole bar to be redrawn when they're updated.

Does the same happen with a horizontal bar? There's a bit more work needed to make text display on a vertical bar but I'd hope it wouldn't make too much of a difference.

**Comment by elParaguayo** [comment]
I just tried this very quickly now using your widgets config. I don't get any flickering at all. 

I can't see any real reason for the flicker other than, when redrawing the bar, there are a few more steps (compared to a horizontal bar) which might introduce a slight delay.

**Comment by karthink** [comment]
I'll try stripping out more stuff until I can find a small configuration that still gives me this problem. Is there a way run Xephyr with qtile pointed to a custom config file?

**Comment by elParaguayo** [comment]
Yes. Not sure how you're starting xephyr but you should just be able to change the config file that's referenced in that script (i.e. `qtile start -c /path/to/config`)

**Comment by karthink** [comment]
I'm starting it from the xephyr script, so this should be fine for testing configs. Thank you, I'll do some testing.

**Comment by elParaguayo** [comment]
@karthink any update on this?

**Comment by karthink** [comment]
I still observe flickering in vertical qtile bars in both a regular session and in Xephyr. I haven't had time to create a minimal config to reproduce this yet, please leave this issue open for a bit longer.

**Comment by musjj** [comment]
I also still ocassionaly observe flickering even in horizontal mode.

**Comment by ervinpopescu** [comment]
Please check out #4433 for a potential solution.

**Comment by musjj** [comment]
It looks like that my build was one whole commit too old, thanks for the heads up! So far, no flickers.
