### ISSUE TITLE
signal-desktop sometimes messes up mouse clicks/focus on wayland backend.

### ISSUE THREAD

**Issue by CharString** [qtile/qtile#3654]
### The issue:

qtile version 0.21.0 with Wayland backend.

Sometimes mouse clicks will go to a different group. It seems connected to the signal-desktop, because closing it will resolve the issue when it occurs. Moving the window to the same group and cycling layouts can help too.

I'm sorry. I know this is a very vague description. Any pointers on how to proceed with debugging this behaviour or at least coming to a better bug report are welcome.

I checked other issues and this may be a duplicate of one of these (but I'm unsure): #2795, #3594, #3596

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Please could you test to see if the issue persists on master?

**Comment by CharString** [comment]
Seems to be solved in 0.21.1.dev74+gc16f96d5!

I had some trouble getting master to run on my mixed Debian Bullseye/Bookworm installation. I'm unsure whether it was pywlroots, pywayland or xkbcommon wheel (I install pywlroots, and let it get the other packages through its dependencies.) And I don't know why. I guess one of the libs broke its abi or something in a minor release. Installing with
```
pipx inject --pip-args "--no-binary :all: --no-cache-dir" qtile pywlroots
```
made sure everything was built against my installed libraries.

These were my errors, just for completeness and the small chance that anyone else bumps into this and, like me, finds mostly Wine threads when searching the web for them.

```
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
libGL: Warning in /usr/share/drirc.d/00-mesa-defaults.conf line -1, column -1: unknown application attribute: executable_regexp.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
MESA-LOADER: failed to open i965: /usr/lib64/dri/i965_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: i965
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
00:00:00.070 [ERROR] [render/allocator/gbm.c:198] gbm_create_device failed
```

**Comment by m-col** [comment]
That's unfortunate, I haven't seen those errors before, and installation via pywlroots and its dependencies should work fine (no minor releases of pywlroots of the current release have been backwards-incompatible). Regardless, thanks for the update, I'm glad it's working now.

**Comment by cr1ogen** [comment]
> Seems to be solved in 0.21.1.dev74+gc16f96d5!
> 
> I had some trouble getting master to run on my mixed Debian Bullseye/Bookworm installation. I'm unsure whether it was pywlroots, pywayland or xkbcommon wheel (I install pywlroots, and let it get the other packages through its dependencies.) And I don't know why. I guess one of the libs broke its abi or something in a minor release. Installing with
> 
> ```
> pipx inject --pip-args "--no-binary :all: --no-cache-dir" qtile pywlroots
> ```
> 
> made sure everything was built against my installed libraries.
> 
> These were my errors, just for completeness and the small chance that anyone else bumps into this and, like me, finds mostly Wine threads when searching the web for them.
> 
> ```
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
> libGL: Warning in /usr/share/drirc.d/00-mesa-defaults.conf line -1, column -1: unknown application attribute: executable_regexp.
> libGL: Can't open configuration file /etc/drirc: No such file or directory.
> libGL: Can't open configuration file /home/chars/.drirc: No such file or directory.
> MESA-LOADER: failed to open i965: /usr/lib64/dri/i965_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
> failed to load driver: i965
> MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
> failed to load driver: kms_swrast
> MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
> failed to load swrast driver
> 00:00:00.070 [ERROR] [render/allocator/gbm.c:198] gbm_create_device failed
> ```

Hello, those MESA-LOADER errors appear to me, could you tell me how you solved it? Thank you very much!!

**Comment by CharString** [comment]
@cr1ogen

> pipx inject --pip-args "--no-binary :all: --no-cache-dir" qtile pywlroots

So basically I tell pip to not install the wheels or binary packages for pywlroots and its dependencies. Make sure you have the libraries and their header files installed. Header files are distributed on Debian in the '...-dev' packages. I think it's '...-devel' on Fedora.

**Comment by cr1ogen** [comment]
Thank you! I use Debian too.
