### ISSUE TITLE
Battery widget goes over 100 percent

### ISSUE THREAD

**Issue by smjt2000** [qtile/qtile#3665]
### The issue:

I'm not good in English.
version : 0.21.0

I'm using Qtile on ArtixLinux with OpenRC.
using battery widget on my bottom panel, when laptop is charging, percentage of widget goes over than 100.
![qtile-battery](https://user-images.githubusercontent.com/60272086/176242653-55dfb869-37bb-4d2a-8279-7d06de237ce0.png)
now it's stuck on 117%, but I saw it goes over than 130%

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by kaistian** [comment]
The widget takes the content of `/sys/class/power_supply/BAT0/energy_now` and divide it by content of  `/sys/class/power_supply/BAT0/energy_full`

So you battery management system(BMS) is reporting some wrong number.
You can probably fix it with drain the battery completely and then charge it to full so the BMC learn the capacity of the battery.

**Comment by elParaguayo** [comment]
@smjt2000 has this fixed your issue? can we close this?

**Comment by elParaguayo** [comment]
Closing for now but please reopen if you have further questions.
