### ISSUE TITLE
Qtile shell should better handle exceptions

### ISSUE THREAD

**Issue by Malex** [qtile/qtile#3668]
### The issue:

I was playing around with the qtile shell, specifically I was exploring the folder structure.
When I tried to ls a folder defined as None, the shell broke down and dropped me back to the terminal.

I think the exception should be catched, the error message shown but to keep being in the the shell.

Here's the example:
`bar[bottom] > ls widget/
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.21.0', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/shell.py", line 36, in qshell
    qsh.loop()
  File "/usr/lib/python3.8/site-packages/libqtile/sh.py", line 360, in loop
    val = self.process_line(line)
  File "/usr/lib/python3.8/site-packages/libqtile/sh.py", line 317, in process_line
    val = builtin(args)
  File "/usr/lib/python3.8/site-packages/libqtile/sh.py", line 236, in do_ls
    objects, items = self._ls(node, rest_path)
  File "/usr/lib/python3.8/site-packages/libqtile/sh.py", line 127, in _ls
    str_items = [str(i) for i in items]
TypeError: 'NoneType' object is not iterable
`
I dont have a bottom bar (it's on the top)

Qtile version is 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
How did you navigate to `bar[bottom]` if you don't have a bottom bar?

At the moment, I can't recreate this.

**Comment by Malex** [comment]
I just checked my configuration, I have a something on the bottom: a
bar.Gap(45)

I guess that's the reason, although it's kinda weird, Bar inherits Gap, not
viceversa

Il mer 29 giu 2022, 22:32 elParaguayo ***@***.***> ha scritto:

**Comment by elParaguayo** [comment]
Ah. That makes sense. That's definitely something I can work with.

As for the inheritance, it's the right way round. Gap reserves space in the screen, Bar goes further and draws a bar in that gap.

Will work on a fix for this.

**Comment by Malex** [comment]
> Ah. That makes sense. That's definitely something I can work with.
> 
> As for the inheritance, it's the right way round. Gap reserves space in the screen, Bar goes further and draws a bar in that gap.
> 
> Will work on a fix for this.

No I understand Bar inherits Gap, the weird thing to me is that qtile shell "see" the Gap as a Bar when, in fact, it's not, being a superclass

**Comment by elParaguayo** [comment]
Ah, yes, I understand exactly what you mean now. Agreed, that is a bit confusing.

**Comment by m-col** [comment]
Interesting, turns out `Gap` is a command object, and it even has an `info()` command. This seems kinda useless, so maybe we can move `CommandObject` inheritance to `Bar` and hide `Gap` from all of the command logic. What do you think @elParaguayo?

**Comment by elParaguayo** [comment]
Agreed - I think that's the right approach.
