### ISSUE TITLE
Curent Layout Icon foreground color

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#3669]
### The issue:

The widget currentLayoutIcon is nos using the foreground color assigned, is always white

Qtile Version 0.21.0

Thanks

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
For this widget `foreground` only sets the text colour (text is shown as a fallback if the widget can't find any icons).

However, it would be very simple for me to add a version of this widget to [qtile-extras](https://github.com/elParaguayo/qtile-extras/) where you can set the icon colour. Might have time to knock that out today.

**Comment by elParaguayo** [comment]
Just dealing with some test failures (which I think are unrelated to this) and will look to merge it after that.

**Comment by elParaguayo** [comment]
This has been merged in qtile-extras now. Closing here.
