### ISSUE TITLE
flashfocus autostart issue after relogging

### ISSUE THREAD

**Issue by ashroyxi** [qtile/qtile#3671]
### The issue:

Qtile Version 0.21.0
OS: Garuda (Arch-based)

in autostart.sh I tried both "flashfocus &" / "run flashfocus &"
it works if I restart my machine. but if I relogging it won't start automatically. I have to kill the process and rerun flash focus. cause it shows that another process is already running. 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Try adding `pkill flashfocus` before `flashfocus &`
