### ISSUE TITLE
CurrentLayoutIcon scaling

### ISSUE THREAD

**Issue by rebdeg** [qtile/qtile#3672]
### The issue:

Arch Linux, latest Qtile version.

Widget.CurrentLayoutIcon. displays way too big builtin icons. Scaling=x does not change the size of the  icon, wahtever value I use.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Jareng** [comment]
works for me.
the option to reduce the size is scale=x not Scaling=x
for example if you want to reduce to half the size you add scale=0.5
this is what i use
```python
CurrentLayoutIcon(
    custom_icon_paths=[
        os.path.expanduser("~/.config/qtile/icons")
    ],
    scale=0.6,
),
```

**Comment by rebdeg** [comment]
This is what I  use:
widget.CurrentLayoutIcon(padding=15,scale=0.6),

Changing the scale=x does not change anything. Changing the padding=x does change the padding. Any suggestions?

**Comment by Jareng** [comment]
I don't know, i just tried
`widget.CurrentLayoutIcon(padding=15,scale=0.6),` 
in my config and it works for me

maybe look at your "widget_defaults" or try scale=0.1 to see if there is really no difference

**Comment by rebdeg** [comment]
I tried scale=0.1 and scale=10.0, but whatever I do it does not change my icon size. Changing padding=x in the same line does change the padding. So it is only scale=x the is not working.
Widget_defaults checked, but no effect.

**Comment by Jareng** [comment]
show your full config

**Comment by rebdeg** [comment]
[config.txt](https://github.com/qtile/qtile/files/9034387/config.txt)

**Comment by rebdeg** [comment]
config.txt is my config.py

**Comment by elParaguayo** [comment]
Ah. You're using qtile-extras to import all widgets and there's a custom version of CurrentLayoutIcon there which is what you're using.

Looks like that's a bug in that widget so, we need to close this one and I'd be grateful if you could open a new issue on the qtile-extras GitHub page.

If you want the widget to work in the meantime then make sure you use the libqtile.widget version.

**Comment by rebdeg** [comment]
Noob's question: how can I make qtile use the libqtile.widget version and not the qtile-extra version?

**Comment by elParaguayo** [comment]
Given that you've used the `widget` name for qtile-extras, you could do:
``` python
import libqtile.widget

libqtile.widget.CurrentLayoutIcon(...)
```

**Comment by rebdeg** [comment]
Thanks, fixed!! Great support!!
