### ISSUE TITLE
Fish shell

### ISSUE THREAD

**Issue by rebdeg** [qtile/qtile#3676]
### The issue:

When I change my default shell to 'fish' lazy.shutdown() freezes the system on the current wallpaper. Changing it back to 'bash' makes lazy.shutdown() work ok.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by SweepingBishops** [comment]
Did some tests, but am unable to reproduce the issue.

**Comment by rebdeg** [comment]
Thanks, I removed fish and changed my shell to bash. Will try again one of these days.

**Comment by elParaguayo** [comment]
So, can we close for now then?

**Comment by SweepingBishops** [comment]
> So, can we close for now then?

Fine by me.

**Comment by rebdeg** [comment]
For now that seems the most logical next step thanks for your help!
