### ISSUE TITLE
Systray: icons not showing for AppImage applications

### ISSUE THREAD

**Issue by KMIJPH** [qtile/qtile#3677]
### The issue:

Couldn't find any information on this. When starting AppImage applications, icons won't show in the systray. All the other icons are displayed normally (eg: `nm-applet`, `steam`).

I know these work in other WMs.

Tested on Xorg (`widget.Systray()`) and Wayland (`widget.StatusNotifier()`).

`qtile --version`
> 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by KMIJPH** [comment]
Yes, I've been running i3 and sway for the last year or so and just switched yesterday :) I'm just asking out of curiosity. There's no log message or anything I can provide unfortunately.

**Comment by elParaguayo** [comment]
Great - just wanted to check.

Will need to do some research. I don't use AppImage or have a system tray so this will be interesting!

**Comment by KMIJPH** [comment]
Just checked again. On Wayland, `widget.StatusNotifier())` seems to display them!

**Comment by elParaguayo** [comment]
`StatusNotifier` also works on X11.

**Comment by KMIJPH** [comment]
But `StatusNotifier` isn't clickable as far as I understood, right? At least we know that only `Systray` seems to be having this problem.

**Comment by elParaguayo** [comment]
What do you mean "clickable"? The default action (which, I think, activates the app) should work. If you mean menus, then you need this: https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#statusnotifier

Also, system tray and status notifier are two, completely different specifications. The apps may just not be designed to work with system tray as it's an old, outdated specification.

**Comment by KMIJPH** [comment]
Ah, alright I see. I have some other problems with that `StatusNotifier`, but I'll post that on your qtile-extras repo. Thank you!
