### ISSUE TITLE
XWayland: Android Studio context menus flash for a split second and disappear

### ISSUE THREAD

**Issue by arjan-s** [qtile/qtile#3678]
### The issue:

Context menus (and for instance the file selection menu opened by double shift press) appear and immediately disappear again.

Qtile version: current master

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by TinyAtoms** [comment]
I want to add that this is also present in clion and pycharm in the current master version of qtile.

**Comment by m-col** [comment]
Related sway issues: https://github.com/swaywm/sway/issues/4370, https://github.com/swaywm/sway/issues/5414, https://github.com/swaywm/sway/issues/3007

**Comment by m-col** [comment]
I believe this is fixed now but please re-open if not.
