### ISSUE TITLE
Qtile on Ubuntu 20.04 with Python 3.8.12

### ISSUE THREAD

**Issue by Meresmata** [qtile/qtile#3686]
### The issue:

I wanted to start Qtile with 'Qtile start' installed with pip. Pip install Qtile 0.21.
Start resulted the message that there is 'No DISPLAY set' . So I checked with 'qtile check', that there is LazyCommandainterface missing in libqtile.lazy.
Then in uninstalled qtile from git and tried to install from source.
This did not work,  too.  It askesme to install the a newer xcffib from. I have a much newer  one and reinstall cairocffi.
Is there chance, that there are a Ubuntu installed packages that are used instead of pip packages, that are to old? 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Meresmata** [comment]
I was now able to install Qtile from source after I remove the Ubuntu packages of cairocffi und xcffib. I updated pip (just looks better)  and removed the cache of pip than reinstalled pip's cairocffi. Still this Qtile 021.1.dev75 results in the error that lib Qtile is only partially initialized.

**Comment by elParaguayo** [comment]
Can you paste the full error message here?

**Comment by Meresmata** [comment]
I am using the laptop in boot to terminal mode, to test Qtile so I try my best to tip most stuff:

Qtile start:... last error line in ~ /anaconda3/lib/python3.8/site-packages/qtile/backend/x11/cory.py, line 82, in  __init__  raise QtileError(No DISPLAY set).
qtile start -b wayland got stuck and Nothing works any more (needs a hard reset)
qtile check: error: Co fig failed to import name 'LazyCommandInterface' from partially initialized module libqtile.lazy' (most likely due to a circular problem) (~/anaconda3/lib/python3.8/site-packages/libqtile/lazy.py) 

Stub: at line 1
MypyFile:1(
/tmp/tmp04o04oOel1o/config.pyi)
Runtime:
MISSING

**Comment by elParaguayo** [comment]
How are you starting qtile?

**Comment by Meresmata** [comment]
For testing I start into the terminal with setting Linux startup option to 3. Then l log in, and call 'Qtile start'

**Comment by elParaguayo** [comment]
That won't work as there's no X server running at that point. I use `startx` from a terminal - see https://wiki.archlinux.org/title/Xinit.

And I have this line at the end of my `~/.xinitrc` file: `exec /usr/bin/qtile start -l WARNING`.

Alternatively use ` .desktop` file and start qtile from your session manager (if you're using one).

**Comment by Meresmata** [comment]
'startx' starts but then I get the message : 'xinit: connection to x server lost'.

I don't have a ~/xinitrc and also no /etc/X11.

I only to that stuff, because my .desktop file does not work and I wanna figure out why.

**Comment by elParaguayo** [comment]
Have a look at the configuration section here: https://wiki.archlinux.org/title/Xinit#Configuration

Copy the default `.xinitrc` file and add the line from my earlier comment at the end.

**Comment by elParaguayo** [comment]
Can you do `dpkg -S $(which startx)` to see which package installed `startx` and then do `dpkg-quey -L <package name>` to show all files installed by that package.

**Comment by Meresmata** [comment]
Ah. Okay I did find X11 it was not in the list where would have expected it (at the end,  because its a Capital X).

So, I could copy that .xinitrc.  Tried adding:

exec ~/qtile start -l WARNING or
exec ~/qtile/bin/qtile start -l WARNING

BUT starting start with that still results in the same issue that the connection is lost.

start is part of xinit.

**Comment by elParaguayo** [comment]
Where is your qtile installed? Those paths look odd.

**Comment by Meresmata** [comment]
'which qtile' points to ~/anaconda3/bin/qtile

I would prefer to be able to run a desktop file. Mine looks like:

[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=Qtile start
Type=Application
Keywords=wm;tiling

**Comment by elParaguayo** [comment]
Exec would probably need to be `/home/your_user_name/anaconda/bin/qtile` but it definitely shouldn't have a capital `Q`.

**Comment by Meresmata** [comment]
Okay I updated the desktop file. QTILE starts. The bar looks a bit off, but this might be some missing 3rd party dependencies. I have to look at it some other day.

**Comment by elParaguayo** [comment]
Great.

If there are issues with the config, please start a new issue.

**Comment by Arrowsome** [comment]
Same issue on Debian and Ubuntu (Regolith)

```bash
sudo pip install xcffib
sudo pip install qtile
```

```bash
# /usr/share/xsessions/qtile.desktop

[Desktop Entry]
Name=Qtile
Comment=Qtile window manager
Exec=python3 /usr/local/bin/qtile start
Type=Application
```
No Display Set error.
