### ISSUE TITLE
Discord not unfocusing

### ISSUE THREAD

**Issue by ThatOneOcto** [qtile/qtile#3689]
### The issue:

I'm having this issue from bspwm https://github.com/baskerville/bspwm/issues/811
It was working when I installed qtile but now it doesn't work, I don't know why

ver: 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you provide steps for recreating this on qtile so I see if I can recreate the issue?

**Comment by ThatOneOcto** [comment]
It just happened, if I didn't know why it happened I wouldn't know how to reproduce but it seemed to fix itself after an update
