### ISSUE TITLE
`widget_defaults` settings get ignored.

### ISSUE THREAD

**Issue by jasper-schnabel** [qtile/qtile#3691]
### The issue:

Hello,
I wanted to set the font and the fontsize as a default for all widgets via `widget_defaults`, but it didn't work. I expected it to work, because if I set the font in the widget itself it works, see the screenshot.

`Version:` 0.21.0

`Config:`

```python
# statusbar config
from libqtile.config import Screen
from libqtile import bar, widget, qtile
import os, subprocess

# defaults
widget_defaults = dict(
  font="Ubuntu Mono Nerd Font",
  fontsize=18,
)

extension_defaults = widget_defaults.copy()

screens = [Screen(
  top = bar.Bar([
    widget.GroupBox(
      highlight_method = "line",
      background = colors[0],
      highlight_color = colors[0],
      block_highlight_text_color = colors[5],
      active = colors[1],
      borderwidth = 0,
      padding_x = 18,
      disable_drag = True,
      hide_unused = True
    ),
    widget.CurrentLayout(
      font="Ubuntu Mono Nerd Font",
      fontsize=18,
    ),
  ],
    size = 40,
    background = colors[0]
  )
)]
```
![screenshot_2022-07-10_14:33:53](https://user-images.githubusercontent.com/67754783/178145146-5bc4e147-f497-45b0-b3d2-a8b2cba15928.png)

Thanks

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by kaistian** [comment]
`widget_defaults` is just a variable with some content that you happen to call default, but that doesn't mean that is automatically applied to the widgets.
So you need to use this variable in widget configuration like so.
```
...
      disable_drag = True,
      hide_unused = True,
      **widget_defaults
    ),

**Comment by jasper-schnabel** [comment]
Sorry that was my mistake that makes sense of course, many thanks for the quick reply.
Thank you :+1:

**Comment by elParaguayo** [comment]
> `widget_defaults` is just a variable with some content that you happen to call default, but that doesn't mean that is automatically applied to the widgets. So you need to use this variable in widget configuration like so.
> 
> ```
> ...
>       disable_drag = True,
>       hide_unused = True,
>       **widget_defaults
>     ),
> ```

That's not actually true.

`widget_defaults` is a special variable name which is used to set values for all widgets but can be overriden by setting those parameters directly in the widget.

@jasper-schnabel - in your screenshot, were you expecting `GroupBox` to have the same font and fontsize?

**Comment by jasper-schnabel** [comment]
Yes I expected it, because I saw `widget_defaults` being set in other configs and they didn't call it in the widgets config via `**widget_defaults`.

**Comment by cronyakatsuki** [comment]
My bar also stopped following widget_defaults settings just the orher day for some reason.
Bar [config](https://github.com/cronyakatsuki/dots/blob/main/.config/qtile/bar.py).
It doesn't follow neither the fonts config,size or the foreground/background colors

**Comment by elParaguayo** [comment]
I assume this is the same thing that was just posted on Reddit.

There have been no updates recently that would make this stop working so you must have changed something. 

Unless I'm being blind, I don't actually see the defaults defined in config.py. Have you moved them to a different file?

**Comment by cronyakatsuki** [comment]
They are in bar.py, I could try setting them in config.py but the used to work that way a couple of days ago and after trying the wayland backend they got broken in both x11 and wayland.

**Comment by cronyakatsuki** [comment]
Oh thank you, I used to set them in bar.py and it worked.
That config was about 1+ year old so there maybe was some changes, either way sorry for the problems.

**Comment by elParaguayo** [comment]
There were no changes. Setting in bar.py is fine.

Your problem was when you tried Wayland with this commit: https://github.com/cronyakatsuki/dots/commit/43b3ad223e242ea364c60487bce75b504f1f3f40

You changed this line:
``` python
from bar import screens, widget_defaults
```
to this:
``` python
from bar import screens
```
That's what broke it.
