### ISSUE TITLE
Notifications broken in Qtile on Fedora 36

### ISSUE THREAD

**Issue by rockhazard** [qtile/qtile#3703]
### The issue:

I get the following error while in a Qtile session when using notify-send:

```shell
$ notify-send "Test" "This is a test"
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```
Expected behavior is for a notification box to pop up displaying the message, but I only get the noted error.

This error does not happen in Cinnamon on the same installation of Fedora 36, where the notification pops up just fine, so I don't see it being external to qtile and/or dbus-next.

Dbus-next is installed:

```shell
$ pip3 list | grep dbus
dbus-next 0.2.3
dbus-python 1.2.18
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Do you have any notification serve running e.g. the `Notify` widget or a third party app like `dunst`?

**Comment by rockhazard** [comment]
Okay. That solved the problem. Thanks, @elParaguayo! 
Although it is strange that it works fine on my Linus Mint 20.2 despite not having installed a separate notification server there. I don't know if Mint has one installed by default, given that the Fedora's Cinnamon spin apparently doesn't (even though notifications work within Cinnamon), but I never had to deal with it. That is a mystery. I'll have to look into it.

**Comment by elParaguayo** [comment]
A desktop environment could well have it's own built-in notification server so it probably doesn't need anything additional installed.

Glad it's working for you.

**Comment by rockhazard** [comment]
Thank you, @elParaguayo.
