### ISSUE TITLE
Wayland: Alacritty app_id not recognized

### ISSUE THREAD

**Issue by 3nprob** [qtile/qtile#3705]
### The issue:

Seeing how different terminals behave in a dropdown:

* kitty: Works normally
* foot: Works normally
* Alacritty: Gets treated as a normal window, not matched.

So, attempting to match via app_id:

```
DropDown('term', 'alacritty --class foo,foo', match=Match(wm_instance_class='foo'))
```

This does not work either - same behavior. A closer look in `qtile shell` confirms that qtile returns the window `wm_class` as `None` for Alacritty, but correctly for the other terminals.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What's the actual issue? Alacritty runs fine in a dropdown for me with no need to change class or add a match rule.

Works fine on wayland and x11.

**Comment by 3nprob** [comment]
As in PR description, alacritty (0.10.1) in a dropdown does not work in wayland here (nixos). It opens and behaves as a normal window.

Which alacritty version are you on? 0.10.0 did some architectural changes wrt windows/processes.

#3704 fixes this for me.
