### ISSUE TITLE
mouse drag without modifier makes click not work

### ISSUE THREAD

**Issue by changsijay** [qtile/qtile#3710]
### The issue:

- Qtile version: 0.21.1.dev75+g6620786f

in my config.py I am trying to make mouse drag a  floating window to change its position without modifiers.

```py
mouse = [
    Drag([],
         "Button1",
         lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod],
         "Button3",
         lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
]
```

tho when I drag a floating window, it does move it properly.
However, any clicking on a floating window will not work, ex: click tabs in chrome.

not sure if the detection of `drag` or `click` have some issue
or if I can define what is a `drag`? say long press `button1`  more than 2 seconds and move (change x, y) as a `drag`?
ex: change some logic in `process_button_motion` or `process_button_click`?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
With a modifier, that code works fine for me (I have those lines in my config).

I could be very wrong but I suspect that trying to do it without modifiers could cause an issue as qtile will try to grab the mouse pointer if it matches the relevant conditions. So, every time you click a button, qtile would try to grab the pointer.

Let me investigate a bit.

**Comment by changsijay** [comment]
oops sorry, my config should remove the modifier to match my question
I've tried to understand the logic to detect a `drag` or `click` but didn't clear out yet.

**Comment by elParaguayo** [comment]
It's triggered on a button press. Qtile then checks whether the combo matches a `Click` or `Drag` object in your config and, if it does, it grabs the pointer.
https://github.com/qtile/qtile/blob/6620786f801f56fc61716514139044108eaef743/libqtile/core/manager.py#L707-L733

**Comment by changsijay** [comment]
just tested and log this part, if no modifier, 
when I just pressed left button, (without moving mouse or release button)
it immediately goes to `elif isinstance(m, Drag): `

**Comment by elParaguayo** [comment]
Exactly. And the end of that block is `self.core.grab_pointer()`.

You could try changing `handled` to `False` but I suspect you'll end up with some odd behaviour if you do that.

**Comment by changsijay** [comment]
after changing handled to False, it comes some error
```
$ tail -f ~/.local/share/qtile/qtile.log
  File "/home/csj/.pyenv/versions/3.10.5/envs/qtile/lib/python3.10/site-packages/libqtile/widget/base.py", line 756, in on_done
    self.update(result)
  File "/home/csj/.pyenv/versions/3.10.5/envs/qtile/lib/python3.10/site-packages/libqtile/widget/base.py", line 659, in update
    old_width = self.layout.width
  File "/home/csj/.pyenv/versions/3.10.5/envs/qtile/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/home/csj/.pyenv/versions/3.10.5/envs/qtile/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```
but still works same behavior, click not work and when I clicking it still goes to `isinstance(m, Drag)`
will study how it is `isinstance(m, Drag)` instead of `isinstance(m, Click)`

**Comment by elParaguayo** [comment]
It's going to `Drag` because it's checking what's in your config. It looks for `Click` and `Drag` objects and sees if the button matches the pressed button.

There's no magic to drag other than `Click` objects take priority over `Drag` ones.

**Comment by changsijay** [comment]
got it, checked `self.mouse_map` too

```
{1: [<Drag ([], Button1)>], 3: [<Drag (['mod4'], Button3)>]}
```

so the `drag` is not as I expected, thought it treat it as drag if key held and there is mouse movement happened after.

**Comment by elParaguayo** [comment]
Is there anything else you need here or can we close this?

**Comment by changsijay** [comment]
i got the logic and config, let me close it , thanks
