### ISSUE TITLE
Gamescope changes size after changing groups

### ISSUE THREAD

**Issue by tralph3** [qtile/qtile#3714]
### The issue:

I use gamescope to play most of my games since it fixes many problems tiling WMs may have with game windows. Problem is, on Qtile, if you change to a different group and come back, the gamescope window will be shrinked to the top left corner, and to fix it you have to unfullscreen it, and fullscreen it again. It's kind of annoying really. I have used other WMs like Xmonad or Awesome, and this doesn't happen on them.

https://user-images.githubusercontent.com/41462117/179572900-d8893515-035b-46fa-9889-96a06ef6156e.mp4

I don't know if it's very clear on the video, but you can see me change between two groups. If I come back to the "game" group, the window has been shrinked for some reason. Ideally, it should just stay in fullscreen mode.

My qtile version is 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Is this on Wayland or X11?

**Comment by tralph3** [comment]
X11

**Comment by tralph3** [comment]
Today I remembered I had opened this issue. And I had forgotten because it's not happening anymore. I guess it was fixed in version 22. Great work guys!
