### ISSUE TITLE
Floating windows don't move when workspace changes monitor

### ISSUE THREAD

**Issue by Douile** [qtile/qtile#3716]
### The issue:

# What happened
When you have a workspace with layout.Floating selected the windows within will not move to the correct monitor when the workspace is moved, instead they remain on top of the workspace that replaces the moved one.

# Expected behavior
The windows remain in the same relative position for the workspace but move to the correct monitor.

# Meta
Version: 0.21.0

My config in case helpful: https://github.com/Douile/dotfiles/blob/qtile/.config/qtile/config.py

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Douile** [comment]
Unable to redproduce

**Comment by Douile** [comment]
Reproduced with steam. After moving the windows manually it functions as it should.

**Comment by mcnuggetsx20** [comment]
I'd like to confirm that I have this issue as well.

**Comment by elParaguayo** [comment]
Can you create a short video showing this behaviour?

**Comment by Douile** [comment]
https://cdn.douile.com/bb9f955a8f0bf2328c4ea97d6d2aad6fd0d3968d679377350034d9ed735136732d9a1027b2a1f5d21a6c554437a7247bc452e68f591d13abe0efbb880906d8cb/2022-08-01%2021-43-04.webm

**Comment by m-col** [comment]
Hi, sorry @Douile, we should have caught the stalebot here. We've updated its config so it's a bit less trigger happy.

I think I've found your issue though. `layout.Floating` isn't intended to be used in the `layouts` list as a 'proper' layout. 

See https://github.com/qtile/qtile/issues/2088 and the discussion in there for more context. Tl;dr it would be great to have a proper floating layout that users could list in `layouts`, but as of yet nobody has worked on implementing this support. It is important though, so we've kept that issue and the one it links open. I'll close this one in favour of those. In the meantime, your best bet is to just configure the layout and set it to the config variable `floating_layout`.
