### ISSUE TITLE
[Wayland] Ardour issues

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#3718]
### The issue:

I'm running the latest Qtile git master under Wayland. When I run Ardour if i go to the Session menu and click Import or use the shortcut Ctrl + I it opens the import window no problem. But if I close that window and try to reopen it either from the menu or shortcut then no window ever appears again. You then have to quit Ardour and go back in again.
I tested this with sway and plasma and it works perfectly every time.
I don't see anything relevant in my log files either ??

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
I believe this is fixed now but please re-open if not.
