### ISSUE TITLE
[layout] The order of stack panes is lost when qtile is restarted

### ISSUE THREAD

**Issue by DePierre** [qtile/qtile#372]
When using the stack layout, the order of the panes is lost when qtile is restarted.
It only keeps one pane on the left and the others are placed on the right one.

For instance, having the following stack panes (using *toggle_split()*):
![stack_before](https://f.cloud.github.com/assets/923297/2120140/de1fd230-91a1-11e3-838c-4a64d5ff52ba.png)

And restarting qtile (using *restart()*) gives the following:
![stack_after](https://f.cloud.github.com/assets/923297/2120141/e1b7eb94-91a1-11e3-874e-15ed26e30461.png)

**Comment by ramnes** [comment]
It is true for every layouts, not just Stack.

I'm putting this comment here to close the other issue.

**Comment by flacjacket** [comment]
This should be covered by the current serialization scheme, closing for now, if this is still an issue, feel free to re-open
