### ISSUE TITLE
buggy window movement on the floating layout

### ISSUE THREAD

**Issue by mcnuggetsx20** [qtile/qtile#3733]
### The issue:

Moving certain windows like Steam is like delayed and it doesn't respond to the mouse movement very well. I am not really sure what causes those windows to act like that but it is really annoying.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Closing in favour of #3716

**Comment by mcnuggetsx20** [comment]
> Closing in favour of #3716

Well, I think my issue is pretty different. I mentioned a problem with moving the windows with mouse and the way it behaves. Maybe 'laggy' is not the best way to describe it, but still I think it's worth a look from you. If you'd like, I could upload a video to show you what i really mean.

**Comment by elParaguayo** [comment]
Yeah, I think I linked the wrong issue!

There is an open issue about laggy movement in #3680 but not sure if that's the same for you.

I'll reopen but do paste a video too please.

**Comment by mcnuggetsx20** [comment]
https://youtu.be/Xrt4cTTdnLM
Here is the link.

**Comment by elParaguayo** [comment]
Thanks. 

What's the setting you change that removed the problem? I'm watching on my phone so can't make it out!

**Comment by mcnuggetsx20** [comment]
It's the polling rate in polychromatic controller. The higher it gets, the worse the movement is. And sorry for the bad resolution, I didn't know I had to specify my weird format somewhere.

**Comment by elParaguayo** [comment]
If it is the polling rate then it sounds like the same issue as #3680

**Comment by mcnuggetsx20** [comment]
Yeah, looks like so. At least you know there's more people having the issue. Thanks a lot and I hope you can fix it some time in the near future!
