### ISSUE TITLE
rustdesk needs titlebar in window to operate

### ISSUE THREAD

**Issue by etrigan63** [qtile/qtile#3742]
### The issue:

Qtile version 0.21.0

The application rustdesk (an open source alternative to teamviewer/anydesk) needs a titlebar to display controls. I may be barking up the wrong tree, but I thought I would report this here.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
If they are placing their own buttons/controls in the title bar then it isn't a generic desktop title bar that they need, they will be using an API from gnome/kde etc. If you try rustdesk in i3 (which does have title bars) I would expect that you will still not see those controls.

If they are _relying_ on having one of those APIs for core functionality of the program, then they only support few environments. My guess is that they would have a setting to create a small window to contain those controls in the absence of a desktop-provided one. Probably worth asking them about that.

**Comment by elParaguayo** [comment]
If they're using the Global Menu spec then you could try the `GlobalMenu` widget in `qtile-extras`.

**Comment by etrigan63** [comment]
I have opened a ticket on their GitHub and am awaiting a response.

**Comment by etrigan63** [comment]
> If they're using the Global Menu spec then you could try the `GlobalMenu` widget in `qtile-extras`.
> 
> EDIT: See https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#globalmenu

Except the docs never contain a sample implementation for config.py. I added the references, created a decor and the widget crashed.

**Comment by elParaguayo** [comment]
> > If they're using the Global Menu spec then you could try the `GlobalMenu` widget in `qtile-extras`.
> > EDIT: See https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#globalmenu
> 
> Except the docs never contain a sample implementation for config.py. I added the references, created a decor and the widget crashed.

OK - so what does the error in your log file say...? (appreciate this is a different issue to the one posted here so, depending on the problem, we may need to open an issue on the qtile-extras github page)

**Comment by etrigan63** [comment]
> > > If they're using the Global Menu spec then you could try the `GlobalMenu` widget in `qtile-extras`.
> > > EDIT: See https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#globalmenu
> > 
> > 
> > Except the docs never contain a sample implementation for config.py. I added the references, created a decor and the widget crashed.
> 
> OK - so what does the error in your log file say...? (appreciate this is a different issue to the one posted here so, depending on the problem, we may need to open an issue on the qtile-extras github page)

The log said i was stupid. I found the error and fixed it. However, `GlobalMenu` did not rectify the situation as the app is expecting something to be there. It may not be qtile friendly. I sent you a message on discord regarding the CurrentLayoutIcon widget. Please let me know what I can do.

**Comment by elParaguayo** [comment]
`GlobalMenu` was a bit of a long shot. Shame it didn't work here!
