### ISSUE TITLE
Widget box behaving weirdly on dual monitor

### ISSUE THREAD

**Issue by Aneeqasif** [qtile/qtile#3743]
### The issue:

so basically i have same bar set up on two monitors and i am using a widgetbox to hide a widget from qtile extras . expected behaviour is when i expand it on laptop(primary screen it should be shown there and similiarly for monitor)

but its not working like that instead it only shows up on my monitor (inside widget box of monitor when i click there and shows on a bit left on monitor even though i click on laptop's widgetbox to expand

https://github.com/Aneeqasif/qtile_conf

qtile --version                      
0.21.1.dev87+g2ecbb5fd

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. I tried recreating this after the post on reddit. I haven't been able to recreate yet but will keep trying.

**Comment by elParaguayo** [comment]
Is this still an issue in 0.22?
