### ISSUE TITLE
Clock and tzupdate 

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#3746]
### The issue:

qtile version:
0.21.0

These days I need to travel with my system and have the need to update my timezone in order to work with my calendar. I'm using `tzupdate` which easily updates my timezone with one command. 

I'm using the Clock widget in the qtile bar as so:
``` python 
        widget.Clock(format="%A %d %b %Y %H:%M:%S %z"),
```

Updating the timezone with `tzupdate` however does not change the timezone on the Clock widget. It requires restarting qtile in order to get this done. I would expect qtile to poll the current system timezone at each tik.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
This isn't exactly a qtile bug.

If you open an interactive python session and do
```
>>> import datetime
>>> datetime.datetime.now()
### change timezone now with tzupdate
>>> datetime.datetime.now()
```
You will see that the timezone is not updated.

**Comment by m-col** [comment]
Is there no way to get the new time zone though? If we did, we could use https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone in the widget, querying the time in UTC and then rendering it with the timezone with that

**Comment by elParaguayo** [comment]
I think you'd need a third party library which seems excessive for the clock widget.

I don't think datetime handles timezone names.

**Comment by m-col** [comment]
Looks like all the widget needs to do is update `self.timezone` if/when needed. If we want to avoid checking the system timezone on every tick we could either make multiple timezones configurable and then commands to scroll between them (so you could literally scroll on the widget to update it). Or if any of those libraries do support fetching the system timezone and the result does indeed change following tzupdate usage, then we can bind a command to that too, so you just need to click the widget to make sure it's timezone is up to date

**Comment by elParaguayo** [comment]
Ha. Yeah. Been a while since I looked at the code. So the third party libraries are there already. That's good.

Agreed on your approach.
