### ISSUE TITLE
Resize windows in tiled mode like in awesome

### ISSUE THREAD

**Issue by ziimro** [qtile/qtile#3747]
### The issue:

qtile v: 0.21.0

I have read some other issues regarding similar issues like this, what isnt clear to me is if the functionality for resizing windows in tiled mode is implemented yet or not.

If anybody has came with a workaround for this i would appreciate a reply :3 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Currently, you can't resize windows with the mouse without them being turned into floating windows.

some layouts, however, do have commands for growing windows which can be bound to key presses.
