### ISSUE TITLE
Steam: combo box instantly closes

### ISSUE THREAD

**Issue by purplebar0** [qtile/qtile#3761]
### The issue:

Similarly to the experience I had on DWM, combo boxes on the Steam client close as soon as they are created. It appears to be due to Qtile managing focus/window position in ways Steam doesn't expect, with the combo box list being a separate "window" entirely.

Qtile version 0.21.0

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by purplebar0** [comment]
The issue is still present, I don't want this to be deleted.

**Comment by ramnes** [comment]
What is a combo box? How do I replicate the issue?
