### ISSUE TITLE
Chromium and Telegram windows are shifted in Qtile Wayland

### ISSUE THREAD

**Issue by TinyAtoms** [qtile/qtile#3764]
# Problem
Chromium and Telegram windows are shifted towards the bottom-right in qtile. This happens in all layouts.
The problem is not present when logging in Qtile for xorg, and also not present in sway, so I believe it to be a problem specific to Qtile wayland.

## Expected behaviour
This is what I expect normal windows to behave like
![image](https://user-images.githubusercontent.com/44430688/184521192-7b51bb8e-a12e-4ca6-8d95-3f8a35c7a9f4.png)
## Resulting behaviour
This is how Telegram and Chromium behave
![image](https://user-images.githubusercontent.com/44430688/184521207-8bd1b68b-5c50-483f-b056-2df0707e1a4a.png)
It is clearer that they're shifting bottom-right in the image below, where I placed the bar at the bottom, and chromium is overlapping with the bar.
![image](https://user-images.githubusercontent.com/44430688/184521221-7d8d30e8-b6e7-4a6a-abd7-15311e1bf3a0.png)

# Environment
I don't know what information is relevant, and in the interest of being not overly verbose I've only added these. There is no relevant qtile log, since there are no warnings or errors produced for this issue. 

Distro: Arch linux
qtile 0.21.0 
wlroots 0.15.1-6
Dunno if you need these, but here they are
wayland 1.21.0-1 
wayland-protocols 1.26-1
xorg-xwayland 22.1.3-1 
python-pywayland 0.4.14-1 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Do any of the appearance settings within chromium make a difference? Such as the theme or 'Use system title bar and borders'

**Comment by TinyAtoms** [comment]
I can't believe I didn't think of that! That fixed the issue for both chromium and telegram.
The relevant setting in telegram is located in `Settings > advanced > use system window frame`
Thanks!

**Comment by clotodex** [comment]
@TinyAtoms I have the same issue. Asking Telegram to use the system frame just fills the gap with a really ugly white frame. Can that be configure as well? (like in qtile?).

**Comment by clotodex** [comment]
@TinyAtoms @m-col Relaunching Telegram fixed the offset (duh! sorry). Your advice fixed all issues for me. Feel free to close this issue.

**Comment by TinyAtoms** [comment]
Do we know what's causing the issue? What is the common factor between telegram and chromium?

**Comment by clotodex** [comment]
Maybe these are some pointers:
[discussion on qtie decoration support](https://github.com/qtile/qtile/discussions/2409#discussioncomment-682619)
[telegram auto defaulting to own decorations if protocol is not found](https://github.com/telegramdesktop/tdesktop/issues/17026) (and maybe they even use an old version of the protocol)?
Don't know enough to come to a conclusion, but maybe that helps you @TinyAtoms

**Comment by m-col** [comment]
> Maybe these are some pointers:
https://github.com/qtile/qtile/discussions/2409#discussioncomment-682619
https://github.com/telegramdesktop/tdesktop/issues/17026 (and maybe they even use an old version of the protocol)?

Yep, we support both protocols so I don't know why telegram isn't showing server-side decorations by default. Perhaps it's to do with the `export QT_QPA_PLATFORM=wayland` they mention in that issue.

> What is the common factor between telegram and chromium?

Is telegram using electron for its GUI? As I understand it chromium and electron share a base and so they'll be using the same code to handle this, or something.

**Comment by TinyAtoms** [comment]
Telegram does not using Electron. They use a  "slightly patched" Qt implementation according to [their readme ](https://github.com/telegramdesktop/tdesktop). This was also a surprise to me, I too assumed that telegram was electron-based untill 5 mins ago.

**Comment by m-col** [comment]
Re-reading this, it's a bug I'm very familiar with and have tried to fix a few times over the past year :laughing: it's very much a bug with qtile and not telegram. It also happens for a short period of time on many GTK windows, before they update themselves and fix it. One window that doesn't fix itself, and it's particularly pronounced in, is `spot`. Check it out:
![image](https://user-images.githubusercontent.com/44536113/198727709-4849bb0f-ee4a-4cc2-985c-8565f9b9ac54.png)
Huge gaps between the borders and the window! I know why it's happening but fixing it in a nice way is not super simple, and I think we should hold off on fixing it until after we use the wlr_scene API in wlroots (coming soon).
