### ISSUE TITLE
QTile crashes on invalid font in widget (tested with PulseVolume)

### ISSUE THREAD

**Issue by clotodex** [qtile/qtile#3766]
### The issue:

When changing the config to a font that does not exist:
- qtile freezes if running (needs sysrq to recover)
- trying to start it results in EGL missing (so qtile starts fine, but e.g. when creating a terminal window with glfw it hard fails and crashes qtile)

Expected behaviour:
- minimum: SOME error message pointing to the config. In both, stdout and qtile.log, there was NO mention of anything going wrong, except for the (in my case kitty) window crashing.
- ideally: Give a notification about a configuration error before applying the configuration

Everything works again if I use a proper font.  
This is not a crucial issue to me, however looking through the other issues, fontmanagement in general is a bit "intransparent" and since I could reproduce this because of a font problem it might be interesting to look into.

qtile version: 0.21.1.dev89+gc8d3aad1
example widget: `widget.PulseVolume(emoji=True, font="source code pro", theme_path=None),`

probably related to and the reason for #2949

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What do you get if you run `fc-match "source code pro"`?

**Comment by clotodex** [comment]
@elParaguayo thanks for following up
I am getting the right font now, `gentoo` had a problem with the source code pro package, which has been resolved now and thus that works.
**However** have you tried setting the font to a non existsing font? e.g. literally to "non existing font"? That is where it crashes for me *without an errormessage*
