### ISSUE TITLE
Transparency on bar not showing on X11, but showing correctly on Wayland

### ISSUE THREAD

**Issue by Oreeeee** [qtile/qtile#3767]
### The issue:

I have a bar with background "2e3440" in which I have some widgets on left and right side of the bar that I separate with a big spacer with the color of "00000000"

Expected behaviour:
- This big spacer with the color "00000000" should be transparent

Actual behaviour:
- The spacer is black, but only on X11, even with compositor (picom) running. On Wayland it it transparent and I can see my wallpaper through it.

Qtile version: 0.21.0
Distro: EndeavourOS

Note that I'm running it in QEMU/KVM with 3D acceleration (Virgl), I haven't tested it on bare metal.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Oreeeee** [comment]
This bug also happens with transparent borders and any widget with transparent background

**Comment by elParaguayo** [comment]
The bar needs to have an alpha value with some slight transparency otherwise transparency is disabled (see the note on [this page](http://docs.qtile.org/en/stable/manual/config/screens.html))

**Comment by elParaguayo** [comment]
Also, transparent borders are not possible on x11.

**Comment by Oreeeee** [comment]
I changed bar background to 2e344000 and the spacer is still black on X11. And yes, transparent borders don't work on Wayland too.

**Comment by elParaguayo** [comment]
I've never used qemu but it's possible that our transparency code doesn't work well with it in x11.  I can send some commands to try to debug this later.

**Comment by Oreeeee** [comment]
Transparency doesn't work on a real machine either

**Comment by elParaguayo** [comment]
Well, it does, because I'm using it!

So, the question is why isn't it working for you?

If you start picom from the terminal, are you getting any error messages?

Anything in the qtile log?

**Comment by elParaguayo** [comment]
What happens if you run `qtile cmd-obj -o bar top -f eval -a "self.drawer._depth"` (changing `top` to whatever position your bar is in)?

**Comment by Oreeeee** [comment]
Executing this command optputs ```(True, '24')```

**Comment by Oreeeee** [comment]
Whole config file is in "dotfiles" repo on my GitHub

**Comment by Oreeeee** [comment]
Okay I'm stupid, I was changing default widget color instead of bar color

**Comment by elParaguayo** [comment]
> Executing this command outputs `(True, '24')`

Well, that's the problem. It's not finding a 32 bit colour depth for your display.

What about `qtile cmd-obj -o cmd -f eval -a "self.core.conn.default_screen._get_depth_and_visual(32)`?

**Comment by elParaguayo** [comment]
Ah, we overlapped on comments. Is it fixed?

**Comment by Oreeeee** [comment]
I'm trying to fix an exception in my config rn

**Comment by Oreeeee** [comment]
Yep, the issue is now fixed
