### ISSUE TITLE
Fullscreen window problem

### ISSUE THREAD

**Issue by mcnuggetsx20** [qtile/qtile#3770]
### The issue:

When I make a window fullscreen (e.g. I maximize a YouTube video) the window freezes. The sound is still there but the window itself is just frozen.

Here is a screenshot of the browser before maximizing:
![image](https://user-images.githubusercontent.com/71185521/184852272-b47d8a21-b997-4f76-8730-32b548085522.png)

And here it is after maximizing:
![image](https://user-images.githubusercontent.com/71185521/184852403-d719790c-092f-4a9e-8b8a-eb9bc6ae83a9.png)

You can see it's bugged and as I mentioned, the video doesn't play, meaning the window itself is frozen. I tried it on different monitors and the issue still occurs. I noticed that switching to a different workspace and then coming back resolves the problem for some windows. 

Qtile version:
0.21.1.dev87+g2ecbb5fd

GPU:
NVIDIA GTX 1660 Ti

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Any messages in your logs (`~/.local/share/qtile/qtile.log`)?

Which backend are you using? wayland or x11?

**Comment by mcnuggetsx20** [comment]
Unfortunately, the logs didn't report anything. I'm using X11

**Comment by mcnuggetsx20** [comment]
Yes, I'm using xcompmgr and everything is fine after I disable it. Maybe you could implement your own compositor for X11?

**Comment by elParaguayo** [comment]
We won't be making a compositor!

Looks like you're running into this issue (or something closely related to it): https://github.com/qtile/qtile/issues/417

**Comment by jwijenbergh** [comment]
Maybe you should try picom?

**Comment by mcnuggetsx20** [comment]
Well, I do know about picom. The thing is, it's bloated and it can't handle two monitors with different refresh rates (it caps both of them to the lower value of the two). Xcompmgr on the other hand doesn't cause any of that issues but you know, there is this problem with fullscreen. It really sucks that nothing works as it should.

**Comment by jwijenbergh** [comment]
The problem is that xcompmgr hasn't been updated in 7 years afaict. See [this thread on bspwm GitHub](https://github.com/baskerville/bspwm/issues/1222) where an user reported it was a xcompmgr issue. But if you don't have this issue with other WMS then it might be a qtile issue

**Comment by TheTerrior** [comment]
> it can't handle two monitors with different refresh rates (it caps both of them to the lower value of the two)

I can safely say this is entirely untrue. I have my main monitor at 165hz and my secondary at 75hz and it is not capping my main one to 75hz. Try switching to picom and see if the problem persists is my recommendation.
