### ISSUE TITLE
Cannot export class instances in qtile.test_data attribute

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3781]
### The issue:

I'm trying some stuff and tried to export `keys` as a value in a dictionary, like this `qtile.test_data["keys"] = keys`.The dictionary already contains the `group_layouts` i use for another thing. That raises this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 121, in unpack
    assert len(data) >= HDRLEN
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ervin/.config/qtile-x11/test_data_testing", line 6, in <module>
    test_data=c.get_test_data()
  File "/usr/lib/python3.10/site-packages/libqtile/command/client.py", line 199, in __call__
    return self._command.execute(self._current_node, args, kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 232, in execute
    status, result = self._client.send((call.parent.selectors, call.name, args, kwargs))
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 171, in send
    return asyncio.run(self.async_send(msg))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 199, in async_send
    data, _ = _IPC.unpack(read_data, is_json=self.is_json)
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 126, in unpack
    raise IPCError("error reading reply! (probably the socket was disconnected)") from e
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```  

`qtile.test_data["keys"] = str(keys)` works fine btw. Gonna try on a fresh default config, to ensure this is not my config's fault (I'd wager highly unlikely but meh). *EDIT*: I was right.

`qtile.test_data = keys` doesn't work either.

This is what I use to get the data:
```
#!/bin/python

from libqtile.command.client import InteractiveCommandClient

c=InteractiveCommandClient()
test_data=c.get_test_data()
print(test_data)
```

`test_data=c.eval("self.get_test_data()")` this also works, but I still get `str` which I can't manipulate to get the objects for some weird reason(neither with json.loads nor with ast.literal_eval).

I can do this differently, I know, but it just `bugs` me ;)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you give more information on what you're trying to do.

I can see references to IPC. That uses JSON so I would not expect it to work with `Key` objects.

**Comment by ervinpopescu** [comment]
> Can you give more information on what you're trying to do.

I was playing around with importing data dynamically from the current qtile instance into scripts, especially stuff I use in the config. I eventually did it by simply adding the config dir to the beginning of `sys.path` (to ensure I get the right thing) and importing the needed stuff (keys and group_layouts in this case).

> I can see references to IPC. That uses JSON so I would not expect it to work with `Key` objects.

Ah, I see. This can be closed then.
