### ISSUE TITLE
[CheckUpdates, doc, Arch] mention `pacman -Sy` is required for `pacman -Qu` to show updated info  

### ISSUE THREAD

**Issue by lrvideckis** [qtile/qtile#3789]
### The issue:

As per title. Maybe this is common knowledge among arch users. I had to spend some debugging time to get the CheckUpdate widget to show updated info, and ended up here

https://www.reddit.com/r/qtile/comments/ur8mz3/comment/i90sa7d/

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
But you shouldn't run `pacman -Sy` without actually upgrading.

You'd be better off installing `pacman-contrib` and using `checkupdates` than riding a partial upgrade.

**Comment by lrvideckis** [comment]
What's the use case for `pacman -Qu` in the widget then? After running `pacman -Syu`, the widget would always show 0 updates.

**Comment by elParaguayo** [comment]
Agreed. I'd be inclined to remove it.

I suspect it's there as it "works" without installing third party packages but checkupdates is by far the better solution, in my view.

**Comment by lrvideckis** [comment]
Also thoughts on making `checkupdates` the default?

**Comment by lrvideckis** [comment]
Maybe the solution is to mention `checkupdates` is the preferred option in the docs (for our reasons), but it requires installing it (and an internet connection). Keep `-Qu` the default.

**Comment by lrvideckis** [comment]
Or actually I think we should remove the `Qu` and only have `checkupdates`

Like the user is already modifying the config to add this widget. And at that moment the user will go to the docs and see that they have to install this for the widget to work. Other widgets already have dependencies which are not installed by default

**Comment by lrvideckis** [comment]
also ditto `pacman -Sup`

**Comment by m-col** [comment]
From what I can tell, https://github.com/qtile/qtile/pull/3785 resolves this issue. Can this be closed? :)
