### ISSUE TITLE
Upgraded from 0.16.1 to 0.21.0; qtile fails to load

### ISSUE THREAD

**Issue by KevinBalkoski** [qtile/qtile#3795]
### The issue:

I recently upgraded from 0.16.1 to 0.21.0. When I tried to log back in, the screen fluttered and it brought me back to my login screen. I've restarted the machine and am getting the same behavior.
I checked the `~/.local/share/qtile/qtile.log ` log and the only potentially relevant thing was:
```
2022-08-25 13:16:17,977 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)
```
I've since tried to:
* Uninstall/reinstall 0.21.0 -> no change
* Tried to re-install 0.16.1 again -> got the error `ffi.error: symbol 'cairo_xcb_surface_create' not found in library 'libcairo.so.2'` despite following [these instructions](https://docs.qtile.org/en/latest/manual/troubleshooting.html#cairo-errors). I recall this being an issue I encountered when I first installed Qtile... but I don't recall how I managed around it.
* Tried to install a few others like 0.17, 0.18, and 0.20 with no success

Any help would be appreciated. I'd prefer to actually upgrade to 0.21, but I'd be at least somewhat satisfied to just get things working again with 0.16.1

#### Environment
OS: Ubuntu 20.04.3; kernel: Linux 5.15.0-46-generic
Python 3.8 installed via Anaconda

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
How are you starting qtile? One of the changes since 0.16.1 was to require the `start` command i.e. `qtile start` rather than the old `qtile`.

**Comment by KevinBalkoski** [comment]
> How are you starting qtile? One of the changes since 0.16.1 was to require the `start` command i.e. `qtile start` rather than the old `qtile`.

That's it! Thanks @elParaguayo

**Comment by elParaguayo** [comment]
Great!

There were some other changes too (notably the formatting of float rules in the config file) so you might hit those at some point.
