### ISSUE TITLE
KDE applications do not redraw properly after qtile restart

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#380]
Having kde apps like kmail running and restarting qtile causes the tray icons to become maximized windows and the client area is not redrawn completely

**Comment by andering** [comment]
Does this mean we can close the bug? :)

**Comment by dequis** [comment]
Nah, should still test it with kde3 stuff

**Comment by dequis** [comment]
Nah, should still test it with kde3 stuff

**Comment by dequis** [comment]
Joking aside, okay, sure.
