### ISSUE TITLE
Clicking blank screen then previous window doesn't focus clicked window

### ISSUE THREAD

**Issue by StevenDoesStuffs** [qtile/qtile#3800]
### The issue:

I have two screens, and `follow_mouse_focus = False`.

Suppose I have two windows on my first monitor, A and B, A is currently focused, and I have no windows on my second monitor.

If I click my second monitor, the focused screen is now my second monitor. 
Interestingly, I can still type stuff in A afterwards, but it doesn't have the focus outline anymore.

Now if I click A, not only does qtile not shift the focus to A (as in no focus outline), my second monitor also remains the focused screen. 
**I expect that if I click A, A should be refocused and that my first monitor is also now focused.**

However, if I click B, everything works as expected. 

However, if I click B, everything works as expected.

I don't see any relevant logs, and I'm running qtile version 0.21.0 on Archlinux. 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report. I can confirm I also see this behaviour.

Will take a look when I can.

**Comment by elParaguayo** [comment]
@StevenDoesStuffs - I've found a solution for this. It feels a bit hacky but I can't pin the exact cause of the issue.
