### ISSUE TITLE
Layout.Next() only works for tiled windows

### ISSUE THREAD

**Issue by DasLixou** [qtile/qtile#3807]
### The issue:

I wanted to also switch between floating and floating windows, and floating and tiled windows, but i can only switch between tiled and tiled windows I think this is a bug.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Not a bug. Floating windows are not managed by the layout so `lazy.layout.next()` won't apply to those windows.

Try `lazy.group.next_window()`. This should cycle through all windows in the current group.

**Comment by DasLixou** [comment]
That kinda works but the floating window hides the content of the tiling window behind it. but when i make the tiling window behind it floating and then tiling again it is in front of the floating window. is there a way to just make the selected to the front?

**Comment by elParaguayo** [comment]
Layering has some bugs in it.

You could add `lazy.window.bring_to_front()` to the same key binding (after the next_window call).

**Comment by DasLixou** [comment]
ah thanks thats what i was searching for :D

**Comment by DasLixou** [comment]
ok now i understand what you ment with has some bugs. when i bring it to the front the other window scales up like the one i did bring to the front were a floating window...

**Comment by elParaguayo** [comment]
Not sure what that means. Can you send a video of the behaviour?
