### ISSUE TITLE
Full screen games do not maximize after getting minimized

### ISSUE THREAD

**Issue by saffanalvy** [qtile/qtile#3808]
### The issue:

Hi. I play Dota 2 in steam which is free. This game launches in full screen mode. After launch if I try to minimize the game by using hotkeys like mod4 + h, j, k, l, the game loses focus and steam windows show up. But if I hit the navigation keys again to get to the game, it plays the sounds and everything which feels like it is focused but it does not maximize or bring forth the game in full screen in the display. In fact, it doesn't even show anything at all except steam or any other app which is opened or desktop.
I'm using the latest version of qtile. However, this problem doesn't occur in any other place like full screen vlc player or full screen youtube videos or etc.
I think it is a bug.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
@saffanalvy Sorry, looks like we missed this one.

You're right, it does sound like a bug. There's an open pull request (#3409) which aims at implementing better handling of window stacking order. This may (or may not) help with this particular issue. However, the PR still has some bugs which need to be sorted.
