### ISSUE TITLE
Bluetooth widget displays adapter name instead of name of connected device

### ISSUE THREAD

**Issue by mrchainman** [qtile/qtile#3816]
### The issue:

version: 0.21.0
log: no relevant log

I configured the bluetooth-widget.
When a device is connected, it shows the adapter name, instead of the device name.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by mrchainman** [comment]
Sure I can test it then

**Comment by mrchainman** [comment]
Update:
I am running 0.21.1.dev106+g5161618c now and the device shows correctly

**Comment by elParaguayo** [comment]
I haven't changed anything yet so I suspect the bug is still there, it's just unexpected that you hit it. 

I'll still work on a fix.
