### ISSUE TITLE
this_screen_border of groupbox is not working 

### ISSUE THREAD

**Issue by dranzer9944** [qtile/qtile#3824]
### The issue:

this_screen_border is not working . i don't know why. can someone explain
 GroupBox(
            font = "JetBrains Nerd Font Mono Bold",
            fontsize = 10,
            padding = 4,
            borderwidth = 2,
            background = dracula["colorback"],
            active = dracula["color7"],
            inactive = dracula["color9"],
            rounded = False,
            ##Block_highlight_text_color = dracula["color3"],
            highlight_method = 'line',
            highlight_color = dracula["colorback"],  #  line block colour
            this_current_screen_border = dracula["color4"],
            this_screen_border = '#FFFFFF',

            urgent_alert_method = 'line',
            urgent_border = dracula["color2"],
            #urgent_text = dracula["color2"],
            disable_drag = True,
        ),
here's the piece of code

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What's not working? Are you getting an error message? Unexpected behaviour?

You need to provide some more information first.

**Comment by dranzer9944** [comment]
not everything is working fine but this variable does not show the color i set

**Comment by elParaguayo** [comment]
Again, not enough information. 

Describe your setup eg how many screens do you have? Describe what you expect to see and what you are actually seeing.

Post a screenshot.

**Comment by dranzer9944** [comment]
yep i have edited the previous text with screenshot

**Comment by elParaguayo** [comment]
That setting does nothing if you have a single screen. It is for indicating group on inactive screen. Your screen is always active as you only have one.

**Comment by dranzer9944** [comment]
then what are these for : 
 "other_current_screen_border" and 
 "other_screen_border"

**Comment by elParaguayo** [comment]
It's for when the widget is on the unfocused screen. From that widget's is on *this* screen. But that screen is unfocused.

"other" screen is for exactly that, a screen that is not the active one.

**Comment by dranzer9944** [comment]
okay. so is there any way to achieve it or available in future.

**Comment by elParaguayo** [comment]
Not currently. The `"line"` option is a highlight method which only applies to visible groups or groups with urgent items.
