### ISSUE TITLE
[Docs] The documentation on the screens_reconfigured hook is inconsistent with the example in FAQs

### ISSUE THREAD

**Issue by keystroke3** [qtile/qtile#3828]
### The issue:
I was looking at the [FAQ section](https://docs.qtile.org/en/latest/manual/faq.html#how-can-i-get-my-groups-to-stick-to-screens) about multi-screen setup and I got confused. The function presented as an example, to dynamically adjust the groups in the bar uses `qtile.screens` but the hook does not pass any arguments according to the [hook's documentation](https://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.screens_reconfigured). If the example function is used as is, the user will get a `NameError` because `qtile` is undefined. Adding `qtile` as an argument to the decorated function does not solve the problem either as that will just throw a `TypeError` for missing positional argument. 

### Proposal 1
Pass the `qtile` object to the hook subscriber. This will make it much easier to perform actions in depending on knowing some property or state of the WM.  Something as simple as getting the number of screens should not be as difficult to figure out  if this is implemented. 
### Proposal 2
Change the documentation to show have a different way of getting the number of screens.  This will get rid of the confusion when someone copy pastes the code in the FAQ and just gets errors. I am personally using a [screeninfo](https://pypi.org/project/screeninfo/)'s `get_monitors()` function to get the number of screens.:
```python
from screeninfo import get_monitors
from libqtile import hooks

@hook.subscribe.screens_reconfigured
async def _():
    if len(get_monitors()) > 1:
        pass
```  

Qtile version: 0.21.1.dev106+g5161618c on Endeavor OS

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
You just need to do `from libqtile import qtile` and `qtile` will then be available in your decorated function.

**Comment by keystroke3** [comment]
Ah, I guess I didn't know that. Thanks for clarifying.
