### ISSUE TITLE
Dynamic screen gap modification takes effect after another command

### ISSUE THREAD

**Issue by Maldus512** [qtile/qtile#3834]
### The issue:

Hello,
I have a conky instance successfully running on the side of my screen, below all other windows. I'd like to dynamically reserve a gap to hide and show conky on the press of a button.

To do so, I've created the following function and shortcut:

```
def toggle_gap(qtile):
    if qtile.screens[0].right.size == 272:
        qtile.screens[0].right.size = 0
    else:
        qtile.screens[0].right.size = 272

#...
    Key([mod], "i", lazy.function(toggle_gap)),
#...
```

This works, but only after another command is issued (e.g. I change the focused window, even if it's the same). It's as if the command was successfully executed but the screen is only updated when another change occurs.

This happens to me with qtile 0.21.0, but works immediately with qtile 0.20.0.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Try this:
```py
def toggle_gap(qtile):
    if qtile.screens[0].right.size == 272:
        qtile.screens[0].right.size = 0
    else:
        qtile.screens[0].right.size = 272
    qtile.current_group.layout_all()
```

I took that layout_all() from this command: https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L1530. I hoped that command  would also work for gaps but it seems it only works for bars. Tbh maybe this could be changed so that you just need to use `lazy.hide_show_bar()` instead of a custom function.

**Comment by Maldus512** [comment]
`qtile.current_group.layout_all()` works even with version 0.21.0, thank you!
