### ISSUE TITLE
Error in website documentation

### ISSUE THREAD

**Issue by traxyax** [qtile/qtile#3835]
### The issue:

I wanted to configure my qtile-wayland input configuration. The InputConfig module in liqtile.wayland.backend library in the website documentation is wrong.
The correct library is liqtile.wayland.backend.inputs.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Hi, thanks for the report. Perhaps you had a typo? The doc here: http://docs.qtile.org/en/stable/manual/wayland.html#libqtile.backend.wayland.InputConfig seems correct. Please could you retry `from libqtile.backend.wayland import InputConfig` and checking that works?

**Comment by traxyax** [comment]
I don't know why but `from libqtile.backend.wayland.inputs import InputConfig` work for me. Perhaps it'is the os. It's related to this
#3447

**Comment by traxyax** [comment]
This is my settings

`
from libqtile.backend.wayland.inputs import InputConfig

wl_input_rules = {
    "*": InputConfig(left_handed=False, pointer_accel=True),
    "type:touchpad": InputConfig(tap=True),
    "type:keyboard": InputConfig(kb_layout="fr", kb_options="ctrl:nocaps"),
}
`

**Comment by m-col** [comment]
Both versions are correct, and both should work (and do the same thing).

**Comment by traxyax** [comment]
It is fixed. My editor highlights this line as an error because this module is not exported by `libqtile.backend.wayland`.It works perfectly.
