### ISSUE TITLE
Bar Window Class

### ISSUE THREAD

**Issue by mrchainman** [qtile/qtile#3838]
Can I somehow add a window class to the bar, so that I can reference it in my picom.conf?

**Comment by elParaguayo** [comment]
This may help: https://github.com/qtile/qtile/issues/2526

**Comment by mrchainman** [comment]
Perfekt

**Comment by mrchainman** [comment]
I am having some issues...
using this hook:
@hook.subscribe.startup
def _():
    main_screen_bar.window.window.set_property("QTILE_BAR", 1)

I get in the logs:
2022-09-17 13:32:46,447 ERROR libqtile hook.py:fire():L406 Error in hook startup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/resources/default_config.py", line 44, in barclass
    main_screen_bar.window.window.set_property("QTILE_BAR", 1)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 331, in set_property
    raise ValueError("Must specify type and format for unknown property.")

Looking at the window.py file, it seems I have to provide a type and format?

**Comment by m-col** [comment]
Try passing `"CARDINAL"` as type and `32` as the format

**Comment by mrchainman** [comment]
Nice now it works, thanks!

**Comment by m-col** [comment]
Great! I'll update my example in that other PR, as I guess it should have raised this error with others too :)

**Comment by mrchainman** [comment]
Awesome :)

**Comment by elParaguayo** [comment]
Should this be in the FAQs?

**Comment by mrchainman** [comment]
Not sure who this question is directed towards, but from a user experience POV it would make sense, maybe on the hacking on qtile page

**Comment by elParaguayo** [comment]
> Not sure who this question is directed towards, but from a user experience POV it would make sense, maybe on the hacking on qtile page

It was for @m-col :smile:

**Comment by m-col** [comment]
Good idea - this is indeed a frequently asked question!

**Comment by m-col** [comment]
https://github.com/qtile/qtile/pull/3842
