### ISSUE TITLE
[Docs] wl_input_rules example in docs is wrong/doesn't work as intended

### ISSUE THREAD

**Issue by npenk** [qtile/qtile#3844]
### The issue:

This example: ` "type:keyboard": InputConfig(xkb_options="caps:swapescape"),` from the docs (https://docs.qtile.org/en/stable/manual/wayland.html) no longer works in Qtile Wayland (0.21.0). `kb_options="caps:swapescape"` does work. I would submit a PR but the file docs/manual/wayland.rst doesn't appear to have all the content that is present on the website.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jx11r** [comment]
Fixed in the latest version: https://docs.qtile.org/en/latest/manual/wayland.html
