### ISSUE TITLE
Disk Free Widget not working

### ISSUE THREAD

**Issue by kraanzu** [qtile/qtile#3845]
### The issue: [Disk Free Widget](http://docs.qtile.org/en/latest/manual/ref/widgets.html#df) returns an empty string on polling

Qtile Version: `0.21.0`
Logs: Does not produce any error in the log

![Error](https://i.imgur.com/DiNqNTf.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Default behaviour is only to show text when the available space is less than the warn space. So, unless your disk is almost out of space, this behaviour is expected.

http://docs.qtile.org/en/stable/manual/ref/widgets.html#df

**Comment by kraanzu** [comment]
Ah, I see. Must've been an update. ( I tried DF some months ago and this wasn't the default behaviour )
Thanks @elParaguayo 😄
