### ISSUE TITLE
LaunchBar not displaying icons despite pyxdg being installed

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#3853]
### The issue:

LaunchBar has some issues to display certain icons.
For example with:
`widget.LaunchBar(progs=[('chromium', 'chromium', 'Launch chromium'),('terminal', 'gnome-terminal', 'Launch gnome-terminal'),]),`
Only chromium icon appears while gnome-terminal is displayed as a text.

One important note: with the Tasklist widget, all my application icons are properly displayed.
Somehow, it seems that the way those two widgets retrieve icons is performed in different way.

Looking at source code of LaunchBar, it seems that .png files are being fetched while my icon theme has .svg file.
Could it be the issue ? (sorry if that's wrong, i'm no dev)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
The rationale for just using PNG files is no longer applicable and qtile can render SVG files. 

Are you able to confirm what `xdg.IconTheme.getIconPath("gnome-terminal")` returns?

**Comment by Crystal4276** [comment]
I found the problem. 
In widget.LaunchBar(progs= ('terminal', 'gnome-terminal', 'Launch gnome-terminal'),]),

The first field 'terminal' must be replaced by the value of  GTK_APPLICATION_ID(UTF8_STRING) as provided by xprop. WM_class doesn't work.
So for the case of gnome-terminal the correct entry is : org.gnome.Terminal
