### ISSUE TITLE
Drawbox width of the Tasklist widget not adjusted depending of icons number + icons not centered

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#3854]
### The issue:
 qtile --version :0.22.1

I wanted to get a tasklist widget with only centered icons and with a widget drawbox adjusted to the number of icon. Instead:
- The icons are placed on the left hand side
- using a non transparent color for the background we can see that the widget is taking more space than necessary.  This prevents the use of RectDecoration (at least to get good cosmetic results).

Ideally the width of the drawbox would be dynamically adjusted depending on the number of icons.

![image](https://user-images.githubusercontent.com/27446196/191791502-4d38c1d0-20fa-4d19-b3f9-225f447214fb.png)

Removal of text was obtained with 
```
def txt_remove(text): 
    text = ""
    return text
```
and in tasklist.widget
` parse_text=txt_remove,`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
If you restore the text, are the icons + text the size of that draw box? If so, we need to factor in the impact of the parse function when calculating the width of the widget.

**Comment by Crystal4276** [comment]
From three tasks i can get the full width filled:
![image](https://user-images.githubusercontent.com/27446196/191805625-d6aae69c-a041-4a9b-98e9-a8875f968b4d.png)

With only two tasks there is still some space left:
![image](https://user-images.githubusercontent.com/27446196/191805738-38639d0f-23e0-4bc2-afb2-4e82dff51dfa.png)

**Comment by elParaguayo** [comment]
Ah. This is a `STRETCH` widget so it fills available space. That's hardcoded at the moment.

**Comment by Crystal4276** [comment]
I remember this rice that had a custom task list doing the job, if that helps:
https://www.reddit.com/r/unixporn/comments/wb2r57/final_rice_on_qtile/

**Comment by elParaguayo** [comment]
That TaskList doesn't change anything to do with its size.

If you want to use a decoration with this then we'd have to stop it being a stretch widget (which is hopefully pretty easy) but you would need to add a stretch widget after it if your bar doesn't have any other stretch widgets.

**Comment by ervinpopescu** [comment]
> I remember this rice that had a custom task list doing the job, if that helps:
> https://www.reddit.com/r/unixporn/comments/wb2r57/final_rice_on_qtile/
> 
> Qtile dots:
> https://github.com/ervinpopescu/dots-Lenovo/tree/main/.config/qtile

Hi, I'm the chef that made that rice :)

As you can see from the dots, the tasklist has a transparent background, the issue you are pointing out bugged me too. I tried to make something like a thumbnail for windows in the tasklist and came across this, tried fixing it by playing with the `calculate_length` method and the `__init__`, but that didn't work, so I eventually gave up, and then gave up on the thumbnail thing too, but not because of this issue.

So yeah, @elParaguayo is completely correct, but it would be nice if we had a way of not hardcoding the widget's length :)

**Comment by elParaguayo** [comment]
I'll add to my list.

**Comment by kobzar** [comment]
need update

**Comment by elParaguayo** [comment]
Sorry for the delay. Have made a PR to fix this - see #4679
