### ISSUE TITLE
Any way to increase the systray rightmost padding?

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#3868]
### The issue:

The rightmost icon in my systray is hugging a little to close to the edge. Is there a simple way to increase that padding, or would I need to subclass the widget?

![1664578581](https://user-images.githubusercontent.com/12877032/193367127-953b7896-6fed-4603-bd3c-df92355cee9b.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Are you using widget decorations from qtile-extras to do the powerline effect?

**Comment by DeeeeLAN** [comment]
Yes. The padding issue exists without the effect, but I previously solved it by increasing the padding on the widget to the right. With the power line in place, that fix doesn’t work. 

The icons are a little strange anyway, only some of them change size when I increase it in settings.

**Comment by elParaguayo** [comment]
Ok. I've got a PR that will allow you add extra length at the end (some other issues to fix first).

As for icon sizes, there's nothing I can do about this as the bar isn't drawing the icons. The icons are separate windows that are embedded in the bar so it's up to that window to set the size and you get a set number of defined sizes rather than being able to define any size in pixels.

**Comment by DeeeeLAN** [comment]
Makes sense, I know those icons can be funky. Some WMs don’t even add support for them anymore. 

Thanks for the PR, that will fix things up nicely. 

While we are on the subject, how difficult would it be to make the icons on the tasklist widget center vertically with the associated text? Right now they both draw from the top so if the icons are a weird size it can look off. 

I manually subclassed it in my area and hard-coded a better offset but it wouldn’t scale well, I wasn’t sure how to make it center.

**Comment by elParaguayo** [comment]
Can you post that as an issue in the qtile page and include a screenshot?

**Comment by DeeeeLAN** [comment]
I added an `extrawidth=20` argument to the decoration, but it isn't looking quite right:
![1664913774](https://user-images.githubusercontent.com/12877032/193915664-b25fad76-cdf7-4028-a993-788f12444edb.png)

**Comment by elParaguayo** [comment]
Ah. Ok. Looks like the `PowerlineDecoration` needs some extra logic to handle the `extrawidth` argument!

**Comment by elParaguayo** [comment]
Have submitted a PR to qtile-extras that should fix this.

**Comment by DeeeeLAN** [comment]
working great now
