### ISSUE TITLE
initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#3869]
### The issue:

I am seeing this repeated many times in the log:

```bash
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2022-09-30 15:55:42,265 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
```

#2307, #2557 might be related? They at least mentioned the error, but neither led to a fix as far as I can tell. 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I do get this message sometimes too. It's something I do want to look into.

**Comment by justinesmithies** [comment]
Yeah I too get the same errors.

**Comment by daveoconnor** [comment]
I'm getting this too, reporoducible when I click play/pause on a Youtube video.
.

**Comment by elParaguayo** [comment]
> I'm getting this too, reproducible when I click play/pause on a Youtube video in Firefox.

What widgets do you have in your bar? This is related to text display.

**Comment by justinesmithies** [comment]
Here's my [widgets.py](https://codeberg.org/JustineSmithies/qtile-wayland-dotfiles/src/branch/master/.config/qtile/[widgets.py](https://codeberg.org/JustineSmithies/qtile-wayland-dotfiles/src/branch/master/.config/qtile/widgets.py)) if that helps ?

**Comment by elParaguayo** [comment]
Thanks.

It was more a question for @daveoconnor 

We really need to be able to recreate this reliably so I need more info. The commend about youtube on Firefox is helpful but, as I watch Youtube on Firefox and don't see this, I need to know what widgets they have in their bar.

**Comment by m-col** [comment]
I can trigger it reliably with the default config by making the reload config binding run it twice in quick succession:
```diff
diff --git a/libqtile/resources/default_config.py b/libqtile/resources/default_config.py
index 5408b07b..1dfd7ee7 100644
--- a/libqtile/resources/default_config.py
+++ b/libqtile/resources/default_config.py
@@ -68,7 +68,7 @@ keys = [
     # Toggle between different layouts as defined below
     Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
     Key([mod], "w", lazy.window.kill(), desc="Kill focused window"),
-    Key([mod, "control"], "r", lazy.reload_config(), desc="Reload the config"),
+    Key([mod, "control"], "r", lazy.reload_config(), lazy.reload_config(), desc="Reload the config"),
     Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
     Key([mod], "r", lazy.spawncmd(), desc="Spawn a command using a prompt widget"),
 ]

```

**Comment by elParaguayo** [comment]
Thanks. Let me investigate.

**Comment by elParaguayo** [comment]
It looks like this is to do with timers triggering a draw on widgets that have been finalised. That shouldn't happen as we delete timers when widgets are finalised so something's going wrong.

**Comment by elParaguayo** [comment]
Think I've worked this one out (see #4113).

I wonder if there are any other scenarios that could trigger a draw on finalised widgets...
