### ISSUE TITLE
Tasklist Widget Icons not vertically centered

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#3873]
### The issue:

Depending on the icon size, the placement of the icon relative to the text shifts. Here is an example with icon size = 45 and text size = 30.

![1664826413](https://user-images.githubusercontent.com/12877032/193666223-f80a1051-ecbd-45fc-894a-1c50ba4d9159.png)

And here it is with icon size = 30 as well:

![1664826716](https://user-images.githubusercontent.com/12877032/193666538-9f88eb29-d0b5-4676-8dc9-c8b423b5cc8d.png)

A simple fix would be to add a user-defined variable to the `y` calculation for `draw_icon`. I subclassed tasklist and manually modified the `y` value to match my icon size, and that works okay. A more flexible solution would be to modify the y value so it is always drawn such that it is centered. 

#1714 discussed the same issue but was never fixed. 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Sorry for the delay.

Agreed that the best solution here is to adapt the vertical positioning based on the icon size. We should do this without a user setting.

**Comment by DeeeeLAN** [comment]
That would work great.

**Comment by elParaguayo** [comment]
Would be great if one of you could test the fix in #4246. Thanks.

**Comment by DeeeeLAN** [comment]
Looks good to me:

![image](https://user-images.githubusercontent.com/12877032/235372230-ab303b9b-84fd-4b47-bd88-ae60d968784c.png)
