### ISSUE TITLE
terminal disappears when starting gui apps from terminal

### ISSUE THREAD

**Issue by dankhap** [qtile/qtile#3875]
### The issue:

qtile version is 0.22.1
OS: Linux Mint 21 x86_64

Each time I open a window using opencv, sdl2, or pygame python app from the terminal, the terminal window gets hidden, and the app window is displayed. this occurs with all standard layouts.
PyQt and matplotlib windows work as expected, new window gets tiled beside the terminal window. 
Tried with several terminal emulators (kitty/xterm/terminator) with the same effect..

didnt find any logs related to these events

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I wonder if the windows are minimising after starting the other windows.

There's probably a better way to do this but can you open a python session in a new terminal and run the following lines
```
>>> from libqtile.command.client import InteractiveCommandClient
>>> i = InteractiveCommandClient()
>>> print(i.group.eval("[w for w in self.windows if w.minimized]"))
```

**Comment by dankhap** [comment]
you were right, the terminal gets minimized. It was due to a client_new hook that i copypasted by mistake from some config.

**Comment by elParaguayo** [comment]
No problem. Shall we close this then?

**Comment by dankhap** [comment]
sure, thanks a lot!
