### ISSUE TITLE
[wayland] Buggy handling of idle and outputs

### ISSUE THREAD

**Issue by clotodex** [qtile/qtile#3881]
### The issue:

Qtile is behaving weird for me when changing displays or turning screens off during idle. I am having trouble pinning down reasons for the behavior, thus I am just describing what happens:

- [1] electron apps (chrome, telegram, vscode, ...) lose track of the correct pointer position (happens 100% of the time)
- [2] the cursor sometimes is unable to move from one screen to the next, I am "locked in" to one monitor (happens 10% of the time)
- [3] the bar almost always stops working (freezes) (happens 90% of the time)
- [4] my active workspace is switched to the initial one (first in the list) (happens 100% of the time in idle)
- very rarely I am getting a full system crash

**More details and (hopefully) steps to reproduce:**
[1], [2] happen when connecting new displays (my main display is a 3k oled, external displays over hdmi are either 4k or full hd; managed through kanshi). If electron apps are already running, they now have a significant offset for the pointer position (clicking somewhere registers the click in a severly offset position). This can be fixed by restarting all electron apps.

[3], [4] happen when swayidle turns off my screen(s) in idle. When the screens turn on again I am getting reset to the first workspace (no matter where I was before). And the bar stops working. I turn the screen on/off like this: `wlr-randr --output eDP-1 --on`

**Cause (my guess)**
All logs are clean (in the case of the crash pywayland segfaults so, dont think this is necessarily a qtile issue and very hard to reproduce). => Officially I have no idea
However, I feel like it has to do with the way screens are handled in wayland in general (could be related to #3645).

If someone knows some tips or tricks please let me know since it is always a bit of a disruption :) Otherwise I am opening this issue as a place to discuss the cause of these behaviors and ideas how qtile can work around them.
E.g. potential feature requrest: ability to manage outputs through qtile => turning outputs on and off, better output management

**Version**
qtile: 0.22.2.dev6+g520a8999

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by clotodex** [comment]
Continuing the thread. When I boot my laptop connected to an external display, my mouse gets stuck on the main display and I cannot move it to the external screen (which was populated by qtile though). The only way to resolve this is to disconnect the display, reload the config and attach it again.

**Comment by m-col** [comment]
Thanks for the report.

> [1] electron apps (chrome, telegram, vscode, ...) lose track of the correct pointer position (happens 100% of the time)

Are these running through XWayland or natively? Might be related to: https://github.com/qtile/qtile/issues/3675

> [2] the cursor sometimes is unable to move from one screen to the next, I am "locked in" to one monitor (happens 10% of the time)

Weird! Are the outputs placed beside each other in the layout or is there a gap between them? Not sure why it would matter though.

Does either of these issues relate to scaling? Does the pointer input offset scale e.g. is less bad closer to top left of the window?

> [3] the bar almost always stops working (freezes) (happens 90% of the time)

Does it just stop updating the window contents, or does it also stop responding to clicks (obviously it won't update contents, but some action might happen like changing group or pausing music)?

> [4] my active workspace is switched to the initial one (first in the list) (happens 100% of the time in idle)

To clarify, this happens when you connect/disconnect external monitors while another has blanked via swayidle? In which case it might be a symptom of https://github.com/qtile/qtile/issues/3404

> very rarely I am getting a full system crash

could be anything, sadly, but glad to hear it is rare. Keep an eye out though, if you figure out any reproducible way to cause segfaults that is valuable info, as you found with the chrome tab dragging :)

>  E.g. potential feature requrest: ability to manage outputs through qtile => turning outputs on and off, better output management

Yep this would be great, discussed in https://github.com/qtile/qtile/issues/3645

**Comment by clotodex** [comment]
>  Are these running through XWayland or natively? Might be related to: https://github.com/qtile/qtile/issues/3675

They are running native wayland

> Weird! Are the outputs placed beside each other in the layout or is there a gap between them? Not sure why it would matter though.
Does either of these issues relate to scaling? Does the pointer input offset scale e.g. is less bad closer to top left of the window?

They are besides each other (no gap), and I dont think it is related to scaling, even moving the cursor extensively it is still stuck (at the screen border, like it is unable to move to the next screen), and with reloading the config and reconnecting this screen this issue gets solved and behavior is as expected

> Does it just stop updating the window contents, or does it also stop responding to clicks (obviously it won't update contents, but some action might happen like changing group or pausing music)?

Clicks still work, just updating fails (including background processes launched in autostart of qtile btw - might be that qtile recovers but not dynamic items like the underlying processes for the bar and autostart). I am pretty sure this is related to me essentially killing the output on idle (wlr-randr off). Zoom segfaults for example when it cannot find any output. I also dont know if this is easily fixable, or if rather qtile should support some form off "sensible" idle like sway does, so that qtile can turn off screens without crashing internally as well as clients crashing. (#3645)

> To clarify, this happens when you connect/disconnect external monitors while another has blanked via swayidle? In which case it might be a symptom of https://github.com/qtile/qtile/issues/3404

No, also happens on singular monitor with sway idle. I guess this is related though, since when I turn off the screen without qtile understanding it, it is rather natural it also forgets the state of what workspace was on what screen (or only the main screen) and resets it to the inital one.

> could be anything, sadly, but glad to hear it is rare. Keep an eye out though, if you figure out any reproducible way to cause segfaults that is valuable info, as you found with the chrome tab dragging :)

Glad to report it has not happened since, but I will keep an eye open.

> Yep this would be great, discussed in https://github.com/qtile/qtile/issues/3645

Haha, routing for it then :))

**Comment by clotodex** [comment]
Hey @m-col 
Sadly, I am getting more and more crashes - only when connecting external monitors (handled by kanshi).
The segfault reported by dmesg comes from qtile in libwlroots.so.

However I think I have it semi-reproducable / more info:
- It is not dependent on the screen (known / unknown etc does not matter)
- It happens over hdmi => I dont know if qtile is handling the audio part handover of hdmi, but I sometimes get audio, sometimes I dont => unrelated of a crash but still fishy
- It is related to groups somehow. Every time a crash happens it was related to a new group being loaded (that is what it felt like). Like it took a few seconds and the moment it wanted to display sth - zap - and it is gone. I now have somewhat evidence for this, since today I connected a monitor and it was fully usable. And as soon as I switched to another group - ZAP - and it was also gone.

Overall crash likelyhood I would put to 30%.

Apart from that [1] still persists but *somehow* got better. [2] is still a pain, and is fully reproducable if you boot the pc, attached to the second monitor - as soon as one starts qtile, the mouse is trapped on one screen. [3] the bar freeze stays tied to turning off one screen through wlr-randr. [4] I fixed with a workaround script I trigger on sleep and wakeup that stores and restores my setup.

Is there any way I can debug the screen issue further? Hard crashes are not fun to deal with :P
I also checked the issues in wlroots, but all similar ones refer back to the compositor, thus I am not sure if it is qtile or pywlroots, but I dont feel like it is caused by wlroots.

**Comment by m-col** [comment]
Awesome that it's happening more, hopefully it will help us track down what state we need to create before handling a new output to trigger the crash. I'm not sure how feasible this would be, but something that would really help would be if you could get the crash happening on the default config or a simple config, hopefully identifying whether changes to it need to be made for the crash to occur, or identifying what steps I would need to make to get crashes.

FWIW I'm also getting lots of crashes recently too (though I run a heavily patched qtile). Hoping to find out what causes them! Something that I've found very helpful which you could also do is to use the `faulthandler` module to get a traceback when the crash happens (though I'm not sure how helpful this will be for output-related crashes). Specifically, add these lines to the top of your entrypoint i.e. `which qtile`:
```py
import faulthandler
faulthandler.enable()
```
For me (not using a display manager) it prints the traceback to the TTY - it won't be logged so might be difficult to capture. :thinking: might be improved by wrapping qtile in a shell script and redirecting stderr/stdout to file now I think about it...

**Comment by clotodex** [comment]
I will try with the default config soon and let you know if something happens.

I tried it already with the faulthandler at the beginning of the config, without getting more info though. Will try again with it at the entry point and will report :)

It is very hard for me to understand the whole flow of how displays are handled with wayland, wlroots and ultimately qtile. I am trying to read up on it to get some assumptions of possible causes going - if you have some nice material for me to dive into it more, please let me know :))

**Comment by clotodex** [comment]
I think I got an error for the idle case (i.e. all screens turned off):
```
2023-01-17 06:24:58,973 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
  31   │ Traceback (most recent call last):
  32   │   File "/home/clotodex/projects/development/linux/qtile-install-script/build/.venv/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
  33   │     callback(listener, data)
  34   │   File "/home/clotodex/projects/development/linux/qtile-install-script/build/.venv/lib/python3.10/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
  35   │     with self.wlr_output as wlr_output:
  36   │   File "/home/clotodex/projects/development/linux/qtile-install-script/build/.venv/lib/python3.10/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
  37   │     self.commit()
  38   │   File "/home/clotodex/projects/development/linux/qtile-install-script/build/.venv/lib/python3.10/site-packages/wlroots/wlr_types/output.py", line 197, in commit
  39   │     raise RuntimeError("Rendering on output failed")
  40   │ RuntimeError: Rendering on output failed
  ```
  dont know why this would affect the bar though, since anything else about qtile works after wakeup

**Comment by clotodex** [comment]
Mini progress: I think it is timing related. I had basically no crashes (with the same monitor) when letting it finish its reconfiguring FULLY - so I make sure I have no windows in fullscreen and I am making no inputs on keyboard or mouse.

I know that I am in some kind of configure loop since there are **as many pointers as screens** while it is configuring (they disappear when I move the mouse) (there might be more weird since sometimes switching to an empty group also makes my cursor disappear).
This is all not crucial, but if interrupted by some input while being in the reconfigure loop I can very much imagine wlroots to be in a weird state if qtile is calling some things in weird order - but this is all speculation.

Something unrelated: when looking at the code in core.py I can see two things that surprise me on output reconfiguring (might be totally normal though - I have no clue about wayland (yet)):
- If any configuration of the screens fail, the for loop is broken out of (i.e. no further screens are processed)
- Even if the configuration failed, the screen reconfigure hook is still fired

**Comment by clotodex** [comment]
Okay I have another (and almost reproducible) idea what might contribute.
As already said it might be (additionally) related to groups, but I think the actual culprit is mapping between qtile and wayland coordinate systems.

My laptop has a 3k screen, so every time I extend the displays I have for sure a differently scaled display in there (the main one).
Now steps to reproduce:
- Connect external display
- cycle through all groups
- Disconnect display (This is where ~70% of the time it desyncs => this is noticable additionally with the pointer positions sometimes being wrong)
- Reconnect same display (50% crashrate) or connect to a differently scaled one (100% crash rate)
- cycle some groups to make the crash happen
=> This thus tells me that the resolution mapping, where pixels are and are painted might desync and most likely end in an undefined state and segfault
This might be related to the effective resolution https://github.com/qtile/qtile/issues/3646

**Comment by jwijenbergh** [comment]
Can you try the latest release? We did a huge refactor of the wayland backend

**Comment by clotodex** [comment]
Yeees, I wanted to report on it anyways :D
Everything works now, no crashes.
The only thing is that SOMETIMES the workspace is switched of the external monitor, when going into idle (and turning off the main display) - this is not a wayland bug though, more of how qtile manages the session

Overall we can close this :)
