### ISSUE TITLE
Dynamic fake screens

### ISSUE THREAD

**Issue by evenAlpha** [qtile/qtile#3893]
### The issue:

Trying to push fake screens to their maximum potential, I implemented the modification of their position and size on the fly.
Only issue is that bars are not reconfigured.

After reviewing the code, i'm pretty sure I found the culprit in `Qtile` class (manager.py), the setup and update of the screens is handled by `_process_screens()` where it is decided to reconfigure bars or not with:
```
screen_info = [(s.x, s.y, s.width, s.height) for s in self.config.fake_screens]
config = self.config.fake_screens
for i, (x, y, w, h) in enumerate(screen_info):
    scr = config[i]
    reconfigure_gaps = (x, y, w, h) != (scr.x, scr.y, scr.width, scr.height)
```
This is equivalent to `reconfigure_gaps = False` unless i'm mistaken. Since I don't care about performance in the scenario, I just set reconfigure_gaps to True if qtile.fake_screens exists and bars are properly reconfigured.
The correct approach should be to compare `qtile.config.fake_screens` against `qtile.screens`, or I may be totally wrong since it's pretty deep in the code and I don't know the project architecture all that well, just messing with it.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Yeah. That does look wrong. Not sure what I was thinking!

Will take another look.

**Comment by elParaguayo** [comment]
How are you modifying `fake_screens`?

**Comment by evenAlpha** [comment]
My code is way to big and nasty to paste here but I wrote and tested this minimal example:
```
def screen0_reduce_height(qtile):
    screen = qtile.config.fake_screens[0]
    screen.height -= 100
    qtile._process_screens()
    screen.group.layout_all()
```
This is working perfectly with `_process_screens` fixed.

**Comment by evenAlpha** [comment]
After more digging, I realized that `Qtile.screens = Qtile.config.fake_screens`. Modifying one or the other leads to the loss of the previous data, ergo it is impossible to compare old and new values this deep in the code. I don't know if the snippet I posted in the first comment is the intended behavior, beside being semantically useless, or if it needs to change.
For my use case, and the example I provided, calling `Qtile._process_screens()` is not mandatory, using `Screen._configure()` is faster and allows to specify `reconfigure_gaps = True` directly as an argument.
The updated example looks like this:
```
def screen0_reduce_width(qtile):
    screen = qtile.config.fake_screens[0]
    screen._configure(
        qtile,
        0,
        screen.x,
        screen.y,
        screen.width - 100,
        screen.height,
        screen.group,
        reconfigure_gaps = True,
    )
    screen.group.layout_all()
```
Since it does not call `Qtile._process_screens`, this example works without modifying the code.

**Comment by elParaguayo** [comment]
That part of the code was not written with `fake_screens` in mind. It's more to force bars to be reloaded when physical screens are added/removed. I don't think we ever anticipated someone modifying the size dynamically (as opposed to updating their config and reloading it).

**Comment by evenAlpha** [comment]
Resizing fake screens for me is like growing a window in a layout, but instead I grow a layout (and the associated bars) in the monitor. I use this to circumvent the limitations of qtile (and most wms) regarding bar placement and size, because I don't want an 1,2 meter 5120px bar on my monitor, i think it's a waste of space, especially vertical space. To illustrate, here is my wip desktop: 
![Screenshot_20221013_190220](https://user-images.githubusercontent.com/17544583/195661369-b8d1aaa1-5f8b-4ee7-8cbf-fe9ff9444b8a.png)
That said, I don't think this should be added as a feature and it doesn't need to since it's totally 
feasible with minimal code and no override.

Now the only thing left to do is maybe some cleanup in `Qtile._process_screens()` to increase performance.

**Comment by elParaguayo** [comment]
Nice. Totally see why you use it like that.

I've been working on a layout that splits the screen into separate layouts. However, I don't think that would help you here either as it shall doesn't support resizing (at least, not yet) and you'd just have the one bar for the whole screen.

**Comment by evenAlpha** [comment]
Looks interesting, I'll give it a try when its ready. For now, I'm using a child class of `layout.Slice` that allows me dynamic population and focus navigation between slice and fallback. Because I'm using fake screens, I can add one slice to the right and left wings (I call this arrangement the Wings layout) to get exactly 2 windows on them, while being able to access and switch between windows with the fallback Max layout, works well for me.
