### ISSUE TITLE
toscreen command of group breaks when used from command line

### ISSUE THREAD

**Issue by clotodex** [qtile/qtile#3895]
### The issue:

`qtile cmd-obj -o group -f toscreen --arg 1` fails with
`TypeError: list indices must be integers or slices, not str`

The reason i guess is this line https://github.com/qtile/qtile/blob/946908b9ca710dedddb0168926aa547cd0593a53/libqtile/group.py#L392 where the argument is actually a string and not an int, thus cannot be used as index. Change it to `int(screen)`? This kind of bug suggests it might actually be in more commands.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. It's a known issue and, you're right, it's not specific to this command.

There's an open (but old) PR to address this (https://github.com/qtile/qtile/pull/2435) which we need to go back to and update.

**Comment by clotodex** [comment]
Ah missed this one, thanks for pointing it out, feel free to close this issue then

**Comment by elParaguayo** [comment]
Probably missed it because it's so old!!
