### ISSUE TITLE
Keyboard stops functioning when closing all the windows in the group except a minimzied one

### ISSUE THREAD

**Issue by SuperDuperDeou** [qtile/qtile#3899]
### The issue:

Qtile version 0.22.1 (Xorg)

If there is a minimized window in the current group and I close all the other windows in the same group, the keyboard input no longer works, only keybindings such as CTRL+ALT+F1. I can restore the functionality (without restarting Qtile) only by opening a window (including unminimizing the window).

The mouse still works properly, including mouse bindings that involve mod keys.

This problem has started happening only in version 0.22.1, it wasn't present in version 0.21.0.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
My guess is that that this is the same issue as #3856.

Are you using the git version? If so, can you go back to the before the commit highlighted in that other thread and test?

**Comment by SuperDuperDeou** [comment]
> My guess is that that this is the same issue as #3856.
> 
> Are you using the git version? If so, can you go back to the before the commit highlighted in that other thread and test?

Maybe they're related, but that sounds like a parsing issue, while this sounds more like Qtile screwing something up with focusing.

I'm running the stable version.

**Comment by elParaguayo** [comment]
Yeah, perhaps you're right but it would be good if we could do a git bisect. I'll see if I can recreate later.

**Comment by elParaguayo** [comment]
Can you give me some steps to recreate this? I just tried opening 2 windows, minimising one, closing the other and keybindings still worked.

**Comment by SuperDuperDeou** [comment]
As far as I'm aware, those are the steps.

Any idea of what might help you to figure it out?
