### ISSUE TITLE
[Wayland] Apps can't fullscreen automatically when opened

### ISSUE THREAD

**Issue by cronyakatsuki** [qtile/qtile#3902]
### The issue:

Apps that automatically open as fullscreen apps like games or mpv don't do so but open tiled not fullscreen. On X11 I don't have this problem but on the wayland side it is.

- qtile version: 0.22.1
- Can't find anything related in logs
- [my config](https://github.com/cronyakatsuki/dots/tree/main/.config/qtile) in case it's a problem with my configuration.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Thanks for the report. Please could you give some other examples of apps that do this? For mpv (and celluloid) if I set `fullscreen=yes` in the mpv config windows still don't open in fullscreen, in both x11 and wayland. If an app requests to be fullscreen, does it correctly get fullscreened? For example firefox makes the request if you hit f11.

**Comment by cronyakatsuki** [comment]
Yes when an app like firefox, mpv, games (like osu! with xwayland) request to be fullscreened while it's running it can fullscreen, but mpv for example with the option `fs` set in `~/.config/mpv/mpv.conf` will fuscreen on load in x11 but won't in wayland.
Xonotic for example won't to go fullscreen no matter what unless I forcibly fullscreen it with qtile.

**Comment by m-col** [comment]
Does https://github.com/qtile/qtile/pull/3905 fix it for you?

**Comment by cronyakatsuki** [comment]
No it doesn't, mpv still doesn't go fullscreen. Might quite posibly be my optimus laptop canfiguration with a amd igpu and nvidia dgpu that is making problems.
Wouldnt be the first time this happened 😞 .

**Comment by m-col** [comment]
Hmm. Please could you enable debug logging and paste those from around the time mpv opens up?

**Comment by cronyakatsuki** [comment]
I went and reinstalled qtile again with #3905 and mpv will start fullscreen but mpv will stay below the bar literally making the mpv window be below the view by the size of the bar, if I hide the bar before launching mpv it fullscreens normally.
Mpv related logs ![qtile-mpv.log](http://0x0.st/owoh.log)

**Comment by m-col** [comment]
Was https://github.com/qtile/qtile/pull/3905 necessary for getting it to start fullscreen or did re-installing alone get that working?

> mpv will stay below the bar literally making the mpv window be below the view by the size of the bar, if I hide the bar before launching mpv it fullscreens normally.

I'm not sure I follow. By "below" do you mean in the y axis or z axis? If z axis, it sounds as though you're using the `Max` layout and its just filled the space. Is that the case?

**Comment by m-col** [comment]
Upon further testing, I find that #3905 is needed, and without it the bar is still visible.

**Comment by cronyakatsuki** [comment]
> Was #3905 necessary for getting it to start fullscreen or did re-installing alone get that working?
> 
> > mpv will stay below the bar literally making the mpv window be below the view by the size of the bar, if I hide the bar before launching mpv it fullscreens normally.
> 
> I'm not sure I follow. By "below" do you mean in the y axis or z axis? If z axis, it sounds as though you're using the `Max` layout and its just filled the space. Is that the case?

Reinstalling with #3905 was necessary to get it working. I tried without afterwards and it wasnt working. Installed #3905 again and it was working.

It was the z axis and I was using max layout at the time.

**Comment by m-col** [comment]
Cool, I've merged that PR so the main issue should be resolved (and i can see it's auto closed this issue). Is everything solved for you or is there still the issue of the window being below the bar?
