### ISSUE TITLE
Focus on Floating window doesn't set _NET_ACTIVE_WINDOW

### ISSUE THREAD

**Issue by locriacyber** [qtile/qtile#3910]
### The issue:

Qtile version: 0.22.1
logs: N/A

When I monitor the output of `xprop -root | grep -i active_window\(`, focusing on a floating window doesn't change `_NET_ACTIVE_WINDOW`, while tiled window (those with tiled layout) does.

The result is when a floating window is focus, other WM tools like status bar `polybar` doesn't know it is focused.

Maybe this is a bug in Qtile?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Looking at the code, that property only seems to be set when the pointer is warped to the window. We may need to change that.

Thanks for flagging.

**Comment by elParaguayo** [comment]
How are you changing the focus? Clicking on the windows does result in _NET_ACTIVE_WINDOW changing to the right window id.

**Comment by locriacyber** [comment]
Ctrl+Tab or mouse over

**Comment by elParaguayo** [comment]
I've just checked this and it seems to be working fine for me. `_NET_ACTIVE_WINDOW` is being set on floating window when focus is changed via click, mouseover and `lazy.group.next_window()`.
