### ISSUE TITLE
Nextcloud client pop up appears in the middle of the screen

### ISSUE THREAD

**Issue by tralph3** [qtile/qtile#3911]
### The issue:

* Qtile version: 0.22.1

The Nextcloud client runs in the background, with an icon in the system tray. When clicked, the client window appears, but it should pop up right under the system tray icon. This is handled properly by AwesomeWM. Qtile however, spawns it in the middle of the screen, which is problematic, since moving the mouse outside the region of the window closes it.

This is intentional, since if the window were to popup where it should, you can quickly move the mouse on top if it, do what you want to do, and just move outside of it to close it.

Since it spawns in the middle, you have to do a very quick maneuver to get to it before it closes, which isn't ideal:

![image](https://user-images.githubusercontent.com/41462117/196790768-dd98023b-5f94-41d6-ab17-265266468586.png)
![image](https://user-images.githubusercontent.com/41462117/196790898-395dcf8d-a6a3-488c-9a06-f22b4c146b6e.png)
 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report. I can see how that is problematic!

Will take a look at this when I can.

**Comment by m-col** [comment]
There is some related information to this here: https://github.com/qtile/qtile/issues/2342 Basically their window is using some old hints that we don't support that are trying to tell us to not manage the window. If we supported these hints, we wouldn't manage it (as a floating window) and it would be placed in its desired position. Other WMs do support these hints so we probably should do.
