### ISSUE TITLE
Wrong volume displayed in Volume widget

### ISSUE THREAD

**Issue by DCsunset** [qtile/qtile#3921]
### The issue:

Qtile version: 0.22.1

A wrong volume (volume of Mic) is displayed for my device when using the Volume widget. The correct value should be the volume of Playback. The reason is that when running `amixer sget` command, the output is shown as below:

```
Simple mixer control 'Headset',0
  Capabilities: pvolume cvolume cvolume-joined pswitch pswitch-joined cswitch cswitch-joined
  Playback channels: Front Left - Front Right
  Capture channels: Mono
  Limits: Playback 0 - 50 Capture 0 - 30
  Mono: Capture 24 [80%] [-6.00dB] [on]
  Front Left: Playback 16 [32%] [-34.00dB] [on]
  Front Right: Playback 16 [32%] [-34.00dB] [on]
```

As we can see, the Capture volume is printed first. But according to the code [here](https://github.com/qtile/qtile/blob/40655f691ef11c883ac40c2a9bac3e02f2c0e614/libqtile/widget/volume.py#L196), it only tries to find the first percentage value.
So this widget shows the Mic volume instead of the playback volume.

I think the solution is to filter out the line with `Capture` from the output or only keep the lines with `Playback` before processing it. I can open a PR if you think it's a good approach.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
If you replace the regular expression with this, does that line get ignore?
```py
re_vol = re.compile(r"(?<!^.*Capture.*)\[(\d?\d?\d?)%\]")
```

**Comment by DCsunset** [comment]
I tried it but it didn't work. The error is `look-behind requires fixed-width pattern`. Since the characters around "Capture" are not fixed-width, this may not work.

**Comment by elParaguayo** [comment]
You can provide your own command in `get_volume_command` so is there a command you can provide that excludes the Capture device?

**Comment by DCsunset** [comment]
> You can provide your own command in `get_volume_command` so is there a command you can provide that excludes the Capture device?

Yes, I can do it by writing my own script to exclude it. But it is counter-intuitive since this widget is meant to process the output directly from `amixer`. Users also need to take a look at the source code before using their own commands.

**Comment by DCsunset** [comment]
> > I tried it but it didn't work. The error is look-behind requires fixed-width pattern. Since the characters around "Capture" are not fixed-width, this may not work.
> 
> That's unfortunate. I was testing without using `re.compile`, instead using `re.search` directly. We could do that instead if it lets this work.

Oh I think it still results in the same error on my machine when using `re.search` directly.

**Comment by DCsunset** [comment]
> If you replace the regular expression with this, does that line get ignore?
> 
> ```python
> re_vol = re.compile(r"(?<!^.*Capture.*)\[(\d?\d?\d?)%\]")
> ```

BTW, I think Playback is a common control that every device has. I think we could find percentage number behind it.

**Comment by elParaguayo** [comment]
There isn't a separate `get_mute_command`. Both volume and mute status are parsed from the same output.

**Comment by DCsunset** [comment]
After thinking over it, I think using a custom command looks more reasonable. Closing this issue now.

**Comment by m-col** [comment]
> BTW, I think Playback is a common control that every device has. I think we could find percentage number behind it.

ooh yeah good idea. We could try this. If you're happy with your solution then that's great, but if anyone else comes and reads this coming across the same issue we can see if we can put together a generalised solution.

**Comment by DCsunset** [comment]
> ooh yeah good idea. We could try this. If you're happy with your solution then that's great, but if anyone else comes and reads this coming across the same issue we can see if we can put together a generalised solution

Sure. Should I reopen the issue or just leave it closed?

**Comment by m-col** [comment]
We can leave it for now and wait until others come reporting the issue in which case we may as well generalise. Unless you'd prefer we fix the issue so you don't have to use a custom command - that's up to you.

**Comment by biscuitrescue** [comment]
I ended up using the PulseVolume widget because Volume displays the volume wrong. Im on pipewire now though, and remember it working working correctly quite a while back, when i was on pulseaudio, though that might just be an update issue
