### ISSUE TITLE
widget.TextBox Stopped Working With Multiple Colors

### ISSUE THREAD

**Issue by jas3333** [qtile/qtile#3932]
### The issue:

After doing a system update the textbox widget stopped working if two colors were being used in a list.

```
# No longer works
bar_color = ["#294247", "#202C2E"] 

# Works
bar_color = "#294247"

                widget.TextBox(font="sans", text="◤", fontsize=70, background=color[2], foreground=bar_color, padding=-1),

```
There are no errors in the Qtile log so I'm not sure where to begin to pinpoint what caused this. The background color still works, it's just the foreground that is broken.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Very odd. I can't recreate this. Works fine for me.

**Comment by jas3333** [comment]
Looks like the problem is fontconfig. My system updated to fontconfig 2.14.1-2 which broke the widget. Downgrading back to 2.14.0-1 fixed it.

**Comment by elParaguayo** [comment]
Ah. Ok. I'm on 2.14.0 (haven't updated recently).

**Comment by jas3333** [comment]
I guess I will hold back that package and hope for the best. Thanks for looking into it.

**Comment by elParaguayo** [comment]
It's still not clear to me why that would cause an issue with the colouring of the text though...
