### ISSUE TITLE
Suspended/minimized window disappears and it is difficult to restore (reproducible with Emacs)

### ISSUE THREAD

**Issue by polaris64** [qtile/qtile#3933]
### The issue:

I have noticed that sometimes windows get minimized/suspended due to something that the owning application does and it's then quite difficult to recover them. This is easily reproducible for me using Emacs.

## Steps to reproduce
1. Open Emacs
2. Type `M-x suspend-frame RET` to minimize/suspend the Emacs frame (window)

## Outcome
The window's title is still visible in the Qtile bar and it appears that the window still has input focus, but the window is completely invisible.

### Restoring the window state
The only way I have found to restore the window is to toggle the window's floating state. Setting it to floating after suspending makes it visible again but not floating (two successive requests to toggle floating are required to make it float).

This is more complicated if the window exists on a desktop with one or more other windows because as soon as another visible window is focused there seems to be no way of focusing the invisible window again except by moving all visible windows to another desktop so that the invisible window is the only window remaining.

## Technical information
 - Window system: x11
 - Qtile version: 0.22.1

Nothing appears in `~/.local/share/qtile/qtile.log` when this happens so I have not included it.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
It does sound minimized. In that case, it shouldn't get any input. What makes you think it has input focus? There is a `lazy.window.toggle_minimize()` command if that helps. IIRC the only convenient way to unminimize a window is using the `TaskList` widget. Also, note you can stop clients from minimizing themselves by setting `auto_minimize = False`.

**Comment by polaris64** [comment]
> It does sound minimized. In that case, it shouldn't get any input. What makes you think it has input focus?

I've just double checked and you're right, it doesn't have input focus after all.

> There is a lazy.window.toggle_minimize() command if that helps.

That works perfectly, thank you!

> IIRC the only convenient way to unminimize a window is using the TaskList widget. Also, note you can stop clients from minimizing themselves by setting auto_minimize = False.

These are both good suggestions too, thank you very much. The `TaskList` widget is very useful if there's more than one window on the desktop at the point at which one gets minimized so I have started using that. Un-setting `auto_minimize` also prevents windows from being minimized in the first place as you say, but in the case of Emacs it just causes the window to be "frozen" without any obvious way to restore it other than switching desktops so I decided against using that.

So, this solves my problem perfectly! I'm not sure if I missed this in the documentation or default configuration but perhaps mentioning `lazy.window.toggle_minimize()` more prominently or giving it a default binding would help others to avoid similar problems?

**Comment by m-col** [comment]
> I'm not sure if I missed this in the documentation or default configuration but perhaps mentioning lazy.window.toggle_minimize() more prominently or giving it a default binding would help others to avoid similar problems?

We can certainly add it to the default config. I'm actually surprised to see that `toggle_maximize` and/or `toggle_fullscreen` aren't already there. All 3 would probably be helpful. Would you like to make a PR for that? :)

> but in the case of Emacs it just causes the window to be "frozen" without any obvious way to restore it other than switching desktops so I decided against using that.

Interesting, that definitely sounds like a bug. It's possible that some windows (like in this case) are saying "I'm going to minimise now" rather than "I'd like to minimise please", which might be detectable by some hint. Please could you paste the `xprop` of the emacs window before and after (when frozen) you try to minimise it?

**Comment by polaris64** [comment]
> We can certainly add it to the default config. I'm actually surprised to see that toggle_maximize and/or toggle_fullscreen aren't already there. All 3 would probably be helpful. Would you like to make a PR for that? :)

I certainly can :) however I'm not sure if my particular bindings would be suitable for a default configuration. I currently have a `KeyChord` for `mod t` set up as a "toggling" chord, then I use "f" (`toggle_floating`), "m" (`toggle_minimize`) and "M" (`toggle_maximize`). I use "F11" for `toggle_fullscreen` as I'm used to that from other window managers.

I'm pretty bad at choosing key bindings so if you have an idea for nicer bindings then please let me know!

> Please could you paste the `xprop` of the emacs window before and after (when frozen) you try to minimise it?

It's a little tricky to do because as soon as it loses focus it seems to un-freeze (so I guess another option to un-freeze it would be to open another window on the same desktop, then switch back to Emacs).

I managed to do this however using `sleep 10; xprop -id ...` so that my focus was on Emacs during both calls to `xprop`. However the results from `xprop` in both cases were identical.

Using `xprop -spy` I can see that the only changes during `suspend-frame` are to `WM_STATE(WM_STATE)` if `auto_minimize` is set. This gets changed to: -

```
WM_STATE(WM_STATE):
		window state: Iconic
		icon window: 0x0
```

However with `auto_minimize` unset (when it causes the window to freeze) the above change does not occur.

I have a feeling this might be more down to Emacs itself. After calling `suspend-frame` it is expecting to be minimized so it doesn't bother to redraw itself until it regains focus again. So perhaps this isn't a Qtile bug after all.

**Comment by purplebar0** [comment]
> There is a lazy.window.toggle_minimize() command if that helps. IIRC the only convenient way to unminimize a window is using the `TaskList` widget.

That is very useful to know to discover a previously minimised window, but I found that it is impossible to switch to minimised windows using key bindings. Would it require additional implementation for each layout?
