### ISSUE TITLE
Wayland: popups should always be above all windows

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#3936]
### The issue:

Qtile version: master at 83388a6c702ebb7253dd74e739fe8b4e6b179124

This was mentioned in https://github.com/qtile/qtile/issues/3533. `XdgPopup` surfaces should be rendered above everything else (above all regular and layer shell surfaces), and similarly should receive input at the top of the Z stack. The solution to fix this would need re-writing after wlr_scene usage is implemented so let's wait until that's added before fixing this.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
This is fixed

**Comment by PhoenixClank** [comment]
Not in my release (0.23.0)
![20231011_00h15m40s_grim](https://github.com/qtile/qtile/assets/30195074/f89ba4b3-cf5a-4c4f-9279-143d2f90a9f2)

**Comment by m-col** [comment]
Ah thanks, my mistake. I think I know how to fix this.
