### ISSUE TITLE
Outer Non-modal KeyChord in Nested Chain Not Aborted After Inner Key Is Pressed 

### ISSUE THREAD

**Issue by yuki-tsubaki** [qtile/qtile#3937]
### The issue:

In previous versions of Qtile, when I press a key in the innermost layer of a nested keychord chain, all of the outer keychords in the chain would be exited. However recently (I believe it started when I updated to 0.22.1, but I didn't check at the beginning as I assumed I mispressed something). I have not changed my config recently (until today when I was trying to figure out what was going on).

Version: 0.22.1 installed with Pacman on Arch

## Minimal Config
An example minimal config that has a problematic KeyChord chain in it can be created by inserting the following into the default config file (https://docs.qtile.org/en/latest/manual/config/default.html#default-config):
In the imports section:
```python
import KeyChord
```
In the `keys` list:
```python
    KeyChord([mod], 'x', [
        Key([], 't', lazy.spawn(terminal)),
        KeyChord([], 'w', [
            Key([], 'w', lazy.spawn('firefox')),
            Key([], 'q', lazy.spawn('firefox https://docs.qtile.org/en/latest/manual/config/default.html#default-config')),
        ]),
    ]),
```
### Expected Behavior
Using this configuration I would expect `Super-x, w, w, t` to run `firefox` and send a 't' to the focused application (probably typing a 't' into the address bar of Firefox).
### Actual Behavior
Firefox is started, but rather than the `t` being sent to Firefox, a terminal window is launched.
### Expected Behavior
`Super-x, w, w, t, t` should launch Firefox and send 'tt' to it.
### Actual Behavior
Firefox is started, a terminal is started, and a 't' is typed into the terminal.

### Xephyr Note
When running this in Xephyr for me, firefox opens outside, but if the mouse and keyboard are grabbed you can still see that the terminal gets launched with the next press of `t`, I would have used another program that acts less weird, but I can't think of any other ubiquitous GUI programs.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. There were some changes to KeyChords but this shouldn't have broken.

I'll test when I can and see if I can post a fix.

**Comment by yuki-tsubaki** [comment]
I tested the same configuration on a computer that had not been updated (it was on 21 still) and it did not have the problem. I then updated it to 0.22.1 and it had the problem.
I forgot to mention earlier, but I am running X11 not Wayland (on both computers).

**Comment by elParaguayo** [comment]
Should be fixed by #3945 - would be great if you could test.

**Comment by yuki-tsubaki** [comment]
Sorry, I've been a bit busy recently. I tested the change, and confirm that the issue is resolved.

**Comment by Sniki** [comment]
Hmm, curious to know if this one has any implication on the bug with keychords breaking simple key binder ?
for example, i use simple_key_binder on my config and whenever i use a keychord, the workspaces keybindings = mod +1...9 do not work anymore, you can click on the workspaces with mouse though to switch them, all other keybindings are not affected.
A quick fix is a mod+shift+r which i use for reload config/qtile restart and i can use mod+1...9 again without a problem.
config = https://gitlab.com/Sniki/dotfiles/-/blob/master/.config/qtile/config.py
