### ISSUE TITLE
QTile not managing xfce4-terminal correctly

### ISSUE THREAD

**Issue by manujchandra** [qtile/qtile#3948]
### The issue:

Version : 0.22.1
Fedora XFCE4

Hi, let's define desired behavior as : 
"When we execute a command in xfce4-terminal using qtile shortcut, the window should open in the current workspace".

I have a [config](https://github.com/magnacore/Productivity-Tools/blob/master/Linux/config/qtile/config_xfce.py) file which is otherwise working as expected. But when I execute any command that opens in xfce4-terminal, the new window randomly goes to workspace 1, 2 or 4.

Eg: mod+enter, mod+t, ctrl+shift+a, ctrl+shift+y (as per my config) will all open in 1, 2 or 4 and not in the workspace where I issued the shortcut from. (Unless they happen to be 1, 2 or 4)

Now, if I reload qtile, I get the desired behavior. But if I reboot the computer, I do not get the desired behavior.

This does not work:
1) Use the above config file
2) Reboot/log out
3) mod+enter from workspace 6 (window goes to workspace 2 where terminal opened on startup)

This works:
1) Use the above config file
2) Reboot/log out
3) Once logged in, reload qtile (mod+ctrl+r)
4) mod+enter from workspace 6 (works - window will correctly open in the workspace 6 where the shortcut was issued)

workspace 6 is just used as an example

I have another [config](https://github.com/magnacore/Productivity-Tools/blob/master/Linux/config/qtile/config.py) that uses Alacritty. It is identical to the above config, the only difference is that it uses Alacritty instead of xfce4-terminal. In this config I get the desired behavior without reloading qtile after login.

Summary : for the xfce4-terminal config file, qtile needs to be manually reloaded after login for commands in terminal windows to open in the current workspace. This need not be done with the Alacritty config file.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
If you pass `--disable-server` to xfce-terminal does it fix the issue? I think things get complicated with the window matching (especially when used by scratchpads) if it's a server process managing multiple windows that should match differently. Im unsure how reloading would make a difference though, that is pretty strange.

**Comment by manujchandra** [comment]
It seems `--disable-server` did the trick. It appears to be working now. I am closing the issue and will test for a few days.
