### ISSUE TITLE
Easy Effects weird margin to border in Wayland

### ISSUE THREAD

**Issue by Magnitudexx** [qtile/qtile#3953]
### The issue:

On Qtile 0.22.1. On Wayland, Easy Effects, a GTK4 application, has a weird transparent margin between the border and the actual window. I have tested on RiverWM, another Wayland compositor, and this doesn't happen. Is this a known bug or have I maybe forked something in my config?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
It's a known qtile bug, see https://github.com/qtile/qtile/issues/3764

**Comment by Magnitudexx** [comment]
Didn't see that one i will close this one in favor off that one
