### ISSUE TITLE
Make apps open automatically when you sign in

### ISSUE THREAD

**Issue by rexwithluv** [qtile/qtile#3954]
### The issue:

_qtile --version -> 0.22.1_

I am a python beginner and and qtiles too, but I've been in Arch and qtiles for months, and I can't manage to make that when logging in with a specific user, programs open automatically (for example, when logging in, a terminal opens in the first group, in the second a firefox browser...).

Apologies if I have not explained myself well. I have reviewed all the qtiles documentation but I have not found the solution (or I have not noticed). I don't even know if it is possible in qtile. Any solution? Thx <3

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by milkias17** [comment]
You can achieve this by passing in a command or a list of commands to execute to the Group class when creating groups so for example: `Group(1, spawn="kitty")`. For documentation you can take a look at the group classes reference documentation [here](http://docs.qtile.org/en/stable/manual/config/groups.html).

**Comment by rexwithluv** [comment]
I have tried following that documentation, but my code is different and I can't get it to fit that way. Every time I've tried I've ended up with Qtile not starting and logging in from a tty to edit the `.config/qtile/config.py file.`

This is how I currently have the code:
```
groups = [Group(i) for i in [
    '', '', '', '', '','', '', '漢', ' ',
]]

for i, group in enumerate(groups):
    desktopnumber = str(i+1)
    keys.extend(
        [
            # mod1 + letter of group = switch to group
            Key(
                [mod],
                desktopnumber,
                lazy.group[group.name].toscreen(),
                desc="Switch to group {}".format(group.name),
            ),
            # mod1 + shift + letter of group = switch to & move focused window to group
            Key(
                [mod, "shift"],
                desktopnumber,
                lazy.window.togroup(group.name, switch_group=True),
                desc="Switch to & move focused window to group {}".format(group.name),
            ),
            # Or, use below if you prefer not to switch to that group.
            # # mod1 + shift + letter of group = move focused window to group
            # Key([mod, "shift"], i.name, lazy.window.togroup(i.name),
            #     desc="move focused window to group {}".format(i.name)),
        ]
    )
```

**Comment by Crystal4276** [comment]
I forgot to mention how to get apps started at login.
This hook is required in config.py
(don't forget import os and importing hook)
```python
# Autostart
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~/.config/qtile/autostart.sh')
    subprocess.Popen([home])
```
And in the autostart.sh script you need to add the apps.
example :
```bash
#!/bin/sh
#starting user applications at boot time
thunderbird &
deluge &
discord &
spotify &
steam &
```
