### ISSUE TITLE
Fake screens groupbox only showing a single screen as active across every monitor

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#3965]
### The issue:

qtile --version: `0.22.2.dev36+ga7663d0e`

I have 2-3 monitors attached and three fake screens of the same dimension configured. My groupbox only shows the "currently active screen" as whatever is on the first monitor, even though the other monitors are displaying a different screen. I imagine this is due to how the fake screens are reported to groupbox, but I imagine since each monitor knows its dimensions, it should still be possible?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by DeeeeLAN** [comment]
Nevermind, I just checked using regular `screens` and it behaves the same way. I though the "active current screen" would be whatever the monitor is displaying, but it appears not to work that way.

**Comment by DeeeeLAN** [comment]
Duh, mirrors.

**Comment by m-col** [comment]
My favourite kind of issue :)
