### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by pranavsetpal** [qtile/qtile#3966]
### The issue:

Qtile version: 0.22.1

Whenever I am using Qtile, it takes about 25+% CPU usage, even when it's freshly booted. I faced this issue on 0.21.0 as well

When I used any DE or xmonad I did not face this issue, it usually used to float 3-5%

top:
![image](https://user-images.githubusercontent.com/68775426/200514044-aa28b0c4-19d5-47e7-99ea-3c5cec2327a6.png)

P.S. I did find another issue regrading this same problem, but it was marked unconfirmed and closed. In case you need me to post it there instead kindly inform me.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Does the same thing happen with the default config? If not, post your config please.

**Comment by pranavsetpal** [comment]
The default config works properly. Should have tested this beforehand.
I'll just mark this as closed and search for the issue. Thanks!

**Comment by elParaguayo** [comment]
No problem. If you do find any issues feel free to reopen this.

**Comment by pranavsetpal** [comment]
P.S. I found out what was causing it, I had set the update interval for the PulseVolume widget to 0, in order to have the widget refresh immediately when I change the volume, Not quite sure how to do it, so if anyone knows, that would much appreciated!

**Comment by m-col** [comment]
Does this change to the widget (bottom of the file) fix it?:
```diff
diff --git a/libqtile/widget/pulse_volume.py b/libqtile/widget/pulse_volume.py
index 8f7385c7..7e4e6bad 100644
--- a/libqtile/widget/pulse_volume.py
+++ b/libqtile/widget/pulse_volume.py
@@ -247,7 +247,7 @@ class PulseVolume(Volume):
 
     def timer_setup(self):
         self.poll()
-        if self.update_interval is not None:
+        if self.update_interval:
             self.timeout_add(self.update_interval, self.timer_setup)
         if self.theme_path:
             self.setup_images()

```
I see that other widgets skip `self.timeout_add` if `self.update_interval` is falsey so this might need to here. An update interval of 0 should be prevented from ramming the CPU.

**Comment by pranavsetpal** [comment]
Hello, this should the fix the issue.
I am not sure how to test it though, I have edited the file in site_packages, but not sure how to install it as pip just says everything is already satisfied.

**Comment by m-col** [comment]
Modifying the file and restarting should be fine

**Comment by pranavsetpal** [comment]
Sorry for the late reply, was a bit a busy, but yes, 

> -        if self.update_interval is not None:
> +        if self.update_interval:
>              self.timeout_add(self.update_interval, self.timer_setup)
>          if self.theme_path:
>              self.setup_images()

This change fixes the issue for when update_interval is 0.

**Comment by ZN0N15** [comment]
I'm having this same High CPU usage Issue when update_interval is set to 0. But changing `if self.update_interval is not None:` to `if self.update_interval:` to the widget doesn't fix it for me, it just made it worse somehow. My result is that its now permanently stuck at "M" meaning its muted and the widget will not update. I'm using Pipewire-Pulse.

**Comment by pranavsetpal** [comment]
Hmm, I may have meant it solved the High CPU Usage, looking at my config I have set the update interval to 0.1 too and ignored the issue for the time-being.

However you can check out this issue https://github.com/qtile/qtile/issues/4011, it's a feature request for the same and [[ei-grad](https://github.com/ei-grad)](https://github.com/qtile/qtile/issues/4011#issuecomment-1460277089) has even come up with a custom widget for it just lask week!
