### ISSUE TITLE
Bar drawing artifacts(?)

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3969]
### The issue:

```console
$ qtile -v
0.22.2.dev40+g29549a23
```

I've copied the `MouseOverClock` widget from the docs and there's something odd going on with it.

https://user-images.githubusercontent.com/84532402/200549063-04abf6f5-fe07-488d-88ca-a5cc55dcfe60.mp4

`qtile cmd-obj -o bar bottom -f info` output:
https://termbin.com/bkqen

Then I tried doing [this](https://github.com/ervinpopescu/dots-Lenovo/blob/main/.config/qtile/extras/mouseoverclock.py#L21-L22) with it, didn't work. Ideas?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
It looks like some odd interaction with widget box.

Can you paste the config for your bar please.

**Comment by ervinpopescu** [comment]
That's not that easy :)
It's modularized and the widgets are assigned to variables.

These are the relevant modules:
https://github.com/ervinpopescu/dots-Lenovo/blob/main/.config/qtile/modules/widgets.py
https://github.com/ervinpopescu/dots-Lenovo/blob/main/.config/qtile/modules/screens.py

The widgets I "wrote" are in here (some of them are present in the "custom" widgetbox):
https://github.com/ervinpopescu/dots-Lenovo/tree/main/.config/qtile/extras

I'll try using the default widgetbox and see if there's a problem with my code in the `MyWidgetBox` class.

**Comment by elParaguayo** [comment]
Do you get error messages in your logfile? I've tried your config in xephyr and I can see errors.

Also, your mouseover clock has an error in. You have references to `self.bar.widgets["mywidgetbox"]` but `widgets` is a list, not a dict so you can't use a key.

**Comment by elParaguayo** [comment]
I think this is a width issue. You've got too much in your bar.

If I remove all of your widgets before systray then I don't get any error messages and the mouseover clock behaves correctly (after correcting the error above).

**Comment by ervinpopescu** [comment]
> Do you get error messages in your logfile? I've tried your config in xephyr and I can see errors.
> 
> Also, your mouseover clock has an error in. You have references to `self.bar.widgets["mywidgetbox"]` but `widgets` is a list, not a dict so you can't use a key.

Oopsie :)

> I think this is a width issue. You've got too much in your bar.
> 
> If I remove all of your widgets before systray then I don't get any error messages and the mouseover clock behaves correctly (after correcting the error above).

Oh ok... Same here. Closing!

**Comment by ervinpopescu** [comment]
Thanks for the help @elParaguayo !
