### ISSUE TITLE
Wayland: support new wlroots release 0.16

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#3982]
### The issue:

wlroots just cut a new release so we need to update in step. First there are a bunch of updates that need to be made in pywlroots, tracked here: https://github.com/flacjacket/pywlroots/issues/108

This to do list is for Qtile's updates specifically but also most things in the pywlroots issue need to be updated in Qtile too.

- [x] compositors must now manually call wlr_xdg_surface_schedule_configure on request_maximize/request_fullscreen if they weren't handling the request.
- [x] add toplevel set_maximized, request_maximized, maybe set_bounds, maybe set_wm_c
- [x] use wlr_buffer for internal windows
- [x] ensure size_hints in xwindow.py isn't accessing an opaque struct

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Qpernicus** [comment]
I am using Qtile as a Wayland Compositor, using the qtile-git package from aur. (so yeah, Arch btw).. 

But the latest version won't build. Could that be caused by this issue/problem?? 

The Version is qtile-git-0.20.0.r33.gc1f50739-2

The Error:

```
build/temp.linux-x86_64-cpython-310/libqtile.backend.wayland._libinput.c:603:10: fatale fout: wlr/types/wlr_surface.h: File or Folder doesnt exist
  603 | #include <wlr/types/wlr_surface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation ended.
error: command '/usr/bin/gcc' failed with exit code 1
```

Version pywlroots: python-pywlroots 0.15.24-3 
Version Wlroots: wlroots0.15 0.15.1-1  (and tried wlroots-git 0.16.0.r5511.e59f4d4f-1 )

Just noticed both WLRoots versions are installed... could that cause issues?

**Comment by m-col** [comment]
Using the packaged version 0.15 for wlroots is correct, as qtile doesn't yet support the new 0.16 release (working on it, most of the updates to pywlroots have been made). Note that qtile won't ever aim to follow the git version of wlroots, only the releases. Which AUR helper are you using to build the qtile-git package? The error suggests it can't find the wlroots headers, though it should be able to as long as the `wlroots` package contents is accessible

**Comment by Qpernicus** [comment]
I'm using paru as a helper. 

Should i remove the wlroots git?

**Comment by Sydiepus** [comment]
1. @Qpernicus yes you should remove wlroots-git and install [wlroots0.15](https://archlinux.org/packages/community/x86_64/wlroots0.15/) instead.
wlroots-git installs version 0.16 which has many breaking changes, you should stay on 0.15 until qtile is updated to support the new wlroots version.

2. It's up to you if you want to switch, your config should work on both wayland and X test both and stick with the one you like.

**Comment by Qpernicus** [comment]
> 1. @Qpernicus yes you should remove wlroots-git and install [wlroots0.15](https://archlinux.org/packages/community/x86_64/wlroots0.15/) instead.
>    wlroots-git installs version 0.16 which has many breaking changes, you should stay on 0.15 until qtile is updated to support the new wlroots version.
> 2. It's up to you if you want to switch, your config should work on both wayland and X test both and stick with the one you like.

Thx.

1) Removed all wlroots except the 0.15 version.. Still qtile-git won't update (neither Yay nor Paru) 
2) Ok. But i'm using the qtile-git package, with a ' wayland only config' (well except dependencies) . Is it in that case better to switch to the qtile-wayland-git package? (if i understood correct it removes the Xorg dependencies?)  It doesnt really matter, and doesnt help with the issue, but was just wondering.

Either way: Qtile-qit is still not updating.

**Comment by Sydiepus** [comment]
can you send the output of yay or paru ?

**Comment by Qpernicus** [comment]
> The Version is qtile-git-0.20.0.r33.gc1f50739-2
> 
> The Error:
> 
> ```
> build/temp.linux-x86_64-cpython-310/libqtile.backend.wayland._libinput.c:603:10: fatale fout: wlr/types/wlr_surface.h: File or Folder doesnt exist
>   603 | #include <wlr/types/wlr_surface.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
> compilation ended.
> error: command '/usr/bin/gcc' failed with exit code 1
> ```
> 
> Version pywlroots: python-pywlroots 0.15.24-3 Version Wlroots: wlroots0.15 0.15.1-1 (and tried wlroots-git 0.16.0.r5511.e59f4d4f-1 )
> 
> Just noticed both WLRoots versions are installed... could that cause issues?

https://github.com/qtile/qtile/issues/4108
