### ISSUE TITLE
Weird padding implemented in tasklist

### ISSUE THREAD

**Issue by mcnuggetsx20** [qtile/qtile#3984]
### The issue:

Qtile version: 0.21.1.dev87+g2ecbb5fd

The tasklist widget uses some weird padding. The text is placed so low, it cuts off the lower parts of some letters as shown in the picture:
![image](https://user-images.githubusercontent.com/71185521/201480212-9c142f1b-84e6-4df4-8b75-f204018052a0.png)
You can see that the 'y' in 'Alacritty' is cut off. Messing around with the `padding_y` option doesn't solve the issue as it affects the icon position as well. What I think needs to be changed is the y positioning of the text, so it matches the way icons are positioned.

The code for my widget looks like this:
```py
                widget.TaskList(
                    parse_text=lambda text: '|' + text, 
                    max_title_width=100,
                    borderwidth=0, 
                    icon_size=18, 
                    txt_floating='',
                    spacing = 20,
                    foreground = gray,
                    txt_minimized='-',
                    font='IBM Plex Mono Bold',
                    #padding_y=-2,
                ),
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
That's a bit odd. Looks very different to the TaskList in https://github.com/qtile/qtile/issues/3873.

I don't disagree that the padding options are all a bit odd. Everything should really just be centered vertically.

**Comment by mcnuggetsx20** [comment]
Wow it really does look different to the one you attached. No idea what's causing it to look so terrible though. Probably something in the tasklist source code needs to be changed.

**Comment by elParaguayo** [comment]
Have you got some padding set in your `widget_defaults`?

**Comment by mcnuggetsx20** [comment]
Yes, I have. It's set to 0.
```py
widget_defaults = dict(
    font='IBM Plex Mono Medium',
    fontsize=13,
    inactive='#FFFFFF',
    padding=0,
)
```
Removing it made things much worse:
![image](https://user-images.githubusercontent.com/71185521/201516577-e03edb3e-1306-4458-aa7e-c6b8b8537ab6.png)

**Comment by atrusnak** [comment]
I've started working on this problem. My current approach is to add a center_aligned argument to the TaskList widget as in the GroupBox widget. This should also solve #3873. This is my first contribution so it will take me some time to run through the whole process of submitting a updating the docs, submitting a PR, etc. Screenshot below (current on top, fixed underneath). 

![tasklistFix](https://user-images.githubusercontent.com/43786596/204105982-1d6dce82-e260-43e5-bcf8-b02980c2a683.png)

**Comment by elParaguayo** [comment]
It's weird as it really shouldn't be needed. You can see that the text is already centered in #3873.

Don't worry about the time. We'll also help if you have questions as you go along.

**Comment by atrusnak** [comment]
If icon_size and fontsize are not set, the default is calculated as barHeight - 2*(border + padding) which implicitly centers the icon and text. Widgets like GroupBox adjust the vertical position if the sizes are not default, but TaskList is missing this. 

As for the center_aligned argument, one could leave it out but maybe some people prefer the top_aligned (center_aligned = false) as it is appears now? Please lmk if that makes sense and what you think the best. Thanks

**Comment by elParaguayo** [comment]
I would think it's unlikely that anyone prefers the top alignment as I'm not aware of any other widgets that do that.
