### ISSUE TITLE
X11: Keyboard events being sent to the incorrect window

### ISSUE THREAD

**Issue by Abdul-AZ** [qtile/qtile#3987]
### The issue:

Changing window focus does not seem to correctly change the window that receives keyboard events.
`qtile --version` is 0.22.1. 
Here is a gif of whats happening:

![editor_keyboard_focus_bug](https://user-images.githubusercontent.com/30045609/201520798-8e86c80d-11e7-4649-949c-eee985d2907f.gif)

Here is the expected behavior (which weirdly enough works for earlier versions of Godot)
![editor_keyboard_focus_godot3](https://user-images.githubusercontent.com/30045609/201520838-394c257f-0550-4e6a-b3aa-8d4bc43de026.gif)

This is an issue I ran into when trying to use the latest version of [Godot](https://github.com/godotengine/godot). 
[Here](https://github.com/godotengine/godot/issues/68572)  is a link to the issue tracking this on that project.
 
The reason I suspect this is a qtile issue is because it does not occur when using i3 or KDE plasma(when set to focus follows mouse). But I am still not entirely sure on whose fault it is.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Daniel-Ros** [comment]
Same issue for me,  Can't use godot with Qtile...

**Comment by Daniel-Ros** [comment]
I don't know actually how to check the _NET_WINDOW_ACTIVE,  looks related, the only things I can tell is that the only thing the fixes the issues for me is changing the layout

**Comment by jwijenbergh** [comment]
> I don't know actually how to check the _NET_WINDOW_ACTIVE, looks related, the only things I can tell is that the only thing the fixes the issues for me is changing the layout

Which layout does the issue arise in? I cannot seem to reproduce it with the latest qtile and godot versions

**Comment by Abdul-AZ** [comment]
> Which layout does the issue arise in? I cannot seem to reproduce it with the latest qtile and godot versions

I'm out for vacation for a month so I can't test until I'm back.
But if I remember correctly, it happened to both MonadWide and VerticalTile layouts that I tried. I did not test other layouts.

**Comment by Daniel-Ros** [comment]
> > I don't know actually how to check the _NET_WINDOW_ACTIVE, looks related, the only things I can tell is that the only thing the fixes the issues for me is changing the layout
> 
> Which layout does the issue arise in? I cannot seem to reproduce it with the latest qtile and godot versions

Happened to me in Columns and max. 
Changing the layout seems to give the other window it's control back (until you focus on godot again)

**Comment by claychinasky** [comment]
only the Max layout works for me(only used max and column), to make it not consume keyboard input. If godot is open on  in any other virtual screen it hidden it still consumes keyboard input, but in Max layout if I make any window full screen that makes Godot inactive, like 'minimized to task bar' like state.
If I have a terminal next to Godot  in same screen, terminal blink cursor stuck to non-filled rectangle inactive looking cursor, if I minimize the Godot it grabs the focus state.

**Comment by gitacrobat** [comment]
Same issue here. 

- godot-3.5.1 works as expected
- godot- 4.0.beta hijacks all keyboard input, except WindowManager commands like moving windows in stack or to another screen, workspace, etc.

**Comment by jwijenbergh** [comment]
> Same issue here.
> 
>     * godot-3.5.1 works as expected
> 
>     * godot- 4.0.beta hijacks all keyboard input, except WindowManager commands like moving windows in stack or to another screen, workspace, etc.
> 
> 
> edit: I compared qtile with xmonad and it seems there is something going on with this godot4-window though the problem in xmonad is more difficult to spot. When I open a new window in xmonad besides godot4, godot4 hijacs the keyboard input, BUT I can switch via mouse or keyboard from godot to the new window and it will retain focus and input.
> 
> If I can help test something I'd be happy to.

does it happen on master still?
