### ISSUE TITLE
Keybindings in images script failing.

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#3988]
### The issue:
http://docs.qtile.org/en/latest/manual/commands/keybindings.html

I wanted to use gen-keybinding-img from https://github.com/qtile/qtile/tree/master/scripts
Script is started without arguments:
`python gen-keybinding-img`

But it fails with this traceback:

```python  
Traceback (most recent call last):
  File "/home/crystal/Downloads/script/gen-keybinding-img.py", line 429, in <module>
    f.render(output_file)
  File "/home/crystal/Downloads/script/gen-keybinding-img.py", line 175, in render
    self.add_logo(context)
  File "/home/crystal/Downloads/script/gen-keybinding-img.py", line 163, in add_logo
    logo = ImageSurface.create_from_png(logo_img)
  File "/usr/lib/python3.10/site-packages/cairocffi/surfaces.py", line 789, in create_from_png
    Surface.__init__(self, pointer)  # Skip ImageSurface.__init__
  File "/usr/lib/python3.10/site-packages/cairocffi/surfaces.py", line 158, in __init__
    self._check_status()
  File "/usr/lib/python3.10/site-packages/cairocffi/surfaces.py", line 170, in _check_status
    _check_status(cairo.cairo_surface_status(self._pointer))
  File "/usr/lib/python3.10/site-packages/cairocffi/__init__.py", line 88, in _check_status
    raise exception(message, status)
FileNotFoundError: [Errno cairo returned CAIRO_STATUS_FILE_NOT_FOUND: b'file not found'] 18
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Are you calling it as a standalone script? Its code suggests that it's written to be used within the git repo. It's looking for a file called `logo.png` in the parent folder of the script

**Comment by Crystal4276** [comment]
Yes.
I git cloned the whole repo and launched the script for there.
New error message. It seems `libqtile._ffi_pango` is missing.

```Traceback (most recent call last):
  File "/home/crystal/Downloads/qtile/libqtile/pangocffi.py", line 51, in <module>
    from libqtile._ffi_pango import ffi
ModuleNotFoundError: No module named 'libqtile._ffi_pango'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crystal/Downloads/qtile/scripts/gen-keybinding-img", line 420, in <module>
    kb_map = get_kb_map(config_path)
  File "/home/crystal/Downloads/qtile/scripts/gen-keybinding-img", line 359, in get_kb_map
    from libqtile.confreader import Config
  File "/home/crystal/Downloads/qtile/libqtile/confreader.py", line 31, in <module>
    from libqtile.backend.x11 import core
  File "/home/crystal/Downloads/qtile/libqtile/backend/x11/core.py", line 37, in <module>
    from libqtile.backend import base
  File "/home/crystal/Downloads/qtile/libqtile/backend/base.py", line 11, in <module>
    from libqtile import drawer, pangocffi, utils
  File "/home/crystal/Downloads/qtile/libqtile/drawer.py", line 35, in <module>
    from libqtile import pangocffi, utils
  File "/home/crystal/Downloads/qtile/libqtile/pangocffi.py", line 53, in <module>
    raise ImportError("No module named libqtile._ffi_pango, be sure to run `./scripts/ffibuild`")
ImportError: No module named libqtile._ffi_pango, be sure to run `./scripts/ffibuild`
```

**Comment by m-col** [comment]
Did you try running `./scripts/ffibuild` per the last line in the error message?

**Comment by Crystal4276** [comment]
Yes this is the output:
```bash
❯ ./ffibuild 
Building Pango interface
    Failed!
    This component is required.
Building xcursors
    Failed!
    This is optional and is needed for: X11 backend
Building PulseAudio interface
    Failed!
    This is optional and is needed for: PulseVolume widget
Building Wayland libinput interface
    Failed!
    This is optional and is needed for: Wayland backend input configurability

Failures for optional components can be ignored.
Pass -v to print full stack traces.
```

**Comment by usmcamp0811** [comment]
I can confirm I have having the exact same issue...

**Comment by m-col** [comment]
> Yes this is the output:

Could you try with `./ffibuild -v`? It will then print out the traceback of why the script failed. Hopefully it provides some useful info

**Comment by Crystal4276** [comment]
Yes sorry i could have done that. 
Some files are missing apparently:
```
❯ ./ffibuild -v
Building Pango interface
    Failed!
    This component is required.
python3: can't open file '/home/crystal/Downloads/qtile/scripts/./libqtile/pango_ffi_build.py': [Errno 2] No such file or directory

Building xcursors
    Failed!
    This is optional and is needed for: X11 backend
python3: can't open file '/home/crystal/Downloads/qtile/scripts/./libqtile/backend/x11/xcursors_ffi_build.py': [Errno 2] No such file or directory

Building PulseAudio interface
    Failed!
    This is optional and is needed for: PulseVolume widget
python3: can't open file '/home/crystal/Downloads/qtile/scripts/./libqtile/widget/pulseaudio_ffi.py': [Errno 2] No such file or directory

Building Wayland libinput interface
    Failed!
    This is optional and is needed for: Wayland backend input configurability
python3: can't open file '/home/crystal/Downloads/qtile/scripts/./libqtile/backend/wayland/libinput_ffi_build.py': [Errno 2] No such file or directory
```

**Comment by elParaguayo** [comment]
I'm not sure if this is an issue but, instead of running `./ffibuild`, you could try running `./scripts/ffibuild` from the root qtile folder as that's the command run by our `Makefile`.

**Comment by Crystal4276** [comment]
I'm on Arch.
I think the root qtile folder is `/lib/python3.10/site-packages/libqtile/`
If i look at the content of `./scripts` i dont see gen-keybinding-img or ffibuild .

```
site-packages/libqtile/scripts  via  v3.10.9 
❯ ls
check.py  cmd_obj.py  __init__.py  main.py  migrate.py  __pycache__  run_cmd.py  shell.py  start.py  top.py
```

**Comment by Crystal4276** [comment]
It worked !!!! 
Thanks.
I think a bit more directions in the doc would help :
http://docs.qtile.org/en/latest/manual/commands/keybindings.html

![mod4](https://user-images.githubusercontent.com/27446196/211885228-e5906cd5-4a17-4945-9948-d6aab0aad1a1.png)

**Comment by elParaguayo** [comment]
It might be easier if we add this to the `qtile ...` commands. That way it gets packaged correctly and we don't need to do any of that complicated steps (we should package the logo correctly too).

**Comment by m-col** [comment]
I'm hesitant to add this script to the main entrypoint because it's currently hard-coded to a specific keyboard layout (correct me if I'm wrong), and I don't think we should 'ship' a tool with such a big caveat. I'd be +1 if it was somehow more configurable in the layout or could get the keyboard layout from the system (if that's even possible). Otherwise, we could instead modify the script to check where it's being run from and catch any errors, informing the user of why it's failing (i.e. it needs to be run from git repo top folder)

**Comment by elParaguayo** [comment]
I was thinking of the first option (making it configurable) but I've never used the script so I've no idea how easy that would be.
