### ISSUE TITLE
[BUG] layout Columns broken after window.toscreen()

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#3995]
### The issue:

qtile-git
qtile-extra-git

Multi-monitor setup.
Screens [1,0,2]

I wanted to send an app window (celluloid) opened on screen 2 to be automatically sent to screen 0.
This is the hook i'm using:
```python
# If Celluloid opens move it to main screen 0
@hook.subscribe.client_name_updated
def celluloid(window):
    if window.name == "Celluloid":
        window.toscreen(0)
```
But after sending the window the layout Columns becomes broken on the receiving group.
(others groups on screen 0 survive)
The only way to recover is to restart qtile.
Video  before sending app window ->no issue:

https://user-images.githubusercontent.com/27446196/201685662-fac75088-c4a8-4800-b23f-2405deb46154.mp4

Video after sending app window -> weird window placement:

https://user-images.githubusercontent.com/27446196/201685819-b6dccf01-5295-48de-805b-a6fdeb0736ba.mp4

One error repeating  in Qtile.log
```python
2022-11-14 17:31:11,653 ERROR libqtile group.py:layout_all():L160 Exception in layout columns
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/group.py", line 158, in layout_all
    self.layout.layout(normal, screen_rect)
  File "/usr/lib/python3.10/site-packages/libqtile/layout/base.py", line 56, in layout
    self.configure(i, screen_rect)
  File "/usr/lib/python3.10/site-packages/libqtile/layout/columns.py", line 271, in configure
    pos += col.heights[c]
KeyError: Window(name='2022-11-14 17-27-47.mp4', wid=115343364)
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I'm struggling to work this one out!

In that example you posted above is `celluloid` in any way related to the `2022-11-14 17-27-47.mp4` window?

**Comment by Crystal4276** [comment]
> I'm struggling to work this one out!
> 
> In that example you posted above is `celluloid` in any way related to the `2022-11-14 17-27-47.mp4` window?

Yes celluloid was send to that screen (`2022-11-14 17-27-47.mp4` window) through the hook defined above and then its window was closed.
If you prefer i can take another movie showing the whole process (namely send app to screen 0 through hook, close the latter app, then open other apps).

**Comment by elParaguayo** [comment]
I wonder if there's some sort of race condition going on with the name change as the layout has a window with a different name.

Could you try changing your function into a coroutine (by changing `def` to `async def`) and see if that makes a difference?

**Comment by elParaguayo** [comment]
@Crystal4276 What's the status on this? Are you still having the issue? Did you try the suggestion above?

**Comment by Crystal4276** [comment]
Hello @elParaguayo 

Sorry it seems i missed your suggestion of using `async def.`
I first check that the issue was still there > yes it is.
Then I changed the hook with async def.

```python
# If Celluloid opens move it to main screen 0
@hook.subscribe.client_name_updated
def celluloid(window):
    if window.name == "Celluloid":
        window.toscreen(0)
 ```
 And it worked !
Not sure to understand what do you mean by a "racing condition" but it did the trick.
Thanks
