### ISSUE TITLE
[bug] qtile.disable_fullscreen

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4000]
### The issue:

qtile-git
qtile-extra-git

I'm getting slowly adventurous with qtile. So i hope it's really a bug and not a lack of understanding of python coding.

I have a game that launch in fullscreen mode by default.
I want it to start in group 3 and be inside a tiled window.
That's the relevant part of the hook i'm using:
```python
elif w_name =="EXAPUNKS":
        window.togroup("3")
        window.qtile.disable_fullscreen
        logger.warning("disable fullscreen ?")
```
The window goes to group 3, fine but stay in a fullscreen state.
Qtile.log
```python
2022-11-15 17:37:48,753 ERROR libqtile hook.py:fire():L406 Error in hook client_managed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/crystal/.config/qtile/config.py", line 971, in _screen0
    window.qtile.disable_fullscreen
  File "/usr/lib/python3.10/site-packages/libqtile/command/base.py", line 283, in __getattr__
    raise AttributeError
AttributeError
```
Xprop on the game window
```
_NET_WM_USER_TIME(CARDINAL) = 28830931
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64):
_NET_WM_NAME(UTF8_STRING) = "EXAPUNKS"
WM_NAME(STRING) = "EXAPUNKS"
XdndAware(ATOM) = BITMAP
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 113906
WM_LOCALE_NAME(STRING) = "C"
WM_CLASS(STRING) = "EXAPUNKS.bin.x86_64", "EXAPUNKS.bin.x86_64"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x2e287c2
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 1920, 0
		program specified minimum size: 1600 by 900
		program specified maximum size: 1600 by 900
WM_CLIENT_MACHINE(STRING) = "terrier"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
STEAM_GAME(CARDINAL) = 716490
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
You don't need the `qtile` attribute there. `disable_fullscreen` is a method of the window.

Try using `window.disable_fullscreen()` (if you're on the latest git version) or `window.cmd_disable_fullscreen` if you're on v0.22.1.

**Comment by Crystal4276** [comment]
Ohhhh.... well sorry.
I'm on qtile-git.
I thought that each time i see a command starting with `cmd_` i need to replace it with `qtile.`

So from there i did few stuffs:
- i used `window.disable_fullscreen()`. It doesn't work but at least no error in qtile.log.
- Then i added `async` in front of the function in the hook. I have no idea why, but  it works ! Except that the window is converted to floating instead of being tiled.
- Lastly, i used `window.toggle_floating()` instead of `window.disable_fullscreen()` and this does the job (async still needed).
