### ISSUE TITLE
Strange graphics behaivor [Xorg]

### ISSUE THREAD

**Issue by bssplatforms** [qtile/qtile#4002]
### The issue:

On some websites, my whole desktop changes it's color. Please see it in a video. Any thoughts what can cause such issue?

[farid@unknown ~]$ qtile -v
0.22.1

No errors in qtile.log

https://user-images.githubusercontent.com/56543439/202471141-5e600539-4301-44a3-bef9-ed0bae9cd26b.mp4

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I may be blind but I don't see any colour changes in that video.

**Comment by cnekmp** [comment]
> I may be blind but I don't see any colour changes in that video.

Concentrate on terminal window. You'll see lines are appearing when the tabs are changing. Same happen on menu bar also

**Comment by bssplatforms** [comment]
> I may be blind but I don't see any colour changes in that video.

Your comment solved my issue. Turns out my LCD had "RTS" mode enabled on it and even on recorded video it was showing "glitches". After reading your comment I've switched to mobile phone and I didn't see any color changes too. So I've turned that mode off on my LCD and it works now.

P.S. Yeah, pretty strange case tbh.... )
