### ISSUE TITLE
widget.CurrentLayoutIcon cannot work with .svg files

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4004]
### The issue:

qtile-git
Arch linux.

 widget.CurrentLayoutIcon is working with .png files stored in `custom_icon_paths`, but .svg files are not loaded.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. The widget is hardcoded to look for a file called `layout-<name>.png`. We should fix that. No reason the icon couldn't be an svg file.
