### ISSUE TITLE
Qtile Wayland backend: wallpaper doesn’t appear with correct configuration

### ISSUE THREAD

**Issue by IchikaZou** [qtile/qtile#4006]
### Qtile version

0.21.0-r1 on Gentoo

### The issue

Follow qtile official documentation to setup wallpaper but screen still black after re-launching qtile.

My Config:

from libqtile.config import Screen

screens = [
    Screen(
      wallpaper='~/Picture/wallpaper/minimalist.png',
        wallpaper_mode='fill',
    )
]

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
I suspect its because of the '~'. If you pass the path through `os.path.expand user()` I suspect

**Comment by m-col** [comment]
Oops hit send by accident.

...I suspect it should work.

But we should do this internally so let's keep this issue open to track that.

**Comment by IchikaZou** [comment]
I changed my config to this, still same result

My config:

from libqtile.config import Screen

screens = [
Screen(
wallpaper=os.path.expanduser('~/Picture/wallpaper/minimalist.png'),
wallpaper_mode='fill',
)
]

**Comment by m-col** [comment]
Should 'Picture' be 'Pictures' by any chance?

**Comment by IchikaZou** [comment]
It's Picture, I make a double check.

**Comment by IchikaZou** [comment]
I copy the path in my config and use lbs to check, the path is correct.

**Comment by IchikaZou** [comment]
I changed my path to `/usr/share/backgrounds/minimalist.png` and screen still appear black after re-launch.

**Comment by IchikaZou** [comment]
I tried xorg version and the wallpaper still not appear

**Comment by elParaguayo** [comment]
Are you sure your config is loading and it's not falling back to the default config (which has a black screen)?

The wallpaper works fine for me on xorg so I do think the issue is with your config somehow.

**Comment by IchikaZou** [comment]
The button right bar do show default config, how to I make sure qtile load my config?

**Comment by elParaguayo** [comment]
Where is your config saved? What happens if you run `python <your_config_file>`?

**Comment by IchikaZou** [comment]
No output

**Comment by elParaguayo** [comment]
If it runs with no error, that's good. 
Where is it saved?

**Comment by IchikaZou** [comment]
/home/localeuser/.config/qtile/config.yo

**Comment by elParaguayo** [comment]
ok. when you start qtile, can you run `qtile cmd-obj -o cmd -f reload_config` and then check the log file (`~/.local/share/qtile/qtile.log`)

**Comment by IchikaZou** [comment]
https://pastebin.com/v4cyEXsK

**Comment by elParaguayo** [comment]
Can you paste your config too.

**Comment by IchikaZou** [comment]
https://pastebin.com/771cH9BU

**Comment by elParaguayo** [comment]
You've copied the default config, added a new `screens` variable but not removed the old one which comes later in the file so it just overwrites yours.

**Comment by IchikaZou** [comment]
Ahh yes, it worked now. Thanks for the help.

I'm feel like a simpleton right now.
