### ISSUE TITLE
widget.groupbox / highlight_method=line / padding_y has no effect on line position

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4009]
qtile-git
qtile-extra-git

### The issue:

I'm trying to bring the pink line inside the RectDecoration
![image](https://user-images.githubusercontent.com/27446196/202837039-1cf730c6-1dfb-4463-92d3-7897c87b842c.png)

I thought i could do that with padding_y, but there was no effect of this parameter with `highlight_method=line`
(`padding_y` works with `highlight_method=border`)

```python
                widget.GroupBox(
                       font="monospace",
                       fontsize = 35,
                       spacing = 10,
                       margin_y = 2,
                       margin_x = 15,
                       padding = 5,
                       background=colors[1],
                       disable_drag = True,
                       active = colors[3],
                       inactive = colors[2],
                       highlight_method='line',
                       this_current_screen_border = colors[3],
                       other_current_screen_border=colors[4],
                       #block_highlight_text_color=colors[3],
                       highlight_color=colors[4],
                       this_screen_border=colors[3],
                       borderwidth = 2,
                       visible_groups=['1', '2', '3'],
                       **decor_nogroup
                ),
```
```python
decor_nogroup = {
    "decorations": [
        RectDecoration(
            #colour=colors[1],
            use_widget_background=True,
            line_width= 0,
            radius=[15, 15, 15, 15],
            filled=True,
            padding_y=6,
            padding_x=0,
            group=False,
        ), 
        RectDecoration(
            colour=colors[17],
            #use_widget_background=True,
            line_width= 1,
            radius=[15, 15, 15, 15],
            filled=False,
            padding_y=6,
            padding_x=0,
            group=False,
        ), 
    ],
}
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Wouldn't `padding_y` also impact the position of the labels?

**Comment by Crystal4276** [comment]
> Wouldn't `padding_y` also impact the position of the labels?

So far it's only `margin_y` that impact the position of the label.

using `padding_y` with `highlight_method=border` is able to redimension border highlight.
`padding_y=10`
![image](https://user-images.githubusercontent.com/27446196/202841283-adc66678-e4ac-480d-a808-8d5bf1eab43c.png)
`padding_y=2`
![image](https://user-images.githubusercontent.com/27446196/202841305-c072bc11-665f-4b85-8631-90db147bd6a9.png)

If we could get the same flexibility with line highlight, that would be perfect !

**Comment by elParaguayo** [comment]
Yeah, that seems reasonable.
