### ISSUE TITLE
Can't change on dragged

### ISSUE THREAD

**Issue by DasLixou** [qtile/qtile#4010]
### The issue:

So when i for example have a image dragged for drag and drop and i want to change to for example window group 3 or whatever these groups are called, i can't.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Interesting. If I drag an image from firefox and try to change groups, I can't. However, if I do the same with brave, I can switch groups.

**Comment by DasLixou** [comment]
> Interesting. If I drag an image from firefox and try to change groups, I can't. However, if I do the same with brave, I can switch groups.

hm.. but when i do it with for example thunar it also doesn't work...
