### ISSUE TITLE
PulseVolume widget should update on volume change event

### ISSUE THREAD

**Issue by dannycolin** [qtile/qtile#4011]
### The issue:

Qtile: 0.22.1
Widget config: 
`widget.PulseVolume(fmt="V: {}")` OR `widget.PulseVolume(fmt="V=: {}", update_interval=0)` 

**STR**

1. Add PulseVolume widget
2. Add a keybind to change your volume
3. Change volume

**Actual Behavior**

By default, PulseVolume has a `update_interval` of `0.2` and it creates a delay between the moment you change the volume and the widget redraw.

To avoid this, I set the `update_interval` to `0`. However, this workaround creates another issue making Qtile uses a lot of CPU (> 50%) at all time.

**Expected Behavior**

PulseVolume shouldn't have an `update_interval` by default and instead redraw its content when an event from PulseAudio API is received. This would eliminate the delay in the redrawing and be less taxing on the CPU than aggressively redrawing the widget content.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Crystal4276** [comment]
Hello,

I think i saw this problem reported before.
Probably this one :
https://github.com/qtile/qtile/issues/3966

**Comment by dannycolin** [comment]
@Crystal4276 Yes, that's the issue with `update_interval=0`. However, I opened this one after talking with mcol in #qtile about the fact that the widget should be event based instead of using an update interval. So it isn't a bug report but a feature request ;).

**Comment by mrtnvgr** [comment]
This widget is already event based. If you want to turn off updates on interval, you can set `update_interval` to None.

**Comment by mrtnvgr** [comment]
> This widget is already event based. If you want to turn off updates on interval, you can set `update_interval` to None.

```python
if self.update_interval:
    self.timeout_add(self.update_interval, self.timer_setup)
```

**Comment by mrtnvgr** [comment]
> ... If you want to turn off updates on interval, you can set `update_interval` to `None`.

I think we can make this as default. I will make a PR.

**Comment by dannycolin** [comment]
> This widget is already event based. If you want to turn off updates on interval, you can set `update_interval` to `None`.

It doesn't work for me. When I set it to `None`, the widget never returns the volume information and permanently shows `M`.

**Comment by mrtnvgr** [comment]
> > This widget is already event based. If you want to turn off updates on interval, you can set `update_interval` to `None`.
> 
> It doesn't work for me. When I set it to `None`, the widget never returns the volume information and permanently shows `M`.

Oh, my bad... I'm sorry, I didn't test that properly.

**Comment by mrtnvgr** [comment]
I don't have pulse audio on my pc. Can you test this diff please?

```diff
diff --git a/libqtile/widget/pulse_volume.py b/libqtile/widget/pulse_volume.py
index 64ce52b3..a9cac001 100644
--- a/libqtile/widget/pulse_volume.py
+++ b/libqtile/widget/pulse_volume.py
@@ -148,6 +148,7 @@ class PulseVolume(Volume):

     def on_sink_update(self, event_type, sink_index):
         self.timeout_add(0.1, self.get_sinks)
+        self.poll()

     def wait_for_operation(self, op):
         state = lib.pa_operation_get_state(op)

```

**Comment by dannycolin** [comment]
Same behaviour. Btw, I use pipewire-pulse.

**Comment by mrtnvgr** [comment]
> Same behaviour. Btw, I use pipewire-pulse. 

Can you check your `~/.local/share/qtile/qtile.log` file?

**Comment by ei-grad** [comment]
Same behaviour with pipewire-pulse. The reason is that the widget can't establish connection properly, it receives `PA_CONTEXT_AUTHORIZING` state into `on_connection_change` and doesn't handle it.

**Comment by ei-grad** [comment]
But it is not handled in all pulseaudio code samples either, strange :-/.

So, just the connection doesn't go to READY state for some reason.

**Comment by elParaguayo** [comment]
HI @ei-grad 

I don't use this widget, nor am I particular familiar with the pulseaudio bindings. However, if there's some spec documentation showing how the authorisation process should be handled by clients then we can certainly look at fixing the code.

**Comment by ei-grad** [comment]
I ended up with this custom widget:

```python
import pulsectl_asyncio 


class PulseVolume(base.InLoopPollText):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.listen_task = asyncio.create_task(self.listen())

    async def listen(self):
        try:
            async with pulsectl_asyncio.PulseAsync('event-printer') as pulse:
                server_info = await pulse.server_info()
                default_sink = await pulse.get_sink_by_name(server_info.default_sink_name)
                info = await pulse.sink_info(default_sink.index)
                text = '{:.2f}'.format(info.volume.values[0])
                self.update(text)
                async for event in pulse.subscribe_events('sink'):
                    logger.debug('pulse event: %r', event)
                    info = await pulse.sink_info(event.index)
                    logger.debug('sink %d info: %r', event.index, info)
                    logger.debug('volumes:', info.volume.values)
                    if event.index == default_sink.index:
                        text = '{:.2f}'.format(info.volume.values[0])
                        self.update(text)
        except Exception as e:
            logger.error("listen failed: %s", e, exc_info=True)
```

**Comment by elParaguayo** [comment]
We've got a new Pulse volume widget now which should solve this issue.
