### ISSUE TITLE
`Window.is_visible`, `Window.bring_to_front` and `Qtile.to_screen`  attributes are not available

### ISSUE THREAD

**Issue by keystroke3** [qtile/qtile#4016]
### The issue:

I wanted to create a sticky window workflow and but the new version of qtile broke my configs. I was using `qtile-git` from the AUR on Endeavor OS, but it broke and I couldn't log in to it. So I reverted to regular `qtile` from the community repos. I am currently running `version 0.22.1-1`. This is the relevant section of my config that I use to create a sticky window and move it accordingly:

```python
win_list = []
def sticky_win(qtile):
    if qtile.current_window in win_list:
        win_list.remove(qtile.current_window)
    else:
        win_list.append(qtile.current_window)

@hook.subscribe.setgroup
def move_win():
    c_win = qtile.current_window
    for w in win_list:
        if not w.is_visible:
            w.togroup(qtile.current_group.name)
            if w.info()['floating']:
                w.bring_to_front()
            if c_win:
                c_win.focus(warp=False)

@hook.subscribe.group_window_add
def sticky_to_front(g, new_w):
    for w in win_list:
        if w.is_visible and w.info()['floating']:
            w.bring_to_front()
            new_w.focus()

@hook.subscribe.client_killed
def remove_sticky_windows(window):
    if window in win_list:
        win_list.remove(window)

```
When  I toggle sticky on a window, I get this error:
```python
2022-11-22 00:42:46,056 ERROR libqtile hook.py:fire():L406 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/salvaje/.config/qtile/config.py", line 73, in move_win
    if not w.is_visible:
AttributeError: 'Window' object has no attribute 'is_visible'
```
When I remove the check for window visibility, I get this error instead:
```python
2022-11-22 00:44:24,654 ERROR libqtile hook.py:fire():L406 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/salvaje/.config/qtile/config.py", line 76, in move_win
    w.bring_to_front()
AttributeError: 'Window' object has no attribute 'bring_to_front'
```

I have another section that moves windows between visible groups on 2 screens.
```python
def window_to_previous_screen(qtile, switch_group=False, switch_screen=False):
    i = qtile.screens.index(qtile.current_screen)
    if i != 0:
        group = qtile.screens[i - 1].group.name
        qtile.current_window.togroup(group, switch_group=switch_group)
        if switch_screen == True:
            qtile.to_screen(i - 1)


def window_to_next_screen(qtile, switch_group=False, switch_screen=False):
    i = qtile.screens.index(qtile.current_screen)
    if i + 1 != len(qtile.screens):
        group = qtile.screens[i + 1].group.name
        qtile.current_window.togroup(group, switch_group=switch_group)
        if switch_screen == True:
            qtile.to_screen(i + 1)

```
with this I get this error after the window has moved and focus shift is attempted:
```python
2022-11-22 00:58:48,145 ERROR libqtile base.py:cmd_function():L216 Exception calling "<function window_to_previous_screen at 0x7f13aeb5b910>":
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/base.py", line 213, in cmd_function
    function(self, *args, **kwargs)
  File "/home/salvaje/.config/qtile/config.py", line 191, in window_to_previous_screen
    qtile.to_screen(i - 1)
AttributeError: 'Qtile' object has no attribute 'to_screen'
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
As you're not on latest git, you need to use `Window.cmd_is_visible`, `Window.cmd_bring_to_front` and `qtile.cmd_to_screen`.

**Comment by keystroke3** [comment]
Okay thanks, the errors have gone. However, I am wondering if the internal definitions of `Window.cmd_is_visible()` has changed. I used the command to check if the sticky window is visible on any screen and only move it when I change groups and it is cannot be seen on any screen. So if  the window is on screen1 group1, and switch to screen1  group2,  it should move, but if I switch to screen2 group3, it should not, because screen1 group1 is still visible.
Now, with `not w.cmd_is_visible()`  the sticky window behaves like a non-sticky window. With the visibility check removed the window follows the mouse movement and changes screens as well as groups instead of just groups.  I am wondering if the `is_visible` property changes or remains the same when switching to a group where the window is not visible.
As there something I am getting wrong?

**Comment by elParaguayo** [comment]
I don't believe there have been any changes.

**Comment by Crystal4276** [comment]
I think in your original code with qtile-git version you may have forgotten to import : 
```python
from libqtile import qtile
```

**Comment by keystroke3** [comment]
I am importing `qtile` at the very top of the file.  I have just pushed my current [config](https://github.com/keystroke3/dotfiles/blob/master/.config/qtile/config.py) file to my dotfiles repo, so may you can have a look at it and provide some feedback.

**Comment by elParaguayo** [comment]
Are there any outstanding questions here or can we close this?

**Comment by keystroke3** [comment]
I still don't know why the `is_visible()` is not behaving as it was before. It used to be `True` if the window is visible on any screen, but now it appears to be `True` all the time, even when the window is not actually visible. With the behavior from before I was able to have the sticky window only follow me when it is not visible on any screen. But now it follows the cursor across screens even when it is still visible on one screen.  Unless there is a bug in my code above that I am not seeing.
