### ISSUE TITLE
Qtile Wayland backend: version 0.22.1 has no cursor.

### ISSUE THREAD

**Issue by RyukaZou** [qtile/qtile#4028]
### The issue:

I bump my qtile version from 0.21.0-r1 to 0.22.1 and cursor is gone for good, I have modified the ebuild from Gentoo repository since `exeinto /etc/X11/Sessions` And `newexe "${FILESDIR}"/${PN}-session-r1 ${PN}`will cause emerge failure so I remove them for ebuild and emerge will success.

I’m not sure weather the bug is cause by modified ebuild or qtile itself.

qtile.log: https://dpaste.com/4RX589AUF

qtile-0.22.1.ebuild from Gentoo repository: https://github.com/gentoo/gentoo/blob/c7f677550b974766eb1bddb5771d01811f4f7e5c/x11-wm/qtile/qtile-0.22.1.ebuild

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Magnitudexx** [comment]
My cursor only dissapears on firefox/librewolf. Is that consistent with your problem

**Comment by IchikaZou** [comment]
> My cursor only dissapears on firefox/librewolf. Is that consistent with your problem

My cursor is gone from launch of qtile but this problem only appear in 0.22.1

**Comment by m-col** [comment]
Please could you try the git version and see if it persists? That said it may do, see: https://github.com/qtile/qtile/issues/4013

**Comment by Magnitudexx** [comment]
I am on that version

**Comment by IchikaZou** [comment]
> Please could you try the git version and see if it persists? That said it may do, see: https://github.com/qtile/qtile/issues/4013

Maybe is the same issue related to https://github.com/qtile/qtile/issues/3956

**Comment by IchikaZou** [comment]
> Ok, i think mine dissapears on group change or focus change to firefox so not the same problem as you have

I do have the same problem as yours in 0.21.0

**Comment by IchikaZou** [comment]
> Please could you try the git version and see if it persists? That said it may do, see: https://github.com/qtile/qtile/issues/4013

I emerge the git version but I can't launch qtile Wayland session, it give me this error.

https://dpaste.com/7VYPDVUMC

**Comment by jwijenbergh** [comment]
What about #3985?
