### ISSUE TITLE
Scaled BatteryIcon has vertical offset from middle of bar 

### ISSUE THREAD

**Issue by astronomike** [qtile/qtile#4043]
### The issue:

When I use the BatteryIcon widget with a scaling that's > 1.0, it seems like the icon gets shifted upwards from the middle of the bar, which messes with the alignment of other icons. 

The following widget method works correctly,
```    
widget.BatteryIcon(
    theme_path=home / ".config/qtile/battery-icons/",
    update_interval=10,
    scale=1.0,
),
```
![Screenshot from 2022-12-07 16-26-18](https://user-images.githubusercontent.com/5190106/206208459-d97de3e2-8e55-4db9-842d-ac76cd0e1d75.png)

But when I change the scale (to 1.4 for example), the following happens:

![Screenshot from 2022-12-07 16-28-17](https://user-images.githubusercontent.com/5190106/206208670-bdb6f7d8-e4fa-4126-8d6a-dd94923e191c.png)

Now the icon size is more consistent, but as you can see the icon is not aligned with the systray's nm-applet icon. 

Is there an easy way to solve this, so that the icon can be scaled down but still sit in the middle of the bar (vertically)? I naively tried to pass some extra padding or margin arguments to the widget, but that didn't work. I then looked at the source code of the BatteryIcon widget, and tried to edit the following method (which I thought was relevant):

```
    def draw(self) -> None:
        self.drawer.clear(self.background or self.bar.background)
        self.drawer.ctx.set_source(self.surfaces[self.current_icon])
        self.drawer.ctx.paint()
        self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.length)
```
by changing the value of the `offsety` argument in the last line. This sort of worked, but it seems like the widget border leaves some region at the top of the bar that is not of the same colour as the rest of the widget background.

![Screenshot from 2022-12-07 16-23-39](https://user-images.githubusercontent.com/5190106/206210194-2f0cee66-c216-476d-a36e-02dc9a831f4d.png)

It seems like there should be a solution to this, but I'm not very familiar with how this all works under the hood. If someone could please take a look at it, or show how to correct it, that would be great! 

Thanks

`qtile --version`:
0.22.1

`qtile-extras` in case it's relevant:
qtile-extras-git r212.f93534b-1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. Very odd. Will add to the list...

**Comment by astronomike** [comment]
Thanks very much!

**Comment by elParaguayo** [comment]
Did you manage to test it?
