### ISSUE TITLE
Mpris2 pollutes logs

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4056]
### The issue:
```
ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
NoneType: None
```
### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you describe what you do that triggers this or whether it happens all the time?

**Comment by ervinpopescu** [comment]
As far as I can tell, it happens on every pause and on every play.

```py
widget.Mpris2(
        font="CaskaydiaCove Nerd Font Mono Bold",
        foreground=colors["darkblue"],
        mouse_callbacks={"Button1": lazy.widget["mpris2"].show_popup()},
        margin=7,
        scroll=True,
        width=300,
        format="{xesam:title} - {xesam:artist}",
        scroll_interval=0.01,
        scroll_delay=1,
    )
```

```console
$ qtile -v
0.22.2.dev78+g48e55340
$ pacman -Q qtile-extras-git
qtile-extras-git r228.c125c64-1
```

**Comment by elParaguayo** [comment]
OK. Can you use the qtile version of the widget, not the qtile-extras one and see if you still get the same issue? Need to narrow this down. If it's a qtile-extras issue we should post this there instead.

Also, can you try applying #4057 to see if we can get a more helpful error message.

**Comment by ervinpopescu** [comment]
Ok, using `libqtile.widget` gives me the same errors. I'll apply that PR now.

**Comment by ervinpopescu** [comment]
Does restarting suffice?

**Comment by ervinpopescu** [comment]
```
2022-12-12 01:29:15,481 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 262, in process_message
    self.parse_message(*message.body)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 353, in parse_message
    self.update(self.displaytext)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 701, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```

**Comment by elParaguayo** [comment]
Thanks. That error is not unique to `Mpris2` (I've seen it lots of times elsewhere) but I don't know what's causing it.

Could you add a logger statement before the `update` call in line 353 of `mpris2widget.py`:
``` python
logger.warning(f"{self.displaytext=}")
```
Maybe that will give us a clue as to why the textbox is raising an error.

**Comment by elParaguayo** [comment]
Looks like #4057 fixes the logging error too so I should get that merged!

**Comment by ervinpopescu** [comment]
This is weird. I restarted my laptop and I can't reproduce. I'll try reloading/restarting qtile, because that's what I was doing yesterday while testing, maybe that has something to do with it.

**Comment by ervinpopescu** [comment]
I think this is `reload` related, as restarting qtile makes it disappear. It's not a huge priority, as it's just logs, what do you think? 

> Looks like #4057 fixes the logging error too so I should get that merged!

Sure seems like it :)

**Comment by ervinpopescu** [comment]
Do you have a "cleaning" system in place which removes the logfile after a certain size has been reached? I assume you do.

**Comment by elParaguayo** [comment]
I use `logrotate` to tidy my logs.

As for `reload` related, I was wondering about that. Do you have a startup script that's configuring monitors or anything?

**Comment by ervinpopescu** [comment]
> I use `logrotate` to tidy my logs.

I actually meant the qtile codebase, like some code that checks for size in log_utils or whatever :) But that looks cool too.

> As for `reload` related, I was wondering about that. Do you have a startup script that's configuring monitors or anything?

I don't actually, I just have a regular `autostart.sh` which I run with the `startup_once` hook.

> If we/you can reliably recreate a situation that triggers this then I can take a look. I've seen this on other widgets but I've not actually had a problem with the output but the log noise is undesirable.

As I was saying, this happens only after a reload and is suppressed by a restart, surely it has to do with something not getting initialized properly in the bar (unlikely) or in the widget, which upon drawing issues this error. Whatever the case is, I'm not actually that adamant about using the Mpris2 widget and I'll be closing this issue.

**Comment by elParaguayo** [comment]
No, there's nothing in the qtile codebase to rotate the log.

As for recreating it, that's fine, I suspect there's something happening with widgets not being finalised properly but I can investigate separately.

Lastly, I saw you tried the qtile-extras version with the popup - if you have any feedback/issues with that I'd love to hear them (but they should be posted on qtile-extras github page and not here!)

**Comment by ervinpopescu** [comment]
This is interesting, the logfile does get deleted/reinitialized every 9 MB or so. I did some stress testing on some widget and noticed it :)

Oops, you're probably right, that error has nothing to do with any type of initialization.

Other than [this](https://github.com/elParaguayo/qtile-extras/issues/91) everything is fine, and great work on the popups!! I have some really great use cases for them, but I don't have the time necessary to implement them at the moment 😿

**Comment by elParaguayo** [comment]
Ok. That one's still on the list...

**Comment by m-col** [comment]
> No, there's nothing in the qtile codebase to rotate the log.

Is that not what this does?: https://github.com/qtile/qtile/blob/master/libqtile/log_utils.py#L114-L118

**Comment by elParaguayo** [comment]
Oh. My mistake!

Learned something new today.
