### ISSUE TITLE
Inconsistent order of windows in TaskList

### ISSUE THREAD

**Issue by DCsunset** [qtile/qtile#4060]
### The issue:

Suppose there are 3 windows in the TaskList.
If I focus on the first window and then create a new window, TaskList will add the window at the end instead of inserting it right after the first one.

This is counter-intuitive since the new window should be next to the first window in any layout.
Ideally, TaskList should show the new window right after the first one.

After looking at some code, I think this issued is probably caused by the inconsistent orders between `Group.windows` and `_ClientList.clients`.

Other info:
* Qtile version: 0.22.1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I don't disagree with what you're saying. Part of the problem here is that I don't think all layouts have a consistent way of ordering clients but, presumably, we'd want the widget order to match the layout order so if bound a key to focus the next window, the widget would highlight the following item.

**Comment by DCsunset** [comment]
I looked further into the code recently. I think the main problem is that `_ClientList.add_client` has an option called `offset_to_current`, which makes it possible to insert new clients at a specific position. However, `_Group.add` doesn't have such option so it can only append new window to the list.

I think we can probably add an offset option to `_Group.add`. Then it's possible to pass the offset to other related functions like `Window.togroup` or `Window.set_group`.

Do you think this is a feasible solution? If so, I'm willing to work on it if you are busy with other features or bug fixes.

**Comment by DCsunset** [comment]
Hi @elParaguayo , is there any update on this issue? I just want to confirm whether this is a good idea before working on it.

**Comment by elParaguayo** [comment]
Sorry, must have missed the earlier post.

The problem you've got is that not every layout uses `_ClientList` to set the window order so I don't think you'll get that to work for every layout.

I'm not 100% sure but I think layouts have a `clients` attribute which may work but that doesn't including floating windows...

I'm not sure there's an easy solution here.

**Comment by DCsunset** [comment]
I see. Then we don't actuall need to map the `_ClientLIst` to `_Group.windows`. Instead, I think a workaround is that we can still possibly allow layouts to add to any position in `_Group.windows` so that each layout can customize their window layout in TaskList as well. This gives layouts more flexibility to decide how they want to display windows for other widgets like TaskList or WindowTabs.

**Comment by sephii** [comment]
I don’t know if that’s related, but navigating with `layout.up()` and `layout.down()` is very difficult when using a max layout and a tasklist since it jumps from one window to another without any apparent logic.

It would be nice if the order of windows in the tasklist would reflect the stack order of the max layout.
