### ISSUE TITLE
terminal position not accurate

### ISSUE THREAD

**Issue by notwidow** [qtile/qtile#4063]
### The issue:

![2022-12-13_15-16](https://user-images.githubusercontent.com/112823418/207291233-718c5da3-d0c8-449d-97e1-336b59018023.png)

ISSUE is in the picture.
all info about issue in picture.
OS: Arch 
WM:qtile v 0.22.1
Terminal alacritty and kitty (both have this issue)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I may not be able to do much on this until I'm back at home but, before then, some questions:
- Does this only happen with those apps or does every app have that issue? Qtile shouldn't treat them differently so it's a bit off if it's just those...
- Can you run the following commands in the terminal and then paste the output here:
```
qtile cmd-obj -o screen -f info
qtile cmd-obj -o window -f info
```

**Comment by notwidow** [comment]
> I may not be able to do much on this until I'm back at home but, before then, some questions:
> 
>     * Does this only happen with those apps or does every app have that issue? Qtile shouldn't treat them differently so it's a bit off if it's just those...
> 
>     * Can you run the following commands in the terminal and then paste the output here:
> 
> 
> ```
> qtile cmd-obj -o screen -f info
> qtile cmd-obj -o window -f info
> ```
```ruby
{'height': 1080, 'index': 0, 'width': 1920, 'x': 0, 'y': 0}
{'float_info': {'height': 945, 'width': 1440, 'x': 5, 'y': 29},
 'floating': False,
 'fullscreen': False,
 'group': '1',
 'height': 1040,
 'id': 8388610,
 'maximized': False,
 'minimized': False,
 'name': 'robot@host: ~',
 'width': 1904,
 'wm_class': ['Alacritty', 'Alacritty'],
 'x': 5,
 'y': 29}
```

**Comment by elParaguayo** [comment]
Thanks. Can you also share your config for that layout?

**Comment by elParaguayo** [comment]
This might be a good example of something I've been confused by in our code and actually reflects the behaviour I expected to see.

Your config defines a margin of 5 and a border of 3, so a total of 8 pixels before the window content. Putting that on the left and right of the window means 16 pixels are needed for the margin and border leaving a total width of (1920-16) = 1904 pixels. This is why you get that window width.

However, the window is being placed at `x=5` i.e. excluding the border width. If that's the case, the window width should be increased accordingly.

I'll need to look at this in more detail later.

**Comment by elParaguayo** [comment]
Hmm. I've tried both alacritty and kitty and both are positioned correctly for me on monadtall.

**Comment by notwidow** [comment]
> Hmm. I've tried both alacritty and kitty and both are positioned correctly for me on monadtall.

mine is also fixed. not sure why that happened yesterday.

**Comment by notwidow** [comment]
> Hmm. I've tried both alacritty and kitty and both are positioned correctly for me on monadtall.

between help me get rid of this setting. 
When i have more than 1 windows or programs whatever you say it. let call it clients as qtile says. so when i have more than 1 clients open. and i reload the config then the focus also moves to the last client opened. How to stop this behaviour of qtile? . For example i have 3 clients open and my focus is on the 2nd client or 1st client. Now if i reload the config. Then the focus automatically moves to the last client. How to stop this behaviour. I want to keep the focus on the client which currently is being focused.
