### ISSUE TITLE
Strange text behaviour

### ISSUE THREAD

**Issue by mrtnvgr** [qtile/qtile#4066]
I noticed something odd.

I replaced IDLE -> "-.-" in my config and the dot appears centered?

![](https://i.imgur.com/SqYcgzq.png)

But when I change it to two dots ("-..-"), text appears fine.

![](https://i.imgur.com/N3tPHfj.png)

_Originally posted by @mrtnvgr in https://github.com/qtile/qtile/pull/4061#issuecomment-1350893928_

**Comment by mrtnvgr** [comment]
@elParaguayo any updates on this?

**Comment by elParaguayo** [comment]
They both render fine for me.

Can you try a different font?

**Comment by mrtnvgr** [comment]
> They both render fine for me.
> 
> Can you try a different font?

Interesting... This issue appears only on `CaskaydiaCove Nerd Font Bold` font, other fonts work fine 🙃. Should I report this bug to nerd-fonts repo?

Noto Sans font:
![](http://0x0.st/o5Sh.png)
![](http://0x0.st/o5SF.png)

**Comment by elParaguayo** [comment]
Might be worth seeing if they have an idea about what's happening.

**Comment by Finii** [comment]
`.-` is a coding ligature that is present in Cascadia Code. Although I have no clue which language that might be.

Other typical examples are `->` and `=>` which become a 'real' arrow.

See https://github.com/microsoft/cascadia-code/wiki/Coding-ligature-coverage

I guess you need to turn ligatures off when rendering, except people expect the ligatures :thinking: 

Sometimes ppl want a ligature-free patched font, but that seems to be the minority.
If you want a 'non-ligature Nerd Font patched Cascadia Code' you can
* remove the ligatures from the Nerd Fonts font with some tool
* use Delugia Mono instead (which is not related to but uses the same tools as Nerd Fonts)
