### ISSUE TITLE
client_urgent_hint_changed hook not firing

### ISSUE THREAD

**Issue by ava5627** [qtile/qtile#4074]
### The issue:

I'm trying to use the client_urgent_hint_changed hook however it doesn't seem to be firing ever. The group box and task list widgets update and the next_urgent command works 
```
@hook.subscribe.client_urgent_hint_changed
def urgent_hint_changed(window):
    logger.warning(f"urgent hint changed for {window.name}")
```
I set up a key-bind to look at the window's attributes and saw that `window.urgent` and `window._demands_attention` were True but `window.hints["urgent"]` was False. Running `window.update_hints()` manually does cause the hook to fire

I found #1847 which might be related

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
The groupbox and tasklist widgets use the same hook, so if they are updating then the hook must be getting fired. Are you certain your hook is being subscribed? E.g. if it's in a separate config file beside config.py, that file needs to be imported to get it to load.

> I set up a key-bind to look at the window's attributes and saw that window.urgent and window._demands_attention were True but window.hints["urgent"] was False. Running window.update_hints() manually does cause the hook to fire

The important one here is `window.urgent` so if it's `True` then the urgency is being correctly picked up.

**Comment by austin5627** [comment]
Yeah, thats what I'm finding so weird. I'm certain it's subscribed because it does fire but only after I call update_hints manually.

code I'm using
```python
def debug_function(qtile):
    windows = list(qtile.windows_map.values())
    for w in windows:
        if "firefox" in w.window.get_wm_class():
            logger.warning("before")
            w.update_hints()
            logger.warning("after")

@hook.subscribe.client_urgent_hint_changed
def urgent_hint_changed(window):
    logger.warning(f"urgent hint changed for {window.name}")
```
I'll cause the window to become urgent, the groupbox will change color and nothing else will happen. Then I'll trigger `debug_function` and 
```
2022-12-18 00:05:29,720 WARNING libqtile config.py:debug_function():L84 before
2022-12-18 00:05:29,720 WARNING libqtile config.py:urgent_hint_changed():L518 urgent hint changed for Google — Mozilla Firefox
2022-12-18 00:05:29,720 WARNING libqtile config.py:urgent_hint_changed():L518 urgent hint changed for Google — Mozilla Firefox
2022-12-18 00:05:29,720 WARNING libqtile config.py:debug_function():L86 after
```

**Comment by ava5627** [comment]
I was able to figure out what was causing this. If `focus_on_window_activation` is `urgent` or `smart` then `window.urgent` is set to `True` but it never fires the hook. The reason that the group box and task list widgets were updating was because the name of the window was changing and they are also subscribed to the name change hook.
