### ISSUE TITLE
Vertical monitor isn't really supported

### ISSUE THREAD

**Issue by yungParrot** [qtile/qtile#4078]
### The issue:

```bash
$ qtile --version
0.22.1
```

I have to external displays connected to my laptop through and USB-C docking station. They get detected and I've set them up like this :point_down: 
```bash
#!/bin/sh
xrandr --output eDP1 --primary --mode 1920x1080 --pos 1840x1680 --rotate normal --output DP1 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off --output DVI-I-2-2 --mode 1920x1080 -r 60 --pos 0x0 --rotate left --output DVI-I-1-1 --mode 3440x1440 -r 144 --pos 1080x240 --rotate normal
```
![image](https://user-images.githubusercontent.com/39010895/208950739-97772a11-d283-42a3-96e1-2934ae547e77.png)

The problem is that qtile doesn't really understand what's happening with `DVI-I-2-2`-> the mouse works correctly and X11 knows that this display is rotated but qtile thinks that it's not... windows aren't rotated (the monitor is set vertically but the windows are horizontally)

My config can be found [here](https://gitlab.com/yungParrot/dotfiles/)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by yungParrot** [comment]
![20221221_171436](https://user-images.githubusercontent.com/39010895/208951760-a48ecdcb-a7c7-4429-a4c0-1117bf52ce89.jpg)

**Comment by elParaguayo** [comment]
Not ignoring this. I just don't have access to a second monitor for a couple more weeks. I'll take a look then.

**Comment by wingej0** [comment]
> Not ignoring this. I just don't have access to a second monitor for a couple more weeks. I'll take a look then.

I use a vertical monitor everyday, and I haven't had this problem...

**Comment by yungParrot** [comment]
> > Not ignoring this. I just don't have access to a second monitor for a couple more weeks. I'll take a look then.
> 
> I use a vertical monitor everyday, and I haven't had this problem...

@wingej0 could you show me your qtile config? Maybe the issue on my side could be caused by the fact that my displays are connected through an usb-c dock that uses display link? 🤔

**Comment by wingej0** [comment]
> @wingej0 could you show me your qtile config? Maybe the issue on my side could be caused by the fact that my displays are connected through an usb-c dock that uses display link? thinking

Happy to.  Here is my screens.py module:
```
from .widgets import init_widgets, init_bottom_widgets
from colors import theme

from qtile_extras import widget
from libqtile import bar
from libqtile.config import Screen

# Initialize widgets
main_widgets = init_widgets(1)
secondary_widgets = init_widgets(2)
vertical_widgets = init_widgets(3)
bottom_widgets = init_bottom_widgets(1)
secondary_bottom_widgets = init_bottom_widgets(2)

# Remove all widgets from vertical monitor except groupbox and Mpris2
del vertical_widgets[10:15]

# Remove Systray from bottom bar for second monitor
del secondary_bottom_widgets[9:10]

# Define 3 monitors
screens = [
    Screen(
        top=bar.Bar(
            widgets=main_widgets,
            size=30,
            background="#00000000",
            margin=4, 
            opacity=0.9
        ),
        bottom=bar.Bar(
            widgets=bottom_widgets,
            size=24,
            background=theme.bg,
            margin=0, 
            opacity=0.9
        ),
        wallpaper=theme.wallpaper1,
        wallpaper_mode="fill"
    ),
    Screen(
        top=bar.Bar(
            widgets=vertical_widgets,
            size=30,
            background="#00000000",
            margin=4, 
            opacity=0.9
        ),
        wallpaper=theme.wallpaper3,
        wallpaper_mode="fill"
    ),
    Screen(
        top=bar.Bar(
            widgets=secondary_widgets,
            size=30,
            background="#00000000",
            margin=4, 
            opacity=0.9
        ),
        bottom=bar.Bar(
            widgets=secondary_bottom_widgets,
            size=24,
            background=theme.bg,
            margin=0, 
            opacity=0.9
        ),
        wallpaper=theme.wallpaper2,
        wallpaper_mode="fill"
    ),
]
```

The rest of my config is at https://github.com/wingej0/qtile.git.  Feel free to explore.  I have my two horizontal monitors connected via a USB-C dock with display port, and my vertical monitor is connected via HDMI.  I will try to turn one of my display port ones vertical and let you know how it works.  In my config, the second screen is the vertical one.

**Comment by wingej0** [comment]
![vertical](https://user-images.githubusercontent.com/19930583/210855840-38311bd5-e2a4-46ee-a673-4290cf81c001.jpg)

My two monitors hooked up via USB-C and Display Port appear to work vertically.  Sorry about the glare.

**Comment by yungParrot** [comment]
@wingej0 @elParaguayo - I've looked into this issue a bit more and it seems that this problem is related to my USB-C dock that uses DisplayLink

When I connect the rotated display through my microHDMI port, everything works as intended...
When I connect the rotated display through my USB-C dock (I use [i-tec USB 3.0/USB-C/Thunderbolt 3 Dual Display, PD 65W](https://www.x-kom.pl/p/456371-stacja-dokujaca-do-laptopa-i-tec-usb-30-usb-c-thunderbolt-3-dual-display-pd-65w.html#Specyfikacja)), it doesn't really work - I think that this might be related to DisplayLink and how it handles rotating displays

I don't know if this can be fixed through qtile or should I contact the DisplayLink devs 🤔

**Comment by elParaguayo** [comment]
If the rotation isn't being picked up correctly because of the dock then it's not a qtile issue.

Can you just just `xrandr` to force the rotation?

**Comment by yungParrot** [comment]
Ok then I'll close this issue :cowboy_hat_face: 

---

> Can you just use `xrandr` to force the rotation?

wdym exactly? [This is the `xrandr` script I was using](https://gitlab.com/yungParrot/dotfiles/-/blob/fd34c68a949b437ad49fff09339c50fea829e4d8/.screenlayout/home.sh). I tried setting up that display with 

```bash
  --output DVI-I-2-2 \
  --mode 1920x1080 \
  -r 60 \
  --pos 0x0 \
  --rotate left
```

but it didn't work -> `xrandr` was rotating the display correctly (the mouse was working alright), but it seemed like qtile wasn't affected by the rotation...

I currently rotated my screen back to the "normal" position and I think I will stick to it :cowboy_hat_face:
