### ISSUE TITLE
Fullscreen mode doesn't work properly

### ISSUE THREAD

**Issue by mrtnvgr** [qtile/qtile#4082]
### The issue:

My terminal emulators (st, urxvt) don't resize properly on full-screen mode, but all other gui applications work fine.
<br>
Screenshots:
![](http://0x0.st/o5Wn.png)
![](http://0x0.st/o54s.png)
<details>
<summary>Other states</summary>

Tiled:
![](http://0x0.st/o5WF.png)

Floating:
![](http://0x0.st/o5WC.png)

</details>
<br>

My keybinding:
```
Key([mod], "F11", lazy.window.enable_fullscreen(), desc="Set state fullscreen to window"),
```
(`lazy.window.toggle_fullscreen` doesn't work either)

<br>
I think that full-screen mode works only when a software has a built-in full-screen support.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
This is explained in dwm's (other wm faq):

 ```
This is due to the column-based nature of terminals. Terminals don't just
insert space somewhere, but tell the WM they can't be resized in a certain
way. The terminal can't use the "wasted space" anyway, so this is purely
aesthetics.
```

To fix this on the St side, apply the following patch https://st.suckless.org/patches/anysize/

We can fix this on the qtile side, but it's more of a terminal issue than a wm issue
