### ISSUE TITLE
hide_show_bar("all") errors when there are bar.Gap objects on any side

### ISSUE THREAD

**Issue by ugly-bastard** [qtile/qtile#4090]
### The issue:

```
❯ qtile --version
0.22.1
```
If there are Gap objects on any side, and use the "all" option to toggle bar visibility with `hide_show_bar()` function, it throws an error warning.
For my case, I have a bar only on one side, bottom, and rest are `Gap`s, the `hide_show_bar()` function's default option "all".

logs from `~/.local/share/qtile/qtile.log`
```
2022-12-28 06:08:54,637 ERROR libqtile manager.py:process_key_event():L407 KB command error hide_show_bar: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 1565, in cmd_hide_show_bar
    if is_show is None:
AttributeError: 'Gap' object has no attribute 'is_show'
```
For the key press event, I'm using this in my config, since "all" is default
`Key([mod], "b", lazy.hide_show_bar(), desc="Toggle bar visibility")`
Instead of using the `if bar:` condition, checking if the bar is an actual bar object or not resolves the issue.
```
for bar in [screen.left, screen.right, screen.top, screen.bottom]:
#if bar:                                ## the original condition
if isinstance(bar, libqtile.bar.Bar):
    if is_show is None:
        is_show = not bar.is_show()
    bar.show(is_show)
```
I don't know if this is meant to be as is for bars on all sides only, but I think this way, you wouldn't have to toggle each bar one at a time either.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. Agreed that this looks like a bug. I can submit your fix as a PR later unless you'd like to do it yourself.

**Comment by ugly-bastard** [comment]
I have made a pull request (is my first on github so was kinda excited)
