### ISSUE TITLE
Can't change tabs on waterfox

### ISSUE THREAD

**Issue by MelihDarcanxyz** [qtile/qtile#4095]
### The issue:

```
> qtile --version
> 0.22.1

> cat ~/.local/share/qtile/qtile.log
> 2022-12-28 23:44:55,609 WARNING libqtile bar.py:_configure_widget():L315 Widget removed: Systray does not support <libqtile.backend.wayland.core.Core object at 0x7f358b702140>.
> 2022-12-28 23:44:55,721 WARNING libqtile bar.py:_configure_widget():L315 Widget removed: Systray does not support <libqtile.backend.wayland.core.Core object at 0x7f358b702140>.
```
I wanted to move a tab to the end on Waterfox and the tab just doesn't move.
Tried the same thing with firefox, sometimes it works, sometimes I see heavy slow down and lots of black boxes. I'm on wayland.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
The black boxes sound like waterfox is running via XWayland. Are you running it with `MOZ_ENABLE_WAYLAND=1` set in the environment? If not, does doing so fix the issue?

**Comment by MelihDarcanxyz** [comment]
Black boxes happen on Firefox, not Waterfox. Tabs just doesn't move on Waterfox. This doesn't happen on River or Sway so I doubt that it's about XWayland.

**Comment by MelihDarcanxyz** [comment]
Is there someone who can confirm this issue is fixed as I'm not using qtile anymore. To reproduce:

```
1. Open waterfox
2. Open multiple tabs
3. Click and hold one of the tabs and try to move it to another position. Like hold the first tab and move it to the last position.
4. If it works, please let me know so I can close the issue.
```

**Comment by jwijenbergh** [comment]
> Is there someone who can confirm this issue is fixed as I'm not using qtile anymore. Qtile should run on Wayland backend. To reproduce:
> 
> ```
> 1. Open waterfox
> 2. Open multiple tabs
> 3. Click and hold one of the tabs and try to move it to another position. Like hold the first tab and move it to the last position.
> 4. If it works, please let me know so I can close the issue.
> ```
> 
> Firefox was problematic too. It was slowing down heavily and black boxes were popping up everywhere. But the tab was moving fortunately. Can someone test this too?

Sorry the github actions bot is annoying. Feel free to throw bad words at it

**Comment by jwijenbergh** [comment]
It seems to work for me, are you still on qtile 0.22.1?

**Comment by MelihDarcanxyz** [comment]
> It seems to work for me, are you still on qtile 0.22.1?

Not using qtile anymore. Thank you for verifying.
