### ISSUE TITLE
Brave browser bugs Qtile's bar when starting

### ISSUE THREAD

**Issue by zLuxorZ** [qtile/qtile#4097]
### The issue:

Version: 0.21.1.dev14+g7e376dcf

Every time when I open Brave-browser for the first time, it displays its icon on the bar. It only happens with Brave. After restarting Qtile it gets solved. It started appearing after a Qtile update.

This is the picture of the icon. 
https://imgur.com/a/xAWdbc2

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Very weird. Can't think of any reason why that would happen.

Can you share your config please.

**Comment by zLuxorZ** [comment]
Here you have the [Config](https://github.com/zLuxorZ/qtileconfig), thank you for your help.

**Comment by m-col** [comment]
Ha that's pretty bizarre. Does it stop if you comment out your `widget.Systray`?

Would you be able to do `git bisect` to try to identify which commit introduced the bug?

**Comment by zLuxorZ** [comment]
It seems like it was a Brave error that was causing the bug. After the last update, it got solved. Even though, it was really strange.

**Comment by elParaguayo** [comment]
OK. Thanks for letting us know. We'll close this for now.

**Comment by Mustafa-cpp** [comment]
![image](https://user-images.githubusercontent.com/80924218/217048681-6b54f7b2-9eab-4c0e-b9c5-0b3fbf78dd5c.png)
still present after updating

**Comment by elParaguayo** [comment]
Could you remove the systray widget from your bar and see if the issue goes?

**Comment by Mustafa-cpp** [comment]
Yes it did solve the problem but I use the systray for wifi connections and clipboard

**Comment by ZacJMagee** [comment]
What happened with this? I have the same issue.
![image](https://github.com/qtile/qtile/assets/131154366/36350b5e-823a-47ac-84e0-380e3abbd13f)

**Comment by ervinpopescu** [comment]
I've had this issue with Chrome as well, if it helps.
