### ISSUE TITLE
Keychords are not being escaped

### ISSUE THREAD

**Issue by Wisehh** [qtile/qtile#4099]
### The issue:

I recently updated qtile on my system and the behavior of the keychords changed in an unexpected way. In my configuration I have the following keychord:

```
...
    KeyChord([sup], "p", [
        KeyChord([], "q", [
            Key([], "a", lazy.spawn("qalculate-gtk")),
            Key([], "u", lazy.spawn("qutebrowser")),
        ]),
    ]), 
...
```

When I run the combination "Super + p + q + q + a" qalculate opens but the keychord state stays at "Super + p", so if I press "q + u" qutebrowser also opens. I think the behavior is a bug since "super + p" is not defined as a mode, so it should escape completely from opening qalculate.

In case it would be useful to add "lazy.ungrab_all_chords()" after the command works to fix it, but I think the expected behavior should be that the keychord once completed should apply it automatically unless otherwise stated (by defining a mode).

**Aditional info**
- `qtile --version` -> `0.22.1`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I think this has been fixed since the 0.22.1 release.

**Comment by Wisehh** [comment]
Yes sir, I was able to verify and it works perfectly with the commit. Thank you very much.

**Comment by elParaguayo** [comment]
Great. Thanks for checking.
