### ISSUE TITLE
Drag skips window floating with upper left corner on other screen.

### ISSUE THREAD

**Issue by mattharrison** [qtile/qtile#41]
If I've dragged a window so it's upper left corner is on the other screen, I'm no longer able to drag it around using a click on the current screen.

There should be a mechanism to determine that a click was on a window even if it belongs to another group/screen.

**Comment by MrMagne** [comment]
I have a really strange behavior when I drag a window from a screen to another.
To reproduce, have two windows on screen A (say A1 and A2) and two windows on screen B (B1, B2).
move A1 to screen B by mouse drag, when window is fully in screen B you find yourself dragging another window (B1), and everything is messed up... and if you try to drag back to screen A, you end up moving A2...

Is it related or should I open another issue ?

**Comment by flacjacket** [comment]
Yes, that behavior is related to this bug.

On Tue, Aug 11, 2015, 09:44 MrMagne <notifications@github.com> wrote:

I have a really strange behavior when I drag a window from a screen to
another.
To reproduce, have two windows on screen A (say A1 and A2) and two windows
on screen B (B1, B2).
move A1 to screen B by mouse drag, when window is fully in screen B you
find yourself dragging another window (B1), and everything is messed up...
and if you try to drag back to screen A, you end up moving A2...

Is it related or should I open another issue ?

—
Reply to this email directly or view it on GitHub
<https://github.com/qtile/qtile/issues/41#issuecomment-129962603>.<img src="
https://ci5.googleusercontent.com/proxy/p1CyEZCl8Q409Ey_z6x5aJnTzkuagt_CWTWCkzUS9vFluWLhocvLzab-trG4HhVVbWuWw9dpcO4O07d1pAEWUBG-dOtJgIC3Jo4865SEh8sLU0K584KvYrdLJyhK6wjHUwncbxyLTft7UZr1VuwSujC63ifYQA=s0-d-e1-ft#https://github.com/notifications/beacon/AApkhcYzxZGjnK3GlVmGAuZ_HQytrS--ks5omh04gaJpZM4Aawj-.gif
">

**Comment by ramnes** [comment]
Damn, this bug is so old, and yet so annoying!

**Comment by flacjacket** [comment]
Dragging windows between monitors works! Finally!
