### ISSUE TITLE
Cursor disappear when open application

### ISSUE THREAD

**Issue by wagnerc4** [qtile/qtile#4102]
### The issue:

debian 11 wayland
qtile --version = dev

The mod4 key dosent work... so I ad a mouse callback in one line of the config.py:

widget.TextBox("Press &lt;M-r&gt; to spawn", foreground="#d75f5f", mouse_callbacks={"Button1": lazy.spawncmd()}),

I it works, but the cursor disappear.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Odd. Does it come back after you've typed in the command to spawn? or if you move the mouse again?

**Comment by wagnerc4** [comment]
Is the mouse the pointer.
It occur when move the mouse again, after a application is open from the command input.

**Comment by wagnerc4** [comment]
1. Click with the mouse pointer on command to spawn.
2. Write command.. example: lxterminal
3. The application open.
4. When move the mouse pointer it disappear.

Sorry I did not explain well before.

**Comment by elParaguayo** [comment]
I'm still struggling to follow this. `spawncmd` starts the `Prompt` widget and lets you start typing a command name to execute. Clicking on that does nothing so I don't understand point 1 in your post.

**Comment by Crystal4276** [comment]
Are you using an nvidia card ?
It reminds me this bug:
https://github.com/qtile/qtile/issues/3864

**Comment by wagnerc4** [comment]
Hello!
All work as spected in the points 1, 2, 3.  Except in the point 4.
I'm a Intel card. Is a laptop Dell XPS

**Comment by wagnerc4** [comment]
Sorry I'm using...

**Comment by m-col** [comment]
Does it happen no matter what command you spawn, and no matter what window is focussed or under the pointer?

Did this always happen or did the issue recently appear for you?

**Comment by wagnerc4** [comment]
It always happen.
It happen no matter what command I spawn.
It exactly happen when the new window spawned is focussed... if I move the pointer only on the bar, it no disapepear.
