### ISSUE TITLE
qtile build error

### ISSUE THREAD

**Issue by krafi-org** [qtile/qtile#4104]
### The issue:

Python 3.11.1
pip 22.2.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Linux 6.0.7-301.fc37.x86_64 x86_64
-------------------

sudo pip install qtile
https://paste.rs/oSO

pip install xcffib
https://paste.rs/9eW

lets try,
`
git clone https://github.com/qtile/qtile.git
cd qtile
pip install .
`

https://paste.rs/CpZ

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Firstly, `sudo pip install` is generally a bad idea. It installs files in system folders but your package manager has no knowledge of them.

So, either use a package manager to install what you need or use `pip install --user` to install the files in your user's folder.

`pip install` without `--user` will try to install in `/usr/lib` which will not be writable by an unprivileged user.

**Comment by elParaguayo** [comment]
Closing this for now but please re-open it if you're still having issues.
