### ISSUE TITLE
Battery Widget not displaying time to empty correctly

### ISSUE THREAD

**Issue by wingej0** [qtile/qtile#4105]
### The issue:

Qtile Version 0.22.1

I want my battery widget to show battery percentage and time to empty.  Instead, it shows something like this: "93% (-5937000:00)".  It shows time to full correctly when plugged in.  My config worked correctly on my System76 Lemur Pro.  I'm now on an HP ZBook Mobile Workstation, and it displays incorrectly.  It appears to be distro agnostic.  The problem exists on Vanilla Arch, EndeavourOS, and OpenSuse Tumbleweed.

My config reads:
```
widget.Battery(
            background=theme.color1,
            foreground=theme.bg,
            format = "{percent:2.0%} ({hour:d}:{min:02d})",
            mouse_callbacks = {
                'Button1' : power_management,
            },
        ),
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
We just read the kernel information about the battery so I would expect this to be consistent across distros and is more likely to do with how the kernel sees your battery.

**Comment by wingej0** [comment]
Any ideas on how I can fix it in my config or even where to start looking?

**Comment by elParaguayo** [comment]
When the battery is discharging, the widget looks at how much energy is left in your battery and how much current you're using.

So, to start off, can you paste the outputs of these commands:
```
cat /sys/class/power_supply/BAT0/charge_now
cat /sys/class/power_supply/BAT0/current_now
```

**Comment by wingej0** [comment]
```
cat: /sys/class/power_supply/BAT0/power_now: No such file or directory
```

**Comment by elParaguayo** [comment]
Actually, I think that's the problem - if `power_now` returns an error then you get a `-1` value in the widget code.

**Comment by elParaguayo** [comment]
ok - can you just do an `ls /sys/class/power_supply/BAT0`

**Comment by elParaguayo** [comment]
I think you've hit this issue: https://github.com/qtile/qtile/pull/1516#issuecomment-576411671

**Comment by wingej0** [comment]
> I think you've hit this issue: [#1516 (comment)](https://github.com/qtile/qtile/pull/1516#issuecomment-576411671)

It would appear so.  I have an HP laptop too.

**Comment by elParaguayo** [comment]
Long shot, but can you try running this: `busctl get-property org.freedesktop.UPower /org/freedesktop/UPower/devices/battery_BAT0 org.freedesktop.UPower.Device TimeToEmpty`
I expect UPower reads the same information but let's see if this gives anything.

**Comment by wingej0** [comment]
```
busctl get-property org.freedesktop.UPower /org/freedesktop/UPower/devices/battery_BAT0 org.freedesktop.UPower.Device TimeToEmpty
x 0
```

**Comment by elParaguayo** [comment]
Ok, so UPower can't read it either. Not sure there's much more we can do here as it seems to be an issue with HP laptops. Might be worth searching more about that and seeing if anyone's found a way to get the information.

**Comment by wingej0** [comment]
Will do.  Thanks for your help.
