### ISSUE TITLE
Overlapping widgets loose mouse callback controls

### ISSUE THREAD

**Issue by Coderangshu** [qtile/qtile#4111]
### The issue:

I wanted to do X, but Y happened, and I expected Z. I think this is a bug.
In qtile bar added some widget.WidgetBox seperated by widget.Spacer, when on opening a widgetBox it overlaps another widget I cannot close the WidgetBox as I expected I can close it as it is displayed above the other widget, there's no mouse_callback registered on the open WidgetBox, I think this is a bug.
![before](https://user-images.githubusercontent.com/57983431/211632150-294beb01-2dd0-4e9a-9a9d-bb6dd0278e01.png)
![after](https://user-images.githubusercontent.com/57983431/211632140-65aea015-1716-48ea-903e-18975073f3ee.png)

As shown above 1st pic is before opening the weather WidgetBox, the 2nd pic is after opening, cannot close the weather WidgetBox by mouse click

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Widgets shouldn't overlap. I suspect having a spacer in the widgetbox doesn't help (and I don't immediately see why it's necessary). Can you share your config please?

**Comment by Coderangshu** [comment]
Thanks for replying @elParaguayo, there is no spacer inside the WidgetBox, it is between the WidgetBox and the other widget. Here's my widget config file
[widgetlist.txt](https://github.com/qtile/qtile/files/10392289/widgetlist.txt)

**Comment by elParaguayo** [comment]
I've only seen this happen once before and that's when someone had too many widgets for their bar! It wasn't specific to WidgetBox.

Could you run `qtile cmd-obj -o bar top -f info` when the box is closed and again when it's open (and giving you the issue that you've reported here) and paste the output here.

**Comment by Coderangshu** [comment]
yes, this is happening because of overflowing widgets, but the issue is the widgets which are visible should accept mouse_callbacks not the widgets that are hidden because of being overlapped
[close.txt](https://github.com/qtile/qtile/files/10392520/close.txt)
[open.txt](https://github.com/qtile/qtile/files/10392523/open.txt)

**Comment by elParaguayo** [comment]
We don't have stacking logic for widgets as we don't envisage overlapping widgets.

Currently, the bar passes the click to the first widget it finds in that position. This would be below anything in the widgetbox as those are drawn after the widgets they overlap.

A simple fix would be to reverse the order in which widgets are searched to find the one that was clicked.

My issue with this is that we don't really expect widgets to overlap so there will be rendering issues in any case so it's not as if it's a scenario that we officially support.

**Comment by Coderangshu** [comment]
Thanks a lot for the insight, where can I find the code to change this click search logic?

**Comment by elParaguayo** [comment]
https://github.com/qtile/qtile/blob/1102157ae23c8b168d0b63abf53274de05cb91b1/libqtile/bar.py#L468-L472

You could try changing line 470 to
``` python
for i in self.widgets[::-1]:
```
as that would reverse the list.
