### ISSUE TITLE
TreeTab does not respect "shuffle left/right"

### ISSUE THREAD

**Issue by singpolyma** [qtile/qtile#4112]
### The issue:

```
$ qtile --version
0.22.1
```

> Initially the panel looks like flat lists inside its section, and looks like trees if some of the windows are "moved" left or right.

But when I push my shuffle left/right keys, nothing happens.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I'm not sure `TreeTab` has implemented its own logic for the shuffle commands. The ones that it's inherited won't do anything as they manipulate a master client list but, from what I can tell, `TreeTab` doesn't use that list.
