### ISSUE TITLE
PulseVolume showing import error

### ISSUE THREAD

**Issue by biscuitrescue** [qtile/qtile#4120]
### The issue:

i use PulseVolume on my bar instead of Volume as it doesnt report the correct volume since i switched to pipewire. On this update (qtile 0.22.2.dev115+g653c52c2), PulseVolume started showing an import error. 
![image](https://user-images.githubusercontent.com/67876678/213006035-12427a2c-2157-4d22-aa31-c10c048bb373.png)

i do have widget imported from libqtile and pulsevolume is configured as so:
![image](https://user-images.githubusercontent.com/67876678/213006475-5ed2e00a-fb36-440f-ba23-bc67deb95e72.png)

Thank you and im sorry if this is just me missing a dependency or a library

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
How did you install qtile? That widget has an import that needs to be built at installation time.

However, can you check your log file to see what the import error actually is?

**Comment by biscuitrescue** [comment]
i installed from source. cloned from the github repository and install with pip. 
This is the relevant information from the log file
2023-01-18 02:30:55,996 WARNING libqtile __init__.py:import_class():L101 Unmet dependencies for 'libqtile.widget.pulse_volume.PulseVolume': /home/cafo/.local/lib/python3.10/site-packages/libqtile/widget/_pulse_audio.abi3.so: file too short

**Comment by elParaguayo** [comment]
Interesting. I've not seen that one before!

@m-col have you seen something like this before with ffi?

**Comment by biscuitrescue** [comment]
New development; i tried to see why the file was there in the first place since it isnt on github. File was empty. I deleted and got this error instead. Might be a messed up variable somewhere?

2023-01-18 10:37:33,715 WARNING libqtile __init__.py:import_class():L101 Unmet dependencies for 'libqtile.widget.pulse_volume.PulseVolume': No module named 'libqtile.widget._pulse_audio'

**Comment by biscuitrescue** [comment]
i reinstalled with the AUR version and it works? i tried reinstalling after wiping everything related clean from source but it always resulted in the same error. The AUR version is the same

**Comment by biscuitrescue** [comment]
After an upgrade, even the aur version throws an import error. i tried compiling from source again but same issue?

**Comment by elParaguayo** [comment]
Do you get any warning when qtile is built? There should be a line saying "Building PulseAudio interface". What does it say after that?

**Comment by biscuitrescue** [comment]
It didnt get a line saying that when i built it. 
![image](https://user-images.githubusercontent.com/67876678/215031872-032bcaf5-6daf-4944-93f3-b9b04e8bb777.png)
This is the output when i compile.

**Comment by biscuitrescue** [comment]
I dont get any such comment. All i get is this output when qtile is built.
![image](https://user-images.githubusercontent.com/67876678/215032083-4f78d453-c48c-4786-b384-ee7ef0569499.png)

**Comment by m-col** [comment]
As you're pip-installing from source, if you run the script at `./scripts/ffibuild` that should generate the necessary module. Then if you run from source, it should work.

If you run `pip --verbose install .`, you should also see this line somewhere in the log output:
```
  adding 'libqtile/widget/_pulse_audio.abi3.so'                                                                                                                                                
```
Is that the case?

**Comment by elParaguayo** [comment]
@biscuitrescue any update here? Can we close this?

**Comment by Nanush7** [comment]
Just in case anyone is having the same problem, I fixed this by installing the package pulsectl-asyncio from PyPI.

**Comment by elParaguayo** [comment]
It's not quite the same error as this issue was reported before we updated the widget to use pulsectl-asyncio. However, the symptoms around be the same!
