### ISSUE TITLE
error importing expose_command from libqtile.command.base

### ISSUE THREAD

**Issue by Javi3y** [qtile/qtile#4121]
### The issue:

i wanted to create this mpris2 widget
https://docs.qtile.org/en/latest/_modules/libqtile/widget/mpris2widget.html
but i got this error:
ImportError: cannot import name 'expose_command' from 'libqtile.command.base' (/usr/lib/python3.10/site-packages/libqtile/command/base.py)
how can i fix this or is there an easier and better way
v=0.22.1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Expose_command is only in master. The docs link is for the latest git version. For the stable 22.1 version, see https://docs.qtile.org/en/stable/_modules/libqtile/widget/mpris2widget.html

**Comment by elParaguayo** [comment]
Are you using qtile-extras as well? If so, as you're using qtile 0.22.1, you need to use the tagged version of qtile-extras too.

Alternatively, you can use the latest git versions of both.

**Comment by elParaguayo** [comment]
@Javi3y is this solved now?
