### ISSUE TITLE
Mpris2 Widget not showing metadata

### ISSUE THREAD

**Issue by gibranlp** [qtile/qtile#4124]
### The issue:

So the Mpris widget still says "there is no metadata for current track", i have checked with playerctl and the data is there:

```
playerctl metadata
cmus  mpris:trackid             '/278'
cmus  mpris:length              182000000
cmus  xesam:artist              David Guetta
cmus  xesam:title               Gettin' Over (feat. Chris Willis)
cmus  xesam:album               One More Love
cmus  xesam:albumArtist         David Guetta
cmus  xesam:genre               big room
cmus  xesam:comment             https://www.youtube.com/watch?v=wweYnY1MGZs
cmus  xesam:trackNumber         2
cmus  xesam:discNumber          1
```

In the logs i get an error everytime new metadata is loaded such as (song change, pause, etc) i have tried cmus, ncspot, spotify, vlc, its all the same.

```
2023-01-21 09:16:33,780 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 262, in process_message
    self.parse_message(*message.body)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 340, in parse_message
    self.track_info = self.get_track_info(metadata.value)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 370, in get_track_info
    return self._formatter.format(self.format, **self.metadata).replace("\n", "")
  File "/usr/lib/python3.10/string.py", line 161, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib/python3.10/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.10/string.py", line 175, in _vformat
    self.parse(format_string):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/mpris2widget.py", line 87, in parse
    format_string = MPRIS_REGEX.sub(r"{\2_\3\4}", format_string)
TypeError: expected string or bytes-like object
```

My version of qtile is 0.22.2.dev115+g653c52c2

Thanks.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for posting. I'll take a look when I can.

It's weird as it works well for me.

**Comment by elParaguayo** [comment]
Can you share your config for this widget please.

**Comment by gibranlp** [comment]
Sure this is it

`## Cmus
            widget.Mpris2(
              decorations=[RectDecoration(colour=color[6], radius=[0,7,7,0], filled=True)],
              mouse_callbacks={'Button1': lambda: qtile.spawn(terminal  + " -e cava")},
              objname='org.mpris.MediaPlayer2.cmus',
              foreground=color[0],
              width=250,
              format=['xesam:artist', 'xesam:title'],
              paused_text='Paused',
              stopped_text='',
              name='cmus',
              scroll=True,
              scroll_repeat=True,
            ),`

**Comment by elParaguayo** [comment]
`format` needs to be a string, not a list. See the docs here: https://docs.qtile.org/en/latest/manual/ref/widgets.html#mpris2
