### ISSUE TITLE
keybindings in Persian keyboard layout

### ISSUE THREAD

**Issue by smjt2000** [qtile/qtile#4129]
### The issue:

Hi
I'm not good in English
I want to make some keybindings like switching groups by using Persian keyboard layout

I tried this but this for switching groups:
```
for i in "123456789":
    if i == '2' or i == '۲':                                                                                                                                                                               
        groups.append(Group(i, layout='bsp'))

```

and this for opening applications:
```
 Key([mod], "b", lazy.spawn(browser)),
 Key([mod], "ذ", lazy.spawn(browser)), #  'ذ' is where 'B' located on keyboard
```

the first one don't work, and if I set second one for apps, Qtile crash and log me out. if I try to login to Qtile, logout again and again.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by mu-us61** [comment]
in this kind of situation those snippets not clear , you should bettter use default config , and use only the specific area in your case "keys and group" section and  post those parts maybe full config , which would be more helpful , 

maybe try this approach:
```
keys.extend(
    [
        # mod1 + letter of group = switch to group
        Key(
            [mod],
            "2",
            lazy.group["2"].toscreen(),
            desc="Switch to group {}".format(i.name),
        ),

        Key(
            [mod],
            "۲",
            lazy.group["2"].toscreen(),
            desc="Switch to group {}".format(i.name),
        ),
    ]
)
```
so you can access the group 2 with different keys

**Comment by smjt2000** [comment]
@mu-us61 It's not even restart the Qtile to apply changes!!

**Comment by smjt2000** [comment]
I found the solution
I used `xbindkeys -mk` to find keys code and do this in my config.
```
farsi_keys = [Key([mod], f"Farsi_{num}", lazy.group[num].toscreen()) for num in "123456789"]
keys.extend(farsi_keys) 
```
it's working nwo.

**Comment by elParaguayo** [comment]
Nice. Thanks for sharing.

Closing this but feel free to reopen if you still have problems.
