### ISSUE TITLE
non-persistent groups persist after last window has been shifted out

### ISSUE THREAD

**Issue by PhoenixClank** [qtile/qtile#4138]
### The issue:

qtile version: 0.22.1

1. have a non-persistent group with a single window
2. move that window to some other group (with `świtch_to_group=True`)
3. the now-empty group does not get removed

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you share your config please.

**Comment by PhoenixClank** [comment]
As you can imagine, it's the same one as in #4139. Should I paste it in again?

**Comment by elParaguayo** [comment]
No. You can ignore me. Not paying enough attention to the names of people posting issues!

**Comment by elParaguayo** [comment]
Sorry for the delay here. I didn't see anything in your config about making a group non-persistent. I can see new groups could be added but there's nothing to tag them as non-persistent so I'm not surprised that they're not removed.

**Comment by PhoenixClank** [comment]
I had assumed groups created that way were non-persistent by default, because when the last window is closed, they _do_ get removed.

**Comment by elParaguayo** [comment]
From what I can tell, `add_group` makes a normal group. The `persist` flag is a property of `dgroups`.

I'll need to look into this properly later.

**Comment by elParaguayo** [comment]
> I had assumed groups created that way were non-persistent by default, because when the last window is closed, they _do_ get removed.

I'm not seeing this behaviour.
