### ISSUE TITLE
qtile-wayland - Unable to create an allocator

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#4146]
### The issue:

qtile -v                                                                                        ─╯
0.22.2.dev127+gffbf518e

Qtile-wayland no longer depends on wlroots? because if i install pywlroots, qtile start -b wayland gives me this error and it doesn't work

```amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
00:00:00.021 [render/allocator/gbm.c:198] gbm_create_device failed
00:00:00.021 [render/allocator/allocator.c:134] Failed to create allocator
Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/core.py", line 125, in __init__
    ) = wlroots_helper.build_compositor(self.display)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wlroots/helper.py", line 30, in build_compositor
    allocator = Allocator.autocreate(backend, renderer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wlroots/allocator.py", line 25, in autocreate
    raise RuntimeError("Unable to create an allocator.")
RuntimeError: Unable to create an allocator.
```

and if i uninstall pywlroots, qtile-wayland works without problems

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by clotodex** [comment]
Are you using the right version of wlroots and pywlroots? There is only 0.15.1 supported right now

**Comment by cr1ogen** [comment]
> 

```pip show pywlroots
Name: pywlroots
Version: 0.15.24
Summary: Python binding to the wlroots library using cffi
Home-page: https://github.com/flacjacket/pywlroots
Author: Sean Vig
Author-email: sean.v.775@gmail.com
License: MIT
Location: /home/cr1ogen/.local/lib/python3.11/site-packages
Requires: cffi, pywayland, xkbcommon
Required-by:```

**Comment by cr1ogen** [comment]
```nala show libwlroots10
Paquete: libwlroots10
Versión: 0.15.1-4
Arquitectura: amd64
Instalado: sí
Prioridad: optional
Esencial: no
Sección: libs
Fuente: wlroots
Origen: Debian
Responsable: Sway and related packages team <team+swaywm@tracker.debian.org>
Tamaño instalado: 846 KB```

**Comment by m-col** [comment]
Your versions look fine, I don't think that is the issue. The first few lines of your logs potentially could be a clue:
```
MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
00:00:00.021 [render/allocator/gbm.c:198] gbm_create_device failed
```
Do you have all the drivers you need for your machine? Did wayland previously work, and you maybe removed some packages? Do other wlroots compositors work (ideally tested with wlroots 0.15 versions)?

**Comment by cr1ogen** [comment]
> Your versions look fine, I don't think that is the issue. The first few lines of your logs potentially could be a clue:
> 
> ```
> MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
> failed to load driver: radeonsi
> MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
> failed to load driver: kms_swrast
> MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
> failed to load swrast driver
> 00:00:00.021 [render/allocator/gbm.c:198] gbm_create_device failed
> ```
> 
> Do you have all the drivers you need for your machine? Did wayland previously work, and you maybe removed some packages? Do other wlroots compositors work (ideally tested with wlroots 0.15 versions)?

I have all the drivers installed, Qtile wayland works if I don't install pywlroots, if I install pywlroots qtile wayland doesn't work. Sway with pywlroots installed works and both (qtile and sway) work without pywlroots, as if it only needed libwlroots (the debian packages)

**Comment by cr1ogen** [comment]
Now with pywlroots 0.16 installed (just released) it gives me a different error

``` qtile start -b wayland
Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/core.py", line 82, in <module>
    from libqtile.backend.wayland import inputs, layer, window, wlrq, xdgwindow, xwindow
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/xdgwindow.py", line 32, in <module>
    from wlroots.wlr_types.xdg_shell import XdgPopup, XdgSurface, XdgTopLevelSetFullscreenEvent
ImportError: cannot import name 'XdgTopLevelSetFullscreenEvent' from 'wlroots.wlr_types.xdg_shell' (/usr/local/lib/python3.11/dist-packages/wlroots/wlr_types/xdg_shell.py)```

**Comment by cr1ogen** [comment]
I think I found my mistake. In Debian I have the wlroots folder in /usr/lib/python3.11/dist-packages and when I install pywlroots it also installs a wlroots folder in /usr/local/lib/python3.11/dist-packages in addition to the folders pywlroots and the two folders seem to conflict and deleting the wlroots folder that pywlroots creates fixes the issue

**Comment by m-col** [comment]
Qtile requires pywlroots>=0.15.24,<0.16.0. It will fail on 0.16. Similarly it needs wlroots 0.15, not 0.16.

> I think I found my mistake. In Debian I have the wlroots folder in /usr/lib/python3.11/dist-packages and when I install pywlroots it also installs a wlroots folder in /usr/local/lib/python3.11/dist-packages in addition to the folders pywlroots and the two folders seem to conflict and deleting the wlroots folder that pywlroots creates fixes the issue

Just to clarify, pywlroots is not installing itself in that location. Either pip (or debian's version of pip) must be installing things into /usr/local/lib. You should only have 1 version of pywlroots installed on your system, and it should be in the above version range.

**Comment by cr1ogen** [comment]
> Qtile requires pywlroots>=0.15.24,<0.16.0. It will fail on 0.16. Similarly it needs wlroots 0.15, not 0.16.
> 
At this moment pip tells me that I have pywlroots 0.16.1 installed (I'm in qtile-wayland)

```pip show pywlroots
Name: pywlroots
Version: 0.16.1
Summary: Python binding to the wlroots library using cffi
Home-page: https://github.com/flacjacket/pywlroots
Author: Sean Vig
Author-email: sean.v.775@gmail.com
License: MIT
Location: /usr/local/lib/python3.11/dist-packages
Requires: cffi, pywayland, xkbcommon
Required-by:```

**Comment by cr1ogen** [comment]
> Just to clarify, pywlroots is not installing itself in that location. Either pip (or debian's version of pip) must be installing things into /usr/local/lib. You should only have 1 version of pywlroots installed on your system, and it should be in the above version range.

Yes, Debian uses the /usr/local directory for locally installed packages and /usr for distribution-installed packages. I install wlroots from the debian deb package and since debian does not have the pywlroot package I have to install it using pip. But pywlroots also installs wlroots for me so I have 2 wlroots folders, one in /usr/local and another in /usr giving me the error but deleting the wlroots folder from /usr/local works. I do not know if I understand.

**Comment by m-col** [comment]
> since debian does not have the pywlroot package I have to install it using pip

>pywlroots also installs wlroots for me so I have 2 wlroots folders

pywlroots definitely shouldn't be installing wlroots if you're installing it via pip. The pywlroots repo doesn't anything like that set up.

> I have 2 wlroots folders, one in /usr/local and another in /usr

So I don't think the one in /usr/local is coming from the pip installation - it must have been created by something else

> deleting the wlroots folder from /usr/local works.

I guess this is good though - if it's not there, and you uninstall then re-install pywlroots using pip (and do nothing else) you shouldn't see the wlroots installation in /usr/local re-appear.

Either way, does that mean you've got it working now?

**Comment by cr1ogen** [comment]
> 
> > deleting the wlroots folder from /usr/local works.
> 
> I guess this is good though - if it's not there, and you uninstall then re-install pywlroots using pip (and do nothing else) you shouldn't see the wlroots installation in /usr/local re-appear.
> 


Yes, when i reinstall pywlroots using pip the wlroots instalacion re- appear

I make a video 
https://www.youtube.com/watch?v=vm4_PLWQtdE

> Either way, does that mean you've got it working now?

Yes Qtile is working now

**Comment by m-col** [comment]
Ah, maybe I misunderstood. That "wlroots" folder that is being created is the pywlroots package. The folder is named "wlroots" because that's the package name in python (i.e. `import wlroots`) but it is pywlroots.

> Yes Qtile is working now

Awesome, should we close this?

**Comment by cr1ogen** [comment]
> Ah, maybe I misunderstood. That "wlroots" folder that is being created is the pywlroots package. The folder is named "wlroots" because that's the package name in python (i.e. import wlroots) but it is pywlroots.

Ok. I understand

>Awesome, should we close this?

Yes, I'm going to close now. Thank you.

**Comment by Freemason-12** [comment]
I have the same issue, except that removing wlroots folder does not help anymore: when I rename the folder qtile cannot start with an error:no module named wlroots.
Using git version of qtile on Debian Bookworm stable.
