### ISSUE TITLE
Alacritty terminal not updating contents unless triggered

### ISSUE THREAD

**Issue by ZmjbS** [qtile/qtile#4148]
### The issue:

Starting alacritty in qtile brings up a terminal window as expected but typing or executing commands seems to do nothing. It just seems unresponsive. Move the terminal to a new column, however, and it updates the window.

I have no idea whether this is an issue with qtile or alacritty but figured I'd check here first as I figured the qtile folk might quicker to confirm whether this is a problem with my setup or a true bug, and help narrow down its source.

Qtile version: 0.22.1

Qtile doesn't log any messages related to this issue.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Unfortunately, I suspect this is something to do with your setup. I use alacritty and don't have the issue that you're reporting.

Do you have anything else grabbing key presses? any keychords in your config?

**Comment by ZmjbS** [comment]
Well, good that it's not a wide-spread issue. I experienced this on a fresh Arch Linux machine with the default Qtile config and no keymapping or anything else.

The odd thing is that I've not experienced this with any other application in qtile. The simplest workaround is to just use good ol' xterm, but was curious to try alacritty and wouldn't mind getting this sorted out, especially if it's just a minor issue with my setup.

But being relatively new to qtile and with no exprience with alacritty I'm not even sure where to start looking. So I'm very grateful for any suggestions or ideas!

**Comment by jwijenbergh** [comment]
Are you using Wayland perhaps?

**Comment by ZmjbS** [comment]
Nope, just the standard xorg-server version 21.1.4 installed via arch's pacman. So far it's a very vanilla setup.

**Comment by thingsiplay** [comment]
I just have a feeling that this could be an issue with Nvidia drivers. Any chance that you use Nvidia card? If you can and want to test, does this happen with Kitty too? (Another GPU rendered terminal.) And if that won't happen with a non GPU powered terminal, then I highly suspect its graphic cards drivers. Just shooting in the dark, it may be very well related to something else.

**Comment by ZmjbS** [comment]
Thanks for the message and sorry for not getting back sooner.

No, I'm running an Intel graphics card but just tried Kitty and yes, it has a similar problem. Not quite the same, though. Kitty seems to try to update something, occasionally I've seen a command appear as I hit the enter key.

Also possibly connected, neither seems to store in buffer anything not on screen. Try to scroll up and the terminal will just flicker.

So, is this just a driver issue and unlikely to be solved, or something possible to trouble-shoot. I'm fine with xterm but was curious to try something hip and cool. Happy to do more tests if it may track down or lead to a resolution of the issue.

**Comment by elParaguayo** [comment]
@ZmjbS have you made any progress on this?

As I said, I don't think this is qtile related and I don't have the knowledge to help you debug this further (particularly if it's driver related).

**Comment by jwijenbergh** [comment]
Could be an x11 compositor?

**Comment by jwijenbergh** [comment]
I can't see how this is a Qtile bug, if it doesn't happen in other WMs please re-open

**Comment by ZmjbS** [comment]
> @ZmjbS have you made any progress on this?

No, unfortunately not. 

> As I said, I don't think this is qtile related and I don't have the knowledge to help you debug this further (particularly if it's driver related).

Thanks. I wasn't sure that it was either, but figured it was a more sensible place to start as I figured there were more qtile users who would be familiar with alacritty or able to set it up to test, than alacritty users who are familiar with qtile or able to set it up to test.

Oh, well. Thanks for the help, everyone!

**Comment by grimcxde** [comment]
@ZmjbS If it still relevant, you can try this. I had the same problem on my hybrid (intel & nvidia, but i use only iGPU) laptop with manually configurated Arch. I fixed it by removing xf86-video-intel, xf86-video-nouveau packages, because i had other installed drivers, such mesa and nvidia-open. Of course, I don't know for sure if you have these packages, but at one time I made the mistake of looking superficially at the Arch wiki.
