### ISSUE TITLE
Max layout: don't just display the active window

### ISSUE THREAD

**Issue by terminalmage** [qtile/qtile#415]
In the Max layout, when using an application that is not floating, but has alpha transparency, the wallpaper/background is shown instead of the application under it in the stack. This appears to be so because only the active window is displayed in the Max layout, and thus there is no application under it to _be_ displayed.

I often use a transparent terminal, and like being able to see through to the application "underneath", for instance a web browser. It would be nice to be able to do this with qtile.

**Comment by ramnes** [comment]
Fixed by 3ce1a785ee81b8f8b4486391f9a92e19a2de70d2
