### ISSUE TITLE
qtile gives wrong error message when wayland backend cannot start.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4152]
### The issue:

When I start qtile with wayland backend without Xwayland installed, it doesn't start because the backend isn't initialized properly. This is probably som bug in pywlroots (as @m-col suggested on Discord), but it's not even relevant for this bug report.

The problem is: qtile gives very strange and misleading error message when it happens:

```
~ ❯ /usr/bin/qtile --version
0.22.2.dev127+gffbf518e
~ ❯ /usr/bin/qtile start -b wayland
usage: qtile [-h] [-v] {start,shell,top,run-cmd,cmd-obj,check,migrate,help} ...

Did you mean:
/usr/lib/python-exec/python3.11/qtile start -b wayland start
```

It should detect, that the backend has failed and inform user about that, instead of this very generic error message.

Relevant links to the code (also thanks to @m-col for them):
- https://github.com/qtile/qtile/blob/master/libqtile/scripts/main.py#L66
- https://github.com/qtile/qtile/blob/master/libqtile/scripts/main.py#L63-L72

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by cr1ogen** [comment]
Stupid question but, you tried to  run qtile with qtile start -b wayland without /usr/bin?

**Comment by ftpd** [comment]
`/usr/bin` in this test was on purpose. My 'normal' qtile is X11 version inside a venv, this was a 'fresh' system-wide installation just for performing this test, so I had to use full path to be 100% sure I'm trying the one with wayland.
