### ISSUE TITLE
Qtile fails to update under NixOS

### ISSUE THREAD

**Issue by Thlr** [qtile/qtile#4157]
### The issue:

Hi,

Lately (I believe it's been a week), I haven't been able to update my system because of a build error (supposedly) from Qtile. Here are the logs I'm getting :

```
error: builder for '/nix/store/b5vg4gcqqszwrmh694sms6zmka692rrs-python3.10-xcffib-1.1.2.drv' failed with exit code 1;
       last 10 log lines:
       > _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
       > _XSERVTransMakeAllCOTSServerListeners: server already running
       > (EE)
       > Fatal server error:
       > (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
       > =========================== short test summary info ============================
       > FAILED test/test_python_code.py::TestXcffibTestGenerator::test_XcffibTest_generator - AssertionError: couldn't connect to xvfb
       > ERROR test/test_connection.py::TestConnection::test_wrap - AssertionError: couldn't connect to xvfb
       > ==================== 1 failed, 36 passed, 1 error in 48.29s ====================
       > /nix/store/3yfs41f4b60jya2gk6xikx4s97zsxjr0-stdenv-linux/setup: line 1573: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/b5vg4gcqqszwrmh694sms6zmka692rrs-python3.10-xcffib-1.1.2.drv'.
error: 1 dependencies of derivation '/nix/store/9689gb58p74cvhrrv282lkpsmc7lx76k-python3.10-qtile-0.22.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3wvnj4mi57n9xwrzpvzdzraccay43hk3-qtile-0.22.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/61qa4k72v8jr9090cv8g10w922a08ihk-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sh8ylcsv16m5ipn1m4p1vb1c84hn8vj0-xsession.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1bm31kk070wlhwy3c6prl21dypnsfgs5-nixos-system-lancey-tlarue-23.05.20230211.e5530ab.drv' failed to build
```

NixOS version : `22.11`

It looks like Qtile is running some tests that it shouldn't be doing on a live system : "Make sure an X server isn't already running(EE)"

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Well, I don't know anything about NixOS but I can tell you that those two tests are actually from `xcffib`, which is a dependency of qtile, and not from qtile itself.

However, it is correct for those tests to create a new X server connection (which would be different to your own session) but I'm not sure why those tests would fail.

I would suggest posting this over at https://github.com/tych0/xcffib and see they can help.

**Comment by Thlr** [comment]
Thanks for the quick response, I will try over there. It seems a bit odd to me still because that repository was last updated three months ago...

I was actually hesitant on posting this here but I had guessed it could be due to some test you are running yourselves.

**Comment by joaojacome** [comment]
I was having the same issue here, but I found out the build works if I disable the qtile overlay, upgrade the system, then enable it again and rebuild.
