### ISSUE TITLE
Qtile pip install . error

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#4160]
### The issue:

qtile --version
0.22.2.dev127+gffbf518e

I updated the Qtile git repository and when I want to install the new version it gives me this error

``` 
pip install .
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

This problem did not give me in previous installations of qtile

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I don't believe this is anything to do with qtile specifically. We've not made any changes that would result in this.

I suspect this is a change in python (see [PEP668](https://peps.python.org/pep-0668/)) which is designed to reduce the risk of breaking your system by overwriting system installed packages.

**Comment by AndrejGorodnij** [comment]
Can I ask, what you trying to do with `pip install .` ?

Technically, this error says you need create virtual environment before using `pip` on system level.

If you had installed Qtile using pip, then you need to update it with pip - `pip install --upgrade qtile`.

I thing you had mix few package installation technics, this error looks like system error, not Qtile.

**Comment by cr1ogen** [comment]
> 

Hi Yes. I use ` pip install .`  because I install the development version of Qtile every time the git repository is updated.
And the `pip install --upgrade qtile` command is used when you want to update the version of the pypi repositories.

http://docs.qtile.org/en/stable/manual/install/index.html#id1

And yes, and I don't know whether to call it an error, it's a python change (see PEP668) as elParaguayo mentions above.

But I'm going to wait since this change won't even let me install the necessary dependencies like pywlroots or pywayland even using pip from pypi. For everything it asks me to create a virtual environment, or in another way learn to create it
Thank you

**Comment by m-col** [comment]
Maybe pip wants the `--user` flag?

**Comment by cr1ogen** [comment]
> Maybe pip wants the `--user` flag?

I used another more extreme method to be able to update Qtile, but if it's a change made to pip which gives me the problem, so I'm going to close the issue. In case you want to take a look, here is the thread  in pip. Thank you.

https://github.com/pypa/pip/issues/11776
