### ISSUE TITLE
Xwayland windows aren't drawn properly when unhidden.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4169]
### The issue:

When I 'close' Xwayland window that's able to stay in the background (discord, in my case) with a key bound to `lazy.window.kill()` and 'restore' it later (by running it from Prompt widget, dmenu, terminal or whatever), the window is not drawn properly. Possible outcomes are:
- window is not visible;
- window is visible on a partof the screen;
- window is visible on every group under other windows.

Each time I can 'fix' this with triggering `lazy.reload_config()` - the window is back where it should be (I have a Match rule for it) and works fine.

~ ❯ qtile --version
0.22.2.dev151+ga6514a0f

Tested with Discord from flatpak (version 0.0.25) and Gentoo's Portage (also version 0.0.25).

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Can confirm with non-flatpak discord (arch repos)

**Comment by jwijenbergh** [comment]
Can you try #3985?

**Comment by jwijenbergh** [comment]
discussed on discord that this can be closed
