### ISSUE TITLE
Firefox window is not redrawn after returning from floating layout

### ISSUE THREAD

**Issue by terminalmage** [qtile/qtile#417]
When Firefox is toggled to floating layout and back, the window stops being redrawn. You can click the browser tabs and the window title in the tasklist widget does update, but the window does not. Moving the window to a different group "fixes" this.

This does not appear to be related to #416 as the issue existed before it was merged.

I'm not sure if this is exclusive to Firefox, but it's the only application where I've seen this issue.

``` bash
[develop] erik@saltmine:~/abs/qtile-git/qtile%  git describe
v0.1-1413-g1b46a8b
```

**Comment by ramnes** [comment]
@Etn40ff do you also use intel drivers?

**Comment by pawamoy** [comment]
@ramnes shouldn't this issue be marked as stale by the bot?

**Comment by jwijenbergh** [comment]
Can anyone still reproduce this? I can't seem to reproduce it. I'm not using xcompmgr though, it might be an issue with that.

**Comment by jwijenbergh** [comment]
a 9 year old issue that I can't reproduce. If someone can reproduce this, please re-open
