### ISSUE TITLE
Configuration file on startpage of qtile.org isn't escaped properly?

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4173]
### The issue:

![image](https://user-images.githubusercontent.com/84532402/221188106-243492d8-b8fb-4c9c-a9c3-b8d4ff85d525.png)

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Yeah - we need to redo the website...

**Comment by ervinpopescu** [comment]
> Yeah - we need to redo the website...

What does `redo` mean exactly? :)

**Comment by elParaguayo** [comment]
We were going to move it from its current host to github pages. Some work's been done on this already but it's low priority!

**Comment by ervinpopescu** [comment]
> We were going to move it from its current host to github pages. Some work's been done on this already but it's low priority!

Oh, I believe I've seen that in m-col's wlroots 0.16.0 PR. Thanks for the clarification!
