### ISSUE TITLE
Qtile does not use all screens when using Nvidia

### ISSUE THREAD

**Issue by ebiscaia** [qtile/qtile#4175]
### The issue:

Hi guys,

I have a hybrid card Intel/Nvidia in which I set to run in nvidia mode with envycontrol. The issue I have is:

   - I have an autostart file and there I start kitty and qutebrowser.
   - Kitty is set to open in one group and qutebrowser in another group
   - When I login both programs start and their groups but on the same screen.
 
This problem only happens in nvidia mode. I moved back to hybrid mode and qtile started to work as it should again (started the programs in different screens).

Is there a way to solve it? Lemme know if I need to provide any files to help you guys,

Thanks

>qtile --version
>0.22.2.dev132+ge86cde0c

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Is this in Wayland or X11?

If X11, could you test using another WM like i3/bspwm etc and check whether it persists?

Does xrandr/arandr detect the monitor or is it completely absent from anything?

**Comment by ebiscaia** [comment]
Hi,

Thanks for the help. I am on X11. The thing, I the other screen is detected as can go to it and move a group to there. The difference is in hybrid mode all the screens are populated automatically during the startup.
