### ISSUE TITLE
Wrong window position and shifted mouse input when leaving fullscreen

### ISSUE THREAD

**Issue by fdev31** [qtile/qtile#4176]
### The issue:

- Xorg / Archlinux / Nvidia
- Qtile 0.22.2.dev121+g4f6ff94d
- No relevant log

### Pre-conditions

- Youtube opened in Google chrome or Brave
- Happens at least with bsp, colums & max layouts
- Bottom bar on screen
- ```auto_fullscreen = False```

### Scenario

- maximize video from youtube's icon
- maximize the window (mod+f)
- un-maximize video from youtube's icon

*Expected result:* the window is displayed according to layout and mouse pointer works as expected, something like this:
![image](https://user-images.githubusercontent.com/238622/221352575-3278a892-cea2-4048-9ec7-f352bc3bb02a.png)

*Current result:* the window is displayed shifted (a margin appears at the top) and the mouse pointer actions seem to be shifted by the same number of pixels (actions don't match visual representation):

![image](https://user-images.githubusercontent.com/238622/221352667-a33b2345-1954-4972-92b7-047859122ee5.png)

Note: some actions (eg: moving cursor to another screen in multi-screen setup) will fix it.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
seems like a chromium bug, but let's not assume that. I will see if I can implement a workaround

**Comment by jwijenbergh** [comment]
@fdev31 great bug report. Does #4181 fix it?

**Comment by fdev31** [comment]
Yes it does !
