### ISSUE TITLE
widget.CheckUpdates not working correctly on Arch

### ISSUE THREAD

**Issue by bknightInfo** [qtile/qtile#4185]
### The issue:

Hi

for some reason widget CheckUpdates will never automatically update without manual intervention.
I have included my widget but everything seems correct according to the wiki/ 

Widget:
```python
              widget.CheckUpdates(
                       update_interval = 800,
                       distro = "Arch_checkupdates",
                       display_format = " {updates} Updates  ",
                       background = colors["magenta"],
                       foreground = colors["bg"],
                       mouse_callbacks = {'Button1': lambda: qtile.cmd_spawn(alacritty + ' -e sudo pacman -Syu')},
                       ),
```

to get it to work I run the following commands
1) sudo pacman -Syu
2) qtile cmd-obj -o widget checkupdates -f eval -a "self.update(self.poll())"'

Kernal: 6.2.2-arch
qtile version: 0.22.1
cpu: AMD 3700x
GPU:  AMD Radeon RX 6700 XT

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What do you mean by "automatically update"? The widget doesn't install updates, it just shows how many are available for updating.

If you're taking about it not update after running pacman, that's because you're not need to put the command in the `execute` parameter, not in `mouse_callbacks`. See http://docs.qtile.org/en/stable/manual/ref/widgets.html#checkupdates

**Comment by bknightInfo** [comment]
Sorry i didn't mean like that.
What i meant is say you have 9 updates available the widget won't list any updates until i manually run those commands.

I did this test
1) sudo pacman -Syu (9 updates available)
2) did a reboot   
3) Had my machine running all day and the widget didn't update

**Comment by elParaguayo** [comment]
Well, there would be no updates after step 1 so your widget shouldn't show anything at that point. However, if step 1 showed there were 9 updates then the widget should have showed something before that step.

One problem with this widget is it interprets any non-zero return code as meaning there are no updates.

Can you run `checkupdates` in a terminal and let's see what error you're getting.

**Comment by bknightInfo** [comment]
Sorry about the delay

currently the widget is reporting 22

if i run checkupdates | wc it gives me 28

**Comment by bknightInfo** [comment]
update_interval = 800

**Comment by elParaguayo** [comment]
Are you still having this issue?
