### ISSUE TITLE
Unable to run Qtile with Wayland on Ubuntu 22.10 - missing XdgTopLevelSetFullscreenEvent from wlroots

### ISSUE THREAD

**Issue by AniAggarwal** [qtile/qtile#4190]
### The issue:

Qtile version:
Tried with `0.22.2.dev165+g4c69fca3`, and everything between `0.18.0` and `0.22.1`.

Logs aren't relevant as qtile doesn't start and therefore doesn't populate them.

I am not using any config at the moment.

Version of dependencies:
```
cffi                     1.15.1
cairocffi                1.4.0
dbus-next                0.2.3
dbus-python              1.2.18
pywlroots                0.16.1
pywayland                0.4.15
xkbcommon                0.8
xcffib                   1.2.0
libwlroots-dev/kinetic 0.15.1-3build1 amd64
```

The error:
```
❯ qtile start -b wayland
zsh: correct 'wayland' to 'xwayland' [nyae]? n
Traceback (most recent call last):
  File "/home/ani/.local/bin/qtile", line 8, in <module>
    sys.exit(main())
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 79, in <module>
    from libqtile.backend.wayland import inputs, layer, window, wlrq, xdgwindow, xwindow
  File "/home/ani/.local/lib/python3.10/site-packages/libqtile/backend/wayland/xdgwindow.py", line 31, in <module>
    from wlroots.wlr_types.xdg_shell import XdgPopup, XdgSurface, XdgTopLevelSetFullscreenEvent
ImportError: cannot import name 'XdgTopLevelSetFullscreenEvent' from 'wlroots.wlr_types.xdg_shell' (/home/ani/.local/lib/python3.10/site-packages/wlroots/wlr_types/xdg_shell.py)
```

## What I've tried:
Worth noting I have conda installed. I have installed all relevant dependencies on my system python.
I have been able to make qtile work with X11, but not with wayland. I have tried rolling back various versions of qtile, I've tried installing all qtile dependencies as apt packages where applicable, tried purely installing all dependencies as python packages into a conda env, etc. 
I have tried using qtile git as well as pip's packaged qtile.
I stopped short of building wlroots from source as I am not experienced in that area.

## The issue (I think)
I believe the error comes from the fact that I have wlroots 0.15.1 which is missing the XDGTopLevelSetFullscreenEvent, which is present on my friend's arch installation of wlroots version 0.16.2-1. 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Qtile currently only supports wlroots/pywlroots 0.15, so you need to downgrade pywlroots to the latest 0.15.x release (I think 0.15.24). That binds the latest 0.15.x release which is therefore also needed. We haven't yet updated to 0.16 on master.

**Comment by AniAggarwal** [comment]
Okay thanks.
Downgrading pywlroots fixed that issue for me. Perhaps this should be noted in the installation wiki? I can make a PR later if you think that's helpful.

Anyhow, I now run into a new issue:
When running `qtile start -b wayland`:

```
libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

00:00:00.023 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

00:00:00.025 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
00:00:00.025 [ERROR] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
00:00:00.025 [ERROR] [render/egl.c:242] Failed to initialize EGL
00:00:00.025 [ERROR] [render/egl.c:521] Failed to initialize EGL context
00:00:00.025 [ERROR] [render/gles2/renderer.c:698] Could not initialize EGL
libinput error: Failed to load the device quirks from /usr/share/libinput and /etc/libinput/local-overrides.quirks. This will negatively affect device behavior. See https://wayland.freedesktop.org/libinput/doc/1.16.3/device-quirks.html for details.
/tmp/tmped_qt9ig: line 3: 463775 Segmentation fault      (core dumped) qtile start -b wayland
```

Let me know if I should make a seperate issue for this.

**Comment by m-col** [comment]
>  Downgrading pywlroots fixed that issue for me. Perhaps this should be noted in the installation wiki? I can make a PR later if you think that's helpful.

Great! Thanks, it is, but I've got it covered: https://github.com/qtile/qtile/pull/4193

> Let me know if I should make a seperate issue for this.

We've seen this before but unfortunately it's a bit of a head-scratcher that we haven't yet resolved: https://github.com/qtile/qtile/issues/3756 & https://github.com/qtile/qtile/issues/4020 for more info.

**Comment by AniAggarwal** [comment]
Hmm, yeah this looks confusing. The other issues are similar but looks like I'm having a slightly different issue.

Just to add some more info about my system.

I'm on a Nvidia GPU, running the latest proprietary Nvidia drivers. My laptop has an Intel iGPU and I have tried running the same command after running `prime-select intel/nvidia/on-demand` etc. Same issue.

I've tried using the patch/install script in #3756  but wasn't able to get it to work. 
Let me know if you need any more info or if I can try something else. 


Additionally, is there a good way of testing by running `qtile start -b wayland` when I have gnome already open? Even if I open a TTY, I can't start qtile while Gnome is running which makes it hard to test various workarounds without logging out everytime.

**Comment by m-col** [comment]
> Additionally, is there a good way of testing by running qtile start -b wayland when I have gnome already open? Even if I open a TTY, I can't start qtile while Gnome is running which makes it hard to test various workarounds without logging out everytime.

In this repo there is a script at `./scripts/wephyr` which wraps qtile and some of us use to run a nested qtile session within our main session. That said just running `qtile start -b wayland` from inside gnome should open a nested session anyway.

**Comment by simonvanderveldt** [comment]
Sounds like this might be fixed by https://github.com/qtile/qtile/pull/3985? Which has now been merged, so guess we can try with the code as it currently lives in master?
