### ISSUE TITLE
X11: Bug fullscreen video initiated from Steam

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4200]
### The issue:

Below a video of the bug.
I have a set of rules to open any new window from the right screen to main screen.
When turning on fullscreen for a youtube video played in steam (right screen), the main screen start blinking with a black screen.

```python
@hook.subscribe.client_managed
async def _screen2(window):
    wm_class = window.window.get_wm_class()
    w_name = window.window.get_name()
    #logger.warning(wm_class)
    #logger.warning(w_name)
    if wm_class == ["steam_app_8500", "steam_app_8500"]:
        if w_name == "Wine System Tray":
            window.kill()
        elif w_name =="EVE Launcher":
            window.togroup("9")
            window.set_size_floating(901,946)
            window.center()
            window.bring_to_front()
        elif w_name == "EVE":
            window.togroup("3")
            qtile.groups_map["3"].toscreen(0)
    elif w_name =="EXAPUNKS":
        window.toscreen(0)
        window.toggle_floating()
        #window.disable_fullscreen()
        #window.togroup("3")
        #qtile.groups_map["3"].toscreen(0)
    elif ((window.group.screen.index == 2) 
        and (wm_class != ['Mail', 'thunderbird']) 
        and (wm_class != ["Thunderbird", "thunderbird"])
        and (wm_class != ['deluge', 'Deluge-gtk'])
        and (wm_class != ['deluge', 'Deluge'])  
        and (wm_class != ['Steam', 'Steam'])
    ):
        window.toscreen(0)
        #window.togroup("3")
        #qtile.groups_map["3"].toscreen(0)
        #window.group.setlayout("max")
```
https://user-images.githubusercontent.com/27446196/225976458-04701835-2116-468d-b7a9-bfe5a32aed3f.mp4

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Are you suggesting that that hook is responsible? Does steam create a whole new window when fullscreening youtube videos out of its main window?

Could you confirm whether this is in X or Wayland? Have you checked the logs for potential clues as to what's going on?

**Comment by Crystal4276** [comment]
Hello,
Sorry for the delayed answer.
"Are you suggesting that that hook is responsible?"
Yes. Without the hook the video is displayed without bug.

"Does steam create a whole new window when fullscreening youtube videos out of its main window?"
Yes. Here's an xprop command on it:
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 8
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_NAME(UTF8_STRING) = "Steam HTML FullScreen"
WM_NAME(UTF-8) = "Steam HTML FullScreen"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 1887
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLASS(STRING) = "steam", "steam"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x593e141f
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 6140, 0
WM_CLIENT_MACHINE(STRING) = "terrier"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0

"Could you confirm whether this is in X or Wayland? "
X11

Have you checked the logs for potential clues as to what's going on?
Logs are empty.

**Comment by jwijenbergh** [comment]
How about the latest steam client?

**Comment by Crystal4276** [comment]
> How about the latest steam client?

Hello,
I'd love to test it, but i'm still waiting python-cairocffi to be bump to 1.6 on Arch.
I can't start qtile at the moment.
I'll report back when it happens.

**Comment by elParaguayo** [comment]
I wrote some PKGBUILD files to install the latest versions of xcffib and cairocffi. They're here:
https://gist.github.com/elParaguayo/d351d7bbea56198a9d27fb662b720545

**Comment by Crystal4276** [comment]
> How about the latest steam client?

Hello,
Reporting back after installing 0.23 and latest steam build.
Now the youtube video going full screen keep the wm_name= "Steam", and WM_CLASS(STRING) = "steamwebhelper", "steam".
Before it was WM_NAME(UTF-8) = "Steam HTML FullScreen"
Now i can't find a clever rule to send the video to a different screen.

So i will close this bug because i can't reproduce it.
