### ISSUE TITLE
X11: qtile crash with League of Legends, issue with  focus and fullscreen

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4201]
### The issue:

Triple monitor setup.
Launching the game from the LOL launcher located on main central screen. 
Two possibilities:
- the mouse pointer and focus stay on main screen -> game start in fullscreen without any issue
- The mouse pointer and focus is on another screen : qtile crashes.

File log is too long. Here's a paste bin:
https://pastebin.pl/view/39d4c5b1

Video capture stop because qtile crashes:

https://user-images.githubusercontent.com/27446196/225990160-48ecab81-ba9a-4f6e-83a6-84429f02867f.mp4

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Do you have anything in Xorg logs? Looks like your X server crashes.

**Comment by Crystal4276** [comment]
Reporting back on this since the upgrade to 0.23.
The Bug is gone.
Now league of legends is opening on the screen being under focus.
I think i can make a rule to stick it to on particular group on the main screen so i will this bug,
Thanks
