### ISSUE TITLE
GenPollText text not centered

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4212]
### The issue:

Any idea why this happens?
![image](https://user-images.githubusercontent.com/84532402/227733676-dea91d67-4849-4a4a-a7ad-b9fab3643986.png)

[custom widget call](https://github.com/ervinpopescu/dots/blob/main/.config/qtile/modules/widgets/my_battery.py)
[custom widget implementation](https://github.com/ervinpopescu/dots/blob/main/.config/qtile/extras/mybattery.py)

I've tried using `padding_y`  and `margin_y` but it doesn't seem to work. `CaskaydiaCove Nerd Font Mono Bold` does not seem to be the culprit either, as `CodeNewRoman Nerd Font Mono Bold` does not change anything:  
![image](https://user-images.githubusercontent.com/84532402/227733984-7bef8514-dfc8-4db4-9209-2f90fa37e694.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
You've probably got a new line character in your script output.

**Comment by ervinpopescu** [comment]
Oh :) That's mighty stupid of me, it's perfectly fine now, thanks!
