### ISSUE TITLE
neofetch slow w/multiple tabs in various terminal emulators. 

### ISSUE THREAD

**Issue by iamhumanipromise** [qtile/qtile#4213]
### The issue:

Using Intel Core i7-9750H w/32GB RAM. After opening the 5th or 6th tab with high CPU activity, neofetch slowly obtains the information before proceeding. 

Suggest a fix for this by using Fastfetch, which is pure C where able and is very lightweight compared to neofetch. This may be a great use case for this. 

https://github.com/LinusDierheimer/fastfetch 
```

archlinux ~ qtile --version
0.22.1
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
How is this an issue with qtile?

**Comment by elParaguayo** [comment]
> QTile autoconfigures bash to load neofetch with each new terminal instance along with customizations.

What? Qtile does no such thing.

**Comment by iamhumanipromise** [comment]
> > QTile autoconfigures bash to load neofetch with each new terminal instance along with customizations.
> 
> What? Qtile does no such thing.


After installing, here's what I have as my terminal output. Custom colors, customized neofetch instance with icons, and the little "I use Qtile WM" message on top. 

I believed this to be Qtile-related given the branding and message, and customization appearing after installing. 
(See Screenshot) 

![Screenshot from 2023-03-27 06-40-38](https://user-images.githubusercontent.com/105223045/228062320-565035c0-f3ff-46ed-9e3f-065d9c7a5430.png)

**Comment by elParaguayo** [comment]
No. That's nothing to do with qtile or, at least, not the default installation - I don't know if you're installing a fork.

I should close this as it's not a qtile issue but I'm curious: how did you install qtile?

**Comment by elParaguayo** [comment]
Also, are you sure your `.bashrc` file wasn't calling neofetch before you installed qtile?

**Comment by Malex** [comment]
@iamhumanipromise any chance you installed this (third party) package? https://aur.archlinux.org/packages/qwinos-qtile-dracula

This does add neofetch to bashrc (https://github.com/QWinOS/Qtile-Dracula/blob/main/.bashrc#L291) and has that message you've shown: https://github.com/QWinOS/Qtile-Dracula/blob/main/.config/neofetch/config.conf#L2

So your are looking for this Issues page: https://github.com/QWinOS/Qtile-Dracula/issues

**Comment by elParaguayo** [comment]
Closing this as I don't think it's related to qtile.

**Comment by iamhumanipromise** [comment]
> @iamhumanipromise any chance you installed this (third party) package? https://aur.archlinux.org/packages/qwinos-qtile-dracula
> 
> This does add neofetch to bashrc (https://github.com/QWinOS/Qtile-Dracula/blob/main/.bashrc#L291) and has that message you've shown: https://github.com/QWinOS/Qtile-Dracula/blob/main/.config/neofetch/config.conf#L2
> 
> If that's the case, your are looking for this Issues page: https://github.com/QWinOS/Qtile-Dracula/issues , not qtile's

This is closed, but yes, yes in fact it is! Jeez, I thought it was just Qtile but with a Dracula theme. Guess its a different project. Sorry about that! Regardless, I would still highly suggest fastfetch (pure C) instead of neofetch. :)
