### ISSUE TITLE
Discord (and some other programs) doesn't show in StatusNotifier widget.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4224]
### The issue:

I'm using Discord and Ferdium from flatpak. After the update, I lost the ability to see icons in the tray provided by `StatusNotifier`. I've tried both master's and qtile-extras' version of the widget.

    ~ ❯ qtile --version
    0.22.2.dev174+ge88537fb

Messages in the logs:

    2023-04-05 11:51:05,117 WARNING libqtile statusnotifier.py:start():L137 Unable to find StatusNotifierItem interface on :1.270
    2023-04-05 11:51:05,117 WARNING libqtile statusnotifier.py:start():L137 Unable to find StatusNotifierItem interface on org.kde.StatusNotifierItem-6-1

It works with previous versions (I can provide flatpak's commits, if necessary). Everything works fine on X with `Systray()` widget.

I've tested it with Waybar and it all works, in both old and new version. Other apps (Slack, Nextcloud client - also from flatpak) are working fine.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
This is a very odd issue. For some reason, the Discord service on dbus is not allowing introspection so our code cannot see what methods are available.

Trying to access the discord service gives me this:
```
╰─❯ busctl --user introspect org.kde.StatusNotifierItem-1863-1  /com/canonical/dbusmenu com.canonical.dbusmenu
NAME TYPE SIGNATURE RESULT/VALUE FLAGS
```
Compare that to the VLC service:
```
╰─❯ busctl --user introspect :1.469  /MenuBar com.canonical.dbusmenu
NAME                     TYPE      SIGNATURE       RESULT/VALUE FLAGS
.AboutToShow             method    i               b            -
.AboutToShowGroup        method    ai              aiai         -
.Event                   method    isvu            -            -
.EventGroup              method    a(isvu)         ai           -
.GetGroupProperties      method    aias            a(ia{sv})    -
.GetLayout               method    iias            u(ia{sv}av)  -
.GetProperty             method    is              v            -
.IconThemePath           property  as              -            emits-change
.Status                  property  s               "normal"     emits-change
.TextDirection           property  s               "ltr"        emits-change
.Version                 property  u               4            emits-change
.ItemActivationRequested signal    iu              -            -
.ItemsPropertiesUpdated  signal    a(ia{sv})a(ias) -            -
.LayoutUpdated           signal    ui              -            -
```

Waybar seems to take a slightly different approach and just requests all properties. That's not the approach our code takes and it wouldn't be a small change to adopt that route. 

This may take me a bit of time to solve...

**Comment by elParaguayo** [comment]
Looking through the Waybar code, they don't try to introspect objects. They assume there's a consistent approach to the object name and the type of object exposed. They also assume the type of object is consistent and use a pre-defined introspection definition.

We/I didn't take that approach because there are differences between implementations. Waybar acknowledges the differences but decides they don't matter (which is probably reasonable) and just removes conflicting methods from their definition.

It should be easy enough to add this approach as a fallback to our current approach.

qtile-extras will also likely need to be updated to ensure a similar approach can be taken for the item menu.
