### ISSUE TITLE
0.22.1: Test failures (test_statusnotifier*) when built/tested against Python 3.11

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#4229]
### The issue:

Hi! We're currently rebuilding all packages against Python 3.11 on Arch Linux.
It seems that the following tests no longer work on Python 3.11 (but worked using Python 3.10):

```
=========================== short test summary info ============================
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_defaults[1-x11]
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_defaults[1-wayland]
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_defaults_vertical_bar[1-x11]
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_defaults_vertical_bar[1-wayland]
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_icon_size[1-x11-sni_config0]
FAILED test/widgets/test_statusnotifier.py::test_statusnotifier_icon_size[1-wayland-sni_config0]
====== 6 failed, 1477 passed, 53 skipped, 4 xfailed in 816.16s (0:13:36) =======
```

[qtile-0.22.1-4-x86_64-build.log](https://github.com/qtile/qtile/files/11186365/qtile-0.22.1-4-x86_64-build.log)
[qtile-0.22.1-4-x86_64-check.log](https://github.com/qtile/qtile/files/11186366/qtile-0.22.1-4-x86_64-check.log)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Yeah. There's a bug in the current release of dbus_next with 3.11. It's fixed in their git master but they've not pushed a new release (I've been chasing for some time).

Assuming you don't want to patch dbus_next, you'll need to skip these tests. We've disabled them for 3.11 in our CI suite for that reason.

**Comment by dvzrv** [comment]
Ah, good to know! Hmm, guess we could also patch dbus_next... but never a good sign if upstream maintainer vanishes :cry:

**Comment by elParaguayo** [comment]
I'm a bit uncomfortable that the maintainer has disappeared too. I don't really want to have to migrate our code to another library!

If you're interested, this is the commit that fixes the issue: https://github.com/altdesktop/python-dbus-next/pull/114

I wouldn't bother patching though. The test is using dbus_next in a way that we don't use in qtile itself. It's used to mock an app that provides a StatusNotifierItem so we can check that our widget works. The bit that's broken in dbus_next is not used in the core qtile code.

**Comment by dvzrv** [comment]
Ah thanks! Then I guess it might be better to wait for upstream to wake up again :crossed_fingers:
