### ISSUE TITLE
Decompression programs (bzip2, gzip, zstd) report "broken pipe"

### ISSUE THREAD

**Issue by acid-bong** [qtile/qtile#4242]
### The issue:

Whenever I run `man` (on Gentoo manpages are bz2-compressed), it says
```
bzip2: I/O or other error, bailing out.  Possible reason follows.
bzip2: Broken pipe
        Input file = (stdin), output file = (stdout)
```
as many times as there are manpages with that name. Similar outputs with other compressors, gzip (`zless /proc/config.gz`) and zstd (manually compressed file). Log says nothing.

Not an issue in tty, ssh or under dwm.

Occurs on qtile 0.21.0 and 0.22.1
Python 3.10.10
GCC 12.2.1
OS: Gentoo Linux

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I know nothing about Gentoo but I'm struggling to see how qtile has any impact on that.

If you're convinced it's qtile causing the issue then you'll probably need to do a bisect to find the offending commit.

**Comment by acid-bong** [comment]
Ight, it's not necessarily qtile's fault: decompressors don't seem to like it when the terminal emulator window's parent isn't login shell or the WM (and qtile launches everything under ppid=1, unlike dwm, xmonad and some others).

Discovered when tested running dwm as a user service, and after dwm's restart the terminal window was reparented by Xorg.

**Comment by Malex** [comment]
I'm actually running Funtoo (which is a fork of Gentoo) and I do not have this issue on python 3.9
Did you try using one of your other py install? (you should have multiple slots)

**Comment by Malex** [comment]
Looking around, it's way more likely it's actually the terminal emulator. (see for example https://github.com/kovidgoyal/kitty/issues/277 or https://bugs.gentoo.org/409745 )

**Comment by ramnes** [comment]
Closing as per @Malex Gentoo bug link, it's on Kitty's side. I'm on Gentoo / Qtile and can open man pages (with ROXTerm).
