### ISSUE TITLE
Bluetooth widget error

### ISSUE THREAD

**Issue by AndreidForGit** [qtile/qtile#4243]
### The issue:

I wanted to use the Bluetooth widget, but i got this
`2023-04-22 18:08:36,419 ERROR libqtile loop.py:_handle_exception():L63 interface not found on this object: org.bluez.Device1
NoneType: None`

qtile 0.22.1-3

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
How did you configure the widget?

**Comment by elParaguayo** [comment]
@AndreidForGit have you resolved this now?

**Comment by AndreidForGit** [comment]
Sorry for stop responding. I already solve the issue, I didn't understood how the widget work but now I do. Thank you very much for trying to help me.
