### ISSUE TITLE
CheckUpdates widget does not follow the config color on start

### ISSUE THREAD

**Issue by alt-013** [qtile/qtile#4252]
### The issue:
When starting Qtile (X11), the CheckUpdates widget color is set to white instead of the user configured color. For the config color to be set, Qtile needs to be reloaded.

**Config**
```
widget.CheckUpdates(
  padding = 0,
  colour_have_updates = '#84b424', 
  colour_no_updates = '#84b424',
  distro = 'Arch_paru',
  display_format = 'Upd {updates}',
  no_update_string = 'Upd 0',
  update_interval = 1800
),
```
**Logs**
`qtile --version`
```
0.22.1
```
`~/.local/share/qtile/qtile.log`
```
2023-05-05 12:44:44,419 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Very odd. Can't immediately see how that's possible from the code.

Will test later to see if I can recreate.

**Comment by elParaguayo** [comment]
Can't recreate this. Colour shows correctly when starting qtile.

**Comment by alt-013** [comment]
I have tried running my configuration on a clean Arch install and the issue is still the same, however when I copy the CheckUpdates widget block into a new configuration, the issue is gone. There may be a  problem with my configuration. I am sorry to bother you.

**Comment by elParaguayo** [comment]
Not a problem at all. If you share your config, I'm happy to take a look.

**Comment by alt-013** [comment]
At startup, on my main machine, the color for a few seconds is green (as in the config) and then it switches to white , waits for the update_interval time, and then goes back to green (I reduced the time from 1800 to 5).

My config is quite messy
https://gitlab.com/alt13/dotfiles/-/blob/master/.config/qtile/config.py
