### ISSUE TITLE
Error Log file for no reason!

### ISSUE THREAD

**Issue by Hamza12700** [qtile/qtile#4254]
### The issue:

qtile version: 0.22.1

I don't know what's wrong but for some reason, it dumps this big error log file, I try to look for the error but I think there's nothing to do with my qtile `config.py` I don't know what's wrong then.
I'm using python version `3.11.3`
Log file [qtile.log](https://github.com/qtile/qtile/files/11411844/qtile.log)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Seems like just a regular log where qtile is shutdown an loses the x11 connection

**Comment by jwijenbergh** [comment]
I am closing this issue because I do not think there is a bug here. If you want to reopen let me know
