### ISSUE TITLE
Intellij context menus flicker and overload the system

### ISSUE THREAD

**Issue by bodograumann** [qtile/qtile#4258]
### The issue:

Similar to #3963 and #3678  before, but now the context menus appear and flicker really quickly.
It looks like they are quickly changing there dimensions back and forth.
Sometimes, e.g. with auto-completion, I am able to select some item with enter.
In most cases though, I either have to kill intellij from a terminal or the whole system gets less and less responsive until it is completely stuck after a few minutes.

### System info
```
> qtile --version
0.22.2.dev185+g4ecf1bde
```

### Logs
It seems the following qtile logs are appearing during the problem:

> 2023-05-08 12:12:39,216 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
>     callback(listener, data)
>   File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
>     with self.wlr_output as wlr_output:
>   File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
>     self.commit()
>   File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 199, in commit
>     raise RuntimeError("Unable to commit output")
> RuntimeError: Unable to commit output

Related source code: https://github.com/flacjacket/pywlroots/blob/main/wlroots/wlr_types/output.py#L199

Intellij logs:

> 2023-05-08 14:26:37,142 [  12206]   WARN - #c.i.o.a.i.ActionUpdater - 1740 ms to grab EDT for BackAction#update@ProjectStructure (com.intellij.ui.navigation.BackAction)
> 2023-05-08 14:26:37,142 [  12206]   WARN - #c.i.o.a.i.ActionUpdater - 1741 ms to grab EDT for BaseStructureConfigurable$MyRemoveAction#update@ToolbarDecorator (AnActionButton$AnActionButtonWrapper/com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable$MyRemoveAction)
> 2023-05-08 14:26:43,426 [  18490]   WARN - #c.i.o.a.i.ActionUpdater - 4052 ms to grab EDT for BaseStructureConfigurable$MyRemoveAction#update@ToolbarDecorator (AnActionButton$AnActionButtonWrapper/com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable$MyRemoveAction)
> 2023-05-08 14:26:43,426 [  18490]   WARN - #c.i.o.a.i.ActionUpdater - 4053 ms to grab EDT for BackAction#update@ProjectStructure (com.intellij.ui.navigation.BackAction)

### Screenshots:

![Screenshot_20230508-120207](https://user-images.githubusercontent.com/1223583/236797398-421e1a29-3b38-4f85-8275-68e21957a863.png)
![Screenshot_20230508-120923](https://user-images.githubusercontent.com/1223583/236797691-7604e20f-4a0b-44b9-8784-73739e85dad1.png)
![Screenshot_20230508-120927](https://user-images.githubusercontent.com/1223583/236797696-03ccd010-0dc5-4a85-b413-7b3b0d0f42d1.png)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Thanks for the bug report, does #3985 fix this?

**Comment by bodograumann** [comment]
> Thanks for the bug report, does #3985 fix this?

Sorry, but I tried and failed to test with the wlroots 0.16 branch :disappointed:

**Comment by arjan-s** [comment]
I'm having this same issue with Android Studio on current git master (commit 91fa38e7)

**Comment by arjan-s** [comment]
There is hope, btw: https://blog.jetbrains.com/platform/2023/08/wayland-support/

**Comment by jwijenbergh** [comment]
Oh right! there was already an issue for this, great

**Comment by jwijenbergh** [comment]
Hmmm I can't reproduce this really, sure it does show a bit of black background on the popup for a second for me but that also happens on sway. I see no flickering. Albeit I only tried small projects. Did you try: `_JAVA_AWT_WM_NONREPARENTING="1"` ?

**Comment by arjan-s** [comment]
Yes, I have that env variable enabled system wide. Regarding reproducing it: it doesn't happen with normal menus or context menus, only with submenus of context menus and with mouseover (hover) popups.

**Comment by jwijenbergh** [comment]
> Yes, I have that env variable enabled system wide. Regarding reproducing it: it doesn't happen with normal menus or context menus, only with submenus of context menus and with mouseover (hover) popups.

I have tried it with a lot of different menus, also e.g. autocompletion.

**Comment by arjan-s** [comment]
One example of flickering is the "global search" function in Android Studio that's activated by default by pressing Shift twice. This brings up the search popup menu that works but gets resized by a few pixes every millisecond or so. This is what gets written to the qtile debug log **a lot** in this case:
```
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
2023-09-04 12:42:30,233 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
```
This specific flicker doesn't cause a crash or freeze for me though, just a very hot laptop. :)

**Comment by arjan-s** [comment]
Okay, one freeze and reboot later, I can confirm that the above lines are also logged endlessly when the freeze is happening I mentioned earlier. The more hefty one occurs when:
- a piece of code is highlighted because Android Studio has a hint about it or there's a syntax error
- mouseover the highlighted code
- the hint popup appears (and works fine)
- the first quick action works fine
- click the "More actions..." link to open up the second level context menu
- observe the log flooded by the above log lines and qtile freezes

**Comment by jwijenbergh** [comment]
> One example of flickering is the "global search" function in Android Studio that's activated by default by pressing Shift twice. This brings up the search popup menu that works but gets resized by a few pixes every millisecond or so. This is what gets written to the qtile debug log **a lot** in this case:
> 
> ```
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,230 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,231 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> 2023-09-04 12:42:30,233 DEBUG libqtile xwindow.py:_on_set_geometry():L458 Signal: xstatic set_geometry
> ```
> 
> This specific flicker doesn't cause a crash or freeze for me though, just a very hot laptop. :)

The global search reproduced it, thanks. Please try: #4442

**Comment by arjan-s** [comment]
Wow fantastic! Yes, that PR makes all menus stable, fluent and most importantly usable! Thank you!

**Comment by jwijenbergh** [comment]
Great! Thanks for testing.

**Comment by bodograumann** [comment]
Just updated to 0.23 and it works for me as well. Thanks for all your efforts!

**Comment by jwijenbergh** [comment]
> Just updated to 0.23 and it works for me as well. Thanks for all your efforts!

Glad it's working!
