### ISSUE TITLE
Fcitx5 glitches and then qtile freezes

### ISSUE THREAD

**Issue by franzmondlichtmann** [qtile/qtile#4260]
### The issue:

Qtile Version 0.22.1
When using Fcitx5-mozc (japanese input layout) and I type some japanese hiragana or katakana in, expected behaviour would be that a popup appears with suggested Kanji.
But when using Qtile and I type something into Google Search on Firefox the Kanji-Popup appears and glitches, then the qtile-wm freezes. Exiting with key press still works.
Btw. I use Nvidia 3050 RTX, but I had no problem with other Wayland-Compositors and Fcitx5 worked fine under KDE Wayland and Hyprland. (Driver Version 530.41.03 should support GBM)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by franzmondlichtmann** [comment]
Fcitx5-mozc works fine under chromium!

**Comment by franzmondlichtmann** [comment]
Setting Firefox to Wayland-Mode did work as a workaround, but the issue still persists without the mode enabled.

**Comment by jwijenbergh** [comment]
Could you give #3985 a spin?
