### ISSUE TITLE
Mpv doesn't respect assign workspace when google-chrome is configured.

### ISSUE THREAD

**Issue by amonetlol** [qtile/qtile#4264]
### The issue:

Distro: Arch
Qtile: 0.22.1
mpv 1:0.35.1-6
google-chrome 113.0.5672.92-1

In the example below, mpv insists on opening in group 3, even configured to open in 6. When I unassign google-chrome, it opens correctly in 6.

```
groups = [Group("1", layout='monadtall'),
          Group("2", layout='monadtall'),
          Group("3", matches=[Match(wm_class='google-chrome')], layout='monadtall'),
          Group("4", layout='monadtall'),
          Group("5", matches=[Match(wm_class='discord|telegram-desktop')],layout='monadtall'),
          Group("6", matches=[Match(wm_class=["mpv", "vlc"])],layout='max'),
          Group("7", matches=[Match(wm_class='qbittorrent')],layout='monadtall'),
          Group("8", matches=[Match(wm_class='vmware')],layout='monadtall'),
          Group("9", layout='floating')]
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
The problem here is that mpv's wm_class is `["gl", "mpv"]`. The way the comparison works is it checks if any of those values are contained in the class of the window it's comparing. As `gl` is a substring of `google-chrome`, it matches.

You can fix that my making the google chrom match a regex i.e.
``` python
import re

...
groups = [
    ...
    Group("3", matches=[Match(wm_class=re.compile('^google-chrome'))], layout='monadtall'),
]
```

**Comment by amonetlol** [comment]
Thank you very much,

Worked perfectly. Problem solved.
