### ISSUE TITLE
CurrentLayoutIcon widget's size affected by bar margins

### ISSUE THREAD

**Issue by ReyVega** [qtile/qtile#4272]
### The issue:

**qtile version:** 0.22.2.dev185+g4ecf1bde

After upgrading my qtile to the latest version, I was looking at my top bar and noticed that the CurrentLayoutIcon widget was getting out of the bar and its size was different. After playing with qtile's default config and mine, it seems that North and South bar's margins are causing the issue. Widget's size was not affected by bar's margins previously

**Then**
![before](https://github.com/qtile/qtile/assets/47400747/1bcc4428-607b-4e35-97c5-db75fab24844)

**Now**
margins=[10, 10, 10, 10]
![error1](https://github.com/qtile/qtile/assets/47400747/0b1f6ad2-b1d3-40d0-8d88-83efa6ff656a)
margins=[0, 10, 0, 10]
![error2](https://github.com/qtile/qtile/assets/47400747/369241da-7ecc-42f4-a227-e0b0e3629842)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. There were some changes to this widget recently so I obviously broke something!

Will take a look.

**Comment by elParaguayo** [comment]
#4273 should fix this.

**Comment by ReyVega** [comment]
Tested it and it works! Thanks :D
