### ISSUE TITLE
`qtile_info` root command returns empty dict

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4274]
### The issue:

This is maybe not that big of a deal, as there's plenty of other things currently on track to be solved, but I'm not one for throwing this under the bed and calling it a day 😄  As a starting point, maybe we could have the path of the currently loaded config? What do you think?

```console
$ qtile cmd-obj -o cmd -f qtile_info
{}
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Sure. Maybe add the version number and log level too.

PR would be welcome.

**Comment by ervinpopescu** [comment]
I was looking through the `start` script and I noticed that's where the config is loaded:
```py
config = confreader.Config(options.configfile)
```
Is this where I'm supposed to get the config path from?
I'm currently clueless as to how I'm supposed to get the `options.configFile` into `core.manager.Qtile` as the options that are passed on the command line are not accessible there.

**Comment by elParaguayo** [comment]
Should just be `self.config.file_path`.

**Comment by ervinpopescu** [comment]
> Should just be `self.config.file_path`.

Oof. That's just me not knowing the innerworkings of qtile once again. I'll get on with doing that then :)
