### ISSUE TITLE
firefox don't open

### ISSUE THREAD

**Issue by Arturo0911** [qtile/qtile#4283]
### The issue:

in qtile when i run firefox take a a long time to open, but in another desktop like gnome open normal.
I love qtile but I have this problem.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Is this on Wayland?

**Comment by MathieuGFB** [comment]
I have the same issue since almost a month. 

It is not Wayland-related, as I use Xorg

**Comment by C0rydoras** [comment]
I had the same issue, I was able to solve it by replacing xdg-desktop-portal-gnome with xdg-desktop-portal-gdk

**Comment by Paradox-me** [comment]
I had the same issue when using xmonad. Not just with Firefox, but with many GTK applications. It seems to be a dbus problem. I solved it (with help from a friend) by putting exec dbus-launch --exit-with-session <PATH-TO-WINDOW-MANAGER> in my ~/.xinitrc.

Good luck! :-)

**Comment by jwijenbergh** [comment]
Doesn't sound like a qtile issue. Most commonly this is a dbus problem. If not please re-open

**Comment by elParaguayo** [comment]
To add to the above comment, the delay is often caused by not having a notification server running (e.g. `dunst` or the `Notify` widget).
