### ISSUE TITLE
Can't set the margin as [N, E, S, W] on MonadThreeCol

### ISSUE THREAD

**Issue by mcnuggetsx20** [qtile/qtile#4288]
### The issue:

While other layouts (e.g. Colums) accept the margin set to a list of margins [N, E, S, W], MonadThreeCol seems to have a problem with it. When I try it everything about the layout breaks
![image](https://github.com/qtile/qtile/assets/71185521/75768361-d74e-4789-a35f-48094635c0c4)
The photo clearly shows that qtile doesn't understand the layout we set. I think it should work like any other layout

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you post your config?

**Comment by mcnuggetsx20** [comment]
Sure thing
https://github.com/mcnuggetsx20/linux-pc/blob/main/.config/qtile/config.py

**Comment by elParaguayo** [comment]
Thanks. Yes - there's a bug in the code here. Will submit a fix shortly.
