### ISSUE TITLE
The documentation site is down.

### ISSUE THREAD

**Issue by ZmjbS** [qtile/qtile#4295]
### The issue:

The document website seems to be down. When I visit http://docs.qtile.org/ my client can't resolve the address.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Use https://qtile.readthedocs.io/en/stable/ for now.

**Comment by elParaguayo** [comment]
Pinning this for now to prevent multiple posts.

**Comment by teika-kazura** [comment]
If this could be of some help:
When qtile.org was down (around 10 June?), docs.qtile.org was alive.

Thanks beforehand.

**Comment by ramnes** [comment]
It's up.
