### ISSUE TITLE
Documentation for Key Chords is out-of-date

### ISSUE THREAD

**Issue by esmith1412** [qtile/qtile#4296]
### The issue:

I'm using Qtile version 0.22.1, and when I look at the documentation for KeyChord modes, [here](https://docs.qtile.org/en/stable/manual/config/keys.html#modes), it says that there are two keyword arguments: `mode` (a boolean) and `name` (a string). However, with the current, stable API there is only one keyword argument: `mode`, and this is a string meant to specify a name (in effect, it does both: setting `mode = True` and `name = foo`). This page should be updated to reflect the current API.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
In the latest version (i.e. git master) `mode` is a boolean and `name` is a string. If you set `mode` as a string you will get a deprecation warning in your log.

Which specific part of the docs do you think is wrong?

**Comment by esmith1412** [comment]
I guess I'm confused; I'm using the latest version of Qtile that's available on Arch Linux, and when I try to set `mode` as a boolean, IntelliJ gives me a warning, and my config compiles perfectly fine when I use a string.

**Comment by elParaguayo** [comment]
The old behaviour was for `mode` to be a string however I think this was changed before 0.22.1.

To avoid breakages, we allow configs to set `mode` as a string even though this isn't what we want. If a user does this, `mode` will be set to `True` and `name` will be set to the string given to `mode` originally. This behaviour will be deprecated so a warning is also provided to the user.

0.22.1 is the stable version and the docs show this:
![20230607_223108](https://github.com/qtile/qtile/assets/946265/c341400d-cf54-4634-921d-7416f2292a03)

**Comment by esmith1412** [comment]
Okay, the reason for my confusion was because Pycharm installed an older version of Qtile, while my OS has the latest stable one. Thank you for your help.
