### ISSUE TITLE
Openweather widget showing "No network" / qtile's use of http vs https

### ISSUE THREAD

**Issue by kennykingdev** [qtile/qtile#4300]
### The issue:

I'm using qtile 0.22.1 on arch linux.  Sometime within the last week, at least a couple days ago, my openweather widget started showing "No network".  My network/internet is fine.

Playing around with the api I figured out that the server is not responding to http requests, but is working fine with https requests.  I see the widget code is using http.  The openweathermap docs still show examples using http, and I don't know if this is a temporary issue for them or a permanent change.

Replacing all use of http with https throughout the project would be ideal (excepting cases where https might still not be available), but at least this widget should be updated to get it working again.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks. Would you be happy to make a pull request for for this?

**Comment by kennykingdev** [comment]
I'd love to, but I'm actually discovering it might be something else on my end after all.  Is anyone else able to reproduce the problem?

**Comment by kennykingdev** [comment]
I'm going to go ahead and close this.  I'm not sure what the problem was, but it's working again with no changes that I'm aware of.
