### ISSUE TITLE
Getting error when trying to use `qtile.core.backend`

### ISSUE THREAD

**Issue by egolep** [qtile/qtile#4301]
### The issue:

I'm trying to follow the indication given in the documentation in order to have wayland specific configuration. However, whenever I try to use `qtile.core.backend` in order to do things differently when this is equal to `x11` or `wayland`, but I keep getting an error stating that `'NoneType' object has no attribute 'core'`.

Is this a deprecated way to do it? I'm I missing an import? Right now, I have `from libqtile import qtile`, as seen in the doc and in many configurations I've seen.

Qtile version: 0.22.1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ervinpopescu** [comment]
As far as I can tell, you have to use `qtile.core.info()["backend"]`.

**Comment by elParaguayo** [comment]
You can use `qtile.core.name` but it doesn't look like it'll fix your problem as `qtile` is `None`.

I've seen this bug before which can happen if the config is loaded before the backend is started as, in that case, `qtile` will still be `None`. However, I'm having trouble recreating it.

Can you share your config?

**Comment by egolep** [comment]
Here it is, with all the auxiliary files I use:

https://gitlab.com/olep/config

If it could be relevant, I use `lightDM` as my display manager

**Comment by egolep** [comment]
Any update on this? I tried to inspect it a bit more but with no luck.
If there is any other information that could be useful, I'd be happy to give it.

**Comment by egolep** [comment]
I also tried to use `SDDM` as my dysplay manager but nothing changed

**Comment by jwijenbergh** [comment]
Which distro is this on?

**Comment by egolep** [comment]
It's on arch. Qtile version 0.22.1

**Comment by egolep** [comment]
Now I tried to install the version coming from the `qtile-git` package from the AUR. It solves the problem with `qtile.core` being `NoneType` but introduces a bug telling `No module named 'cairocffi.ffi'`

**Comment by elParaguayo** [comment]
If you're on git version you need latest versions of cairocffi (1.6.0) and xcffib (1.4.0)

**Comment by elParaguayo** [comment]
@egolep can this be closed now?

**Comment by egolep** [comment]
I'm still facing the problem. Now that Arch repositories updated the `cairocffi` and `xcffib` libs to the correct version, eventi the `qtile-git` package from the AUR have this issue.
If you think this is a packaging problem on Arch's end, you can close this.

**Comment by elParaguayo** [comment]
Which error are we talking about? The `No module named 'cairocffi.ffi'` or `'NoneType' object has no attribute 'core'`?

**Comment by egolep** [comment]
The original error of the issue, meaning `'NoneType' object has no attribute 'core'`

**Comment by m-col** [comment]
I don't think anything related to this changed since the last release. `from libqtile import qtile` should work as you expect in the last couple releases and previous one, and doing that is the correct method. When the user config is imported and used by qtile, `libqtile.qtile` has already been set to be not `None`. It sounds like you have edited the `default_config.py` file in place, rather than using your own file. Is that possible?

**Comment by egolep** [comment]
I don't think so, since I tried this on different machines on different fresh installs of Arch. I clone my own config files and use them directly after installing `qtile`.
If it can be useful, I can try to see if using `default_config.py` the problem is still present or not

**Comment by m-col** [comment]
Where do you clone your config files to?

>  If it can be useful, I can try to see if using default_config.py the problem is still present or not

Yeah that would be good thanks

**Comment by elParaguayo** [comment]
Changing the test to `qtile.core.name` in your config runs fine on my machine.

**Comment by elParaguayo** [comment]
This was fixed in #4544.
