### ISSUE TITLE
non-latin keyboard layout

### ISSUE THREAD

**Issue by parham-dev27** [qtile/qtile#4302]
### The issue:

Qtile 0.22.1
I change my keyboard layout using this function:
`def switchLayout(qtile):
    p1 = subprocess.Popen(['setxkbmap', '-query'], stdout=subprocess.PIPE)
    p2 = subprocess.Popen(['grep', 'layout'], stdin=p1.stdout, stdout=subprocess.PIPE)
    p3 = subprocess.Popen(['cut', '-d', ':', '-f2'], stdin=p2.stdout, stdout=subprocess.PIPE)
    output = subprocess.check_output(['tr', '-d', ' '], stdin=p3.stdout)

    # Decode the output (it will be in bytes)
    output_str = output.decode('utf-8').strip()

    if output_str.lower() == "de":
        subprocess.Popen(['setxkbmap', '-layout', 'ir'])
    else:
        subprocess.Popen(['setxkbmap', '-layout', 'de'])
`
Keybindings like ctrl+c,  ctrl+x or super+q etc. work in a latin layout but not in non latin layout.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Closing in favor of #4250
