### ISSUE TITLE
Gap on second window monadthreecol

### ISSUE THREAD

**Issue by yodigi7** [qtile/qtile#4311]
### The issue:

I wanted to toggle the bar off with two windows open in MonadThreeCol layout.
It successfully hid the bar but left a gap on only the secondary window above and below but not the main window. It works as expected in the MonadTall layout.
I expected both windows to successfully span the full screen from top to bottom.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you add a screenshot?

I've got an open PR to fix something else with that layout so I can add this to it.

**Comment by yodigi7** [comment]
![image](https://github.com/qtile/qtile/assets/19217358/c65e7e6b-3dfd-4bba-8e8c-094a601ca13c)

**Comment by yodigi7** [comment]
note the ~15 pixel gap below on the right hand window

**Comment by elParaguayo** [comment]
Great. Thanks. I'll get this fixed.

**Comment by elParaguayo** [comment]
This should be fixed by #4292
