### ISSUE TITLE
Invisible bar when unhiding

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4313]
### The issue:

When I hide the bar and unhide it after some time, i have only a gap instead of the bar. So far, I haven't dived into it, but #4311 reminded me of it and made me wonder if it's related to `monad*` layouts only. I'll try to get more info and maybe make it reproducible.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
This should be independent of the layout.

If you can recreate this reliably then I'll take a look.

**Comment by ervinpopescu** [comment]
I can't recreate now, if this comes up again, I'll reopen.
