### ISSUE TITLE
Qtile Wayland - unable to create allocator

### ISSUE THREAD

**Issue by Freemason-12** [qtile/qtile#4325]
### The issue:

qtile version: `0.22.2.dev203+g42ed926a`

When I try to start qtile ob wayland session I get this:
```
MESA-LOADER: failed to open iris: /usr/lib64/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
00:00:00.049 [render/allocator/gbm.c:198] gbm_create_device failed
00:00:00.049 [render/allocator/allocator.c:134] Failed to create allocator
Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/main.py", line 82, in main
    func(options)
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/core.py", line 125, in __init__
    ) = wlroots_helper.build_compositor(self.display)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wlroots/helper.py", line 30, in build_compositor
    allocator = Allocator.autocreate(backend, renderer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wlroots/allocator.py", line 25, in autocreate
    raise RuntimeError("Unable to create an allocator.")
RuntimeError: Unable to create an allocator.
```

and yet the issue is not completely the same as #4146 because there the creator of that issue had a `wlroots` folder in `/usr/lib/python3.11/dist-packages` directory, but i don't have that. I only have that folder is `/usr/local/lib/python3.11/dist-packages` folder after I install the needed version of `pywlroots`
How can I solve this?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Freemason-12** [comment]
I was able to solve the issue (I'm running Debian Bookworm stable)
First, we need to give a link to system's xkbcommon.so file so that qtile uses that and not the one installed with pip:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libxkbcommon.so /usr/local/lib/python3.11/dist-packages/pywlroots.libs/libxkbcommon-de59cad2.so.0.0.0`
and then I had to execute qtile with a different command, which sets proper environment variable for driver lookups:
`LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri/ qtile start -b wayland`
the last command is what is written in `.desktop` file to execute it.

**Comment by Freemason-12** [comment]
Oh well, not so fast. I put the last command into `/usr/share/wayland-sessions/qtile.desktop`, but it does not work (at least with sddm), it works only on tty for some reason.

**Comment by Freemason-12** [comment]
I was able to launch to wayland session by just using `qtile start -b wayland` on `/usr/share/wayland-sessions/qtile.desktop`, but cursor turns invisible after I launch any kind of window.

**Comment by Freemason-12** [comment]
Looking at the journal, seems like it does not see xdg-desktop portal. from Wayland to-do list it looks like something which is not implemented yet.
Is there a way around this?

**Comment by jwijenbergh** [comment]
> I was able to launch to wayland session by just using `qtile start -b wayland` on `/usr/share/wayland-sessions/qtile.desktop`, but cursor turns invisible after I launch any kind of window.

Try lauching with WLR_NO_HARDWARE_CURSORS=1

**Comment by Freemason-12** [comment]
> > I was able to launch to wayland session by just using `qtile start -b wayland` on `/usr/share/wayland-sessions/qtile.desktop`, but cursor turns invisible after I launch any kind of window.
> 
> Try lauching with WLR_NO_HARDWARE_CURSORS=1

Thank you, it works, but only when launching with tty. How can I launch with this env variable in SDDM (writing an env variable in `qtile.desktop` does not work)?

**Comment by ervinpopescu** [comment]
https://wiki.archlinux.org/title/environment_variables#Per_Wayland_session

Is this any help?

**Comment by cr1ogen** [comment]
I no  had a wlroots folder in `/usr/lib/python3.11/dist-packages` directory, anymore (Debian Sid)

**Comment by Freemason-12** [comment]
> https://wiki.archlinux.org/title/environment_variables#Per_Wayland_session
> 
> Is this any help?

I found another workaround. Just start a script written in the same directory instead of writing to the `.desktop` file directly

**Comment by Freemason-12** [comment]
here is the script:
```
#!/bin/bash
LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
```
the `dbus-launch` part may not be necessary though.

**Comment by cr1ogen** [comment]
> here is the script:
> 
> ```
> #!/bin/bash
> LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
> ```
> 
> the `dbus-launch` part may not be necessary though.

Don't work for me, give me a Segmentation faults

**Comment by Freemason-12** [comment]
> > here is the script:
> > ```
> > #!/bin/bash
> > LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the `dbus-launch` part may not be necessary though.
> 
> Don't work for me, give me a Segmentation faults

how did you launch it, started from tty? I put it a `/usr/share/wayland-sessions/qtile.desktop` as a `Exec` property and launched a session using SDDM.

**Comment by cr1ogen** [comment]
> > > here is the script:
> > > ```
> > > #!/bin/bash
> > > LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the `dbus-launch` part may not be necessary though.
> > 
> > Don't work for me, give me a Segmentation faults
> 
> how did you launch it, started from tty? I put it a `/usr/share/wayland-sessions/qtile.desktop` as a `Exec` property and launched a session using SDDM.
> Also, did you try removing the `dbus-launch` part?

Through tty, I'm going to try sddm because using lightdm it takes me back to the login manager. yes u try whitout dbus launch part

**Comment by Freemason-12** [comment]
> > > > here is the script:
> > > > ```
> > > > #!/bin/bash
> > > > LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the `dbus-launch` part may not be necessary though.
> > > 
> > > 
> > > Don't work for me, give me a Segmentation faults
> > 
> > 
> > how did you launch it, started from tty? I put it a `/usr/share/wayland-sessions/qtile.desktop` as a `Exec` property and launched a session using SDDM.
> > Also, did you try removing the `dbus-launch` part?
> 
> Through tty, I'm going to try sddm because using lightdm it takes me back to the login manager. yes u try whitout dbus launch part

Use SDDM instead, since lightdm still cannot work with wayland sessions for some reason.

**Comment by cr1ogen** [comment]
> > > > > here is the script:
> > > > > ```
> > > > > #!/bin/bash
> > > > > LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri WLR_NO_HARDWARE_CURSORS=1 dbus-launch qtile start -b wayland
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > the `dbus-launch` part may not be necessary though.
> > > > 
> > > > 
> > > > Don't work for me, give me a Segmentation faults
> > > 
> > > 
> > > how did you launch it, started from tty? I put it a `/usr/share/wayland-sessions/qtile.desktop` as a `Exec` property and launched a session using SDDM.
> > > Also, did you try removing the `dbus-launch` part?
> > 
> > Through tty, I'm going to try sddm because using lightdm it takes me back to the login manager. yes u try whitout dbus launch part
> 
> Use SDDM instead, since lightdm still cannot work with wayland sessions for some reason.

SDDM It doesn't work either

**Comment by cr1ogen** [comment]
In Qtile 0.23.0 the problem persist for me

**Comment by jwijenbergh** [comment]
This is not a qtile issue I think, try other wlroots based compositors

**Comment by cr1ogen** [comment]
> This is not a qtile issue I think, try other wlroots based compositors

I tried Sway and it works

**Comment by cr1ogen** [comment]
> > This is not a qtile issue I think, try other wlroots based compositors
> 
> I tried Sway and it works

maybe be a pywlroots problem? 🤔

**Comment by cr1ogen** [comment]
> This is not a qtile issue I think, try other wlroots based compositors

I Uninstall pywlroots which I installed via pip and download the source package from pypi.org, install it and now qtile-wayland works

**Comment by jwijenbergh** [comment]
Thanks. Could I close this or is there then still an issue?

**Comment by cr1ogen** [comment]
> Thanks. Could I close this or is there then still an issue?

I am not the author of the issue, I just had the same problem as him.
I hope he can solve it too

**Comment by jwijenbergh** [comment]
Feel free to re-open @Freemason-12
