### ISSUE TITLE
WidgetBox doesn't support padding

### ISSUE THREAD

**Issue by Tanish2002** [qtile/qtile#4328]
### The issue:

The WidgetBox widget doesn't support the padding attribute. 

Right Now I can use padding inside children widgets to space them.
But the `text_closed` and `text_open`can't be padded

It would be nice to have a `spacing` and a `padding` attribute
the spacing attribute could be used to space the widgets inside the widgetBox and padding attribute could be used for padding `text_open` and `text_closed`

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
#4333 adds the ability to set `padding`.

As for `spacing`: no, this won't happen. You just need to set padding for the individual widgets. WidgetBox isn't an actual container, it just adds/removes widgets from the bar so they are displayed according to their own settings.

**Comment by Tanish2002** [comment]
Alright makes sense! Thanks
