### ISSUE TITLE
Window doesn't size properly?

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4332]
### The issue:

Samples:

**with picom:**

[](https://github.com/qtile/qtile/assets/84532402/d146f274-5115-4304-9e0c-92eddf9796f7)

**without picom:**

[](https://github.com/qtile/qtile/assets/84532402/e4760be1-9296-4c15-b211-126311d0fe86)

The window gets sized properly once I click.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Does it happen with other wms + picom?

**Comment by ervinpopescu** [comment]
Will test.

**Comment by ervinpopescu** [comment]
https://github.com/qtile/qtile/assets/84532402/5c620873-ed7d-4328-8b8d-3c01b7c7d284

**Comment by ervinpopescu** [comment]
Cannot reproduce on qtile rn. Will reopen if it reappears.

**Comment by jwijenbergh** [comment]
Alright! Thanks for the update
