### ISSUE TITLE
volume widget doesn't work with pamixer

### ISSUE THREAD

**Issue by The-Piccion** [qtile/qtile#4335]
### The issue:

Hi everyone,

I was trying to make qtile volume widget working with pamixer (btw, I am using pipewire).
I configured the widget like this:
> widget.Volume(
                       foreground = colors[2],
                       background = colors[5],
                       padding = 5,
                       volume_app = "pamixer",
                       get_volume_command = "pamixer --get-volume-human"
                       )

The problem is that qtile doesn't seem to care much about the `volume_app` setting and keeps trying to load amixer; this is the log:
>  2023-07-06 18:56:15,558 ERROR libqtile base.py:_wrapper():L359 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 357, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/volume.py", line 126, in update
    vol = self.get_volume()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/widget/volume.py", line 188, in get_volume
    mixer_out = self.call_process(get_volume_cmd)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 344, in call_process
    return subprocess.check_output(command, **kwargs, encoding="utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] File o directory non esistente: 'amixer'

qtile Version : 0.22.1

PS: I've already read the issue https://github.com/qtile/qtile/issues/1711, but it didn't work out for me as I have a different setting. I also tried to remove foreground, background and padding settings but nothing happened 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Please test master, that widget had changes

**Comment by The-Piccion** [comment]
What do you mean by "test master"? because there is neither widget  nor options that are called like that

**Comment by elParaguayo** [comment]
Use the latest git version of the widget rather than the release. There have been a lot of updates since then.

**Comment by The-Piccion** [comment]
ok, I'll try to (but I guess it will be tomorrow. can you wait a bit to close the issue, pls?)

**Comment by elParaguayo** [comment]
Don't worry. We won't close until you've confirmed you're happy for it to be closed.

**Comment by The-Piccion** [comment]
I tried to download the master version as explained into the download section of the qtile site, but I can not perform a makepkg or a make that installs it, so I am quite stack (as the install doc web page gives me a DNS error)

**Comment by ervinpopescu** [comment]
Use https://qtile.readthedocs.io/en/latest/.

**Comment by The-Piccion** [comment]
I tried to create the file qtile.desktop in /usr/share/xsession/ as an empty file at first. Then, i tried to put Exec=/etc/X11/xsession in it and it still didn't work. At last, I tried to put at the endo of the file exec qtile start.
In all these cases gdm wasn't able to spot qtile between the available option before the login

**Comment by The-Piccion** [comment]
I fell even more stupid than normal... I have tried /usr/share/xsessions, in my last message I made a typing error

**Comment by ramnes** [comment]
Use Qtile 0.23.0 and PulseVolume instead

**Comment by The-Piccion** [comment]
> Use Qtile 0.23.0 and PulseVolume instead

I have no problem while using pulse. My problem was thatI needed to use pipewire and it didn't work with that

**Comment by ramnes** [comment]
Isn't Pipewire supposed to be ABI-compatible with PA?

**Comment by jwijenbergh** [comment]
It should be if you use pipewire-pulse

**Comment by The-Piccion** [comment]
> It should be if you use pipewire-pulse

I installed that package, but it just didn't work

**Comment by jwijenbergh** [comment]
What does "doesn't work" mean?

**Comment by The-Piccion** [comment]
> What does "doesn't work" mean?

After all this time, I don't remember what wasn't working precisesly. I just remember that I was not able to control system volume in any way
