### ISSUE TITLE
Logs pollution - keyboardlayout.py

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4342]
### The issue:

Bunch of these:
```
2023-07-15 15:28:06,304 ERROR libqtile keyboardlayout.py:set_keyboard():L102 Can not load ~/.Xmodmap:
```
My humble opinion is that if I don't use something optional, I shouldn't have an error about it in the logs. Oh and it's supposed to be **"Cannot"**. I don't have another idea on how this should be done atm.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Agreed. That looks like it could log error messages too often.

I've made some changes in #4348 - would be good if you could test.
