### ISSUE TITLE
`plank` window not kept above

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4355]
### The issue:

Following discussion at #4049. Would be interesting to check if related to #1145. Going to try  `keep_above` with `tint2`, although I think this is a `qtile` issue. Also gonna try my hand at a `bisect`.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I'm not sure I'd bother with a bisect. I suspect there's just a bug in our implementation of layering.

NB by default, floating windows will have `kept_above` set to `True` so `plank` wouldn't necessary stay above these. That being said, I don't think the implementation is quite right as normal, tiled windows seem to open above it which shouldn't happen.

**Comment by elParaguayo** [comment]
I'll need to look at my code again but I have an idea what the issue is here: `plank` is a `Static` window which means it has no group attached to it. This may interfere with some of the logic as currently written.

**Comment by elParaguayo** [comment]
Ignore that. Your original suggestion (in the Discussion) was correct - the issue is that `bring_to_front` ignores these rules.
