### ISSUE TITLE
Need help installing qtile in arch

### ISSUE THREAD

**Issue by zielOS** [qtile/qtile#4358]
### The issue:

Cannot install git version of qtile arch. Need  cairocffi[xcb]>=1.6.0. Only 1.5.0 available in arch

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Although some of the Qtile maintainers and contributors also happen to be packagers for various Linux distributions, this issue tracker is about Qtile, not Arch Linux. Sorry!

**Comment by ervinpopescu** [comment]
How about following this in a discussion? Would that be okay, @ramnes?

**Comment by ramnes** [comment]
Yes why not, but then I'm not sure why you guys want to discuss that on Qtile's GitHub repository rather than on Arch forums or similar

**Comment by elParaguayo** [comment]
I have some sympathy here. I've flagged the packages as being out of date on Arch a while ago and they haven't been updated yet. I suspect they won't be updated until we force the issue with the next release. 

In the meantime, you can use these PKGBUILD files: https://gist.github.com/elParaguayo/d351d7bbea56198a9d27fb662b720545

Note: While these files work for me, I'm not well versed in package management so don't blame me if they break something on your system.

**Comment by zielOS** [comment]
Yeah I am thinking of doing that, for the other packages too. Btw, I haven't tested your code yet hopefully tmrw and let you know. Btw I can't thank you enough for all the help you provided. @elParaguayo. You truly are gem of a selfless person.
