### ISSUE TITLE
BSP layout , lazy.layout.next()  stuck at first windows.

### ISSUE THREAD

**Issue by tomudo** [qtile/qtile#4359]
### The issue:

I wanted to focus around windows , but it stuck at the first window, and I expected it move focus to all next windows but it stuck on first window. I think this is a bug.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can't replicate this. On `Bsp` layout, `lazy.layout.next()` moves to the next window until it reaches the last window and then it stops. `next()` doesn't go back to the beginning. You

**Comment by tomudo** [comment]
Sorry for my  incorrectly description.

When I create 6 terminal BSP layout, I have window order like this
[1] [5] [   3   ]
[2] [6] [   4   ]

When I call lazy.layout.next() by keybind "mod  + space" , window focus order is 1 -> 5 -> 2 -> 6 -> 3 -> 4 .
It stuck at window #4 which I think it should have next focus to windows #1.

**Comment by elParaguayo** [comment]
In that scenario,  I expect 4 is the end of the tree.  As i said above, `next` does not go back to the beginning so it won't go to 1. It may be possible to add code so that `next` will wrap back to the beginning.

**Comment by tomudo** [comment]
Thank for your info.
