### ISSUE TITLE
Pcmanfm "Operation not supported" in Qtile - works in Xfce (Void Linux)

### ISSUE THREAD

**Issue by ebiscaia** [qtile/qtile#4369]
### The issue:

Hi,

Not quite sure where the problem is, but every time I try to use the Devices or Network buttons in Pcmanfm running in Qtile I get the error: "Operation not supported". So, I decided to install the Xfce4 version in a VM and everything worked fine. To finish that I installed Qtile in the same VM and same problem as in the main machine. All of this in Void Linux.

Qtile version:
```
❯ qtile -v                        
0.22.0
```

Thanks

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
How are you launching qtile? Smells like a dbus issue. see https://www.reddit.com/r/voidlinux/comments/ifea3z/no_trash_support_for_pcmanfm_nonqt/ for a related issue

**Comment by ebiscaia** [comment]
Hi mate,

I am using Lightdm to start qtile. I managed to solve my problem after seeing your link and then this [post](https://www.reddit.com/r/voidlinux/comments/qhtdjd/it_looks_like_gvfs_is_not_available).

What I did was to edit the file /etc/lightdm/Xsession from:
```
exec $@
```
To:
```
exec dbus-run-session $@
```
Thanks again
