### ISSUE TITLE
Firefox Floating Prompts inaccessible+not hidden on workspace change

### ISSUE THREAD

**Issue by anymuster2** [qtile/qtile#4371]
### The issue:

Firefox permission prompts are not hidden when workspace is changed. Given the following HTML:

```
<html><body></body><script>
const successCallback = (position) => { console.log(position); };
const errorCallback = (error) => { console.log(error); };
navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
</script>
</html>
```

If I load the page in Firefox (served via `python3 -m http.server` and accessed on localhost, remotely it requires a HTTPS context). When loaded it shows an access prompt (screenshot below). If I change the workspace to Workspace 2,  the prompt remains, I can not click approve or deny on the prompt until I return to the valid workspace - this is despite button hover and button click events propagating to the window.

![Firefox prompt on Workspace 1](https://github.com/qtile/qtile/assets/54927313/fbd2fd8f-ee83-4e21-ac32-56c7347ae831)

![Firefox prompt on workspace 2](https://github.com/qtile/qtile/assets/54927313/786bb34e-8e2e-4913-b1c8-60f5f227cff8)

Tested on the latest git master under Ubuntu 23.04. Let me know if you need further version info / checks.   

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by anymuster2** [comment]
Edit: I should mention I'm using X11

**Comment by jwijenbergh** [comment]
This happens on i3 and awesome as well for me. firefox bug?

**Comment by anymuster2** [comment]
You may be right, I've raised it on FF bugtrack, https://bugzilla.mozilla.org/show_bug.cgi?id=1847145

**Comment by jwijenbergh** [comment]
Thanks for raising the issue! If this is a qtile bug, please re-open
