### ISSUE TITLE
Key input going to wrong window on recent focus change

### ISSUE THREAD

**Issue by anymuster2** [qtile/qtile#4372]
### The issue:

I have this issue, it started approximately 8-12 months ago but I was unable to figure out reliable steps to reproduce, apologies for the following instructions:

 -   Set follow_mouse_focus = False, aside from that the config I am using is entirely default
 -   Install BurpSuite Community Edition, https://portswigger.net/burp/communitydownload
 -   Open BurpSuite (it is in path pointing to /usr/local/bin/BurpSuiteCommunity at the top of the display there is a tab called 'Repeater', within the main panel, click the 'X' to show the request/response input fields
 -   Open Firefox
 -   Open a third window (this is my current workaround)
 -   In firefox, I click the address bar, type 'aaaa'
 -   In BurpSuite, I click the 'request' area and type 'bbbb'
 -   In firefox, I cilck the address bar and type 'cccc' - the 'cccc' is inputted into burpsuite, despite firefox having focus
-    If I reproduce the same steps, but after typing 'bbbb', I click the terminal, and then click the firefox address bar, it works fine. Focus seems to work fine with the terminal (e.g., if instead of Firefox I reproduce with the terminal). I am able to reproduce if I use a HTML text input in firefox (it is not specific to the the address bar).

BurpSuite is (from my understanding) a Java/SWING application. I have no idea if this is relevant but I have not seen the issue manifest elsewhere.

Tested Ubuntu 23.04 using Qtile git master (and previous versions) using X11. As I said above, this issue appears to have been introduced in the last 8-12 months (maybe a bit earlier, idk), I'm unsure if this is a Qtile bug or an underlying lib, but either way the issue does not seem to be widespread to other Window Managers.

![focus-bug](https://github.com/qtile/qtile/assets/54927313/8d50c6a7-467c-41cb-b787-44f71593a633)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
It seems to me that this is actually a burpsuite bug. Xprop gives the following:

`
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: False
                Initial state is Normal State.
`

This means qtile does not correctly update focus because of this, see https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/window.py#L1235-L1238. I will fix this but need to decide how we can best handle this. Thanks for the great bug report!

**Comment by jwijenbergh** [comment]
Please try https://github.com/qtile/qtile/pull/4375

**Comment by anymuster2** [comment]
That appears to have fixed it, thanks.

**Comment by jwijenbergh** [comment]
Thanks for testing! It will be merged shortly

**Comment by anymuster2** [comment]
@jwijenbergh I may have spoken too soon, your patch fixes the above test case but there appear to be others but I'm yet to create a reliable reproduction scenario. Should I open a new issue when I have that? 

Thank you for your time it is much appreciated - this bug has been annoying me for months (I thought it was user error for a long time, and I have no idea how X11 works).

**Comment by jwijenbergh** [comment]
> Should I open a new issue when I have that?

Sure issues are always welcome

> I have no idea how X11 works

No one really does, it's guess work :clown_face:
