### ISSUE TITLE
[wayland] Urgency doesn't work.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4380]
### The issue:

Like the title says - tested in foot and alacritty.

How to replicate:
1. open a terminal in one group
2. run `sleep 3; tput bel` in it
3. switch group

Expected result: urgency notification in GroupBox widget.

This can be solved via this patch: https://github.com/qtile/qtile/pull/3985#issuecomment-1657244951 but I've decided to create an issue instead of PR, as it was @jwijenbergh who found it and I don't want to take credit.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Is this still an issue? I don't think any PR was raised but I don't have this issue locally, tested with foot and alacritty.

**Comment by ftpd** [comment]
Yes. I'm running the current master and if I do something like `sleep 3; tput bel` and change the group, the one supposed to is not 'signaling' the urgency.

**Comment by jwijenbergh** [comment]
> Is this still an issue? I don't think any PR was raised but I don't have this issue locally, tested with foot and alacritty.

Hmmm, I think nothing changed to fix it

Maybe we should do https://github.com/qtile/qtile/pull/3985#issuecomment-1657244951 after all? Or is there a better fix?

**Comment by ftpd** [comment]
@jwijenbergh this still works - but only with `focus_on_window_activation = 'smart'` (the default, afaik). I would like to have it set to `never`, though - so for example my irc window won't steal the focus from the second terminal near it when I got a message.

**Comment by m-col** [comment]
Hmm, I wonder why it works for me. Did you configure the terminals to set urgency on bell? For example in foot you need:
```
[bell]
notify=no
urgent=yes
```
my alacritty config appears to be stock though 

FWIW I have: `focus_on_window_activation = "urgent"`

**Comment by ftpd** [comment]
I have the same `urgent=yes` set in foot. But! I have `focus_on_window_activation = "never"`. Let me test with `"urgent".

Btw. can we discuss it on discord? It will be easier ;-)

**Comment by ftpd** [comment]
Oh. It works fine with `focus_on_window_activation = "urgent"` AND also it doesn't steal the focus from the other window when I'm on the same group! Nice.

I think that concludes it and we can close the ticket as "user's fault"? ;-) Shall I?

**Comment by jwijenbergh** [comment]
I think there's still a bug here. The `focus_on_window_activation` should not influence whether or not we see the urgency color in the bar right?

**Comment by ftpd** [comment]
Yes, that's the conclusion we've got on Discord a minute ago.

**Comment by m-col** [comment]
OK yeah let's merge that diff :)

**Comment by ftpd** [comment]
But this diff doesn't help, groupbox still doesn't change when `focus_on_window_activation = "never"`.

**Comment by m-col** [comment]
How's this?: https://github.com/qtile/qtile/pull/4486

I've tried to describe the logic inline for future readers, hope it's clear :)

**Comment by ftpd** [comment]
Doesn't work with "never" for me.

**Comment by ftpd** [comment]
Also, with "urgent", it immediately switched me to the window (and group) which triggered urgency, so it now behaves like the original "focus" setting.

**Comment by m-col** [comment]
Never doesnt work? It should reach the last part of the function, could you debug to confirm that please?
