### ISSUE TITLE
Please add before-sleep hook.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4385]
### The issue:

As discussed on Discord, I'm creating this issue for @jwijenbergh. This hook would solve the problem with screen lockers started by `resume` hook and the fact they show the desktop briefly before the locker kicks in.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
@jwijenbergh I can pick this up if you want. I added the resume hook previously.

Catching the sleep signal should be easy enough but I wonder if qtile needs to set an inhibitor to allow it to run a command before the machine sleeps.

**Comment by elParaguayo** [comment]
95% done. Just one odd little bug that I can't work out...!
