### ISSUE TITLE
Scratchpads under Wayland forces mouse focus on themselves.

### ISSUE THREAD

**Issue by ayham-1** [qtile/qtile#4390]
### The issue:

qtile v0.22.1

1- Follow the docs regarding setting up Scratchpads through DropDowns.
2- Run qtile using qtile start -b wayland
3- Press the keybinding for showing the scratchpad
4- press again to hide.
5- try and use mouse on the original active group, clicks on buttons of the scratchapd.

I tried this on Obsidian, Thunderbird, and Alacritty, all of them grabbing mouse focus indefinitely.
I tried playing with wrap_pointer and on_focus_lost_hide options with no change.

Weirdly, reloading config *sometimes* fixes the issue.

Logs don't show anything.

Maybe related:
Running Thunderbird with wayland option breaks the scratchpad. Shows only 'thunderbird' in the layout widget in the ar, and is not togglable.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Are those apps all running as X clients via XWayland? And if so, does it ever happen with wayland clients?

**Comment by ayham-1** [comment]
Those apps are running as XWayland, I checked through xprop. No, this issue does not seem to happen when using pure wayland.
