### ISSUE TITLE
[wayland] wlroots egl/gels2 errors in startup log since new wlroots version, no crash though

### ISSUE THREAD

**Issue by clotodex** [qtile/qtile#4400]
### The issue:

 While #3985 fixed a lot of issues for me, this one got introduced:
 ```
   1   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
   2   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
   3   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
   4   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [render/egl.c:264] Failed to initialize EGL
   5   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [render/egl.c:554] Failed to initialize EGL context
   6   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [render/gles2/renderer.c:679] Could not initialize EGL
   7   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [render/wlr_renderer.c:333] Could not initialize renderer
   8   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [backend/drm/renderer.c:27] Failed to create renderer
   9   │ 2023-08-14 09:05:48,567 ERROR wlroots log.py:log_func_callback():L16 [backend/drm/backend.c:256] Failed to initialize renderer
  10   │ 2023-08-14 09:05:48,568 ERROR wlroots log.py:log_func_callback():L16 [backend/backend.c:228] Failed to create DRM backend
  ```
  I don't feel any adverse effects (qtile running as normal) however, this is in the log so I am reporting it.
  
  Qtile version: commit: https://github.com/qtile/qtile/commit/f46450eef6eb2fab5e6a1037fe46893a8c8cc0ce (weirdly `qtile --version` returns 0.0.0, is that normal for a master branch install?)  
  A note on my system: Laptop with integrated AND dedicated graphics (dedicated turned off fully though) - I dont know if wayland/qtile make any assumptions and try to load the wrong drivers, maybe this is also not related at all

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
qtile doesn't do any special handling with loading drivers, that's all handled by a library called wlroots. Could you try other compositors that use the same wlroots version (0.16.0), maybe sway?

**Comment by clotodex** [comment]
The error magically disappeared after updates of the libaries (wlroots, pywlroots, qtile, wayland, ..) dont know what fixed it, but i will close as resolved :)

**Comment by jwijenbergh** [comment]
Thanks for the update and great it's resolved :). If it comes back feel free to re-open
