### ISSUE TITLE
Task: Steal horsik's widget-layouts code

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#441]
@horsik did a bunch of work in qtile a few months ago, but according to him the code was never ready to be merged. He hasn't been very active the last few months, so I propose we forcefully steal his code and include it in qtile. And by that I mean we should check his stuff, review changes and complete whatever it's missing.

**Comment by elParaguayo** [comment]
7 1/2 years old and I don't know what the "code" is... so closing this.
