### ISSUE TITLE
Weird borders around floating/dropdown windows

### ISSUE THREAD

**Issue by parham-dev27** [qtile/qtile#4416]
### The issue:

Version: 0.22.1

There are weird borders around some floating/dropdown windows. I use picom as a compositor but it also happens without picom. 
![20230822_223427](https://github.com/qtile/qtile/assets/87090730/62a160d7-6f15-4581-9a55-8d2b56c3e91f)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Please be more precise, it's simply impossible to replicate without more info. :(
