### ISSUE TITLE
Bar flickering

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4425]
### The issue:

qtile version: master

https://github.com/qtile/qtile/assets/84532402/52399af0-8fec-43f3-95cc-feb6f5581a3a

I have been running commit 51b394b6 and that seems fine. Will try to figure out which commit introduced this. I am running picom too and without it it looks the same. Any changes to `bar.draw` lately?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the post.

I'm not aware of any significant changes to `Bar.draw` before that commit. There have been some changes since...

However, I'd be inclined to disable some of your widgets one-by-one and see if it can be isolated to one of those.

**Comment by elParaguayo** [comment]
Ah, my misunderstanding.

Is this Wayland or X11?

Ideally, it would be great if you could do a `git bisect` here to find the offending commit.

**Comment by ervinpopescu** [comment]
X11, will get on the bisect ASAP, perhaps this evening.

**Comment by ramnes** [comment]
bisected to c840df2775a6209345b0350e04c0161723bc36c4

**Comment by elParaguayo** [comment]
Interesting. Any steps to recreate this?

**Comment by ramnes** [comment]
I just open something like 10 terminals by spamming my keybinding, and the bar flickers because the window names widget get's updated.

**Comment by elParaguayo** [comment]
Hmm. Still can't recreate. Even ran a loop calling bar.draw() multiple times.

**Comment by ervinpopescu** [comment]
For me, it's the TaskList widget and toggling widgetbox(es). As the bar is drawing widgets sequentially, I only see the flickering on its right side.

**Comment by ramnes** [comment]
> Hmm. Still can't recreate. Even ran a loop calling bar.draw() multiple times.

Maybe there's one widget in particular that doesn't like being re-drawn all the time? Or maybe it's the amount of widgets?

Here's the relevant part in my config: https://github.com/ramnes/qtile-config/blob/7b409ffc84608854bcb9007f60cffdcb0c4d89ec/config.py#L232-L270

**Comment by elParaguayo** [comment]
Nice - will check that later.

I'm assuming the problem is caused by that commit because it clears the bar's background and then each widget has to redraw itself every time we call `Bar.draw()`. Before that commit, the flickering should still exist if the bar is drawing borders as that's was the trigger for needing to clear the drawer. Are you able to revert the offending commit and confirm that that's the case?

**Comment by ramnes** [comment]
Do you have any idea as to to how we could confirm that the bar flickers when it's drawing borders?

**Comment by elParaguayo** [comment]
Sorry, I wasn't clear. What I'm suggesting is:
- Revert commit c840df2
- Add borders to your bar
- Do exactly the same steps you did before to trigger the flickering
- Confirm whether flickering still happens or not

**Comment by ervinpopescu** [comment]
It does flicker for me.

**Comment by elParaguayo** [comment]
I've got a solution that should work for x11 but I need to work out the wayland implementation as the Drawers are slightly different.

**Comment by elParaguayo** [comment]
This has actually led me to find another issue: borders are broken on vertical bars.

**Comment by elParaguayo** [comment]
Can you see if #4433 solves this?

**Comment by ramnes** [comment]
it does

**Comment by ervinpopescu** [comment]
Yep it does for me too.
