### ISSUE TITLE
Missed key in xkeysyms.py

### ISSUE THREAD

**Issue by foresle** [qtile/qtile#4427]
### The issue:

Qtile version: `0.22.1`

I wanted to set key bind for switching language layout to one of "ThinkPad Extra Buttons". By `evtest` I found button name, it's "KEY_KEYBOARD". 

```
Event: time 1693412581.654672, -------------- SYN_REPORT ------------
Event: time 1693412581.654715, type 4 (EV_MSC), code 4 (MSC_SCAN), value 49
Event: time 1693412581.654715, type 1 (EV_KEY), code 374 (KEY_KEYBOARD), value 0
Event: time 1693412581.654715, -------------- SYN_REPORT ------------
```

I guessed, it can be named as "XF86Keyboard", like another functionally keys. 

```python
Key([], "XF86Keyboard", lazy.spawn("setxkbmap -query | grep -q 'ua' && setxkbmap us || setxkbmap ua,us"))
```

But got an error.

```
➜  ~ qtile check
Checking Qtile config at: /home/foresle/.config/qtile/config.py
Success: no issues found in 1 module
Success: no issues found in 1 source file
Config file type checking succeeded!
Traceback (most recent call last):
  File "/usr/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/check.py", line 137, in check_config
    config.validate()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 143, in validate
    raise ConfigError("No such key: %s" % k.key)
libqtile.confreader.ConfigError: No such key: XF86Keyboard
```

So I can't find correct key in [xkeysyms.py](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/xkeysyms.py), and I guess it's some issue.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by tych0** [comment]
I think it's just an oversight, we haven't updated xkeysyms in a long time. It used to be a regex, but I think that has long since gone away. It looks like the keysym for that key is this: https://cgit.freedesktop.org/xorg/proto/x11proto/tree/XF86keysym.h#n200

If you want to send a PR to add it to the map (and maybe update any others that are missing), that would be great!
