### ISSUE TITLE
qtile doesn't handle well focus in certain situations

### ISSUE THREAD

**Issue by jody-frankowski** [qtile/qtile#444]
Consider the following situation:
When one types in a webpage field (In Firefox only, chrome doesn't behave the same way) and autocompletion appears, the mouse cursor appears and as soon as one type too much so that the auto completion disapears, focus goes on the window where the mouse was.
The problem with firefox is that the autocompletion box is apparently a real X window.
But the real goal of course is to fix qtile handling of focus.

**Comment by kynikos** [comment]
I can't reproduce this bug even with old commits, maybe recent versions of Firefox fixed this?
And did #581 fix this in general?

**Comment by jhaubrich** [comment]
I can confirm this bug with Firefox 38.0.5. 

I think a hack where the mouse follows stack focus would fix this.

**Comment by jhaubrich** [comment]
Found `cursor_warp = True`, which totally fixes this.

**Comment by ramnes** [comment]
Please ping me if the bug is still present but since I can't reproduce, I'll assume that this issue is outdated. Thanks!
