### ISSUE TITLE
Dependency conflict on Arch

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#4443]
### Issue description

I tried to update my packages this morning and saw it failed with a conflict between python-pipenv and qtile-git (installed through AUR). 

```bash
error: failed to commit transaction (conflicting files)
python-pipenv: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.opt-1.pyc exists in filesystem (owned by qtile-git)
python-pipenv: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.pyc exists in filesystem (owned by qtile-git)
python-pipenv: /usr/lib/python3.11/site-packages/docs/conf.py exists in filesystem (owned by qtile-git)
```

I uninstalled qtile temporarily to resolve the conflict and update the rest of the packages, but attempting to reinstall qtile fails with the same errors:

```bash
error: failed to commit transaction (conflicting files)
qtile-git: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.opt-1.pyc exists in filesystem (owned by python-pipenv)
qtile-git: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.pyc exists in filesystem (owned by python-pipenv)
qtile-git: /usr/lib/python3.11/site-packages/docs/conf.py exists in filesystem (owned by python-pipenv)
Errors occurred, no packages were upgraded.
```

Was there a change in qtile or in python-pipenv that is leading to this conflict? What can I do to resolve it?

### Version

qtile-git-0.23.0.beta2.r4.g2c955718-1

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks for the report - we're trying to sort out packaging but there are some issues still!

@tych0 - I think this is the issue I mentioned about the wheels not respecting `Manifest.in` so we're packaging docs etc when we shouldn't be.

**Comment by DeeeeLAN** [comment]
What is a good commit I can revert to?

**Comment by elParaguayo** [comment]
91fa38e77b01eaba759d9049204e7ec6173ec44a
This should be before the packaging changes started.

**Comment by tych0** [comment]
Yep, thanks. Definitely needs fixing before release!
