### ISSUE TITLE
Bug: huge cpu usage lead to mouse problem in wayland/wirepipe

### ISSUE THREAD

**Issue by superiums** [qtile/qtile#4471]
### Issue description

mouse cursor flash all the time. (disappear, show, disappear,show quickly) in wayland.

also i notice qtile use 6% cpu and 2% mem of 16GB.
this is too high.

### Version

0.22.0

### Backend

Wayland (experimental)

### Config

```python
default
```

### Logs

```text
None
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
>  this is too high

Post CPU/RAM usage of other wlroots based compositors before making this claim

> mouse cursor flash all the time. (disappear, show, disappear,show quickly) in wayland.

please try to launch qtile wayland with the WLR_NO_HARDWARE_CURSORS=1 env variable set

Is this nvidia?

**Comment by m-col** [comment]
>  this is too high.

PR welcome

**Comment by superiums** [comment]
let me try.

> Is this nvidia?
No, it's amdgpu.

**Comment by superiums** [comment]
> this is too high.
if i touched any emotion, i apologize for it.
i only would like to figure out sth , without any emotion.

**Comment by superiums** [comment]
after set the variable:  `WLR_NO_HARDWARE_CURSORS=1` :
- the cursor still flash: be quiete for 2 seconds, and flash for 3 seconds. and go on. (formly always flash maybe for there's another tty running another wm, if only qtile running , flash 3 seconds every 5 seconds.)
- the cup usage slow down to normal 0.x as below:
(formly is 6% even idle)

```bash
❯❯❯ top |grep qtile
 2253 shvo      20   0 1357484 157412  99152 S   0.3   1.0   0:06.98 qtile      //---->do nothing
 2253 shvo      20   0 1357484 157412  99152 S   0.3   1.0   0:06.99 qtile      
 2253 shvo      20   0 1357484 157412  99152 S   0.7   1.0   0:07.01 qtile      
 2253 shvo      20   0 1357484 157412  99152 S   0.7   1.0   0:07.03 qtile      
 2253 shvo      20   0 1346108 157412  99152 S   5.3   1.0   0:07.19 qtile      //-----> move cursor
 2253 shvo      20   0 1346108 157412  99152 S   2.7   1.0   0:07.27 qtile      
 2253 shvo      20   0 1346108 157412  99152 S   3.3   1.0   0:07.37 qtile      
 2253 shvo      20   0 1344060 157412  99152 S   5.3   1.0   0:07.53 qtile      
 2253 shvo      20   0 1344060 157412  99152 S   4.7   1.0   0:07.67 qtile      
 2253 shvo      20   0 1378632 153956  95696 R   2.3   1.0   0:07.73 qtile      
 2253 shvo      20   0 1362872 141668  83408 R 100.0   0.9   0:07.75 qtile     //-----> open new window 
 2253 shvo      20   0 1399308 157124  98864 S   4.3   1.0   0:07.88 qtile      
 2253 shvo      20   0 1393392 157124  98864 S   1.3   1.0   0:07.92 qtile      
 2253 shvo      20   0 1393392 157124  98864 R   1.7   1.0   0:07.97 qtile      
 2253 shvo      20   0 1401232 157252  98992 S   8.9   1.0   0:08.24 qtile      //----->move cursor
 2253 shvo      20   0 1411180 157508  98992 S  12.6   1.0   0:08.62 qtile      
 2253 shvo      20   0 1409288 157764  99120 S  13.2   1.0   0:09.02 qtile      
 2253 shvo      20   0 1405388 157892  99248 S   8.6   1.0   0:09.28 qtile      
 2253 shvo      20   0 1405192 157892  99248 S  10.3   1.0   0:09.59 qtile   

```

pstree:
[tree.txt](https://github.com/qtile/qtile/files/12725637/tree.txt)

ps:
[ps.txt](https://github.com/qtile/qtile/files/12725648/ps.txt)

**Comment by m-col** [comment]
> if i touched any emotion, i apologize for it.

no worries :)

does the issue only happen with a specific piece of hardware? If you try another mouse, does it behave differently?

**Comment by superiums** [comment]
I'm on a laptop, i have touchpad and a Logitec wireless mouse.
i'll try to remove the wireless mouse later.

**Comment by superiums** [comment]
got it, its because the config file. 
seems there's something wrong with the config.
thanks for all your attention.

**Comment by superiums** [comment]
sovled

**Comment by superiums** [comment]
i've found more information about this.

- sometimes mouse flash over and over.
- sometimes it's not smooth while mouse moving.

all these is becuase the Xwayland process takes 100% cpu of 2 core. i only opened some blank alacritty.

**Comment by jwijenbergh** [comment]
What about other compositors such as sway?

**Comment by ramnes** [comment]
I'm going to be rude and I'm sorry in advance, it doesn't amuse me.

This issue isn't going anywhere and I want to keep a certain degree of "cleanliness" on our tracker, this is not a place for open discussions. If you just want to have someone try things on your side, come on Discord, people might be willing to help.

Otherwise, please open an other issue and put more effort into it. Limit yourself to one problem at a time. Then re-read your issue twice before checking this: "I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate."

In your case, that would mean explaining what works (default config? other compositor? other distro? other mouse? other computer?), the different things you tried, and what are the conditions required to trigger the problem. Ideally what would really help is a precise step by step guide to reproduce the issue reliably.
