### ISSUE TITLE
widget.groupBox() not rendering on multiplay displays

### ISSUE THREAD

**Issue by DanielRasho** [qtile/qtile#4489]
### Issue description

I currently running a setup with 3 monitors with all from different sizes in Manjaro:
- primary: 1920 x 1080
- secondary (2k) : 2560 x 1440
- tertiary (ultrawide): 2560 x 1080

I have tried to edit the way I define de widget.groupBox() and add it to "screen" variable, but something weird happen: Is well rendered on the primary display
![image](https://github.com/qtile/qtile/assets/98480883/8c4278a7-7e89-4e45-8fa1-fb4c60573ec6)

But it isn't visible on the others displays, but if you press in the areas were the gruops should be render, it changes de groups, so even though they are not visible, they are there:

![image](https://github.com/qtile/qtile/assets/98480883/6a6577ab-dde4-4a50-afea-a9defbe3aa6f)

![image](https://github.com/qtile/qtile/assets/98480883/b10cf1a1-de04-44eb-8885-9bfe69ab58b1)

This error just happen when I am in this 3 monitor setup, as fast as I disconnect one monitor, the groups start to render correctly on the 2 remaining monitors.

## What I have tried:
I tried to run the the default qtile config file, just  modifying the "screens" list variable by adding 2 new Screens() with the same parameters (Except from widget.systray) as the one shown in the default file. 
```python
screens = [
    Screen(
        bottom=bar.Bar(
            [
                widget.CurrentLayout(),
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Chord(
                    chords_colors={
                        "launch": ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.TextBox("default config", name="default"),
                widget.TextBox("Press &lt;M-r&gt; to spawn", foreground="#d75f5f"),
                # NB Systray is incompatible with Wayland, consider using StatusNotifier instead
                # widget.StatusNotifier(),
                widget.Systray(),
                widget.Clock(format="%Y-%m-%d %a %I:%M %p"),
                widget.QuickExit(),
            ],
            24,
            # border_width=[2, 0, 2, 0],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),
        # You can uncomment this variable if you see that on X11 floating resize/moving is laggy
        # By default we handle these events delayed to already improve performance, however your system might still be struggling
        # This variable is set to None (no cap) by default, but you can set it to 60 to indicate that you limit it to 60 events per second
        # x11_drag_polling_rate = 60,
    ),
]
```

### Version

0.22.1

### Backend

X11 (default)

### Config

```python
Y have divided my config.py file in many modules:
https://github.com/Smaugthur/dotfiles/tree/main/stow/qtile

The main of your interest might be: 

main config file:
https://github.com/Smaugthur/dotfiles/blob/main/stow/qtile/config.py
widget definition:
https://github.com/Smaugthur/dotfiles/blob/main/stow/qtile/settings/widgets.py
screens definition:
https://github.com/Smaugthur/dotfiles/blob/main/stow/qtile/settings/screens.py
```

### Logs

```text
There are no log errors nor warnings.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
I think it's because you're essentially using the same variables in each screen, this won't work. https://github.com/Smaugthur/dotfiles/blob/172376c2e2ca62360c0171ac4c10b48e9e6f3326/stow/qtile/settings/widgets.py#L65-L111 can you change that to a function that returns these widgets instead and then call that function for each screen?

How did you modify the default config exactly? (MVP would be nice)

**Comment by DanielRasho** [comment]
I made the change you suggested, about changing the secondary_widgets variable to a function. And now it works like a charm! Thanks a lot!
