### ISSUE TITLE
TaskList not load icon

### ISSUE THREAD

**Issue by superiums** [qtile/qtile#4501]
### Issue description

TaskList not load icon, except terminator.
pyxdg already installed.

- backend: wayland.
- qtile: 0.23.0

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
widget.TaskList(
                    icon_size = 18,
                  #  icon_theme = "Obsidian",
                  #  theme_mode = "preferred"
                ),
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Which apps? Have you verified that the icons exist on your system?

**Comment by superiums** [comment]
> Which apps? Have you verified that the icons exist on your system?

all apps except one: terminator. i can see only the icon of terminator.
i have my icons, and works in waybar and wofi.

**Comment by elParaguayo** [comment]
OK. Can you try this:
```
>>> from xdg.IconTheme import getIconPath
>>> getIconPath(<app_name>)
```
replacing `<app_name>` with whatever programs you've tried.

**Comment by superiums** [comment]
>>> from xdg.IconTheme import getIconPath
>>> getIconPath('geany')
>>> getIconPath('terminator')
'/usr/share/pixmaps/terminator.png'
>>> getIconPath('firefox')
>>> getIconPath('foot')
>>> getIconPath('mpv')
>>> 

only terminator response, what's the problem ?

**Comment by elParaguayo** [comment]
The problem is that those apps don't have icons installed in your default theme. 
```
>>> from xdg.IconTheme import __get_themes as gc
>>> from xdg.Config import icon_theme
>>> list(gc(icon_theme))
```

**Comment by elParaguayo** [comment]
Also, with that `getIconPath` command from my earlier comment, can you try adding `extensions=["svg"]` and see if you get a different answer.

**Comment by superiums** [comment]
> The problem is that those apps don't have icons installed in your default theme.
> 
> ```
> >>> from xdg.IconTheme import __get_themes as gc
> >>> from xdg.Config import icon_theme
> >>> list(gc(icon_theme))
> ```
> 
> This will show you what icon themes are being searched for the icons.

yes, as you pointed out, it use the `hicolor` theme.
but i've configed gtk and qt to use my own theme. all gtk/qt apps respect the settings.

**Comment by elParaguayo** [comment]
You need to set the `theme_path` for the widget to tell it where to look for icons. It doesn't look for your gtk config.

**Comment by elParaguayo** [comment]
If you want to use the Gtk theme, you can probably import that in your config and pass it to `theme_path`.

Something like:
```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

GTK_THEME = Gtk.Settings.get_default().get_property("gtk-icon-theme-name")

widget_defaults = {"theme_path": GTK_THEME}
```

**Comment by superiums** [comment]
the above lines got the theme currectly in python,
i copied the above config to my sceen.py , but got error log:
```
2023-10-08 18:24:12,143 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 355, value 8388715
2023-10-08 18:24:12,143 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 356, value 8388715
2023-10-08 18:25:13,922 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ConfigureWindow (no minor), code Value (no extension), sequence 421, value 0
2023-10-08 18:25:16,201 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 500, value 10485773

```

**Comment by superiums** [comment]
i've try to set it in TaskList directly:

```python
                widget.TaskList(
                    icon_size = 18,
                    theme_path = "Obsidian"
                    # theme_path = "/usr/share/icons/hicolor"

                ),

```

both absolute path and icon-theme not work.

**Comment by elParaguayo** [comment]
OK. Pining @m-col so he can look at those wayland errors.

**Comment by m-col** [comment]
> the above lines got the theme currectly in python,
> i copied the above config to my sceen.py , but got error log:
> ```
> 2023-10-08 18:24:12,143 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 355, value 8388715
> 2023-10-08 18:24:12,143 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 356, value 8388715
> 2023-10-08 18:25:13,922 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ConfigureWindow (no minor), code Value (no extension), sequence 421, value 0
> 2023-10-08 18:25:16,201 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 500, value 10485773
> 
> ```

I think these arent an issue. I see these but there dont appear to be any noticable side effects. We arent handling xwayland perfectly so its probably no surprise we get messages like this but unless there is an actual disruption to usage then ignore them.

**Comment by elParaguayo** [comment]
Try adding `theme_mode="preferred"` to the widget's config.

**Comment by superiums** [comment]
> Try adding `theme_mode="preferred"` to the widget's config.

yes, it works. Thank you very much.

but i found if there's no icon found, there's no icon displayed there.
could i set a default icon to take up the space ? the tasklist has an icon no matter what is was better than blank.

**Comment by elParaguayo** [comment]
There's no current ability to set a default icon. Someone would need to submit a PR with the changes. I can add to my list but it's going to be low priority for me.

**Comment by elParaguayo** [comment]
> > Try adding `theme_mode="preferred"` to the widget's config.
> 
> yes, it works. Thank you very much.

Just looking at your original post - both `theme_path` and `theme_mode` were there but commented out. Not sure what happened there but, presumably, it was working before those were commented out.

**Comment by superiums** [comment]
thank you very much. 
before i commented it because i found it in doc, think it may be related. but the it not work for dbus user session was not launched, and also i don't know what `mode preferred` stand for.
