### ISSUE TITLE
systray couldn't be load in wayland

### ISSUE THREAD

**Issue by superiums** [qtile/qtile#4504]
### Issue description

systray couldn't be load in wayland

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
widget.Systray()
```

### Logs

```text
2023-10-08 15:05:27,867 WARNING libqtile bar.py:_configure_widget():L358 Widget removed: Systray does not support <libqtile.backend.wayland.core.Core object at 0x7f70ce24bb10>.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
This isn't a bug. Systray is an x11 protocol and is unavailable in Wayland. That is why qtile removes the widget when you're using Wayland.

**Comment by superiums** [comment]
> This isn't a bug. Systray is an x11 protocol and is unavailable in Wayland. That is why qtile removes the widget when you're using Wayland.
> 
> I will tidy up the log message though.

i've checked the doc of qtile and seems it's not mentioned.
then we should document it.

**Comment by elParaguayo** [comment]
It is mentioned:

![20231008_082602](https://github.com/qtile/qtile/assets/946265/19cfedc1-269c-4d3d-8554-96c5ed376874)

Last line: "Only available on the following backends: x11"
