### ISSUE TITLE
Transparent background for widgets

### ISSUE THREAD

**Issue by PhoenixClank** [qtile/qtile#4510]
### Issue description

When the background of a bar is set to a gradient, the area occupied by widgets is filled with a solid color. At the end of the area is a sharp transition to the already-begun gradient.

See example fading from `#ffff00` to `#1f1fff`:
![screenshot](https://github.com/qtile/qtile/assets/30195074/7b7dcb1b-1500-4b45-84f6-ddf7c207258e)

This was not a problem on the previous version of wlroots.

### Version

0.23.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
~That's interesting. Are you saying it used to work before?

I'm surprised that it did because widgets, if they don't specify their own background, copy the bar background. However, that means they copy the fact that there is a gradient, but I'd expect them to apply that gradient to the length of the widget so each widget would go from yellow to blue.~

Ah, hang on. You want the gradient to start after the last widget. Try adding a spacer widget to the end of your widgets list and add the gradient to that.

**Comment by PhoenixClank** [comment]
That's a nice workaround for now but I do want, and originally had, the gradient to start under the first widget.

I thought it worked because the widgets have a drawer for the entire bar area and explicitly specify their own bounds, so the drawer knows which part of the gradient to use.

**Comment by elParaguayo** [comment]
No, it doesn't quite work like that. When widgets draw themselves, they "copy" the bar's background but this means they copy the settings, not the underlying data. So, if you set a gradient in the bar, each widget will draw the same gradient but scaled over the length of the widget.

I've thought about this issue before I figured somebody would run into the issue you're describing at some point!

There's no current way to do it via the bar. The alternative is to have the gradient be part of the wallpaper with a transparent bar but that's a ridiculous idea!

**Comment by PhoenixClank** [comment]
Through fiddling around I have found out that the widgets _do_ have a background gradient that is as large as the bar, but each widget draws only the beginning of it. See here:
![20231011_13h12m57s_grim](https://github.com/qtile/qtile/assets/30195074/8d0a9e27-c35c-453e-8ba5-b97c5e58f444)

Again, I don't remember this being the case until a couple days ago. That is, until then each widget drew the correct part of its background gradient.

**Comment by elParaguayo** [comment]
So here's how (I understand) it works:
- Each widget gets its own `Drawer` object which is the same length of the bar
- Before drawing the widget, the `Drawer` is cleared. This means the existing contents is deleted and the drawer is then filled with a background colour. This colour can be set per widget and, if not, it falls back to the bar's background setting
- This means that, in your case, the widget's drawer would be filled with the gradient for the full length of the bar
- However, when the widget is drawn, the contents always starts at (0, 0) in the drawer, regardless where the widget is located in the bar.
- Drawing the widget copies the relevant part of the widget and places it in the bar's window.
- The result is that I'd expect the gradient to restart for each new widget

I don't believe this is new behaviour as I remember the same issues years ago when I was playing around with custom gradients in the bar.

**Comment by elParaguayo** [comment]
I appreciate this is old but I've added a GradientDecoration in qtile-extras which should address the issue here: https://qtile-extras.readthedocs.io/en/latest/manual/ref/decorations.html#gradientdecoration

If it doesn't work, I'm happy to open an issue in qtile-extras to look at this further.
