### ISSUE TITLE
Mouse-selected Floating Window Not Displaying on Top of Others

### ISSUE THREAD

**Issue by casualtyface** [qtile/qtile#4516]
### Issue description

Description:

I have encountered an issue with Qtile where when i select a floating window with the mouse, it does not come to the forefront and overlay above all other floating windows as it used to do about one or two weeks ago. Unfortunately, due to my busy work schedule during that time, I cannot recall the exact date when this behavior started to occur.

Steps to Reproduce:

1. Open multiple floating windows in Qtile.
    
2. Use the mouse to select a specific floating window.
    
3. Observe that the selected window does not display on top of other floating windows.
    

Expected Behavior:

The mouse-selected floating window should be brought to the front, displaying on top of every other floating window, allowing for seamless interaction with the selected window.

Actual Behavior:

The mouse-selected floating window remains obscured beneath other floating windows.

Configuration Information:

My Qtile config:

[https://github.com/casualtyface/.config/blob/main/config.py](https://github.com/casualtyface/.config/blob/main/config.py)

Logs:

My Qtile.log file:

[https://github.com/casualtyface/.config/blob/main/qtile.log](https://github.com/casualtyface/.config/blob/main/qtile.log)

System Information:

- Operating System: EndeavourOS Linux x86_64
    
Thank you for your attention to this matter. Please let me know if any additional information is required to address this issue.

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by casualtyface** [comment]
> Can you try setting `follow_mouse_focus = False` in your config and check whether clicking on floating windows does then bring them to the front?

It worked but I definitely tried that before and it didn't work. How strange thanks.

**Comment by ramnes** [comment]
Reopening because it seems to me that `follow_mouse_focus` shouldn't change anything, clicking a floating window should always put it on top of the stack. Am I missing something?

**Comment by elParaguayo** [comment]
Correct. This is a bug and is a known issue that we haven't fixed yet.

**Comment by casualtyface** [comment]
well I don't know i closed it because it fixed it. I don't know if this is a bug or not, but anyways now i have another problem its not that important and probably can be solved if i googled it but i will post it here if anyone knows how to fixed it. The issue is that when i drag the window if i let go of the mouse click but not the super key i cant select a new window to drag it will only drag the first window even if it's out of bounds of the window.

**Comment by elParaguayo** [comment]
Drag works on the currently focused window, not what's under the mouse so you need to focus the next window first and then start the drag.
