### ISSUE TITLE
Floating windows re-open in the same Group

### ISSUE THREAD

**Issue by MNandor** [qtile/qtile#4523]
### Issue description

See also https://github.com/qtile/qtile/issues/1232 as it reports the same behavior - though it had been fixed at the time all the way until 0.22.0 inclusive.

Replicate:
- Install launch Albert launcher
- Open it with one a hotkey on Qtile group 1
- Close Albert (either with hotkey or by launching a program)
- Switch to Qtile group 2
- Open Albert again with hotkey

Expectation: Albert should launch on group 2 now.

Reality: Albert launches on group 1 (and on a single-monitor setup, this means it's not visible). Also, Albert launches underneath tiling windows despite being floating itself.

The original issue was resolved with https://github.com/qtile/qtile/pull/2766.

The most recent change to the code around that part was in `handle_UnmapNotify` in `core.py`.

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. I'll take a look at this when I can.

**Comment by amerlyq** [comment]
Same issue observed with `copyq` for me.
Very irritating.
Is there any fast workaround I can apply to my sources of `qtile` until official fix is ready?

**Comment by ava5627** [comment]
I've been using
```python

@hook.subscribe.client_new
def fix_group(window):
    if "copyq" in window.get_wm_class(): 
        group = qtile.current_group
        if window.group != group:
            window.togroup(group.name)

```

**Comment by MNandor** [comment]
> I've been using
> 
> ```python
> @hook.subscribe.client_new
> def fix_group(window):
>     if "copyq" in window.get_wm_class(): 
>         group = qtile.current_group
>         if window.group != group:
>             window.togroup(group.name)
> ```

Works really well for me, thank you!

As an added tip for those who might need it: if you don't know a window's wm_class, you can always run the command `xprop` and click on the window to find it.

**Comment by Saco93** [comment]
> I've been using
> 
> ```python
> @hook.subscribe.client_new
> def fix_group(window):
>     if "copyq" in window.get_wm_class(): 
>         group = qtile.current_group
>         if window.group != group:
>             window.togroup(group.name)
> ```

I put this snippet into my config, but got the following error when the hook is triggered:
```log
2023-12-07 22:09:00,025 ERROR libqtile hook.py:fire():L903 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 901, in fire
    i(*args, **kwargs)
  File "/home/saco/.config/qtile/config.py", line 425, in fix_group
    group = qtile.current_group
            ^^^^^
NameError: name 'qtile' is not defined
```

**Comment by MoonlyVibes** [comment]
Fix that handles multiple apps
```python
fix_group_apps_wm_class = ["brave-browser", "copyq"]

@hook.subscribe.client_new
def fix_group(window):
    if any(app in window.get_wm_class() for app in fix_group_apps_wm_class):
        group = qtile.current_group
        if window.group != group:
            window.togroup(group.name)
```
