### ISSUE TITLE
Check if it's possible to remove (e)logind as suspend/resume hooks' dependency.0.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4526]
### Issue description

Currently the `suspend` (and possibly `resume`, but I haven't checked) hook requires `logind/elogind` to be installed and runnine to work. If it's not enabled, there is a warning in the log (see Logs section below), also the hooks are not working - which is expected.

Please check if it would be possible to remove this dependency. It would be a great improvement for us, non-systemd folks - elogind is the last part of systemd (ported to standalone solution) that I have to use to have everything working and I would gladly get rid of it.

Basing on the short talk on Discord, it seems that dbus only should be sufficient for this - I'm leaving it here as a hint.

Thanks in advance!

### Version

0.23.0

### Backend

Wayland (experimental)

### Logs

```text
2023-10-17 01:07:56,520 WARNING libqtile sleep.py:_start():L106 Could not find logind service. Suspend and resume hooks will be unavailable.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ftpd** [comment]
Note: for the suspend functionality instead of elogind I can use https://sourceforge.net/projects/acpid2/. I don't know if it's relevant.

**Comment by elParaguayo** [comment]
My dbus question was because I know nothing about elogind but just saw that it has the same dbus interface as systemd/logind.

If you don't want to use either logind or elogind then can you let me know how those systems manage suspend/resume events. 

The difficulty here is that I will have no way to test any solution that we try to implement.

**Comment by ftpd** [comment]
It seems both are reacting to ACPI events: https://docs.voidlinux.org/config/power-management.html

**Comment by elParaguayo** [comment]
Posted a comment in Discord. I think that, rather than devising a custom ACPI solution, we could allow for custom hooks which you could then fire from a script that works with ACPI.

**Comment by ftpd** [comment]
After discussing the matter on Discord, I'm closing this issue as 'no longer relevant'. The idea I had was qtile being able to 'automagically' detect what provides suspend/resume events, but it's not going to happen.
