### ISSUE TITLE
Tasklist don't show all windows

### ISSUE THREAD

**Issue by Tokariew** [qtile/qtile#4528]
### Issue description

Add in config Tasklist window, open some floating subwindow, for example in calibre edit metadata, and newly spawned window is not show in TaskList widget, but when focused is showed in WindowName, and is showed in WindowTab widget.
Found out when checking #4488

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
Default config with switched WindowName to TaskList.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Tokariew** [comment]
after more digging, check in this commit made  some floating window to not show:
https://github.com/qtile/qtile/commit/0de37b01b

**Comment by elParaguayo** [comment]
The change to TaskList was intentional. I'm not sure we'd want the same change to WindowName.

What behaviour would you like to see?

**Comment by Tokariew** [comment]
sorry for late reply.
I was reading the docs, and from it i got that the only diffrence beetween tasklist and windowname widget is that one is interactive, and have markup options
