### ISSUE TITLE
Qt based polkit agents (password prompts) get stuck behind other windows

### ISSUE THREAD

**Issue by yobleck** [qtile/qtile#4529]
### Issue description

All polkit agents listed from https://wiki.archlinux.org/title/Polkit

Both [lxqt-policykit](https://archlinux.org/packages/?name=lxqt-policykit) and [polkit-dumb-agent-git](https://aur.archlinux.org/packages/polkit-dumb-agent-git/) get stuck behind other windows

Steps to reproduce:
1. put `qtile.spawn("/path/to/polkit-dumb-agent") ` in the `@hook.subscribe.startup_once` section of the config file
2. start qtile
3. open a gui text editor and open a file that requires root permissions to edit
4. make an edit and save. a pop up window should prompt for the root password
5. close the text editor and redo steps 3 and 4. the password prompt should be stuck behind the text editor window (any layout)
6. restart qtile. you should briefly see the border around where the floating dialog window was.

I believe this is because the window isn't actually killed after you type in the password. The window id can still be queried with `xprop -id $ID` even though it is completely non interactive and does not show up in `qtile.window()` or `qtile.internal_window()`. If you run `xdotool windowkill $ID` it kills the polkit agent background process which complains about the X server dying even though it hasn't. I'm not very familiar with programming Qt in C/CPP but the polkit-agent-dumb and lxqt-policykit source code contains the line `app.setQuitOnLastWindowClosed(false);` which might be the root cause of why the windows don't fully disappear.

I've replicated this bug with two different agents listed above and confirmed no issue with the gtk3 based [mate-polkit](https://archlinux.org/packages/?name=mate-polkit)

Attempted fixes:
1. using `@hook.subscribe.client_managed` and `client_new` to add the functions `window.kept_above = True`, `window.move_to_top(force=True)`, `window.bring_to_front()`, `window.move_up(force=True)` none of which worked.
2. using `mouse = [Click([mod], "Button2", lazy.window.bring_to_front())]`. This works but assumes that part of the floating dialog window is visible to click on
3. adding the line `window.floating = False` to `@hook.subscribe.client_managed`. This works but causes a jarring layout rearrangement.
**QUICK FIX**
4. Switch to a non Qt based polkit agent like the mate agent (the [xfce-polkit](https://aur.archlinux.org/packages/xfce-polkit/) and [polkit-gnome](https://archlinux.org/packages/?name=polkit-gnome) agent are also gtk based and should be fine but I didn't test them. The [ts-polkitagent](https://aur.archlinux.org/packages/ts-polkitagent/) and the [polkit-kde-agent](https://archlinux.org/packages/?name=polkit-kde-agent) are probably affected since they are Qt based but I didn't test them).

A potential way to deal with this in qtile, is to check for windows that are being remapped or unhidden (or however Qt handles that) and applying all the appropriate adjustments to the window same as when it was created so that properties like `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG` and `_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_MODAL` are respected. Or there might be a way for qtile to keep track of WID's that are still in use even if there is no apparent window for it and save the z layer stacking settings for that window.

minor side note:
I've had similar issues with a custom qtile widget I made for myself that uses a persistent popup window from qtile's internal window class. I ended up rewriting that widget to just destroy the window every time it's closed and redraw all the saved data the next time it opens so that it's always on top of other windows. window.bring_to_front() etc didn't work in that case either.

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
n/a
```

### Logs

```text
n/a
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by roverton** [comment]
I am also experiencing this issue but with the kde polkit agent as conjectured by yobleck.

Each time it happens in my testing so far, I also receive this error in the qtile.log:
```
2023-10-17 21:37:53,772 ERROR libqtile core.py:_xpoll():L370 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 322, in _xpoll
    event = self.conn.conn.poll_for_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 579, in wrapper
    return f(*args)
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 620, in poll_for_event
    return self.hoist_event(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 694, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 657, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
```

I was also trying to write a function on the client_new hook that would catch the window and bring_to_front, which also failed for me. I do have a different function that enumerates all of the windows in the current group, checks if they are floating, and brings them to the front that I bound to a Key and that actually does work.

Once I removed all of the code from my config that I could find that might be generating the above error, I came here trying to find out if there was an information about any of this.

Hope this helps some.

**Comment by roverton** [comment]
Huh... turns out I didn't actually have that in my config.

Strange result though. Putting floats_kept_above = true into my config results in all of the exact same behavior (no change), but now I don't receive the same error in the qtille.log. I don't see any new entries in the qtile.log when testing the polkit windows.

**Comment by roverton** [comment]
After more testing, I don't see that error message any more regardless of that setting. It was really consistent when I was doing the testing from my original comment. Maybe just coincidence, but that's pretty odd with how consistent it was then.

**Comment by yobleck** [comment]
With some more testing I discovered that 

```
@hook.subscribe.client_focus
def client_focus_stuff(window):
    if window.window.get_wm_class()[0] == "lxqt-policykit-agent":  # or any other agent
        window.bring_to_front()
```

does work. According to the logs it fires twice which might be why.

This is easier than any of the temporary fixes I suggested above. Tested with lxqt-policykit-agent and polkit-agent-dumb.

1. Also noticed that `@hook.subscribe.client_killed` if firing even though the window's resources are still accessible via `xprop`. This might be confusing qtile as to whether or not the window is actually dead.

2. Also when running xprop on the root window with and without the polkit window active, the position of the window id in the window list doesn't update for the property `_NET_CLIENT_LIST_STACKING(WINDOW)` but does update for `_NET_CLIENT_LIST(WINDOW)`

example of xprop outputs where `0x260002d` is the wid for the polkit window:

```
with polkit window open ** added for emphasis
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x40000b, 0x80000a, 0xe00003, **0x260002d**, 0x3000006, 0x2a00003
_NET_CLIENT_LIST(WINDOW): window id # 0x40000b, 0x80000a, 0xe00003, 0x2a00003, 0x3000006, **0x260002d**
without
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x40000b, 0x80000a, 0xe00003, 0x3000006, 0x2a00003
_NET_CLIENT_LIST(WINDOW): window id # 0x40000b, 0x80000a, 0xe00003, 0x2a00003, 0x3000006
```

I'm don't know if this is helpful or if I'm just chasing ghosts.

**Comment by yobleck** [comment]
Small update. With git bisect I've confirmed that the commit that caused this issue was 5872845307df93a56fe2fa61c9049ef25a44ad00 `x11: Add z-layer stacking`.
but this is a very large commit so I'm not sure where to start looking.

**Comment by elParaguayo** [comment]
Is the GUI text editor also a floating window or is it tiled?

**Comment by elParaguayo** [comment]
Can you also check if #4417 helps at all here.

**Comment by yobleck** [comment]
@elParaguayo the GUI text editor is tiling (I've only tested the columns and max layouts).

xprop info for the polkit window:

```
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 1, 1
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 95112
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL, _NET_WM_STATE_ABOVE
WM_TRANSIENT_FOR(WINDOW): window id # 0x1400008
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Enter the root password"
_NET_WM_NAME(UTF8_STRING) = "Enter the root password"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1400008
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x1400008
WM_CLIENT_MACHINE(STRING) = "yobleck-pc"
_NET_WM_PID(CARDINAL) = 1677
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20971527
WM_CLASS(STRING) = "polkit-dumb-agent", "polkit-dumb-agent"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST, _NET_WM_CONTEXT_HELP
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 809, 614
		user specified size: 922 by 133
		program specified minimum size: 922 by 133
		program specified maximum size: 32767 by 133
		window gravity: Static
```

Yes #4417 does appear to fix the issue. I didn't make the connection between `WM_TRANSIENT_FOR` and when I searched for layering issues.

**Comment by elParaguayo** [comment]
4417 now merged.
