### ISSUE TITLE
QTILE remembers last session , how to turn it off

### ISSUE THREAD

**Issue by mu-us61** [qtile/qtile#4530]
### Issue description

Group("2", spawn="code", matches=[Match(wm_class=["Code"])]),

so I have this code to autostart vscode , but in my session I open a few vs code instances too lets say about 5 total in different groups, so after shutdown and open my computer again , in my group 2 there always spawns 5 of them from last session , how to turn it off this , all I want is only 1 vs code at start just like I setup

steps to produce ;
1- open  a few instances of vscode 
2- restart the PC
3- start vscode

now instead of 1 vscode , gonna start a few from the last session , I check google, it says qtile has no session but some how it happens

I use debian 12 KDE installation as main , installed Qtile after

### Version

0.23

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Qtile doesn't store any information about sessions so I assume vscode remembers the last session.

**Comment by mu-us61** [comment]
> Qtile doesn't store any information about sessions so I assume vscode remembers the last session.

thanks I check the vscode setting and did restoreWindows to None
