### ISSUE TITLE
PWA app from browser can't be opened

### ISSUE THREAD

**Issue by naranyala** [qtile/qtile#4533]
### Issue description

In other tiling-wm (awesome), PWA apps from the browser work the same as regular apps, when switching to QTILE the PWA app doesn't work.

For example try installing Twitter/X to a PWA with a chromium based browser, my case is the Edge/Brave browser.

The installation was successful, but when I try to open it from the launcher (rofi) it just shows a new browser tab without any links, and the default behavior of PWA is not to create a new tab, just open the app.

### Version

v0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ramnes** [comment]
Can you try with Chrome?
