### ISSUE TITLE
test failures in opensuse open build service

### ISSUE THREAD

**Issue by uncomfyhalomacro** [qtile/qtile#4538]
Hello there. I am a packager for qtile at openSUSE. 

I received some weird test failures in opensuse build service for packaging qtile.

This is not a full test suite log but it's too many to count so I just leave a part of it here: 

```
[   24s] test/test_bar.py::test_completion PASSED                                 [  0%]
[   46s] test/test_bar.py::test_draw[1-x11-GBConfig] ERROR                        [  0%]
[   68s] test/test_bar.py::test_prompt[1-x11-GBConfig] ERROR                      [  0%]
[   89s] test/test_bar.py::test_event[1-x11-GBConfig] ERROR                       [  0%]
[  110s] test/test_bar.py::test_textbox[1-x11-GBConfig] ERROR                     [  0%]
[  131s] test/test_bar.py::test_textbox_errors[1-x11-GBConfig] ERROR              [  0%]
[  153s] test/test_bar.py::test_groupbox_button_press[1-x11-GBConfig] ERROR       [  0%]
[  154s] test/test_bar.py::test_geometry[1-x11-GeomConf] PASSED                   [  0%]
[  154s] test/test_bar.py::test_resize[1-x11-GeomConf] PASSED                     [  0%]
[  155s] test/test_bar.py::test_basic[1-x11] PASSED                               [  1%]
[  155s] test/test_bar.py::test_singlespacer[1-x11] PASSED                        [  1%]
[  155s] test/test_bar.py::test_nospacer[1-x11] PASSED                            [  1%]
[  155s] test/test_bar.py::test_consecutive_spacer[1-x11] PASSED                  [  1%]
[  176s] test/test_bar.py::test_configure_broken_widgets[1-x11] FAILED            [  1%]
[  178s] test/test_bar.py::test_bar_hide_show_with_margin[1-x11] PASSED           [  1%]
[  178s] test/test_bar.py::test_bar_border_horizontal[1-x11] PASSED               [  1%]
[  178s] test/test_bar.py::test_bar_border_vertical[1-x11] PASSED                 [  1%]
[  178s] test/test_bar.py::test_unsupported_widget[1-x11] PASSED                  [  1%]
[  200s] test/test_command.py::test_layout_filter[1-x11-CallConfig] FAILED        [  1%]
[  201s] test/test_command.py::test_cmd_commands[1-x11-ServerConfig] PASSED       [  2%]
[  222s] test/test_command.py::test_cmd_eval_namespace[1-x11-ServerConfig] ERROR  [  2%]
[  244s] test/test_command.py::test_call_unknown[1-x11-ServerConfig] ERROR        [  2%]
[  244s] test/test_command.py::test_items_qtile[x11-ServerConfig-2] PASSED        [  2%]
[  265s] test/test_command.py::test_select_qtile[x11-ServerConfig-2] ERROR        [  2%]
[  267s] test/test_command.py::test_items_group[1-x11-ServerConfig] PASSED        [  2%]
[  289s] test/test_command.py::test_select_group[x11-ServerConfig-2] ERROR        [  2%]
[  311s] test/test_command.py::test_items_screen[1-x11-ServerConfig] ERROR        [  2%]
[  312s] test/test_command.py::test_select_screen[1-x11-ServerConfig] PASSED      [  2%]
[  312s] test/test_command.py::test_items_bar[1-x11-ServerConfig] PASSED          [  2%]
[  334s] test/test_command.py::test_select_bar[x11-ServerConfig-2] ERROR          [  3%]
[  334s] test/test_command.py::test_items_layout[1-x11-ServerConfig] PASSED       [  3%]
[  335s] test/test_command.py::test_select_layout[1-x11-ServerConfig] PASSED      [  3%]
[  356s] test/test_command.py::test_items_window[x11-ServerConfig-2] ERROR        [  3%]
[  358s] test/test_command.py::test_select_window[x11-ServerConfig-2] PASSED      [  3%]
[  379s] test/test_command.py::test_items_widget[1-x11-ServerConfig] ERROR        [  3%]
[  401s] test/test_command.py::test_select_widget[1-x11-ServerConfig] ERROR       [  3%]
[  401s] test/test_command.py::test_core_node[1-x11] PASSED                       [  3%]
[  401s] test/test_command.py::test_lazy_arguments[1-x11] PASSED                  [  3%]
[  422s] test/test_command.py::test_decorators_manager_call[x11-ServerConfig-2] ERROR [  3%]
[  444s] test/test_fakescreen.py::test_basic[1-x11-FakeScreenConfig] ERROR        [  4%]
[  465s] test/test_fakescreen.py::test_gaps[1-x11-FakeScreenConfig] ERROR         [  4%]
[  487s] test/test_fakescreen.py::test_maximize_with_move_to_screen[1-x11-FakeScreenConfig] ERROR [  4%]
[  508s] test/test_fakescreen.py::test_float_first_on_second_screen[1-x11-FakeScreenConfig] ERROR [  4%]
[  529s] test/test_fakescreen.py::test_float_change_screens[1-x11-FakeScreenConfig] ERROR [  4%]
[  551s] test/test_fakescreen.py::test_float_outside_edges[1-x11-FakeScreenConfig] ERROR [  4%]
[  572s] test/test_fakescreen.py::test_hammer_tile[1-x11-FakeScreenConfig] ERROR  [  4%]
[  593s] test/test_fakescreen.py::test_hammer_ratio_tile[1-x11-FakeScreenConfig] ERROR [  4%]
[  615s] test/test_fakescreen.py::test_ratio_to_fourth_screen[1-x11-FakeScreenConfig] ERROR [  4%]
[  616s] test/test_floating.py::test_maximize[1-x11-FakeScreenConfig] PASSED      [  4%]
[  618s] test/test_floating.py::test_fullscreen[1-x11-FakeScreenConfig] PASSED    [  5%]
[  620s] test/test_group.py::test_window_order[1-x11-GroupConfig] PASSED          [  5%]
[  622s] test/test_group.py::test_focus_by_index[1-x11-GroupConfig] PASSED        [  5%]
```

At first, it was an out of memory issue so i have to increase the physical memory to 24GB (16GB seems not enough).

Not sure if this is related to the VM environment of Open Build Service so I have it disabled for now. Qtile runs successfully when installed so it's likely the VM.

**Comment by ramnes** [comment]
Hi @uncomfyhalomacro,

That would probably help if you'd share the actual errors.

If almost all tests are erroring then I guess something is wrong with your setup. Did OpenSUSE acknowledge our latest release and updated xcffib and cairocffi accordingly?

If not, please have a look at the changelog and update your packages accordingly.

**Comment by ramnes** [comment]
Also @uncomfyhalomacro, it seems that Qtile does not run correctly for some of your users, see #4543

**Comment by uncomfyhalomacro** [comment]
I will come back to this in a week.

**Comment by uncomfyhalomacro** [comment]
In the meantime, users can have https://build.opensuse.org/package/show/home:uncomfyhalomacro:branches:home:uncomfyhalomacro:branches:X11:windowmanagers:disabled_test_for_users_to_use/qtile

I disabled the tests for this one. I will come back with the one with enabled tests later with all the logs. ☺️

**Comment by uncomfyhalomacro** [comment]
First set of failures seen in this build log (the one where tests are enabled) https://build.opensuse.org/package/live_build_log/home:uncomfyhalomacro:branches:X11:windowmanagers/qtile/openSUSE_Tumbleweed/x86_64

Let's wait for it to complete in a few hours 🥲

**Comment by uncomfyhalomacro** [comment]
@ramnes here is the full build log 
[qtile_failed_test_log.txt](https://github.com/qtile/qtile/files/13195091/qtile_failed_test_log.txt)

**Comment by ramnes** [comment]
Thanks. The main Python package versions look right, so this is probably not the issue.

Does it fail as well on an older version of Xorg / Xvfb, such as 21.1.8?

**Comment by JoelBierman** [comment]
I have noticed that if I try to run qtile in an openSUSE virtual machine, it will only work if I install the dependencies listed on the qtile installation page first through pip, then install qtile itself with zypper. This seems less than ideal since having system-wide packages installed through two different package managers might cause issues later on. For some reason or another, the official openSUSE qtile package does not seem to install the dependencies properly.

**Comment by uncomfyhalomacro** [comment]
> I have noticed that if I try to run qtile in an openSUSE virtual machine, it will only work if I install the dependencies listed on the qtile installation page first through pip, then install qtile itself with zypper. This seems less than ideal since having system-wide packages installed through two different package managers might cause issues later on. For some reason or another, the official openSUSE qtile package does not seem to install the dependencies properly. And even then, qtile (wayland) does not show up as an option in the login menu and running `qtile start -b wayland` results in a segmentation fault (core dumped).

i finally fixed it. i did the wrong thing when building the package. @JoelBierman 

@ramnes I also polished the build and tests finally have the following build failure log file: 
[final-qtile-log.log](https://github.com/qtile/qtile/files/13199550/final-qtile-log.log)

**Comment by uncomfyhalomacro** [comment]
> Thanks. The main Python package versions look right, so this is probably not the issue.
> 
> Does it fail as well on an older version of Xorg / Xvfb, such as 21.1.8?

xorg-x11-server-Xvfb-21.1.9-1.1  is the latest version. i will check if that 21.1.8 is available

**Comment by uncomfyhalomacro** [comment]
> If almost all tests are erroring then I guess something is wrong with your setup. Has OpenSUSE acknowledged our latest release and updated xcffib and cairocffi accordingly?

Yep. I am the one updating those :)

**Comment by uncomfyhalomacro** [comment]
Closed as finally realized it needs importlib
