### ISSUE TITLE
External panels cannot set focus

### ISSUE THREAD

**Issue by eigengrau** [qtile/qtile#455]
I tried out some external panels today, and I noticed that I cannot use these to switch focus to another window. Whenever I click on a window entry in the panel (I tried it with fbpanel, bmpanel2 and tint2), the focus seems to just jump back to the window that was in focus before that.

Switching focus using `wmctrl` works for me, though.

This is with the current HEAD, 5dc2794.

**Comment by mattheww** [comment]
The message is sent to the root window, but `handle_ClientMessage` is called on the window identified in the event message.

Simply adding the following two lines to the end of `_Window.handle_ClientMessage` makes window activation work for me:

        elif atoms["_NET_ACTIVE_WINDOW"] == opcode:
            self.group.focus(self, False)

(an easy way to test is to use `xdotool windowactivate`.)

**Comment by MarSoft** [comment]
Similar problem for me: cannot activate Upwork's window with xdotool - it switches to the right desktop but fails to bring the window up. But wmctrl works.

**Comment by flacjacket** [comment]
This has been reported fixed by #897, feel free to reopen if this is still a problem.
