### ISSUE TITLE
Dialog window pops-up behind main window in pcmanfm-qt

### ISSUE THREAD

**Issue by pepper-jelly** [qtile/qtile#4555]
### Issue description

In pcmanfm-qt Rclick --> Properties opens dialog behind main window. Dragging with Super+Lmouse brings it on top.

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
floating_layout = layout.Floating(
    float_rules=[
        *layout.Floating.default_float_rules,
        Match(wm_class="pcmanfm-qt"),
    ]
)
```

### Logs

```text
empty
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Does #4417 fix this?

**Comment by pepper-jelly** [comment]
yes, applied to release as https://github.com/qtile/qtile/pull/4417.patch

**Comment by elParaguayo** [comment]
#4417 merged.
