### ISSUE TITLE
Tests occasionally fail with AssertionError: couldn't connect to xvfb

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#4573]
### Issue description

I am maintaining an RPM Qtile package for Fedora and running tests while building it. Basically, I am using this command:

```
/usr/bin/pytest -vv --backend x11
```

Sometimes the tests fail with `AssertionError: couldn't connect to xvfb`. I usually just resubmit the build and then it succeeds, so it doesn't look like I am doing something wrong.

```
=========================== short test summary info ============================
ERROR test/test_command.py::test_items_window[x11-ServerConfig-2] - Assertion...
ERROR test/test_command.py::test_select_window[x11-ServerConfig-2] - Assertio...
====== 977 passed, 18 skipped, 30 warnings, 2 errors in 794.65s (0:13:14) ======
```

Is this a known bug, please?
A full log can be seen here https://download.copr.fedorainfracloud.org/results/frostyx/qtile-f39/fedora-rawhide-x86_64/06625185-qtile/builder-live.log.gz

### Version

0.23.0

### Backend

X11 (default)

### Logs

```text
==================================== ERRORS ====================================
___________ ERROR at setup of test_items_window[x11-ServerConfig-2] ____________

request = <SubRequest 'xephyr' for <Function test_items_window[x11-ServerConfig-2]>>
outputs = 2

    @pytest.fixture(scope="session")
    def xephyr(request, outputs):
        if "x11" not in request.config.option.backend:
            yield
            return
    
        from test.backend.x11.conftest import x11_environment
    
        kwargs = getattr(request, "param", {})
    
>       with x11_environment(outputs, **kwargs) as x:

test/conftest.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.12/contextlib.py:137: in __enter__
    return next(self.gen)
test/backend/x11/conftest.py:150: in x11_environment
    with xvfb():
/usr/lib64/python3.12/contextlib.py:137: in __enter__
    return next(self.gen)
test/backend/x11/conftest.py:37: in xvfb
    with xcffib.testing.XvfbTest():
/usr/lib/python3.12/site-packages/xcffib/testing.py:117: in __enter__
    self.setUp()
/usr/lib/python3.12/site-packages/xcffib/testing.py:84: in setUp
    self.conn = self._connect_to_xvfb()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xcffib.testing.XvfbTest object at 0x7f228798ac60>

    def _connect_to_xvfb(self):
        # sometimes it takes a while for Xvfb to start
        for _ in range(100):
            try:
                conn = Connection(os.environ['DISPLAY'])
                conn.invalid()
                return conn
            except ConnectionException:
                time.sleep(0.2)
>       assert False, "couldn't connect to xvfb"
E       AssertionError: couldn't connect to xvfb
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
Wouldn't surprise me if there is a race condition somewhere in our test suite. Would also explain why getting parallel builds to work is so difficult #1634. Wouldn't surprise me if we had this failure a couple of times in the CI here too. How often does it happen for you?

**Comment by FrostyX** [comment]
In the last couple of days, I did 8 builds and 3 of them failed like this. I don't know how accurate it is though. If it would be helpful for you if I for example submit 100 builds and see what happens, so you can decide whether it is worth debugging or not, I can do that.

**Comment by FrostyX** [comment]
I am trying to build the package in Koji (the official Fedora build system)
https://koji.fedoraproject.org/koji/taskinfo?taskID=109675637
and it works fine for x86_64 and aarch64 but i686 seems to be failing every time with the `AssertionError: couldn't connect to xvfb` error - https://kojipkgs.fedoraproject.org//work/tasks/5771/109675771/build.log

**Comment by carlwgeorge** [comment]
Have you seen [this accepted change proposal](https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval)?  You can add `ExcludeArch: %{ix86}` to the spec file to just skip the i686 build completely.  It doesn't help with whatever the underlying problem is, but it may help you avoid running into it as often.
