### ISSUE TITLE
[Arch Wayland Nvidia] EGL Bad Parameter error - Invalid format

### ISSUE THREAD

**Issue by ErgoPraxis** [qtile/qtile#4574]
### Issue description

I tried to run qtile on a fresh install of arch linux with wayland and the proprietary nvidia driver. 
`qtile start -b wayland`
This produces the following EGL error captured in ~/.local/share/qtile/qtile.log
```
2023-11-12 21:33:09,183 ERROR wlroots log.py:log_func_callback():L15 [EGL] command: eglQueryDmaBufModifiersEXT, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In eglQueryDmaBufModifiersEXT: Invalid format"
2023-11-12 21:33:09,183 ERROR wlroots log.py:log_func_callback():L15 [render/egl.c:841] Failed to query dmabuf number of modifiers
2023-11-12 21:33:09,183 ERROR wlroots log.py:log_func_callback():L15 [EGL] command: eglQueryDmaBufModifiersEXT, error: EGL_BAD_PARAMETER (0x300c), message: "EGL_BAD_PARAMETER error: In eglQueryDmaBufModifiersEXT: Invalid format"
2023-11-12 21:33:09,183 ERROR wlroots log.py:log_func_callback():L15 [render/egl.c:841] Failed to query dmabuf number of modifiers
```
Qtile does run, but in a broken state (disclaimer: this is my first time running qtile, so I might not recognize a 'normal' state).
* The menu bar / task bar is visible at the bottom of screen, but it is filled with blank symbols indicative of a missing font package or something. This might not be related to the EGL error.
* Qtile does not run a terminal emulator when pressing super+enter. I have the foot emulator running for wayland, so it should work.

My conclusion from the above two points is qtile is not running normally due to the EGL error.

Everything is installed with `pacman -S ...`
package versions:
```
[root@praxis ergo]# pacman -Q | grep -e 'wlroots' -e 'wayland' -e 'nvidia' -e 'qtile'
egl-wayland 2:1.1.13-1
nvidia 545.29.02-4
nvidia-utils 545.29.02-2
python-pywayland 0.4.17-1
python-pywlroots 0.16.6-1
qtile 0.23.0-1
wayland 1.22.0-1
wlroots 0.16.2-2
xorg-xwayland 23.2.2-1
```

The nvidia driver is configured per the arch installation guide.
```
[root@praxis ergo]# cat /etc/modprobe.d/nvidia_drm.conf 
options nvidia_drm modeset=1 fbdev=1
```
and 
```
[root@praxis ergo]# cat /etc/mkinitcpio.conf | grep -e '^MODULE' -e '^HOOKS'
MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
HOOKS=(base udev autodetect modconf keyboard keymap consolefont block filesystems fsck)
```
NOTE: the kms is removed from the hooks section.

I use `timeout 30s qtile start -b wayland -l=DEBUG`  for the details log at end of issue; so the `Qtile will now terminate` message is due to the timeout command and not related to the error. Attached the details debug log as file.
[qtile.log](https://github.com/qtile/qtile/files/13330378/qtile.log)

let me know if this is a wlroots issue and I will open an issue over there. Since the qtile log shows invalid format, I figured it's possible qtile is passing bad parameters to the wlroots library.

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
Default config not touched.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ErgoPraxis** [comment]
let me know if this is a wlroots issue and I will open an issue over there. Since the qtile log shows invalid format, I figured it's possible qtile is passing bad parameters to the wlroots library.

**Comment by jwijenbergh** [comment]
I'm not sure what the current status is of nvidia + wlroots but in the past it has not been a good duo. That being said, could you try other compositors to see how they behave? E.g. hyprland/dwl/sway.

> The menu bar / task bar is visible at the bottom of screen, but it is filled with blank symbols indicative of a missing font package or something. This might not be related to the EGL error.

Which config is this?

> Qtile does not run a terminal emulator when pressing super+enter. I have the foot emulator running for wayland, so it should work.

Try another terminal, if that runs execute foot from there and see if it works or which error it gives

Also does qtile start when already in a session (nested session)? This is a good way to debug things

**Comment by ErgoPraxis** [comment]
Interestingly. I just installed sway. It was the only thing I did. 

Then, I immediately tried running qtile again (without attempting to run sway).

Qtile runs: 
* The bar at bottom now correctly displays readable words showing the 1 through 9 workspaces and the other text to the bottom right.
* When pressing super+enter, the foot terminal now opens.

It appears the qtile package on pacman doesn't install all dependencies. It was probably the font package the sway package had me select when I installed it. Perhaps this was the reason foot wasn't running either. 

The EGL error still exists; I will play around with it and sway this week (hopefully after work today).

**Comment by ErgoPraxis** [comment]
I tried running sway and it works (when run in --unsupported-gpu mode). 

However the first message was that nvidia drivers are not supported and do not submit issues.

.... ok. I see what you mean about wlroots and the issue ... it looks like everyone is pretty resource constrained at the moment and given what you said about the difficulty in debugging proprietary stuff. 

Feel free to close this issue. Unless I come across anymore results while pursuing other things, I'm going to assume the egl error isn't critical. Hopefully this issue will help others find the current state of things in their pursuits.

**Comment by ErgoPraxis** [comment]
Oh, also, The same precise error appears with sway. So, yep. It appears to be a common library issue. Probably wlroots x nvidia driver.

**Comment by jwijenbergh** [comment]
I am closing this as it doesn't seem like a qtile issue. Did the font thing also happen with the default config? If so then maybe the aur package needs to be changed

**Comment by ErgoPraxis** [comment]
Qtile was using its default config.

* Arch was installed.
* Systemd related things configed to get networking going (resolved, networkd)
* Nvidia proprietarty driver installed and configed.
* Qtile installed.

Everything was installed from the officially maintained repos from a frsh install of arch using pacman. No AUR packages have been involved yet. No attempts to configure qtile yet.

**Comment by jwijenbergh** [comment]
Ah sorry I forgot it's an official arch package, maybe the qtile package needs font. Pinging package maintainer @dvzrv
