### ISSUE TITLE
Parameter of groupbox widget missing from docs

### ISSUE THREAD

**Issue by Jan-V2** [qtile/qtile#4584]
### Issue description

There is minor mistake in the current version of the documentation
In the builtin widgets section, the groupbox widget is missing the disable_drag parameter.
https://docs.qtile.org/en/latest/manual/ref/widgets.html#agroupbox

It is however in the source code on the same website, which is where i found it.
https://docs.qtile.org/en/latest/_modules/libqtile/widget/groupbox.html
I've tested it and the parameter, does work on my machine, running qtile 0.23.0.

I tried changing it myself, i think that section is generated somewhere within the automated build system for the website.

### Version

0.23.0 

### Backend

X11 (default)

### Config

```python
n/a
```

### Logs

```text
n/a
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
You're looking at the wrong widget. You've linked `AGroupBox` which is a widget that just shows the current group.

Looking at https://docs.qtile.org/en/latest/manual/ref/widgets.html#groupbox and you'll see `disable_drag` is there.
