### ISSUE TITLE
Systray widget fails to show anything

### ISSUE THREAD

**Issue by alethiophile** [qtile/qtile#4588]
### Issue description

The systray widget is failing to show anything. I set it up and, despite running several systray apps, nothing appears on the bar.

My config, in relevant part:

```
screens = [
    Screen(
        top=bar.Bar(
            [
                widget.CurrentLayout(),
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Chord(
                    chords_colors={
                        'launch': ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.Systray(icon_size=20),
                widget.Clock(format='%Y-%m-%d %a %I:%M %p'),
            ],
            24,
        ),
    ),
```

I've tried without the `icon_size` parameter just to check; the same problem happens. The widgets on both sides display just fine.

Nothing relevant appears in the logs. One note is that I'm running Qtile within KDE Plasma, in place of their KWin WM. Plasma provides its own system tray as part of its panel implementation, but I've removed the panels that hold it.

### Version

0.23.1.dev80+g55126980

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks for the report. I'm not entirely sure how to go about fixing this as I'm not using Plasma and the tray works (well enough) as it is. My suspicion is therefore that Plasma is still advertising a system tray even if you've removed the panel. 

If you start qtile outside of Plasma, does the tray start working?

**Comment by alethiophile** [comment]
I've just run Qtile outside of Plasma and the system tray seems to work. So probably that's the root of the issue.

I'll mess around a bit and see if I can disable the KDE one.

**Comment by elParaguayo** [comment]
Nice. I'll close this for now but please re-open it if there's a qtile issue here.

**Comment by alethiophile** [comment]
Update: I solved this issue within KDE by going to systemsettings5 -> Startup and Shutdown -> Background Services and disabling "Status Notifier Manager". Apparently KDE runs its own weird systray system that usurps the normal protocol even if the panels are removed.

This has nothing to do with qtile specifically, but I thought I'd leave an answer here for future frustrated websearchers.

**Comment by elParaguayo** [comment]
Great work and thanks for sharing the solution.
