### ISSUE TITLE
Qtile Wayland won't start

### ISSUE THREAD

**Issue by kraanzu** [qtile/qtile#4590]
### Issue description

I'm trying to log in to qtile wayland session and it just opens up a black screen, waits a few seconds (~5), and then logs me back out.

I can see the wayland session in a window from my `X11` session if I run this
```bash
qtile start -b wayland
```

<hr>

Additional (what I tried from other issues):

- I removed systray from bar
- I ensured that KMS is on
```
$ sudo dmesg | grep modesetting
[    7.214022] [drm] amdgpu kernel modesetting enabled.
[    7.224623] [drm] initializing kernel modesetting (DIMGREY_CAVEFISH 0x1002:0x73EF 0x1458:0x2406 0xC1).
```

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
I tried this with default config and it didn't work either
```

### Logs

```text
2023-11-24 22:06:06,603 ERROR wlroots log.py:log_func_callback():L15 [backend/backend.c:114] Timeout waiting session to become active
2023-11-24 22:06:06,604 ERROR wlroots log.py:log_func_callback():L15 [backend/backend.c:357] Failed to start a DRM session
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
- How are you launching qtile?
- Do you have polkit installed or your user added to the 'seat' group when using seatd
- Do other wayland compositors such as sway work on your system?

**Comment by kraanzu** [comment]
> How are you launching qtile (tty/display manager)?

Lightdm

> Do you have polkit installed or your user added to the 'seat' group when using seats

Yes Polkit it installed 
I was not in the `seat` group. I ran this and rebooted the system as well but no luck
```bash
sudo usermod -a -G seat $USER
```

> Do other wayland compositors such as sway work on your system?

Yes Hyprland works

**Comment by kraanzu** [comment]
Thanks @jwijenbergh! I'll close this

**Comment by jwijenbergh** [comment]
Cool! I think we need a more extensive Wayland troubleshooting section to the docs
