### ISSUE TITLE
Bluetooth Widget doesn't work (dbus-next InterfaceNotFoundError)

### ISSUE THREAD

**Issue by SebastianStork** [qtile/qtile#4591]
### Issue description

This seems to be an issue with dbus-next. Is this the right place for this question or should I ask this at the dbus-next repository?

I installed dbus-next like instructed in the documentation but the widget doesn't show up on the bar, instead I got some error messages in the log.

How I understand it, dbus-next should work out of the box and there shouldn't be any manual configuration needed but it seems like dbux-next can't find my bluetooth device.

My bloetooth works fine. I use the bluetooth manager that ships with linux mint. The wifi and bluetooth chip my laptop uses is the Realtek RTL8821CE. I don't have any additional drivers installed.

The only somewhat related Issue I found is this: [dbus_next.errors.InterfaceNotFoundError](https://github.com/SilvairGit/python-bluetooth-mesh/issues/101) but it didn't help.

I am afraid I am missing something really obvious here. Any help is appreciated.

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
from libqtile import bar, layout, widget, hook
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
import os
import subprocess

...

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.CurrentLayout(),
                # widget.WindowName(),
                widget.Spacer(),

                widget.Clipboard(),                
                # widget.Wlan(),
                widget.Bluetooth(),
                # widget.Volume(),
                # widgRet.Backlight(),
                widget.Battery(format="{percent:1.0%}"),
                widget.Clock(format="%d.%m.%Y %H:%M"),
            ],
            24,
            # border_width=[2, 0, 2, 0],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),
        # You can uncomment this variable if you see that on X11 floating resize/moving is laggy
        # By default we handle these events delayed to already improve performance, however your system might still be struggling
        # This variable is set to None (no cap) by default, but you can set it to 60 to indicate that you limit it to 60 events per second
        # x11_drag_polling_rate = 60,
    ),
]

...
```

### Logs

```text
2023-11-25 11:00:55,952 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/home/sebastian/.local/lib/python3.10/site-packages/dbus_next/proxy_object.py", line 217, in get_interface
    intr_interface = next(i for i in self.introspection.interfaces if i.name == name)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/.local/lib/python3.10/site-packages/libqtile/widget/bluetooth.py", line 61, in _config_async
    self.connected, self.device = await self._init_device()
  File "/home/sebastian/.local/lib/python3.10/site-packages/libqtile/widget/bluetooth.py", line 83, in _init_device
    iface = obj.get_interface(BLUEZ_DEVICE)
  File "/home/sebastian/.local/lib/python3.10/site-packages/dbus_next/aio/proxy_object.py", line 159, in get_interface
    return super().get_interface(name)
  File "/home/sebastian/.local/lib/python3.10/site-packages/dbus_next/proxy_object.py", line 219, in get_interface
    raise InterfaceNotFoundError(f'interface not found on this object: {name}')
dbus_next.errors.InterfaceNotFoundError: interface not found on this object: org.bluez.Device1
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
It's probably a bug in the widget rather than dbus-next. I'll try to help you debug it when I have some time.

**Comment by elParaguayo** [comment]
Ah... I'm guessing you're on v0.23.0 of qtle but you've been looking at the latest version of the docs (which tracks the git version of qtile) as opposed to the stable version which tracks tagged releases.

In short, the bluetooth widget was updated after the 0.23.0 release. Prior to that, you have to specify the object name for a bluetooth device. See https://docs.qtile.org/en/stable/manual/ref/widgets.html#bluetooth and look at the `hci` parameter.

However, I'd recommend using the git version of qtile as then you have access to the new version of the widget which has much more functionality.

**Comment by elParaguayo** [comment]
I'm going to close for now but please reopen if you're still having issues.
