### ISSUE TITLE
Chord seems wrong

### ISSUE THREAD

**Issue by mu-us61** [qtile/qtile#4597]
### Issue description

when using chords Qtile gets stuck cant even switch workspaces , unless I had to continue to use chord key , like in the example I had to press "x" to spawn xterm  , or pressing "esc" , so what it should be if we type something that dont fit chord shortcuts it would be better Qtile to cancel chords automatically , I made it explicitly mode =false but still same

steps to repuroduce :
you can use this keychord , and press mod + g , it will stuck unless pressing "ESC" or "x" which will spawn xterm

### Version

0.23

### Backend

X11 (default)

### Config

```python
KeyChord(
        [mod],
        "g",
        [
            Key([], "x", lazy.spawn("xterm")),
        ],
        mode=False,
    ),
```

### Logs

```text
no error on logs
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
That's not quite how it works.

`mode=True` means you stay in the chord, even after executing a command. `mode=False` exits the code when a valid command has been run.

I understand your issue but qtile isn't set up to work like that currently. When we trigger a keychord, qtile only listens for the key bindings related to the chord. Everything else is passed to the active window. 

I'm not inclined to change this but welcome thoughts from @jwijenbergh @m-col or @ramnes

**Comment by jwijenbergh** [comment]
> I'm not inclined to change this but welcome thoughts from @jwijenbergh @m-col or @ramnes 

I agree. IMO they should work similar to emacs, when you press a button (after e.g. Ctrl-c) that is not defined it just says "undefined" and does nothing. So the behaviour currently is similar to that.
