### ISSUE TITLE
Bar on multi monitor doesnt render

### ISSUE THREAD

**Issue by ranjandatta** [qtile/qtile#4607]
### Issue description

Trying to duplicate my bar on second screen causes both bars to not render in X.

Screenshot
https://imgur.com/a/t18880B

screens.py code
```
from libqtile.config import Screen, Group, DropDown, Key
from libqtile import bar

from modules.widgets import widgets_list  
from modules.palette import palette 

widget_defaults = dict(
    font="Cartograph CF",
    fontsize = 14,
    padding = 8,
    foreground = palette.foreground,
    background=palette.background,
)

extension_defaults = widget_defaults.copy()

bar_defaults = {
    'size': 28, 
    'border_width': [8,0,8,0], 
    'background': palette.background,
    'border_color': palette.background,
    'margin': 0
}

def init_widgets_list():
    return widgets_list

def init_widgets_screen1():
    widgets_screen1 = init_widgets_list()
    return widgets_screen1


def init_widgets_screen2():
    widgets_screen2 = init_widgets_list()
    return widgets_screen2


def init_screens():
	return [
        Screen(top=bar.Bar(widgets=init_widgets_screen1(), **bar_defaults)),
        Screen(top=bar.Bar(widgets=init_widgets_screen2(), **bar_defaults))
    ]

screens = init_screens()
```
widgets.py code
```
from libqtile import qtile, widget

from modules.palette import palette
from modules.prefs import terminal
from modules.clock import Clock

widgets_list = [
    widget.Spacer(length=12),
    Clock(
        format="%D | %I:%M %p",
        other_format="%D |%I:%M %p",
        other_timezone='Asia/Kolkata',
        foreground = palette.green,
    ),
    widget.Spacer(length=12),
    widget.Spacer(),
    widget.GroupBox(
        active =            palette.green,
        inactive =          palette.gray,
        borderwidth =       0,
        highlight_method =  "text",
        this_current_screen_border=palette.green,
        visible_groups =["1", "2", "3", "4", "5"],
        
    ),
    widget.Spacer(),
    widget.Spacer(length=12),
    widget.PulseVolume(
        foreground = palette.green,
        fontsize = 20,
        emoji=True,
        emoji_list=['󰝟', '󰕿', '󰖀', '󰕾'],
        mouse_callbacks = {'Button3': lambda: qtile.cmd_spawn('xdotool key super+control+v')},
    ),
    widget.PulseVolume(
        foreground = palette.green,
        mouse_callbacks = {'Button3': lambda: qtile.cmd_spawn('xdotool key super+control+v')},
    ),   
    widget.Spacer(length=12),        
]
```

### Version

0.23.0

### Backend

X11 (default)

### Logs

```text
2023-11-30 16:17:48,871 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2023-11-30 16:55:29,973 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-11-30 16:55:29,974 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-11-30 16:55:29,975 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-11-30 16:55:29,975 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-11-30 16:55:29,978 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-11-30 16:55:29,978 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,704 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,704 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,705 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,705 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,711 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
2023-12-01 05:14:46,712 WARNING libqtile pulse_volume.py:get_sink_info():L116 Cold not get info for default sink
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. I have a theory about this but won't be able to test until later.

**Comment by ranjandatta** [comment]
Thanks, please take your time, no rush. I am using the bar on a single monitor without issue

**Comment by elParaguayo** [comment]
Mirrors look to be pretty broken! Will work on a fix.

**Comment by elParaguayo** [comment]
Can you try #4613 and see if that works?

**Comment by elParaguayo** [comment]
I've merged the fix so using qtile-git in AUR should solve your issue.

**Comment by ranjandatta** [comment]
qtile-git doesnt install on arch 
```ERROR Missing dependencies:
	pywlroots<0.17.0,>=0.16.4```
I am not a wayland user and will not be for the foreseeable future. I am sure there are many like me that do not want to migrate to wayland for quite some time. 

Why is there a hard dependency on wayland libraries?

**Comment by elParaguayo** [comment]
You're right, it shouldn't be a hard dependency. The dependency should only be for build purposes so that our wayland bindings get built. However, I had hoped that it would just skip building the backend if the dependency wasn't present.

Can you post more of the log rather than just that one line so I can see at what stage this issue is happening.

**Comment by ranjandatta** [comment]
`PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: qtile-git 0.22.1.r215.g142dc80a-1 (Mon 08 Jan 2024 06:05:49 AM MST)
==> Retrieving sources...
  -> Updating qtile git repo...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 30 (delta 13), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (30/30), 34.17 KiB | 1.80 MiB/s, done.
From https://github.com/qtile/qtile
 + f6f3dfb3...bc7573bf refs/pull/4202/merge -> refs/pull/4202/merge  (forced update)
 + 115cd919...d0f13f6d refs/pull/4486/merge -> refs/pull/4486/merge  (forced update)
 + 5adc48c2...7b3285eb refs/pull/4524/merge -> refs/pull/4524/merge  (forced update)
 * [new ref]           refs/pull/4641/head  -> refs/pull/4641/head
 * [new ref]           refs/pull/4641/merge -> refs/pull/4641/merge
==> Validating source files with md5sums...
    qtile ... Skipped
==> Making package: qtile-git 0.22.1.r215.g142dc80a-1 (Mon 08 Jan 2024 06:05:51 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating qtile git repo...
==> Validating source files with md5sums...
    qtile ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of qtile git repo...
Cloning into 'qtile'...
done.
==> Starting pkgver()...
==> Updated version: qtile-git 0.23.0.r98.gc5e7fc98-1
==> Sources are ready.
qtile-git-0.22.1.r215.g142dc80a-1: parsing pkg list...
==> Making package: qtile-git 0.23.0.r98.gc5e7fc98-1 (Mon 08 Jan 2024 06:05:54 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
* Getting build dependencies for wheel...
Failed to find pywlroots. Wayland backend dependencies not built.

ERROR Missing dependencies:
	pywlroots<0.17.0,>=0.16.4
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'qtile-git-0.22.1.r215.g142dc80a-1':
error: packages failed to build: qtile-git-0.22.1.r215.g142dc80a-1`
