### ISSUE TITLE
TreeTab not drawing menu correctly on multimonitor setups

### ISSUE THREAD

**Issue by Etn40ff** [qtile/qtile#4634]
### Issue description

I have a two monitor setup with different resolutions. 
One of my groups uses the TreeTab layout. Depending on which monitor it is first created on this layout has a gap in the menu region as you can see in this screenshot (the higher resolution monitor is on the left)
![2023-12-19_09-09](https://github.com/qtile/qtile/assets/1158010/8701c991-918c-40e7-b0d1-d305c1ba70b5)

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Sorry for the delay.

I know where the problem is. I'm just thinking about the best way to fix it!

**Comment by elParaguayo** [comment]
Can you try #4636 please.
