### ISSUE TITLE
A small mistake in the documentation

### ISSUE THREAD

**Issue by VelocityREST** [qtile/qtile#4637]
### Issue description

I was reading the [command graph](https://docs.qtile.org/en/stable/manual/commands/command_graph.html) page trying to follow along, when I stumbled upon this small snippet 
`c.group["b"].to_screen(1)`
Should be changed to:
`c.group["b"].toscreen(1)`

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. Can you make a PR to fix it?
