### ISSUE TITLE
KeePassXC "Access request" window is always below every other. Even if i force it to be above with `.bring_to_front()`

### ISSUE THREAD

**Issue by kulkesk** [qtile/qtile#4643]
### Issue description

I use KeePassXC secret service. When app needs to access the secret data keepass pops up with a smaller window and asks should it give the window the access to the entries of it's database or not. But this window is always below every other window. No matter what i do. Even if i explicitly set that window on top of every other window with `.bring_to_front()` or `move_to_top()`.
Here is the output of the xprop command on that window if it will help in any way:
```
_NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 2, 2
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 1451114
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_MODAL, _NET_WM_STATE_STAYS_ON_TOP
WM_TRANSIENT_FOR(WINDOW): window id # 0x1000008
_NET_WM_ICON_NAME(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "KeePassXC -  Access Request"
_NET_WM_NAME(UTF8_STRING) = "KeePassXC -  Access Request"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1000008
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x1000008
WM_CLIENT_MACHINE(STRING) = "[REDACTED]"
_NET_WM_PID(CARDINAL) = 914
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777357
WM_CLASS(STRING) = "keepassxc", "KeePassXC"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST, _NET_WM_CONTEXT_HELP
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 270, 202
		user specified size: 807 by 284
		program specified minimum size: 570 by 156
		window gravity: Static
```

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Does #4583 fix this for you?

**Comment by kulkesk** [comment]
Hi @elParaguayo , sorry for missing for so long. Yes, I tested your pull request, and it indeed fixes my issue. Thank you! Can't wait for it to be merged into main repo

**Comment by elParaguayo** [comment]
Thanks for the update. 

There are a couple of little bugs with window stacking that I need to look at but we may be able to merge this in the meantime.
