### ISSUE TITLE
Tabs in Firefox can't be moved left/right with mouse.

### ISSUE THREAD

**Issue by ftpd** [qtile/qtile#4644]
### Issue description

Sometimes I want to switch positions of open tabs - normally I drag one with the mouse and simply move it left/right. It works fine on 'stable' qtile 0.23.0, but after switching back to git's master (last commit when I write this: `c5e7fc98`), it stopped working. The 
similar issue I can see in Jira - when I try to move the tickets around on a kanban board, I simply can't.  
I've tested in on 'native' Firefox from my distribution's repository and also with Flatpak version - both have the issue. I can't reproduce it in Chromium-likes (tested on Ungoogled Chromium and Brave).  
Logs are clean.

After using `git bisect` I was able to pinpoint the source of the issue to this PR: https://github.com/qtile/qtile/pull/4540

(Disclaimer for the 'Version' field: `qtile --version` shows `0.0.0` for me when installed via pip, so I'll put there only the commit hash of the current HEAD - sorry).

### Version

c5e7fc98

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by QBobWatson** [comment]
I fixed this in https://github.com/qtile/qtile/pull/4641 -- can you try that out?

**Comment by ftpd** [comment]
Confirmed, it works fine now.

**Comment by jwijenbergh** [comment]
Merged.
