### ISSUE TITLE
Non-persistent Groups are still alive when its last window is moved to another group

### ISSUE THREAD

**Issue by ValdezFOmar** [qtile/qtile#4654]
### Issue description

# Issue
When a group is created with the option `persist=False` and its last window is moved to another group (instead of being kill inside that group), the non-persistent group is still alive.

## Expected behavior
A non-persistent group should be removed when it no longer contains any window and _not_ when its last window is **specifically killed inside the group**. 

## Steps to reproduce:

1. Create a group with the following configuration:
    ```python
    groups = [
        # Some property to match
        Group("a", matches=[Match(wm_class="foo")], exclusive=True),
        # other groups
    ]
    ```
2. Open a window in group `"a"` that doesn't match any of the group's matches and doesn't match any other group.
3. A new group will be created with the name of the window as the last group.
4. Move this new group to the current screen.
5. Send the (only) window to any other group.
6. The new group is still alive, even though it doesn't have any windows and it's not persistent.

The group can still be remove either through the commands API or, as a workaround, by opening a new window in that group and then killing it while the window is still in the group.

The problem seems to be that the `DGroups._del()` method at `/libqtile/dgroups.py` it's only run when the `client_kill` event is fired, so groups are only ever consider for removal when windows are killed/closed but not when windows are only removed from them, which matches the previously described behavior.

> NOTE: I've only test it X11

Is this intended behavior?

### Version

0.24.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
I'd say it is expected behaviour but only in the sense that it is doing what it should. Is it the _desired_ behaviour? Probably not given you've posted an issue.

I'll take a look when I can.
