### ISSUE TITLE
Icons used in cloned LaunchBars do not dynamically change their size when `icon_size` isn't set

### ISSUE THREAD

**Issue by ArbitraryRenaissance** [qtile/qtile#4668]
### Issue description

I cloned a LaunchBar for use on my multi-monitor setup, and drew bars for each monitor, with the main bar a different size from the secondary bars.

Resulting behavior: the icons on the secondary bar are sized appropriately, and the icons on the main bar match the size of the icons on the secondary bar.

Secondary bar:
![1706381680](https://github.com/qtile/qtile/assets/794101/7c7b2c65-344f-4493-b8a4-8fc31225c9ce)

Main bar (whose height is 2x the height of the secondary bar):
![1706381644](https://github.com/qtile/qtile/assets/794101/207e4480-1ad5-4904-be6b-c718527ae8b9)

Expected behavior: the size of the icons fit to the size of their respective bars.

Steps to reproduce:
1. Create a qtile environment with at least two available screens.
2. Create a LaunchBar widget that loads an image for the icon.  For example, a simple Discord launch button like `LB_test = widget.LaunchBar(progs=['discord', 'discord', ''])` should suffice.
3. Draw two bars in `screens` where one bar has a different size from the second one, and a clone of the above widget is inserted in place of the original.  For example, `screens = [Screen(bottom=bar.Bar([LB_test], 56)), Screen(bottom=bar.Bar([LB_test.clone()], 28))]`

If needed, I can include a version of my configuration file where the issue is produced.

### Version

0.23.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Interesting. Will take a look.
