### ISSUE TITLE
TypeError with group focus_by_index CLI command

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#4691]
### Issue description

I'm using commands like `qtile cmd-obj -o group 3 -f focus_by_index -a 0` to programmatically focus specific windows in a specific group. However it fails because the CLI arg is passed as a string instead of an integer, and the subsequent comparisons raise a type error:

```
error: Sorry cannot run function 'focus_by_index' with arguments ['1']: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/command/interface.py", line 317, in call
    return SUCCESS, cmd(obj, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 537, in focus_by_index
    if index < 0 or index > len(windows) - 1:
       ^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

I've fixed this locally by patching the function, adding `index = int(index)` right before the comparison. It's not very elegant, especially since the parameter is type annotated as `int`, but that's the quickest fix until the `@expose_command` logic is improved as to type-cast arguments based on their annotations, which I'm unsure is even planned :slightly_smiling_face: 

 I can send a PR with the mentioned quick fix if you think it's reasonable while waiting for something more sophisticated (there are probably other places where this type error happens).

### Version

0.24.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. This is a known issue which we still haven't fixed. Sorry about that!

**Comment by elParaguayo** [comment]
That would be amazing - that's exactly the type of approach that would make sense (although I suspect there may be several exposed commands that are not currently typed - but we can fix that).

**Comment by pawamoy** [comment]
Great! Additional note: casting strings into complex objects will probably require one of these two things:

- that these complex objects can be instantiated from a string value
- that these complex objects provide a staticmethod/classmethod to create instances from string values

(Second option is definitely better)

**Comment by elParaguayo** [comment]
I'd really hope we don't need either of those too often. For the most part, exposed commands really should just be using simple types. There are some exceptions (e.g. `lazy.function` needs a callable that takes an argument) but I'd hope we're typically just using numbers, strings and bools.

I could be very wrong!

**Comment by elParaguayo** [comment]
This can be closed as tych0 implemented a solution.

**Comment by pawamoy** [comment]
Could you share a link to this implemented solution :slightly_smiling_face: ?

**Comment by elParaguayo** [comment]
I think it was this one: https://github.com/qtile/qtile/pull/4741
