### ISSUE TITLE
lazy.spawn does not allow env variables with shell=True

### ISSUE THREAD

**Issue by bodograumann** [qtile/qtile#4705]
### Issue description

A common shell syntax, to pass environment variables to processes is `GDK_DPI_SCALE=1 firefox`, i.e. putting it before the command to run. So it should also work when running it like this:

```python
lazy.spawn("GDK_DPI_SCALE=1 firefox", shell=True)
```

Instead qtile just logs:

> 2024-02-20 10:37:49,721 ERROR libqtile manager.py:spawn():L1255 couldn't find `GDK_DPI_SCALE=1`

The relevant code is here:
https://github.com/qtile/qtile/blob/afa4dcbff0c72452571465bf8258ea45510af959/libqtile/core/manager.py#L1255-L1261

It assumes that the first  part of the given string is a command name, but here it is the env setting.

Cf. discussion here: https://github.com/qtile/qtile/discussions/2794

### Version

0.24.0

### Backend

Wayland (experimental)

### Config

```python
EzKey("b", lazy.spawn("GDK_DPI_SCALE=1 firefox"), desc="Run firefox without scaling"),
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. Yes, this is an issue caused by our code as we always assume the first item is the name of the command to run so we check if that's available.

I'll have a think at the best way to fix this.

**Comment by elParaguayo** [comment]
#4709 should fix this. For your example, you'd run:
```python
lazy.spawn("firefox", env={"GDK_DPI_SCALE": "1"} )
```
