### ISSUE TITLE
get_volume_command not working on PulseVolume widget

### ISSUE THREAD

**Issue by Sprinter05** [qtile/qtile#4759]
### Issue description

When using the option `get_volume_command="pamixer --get-volume-human",` on the qtile configuration file nothing changes in the output and no error is reported by the logs. I already saw a closed issue about this but the only thing I could get from that is that it worked on 0.23.0 onwards but I'm using 0.24.1 and it is not working so Im reporting this issue again.

### Version

0.24.1.dev41+gc4d3c6e6

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
If you want to use a custom command, use the `Volume` widget. The `PulseVolume` widget doesn't use the `get_volume_command` parameter - it connects to the pulse server directly via an API.

The `get_volume_command` is shown in the docs as the widget inherits the `Volume` class.

On my list of things to do is an item to hide unused parameters from the docs to avoid issues like this. It's low priority though!

Anyway, this isn't a bug in my mind so I'd propose closing this issue.

**Comment by Sprinter05** [comment]
Oh okay I got confused because of that, still it's weird because using `pipewire-pulse` the volume reported by the API seems inaccurate to apps like `pamixer` which is why I was trying to override the command to get the volume. Maybe I will check why this happens on another day and submit a PR if necessary. I'll close this issue now then.
