### ISSUE TITLE
Qtile isn't running as wayland wm

### ISSUE THREAD

**Issue by fedya-eremin** [qtile/qtile#4761]
### Issue description

I want to use Qtile as wayland compositor, but it doesnt. First, I installed wlroots0.16 and wlroots0.16-devel in Fedora 39 (python 3.12.2). Then I installed pywlroots==0.16.4 as it stated in wiki. Then I installed qtile[wayland]. On startup it shows error as it is in logs and blinks to black screen for second. What should I do with it? TY

### Version

0.25.0

### Backend

Wayland (experimental)

### Config

```python
default config
```

### Logs

```text
Warning: Wayland backend not built. Backend will not run.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
You could start by posting the error messages that you're getting.

**Comment by fedya-eremin** [comment]
Im sorry, but the only error message I am getting is the one in logs

**Comment by elParaguayo** [comment]
Try
```
pip install --no-binary :all: --config-setting backend=wayland qtile[wayland]
``|

**Comment by fedya-eremin** [comment]
TY, it worked out! Is it because of flags that recompile wheels?

**Comment by elParaguayo** [comment]
I don't know what system you're on but, for some reason, pip wasn't giving you a prebuilt wheel from pypi. Is this on a raspberry pi?

**Comment by fedya-eremin** [comment]
It is Fedora 39 as it stated in issue desc. Can I close this?

**Comment by elParaguayo** [comment]
Sorry. Missed that. Not sure why you didn't get a wheel with wayland support already built. 

Anyway, fine to close this.

**Comment by elParaguayo** [comment]
Sorry, last question, what python version are you on?
