### ISSUE TITLE
applying a wallpaper image does not get rid of the old one

### ISSUE THREAD

**Issue by PhoenixClank** [qtile/qtile#4772]
### Issue description

It seems like the new wallpaper image is _added_ to the old one, which causes it to get iteratively brighter. For example, this is how my screen is supposed to look:
![a regular-looking photo](https://github.com/qtile/qtile/assets/30195074/09f7a007-8b49-4c2d-a09c-c250fb781b25)
And this is how it looks like after reloading config five times:
![a very over-exposed-looking photo](https://github.com/qtile/qtile/assets/30195074/809a1e68-0ca2-4b92-b58b-06344388547d)

### Version

0.25.1.dev0+g005da458.d20240413

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
This could have been caused by #4621

Pinging @jwijenbergh as this is Wayland...

**Comment by wingej0** [comment]
I can confirm this on my machine as well.  I posted a screencast of it on the Discord server.

**Comment by jwijenbergh** [comment]
Which gpu? Also can you share the wallpaper?

**Comment by PhoenixClank** [comment]
It's the integrated graphics of an AMD Ryzen 5 5500U. The wallpaper is at https://s20.directupload.net/images/240422/87h4htpr.png. It gets downscaled to 1920x1080 with the "fill" wallpaper mode of qtile.

**Comment by jwijenbergh** [comment]
Can anyone try #4785 ?
