### ISSUE TITLE
Source install instructions refer to nonexistent PyPI packages

### ISSUE THREAD

**Issue by jgarvin** [qtile/qtile#4809]
### Issue description

[The docs](https://docs.qtile.org/en/latest/manual/install/#installing-from-source) refer to installing `qtileall`, `qtilewidgets` and `qtilewayland`, but there are no such packages in PyPI.

### Version

0.25.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
seems to work for me:

```
$ pip3 install qtile[wayland]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: qtile[wayland] in /home/tycho/.local/lib/python3.10/site-packages (0.21.1.dev14+g09c6a326)
Requirement already satisfied: cairocffi[xcb]>=0.9.0 in /home/tycho/.local/lib/python3.10/site-packages (from qtile[wayland]) (1.6.1)
Requirement already satisfied: cffi>=1.1.0 in /home/tycho/.local/lib/python3.10/site-packages (from qtile[wayland]) (1.15.0)
Requirement already satisfied: xcffib>=0.10.1 in /home/tycho/.local/lib/python3.10/site-packages (from qtile[wayland]) (1.5.0)
Collecting pywlroots<0.16.0,>=0.15.12 (from qtile[wayland])
```

looks like you might have omitted the `[]`s?

**Comment by jgarvin** [comment]
I misunderstood, I thought it was saying you should optionally add those suffixes to get more packages, I didn't realize brackets could actually be in the name 😂 I did search for the PyPI web interface though and they didn't show there, how does that work?

**Comment by tych0** [comment]
They're "just" standard "extras"; here's setuptools' docs: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by jgarvin** [comment]
Ah thanks for the clarification, sorry for the noise
