### ISSUE TITLE
System tray symbolic icon not visible when bar is black

### ISSUE THREAD

**Issue by dawin64** [qtile/qtile#4816]
### Issue description

I am using 'volumeicon' on i3 and the symbolic icon appears in white but when I want to use the same program on qtile the icon is black and does not appear(black on black) if I would use `widget.Systray(background="ffffff")` it would work but this is not a good solution in my opinion. I could not find any information in the documentation if I can change the icon color of symbolic icons, but when the color is too dark the symbolic icon should be the inverse.

### Version

0.25.1.dev0+g005da458.d202440413

### Backend

X11 (default)

### Config

```python
widget.Systray(),
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
The widget doesn't select which icon to draw this is done by the relevant program itself. I would expect this to be determined by some theme setting elsewhere. However, I am not sure why it would work on i3 and not on qtile as both should benefit from the same theme configs (unless you put something specific in your i3 config).

**Comment by dawin64** [comment]
Maybe something with _NET_SYSTEM_TRAY_COLORS for GTK+ 3? I don't have any themes installed manually I only use Adwaita icons and also never set it anywhere.

**Comment by elParaguayo** [comment]
It would be easy enough to add an option to the widget to set this but do you know the meaning of the different values being set?

**Comment by richcarni** [comment]
I had to do some research on this. From what I can gather the _NET_SYSTEM_TRAY_COLORS atom is used by some gtk3 apps to stylise symbolic icons. It doesn't appear to have ever been adopted into the desktop standard and was probably never used that widely

Anyway, the original link I posted also has a link to this gtk commit, which has some more detail: https://mail.gnome.org/archives/commits-list/2010-April/msg09154.html

Basically, the numbers are 4 RGB triplets (16 bit) for:
1. foreground color
2. error color
3. warning color
4. success color

So the values I used are white, red, orange, green respectively. I'm not sure 2-4 are important/used. I probably wouldn't expose these unless someone reported a case where they would be useful

I'd be willing to have a go at a PR but it wasn't immediately obvious to me how to create/set an atom (without using a system call)

As a somewhat related question, is the idea that StatusNotifier will replace Systray or is this really dependent on apps adding support for StatusNotifier icons? I tried nm-applet and keepassxc but they didn't display an icon (blueman did)

**Comment by ervinpopescu** [comment]
> As a somewhat related question, is the idea that StatusNotifier will replace Systray or is this really dependent on apps adding support for StatusNotifier icons? I tried nm-applet and keepassxc but they didn't display an icon (blueman did)

https://github.com/qtile/qtile/issues/4995#issuecomment-2340309728
https://github.com/qtile/qtile/issues/4995#issuecomment-2340409234

Basically, there's talk about a new standard in town, designed to deprecate both Systray and StatusNotifier.
