### ISSUE TITLE
Wayland: Popups are clipped

### ISSUE THREAD

**Issue by jwijenbergh** [qtile/qtile#4819]
### Issue description

Starting from wlr 0.17 branch, popups in e.g. firefox are clipped when resizing (but maybe in other scenarios too). figure out what is going wrong. It's not super breaking as it's only the edges of the popup. To repro:

- start firefox
- right click to open popup
- resize the firefox window with a super+right click drag, popup edges will be clipped. Also happens when toggling floating
### Version

git

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by bendi-github** [comment]
Updated to Firefox 127.0.1-1 (arch linux) today, the popups are no longer cut off.

**Comment by jwijenbergh** [comment]
> Updated to Firefox 127.0.1-1 (arch linux) today, the popups are no longer cut off.

Interesting. Might have been a Firefox bug then. Did you see this in another application?
