### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'create_layout'" in backend/base/drawer.py

### ISSUE THREAD

**Issue by DeeeeLAN** [qtile/qtile#4833]
It looks like the error is coming from the following two snippets of code, where the initializer for `TextLayout` is missing the `drawer` input.

https://github.com/qtile/qtile/blob/5cf924fbce84bc709ad71b2ee84575091992215d/libqtile/backend/base/drawer.py#L322-L324

https://github.com/qtile/qtile/blob/5cf924fbce84bc709ad71b2ee84575091992215d/libqtile/backend/base/drawer.py#L378-L381

Here is the full stack trace which is repeatedly spamming my log (originating from the qtile-extras globalmenu widget):

```
2024-05-22 14:47:01,908 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.12/site-packages/qtile_extras/resources/dbusmenu/__init__.py", line 266, in parse_menu
    callback(menu)
  File "/home/dillan/.config/qtile/widgets/globalmenu.py", line 152, in parse_root_menu
    layout = self.drawer.textlayout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 322, in textlayout
    textlayout = TextLayout(
                 ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 383, in __init__
    layout = drawer.ctx.create_layout()
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_layout'
```

**Comment by elParaguayo** [comment]
If this is specific to the `GlobalMenu` widget then this is really a qtile-extras issue but let's deal with it here for now!

Did this happen when starting qtile or had you done something like reloading the config?

**Comment by DeeeeLAN** [comment]
I wasn’t sure, I figured since the error looked like it was caused by just those two files in the main qtile repo, I would post it here. 

From what I can tell, the error just shows up continually. The global menu still works despite the errors. I will monitor the log and see if it starts as soon as the session starts or if it isn’t until after  a reload.

**Comment by DeeeeLAN** [comment]
Okay I dug further. On a fresh start, there are no errors. Once I reload with `lazy.reload_config()`, then the error appears each time my mouse enters VS Code.

**Comment by elParaguayo** [comment]
Thanks. That's helpful. I'll see if I can recreate later.

**Comment by elParaguayo** [comment]
I think this is a `GlobalMenu` issue but I'm struggling to track down the root cause of the issue!

**Comment by DeeeeLAN** [comment]
I am confused then (not saying you are wrong though). But why is the `TextLayout` usage mismatched in the code snippets I posted? And why doesn't the missing `drawer` from the init call not pop up a lot more?

**Comment by elParaguayo** [comment]
The issue seems to be that the widget is trying to create a text layout on a drawer that has been finalised. This is probably due to some callbacks that aren't cleared when the config is reloaded.

**Comment by elParaguayo** [comment]
Found it. This should fix it: https://github.com/elParaguayo/qtile-extras/pull/349

**Comment by DeeeeLAN** [comment]
Nice! I am not seeing any more errors show up after installing that and restarting.

**Comment by elParaguayo** [comment]
Thanks. I've fixed the test failures so will now get this merged.
