### ISSUE TITLE
`client_unmanaged` hook before `client_killed`

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4844]
### Issue description

I believe we should have such a hook, which will allow the client management to look like so:
```py
client_new > client_managed > client_unmanaged > client_killed
```

@elParaguayo @tych0 thoughts? 

---

Context:

Trying to do this:

```py
import json
import os
from modules.path import config_path

class Session:
    def __init__(self):
        self.apps = []

    def add_app(self, exe: str):
        self.apps.append(exe)

    def remove_app(self, exe: str):
        self.apps.remove(exe)

    def save(self):
        with open(os.path.join(config_path, "json", "session.json"), "w") as f:
            json.dump(self.apps, f)

    def restore(self):
        with open(os.path.join(config_path, "json", "session.json"), "r") as f:
            self.apps = json.load(f)


session = Session()

@hook.subscribe.client_managed
def add_app_to_session(client: Window):
    pid = client.window.get_net_wm_pid()
    process = psutil.Process(pid)
    exe = process.exe()
    args = process.cmdline()
    logger.info("%s,%s", exe, args)
    session.add_app(exe)
    logger.info("%s", session.apps)

@hook.subscribe.client_killed
def remove_app_from_session(client: Window):
    pid = client.window.get_net_wm_pid()
    process = psutil.Process(pid)
    exe = process.exe()
    args = process.cmdline()
    logger.info("%s,%s", exe, args)
    session.remove_app(exe)
    logger.info("%s", session.apps)

@hook.subscribe.startup_once
def restore_session():
    session.restore()
    apps = session.apps
    logger.info("Restoring session with apps: %s", ",".join(apps))
    for app in apps:
        qtile.spawn(app)

@hook.subscribe.shutdown
def save_session():
    session.save()
    apps = session.apps
    logger.info("Saving session with apps: %s", ",".join(apps))
```

which will yield:
```py
2024-05-27 12:25:34,160 INFO libqtile hooks.py:remove_app_from_session():L127 /usr/bin/python3.12
2024-05-27 12:25:34,161 ERROR libqtile hook.py:fire():L193 Error in hook client_killed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/hook.py", line 191, in fire
    i(*args, **kwargs)
  File "/home/ervin/.config/qtile/modules/hooks.py", line 128, in remove_app_from_session
    session.remove_app(process)
  File "/home/ervin/.config/qtile/modules/session/__init__.py", line 9, in remove_app
    self.apps.remove(exe)
ValueError: list.remove(x): x not in list
```
The `pid` in `client_killed` is already gone, since qtile killed it, right? 

### Version

0.26.1.dev6+ga7f5d1c8

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
I think (?) such a race still exists: if a client is unmanaged, it may be that someone has killed it, so by the time you see and process the event, the pid will be dead anyway.

If you save the wid in addition to the pid, you could disambiguate this situation with the wid instead (and still use the pid to get whatever info you wanted about it in the interim).

**Comment by ervinpopescu** [comment]
> I think (?) such a race still exists: if a client is unmanaged, it may be that someone has killed it, so by the time you see and process the event, the pid will be dead anyway.

Yes, in this particular instance, `qtile` was killing the pid, I added the updated MRE (the one that produces these logs) in the issue description:
```py
2024-05-29 10:53:32,316 INFO libqtile hooks.py:add_app_to_session():L122 /usr/bin/alacritty,['alacritty']
2024-05-29 10:53:32,317 INFO libqtile hooks.py:add_app_to_session():L124 ['/usr/bin/alacritty']
2024-05-29 10:53:33,646 INFO libqtile hooks.py:remove_app_from_session():L132 /usr/bin/python3.12,['qtile', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
2024-05-29 10:53:33,647 ERROR libqtile hook.py:fire():L193 Error in hook client_killed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/hook.py", line 191, in fire
    i(*args, **kwargs)
  File "/home/ervin/.config/qtile/modules/hooks.py", line 133, in remove_app_from_session
    session.remove_app(exe)
  File "/home/ervin/.config/qtile/modules/session/__init__.py", line 13, in remove_app
    self.apps.remove(exe)
ValueError: list.remove(x): x not in list
```
> If you save the wid in addition to the pid, you could disambiguate this situation with the wid instead (and still use the pid to get whatever info you wanted about it in the interim).

While this does sound interesting, I fail to see how I can use this for the problem I want to solve, which is "session" management. Some more details, perhaps? :)

I think that you misunderstood, the `pid` is actually `qtile`'s, as I thought from the beginning.

----

The `client_unmanaged` hook would allow me to get in the state before `qtile` killing the process and get the actual process `pid` that is getting killed.

I can open a PR for it, if you want me to.

**Comment by tych0** [comment]
> The client_unmanaged hook would allow me to get in the state before qtile killing the process and get the actual process pid that is getting killed.

I don't think it will: when the client is unmanaged, that means the window is dying, and the pid may exit depending on how long it takes your code to be called. (You could try putting a sleep in the hook to simulate a "long time")

> While this does sound interesting, I fail to see how I can use this for the problem I want to solve, which is "session" management. Some more details, perhaps? 

I don't really understand what problem you want to solve. It sounds like you want to maintain some state about which pids (windows) are alive. You can't use the pid, because the pid might die, and then you can't query it any more. If you use the wid, x11 will send an event for "this wid was destroyed" (i.e. DestroyNotify), and you can reason about it that way. I.e. if you maintain a `dict[wid, str]` in Session, you will be able to reason about the wid -> executable mapping, and on deletion it doesn't matter if the pid is dead, because you have the wid.

> I think that you misunderstood, the pid is actually qtile's, as I thought from the beginning.

You mean the pid returned from `get_net_wm_pid()` is qtile's? That sounds like a bug to me.

**Comment by ervinpopescu** [comment]
> I don't really understand what problem you want to solve. It sounds like you want to maintain some state about which pids (windows) are alive.

Correct.

> You can't use the pid, because the pid might die, and then you can't query it any more. If you use the wid, x11 will send an event for "this wid was destroyed" (i.e. DestroyNotify), and you can reason about it that way. I.e. if you maintain a dict[wid, str] in Session, you will be able to reason about the wid -> executable mapping, and on deletion it doesn't matter if the pid is dead, because you have the wid.

I mostly got it. I guess I'll follow this codepath.

> You mean the pid returned from get_net_wm_pid() is qtile's? That sounds like a bug to me.

I don't think it's a bug, when `qtile` sends the kill signal to the PID (which afair this is what's happening, would need to check in the code), it probably "takes the focus" (wrong description of what's actually happening, but let's roll with it). Not sure if this is the right behavior tho.

Closing this.
