### ISSUE TITLE
packaging: 0.26.0 supports wlroots 0.17 but fails to build on openSUSE

### ISSUE THREAD

**Issue by uncomfyhalomacro** [qtile/qtile#4850]
I seem to be confused with the new release. It might be a faulty source but despite repeats of getting the same sources from pypi, I get this error

https://build.opensuse.org/build/X11:windowmanagers/openSUSE_Tumbleweed/x86_64/qtile/_log

Specifically this line:

```
[   18s] + ./scripts/ffibuild -v
[   19s]     Failed!
[   19s]     This is optional and is needed for: Wayland backend
[   19s] libqtile/backend/wayland/_ffi.c:587:10: fatal error: wlr/types/wlr_idle.h: No such file or directory
[   19s]   587 | #include <wlr/types/wlr_idle.h>
[   19s]       |          ^~~~~~~~~~~~~~~~~~~~~~
[   19s] compilation terminated.
[   19s] Traceback (most recent call last):
[   19s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
[   19s]     self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
[   19s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
[   19s]     spawn(cmd, dry_run=self.dry_run, **kwargs)
[   19s]   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
[   19s]     raise DistutilsExecError(
[   19s] distutils.errors.DistutilsExecError: command '/
```

It seems to me that 0.26.0 from pypi does not ship with the updated code or am i confused here??

Relevant specfile: https://build.opensuse.org/projects/X11:windowmanagers/packages/qtile/files/qtile.spec?expand=1

Python Pywlroots specfile: https://build.opensuse.org/package/show/X11:Wayland/python-pywlroots (0.17.0)

Possible duplicate of #4604

**Comment by uncomfyhalomacro** [comment]
Seems to be some LDFLAGS thing based on the possible duplicate issue. I will try setting the flag and close this once that's done

**Comment by elParaguayo** [comment]
Those flags needed to be set previously to make sure the build pointed at wlroots 0.16. They shouldn't be needed now.

Have you actually got wlroots 0.17 installed?

**Comment by uncomfyhalomacro** [comment]
Closing. Seems the build image has not shipped yet. Sorry for the false alarm!

**Comment by elParaguayo** [comment]
All good. Let us know if you still have issues later on.
