### ISSUE TITLE
Current group lost on dgroup removal

### ISSUE THREAD

**Issue by phragment** [qtile/qtile#4870]
### Issue description

There seems to be a race condition during the auto removal of dynamically created groups.
I make intensive use of dynamic groups and notices strange behavior when dynamically created groups get removed (after closing the last window in them).
The groupbox widget doesn't highlight the current group anymore, and switching between groups using shortcuts results in the exceptions appended below.
Whats probably worse, I can (accidentally) start windows on the now "non existant group", when I then switch to another group (eg using the groupbox widget) I can never reach this "hidden" group again.

I can reproduce this by running the following script. I'm not 100% sure if this will take the same code path internally.
I tried to debug this myself, but got stuck tracking the delayed removal of the dgroup (delete_client) in libqtile/dgroups.py

```python
#!/usr/bin/env python3

import time

from libqtile.command.client import InteractiveCommandClient


if __name__ == "__main__":
    client = InteractiveCommandClient()

    # create two groups
    #   and make them active (populating group "switch stack")
    for i in range(2):
        gname = "test " + str(i)
        client.addgroup(gname)
        client.group[gname].toscreen()
        time.sleep(1)

    # cleanup
    time.sleep(1)
    for i in range(2):
        gname = "test " + str(i)
        client.delgroup(gname)
```

### Version

0.26.1.dev0+ge4b4bb8b.d20240523

### Backend

Wayland (experimental)

### Logs

```text
libqtile: KB command error prev_group: Traceback (most recent call last):
    File "/usr/lib/python3.12/site-packages/libqtile/command/interface.py", line 317, in call
     return SUCCESS, cmd(obj, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/libqtile/config.py", line 665, in prev_group
     n = self.group.get_previous_group(skip_empty, skip_managed)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/libqtile/group.py", line 432, in get_previous_group
     return self._get_group(-1, skip_empty, skip_managed)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/libqtile/group.py", line 428, in _get_group
     index = (groups.index(self) + direction) % len(groups)
          ^^^^^^^^^^^^^^^^^^
    ValueError: <group.Group ('test 0')> is not in list
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
Misclick
