### ISSUE TITLE
High CPU usage and bad performance on Intel N100

### ISSUE THREAD

**Issue by Lunitur** [qtile/qtile#4874]
### Issue description

Really bad performance on Intel N100 chipset. Everything is really laggy, like scrolling, and there is significantly higher CPU usage when idle and when using other apps e.x. Firefox. 

On sway I don't have those issues. X11 is also affected but it seems a bit better than on Wayland.

I tested this on NixOS, with both stable(24.05) and unstable channels. Also same config works just fine on other AMD/NVIDIA machines.

This is the complete log, I didn't find anything relevant skimming through it.
[qtile.log](https://github.com/user-attachments/files/15774130/qtile.log)

I feel like the problem is that everything renders on CPU instead of GPU, but I don't know why that would be or is that really happening.

### Version

0.25.0 and 0.26.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Do you get the same issues with the default config?

**Comment by Lunitur** [comment]
> Do you get the same issues with the default config?

No I do not actually... default works fine but I don't understand why that would be since it works fine on other computers.
I will try to disable some widgets or something maybe it helps, any ideas on possible solution are appreciated.

**Comment by Lunitur** [comment]
Disabling Volume widget fixed the issue.

**Comment by elParaguayo** [comment]
Thanks. That's helpful. 

Can you share your config for that widget (if you've customised it)?

Also, are there any error messages in your log file?

**Comment by Lunitur** [comment]
```
Volume(
    emoji=True,
    emoji_list=[icons.get('volume_mute','VOL_MUTE'),icons.get('volume_low','VOL_LOW'),icons.get('volume_mid','VOL_MID'),icons.get('volume_high','VOL_HI')],
    **{**theme_defaults, 'padding':2})

Volume( **{**theme_defaults, 'padding':4})

theme_defaults = dict(
            font='Hack Nerd Font Bold',
            fontsize=14,
            icon_size=14,
            padding=10,
            background=main_background,
        )
```
Yes there are errors in a log file, but nothing relevant I think.

**Comment by Lunitur** [comment]
Actually bug is present on my other desktops too, it's just I didn't notice because those CPUs are significantly faster.
