### ISSUE TITLE
Missing deprecation warnings for libqtile.command.lazy

### ISSUE THREAD

**Issue by ei-grad** [qtile/qtile#4881]
### Issue description

Updated to 0.26, and found that `libqtile.command.lazy` has been deprecated without any deprecation warnings in logs.

Looks like _LazyTree warnings don't work for some reason:
![image](https://github.com/qtile/qtile/assets/78607/cad103f4-da74-47f7-9770-3e58a393e3c1)

ImportError: cannot import name 'lazy' from 'libqtile.command'
(string to make this issue found in search results for this query)

### Version

0.26

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
`from libqtile.lazy import lazy`

**Comment by ei-grad** [comment]
Yea, sorry, I should give a proper title to the issue.

**Comment by ei-grad** [comment]
Can someone go to commit before 91d299e6 and confirm that deprecation warnings for `libqtile.command.lazy` are shown somewhere? Maybe its my environment?..

**Comment by elParaguayo** [comment]
It was deprecated a long time ago. What got dropped in the latest release was the backwards compatibility. 

I'm not sure what happened to the warnings but I suspect most users never even came across this error. You've obviously been with us for longer, so thank you!

**Comment by ei-grad** [comment]
Oh. Ok, so that is clearly very minor.
