### ISSUE TITLE
Instructions for building documentation don't seem to be up-to-date

### ISSUE THREAD

**Issue by b-jazz** [qtile/qtile#4891]
### Issue description

In the `docs/BUILDING` file, there is the following commands to run:

```
...
$ pip install -r requirements.txt
$ make html
```

But when I try to `make html`, I get the following error:

```
...
Traceback (most recent call last):
  File "/home/jasmerb/github/qtile/docs/../scripts/gen-keybinding-img", line 11, in <module>
    import cairocffi as cairo
ModuleNotFoundError: No module named 'cairocffi'
```

I `pip install cairocffi` by hand and run `make html` again and get the following error:

```
Exception occurred:
  File "/home/jasmerb/github/qtile/libqtile/scripts/migrations/change_bitcoin.py", line 20, in <module>
    import libcst as cst
ModuleNotFoundError: No module named 'libcst'

```

I notice that there is a second file called `docs/requirements-rtd.txt` that includes `libcst` and `cairocffi` and when I `pip install -r` with that file instead, the `make html` works much better. Is the `BUILDING` file out of date? I'm not sure the correct way to proceed here.

### Version

N/A

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
We also have /dev.sh, which also doesn't work right in #4858. I wonder if we can switch our CI env to using dev.sh, which will force us to maintain it and keep it working. I'm not sure about the docs though, perhaps just pointing people to a working script is enough then?

But yes, things are broken here :(
