### ISSUE TITLE
OpenWeather built-in widget wrong dispaly of min/max temp

### ISSUE THREAD

**Issue by FeralSmurf** [qtile/qtile#4894]
### Issue description

 This is my conf.

```
widget.OpenWeather(
                    location='secret', format='~{main_feels_like:.0f}°{units_temperature}, {main_temp_min:.0f}|{main_temp_max:.0f}°{units_temperature}, {weather_details}, {pressure}hPa, {wind_speed:.0f}km/h, {humidity}%H', fmt='🏙️ {}', app_key='secret'),
```
                    
everything works fine, except the min/max temp. I get the realfeel, 31 right now, but the min shows as 30 and the max as 32, which is clearly not right, unless min and max mean something else.

### Version

latest

### Backend

X11 (default)

### Config

```python
widget.OpenWeather(
                    location='secret', format='~{main_feels_like:.0f}°{units_temperature}, {main_temp_min:.0f}|{main_temp_max:.0f}°{units_temperature}, {weather_details}, {pressure}hPa, {wind_speed:.0f}km/h, {humidity}%H', fmt='🏙️ {}', app_key='secret'),
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
Is this a qtile bug? I guess that the weather reports are just inaccurate. Or are you saying that qtile is rendering stuff for the wrong location?

**Comment by FeralSmurf** [comment]
Thanks for your reply tych0!

 I'm saying the weather reports in the qtile widget are off, yes. NOT a qtile thing, but I figured it was worth mentioning it. Tried different location, same result, the min and max temps are off.

**Comment by saviola777** [comment]
> unless min and max mean something else.

According to [the documentation](https://openweathermap.org/current#min), this is the case. It's not the daily min/max temperature, but "optional parameters mean min / max temperature in the city at the current moment just for your reference." (How useful this is I cannot really say 😄 )
