### ISSUE TITLE
Black screen when changing screen with xrandr

### ISSUE THREAD

**Issue by g-wizzy** [qtile/qtile#4906]
### Issue description

I have a script to switch between my desktop monitor and my TV screen, which uses xrandr :

```sh
# ...
xrandr --output "$MONITOR" --off --output "$TV" --auto --primary
# ...
qtile cmd-obj -o root -f restart
```

I use it all the time, and it used to work with qtile. But after some update, I now get a black screen, with only my mouse cursor visible. Switching back to my desktop monitor does not solve the issue, and I have to close qtile and launch it again.

I have seen #4886, but adding a second screen to my config did not change anything.

Do you know what might cause this issue ?

### Version

0.26.1.dev0+ge4b4bb8b.d20240523

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by g-wizzy** [comment]
**Update:** I tried running `xrandr --output "$TV" --auto --primary` without turning off the main monitor, and something else happened which might be of interest. Both screens turned black, with only the cursor remaining visible (mirrored on both screens, since I only have a single screen in my qtile config). However, the desktop came back once the mouse entered a region of the screen outside of my main monitor's range.

I am puzzled as to how this happens. Does anyone have a clue how to handle this ?

**Comment by tych0** [comment]
If qtile crashed, it probably logged something somewhere. Can you look in the logs and see?

**Comment by g-wizzy** [comment]
Nothing in my qtile logs. Qtile doesn't crash, as my mouse cursor still moves. It even changes into a caret if I spawn a terminal using my qtile shortcut, indicating that qtile still works behind the black screen.

Interestingly, quitting qtile with the `lazy.shutdown()` shortcut removes the black screen for a very short moment before actually quitting.

**Comment by g-wizzy** [comment]
Well, I'm dumb. I didn't know about the `reconfigure_screens` setting. Why it worked before and ceased working only a couple weeks ago, I don't know. But it works now, and I apologize for the waste of time.
