### ISSUE TITLE
check_update widget uses a FreeBSD deprecated command 

### ISSUE THREAD

**Issue by fjpavon** [qtile/qtile#4907]
### Issue description

The pkg_version command is deprecated since FreeBSD 10.0.
In the [Release Notes](https://www.freebsd.org/releases/10.0R/relnotes/): _The pkg_add, pkg_create, pkg_delete, pkg_info, pkg_updating, and pkg_version utilities have been removed. [pkg(7)](http://www.freebsd.org/cgi/man.cgi?query=pkg&sektion=7) must now be used to install binary packages. [pkg(7)](http://www.freebsd.org/cgi/man.cgi?query=pkg&sektion=7) is the next generation FreeBSD package manager
To check the updates you have to run the command _pkg upgrade_

### Version

all versions

### Backend

X11 (default), Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by fjpavon** [comment]
Hi tych0
I want to create a pr with the new command, but i think that i have to fix my fork before. Anyway this is the output of the command in my laptop:
```
 fjp@claire  ~  pkg upgrade --dry-run                                                                                                                                                                          80%
Checking for upgrades (74 candidates): 100%
Processing candidates (74 candidates): 100%
The following 19 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	aom: 3.8.2 -> 3.8.3
	emacs: 29.3,3 -> 29.3_3,3
	firefox: 127.0_1,2 -> 127.0.2,2
	glib: 2.80.2,2 -> 2.80.3,2
	qt5-assistant: 5.15.13p4 -> 5.15.14p4
	qt5-core: 5.15.13p142 -> 5.15.14p140
	qt5-dbus: 5.15.13p142 -> 5.15.14p140
	qt5-gui: 5.15.13p142 -> 5.15.14p140
	qt5-help: 5.15.13p4 -> 5.15.14p4
	qt5-linguist: 5.15.13p4 -> 5.15.14p4
	qt5-linguisttools: 5.15.13p4 -> 5.15.14p4
	qt5-network: 5.15.13p142 -> 5.15.14p140
	qt5-printsupport: 5.15.13p142 -> 5.15.14p140
	qt5-sql: 5.15.13p142 -> 5.15.14p140
	qt5-sqldrivers-sqlite3: 5.15.13p142 -> 5.15.14p140
	qt5-svg: 5.15.13p6 -> 5.15.14p5
	qt5-widgets: 5.15.13p142 -> 5.15.14p140
	qt5-xml: 5.15.13p142 -> 5.15.14p140

Installed packages to be REINSTALLED:
	python3-3_3 (direct dependency changed: python39)

Number of packages to be upgraded: 18
Number of packages to be reinstalled: 1

130 MiB to be downloaded.
```
The --dry-run is to check only,..

**Comment by elParaguayo** [comment]
Hmm. I'm not sure that's compatible with how the widget currently works.

For the preset list of distros supported by the widget, we supply a number which is subtracted from the number of lines of the output. The output you've provided above suggests this number will not be constant as you may have some packages to be reinstalled or you may not.

We could change this so the behaviour is to do something with the output, not just the number of lines in the output.

**Comment by fjpavon** [comment]
I use awk and it seems more useful output and we don't need to touch the code....

 fjp@claire  ~  pkg upgrade -n | awk '/\t/ { print $0 }'                                             ∞
	aom: 3.8.2 -> 3.8.3
	emacs: 29.3,3 -> 29.3_3,3
	firefox: 127.0_1,2 -> 127.0.2,2
	glib: 2.80.2,2 -> 2.80.3,2
	qt5-assistant: 5.15.13p4 -> 5.15.14p4
	qt5-core: 5.15.13p142 -> 5.15.14p140
	qt5-dbus: 5.15.13p142 -> 5.15.14p140
	qt5-gui: 5.15.13p142 -> 5.15.14p140
	qt5-help: 5.15.13p4 -> 5.15.14p4
	qt5-linguist: 5.15.13p4 -> 5.15.14p4
	qt5-linguisttools: 5.15.13p4 -> 5.15.14p4
	qt5-network: 5.15.13p142 -> 5.15.14p140
	qt5-printsupport: 5.15.13p142 -> 5.15.14p140
	qt5-sql: 5.15.13p142 -> 5.15.14p140
	qt5-sqldrivers-sqlite3: 5.15.13p142 -> 5.15.14p140
	qt5-svg: 5.15.13p6 -> 5.15.14p5
	qt5-widgets: 5.15.13p142 -> 5.15.14p140
	qt5-xml: 5.15.13p142 -> 5.15.14p140
	python3-3_3 (direct dependency changed: python39)

**Comment by tych0** [comment]
We call the subprocess with `shell=True` here: https://github.com/qtile/qtile/blob/dfb7186eed9253fff9958877bb3fe1e5e0ffcf32/libqtile/widget/check_updates.py#L157

so I think your awk line will work just fine. Can you send a patch?
