### ISSUE TITLE
GroupBox - possibility to substitute group names

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#492]
Hello everyone,
I want ask about this cosmetic improvements. It would be pretty easy to do this. I can code it and send PR if you want, but there is two ways how to do it and I don't know which one suits you better.

a) Add `label=name` property to `Group` class and let `GroupBox` print it instead of `name`
b) Add dict `labels={}` to `GroupBox`. When `group.name in labels` print `labels[group.name]` instead of `group.name`

Additionally it could support substituting icons.

**Comment by iderik** [comment]
I would love this as long as you can use a font to draw icons. I think its quite common that people using fonts like FontAwesome to draw icons in other applications too, like terminal or editors. Feels more universal than using images. Not sure how many terminals that can draw images.

**Comment by Masacaai** [comment]
> A caveat is that you can not use a glyph twice, as Qtile collapses duplicate groups into a single group (I had originally wanted to use `fa-star` to label all three of my misc groups, but had to settle for the circle variants instead).

Is there any workaround for this? I want to set shape glyphs as my group names but qtile still keeps collapsing identical groups into one.

**Comment by ramnes** [comment]
Not that I know of, so let's revive this issue. I'm good with giving groups a label, or an icon, or anything that people like really.

@tych0, I do understand your concern of confusion between `name` and `label` though. What do you think of introducing an `id` value, that would take the name of the group by default, or any other value if specified, and would be used in places where the name is used today, except for the widget output? Or just rename `name` as `id`, and add `label`?

**Comment by tych0** [comment]
I don't think `s/name/id/` really fixes the confusion I was worried about, though. Fundamentally, if we care about this, we should change group_map into group_list. Anything else will be a hack.

**Comment by ramnes** [comment]
How does that change the problem? We still won't be able to match a group based on its name if two groups have the same.

**Comment by Masacaai** [comment]
I was able to get identical glyphs after all. Turns out 'labels' are already a part of the code. The documentation needs to be updated. I was able to find labels while digging through the source code for the GroupBox class. 

Identical glyphs were previously not possible because the code only used 'names' to both display and identify individual groups. The addition of a 'labels' attribute allows us to keep the names different for identification and set the same label for each group.

**Comment by tych0** [comment]
> How does that change the problem? We still won't be able to match a group based on its name if two groups have the same.

Right, but what you're suggesting is that we don't want groups to be uniquely indexed by name any more. We can't put that in a map if we want this to be true.

**Comment by Masacaai** [comment]
![2021-01-08-224825_423x27_scrot](https://user-images.githubusercontent.com/59050442/104053174-3ce63a00-5204-11eb-8aae-e77547e1fa13.png)

The relevant part of my code:

`groups = [Group(i,label='') for i in "1234567890"]
`

**Comment by ramnes** [comment]
Then it's a non-problem, great! Thanks for the heads up. :)
