### ISSUE TITLE
keyrepeat doesn't work on Qtile commands

### ISSUE THREAD

**Issue by iacore** [qtile/qtile#4920]
### Issue description

I have Super+Shift+Up Super+Shift+Down configured to resize windows.

In X11, I can hold down the keys and wait for the keyrepeat to kick in.

In Wayland, keyrepeat only works inside applications, not for Qtile. I have to hold down Super+Shift and press Up/Down repeatly for it to work.

### Version

0.26.1.dev0+ge4b4bb8b.d20240523

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by iacore** [comment]
can confirm.

**Comment by tych0** [comment]
I wonder if we really do need another release, and if we should revert my leak fixings to do so? There are a few of these kinds of fixes floating around that people have asked about.

**Comment by elParaguayo** [comment]
No objections here.

**Comment by tych0** [comment]
ok, let me prepare a revert, and we can target a release this weekend
