### ISSUE TITLE
The test_chord_widget test runs forever on Fedora Rawhide

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#4930]
### Issue description

I am maintaining the Qtile package for Fedora and while building it for Fedora Rawhide (which is going to be F41 in the future), I had to skip the `test/widgets/test_chord.py::test_chord_widget` test because it runs forever and the build eventually timeouts.

Relevant Koji build
https://koji.fedoraproject.org/koji/taskinfo?taskID=120744076

and Copr build
https://copr.fedorainfracloud.org/coprs/frostyx/qtile-rawhide/build/7731214/

It ends with

```
test/widgets/test_chord.py::test_chord_widget  !! Copr timeout => sending INT
Copr build error: Build failed
```

I couldn't gather any information that would be helpful for debugging. It works fine on Fedora 40, so maybe the relevant difference is Python 3.13 vs Python 3.12?

### Version

0.27.0

### Backend

X11 (default), Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
I wonder if this is to do with that `chord.finalize()` line at the end of the test.
