### ISSUE TITLE
adding more characters to xkeysyms.py

### ISSUE THREAD

**Issue by nizaralheet** [qtile/qtile#4931]
### Issue description

i was trying to add a translation in my config to be able to use the shortcuts while the keyboard layout is in Arabic because some shortcuts will not work like mod+w if i used arabic KBlayout it will be mod+ص so i used this function 
```
import copy
translation = {
        "w":"Arabic_sad",
        "r":"Arabic_qaf",
        "v":"Arabic_ra",
        "f":"Arabic_beh",
        "t":"Arabic_feh",
        "b":"Pointer_DfltBtnNext" # the problem is here 
        }

def translate_key(key):
    key = copy.copy(key)
    key.key = translation[key.key]
    return key
keys += [translate_key(key) for key in keys if key.key in translation]
```
it was gooing good until i wanted to add the b key , the Arabic key will be ﻻ (la) -which is a combination of two two chracters- but i can't find it [here](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/xkeysyms.py) so i tried to look for it one my system at ```/usr/share/X11/xkb/symbols/ara``` and i found it's name was "UFEFB" i look for it's UTF-16 which is 0xFEFB  and found it  equivalent to Pointer_DfltBtnNext on the xkeysyms.py ,it is working now but  it took me some time to find that , so i am not sure if you could add it as a key to xkeysyms.py or not .
-btw  is a major key in the arabic layout not used a lot but due to that it the same english b key-

### Version

0.26.1.dev0+ge4b4bb8b.d20240714

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
If it's missing, I think we should add it. Is it in this list somewhere? https://github.com/qtile/qtile/blob/ff90e5cfae7418ad62d0accc3cb38757fca2cdb9/libqtile/backend/x11/xkeysyms.py#L959-L1039

if not, can you send a patch to add it there?

**Comment by elParaguayo** [comment]
I have no objection to adding keys if they're missing. However, I would note that we merged keycode support recently. This would enable you to bind keys, irrespective of the layout.

**Comment by nizaralheet** [comment]
> I have no objection to adding keys if they're missing. However, I would note that we merged keycode support recently. This would enable you to bind keys, irrespective of the layout.
nice this would be even better .
