### ISSUE TITLE
Can not install with wayland on Linux Mint 22

### ISSUE THREAD

**Issue by agoodfellow123** [qtile/qtile#4945]
### Issue description

I am trying to install Qtile with wayland on Linux Mint 22.
I did install pywlroots from pipx and still I got the error "Backend 'wayland' missing required Python dependencies: wlroots" when I ran "qtile start -b wayland".
Exact same issue persists on FreeBSD, only difference being instead of pipx I used pkg.

### Version

0.27.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment]
You need `wlroots` on top of `pywlroots`

**Comment by agoodfellow123** [comment]
I have installed all the libwlroots packages including libwlroots-dev with apt. Same problem.

**Comment by jwijenbergh** [comment]
Ah right I think I see the issue, you can't install pywlroots from pipx, you need to install it with regular pip. Pipx install it in its own environment

**Comment by kaistian** [comment]
> Ah right I think I see the issue, you can't install pywlroots from pipx, you need to install it with regular pip. Pipx install it in its own environment

You can with `pipx inject` it installs packages in an environment, check out `man pipx`

**Comment by jwijenbergh** [comment]
> > Ah right I think I see the issue, you can't install pywlroots from pipx, you need to install it with regular pip. Pipx install it in its own environment
> 
> You can with `pipx inject` it installs packages in an environment, check out `man pipx`

I doubt OP did that?

**Comment by agoodfellow123** [comment]
Is it a good idea to install via pip on Debian based systems? Or a separate environment?

**Comment by cr1ogen** [comment]
I don't know why but in Debian I have to compile pywroots from source for it to work and not give that error.. Try that
