### ISSUE TITLE
`pip3 install qtile[all]` fails with "Failed building wheel for xkbcommon" 

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [qtile/qtile#4946]
### Issue description

```
Building wheels for collected packages: xkbcommon
  Building wheel for xkbcommon (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for xkbcommon (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/xkbcommon
      copying xkbcommon/xkb.py -> build/lib.linux-x86_64-cpython-312/xkbcommon
      copying xkbcommon/__init__.py -> build/lib.linux-x86_64-cpython-312/xkbcommon
      copying xkbcommon/ffi_build.py -> build/lib.linux-x86_64-cpython-312/xkbcommon
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.c'
      creating build/temp.linux-x86_64-cpython-312
      building 'xkbcommon._ffi' extension
      creating build/temp.linux-x86_64-cpython-312/build
      creating build/temp.linux-x86_64-cpython-312/build/temp.linux-x86_64-cpython-312
      gcc-11 -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/linuxbrew/.linuxbrew/opt/python@3.12/include/python3.12 -c build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.c -o build/temp.linux-x86_64-cpython-312/build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.o
      build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.c: In function ‘_cffi_const_XKB_CONTEXT_NO_SECURE_GETENV’:
      build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.c:1017:12: error: ‘XKB_CONTEXT_NO_SECURE_GETENV’ undeclared (first use in this function); did you mean ‘_cffi_const_XKB_CONTEXT_NO_SECURE_GETENV’?
       1017 |   int n = (XKB_CONTEXT_NO_SECURE_GETENV) <= 0;
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |            _cffi_const_XKB_CONTEXT_NO_SECURE_GETENV
      build/temp.linux-x86_64-cpython-312/xkbcommon._ffi.c:1017:12: note: each undeclared identifier is reported only once for each function it appears in
      error: command '/usr/bin/gcc-11' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xkbcommon
Failed to build xkbcommon
ERROR: Could not build wheels for xkbcommon, which is required to install pyproject.toml-based projects
```

At the same time I have already `libxkbcommon-dev` installed:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxkbcommon-dev is already the newest version (1.4.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

*os*: Ubuntu 22.04.4 LTS x86_64
*pip3 --version*: pip 24.0 from /home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/site-packages/pip (python 3.12)

### Version

Unknown

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
https://github.com/sde1000/python-xkbcommon/issues/26

**Comment by EmilyGraceSeville7cf** [comment]
What should I do?

**Comment by tych0** [comment]
upgrade your xkbcommon to >= 1.5

**Comment by EmilyGraceSeville7cf** [comment]
When I try `pip3 install xkbcommon` it [fails](https://github.com/sde1000/python-xkbcommon/issues/27). Any ideas?

**Comment by sde1000** [comment]
If you're on Ubuntu 22.04, you don't have version 1.5 of libxkbcommon so you can't install python-xkbcommon version 1.5 or later.

You could try `pip3 install 'xkbcommon<1.1'`

**Comment by sde1000** [comment]
qtile should fix this by changing `xkbcommon>=0.3` to `xkbcommon<1.1`:
https://github.com/qtile/qtile/blob/ff90e5cfae7418ad62d0accc3cb38757fca2cdb9/setup.cfg#L40

**Comment by elParaguayo** [comment]
But what about those users who do have libxkbcommon > 1.5?

**Comment by tych0** [comment]
when would it be safe to unpin?

**Comment by sde1000** [comment]
"Never", approximately.

When the libxkbcommon API is extended (rare, but it happened in versions 1.5 and 1.6) then I add support for the new API features in python-xkbcommon and make a release with corresponding new major and minor version numbers. If you try to install python-xkbcommon 1.5 on a system that does not have at least libxkbcommon version 1.5, it will fail.

I'm not dropping support for versions of python-xkbcommon that work with earlier libxkbcommon API versions — at the moment I'm actively supporting branches for 1.0, 1.5 and (when released) 1.6. If your project doesn't make use of the new libxkbcommon API features, you don't need a newer branch of python-xkbcommon. If you depend on `xkbcommon<1.1` then you'll pick up new releases in the 1.0 branch automatically.

I considered alternatives:

* I could leave "xkbcommon" at version 1.0, and release "xkbcommon15", "xkbcommon16", and so on with the later libxkbcommon dependencies, but that would probably cause additional confusion.
* I could try to make python-xkbcommon adapt to the libxkbcommon version installed on the system. This appears to be an absolute pain to do with python-cffi, though!

**Comment by elParaguayo** [comment]
Presumably that doesn't cause an issue for packagers on distros that have more up-to-date packages (e.g. Arch) as they build with the "--no-isolation" flag so the dependencies list will be ignored.

**Comment by sde1000** [comment]
That's right - and distributions should have the appropriate version of python-xkbcommon packaged to match their version of libxkbcommon.
