### ISSUE TITLE
StatusNotifier Widget shows fallback icon for Gajim

### ISSUE THREAD

**Issue by phragment** [qtile/qtile#4948]
### Issue description

The StatusNotifier widget does not show the correct icons for Gajim states.

Short rundown:

The IconThemePath property of StatusNotifierItems is not part of the XDG spec https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/ and seems to be a kind of hack ( https://mail.kde.org/pipermail/plasma-devel/2010-March/010679.html ) which KDE introduced and cannot get rid of anymore, they removed it in KDE 6 but readded it ( https://bugs.kde.org/show_bug.cgi?id=479712 ) because programs already rely on it.

Therefore it is not entirely clear what a correct IconThemePath is.

Adding some debug in _get_local_icon() ( libqtile/widget/helpers/status_notifier/statusnotifier.py ) show me that Gajim sets:
icon_name: dcraven-offline
icon_path: /usr/lib/python3.12/site-packages/gajim/data/icons

This  fails because _get_custom_icon() assumes (reasonably) that the icon will be directly within the icon_path.
But Gajim installs a whole icon theme hierarchy under site-packages/gajim:

> $ pacman -Ql gajim | grep icons
gajim /usr/lib/python3.12/site-packages/gajim/data/icons/hicolor/index.theme
gajim /usr/lib/python3.12/site-packages/gajim/data/icons/hicolor/scalable/
gajim /usr/lib/python3.12/site-packages/gajim/data/icons/hicolor/scalable/status/dcraven-offline.svg
...

### Version

0.27.1.dev0+g17cc04b3.d20240714

### Backend

X11 (default), Wayland (experimental)

### Logs

```text
libqtile: Cannot find icon in current theme and no icon provided by StatusNotifierItem.
libqtile: Could not find icon for 'dcraven-offline'. Using fallback icon.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by phragment** [comment]
I would propose a simple subdir search as possible solution, as implemented in the referenced feature branch.
Of course I'm open for code improvements or alternate solutions.

**Comment by elParaguayo** [comment]
Just so I understand, are you saying that the icon does exist in a subfolder of the provided `icon_path`?

**Comment by phragment** [comment]
Yes, the icon exists in a subfolder of the provided icon_path.
Gajim even installs a proper icon_theme hierarchy under its site-package directory, as shown in the package manager output. (But I think it would be too complicated to parse the whole theme.)

A subdir search could even be considered as replacement for _get_custom_icon.

**Comment by elParaguayo** [comment]
OK - let me implement something and I'll let you know when it's read to test.

**Comment by elParaguayo** [comment]
Could you try running #4955 and let me know if that works.

**Comment by phragment** [comment]
I just tested your pullrequest and can confirm it working.
Thank you very much!
