### ISSUE TITLE
Custom shortcut keys need to be pressed twice to be effective

### ISSUE THREAD

**Issue by hulutouer** [qtile/qtile#4950]
##### qtile 0.27.1.dev0+g17cc04b3.d20240714

---

- Hello, I have been trying to use qtile recently
- I am trying to implement the function of switching between the two nearest workgroups
- Added two functions

```python
last_group = [None]
current_group = [None]
@hook.subscribe.setgroup
def update_last_group():
    global last_group, current_group
    current = qtile.current_group.name
    if current_group[0] != current:
        last_group[0] = current_group[0]
        current_group[0] = current
def switch_to_last_group(qtile):
    global last_group, current_group
    if last_group[0]:
        qtile.groups_map[last_group[0]].toscreen()
        current_group[0], last_group[0] = last_group[0], current_group[0]
Keys = [
    ...
    Key([mod], "Escape", lazy.function(switch_to_last_group), desc="Switch to last group"),
]
```

> When I try to switch to the previous workgroup by pressing the shortcut key, I need to press `super+esc` twice

```log
Partial log information:
2024-08-07 11:02:02,937 ERROR libqtile hook.py:fire():L193 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/hook.py", line 191, in fire
    i(*args, **kwargs)
TypeError: update_last_group() missing 1 required positional argument: 'caller'
```

I tried to add a `caller` parameter to `update_1ast_group()`
`update_last_group(caller)`
The `super+esc` shortcut key will not work
Can you try to help me analyze where the problem lies
Thanks!
my [config.py ](https://github.com/hulutouer/dotfiles/blob/main/qtile/config.py)

### Version

0.27.1.Dev0+G17CC04B3.D20240714

### Backend

X11 (default)

### Config

```python
https://github.com/hulutouer/dotfiles/blob/main/qtile/config.py
```

### Logs

```text
Partial log information:
2024-08-07 11:02:02,937 ERROR libqtile hook.py:fire():L193 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/hook.py", line 191, in fire
    i(*args, **kwargs)
TypeError: update_last_group() missing 1 required positional argument: 'caller'
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
That config runs fine for me. Mod + Escape switches to the last group.

**Comment by hulutouer** [comment]
If we were in the first working group now,
When I press super+4 to switch to the fourth workgroup,
Pressing super+esc will switch to the first workgroup
When I try to switch back to the fourth workgroup again, I need to press super+esc twice to achieve it
I hope it can be achieved with just one press

**Comment by hulutouer** [comment]
qtile.groups_map[last_group[0]].toscreen(toggle=True)
Effectively solved the problem I described
