### ISSUE TITLE
The instructions for installing Qtile on Fedora is outdated.

### ISSUE THREAD

**Issue by PaperCyb** [qtile/qtile#4969]
### Issue description

Both **X11** and **Wayland** Stable versions of Qtile can now be found in Fedora's repository as of **Fedora 40**.

They can also be installed just using the DNF package manager.

---

Fedora's Repo
https://packages.fedoraproject.org/pkgs/qtile/qtile/
or
https://src.fedoraproject.org/rpms/qtile

### Version

0.27.0

### Backend

X11 (default), Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by PaperCyb** [comment]
Just can't decide on a name for this.

**Comment by tych0** [comment]
Can you send a patch to update the docs?

**Comment by PaperCyb** [comment]
Okay, I believe Its done now.
Just waiting for it to be reviewed and approved.

I tried to make the instructions as clear as possible but let me know If there's anything I should add or remove.
