### ISSUE TITLE
TreeTab Layout, using `increase_ratio` results in weird window names

### ISSUE THREAD

**Issue by c0rydoras** [qtile/qtile#4979]
### Issue description

I tried to `increase_ratio` for the `TreeTab` layout, it does work but the window names dont scale (it does weird things)

![image](https://github.com/user-attachments/assets/a7363aee-0f93-4b66-8fcd-bbc0c2cd8210)
After calling `increase_ratio` a couple times:
![image](https://github.com/user-attachments/assets/994d72ba-3abe-48c9-96b6-00535e019421)

I expected it to not look this cursed.

How to reproduce:

1. Add tree tab layout to configuration
2. Add keybinding for `lazy.layout.increase_ratio()`  
3. Reload config
4. Open window in tree tab layout
6. Use Keybinding for increasing ratio

observe issue

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Config

```python
-
```

### Logs

```text
-
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. That looks very odd. I'll take a look later.

**Comment by c0rydoras** [comment]
![24-08-29__12-01-36__screenshot](https://github.com/user-attachments/assets/bfcac48b-3ee8-4e8b-b3e2-c69577364f58)
it does even weirder things without `place_right=True`

**Comment by elParaguayo** [comment]
Please test #5008

**Comment by c0rydoras** [comment]
Sadly this doesn't fix it

**Comment by elParaguayo** [comment]
That's odd. I can't recreate the issue with this fix applied.

Did you restart qtile?
