### ISSUE TITLE
Dropdown not centering on screen despite dimensions

### ISSUE THREAD

**Issue by Shringe** [qtile/qtile#4986]
### Issue description

I want to set a "maximized" dropdown. Whenever I set the dimensions accordingly, the dropdown is a couple pixels to the bottom right of where it should be, leaving a small gap in the upper left, and hanging slightly off the screen on the bottom right.
![scratchpad_off_center](https://github.com/user-attachments/assets/228ce60b-5ce2-4429-a42a-b94cf7d590c6)
The bottom and right borders being off-screen is the easiest way to see this effect.

This seems to happen to all dropdowns actually, but it is most noticeable here.

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Config

```python
groups: list = [
    Group("1", layouts=[primary_layout]),
    Group(
        "2",
        layouts=[VerticalTile],
        matches=[Match(wm_class="strawberry"), Match(wm_class="tidal-hifi")],
    ),
    Group("3", layouts=[primary_layout]),
    Group("4", layouts=[primary_layout]),
    Group("5", layouts=[primary_layout]),
    Group("6", layouts=[primary_layout]),
    Group("7", layouts=[primary_layout]),
    Group("8", layouts=[primary_layout]),
    Group("9", layouts=[primary_layout]),
    ScratchPad(
        "0",
        [
            DropDown(
                "khal",
                format_tui("ikhal", apps.terminal),
                opacity=1,
                x=0.7,
                y=0.0,
                width=0.3,
                height=1,
            ),
            # FULLSCREEN DROPDOWN HERE
            DropDown(
                "music",
                format_tui(apps.music_player, apps.terminal),
                opacity=0.6,
                x=0.0,
                y=0.0,
                width=1,
                height=1,
            ),
            DropDown(
                "terminal",
                apps.terminal,
                x=0.25,
                y=0.15,
                width=0.5,
                height=0.7,
            ),
        ],
    ),
]
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
I wonder if this is to do with the border widths. I'll take a look later.

**Comment by elParaguayo** [comment]
Found the problem. Will work on a fix when I can.
