### ISSUE TITLE
Doesn't start without a config file

### ISSUE THREAD

**Issue by superbobry** [qtile/qtile#50]
It was surprising to see the following, after resolving `pangocairo` problem:
    $ qtile
    Traceback (most recent call last):
      File "/usr/bin/qtile", line 72, in <module>
        main()
      File "/usr/bin/qtile", line 58, in main
        c = confreader.File(options.configfile)
      File "/usr/lib/python2.7/site-packages/libqtile/confreader.py", line 51, in **init**
        raise ConfigError("Config file does not exist: %s"%fname)
    libqtile.confreader.ConfigError: Config file does not exist: /home/bobry/.config/qtile/config.py

Why doesn't `qtile` copy default config to `~/.config/qtile/`? or at least use default settings behind the scenes.

**Comment by acornejo** [comment]
IU just installed qtile from the ppa and got this exact same error.. why was this issue closed?

**Comment by flacjacket** [comment]
You need to use a more recent version, this bug was fixed 3 years ago, you
can see the commit that did it above. You should check the docs on qtile.org
for how to install a current version with pip.

**Comment by acornejo** [comment]
@flacjacket thanks so much! as a sidenote, are the ppa's deprecated and shouldn't be used anymore?
