### ISSUE TITLE
Allow multiple systray's for multiple monitor configurations

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#500]
From the X standard [1], only one window can function as a systray (i.e. get the `_NET_SYSTEM_TRAY_S0` selection), which prohibits 2 Systray widgets from running. It would be nice if the systray could be configured to display in multiple locations when you have things like multiple monitors.

[1] http://standards.freedesktop.org/systemtray-spec/systemtray-spec-latest.html

**Comment by FrostyX** [comment]
Personally, I would like to see a `fallback=""` parameter for the `Systray` widget, so that I can render some text in place of the systray on the secondary monitors, so my panel doesn't look weird :-)

**Comment by m-col** [comment]
This limitation of the protocol is one of the (many) reasons that many DEs/projects have moved onto using the Status Notifiter Item spec instead, so if we get a widget for that working (https://github.com/qtile/qtile/issues/1523) then maybe we can happily ignore the problems the systray causes us :)

**Comment by elParaguayo** [comment]
This feels like a "won't fix" type issue unless someone's got a realistic way of implementing it. As per m-col's post above, this is an inherent limitation of the protocol.
