### ISSUE TITLE
last cairo 1.18.0-2 update breack pulse volume widget 

### ISSUE THREAD

**Issue by nizaralheet** [qtile/qtile#5000]
### Issue description

hi , after the last update for cairo on Arch it now break the PulseVolume widgets and even qtile-extras image popups  , i am not sure is it a qtile issue or  the cairo 

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
This should be fixed in latest git version.

**Comment by nizaralheet** [comment]
yes it is done 👍
