### ISSUE TITLE
Qtile Layout borders bug?

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#5025]
### Issue description

When I move or resize a window, it loses the normal border color and the focused border, in the configuration options.
It happens in all layouts.

Here is a video with the problem https://www.youtube.com/watch?v=ruI1pbG02o4

### Version

0.28.2.dev33+g4785b51e

### Backend

Wayland (experimental)

### Config

```python
from libqtile import layout
from libqtile.config import Match
from modules.colors import colors

# Setup layout Theme

layout_theme = {
     "border_width":7,
     "margin":16,
     "border_focus":colors[1], #['orange'],
     "border_normal":colors[0], #['dark'],
     "single_border_width": 8,
 }

layouts = [
    layout.MonadTall(**layout_theme),                   
    layout.Max(**layout_theme),
    layout.MonadWide(**layout_theme),
    layout.Floating(**layout_theme),
    # layout.RatioTile(),
    # layout.Tile(),
    # layout.TreeTab(),
    # layout.VerticalTile(),
    # layout.Zoomy(),
]

floating_layout = layout.Floating(
 float_rules = [
        # Run the utility of `xprop` to see the wm class and name of an X client.
        *layout.Floating.default_float_rules,
        Match(wm_class="confirmreset"),  # gitk
        Match(wm_class="makebranch"),  # gitk
        Match(wm_class="maketag"),  # gitk
        Match(wm_class="waypaper"),  # ssh-askpass
        Match(title="branchdialog"),  # gitk
        Match(title="pinentry"),  # GPG key password entry
        ],
)
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by MoonCubes** [comment]
You need to include your border colors in the `floating_layout` variable.

```python
floating_layout = layout.Floating(
 border_focus=colors[1],
 border_normal=colors[0],
 float_rules = [
        # Run the utility of `xprop` to see the wm class and name of an X client.
        *layout.Floating.default_float_rules,
        Match(wm_class="confirmreset"),  # gitk
        Match(wm_class="makebranch"),  # gitk
        Match(wm_class="maketag"),  # gitk
        Match(wm_class="waypaper"),  # ssh-askpass
        Match(title="branchdialog"),  # gitk
        Match(title="pinentry"),  # GPG key password entry
        ],
```

**Comment by cr1ogen** [comment]
> You need to include your border colors in the `floating_layout` variable.
> 
> ```python
> floating_layout = layout.Floating(
>  border_focus=colors[1],
>  border_normal=colors[0],
>  float_rules = [
>         # Run the utility of `xprop` to see the wm class and name of an X client.
>         *layout.Floating.default_float_rules,
>         Match(wm_class="confirmreset"),  # gitk
>         Match(wm_class="makebranch"),  # gitk
>         Match(wm_class="maketag"),  # gitk
>         Match(wm_class="waypaper"),  # ssh-askpass
>         Match(title="branchdialog"),  # gitk
>         Match(title="pinentry"),  # GPG key password entry
>         ],
> ```

the borders colors is in this variable

```layout_theme = {
     "border_width":7,
     "margin":16,
     "border_focus":colors[1], #['orange'],
     "border_normal":colors[0], #['dark'],
     "single_border_width": 8,
 }
 ```
I also tried as you told me in case I was wrong and it keeps doing the same thing and not working. Thanks

**Comment by elParaguayo** [comment]
When you move or resize a window, it becomes a floating window so the above suggestion was correct.

Are you applying `layout_theme` to the frosting layout definition? It's not a standard variable and won't be applied automatically.

**Comment by cr1ogen** [comment]
I just added MoonCubes suggestion and the same thing happens (the video is made with the floating layer anyway).
I didn't understand this `Are you applying layout_theme to the frosting layout definition` , should I add or remove something else? Thanks
![241011_21-32-27](https://github.com/user-attachments/assets/a259d410-12a7-40e4-b8e5-b791c26333dc)

**Comment by elParaguayo** [comment]
Remove the `Floating` layout from `layouts` - it's not really meant to be used there.

When you move/resize a window, it becomes a floating window but it's not using that `Floating` layout in your `layouts` list. So, you need to add `**layout_theme` to the layout defined in `floating_layout`.

**Comment by cr1ogen** [comment]
![241012_23-25-13](https://github.com/user-attachments/assets/bf7fde3f-fb8c-4c95-9c61-02fa63b11e3d)

Im removed Floating layout from layout and add `**layout_theme` to `floating_layout` im tried with 
```
floating_layout = layout.Floating(
 border_focus=colors[1],
 border_normal=colors[0],
```
and nothing change when move/resize the windows, the border focus and border normal becomes blue.

**Comment by elParaguayo** [comment]
Is this in `config.py` or a separate file? If it's a different file, you need to make sure that `floating_layout` is imported into `config.py` otherwise you'll just use the default value.

**Comment by MoonCubes** [comment]
@cr1ogen  From [your config file](https://github.com/cr1ogen/cr1odots/blob/main/config/qtile/config.py) I can see that you have this line: 
```py
from modules.layouts import layouts
```
You need to add `floating_layout` to the imports for it to work
```py
from modules.layouts import layouts, floating_layout
```

**Comment by cr1ogen** [comment]
Thank to  @MoonCubes,and @elParaguayo  now works, and sorry for the inconvenience.

**Comment by cr1ogen** [comment]
> @cr1ogen From [your config file](https://github.com/cr1ogen/cr1odots/blob/main/config/qtile/config.py) I can see that you have this line:
> 
> ```python
> from modules.layouts import layouts
> ```
> 
> You need to add `floating_layout` to the imports for it to work
> 
> ```python
> from modules.layouts import layouts, floating_layout
> ```

Thank you
