### ISSUE TITLE
Newly opened windows appear to be floating until group has been switched back and forth

### ISSUE THREAD

**Issue by tcld** [qtile/qtile#5034]
### Issue description

I'm having some issues with the most recent Qtile-master, in particular [this PR](https://github.com/qtile/qtile/pull/4426) seems to be where those issues originate (just did a bisect):

When I open a new terminal (terminator) or browser (firefox), the windows open up unmaximized at the center of the screen (I've tested Bsp- and Treetab-layouts), almost as if they were floating windows. They take up about a quarter of the space available on the screen for me.
After switching to another group and back the windows are displayed the way the layouts should display them. Any new windows suffer from the same issue, though.

I haven't found anything interesting in the Qtile-log.

@elParaguayo fyi

### Version

dev 284e6dc16be6f8a9ba6e94b597f498078371c397

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Very odd. I can't recreate this. Windows open normally for me.

**Comment by jwijenbergh** [comment]
Did you try the default config?

**Comment by elParaguayo** [comment]
Yes

**Comment by ervinpopescu** [comment]
Huh, I get the same issue with my config but not with the default one. Interesting. I only tested default before...

**Comment by elParaguayo** [comment]
Hmm. If multiple users are saying this then I'm inclined to revert for now.

**Comment by ervinpopescu** [comment]
If it's config generated, I would say revert is not needed. @tcld can you please confirm if default config generates this?

**Comment by tcld** [comment]
I'm using my setup for work right now, and I don't know how to quickly test this (and restart from the default config afterwards) without disrupting things too much. Maybe I can try in about four or five hours.

**Comment by jwijenbergh** [comment]
Do you have the floating layout in your layouts?

**Comment by tcld** [comment]
No, I don't.

**Comment by tcld** [comment]
I checked the default configuration, specifically at https://github.com/qtile/qtile/commit/284e6dc16be6f8a9ba6e94b597f498078371c397 . I see the issue there as well.

For completeness, I modified the default config slightly by adding these keys (otherwise I just copied the "default_config.py" into a fresh ".config/qtile"-folder and renamed it to "config.py"):
```python
    Key([mod, "shift", "control"], "r", lazy.restart(), desc="Restart Qtile."),
    Key([mod], "b", lazy.spawn("firefox"), desc="Launch browser."),
    Key([mod], "t", lazy.spawn("terminator"), desc="Launch terminal."),
```

Also, I restarted Qtile via `lazy.restart()`, which apparently doesn't lead to the fullest of restarts (I saw my old groups in addition to the default ones, but iirc that's a pretty old issue).

**Comment by tcld** [comment]
`master` is running fine again, thank you for reverting the commit.

If there is any more insight I can give to help find the root cause, let me know.
