### ISSUE TITLE
LibreOffice not rendered correctly until group has been switched back and forth

### ISSUE THREAD

**Issue by saviola777** [qtile/qtile#5043]
### Issue description

Ever since 284e6dc16be6f8a9ba6e94b597f498078371c397, opening LibreOffice on the Max layout will render only a tiny bit of the UI, clicking around and opening a menu will increase the window size accordingly, but it will never show the entire window. Switching groups back and forth fixes the issue.

Very closely related to #5034.

I've tried poking around the offending commit to see if I can maybe understand what's going on and fix it, but I failed. Some questions that have come up:

- the code seems to be closely aligned to the fullscreen code, using the `auto_fullscreen` option (see [group.py#L259](https://github.com/qtile/qtile/blob/284e6dc16be6f8a9ba6e94b597f498078371c397/libqtile/group.py#L258), if `auto_fullscreen` is set to `False` in the config, this issue disappears), is this correct?
- [group.py#L265](https://github.com/qtile/qtile/blob/284e6dc16be6f8a9ba6e94b597f498078371c397/libqtile/group.py#L265) and following check for `fullscreen`, but not for `maximized`. Is this correct?

Well, I guess I don't really understand the code, but I tried! I don't really understand `auto_fullscreen` either.

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Config

```python
auto_fullscreen = True
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by MoonCubes** [comment]
`auto_fullscreen` is used to fullscreen / maximize windows automattlicly. This might happen if the window has a maximize button or a fullscreen option. If this is set to `False` windows will only go fullscreen / maximize with a keypress. Libreofffice remembers that it was previously maximized and wants to maximize again when it is opened. For some reason some windows like libreoffice that want to be maximized when they are opened, don't get rendered correctly.

**Comment by saviola777** [comment]
Yeah, I believe the implementation is not correct (or does not lead to the expected results at least), but that's a story for another issue.

This one is fixed with the recent revert.
