### ISSUE TITLE
RectDecoration makes the systray hide

### ISSUE THREAD

**Issue by RVSmooth** [qtile/qtile#5048]
### Issue description

Before RectDecoration

![2024-10-20_06-13](https://github.com/user-attachments/assets/b2fd5e27-5f16-46c8-935a-fa99464a1803)

After RectDecoration
![2024-10-20_06-15](https://github.com/user-attachments/assets/812c3b1c-771e-4d7d-854f-578d667398f7)

applied decoration,

```
decoration_group = {
        "foreground": colors[11],
        "padding": 10,
        "decorations": [
            RectDecoration(colour=colors[1], radius=13, filled=True, padding_y=4, group=True)
            ]
}

```

my picom conf: https://pastebin.com/5T5uem1M
* same issue with 0.29.0 as well

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Those images look identical to me.

Also, if you think the issue is `RectDecoration` then this should be posted in qtile-extras, not here.

**Comment by RVSmooth** [comment]
> Those images look identical to me.
> 
> Also, if you think the issue is `RectDecoration` then this should be posted in qtile-extras, not here.

sorry I uploaded wrong images, edited
