### ISSUE TITLE
Zoom screenshare leaves behind zombie windows

### ISSUE THREAD

**Issue by Etn40ff** [qtile/qtile#5065]
### Issue description

 After a zoom call with screenshare some fake window remains in qtile stack of managed windows even though the window does not exists anymore. This messes up both with navigation commands and with appearence. In the following example the right side of the screen is unusable.

```
[ins] In [1]: from libqtile.command.client import InteractiveCommandClient
          ...: c = InteractiveCommandClient()
          ...: c .group.info()
Out[1]:
{'name': '5',
 'label': '5',
 'focus': 'VulK@bunion: ipython',
 'tiled_windows': {'VulK@bunion: ipython', 'zoom'},
 'windows': ['VulK@bunion: ipython'],
 'focus_history': ['VulK@bunion: ipython'],
 'layout': 'columns',
 'layouts': ['max', 'columns'],
 'floating_info': {'name': 'floating', 'clients': []},
 'screen': 1}
```
![image](https://github.com/user-attachments/assets/852b3e73-cd4e-47dd-829f-aaab133e2528)

### Version

0.29.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
Can you get an xprop for one of these zombie windows?

**Comment by Etn40ff** [comment]
I am having a hard time reproducing the problem; it usually happens with a specific person so I'll need to ping them to try. I'll update this as soon as I can.

Meanwhile let me say that I tried xprop when I first encountered the issue and I am almost sure that it returned the properties of the root window. Unfortunatey I do not have any log handy. 

PS: for what it is worth I also have the following hook subscription:
```
# Float Zoom's notifications but not all the rest
@hook.subscribe.client_managed
def managed_hook(window):
    if (
        "zoom" in window.get_wm_class()
        and window.get_hints()["base_width"] in [ 0, 355]
        and window.get_hints()["base_height"] == 0
    ):
        window.enable_floating()
```
but this should not be the root of the problem since the zombies are always tiled windows.

**Comment by tych0** [comment]
I wonder if the window has died but somehow the layout didn't know about it?

> Meanwhile let me say that I tried xprop when I first encountered the issue and I am almost sure that it returned the properties of the root window.

suggests to me that there was some "hole"; especially in light of your hook to always make zoom windows float, it seems like some layout didn't like this. Which layout was it?

**Comment by Etn40ff** [comment]
Here you go:
```
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x1e0004e
WM_CLASS(STRING) = 
_NET_WM_ICON_NAME(UTF8_STRING) = 
CUT_BUFFER0(STRING) = ""
_QT_GET_TIMESTAMP(INTEGER) = 
_NET_ACTIVE_WINDOW(WINDOW): window id # 0xb000003
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x2800004, 0x2800011, 0x3a00004, 0x4800004, 0x980001e, 0x9800033, 0x9800059, 0x3600003, 0x340000e, 0x9c00003, 0x8e00003, 0x540000e, 0x140000e, 0x2000003, 0x8600004, 0x2400003, 0x2800096, 0x5600003, 0xc800003, 0xee00003, 0x640000a, 0x8800046, 0x6000003, 0xb000003
_NET_CLIENT_LIST(WINDOW): window id # 0x2800004, 0x2800011, 0x3a00004, 0x4800004, 0x980001e, 0x9800033, 0x9800059, 0x3600003, 0x340000e, 0x9c00003, 0x8e00003, 0x540000e, 0x140000e, 0x2000003, 0x8600004, 0x2400003, 0x2800096, 0x5600003, 0xc800003, 0xee00003, 0x640000a, 0x6000003, 0x8800046, 0xb000003
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 2560, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_CURRENT_DESKTOP(CARDINAL) = 4
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "8", "9"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 9
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_STATE, _NET_WM_STRUT_PARTIAL, _NET_WM_PID, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_STATE_MODAL, _NET_WM_STATE_STICKY, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_FOCUSED
PULSE_COOKIE(STRING) = "1ed59d7ee96c86b21cd1ffaa7d26fc544195d0c6a6e72a99a17b902394b75ca710168372fd41c6da4025f59e4b3625ba1a75340158aa52aac3780705faf289a373911785abc6d4a559d2610cb30e9432a773f48838e942f6374e6ad607e248cb5ef4465f216fa7c6adb8309c5ab1bc4a30f03f5174f9c3d553abc21ce7b2f1e09275d5089f9b085370f5287b244509afe549dc9db7623c40f289ea9ed5892ea8d3522d879a461e7f4575b77f523b79289db4e48ff51726fea2a7cca345cf8afa3d6ffb1c4b0bf03338fa68efad10446868ec6a39218c977a4bfd75cdf20cdd20dad0a898d3daeca4c35926292361844f1e6c90e76c0c212497954ff3f0d2fe65"
PULSE_SERVER(STRING) = "{17080d4e4d3049461091d62854ec7079}unix:/run/user/1000/pulse/native"
PULSE_SESSION_ID(STRING) = "2"
PULSE_ID(STRING) = "1000@17080d4e4d3049461091d62854ec7079/8447"
RESOURCE_MANAGER(STRING) = "xterm*reverseVideo:\ttrue\nxterm*saveLines:\t500\n"
AT_SPI_BUS(STRING) = "unix:path=/run/user/1000/at-spi/bus_0.0,guid=e84648e777925a9c15f1e206671abd36"
GDK_VISUALS(INTEGER) = 1383, 1591
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 9, -27, 110, 8, 0, 0, 0, 0, 1, 29, 1, 4, -91, 34, 19, 120, 3, 88, -11, -90, 88, 85, -99, 38, 14, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -106, 59, -128, 54, 113, 56, 60, 64, 48, 32, 54, 0, 88, -62, 16, 0, 0, 26, -85, 47, -128, 54, 113, 56, 60, 64, 48, 32, 54, 0, 88, -62, 16, 0, 0, 26, 0, 0, 0, -2, 0, 66, 79, 69, 32, 67, 81, 10, 32, 32, 32, 32, 32, 32, 0, 0, 0, -2, 0, 78, 86, 49, 53, 54, 70, 72, 77, 45, 78, 54, 49, 10, 0, -71
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x200005
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us,il", "qwerty", "compose:caps,terminate:ctrl_alt_bksp,grp:shifts_toggle"
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
```
I am not sure in which layouts this happens but I am using Max, Columns, and Treetab

**Comment by tych0** [comment]
That looks like the xprop for the root window, which suggests that there is a hole. Can you get qtile's view of the group via its shell to see which window it thinks is there?

**Comment by Etn40ff** [comment]
Is this what you want?
```
% qtile shell
 > cd group/5
group[5]
group[5] > info()
{'floating_info': {'clients': [], 'name': 'floating'},
 'focus': 'VulK@bunion: qtile shell',
 'focus_history': ['VulK@bunion: qtile shell'],
 'label': '5',
 'layout': 'columns',
 'layouts': ['max', 'columns'],
 'name': '5',
 'screen': 0,
 'tiled_windows': {'zoom', 'VulK@bunion: qtile shell'},
 'windows': ['VulK@bunion: qtile shell']}
```

**Comment by tych0** [comment]
Yeah, so it looks like `tiled_windows` has `zoom`, but presumably that is the window that has disappeared. Do you get a `DestroyNotify` for this window? (https://github.com/qtile/qtile/blob/059a3596d9668b5dce40abc44e76362d695004b8/libqtile/backend/x11/core.py#L771-L777 would be the place to log)

My guess is that you do get DestroyNotify, but there is some logic bug in the layouts. 

I suppose another option is: since you're marking this as floating, maybe the transition from tiled -> floating is broken for some layouts?

**Comment by Etn40ff** [comment]
I'll try again tomorrow without those floating rules. If the bug is still there I'll try to add some log to `handle_DestroyNotify` as you suggest.

**Comment by Etn40ff** [comment]
I had no chance to reproduce the bug yet but I had to restart qtile today (it was messing up with my multimonitor setup but that's a story for another bug report) and I realized that after restart my log is spammed by things of the form 
```
2024-11-07 21:29:16,941 ERROR libqtile core.py:_xpoll():L359 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 334, in _xpoll
    self.handle_event(event)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 301, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 773, in handle_DestroyNotify
    if self.qtile.current_window is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window
```

**Comment by tych0** [comment]
Yes, I also have a fix for this one in #5020, but last time we landed it it caused a bunch of other problems. I would appreciate any testing on that branch as well.

**Comment by Etn40ff** [comment]
I will give #5020 a spin when I have a little of free time.

Meanwhile I am runnin a X session on which I had several occurrences of the bug
and several qtile restarts (a single restart is sufficient to maka the "hole"
disappear). It looks like the zombie windows are still there but are not handled
by qtile though:

```
[ins] In [1]: from libqtile.command.client import InteractiveCommandClient
[ins] In [2]: import re
[nav] In [3]: c = InteractiveCommandClient()
[ins] In [4]: len([ x for x in c.windows() if re.search('zoom',x['name']) ])
Out[4]: 2
[ins] In [4]: len([ x for x in c.windows() if re.search('Zoom',x['name']) ])
Out[5]: 2
```

while
```
% xdotool search --class --name  . | xargs -n 1 xdotool getwindowname | grep zoom | wc
     12      32     176
% xdotool search --class --name  . | xargs -n 1 xdotool getwindowname | grep Zoom | wc
     12      51     359
```

This looks like a bug in zoom but I doubt it will ever be addressed. Zoom does some horrible things to windows.

**Comment by tych0** [comment]
So this is the other way then right? The window exists, but qtile seems to have forgotten about it somehow?

Since you have the list of wids, can you get the xprop from these stray zoom ones?

**Comment by Etn40ff** [comment]
It looks like there are plenty of ids that are not managed by qtile. I assume
these are not really windows (e.g systray icons, compositor, etc.).

```
[ins] In [1]: from libqtile.command.client import InteractiveCommandClient
[ins] In [2]: import re
[ins] In [3]: c = InteractiveCommandClient()
[ins] In [4]: import subprocess
[ins] In [5]: qtile_ids =  [ x['id'] for x in c.windows() ]
[ins] In [6]: xorg_ids = map(int,subprocess.Popen(["xdotool", "search", "--class", "--name", "."],stdout=subprocess.PIPE).stdout.readlines())
[nav] In [7]: with open("/tmp/outfile","a") as outfile:
         ...:      for x in xorg_ids:
         ...:          if x not in qtile_ids:
         ...:              print("####################################################################################",file=outfile, flush=True)
         ...:              print("#", x,file=outfile, flush=True)
         ...:              print("####################################################################################",file=outfile, flush=True)
         ...:              p = subprocess.Popen(["xprop", "-id", str(x)] , stdout=outfile)
         ...:              p.wait()

```
[outfile](https://paste2.org/ayZILMvX)

**Comment by tych0** [comment]
Thank you! Most of that looks normal (e.g. the clipboard ones are doing the clipboard protocol, the systray ones we don't add to the `windows` list but do manage via the systray protocol, etc.

But for your stray zoom ones, this jumps out at me:
```
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
```
our code assumes the first window type is the one we understand, but I can imagine a world in which the atoms get added in the other order, and our code fails. Can you try https://github.com/tych0/qtile/commit/6a470bfc20238c9b7783cdbde083684cdbfcfbb6 and see if that fixes it? I need to write a real commit message, but hopefully the code is obvious enough.

If that's not it, then I wonder if:
```
		window gravity: Static
```

is wonky, but I don't see how that would be *racy* as you describe.

**Comment by Etn40ff** [comment]
I tried the patch but nothing changed for the zombie windows already there. I had to restart my session so I do not have zombies anymore to test on. I'll keep the patch loaded and I will report when I have another occurrence.

**Comment by tych0** [comment]
Huh, ok. I think we should probably apply the patch anyway because it does fix a bug, but maybe not yours. I'll try to have a look soon at the window gravity thing

**Comment by tych0** [comment]
Whoops, I didn't mean to close this until we actually know that it's resolved.

**Comment by Etn40ff** [comment]
Life got in the way and I did not have time to test this thoroughly yet

**Comment by Etn40ff** [comment]
I can confirm that the bug is not fixed by #5076

**Comment by Etn40ff** [comment]
Bump

**Comment by nazar-pc** [comment]
Looks similar to https://github.com/qtile/qtile/issues/4915

**Comment by Etn40ff** [comment]
Still here

**Comment by tych0** [comment]
Can you add this logging? https://github.com/qtile/qtile/issues/5065#issuecomment-2460842724

I am still suspicious that we don't remove the window correctly, but it is unclear exactly how.

**Comment by Etn40ff** [comment]
Yes I can, I do not use zoom often and the bug appears sporadically so it might take me a while to report back (I am willing to do some test calls if someone is available). Do you want me to log only the calls to `handle_DestroyNotify` or do you need something more?

**Comment by tych0** [comment]
To be honest, I'm not really sure what we need. I think DestroyNotify is a good place to start, but the more logging you have the better. Knowing what happens in `libqtile/core/manager.py::unmanage()` would also be useful. e.g. if the window is not in the windows map already, that might explain it, or if the `c.group.remove()` bit in there is not called for some reason. So maybe the type of the window as well?
