### ISSUE TITLE
Switching workspaces sometimes takes seconds!

### ISSUE THREAD

**Issue by G1ya777** [qtile/qtile#5080]
### Issue description

This problem started recently. I tried without picom, it didn't stop the issue. 

### Version

0.29.1.dev0+geed1e03c.d20241021

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by G1ya777** [comment]
I just tried, the issue is gone with the default config.

**Comment by jwijenbergh** [comment]
Can you share your config?

**Comment by G1ya777** [comment]
I found what's causing the issue, its the ThermalSensor widget. commenting the line `widget.ThermalSensor(tag_sensor="Tctl", threshold=80),` in my config fixed the issue.

**Comment by tych0** [comment]
hi - can you try the above patch? I think that'll fix your issue.
