### ISSUE TITLE
prompt widget closes on window spawn

### ISSUE THREAD

**Issue by 3hhh** [qtile/qtile#5089]
### Issue description

If a window spawns while one is entering a command inside the prompt widget, the window apparently steals the focus, closes the prompt and the command may go to the new window (if one is still typing).
This is rather annoying and may also leak information to windows (imagine a web page window) for which it's not supposed.

I suppose the same _may_ happen for other widgets, too, but I haven't verified that.

### Version

0.29.0

### Backend

X11 (default)

### Config

```python
https://github.com/3hhh/qubes-qtile
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
Yeah, I have noticed this too. I personally have `focus_on_window_activation = "never"` and it still does it, maybe it shouldn't in this case? But in the other cases (e.g. "smart"), I think it is still reasonable to focus the default window? Not sure, I could be convinced otherwise.

**Comment by 3hhh** [comment]
I doubt that the window actually requested focus; that's probably why `focus_on_window_activation` has no effect in this case.

It's however weird that this behaviour even bypasses `window.can_steal_focus()`, which [I overwrite](https://github.com/3hhh/qubes-qtile/blob/master/config.py#L119).
I'd vote to at least respect that function.

I'm not 100% sure about other default behaviour changes as it may have to be decided per widget type:
A widget designed to open windows may want to pass focus to these windows; the prompt widget may usually never want to pass focus.
A per-widget setting may be ideal, but probably also a lot of code...

**Comment by tych0** [comment]
oh, yeah, `can_steal_focus()` is nice; then people could do the same thing you are, or check if the prompt widget is open or whatever.
