### ISSUE TITLE
Backlight widget has high latency and slows system with stutters when using `ddcci` + `brightnessctl` with external monitor

### ISSUE THREAD

**Issue by raj-magesh** [qtile/qtile#5119]
### Issue description

When using `ddcci` to control the brightness of an external monitor, enabling the Qtile backlight widget makes my computer stutter pretty seriously, causing e.g. key repeats when typing and cursor flickering. CPU usage also seems to spike.

Right now, I'm using `brightnessctl` to control the external monitor since `ddcci` exposes it as a backlight in `/sys/class/backlight`:

```{python}
widget.Backlight(
    format="{percent:2.0%}",
    backlight_name="ddcci8",
    brightness_file="actual_brightness",
    max_brightness_file="max_brightness",
    change_command="brightnessctl set {0}%",
    step=5,
    update_interval=0.2,
    foreground=COLORS["backlight"],
)
```

This works, but there is significant latency between my input on the widget and the monitor brightening. I'd like to:

- get rid of the stutters when the backlight widget is enabled
- reduce the latency between my input and the screen brightening (`brightnessctl` has low latency on the command line, so it seems to be a widget issue)

### Version

0.29.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
Can you quantify significant here? I haven't looked at the code in detail, but if you switch to qtile's built-in udev rules and brightness management, it won't need to exec another process and that should be faster.

**Comment by tych0** [comment]
> I'm not sure if Qtile automatically supports external monitors? Without installing ddcci and configuring some udev rules, the monitor isn't exposed in /sys/class/backlight, which appears to be necessary.

Yeah, we don't have udev rules for specific hardware.

> There's perhaps 0.5 s latency between scrolling once on the widget and the brightness adjusting. Also, the cursor is stuck on the widget for that duration (stutters a lot when I move it after the scroll). Scrolling multiple steps at once slows it more. Keyboard inputs are also slowed.

If you have the right rules and write perms (you're in the groups that ddcci configures in its udev stuff, etc.) qtile has a mode where it'll write to the file directly: https://github.com/qtile/qtile/blob/cc122253f5d7e76047869f213113b5963e79ffa4/libqtile/widget/backlight.py#L138-L146 and that should be faster.

But I agree, it's weird that it hangs. How many widgets do you have on your bar? The code *looks* like it should be async, unless you have lots of blocking IO going on, which could max out the threadpool, and then it would be blocking.
