### ISSUE TITLE
Can't find a way to make titlebars float on windows

### ISSUE THREAD

**Issue by 42e6** [qtile/qtile#5126]
### Issue description

The [docs](https://docs.qtile.org/en/stable/) don't mention how we can modify title bars, such as by making them float over windows (to implement auto-hide for titlebars like status bar's auto hide).

Is it even possible to do this with qtile? 

### Version

0.29.0

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
I'm not sure I understand what you're trying to do.

Qtile doesn't generate title bars for windows so doesn't control their appearance/behaviour.

**Comment by 42e6** [comment]
So, when I have a stack of tabbed/stacked windows, there is no titlebar or a tabs list?  Usually almost all window managers place them on top of the windows.

**Comment by elParaguayo** [comment]
Qtile doesn't generate title bars for windows. There is the treetab layout which will put names of windows on the side of the screen but I suspect that's not quite what you want.

As for the borders, most layouts allow for different border colours depending on whether the window is focused on not. You can use qtile-extras to set conditional border widths if you want finer control.

**Comment by 42e6** [comment]
The titlebar approach is fine. I even find the qtile approach better.

But, about the borders, can I make the borders "float" or "hover" over the window content?

Basically, I want borders to appear only when I press $mod, then disappear as I release $mod.

**Comment by elParaguayo** [comment]
No, that's not currently possible in qtile.

**Comment by 42e6** [comment]
What's the point of qtile then? I  thought it was in python "cause flexible"....... can't even make my owner border go floaty?

**Comment by elParaguayo** [comment]
What a bizarre reaction....

Anyway, that's why I said "currently". It's not implemented but you're welcome to hack the code to make it do what you want.

**Comment by 42e6** [comment]
How easy is it to make floaty borders? Or what are the approaches that you'd recommend?

**Comment by elParaguayo** [comment]
The hardest bit is actually getting qtile to do something while the key is held down and then released as qtile doesn't currently listen for both press and release events.

Skipping that bit, you'd need to do something like the following:
```python
from qtile_extras.layout.decorations import ConditionalBorderWidth

SHOW_BORDER = False


@lazy.function
def toggle_border(qtile):
    global SHOW_BORDER
    SHOW_BORDER = not SHOW_BORDER
    qtile.current_group.layout_all()
```
In the various layout definitions, you'd set `border_width=ConditionalBorderWidth(default=0, matches=[(Match(func=lambda win: SHOW_BORDER), 2)])`

You can then set a key binding to toggle the status, e.g. `Key([mod], "z", toggle_border)`

**Comment by 42e6** [comment]
Why can't qtile listening to press/release vents?

**Comment by elParaguayo** [comment]
It can.  We just don't do that currently so it would need more code to be rewritten.

**Comment by 42e6** [comment]
Can borders be rendered above windows?  Like hover around the edge?

E.g. if a border's thickness is 10 pixels, then those 10 pixels render on top of the windows, not on the outside.  Ideally with some opacity/transparency to see through a bit.

**Comment by elParaguayo** [comment]
> Can borders be rendered above windows? Like hover around the edge?
> 
> E.g. if a border's thickness is 10 pixels, then those 10 pixels render on top of the windows, not on the outside. Ideally with some opacity/transparency to see through a bit.

Probably, yes, but only with a bigger rewrite of the codebase.

> I think your code only disables borders?
> 
> ```python
> @lazy.function
> def toggle_border(qtile):
>     global SHOW_BORDER
>     SHOW_BORDER = not SHOW_BORDER
>     qtile.current_group.layout_all()
> ```

No, it does exactly what it says. It toggles that status. `SHOW_BORDER` will change between `True` and `False` each time that function is called. The `layout_all()` call will tell qtile to redraw the windows at which point it checks to see the status of `SHOW_BORDER` which will determine the border width.

**Comment by 42e6** [comment]
Ok, someone kindly do this:
- Add support to floating borders.
- Add support for press/release events.

These are necessary to catapult qtlite to new heights unfathomable by life form in the whole history of the cosmos.

**Comment by elParaguayo** [comment]
The first might happen. The second is unlikely.

**Comment by 42e6** [comment]
The reason this is important, is because, we can completely delete borders, and make them appear only when `Mod4` is pressed.

This is really nice, because we will see borders only when we care, otherwise we make 100% utilisation of the monitor space.

The same with titlebars, this way, titlebars can be rendered overlaid the window itself, including stacks/tabs/trees/etc, and only show when `Mod4` is pressed.

I don't see why no one wants this when it's so nice it must be the standard WM experience.

**Comment by elParaguayo** [comment]
Please do not confuse your own desires with that of other users. For example, I have no desire/need for any of the features you think are important.

**Comment by 42e6** [comment]
My "desires" are objectively optimal..... You're just like the scientific insights to know the superior UI..... you're like those who were happy with old Nokia phones and thought that iPhone's touch interface wasn't good.

**Comment by elParaguayo** [comment]
You know nothing about me. We're done here.
