### ISSUE TITLE
X11: Initially fullscreen mpv is not resized/positioned correctly

### ISSUE THREAD

**Issue by saviola777** [qtile/qtile#5130]
### Issue description

When using mpv with the configuration option `fullscreen=yes` and the (default) qtile configuration setting of `auto_fullscreen = True`, the mpv window is initially rendered centered on the screen in the original video resolution, i.e. the window is not resized or repositioned to appear fullscreen. This should be true for other applications that want to start in fullscreen mode, but it might not and I don't have any other applications to test at the moment.
I have a bar at the top and at the bottom. If the video resolution is the same as the screen resolution the video is rendered starting below the top bar and exceeding the screen at the bottom by the same margin (hiding the bottom bar).
Pressing `f` to toggle (leave) fullscreen correctly maximizes the window between the two bars, pressing `f` to toggle fullscreen again correctly goes into fullscreen, hiding both bars.

What I have identified as (one of) the areas in the code that cause this issue is

https://github.com/qtile/qtile/blob/5fe89de8343d0e7f6b88468b712b1dbfaa83efc5/libqtile/group.py#L255-L275

In particular, the line

```python
win._float_state = FloatStates.FULLSCREEN
```

This directly changes the internal `_float_state`, skipping the relevant [setter code](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/window.py#L1803). The setter code is also not called from [update_state()](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/window.py#L659) because of the check `if getattr(self, attr) != val` – the getter for `fullscreen` already returns `True`.

Simply changing the above-mentioned line to

```python
win.fullscreen = True
```

fixes the issue for me, mpv is correctly spawned in fullscreen mode covering the whole screen.

The question is: why are we directly setting the `_float_state` in `group.add()` instead of calling the setter? The same logic should apply to floating as well, is there a reson we do not simply use `win.floating = True`? That would also render the lines

https://github.com/qtile/qtile/blob/5fe89de8343d0e7f6b88468b712b1dbfaa83efc5/libqtile/group.py#L264-L265

unnecessary, because they are essentially replicated in the setter:

https://github.com/qtile/qtile/blob/5fe89de8343d0e7f6b88468b712b1dbfaa83efc5/libqtile/backend/x11/window.py#L1751-L1752

I can create a PR with these two changes (or at least with the fullscreen one), but I first wanted to hear your opinions and thoughts because for now I'm assuming there is a good reason why we skip the setters here.

Possibly related to a lot of other issues like #5043, #5034, #4058, #4176, #3814, #2415, #2163

### Version

0.29.0+fd6b2cd.flake

### Backend

X11 (default)

### Config

```python
auto_fullscreen = True
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by MoonCubes** [comment]
this might be related to #5034 and #5043

**Comment by Gurjaka** [comment]
I have same issue on wayland, flameshot doesn't start fullscreen, instead it is tiled just like any other application

**Comment by saviola777** [comment]
> I have same issue on wayland, flameshot doesn't start fullscreen, instead it is tiled just like any other application

I'm not sure if this is the same, because mpv is actually not tiled (more like a floating window which hides the bottom bar), basically just the size and position is wrong.

**Comment by Gurjaka** [comment]
> > I have same issue on wayland, flameshot doesn't start fullscreen, instead it is tiled just like any other application
> 
> I'm not sure if this is the same, because mpv is actually not tiled (more like a floating window which hides the bottom bar), basically just the size and position is wrong.

oh I didn't understand ig, but isn't this issue about applications not starting fullscreen?

**Comment by saviola777** [comment]
Yes, in some way: mpv is asking to start in fullscreen and it thinks its in fullscreen, and qtile also thinks it's in fullscreen. But because the code that actually makes a window fullscreen is never executed, the window size and position is wrong.
It might be similar in Wayland, maybe you can try it with mpv and the config I mentioned above?

**Comment by Gurjaka** [comment]
> Yes, in some way: mpv is asking to start in fullscreen and it thinks it's in fullscreen, and qtile also thinks it's in fullscreen. But because the code that actually makes a window fullscreen is never executed, the window size and position is wrong (in my limited understanding). It might be similar in Wayland, maybe you can try it with mpv and the config I mentioned above?

I will try later today

**Comment by elParaguayo** [comment]
Your proposed fix makes sense to me. I'm not sure why we're not using the setters. I wonder if @tych0 knows.

I'd be inclined to submit a PR with your fix and see if that causes any issues with the test suite!

**Comment by tych0** [comment]
I don't know offhand why we don't use them, though in general setters are a code smell in our code base to me. 

That said, the PR is net negative lines, so it's a clear improvement!
