### ISSUE TITLE
Allow some windows to be prevented from stealing focus

### ISSUE THREAD

**Issue by Magicloud** [qtile/qtile#537]
For example pidgin new conversation dialog, which will take input focus and interrupt my inputting flow.

**Comment by kynikos** [comment]
Why was this closed? I think it was a valid request, and if #568 is merged, also easy to implement: just add a new boolean configuration option, and test it in `window._Window.can_steal_focus()`.

However, I'd like to discuss more in general the possibility to let users define, in the configuration file, custom focus-stealing tests to be evaluated in `window._Window.can_steal_focus()`, for example to decide what windows can steal focus depending on their type or role, like the `Match` objects for groups.

**Comment by tych0** [comment]
On Fri, Jan 02, 2015 at 07:37:43AM -0800, Dario Giovannetti wrote:
> Why was this closed? I think it was a valid request, and if #568 is merged, also easy to implement: just add a new boolean configuration option, and test it in `window._Window.can_steal_focus()`.
> 
> However, I'd like to discuss more in general the possibility to let users define, in the configuration file, custom focus-stealing tests to be evaluated in `window._Window.can_steal_focus()`, for example to decide what windows can steal focus depending on their type or role, like the `Match` objects for groups.

I've been thinking about this for a while, and I don't see a nicer way
to do it than sticking something like this in peoples' configs:

```
no_focus_steal = [
  Match(...),
  Match(...),
]

Did you have something more dynamic in mind?

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/qtile/qtile/issues/537#issuecomment-68534998

**Comment by kynikos** [comment]
I think a `no_focus_steal` list like that would be perfect! Do you want to reopen this issue so it doesn't get forgotten?

**Comment by kynikos** [comment]
After 6 months I thought I would bump this one :) Can we reopen?

**Comment by flacjacket** [comment]
Sure, this seems valid

**Comment by oscar-carlsson** [comment]
Agreed; this is a function I would have a lot of use for, and it's been 9 years since this was opened. Is there any update on this?

**Comment by tych0** [comment]
I think nobody has written a patch for this in those nine years. Maybe now someone will!
