### ISSUE TITLE
Floating windows with two screens and cursor_warp

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#538]
As we seen on IRC, when a floating window pop from an application on one screen, it almost always goes on the other screen. Worse, if `cursor_warp` is active, the floating window on the other screen become completely unusable: each click that is done on it warp the cursor to the original screen.

I didn't take a look at the code on this one, but it seems to me that the fix would just be to always pop floating windows on the current screen.

**Comment by ramnes** [comment]
If someone had time to fix that one, that would be a huge relief to me. :+1:

**Comment by flacjacket** [comment]
I think the most recent commit should fix this, at the very least, it should place the dialog windows on the correct screen for the group that they are placed in, so it might still warp you when the dialog comes up, but you should be able to interact with the dialog without warping off again. Let me know if this a still not quite fixed and feel free to reopen this.

**Comment by ramnes** [comment]
wuuuuuuuuuuut

**Comment by ramnes** [comment]
Okay, so the fact that the cursor was coming back to the other screen seems fixed.

**Though**, windows are still placed on the wrong screen with a simple config. I just tried with Gimp on screen 2, and clicked on "File > Open...", and it appeared on screen 1.

With my config, the problem is mitigated, thanks to the following part:
```python
@hook.subscribe.client_new
def set_floating(window):
    floating_types = ["notification", "toolbar", "splash", "dialog"]
    floating_roles = ["EventDialog", "Msgcompose", "Preferences"]
    floating_names = ["Terminator Preferences"]

    if (window.window.get_wm_type() in floating_types or
        window.window.get_wm_window_role() in floating_roles or
        window.window.get_name() in floating_names or
        window.window.get_wm_transient_for()):

        screen = window.qtile.find_closest_screen(window.x, window.y)
        window.floating = True
        window.x = int(screen.width / 2 - window.width / 2)
        window.y = int(screen.height / 2 - window.height / 2)
```
