### ISSUE TITLE
Bar transparency

### ISSUE THREAD

**Issue by eskin** [qtile/qtile#541]
Please, add support for transparent bar. Maybe then qtile will be more popular =)

**Comment by prateekamana** [comment]
@eskin I tried that but it also makes the text trasnparent, how would one go about making just the background transparent?

**Comment by elParaguayo** [comment]
@prateekamana that comment you replied to is almost 7 years old.

Transparency has been added to the bar and widgets. See here: http://docs.qtile.org/en/latest/manual/config/screens.html

You'll need v0.18 for this to work.

If you have any problems, please start a new issue.

**Comment by prateekamana** [comment]
I'm sorry for the necrobump, I just did
```
background="#000000.3", opacity=1,
```
and it worked.
