### ISSUE TITLE
Qtile doesn't remember windows order when restarting

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#549]
When restarting Qtile, windows order inside layouts isn't kept.

**Comment by kynikos** [comment]
#372 is related.

**Comment by tych0** [comment]
In fact, aren't they dupes?

**Comment by ramnes** [comment]
They are.

**Comment by kynikos** [comment]
I thought the other one was only about the stack layout and this one was generic :) I'm fine if you want to close it.
