### ISSUE TITLE
pycharm white window

### ISSUE THREAD

**Issue by whoizit** [qtile/qtile#558]
latest qtile
latest pycharm
dialog open/create project works, but main window is blanked. But elements on window still clickable. toggle_floating, mouse dragging haven't effect. Running pycharm in console -> empty output, didn't have warnings or errors

http://rghost.ru/59507329.view
http://ix.io/16m/

pycharm on lxqt with openbox works well

**Comment by pawamoy** [comment]
Happened to me 5 years later :slightly_smiling_face: Yet the bug reports linked in a previous comment say they are fixed?

I had changed the `wmname` string to `qtile` (for a tool similar to `neofetch`). Changed it back to `LG3D` and PyCharm works now...

It also works when simply exporting `_JAVA_AWT_WM_NONREPARENTING=1` so I'll put back `qtile` as `wmname`.
