### ISSUE TITLE
Notification widget not working

### ISSUE THREAD

**Issue by CraigBarnesOpusVL** [qtile/qtile#570]
With the recent changes to get dbus working again, I'm still not seeing the notification widget working.

I am running in Python 3.4 on Debian Jessy.

notify-send no longer blocks followed by timout error, but the widget is not displaying sent text.

**Comment by tych0** [comment]
Have you checked that qtile actually sees the messages and just doesn't display them? (i.e. something in the widget linkage is broken?)

**Comment by cjbarnes18** [comment]
I've not dug into the code yet, but having set the background to the notification widget I can see that it gets it's length changed when I run notify-send.

**Comment by cjbarnes18** [comment]
Are there any other widgets that use pango to set the text style?

**Comment by cjbarnes18** [comment]
I have just removed markup=True from the notification widget and now text appears, so pango markup appears to the broken.

**Comment by tych0** [comment]
On Sun, Jan 11, 2015 at 10:59:46AM -0800, Craig Barnes wrote:
> I have just removed markup=True from the notification widget and now text appears, so pango markup appears to the broken.

Yeah, that' doesn't surprise me unfortunately. I suspect pangocffi's
markup parsing is broken somehow (the only other widget that uses
pango markup right now is the google calendar widget, and it was
seeing crashes).

I just pushed some patches a few days ago to allow setting
self.foreground in widgets at any time, so if you're just using the
markup to change colors, perhaps that's a more reliable way to do it?
We should in any case fix pangocffi, but that's a workaround for now.

**Comment by cjbarnes18** [comment]
Unfortunately bold is also used to indicate the notification heading.

Do you have any ideas where to start hunting for this?

**Comment by tych0** [comment]
On Sun, Jan 11, 2015 at 11:50:13AM -0800, Craig Barnes wrote:
> Unfortunately bold is also used to indicate the notification heading.
> 
> Do you have any ideas where to start hunting for this?

Yeah, my guess is that libqtile.pangocffi.parse_markup is probably
broken, and that we're either using the api from pango_parse_markup
incorrectly or our ffi.string() call is wrong somehow (perhaps we
shouldn't dereference text? I'm not sure). I'm guessing if you look at
the result of parse_markup, it'll be an empty string.

**Comment by cjbarnes18** [comment]
strange stuff...

I have a simple script that sets a text wiget on my bar.
```python
#!/home/craig/qtile/venv3/bin/python
from libqtile.command import Client
from sys import argv

def set_note(c, text):
    c.widget['note'].update(text)

def clear_note(c):
    set_note(c, '')

if __name__ == '__main__':
    c = Client()
    if len(argv) > 1:
        text = ' '.join(argv[1:])
    else:
        clear_note(c)
        exit(0)
    current = c.widget['note'].get()
    if current > '':
        text = current + ' | ' + text
    set_note(c, text)
    exit(0)
```
and in my config I have set that textbox to markup=True

The following works as expected (except shadow is same colour as text, and there is no bold (but that may be my font)).
```sh
 $ note '<span weight="bold" color="green">H</span><span color="red">e</span><span color="brown">l</span><span color="yellow">l</span><span color="purple">o</span><span color="cyan">!</span> <span color="yellow">Tyc0 {^v^}</span>'
```
But this gives me an exception from my script and sets the widget to have a space in it and nothing else (which is the same as notify)
```sh
 note '<crap>crap</crapity> crap crap'
Traceback (most recent call last):
  File "/home/craig/bin/note", line 21, in <module>
    set_note(c, text)
  File "/home/craig/bin/note", line 6, in set_note
    c.widget['note'].update(text)
  File "/home/craig/qtile/libqtile/command.py", line 113, in __call__
    return self.call(self.selectors, self.name, *args, **kwargs)
  File "/home/craig/qtile/libqtile/command.py", line 248, in call
    raise CommandException(val)
libqtile.command.CommandException: Traceback (most recent call last):
  File "/home/craig/qtile/bin/libqtile/command.py", line 93, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/home/craig/qtile/bin/libqtile/widget/textbox.py", line 33, in cmd_update
    self.update(text)
  File "/home/craig/qtile/bin/libqtile/widget/textbox.py", line 26, in update
    self.text = text
  File "/home/craig/qtile/bin/libqtile/widget/base.py", line 178, in text
    self.layout.text = value
  File "/home/craig/qtile/bin/libqtile/drawer.py", line 37, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
  File "/home/craig/qtile/bin/libqtile/pangocffi.py", line 253, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'<crap>crap</crapity> crap crap'
```
An additional point yo note is that there are no error in the qtile log, only the exception from Client
So I see 2 issues.  
1. It seems that the text set in notify is perceived to be invalid syntax even though it looks OK.
2. We aren't logging the exception when there is a format error.

**Comment by cjbarnes18** [comment]
looks like hex might be the issue
