### ISSUE TITLE
Mouse clicks on the bar shouldn't steal focus from other windows

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#572]
When clicking on a widget in the bar that doesn't explicitly give focus to another window, the focus stays on the bar. This happens for example when clicking on a Systray icon, or on the GroupBox icon for the currently selected group, or on the tab of the currently focused window in the Tasklist widget.
Some widgets, though, should better keep the focus, for example Prompt.

**Comment by drunkbear** [comment]
I guess just ignoring internal windows like 1ca566022ef9185cdc300403125cc9ab883230c2 will do the thing?

**Comment by frostidaho** [comment]
@drunkbear your solution works for me, thanks.

**Comment by flacjacket** [comment]
Just pushed @drunkbear's commit, should be fixed in develop
