### ISSUE TITLE
Vertical bar

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#573]
It would be nice if the bar could also be shown vertically at the left/right sides of the screeen.
This is very easy to implement for the bar itself, but of course the problem is that widgets should support this too.
I think however that not all widgets should necessarily support the vertical orientation, and this could be solved widget-by-widget by moving the test in [bar.py#L155](https://github.com/qtile/qtile/blob/develop/libqtile/bar.py#L155) to a new `bar._HWidget` class that inherits from the existing `bar._Widget` class, so that horizontal-only widgets could derive from it, including `bar._TextBox`. Of course a `bar._VWidget` class should be created too, for completeness' sake. As widgets are given the ability to adapt to the bar orientation, they can be made to inherit directly from `bar._Widget`.

**Comment by tych0** [comment]
On Sat, Jan 10, 2015 at 08:40:29PM -0800, Dario Giovannetti wrote:
> It would be nice if the bar could also be shown vertically at the left/right sides of the screeen.
> This is very easy to implement for the bar itself, but of course the problem is that widgets should support this too.
> I think however that not all widgets should necessarily support the vertical orientation, and this could be solved widget-by-widget by moving the test in [bar.py#L155](https://github.com/qtile/qtile/blob/develop/libqtile/bar.py#L155) to a new `bar._HWidget` class that inherits from the existing `bar._Widget` class, so that horizontal-only widgets could derive from it, including `bar._TextBox`. Of course a `bar._VWidget` class should be created too, for completeness' sake. As widgets are given the ability to adapt to the bar orientation, they can be made to inherit directly from `bar._Widget`.

This is a nice idea (and perhaps even useful for people whose native
languages aren't RTL or LTR ones). Does pango support up/down
rendering of glyphs? If so, then it seems we'd want textbox to support
both horizontal and vertical rendering as well.

I'm not convinced that inheritance is the best design for this,
though, since some widgets would need both rendering methods, and to
switch between them at runtime. Perhaps just a set of constants, and
each widget somehow asserts when qtile starts that the bar orientation
requested is something that it supports?

**Comment by kynikos** [comment]
Ok, it's possible that we're misunderstanding each other: in my proposal, all widgets would inherit from `bar._Widget` in any case, either directly or through the `bar._{H,V}Widget` classes (they'd inherit from `bar._Widget`). `bar._Widget` would support both rendering methods, choosing it according to the bar orientation: this means that all widgets would support both rendering methods. The only thing that the `bar._{H,V}Widget` classes would do is the "assert[ion] when qtile starts that the bar orientation requested is something that it supports", so that we don't have to duplicate that test in every widget that needs it.

**Comment by tych0** [comment]
On Sun, Jan 11, 2015 at 08:54:43PM -0800, Dario Giovannetti wrote:
> Ok, it's possible that we're misunderstanding each other: in my proposal, all widgets would inherit from `bar._Widget` in any case, either directly or through the `bar._{H,V}Widget` classes (they'd inherit from `bar._Widget`). `bar._Widget` would support both rendering methods, choosing it according to the bar orientation: this means that all widgets would support both rendering methods. The only thing that the `bar._{H,V}Widget` classes would do is the "assert[ion] when qtile starts that the bar orientation requested is something that it supports", so that we don't have to duplicate that test in every widget that needs it.

Yeah, I'm just wondering if inheritance is the best model given that
the superclasses would essentially have one assert in them. Seems like
it would be easier just to add the assert.

**Comment by kynikos** [comment]
Uh now I get it, I agree. Maybe another idea to preserve a centralized orienation assertion would be to add a `horizontal=True` and `vertical=True` parameters to `_Widget`'s `__init__`, so that a subclass can call it with e.g. `vertical=False` to indicate that vertical orientation is not supported; in `_Widget.__init__` it would be asserted with something like `is_bar_horizontal() or vertical` (`is_bar_horizontal()` is to give you the idea, I haven't actually thought of how to test the top/bottom/left/right setting in `_Widget`).

**Comment by tych0** [comment]
Yeah, there are probably lots of reasonable ways to do it, I just wanted to
avoid a complicated inheritance hierarchy :). I'm happy to review any code
you have before/when you PR it, though!

On Wed, Jan 14, 2015 at 3:12 AM, Dario Giovannetti <notifications@github.com

**Comment by kynikos** [comment]
Adaptation of widgets is now tracked in #652, closing.
