### ISSUE TITLE
Separate widget polling from TextBoxes

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#575]
Currently, all polling classes subclass _TextBox, I think ideally, the polling classes would be standalone (as subclasses or decorators?) and text/icons/etc would be added into widgets separately. I think this might mess up widgets like volume, which can be configured as either icons or text, but would clean up the battery widgets, which look to me to be a bit of a mess (e.g. `_IconBox` could be split out to a new subclass).

I don't think would be _too_ hard, but I wanted to get some feedback on if people liked this before working on it.

**Comment by tych0** [comment]
On Sun, Jan 11, 2015 at 11:44:57AM -0800, Sean Vig wrote:
> Currently, all polling classes subclass _TextBox, I think ideally, the polling classes would be standalone (as subclasses or decorators?) and text/icons/etc would be added into widgets separately. I think this might mess up widgets like volume, which can be configured as either icons or text, but would clean up the battery widgets, which look to me to be a bit of a mess (e.g. `_IconBox` could be split out to a new subclass).
> 
> I don't think would be _too_ hard, but I wanted to get some feedback on if people liked this before working on it.

Yeah, that would be nice. I thought about doing this when I originally
did that refactoring, but when I started looking at Volume it looked
like a bigger job than I wanted to deal with at the time. I would
definitely love a patch that did this, though.
