### ISSUE TITLE
Unexpected behavior of x composite.

### ISSUE THREAD

**Issue by Magicloud** [qtile/qtile#579]
I am using unagi to be the composite manager. No errors got. But floating window (dock hint) with alpha channel will have desktop background as background, instead of the windows below it.
Am I using it wrong?

**Comment by tych0** [comment]
I don't think we currently do any Z axis management, so it doesn't really surprise me that it doesn't work :-). I think in order to get it to work with a compositor we'd need some more code.

**Comment by Magicloud** [comment]
Thank you for the reply. Sounds like a lot of changes....

**Comment by ramnes** [comment]
Transparent floating windows are showing backward windows correctly for me.

Maybe you just don't use it correctly, otherwise you should try with xcompmgr (I remember of strange behaviors with unagi).

**Comment by kynikos** [comment]
Overlapping transparent windows are displayed correctly for me too, tested with xcompmgr and compton (Intel graphics).

**Comment by tych0** [comment]
Going to close this, since it seems to work for people. Come to #qtile if you're still having issues, and we can help sort you out.

**Comment by Magicloud** [comment]
Ah, I was about to reply.
Thank you all. I will give xcompmgr a shot. I did not consider it because it is based on X11 libs, which uses too much resource under XDMCP. And with chrome, this would be a dead end.
