### ISSUE TITLE
Disable Caps Lock by Group Switching

### ISSUE THREAD

**Issue by Azd325** [qtile/qtile#580]
Hey,
is there someway to disable caps lock by qtile if I switch screens?

**Comment by kynikos** [comment]
I haven't tested it, but I guess you can bind a function to the `setgroup` hook that in turn calls a shell command to disable caps lock (you'll have to look for the correct shell command, I don't remember it).
To run the shell command you can either try `lazy.spawn` or use a normal python subprocess.

Hooks: http://qtile.readthedocs.org/en/latest/manual/config/hooks.html
Built-in hooks: http://qtile.readthedocs.org/en/latest/manual/ref/hooks.html

**Comment by tych0** [comment]
Yes, the hooks are the best way. Please use the mailing list in the future for discussion.
