### ISSUE TITLE
Crash if trying to use ImapWidget with 0.9

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#583]
Even worse, just having keyring installed will cause qtile to crash.

Basically, keyring is imported from `imapwidget.py`, which will import `gi.repository`, which in turn causes the import in `libqtile/manager.py` to fail. Because all the widgets are imported from `libqtile/widgets/__init__.py`, if keyring is installed, qtile will always crash, as:
```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 120, in make_qtile
    state=options.state,
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 172, in __init__
    self.setup_python_dbus()
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 250, in setup_python_dbus
    gobject.threads_init()
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 62, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

On IRC, this https://github.com/tych0/qtile/commit/0a5116449ea0ee3cb3162e3219e4f830d0864052 was reported to fix this problem.

The only risk we run is of someone using something else that does `import gobject`.

**Comment by tych0** [comment]
Thanks for the info!
