### ISSUE TITLE
General Inquiry

### ISSUE THREAD

**Issue by ankitvad** [qtile/qtile#586]
Hi, I'm working on Crunchbang Linu(#!) which uses the openbox stacking window manager. Since it's a pain to keep resizing the windows, i wanted to switch to a tiling manager. Awesome is too heavy.
Does Qtile provide it's own windows manager? With a new taskbar/dock and stuff? Or is it like a layer that can work on-top of Openbox.

I don't want to remove OpenBox and all of it's configuration. I just want a tool that makes tiling easier.

Any ideas on what i should do, and/or what should the best tool/program be for me?

Thanks.

**Comment by ankitvad** [comment]
Naah, Qtile is a minimal windows manager.
Coolio, i think whaw//tile would suit me better.

**Comment by kynikos** [comment]
Hi, you might be interested in [ArchWiki - List of applications#Window tilers](https://wiki.archlinux.org/index.php/List_of_applications#Window_tilers)
Please next time use the [mailing list](https://groups.google.com/forum/#!forum/qtile-dev) for general enquiries :)
