### ISSUE TITLE
docs doesn't list the requirements for installing the python tools

### ISSUE THREAD

**Issue by erikb85** [qtile/qtile#587]
I am just aiming in on what might result in "libffi-dev"!? And I guess there is more to come. Would be great if they would be listed like "just install the following packages with `sudo apt-get install <package1> <package2>...`".

Also please don't ask people to `sudo pip` things. `sudo apt-get` something or `pip` something in a virtualenv. Thanks! :)

**Comment by erikb85** [comment]
Okay, I think if you drop the following line into your install docs you are fine:

```
sudo apt-get install libxcb-render0-dev libffi-dev
```

**Comment by tych0** [comment]
You're looking at xcffib docs, so this should probably be filed there. In any case, doesn't xcffib depend on libxcb-render0-dev?

**Comment by erikb85** [comment]
I want your project to run, so your install guide should tell me how to do that, don't you think? You can't expect the average Python coder to know how to get c extensions to work. E.g. I only had about 2 months of helloworld.c education in college, which is a few years back. Just because I had to work with some ssh and serial libraries before I know anything about these header files.

**Comment by tych0** [comment]
I'm confused. What about the (xcffib) install guide doesn't tell you how to install it?

**Comment by erikb85** [comment]
Open a fresh Ubuntu VM, clone your repo and just hit `pip install -e .` inside. You'll immediately hit a few compile errors you need to work through before this will work. If you look into [the qtile install guide](http://qtile.readthedocs.org/en/latest/manual/install/index.html) it just tells you to do the same thing that your `pip` already did a few seconds before (also the `sudo` there is really a bad life choice). You'll get the same compile errors, just split up between the two packages xcffib and cairocffi. Yes cairocffi has more errors, after the ones from xcffib are fixed.

**Comment by erikb85** [comment]
Thanks man. Respect for reacting to user support even if you don't agree or don't feel there's a problem.

**Comment by felipedau** [comment]
Hi! Had the same problem today when I was installing Qtile from source:

```
  Downloading xcffib-0.3.2.tar.gz (65kB)
    100% |████████████████████████████████| 65kB 260kB/s
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
```

Maybe I should have paid more attention, but I did not find anything instructing me to `sudo apt-get install libffi-dev`, which seems to have matched the requirements and [xcffib] could install successfully. I know this is a sub-dependency of xcffib, but even on its `README` the only instruction given before calling pip is:

> To install it, you'll need libxcb's headers and libxcb-render's headers (these are available via sudo apt-get install libxcb-render0-dev on Ubuntu).

Anyways, I believe this could be added to the instructions, because in the end, it also becomes a sub-dependency of Qtile and that's keeping the user from installing it.

Thanks!

[xcffib]: https://github.com/tych0/xcffib

**Comment by erikb85** [comment]
Yeah, I didn't know how to put it into the right words but that's also what I'm thinking. Users won't recursively work through a project's requirements and the required package's docs. As a developer I can totally understand why one doesn't want to repeat and maintain already existing docs but users don't work that way, even if they're capable developers themselves.

**Comment by flacjacket** [comment]
I just added the bit about libffi-dev, thanks for pointing that out. It is technically a dependency of cffi, but you're right that we should specify it in our docs so users don't have to go hunting around.

**Comment by felipedau** [comment]
> As a developer I can totally understand why one doesn't want to repeat and maintain already existing docs but users don't work that way, even if they're capable developers themselves.

Exactly

> I just added the bit about libffi-dev, thanks for pointing that out. It is technically a dependency of cffi, but you're right that we should specify it in our docs so users don't have to go hunting around.

Thanks!
