### ISSUE TITLE
Fullscreen does work with flash, but not with html5 videos on Chromium

### ISSUE THREAD

**Issue by farebord** [qtile/qtile#605]
Hi, I'm having a little issue when I go fullscreen on my browser's videos. Like youtube videos, etc. But when I go fullscreen on VLC, it works fine.

Did I forget to configure something? Or is this a bug?

Thanks.

**Comment by ramnes** [comment]
I have Flash 16.0.0.305 and it works with Youtube on Chromium.

**Comment by tych0** [comment]
What is your browser?

**Comment by farebord** [comment]
I change the title, actually now it doesn't work with HTML5 videos, it stay on the browser window but dont go fullscreen. Browser: Chromium and Firefox
