### ISSUE TITLE
Windows from other groups sometimes appear on the screen

### ISSUE THREAD

**Issue by DanielStutzbach** [qtile/qtile#613]
On my workstation, windows from other groups sometimes appear on the screen.  Sometime they appear under other window.  Other times, they flicker over foreground windows.  They never manage to acquire the focus.  If I mouse over them and click, the click falls through to the window in the current group that should be visible at that location.  If the mouse is in motion, the correct window is always displayed under it.  Sometimes a window from another group reappears as soon as the mouse stops moving.

Any idea what might cause something like this or how I can track down the root cause of the problem?

**Comment by tych0** [comment]
On Tue, Feb 17, 2015 at 03:15:50PM -0800, Daniel Stutzbach wrote:
> On my workstation, windows from other groups sometimes appear on the screen.  Sometime they appear under other window.  Other times, they flicker over foreground windows.  They never manage to acquire the focus.  If I mouse over them and click, the click falls through to the window in the current group that should be visible at that location.  If the mouse is in motion, the correct window is always displayed under it.  Sometimes a window from another group reappears as soon as the mouse stops moving.
> 
> Any idea what might cause something like this or how I can track down the root cause of the problem?

You wouldn't happen to have an nVidia graphics card, would you? We've
seen similar things with nVidia cards before, and the solution seems
to be to run a compositor in addition to qtile (even if you don't have
it configured to actually do anything). That is, add something like
`xcompmgr &` to your ~/.xsession.

**Comment by DanielStutzbach** [comment]
I do indeed have an nVidia graphics card and starting xcompmgr did indeed solve my problem.  Thanks so much!

**Comment by tych0** [comment]
On Tue, Feb 17, 2015 at 03:43:09PM -0800, Daniel Stutzbach wrote:
> I do indeed have an nVidia graphics card and starting xcompmgr did indeed solve my problem.  Thanks so much!

No problem. I used to see it a lot with chrome myself, but more recent
versions of the nvidia graphics packages (>331 on ubuntu) seem to have
fewer issues. Maybe someone inside nVidia is a Qtile user :)
