### ISSUE TITLE
Dual monitor switching was borked

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#618]
http://files.tycho.ws/tmp/qtile_bug.png

I tried to switch to a group, and then somehow it got in a strange state where I couldn't switch groups on one monitor at all. I've been running this hash for several days and not seen this, so it seems quite rare, unfortunately.

**Comment by kynikos** [comment]
A similar thing happened to me a couple of times too, and I only have 1 monitor, but as you say, it seems very hard to reproduce.

**Comment by tych0** [comment]
@flacjacket also reports this happening on IRC recently, so it must have been a patch in the last few weeks.

**Comment by tych0** [comment]
this finally just happened to me again, here's a log: http://paste.ubuntu.com/10774160/

**Comment by tych0** [comment]
Ok. I don't think this will happen any more with the above commits, but it will at least print a big nasty stack trace to the log so hopefully someone will tell us about it :)
