### ISSUE TITLE
TreeTab and Zoomy layouts: changing a window to floating should also show the previous tiled window

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#619]
EDIT: This bug was originally reported for the Max layout, but it was later discovered to affect other layouts too.

Steps to reproduce:
1. Open 2 windows in a group with Max layout.
2. Change the focused window to floating: the other window is not shown below it.

The expected behavior would be to also show the previous tiled window when one is changed to floating.

**Comment by tych0** [comment]
This is probably true of all layouts, not just max?

**Comment by ramnes** [comment]
Just Max in my use cases.

**Comment by prizrak-pro** [comment]
I do not know where to ask a question.
When the default configuration add
c = Client ()
print c.status ()

An error occurs IPCError: Could not open ~ / .cache / qtilesocket.: 1.0

I do not know what to do?

**Comment by ramnes** [comment]
That's clearly not the place. Feel free to open a new issue.

**Comment by kynikos** [comment]
Returning on topic, this bug also affects the TreeTab and Zoomy layouts.

**Comment by flacjacket** [comment]
It looks like #647 and #656 fix this, @kynikos can you confirm this?

**Comment by kynikos** [comment]
It looks like there's still a way to reproduce it in the TreeTab layout:

1. Open 2 windows in the same group.
2. Drag the *top* (or first) window so that it floats: the bottom (or second) one is still not shown.
    Dragging the second window seems to work correctly though, so it must be simply a problem with a 0 index somewhere.

The Zoomy layout seems fixed to me too, thank you @luxrck for the patches!
