### ISSUE TITLE
TreeLayout works bad with two screens

### ISSUE THREAD

**Issue by tailhook** [qtile/qtile#62]
Left panel does not move between screens.
(will probably fix myself, just to not to forget)

**Comment by andering** [comment]
Same here,
it works as expected.
Having mixed windows in both panels would be confusing,
so i don't think this is bug but maybe feature, to have this options.
 I could implemented., but does anybody want this option?
This issue is 5 years old with not respond, what is politic of closing issues ? :)

**Comment by flacjacket** [comment]
Since it seems to be working by multiple reports, we'll close, if it's still a problem, it can be reopened :)
