### ISSUE TITLE
Bar: split to standalone client

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#622]
This was reportedly discussed on IRC a few times and proposed in the [ML (GSoC thread)](https://groups.google.com/d/msg/qtile-dev/KEfFHPQ2reY/rgCd8cOeK68J) as a possible project, so I think it's at least worth a reminder feature request.
The idea is to split the bar and the widgets to a separate application (i.e. process) that interacts with qtile as a normal client. I think it would make the code much cleaner, also making it easier to distinguish bugs related to qtile from bugs related to widgets. It would also serve as an official example of a qtile client in general. Many other window managers are structured that way, for example i3 and i3bar or xfwm4 and xfce4-panel.
The bar shouldn't necessarily be moved to a separate repository, for example i3 keeps i3bar in a folder at the root of the project, [see the repo](https://github.com/mgsnova/i3).

**Comment by LoganKaser** [comment]
I agree, I think this will help with stability a lot and make it much easier on devs in the long run.

**Comment by kynikos** [comment]
I think also the extensions should work as clients, e.g. `qtile-dmenu`.

**Comment by zordsdavini** [comment]
The main idea of extensions was to integrate 3rd part software into qtile environment. Dmenu is one of examples. And for this dmenu I imagine widgets can be used, too. Ex., I have youtube-dl, widget to manage it, for example click will use clipboard content to try fetch song, then dmenu can popup as suggestion to select place where to save. So, if we will have more clear code and still have good integration between objects - awesome

**Comment by kynikos** [comment]
I really like the idea of integrating qtile with other applications, however my view is that qtile is a bit diverging from the Unix philosophy of "do one thing and do it well", which in its case is managing windows.
If you look well, in your youtube-dl example, qtile is only involved because it's directly running both the widget/bar and the dmenu extension, but in practice there's no window management involved in that functionality, which would instead be better engineered as an extension to the bar/widget (which IMO should be a separate process), not the whole window manager.

**Comment by zordsdavini** [comment]
@kynikos you are right. That I said is to integrate into Qtile environment. In this case I used _environment_ - WM,  apps, widgets, extensions etc. as one team. Something like DE (but we are not working toward that).  Qtile as WM should be standalone as it can be used in gnome or somewhere else (I don't know why :laughing: )

**Comment by elParaguayo** [comment]
I'm going to close this.

I'm not aware of any ongoing discussions to split out the bar and I don't immediately see any benefits of doing so.

Happy to start a new discussion if people want.
