### ISSUE TITLE
sound widget unmute not working

### ISSUE THREAD

**Issue by muhammedabuali** [qtile/qtile#630]
clicking unmute on the sound widget doesn't unmute the sound.

**Comment by muhammedabuali** [comment]
the problem is in the *amixer* program.
 according to [SuperUser](http://superuser.com/questions/805525/why-is-unmute-not-working-with-amixer-command) the speaker and mic channels get muted too when you call >  amixer -q -c 0 -- sset Master playback toggle

**Comment by zordsdavini** [comment]
I use "amixer -q set Master toggle"

Arns

On 20 March 2015 at 23:26, muhammedabuali <notifications@github.com> wrote:

> the problem is in the *amixer* program.
> according to SuperUser
> <http://superuser.com/questions/805525/why-is-unmute-not-working-with-amixer-command>
> the speaker and mic channels get muted too when you call > amixer -q -c 0
> -- sset Master playback toggle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/630#issuecomment-84153130>.
>



-- 
Arns Udovīčė

**Comment by muhammedabuali** [comment]
@zordsdavini this works for me too

**Comment by zordsdavini** [comment]
I don't know do you need it to hardcode here, because you can simple use it in config like:

        widget.Volume(emoji=True,
            mute_command=[
                'amixer',
                '-q',
                'set',
                'Master',
                'toggle'],
            **Theme.widget),

The ticket could be closed, but may be better to add some documentation about this problem and the way how to fix it (by editing config)

**Comment by tych0** [comment]
Going to go ahead and close this for now, since it seems like it's not quite a bug. Thanks!
