### ISSUE TITLE
Widgets: support vertical bar

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#652]
Following #573/#628, the bar supports vertical orientation (positioned at the left or right sides of the screen), but widgets have to be adapted one by one.
Even `widget.base._TextBox` still supports horizontal orientation only, so all widgets subclassing it necessarily inherit this limitation.
In general, what needs to be done in each widget module is:
1. Update the `orientations` class attribute to `base.ORIENTATION_BOTH` (if it's missing, it's inherited from its superclasses).
2. Look for any references to horizontal attributes like "width" or "offsetx" and add vertical counterparts: the bar orientation can be tested with `if self.bar.horizontal:`. Common cases are the `calculate_length` method and calls to `self.drawer.draw`.
3. Update configuration options and docstrings to be orientation agnostic, or to refer to both orientations.

**Comment by jtyers** [comment]
This would be great to have - I run Awesome with vertical task bars to make max use of my screen space. Vertical widgets is the one thing preventing me from moving across.

**Comment by gbdlin** [comment]
One thing worth considering is to widget have the ability to determine automatically if it is placed in a vertical or horizontal bar. There shouldn't be a need to specify orientation per widget.

**Comment by elParaguayo** [comment]
Vertical text boxes have been implemented. If there are other specific widgets that need to be updated then a new issue can be created.
