### ISSUE TITLE
Pop up window opens only ony the first group it was opened on

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#677]
replicated with insync app.

WM_STATE(WM_STATE):
window state: Normal
icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 11
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 2097207
_NET_WM_USER_TIME(CARDINAL) = 89443567
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "-"
WM_CLIENT_LEADER(WINDOW): window id # 0x200004
_NET_WM_PID(CARDINAL) = 20202
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x4, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NAME(STRING) = "-"
WM_LOCALE_NAME(STRING) = "en_AU.UTF-8"
WM_CLASS(STRING) = "insync.py", "Insync.py"
WM_HINTS(WM_HINTS):
Client accepts input or input focus: True
Initial state is Normal State.
bitmap id # to use for icon: 0x200034
window id # of group leader: 0x200004
WM_NORMAL_HINTS(WM_SIZE_HINTS):
user specified location: 1180, 10
program specified location: 1180, 10
user specified size: 420 by 500
program specified size: 420 by 500
program specified minimum size: 420 by 500
program specified maximum size: 420 by 500
window gravity: NorthWest
WM_CLIENT_MACHINE(STRING) = "steven-series9"
WM_COMMAND(STRING) = { "insync.py" }

**Comment by tych0** [comment]
Is this really a bug? I don't understand what the desired behavior would be.

**Comment by jagguli** [comment]
If I open the popup on a particular group and then close the window, the next time if I am on a different group the popup will show on the initial group only even if the initial group is not visible currently.

**Comment by flacjacket** [comment]
I _think_ the floating changes that I just made would fix this, but I'm not exactly able to test it. If you are still having this problem, feel free to re-open this.
