### ISSUE TITLE
Qtile doesn't remember focus after closing a floating window

### ISSUE THREAD

**Issue by Kilte** [qtile/qtile#679]
I've tried to find an existing issue, but I've found nothing. 

Steps to reproduce problem:

1. Open Sublime Text and Terminal Emulator on `Max` layout.
2. Create new file in sublime text using <kbd>Ctrl+N</kbd>
3. Press <kbd>Ctrl+S</kbd>, choose filename and save it.

After this, Qtile should pass focus to Sublime Text, but I've got a terminal instead.

**Comment by kynikos** [comment]
Are you testing on the development version of qtile, or the latest official release (9.1)? Because this bug should have been fixed by #581, which however I don't think made it to be included in the 9.1 release.

**Comment by Kilte** [comment]
>Because this bug should have been fixed by #581
My Bad.

I'm using 0.8.0
