### ISSUE TITLE
Only one window should have focus decoration with multi screens

### ISSUE THREAD

**Issue by mattharrison** [qtile/qtile#68]
When switching focus from one screen to another there ends up being a focused window on each screen (ie both windows have the focus decoration). I would think that since only one window can have focus, there should only be one window with focus decoration.

**Comment by zordsdavini** [comment]
__Test__
I set both monitors on MonadTall layout. I get focus decorations only on one window. I think  this can be closed. 
![2019-10-16-092644_3840x1200_scrot](https://user-images.githubusercontent.com/4191548/66893713-55fb3d80-eff7-11e9-8280-cad3ba38554d.png)

**Comment by tych0** [comment]
Seems like it's layout specific then? For the layouts I use (xmonad and stack) it works.

**Comment by m-col** [comment]
Lots of changes since last October could have fixed this. Still a thing? :)

**Comment by ramnes** [comment]
yes

**Comment by ramnes** [comment]
Oh wait, it only happens when I toggle groups on one screen, not when I jump from a screen to another (with the mouse or with a keybinding). That may explain why you guys couldn't reproduce.
