### ISSUE TITLE
python-cairocffi update breaks qtile

### ISSUE THREAD

**Issue by soulchainer** [qtile/qtile#680]
This morning, my qtile stop starting.
I reviewed my qtile logs and there's the traceback I got:

```
2015-06-16 14:02:27,099 ERROR make_qtile:124 Qtile crashed during startup
Traceback (most recent call last):
  File "/usr/bin/qtile", line 121, in make_qtile
    state=options.state,
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 159, in __init__
    self._process_screens()
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 315, in _process_screens
    self.groups[i],
  File "/usr/lib/python3.4/site-packages/libqtile/config.py", line 262, in _configure
    i._configure(qtile, self)
  File "/usr/lib/python3.4/site-packages/libqtile/bar.py", line 184, in _configure
    self.height
  File "/usr/lib/python3.4/site-packages/libqtile/drawer.py", line 226, in __init__
    self.height,
  File "/usr/lib/python3.4/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 629, in __getattr__
    make_accessor(name)
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 625, in make_accessor
    make_accessor_locked(name)
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 619, in make_accessor_locked
    raise AttributeError(name)
AttributeError: cairo_xcb_surface_create
```
So, I got it was something related with cairo.
It happens that, yesterday, I upgraded, aside with others, `python-cairocffi` package, doing, like I'm used to, `yaourt -Syua` in my Archlinux.
So, I have downgraded `python-cairocffi` to their previous version (from 0.7-1 to 0.6-2) and now everything works like expected.
This happens equally with [qtile-python3-git](https://aur4.archlinux.org/packages/qtile-python3-git/) and with last develop branch changes.

**Comment by zordsdavini** [comment]
same with stable 0.9.1 qtile version

**Comment by zordsdavini** [comment]
please, mark it as release-blocker

**Comment by dequis** [comment]
You built cairocffi without xcffib support Ensure you have the latest version of cairoffi and reinstall cairocffi.

Maybe the check in 54cba4b88537228339117097bc3f8de9fdce5164 should also be moved to runtime...

**Comment by zordsdavini** [comment]
I use archlinux package and not building it

**Comment by rmsc** [comment]
I believe this problem is archlinux related, in that python-xcffib-0.3.2-1 is still in the community-testing repository...

In order to compile qtile-python3-git from aur, you need to install the latest python-xcffib package from community-testing. Just enable the repository, install the package and disable it again. You should have no trouble, and you'll be able to compile and run qtile again.

**Comment by renatoGarcia** [comment]
@soulchainer and @zordsdavini: I'm running an up to date Arch Linux too. To make the last Qtile develop commit (6a473e5) to work, I have simply built and installed a python-xcffib 0.3.2 package myself. Also, I'm running Qtile with Python 3.

**Comment by soulchainer** [comment]
Many thanks to all :).
@renatoGarcia Maybe that works... but the aim was to not be forced to built something by hand, but have package manager dealing with it ;).
@rmsc YEAH! :D That solved the problem. THANKS.
@zordsdavini If you don't care about what package you use while you get yaourt/pacman dealing with it for you, @rmsc suggestion was all you need. That is:

```
$ vim /etc/pacman.conf
...
[community-testing]
Include = /etc/pacman.d/mirrorlist
...
```
And 
```
$ yaourt -Sy
yaourt -S python-xcffib python-cairocffi qtile-python3-git
```
(and comment again `[community-testing]` later).
Still, I hope package maintainers will take this into account, because I guess, if not, updating `python-cairocffi` still will break qtile if you're using stable qtile... or not?

**Comment by zordsdavini** [comment]
thanks, this solved it temporarily. Will look for archlinux package update.

**Comment by benaryorg** [comment]
I have a similar problem on Gentoo GNU/Linux I think.

Crash: http://pastebin.com/UwtNqEKN

I have built, rebuilt and reinstalled qtile cairo cairocffi and xcffib.

**Comment by cachedout** [comment]
+1 for the breakage on Arch. Does anybody know if the package maintainers are aware of this issue?

**Comment by Roger** [comment]
Maintainer here, sorry about that.. i'll look into this today, had really busy days

**Comment by cachedout** [comment]
@Roger Much appreciated!

**Comment by sammanthp007** [comment]
@rmsc same problem, solution did it for now. much appreciated

**Comment by sammanthp007** [comment]
@rmsc same problem, solution did it for now. much appreciated

**Comment by sammanthp007** [comment]
@rmsc @Roger @soulchainer its about a fortnight now and yet this problem exists; has there been any new approach to solving this in a more permanent way (and thank you for the solution)

**Comment by rmsc** [comment]
I believe python-xcffib 0.3.2-1 is already in the "community" repository, so things should work out of the box now...

@sammanthp007 you should try qtile-python3-git (and don't forget to sync).

**Comment by jhaubrich** [comment]
I had trouble on arch too, python-xcffib 0.3.2-1 did not work for me, nor did downgrading cairocffi.

However, after much fiddling, I managed to get qtile on master running from source in a virtualenv with the following package versions:

``` sh
$ pip install cairocffi==0.6
$ pip install cffi==0.8.2
$ pip install xcffib==0.1.11
$ python setup.py install  # qtile:master
$ pip freeze
cairocffi==0.6
cffi==0.8.2
pycparser==2.14
qtile==0.9.1
six==1.9.0
xcffib==0.1.11
```
note: Python 3.4.3, master branch

I tried many combinations of the above library versions. Needless to say, the current versions on these packages do not work for me.

It might be good to specify the max package versions in `requirements.txt` when a qtile version is tagged. Thereby freezing the packages with the version. This way master will always build.

I usually bracket to allow point releases, e.g.

``` sh
$ cat requirements.txt
cairocffi >=0.6, <7.0
cffi >=0.8.2, <0.9
xcffib >=0.1.11, <0.2
```

**Comment by LoganKaser** [comment]
I've been Qtile less for awhile now any progress on finding/fixing the source of the problem instead of duct-taping dependencies?

**Comment by Roger** [comment]
qitle git packages should work now on arch.. stable ones won't until a new release of qtile

**Comment by flacjacket** [comment]
The changes in 0.10.0 fix compatibility with current versions of cairocffi and xcffib. If there are new problems, feel free to re-open this or open new issues.
