### ISSUE TITLE
get_wm_transient_for() always returns None

### ISSUE THREAD

**Issue by tonich-sh** [qtile/qtile#688]
changing
r = self.get_property("WM_TRANSIENT_FOR", "ATOM")
to
r = self.get_property("WM_TRANSIENT_FOR", "WINDOW")
fixed this but makes list instead of integer

PS: xorg-server-1.17.1

**Comment by flacjacket** [comment]
Thanks for reporting this, this should fix it: https://github.com/flacjacket/qtile/tree/fix_get_transient_for

Do you mind checking if it works for you?

**Comment by flacjacket** [comment]
This should be fixed, I pushed that commit and it's in 0.10, feel free to re-open if this is still a problem.
