### ISSUE TITLE
Cannot install v0.10.0 from PyPI

### ISSUE THREAD

**Issue by lightcatcher** [qtile/qtile#691]
The PyPI package does not contain all of the same files and directories as are present on github.

```
[emartin@eric-Thinkpad:~] ls qtile-0.10.0_github
bin  CHANGELOG  debian  docs  libqtile  LICENSE  Makefile  MANIFEST.in  README.rst  requirements.txt  resources  scripts  setup.py  test
[emartin@eric-Thinkpad:~] ls qtile-0.10.0_pypi 
bin  libqtile  LICENSE  MANIFEST.in  PKG-INFO  qtile.egg-info  README.rst  setup.cfg  setup.py
```
where the github version comes from downloading the v0.10.0 archive and the PyPI version comes from ``pip install --download . --no-deps qtile"

This difference in files results in the error message ``error: can't copy 'resources/qtile.1': doesn't exist or not a regular file`` while installing from the PyPI package.

A complete example of an installation failure is demonstrated here: https://gist.github.com/lightcatcher/d819cb3f63ed34649ab7

I set up a new virtualenv, installed xcffib (to ensure it downloads before cairocfii), and then attempted and failed to install qtile.

I believe this same bug might also have also happened with v0.9.1, but I don't remember (I wasn't paying as much attention while doing some tweaks trying to get it working).

**Comment by flacjacket** [comment]
Oops, thanks for the report, I'll take a look at this tonight.

**Comment by flacjacket** [comment]
Not all the files in the repository are supposed to be in the PyPI release, but those definitely should be, I just tagged 0.10.1, which should be installable.

**Comment by lightcatcher** [comment]
Awesome, thanks for the fast fix!

I don't know if it's still relevant at this point, but I'm 80% sure the same bug exists in the last 0.9 release (should be easy to check).

**Comment by flacjacket** [comment]
Yeah, I was just checking and those files were added to github before 0.9, so our package has been broken for a while, so thanks for reporting it. We don't really support older versions, probably not unless someone really asks for it, so it's not so bad that those releases are broken.
