### ISSUE TITLE
Remove imp module from manager.py

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#701]
`imp` is used in manager.py in `cmd_run_external()`, these methods have been deprecated in Python 3.4, we should replace them with the equivalent `importlib` functions (while maintaining backwards compatibility).

**Comment by kseistrup** [comment]
IMHO, this is not just an enhancement, but a potential bug.  While the code still runs on Python 3.4, it will most likely not on the upcoming Python 3.5 (scheduled this autumn) which will then be the default interpreter version in distros like ArchLinux.

**Comment by flacjacket** [comment]
It is a potential bug, but it doesn't look like imp is being removed in the near future, the [3.5 docs](https://docs.python.org/3.5/library/imp.html) still have it, and we've started testing against the latest nightly (currently 3.6a0) so we'll catch it before the change happens. Deprecated stuff tends to stay around a while (optparse has been deprecated since 3.2, but it still around), it seems it is more to say there are better alternatives. That said, it is an easy fix and definitely on the todo list.

**Comment by kseistrup** [comment]
Cool, thanks.
