### ISSUE TITLE
Dgroup rules not applied on restart

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#704]
Dgroup matching rules are only executed when windows are added, can this be made into a separate function that can be called independently. Especially on restart?

Not sure if this is abug specific to my configuration.

**Comment by jagguli** [comment]
Got it working as a keybinding using lazy function, but adding it to the start hook didn't work for some reason.



def set_groups(qtile):
    for client in qtile.windowMap.values():
        for rule in qtile.dgroups.rules:
            if rule.matches(client):
                if rule.group:
                    client.togroup(rule.group)

**Comment by ramnes** [comment]
Thanks @jagguli. Closing in favor of #960, which gives more background.
