### ISSUE TITLE
Layout serialization broken for TreeTab and Slice

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#708]
Currently TreeTab and Slice layouts are unable to generate a State because they cannot be pickled. This is because each of these layouts create their own Drawer, and the Drawer contains cffi objects which are not pickleable. I think this may cause crashes for people with TreeTab or Slice layouts on restart, but I haven't checked. Regardless, we should fix these before we do any releases.

See Travis tests with all of the layouts being serialized:

https://travis-ci.org/flacjacket/qtile/builds/71703405

Ping @aniruddhkanojia

**Progress**

- [ ] Tree Tab
- [x] Slice

**Comment by aniruddhkanojia** [comment]
For Slice layout , I think the attributes `_slice` and `fallback` are cause of the error.

For TreeTab I will look into that further.

**Comment by flacjacket** [comment]
From those tests on Travis, it's currently complaining about cdata objects
not being pickleable, which I figured were the Drawers, but I could be
wrong. Keep us posted on your progress :)
