### ISSUE TITLE
Python 2 cmd_grow/shrink problem with XmonadTall

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#715]
As reported by @Ippolo on IRC, growing/shrinking secondary panes in the xmonad layout is broken when running with Python 2, but not with Python 3. I run with 3, so I can't confirm this, but I will try to reproduce and fix when I get the chance.

**Comment by flacjacket** [comment]
@Ippolo I will try to replicate this tonight, but just glancing at the code, using float division might fix it and would explain the 2/3 problem, you can try my branch here https://github.com/flacjacket/qtile/tree/fix_monad

**Comment by Ippolo** [comment]
@flacjacket yes, using float division fixes the problem =)

**Comment by flacjacket** [comment]
I fixed this up and added some tests of the MonadTall layout so hopefully it doesn't happen again
