### ISSUE TITLE
Remove margin when only one window

### ISSUE THREAD

**Issue by farebord** [qtile/qtile#723]
Hey guys, first of all, love your work. I'm having a little problem to configure, I wanna make margin disappear when only one window exist, I'm currently using MonadTall as default layout.

Thanks.

**Comment by flacjacket** [comment]
Actually, adding the border when to a single window was [just added a couple days ago](https://github.com/qtile/qtile/commit/9c88d06b6be3716c33f0ad9b373a672b699d8862), but it would be easy to make that toggleable

**Comment by flacjacket** [comment]
You should be able to toggle this with the `single_border_width` option now
