### ISSUE TITLE
Dual monitor setup - dialog windows

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#726]
On dual monitor setup with monitors A, B where A is a primary, dialog windows are spawned always on actual group displayed on monitor A even if focus is on B.

##### Steps to reproduce:
1. Have dual monitor setup
2. Move focus to secondary one
3. Run dialog window such a `gmrun` or `libreoffice`'s lanucher

##### Actual results:
Dialog windows always pops up on primary monitor

##### Expected results:
Dialog window should pop up on currently focused monitor.

**Comment by ramnes** [comment]
Related to https://github.com/qtile/qtile/issues/538

**Comment by flacjacket** [comment]
I just fixed up a lot of floating stuff, this should be covered by it. Let us know if you still have any problems!

**Comment by FrostyX** [comment]
Well, that is awesome news! Thank you.
