### ISSUE TITLE
Focus is not returned to previous window after closing dialog

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#727]
On `Max` layout, when non-master window is focused and dialog appears, then after closing it, focus is changed to master window. This is realy, realy bad and makes using some applications very painful (dolphin - create new; file-roller - extracting; gmrun - in general)
##### Steps to reproduce:
1. Activate the `Max` layout
2. Spawn windows `A` and `B` (it means that `B` will be master window)
3. Change focus to window `A`
4. Spawn dialog window such a `gmrun`
5. Close that dialog
##### Actual results:

You have now focused window `B` (primary)
##### Expected results:

You should get focus back to the previous window. In this case `A`.
##### Additional note:

Please note that this issue can be found also on other layouts, but behaves slightly different. I've described the `Max` layout, because it's most significant there.

**Comment by kynikos** [comment]
Isn't the "master" window always the same as the focused one in the Max layout? I can't reproduce the bug, I do get `A` in your scenario. #581 should have fixed that behavior, are you sure you're testing on the latest commits?

**Comment by FrostyX** [comment]
> are you sure you're testing on the latest commits?

I have the latest fedora package

**Comment by flacjacket** [comment]
It looks like the Fedora package is 0.9.1, and the PR @kynikos references wasn't in a package until 0.10.0 [2]. It looks like qtile 0.10 is stuck on updating xcffib/cairocffi.

[1] https://apps.fedoraproject.org/packages/qtile/overview/
[2] https://github.com/qtile/qtile/commit/b3ee4482f4848e00346e4dfc55243e1639b49686

**Comment by kynikos** [comment]
So this one can be closed?

**Comment by flacjacket** [comment]
Maybe, @FrostyX is there any way you can try with a more recent release?

**Comment by ramnes** [comment]
I will go ahead and consider this issue outdated. Please ping me if a reopening is needed!
