### ISSUE TITLE
[rfe] block showing group if it is already showed on other monitor

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#728]
On dual monitor setup, when one screen attempts to show group which is already showed on the other screen, attempt is successful and other screen is switched to something else. I would rather to just not be able to open it, because in 99% cases I think that focus is on the other screen and then it smashes my setup.

##### Steps to reproduce:
1. Have dual monitor setup
2. Show group `1` on monitor `A`
3. Show group `2` on monitor `B`
4. Attempt to show group `1` on monitor `B`

##### Actual results:
Group `1` is showed on the monitor `B` (as wanted), but group on monitor `A` is implicitly changed.

##### Expected results:
Ideal way for me is that group `1` is showed on monitor `B` as wanted, but monitor `A` is not changed, so both monitors is showing the same group. But I guess this approach is not possible.

So almost ideal, but way better then actual results would be unsuccessful attempt of showing the requested group. This means that if group `1` is showed on monitor `A` than it should be blocked for all other monitors to show group `1` until `A` is switched to some other group. 

##### Additional notes:
I was informed that this behavior is not u bug and some users uses it as a feature. That's why I suggest some boolean to turn this feature on and off.

**Comment by btwe** [comment]
Recently, I came from i3 and started with qtile 0.10.1 and expected similar behaviour as you.

But I ran into that weired behaviour of swapping groups across outputs which are aligned left/right (I call them output in the term of xrandr --output) when cycling through the groups with screen.{next,prev}_group() commands.

To solve that, I found a solution while having a look into the src. The functions screen.{next,prev}_group() take two extra kwargs which are set to False per default. One of them is named 'skip_managed'.

Setting the keybind to cycle to the next, prev group to that function with kwarg skip_managed=True, does not jump to a group which is currently active on another screen. That at least solved the weired/unintentional jumping of groups from left/right output.

```python
Key([mod], "comma", lazy.screen.prev_group(skip_managed=True)),
Key([mod], "period", lazy.screen.next_group(skip_managed=True)),
```

**Comment by FrostyX** [comment]
This is absolutely beautiful, thank you very much @btwe . Accessing some group directly by it's key and accidentally at the same, happens a very little. But the cycling next/prev was horror.

I can happily say that it solves my issue, so am closing it. Anyone please feel free to reopen it if it's not good enough for you.
