### ISSUE TITLE
Battery Widget does not handle "Unknown" battery state

### ISSUE THREAD

**Issue by dmaniry** [qtile/qtile#730]
The recent thinkpads have two batteries. The battery widget can't handle this because it assumes that a battery is either charging, discharging or full:

https://github.com/qtile/qtile/blob/develop/libqtile/widget/battery.py#L211at

That leads to an empty battery that is not discharging being shown as Full.
In the two battery system a battery that is neither charging nor discharging has the status "Unknown"
in info['stat'](/sys/class/power_supply/BAT1/status)

**Comment by flacjacket** [comment]
What is `info['now']` when it is empty? If it's 0 we may be able to use that to distinguish full from empty.

**Comment by duschendestroyer** [comment]
This won't be enough because the battery is not necessarily empty when it is in the "Unknown" state. The batteries are not discharged one after the other. First one battery goes 5% then the other one is discharged.

**Comment by flacjacket** [comment]
Hmm, in that case, we may be able to use `/sys/class/power_supply/AC/` to resolve an unknown status

**Comment by llybin** [comment]
duschendestroyer, can you show the output: /sys/class/power_supply/{...}/uevent
I believe it is necessary to rely on the value of the status of the battery.

**Comment by duschendestroyer** [comment]
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=11955000
POWER_SUPPLY_POWER_NOW=0
POWER_SUPPLY_ENERGY_FULL_DESIGN=23200000
POWER_SUPPLY_ENERGY_FULL=18970000
POWER_SUPPLY_ENERGY_NOW=5380000
POWER_SUPPLY_CAPACITY=28
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=45N1773
POWER_SUPPLY_MANUFACTURER=SANYO
POWER_SUPPLY_SERIAL_NUMBER=  979


POWER_SUPPLY_NAME=BAT1
POWER_SUPPLY_STATUS=Unknown
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=9900000
POWER_SUPPLY_POWER_NOW=0
POWER_SUPPLY_ENERGY_FULL_DESIGN=23200000
POWER_SUPPLY_ENERGY_FULL=18320000
POWER_SUPPLY_ENERGY_NOW=0
POWER_SUPPLY_CAPACITY=0
POWER_SUPPLY_CAPACITY_LEVEL=Critical
POWER_SUPPLY_MODEL_NAME=45N1775
POWER_SUPPLY_MANUFACTURER=SANYO
POWER_SUPPLY_SERIAL_NUMBER=24987

**Comment by llybin** [comment]
I can not understand why if battery is a discharging, power_now is 0. Why if battery is a empty, can to see information about battery. May be problem in drivers in lenovo...
When my battery is empty(samsung notebook): cat /sys/class/power_supply/BAT1/uevent                                                                                                                            
cat: /sys/class/power_supply/BAT1/uevent: No such file or directory
And widget continues to show FULL - yes, a bug, but the other.

**Comment by m-col** [comment]
Is this still an issue?

**Comment by m-col** [comment]
> Is this still an issue?

I'm thinking this is not. Feel free to re-open if there is still a problem.
