### ISSUE TITLE
Clicking on widget.Notify will eat my notifications

### ISSUE THREAD

**Issue by ff2000** [qtile/qtile#732]
LMB clears the notification widget (which is what I intended). But further notifications will not be displayed anymore. They get eaten. Somewhere. lazy.restart() doesn't help, I need to shutdown qtile and start it, again.

**Comment by ff2000** [comment]
Sorry, forgot to mention details on my environment:
I am on Gentoo (shouldn't matter) running latest develop-branch on python-3.4.1. If you need further infos please tell me so.

**Comment by andering** [comment]
Gentoo says hi to gentoo :).
Today i tried simulate your problem but not successfully,
so just to make sure i understand your problem:

1. `notify-send 'notification 1'`
2. widget show me notification 1
3. LMB on it to clear it out
4. `notify-send 'notification 2'`
5. and it doesn't show up ?

**Comment by ff2000** [comment]
Thx for your comment!
Yes, that's what I experienced. I just installed qtile again (I am currently using awesome) and need to confirm that this seems to have been fixed magically. 0.10.1 (which should be similar to what I used when I reported this issue) does everything as expected, so "something" created this issue but not qtile. So I will close this issue.
