### ISSUE TITLE
lib*.so references in pangocffi.py

### ISSUE THREAD

**Issue by jsqliu** [qtile/qtile#734]
When upgrading from 0.9.1 to 0.10.1, I needed to modify the following references for my system (Ubuntu Vivid) in libqtile/pangocffi.py

gobject = ffi.dlopen('libgobject-2.0.so')
pango = ffi.dlopen('libpango-1.0.so')
pangocairo = ffi.dlopen('libpangocairo-1.0.so')

**Comment by tych0** [comment]
On Mon, Aug 03, 2015 at 11:39:14PM -0700, jsqliu wrote:
> When upgrading from 0.9.1 to 0.10.1, I needed to modify the following references for my system (Ubuntu Vivid) in libqtile/pangocffi.py
> 
> gobject = ffi.dlopen('libgobject-2.0.so')
> pango = ffi.dlopen('libpango-1.0.so')
> pangocairo = ffi.dlopen('libpangocairo-1.0.so')

Sorry, what's the bug here? My copy of the tree has those in it as
well. Can you post a patch of your modifications?

**Comment by jsqliu** [comment]
On my system two of the .so filenames are slightly different so I'm using

    pango = ffi.dlopen('libpango-1.0.so.0')
    pangocairo = ffi.dlopen('libpangocairo-1.0.so.0')

libpango and libpangocairo should have been installed through apt.  I used `dpkg -L libpango-1.0-0:amd64` and `dpkg -L libpangocairo-1.0-0:amd64` to locate these files.

I'm not sure if this counts as a bug or if there is a more system independent way to write this, but it's a step beyond the documented installation instructions I had to take.

**Comment by tych0** [comment]
On Tue, Aug 04, 2015 at 09:29:42AM -0700, jsqliu wrote:
> On my system two of the .so filenames are slightly different so I'm using
> 
>     pango = ffi.dlopen('libpango-1.0.so.0')
>     pangocairo = ffi.dlopen('libpangocairo-1.0.so.0')
> 
> libpango and libpangocairo should have been installed through apt.  I used `dpkg -L libpango-1.0-0:amd64` and `dpkg -L libpangocairo-1.0-0:amd64` to locate these files.
> 
> I'm not sure if this counts as a bug or if there is a more system independent way to write this, but it's a step beyond the documented installation instructions I had to take.

Oh, no, you're right, I think qtile is wrong here. It looks like the
raw libpango-1.0.so is provided by libpango1.0-dev, which we don't
(well, shouldn't) require as a dependency. I'll try to send a patch
soon, thanks!
