### ISSUE TITLE
Wlan widget not work

### ISSUE THREAD

**Issue by farebord** [qtile/qtile#745]
Hi guys, recently I tried to use Wlan widget on my config, and Qtile crash. So I discovered that Wlan relies on pythonwifi module (python-wifi 0.6.0 on pypi). The problem is, I think, pythonwifi its not ported to python3 yet. 
I tried using iwlib module. It works just fine. The only problem I found using this module its that when you change the wireless network its not updated (but change in quality are updated just fine).

Sorry for my poor english.

**Comment by ramnes** [comment]
Your English is okay. :+1: 

Could you make a pull request with your changes to use `iwlib`, so we can take a look at the network update problem ?

**Comment by farebord** [comment]
Hey ramnes, I'll try to do that. I'm not very into git-related tools. 
Correct me if I'm wrong.
Thanks

**Comment by ramnes** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by farebord** [comment]
I think I did it. Thanks for the help.

**Comment by flacjacket** [comment]
Great, discussion can continue on the PR
