### ISSUE TITLE
Prompt widget quits immediately

### ISSUE THREAD

**Issue by btwe** [qtile/qtile#756]
qtile: 0.10.1

I heavily use the prompt widget to enter names of groups or spawn programs, e.g. and so I realize that
it happens quite often that the prompt widget gets activated and then immediately quits. Hitting the bound key to get the prompt a second time works well.

I do not know which information could be useful to you. Maybe you could tell me how to debug that issue in more detail.

I have the feeling that this problem is related to what I have typed before calling the prompt. At least one procedure to reproduce this is to let my terminal (urxvt) blink (visual-bell by tab-completion or backspace at the beginning of the input line) and then hitting the key to call the prompt.

**Comment by flacjacket** [comment]
That's very interesting, I haven't seen this, but I'll see if I can't reproduce that.

**Comment by ramnes** [comment]
@btwe is the bug still there on Qtile 0.12?

**Comment by btwe** [comment]
Thanks for coming back to this.
With 0.12 I cannot reproduce anymore.

**Comment by ramnes** [comment]
Thank you for your reactivity @btwe, glad that it got fixed!
