### ISSUE TITLE
`cursor_warp = True` not warping on some configs

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#760]
`cursor_warp = True` seems to conflict with something else in some configs.

That config warps correctly: https://github.com/ramnes/qtile-config/blob/master/config.py
But that one doesn't: https://gist.github.com/anonymous/7b1c52b46d60c9e894c7

Strange thing being:
> rogerduran: hallyn: can you try, eval("self.config.cursor_warp"), from qsh?
> hallyn: > eval("self.config.cursor_warp")
> hallyn: (True, 'True')
> rogerduran: at least is set

Some more IRC copy-pastah:
> tych0: hallyn: i'm thinking the real patch should look something like this, https://github.com/tych0/qtile/commit/21ae6d9765d4624f7b19734a31a8f235eaafd5fb

Looked like Tych0 was going to make a PR in the end.

**Comment by tych0** [comment]
Yep, sorry, got sidetracked by running the test suite and the AWS meltdown. I'll try to make the PR shortly.
