### ISSUE TITLE
MonadTall - Single Client Double Margin

### ISSUE THREAD

**Issue by xplv** [qtile/qtile#767]
When the layout MonadTall is used and only on window is present it seems that the margin on the right side and the bottom is too big. A fix I found is changing the lines 312 & 313 in xmonad.py
from
```python
self.group.screen.dwidth - 2 * self.single_border_width - self.margin,
self.group.screen.dheight - 2 * self.single_border_width - self.margin,
```
to 
```python
self.group.screen.dwidth - 2 * self.single_border_width,
self.group.screen.dheight - 2 * self.single_border_width,
```

before
![2_005](https://cloud.githubusercontent.com/assets/5399010/10140387/8aef68d2-6607-11e5-9efe-95c664daf55d.png)
after
![2_006](https://cloud.githubusercontent.com/assets/5399010/10140426/aa3c3b98-6607-11e5-9a83-e1f28b3374e0.png)

**Comment by flacjacket** [comment]
There was some shuffling around of stuff in MonadTall, and I tried adding tests for it, but I don't think I did any tests with margins. I can try to whip something up later today or tomorrow, unless you want to try and open a PR for it.

**Comment by xplv** [comment]
I've never done this before, but I'll give it a shot.
