### ISSUE TITLE
switch window by fuzzy matching window title

### ISSUE THREAD

**Issue by QiangF** [qtile/qtile#769]
Hi everyone,
I have never used qtile but I use emacs a lot. I am wondering if qtile support switch windows like switching buffers in emacs with helm? Basicaly it just pops up a list which narrows in as you type the keyword for mathing the window title. 
Thank you!

**Comment by tych0** [comment]
On Thu, Oct 01, 2015 at 01:33:41PM -0700, QiangF wrote:
> Hi everyone,
> I have never used qtile but I use emacs a lot. I am wondering if qtile support switch windows like switching buffers in emacs with helm? Basicaly it just pop up a list which narrows in as you type the keyword for mathing the window title. 

No, I'm not aware of anything like that today. You might consider
using the mailing list for discussion, instead of filing issues.

**Comment by flacjacket** [comment]
> You might consider using the mailing list for discussion, instead of filing issues.

In particular for asking questions, if you have any bugs or feature requests, you can file bugs for them, but the mailing list is better for getting help.

**Comment by zordsdavini** [comment]
I have created some dmenu to list all opened apps in qtile. Take a look
here
https://github.com/qtile/qtile-examples/blob/master/zordsdavini/bin/dmenu-qtile-windowlist.py

On 2 October 2015 at 00:42, Sean Vig <notifications@github.com> wrote:

> You might consider using the mailing list for discussion, instead of
> filing issues.
>
> In particular for asking questions, if you have any bugs or feature
> requests, you can file bugs for them, but the mailing list is better for
> getting help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/769#issuecomment-144858169>.
>



-- 
Udovīčė Arns

**Comment by QiangF** [comment]
I found this one, it looks good.
https://github.com/XCMer/fuzzy-window-switcher

**Comment by zordsdavini** [comment]
Mine choice has additional group name after window name. But take what is
better for you :)

On 2 October 2015 at 15:13, QiangF <notifications@github.com> wrote:

> I found this one, it looks good.
> https://github.com/XCMer/fuzzy-window-switcher
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/769#issuecomment-145000599>.
>



-- 
Udovīčė Arns

**Comment by nicoe** [comment]
And there is also rofi: https://github.com/DaveDavenport/rofi

**Comment by QiangF** [comment]
Thank you for the recommendation. Also if you use emacs, have a look at
https://github.com/ch11ng/exwm
It can solve all the problems with emacs lisp!!

**Comment by zordsdavini** [comment]
It looks like ticket should be closed. Now we even have extension for dmenu to get list of windows

**Comment by flacjacket** [comment]
Good point, closing!
