### ISSUE TITLE
mouse button binding

### ISSUE THREAD

**Issue by QiangF** [qtile/qtile#770]
Hi everyone,
In freecad, there is a cool mouse binding: click middle button the click right button to rotate view.
Ho can I make it to run apwal in qtile? Apwal is a tool that will bring up a list of icons around the clicked point, each icon lauches an application. It would be nice to make the application right in the clicked area.
Thank you!

**Comment by tych0** [comment]
On Thu, Oct 01, 2015 at 02:05:43PM -0700, QiangF wrote:
> Hi everyone,
> In freecad, there is a cool mouse binding: click middle button the click right button to rotate view.
> Ho can I make it to run apwal in qtile?

Read the documentation,

http://docs.qtile.org/en/latest/manual/config/mouse.html

> Apwal is a tool that will bring up a list of icons around the clicked point, each icon lauches an application. It would be nice to make the application right in the clicked area.
> Thank you! 

You'll have to set it as a floating window by default, and then set
its position. You could do this with a hook that fires when the window
spawns.

**Comment by flacjacket** [comment]
In addition to what Tycho said, you should also look at the lazy functions to spawn your program:

http://qtile.readthedocs.org/en/latest/manual/config/keys.html#lazy-functions

**Comment by QiangF** [comment]
But can you set a timer after press the middle button, then if you click right button say within 0.5 seconds after that do something? And what is the binding for press left and right mouse button at the same time?

**Comment by flacjacket** [comment]
We don't have support for chained commands like that, there is already a feature request open for it #470. We currently only trigger `Click` commands on the button press, so there isn't a way to set it up to handle two mouse button presses.

**Comment by QiangF** [comment]
Maybe you should also considr add mouse gestures in the future, then qtile can be used on tablet and phones, that will be cool.

**Comment by flacjacket** [comment]
Closing this in favor of #800
