### ISSUE TITLE
How to pan with keyboard

### ISSUE THREAD

**Issue by QiangF** [qtile/qtile#771]
Hi everyone,
I have a display with a native resolution of 1024X600. I set it to 1024X724, because some window can't be display in the native resolution. I have to use the mouse to do the panning. 
Is it possible to do the panning with keyboard in qtile?
Is there a way to set all windows be displayed in the upper 1024X600 region of the display? 
Thank you!

**Comment by tych0** [comment]
On Thu, Oct 01, 2015 at 02:26:15PM -0700, QiangF wrote:
> Hi everyone,
> I have a display with a native resolution of 1024X600. I set it to 1024X724, because some window can't be display in the native resolution. I have to use the mouse to do the panning. 
> Is it possible to do the panning with keyboard in qtile?

I'm not sure what you mean here.

> Is there a way to set all windows be displayed in the upper 1024X600 region of the display? 

Have you tried `Screen(width=..., height=...)`?

**Comment by QiangF** [comment]
I mean my desktop is bigger than my physical screen, so there is a need to pan.

**Comment by QiangF** [comment]
Perhaps the question should be can I set qutile to only use the upper part of the display 1024X600 out of 1024x724 for tiling window? And use the full display for floating window since I can pan with my mouse.

**Comment by flacjacket** [comment]
Yes, if you use the `Screen(width=..., height=...)` configuration that Tycho suggested, you can set the height of the screen in qtile to be different that what the monitor is displaying. Because this is a static configuration, there is no way currently to pan the view around when you do this.

**Comment by QiangF** [comment]
FYI, I have find EXWM -- an window manager using emacs, it's unbelievably amazing!
