### ISSUE TITLE
python 3.5 for archlinux

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#772]
If on stable qtile release (maybe and on git version) Qtile crashes after python 3 upgrade to 3.5.
Workaround for now is to reinstall qtile. Maybe this is problem of Arch linux packaging (should ask for new version)

**Comment by tych0** [comment]
On Fri, Oct 02, 2015 at 12:38:51AM -0700, Arnas Udovičius wrote:
> If on stable qtile release (maybe and on git version) Qtile crashes after python 3 upgrade to 3.5.
> Workaround for now is to reinstall qtile. Maybe this is problem of Arch linux packaging (should ask for new version)

Can you post a stack trace please?

**Comment by flacjacket** [comment]
Ping @Roger who handles arch packaging

**Comment by flacjacket** [comment]
It might be something to do with the cffi stuff needing to be built with the right Python version?

**Comment by zordsdavini** [comment]
I just reinstalled and everything works fine. So we just need bump new
versiom on arch aur packaging system. I dont have log for it,  but I guess
it tried to look for libqtile under 3.5 version but it was under 3.4. So,
after Roger will fix, i'll ask to close. Now leave it for information how
to make workaround
2015 Spal. 2 19:19 "Sean Vig" <notifications@github.com> rašė:

**Comment by ghosthoughts** [comment]
Reinstalling did not resolve the issue for me. I have attached the error screenshot as I am on command line at the moment and posting this from phone.

![img_20151005_142316](https://cloud.githubusercontent.com/assets/1915507/10276439/0c696e3e-6b6d-11e5-826c-1b7985bac36a.jpg)

**Comment by ghosthoughts** [comment]
On further inspection (or it may be obvious to you guys from the screenshot), I found that the prompt widget causes the issue. I have replaced its usage temporarily with dmenu.
Note that I had to comment out the `Prompt()` line in both, `default_config.py` and user config file. Am I correct to understand that `default_config.py` is read regardless of providing a user config, followed by user config overwriting the conflicting values.?

**Comment by tych0** [comment]
hi,

On Mon, Oct 05, 2015 at 06:58:33AM -0700, Jayesh Bhoot wrote:
> On further inspection (or it may be obvious to you guys from the screenshot), I found that the prompt widget causes the issue. I have replaced its usage temporarily with dmenu.
> Note that I had to comment out the `Prompt()` line in both, `default_config.py` and user config file. Am I correct to understand that `default_config.py` is read regardless of providing a user config, followed by user config overwriting the conflicting values.?

d53cb9c791d4c8f02223ce0fdb5126670dc346af should fix your issue if you
install from the latest source.

**Comment by ghosthoughts** [comment]
> d53cb9c should fix your issue if you install from the latest source.

That worked like a charm! Thanks a lot!
As a side note, I must say qtile is a lot more comfortable and intuitive than the clumsy/unintuitive i3 or awesome. I experienced the fact the hard way after having to unsuccessfully resort to them today as fallbacks.
Keep up the good work!

**Comment by Roger** [comment]
This should be "fixed", i updated revisions on packages, to force rebuild the package for python3.5

**Comment by ThomasChiroux** [comment]
Hi!

I've another issue after upgrading my archlinux to python3.5 (and upgraded qtile to the latest git via aur).
When moving a window to another group, i get the following traceback:

2015-10-06 16:53:47,205 ERROR handle_KeyPress:912 KB command error togroup: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 94, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 1222, in cmd_togroup
    self.togroup(groupName)
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 986, in togroup
    self.group.remove(self)
  File "/usr/lib/python3.5/site-packages/libqtile/group.py", line 283, in remove
    i.remove(win)
  File "/usr/lib/python3.5/site-packages/libqtile/layout/tree.py", line 358, in remove
    self._nodes[win.window.wid].remove()
KeyError: 10635015

**Comment by tych0** [comment]
On Tue, Oct 06, 2015 at 07:59:13AM -0700, Thomas Chiroux wrote:
> Hi!
> 
> I've another issue after upgrading my archlinux to python3.5 (and upgraded qtile to the latest git via aur).
> When moving a window to another group, i get the following traceback:
> 
> 2015-10-06 16:53:47,205 ERROR handle_KeyPress:912 KB command error togroup: Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 94, in call
>     return (SUCCESS, cmd(*args, **kwargs))
>   File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 1222, in cmd_togroup
>     self.togroup(groupName)
>   File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 986, in togroup
>     self.group.remove(self)
>   File "/usr/lib/python3.5/site-packages/libqtile/group.py", line 283, in remove
>     i.remove(win)
>   File "/usr/lib/python3.5/site-packages/libqtile/layout/tree.py", line 358, in remove
>     self._nodes[win.window.wid].remove()
> KeyError: 10635015

Thanks for the report. Can you file a separate issue so we can keep
track? Thanks!

**Comment by ThomasChiroux** [comment]
yep will do that, thanks.

**Comment by flacjacket** [comment]
> This should be "fixed"

Re-open if this remains a problem, thanks!
