### ISSUE TITLE
MailDir widget problem

### ISSUE THREAD

**Issue by tollerm** [qtile/qtile#773]
Hi,
The MailDir widget cannot find a path to a directory with a mail. After quick look it turned out that the problem happens in the poll function when looping over mail directory. In "for loop" a container is "self._SubFolders". Shouldn't it be without underscore, i.e. "self.subFolders"? After this changing the widget works as expected. I do not know (or too lazy to look deeply in the source code) how function parameters are passed when initializing an object, though.

**Comment by flacjacket** [comment]
Thanks for the bug report. I made a small change to the Maildir widget that I think should fix this. If it doesn't work, you can re-open this.
