### ISSUE TITLE
Re-implement layout serialization

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#774]
After several reports of bugginess, the layout serialization scheme that we'd implemented has been rolled back. The relevant had addressed several reported serialization bugs which had been closed, so this will stand in for those old issues. The commit that reverts the changes can be seen here 514628612ac07d1d564cd810a5f22244d97329a2, along with links to the relevant PR's. This code must be cleaned up and properly tested before we can re-include it.

**Comment by elParaguayo** [comment]
7 years old and we've made changes to how we preserve state. Think we can close this...
