### ISSUE TITLE
A new window should pop on the group where it was launched, not on the current one

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#775]
Right now, if I'm in group A, open something a bit heavy to load (i.e. Chromium) and switch to group B, the window will appear in group B, while I would expect it in group A.

**Comment by tych0** [comment]
On Fri, Oct 02, 2015 at 05:52:27PM -0700, Guillaume Gelin wrote:
> Right now, if I'm in group A, open something a bit heavy to load (i.e. Chromium) and switch to group B, the window will appear in group B, while I would expect it in group A.

Are you doing this from the prompt? We could use the same hack we use
for Match there, but it doesn't work for everything. If it's not from
prompt, I'm not sure we really have any hope of doing this
successfully.

**Comment by ramnes** [comment]
It's true for every window, from the prompt or not.

Couldn't we use a kind of queue where is put every instruction, with some info like on what group it was called?

**Comment by tych0** [comment]
On Sat, Oct 03, 2015 at 03:32:28AM -0700, Guillaume Gelin wrote:
> It's true for every window, from the prompt or not.
> 
> Couldn't we use a kind of queue where is put every instruction, with some info like on what group it was called?

What happens if a process calls fork()?

**Comment by ramnes** [comment]
I can't find a concrete example in my use cases where I would like a process to fork and go on an other group, so I think children processes should always be spawned in their parent group. This would actually partially resolve #538!

**Comment by tych0** [comment]
On Sat, Oct 03, 2015 at 04:50:53AM -0700, Guillaume Gelin wrote:
> I can't find a concrete example in my use cases where I would like a process to fork and go on an other group, so I think children processes should always be spawned in their parent group. This would actually partially resolve #538!

No, I mean, how does qtile detect a fork that creates a new window?

**Comment by ramnes** [comment]
IRC copy-pastah:

```
22h29 dx: one answer to that question can be WM_TRANSIENT_FOR
22h29 dx: https://tronche.com/gui/x/icccm/sec-4.html#WM_TRANSIENT_FOR
22h30 dx: "The WM_TRANSIENT_FOR property (of type WINDOW) contains the ID of another top-level window. The implication is that this window is a pop-up on behalf of the named window"
22h31 dx: unlikely to cover fork() or fork()+exec() but it's something we should do
22h31 ramnes: yep
22h31 ramnes: for the fork thing
22h32 ramnes: I guess we could try when a new window appears to see if its parent process has a window
22h32 ramnes: and then do things accordingly
22h33 ramnes: might be a bit overkill/slow tho
22h33 dx: emphasis in "try", some process detach themselves from the parents
22h33 dx: *processes
22h34 @tych0: right
22h34 @tych0: i don't think there's a fool proof way to do this
22h35 ramnes: I guess if we can't find a parent, we should just put the window in the focused screen/group
22h35 ramnes: (captain obvious)
22h35 dx: we should just do whatever the current behavior is
```

**Comment by alexf91** [comment]
There's also a problem with some terminals (gnome-terminal, xfce4-terminal, ...):
Apparently, these terminals run a server process, so I don't think that there's a way to find out from which window a new process is started, because the parent's PID of the new window just points to the server.

Otherwise, something like this should work:
```python
import psutil

def get_parent_window(window):
    windowMap = window.qtile.windowMap

    # Get the PIDs of all windows. Filter out PIDs with multiple windows,
    # since we can't determine the correct parent from it.
    pids = [w.window.get_net_wm_pid() for w in windowMap.values()]
    filter_condition = lambda x: x and pids.count(x) == 1
    pids = list(filter(filter_condition, pids))

    processMap = {w.window.get_net_wm_pid() : w for w in windowMap.values()}
    processMap = {k:v for k,v in processMap.items() if k in pids}

    # If a window has WM_TRANSIENT_FOR set, we can get it's parent immediately
    parentWid = window.window.get_wm_transient_for()
    if parentWid in windowMap:
        return windowMap.get(parentWid)

    # Otherwise, we have to search for a parent window by looking at the
    # parent processes
    pid = window.window.get_net_wm_pid()
    if pid is None:
        return

    parent = psutil.Process(pid).parent()
    while parent:
        parentWindow = processMap.get(parent.pid, None)
        if parentWindow:
            return parentWindow

        parent = parent.parent()
```

**Comment by nicoe** [comment]
Is this fixed by 9bbd90859b024ffe9283fa52881226c8525ac160 ?

**Comment by jmi2k** [comment]
Can this even be accomplished? I mean, any process can create windows at any moment. The only way I can think on is to start processes with a custom command (`qlaunch ...` for example), and record the PID of the process. Then, whenever a window is created, qtile looks for the PID of the process who created the window, and if it is registered, then display it in the correct group. If not in the list, default to the current behaviour.

**Comment by nicoe** [comment]
According to me it depends what you call 'launch'.
If launch means that it's a dialog window or a modal window for another window then it should be possible.
But indeed if 'launch' means that it's a command executed from urxvt / … then it's not possible according to me.

**Comment by m-col** [comment]
I also don't think there is any way to tie a process that creates a new window to a specific group to know where to move it. I modified a snippet from a discussion on window swallowing (https://github.com/qtile/qtile/issues/1771) to get the behaviour mentioned in that IRC snippet above, which seems to work pretty well actually.
```
import psutil

@hook.subscribe.client_new
def _swallow(window):
    ppid = psutil.Process(window.window.get_net_wm_pid()).ppid()
    pids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
    for i in range(5):
        if not ppid:
            return
        if ppid in pids:
            parent = window.qtile.windows_map.get(pids[ppid])
            window.togroup(parent.group.name)
            return
        ppid = psutil.Process(ppid).ppid()
```
It's a bit of a workaround but as others have said I don't think a "proper" way to always do this is possible.

I'm going to close this because it's pretty old and the consensus seems to be that it isn't possible (beyond this kind of workaround).
