### ISSUE TITLE
Conkeror window always floated

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#778]
_NET_WM_USER_TIME(CARDINAL) = 8547499
ZOOM(UTF8_STRING) = "1.0"
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
                window id # of group leader: 0x2400001
WM_WINDOW_ROLE(STRING) = "browser"
XdndAware(ATOM) = BITMAP
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 37748889
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2400098
WM_CLIENT_LEADER(WINDOW): window id # 0x2400001
_NET_WM_PID(CARDINAL) = 20469
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "steven-series9"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified minimum size: 104 by 76
                program specified maximum size: 32767 by 32767
                window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Navigator", "Conkeror"
WM_ICON_NAME(STRING) = "{default} https://github.com/qtile/qtile/issues/new"
_NET_WM_ICON_NAME(UTF8_STRING) = "{default} https://github.com/qtile/qtile/issues/new"
WM_NAME(STRING) = "{default} https://github.com/qtile/qtile/issues/new"
_NET_WM_NAME(UTF8_STRING) = "{default} https://github.com/qtile/qtile/issues/new"

{'float_info': {'h': 900, 'w': 1600, 'x': 0, 'y': 0},
  'floating': True,
  'fullscreen': True,
  'group': '1',
  'height': 900,
  'id': 37748865,
  'maximized': False,
  'minimized': False,
  'name': '{default} '
          'http://unix.stackexchange.com/questions/39145/execute-command-in-remote-active-terminal',
  'width': 1600,
  'x': 0,
  'y': 0},

**Comment by flacjacket** [comment]
What is your config file like?

**Comment by tych0** [comment]
On Wed, Oct 07, 2015 at 03:45:37AM -0700, Steven wrote:
> _NET_WM_USER_TIME(CARDINAL) = 8547499
> ZOOM(UTF8_STRING) = "1.0"
> _NET_WM_DESKTOP(CARDINAL) = 0
> WM_STATE(WM_STATE):
>                 window state: Normal
>                 icon window: 0x0
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN

This looks like the source of your issue, any idea why this is getting
set?

**Comment by jagguli** [comment]
here's my config https://bitbucket.org/jagguli/qtile_config/src/2bd949efc017?at=master

no idea why thats being set, I've worked around it by creating set_group hooks, might be a change in conkeror.
