### ISSUE TITLE
"Gracefully" handle X dying

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#784]
If we have X die on us, either through a bug in X, or for testing, by starting in Xephyr and killing Xephyr, qtile goes into an infinite loop. Something in this loop should recognize the problem and kill the eventloop.

**Comment by tych0** [comment]
On Tue, Oct 13, 2015 at 03:15:09PM -0700, Sean Vig wrote:
> If we have X die on us, either through a bug in X, or for testing, by starting in Xephyr and killing Xephyr, qtile goes into an infinite loop. Something in this loop should recognize the problem and kill the eventloop.

Is there an example stack trace of this somewhere? I remember looking
at this a while ago.

**Comment by flacjacket** [comment]
So I tried to reproduce this, someone reported it on IRC and I made this to not forget about it, but it looks like this is fixed in the current develop, so I'm not sure this is still valid

**Comment by nxnfufunezn** [comment]
I can vouch that this has been fixed, It used to happen earlier.

**Comment by nxnfufunezn** [comment]
For me it used to happen when I killed xephyr from terminal.

**Comment by flacjacket** [comment]
Great, thanks for the feedback!
