### ISSUE TITLE
Add sound option to notification widget

### ISSUE THREAD

**Issue by nxnfufunezn** [qtile/qtile#786]
Notification widget can have optional sound parameter to play sound on notification.

**Comment by nxnfufunezn** [comment]
Working on this!

**Comment by nxnfufunezn** [comment]
Should I use subprocess call  "ffplay" or use external libraries which will add more dependencies ?

**Comment by flacjacket** [comment]
Since it looks like you logged off IRC and missed this:
```
06:48:25 <ramnes> no idea
06:48:45 <ramnes> I think I would have used cmd_spawn to call aplay, since it's pretty standard
```
^^ This would be a good starting point

**Comment by nxnfufunezn** [comment]
thanks.. @flacjacket
