### ISSUE TITLE
SystTray widget does not show up on secondary screen

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#792]
I have a multi monitor setup, and I have only one systray in one of the  bars in one screen, 

If the bar/screen is displayed on the primary monitor the system tray shows up.

If the bar/screen is displayed on the secondary monitor the syetem tray does not show up.

If the systray is added to both screens, it shows up on the primary.

I'm quite sure this used to work for me before.

Tested this on qtile (pip) python2/3

**Comment by flacjacket** [comment]
See #500

**Comment by jagguli** [comment]
Yep but its not the same, the systray doesn't show up even if its only added once, on the secondary screen.

**Comment by tych0** [comment]
This could be what I'm seeing, although I haven't tried to put the systray
in screen 0 ti see if it works.

0.10.1 doesn't have this problem.

**Comment by flacjacket** [comment]
Oh, I see what you're saying, so @jagguli, what versions is the systray broken on? If it's on a change between 0.10.1 and 0.10.2, it should be easy enough to track down.

**Comment by flacjacket** [comment]
It looks like this was introduced in 0.10.2, does this fix your problem:

https://github.com/flacjacket/qtile/tree/fix_systray_secondary_screen

**Comment by jagguli** [comment]
Yes that does, thank you.
