### ISSUE TITLE
Collapsed borders in tiled layouts

### ISSUE THREAD

**Issue by wavexx** [qtile/qtile#798]
I'm pretty new to qtile, but I've been using several tiling window mangers before (awesome, spectrm, i3, etc). I'd like to point out a nice feature in i3, which I later ported to spectrwm, and I'd love to have in qtile as well: collapsed borders.

In a tiled setup, I like to have fat borders (at least 3 pixels) to have a strong indicator of focus. However, the edges of the tiles become twice as wide, which wastes a lot of space for no reason. Since the borders have a flat color, it makes sense to overlay the borders in the middle of the layout, making sure the focused window stays raised.

Not only it saves space, but IMHO it actually looks much better.

The following is a regular tiled layout:

![normal](https://cloud.githubusercontent.com/assets/1017726/10965380/de86c0a4-83ac-11e5-93df-0b9b62b52107.png)

and this is a layout with collapsed borders:

![collapsed](https://cloud.githubusercontent.com/assets/1017726/10965388/e811d01e-83ac-11e5-845d-41e86122172c.png)

**Comment by de-vri-es** [comment]
I had a quick look at the source code, and it seems currently each layout would have to support collapsed borders individually.

I was thinking it is also possible to add some datastructure for layouts to return that describes how to tile the windows, and then have something else (a `Tiler`?) do the tiling. Then only that other thing has to be able to do border collapsing.

Of course, that doesn't work for layouts that don't fit the datastructure. The current interface gives layout maximum flexibility, allowing for arbitrary placement and sizes.

A compromise could be to add a `Tiler` but have layouts invoke it, or not. That would remove the need for code duplication without taking away the flexibility of the current layout API.

I may make a PR for this, as I would really like to have collapsed borders (it's keeping me on xmonad for now).

**Comment by m-col** [comment]
This is actually already possible by setting the margin setting of a layout to `- border_width //2` :P

Caveat: you also need to add a margin around the outside of the layout otherwise the windows would also grow outward offscreen

**Comment by m-col** [comment]
I'm going to close this as it's possible.

**Comment by wavexx** [comment]
On Sun, Aug 23 2020, m-col wrote:
> This is actually already possible by setting the margin setting of a
> layout to `- border_width //2` :P
>
> Caveat: you also need to add a margin around the outside of the layout
> otherwise the windows would also grow outward offscreen

I'm revisiting this now, but it still doesn't seem to work as I would
expect.

Adding margin makes sense, but how do I do that on all screens?

Testing using the "Column" layout, the focused window is not restacked
on top of neighbors, so the border can be occluded (indication of focus
is partially hidden depending on the where the window is inside the
layout). The same is true in "Tile".
