### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#800]
QiangF already suggested to add gestures to Qtile. If we think about future - it is one of killing feature according to others managers. So, I looked for some articles about it. One of them http://snipplr.com/view/7216/mouse-gestures/
We could discuss how it should look and gather all information about it and then we could implement it

**Comment by flacjacket** [comment]
#770 The other issue for reference

It would definitely be great to have some form of mouse or touch gesture support if it can be integrated with current key and mouse events

**Comment by zordsdavini** [comment]
All suggestions for what gestures should be supported and what it should do are welcome :) Now I got laptop with touchscreen, so I'll try to do something here after dmenu wrapper and extentions.

**Comment by m-col** [comment]
IMO this is probably best left to something like [libinput-gestures](https://github.com/bulletmark/libinput-gestures). With that, we can bind complex gestures to arbitrary shell commands and can manipulate Qtile via those.

**Comment by LucStr** [comment]
Are Gestures supported in qtile?

**Comment by m-col** [comment]
Not directly - you can use libinput-gestures to bind commands to gestures under X11. Gestures are not supported under Wayland. I think supporting for binding things to them from within Qtile would be welcome but nobody has picked it up.

**Comment by godalming123** [comment]
This would be really nice. Since currently libinput-gestures does not appear to support 1:1 gestures (this could be implemented by running a command but substiting values with `{}`) **EG:**
```
open-menu -progress{x-touchpad-cord}
```
