### ISSUE TITLE
Docs don't include all defaults

### ISSUE THREAD

**Issue by Azd325** [qtile/qtile#803]
e.g:
 [Doc of `AGroupBox`](http://docs.qtile.org/en/latest/manual/ref/widgets.html?highlight=widget#libqtile.widget.AGroupBox
) 
Has only one row of defaults but in the code `AGroupBox` inherits from `_GroupBase` what has the has also defaults (borderwidth, center_aligned) but they don't get documented with sphinx. So it should be at least 3 rows.

I found this because I wanted to change the border of the `Groupbox` but didn't find anything about it

**Comment by flacjacket** [comment]
I think this is a problem with the way we handle and display those defaults. Currently, each class instance loads its parent's defaults and only defines new or overriding values, which is all the docs currently know how to display, but really they should display the parents options, too (and ideally from which parent it is inherited). See https://github.com/qtile/qtile/blob/develop/docs/sphinx_qtile.py

**Comment by Azd325** [comment]
:+1:
