### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by Azd325** [qtile/qtile#804]
It would be cool if we had this file to improve contributions because I saw that this page [Qtile Contributing Guideline](http://docs.qtile.org/en/latest/manual/contributing.html) is not linked in the [README](https://github.com/qtile/qtile#contributing) and we had this yellow box from https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by flacjacket** [comment]
I'd be all for this. Tho I don't know if we'd just want to link to our contribution docs page or add something more.

**Comment by Azd325** [comment]
In my opinion it would enough to give the user some basic information about reporting, maybe this part http://docs.qtile.org/en/latest/manual/contributing.html#reporting-bugs.
Otherwise I would add a link to the documentation so that we only have one page to maintain.
