### ISSUE TITLE
`lazy.group.{prev,next}_window` don't work with VerticalTile

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#806]
Nothing happens.

**Comment by tych0** [comment]
On Fri, Nov 13, 2015 at 07:04:26AM -0800, Guillaume Gelin wrote:
> Nothing happens.

What about getting rid of the hyphen?

**Comment by ramnes** [comment]
You mean the underscore? It doesn't work on any layout if I remove it.

**Comment by ramnes** [comment]
By the way, this is kinda related to #665. We should test that commands are consistent between layouts.

**Comment by flacjacket** [comment]
Does this fix it? https://github.com/flacjacket/qtile/tree/verticaltile_next

We definitely some better guidelines for the layout methods.

**Comment by flacjacket** [comment]
This emphasizes the need for a standard guide on what all needs to be in a layout, but it should be fixed now
