### ISSUE TITLE
Params with fallbacks (e.g. padding_y) are ignored if they're set to 0

### ISSUE THREAD

**Issue by mjkillough** [qtile/qtile#820]
`configurable.ExtraFallback.hidden_attribute()` uses the fallback attribute if the configured value is falsey.

This means that passing `padding_y=0` to widgets like `widget.GroupBox()` has no effect.

**Comment by tych0** [comment]
Does the above happen to fix it?

**Comment by mjkillough** [comment]
Yes. :) You beat me to it - I was just committing the same fix.

I'll still make a PR, as I have added some tests.

**Comment by tych0** [comment]
Great, thanks!

**Comment by mjkillough** [comment]
Fixed in 9f596cb2a5945ad4a5f2ba4dc94e4c196ffd8a53. (I failed to put the magic "closes #820" in the commit message).

Thanks for the quick response @tych0, @flacjacket.

**Comment by tych0** [comment]
Sure, np. Thanks for debugging.
