### ISSUE TITLE
hacking.rst should list xrandr as a requirement

### ISSUE THREAD

**Issue by mjkillough** [qtile/qtile#822]
`tests/test_manager.py` uses `xrandr` and the tests fail if it is not installed. It is not currently listed as a dependency in `hacking.rst`.

**Comment by s-hell** [comment]
I've added a Pull Request [#824](https://github.com/qtile/qtile/pull/824)

**Comment by mjkillough** [comment]
This was fixed by 7aba22c4af0120434b40a00c8c222ba73a2945c4.
