### ISSUE TITLE
some dead area

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#827]
qtile-10.2

I have got some area that looks dead. I can't touch it or somehow to move it
![20151207_1416](https://cloud.githubusercontent.com/assets/4191548/11626686/629337e8-9ced-11e5-8b2e-06e4189e8d9c.png)

what should I give logs to find what Qtile did here?

**Comment by zordsdavini** [comment]
ok, it was my owncloud Qt instance:
arnas@arns-arch ~> xprop _NET_WM_PID
_NET_WM_PID(CARDINAL) = 22477
arnas@arns-arch ~> ps --pid=22477
  PID TTY          TIME CMD
22477 ?        00:00:21 owncloud

Next question, why Qt left such area?

**Comment by flacjacket** [comment]
Hmm, that's very odd, is this reproducible? What if you add more windows, does the un-allocated space change? Can you move your window around with your shuffle_up command? Can you take a look with qsh and see what other windows it thinks are running?

**Comment by zordsdavini** [comment]
I can't it reproduce when I want :) But it repeats time after time. It
doesn't listen to window move. But if I toggle background window  to float
and back, this dead area will become in background. One more thing: this
dead area exist in all groups same place

On 12 December 2015 at 00:25, Sean Vig <notifications@github.com> wrote:

> Hmm, that's very odd, is this reproducible? What if you add more windows,
> does the un-allocated space change? Can you move your window around with
> your shuffle_up command? Can you take a look with qsh and see what other
> windows it thinks are running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/827#issuecomment-164065752>.
>



-- 
Udovīčė Arns

**Comment by zordsdavini** [comment]
shuffle_up doesn't change anything. If I create new window it will appear  in front of this dead area.
I tried to look with qsh, but I don't know what I should look for, so some infos (it can be about other window):

window> ls
group/     screen/    layout/    6293536/   10485937/  10485915/  35651620/  31457289/  29360131/  23068673/  12586363/
<...>
window[6293536]> cd ../10485937
window[10485937]> info
{'float_info': {'h': 1, 'w': 1, 'x': -1, 'y': -1},
 'floating': False,
 'fullscreen': False,
 'group': None,
 'height': 1,
 'id': 10485937,
 'maximized': False,
 'minimized': False,
 'name': '<no name>',
 'width': 1,
 'x': -1,
 'y': -1}
window[10485937]> cd ..
window> cd 10485915
window[10485915]> info
{'float_info': {'h': 24, 'w': 1366, 'x': 0, 'y': 0},
 'floating': False,
 'fullscreen': False,
 'group': None,
 'height': 24,
 'id': 10485915,
 'maximized': False,
 'minimized': False,
 'name': '<no name>',
 'width': 1366,
 'x': 0,
 'y': 0}
<...>
window[35651620]> inspect     **<-- after fix window it leavs the same**
{'attributes': {'all_event_masks': 6463615,
                'backing_pixel': 0,
                'backing_planes': 4294967295,
                'backing_store': 0,
                'bit_gravity': 0,
                'class': 1,
                'do_not_propagate_mask': 0,
                'map_is_installed': 0,
                'map_state': 2,
                'override_redirect': 1,
                'save_under': 0,
                'visual': 159,
                'win_gravity': 1,
                'your_event_mask': 4358144},
 'float_info': {'h': 16, 'w': 16, 'x': 1418, 'y': 4},
 'hints': {'flags': {'InputHint', 'StateHint'},
           'icon_mask': 0,
           'icon_pixmap': 0,
           'icon_window': 0,
           'icon_x': 0,
           'icon_y': 0,
           'initial_state': 1,
           'input': 1,
           'window_group': 0},
 'name': 'ownCloud',
 'normalhints': {'base_height': 0,
                 'base_width': 0,
                 'flags': {'PMinSize', 'USSize', 'USPosition', 'PWinGravity'},
                 'height_inc': 0,
                 'max_aspect': 0,
                 'max_height': 0,
                 'max_width': 0,
                 'min_aspect': 0,
                 'min_height': 22,
                 'min_width': 22,
                 'width_inc': 0,
                 'win_gravity': 0},
 'properties': ['WM_STATE',
                '_NET_WM_USER_TIME',
                '_NET_WM_ICON',
                'XdndAware',
                'WM_NAME',
                '_NET_WM_NAME',
                '_MOTIF_WM_HINTS',
                '_NET_WM_WINDOW_TYPE',
                '_XEMBED_INFO',
                'WM_CLIENT_LEADER',
                'WM_HINTS',
                '_NET_WM_PID',
                'WM_CLASS',
                'WM_PROTOCOLS',
                'WM_NORMAL_HINTS'],
 'protocols': ['WM_DELETE_WINDOW', '_NET_WM_PING', 'WM_TAKE_FOCUS'],
 'state': (1, 0),
 'wm_class': ('owncloud', 'ownCloud'),
 'wm_client_machine': None,
 'wm_icon_name': None,
 'wm_transient_for': None,
 'wm_type': '_KDE_NET_WM_WINDOW_TYPE_OVERRIDE',
 'wm_window_role': None}
<....>
window[10485915]> inspect      **<-- I don't know what is it**
{'attributes': {'all_event_masks': 6455325,
                'backing_pixel': 0,
                'backing_planes': 4294967295,
                'backing_store': 0,
                'bit_gravity': 0,
                'class': 1,
                'do_not_propagate_mask': 0,
                'map_is_installed': 1,
                'map_state': 2,
                'override_redirect': 0,
                'save_under': 0,
                'visual': 33,
                'win_gravity': 1,
                'your_event_mask': 6455325},
 'float_info': {'h': 24, 'w': 1366, 'x': 0, 'y': 0},
 'hints': None,
 'name': None,
 'normalhints': None,
 'properties': ['_NET_WM_WINDOW_OPACITY', 'WM_STATE', 'QTILE_INTERNAL'],
 'protocols': [],
 'state': (1, 0),
 'wm_class': None,
 'wm_client_machine': None,
 'wm_icon_name': None,
 'wm_transient_for': None,
 'wm_type': None,
 'wm_window_role': None}
<...>
window[10485937]> inspect
{'attributes': {'all_event_masks': 4358144,
                'backing_pixel': 0,
                'backing_planes': 4294967295,
                'backing_store': 0,
                'bit_gravity': 0,
                'class': 1,
                'do_not_propagate_mask': 0,
                'map_is_installed': 1,
                'map_state': 0,
                'override_redirect': 0,
                'save_under': 0,
                'visual': 33,
                'win_gravity': 1,
                'your_event_mask': 163840},
 'float_info': {'h': 1, 'w': 1, 'x': -1, 'y': -1},      **<-- is it good?**
 'hints': None,
 'name': None,
 'normalhints': None,
 'properties': ['WM_STATE'],
 'protocols': [],
 'state': (1, 0),
 'wm_class': None,
 'wm_client_machine': None,
 'wm_icon_name': None,
 'wm_transient_for': None,
 'wm_type': None,
 'wm_window_role': None}

When it happens? I suspended computer and move to another place, so wifi should be re enabled. Next thing is that I uploaded some photos, so it should sync in background. Other interesting case that I moved mouse on dead area and got help text (it is something similar like title attribute popups in html). I was be able to expand tree of files in owncloud settings (that was the window), but it doesn't lissen to any qtile key bindings, I couldn't close the window, just clicking notification icon helps (redraw and then close by clicking icon)

**Comment by zordsdavini** [comment]
on Qtile 0.10.4 problem still exist

**Comment by flacjacket** [comment]
How reproducible is this? Is it on all layouts? Any programs that trigger it? I haven't seen this, is you know a way I can reproduce I can look into this. One thing to check is in qsh you can cd into screen and run info(), it should give the actual screen size.

**Comment by zordsdavini** [comment]
This I can reproduce like this:
run owncload client, login
suspend
move to other network (new environment)
wake up
owncloud is doing sync – it creates float window what is not managed by
qtile

clicking on systray will add content to this window and I can close it (but
not move or something else)

next time I'll look in qsh for info()

On 21 January 2016 at 09:43, Sean Vig <notifications@github.com> wrote:

> How reproducible is this? Is it on all layouts? Any programs that trigger
> it? I haven't seen this, is you know a way I can reproduce I can look into
> this. One thing to check is in qsh you can cd into screen and run info(),
> it should give the actual screen size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/827#issuecomment-173485378>.
>



-- 
Udovīčė Arns

**Comment by zordsdavini** [comment]
I tried qsh. It just give:
$ qsh
> cd screen
screen> ls
layout/  window/  bar/     0/       1/
screen> cd 0
screen[0]> ls
layout/  window/  bar/
screen[0]> info()
{'height': 1200, 'index': 0, 'width': 1920, 'x': 0, 'y': 0}

screen[0]> cd layout
screen[0].layout> info()
{'clients': ['qsh'], 'group': 'd', 'name': 'max'}
![20160125_0818](https://cloud.githubusercontent.com/assets/4191548/12543830/33e50852-c33c-11e5-9989-491b739839a2.png)

**Comment by emdete** [comment]
this looks like a problem i investigated a bit as well but it happened after a restart of qtile.

it seems to be a qt problem when the program does not close the window properly. the window stays but is in a strange state and won't answer on X11 requests. on restart qtile maps the window to the screen but it's noop.

i have the problem with qupzilla for example with basic-auth login windows. when you had one and restart qtile it happens.

**Comment by zordsdavini** [comment]
yes, it is mostly after qtile restart, because I move from two monitors,
suspend and wake up with only one monitor

On 27 January 2016 at 20:08, M. Dietrich <notifications@github.com> wrote:

> this looks like a problem i investigated a bit as well but it happened
> after a restart of qtile.
>
> it seems to be a qt problem when the program does not close the window
> properly. the window stays but is in a strange state and won't answer on
> X11 requests. on restart qtile maps the window to the screen but it's noop.
>
> i have the problem with qupzilla for example with basic-auth login
> windows. when you had one and restart qtile it happens.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/827#issuecomment-175776358>.
>



-- 
Udovīčė Arns

**Comment by zordsdavini** [comment]
In Qtile 0.10.5 I haven't got that bug, so I close this bug. If I'll get something – I'll reopen it
