### ISSUE TITLE
lazy.screen.nextgroup() and lazy.screen.prevgroup() incorrect in documentation

### ISSUE THREAD

**Issue by stutonk** [qtile/qtile#829]
The names of these functions are not properly documented on this page:
http://docs.qtile.org/en/latest/manual/config/keys.html

After poking around in the soruce, it looks like they're supposed to be next_group() and prev_group()

**Comment by flacjacket** [comment]
I think this is just because the docs building on readthedocs was broken for a few versions, and a new release hasn't happened since that was fixed. If you look at the develop docs [1], you'll see the correct functions.

[1] http://docs.qtile.org/en/develop/manual/config/keys.html

**Comment by flacjacket** [comment]
This should be fixed now.
