### ISSUE TITLE
simple_key_binder does nothing

### ISSUE THREAD

**Issue by stutonk** [qtile/qtile#830]
I have the following lines in my config.py after my list of groups:

``` python
mod = "mod4"
...
from libqtile.dgroups import simple_key_binder
dgroups_key_binder = simple_key_binder(mod)
```

which is supposed to map (in this case) WinKey + 1-0 to each group by position. Instead, nothing happens. Qtile doesn't even capture the key combo when pressed. Nothing is mentioned in the log.

**Comment by flacjacket** [comment]
This only defines the keybindings, you also need to define the groups, something like:
```
groups = [Group("%d" % (n+1)) for n in range(10)]
```

**Comment by stutonk** [comment]
I have a list of groups defined, but they're all named (not numbered). According to the documentation, the default generated binding should switch based on group's position. For example, I have a group called 'Shell' in position 1. So mod4(WinKey) + 1 should switch to that group, right?

**Comment by stutonk** [comment]
So just to test it,  I tried it with
```python
mod="mod4"
groups = [Group("%d" % (n+1)) for n in range(10)]
from libqtile.dgroups import simple_key_binder
dgroups_key_binder = simple_key_binder(mod)
```
and it still does nothing/doesn't capture the keypress combo

**Comment by flacjacket** [comment]
Yes, that is what it is supposed to do, and it should work fine for named rather than numbered groups. If you use the default config (which does explicit keybindings to a/s/d/f [1]) does that work?

[1] https://github.com/qtile/qtile/blob/develop/libqtile/resources/default_config.py#L87

**Comment by stutonk** [comment]
I tried it with the default config with the same result (doesn't capture the keypress combo/nothing happens)

I'm using Arch and I've tried both the 'qtile' and 'qtile-python3-git' AUR packages with the same results. I also confirmed that dgroups.py was there in the filesystem and simple_key_binder was correctly defined therein just to make EXTRA sure everything was kosher with my install.

**Comment by flacjacket** [comment]
With the default config, it should be Win+"a", Win+"s", etc. If that is not working, we'll have to do some more debugging. Anything non-standard with your setup?

**Comment by stutonk** [comment]
Ah, I wasn't specific enough in my last comment -- The Win+a, Win+s, etc is working in the default config. What's not working is adding simple_key_binder to the default config (that is, Win+1, Win+2, etc still does nothing when I drop in simple_key_binder below the group list). I've also tried totally restarting X after putting simple_key_binder into the config with no effect.

My setup is pretty standard. Basically all mainline Arch Linux x86_64 packages for X (and input libs), Python 3.5.0. Normal EN-US keymap, ordinary USB keyboard, etc.

**Comment by andering** [comment]
Thank you for example of code, it make it more clear,
i tried and it works as expected.

1. check if you have same problem with new release
2. check if you don't bind same Keys also to something else
3. are you running qtile from some other windows manager or standalone ?
4. give me ,if you can, your whole config.py to i can see if the problem is not coming from something else

by the way i do it this way :

```
for i, (name, kwargs) in enumerate(group_names, 1):
    keys.append(Key([mod], str(i), lazy.group[name].toscreen()))
    keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(name)))
```

it gives me more flexibility (its from [emdete config example](https://github.com/qtile/qtile-examples/blob/master/emdete/config.py))

**Comment by stutonk** [comment]
Tested on latest release (0.10.6); everything working fine.

Embarrassingly, after looking at the source and noticing that s_k_b was a higher order function I realized that the *actual* issue here was that I was using it wrong (wasn't invoking the binder on any groups). Sorry for wasting everyone's time! x_x

**Comment by parsrch** [comment]
> Thank you for example of code, it make it more clear,
> i tried and it works as expected.
> 
>     1. check if you have same problem with new release
> 
>     2. check if you don't bind same Keys also to something else
> 
>     3. are you running qtile from some other windows manager or standalone ?
> 
>     4. give me ,if you can, your whole config.py to i can see if the problem is not coming from something else
> 
> 
> by the way i do it this way :
> 
> ```
> for i, (name, kwargs) in enumerate(group_names, 1):
>     keys.append(Key([mod], str(i), lazy.group[name].toscreen()))
>     keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(name)))
> ```
> 
> it gives me more flexibility (its from [emdete config example](https://github.com/qtile/qtile-examples/blob/master/emdete/config.py))

How can I use Match with this config?
