### ISSUE TITLE
Windows are moved to the wrong groups after restart when using dgroups

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#839]
In the initialization of libqtile.window.Window, the _NET_WM_DESKTOP property is used as the index of the group, if there are enough groups created for that index to be valid.

```python
        # add to group by position according to _NET_WM_DESKTOP property
        index = window.get_wm_desktop()
        if index is not None and index < len(qtile.groups):
            group = qtile.groups[index]
            group.add(self)
```

The `index < len(qtile.groups)` part is important since that number is variable with dgroups, where groups are added as windows get managed.

This wasn't a big deal if you carefully configured groups with exclusive rules, but since commit ad355f782a5ff94f124fca8c9060a62e41a2608a the index in _NET_WM_DESKTOP takes priority over dgroups rules, so not even exclusive groups are safe from this.

This is particularly evident after reordering groups. Since the order in which they get managed isn't the order in which i'd prefer them to appear in the groupbox, I reorder those groups. For example:

"Natural" order:

    term, skype, leafpad, www, gimp

Swap www and leafpad:

    term, skype, www, leafpad, gimp

Groups after restart:

    term, skype, leafpad, gimp

Where the leafpad group has both leafpad and firefox.

In my setup only group with init=True is "term", and the "www" group is supposed to be exclusive. 

Here's a custom debug log of the relevant sections in the above situation:

```
dgroups._add:
    adding client Window('Skype')

window.group setter:
    window name: Skype
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>]
    _NET_WM_DESKTOP not set, still 1


dgroups._add:
    adding client Window('Leafpad')

window.group setter:
    window name: Leafpad
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>, <group.Group ('Leafpad')>]
    ====> _NET_WM_DESKTOP set from 3 to 2 <====


window.group setter:
    window name: maximo integer - Skype™
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>, <group.Group ('Leafpad')>]
    _NET_WM_DESKTOP not set, still 1


dgroups._add:
    ignored client Window('maximo integer - Skype™')

window.group setter:
    window name: Mozilla Firefox
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>, <group.Group ('Leafpad')>]
    _NET_WM_DESKTOP not set, still 2


dgroups._add:
    ignored client Window('Mozilla Firefox')

window.group setter:
    window name: st
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>, <group.Group ('Leafpad')>]
    _NET_WM_DESKTOP not set, still 0


dgroups._add:
    ignored client Window('st')

dgroups._add:
    adding client Window('GIMP')
    matched rule <Rule match=<Match [('wm_class', 'Gimp'), ('wm_class', 'gimp')]> actions=(group=gimp, float=True, break_on_match=True)>

window.group setter:
    window name: GIMP
    current groups: [<group.Group ('term')>, <group.Group ('Skype')>, <group.Group ('Leafpad')>, <group.Group ('gimp')>]
    ====> _NET_WM_DESKTOP set from 4 to 3 <====
```

(FWIW, the logging patch is here http://dump.dequis.org/RT_PC.txt)

The `====> _NET_WM_DESKTOP set from 3 to 2 <====` lines are when the index of the group that is being set is different from the index of the _NET_WM_DESKTOP attribute of the window. They are not actually that important but they mean that something is being moved.

The "ignored client" lines are gone if i revert ad355f782a5ff94f124fca8c9060a62e41a2608a. That improves the situation significantly since i stop getting crap in groups that have rules defined, like www or gimp.

Maybe the right solution to this nonsense is to restore groups by name from the `_NET_DESKTOP_NAMES` property of the root window

```
_NET_DESKTOP_NAMES(UTF8_STRING) = "term", "www", "Skype", "leafpad", "gimp"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
```

**Comment by flacjacket** [comment]
Did this get fixed by the recent changes to restarts and dgroups?

**Comment by dequis** [comment]
Huh I forgot I had reported this one. I think it was fixed, yeah, but can't verify it right now, not at home. I'll just close it now, making a note to check later and reopen this if i'm wrong.
