### ISSUE TITLE
some thoughts around logging

### ISSUE THREAD

**Issue by emdete** [qtile/qtile#841]
- the logline should not be formatted like in

```python
 self.qtile.log.info("Unknown window property: %s" % name)
```

 instead it is much better to write

```python
self.qtile.log.info("Unknown window property: %s" % name)
```
 and leave formatting up to the logging library (it will decide if that level will be logged at all before it does the formatting and save resources).

 - i would use loggers per module instead of a single logger for all, each module should contain a

```python
from logging import getLogger
logger = getLogger(__name__)
```

 which makes clear where the logline comes from (and the linenumbers are usefull now).

 - the config should set the level on the root logger, currently this:

```python
log = getLogger(logger)
log.setLevel(log_level)
```

only sets it for the logger `logger` (if foreign modules would use logging this would get lost). this would be better:

```python
log = getLogger()
log.setLevel(log_level)
```

 - i would not doublicate logging into file + stdout but switch by config to either way

 - color logging should be optional dis/enabled by config

 - the log member of qtile should be removed or deprecated

**Comment by emdete** [comment]
see https://github.com/qtile/qtile/pull/842

**Comment by ramnes** [comment]
> the logline should not be formatted like in
>  self.qtile.log.info("Unknown window property: %s" % name)
> instead it is much better to write
> self.qtile.log.info("Unknown window property: %s" % name)

wat?

**Comment by flacjacket** [comment]
I think the last one was supposed to be `self.qtile.log.info("Unknown window property: %s", name)`

**Comment by ramnes** [comment]
> i would use loggers per module instead of a single logger for all, each module should contain a
> from logging import getLogger
> logger = getLogger(__name__)

I really don't like this. Why would we duplicate code rather than having a single properly instanciated object, which is less prone to error and definitely more DRY?

**Comment by tych0** [comment]
On Thu, Jan 07, 2016 at 11:07:50AM -0800, Guillaume Gelin wrote:
> > i would use loggers per module instead of a single logger for all, each module should contain a
> > from logging import getLogger
> > logger = getLogger(__name__)
> 
> I really don't like this. Why would we duplicate code rather than having a single properly instanciated object, which is less prone to error and definitely more DRY?

Doesn't this way prefix each log message with the module it came from?
That seems useful (although marginally, we could grep for error
messages too which are probably mostly unique).

Overall, I like the idea of not passing a logging object around as an
attribute, but instead having a "global" one that is has the same name
in each file, so you can just write logger.error("foo"), instead of
having to figure out how to resolve the logger each time you want to
use it. Whether or not it's the same actual object or not I don't much
care about; I think the duplicate code argument is moot, though,
because each file will have either:

from libqtile.log import logger

or

from logging import getLogger
logger = getLogger(__name__)

and they don't seem radically different.

**Comment by ramnes** [comment]
That's one more useless line in each file, with zero benefit. I don't see the point. And you can have the the log message showing the line number with the current implementation (and IIRC it already does it).

**Comment by ramnes** [comment]
Also, if you use the root logger, you can just do `import logging` and `logging.info` directly, no need to use `getLogger`.

**Comment by tych0** [comment]
On Fri, Jan 08, 2016 at 08:09:08AM -0800, Guillaume Gelin wrote:
> That's one more useless line in each file, with zero benefit.

Sorry, are you talking about preferring option 2 I described above
over option 1? Because they both clearly have a benefit: you don't
have to think about how to get a logging object when you want to log
something, it's just there.

> I don't see the point. And you can have the the log message showing the line number with the current implementation (and IIRC it already does it). 

Yep, could be that option 1 is best for this reason; I don't have a
strong preference either way.

**Comment by flacjacket** [comment]
You're right that the line number is already in the log, I'd thought the reason we wanted to do `logger = getLogger(__name__)` was to get the module path in the log through the logger name, but looking at the logging attributes [1], we can get the file name from `$(filename)s` in our Formatter string.

I do like getting rid of the `self.qtile.log` to do logging, tho from this discussion using either `from libqtile.log import logger; logger.info()` or `import logging; logging.info()` are probably the better options.

[1] https://docs.python.org/2/library/logging.html#logrecord-attributes

**Comment by ramnes** [comment]
:+1:

**Comment by emdete** [comment]
there are some places where the new logging is not adapted, namely:

libqtile/widget/battery.py:108:            self.log.exception("Failed to get %s" % name)
libqtile/widget/keyboardkbdd.py:52:            self.log.error('Please check if kbdd is running')
libqtile/widget/keyboardkbdd.py:85:            self.log.error('variable "colours" should be a list, to set a\
libqtile/widget/backlight.py:70:            self.log.exception("Failed to get %s" % name)
libqtile/widget/imapwidget.py:75:            self.log.critical('Gnome Keyring Error')
libqtile/widget/keyboardlayout.py:95:            self.log.error('Can not get the keyboard layout: {0}'.format(e))
libqtile/widget/keyboardlayout.py:97:            self.log.error('Please, check that xset is available: {0}'.format(e))
libqtile/widget/keyboardlayout.py:107:            self.log.error('Can not change the keyboard layout: {0}'.format(e))
libqtile/widget/keyboardlayout.py:109:            self.log.error('Please, check that setxkbmap is available: {0}'.format(e))
libqtile/widget/mpdwidget.py:116:                self.log.exception('Failed to connect to mpd')
libqtile/widget/mpdwidget.py:123:                self.log.warning('Authentication failed.  Disconnecting')
libqtile/widget/mpdwidget.py:271:            self.log.exception('Mpd error on update')
libqtile/widget/mpdwidget.py:297:                self.log.exception('Error communicating with mpd')
libqtile/widget/mpdwidget.py:328:            self.log.exception('Mpd error on click')
libqtile/widget/check_updates.py:60:            self.log.error(self.distro + ' is not a valid distro name. ' +
libqtile/widget/graph.py:338:                self.log.warning(
libqtile/command.py:446:            self.log.error('Exception calling "%s":\n%s' % (function, error))

the log member is gone so these (mostly in except blocks on errors) won't work i assume.

**Comment by flacjacket** [comment]
@emdete thanks for pointing those out, those should be fixed now.
