### ISSUE TITLE
How would you go about making only the bar 100% transparent, but not the widgets?

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [qtile/qtile#853]
Im trying to make it so my top bar is 100% transparent (opacity=0) and it makes the widgets transparent as well. How would I make it so the widgest stay visible?

**Comment by tych0** [comment]
I don't think it's possible right now; basically qtile would have to look at the root window and draw what is underneath it. You could use a compositor and set opacity on the windows, but that will fade the widgets as well as the bar.

**Comment by YOUR-WORST-TACO** [comment]
alright, thanks for the response.
