### ISSUE TITLE
LibreOffice menus don't appear or don't stay visible 

### ISSUE THREAD

**Issue by jrazik** [qtile/qtile#854]
Hi,

Since several versions of qtile and libreoffice,  I'm not able to use mouse for menu action.
If I click, the subpanel doesn't seem to appear (like "Files" for example). If I use the keyboard it's ok.
If I try to click on the icon to open a file, the menu disappear as soon as I release the mouse button.
If I try to change the font by clicking on the arrow, nothing appear.
No error shown and nothing in qtile.log.
Currently I'm using qtile 0.10.4, libreoffice 5.0.4.2 and fedora 23. May be it's a wayland related problem.
With awesome it works fine.

**Comment by zordsdavini** [comment]
In Archlinux Qtile 0.10.4, libroffice 5.0.4.2 (and I remember in earlier versions) if I select MonadTall layout I can't get menus, too. But if I select Max layout – it appears.

**Comment by jrazik** [comment]
Yeah !
I just try and yes, with Max layout it works. And also we Treetab but not with the other following ones that I tried: floating, monadtall, tile, and stack.

**Comment by jrazik** [comment]
I just test to maximize the LibreOffice window and in this case, it works also, with all my layout.
Thanks again for the temporary solution until understanding why.

**Comment by flacjacket** [comment]
My LibreOffice menus will stay up, but I always have to right click the menu to get it to show up and I was never able to figure out why.

**Comment by ThomasWaldmann** [comment]
same problem here. totally annoying.

**Comment by ThomasWaldmann** [comment]
With current code from master, a normal (left) click on "File" menu works now as expected in LibreOffice.

**Comment by jrazik** [comment]
Still not working with me, even after a git pull just now.

**Comment by zordsdavini** [comment]
on Qtile 0.10.5 problem still exist

On 21 March 2016 at 11:39, jrazik <notifications@github.com> wrote:

> Still not working with me, even after a git pull just now.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/qtile/qtile/issues/854#issuecomment-199193414>
>



-- 
Udovīčė Arns

**Comment by ThomasWaldmann** [comment]
I'm at 2b6a04de5e3f6d6d0e7d30a92c197f0d417f47bb and it works for me.

**Comment by jrazik** [comment]
I revert to this commit but unfortunately it still didn't work.
LibreOffice 5.0.5.2 00(Build:2) Fedora 23, but the problem appear long ago.
I also have a new problem, when moving my roxterm window, its changing its size (shrinking) and moving. I don't know if it's related.

**Comment by rmsc** [comment]
Still having this problem with latest git.
I  found a nicer workaround though, if you press ctrl while clicking the mouse it works fine. So it probably has to do with modifiers..

**Comment by kes31** [comment]
While developing an extension for having static video-windows, I figured out the following:
The Problem disappears in the moment the libreoffice window becomes static. Furthermore it reappears, if libreoffice becomes unstatic again.

**Comment by kes31** [comment]
Setting the environment variable »SAL_USE_VCLPLUGIN=gen« for libreoffice is a workaround.

**Comment by ThomasWaldmann** [comment]
As this is a very common problem and a total spoiler: add it (previous comment) to FAQ until a fix is available?

**Comment by rmsc** [comment]
2016-10-14 12:45 GMT-04:00 TW <notifications@github.com>:

> As this is a very common problem and a total spoiler: add it (previous
> comment) to FAQ until a fix is available?
>
Indeed!

**Comment by zordsdavini** [comment]
With Libreoffice 5.3 I can see all menus. For me this bug is solved

**Comment by ramnes** [comment]
I will go ahead and close this one, considering it solved by the recent versions of LibreOffice. Also, the note explaining the workaround got added in the FAQ. Please ping me if a reopening is needed.
