### ISSUE TITLE
toggle_minimize in widget.TaskList

### ISSUE THREAD

**Issue by Sqozz** [qtile/qtile#856]
Hi all,

is it possible to catch a click event from an item in the TaskList so I can call toggle_minimize() on that window? I'd like to minimize and restore unneeded windows by a simple click onto their TaskList entries.
My current approach is a client_focus event, which gets called just fine if I activate a "hidden" window. But if I click on an already active window in my TaskList I only get a client_focus event from a strange target (Internal event: client_focus((Internal(<no name>, 2097231),), {}))

**Comment by flacjacket** [comment]
I haven't looked into this too deeply, but it might be possible to subclass TaskList and override some functions to do what you want

**Comment by Sqozz** [comment]
I'll look into that and report if I have any success.

**Comment by andering** [comment]
Hello i wanted address this by creating hook but than i realized that i don't really understand hook/event concept in the qtile, i would expect that there would be event, and its default behavior, and when i hook something on the event default behavior would get disabled or i would have ability to disable it.

So i only add toggle_minimalize() as behaviour in case i press on active window.
#923

**Comment by flacjacket** [comment]
This is closed by #923 as the default behavior
