### ISSUE TITLE
Support for svg in battery icon widget icons

### ISSUE THREAD

**Issue by lf-** [qtile/qtile#869]
It would significantly improve the theme support if svg was supported in the battery icon widget. The disadvantage is likely introducing a librsvg dependency for a very minor thing.

**Comment by flacjacket** [comment]
I at one point converted some SVGs to vector cairo drawings, and it was terrible, this would definitely be a nice addition.

**Comment by elParaguayo** [comment]
This should be closed as svg images are supported.
