### ISSUE TITLE
Second monitor crashes when rendering certain dotted patterns  

### ISSUE THREAD

**Issue by Jwpe** [qtile/qtile#876]
### Description

This is a strange issue that I've been encountering for some time: when my second monitor tries to render anything that contains a dotted line (see screenshot for example), it crashes and becomes black. Nothing appears in the `qtile` logs, and the screen comes back online as soon as the dots disappear. This does not occur at all on the primary monitor. 

### Versions + Configuration
- Qtile: 0.10.1
- OS: Ubuntu 14.04
- `qtile` screens: 
```python
screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Volume(),
                widget.Battery(
                    energy_now_file='charge_now',
                    energy_full_file='charge_full',
                    power_now_file='current_now',

                ),
                widget.Systray(),
                widget.Clock(format='%Y-%m-%d %a %I:%M %p', ),
            ],
            25,
        ),
    ),
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.TextBox("CPU:"),
                widget.CPUGraph(samples=400, width=400),
                widget.TextBox("RAM:"),
                widget.MemoryGraph(samples=400, width=400),
            ],
            25,
        ),
    ),
]
```

### Steps to Reproduce
- Ensure that a second monitor is connected
- On the screen visible on the second monitor, open a window containing a dotted pattern. An example is any HTML page that renders an element using the `dotted` CSS `border` property, e.g. http://www.django-rest-framework.org/ 
![2016-02-22-134149_847x86_scrot](https://cloud.githubusercontent.com/assets/1651943/13228479/4104f38c-d96a-11e5-9220-45769fd1a30a.png)
- Observe the screen flicker and then stop rendering entirely

**Comment by flacjacket** [comment]
Hmm, this is interesting, I cannot reproduce this on the current master. Are you able to update qtile and try this again? It might be a product of some bug that was fixed between then and now.

**Comment by Jwpe** [comment]
Updated to 0.10.4 and was able to reproduce - maybe this is something beyond the scope of Qtile if you aren't able to recreate it on your side.

**Comment by flacjacket** [comment]
You could try turning up the logging, run `qsh` and from the command
prompt, type `info`.

**Comment by flacjacket** [comment]
This could also be a problem with xcffib? You should check you're on the
latest version there, too.

**Comment by Jwpe** [comment]
I think this might have been a monitor-specific issue. Tried switching some hardware around and I can't reproduce. I'm going to close this out for the moment - thank you so much for your time and quick response @flacjacket!
