### ISSUE TITLE
libreoffice dialog invisible

### ISSUE THREAD

**Issue by ThomasWaldmann** [qtile/qtile#879]
ubuntu 14.04, qtile from github master branch.

when working in libreoffice writer and trying to export to a PDF file, the dialog "PDF Options" that should appear is invisible (I see its window name in the bar though).

also, as the dialogue is blocking, libreoffice is blocked and you can't do anything with it anymore besides killing it from the outside.

**Comment by tych0** [comment]
Erm, so isn't this a dupe of #854 as you commented there as well?

**Comment by ThomasWaldmann** [comment]
No, #854 is about being unable to click on the dropdown menus.

**Comment by ThomasWaldmann** [comment]
btw, would it make sense to have priorities / severities in this issue tracker?

stuff like the above leave users no choice other than to use some other WM and should have higher prio / severity.

**Comment by ThomasWaldmann** [comment]
maybe duplicate of / related to #809.

**Comment by tych0** [comment]
On Fri, Feb 26, 2016 at 12:09:36PM -0800, TW wrote:
> btw, would it make sense to have priorities / severities in this issue tracker?

Probably not, any effort that went into sorting things by priorities
would be better used actually writing patches :)

**Comment by flacjacket** [comment]
Can you check this again? A big floating/dialog fix just went in, especially if this is something you're seeing on a multimonitor setup, that might have fixed this.

**Comment by ThomasWaldmann** [comment]
I did a quick check with latest code from master branch: yes, it is better now.

As far as this ticket is concerned ("invisible"), it can be considered fixed.
