### ISSUE TITLE
wrong references to old logging

### ISSUE THREAD

**Issue by emdete** [qtile/qtile#887]
there are some places where the old logging is still used. it doesn't matter as long as no errors occour in most places. anyway if you catch an exception and this is logged qtile crashes. you can search for those places in code for example by

    grep '\.log\.' libqtile/ -r

which shows 17 occurences. i looked for ".log =" in the code with no success.

**Comment by flacjacket** [comment]
Doing that grep with the current develop only gave one instance for me, just pushed the fix for it. If there are any that got missed, let me know.

**Comment by flacjacket** [comment]
Thanks for the report!
