### ISSUE TITLE
Battery can't be read if not BAT0

### ISSUE THREAD

**Issue by jwarner112** [qtile/qtile#888]
Hello,

For some reason my laptop reads as `BAT1` instead of `BAT0`. Unfortunately, this trips up the Battery widget. Looking into it shows me there's a default for `BAT0` and no logic to find a different battery if it's not found.

I'm thinking an easy solution is an optional `battery_name` kwarg in the `_Battery` class so it spills into `BatteryIcon` as well. I haven't had the time to do this myself but want to contribute to the project anyway and if this isn't solved before I can figure it out, I'll get this one as I mentioned.

Let me know it my approach is unfavorable.

Thanks,
Jeff.

**Comment by flacjacket** [comment]
There should already be a `battery_name` kwarg for the _Battery class (here https://github.com/qtile/qtile/blob/develop/libqtile/widget/battery.py#L66). I know there was a bit of work done a little while ago to get dual batteries working, so I think it should work to specify which battery you are using that way.

**Comment by flacjacket** [comment]
Since I think this is handled already, I'll close this, if you need any more help feel free to come back to this. Thanks!

**Comment by jwarner112** [comment]
Hey Sean, 

Thanks for clearing up the issue for me-- I must have missed the `battery_name` option. I've introduced it to my environment and it works.
