### ISSUE TITLE
center (libreoffice) dialogues

### ISSUE THREAD

**Issue by ThomasWaldmann** [qtile/qtile#889]
#879 is fixed now, but dialogues are still strange:

the dialogues appear now on same monitor, but not above the libreoffice window, but at seemingly random places (floating above unrelated windows).

it would be nice to center them floating above libreoffice window.

**Comment by ramnes** [comment]
Yeah, that kind of disturbed me too. I made [that dirty hack](https://github.com/ramnes/qtile-config/blob/master/config.py#L202-L205) to always spawn floating windows in the center of the screen.

**Comment by ramnes** [comment]
My dirty hack isn't working anymore. :(

**Comment by flacjacket** [comment]
I've noticed some annoying window placements lately, I think this commit: https://github.com/qtile/qtile/commit/397704fe50053962144556881f2a920c12cc13d3 may be to blame, tho I haven't tried reverting it, yet

**Comment by hgaiser** [comment]
@ramnes do you have a new method to spawn floating windows in the center of the screen (or preferably its parent window)? This is bugging me too.

**Comment by ramnes** [comment]
Also, see my comment on https://github.com/qtile/qtile/commit/397704fe50053962144556881f2a920c12cc13d3.

Pretty sure that a revert of this commit would fix everything. Can't test right now.

**Comment by flacjacket** [comment]
@ramnes I think I cleaned up that logic and it looks like it is working now, let me know if it isn't working for you

**Comment by ramnes** [comment]
Yep, it does. Thanks!
