### ISSUE TITLE
Yahooweather widget stopped to work

### ISSUE THREAD

**Issue by tollerm** [qtile/qtile#899]
Yahooweather widget does not produce output anymore.

**Comment by tych0** [comment]
On Tue, Mar 29, 2016 at 02:01:33PM -0700, tollerm wrote:
> Yahooweather widget does not produce output anymore.

Yes, there was some discussion on IRC a few days ago that yahoo just
started requiring oauth2 for their API, so until someone has time to
patch it it'll stay broken :(
