### ISSUE TITLE
Incorrect behaviour of alpha channel in Bar background

### ISSUE THREAD

**Issue by jmi2k** [qtile/qtile#900]
I want to make a status bar with a nice shadow-like gradient background, but I'm limited by the fact that I can't set a gradient with alpha values.

I don't know if this issue is applicable to flat colors too, because of the 'opacity' property of Bar.

**Comment by flacjacket** [comment]
When we set the color to draw [1], the function is called `set_source_rgb`, but it takes and uses RGBA colors, see [2]. Does it work if you try to set an opacity?

[1] https://github.com/qtile/qtile/blob/develop/libqtile/drawer.py#L327

[2] https://github.com/qtile/qtile/blob/develop/libqtile/utils.py#L121

**Comment by jmi2k** [comment]
Oh, I didn't know about that! But there's more: when I set the opacity value of the color to something, it looks like the color were translucent, but there were a black solid background behind it. So, for example: #ff0000 results in a bright red background, but #ff0000.2 gives a very dark red (as opposed to the almost invisible transparent red I want).

**Comment by flacjacket** [comment]
@jmi2k if you have a black background, wouldn't you expect `#ff0000.2` to give a very dark red (since it's seeing through to the black underneath)? You might need to reduce the red-ness to get a lighter red. What if you have a patterned background, do you see it then?

**Comment by jmi2k** [comment]
I'll try to explain better: I have a picture as my background (i use a photo loaded with feh as my background). In the version I'm using (0.10.15, from Arch Linux AUR), if I set an opacity to the bar background, let's say #ff0000.2, what I expect is a red overlay over my image (a reddish background). But instead, I get a solid and dark red, without any transparency. I'll attach some screenshots later today, as well as make some tests with the latest version of this repo, but now this is all I can say:

```
$ qtile --version
0.10.5
$ cat .xinitrc
xrdb -load .Xresources
feh --bg-fill ~/.local/wallpaper
compton -b
exec qtile
```

**Comment by jmi2k** [comment]
I changed the title to describe the *actual* problem.

**Comment by flacjacket** [comment]
I see, I misunderstood you. Yes, that is a problem then, tho I'm not sure where the problem lies, since it may have to do with compositing in order to get transparency working right.

**Comment by jmi2k** [comment]
Some pictures of the bug:

![2016-04-21-152813_1366x768_scrot](https://cloud.githubusercontent.com/assets/17623703/14711492/c73830c0-07d9-11e6-87d6-c17a3721e21a.png)
![2016-04-21-152906_1366x768_scrot](https://cloud.githubusercontent.com/assets/17623703/14711491/c72edd4a-07d9-11e6-8e9e-18e9fbf760b1.png)
![2016-04-21-153014_1366x768_scrot](https://cloud.githubusercontent.com/assets/17623703/14711490/c724b7d4-07d9-11e6-8d4a-1069b68c8931.png)

**Comment by pandada8** [comment]
same here.
btw, It seems that the bar is drawed over last result, and not cleared.
I tried call `self.drawer.clear(self.background)` in the `Bar._actual_draw()` function, but didnot help. :/

**Comment by g0josh** [comment]
Hi team,
I'm facing the same issue, any updates on this one?

**Comment by elParaguayo** [comment]
#2513 merged. Closing.
