### ISSUE TITLE
Custom width for Stack layout

### ISSUE THREAD

**Issue by nielsonsantana** [qtile/qtile#905]
There any way to increase the width of only one Stack?
I like this layout, but the only thing that I need is it be more flexible in the width of columns.

**Comment by flacjacket** [comment]
Stack doesn't have a way to change the width of the two stacks. You might look into trying the Columns layout, it is an extension of the Stack layout and has the ability to resize the columns.

**Comment by nielsonsantana** [comment]
Yeah, but think that Stack is a very flexible layout, except for it. I can move one window from one stack to other(lazy.layout.client_to_next). It's a very important for me. I will try extend Stack layout to support dynamic resize.

**Comment by nielsonsantana** [comment]
I would like do it, but don't figured out how this change may be made. On layout `tile` are used one variable called `ratio`, then you can increase or decrease the ratio of the current client.

My solution currently and only for two stacks was it:

```
FACTOR_FIRST_STACK =  0.91
class StackCustom(Stack):

    def configure(self, client, screen):
        for i, s in enumerate(self.stacks):
            if client in s:
                break
        else:
            client.hide()
            return

        if client is self.group.currentWindow:
            px = self.group.qtile.colorPixel(self.border_focus)
        else:
            px = self.group.qtile.colorPixel(self.border_normal)

        nstack = len(self.stacks)
        factorFirst =  FACTOR_FIRST_STACK
        factorLast =  (nstack - factorFirst) / ((nstack-1) or 1)
        firstColumn = int((screen.width / len(self.stacks)) * factorFirst)
        if i == 0:
            columnWidth = int((screen.width / len(self.stacks)) * factorFirst)
        else:
            columnWidth = int((screen.width / len(self.stacks)) * factorLast)
        
        xoffset = screen.x + i * firstColumn
        winWidth = columnWidth - 2 * self.border_width

        if s.split:
            columnHeight = int(screen.height / len(s))
            winHeight = columnHeight - 2 * self.border_width
            yoffset = screen.y + s.index(client) * columnHeight
            client.place(
                xoffset,
                yoffset,
                winWidth,
                winHeight,
                self.border_width,
                px,
                margin=self.margin,
            )
            client.unhide()
        else:
            if client == s.cw:
                client.place(
                    xoffset,
                    screen.y,
                    winWidth,
                    screen.height - 2 * self.border_width,
                    self.border_width,
                    px,
                    margin=self.margin,
                )
                client.unhide()
            else:
                client.hide()
```

**Comment by andering** [comment]
as @flacjacket says the functionality you need its in layout called **Columns** , function `client_to_next` you can replace by function `shuffle_right` or `shuffle_left`. So there is no need and reason to implement it into Stack. (there could be for someone reason to merge those two together).

I think this issue can be actually closed.
