### ISSUE TITLE
Large fonts on Ubuntu

### ISSUE THREAD

**Issue by nielsonsantana** [qtile/qtile#915]
I having problem of large fonts in my environment. It's happen some times after I suspend my notebook or anything else. Old opened applications have normal font, but when I try open a new application, the size of font is too large.  

![screenshot from 2016-05-20 08 29 27](https://cloud.githubusercontent.com/assets/627596/15426827/73ad0cf6-1e67-11e6-806d-642a21445480.png)

**Comment by flacjacket** [comment]
Hmm, I'm not sure if this is from something we're doing, if it's a suspend problem, or some combination of the two...

Have you used other WM's previously in the same environment on the same laptop?

**Comment by nielsonsantana** [comment]
It's not happen only after suspend. Sometimes occur when I using the system normally without suspend. 
My previous environment was Gnome-shell.

My current startup script is:

```
dropbox start &
tilda &
nm-applet &
rescuetime &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring-daemon --start --components=ssh &     
```
Another factor in this problem, maybe that I using a hdmi monitor 23" with Full HD resolution instead of  the HD screen of the notebook.

**Comment by nielsonsantana** [comment]
No, this bug disappear.
