### ISSUE TITLE
qsh name collision

### ISSUE THREAD

**Issue by irl** [qtile/qtile#919]
A package in Debian already provides the file /usr/bin/qsh. This program is used for managing job queues in grid computing environments and a number of alternatives exist in Debian. It is acceptable for alternatives to conflict with each other, but it is not acceptable (by Debian policy) for non-alternative applications to conflict with each other.

Would you consider renaming qsh in the upstream sources? If not, the file will need to be renamed through a patch set in Debian.

The relevant bug is at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824752.

**Comment by flacjacket** [comment]
Hmm, we can probably rename it to qtilesh or qtile-sh

**Comment by irl** [comment]
On 22/05/16 18:24, Sean Vig wrote:
> Hmm, we can probably rename it to qtilesh or qtile-sh

qtsh, qtilesh or qtile-sh are all good choices.

If you have a Debian system handy, you can use apt-file to check for
name collisions.

Thanks,
Iain.

**Comment by jhdulaney** [comment]
Ahh, yes, this collision also exists in Fedora.  I can workaround by doing a Conflicts:  gridengine, but that's really not the best practice.

**Comment by jhdulaney** [comment]
No collision in Fedora with qtilesh, qtile-sh, or even qshell (my official nomination).

**Comment by flacjacket** [comment]
qshell sounds good, @irl I don't have a Debian system handy, is that alright? Otherwise I can try to check later today.

**Comment by irl** [comment]
On 22/05/16 19:25, Sean Vig wrote:
> qshell sounds good, @irl <https://github.com/irl> I don't have a Debian
> system handy, is that alright? Otherwise I can try to check later today.

qshell is fine (:

Thanks,
Iain.

**Comment by flacjacket** [comment]
I just fixed this in the above commit. If it would help to get a release tagged with the changes, we can probably get that organized fairly easily.

**Comment by irl** [comment]
On 24/05/16 01:16, Sean Vig wrote:
> I just fixed this in the above commit. If it would help to get a release
> tagged with the changes, we can probably get that organized fairly easily.

That would help a lot (:

Thanks,
Iain.

**Comment by flacjacket** [comment]
Just tagged 0.10.6, release announcement coming shortly.
