### ISSUE TITLE
Two bars stack on each other

### ISSUE THREAD

**Issue by andering** [qtile/qtile#926]
Does qtile allow to have more bars stack on each other,
i mean that's handy (basic) to be able have more than one line bar, or not ?

From source seems to me it's not possible,
but maybe im missing something.

I'm trying to get to this point  - [two rows bar](http://s33.postimg.org/is0x61xe7/2016_05_28_113119_1920x1848_scrot.png)

If that's not possible i could implement it,
while that's key of my workflow.

**Comment by flacjacket** [comment]
Currently, we don't have functionality like this, we just allow positioning along one of the four edges.

**Comment by flacjacket** [comment]
Probably the best way to do this is as part of the planned split of widgets out into their own windows.

**Comment by andering** [comment]
is somewhere more info about this plan, or it's some private developers discussion ?

**Comment by flacjacket** [comment]
It has been mentioned before on IRC, but it isn't documented anywhere.

**Comment by andering** [comment]
Is it this thread ? #622
