### ISSUE TITLE
create Key by keycode

### ISSUE THREAD

**Issue by danmilon** [qtile/qtile#933]
I'm often switching between US and Greek keyboard layouts, and when I do that, the registered keyboard shortcuts stop working, which is reasonable because `Key('M-f')` is different than `Key('M-φ')`.

But the interesting thing is that both `f`, and `φ`, which are the same physical key, have the same keycode. So I thought I should be able to create a shortcut by specifying the keycode instead of the symbol. [Awesome WM does that](https://awesome.naquadah.org/wiki/Global_Keybindings) through notation such as `#48` (indicating key with keycode 48). It would be very helpful for me to have similar functionality in QTile.

If you agree we need this, I could jump in and try to implement it but would need to know where in the code I should do that.

As a workaround I can create both `Key('M-f')` and `Key('M-φ')` but thats redundant.

**Comment by andering** [comment]
So, keys are being compared with (i think Unicode Hexadecimal) [xkeysyms.py](https://github.com/qtile/qtile/blob/develop/libqtile/xkeysyms.py)
and check is being done here [config.py](https://github.com/qtile/qtile/blob/develop/libqtile/config.py#L58)

btw.: f = 0x03d5 and φ = 0x0066 , that's reason it doesn't work way you expect.
I would personally create **'else if'** with check if format is hexadecimal, in case key is not found in xkeysyms.

But i have no clue if that's ok with developers :).

**Comment by zordsdavini** [comment]
it should be ok, because there are many users what are not using latin
basic or even latin alphabet. For example my number line is "ąčęėįšų", so I
can't bind any keybinding on numbers (ex. dynamic groups)

On 1 July 2016 at 12:16, Andrej Kouřil <notifications@github.com> wrote:

> So, keys are being compared with (i think Unicode Hexadecimal) xkeysyms.py
> <https://github.com/qtile/qtile/blob/develop/libqtile/xkeysyms.py>
> and check is being done here config.py
> <https://github.com/qtile/qtile/blob/develop/libqtile/config.py#L58>
>
> btw.: f = 0x03d5 and φ = 0x0066 , that's reason it doesn't work way you
> expect.
> I would personally create *'else if'* with check if format is
> hexadecimal, in case key is not found in xkeysyms.
>
> But i have no clue if that's ok with developers :).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qtile/qtile/issues/933#issuecomment-229898971>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AD_1PGTX7JojnS5-3P5JrBGHWKAnW-ecks5qRNrjgaJpZM4JC5UW>
> .
>



-- 
Udovīčė Arns

**Comment by andering** [comment]
Ok,
than what about make it better by:
actually asking `hex(ord('<char>'))` and in xkeysyms.py keep only Special keys ?

**Comment by danmilon** [comment]
I made necessery changes to add support for `Key(['mod4'], '#33', ...)` (`#33` means keycode 33 as reported by xev (decimal)). and this works too `EzKey('M-<#33>', ...)`.

In a nutshell, I changed the `Key` class a bit to understand keycodes, and then in `manager.py` changed `keyMap` to use `(code, modifiers)` tupple as index, instead of `(symbol, modifiers)`. And then made minor fixes to incoroporate that here and there.

https://github.com/qtile/qtile/compare/develop...danmilon:feature-933?expand=1

From some very quick testing, it works as expected. Can you please check it? If you agree with the approach of the implementation, I'll add some tests, docs and send a PR.

**Comment by danmilon** [comment]
Actually now that keys are registered by keycode internally, and not by keysym, I can for example even register only `EzKey('M-f)` and it works with both US and Greek layouts.

**Comment by Arherion** [comment]
I've the same issue.
I tried @danmilon 's solution and...it works for me!

**Comment by magniff** [comment]
@danmilon hm, didnt work for me. Qtile version 0.10.7
So, I've added an easy key for keyboard layout switcher:
```
EzKey("A-C-k", lazy.widget["keyboardlayout"].next_keyboard())
```
The actual widget works properly, it correctly reacts on mouse and keyboard shortcut, but only in EN map. Going from EN to RU makes this unavailable.

**Comment by magniff** [comment]
Ok, it seems that adding toggler via the X keyboard controller actually solves the problem
```
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:alt_shift_toggle
```

**Comment by Nevimmu** [comment]
As anyone been able to have keycode work? As a user of ```fr``` keyboard I would love a patch like [keycode patch](https://dwm.suckless.org/patches/keycodes/) for DWM

**Comment by Nevimmu** [comment]
As anyone been able to have keycode working? As a user of the ```fr``` keyboard I would love to see a patch like the [keycode patch](https://dwm.suckless.org/patches/keycodes/) for DWM

**Comment by zordsdavini** [comment]
old @danmilon code how he fixed keysymbol to keycode issue. I guess PR was never created. Maybe someone would like to try to fix it? https://github.com/danmilon/qtile/commit/66ea0d0758e759345dc817f9d94aead95c6f219c

**Comment by zordsdavini** [comment]
I added priority to this issue as it adds misunderstanding to all people who use not only English layout

**Comment by serzhshakur** [comment]
If you want to toggle layout with some shortcut and have the current layout displayed at your bar you can do as follows:
- install `xkblayout-state` (which allows to print specific information about the currently used keyboard layout)
- in your `autostart.sh` add 
```
setxkbmap -layout lv,ru -variant ",phonetic_winkeys" -option "grp:lalt_lshift_toggle" &
```
- in your `config.py` create function which will get current layout name
```
def get_kb_layout():
    output = subprocess.run(
        ['xkblayout-state', 'print', '%s'],
        capture_output=True,
        encoding="utf-8"
    ).stdout
    return output
```
- add this to the list of your bar's widgets:
```
                widget.GenPollText(
                    func=get_kb_layout,
                    update_interval=0.5,
                    font='Droid Sans, Bold',
                    width=25
                ),
```

**Comment by mosaleh52** [comment]
Same problem here i can not control qtile with AR layout even the shortcut I use to toggle layout work from en to AR only 
when I tried to use AR char in my config, qtile does not work until I remove them from config
I have basic knowledge in python if there is someone who is willing to guide me I could work on it

**Comment by m-col** [comment]
>  I have basic knowledge in python if there is someone who is willing to guide me I could work on it

I'd be happy to help out if I can. I think something like this might start you off:
```diff
diff --git a/libqtile/backend/x11/core.py b/libqtile/backend/x11/core.py
index cb856bc9..e0ce2a78 100644
--- a/libqtile/backend/x11/core.py
+++ b/libqtile/backend/x11/core.py
@@ -432,12 +432,15 @@ class Core(base.Core):
 
     def lookup_key(self, key: Union[config.Key, config.KeyChord]) -> Tuple[int, int]:
         """Find the keysym and the modifier mask for the given key"""
-        try:
-            keysym = xcbq.get_keysym(key.key)
-            modmask = xcbq.translate_masks(key.modifiers)
-        except xcbq.XCBQError as err:
-            raise utils.QtileError(err)
+        if isinstance(key.key, str):
+            keysym = xcbq.keysyms.get(key)
+            if not keysym:
+                raise utils.QtileError("Unknown key: %s" % key.key)
+
+        else:
+            keysym = self.conn.code_to_syms[key.key][0]
 
+        modmask = xcbq.translate_masks(key.modifiers)
         return keysym, modmask
 
     def grab_key(self, key: Union[config.Key, config.KeyChord]) -> Tuple[int, int]:
diff --git a/libqtile/backend/x11/xcbq.py b/libqtile/backend/x11/xcbq.py
index e9ce1b53..2d2e387a 100644
--- a/libqtile/backend/x11/xcbq.py
+++ b/libqtile/backend/x11/xcbq.py
@@ -782,13 +782,6 @@ class Painter:
         self.conn.disconnect()
 
 
-def get_keysym(key: str) -> int:
-    keysym = keysyms.get(key)
-    if not keysym:
-        raise XCBQError("Unknown key: %s" % key)
-    return keysym
-
-
 def translate_modifiers(mask: int) -> typing.List[str]:
     r = []
     for k, v in ModMasks.items():
diff --git a/libqtile/config.py b/libqtile/config.py
index 6a22d9bf..07cfc7cf 100644
--- a/libqtile/config.py
+++ b/libqtile/config.py
@@ -61,7 +61,7 @@ class Key:
         description to be added to the key binding
     """
 
-    def __init__(self, modifiers: List[str], key: str, *commands, desc: str = ""):
+    def __init__(self, modifiers: List[str], key: Union[str, int], *commands, desc: str = ""):
         self.modifiers = modifiers
         self.key = key
         self.commands = commands
@@ -92,7 +92,7 @@ class KeyChord:
     def __init__(
         self,
         modifiers: List[str],
-        key: str,
+        key: Union[str, int],
         submappings: List[Union[Key, KeyChord]],
         mode: str = "",
     ):
```

This is untested but you get the general idea. `Key` and `KeyChord` can accept an `int`, in which case the key is being interpreted as a keycode rather than a keysym. Currently `Qtile.keysmap` uses keysyms as part of its dictionary keys, but if it makes things easier (e.g. if storing keysyms is not necessary at all) then that can be changed to be keycodes.

**Comment by Phl3gmaTREEc** [comment]
+1
I would to just express my interested in solution for this with my Czech keyboard, as I'd love to use number row for groups, but can't

**Comment by zordsdavini** [comment]
> +1 I would to just express my interested in solution for this with my Czech keyboard, as I'd love to use number row for groups, but can't

you can (example of Samogitian (or same in Lithuanian) keyboard, where I have on numbers: ąčęėįšųū„“)

```
groups = [Group(i) for i in "1234567890"]
sgs_groups = {
    '1': 'aogonek',
    '2': 'ccaron',
    '3': 'eogonek',
    '4': 'eabovedot',
    '5': 'iogonek',
    '6': 'scaron',
    '7': 'uogonek',
    '8': 'umacron',
    '9': 'doublelowquotemark',
    '0': 'leftdoublequotemark'
    }

for i in groups:
    keys.extend([
        EzKey("M-%s" % i.name, lazy.group[i.name].toscreen(toggle=True)),
        EzKey("M-S-%s" % i.name, lazy.window.togroup(i.name)),

        EzKey("M-<%s>" % sgs_groups[i.name], lazy.group[i.name].toscreen(toggle=True)),
        EzKey("M-S-<%s>" % sgs_groups[i.name], lazy.window.togroup(i.name)),
    ])

```

**Comment by Phl3gmaTREEc** [comment]
Well, someone give this person a medal. It seems to be working for my Czech keyboard as well, with updates to Czech symbols of course.
Maybe add this to documentation or something, because there are couple of issues opened about this topic.

**Comment by 0range0range** [comment]
So are there a solution?

There are 2 main problems:

1) Custom keybindings in Qtile, which can be simply duplicated for every keyboard layout with corresponding keysyms.
Is there a solution without duplication? (now I create Key[..., a]) and  Key[..., Cyrillic_ef] for the same action.)

2) Hotkeys like `Ctrl-c`, `Ctrl-v`, `Ctrl-a` also work in Latin layout only, which can not be easily set in Qtile config as far as I understand. 
Is 2nd a problem with Qtile or a more general one? Does anyone knows how to deal with it?
I found this post:

https://www.reddit.com/r/archlinux/comments/sjgfxj/comment/ij6twko/?utm_source=share&utm_medium=web2x&context=3

but even switching layout with `setxkbmap` and disabling the keyboard layout widget does not help with `Ctrl-c`, `Ctrl-v`, `Ctrl-a` in my case.

**Comment by LeKSuS-04** [comment]
> Is 2nd a problem with Qtile or a more general one? Does anyone knows how to deal with it?

> but even switching layout with setxkbmap and disabling the keyboard layout widget does not help with Ctrl-c, Ctrl-v, Ctrl-a in my case.

The problem must be within Qtile. I'm the author of that reddit post you mentioned, and the actions I described there fixed the issue for me. Looks like the problem is not only because of the `setxkbmap` and keyboard layout widget, but then I have no idea, what causes it. Also, I've tried XMonad, and the problem wasn't present there in any way, so no way this problem is general. 

Here are my dotfiles
https://github.com/LeKSuS-04/my-arch/tree/master/dotfiles/qtile
This configuration doesn't have such an issue (`Ctrl-a`, `Ctrl-c` and others still work in russian layout), so you might be interested in taking a look at it.

**Comment by MOIS3Y** [comment]
> > Is 2nd a problem with Qtile or a more general one? Does anyone knows how to deal with it?
> 
> > but even switching layout with setxkbmap and disabling the keyboard layout widget does not help with Ctrl-c, Ctrl-v, Ctrl-a in my case.
> 
> The problem must be within Qtile. I'm the author of that reddit post you mentioned, and the actions I described there fixed the issue for me. Looks like the problem is not only because of the `setxkbmap` and keyboard layout widget, but then I have no idea, what causes it. Also, I've tried XMonad, and the problem wasn't present there in any way, so no way this problem is general.
> 
> Here are my dotfiles https://github.com/LeKSuS-04/my-arch/tree/master/dotfiles/qtile This configuration doesn't have such an issue (`Ctrl-a`, `Ctrl-c` and others still work in russian layout), so you might be interested in taking a look at it.

Looking at the sources, it seems that qtile switches the keyboard language by changing the setxkbmap keys, which causes the keybindings to stop working.
The solution from LeKSuS-04 works. He created a custom keyboard widget and switches the language with the xkb-switch utility, which needs to be installed additionally, as in my case on VoidLinux. You will also need pip install dbus-next.

Additionally I created:
https://wiki.archlinux.org/title/Xorg/Keyboard_configuration

/etc/X11/xorg.conf.d/00-keyboard.conf

```
Section "InputClass"
        Identifier "system-keyboard"
        Option "XkbLayout" "ru, us"
        Option "XkbModel" "pc105"
EndSection
```

Without this, xkb-switch -n will simply not see the second layout.

**Comment by zordsdavini** [comment]
I use setxkbmap and xkb-switch combination with config.py:

@lazy.function
def z_next_keyboard(qtile):
    check_output(['xkb-switch', '-n'], shell=True)
    filenames = {
        'us': '~/.config/qtile/flags/en.png',
        'lt(sgs)': '~/.config/qtile/flags/sgs.png',
        'ru(phonetic)': '~/.config/qtile/flags/ru.png',
        }
    keyboard = check_output(
            ['xkb-switch', '-p'],
            shell=True).decode('utf-8').replace('\n', '')
    qtile.widgets_map.get('image').cmd_update(filenames[keyboard])


@lazy.function
def z_next_keyboard_group(_):
    global current_layout

    # options =
'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch,caps:hyper'
    options = 'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch'
    layouts = {
            'en-sgs-ru': [
                'us,lt,ru',
                ',sgs,phonetic'
                ],
            'en-sgs': [
                'us,lt',
                ',sgs'
                ],
            }
    current_layout = 'en-sgs' if current_layout == 'en-sgs-ru' else
'en-sgs-ru'
    layout = layouts[current_layout]
    command = f'setxkbmap -layout {layout[0]} -variant {layout[1]} -option
{options}'
    run(command.split(), check=True)
<...>
    EzKey("A-<space>", z_next_keyboard, desc='switch keyboard layout'),
    EzKey("S-A-<space>", z_next_keyboard_group, desc='switch keyboard
group'),

And files to display flag in the bar
[image: image.png]

**Comment by zordsdavini** [comment]
I use setxkbmap and xkb-switch combination with config.py:

```
@lazy.function
def z_next_keyboard(qtile):
    check_output(['xkb-switch', '-n'], shell=True)
    filenames = {
        'us': '~/.config/qtile/flags/en.png',
        'lt(sgs)': '~/.config/qtile/flags/sgs.png',
        'ru(phonetic)': '~/.config/qtile/flags/ru.png',
        }
    keyboard = check_output(
            ['xkb-switch', '-p'],
            shell=True).decode('utf-8').replace('\n', '')
    qtile.widgets_map.get('image').cmd_update(filenames[keyboard])


@lazy.function
def z_next_keyboard_group(_):
    global current_layout

    # options = 'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch,caps:hyper'
    options = 'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch'
    layouts = {
            'en-sgs-ru': [
                'us,lt,ru',
                ',sgs,phonetic'
                ],
            'en-sgs': [
                'us,lt',
                ',sgs'
                ],
            }
    current_layout = 'en-sgs' if current_layout == 'en-sgs-ru' else 'en-sgs-ru'
    layout = layouts[current_layout]
    command = f'setxkbmap -layout {layout[0]} -variant {layout[1]} -option {options}'
    run(command.split(), check=True)
<...>
    EzKey("A-<space>", z_next_keyboard, desc='switch keyboard layout'),
    EzKey("S-A-<space>", z_next_keyboard_group, desc='switch keyboard group'),
```

And files to display flag in the bar
![image](https://user-images.githubusercontent.com/4191548/211976538-1321cdf3-b4e0-4a07-8f46-2b51dfb62658.png)

Mostly I use Samogitian or English, but if I want to write something in Russian I switch to bigger group

**Comment by Sunderland93** [comment]
> I use setxkbmap and xkb-switch combination with config.py:
> 
> ```
> @lazy.function
> def z_next_keyboard(qtile):
>     check_output(['xkb-switch', '-n'], shell=True)
>     filenames = {
>         'us': '~/.config/qtile/flags/en.png',
>         'lt(sgs)': '~/.config/qtile/flags/sgs.png',
>         'ru(phonetic)': '~/.config/qtile/flags/ru.png',
>         }
>     keyboard = check_output(
>             ['xkb-switch', '-p'],
>             shell=True).decode('utf-8').replace('\n', '')
>     qtile.widgets_map.get('image').cmd_update(filenames[keyboard])
> 
> 
> @lazy.function
> def z_next_keyboard_group(_):
>     global current_layout
> 
>     # options = 'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch,caps:hyper'
>     options = 'grp:alt_space_toggle,compose:rctrl,lv3:ralt_switch'
>     layouts = {
>             'en-sgs-ru': [
>                 'us,lt,ru',
>                 ',sgs,phonetic'
>                 ],
>             'en-sgs': [
>                 'us,lt',
>                 ',sgs'
>                 ],
>             }
>     current_layout = 'en-sgs' if current_layout == 'en-sgs-ru' else 'en-sgs-ru'
>     layout = layouts[current_layout]
>     command = f'setxkbmap -layout {layout[0]} -variant {layout[1]} -option {options}'
>     run(command.split(), check=True)
> <...>
>     EzKey("A-<space>", z_next_keyboard, desc='switch keyboard layout'),
>     EzKey("S-A-<space>", z_next_keyboard_group, desc='switch keyboard group'),
> ```
> 
> And files to display flag in the bar ![image](https://user-images.githubusercontent.com/4191548/211976538-1321cdf3-b4e0-4a07-8f46-2b51dfb62658.png)
> 
> Mostly I use Samogitian or English, but if I want to write something in Russian I switch to bigger group

Does it works with Wayland?

**Comment by Shringe** [comment]
+1
I don't think keycodes would be very hard to add and would add immense value to many people.

**Comment by elParaguayo** [comment]
I can see why this one would be useful.

I've made a start on implementing it.

**Comment by Shringe** [comment]
Is there any progress on this? I would be willing to help test and contribute

**Comment by elParaguayo** [comment]
You could test #4707 but I may need to revise it first...
