### ISSUE TITLE
vim does not work well in qtile

### ISSUE THREAD

**Issue by Infinemen** [qtile/qtile#934]
I change the theme of vim, but it does't work well in qtile. When i open a file, the old message is still display on the screen. What's more, qtile can't display Chinese.
Any advice will be appreciated. Thanks!

**Comment by AlexTalker** [comment]
Well, can you post some screenshot, please?

**Comment by andering** [comment]
@Infinemen any progress ?

**Comment by flacjacket** [comment]
I'm not entirely sure what this issue is supposed to mean, there is nothing in qtile that effects vim configuration

**Comment by zordsdavini** [comment]
I use vim all time. I had something similar about 1-2 years ago. But it was fixed. Now I don't get any issue that can be related to vim. I suggest to close this.

**Comment by zordsdavini** [comment]
And Chinese is not related to vim - except UTF-8 issue in window titles that was more then 1 year ago. I think this problem is solved.

**Comment by flacjacket** [comment]
Agreed
