### ISSUE TITLE
keycode to keysym conversion

### ISSUE THREAD

**Issue by andering** [qtile/qtile#944]
There is few think i don't understand and sense are wrong.
1. why are the keys handling from **xcffib**, not from some asynchronous python function where there wouldn't be need for **keycode -> keysym** conversion _(i believe there is reason, so i would like just some quick explanation to understand better core of the qtile)_
2. why `xkeysyms.py` exists ? why isn't it taken from `xmodmap` , wouldn't it give actually better international support for Keymap.?
3. shouldn't be **_xpoll** function from `manager.py`be named **_xpool**  ? :)
4. `handle_KeyPress : manager.py` has by my opinion wrong logic. I believe it should work similar way as its described  here in [/\*  Use of the 'col' parameter section](http://opensource.apple.com/source/X11libs/X11libs-60/xcb-util/xcb-util-0.3.6/keysyms/keysyms.c). (you need bit scroll down). That's reason why Caps-lock, numlock doesn't really work.
5. # 933 and #943
6. Shouldn't be qtile as first convert keycode to correct keysym and then pass it to the widget or to other parts of qtile core ? So keysym would be main character representation with which qtile works ?
7. Today morning found [xcb-util-keysyms](http://www.linuxfromscratch.org/blfs/view/svn/x/xcb-util-keysyms.html) , isn't it binding which would **do it for us all** ?

**Comment by dequis** [comment]
>1\. why are the keys handling from **xcffib**, not from some asynchronous python function where there wouldn't be need for **keycode -> keysym** conversion _(i believe there is reason, so i would like just some quick explanation to understand better core of the qtile)_

What do you mean by "asynchronous python function" here?

>2\. why `xkeysyms.py` exists ? why isn't it taken from `xmodmap` , wouldn't it give actually better international support for Keymap.?

It exists because xpyb didn't have the equivalent modules that the python xlib bindings did have. They are constants that are part of the X api, not dynamic stuff, it doesn't make sense to pull them from xmodmap. I don't see how that would help with internationalization.

>3\. shouldn't be **_xpoll** function from `manager.py `be named **_xpool**  ? :)

https://en.wikipedia.org/wiki/Polling_(computer_science)

(unless this is a joke that went over my head?)

>4\. `handle_KeyPress : manager.py` has by my opinion wrong logic. I believe it should work similar way as its described  here in [/*  Use of the 'col' parameter section](http://opensource.apple.com/source/X11libs/X11libs-60/xcb-util/xcb-util-0.3.6/keysyms/keysyms.c). (you need bit scroll down). That's reason why Caps-lock, numlock doesn't really work.

What do you mean by "wrong logic"? I'm not even sure if you can compare both functions, as they do different things. Numlock is filtered out because it interferes with keybindings, that's intended.

>6\. Shouldn't be qtile as first convert keycode to correct keysym and then pass it to the widget or to other parts of qtile core ? So keysym would be main character representation with which qtile works ?

Most things are fairly direct X event handlers, and they get whatever the event includes. Where were you thiking of doing this conversion?

>7\. Today morning found [xcb-util-keysyms](http://www.linuxfromscratch.org/blfs/view/svn/x/xcb-util-keysyms.html) , isn't it binding which would **do it for us all** ?

Well, first, it's not a binding, it's a C library, so bindings are required for it - that's something that needs to be implemented in xcffib. Second, i don't see any documentation and the xcb_keysyms.h header doesn't seem to have anything interesting.

**Comment by andering** [comment]
> 1. What do you mean by "asynchronous python function" here?

I meant some python function which would give you not event but do all conversion for you and give you just keysym or char. But since i see how the events are distributed in qtile i see the point and advantage of using events.

> 2. It exists because xpyb didn't have the equivalent modules that the python xlib bindings did have. They are constants that are part of the X api, not dynamic stuff, it doesn't make sense to pull them from xmodmap. I don't see how that would help with internationalization.

I see, i didn't expect that it's complete list of them, actually i thought it's kind of dynamic. Thank you for clarification. Than yes, xmodmap wouldn't make sense and forgot about international comment.

> 3. (unless this is a joke that went over my head?)

sorry about that

> 4. What do you mean by "wrong logic"? I'm not even sure if you can compare both functions, as they do different things. Numlock is filtered out because it interferes with keybindings, that's intended.

I should have said strange, not wrong. Because i'm probably the one who is wrong :). If i think now,
let me please know if i understand correctly, Num lock, Caps lock in key-bindings are off on purpose so keybindings are Numlock-less and case insensitive ?

Why numlockMask bit is added and than removed through self.validMask ?
```
    def handle_KeyPress(self, e):
        keysym = self.conn.code_to_syms[e.detail][0]
        state = e.state
        if self.numlockMask:
            state = e.state | self.numlockMask
        k = self.keyMap.get((keysym, state & self.validMask))
```

I don't really understand why is necessary to detect if numlockMask bit exist,
and also why ModMasks['lock'] is present only in case numlockMask exists.
I think that's one the reason KeyMap doesn't work if CapsLock active.
```
    def mapKey(self, key):
        self.keyMap[(key.keysym, key.modmask & self.validMask)] = key
        code = self.conn.keysym_to_keycode(key.keysym)
        self.root.grab_key(
            code,
            key.modmask,
            True,
            xcffib.xproto.GrabMode.Async,
            xcffib.xproto.GrabMode.Async,
        )
        if self.numlockMask:
            self.root.grab_key(
                code,
                key.modmask | self.numlockMask,
                True,
                xcffib.xproto.GrabMode.Async,
                xcffib.xproto.GrabMode.Async,
            )
            self.root.grab_key(
                code,
                key.modmask | self.numlockMask | xcbq.ModMasks["lock"],
                True,
                xcffib.xproto.GrabMode.Async,
                xcffib.xproto.GrabMode.Async,
            )
```


> 6. Most things are fairly direct X event handlers, and they get whatever the event includes. Where were you thinking of doing this conversion?

After more knowledge about how qtile works, i can see dependency on keycode coming from xcffib. From this perspective i would just wrap xcffib KeyPress event on the beginning when coming from xcffib so to you can in any other place touch {keycode = xxx, keysym = xxx, keymask = xxx} and maybe even add functions like isNumlock, isLock or/and some constant with maps modifiers bits
so you wouldn't have to do conversion between keycode and keysym everytime again in every widgets where you using KeyPress event

> 7. Well, first, it's not a binding, it's a C library, so bindings are required for it - that's something that needs to be implemented in xcffib. Second, i don't see any documentation and the xcb_keysyms.h header doesn't seem to have anything interesting.

It would outsource out algorithm of conversion between kycode and keysym. But i don't see it as good idea anymore as xcffib works with keycodes.

Thank you for your patience with qtile beginner :)
