### ISSUE TITLE
keybinding like ctrl+esc or ctrl+tab

### ISSUE THREAD

**Issue by Hammer2900** [qtile/qtile#952]
Please implement keybinding like ctrl+esc or ctrl+tab. I try paste this key to config but it not working for me.

**Comment by frostidaho** [comment]
It is implemented - just tested the following and it works

```python
keys.append(Key(['control'], 'Escape', lazy.spawn('notify-send control+Escape')))
keys.append(Key(['control'], 'Tab', lazy.spawn('notify-send control+Tab')))
```

ctrl is 'control'
and you can find the string representations of other keys in [libqtile/xkeysyms.py](https://github.com/qtile/qtile/blob/develop/libqtile/xkeysyms.py)

**Comment by Hammer2900** [comment]
ah thank you !

**Comment by flacjacket** [comment]
@frostidaho thanks for the answer, closing this, reopen if you have any more troubles
