### ISSUE TITLE
Separate layout on each group ?

### ISSUE THREAD

**Issue by Hammer2900** [qtile/qtile#953]
And this moment, how i make separate Layout for each group ? or i make only one layout for all groups.
And how switch layout by hot keys ?

**Comment by flacjacket** [comment]
At this point, you could set a particular layout to be on a group, but at a quick glace, I don't see a way to set a particular to a layout on one and only one group.

**Comment by flacjacket** [comment]
As for switching layouts, the easiest thing to do is use the `simple_key_binder` [1], which will generate keybindings to numerical order of the group as `mod + N` to move to the Nth group, but you can also do a custom key binding, as is done in the default config [2] to bind to the letter of each group.

[1] http://docs.qtile.org/en/latest/manual/config/groups.html#example
[2] https://github.com/qtile/qtile/blob/develop/libqtile/resources/default_config.py#L87

**Comment by dhannes** [comment]
According to http://docs.qtile.org/en/latest/manual/config/groups.html#group it is possible to define `Group` argument `layouts` which is "_the group layouts list overriding global layouts_ ".
Thus it is possible to define seperate layouts for single or all groups, and its also documented and working (I tested it).
I guess we can close this.
