### ISSUE TITLE
window groups on restart

### ISSUE THREAD

**Issue by cycomanic** [qtile/qtile#960]
My windows seem to be moved all over the place when I restart, none of the groups are being remembered. This is quite annoying as I'm using qtile on a laptop and move back and forth from work (plugging into external monitors ->triggering a restart). I've seen #764 and #704, but it seems some of these issues were supposed to be fixed by #765. However this does not seem the case for me, both qtile 0.10.6 and recent develop show the same issues. If someone could point me into the right direction, I can try to fix this myself.

**Comment by flacjacket** [comment]
Hi @cycomanic, we had some work done to try to correctly reset the state of qtile on restarts, but it caused more problems than it solved, which is why we reverted it in #765. Fixing issues with restarts is definitely still on the to-do list, tho.

**Comment by and3rson** [comment]
@cycomanic If you still have this issue, you can use a command that I made for myself to reparent windows to their respective group rules once they're messed up after a restart:
```
class FixGroups(object):
    """
    Reassigns windows to their matching groups.
    Useful once some damn window gets into a wrong group.
    """
    def __init__(self):
        pass

    def __call__(self, qtile):
        for client in qtile.windowMap.values():
            for rule in qtile.dgroups.rules:
                if rule.matches(client):
                    if rule.group and hasattr(client, 'togroup'):
                        client.togroup(rule.group)
```

**Comment by m-col** [comment]
I'm pretty sure this has been fixed. If this is still an issue please comment and re-open!
