### ISSUE TITLE
Match of windows based on all itens of WM_CLASS

### ISSUE THREAD

**Issue by nielsonsantana** [qtile/qtile#981]
In my testes qtile only detect the last wm_class name.
Example:
`WM_CLASS(STRING) = "netflix.com", "google-chrome"`

Qtile only match "google-chrome".

**Comment by Roger** [comment]
Just found out this issue, we already support "wm_instance_class" to match that, in this case "netflix.com"

**Comment by ramnes** [comment]
I'll go ahead and close this, then. Thank you @Roger!

@nielsonsantana feel free to ping me and I'll reopen if needed.
