### ISSUE TITLE
Single Key to open windows in multiple groups

### ISSUE THREAD

**Issue by canyon289** [qtile/qtile#986]
I'm trying to create a keybinding that will spawn an application in two different groups. For example in the default config I added this code

```
    Key([mod], "b", lazy.group["o"].toscreen(),
                    lazy.spawn("xterm"), 

                    # Switch to another group and spawn Xterm
                    lazy.group["i"].toscreen(),
                    lazy.spawn("xterm")
                    ),
```
The issue I'm having is that both xterms will be spawned in group(i). I don't think this is a bug, more so a lack of understanding on how the async works, but I could use any direction in getting this to behave in the manner I would like.

Test Config File Attached
[multiple_groups_config.txt](https://github.com/qtile/qtile/files/619544/multiple_groups_config.txt)

**Comment by canyon289** [comment]
Also I read through the issues and found this one. It's likely related but I was unable to connect them meaningfully
https://github.com/qtile/qtile/issues/775

**Comment by and3rson** [comment]
@canyon289 A workaround is to spawn `xterm` with `-class xxxxx` option thus providing custom `WM_CLASS` value and having a group matching rule for this `WM_CLASS`.

**Comment by canyon289** [comment]
@and3rson 
Thank you for the suggestion. While that works if I want things to spawn in one group, it would work less flexibly if I want things to span in multiple groups.

In your opinion would figuring out how to make the arguments calls synchronous help with understanding what's going on? Definitely willing to learn, however I can't wrap my head around the source code to know where to look. I tried reading through the manager module below.

This is also my last question so please feel free to close this issue. 

http://docs.qtile.org/en/latest/_modules/libqtile/manager.html
