### ISSUE TITLE
404 for the link to config file for cjbarnes18.jpg on the main page

### ISSUE THREAD

**Issue by Huge** [qtile/qtile#987]
I liked that one from the gallery at qtile.org

**Comment by canyon289** [comment]
I found his repo on google. Hopefully this is what you're looking for
https://github.com/cjbarnes18/qtile-examples

**Comment by flacjacket** [comment]
Paging @dmpayton

**Comment by dmpayton** [comment]
I'll make some time today to go through the listed examples and make sure all links still work.

**Comment by flacjacket** [comment]
Did you get a chance to check this @dmpayton ?

**Comment by flacjacket** [comment]
Closing for now, if this is still an issue, feel free to re-open
