### ISSUE TITLE
cursor_warp warps too much on Chromium

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#990]
Since a few days, `cursor_warp` warps at each link clicked in Chromium, if it links to another domain name. I have updated both Chromium (version 55.0.2883.75) and Qtile recently, I don't know which one is faulty.

**Comment by flacjacket** [comment]
It shouldn't be too hard to try an old version of qtile to see if that's the problem. If it is only for different domains, that seems like it is a problem with Chromium creating new windows. If we know how to select those windows, it may be possible to stop the warping to those windows.

**Comment by ramnes** [comment]
I've rolled back to Chromium 52 for other reasons - namely, Hangout not working on Chromium 55 and a bug with Symantec certificates on Chromium 53 - and it fixed my problem, so it seems that Chromium 55 is faulty here.

Does anybody have Chromium 56 or 57 installed to try it out? Otherwise I'll report it here once I'll be up-to-date.

**Comment by ramnes** [comment]
Chromium 60 doesn't have this problem anymore.

**Comment by ramnes** [comment]
I might have concluded this prematurely: it still happens when opening a new tab, even on the same domain name. I'll let some time to see if that's really perturbing, and if so I'll open another issue.

**Comment by ramnes** [comment]
I'll just reopen this one actually. Go on any Google Search page and click on the "Next" button, it will warp. :-1:

**Comment by ramnes** [comment]
Chromium 70 seems to have it right.

**Comment by ramnes** [comment]
Actually not. Middle clicking on a link still warp for no reason…

**Comment by ramnes** [comment]
Fixed with `focus_on_window_activation = "never"` :)
