### ISSUE TITLE
Mouse being "offset" in LibreOffice

### ISSUE THREAD

**Issue by MarSoft** [qtile/qtile#995]
When I start any LibreOffice program (tested with Writer, Calc and plain `libreoffice` where I am asked to open or create a document) under Qtile, I encounter this problem:
If I hover mouse over some button in the app's UI, it is handled correctly. But when I press mouse button, it is recognized as being pressed and then immediately moved about 20-30 pixels down. I.e. if I press left mouse button on some toolbar button, click event is handled as if it occured below this toolbar. Mouse pointer itself is not moved during that.
It is only press/release events which are "broken" in this way; mouse-move events are seemingly recognized with the correct coordinates.
This doesn't happen when I click in the menu (but does happen if I click toolbar button under the menu, or statusbar, or within a document). Dialog windows are seemingly not affected as well.

Also the problem DOESN'T occur if I click with *right* button or scroll with a wheel (which IMO is handled as "additional" button presses). Only the left button is corrupted.

I tried other WMs - `dwm`, `twm`. They work fine. Only `qtile` has this problem, and only with `LibreOffice`.

I tried changing gtk2 and gtk3 themes, didn't help.
I tried setting `OOO_FORCE_DESKTOP` variable to either `GNOME` or `KDE`. Icons changed, but the problem still happens.
Also I tried with empty (default) config for both LibreOffice and Qtile - it didn't help either.

Package versions:
```
Arch Linux
qtile-git fa0cc966
python 3.6
libreoffice 5.2.4
gtk3 3.22.6
xorg-server 1.18.4
```

Could anyone suggest where and how to dig deeper into this issue? I have no ideas where to start investigating...

**Comment by ramnes** [comment]
Do you happen to have `mouse_warp = True` in your `config.py`?

**Comment by MarSoft** [comment]
@ramnes no, I have explicitly `cursor_warp = False`. Also I did check with default config (where it is `False` as well). And I have just checked with `cursor_warp = True`, just to be sure - and it doesn't influence my problem in any way.

**Comment by zordsdavini** [comment]
With liberoffice 5.3.0 the problem has been gone.

**Comment by MarSoft** [comment]
I can confirm, this bug does not happen anymore with LibreOffice 5.3.0. Probably we can close it for now.

**Comment by t-wissmann** [comment]
I had the same issue btw with herbstluftwm in November 2016, but now it seems to be gone. (Now I'm using: `Version: 5.2.6.2; Build ID: 5.2.6-1; CPU Threads: 8; OS Version: Linux 4.10; UI Render: default; VCL: gtk2; Locale: de-DE (de_DE.UTF-8); Calc: group`)

**Comment by Cysign** [comment]
A friend of mine is using 5.3 but hat the same issue.
Using the menu itema his mouse has an y-offset.
Any idea how to correct it?

**Comment by guitarmonkey** [comment]
Here is the the friend of his ;D
check out my screenshot. I got an y-axis-offset as well. I need to click way below an icon in order to select it. it's a pain in the ass unfortunatley. 
![capture](https://cloud.githubusercontent.com/assets/28880244/26333660/97db8b74-3f5f-11e7-9091-a31e6d14f51c.PNG)

**Comment by guitarmonkey** [comment]
I found the solution (I guess this could potentially help a lot of people)

For me this fixed all of my problems:
Just run the program with your primary graphic card processor (for me thats not my intel but my NVIDIA)
You can do this by rightclicking and then selecting your graphic card of your choice 
;)

**Comment by Cysign** [comment]
Just some background: He's using a notebook with Intel i7, and nVidia graphics (optimus, GTX1050Ti). Selecting the nVidia chip works fine using Window 10 (didn't approve this in any other OS).

**Comment by tom-gangemi** [comment]
I'm also encountering the same issue as guitarmonkey (menus are cut off, the cursor is offset and lots of blurriness). I can confirm that forcing the application to run on my nvidia graphics instead of Intel HD graphics solves the issue.

I'd be happy to provide any debug info or test out anything.

**Comment by bugsyb** [comment]
Same issue here - w10, nvidia card, but using Intel built in by default. LibreOffice v5.4.0.3 (downloading latest).

**Comment by steveeJ** [comment]
Upgrading LibreOffice from v4.2 to v4.3 solved the issue for me.

**Comment by asm28** [comment]
I tried the solution proposed by "**guitarmonkey**" in the comment above and it works well.

> Just execute the program with your primary graphical card.

**Comment by Morgensohn** [comment]
I can confirm that the problem no longer exists in Libreoffice 6.0.

**Comment by flacjacket** [comment]
@Morgensohn had you been seeing this issue previously with 5.x versions?

**Comment by stevenleigh** [comment]
I think I am getting this same issue - the mouse is always clicking an offset of about 20-30 pixels from where it appears

Fresh install of LibreOffice_6.3.4_Win_x64

I tried switching the graphics card, but issue still persists.  These are the options I have:
Intel HD Graphics 530
NVIDIA Geforce GTX 960M

My machine is:  Dell XPS, Windows 10 pro, x64, i7
