### ISSUE TITLE
Giving 'Spawn' widget it's own window

### ISSUE THREAD

**Issue by ghost** [qtile/qtile#997]
One way qtile excels from the desktop environments is the spawn widget. It actually executes the command typed in background instead of just spawning the app, another example of why small is beautiful. Hence I can do some stuff like 'pkill -9 \<program\>', 'vlc \<music folder\>' etc. It would be nice if the 'Spawn' widget had it's own small window in which I could view the output of some command or use some ncurses based app like mc, vim, nvlc or nmtui. I have more than enough time to work on that but I don't have much knowledge of xorg. Any references would be highly appreciated.

**Comment by soulchainer** [comment]
Maybe I'm understanding this wrong, but when I read this

> It would be nice if the 'Spawn' widget had it's own small window in which I could view the output of some command

it sounds to me much like: «It would be nice to have an small terminal emulator» O_O.

**Comment by gsaga** [comment]
Yes right. It could be used for small stuff which would otherwise require us to open a separate terminal emulator or a tmux pane. I guess a network manager widget could be made by inheriting from it with the help of nmtui.

**Comment by ramnes** [comment]
Or for something more advanced like rofi. :)

That being said, this could be also done quite simply by writing an option for spawn that would make it run its command in a terminal. PR welcome!
